### ISSUE TITLE
Backup seems very slow both incremental and full...

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1000]
_From [usu...@gmail.com](https://code.google.com/u/116101244115797405375/) on April 14, 2014 16:42:03_

What steps will reproduce the problem? 1.  Schedule backup 
2.  Wait...
3.  Wait... What is the expected output? What do you see instead? Faster than a 1 Day 18 hours and 46 minutes for a ~227GB full
Faster than 4 hours 48 minutes for a ~30KB incremental What version of Duplicati are you using? On what operating system? Version=1.3.4.0, Windows 2003r2 x64 SP2 What backend (destination) are you using? Local iSCSI connected Dell EqualLogic SAN array on 1GB LAN Please provide any additional information below. <
BackupType      : Full
TypeReason      : A full backup is made because the latest full backup is from 3/11/2014 3:24:02 PM and the full backup threshold is 1M
BeginTime       : 04/12/2014 01:00:01
EndTime         : 04/13/2014 19:46:16
Duration        : 1.18:46:14.6588656
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 0
AddedFiles      : 1706030
AddedFolders    : 55974
ExaminedFiles   : 1706030
OpenedFiles     : 1706030
SizeOfModified  : 0
SizeOfAdded     : 226302965926
SizeOfExamined  : 226302965926
Unprocessed     : 0
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 226941659550
BytesDownloaded : 0
RemoteCalls     : 52360

Cleanup output:
>

<
BackupType      : Incremental
TypeReason      : An incremental backup is made because the latest full backup is from 3/11/2014 3:24:02 PM and the full backup threshold is 1M
BeginTime       : 04/11/2014 01:00:01
EndTime         : 04/11/2014 05:48:44
Duration        : 04:48:42.4292896
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 13
AddedFiles      : 1
AddedFolders    : 0
ExaminedFiles   : 1706030
OpenedFiles     : 20
SizeOfModified  : 163378
SizeOfAdded     : 771
SizeOfExamined  : 194661
Unprocessed     : 0
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 30709
BytesDownloaded : 4834086
RemoteCalls     : 24

Cleanup output:
>

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=973_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
