### ISSUE TITLE
Move duplicatie settings to a new PC

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1002]
_From [pieter.d...@gmail.com](https://code.google.com/u/102524829924697259701/) on April 19, 2014 10:08:22_

Hello,

Is there any possibility to move the duplicati backup-settings to a new computer? As i have a new computer, I want to continue backup my USB-files on this computer, but i still want to use the same online backup location. 

kind regards,

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=975_

**Comment by gtangt** [comment]
sorry, on a mac where would I find the Duplicati.sqlite?
