### ISSUE TITLE
GDEBI does not create menu start element under Lubuntu / hidden files not available for selection onn wizard

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1005]
_From [Glasair...@gmail.com](https://code.google.com/u/116776116716902254246/) on April 29, 2014 21:48:47_

What steps will reproduce the problem? 1.start from CLI /usr/bin/duplicati
2.having involuntarily srated from CLI, the wizard does not allow selection of a hidden folder (in my case, .thunderbird, the only reason to install duplicity) What is the expected output? What do you see instead? had to use the command line interface instead of Menu/etc.

no hidden folders visible What version of Duplicati are you using? On what operating system? 1.3.4 under Lubuntu 13.04 What backend (destination) are you using? Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=978_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
