### ISSUE TITLE
What does "gefolgt von einer anschließenden Bereinigung" mean?

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1007]
_From [101.47...@germanynet.de](https://code.google.com/u/117770065284261324802/) on May 01, 2014 22:15:50_

What steps will reproduce the problem? 1. Backup incremental data to Strato hidrive 2. 3. What is the expected output? What do you see instead? I fully backed up about 40 GB to a Strato hidrive followed by one month of daily incremental backups using webDav-based connection to webdav.hidrive.strato.com. 

I receive the following error message when trying to run the scheduled incremental backup (in quatation marks):

"Fehler: Die Sicherungslisten-Datei duplicati-inc-manifestB.20140430T180326Z.manifest zeigt an, dass 56 Volumes vorhanden sein sollten, aber die Dateiliste zeigt nur 13
Wenn der Fehler nicht behoben werden kann, können Sie entweder einen neues Voll-Backup erstellen, oder die fehlerhaften Sicherungslisten-Dateien händisch löschen - gefolgt von einer anschließenden Bereinigung. Die widersprechenden Sicherungslisten-Dateien sind:

duplicati-inc-manifestB.20140430T180326Z.manifest

Error: System.Exception: Die Sicherungslisten-Datei duplicati-inc-manifestB.20140430T180326Z.manifest zeigt an, dass 56 Volumes vorhanden sein sollten, aber die Dateiliste zeigt nur 13
Wenn der Fehler nicht behoben werden kann, können Sie entweder einen neues Voll-Backup erstellen, oder die fehlerhaften Sicherungslisten-Dateien händisch löschen - gefolgt von einer anschließenden Bereinigung. Die widersprechenden Sicherungslisten-Dateien sind:

duplicati-inc-manifestB.20140430T180326Z.manifest

   bei Duplicati.Library.Main.Interface.VerifyBackupChainWithFiles(BackendWrapper backend, ManifestEntry entry)
   bei Duplicati.Library.Main.Interface.Backup(String[] sources)
   bei Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
Ergebnis des Aufräumens:"

I deleted the quoted file on the destination drive manually but I don't know what "gefolgt von einer anschließenden Bereinigung" means and how to execute it. What version of Duplicati are you using? On what operating system? 1.3.4 on Windows 8.1 (Version 6.3/Build 9600) What backend (destination) are you using? Strato HiDrive 100 GB, 16 GB free space Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=980_

**Comment by Chrescht** [comment]
"gefolgt von.." means followed by a cleaning (or purging). I assume they mean delete the conflicting files.

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
