### ISSUE TITLE
SSH-backend retries failed authentication 5 times

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1011]
_From [kakos...@gmail.com](https://code.google.com/u/102069476005370821367/) on May 04, 2014 15:28:58_

What steps will reproduce the problem? 1.Duplicati.CommandLine.exe backup ssh:<source-URL> <TARGET> --auth-username=username --auth-password=wrong_password

What is the expected output? 
Authentication failure after the first attempt. 

What do you see instead?

---

Backup started at 4.5.2014 16:16:54

Enter encryption passphrase: 

Confirm encryption passphrase: 
Checking remote backup ...
  Listing remote folder ...
Operation List with file  attempt 1 of 5 failed with message: No suitable authentication method found to complete authentication. => No suitable authentication method found to complete authentication.
  Listing remote folder ...
Operation List with file  attempt 2 of 5 failed with message: No suitable authentication method found to complete authentication. => No suitable authentication method found to complete authentication.
  Listing remote folder ...
Operation List with file  attempt 3 of 5 failed with message: No suitable authentication method found to complete authentication. => No suitable authentication method found to complete authentication.
  Listing remote folder ...
Operation List with file  attempt 4 of 5 failed with message: No suitable authentication method found to complete authentication. => No suitable authentication method found to complete authentication.
  Listing remote folder ...
Operation List with file  attempt 5 of 5 failed with message: No suitable authentication method found to complete authentication. => No suitable authentication method found to complete authentication.
Fatal error => No suitable authentication method found to complete authentication.

No suitable authentication method found to complete authentication.

---

That is, five attempts to connect to the ssh-server. I confirmed this also from server logs. What version of Duplicati are you using? On what operating system? Version 2.0_CLI_experimental_2013-11-20 on Linux. What backend (destination) are you using? SSH Please provide any additional information below. Authentication failures are not likely to be transient, so it would be better to treat them as fatal immediately. Also, unnecessary failed connection attempts can cause people using Fail2ban and similar tools to be locked out of their server. 

Based on reading 2.0_CLI_experimental_2013-11-20 this issue affects other backends as well.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=984_
##

**Comment by warwickmm** [comment]
This still occurs in 2.0.5.110, but I don't think it's that big of an issue.  Closing this as won't fix until enough users find this to be a problem.
