### ISSUE TITLE
Windows uninstall does not remove shortcut (1.3.4)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1012]
_From [jonda...@gmail.com](https://code.google.com/u/100302848913163736190/) on May 04, 2014 15:52:27_

What steps will reproduce the problem? 1. Install Duplicati
2. Uninstall from Control Panel What is the expected output? What do you see instead? Program is removed but shortcut on desktop remains What version of Duplicati are you using? On what operating system? 1.3.4 - Windows 7 What backend (destination) are you using? Google Drive or S3

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=985_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
