### ISSUE TITLE
backup fails with offending manifest file error message

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1017]
_From [Jarmo.P@gmail.com](https://code.google.com/u/Jarmo.P@gmail.com/) on May 13, 2014 21:31:11_

I'm backing up one of my Ubuntu servers to remote path. This is the command i'm executing on a daily basis via cron task under root user:
duplicati-commandline backup "/etc" "remote-backup-path" --passphrase="secret" --volsize=100mb --auto-cleanup --full-if-older-than=1M --usn-policy=auto --snapshot-policy=auto --full-if-sourcefolder-changed && \
duplicati-commandline delete-all-but-n 2 "remote-backup-path" --passphrase="secret" --force

(ignore some Windows-specific flags since i'm using similar script on Windows machines as well).

It works few days and then starts failing with message similar to this:
The manifest file duplicati-inc-manifestB.20140513T090457Z.manifest.aes specifies that there should be 6 volume pairs, but the following pairs were not found:
duplicati-inc-content.20140513T090457Z.vol5.zip.aes
duplicati-inc-content.20140513T090457Z.vol6.zip.aes
duplicati-inc-signature.20140513T090457Z.vol5.zip.aes
duplicati-inc-signature.20140513T090457Z.vol6.zip.aes

If this error cannot be resolved, you can either create a new full backup or delete the offending manifests manually, followed by a cleanup command. The offending manifest files are:

duplicati-inc-manifestB.20140513T090457Z.manifest.aes

If i delete that offending manifest file and issue a:
duplicati-commandline cleanup "remote-path" --force

command then i will get a new offending manifest file on a next backup try. Only way to overcome that situation is to remove the backup on a remote server and issue a new full backup. What version of Duplicati are you using? On what operating system? 1.3.4-dev05, Ubuntu What backend (destination) are you using? Webdav Please provide any additional information below. That same script works well on a different Ubuntu machine and numerous Windows machines.

What could be the possible problem and how to fix that properly?

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=990_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
