### ISSUE TITLE
Duplicati 2 fails to back up to file:// with mapped drive, works with UNC path

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1020]
_From [00G...@gmail.com](https://code.google.com/u/109411332562327676540/) on May 19, 2014 02:00:43_

What steps will reproduce the problem? 1. Create a basic backup command using file://<mapped drive>\<optional path> as the destination. What is the expected output? What do you see instead? Expect the backup to run normally, instead it fails with "path not found" when the path most certainly exists. What version of Duplicati are you using? On what operating system? 2.0 CLI experimental 11-20-2013 Windows Server 08R2 What backend (destination) are you using? File based Please provide any additional information below. Backup target is a freenas server on the same lan with the source server. My first attempt was using a mapped drive z:\ pointing at \\freenas\extra-bak. This contains a folder called icsng, so --file://Z:\icsng
Duplicati's log says:

Information: Backend event: List - Retrying:  ()
Warning: Failed to create folder: The folder Z:\icsng does not exist
System.IO.DirectoryNotFoundException: Could not find a part of the path 'Z:\icsng'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Duplicati.Library.Main.BackendManager.ThreadRun()

I attempted the same thing simply to the Z drive with the same result. Using --file://\\freenas\extra-bak\icsng works fine however.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=993_

**Comment by nobels** [comment]
Hello,
I got the same error:
Error: Failed to upload file "duplicati-inc-signature.20160908T194659Z.vol1.zip": Kan de map of het bestand niet maken.


```
Error: System.Exception: Failed to upload file "duplicati-inc-signature.20160908T194659Z.vol1.zip": Kan de map of het bestand niet maken.
 ---> System.IO.IOException: Kan de map of het bestand niet maken.

   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bij Duplicati.Library.Backend.File.Put(String remotename, Stream stream)
   bij Duplicati.Library.Main.BackendWrapper.PutInternal(BackupEntryBase remote, String filename)
   --- Einde van intern uitzonderingsstackpad ---
   bij Duplicati.Library.Main.BackendWrapper.Put(BackupEntryBase remote, String filename, Boolean forcesync)
   bij Duplicati.Library.Main.Interface.Backup(String[] sources)
   bij Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.IO.IOException: Kan de map of het bestand niet maken.

   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bij Duplicati.Library.Backend.File.Put(String remotename, Stream stream)
   bij Duplicati.Library.Main.BackendWrapper.PutInternal(BackupEntryBase remote, String filename)
Cleanup output:
```

This is the same day i force backup. (12 hours in between)
I use external backup drive: E:\Duplicati


This is the first backup that works:
```
BackupType      : Full
TypeReason      : A full backup is made because no existing backup chains were found on the destination
BeginTime       : 09/07/2016 20:54:34
EndTime         : 09/08/2016 01:39:43
Duration        : 04:45:09.3931930
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 0
AddedFiles      : 30708
AddedFolders    : 2898
ExaminedFiles   : 30708
OpenedFiles     : 30709
SizeOfModified  : 0
SizeOfAdded     : 66308538973
SizeOfExamined  : 66308538973
Unprocessed     : 13544
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 68818024683
BytesDownloaded : 0
RemoteCalls     : 18148
NumberOfErrors  : 2
****************
Failed to process file: C:\Users\xxx\AppData\Roaming\Duplicati\control_dir\lock. Error message: Kan geen toegang krijgen tot het bestand C:\Users\xxx\AppData\Roaming\Duplicati\control_dir\lock omdat het wordt gebruikt door een ander proces.
Failed after uploading 6047 volume(s). Error message: Failed to upload file "duplicati-full-signature.20160907T185434Z.vol6048.zip": Kan de map of het bestand niet maken.

****************
NumberOfRetries : 5
RetryOperations : 5

Cleanup output:
```

Can you help me ?
Do you need more information ? Just ask what you need :-)

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
