### ISSUE TITLE
Upload a new backup if some files have been deleted

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1021]
_From [Kolari...@gmail.com](https://code.google.com/u/102468357892399225002/) on May 19, 2014 17:18:13_

What steps will reproduce the problem? 1. create a directory with two files - file A and file B
2. create a backup of this directory 
3. delete file A
4. create another backup
5. restore files from the backup What is the expected output? What do you see instead? I'd expect only file B being restored, but both files are restored instead. What version of Duplicati are you using? On what operating system? 1.3.4 on Windows 8.1 What backend (destination) are you using? Local filesystem and webdav, but the behavior is probably same for all backends. Please provide any additional information below. I've found the workaround for this problem - setting upload-unchanged-backups to true - but that results in many unnecessary backups being created when there are no changes (no additions nor deletions) at all. I think the correct behavior is to always upload the changes if files have been deleted even if no files have been added.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=994_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
