### ISSUE TITLE
Command-Line-Option for setting the max. file size

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1022]
_From [dirk.zie...@gmail.com](https://code.google.com/u/115994092981078731938/) on May 19, 2014 22:12:57_

I'm using the latest v2 build. I want to set the file size to 400MB (or something).

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=995_

**Comment by grinsted** [comment]
What if i want my backups to include a 600 Mb file, but my back-end has a max-file-size of 40 Mb. How would i specify that?

I read the command-line help and it says: 
```
  --dblock-size (Size): Limit the size of the volumes
    This option can change the maximum size of dblock files. Changing the size can be useful if the backend has a limit on the size of each
    individual file
    * default value: 50mb
```

and it also says

```
Usage: backup <storage-URL> "<source-path>" [<options>]

  Makes a backup of <source-path> and stores it in <storage-URL>. The format for <storage-URL> is
  protocol://username:password@hostname:port/path?backend
  _option1=value1&backend_option2=value2. Multiple source paths can be specified if they are separated by a space. **Defaults are: The maximum file
  size is 100MB**, backups are deleted when they are older than one month.
```

**Comment by kenkendk** [comment]
It does not matter what size the source files have. All files are split into chunks (`--blocksize`) which are stored in compressed files of size `--dblock-size`.

The documentation in the second example is wrong, the default volume size is 100mb.
