### ISSUE TITLE
Recent SkyDrive API change/update?

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1026]
_From [L.Jonsso...@gmail.com](https://code.google.com/u/109408775885577997767/) on May 25, 2014 13:55:04_

What steps will reproduce the problem? 1. Trying to upload/test connection to the SkyDrive servers. What is the expected output? What do you see instead? "Connection Failed: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel." What version of Duplicati are you using? On what operating system? 1.3.4, Windows 8. What backend (destination) are you using? SkyDrive. Please provide any additional information below. I've been running a daily backup via Duplicati to SkyDrive for a couple of months now. It stopped working on the 21th of this month. (2014-05-21)

Possibly a API change on their end?

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=999_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
