### ISSUE TITLE
Status window does not remember window size

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1027]
_From [rickyorb...@gmail.com](https://code.google.com/u/117733090307531583059/) on June 05, 2014 23:29:03_

What steps will reproduce the problem? 1. Open status window
2. Resize it
3. Close it
4. Open it again What is the expected output? What do you see instead? Resized window from before. Default sized window. What version of Duplicati are you using? On what operating system? 1.3.4, Win 7 x86_64

Grabbed the source but cannot find the code where you draw the UI, so came here to submit an issue instead.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1000_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
