### ISSUE TITLE
Duplicati RPM doesn't include Mono dependencies; hangs on Linux EL6.5 with the epel Mono 2.4 RPMs

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1033]
_From [durval.m...@gmail.com](https://code.google.com/u/112350301229592733351/) on June 13, 2014 09:51:59_

-> What steps will reproduce the problem?

1. Install the RPM listed on Duplicati's web page: 
sudo yum localinstall http://duplicati.googlecode.com/files/Duplicati&#37;201.3.4.noarch.rpm 2. Install mono RPMs until duplicati is able to run (BTW: why aren't they listed as dependencies in the Duplicati RPM?):
sudo yum install mono-core mono-winforms
   -> This resulted in downloading and installing the following RPMs, all from the "epel" EL6 yum repo:
        mono-core-2.4.3.1-4.el6.x86_64.rpm
        mono-data-2.4.3.1-4.el6.x86_64.rpm
        libgdiplus-2.4.2-3.el6.x86_64.rpm
        mono-data-sqlite-2.4.3.1-4.el6.x86_64.rpm    
        mono-web-2.4.3.1-4.el6.x86_64.rpm
        mono-winforms-2.4.3.1-4.el6.x86_64.rpm

3. Start duplicati; from the command-line:
   duplicati

-> What is the expected output? What do you see instead?
Expected: Duplicati should just work. 
Instead: When opening its main (wizard) screen, it shows the message below:
        Failed to load Mono.Data.Sqlite.SqliteConnection, reverting to built-in.
         Error message: System.NullReferenceException: Object reference not set to an instance of an object
          at Duplicati.GUI.SQLiteLoader.get_SQLiteConnectionType () [0x00000]
   -> I decided to continue, and at seemingly random points the program just hangs: program doesn´t respond to mouse clicks, no window repaints (ie, dragging/opening some other window on top of the Duplicati Window and then removing it leaves the Duplicati window with a "carbon copy" of the part of the window that obscured it), etc. Program has to be terminated using "kill" from the command-line.

-> What version of Duplicati are you using? On what operating system?
Duplicati 1.3.4, on Linux EL6.5.

-> What backend (destination) are you using?
Doesn't matter: problem happens with ssh destination, file destination, etc.

-> Please provide any additional information below.

Duplicati started working When I removed the epel mono 2.4 RPMs mentioned above, and re-installed  mono 2.10.6 from the OpenSUSE Mono:EL6 repo as instructed here: http://www.picotech.com/support/topic13433.html In retrospect, when I searched Duplicati's wiki for a minimum Mono version recommended for linux, I found conflicting information at https://code.google.com/p/duplicati/wiki/LinuxHowto , to wit:
   "sudo apt-get install mono-runtime libmono2.0-cil"
                                             ^^^ seems to indicate a 2.0 or greater version of mono would be adequate;
   "These instructions use the generic binaries, and works with any version of Mono > 2.6."

So, the solution IMO would be to:
1) to specify the Mono dependencies (mono > 2.6, etc) directly in the Duplicati RPM; 
2) To amend the Wiki page to make things more clear, ideally including a section about installing Duplicati on RHEL systems. 

=Eof=

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1006_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
