### ISSUE TITLE
It dropped the connection: The server committed a protocol violation.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1043]
_From [cgorri...@gmail.com](https://code.google.com/u/101932158175909790826/) on June 30, 2014 05:39:11_

What steps will reproduce the problem? 1. I was able o made my backups allright, but 2 weeks ago i cant made a connection and made my backups. I try with 2 differents servers, and i still cant backup my data.
2. I use ftp connection. What is the expected output? What do you see instead? I have the following error message:
"Error: No se ha podido subir el fichero "duplicati-full-content.20140629T143007Z.vol1.zip": Se ha terminado la conexión: El servidor ha cometido una infracción de protocolo.

Error: System.Exception: No se ha podido subir el fichero "duplicati-full-content.20140629T143007Z.vol1.zip": Se ha terminado la conexión: El servidor ha cometido una infracción de protocolo. ---> System.Net.WebException: Se ha terminado la conexión: El servidor ha cometido una infracción de protocolo.
   en System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   en System.Net.FtpWebRequest.RequestCallback(Object obj)
   en System.Net.CommandStream.InvokeRequestCallback(Object obj)
   en System.Net.CommandStream.Abort(Exception e)
   en System.Net.CommandStream.CheckContinuePipeline()
   en System.Net.FtpWebRequest.DataStreamClosed(CloseExState closeState)
   en System.Net.FtpDataStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   en System.Net.FtpDataStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en System.IO.Stream.Dispose()
   en Duplicati.Library.Backend.FTP.Put(String remotename, Stream input)
   en Duplicati.Library.Main.BackendWrapper.PutInternal(BackupEntryBase remote, String filename)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Duplicati.Library.Main.BackendWrapper.ExtractPendingUploads()
   en Duplicati.Library.Main.Interface.Backup(String[] sources)
   en Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: Se ha terminado la conexión: El servidor ha cometido una infracción de protocolo.
   en System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   en System.Net.FtpWebRequest.RequestCallback(Object obj)
   en System.Net.CommandStream.InvokeRequestCallback(Object obj)
   en System.Net.CommandStream.Abort(Exception e)
   en System.Net.CommandStream.CheckContinuePipeline()
   en System.Net.FtpWebRequest.DataStreamClosed(CloseExState closeState)
   en System.Net.FtpDataStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   en System.Net.FtpDataStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en System.IO.Stream.Dispose()
   en Duplicati.Library.Backend.FTP.Put(String remotename, Stream input)
   en Duplicati.Library.Main.BackendWrapper.PutInternal(BackupEntryBase remote, String filename)
Resultado de la limpieza: " What version of Duplicati are you using? On what operating system? Im using the Duplicati 1.3.4, but i also try the last version and i have the same problem. My OS is Windows XP SP3. What backend (destination) are you using? ftp Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1016_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
