### ISSUE TITLE
Make it possible to change the LZMA compression level

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1050]
_From [caffeine...@gmail.com](https://code.google.com/u/118357788592889920896/) on July 04, 2014 22:58:56_

Duplicati 2.0 is great, but it's slow as molasses to backup 300GiB of virtual machine images although all CPU cores are at peak load. I want to trade backup time for space usage.

I would like to be able to set the backup's compression level via a commandline switch like --lzma-level=1.

To be able to set the compression level, managed-lzma needs to be patched, since the compression level is baked into the encoder, see https://code.google.com/p/managed-lzma/source/browse/trunk/master/7zip/ArchiveWriter.cs?r=51#1087 I have a patched managed-lzma hosted at https://github.com/mostlyuseful/managed-lzma My changes to duplicati can be found at https://github.com/mostlyuseful/duplicati Patches for managed-lzma@ r51 and duplicati master are attached.
I've also raised a feature request at managed-lzma https://code.google.com/p/managed-lzma/issues/detail?id=1

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1023_

**Comment by Poincare1** [comment]
So .... how do we set a custom compression level for LZMA then?

**Comment by antivirtel** [comment]
Hi, I have the same question as above. I've used the deprecated `compression-level` option. It seems the files are small, so maybe that works? But if the `zip-compression-level` is ignored for LZMA, then how to set the compression level for that? I'm on the latest beta, `2.0.6.3_beta_2021-06-17`. Thanks!

**Comment by ts678** [comment]
```
Duplicati.CommandLine.exe help 7z
Experimental - 7z Archive (.7z):
 *Experimental*: 7z Archive with LZMA2 support.
 Supported options:
  --lzma-thread-count (Integer): Number of threads used in compression
    The number of threads used in LZMA 2 compression. Defaults to the number
    of processor cores.
    * default value: 4
  --7z-compression-level (Enumeration): Sets the 7z compression level
    This option controls the compression level used. A setting of zero gives
    no compression, and a setting of 9 gives maximum compression.
    * values: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
    * default value: 5
  --7z-compression-fast-algorithm (Boolean): Sets the 7z fast algorithm usage
    This option controls the compression algorithm used. Enabling this option
    will cause 7z to use the fast algorithm, which produces slightly less
    compression.
    * default value: False
  ```

but note the `Experimental`, and note the CLI warning below it wrote before breaking, at least for me:

> The 7z compression module has known issues and should only be used for experimental purposes

[Disable or fix 7z/LZMA2 #3054](https://github.com/duplicati/duplicati/issues/3054)

[Added warnings to discourage people from using 7z in the current state](https://github.com/duplicati/duplicati/commit/fe7f9cf67a32af00f71526b7a93e3ea5cd6e49e3)

**Comment by ts678** [comment]
> which is not Deflate

I don't think there is one, but Deflate has never been reported as hugely worse than LZMA as you say, in Internet reports I see.
Maybe other factors got in? For example, if you're using 7-Zip, that adds in other factors such as solid archives. 1/4 is still a lot.
Can you try to replicate my rather light web research results showing nowhere near that difference due solely to compression?

**Comment by antivirtel** [comment]
Hi,

This doesn't seem to be supported:
> ```
>   --7z-compression-level (Enumeration): Sets the 7z compression level
>     This option controls the compression level used. A setting of zero gives
>     no compression, and a setting of 9 gives maximum compression.
>     * values: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
>     * default value: 5
> ```

it displays a warning:
```
[Warning-Duplicati.Library.Main.Controller-UnsupportedOption]: The supplied option --7z-compression-level is not supported and will be ignored
```

Does the compression-level or zip-compression-level have any effect on LZMA?

Thanks!

**Comment by ts678** [comment]
> it displays a warning

Probably because you didn't tell it to use 7z via `--compression-module=7z` but that fails for me with:

> The 7z compression module has known issues and should only be used for experimental purposes

and then doesn't work. I think you should heed the warning and stop trying, or at least I can't help it.
[https://usage-reporter.duplicati.com/](https://usage-reporter.duplicati.com/) stats by compression might also convince you it's just not used.
