### ISSUE TITLE
Fails to backup to FTP with AES Extensions

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1052]
_From [erobis...@greenrain.us](https://code.google.com/u/103711471511193035632/) on July 14, 2014 22:27:30_

What steps will reproduce the problem? 1. FTP Backups with AES 2. 3. What is the expected output? What do you see instead? What version of Duplicati are you using? On what operating system? 22.0.0.7- 2.0_CLI_experimental_2014-06-23 - DEBUG What backend (destination) are you using? MS Server ASP hosting FTP Please provide any additional information below. The files DO backup successfully, but this error is listed for every backup:

System.Exception: The file duplicati-20140710T180520Z.dlist.zip.aes was uploaded but not found afterwards, the file listing returned 
at Duplicati.Library.Main.BackendManager.List()
at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
at 

I assume this is some MS ASP Issue....
How do I resolve this?

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1025_
##

**Comment by anneb** [comment]
backup to FTP fails when (windows) ftp server has setting 'always use lowercase for LIST'. 
Duplicati does a case sensitive compare and thinks uploaded files are not uploaded.
Fix: disable 'always use lowercase for LIST' on ftp server.

**Comment by kenkendk** [comment]
@anneb Thanks!
