### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1055]
_From [3rcale...@gmail.com](https://code.google.com/u/102360219347325644583/) on July 21, 2014 23:47:42_

What steps will reproduce the problem? When I press Test Connection an error message pops up, There are multiple folders named "........, please rename them manually" What is the expected output? What do you see instead? It should just copy instead of giving me the error. I cannot move forward. What version of Duplicati are you using? On what operating system? 1.3.4 What backend (destination) are you using? Google Drive Please provide any additional information below. None

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1028_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
