### ISSUE TITLE
2.0 Preview, Password Strength indictator changes to Unknown

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1058]
_From [jvanderv...@gmail.com](https://code.google.com/u/106295904093303653561/) on July 22, 2014 17:28:01_

What steps will reproduce the problem? 1. Refresh the browser GUI
2. Edit backup
3. Password strength indicator changes to unknown What is the expected output? What do you see instead? I would expect it to still indicate the strength. What version of Duplicati are you using? On what operating system? 2.0 preview What backend (destination) are you using? FTP Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1031_

**Comment by agrajaghh** [comment]
should be fixed with the new UI, please reopen if you encounter this again.
