### ISSUE TITLE
2.0 Preview, Submit Bug Report doesn't take you anywhere

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1059]
_From [jvanderv...@gmail.com](https://code.google.com/u/106295904093303653561/) on July 22, 2014 17:33:57_

What steps will reproduce the problem? 1. From backup context menu, select create bug report
2. "Method is missing a method for retrieving the report after it has been generated" appears. What is the expected output? What do you see instead? I would expect to either be taken to google code issue queue, or something built-in to happen. What version of Duplicati are you using? On what operating system? 2.0 Preview. What backend (destination) are you using? FTP Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1032_

**Comment by agrajaghh** [comment]
should be fixed now, please reopen if you encounter this again.
