### ISSUE TITLE
Run command before or after backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#106]
_From [nev1...@gmail.com](https://code.google.com/u/101157306107968038345/) on September 15, 2009 13:57:49_

It would be very handy to run a command prior to backup, such as a batch
file. This would allow closing of programs prior to backup that would
normally stop the backup completing properly due to open files.
(PS I'm a donater :D )

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=106_

**Comment by betohresdroid** [comment]
I need to know, how to make a script to make a task after my backup process, but I made a bat type file  in my hard disk c:\shutdown.bat, but after my backup nothing happend. How need to write and where need to write my script to shutdown the computer after my backup? I run Duplicati in Windows Operating system. Thanks for your guide.

I wrote this command : --run-script-after =c:\apaga.bat    but nothing happend
