### ISSUE TITLE
Umlaut breaks path (Duplicati 2.0.0.53- 2.0_preview_2014-07-25)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1063]
_From [mart.br...@gmail.com](https://code.google.com/u/116336007602888283531/) on July 27, 2014 11:50:06_
1. Umlauts (äüö ...) in source folders are not accepted any more. I can not save an existing backup set after editing.
   While trying to save, you get: "Could not save: Unable to parse backup or schedule object: Bad JSON escape sequence: \Ã¤. Path 'Backup.Sources[6]', line 1, position 1782". 
   Backup set contains "E-Mail-Anhänge" as source folder. This source folder is marked red.
2. When you create a backup target "abcädef" you get "abc\ädef" (subfolder "ädef" uder "abc") created.
3. Folders with umlauts in path seem to be treated correct while executing backup.
   " 
   Information: Adding directory C:\Daten\test\OrdnerÜlaut\
   Information: Checking file for changes C:\Daten\test\OrdnerÜlaut\test.txt
   Information: New file C:\Daten\test\OrdnerÜlaut\test.txt
   "
   In the restore dialog "OrdnerÜlaut" is listed, but without any content. What version of Duplicati are you using? On what operating system? Duplicati 2.0.0.53- 2.0_preview_2014-07-25
   Windows 7 x64

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1036_

**Comment by nathanejohnson** [comment]
https://github.com/duplicati/duplicati/commit/b8199ad1c44e2c4ab558cf90cfde5fdd17ed9d73#diff-29da11ba290ec47dc775a1696f4dcbd6R385

This regex doesn't seem to work, as {2,4,6,8} is not a valid regex quantifier.

https://docs.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions?view=netframework-4.7.2

The regex compiles, but from my testing it doesn't actually seem to match %u .  Also, are there situations where you've seen anything but %u followed by 4 characters in the wild?  The previous version had {4}, and from a quick glance at wikipedia that seems to be the most common.

**Comment by warwickmm** [comment]
Thanks @nathanejohnson.  My IDE claims the same (see issue #3737).
