### ISSUE TITLE
Add support for OVH hubiC

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1065]
_From [desoxyrebonukleinsaure@gmail.com](https://code.google.com/u/desoxyrebonukleinsaure@gmail.com/) on July 29, 2014 08:21:59_

I'd like to put my files to hubic ( https://hubic.com ) - the also have some sort of API: https://api.hubic.com/

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1038_

**Comment by seppi91** [comment]
+1

**Comment by chauffer** [comment]
+1
Duplicity already supports this.
