### ISSUE TITLE
Portable duplicati

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1074]
_From [ulic...@gmail.com](https://code.google.com/u/103035830080726123524/) on August 02, 2014 18:52:33_

What steps will reproduce the problem? 1.Duplicati.Server.exe --portable-mode
2.Creating task using web interface
3.In DB Duplicati-server.sqlite table backup is there still C:\Users\user\AppData\Roaming\Duplicati\TVQDDDYSHZ.sqlite
4.Even with task has this --dbpath=./data/localdb/Max_Daily.sqlite, because TVQDDDYSHZ.sqlite is created sooner that this option can be edit.
5.If deleted C:\Users\user\AppData\Roaming\Duplicati\TVQDDDYSHZ.sqlite logs are not working What is the expected output? What do you see instead? 1. With server run in portable no output should be placed in AppData\Roaming. Place it rather in data\localdb. Data folder is created right. What version of Duplicati are you using? On what operating system? latest What backend (destination) are you using? Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=1047_
##

**Comment by mr-flibble** [comment]
Hello, I report same problem in 2.0.0.81.
sqlite DB is created every time in \AppData\Roaming\Duplicati 
And setting:
"--asynchronous-upload-folder" or "--tempdir=" 
also does not work, temp is stored in \AppData\Local\Temp\2 

I have drive C SSD, so do not want to unnecessarily write temp data.
Any workaround? Thank you!

**Comment by mr-flibble** [comment]
Hello, I think this is now fixed (same as #128 )

If I use environment variable "duplicati_home" with path to folder, DB is created there. 
Then I only need set up advanced option "tempdir" for every backup config. 
Thanks

**Comment by kenkendk** [comment]
For the tempdir, you should be able to set the environment variable `TEMPDIR`, and that should apply to all temporary files.
