### ISSUE TITLE
Stuck at Completing Backup - No Log File Data Read

### ISSUE THREAD

**Issue by lovelytwo** [duplicati/duplicati#1077]
Stuck at Completing Backup. Just sit around using 1 whole cpu, No disk access. 967 MB of RAM, for 180gig backup. Also get error when trying to read log file "Failed to read log data"

How do you rebuild the local sqllite database from the remote end?

What version of Duplicati are you using? On what operating system?
Windows Server 2008 - Duplicati 2.0.0.53- 2.0_preview_2014-07-25

What backend (destination) are you using?
Local Folder

Please provide any additional information below.
Cmdline Options:
--no-encryption=True
--dbpath=G:\duplicati.sqlite
--snapshot-policy=on
--synchronous-upload=true

----------------------------
I've tried turning snapshot-policy=off and it still is stuck at the end of backup.

----------------------------
I tried following the procedure list here.

1. You need to create a new "backup" and be sure to remove the scheduled run. 
2. Renamed the sqllite database.
3. Then use the menu to run the "repair" command, this will rebuild the local database. After this you can restore as before. 

It finishes quickly and only creates a sqllite database which is a 17kb in size and still can't read the log. I'm guessing that dbpath isn't being handled correctly.

----------------------------
So I went ahead with using the command line client to repair the database. (Create new local database).
Duplicati.CommandLine.exe --no-encryption=True --debug-output=true repair file://G:\
Then I moved the new database out of APPDATA and into G:\, renamed it.

Still no log information
Did a Verify (happened very quickly 30 seconds)
Then did a Backup. Proceeded as Normal. Then hung at the end like before, I leave it running and see it ever finishes it not hitting any files on disk.

----------------------------
Nope Still Stuck at completing backup.

----------------------------
Is there anything else I should try before I delete this backup and start again?

**Comment by YasharF** [comment]
This seems to have been fixed.  Can we close this issue?

**Comment by renestach** [comment]
I think it is time to close this.
