### ISSUE TITLE
Preview 2.0 Layout Issue with IE 11

### ISSUE THREAD

**Issue by dtrhieu** [duplicati/duplicati#1081]
When running Duplicati Preview build 2.0.0.53 with IE11 on Windows server 2008, the UI is not usable.
UI works with Chrome.
![duplicati](https://cloud.githubusercontent.com/assets/8414622/3873497/57255d6a-2132-11e4-9bbb-c8368ab9b996.png)
##

**Comment by kenkendk** [comment]
This was fixed with the ngax theme.
