### ISSUE TITLE
--throttle-upload not working

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1084]
I already posted this in the [google group](https://groups.google.com/forum/#!topic/duplicati/oiP1ZGyl6Fo), but I think this is the better place for a bug report.

I'm running duplicati `2.0.0.57- 2.0_preview_2014-08-12` on Windows 8.1 (64 bit) and Windows 7 (32bit).

I tried to put these settings in the options field from the GUI:
    
    --throttle-upload=20000
    --throttle-upload=20kb
    --throttle-upload=20

but duplicati is still uploading with full speed (120kB/s) instead of 20kB/s.

**Comment by BmH86Qv6t** [comment]
Tested version 2.0.0.73_preview_2014-11-11 on Windows 7 Pro x64, Windows 8.1 x64, Windows Server 2008 R2 Standard x64.

Issue still existed in all tests.  :/

**Comment by agrajaghh** [comment]
Thanks @kenkendk ! Speed limiting is working for me now, but if I put `--throttle-upload=20` it's limiting the upload at 20KB/s not at 20B/s. I guess this is intentional? 

Because in the options help file its still written `Max number of bytes to download pr. second` and `Max number of bytes to upload pr. second`. Should I make a PR to fix the help file?

**Comment by BmH86Qv6t** [comment]
@agrajaghh Did you perform a build to test this?  I hadn't seen a new build released and I don't have the tools to build from source on my own.

**Comment by agrajaghh** [comment]
@BmH86Qv6t no, I downloaded the 2.0.0.76 directly. Look here for the link: https://groups.google.com/forum/#!topic/duplicati/FDrYVk1NyrY
