### ISSUE TITLE
Duplicati user interface rebrand and redevelopment

### ISSUE THREAD

**Issue by eswoosh** [duplicati/duplicati#1091]
To redesign and develop new Duplicati interface
##

**Comment by alexplusde** [comment]
Any news for a redesign? Duplicati is such a feature-rich and robust tool, it could be one of the best and easiest (and free!) backup tools with a tuned UX/UI.

**Comment by kenkendk** [comment]
I have added my work-in-progress for a new Angular based UI in the "angular_ui" branch.
It includes a new contributed layout/design.
Feel free to poke around :)

**Comment by StudioLE** [comment]
How is the Angular UI progressing? Are you looking for additional contributors?

I have some experience in Angular and about a year ago I had the same thoughts regarding the need for a UI redesign so put together a prototype but never got around to finishing or publishing it but I may as well put it forward in it's current state:

 [Demo](http://duplicati.studiole.uk/)
 [GitHub repo](https://github.com/StudioLE/DuplicatiUI)

**Comment by kenkendk** [comment]
Yes! I am definitely looking for help with the Angular UI!

If you check out the angular_ui branch, there is now an Angular UI in the ngax folder:
https://github.com/duplicati/duplicati/tree/angular_ui/Duplicati/Server/webroot/ngax

It is based on a html/css design by Alexander, where I have added all the Angular code required to make it running. However, I am no design CSS expert, so I have just hacked on additional styles as I needed them, but it needs some polish to look nice.

The current code has all the Angular controllers, directives, etc required to do most of the operations with Duplicati: List backups, Monitor server state, Pause/resume server, Run backup, Edit/Add backup, Browse source folders, Edit backend URI, Activity progress bar, Restore direct and from existing, Browse/search/select restore data.

Some of the stuff that is not yet implemented is the context menu (import, export, etc), the log area and the notifications.

I like the demo, it looks very nice and polished.
You are using jquery only? Would you want to move it to Angular?

**Comment by StudioLE** [comment]
I'd be happy to port the UI to Angular, however I've never worked on a C# project before and haven't a clue how to launch the backend on the angular_ui branch.

**Comment by kenkendk** [comment]
@StudioLE: Otherwise, you can use latest build and replace the webroot folder with whatever you like.

**Comment by kenkendk** [comment]
The new UI is now in the master branch.

I implemented the missing functionality, except the notifications.

You can choose between the themes from a theme picker, which should also make it easier to add new UI's (or themes) in the future.

There is a new build with the Angular based UI here:
http://updates.duplicati.com/preview/duplicati-2.0.0.92_preview_2015-11-30.zip

**Comment by agrajaghh** [comment]
@kenkendk really nice work, keep it up! :blush:

Do you already want bug reports regarding the new UI? I just noticed some small glitches (you probably already know about them anyway...)

**Comment by kenkendk** [comment]
There are quite a few layout issues (buttons hanging off center, etc), but other than that, feel free to create issues. Be sure you mention what UI you are using :).

**Comment by kenkendk** [comment]
I am closing this as we are now fully on the NGAX UI with Angular.
