### ISSUE TITLE
Duplicati _2.0.0.57: DBPATH not imported from JSON File

### ISSUE THREAD

**Issue by donestefan** [duplicati/duplicati#1095]
Hi,
Steps to reproduce:
- Create an Backup Job
- Start the Backup Job
- export the Backup Job to a file (json)
- delete the Backup Job
- re-import the backup job from the file
- click on the Backup Job and select "verify". This gives an error:
  "Error while running Backupjob. Database file does not exist: C:\Users.....\EKSANJDIKH.sqlite"
  The filename shown is not the one from the json file.
- Starting the the Backup job afterwards results in an Error:
  "Error while running backupjob: Found 3 remote files that are not recorded in local storage, please run repair"
- Running repair results in an error message: "Error while running backupjob: Der Prozess kann nicht auf die Datei zugreifen, da sie bereits von einem anderen Prozess verwendet wird." (process can not access the file, because it is in use by a different process)

The cause of the problem is that the "DBPath" value in the json file is not honored during import. Duplicati will create a new sqlite File which is empty (ignoring the existing sqlite File). 

Even the Option "--no-local-db=true" will not changeanything.

I guess this is not intended behaviour.
##

**Comment by dd23** [comment]
Same problem here on most recent 2.0.0.85

**Comment by Pectojin** [comment]
Behvaior today is to not import the DB path intentionally, reference #3005.

Although I believe the handling of imports has been improved so that the job created a proper new database and doesn't throw an error.
