### ISSUE TITLE
Duplicati 2 does not store and check files modification time

### ISSUE THREAD

**Issue by lucatrv** [duplicati/duplicati#1099]
I am using Duplicati 2.0.0.60 on Windows 7 64-bit.

If I make a backup, then replace a file with an older copy (modification time earlier than the backup), then run again the same backup, the older file is not stored in the second backup.

I found online other references to this issue, it turns out that Duplicati does not store the modification time of each file, only the time of the backup, and then analyses only those files that have modification time later than the backup. This is a serious issue, as one of the good features of a versioning backup software like Duplicati 2 is being able to restore files to previous versions... it does not make sense that then these files cannot be backed up anymore.

Please notice how "rsync" behaves, from its man page: Rsync finds files that need to be transferred using a "quick check" algorithm (by default) that looks for files that have changed in size or in last-modified time.

This should be the default for any backup software. Duplicati should by default store file size and modification time. If either one of the two have changed the file content should be analyzed.

The option "--disable-filetime-check=true" is not the solution, as it greatly increases backup time (all files are analyzed). The same option exists for rsync.

The option "--store-metadata=true" does not seem to help (the older file is still not backed up). On a side note, I verified that the db files using this option are similar in size to a standard backup, so I actually wonder if this option works at all.

In my opinion, size an modification time of all files should always be stored and checked, and the option "--store-metadata=true" should still be available to store and check metadata other than modification time.

**Comment by kenkendk** [comment]
The reason --store-metadata was not on by default was that the restore of metadata was not implemented.

This is implemented in 2.0.0.79 and later, where the store-metadata option is now obsolete and the --skip-metadata option can be used to avoid the metadata.
