### ISSUE TITLE
2.0.0.60: Problem editing the local Folder Backup Location

### ISSUE THREAD

**Issue by donestefan** [duplicati/duplicati#1101]
Duplicati 2.0.0.60 on Windows7

Steps to reproduce:
- Edit an already defined Backup to a local Folder
- the "General" Tab shows the correct Path (e.g. "file://C:\Backup_location\")
- Clicking "Backup to..." shows the wrong Path ("C" instead of "C:\Backup_location\"]

**Comment by donestefan** [comment]
The Problem is gone in the new Webinterface of Version 2.0.1.7_experimental_2016-03-19

**Comment by kenkendk** [comment]
Great, thanks for reporting back.
