### ISSUE TITLE
Invalid header marker

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1122]
Since the update to 2.0.0.65 I'm getting these errors/warnings:

**Message**

    remote file duplicati-beb8f93c067464d2dacd83e45b8ab2084.dblock.zip.aes is listed as Verified with size 0 but should be -1, please verify the sha256 hash ""

**Message**

    No hash recorded for duplicati-beb8f93c067464d2dacd83e45b8ab2084.dblock.zip.aes, performing full verification

**Retry (5x)**

    Operation Get with file duplicati-beb8f93c067464d2dacd83e45b8ab2084.dblock.zip.aes attempt 1 of 5 failed with message: Invalid header marker
    System.Security.Cryptography.CryptographicException: Invalid header marker ---> System.IO.InvalidDataException: Invalid header marker
    bei SharpAESCrypt.SharpAESCrypt.ReadEncryptionHeader(String password)
    bei SharpAESCrypt.SharpAESCrypt..ctor(String password, Stream stream, OperationMode mode)
    bei Duplicati.Library.Encryption.AESEncryption.Decrypt(Stream input)
    bei Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
    bei Duplicati.Library.Encryption.EncryptionBase.Decrypt(String inputfile, String outputfile)
    bei Duplicati.Library.Main.BackendManager.DoGet(FileEntryItem item)
    --- Ende der internen Ausnahmestapelüberwachung ---
    bei Duplicati.Library.Main.BackendManager.DoGet(FileEntryItem item)
    bei Duplicati.Library.Main.BackendManager.ThreadRun()

**Result**

    Warnings: [remote file duplicati-beb8f93c067464d2dacd83e45b8ab2084.dblock.zip.aes is listed as Verified with size 0 but should be -1, please verify the sha256 hash "", remote file duplicati-beb8f93c067464d2dacd83e45b8ab2084.dblock.zip.aes is listed as Verified with size 0 but should be -1, please verify the sha256 hash ""]
    Errors: [Failed to process file duplicati-beb8f93c067464d2dacd83e45b8ab2084.dblock.zip.aes => Invalid header marker]

The file duplicati-beb8f93c067464d2dacd83e45b8ab2084.dblock.zip.aes doesn't exist on my remote storage (WebDAV).

I didn't had any problems with 2.0.0.60. What could be the cause? Should I create a bugreport?

**Comment by agrajaghh** [comment]
seems to be fixed with 2.0.0.76  :+1:

**Comment by kenkendk** [comment]
Nice!
