### ISSUE TITLE
Unable to Update

### ISSUE THREAD

**Issue by mdarbyg** [duplicati/duplicati#1125]
I read that version 2 is supposed to auto update.
I do not know what it is supposed to do, but it just goes in circles. when I clicked the install button for  2.0.0.65. It downloads, then shows another install button, which downloads, then shows another install button, as so on. No error Messages or anything

The only possible issue I can figure is that Avast vaulted it as malware the first time. However, I have disabled the virus scanner and still see the same behavior.

**Comment by agrajaghh** [comment]
There were some changes regarding the autoupdate. Please reopen if you encounter this again with the new versions.
