### ISSUE TITLE
"Inconsistency in file while validating database" breaks backup

### ISSUE THREAD

**Issue by Simpelton** [duplicati/duplicati#1143]
I regularly get the error message
System.IO.InvalidDataException: Found inconsistency in the following files while validating database: 
C:\SomeFile.xyz, actual size 7344, dbsize 8369, blocksetid: 1234

Two issues:
1. The backup stops with this error message. Better: Continue with the backup and ignore the affected file(s)
2. No graceful recovery possible. Repairing the DB option fails due to error message "File already in use". So I need to completely dump the backup and start over again.

Observation:
The initial inconsistency issue seems to be related to incomplete initial backup runs. This error happend already multiple times. Each time the initial backup run got interupted  (my backup destination disconected). As I did not find a way to gracefully recover, I did dump the backup and started over again.
Update: Once in 3-4 tries I did manage to delete the DB "Delete local data" AND repair the local DB without the error message "File already in use". Repair did rebuild the DB and the backup started up to grind through the rest of the files.

Background:
Duplicati 2.0.0.65, Windows 8.1, Duplicati Service.exe is started as a service with a User that is member of the local admins. Service was created with the SC command line tool.
Backup destination is a dedicated NAS that operates only during a certain period of the day. Backup data amount is about 400GB
##

**Comment by solemgar** [comment]
This is still happening in 2.0.90

**Comment by kenkendk** [comment]
To fix this, I need a copy of a database with the problem.
You can create a copy with the "bugreport" command, which will delete all path information, so the database only contains hashes.

**Comment by solemgar** [comment]
Hi Kenneth, not sure if you will receive the email here, I am attaching the
bug report as requested. Thanks a lot for your time, I really appreciate it
and I know that developing a tool like this is not an easy task.

Let me know if you need more info from my side.

Marcos.​
 bugreport.zip
<https://drive.google.com/file/d/0B5F6SinSpEaQT2VoSWtsSGxxU0E/view?usp=drive_web>
​

On Wed, Oct 28, 2015 at 11:00 AM, Kenneth Skovhede <notifications@github.com
