### ISSUE TITLE
Win8.1: Duplicati.Service.exe times out when started as a service

### ISSUE THREAD

**Issue by Simpelton** [duplicati/duplicati#1144]
I have setup Duplicati.Service.exe to start as a windows service (Win8.1) using the SC command line.

sc create DuplicatiServer Binpath="C:\Programfiles\Duplicati\Duplicati.Service.exe"

The service is run with a user that has admin rights. Every time the service starts, windows reports the service did not respond within the expected time period. Never the less, Duplicati is working and operational.

A potential workaroung might be to change the time that windows waits for services to respond. But that registry setting would affect all windows services and thus seems inappropirate.

The issue affects particularly the debugging, as the Duplicati.Service can not be controlled via the service management (it is reported as not running in the windows services, despite the fact that Duplicati works nicely). So I need to kill the duplicati process ungracefully or do a restart of the windows box.

**Comment by kenkendk** [comment]
The latest canary build can self-install, just use:
```
Duplicati.WindowsService.exe install
```
