### ISSUE TITLE
Duplicati hangs with Google Drive

### ISSUE THREAD

**Issue by bfops** [duplicati/duplicati#1147]
Installed Duplicati x86_64 on Arch Linux (also tried with duplicati-latest). Went through the dialogs, tried to sign into a Google docs account, and "Test connection" just hangs. If I create the backup anyway, it hangs at "verifying backend data".
##

**Comment by hifi25nl** [comment]
I have the same problem: test connection will take a long time without success.
I don't think this has something to do with volume size.

**Comment by mjmayer** [comment]
I believe this may be an issue with the version of Mono installed. I'm running Mint 18.3 on my desktop and the repos had mono 4.6.2.16 installed. I installed the latest version of mono  5.4.1.6 from the mono [website](http://www.mono-project.com/download/). Duplicati was able to successfully test the connection and complete a backup.

**Comment by Pectojin** [comment]
@mjmayer likely. I've been using GDrive on Ubuntu for 6 months no problems. I don't think this issue is relevant anymore with newer versions.
