### ISSUE TITLE
Dismissing a notification has sideeffects

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1153]
When dismissing a notification other notifications can also disappear.

This was reported in issue #1150:
"Minor issue: When multiple Backups have completed with warnings (3 in my case) and i "dismiss" the topmost one, the lowest on the list also disappears."
##

**Comment by warwickmm** [comment]
Each notification has its own dismiss button, and there is also a "dismiss all" option.

https://github.com/duplicati/duplicati/issues/1268#issuecomment-749238941
