### ISSUE TITLE
Cannot download Duplicati 2.0

### ISSUE THREAD

**Issue by lablua** [duplicati/duplicati#1164]
The Duplicati website provides the following download link: http://updates.duplicati.com/preview/latest.zip

However, when I try to download it I get ERR_CONNECTION_RESET. Also, the following site confirms it is not just down for me: http://www.downforeveryoneorjustme.com/http://updates.duplicati.com/preview/latest.zip

**Comment by YasharF** [comment]
Avast is marking v2.0.1.13-2.0.1.13_canary_2016-04-10 as Win32:Malware-gen; I reported it as a false positive a week ago, but I think they didn't whitelist it.  Did some meta data change in this build?

**Comment by kenkendk** [comment]
I think this is now solved as all files are signed with a codesigning certificate.
