### ISSUE TITLE
Unable to setup backup on windows client using webdav

### ISSUE THREAD

**Issue by zubanst** [duplicati/duplicati#1167]
Hello,

I installed Duplicati 1.3.4 for Windows - (32bit, msi) on a windows 7 home edition; when setting up a backup task using webdav based destination, I get the following error: Connection failed: The underlying connection was closed: An unexpected error occurred on a send.

![duplicati](https://cloud.githubusercontent.com/assets/9291863/4688781/e31e2c90-5691-11e4-8c47-b03fb2785397.PNG)
![duplicati_error](https://cloud.githubusercontent.com/assets/9291863/4688784/02cd8c52-5692-11e4-8957-5a0849e3f17b.PNG)

 Yet the server is up and runnung and setting up a webdav drive in ubuntu works fine.

The server is www.pennyitsupport.eu connection ssl.

**Comment by kenkendk** [comment]
405 indicates that the remote server does not support a specific method, which I am guessing is "PROPFIND". This would indicate that the server rejects WebDAV commands. This could also happen if you attempt to use WebDAV features without being logged in. If there are still issues, please open a new issue so there is no confusion with the 1.3.x version.

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.

like kenkendk said, if you are still having problems with webdav and duplicati 2.0, please open a new issue. Thanks.
