### ISSUE TITLE
2.0 reverting "next run" date to past date (first date ever set on that backup) after running

### ISSUE THREAD

**Issue by mangiarape** [duplicati/duplicati#1173]
Issue occurs when:
1. I force a backup to run now, without setting a next run date in the future
2. I set a next run date in the future. Backup runs accordingly, then after that "next run" appears again as the original date (the date I set up and saved that backup settings for the first time.
##

**Comment by Pectojin** [comment]
I don't think this issue occurs anymore on newer versions. Please let me know if it still does.
