### ISSUE TITLE
Duplicati bug in restore ui in linux version 2.0.0.66

### ISSUE THREAD

**Issue by Roadrunneruk** [duplicati/duplicati#1176]
Hi
I made a backup in the command line on a windows 7 machine about 2 month ago, there restore ok in windows, but when i try and restore these files on a  linux computer I  get " you must select at least one path to restore" message see pictures

![1](https://cloud.githubusercontent.com/assets/9529362/4881387/491c51b2-6348-11e4-8dd4-9288190ab904.png)
![2](https://cloud.githubusercontent.com/assets/9529362/4881390/50a98918-6348-11e4-81f1-f5a9743622df.png)

Hope this can be fixed.

Thanks
Andy
##

**Comment by Pectojin** [comment]
Again, I hope I don't step on anyone's toes, but I'm not sure this bug even exists anymore (I don't even recognize the UI).

I think it's safe to close this issue.
