### ISSUE TITLE
Duplicati restore help bubble stays open on restore screen

### ISSUE THREAD

**Issue by Roadrunneruk** [duplicati/duplicati#1177]
Hi
Running version 2.0.0.66 and when i click on "restore from target"  and then click on "restore from", the help bubble stays on the screen and covers the underline text and you have to drag the underline window over. This only happens the first time you run restore command, you have to restart the browser to get this to happen again. 

![3](https://cloud.githubusercontent.com/assets/9529362/4881545/58dd1f62-634a-11e4-8db2-4873eb70a102.png)
![4](https://cloud.githubusercontent.com/assets/9529362/4881547/5ad1804c-634a-11e4-9f5f-2e1117188bdf.png)
![5](https://cloud.githubusercontent.com/assets/9529362/4881549/5cdc5966-634a-11e4-8ce5-0b8e67517903.png)

Hope this helps

Andy
##

**Comment by Pectojin** [comment]
I hope I don't step on anyone's toes, but I'm not sure this bug even exists anymore (I don't even recognize the UI).

I think it's safe to close this issue.
