### ISSUE TITLE
Menu is displayed cut-off

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1183]
I'm having a problem with duplicati: the menu is cut-off so I can't click on "run backup now":
![dp](https://cloud.githubusercontent.com/assets/5296073/4953197/c7c912ce-667d-11e4-985a-71bcf2fa783b.png)
I guess its because the menu is either displayed above or below the button, but nothing in between for smaller screens.

**Comment by rocifier** [comment]
I fixed this issue in my fork

**Comment by agrajaghh** [comment]
@rocifier thanks man! Hope to see a PR soon ;) Btw, do you need some help with git? I noticed that you had some problems earlier with another PR... I can't help with real development, but perhaps I can help like that...

**Comment by rocifier** [comment]
@agrajaghh yes please I suck at git, how do I create a push req for just that small change? I changed a lot of other stuff too

**Comment by agrajaghh** [comment]
@rocifier I wrote you an email

**Comment by huste** [comment]
It seems to be fixed in 82, true?

**Comment by agrajaghh** [comment]
@huste not for me

**Comment by huste** [comment]
Hm, maybe it's because at work I have more backup jobs so that I can always scroll. I Will check at home with less backup jobs.

**Comment by agrajaghh** [comment]
It just happens now with really small window sizes (menu will be cut off at the end), so I guess this issue could be closed. But I'll leave this up to you...

**Comment by huste** [comment]
Yes, that's true. On my laptop where I had this issue due to low vertical resolution, it works fine.

**Comment by kenkendk** [comment]
I will mark this issue as closed unless it really bothers people :)
