### ISSUE TITLE
SSH backend not available in duplicati-commandline version 1.3.4-dev05 for Debian

### ISSUE THREAD

**Issue by lukasbaxa** [duplicati/duplicati#1185]
Version 1.3.4 (duplicati-commandline) cannot be used for scripting purposes, because it doesn't return proper exit codes. This is fixed in the development snapshot 1.3.4-dev05 (https://code.google.com/p/duplicati/wiki/Downloads?tm=2). Tested on Debian wheezy.

However, duplicati-commandline version 1.3.4-dev05 (from the deb package) lacks support for the ssh backend which makes it unusable in our environment.

The output is always following (credentials are correct, ssh works in 1.3.4):
$ duplicati-commandline backup 'data1:data2:data 3' ssh://dpa-backup@localhost/dst --full

Unable to find backend for: ssh://dpa-backup@localhost/dst

Also the output of help doesn't mention this target:
$ duplicati-commandline help
...
  Targets: cloudfiles, ftp, file, googledocs, s3, skydrive, webdav
...

However, we need to run the script also on CentOS (rpm).

**Comment by kenkendk** [comment]
Closing as we are no longer working on 1.3.x. Version 2.0 builds on Ubuntu and Fedora without issues.
