### ISSUE TITLE
Yoshmite MacOS10.10 Installation Failed

### ISSUE THREAD

**Issue by Bazzalad** [duplicati/duplicati#1187]
Hi, I am using the lastest version of MacOS10.10, including the latest test seed (in case thats causing the issue) and followed installation instructions, including downloading the additional mono framework. 

However, when the App is opened to run it bounces nicely in the dock but then becomes unresponsive and fails to open.

 I have reported this issue to Apple as well via the Beta testing feedback framework (I don't know if they pass on any information to 3rd party developers or not?). 

If you like I am more than happy to send a copy of my system log and any all data that was forwarded to Apple, so they can investigate at their leisure. Was so amped about finding your app, so hoping this is a simple OS compatibility related issue that is easily resolved in near future. If this is specific to my environment then I definitely like to know so I can look to resolve. Cheers, 
##

**Comment by ethus3h** [comment]
It worked eventually for me, I just left it open a long time, might have restarted it a couple times. (I'm using Yosemite)
