### ISSUE TITLE
UI Password ignored

### ISSUE THREAD

**Issue by Brenkon** [duplicati/duplicati#1191]
Duplicati.GUI.TrayIcon - version 2.0.0.71 - run as admin

When I set the User Interface password  in Options, and then click "OK" - the password prompt does not appear when I reopen the browser to http://127.0.0.1:8200/greeno/ . I have open access to the UI. 

Chrome browser on Windows 7 64bit.

UPDATE: 

I tested again after leaving the localhost:8200/greeno UI for a few hours, and I was correctly prompted for a password. 

So my question now is: what is the default time duration for the UI passwork lock to turn ON, and is this configurable?

**Comment by caldude321** [comment]
Is there a way to view or reset the password?  I can't seem to access mine.  It's hard to believe I forgot all my passwords, perhaps it didnt like a special character.  I probably used one or all of the following: $%&*() 

Thanks.

**Comment by kenkendk** [comment]
@caldude321 You can start Duplicati.GUI.TrayIcon.exe or Duplicati.Server.exe with the option --webservice-password=new_password
