### ISSUE TITLE
msvcr100.dll in release

### ISSUE THREAD

**Issue by ulicky** [duplicati/duplicati#1197]
Hi, it is possible to include msvcr100.dll in alphavss folder? 
Otherwise it throws error during backup: Failed to create a snapshot: System.IO.FileNotFoundException: Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies. The specified module could not be found.
I dont want to install msvcr100.dll globally. Thanks

**Comment by rocifier** [comment]
Visual C runtimes are supposed to be installed globally though?

**Comment by kenkendk** [comment]
Yes, you need the Visual C runtime installed.
I doubt you can just copy in the msvcr100.dll and have it all working.

**Comment by ulicky** [comment]
Yes, it just working this way. These share libraries could be installed globally and locally by each application. Without this is difficult to have application portable :(
