### ISSUE TITLE
https for webinterface

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#1198]
Hi, it is possible to add support for https and custom certificates? It transfers passwords like webinterface, or passphrases for backups in clear text.
Thanks

**Comment by ulicky** [comment]
Any updates? Passwords are traversing over network unencrypted, which is bad even for internal network :( especially password for target backup destinations during editing of job, and passwords for encryption of backup itself. Webserver used in Duplicati support HTTPS https://webserver.codeplex.com/wikipage?title=HTTPS&referringTitle=Home
All we need is some config box for certificate upload to database and checkbox to choose whether to use HTTP or HTTPS.

**Comment by HRomie** [comment]
A secure web interface would be very useful. If i know that i can open up duplicati port to the world (well, not really 'the world'. maybe internal network) and it would be protected against password snooping, and also the login webpage could not be bypassed somehow, i could easily centralize the clients backups management. I went as far as setting up stunnel on each client to secure http requests externally, but i would love an integrated solution.
Requiring a valid CA by the browsers, is not a new feature/issue and probably not a good enough one for not implement the https support. if a user is advanced enough to feel the need to use https, he is advanced enough to take care of the CA issue. Beside, with the solutions like Let's Encrypt, getting a valid signed certificate has become easier and cheaper than ever.

**Comment by glannes31** [comment]
Hello , I have an error secure chanel when i tick use ssl. i opened an issue for that . Please help me

**Comment by mnaiman** [comment]
@glannes31 don't understand your question at all. where do you tick? what kind of error? be more detailed

**Comment by glannes31** [comment]
https://github.com/duplicati/duplicati/issues/1836 the error is in the issue. In duplicati 2.0 , i tick use ssl , i entered server and port , path , username and password  . I click on test connexion and i have SecureChanelFailure

**Comment by mnaiman** [comment]
These two issues are not connected. Youre issue is about connecting to webdav backend, this issue is about about ability to serve admin pages over https.

**Comment by rkarlsba** [comment]
Any idea if this will be included the next beta? Not supporting https/tls in 2018 is rather a wierd disability…

**Comment by mnaiman** [comment]
@rkarlsba HTTPS is supported, you must enable it via command line, GUI for setup is not available so far
