### ISSUE TITLE
advanced deleting of backup configs

### ISSUE THREAD

**Issue by donestefan** [duplicati/duplicati#1201]
When selecting "delete Configuration" in the GUI  it might be a good idea to use the following Popup to 

- offer exporting the configuration to a file before deleting
- offer deleting the local database in the same step (to avoid cluttering the duplicati config folder with old configurations). Maybe one should even point out that deleting the database does not render the backup data useless, since the local database can easily be rebuild from the Backup destination when re-importing a configuration.
- even offer deleting the actual backup data 

Quite a few users might not be aware that all this is worth considering... 
And when you already deleted a Backup Configuration it's very difficult to find out which database was associated with it (so you can delete it later). It might be worth stating that clearly before the user deletes the config.

**Comment by kenkendk** [comment]
I have implemented this in 5a74a6e22e201bc6fa0d75942796d079232c8e41.

Perhaps I am being paranoid, but I really don't like the idea that there is a single web-api call that can erase your backup. If I merge this in, then ransomware can simply make a http request to the local webserver and this will cause Duplicati to erase the remote backup.

I think we should add something like a CAPTCHA or similar defense, if the user has checked the "delete all remote data" option.

**Comment by agrajaghh** [comment]
> I think we should add something like a CAPTCHA or similar defense, if the user has checked the "delete all remote data" option.

or ask for the remote password and/or encryption password again?

I agree, this option is dangerous... But I guess every other backup solution has a way of deleting the backup as well no?

**Comment by kenkendk** [comment]
We can ask for the password again, but it is trivial to bypass this from outside the GUI.

I think other backup solutions are not as exposed if they do not have a web-api. You can automate some GUI clicks, but sending a web-request is far easier.

**Comment by agrajaghh** [comment]
true, but you could also delete all local files, set "keep backups" to 1 second and run compacting via the web-api or command line. The only safe thing would be not to save the backend password I guess, but this would make background backups impossible 😏

**Comment by kahomono** [comment]
I have been testing a LOT of large backups.

I **had** been going to my SSH login to delete the last backup before making the next one. 

Then I tried the "Delete" checkbox and got the captcha.  I can only describe my feeling at seeing a captcha sully the UI of Duplicati as, a shock of disappointment.

I'll be back to SSH when the next backup is ready to go.
