### ISSUE TITLE
2.0.0.73: Balloon tips don´t disappear 

### ISSUE THREAD

**Issue by Dachu23** [duplicati/duplicati#1204]
I think it would be a bug you would like to address. There are balloon tips displaying while browsing through the options and they just don´t disappear, making clicking something not possible. I have to refresh the webpage but it does not always help.. 

I am using:
Duplicati 2.0.0.73- 2.0.0.73_preview_2014-11-11
Firefox 33.1

![balloon tips](https://cloud.githubusercontent.com/assets/9768342/5058113/1b48f300-6ce2-11e4-9176-648ede7c3195.PNG)
##

**Comment by rocifier** [comment]
This happens very occasionally in Chrome on Win7. Another small related issue is the pull-down menus on the index page, which only close when you click the button again instead of anywhere on the page.
