### ISSUE TITLE
Mono crashes when trying to install 2.0 Preview in Linux

### ISSUE THREAD

**Issue by jd-hupp** [duplicati/duplicati#1211]
As root I extracted today's latest.zip into /opt/duplicati.  Then I installed the mono-runtime package.  In a terminal, from /opt/duplicati I then ran:
$ mono Duplicati.GUI.TrayIcon.exe

The terminal window output:

Missing method .ctor in assembly /opt/duplicati/Newtonsoft.Json.dll, type System.Runtime.CompilerServices.ExtensionAttribute
Can't find custom attr constructor image: /opt/duplicati/Newtonsoft.Json.dll mtoken: 0x0a000075
- Assertion at class.c:5597, condition `!mono_loader_get_last_error ()' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at Duplicati.Library.AutoUpdater.UpdaterManager.ReadInstalledManifest (string) <0x0010b>
  at Duplicati.Library.AutoUpdater.UpdaterManager..cctor () <0x00373>
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at Duplicati.GUI.TrayIcon.Program.Main (string[]) <0x0000f>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

```
mono() [0x8105b4a]
[0xb777c40c]
[0xb777c424]
/lib/i386-linux-gnu/libc.so.6(gsignal+0x47) [0xb7573577]
/lib/i386-linux-gnu/libc.so.6(abort+0x143) [0xb75769a3]
mono() [0x8288b23]
mono() [0x8288bb3]
mono() [0x816b4d1]
mono(mono_class_get_full+0xff) [0x816bdff]
mono(mono_class_get+0x1f) [0x816bf4f]
mono() [0x81907ed]
mono(mono_get_method_full+0x8c) [0x819091c]
mono() [0x80b0055]
mono() [0x8066ccc]
mono() [0x8068de4]
mono() [0x8069aee]
mono() [0x8106d17]
[0xb776603e]
[0xb720046c]
[0xb71fff79]
mono() [0x8069bf0]
```

Debug info from gdb:

Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries used by your application.

Aborted (core dumped)

---

---

---

The output doesn't seem to indicate a permissions issue, but just to be clear: Do I need to run this mono command with sudo?  Or make some other mistake?

I'm running Lubuntu 14.04 32-bit on a Pentium 4 @ 3 GHz with 1 GB RAM.

**Comment by pbhj** [comment]
Same, on Kubuntu 14.10 mono-complete fixed this error for me, however with the latest.zip (2.0.0.87 IIRC) my browser can't access the GUI (even with firewall disabled) despite the tray icon showing that Duplicati is running.
