### ISSUE TITLE
2.0.0.73 failing to update

### ISSUE THREAD

**Issue by mangiarape** [duplicati/duplicati#1212]
Running 2.0.0.71. I get notified about the 2.0.0.73 update available. It downloads the update but then I cannot find even the 2.0.0.73 folder at /updates. In other words I do not know where those files are being downloaded.
If I click on "restart" to complete the update, nothing happens. 
OS is W7 64bit.

**Comment by kenkendk** [comment]
I think this is now solved as all files are signed with a codesigning certificate.
