### ISSUE TITLE
2.0: Special chars in argument --prefix throws error

### ISSUE THREAD

**Issue by rdebel** [duplicati/duplicati#1219]
Using special chars like " or even - in the prefix argument throws following error: Error: "Object reference not set to an instance of an object" .
In Duplicati 2.0 Server using the gui, but apparently also when using the commandline. See https://groups.google.com/d/msg/duplicati/VZyIKV1xKSI/zCipif4iMVoJ 
##

**Comment by Pectojin** [comment]
https://github.com/duplicati/duplicati/commit/7e466e11cf896868e824811f1eeb10039bb7dff3
