### ISSUE TITLE
Feature: BITS Upload for OneDrive (Files >100mb)

### ISSUE THREAD

**Issue by J0s3f** [duplicati/duplicati#1222]
It would be great if Duplicati 2 supported the BITS upload protocol for OneDrive.
With this protocol, files > 100mb can be uploaded in chunks (up to 10GB per file atm).
This might be relevant for heavy users in the future, because while OneDrive removes the size limit, there is still a file limit of 10 million files.
With 10GB files instead of 100MB, the possible amount stored in one OneDrive is 100 times higher!

Information aubout the protocol: https://github.com/mk-fg/python-onedrive/issues/34

**Comment by kenkendk** [comment]
The protocol seems fairly easy to use:
https://gist.github.com/rgregg/37ba8929768a62131e85

**Comment by kenkendk** [comment]
I have this implemented, and am currently running tests to see that it performs as expected.
