### ISSUE TITLE
LINUX - Enable remote access from command line

### ISSUE THREAD

**Issue by guiand888** [duplicati/duplicati#1223]
I want to run Duplicati on my headless Debian home server, and access its webUI from another laptop.

Duplicati starts fine in command line but I can't access the webUI.
For instance, homeserver (H) is 192.168.0.100
My laptop is (L)

I ssh to from (L) to (H), then run "mono Duplicati.Server.exe --webservice-port=8200"
From what I understand, I should then access the webUI at: http://localhost:8200
But of course, I can't access (H) localhost since my browser is running on (L).
I want to access the webUI running http://192.168.0.100:8200

My guess is I can't access it because the "remote access" option that is available in the GUI is not activated by default. And of course, since I cannot access the webUI, I can't activate it.

Is there any command line to activate it? Or could this be activated by default?

Thanks!

**Comment by phrogg** [comment]
I'm trying the same thing here, don't want to use ssh tunneling. How did you enable the remote access?
