### ISSUE TITLE
Add Amazon S3 AWS4 support

### ISSUE THREAD

**Issue by mkiehl** [duplicati/duplicati#1224]
Hello,

Duplicati currently does not support AWS Signature Version 4, making it unable to work with e.g. the Frankfurt AWS location. It would be very nice to see this feature added.

Thanks for your great software :+1:

**Comment by rocifier** [comment]
Hi I've upgraded the AWSSDK to the latest version here, and it's a very easy change actually. Just delete the reference in S3 project to AWSSDK and use nuget package manager to re-install AWSSDK. Go through the errors 1 by 1 and update the syntax. A lot of the client setup parameters for example using SSL are not configurable anymore and are on by default.

**Comment by kenkendk** [comment]
I had a patch for the AWSSDK upgrade lying around, I have added it to the master branch.
@rocifier : are the customizations useful for others?

**Comment by rocifier** [comment]
kenkendk: some of them are, some of them aren't.. for example the UI looks better now. But the main thing I wanted to modify was using existing cloud provider accounts so the user doesn't have to sign up with a cloud provider. This involved quite heavy hacks to the backend modules, for example in S3 I am using a fixed bucket name and a folder which is the username.
