### ISSUE TITLE
Sending backups very slow with 2.0.0.70

### ISSUE THREAD

**Issue by schoenenbach** [duplicati/duplicati#1228]
My system:
Debian 7 Wheezy
Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-8)
Backupserver: Raspberry Pi (SSH) over WLAN 

I tried the stable release 1.3.4 successfully with an upload speed of roughly 20 MB/s.

Now I'm trying the latest release of duplicati 2 (from 2014-11-11) and I only get speeds of about
40 kB/s.

Also I can't pause the upload by pausing the server. Mono is still pushing with 40 kB/s in the background when the server is stopped. Though I don't know if this is a bug or intended.
##

**Comment by rocifier** [comment]
I'm also getting around 40kB/s-100kB/s with version 2, haven't tested 1.3.4. When I pause, it takes at least 30 minutes before the server actually stops. The server also continues on to uploading the next (in my case 50MB) block.

**Comment by kenkendk** [comment]
The 2.0 version uses a new SSH library, which I would expect to perform much better.

The pause issue is adressed in #1088.

I have not speed tested the SSH library, but 40 kb/s sounds dog slow.

**Comment by kenkendk** [comment]
I just tested, I get 6.49 MB/s:
Profiling: Uploaded 798,51 MB in 00:02:03.0201900, 6,49 MB/s

This is on a 1 gbit/s line, but I am not sure which path it takes or if the entire path is 1 gbit/s.
