### ISSUE TITLE
Error: System.Exception: Failed to retrieve file listing: The remote server returned an error: (501) 

### ISSUE THREAD

**Issue by nicks123** [duplicati/duplicati#1230]
Hi, I'm attempting to backup to Windows IIS 8 FTPS however keep getting the error below, Other clients such as FlashFXP etc connect without issue any idea as to the problem.

Error: System.Exception: Failed to retrieve file listing: The remote server returned an error: (501) 
Failed to retrieve file listing: The remote server returned an error: (501) Syntax error in parameters or arguments. ---> System.Net.WebException: The remote server returned an error: (501) Syntax error in parameters or arguments.

Thanks
I
##

**Comment by rdptechs** [comment]
he remote server returned an error: (501) Syntax error in parameters or arguments.
Same Problem Here
