### ISSUE TITLE
torjan

### ISSUE THREAD

**Issue by thorpattersonritz** [duplicati/duplicati#1234]
In performing a daily Hitman Pro scan it noted the duiplicati.GUI.Traylcon.exe as a trojan

**Comment by thorpattersonritz** [comment]
Additional info: I had downloaded it from www.duplicati.com.  In addition to above I used Malwarebytes after hitman did a quarantine. None was reported after doing the quarantine.

**Comment by kenkendk** [comment]
This has happened a few time with different AV vendors (TrendMicro, Norton, etc).

I assume you are getting the alert on a Windows machine?
Can you elaborate on what kind of trojan was reported?

The executable is built on OSX, so it is highly unlikely that it has been infected with a Windows virus.
