### ISSUE TITLE
--store-metadata option ignored

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1247]
Using Duplicati 2.0.0.73 GUI, the "--store-metadata=true" option has no effect, or I don't understand what it's supposed to do.

I've created a test backup, selected a folder with a few files, and ran it. Then I restored them to another folder, and expected them to retain their original timestamps. However their timestamps were the time the restore was performed.

**Comment by kenkendk** [comment]
The restore and general handling of metadata is not implemented until 2.0.0.74.

**Comment by David-Pa** [comment]
I didn't know a newer version was available, because when I checked for updates through the GUI, it said there was no newer version available...

Anyway, I'm with 2.0.0.76 now, and I'm wondering if I have to perform the backup from scratch if I want it to include the metadata?

**Comment by kenkendk** [comment]
When using the newer version, metadata will be added to the backup (you don't need to start over).

The next release is not public because we need to fix a few issues:
https://github.com/duplicati/duplicati/milestones/preview_2.0.0.80

But you can use it anyway: a82e48b1f5a35e8c22164622b280029975b7d703

**Comment by David-Pa** [comment]
Just so you know, I tried with the version you linked to (2.0.0.79), and it's not the case.
New backups have correct file timestamps, but files restored from existing backups still get the current timestamp.
Not sure if you were addressing the unreleased version (2.0.0.80) or the one you linked to (2.0.0.79).

**Comment by kenkendk** [comment]
Yes. I should have been more precise.

When you run the 2.0.0.79 version, it will record existing metadata and append that to the backup data.
Existing backups/filesets do not contain metadata and will not be modified, so you will not get timestamps recorded "back in time", only forward.
