### ISSUE TITLE
Fails to delete local database

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1249]
Duplicati 2.0.0.73 GUI, Windows 8.1, running from the Task Scheduler using elevated privileges.

Attempted to delete local database by clicking the options button near a certain backup, and selecting "Delete local database".

Error:
Failed to delete local data: The process cannot access the file 'C:\Users\David\AppData\Roaming\Duplicati\DFYXDIDYVJ.sqlite' because it is being used by another process.

Notice that event deleting the backup profile does not get rid of the database files! ("DFYXDIDYVJ.sqlite" and "DFYXDIDYVJ.sqlite-journal").
##

**Comment by rocifier** [comment]
I've had this same error I _THINK_ with trying to restore a backup too. As far as I was aware, no backup was currently uploading.
