### ISSUE TITLE
for images and mp3 I never get an incremental backups

### ISSUE THREAD

**Issue by nirmelamoud** [duplicati/duplicati#1255]
every backup for my images folders and my mp3 folders are full backup, not incremental, the system 

the log show:
BackupType      : Incremental
TypeReason      : A full backup is made because the source folders have changed

but nothing really changed in the folders and files  (I do have the ignore timestamp flag set on the backup configuration just in case)

thats 21GB of additional storage I need to pay for weekly (Amazon s3) 

any idea to why ?

**Comment by agrajaghh** [comment]
Are you using duplicati 1.3.4 or 2.0?

**Comment by rocifier** [comment]
Sounds like an older version - 2.0 is imo (just) usable now, so update to that. Note: you will probably have to redo your entire backup.

**Comment by kenkendk** [comment]
The hint is "A full backup is made because the source folders have changed".

For 1.3.x, you need to create a full backup each time you change the source folders.
If you have not manually added or removed source folders (in the GUI or on the commandline), then something happens when parsing the source folders that causes it to think you have changed it.

**Comment by nirmelamoud** [comment]
im on 1.3.4
nothing change on the images folders for sure (im manually adding files and I have not done that for 6 monthes at least)
I added a file to the mp3 folders, is that mean the system will do a full backup of the mp3 folder just because of an additional file ?

any other idea to why the pictures folder did full backup (or because  it part of the same backup process / set it did the whole set of folders) ?

thanks

**Comment by agrajaghh** [comment]
version 1.3 is not maintained anymore, but we are working on Duplicati 2.0 to become stable soon
