### ISSUE TITLE
GUI UpdateDownloadProgressError (Mac OSX 10.9) Latest 2.0 preview

### ISSUE THREAD

**Issue by gmalouf** [duplicati/duplicati#1263]
I run the Duplicati GUI via mono.  Often while a backup is running, the progress bar stops updating and I see the following error in the shell that kicked the Duplicati GUI process off:

Request error: Input string '00.0' is not a valid number. Path 'UpdateDownloadProgress', line 6, position 33

Not sure whether this is a known issue or if anyone else is experiencing it.
##

**Comment by renestach** [comment]
Does it still happen in the latest version?
