### ISSUE TITLE
Backend request: Pogoplug

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1272]
They provide unlimited hosting.
Upload is done through the browser or a client.
I tried to upload an unknown file type through the browser (ie: not picture, video, audio, etc), and it was accepted.
If you need access to an account, let me know and I'll provide you with one.
##

**Comment by kenkendk** [comment]
Not sure how active PogoPlug is, but there is a library here from 2012:
https://pogoplugnet.codeplex.com

**Comment by ts678** [comment]
[Pogoplug unlimited cloud storage service is shutting down on September 28](https://venturebeat.com/2016/09/21/pogoplug-unlimited-cloud-storage-service-is-shutting-down-on-september-28/) (2016).

No seeming need to keep this issue open.
