### ISSUE TITLE
Strange error message when ssh authentication fails, with 2.0.0.73 on Linux (Fedora 21)

### ISSUE THREAD

**Issue by alzadude** [duplicati/duplicati#1279]
Steps to reproduce:
1) sudo yum install mono-basic
2) wget http://updates.duplicati.com/preview/latest.zip
3) sudo mkdir /usr/local/duplicati
4) sudo unzip -d /usr/local/duplicati latest.zip
5) rm -rf ~/.config/Duplicati
6) mono /usr/local/duplicati/Duplicati.CommandLine.exe backup ssh://user@host//mnt/log-backup /var/log

Actual:
1) The following error displayed five times.
"Operation List with file  attempt 1 of 5 failed with message: Argument cannot be null.
Parameter name: s => Argument cannot be null.
Parameter name: s"

Expected:
1) A more helpful error message displayed once only, not five times, explaining that authentication failed as a password was not provided either by --auth-password or AUTH_PASSWORD.
##

**Comment by kenkendk** [comment]
Are you still seeing this? If so, could you try with --debug-output and --verbose ?
That should give me a stack trace so I can see exactly where the "s" argument is used.
