### ISSUE TITLE
Local database should store file paths in a space-optimized fashion

### ISSUE THREAD

**Issue by bks** [duplicati/duplicati#1283]
Using Duplicati 2.0.80, I have a ~75 GB backup set, but the local database is taking up 1.999 GB itself. 

From poking at `%APPDATA%\Duplicati\LRELCBKGXP.sqlite` with sqlite3, it appears that a great deal of that space is used storing the full path for every file in the database. Running `SELECT sum(length(Path)) FROM File;` reports that the actual path strings occupy ~572 MB not counting overhead. Running `DROP INDEX FilePath;` and comparing the `.sqlite` file size before and after indicates that the index uses ~730 M, so the total space cost of the path strings is probably closer to 600 MB in the main table and then the same amount again in the index.

I did a bit more analysis of the paths using python:

``` python
tot, paths = 0, 0
for name in db.execute('SELECT Path FROM File'):
     tot += name[0].rindex('\\')
     if name[0].endswith('\\'): # this File is for a directory
         paths += len(name[0])
print 'Total redundant path components: %d, total unique path components %d' % (tot, paths)
```

It tells me that the leading path components contribute ~418 MB of data for only ~36 MB of unique leading paths; the 418 MB is then doubled by the FilePath index.

So, I suggest optimizing the storage of file paths. One simple way is to partially dematerialize the full path into `dirname` and `basename` parts:

``` sql
CREATE TABLE "Dirname" (
      "ID" INTEGER PRIMARY KEY,

 -- this creates an implicit index, but the UNIQUE constraint is important
      "Dirname" TEXT UNIQUE NOT NULL
);

CREATE TABLE "File" (
 (
        "ID" INTEGER PRIMARY KEY,
        "Dirname" INTEGER NOT NULL,
        "Filename" TEXT NOT NULL,
        "BlocksetID" INTEGER NOT NULL,
        "MetadataID" INTEGER NOT NULL
);

-- If the UNIQUE constraint is really only (Dirname, Filename), it would be nice to take the other
-- columns out of the index. But if not, this is still a lot smaller than before.
CREATE UNIQUE INDEX "FilePath" ON "File" ("Dirname", "Filename", "BlocksetID", "MetadataID");
```

This fairly simple change will probably shrink the local database by 50+%.
##

**Comment by kenkendk** [comment]
Great investigation!

I had considered doing a full split of the path, but that gives very large chained lookups.
Your solution would work with minimal overhead, given that most folders contains more than a single file.

**Comment by rocifier** [comment]
Love it. It would actually probably be more efficient both in storage space and program speed to index a single column which contains a hash. The hash could be custom built in the app to represent a combination of whichever columns need to be included to identify the record as unique. For example, a hash might be computed for Dirname + Filename and stored. When this record is later looked up, a temporary hash is generated eg. md5(Dirname + Filename); and used to retrieve the record from the database.
