### ISSUE TITLE
Absurd warnings since updating to 2.0.0.81

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1287]
This happens with all my backups:

Warnings: [The supplied option ----auto-cleanup is not supported and will be ignored, The supplied option ----compression-module is not supported and will be ignored, The supplied option ----thread-priority is not supported and will be ignored, The supplied option ----all-versions is not supported and will be ignored, The supplied option ----asynchronous-upload-limit is not supported and will be ignored, The supplied option ----debug-output is not supported and will be ignored, The supplied option ----snapshot-policy is not supported and will be ignored, The supplied option ----usn-policy is not supported and will be ignored]

**Comment by kenkendk** [comment]
Is this from the GUI ?

Can you edit the advanced options? Do they contain four ---- marks instead of the two -- they should have?

**Comment by David-Pa** [comment]
Yes, it's from the GUI.

The advanced options contain two -- as they should.
I tried to change them to be without -- at all, but after saving I opened the settings again, and the -- were back.

**Comment by HaraldOnline** [comment]
Here too: Warnings: [The supplied option ----snapshot-policy is not supported and will be ignored]

**Comment by David-Pa** [comment]
I can confirm this issue is resolved.
Thanks!

**Comment by HaraldOnline** [comment]
Me too! Thanks!
