### ISSUE TITLE
Performance Issue - Duplicati 2.0.0.81 - Platform: Windows 2012 R2

### ISSUE THREAD

**Issue by C0ReDuMP79** [duplicati/duplicati#1289]
Hello,
We are using Duplicati 2.0.0.81 on Windows 2012 R2 OS to backup 900K files for a total of 200GB. We decided to keep the default blocksize (100KB). The resulting SQLite database is quite big over 1GB.
We noticed that the file scan during incremental backup operations is slow and getting the file list for restore operations takes also a lot of time (over 15 minutes to get the list of the root folder and more or less the same time to expand every single subfolder).
We made some debug and analyzing the system performance monitor we noticed that Duplicati seems to saturate 1 CPU core during these operations and the all the remaining cores show no load at all (it's a 8 core system). We are not talking about multicore compression but we have the impression that SQLite uses only one core (Single-Thread approach) as described here:
https://www.sqlite.org/threadsafe.html

Is it possible for you to verify this issue and in this case is possible to recompile SQLite to use another thread model?

I don't know if configuring Duplicati 2 with the old-lookup-memory-defaults can help (with a big overhead on memory obviously). Can I try to change this parameter without the need to make again a full backup? I think that debugging correctly this issue can make your great product even better.

Thanks in Advance,
C0ReDuMP79
##

**Comment by kenkendk** [comment]
From what I understand the "threadsafeness" of SQLite refers to being able to perform concurrent operations. That means one thread is updating a table while another is reading. It will not make SQLite utilize multiple cores for executing queries.

Most likely I need to rewrite an SQL query (and some support code) to make the query more effecient.
Can you try starting Duplicati with --log-file=C:\some-log.txt and --log-level=profiling and then list the root folder?

This will create a log file with timing info, so you can see which query is taking so long. If you send me the log entry I will see if I can improve it.

**Comment by C0ReDuMP79** [comment]
Hello kenkendk,
I'm not a developer so I don't know if this can be an idea: is it possible to create a local cached filelist (client side) at the end of any backup job and let the user decide, during the restore job, if he prefer to check the database to build the filelist (more secure way) or work with the local cached filelist (cached in a file)?

Maybe, working that way building the filelist is faster, I don't know if this can be the right direction. I saw some software that gives that possibility, Syncovery for example. I know that Duplicati is different from syncovery. The idea behind the engine of Duplicati 2 is great, I think that it can become the leader solution in block based remote backup.

Thanks
