### ISSUE TITLE
Duplicati 2.0.0.81 / FTP / Test connection / Failed to connect / 227 Entering Passive Mode

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [duplicati/duplicati#1291]
With the current 2.x preview I'm trying to use the 1 & 1 FTP backup for my hosted W2008R2 Server. After entering the connect info I get "Failed to connect: The remote Server returned an error: 227 Entering Passive Mode (195,20,242,37,183,252).".

The folder given in "Path on Server" IS created - so I'm pretty sure I entered the correct login information.

What are the minimum requirements so that duplicati FTP backup will work?

PS: In the meantime I've been able to connect to the backup server using file://\backupXXX.onlinehome-server.info\bak5208YYY\dupli (user / password entered & saved in Windows Explorer). Obviously the server is supporting several protocols.
##

**Comment by renestach** [comment]
I think that there is a connection issue with the remote server. I assume that the remote server was not able to establish a proper connection. A quick search on the Internet shows that a firewall or a high load situation on the server can be reasons for this kind of error.

I myself have no issues running Duplicati via FTP in passive mode.

**Comment by ismaail** [comment]
same issue `2.0.6`

using the **Storage Type: FTP(Alternative)** works fine
