### ISSUE TITLE
Duplicati 2.0.0.81 / VSS Error 8194 in Application Log when using --snapshot-policy=required

### ISSUE THREAD

**Issue by HaraldOnline** [duplicati/duplicati#1297]
When running Duplicati on a virtual *W2012R2* Server using --snapshot-policy=required I consistently get an Event 8194 VSS error logged in the application event log. No error is reported in the Duplicati logs. I'm just not sure whether this error can be safely ignored.

---
Volumeschattenkopie-Dienstfehler: Beim Abfragen nach der Schnittstelle "IVssWriterCallback" ist ein unerwarteter Fehler aufgetreten. hr = 0x80070005, Zugriff verweigert
. Die Ursache hierfür ist oft eine falsche Sicherheitseinstellung im Schreib- oder Anfrageprozess. 

Vorgang:
   Generatordaten werden gesammelt

Kontext:
   Generatorklassen-ID: {e8132975-6f93-4464-a53e-1050253ae220}
   Generatorname: System Writer
   Generatorinstanz-ID: {a57f8196-9141-430d-aa03-0f794f3f4961}

---

PS: I'm getting the same VSS error on a *W2008R2* server system:

Volume Shadow Copy Service error: Unexpected error querying for the IVssWriterCallback interface.  hr = 0x80070005, Access is denied.
. This is often caused by incorrect security settings in either the writer or requestor process. 

Operation:
   Gathering Writer Data

Context:
   Writer Class Id: {e8132975-6f93-4464-a53e-1050253ae220}
   Writer Name: System Writer
   Writer Instance ID: {2fe3e19b-1667-4d44-aa58-950653db9d79}

**Comment by agrajaghh** [comment]
Did you run duplicati with admin privileges?

**Comment by HaraldOnline** [comment]
Yes, I did ... I'm starting Duplicati.GUI.TrayIcon.exe through a desktop link with compatibility setting "Run as Administrator" checked".

**Comment by Fritata** [comment]
I use --snapshot-policy=on, slightly different than "required". It threw the 8194 error at me too. The solution that worked for me was to exclude the faulty VSS writer using the following option:

--vss-exclude-writers={}  - and in your case try 2fe3e19b-1667-4d44-aa58-950653db9d79 inside the parenthesis.

**Comment by HaraldOnline** [comment]
@Fritata Thank you very much for your comment! I'm pretty sure that your suggestion would get me rid of the logged VSS error ...

But for me the question is more why the error occurs in the first place; so I did a little more research (= binging ;) ) and came up with [http://help.remote-backup.com/index.php?/Knowledgebase/Article/View/327/5/eliminating-vss-error-8194-from-event-log](http://help.remote-backup.com/index.php?/Knowledgebase/Article/View/327/5/eliminating-vss-error-8194-from-event-log).

> In general, Remote Backup is not used to backup the files managed by these VSS system writers - so the errors have no impact on the success of the backup. However, Managed Service providers are typically concerned by these recurring error messages and often question whether the backups are actually running properly - since the event is listed as a serious error.

There is also a description of how to use *dcomcnfg* to resolve the security issue that is preventing the vss writers from working in the first place.

Since this issue seems to be more of a general Microsoft / security design "feature" I'm closing it.
