### ISSUE TITLE
Clean log data

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1298]
Both the server database and the backup databases contain log data and they grow indefinetly. 

There should be a server setting for clearing the data as well as a commandline setting. The commandline setting should also have an environment variablle.

**Comment by agrajaghh** [comment]
What do you think about automatically deleting log data older than 30(?) days?
I don't think any user will do this manually...

**Comment by kenkendk** [comment]
I was thinking three weeks, but 30 days sounds better. 

And I agree no user will remember to purge it manually.

**Comment by agrajaghh** [comment]
I guess it depends on the log data, perhaps one week is enough? I read the post in the google groups about the sqlite file. 7.4Gb sounds really impressive! Would be good to know how old this log and how big the backup is I guess...
