### ISSUE TITLE
Compression libraries

### ISSUE THREAD

**Issue by lucatrv** [duplicati/duplicati#1300]
Hi, I have a few comments regarding the compression libraries used by Duplicati, both for zip and 7z formats.

Zip:
I noticed that the included zlib1.dll file is an old version, current version is 1.2.8 (http://www.zlib.net/).
Moreover I wonder if pigz could be used instead of zlib to improve performance (http://zlib.net/pigz/).
Pigz has been ported to Windows:
http://blog.kowalczyk.info/article/4/How-I-ported-pigz-from-Unix-to-Windows.html
I report this only for information, I am not sure if pigz could significantly improve Duplicati's performance (probably only in some cases).

7z:
In my opinion the current C# implementation (managed-lzma) is too slow and requires too much memory. I wonder why not using the 7za.dll library instead, which is available as pre-built binary on sf.net, see for instance the file 7z920_extra.7z at the following link:
http://sourceforge.net/projects/sevenzip/files/7-Zip/9.20/
Another option could be liblzma (also available as pre-built binary: http://tukaani.org/xz/) but I believe it only allows to compress a single file.

Regards
##

**Comment by kenkendk** [comment]
There are two reasons for choosing managed-lzma:
1) It is cross platform
2) A developer (Tobias) implented support for it in Duplicati.

Generally I try to add things that work cross platform, as that makes it simpler to test.
If you (or someone else) would like to add a 7z compression module that wraps 7za.dll, I would happily include it, even if it only works on Windows.

**Comment by lucatrv** [comment]
I certainly agree that Duplicati should be cross platform. I myself run it under both Windows and Linux.

Not to say that I will work on this (I am not sure if I will ever have the time), I would like to ask your opinion about the following proposal:
* Duplicati could actually use the full "7z" library (rather than "7za"), which supports zip and 7z compression and AES encryption (for both formats).
* The "7z" library is available for Windows, Linux and many other platforms (http://www.7-zip.org/download.html), it is very popular and under active development.
* With the "7z" library, several other libraries currently used by Duplicati would become unneccessary: zlib, managed-lzma, SharpAESCrypt, and probably also gpg. These libraries could be removed from the code tree, making it simpler to maintain.

Do you think it would work?
Thanks

**Comment by kenkendk** [comment]
I am sure it could work.

I don't know enough about the API for 7z to guess at how much work it would
be, but I doubt it will be a huge task.

It would not replace SharpAESCrypt as the encryption is more solid when it
is fully decoupled from the file format.

**Comment by lucatrv** [comment]
I agree with you, it is a good idea to keep encryption separate from compression.

I won't probably have time to work on this anytime soon, but I would like to review with you the following points:

* Between SharpAESCrypt and GnuPG, the latter is certainly much more popular, and thus audited and safe. Another very popular and safe option would be OpenSSL. Both GnuPG and OpenSSL are cross platform and implement several ciphers including AES-256. It is known that the key aspect in the implementation of encryption algorithm is to avoid bugs that would make it weak, this is a very difficult task and only few programs are so widely tested to be considered safe. For this reason in my opinion either GnuPG or OpenSSL are intrinsically safer than AES Crypt. Since GnuPG is already integrated into Duplicati, I wonder why AES Crypt should be the default choice instead. If the reason is because it is a library rather than an executable command, then Duplicati could use Libgcrypt instead, which is the library behind GnuPG: http://www.gnu.org/software/libgcrypt/.

* Considering the use of 7z for compression and GnuPG for encryption, for both of them either the shared libraries could be accessed or the executable commands could be called from the C# code. Looking at the code, I understand GnuPG is now run as an executable command, do you think this would be a good solution for 7z as well or would it be preferable to access the shared libraries for both 7z and GnuPG? Calling the executable commands may be easier to implement, but I would like to ask your opinion about possible drawbacks.

**Comment by kenkendk** [comment]
I agree that GnuPG/OpenSSL is more popular, and thus has more code review audit (or at least I hope so!).
But, they are also gigantic projects with countless options and hardware specific optimizations. This increases the chances that there is an insecurity. AESCrypt is very small, and does not have any options. It also runs on all platforms that support the CIL with no extra tweaks. It is simple to deploy updates and monitor changes to the source.

In the past I have seen issues where e.g. the SSH binaries change and break things (i.e. -P vs. -p ). All this is avoided by having a small and very specific component like AESCrypt.

The encryption is done on the compressed archive, so it is simple to do on the commandline (i.e. encrypt infile.zip outfile.zip.aes --password=1234). For the compression it is slightly harder because multiple files are added. If this is implemented with a commandline, you need to either call an update method repeatedly, or use some interface where you can write data to stdin. When reading the files from the archive you have a similar issue with listing the files and providing random access.

A solution that is not particularly efficient is to simply dump files in a temp folder, and on close call the compressor. On decompression you can then extract all files and have easy random access to the files.

**Comment by lucatrv** [comment]
Thank you for the explanation, now I agree the compression tool should be a library while the encryption can be done on commandline. Here are my comments:

* 7z archives can be either solid or non-solid (zip archives are only non-solid). Solid format leads to better compression (all data is compressed as a single stream) but slow random access of compressed data (accessing a file at the end of the archive requires to decompress all data in memory). I noticed that Duplicati uses solid 7z archives, I wonder if this is why it is so slow.

* I had a look at the source code, I could not find exactly were the parameters of the gpg commandline are defined, but I wonder if compression is disabled. Gpg by default compresses data before encryption, which is unnecessary if the data is already compressed. Here is the gpg command for AES encryption without compression:
gpg --symmetric --cipher-algo AES256 --compression-algo none file.txt

Note: in my opinion having both gpg and AEScrypt available is unnecessary, after reviewing the two projects I choose gpg for best safety of my data.

**Comment by renestach** [comment]
As far as I can see, the original 7z SDK does not support LZMA2 for C#. This means, all compression is single-threaded. The current implementation we have in multi-threaded (LZMA2) which is a huge performance advantage especially as the C# implementation is slower than the original C++ version.

Furthermore, this seems like a very technical issue. But I do not see anything the users would benefit from.

**Comment by lucatrv** [comment]
The problem for the user (at least for me) is that the current 7z implementation is ridiculously slow and requires lots of memory. I was trying to find a better solution, but if that is not good I can live with zip.

**Comment by renestach** [comment]
I think we already pushed the 7z implementation to its limits. 

Fact is, that LZMA/7z has better compression than zip. But that requires a lot more CPU power. A lot! As Duplicati is cross-platform in C# that power must come from managed code which is unfortunately slower than a native implementation in C or C++. To achieve a better compression, LZMA furthermore holds a huge dictionary in memory. Better compression at the cost of CPU (a lot) and memory (also very much).

To cope with that we implemented LZMA2 and more optimizations. First, our 7z implementation is multi-threaded. It uses multiple CPU cores which speeds up the whole compression by the number of cores used. 8 cores, 8 times faster. But this also means, that the threads require 8x the memory. Second, we decided to write compressed data (mp3, H.264, etc.) directly into the archives without compressing them. 

As a result of that I was able to perform a backup with LZMA/7z at the same time as a backup with zip. I required much more CPU power (4 cores) and memory. But is also resulted in 15% smaller backups.

If you do not need that extra 5-25% file size reduction, just use zip. If you need it, you have to pay for it (CPU, RAM, speed). 

We will not implement native libraries in C or C++ to improve the speed of LZMA. But if anyone volunteers to do it, and is able to beat the current performance, please get in touch with us.

**Comment by lucatrv** [comment]
I might be wrong but it seems to me that Duplicati already uses other native dll's, like SQLite and zlib. If this is true, I do not see why LZMA should be implemented in C# instead. I made some tests and the current LZMA implementation in C# seems slower than the native binary. Moreover it requires more memory, which does not seem to be unallocated at the end of the backup.

I agree with you that if you do not need extra compression you can just stay with zip and be fine. However I would like to add that the comparison you did between 7z and zip is not very fair. First of all as you said you are comparing a multi-threading implementation (LZMA2) with one using a single thread. However, it is possible to parallelize zlib, either with multi-threading (see http://zlib.net/pigz/) or just running more than one process at once (concurrent compression of archive files). Moreover, you are comparing zlib compressing all files with managed-lzma compressing only compressible files. It would be possible to put zlib in same conditions simply dividing compressible and incompressible files in separate archives (sorting them out based on the extension). The same strategy could be used of course also with the native 7z dll. Comparing managed-lzma with native 7z dll and zlib in same conditions shows in my opinion that managed-lzma is slower than the others.

Of course Duplicati is already a very good software with zlib alone. However implementing the two strategies above (in particular separating compressible and incompressible files in different archives) would make it even better. In this case I believe the native 7z dll would prove out to be much faster than managed-lzma.
