### ISSUE TITLE
Mono-related error message displayed, with 2.0.0.81 on Linux (Fedora 21)

### ISSUE THREAD

**Issue by alzadude** [duplicati/duplicati#1304]
I recently upgraded from 2.0.0.73, which does not give this error message, with the same steps performed. So it would appear something has changed between these versions?

Steps to reproduce:
1) sudo yum install mono-basic
2) wget http://updates.duplicati.com/preview/latest.zip -O duplicati-2.0.0.81.zip
3) sudo mkdir /usr/local/duplicati-2.0.0.81
4) sudo unzip -d /usr/local/duplicati-2.0.0.81 duplicate-2.0.0.81.zip
5) mono /usr/local/duplicati/Duplicati.CommandLine.exe help

Actual:
Missing method .ctor in assembly /usr/local/duplicati-2.0.0.81/Duplicati.Library.Main.dll, type System.Runtime.CompilerServices.ExtensionAttribute
Can't find custom attr constructor image: /usr/local/duplicati-2.0.0.81/Duplicati.Library.Main.dll mtoken: 0x0a000113
An exception was thrown by the type initializer for Duplicati.Library.Main.Options

Expected:
Help displayed
##

**Comment by archfrog** [comment]
You might want to try the Mono distribution from http://www.mono-project.com.  It is at version 3.12 and Duplicati APPEARS to work fine with it.  You probably need to uninstall your current Mono and then follow the directions on the Mono site to download the latest and greatest Mono.  I have only tried a few commands, but the command-line tool and the server both start up just fine.

**Comment by alzadude** [comment]
Hi there, 

Thanks for the suggestion, I will give it a try. I didn't realise the Mono package for Fedora were for an older version, then I found this: https://fedoraproject.org/wiki/Changes/Mono_3

Seems I have to wait until for Fedora 22 for version 3 to be bundled! In the meantime I guess I'll have to use the one from mono-project as you suggest. I'll give it a go and report back.

Thanks :)
