### ISSUE TITLE
Restore Dialog with "Umlaute" does not show Files and Folders

### ISSUE THREAD

**Issue by gkruschina** [duplicati/duplicati#1305]
If there is a folder with contains german "umlaute"  the restore dialog does not show the containing files and folders. So you cannot expand the view of such a folder and further selection is not possible.
I have tested this with 2.0.0.82- 2.0.0.82_preview_2015-02-15.
##

**Comment by huste** [comment]
I can't verify that. I have a folder called "Datenübernahmen" in my backup set and it appears as t should in 2.0.0.82- 2.0.0.82_preview_2015-02-15. That is for backups created with 82 nad for backups created with 81.

**Comment by gkruschina** [comment]
I have also created my backups with version2.0.0.82- 
2.0.0.82_preview_2015-02-15. The folder "Müller" appears at the root of 
the backup set, but
i cannot expand this to go down in this selection.
This is the same behaviour on all folders with "Umlaute".
huste schrieb:

**Comment by gkruschina** [comment]
What I forgot: The restore works. This is not the problem.
huste schrieb:

**Comment by huste** [comment]
You're right. Clicking on the expand arrow shows the "please wait" indicator but does not open the tree.

**Comment by Pectojin** [comment]
This appears to have been resolved at some point.
<img width="248" alt="screen shot 2018-02-28 at 22 13 54" src="https://user-images.githubusercontent.com/1561484/36813388-b1226014-1cd4-11e8-8b3d-8ae00abe8f21.png">
