### ISSUE TITLE
Duplicati 2.0 no longer compatible with Windows XP

### ISSUE THREAD

**Issue by masgo** [duplicati/duplicati#1310]
Since the 2.0 version requires .NET 4.5 it is not compatible with windows XP (see http://blogs.msdn.com/b/dotnet/p/dotnet45xp.aspx ).

I know that XP is old and no longer maintained by Microsoft. Therefore I do NOT request to make it compatible with it XP. I just request to:

a) State clearly on the duplicati Homepage (i.e., here: http://www.duplicati.com/howtos/how-to-install-and-run-duplicati-2-0-preview ) that it requires Vista or higher.

b) Provide a better error when running the program under XP. One that just openly says that i will not work. (Right now one gets a message that .NET 4 is required, after this is installed it requests for 4.03, and after this is installed it requests for 4.5 which is not available for XP)

**Comment by lucatrv** [comment]
I cannot test it because I do not have Windows XP, but I wonder if you can use Mono instead.

**Comment by renestach** [comment]
a) I just changed the website and added a hint to .NET 4.5

b) That is a standard message that comes from the Windows system. Unfortunately, we cannot change it :-/

**Comment by Athep** [comment]
I found a workaround:

1. Install duplicati-2.0.0.79_preview_2015-01-19.zip
2. Use the auto update feature  to update to the latest version.

It works for me, both on XP and SBS 2003 server.

**Comment by pbhj** [comment]
Ah, Athep's workaround for installing 2.0.0.79 works for me on XP. However if I update to the latest version which is now 2.0.0.87 then the program will no longer run. See http://alicious.com/duplicati-google-winxp/ for details (including error message text).

**Comment by kenkendk** [comment]
@pbhj Have you tried installing Mono and running it with Mono instead?

**Comment by pbhj** [comment]
@kenkendk I'm just looking at this again to see if there were updates - I haven't tried Mono, how would I run the app using Mono? Is it just a case on installing and running the TrayIcon.exe file and the app uses Mono automatically, or is there more to it? Thanks.

**Comment by FootStark** [comment]
@pbhj: Did you start the .exe with mono or just by clicking it?
To use mono, you have to call like `mono Duplicati.GUI.TrayIcon.exe`

**Comment by nerijus** [comment]
I've installed mono on Windows 2003, but running mono Duplicati.GUI.TrayIcon.exe just exits (I can see mono process appearing and disappearing in Task Manager).
mono Duplicati.CommandLine.exe works.
