### ISSUE TITLE
Duplicati 2.0.0.82 / Processing 123456 files ... / OneDrive

### ISSUE THREAD

**Issue by HaraldOnline** [duplicati/duplicati#1312]
Currently a Duplicati job is copying < 40 GB from a mapped network drive to OneDrive. According to *Show Log ... / Live (Profiling)* Duplicati is still working but it's been showing *"Processing 123456 files"* for quite a while. Still hoping that backup will work but the message could be improved ... ;)

(Windows Server 2012R2, current Firefox release)

![duplicati processing 123456 files](https://cloud.githubusercontent.com/assets/2997561/6381290/51665a8c-bd40-11e4-82c4-89c78636dec5.png)

**Comment by renestach** [comment]
I think this is fixed in the code already.

**Comment by renestach** [comment]
Did not see "Processing 123456 files" again, so I am closing this now.
