### ISSUE TITLE
82: minor UI issue: Display of multiline edits: no line breaks (like souce data filters)

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1313]
In 82, I have some backup jobs with source data filters. They work properly, but they are displayed on a single line. The hint still says, "Enter filters, one per line".
The problem is: When I press Enter in Firefox, there is no line feed but a space. So I can't enter filters one per line.

Exporting the backup job to a file produces the same result as in 81, with several items in the Filters-array.
![zwischenablage01](https://cloud.githubusercontent.com/assets/9739281/6408934/c0d8f60a-be5c-11e4-9ee5-79f511f00c74.png)

The same is true for the backup options.

**Comment by agrajaghh** [comment]
I got the same problem in the advanced options textfield
