### ISSUE TITLE
Problems with Restore from Target 2.0.0.82

### ISSUE THREAD

**Issue by davidwbryant** [duplicati/duplicati#1314]
Testing by running nightly scheduled backups with multiple backup jobs to OneDrive on Windows 7.

Restoring selected backups on a different Windows 7 system - i.e. disaster recovery scenario.

Restore using the --all-versions=true option doesn't work as expected as noted in #1308 

When --all-versions is false, restore of the earliest dated version of a given backup restores the files in the same hierarchy as when they were backed up, however if subsequent backups (with just the changed files) are restored over the original restore, the new files are restored to the root of the restore location rather than to their correct place in the hierarchy.

A more alarming problem is that some backups fail to load altogether. The restore fails after the database is built and may fail saying that it can't get the list of backup dates, can't get the list of files, or once saying "Cannot start restore while backup is active" (it wasn't).

When a backup won't load on the second system it can still be restored via the backup job on the original system.

Typically when another day has passed and the backup job has run again it will be possible to restore it on the second system. 

I haven't been able to establish any pattern to this yet, or any way to repeat the problem.
##

**Comment by agrajaghh** [comment]
seems fixed to me on 2.0.0.85 although I don't know which commit could have fixed it...

**Comment by davidwbryant** [comment]
Files still don't necessarily get restored to the right place. This is true whether --all-versions is true or false.

This is repeatable with a backup job that contains an original backup plus a subsequent backup with only one file changed. I'm wondering if this is specific to the case where a backup contains only a single change. Will do some more tests.

I haven't seen the problem where the backup completely fails to restore since 2.0.0.85, but this problem came and went in any case, so it's too early to be sure.

**Comment by davidwbryant** [comment]
The problem with files being restored to inconsistent locations when using Restore from Target only affects the "Pick a new location" case.

If restoring to "Original location" the files are restored to where they came from.

This is still a major problem because "Pick a new location" will be used for most regular testing to check that a backup process is working correctly, and also when files have to be restored onto a different system.

Both the --all-versions=false and --all-versions=true cases are affected.  

Where the modified copies  get restored to depends on which other files were backed up in the same backup job run.

One expects the most recent version of a file to be restored in the place in the hierarchy where it originated, whereas one typically finds the oldest version of the file in its original place, and modified versions at various levels in the tree of restored files.

It is generally possible, although time consuming, to sort this out after the restore, but if the tree being backed up contains files of the same name at different levels of the tree, data may be lost. It is also very easy not to realise that you are not looking at the most recent version of the file as the latest one can be restored many directory levels away.

This appears to be a design issue rather than an implementation bug.

The backup seems to store the full path (on the original system) to the files that were backed up. It doesn’t seem to know which component in that path was the first to get backed up.

If a given backup run contains files at the top level of the tree that was being backed up, the files get restored in a tree that mirrors the tree that was backed up. If the backup run only contains files from a leaf directory, those get restored directly into the restore location without their path prefix.

If you want to restore to the state at a given date by restoring multiple backups over each other in sequence it doesn’t work properly because the individual restores are mis-registered against each other.

For example:

Create C:\users\d\documents\files\Test1. The archive folder contains existing folders.
Add "Test1.txt" and "Test1 - Copy.txt” in Test1

Create a new backup job and select C:\users\d\documents\files as the source
Run backup

Create target folder for restore E:\RT
Restore from Target earliest backup, —all-versions=false
Restore file & folders dialogue shows C:\Users\D\Documents\Files at the top level and various sub-folders including Test1
Select Test1 only
Pick restore folder as E:\RT, Select Overwrite, and Restore read/write permissions
Restore

E:\RT contains Test1.txt and Test1 - Copy.txt (no Test1 folder)

Modify a file under C:\Users\D\Documents\Files\AnotherFolder and add a sub-folder zz containing modified "Test1.txt" and "Test1 - Copy.txt” below Test1
Run Backup

Restore, checking top-level check-box, E:\RT now contains

AnotherFolder
     AFile
Test1
     zz
          Test1 - Copy.txt
          Test1.txt
Test1 - Copy.txt
Test1.txt

(Note that the original Test1 - Copy.txt and Test1.txt appear in the top level folder and not under Test1 folder)

Add sub-folder yy under Test1, containing a modified Test1.txt
Run backup

Restore checking top level check-box against c:\Users\D\Documents\Files\Test1, E:\RT contains:

AnotherFolder
     AFile
Test1
     zz
          Test1 - Copy.txt
          Test1.txt
yy
     Test1.txt
Test1 - Copy.txt
Test1.txt

(yy belongs under Test1)

**Comment by kenkendk** [comment]
The target folder is not cleared before restoring. 
You can restore files into an existing folder, which is why you can choose overwrite or not.
From your data it seems that you are repeatedly restoring into the same folder, which leaves things around and confuses.

When restoring to a new location, Duplicati finds the shortest path that can be used to restore the selected files and the structure that represents it. Thus, if you select the folder "Test1", the files can be restored without the need for the "Test1" and "zz" folders. If there were a file in the "Test1" folder, then the "zz" folder would also be needed to correctly reflect the structure.

I can see that if you explicitly choose the "Test1" folder, you would expect that one to be restored. The current file picker is not all that nice, so it only selects "leaves", and that means the files you have selected, and not the folders.

Does that explain the behavior that you describe?

**Comment by davidwbryant** [comment]
Apologies for the long delay in replying.

I think we are at cross-purposes here. What I wanted to do was to be able to restore all of the data from a backup into an empty folder.

My first attempt was to use the GUI to do a restore from target with the advanced option flag --all-versions=true. This restored only the few files that had changed and which were included in the most recent backup, rather than all the files that were present at the time that the last backup was made.

The process I was describing above was an attempt to restore all of my files by restoring each backup in turn beginning with the earliest one into the target folder.

I'm guessing that I just don't understand correctly  how I'm supposed to do a complete restore to an empty folder.

**Comment by kenkendk** [comment]
--all-versions is not meant for use with the GUI.
It is used to find find one or more files when using the LIST command on the commandline.

To restore into an empty folder, you only need to select the top-level entry when restoring.
It should then include all files found in that backup, regardless of them having any recent changes.

**Comment by davidwbryant** [comment]
Using the latest version, downloaded a couple of days ago, I just tried 
a  GUI restore of a folder with lots of sub-folders, containing hundreds 
of files and many backups over several months.

When setting up the restore from target I see a tree with the top level 
folder and all the sub folders as expected. I  checked only the top 
level folder, and left the drop down for selecting backups alone, so 
that it was showing the date of the most recent backup.

Only two files were restored, one at the top level and one in a sub-folder.

The back-end is OneDrive in this case.

I haven't found anything I can do to restore an entire file hierarchy 
using the GUI. Somebody raised the same thing in the forum, which was 
where the --all-versions suggestion came from.

Apologies if I'm being dense, but I just can't see what I'm doing wrong.

Since my last post I figured out that I can do a full restore using the 
command line, so not actually a huge issue for me any more.

**Comment by ts678** [comment]
There are a lot of parts to this, some of which have already been explained, such as [--all-versions](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#all-versions) not being related, and paths being compressed to a minimum on a `Pick location` restore, interfering with restore build-up from hand-selected files at different times.

2.0.1.39_canary_2017-01-08 seems to have added an option which will allow such restores to land in correct tree. Current help text:

```
  --dont-compress-restore-paths (Boolean): Disables path compression on
    restore
    When restore a subset of a backup into a new folder, the shortest possible
    path is used to avoid generating deep paths with empty folders. Use this
    flag to skip this compression, such that the entire original folder
    structure is preserved, including upper level empty folders.
    * default value: false
```

> Since my last post I figured out that I can do a full restore using the command line, so not actually a huge issue for me any more.

If anyone thinks this issue should stay open, please test on current software and point to a part. One can also always file new issues.

**Comment by warwickmm** [comment]
I'm going to close this since it is so old and large in scope.  Please open a new issue with updated details if these problems still exist.
