### ISSUE TITLE
Scheduled backup stops working 2.0.0.82

### ISSUE THREAD

**Issue by davidwbryant** [duplicati/duplicati#1317]
A scheduled backup has been running nightly without problem for about two weeks, backing up 664MB of data that has a low rate of change.

The backup runs on WIndows 7 and backs up to OneDrive.

Now the backup has stopped working with "The remote server returned an error: (500) Internal Server Error."

I can't see any way to recover from this and get the backup running again.

I can recover the data from the earlier backups by using Restore from Target on another Windows 7 machine.

I can create a new backup of the same data to another target folder on OneDrive, and that has backed up (once so far) ok.

The error log shows:

Operation Delete with file duplicati-i297b5b7de76c4d398ad2cfa1933c2c64.dindex.zip.aes attempt 1 of 5 failed with message: The remote server returned an error: (500) Internal Server Error.
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()

**Comment by renestach** [comment]
This could be the same issue as #1299. If so, it should be fixed in the latest version. Please verify.

**Comment by davidwbryant** [comment]
It's not the same issue, as #1299 was a response timeout on large backups whereas this one was an internal error returned when trying to delete files on a small backup.

That backup is however working again with 2.0.0.85. Not sure if something in the later Duplicati version has fixed it, or whether it was some kind of glitch at the OneDrive end, but in any case I think this can be closed.

**Comment by davidwbryant** [comment]
It is also [possible to get spurious write permission errors with OneDrive using the OneDrive web GUI to upload. I believe this is what I was seeing here, but via the OneDrive API
