### ISSUE TITLE
Need to force FULL backup to run only on Fridays

### ISSUE THREAD

**Issue by izabelcka** [duplicati/duplicati#1318]
How can I schedule one task to do a FULL on friday night 10PM and incrementals on all other days at 10PM.

Thanks.

**Comment by izabelcka** [comment]
The rest of the days are incrementals.

**Comment by agrajaghh** [comment]
There is no such thing as full and incremental backups anymore with duplicati 2.0

see: https://sites.google.com/a/duplicati.com/duplicati/news/theduplicati20storageengineishere

**Comment by izabelcka** [comment]
I am using version 1.3.4.

**Comment by renestach** [comment]
You need to play with the full/incremental settings. If you run backups every day, you could advice Duplicati to make a full backup every 7 days or to keep 7 versions before another full backup is done.

**Comment by izabelcka** [comment]
Ok. I actually did a test: I run an incremental each day besides friday. And I run another task, a full each Friday. 

I make sure their target folder is the same.
I did a restore using the incremental task, and voila, I was able to restore everything.
