### ISSUE TITLE
Support for TLSv1.2

### ISSUE THREAD

**Issue by zalethul** [duplicati/duplicati#1320]
Hello,

i tested duplicati 2.0.0.82- 2.0.0.82_preview_2015-02-15 with Apache/2.2.22 and would like to get rid of TLS1.1 and TLS1.0.
I am no .NET expert but from the documentation it says:

"SslProtocols Enumeration"
"Default	Specifies that either Secure Sockets Layer (SSL) 3.0 or Transport Layer Security (TLS) 1.0 are acceptable for secure communications"

Could you change that to also accept TLSv1.2?

https://msdn.microsoft.com/en-us/library/system.security.authentication.sslprotocols(v=vs.110).aspx

Best

**Comment by kenkendk** [comment]
Only Microsoft can change those. But it now shows TLS1.2 as well.
