### ISSUE TITLE
Wrong Update offer

### ISSUE THREAD

**Issue by SoaresJunior** [duplicati/duplicati#1322]
Is being offered update even with a newer version running.
I´m running 2.0.0.85_2015-03-07 and is beeng offered uptade to 2.0.0.84_2015-02-27.

TIA
Soares Junior

**Comment by huste** [comment]
Same here.

**Comment by agrajaghh** [comment]
There were some changes regarding the autoupdate. Please reopen if you encounter this again with the new versions.
