### ISSUE TITLE
0Auth2 for Google Drive

### ISSUE THREAD

**Issue by gfalgiano** [duplicati/duplicati#1323]
Google has a message saying that they are moving to 0Auth2 and that the current way Duplicati connects to Google Drive is not secure.

Will Duplicati move to this new authentication method?

Backing up to Google Drive can be very beneficial as they offer 1TB free for chromebook users.

**Comment by TechGuy2000** [comment]
I would also very much like to see support for OAuth2 support added for Google Drive. I would also like the scope of the authorization to be limited to the Application Data Folder (see: https://developers.google.com/drive/web/scopes), or at least to allow the user to select that option during the authorization process. My Google Drive setup involves terabytes of data of various kinds, including backups. I do not want to authorize any apps to have full access to the contents of my Google Drive.

**Comment by kenkendk** [comment]
This is tracked in #1347, and the answer is: Yes, Duplicati is moving to OAuth2.
