### ISSUE TITLE
Feature Request - Add support for Tencent cloud storage

### ISSUE THREAD

**Issue by gfalgiano** [duplicati/duplicati#1325]
tencent offers 10TB, yes TB of free cloud storage for users. They now have an API to use their storage with 0AUth.

This cloud provider is perfect for the Duplicati project because they offer lots of storage and since they are hosted in China, people may have security concerns. Duplicati's encryption helps to alleviate that issue. I think it can be a great solution for backing up high capacity files/folders that don't have any personal security risk, such as your HD movie collection, Gopro videos, etc. Basically things that take up a lot of space, that you want to have offsite protection for, but you don't care who has access to it (worse case scenario).

If you were to implement this, I would backup my 7.5TB movie collection to Tencent and my more personal files to Google Drive, all with Duplicati's encryption of course :)

Here is a link to their API:
http://www.weiyun.com/api.html

A link to get the 10TB free storage if you are interested:
http://www.1mtb.com/how-to-get-10-tb-free-online-cloud-storage-from-tencent-weiyun/
##

**Comment by hrez** [comment]
I'd like to add my vote for this feature request.

**Comment by Fr0stbyte5** [comment]
This is two years old now, and the "http://www.weiyun.com/api.html" link now redirects to the main page, which is in Chinese.  Did they pull their API, which would kill this feature request?  That would be a bummer.
