### ISSUE TITLE
Recreate DB broken / takes forever v2.00.85

### ISSUE THREAD

**Issue by Simpelton** [duplicati/duplicati#1328]
A recreate DB takes very long (or does not finish at all) after the DB has been deleted. Not sure how to qualify if the recreate was successfull - should there be any log message indicating this?
- Web UI states "Recreating database"
- Minor local disk and network activity by DuplicatiServer
- Harmless CPU (15% on a Quad Core CPU)
- Takes more than a day to finish. Due to duration and missing success log entry, can't tell how long exactly
- Live log fires a bunch of "useless" data (see below)

"
14.3.2015 10:02:55 Starting - ExecuteScalar: INSERT INTO "Metadataset" ("BlocksetID") VALUES (?); SELECT last_insert_rowid();
14.3.2015 10:02:55 ExecuteScalar: INSERT INTO "Metadataset" ("BlocksetID") VALUES (?); SELECT last_insert_rowid(); took 00:00:00.001
14.3.2015 10:02:55 Starting - ExecuteScalar: SELECT "ID" FROM "File" WHERE "Path" = ? AND "BlocksetID" = ? AND "MetadataID" = ?
14.3.2015 10:02:55 ExecuteScalar: SELECT "ID" FROM "File" WHERE "Path" = ? AND "BlocksetID" = ? AND "MetadataID" = ? took 00:00:00.000
14.3.2015 10:02:55 Starting - ExecuteScalar: INSERT INTO "File" ("Path", "BlocksetID", "MetadataID") VALUES (?,?,?); SELECT last_insert_rowid();
"

---
- Backup target is local NAS via SMB share
- Source running Duplicati is Windows8.1
- Volume ~350 GB in backup destination

Might be related to this
https://groups.google.com/forum/#!topic/duplicati/fBXKroSx6NE
##

**Comment by VidalDuval** [comment]
I may be experiencing a similar issue (feel free to create a new thread if it is not the case). A backup made with Duplicasti 2.0.0.85 running on Windows 7 is stored on a Ubuntu 14.04.02 file server accessed by SSH. I'm trying to restore the backup on Linux Mint 17.1. At the beginning of the restore I see a progress bar, and after a while this progress bar becomes white (ie blank, invisible), After 24 hours I'm still at the "Building local database" prompt.

This is a 113GB backup. CPU usage is high (~100%), memory not so much (~68MB used by mono). I have a dup-167b0afa-165e-474e-86e6-010fe2fda8b2 (1.6GB) and a dup-167b0afa-165e-474e-86e6-010fe2fda8b2-journal (68.1MB) file in my (custom) tmp folder that both seem to be updated every few seconds.

**Comment by mdsmdsmds** [comment]
I confirm. Same situation. Download forever but no real recreation.

**Comment by Pectojin** [comment]
Issue 2889 seems to encompas the spirit of this issue well and gets the most attention of the two, so I'll close this one so we just have one to watch.
