### ISSUE TITLE
Filter setting to exclude locked files from backup

### ISSUE THREAD

**Issue by masgo** [duplicati/duplicati#1331]
In my backups I often encountered files that can not be backed up. Like this one:
...\http___download_eclipse_org_recommenders_models_luna_\\**write.lock**
It is obvious that this is just a lock file from eclipe and I do not need to back it up. 

It would be really nice if Duplicati provided an interface similar to git tools to ignore such files. So one could click on the Duplicati error message and get a dialog similar to this:
![ignore-gui](https://cloud.githubusercontent.com/assets/1336992/6666364/e2ee90ee-cbe3-11e4-8fdb-ab0dc5a0175a.png)
This would then add an ignore entry to the backup.

**Comment by kenkendk** [comment]
Is this really for 1.3.x ?

For 2.0, you can add a filter:
-*.txt

To exclude all .txt files.

The lock files can be excluded with:
-*\write.lock

**Comment by masgo** [comment]
I meant 2.0, but I am not able (or capable?) to set a label.

Setting a filter as text is what I have done. But having a GUI as proposed would be even better. This issue should be considered as an enhancement, not a bug.

**Comment by GitHubror** [comment]
In 1.3.4 there is a property page in the UI where filters are defined.
![duplicatifiler](https://cloud.githubusercontent.com/assets/12608635/7810263/bfcb1ade-03a0-11e5-9ff6-981a69f4c065.PNG)
I think the issue can be closed.

**Comment by masgo** [comment]
As said in my previous comment, the issue is about the 2.0 version, but I can not change the label accordingly. 

The solution from 1.3.4 is much better then what is available in 2.0; so having this would be an improvement.

**Comment by renestach** [comment]
We are not convinced about the benefit of this feature. What could happen:

- A user gets notified that a file was locked and not included in the backup
- The user will exclude locked files from the backup and won't get notified about issues with locked files anymore
- Other files arelocked and not included in the backup. The user will never know about this.
- One day the user needs to restore files and notices that many files are not available in the backup. 
- Those user will never know why the files are missing and blame a bad backup software for this.
