### ISSUE TITLE
error restoring local db from remote storage: "System.InvalidCastException: Specified Cast is not valid"

### ISSUE THREAD

**Issue by sneaker2** [duplicati/duplicati#1334]
Hi, after deleting the localdb and trying to restore it because of errors when backing up I get the following error using 2.0.0.85 after a number of files have been downloaded:

2015-03-21 08:52:02Z - Error: Terminated with error: Die angegebene Umwandlung ist ungültig.
System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   bei System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
   bei Duplicati.Library.Main.Database.LocalRecreateDatabase.<GetMissingBlockListVolumes>c__Iterator1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   bei Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   bei Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal()
   bei Duplicati.Library.Main.Operation.RepairHandler.Run()
   bei Duplicati.Library.Main.Controller.<Repair>m__1(RepairResults result)
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)

**Comment by haweig** [comment]
I face the same issue with one of my databases. I tried to recreate / repair the DB multiple times.
