### ISSUE TITLE
restoring backup that has never run breaks restoring for all

### ISSUE THREAD

**Issue by m2tek** [duplicati/duplicati#1336]
When I try to restore backup that has never run, the webpage shows some js alerts and doesn't let me restore any other backup. Only refreshing helps.

How to reproduce: 
1. Create two backups, let the first one run to completion and disable the schedule in the second one so it doesn't upload any data. 
2. try to restore the second backup. It should display empty resotre dialog. Clicking next produces js alert with some errors in console.log 

``` javascript
Cannot read property 'jstree' of undefined
on following line in restoredialog
var tr = strees[t].jstree(); (line ~520)

and : 
GET http://127.0.0.1:8200/control.cgi?action=list-backup-sets&id=4 500 (Error)
```

 Nothing to do here, close. 
3. try to restore the first backup. The website shows js alert with text:

```
Failed to get list of backup times
```

console.log

``` javascript
Uncaught TypeError: Cannot read property 'Time' of undefined
on following line in restoredialog: (line ~588)
var latest_group = $('<optgroup></optgroup>').attr('label', 'Newest - ' + $.timeago(data[0].Time));
```
##

**Comment by Pectojin** [comment]
No longer produces errors. Just loads the restore window with no entries to restore from.
