### ISSUE TITLE
Duplicati 2.0.0.85: GUI-login: Error message "Request Queue is full"

### ISSUE THREAD

**Issue by umgfoin** [duplicati/duplicati#1339]
A backupjob is running in context of "nohup mono DuplicatiServer.exe &"

Trying to open GUI
http://127.0.0.1:8200

Instead of the login-screen, page with message "Request Queue is full" is displayed.
No access possible, Server kill required.

Duplicati 2.0.0.85- 2.0.0.85_preview_2015-03-07

mono --version
Mono JIT compiler version 3.12.1 (tarball Tue Mar 10 11:06:38 UTC 2015)

uname -a
Linux 2.6.32-042stab104.1 #1 SMP Thu Jan 29 12:58:41 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
##

**Comment by JonMikelV** [comment]
I know this is closed, but I thought I'd mention this just happened to me with 2.0.3.12 in a Docker container. 
 Restarting the container resolved the issue.
https://forum.duplicati.com/t/request-queue-is-full-browser-message/5143?u=jonmikelv

**Comment by DesktopMasters** [comment]
Yeah this just happened to me running Duplicati as a local service.  Waiting for the job to finish so I can restart the service.
