### ISSUE TITLE
Warning: Invalid Name

### ISSUE THREAD

**Issue by TechGuy2000** [duplicati/duplicati#1345]
I am running Duplicati 2.0.0.85- 2.0.0.85_preview_2015-03-07 under Windows 7, and I am receiving the following warning:
Warnings: [Failed to process path: D:\1 - ZZ Archive\1 - MY DOCUMENTS\Misc\Website (move to personal laptop)\Backups\Website Backups\2014-07-08 - testalphabackup.com archive\testalphabackup.com\articles\pdf\Research Article, Network Security and Testing, 12 RE. V. 333. 4935 (2015) [Scanned].pdf => Invalid name.
Parameter name: name]

The complete path and filename is 260 characters, which I understand to be equal to the Windows 260 character limit. See: http://windows.microsoft.com/en-us/windows/file-names-extensions-faq#1TC=windows-7

Thanks!
##

**Comment by Pectojin** [comment]
Identical to #1379, so I just picked one.
