### ISSUE TITLE
to long folders chain in google drive

### ISSUE THREAD

**Issue by miriampl** [duplicati/duplicati#1346]
Hi there

I don't know how it work but i have a google drive pro vestion and i already have a 10Tb of data and when i whan't to start bacup - create a backup i get a silly bug. it say's :
Connection Failed: There are multiple folders named "xxxxxxxxxxxxxxxxx@ssdafasdf.com/fsdalflsdfkjalsdf/alsdkfjalsdfjk/lasdkfjalsdkfj/lsakdfjlasfdkj/lsadkfjlsdafkj/alsdfkjlasfkdj", please rename them amnually

WTF ? why his checking what's on google drive. How to point a location of my backup folder on the google drive ?

I have try the 1.3.4 and 2.0 version all with the same error.

**Comment by kenkendk** [comment]
That error is caused by the lookup method for finding folders with the Google Docs API.
This is solved in the new Google Drive backend, being tracked in issue #1347
