### ISSUE TITLE
communication with SSL/TLS server without SSLv3

### ISSUE THREAD

**Issue by ulicky** [duplicati/duplicati#1350]
Hi, if you have server with secure communication, but where server have SSLv3 disabled (enabled only TLS) communication with it is failing. It does not matter if it is HTTPS, FTPS, SMTPS. My current problem is with SMTPS, but it needs to be repaired everywhere.
It is related how .NET FW version enumerate security protocols.

http://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5
http://stackoverflow.com/questions/26389899/how-do-i-disable-ssl-fallback-and-use-only-tls-for-outbound-connections-in-net
https://msdn.microsoft.com/cs-cz/library/system.net.securityprotocoltype%28v=vs.110%29.aspx

**Comment by ulicky** [comment]
Maybe solving this issue could be way to solve this https://github.com/duplicati/duplicati/issues/1341 issue too.

**Comment by laurensb** [comment]
Interesting, I have SSL 3 disable on my WebDaV server (HTTPS) and Duplicati both 1.3 and 2.0 work fine for me.

Could you run SSL Server Test (https://www.ssllabs.com/ssltest/) against your server and post what the test report under Configuration -> Protocols as well as Configuration -> Protocol Details -> 'POODLE (SSL3)', 'POODLE (TLS)' and 'TLS version intolerance' as well as the final rating?

**Comment by glannes31** [comment]
For information,  i choose allowed-ssl-version then TLS1.2 . I capture this on wiresharck and i see TLSv1  and not TLSv1.2
