### ISSUE TITLE
HubiC support

### ISSUE THREAD

**Issue by tiernano** [duplicati/duplicati#1351]
Morning all. 
If I wanted to add hubic support (www.hubic.com) where would be a good place to start? It's based on oauth2 and openstack swift... I have done some playing with it and would like to add support...

Thanks.

**Comment by kenkendk** [comment]
From what I can see, it is a matter of choosing an openstack library and adding a backend. 

See issue #626 for the two libraries I found to be promising. 

Once you've picked one, you need to implement IBackend in a class. 

See the CloudFiles backend for an example of this : 
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/CloudFiles/CloudFiles.cs

**Comment by tiernano** [comment]
Cool. Will start looking atthis tomorrow and see how we go. Once I create a backed, how do I get it picked up? Just drop in a dll?

--Tiernan

**Comment by kenkendk** [comment]
Yes. Just add a reference to TrayIcon or the CommandLine project, and it gets loaded dynamically.
