### ISSUE TITLE
Impossible to specify a custom clean up duration. 

### ISSUE THREAD

**Issue by jonbodart** [duplicati/duplicati#1354]
When I want to give a custom duration for cleanup (when checking the box "Never keep backups older than this -> Custom ..."), it fails throwing the following error:  
"The cleanup duration entered is less than 1 day. This will give very poor system performance". 
I would like to never keep backups older than 3 days but I cannot enter this duration (I tried "Three days", "3 days", "three days", but all fail). 

See attached file. 

![capture](https://cloud.githubusercontent.com/assets/10274272/7021835/261e889e-dd26-11e4-8252-a070cf7cd904.PNG)

**Comment by kenkendk** [comment]
The syntax is "3D".
There should be a tooltip explaining the format.

**Comment by jonbodart** [comment]
Thank you !
