### ISSUE TITLE
Duplicati pauses when logging out of Windows

### ISSUE THREAD

**Issue by sussidio** [duplicati/duplicati#1355]
Does Duplicati have a service option or can the client app run in the background when logging out of Windows?
##

**Comment by Cylution** [comment]
I couldn't see a service option. Would be very interested to find this out too.

**Comment by kenkendk** [comment]
This is one of the reasons why we are working on 2.0.

With 2.0 you can use NSSM to install Duplicati as a service, that can run before login.
Once we get installers working, this will (optionally) happen as part of the install.

**Comment by Cylution** [comment]
Ideal

**Comment by sussidio** [comment]
Great thanks for the update Kenneth.

On 14 April 2015 at 05:52, Kenneth Skovhede <notifications@github.com>
wrote:

> This is one of the reasons why we are working on 2.0.
>
> With 2.0 you can use NSSM to install Duplicati as a service, that can run
> before login.
> Once we get installers working, this will (optionally) happen as part of
> the install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/duplicati/duplicati/issues/1355#issuecomment-92477903>
> .
>



-- 

Cheers,

Ben Fausti

**Comment by sanwilly** [comment]
so, what's the service's name?
