### ISSUE TITLE
Restored file 'scrambled'

### ISSUE THREAD

**Issue by richardcookson** [duplicati/duplicati#1357]
Hi,

I have recently tried to restore a file using 2.0.0.85- 2.0.0.85_preview_2015-03-07

I have previously carried out a restore with no problem. 

Now everything apparently works as it should, and the restored file appears with the correct file name etc, but when opened, the contents are 'scrambled'.  i.e. a restored MS Word document cannot be opened by word anymore. I wonder if there is an issue with the encryption / decryption?  
##

**Comment by kenkendk** [comment]
How did you restore it?

Duplicati checks the hash after restoring files, so it should complain if the restore failed.

**Comment by richardcookson** [comment]
I restored it using the menu item (Operations - Restore files...) from the
menu of the particular backup job. There was no complaint, I got the
'restore successful' window with the invitation to make a donation etc. The
file also has the correct filename and extension, but not the contents.

Richard Cookson BSc(Hons) PhD MIOA
Senior Consultant



Philip Dunbavin Acoustics Ltd
Alder House
Willow Tree Park
Booths Lane
Lymm
Cheshire
WA13 0GH

Tel: 01925 759380

**Comment by kenkendk** [comment]
Were the backup files created by an earlier version of Duplicati ?
Can you try restoring using the "Restore from target ..." menu in the upper right?

There is another report that sounds a bit like yours, and he said the remote files were created by an older version of Duplicati, but he saw the errors when restoring from the newer version:
https://groups.google.com/forum/#!msg/duplicati/SN2BFppUkYg/0XLEgj6p2qgJ

**Comment by richardcookson** [comment]
Yes they were an older backup.

**Comment by kenkendk** [comment]
Closing as I assume this is now fixed.
