### ISSUE TITLE
Replace embedded HTTP server

### ISSUE THREAD

**Issue by laurensb** [duplicati/duplicati#1358]
The current embedded HTTP server is no longer maintained. Switching to one that is (such as NHttp, Nancy, or Katana Host) would be nice.

See: https://groups.google.com/forum/#!topic/duplicati/12dccRkm8o8
##

**Comment by ts678** [comment]
[Switch the webserver to a more maintained version #1501](https://github.com/duplicati/duplicati/issues/1501) is a later issue with a bit more discussion, and some different candidates.

**Comment by warwickmm** [comment]
Closing this in favor of issue #1501.
