### ISSUE TITLE
Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies. 

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#1363]
Hi,

Backups in duplicati 1.3 work good with snapshots required set but the same with 2.0 gives this error

Windows Server 2008 R2 Standard X64
Runing as admin
Duplicati 2.0.0.85- 2.0.0.85_preview_2015-03-07

options
--no-encryption=True
--snapshot-policy=required
---------------------------------------------------------
    Error while running Test Snapshot: Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies. The specified module could not be found.

Log data

    General
    Remote

4/23/2015, 1:05:27 PM
Message
Fatal error
System.IO.FileNotFoundException: Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies. The specified module could not be found.
File name: 'AlphaVSS.60.x64.dll'
at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
at System.Reflection.Assembly.LoadFile(String path)
at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

3/20/2015, 4:45:33 PM
Message
---------------------------------------------------------

Any help

Savio

**Comment by PrismaComputer** [comment]
You need to have vc++ 2010 redist installed on your computer. Or you need to have the missing redist dlls with a matching manifest file in the same folder with Alpha vss. Sometimes this does the trick with redistributables without having to install them

**Comment by saviodsouza** [comment]
Thank You and sorry for the delay in replying back.
Installing VC++2010 x64 solved the problem.

In the page 'how to backup open pst files' adding the link to vc++2010 for duplicati Ver2.x would be a good.
'How to backup open pst files' currently has a link to vc++2008.

Thank you once again.

Savio
