### ISSUE TITLE
Never Keep Backups Older than X 

### ISSUE THREAD

**Issue by Zapto26001** [duplicati/duplicati#1365]
When Selecting custom under "Never Keep Backups older than" there is no time scale give. So users do not know what value to provide. 
##

**Comment by kenkendk** [comment]
Duplicati supports the follwing time specifiers:

Y - Year
M - Month
D - Day
W - Week
h - Hour
m - Minute
s - second

If you want to specify that you want a full backup each 14 days, you can use any of the following options:
2W
14D
1W7D
3D2D2D1W
