### ISSUE TITLE
Migrating Configuration

### ISSUE THREAD

**Issue by startailcoon** [duplicati/duplicati#1366]
This issue are observed on Windows with Duplicati 2.0.0.85- 2.0.0.85_preview_2015-03-07.

When moving/migrating Duplicati backup configurations from the defaulted setup user (being Admin for me at first) to a more dedicated daemon user I ran in to an issue with this. Stated on the webpage sais to move the "duplicate-server.sql" file, and it works for moving the actual backup information, but the links to the databases are not changed. When trying to start the backups the software complains about not finding the databases (even moving the backup databases does nothing). Trying to verify the databases sais it cant read/find the database file "C:\Users\Administrator\AppData\Duplicati\xxxx.sql".

The only solution for this is to give the new user access to the old fold that was used for storing the syncing data.
##

**Comment by ironjohn** [comment]
I second this observation.  Just ran in to the exact same problem with the exact same work around.

Duplicati's config could benefit from an easy way repoint the file locations.

**Comment by kenkendk** [comment]
This happens because it is not possible to edit the --dbpath parameter from the user interface, which should be fixed.
