### ISSUE TITLE
No filesets found on remote target

### ISSUE THREAD

**Issue by swatcats** [duplicati/duplicati#1367]
I am trying to backup my local files to a remote FTP server. Then i try to restore them on the original computer. When i do, i get the following error.

Error:
"Failed to get list of back times:
No filesets found on remote target"

Backup Settings:
--snapshot-policy=auto
--asynchronous-upload-folder=C:\Duplicati-Temp\
--tempdir=C:\Duplicati-Temp\
--restore-path=C:\Restore\
--no-local-blocks=true
--no-local-db=true
--upload-verification-file=true
--auto-cleanup=true
--all-versions=true
--keep-versions=-1

If i use the work around from issue 966 by specifying --time=now. It will bring up the restore window. The window has an infinite tree of folders. See attached image.
![restore](https://cloud.githubusercontent.com/assets/3029548/7361928/cb9d7082-ed2f-11e4-98a6-12a0cdc42e90.png)

This might be in line with issue 966 (https://github.com/duplicati/duplicati/issues/966). I am not using any prefix that i am aware of. I get the same error with encrypted and un-encrypted backups. 
##

**Comment by kenkendk** [comment]
Does this happen when you use a stored backup configuration and/or when using a "direct" restore?

Does things change if you remove --all-versions ?

What do you get from the commandline client:
Duplicati.CommandLine.exe list "ftp://server/path" --no-local-db

**Comment by swatcats** [comment]
1. Does this happen when you use a stored backup configuration and/or when using a "direct" restore?

The stored backup configuration from the webui dose not work. but the restore from target works fine.



2. Does things change if you remove --all-versions ?

No, I made a new backup to test from a clean start.




3. What do you get from the commandline client:
Duplicati.CommandLine.exe list "ftp://server/path" --no-local-db

No local database, accessing remote store

An attempt was made to load an assembly from a network location which would have
 caused the assembly to be sandboxed in previous versions of the .NET Framework.
 This release of the .NET Framework does not enable CAS policy by default, so th
is load may be dangerous. If this load is not intended to sandbox the assembly,
please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwli
nk/?LinkId=155569 for more information.

**Comment by kenkendk** [comment]
@swatcats The error you get can be fixed:
https://github.com/duplicati/duplicati/wiki/FAQ#user-content-windows-sandboxing

**Comment by kenkendk** [comment]
I think this is fixed.
