### ISSUE TITLE
Changing schedule date does not take effect

### ISSUE THREAD

**Issue by szyb** [duplicati/duplicati#1369]
Once I had to change system date to some future date (i.e. October 2015). After that I found out that all backup tasks has been rescheduled to that date. I set up correctly the system date and manually changed schedule date to current date, but backup task didn't run. Is there any way to reschedule all tasks to work normally?
##

**Comment by kenkendk** [comment]
If you edit and save the backup, it should trigger a re-schedule of the backup.

**Comment by szyb** [comment]
Hi,
Above situation I fixed by create new backup jobs (the same as original) and remove wrong ones. However I remember I have tried change the schedule (Schedule->Next date) and I set it to current date (+1h), so I could check whether it worked or not. It didn't worked, so I did workaround. 
Yesterday I had the same problem. I changed system date to 2015-06-04 and changed it back to current date and now I get: 
"Last successful run: 6 days from now". 
Yesterday I also changed the schedule date to 2015-05-28 15:45 and it didn't as well. Today it stills shows: "Next run: 2015-05-28 15:45".
Any ideas how to fix this?

**Comment by netnotix** [comment]
i have the same problem using 2.0.1.17. I have set a backup job with a weekly schedule. Then i tried to change this to daily with a new "next time" date (now + 1h). But this didn´t work. Where are these values stored so i can edit these ?

**Comment by netnotix** [comment]
I had to wait a week till the scheduled job was finished. This changed the job from weekly to daily. But it does not change the time, only the cycle from weekly to daily.
So you have to carefull set the time if you set up a new backup job. you can not change it later.

**Comment by Pectojin** [comment]
#2983 fixes problems with backups run "in the future"
