### ISSUE TITLE
Found duplicate metadatahashes, repairing - takes hours

### ISSUE THREAD

**Issue by gmalouf** [duplicati/duplicati#1376]
I have a scheduled s3 backup that had to be interrupted.  When I went to restart it, an error message came up saying that a repair needed to be run as there were x remote files missing on the remote server.

I started the repair and it quickly became stuck at 'Found duplicate metadatahashes, repairing'.  This has been running for a few hours now - I will edit when it finishes.  
##

**Comment by jarmo** [comment]
Did it ever finish then? I'm experiencing something similar at this moment that's why i'm asking.

**Comment by gmalouf** [comment]
it never finished, I ended up rebuilding my backup.  That was an awful experience for sure.
