### ISSUE TITLE
Duplicati sends muiltiple email alerts. (Duplicati 2.0.0.85- 2.0.0.85_preview_2015-03-07)

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#1378]
Duplicati sends multiple email alerts.
-------
First one:::

Good
-----------------
Second one:

ListFilesets: [Duplicati.Library.Main.ListResultFileset, Duplicati.Library.Main.ListResultFileset]
VerboseOutput: False
VerboseErrors: False
Messages: []
Warnings: []
Errors: []

------------------
Third

ListFilesets: [Duplicati.Library.Main.ListResultFileset]
Files: [Duplicati.Library.Main.ListResultFile]
VerboseOutput: False
VerboseErrors: False
Messages: []
Warnings: []
Errors: []

------------------------

Forth

ListFilesets: [Duplicati.Library.Main.ListResultFileset]
Files: [Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile, Duplicati.Library.Main.ListResultFile]
VerboseOutput: False
VerboseErrors: False
Messages: []
Warnings: []
Errors: []

--------------------------

In Total 9 emails. Are these bug reports?

Savio D'souza

**Comment by kenkendk** [comment]
It looks like at least some of the operations are from a List operation.
Normally only the backup operation sends emails.
Are you using the option --send-mail-any-operation ?

**Comment by saviodsouza** [comment]
Thanks for your reply.

Yes, (but now I set it to false) and today I got only 1 email for each
backup

Now in that single mail how do I get a variable value (sucess/failure/or
similar)
*Subject
eg "%hostname% %backupname% completed %sucessfully%

*body
value of source data #GB
value of previous backup data #GB
value of current backup data #GB
etc

Savio
