### ISSUE TITLE
Invalid Filename

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1380]
I'm getting this error when running a backup. It says "Invalid Name" (Ungültiger Name), but the name seems pretty normal to me... Its 261 characters long, is it a problem when its above 256?

I'm running duplicati 2.0.0.85 on Windows 8.1x64 with a NTFS drive.

````
Failed to process path: C:\Users\Username\Dropbox\Uni\Projektarbeit\Literatur\Harris, Bryan - 2003 - Fatigue in composites - Science and technology of the fatigue response of fibre-reinforced plastics\21-A-neural-network-approach-to-fatigue-life-prediction_2003_Fatigue-in-Composites.pdf
System.ArgumentException: Ungültiger Name.
Parametername: name
bei System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
bei System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
bei System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
bei Duplicati.Library.Snapshots.SystemIOWindows.GetAccessControlFile(String path)
bei Duplicati.Library.Snapshots.SystemIOWindows.GetMetadata(String path)
bei Duplicati.Library.Snapshots.WindowsSnapshot.GetMetadata(String file)
bei Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata(String path, FileAttributes attributes)
bei Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)
````

Btw, it's not possible to display the stacktraces in english, no?

**Comment by agrajaghh** [comment]
hm, I can't rename the file. Windows is telling me it's too long. But how could Dropbox sync this folder? And moving the folder to c:\ and back is working as well, weird...

Is it still a duplicati issue? I'm able to open the pdf so it should be possible for duplicati too, no?

**Comment by ironjohn** [comment]
Make a copy on C:\, then try to rename that copy.  

Use a much shorter name like dup-file-name-test.pdf for this.

If the rename is successful, please copy the new file to the original folder.  Then run the backup again.

**Comment by agrajaghh** [comment]
I renamed the long folder name without problems, backup is running now.

But I think duplicati should be able to backup these files anyway no?

**Comment by ironjohn** [comment]
I think the goal is to back up every file requested in every situation.  But the guys have limited development time to work on these problems and rely on us to give them as much information as possible.  

The further we can narrowing down the symptoms the easier it will be for them to create a solution.

If I have time I will try to recreate the problem on one of my systems with both v.85 and the current Github code.

**Comment by lanmower** [comment]
I'm having a similar message.
(having replaced all letters with 'x')

Failed to process path: D:\XXXXXXXX\XXX XXXXXXXX XXXXXXXX XX\XXX XXXXXXX XXXXXXXXXX\XX XXXXXXXX XXXX\X XXXXX XXXX - XXX XXXX XXXX\XXXXX - XXXXXXXXX\XXX XXXXX - XXXXX XXXX\XXX XXXXX - XXXX XX-XX XXXXX XXXX\XXX XXXXX - XXXXXXXX XXXXXXXXX XXXXXX XXXX XXXXXX - XX XXXXX XXXX XXXX.xlsx
System.ArgumentException: Invalid name.
Parameter name: name
at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType, String name, AccessControlSections includeSections, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
at System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
at Duplicati.Library.Snapshots.SystemIOWindows.GetAccessControlFile(String path)
at Duplicati.Library.Snapshots.SystemIOWindows.GetMetadata(String path)
at Duplicati.Library.Snapshots.WindowsSnapshot.GetMetadata(String file)
at Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata(String path, FileAttributes attributes)
at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(String path, FileAttributes attributes)

**Comment by agrajaghh** [comment]
Backup and restore working with long filenames on 2.0.0.90! Thanks again for your great work :blush:
