### ISSUE TITLE
Execution of authentication request returned unexpected result: 404

### ISSUE THREAD

**Issue by ypmict** [duplicati/duplicati#1390]
Hi,
Using the latest Duplicati 2.0.0.85- 2.0.0.85_preview_2015-03-07 and Google Drive as a target backup, last night the error just happened to all of my backup to Google Drive, before this it is good..
..also using the config to test the Connection URi using valid id and password also result 404 error..
any known new issue with Google Drive backup?
thanks for such a great tools...

![error404-duplicati2](https://cloud.githubusercontent.com/assets/8087038/7828477/94fb8f20-0466-11e5-9c7b-d3ce1b8e67ba.png)

**Comment by mattwhitfield** [comment]
According to [this thread][1], the target needs updating to use the v3 client libraries.

Would also like to take the opportunity to say thanks.

[1]: https://code.google.com/p/google-apps-script-issues/issues/detail?id=5101

**Comment by JoeSchmuck** [comment]
I too am having the same issue using Duplicati 1.3.4 and found the same link listed above discussing the v3 libraries and OAuth2.0.  Looking forward for a fix, I really like the simplicity of Duplicati to conduct an important task.

**Comment by MalachiC** [comment]
This is also affecting me.  I have a dozen backups that are now failing because of this same issue.  I would really like to see a fix for this too!

I would also love to say thanks for making such a great program!

**Comment by cktjonne** [comment]
I have the same problem what's Happen?
Google was update some API?
Thx.

**Comment by Athep** [comment]
Same problem here

**Comment by carefreews** [comment]
I have same problem.

**Comment by cmargena** [comment]
Will there be any patch for this google drive authentication issue for duplicati 1.3.4? I really use this simple tool to backup my data and made a lot of recommendation to other users. Thanks,

**Comment by HennieRoets** [comment]
Same here. Hoping for a solution quickly. The greatest backup software available!!!!!!!!!

**Comment by extdevelopment** [comment]
temporary solution:
1. use Google Sync (googledrivesync) and sync local copy with Duplicati backup files
2. edit existing backup settings and set file based store, use Googe Sync folder

In my case, Duplicati 1.3.4 can continue incremental backup and Google Sync to put those backup files on Google Drive.

**Comment by HennieRoets** [comment]
That will work. But, the reason for using Duplicati, is that Duplicati makes backup to a folder in drive. The in drive on windows, I deselected that folder from syncing. Which means that if I get infected with Ransomware, it does not have access to THAT drive folder.

**Comment by extdevelopment** [comment]
@HennieRoets you are right Ransomware potential danger.
But Googe Drive handle [file versions](https://support.google.com/drive/answer/2409045?hl=en).
(But Older versions of files may automatically be deleted after 30 days or 100 revisions).
In case of infection the previous version of the Duplicati backup files can be restored.

**Comment by HennieRoets** [comment]
Great. I new about that but for some reason my mind was on holiday...;o)

Then Google Drive is the perfect backup solution AND the cheapest. Even if the client gets infected with Ransomware, just restore the previous version.

Thanks a mil for kicking me in the but and activating my memory again ;o)

**Comment by cmargena** [comment]
You need extra storage space to handle a google sync folder in your installation and the backup window needs extra time, apart from this everything works.

**Comment by HennieRoets** [comment]
cmargena

please explain what your post means

**Comment by HennieRoets** [comment]
Then a question. So google drive keeps file versions. Lets say that the Ransomware virus infects all 20 000 documents on google drive. Is there a way to restore all files before the infection. Or will I have to restore one file at a time? Thanks all for help

**Comment by cmargena** [comment]
I try to explain my position on the temporary solution given by extdevelpment 2 days ago:
"
temporary solution:
1. use Google Drive Sync and sync local copy with Duplicati backup files
2. after sync finished, edit existing backup settings and set file based store, use local Google Drive folder

In my case, Duplicati 1.3.4 can continue incremental backup and Google Sync to put those backup files on Google Drive."

I think that the solution is ok but I need extra storage space to hold backup data into goole drive sync or I am wrong?

**Comment by filipposantovito** [comment]
Isn't easier to fix google auth in the code or pay someone to do it instead of waiting and implementing "naive" solutions?

**Comment by HennieRoets** [comment]
Hi. Agreed. But how to fix the duplicati code? Is it available to change myself or what is the procedure?

**Comment by filipposantovito** [comment]
I'm looking at the code right now. It's a c# project and I think the problem lives inside https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/GoogleDocs/GoogleDocs.cs 
It should be sufficient to upgrade to the latest google auth protocol.

Anyone can fix the problem for himself but he can (should) share his patch using a pull request to the author. More info @ https://help.github.com/articles/using-pull-requests/

**Comment by extdevelopment** [comment]
@cmargena yes, "temporary solution" need extra storage space on client side.

**Comment by filipposantovito** [comment]
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/GoogleDocs/GoogleDocs.cs#L76

https://developers.google.com/gdata/docs/auth/clientlogin

**Comment by extdevelopment** [comment]
@HennieRoets 
"Then a question. So google drive keeps file versions. Lets say that the Ransomware virus infects all 20 000 documents on google drive. Is there a way to restore all files before the infection. Or will I have to restore one file at a time? Thanks all for help"

I think it's a problem also, unfortunately, no ready-made solution to restore all files before the infection.
But with [Googe Drive Api Lists a file's revisions ](https://developers.google.com/drive/v2/reference/revisions/list) looks useful for any restore script.

When I'm in infected situation, I think of something. This backup is more than nothing.
Duplicati Googe Drive auth to fix would look much better :)

**Comment by SergeantHawke** [comment]
Just in case anyone here is running Duplicati on Linux, I found an interim solution that is working great for my company's 130GB of backups. Its a FUSE library that lets you turn your Google Drive into a folder on your Linux filesystem. It accesses the files remotely - You aren't syncing the entire backup to and fro and storing a local copy, which was what I wanted to avoid.

http://gdfuse.forge.ocamlcore.org/

There's a PPA available for Ubuntu, it lets you attach Google Drive to a folder. From there its a simple matter of changing Duplicati to back up to the "not-so-local folder" instead of Google Drive.

**Comment by cmargena** [comment]
@SergeantHawke , is there anything else alike gdfuse for windows?

**Comment by SergeantHawke** [comment]
@cmargena I found a product called NetDrive - http://www.netdrive.net/

I haven't tried it, but according to their website it can map Google Drive to a drive letter without syncing all the contents of the drive.

**Comment by cktjonne** [comment]
Back to work here... and yours?

**Comment by mode2k** [comment]
Here working again too.

**Comment by cmargena** [comment]
yes it is working. My question: Did google enable the previous version again of their authentication interface?. Did they publish another due date for this? thanks everyone.

**Comment by mattwhitfield** [comment]
Just another confirmation here, working on Duplicati 2. Looks like they definitely re-enabled it - the question is whether they did that on purpose? I certainly can't find any evidence of another date...

**Comment by b00nish** [comment]
Unfortunately it still doesn't work for me. What did you do to reenable it?

**Comment by ypmict** [comment]
yes.. confirmed it working again about 11th June ago... maybe this is temporary allowed by Google.. need to wait for proper fixed by dev.. nothing is done to make it worked again, I just let it do auto schedule backup...
thanks for such a useful tools...

**Comment by kenkendk** [comment]
I am currently finishing the test process for a new Google Drive backend which uses OAuth2.
The progress for this is tracked in #1347, you can subscribe to that issue to get notifications on further progress.

**Comment by mattwhitfield** [comment]
You rock.
Have donated - have a beer on me. :)

**Comment by kenkendk** [comment]
Thanks :beers: !!

**Comment by mathewgancarz** [comment]
10 Euro donation sent to the project as well. Thank you for all the work on it!

**Comment by kenkendk** [comment]
Thanks! Code is comitted to 3fc9102acc7a, I need to push the Oauth server code as well.

**Comment by HennieRoets** [comment]
Hi all hard working people.

Please explain what is happening. Are these changes being made at google themselves, which means Duplicati 1.3 will also continue to work with new authenticating?

Consider me stupid please ;o)
