### ISSUE TITLE
Feature request: Make an option to use the old engine in duplicati2

### ISSUE THREAD

**Issue by hchaase** [duplicati/duplicati#1395]
I know that the majority of the functionality of duplicati2 would not work with the old engine, but if you added an option to use the old engine, the features that don't depend on the 2.0 engine could still be used by people like me that prefer the old achieve method.

Your first [experimental release of duplicati2] (http://www.duplicati.com/news/experimentalbuildcommandlineonly) used the old engine but still brought improvements. 

As mentioned before (#1284), I regret that the old archive system of encrypted compressed folders is changed. But I totally understand that you chose another direction and cannot maintain two programs. Hence my suggestion.  

If it would help, I would be willing to donate for the creation of this.

**Comment by kenkendk** [comment]
The two versions are fundamentally different. The commandline version used the new storage format throughout, and was not using (nor compatible with) the existing files.

So having support for the 1.3.x method would mean maintaining two different backup systems. And neither do what you would like, which is to keep a copy of each file on the remote site.

Perhaps some of the suggested alternatives do what you want: https://github.com/duplicati/duplicati/wiki/FAQ
