### ISSUE TITLE
Incremental backups without keeping previous sources

### ISSUE THREAD

**Issue by David-Pa** [duplicati/duplicati#1397]
Using Duplicati 2.0.0.85, I created a new backup with the source being a certain directory. The idea is to place files there, back them up using Duplicati, and then delete them. Periodically repeat the process. I've set the backup to keep all previous backups forever.

The expected behavior is to perform a full backup the first time, and then only store the deltas. But in reality what happens is that all backups are performed fully. So if each batch of files is 1.5GB with only few changes, the result in Duplicati would be about 3GB instead of a bit over 1.5GB.

Am I doing something wrong, or am I not understanding how Duplicati works?
##

**Comment by David-Pa** [comment]
What does a man have to do to get an answer here?

**Comment by kenkendk** [comment]
Yes, after the first backup, all subsequent backups of the same data should not upload anything.
If there are small changes to the data, small uploads should occur.

I am not sure how it can happen like you describe, that each backup just adds more data.

You can try to look at the log in the WebUI, or use --log-level=profiling --log-file=path-to-file, to get a list of what happens and why the files are re-uploaded.

**Comment by David-Pa** [comment]
Thanks for replying. I will test it again with the logging, hoping that it will make sense to me. But before I do that I just want to mention (if it wasn't clear from my original post), that the original files are DELETED from the directory before performing the new backup. Also the files are placed in sub-directories with different names, but their content is almost identical.

I'm trying to use this technique to backup NANDroid backups. Each NANDroid back is essentially a set of files in a directory carrying the date in its name.

So the scenario is as follows:
1. Place NANDroid backup in directory (ie: c:\nandroid\2015-06-14--13-27-06)
2. Backup directory (c:\nandroid)
3. Delete files from directory (c:\nandroid is now empty)
4. Place new nandroid backup in directory (*) (ie: c:\nandroid\2015-06-21--13-30-01)
5. Backup directory (c:\nandroid)
6. Delete files from directory (c:\nandroid is now empty)
7. Repeat from number 4 periodically

(*) The new files are similar to the original files, with minor changes.

The expected result is for the backup to include all the original files + the chain of changes in the new files, since in Duplicati 2 each file block is hashed and should not be duplicated even if it originates from different files. (right?)

In reality the backup contains the original files + the new files.

**Comment by kenkendk** [comment]
Yes, it is all based on hashes, so the name and location of files does not matter.

But, the "diff algorithm" is very simple, in that it checks each block. If you shift the file a byte, all hash checks will fail and the data will be considered new.

So if the files contain a timestamp, at least the block with the timestamp will be different. If there is compression involved, the timestamp may cause cascading changes in the file, causing the blocks to not match. Same goes for encryption.

I expect that something like this is happening for you.
