### ISSUE TITLE
Problem with the v.1.3.4 'Completed Backups' Time : "1/1/0001 12:00 AM".

### ISSUE THREAD

**Issue by valp47** [duplicati/duplicati#1399]
With Duplicati 1.3.4 under Windows 7, everything has been well for months but this detail : the  'Completed Backups' Time allways remains "1/1/0001 12:00 AM". Is there something I missed? --Thank you.
##

**Comment by saviodsouza** [comment]
Check the date and time on your computer before runing duplicati 134.

If it is correct then close duplicati, start it again and try.

**Comment by valp47** [comment]
The date and time on my computer is in French and ok. To close duplicati and start it again does not change anything.

**Comment by kenkendk** [comment]
I am closing this as I am no longer maintaining 1.3.x
