### ISSUE TITLE
OAuth handler out of quota

### ISSUE THREAD

**Issue by thekrugers** [duplicati/duplicati#1403]
I see duplicati-oauth-handler.appspot.com is over quota. Would it be possible to get a copy of the source for that site so those using Google Cloud Storage could deploy their own oauth handlers on their own App Engine projects?

**Comment by kenkendk** [comment]
The way OAuth works is that you need to register (an app) with Google, and in turn you get a client secret. The client secret cannot be shared. If it was shared, it would allow anyone to impersonate Duplicati on login, and I am sure Google would block it quite quickly.

If you would like to host your own OAuth service, I can perhaps make a mini-version available that would be configureable with your own credentials.

Currently the backends are hard-coded to use duplicati-oauth-handler.appspot.com, so they would need to be updated to solve this.

Is it something you would like to do anyway?

For now I have changed the settings so the quota problem should be solved.

**Comment by thekrugers** [comment]
A mini version of the duplicati-oauth-handler.appspot.com source with your secret data stripped out would be perfect. We have a couple of apps in App Engine, so we can host our own OAuth handler on one of those and I can just change my copy of the source code to use that instead of your handler. We're building Duplicati from source anyway, so changing one or two URL strings before compile is not a problem for us.

In fact, considering the kind of data we plan on backing up, our auditors might insist on Duplicati using our own OAuth handler anyway.

**Comment by kenkendk** [comment]
I saw it went over quota once again.

I have added a generic version of the GAE code here: https://github.com/duplicati/oauth-handler

You need to change the app-name in app.yaml, copy config-template.py to config.py and add secrets+config stuff in there.

I will be looking into adding an option for setting the auth-uri as an option.
