### ISSUE TITLE
Improve file picker

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1404]
The source folder picker should be changed into a file explorer tree.

At a minimum the tree should have filled and half-filled checkboxes to indicate what should be included.

**Comment by koobs** [comment]
Also, selecting multiple folders is possible (allowed), but doesn't work correctly (only the first path selected is added). 

I suggest we make this issue a meta issue with a list of usability enhancements that can be checked off

- [ ] Fix selecting multiple paths/folders in file picker
- [ ] Support HTML5 Drag'n'Drop of paths into File Browser label dropzone

**Comment by kenkendk** [comment]
I have not attempted to make a "meta issue", but it sounds like a good idea. There are discussions to be had on all issues I suppose :).

The HTML5 Drag-n-drop is unfortunately not possible. The reason is that the drop delivers the files and folders to the app, but does not reveal the real source. That means that Duplicati can read the file/folder names (but not path information) and the file data.

**Comment by koobs** [comment]
@kenkendk Would you like me to create a separate "Improve Web UI usability (meta issue)" issue, or refactor this one to make it cover more than the original description?

**Comment by renestach** [comment]
We have a new file picker now in NGAX
