### ISSUE TITLE
Running duplicati as admin on a domain network to backup client outlook files

### ISSUE THREAD

**Issue by azkerm** [duplicati/duplicati#1408]
Hi There,

I'm trying to run duplicati on workstations connected to a domain. Its is nearly difficult to run the application on workstations as an admin since the UAC prompts for admin password no matter how hard you change the permissions. I use to run freefilesync before using the task scheduler which worked well but the PST copying was not that efficient.

Is there a possibility to over come this?
##

**Comment by thekrugers** [comment]
Hi,

I run Duplicati.Server vir Task Scheduler as a domain administrator with no problems. The config I go with is:

The trigger is "At startup".

Under General have "Run whether user is logged on or not" selected and "Do not store password" turned OFF. Also have a domain administrator account selected under "When running the task use the following user account".

Under Settings have "Stop the task if it runs longer then" turned OFF.

Hope this helps.
