### ISSUE TITLE
Windows Commandline Error Codes

### ISSUE THREAD

**Issue by helmutdux** [duplicati/duplicati#1409]
I use the newest Duplicati2 Version 2.0.0.87 under Win7 prof
and the command-line interface to Duplicati, but:

The Windows return code (errorlevel) seems to be always 0, even when serious errors occur.
Especially noticed using the restore-option.

Is that a missing feature or what else?
##

**Comment by helmutdux** [comment]
Hi!
I still suffer from receiving no error codes using Duplicati-Command-line Version under Windows -still in the newest version.
Its not usable always to scan logs manually.
I suggest to -at least - deliver errorlevel -1 when any error occurs.
Sometimes duplicati restore recognizes hash differences when restoring files, but delivers errorlevel 0. I always have to make a binary compare between original and restored files to find those errors

**Comment by ts678** [comment]
> The Windows return code (errorlevel) seems to be always 0, even when serious errors occur.

How does current version look? It might not be perfect, but it's not always 0. Documented as:

```
Duplicati.CommandLine.exe help returncodes

Duplicati reports the following return/exit codes:
  0 - Success
  1 - Successful operation, but no files were changed
  2 - Successful operation, but with warning(s)
  3 - For backup: finished with error(s), for test: error(s) found on the
  backend
  50 - Backup uploaded some files, but did not finish
  100 - An error occurred
  200 - Invalid commandline arguments found
```

Removing `bug` label as it's at least better now. Adding `pending user feedback` in case something specific must  be said,
 however specific problems (not following the above) probably deserve their own issue saying exactly what the situation is.

Arguably this "no error codes" issue should close if there are any error codes now.

**Comment by helmutdux** [comment]
Hi!
 For me its OK like this Thanks a  lot , finally solved.
