### ISSUE TITLE
repair produces an inconsitent DB / unchanged files are missing in followup file sets

### ISSUE THREAD

**Issue by kunom** [duplicati/duplicati#1410]
Create the follwing backup target directory.
```
echo hi > source\a
duplicati.commandline.exe backup source target
echo there > source\b
duplicati.commandline.exe backup source target
```

The command `duplicati.commandline.exe find target` lists two filesets, containing one and two files.

Then delete the SQLite DB (!important) and then run `duplicati.commandline.exe repair target`. Now, `duplicati.commandline.exe find target` lists two filesets, containing each one only a single file.

Browsing the corresponding, recreated SQLite DB gives:

```
The FILESENTRY table:
"1","1","0"
"1","2","635718814010000000"
"2","3","0"
"2","4","635718814010000000"
"2","5","635718814340000000"

The FILE table:
"1","D:\Projekte\duplicati2scripts\tmp\source\","-100","1"
"2","D:\Projekte\duplicati2scripts\tmp\source\a","2","2"
"3","D:\Projekte\duplicati2scripts\tmp\source\","-100","3"
"5","D:\Projekte\duplicati2scripts\tmp\source\b","5","5"
```

Obviously, the FILE table misses an entry 4; or the FILESENTRY incorrectly references the non-existing entry 4 instead of 2.

This happens with the latest release 2.0.0.87.

**Comment by kenkendk** [comment]
Thank you for providing such a simple reproducible test case!
