### ISSUE TITLE
Feature Request - Upload to multiple locations

### ISSUE THREAD

**Issue by simonjtaylor212** [duplicati/duplicati#1411]
Hi

I would really like to be able to upload one backup to two destinations - for example a NAS and Google Drive

Thanks
##

**Comment by barsthebars** [comment]
+1

**Comment by Aeyoun** [comment]
+1, see also [Horcrux](http://chrispoole.com/project/general/horcrux/).

**Comment by Pectojin** [comment]
Closing since it's a duplicate of 234
