### ISSUE TITLE
Latest update will not list previous backups

### ISSUE THREAD

**Issue by richardcookson** [duplicati/duplicati#1412]
Hi,

I've just installed version 2.0.0.87

When I try to restore a file from my previous backups (backed up to a network drive) Duplicati reports the following error (in the error window).

Error while running PDA Backup: Could not load file or assembly 'Duplicati.Library.Snapshots, Version=2.0.0.87, Culture=neutral, PublicKeyToken=8bfe994a39631a7b' or one of its dependencies. The system cannot find the file specified.

No previous backups are listed so it's not possible to restore. The same thing happens if I try the 'Restore from target' option, the software starts to recreate the local database, it gets as far as listing the dates of the previous backups but crashes with a similar error before any files are listed.
##

**Comment by kenkendk** [comment]
Is it an update with the built-in updater, or did you download the zip yourself?

**Comment by richardcookson** [comment]
I used the built in updater.
