### ISSUE TITLE
Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies. is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

### ISSUE THREAD

**Issue by mmehnert** [duplicati/duplicati#1414]
Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies. is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

I get this on Windows 8.1 x64 with --snapshot-policy=required .
Visual C++ redistributables 2005, 2008, 2010, 2012 and 2013 are installed, each both the x86 and x64 version.

**Comment by mmehnert** [comment]
Disregard that. The 2008 SP1 x64 C++ redistributable installation was broken.

**Comment by quincunx** [comment]
I had this problem, too. You need .NET 3.5 framework and "Microsoft Visual C++ 2010 Redistributable Package (x64)" (https://www.microsoft.com/en-us/download/details.aspx?id=14632)
