### ISSUE TITLE
Hubic see file

### ISSUE THREAD

**Issue by remydev** [duplicati/duplicati#1416]
Hello,
On Hubic (i haven't tried on an other Target Type) I can't see the upload files, on the hubic website.
However i can restore it if I want, but i wish see the new files, just to know if it's work properly.

**Comment by McBochi** [comment]
If you want to see the files on the hubiC website, you have to push your backups somewhere to the "default" bucket.
Or you could simply use some explorer like the Swift Explorer (http://www.619.io/swift-explorer) to check you object store.

**Comment by remydev** [comment]
Thanks, it's wortk with Swift Explorer
