### ISSUE TITLE
Issue backing up to google drive

### ISSUE THREAD

**Issue by muyiwao221** [duplicati/duplicati#1418]
I am currently configuring Duplicati 2.0 with GUI on my headless ubuntu server to back up my media files to my unlimited storage google drive education account. I have everything set up, and I use the OAuth Handler to create a key, but when I try to test it or try to back up I get the error below:

Error while running Mootoo Drive: Failed to authorize using the OAuth service: GetResponse timed out. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com/type=googledrive

I have gotten about 5 new authid tokens, but it does not seem to work. In terms of configuration (if it matters) I have it running off the default port with a subdomain linking to that port (8200). 

On another note I know Duplicati 2.0 works as I was successfully able to backup my laptop to my server using SFTP, and additionally I am able to backup from my laptop to my Google Drive education account. But for some reason I cannot backup from my server to the google drive, so clearly its a server side issue. Any ideas what this error message means and what I can do to fix it?

Thanks!
##

**Comment by kenkendk** [comment]
The error message means that the Duplicati OAuth server is not responding.

I cannot see this problem on the server, so something in between you and the server.

Since you can get the authid, it is slightly strange.

Do you have a firewall or something that would block Duplicati on port 443?

**Comment by gkruschina** [comment]
I had the same problem then I tried the following option:
--accept-any-ssl-certificat=true
on creating the uri to google-drive. Now it works without problems.

**Comment by andrej-zirko** [comment]
Thank you @gkruschina. This has resolved my issues as well.

**Comment by Betree** [comment]
I'm having the same issue with Duplicati 2.0.2.1_beta_2017-08-01. Some digging shows a problem with the SSL certificate :

```bash
$ mono /usr/lib/duplicati/utility-scripts/TlsTest.exe --web https://duplicati-oauth-handler.appspot.com/type=googledrive

https://duplicati-oauth-handler.appspot.com/type=googledrive
[Version]
  V3

[Subject]
  CN=*.appspot.com, O=Google Inc, L=Mountain View, S=California, C=US

[Issuer]
  CN=Google Internet Authority G2, O=Google Inc, C=US

[Serial Number]
  71B59F395A1BC3F6

[Not Before]
  11/29/2017 8:37:00 PM

[Not After]
  2/21/2018 8:37:00 PM

[Thumbprint]
  7DB0D89D60C28EA59777F5596361A672EF9E2852

[Signature Algorithm]
  (1.2.840.113549.1.1.11)

[Public Key]
  Algorithm: RSA
  Length: 2048
  Key Blob: 30 82 01 0a 02 82 01 01 00 be 7c a9 78 b2 a4 94 49 0a f6 8b 03 72 bc b4 9e 7c 9c d5 cd dd 3e 2c 1b f4 05 db d4 e4 02 24 2f 85 77 94 59 99 2b 60 c1 ee 0b 97 89 8c a9 ce 53 a4 8d 53 28 ce 4f 1f 0d 81 8a d9 8d 40 63 be 7f d3 8d 2e 25 48 de 50 19 27 c7 20 71 8f 70 d7 05 4d d6 25 67 1c b9 0b 6c 59 45 85 51 9c 29 68 79 ca e4 c9 8d c2 70 93 5b d0 66 90 f5 fd 06 80 59 f9 54 b2 b2 86 f7 43 62 06 d8 c3 be 69 dc 6f fa 4d ac 8e e6 13 cf dc 9b af 25 72 f2 dd fe f9 98 57 5f c2 cf 94 64 46 dd e2 3f c4 f4 c3 e9 92 de 13 ed 23 56 66 4e e2 85 6f cc 10 4c 47 1b 34 57 44 69 2d 6f a0 3e bc e0 66 ec e9 30 9a 02 f3 71 c7 0b 4f 40 09 61 5e c6 8c 54 b2 9a d4 68 0c 77 20 78 c1 12 64 c0 5e 1c f7 ed 6b 95 3b 7b 81 cf 0c 6f 02 d9 db b0 af 2c 37 4e cc 3c 6d 31 ee c0 02 9c b5 67 1b ca 9f 98 1a b4 68 f4 6b 49 ae 53 02 03 01 00 01
  Parameters: 05 00

	Valid From:  11/29/2017 8:37:00 PM
	Valid Until: 2/21/2018 8:37:00 PM

Error #-2146762486: CERT_E_CHAINING 0x800B010A

```

**Comment by Betree** [comment]
@kenkendk any updates on this, does the log provided above helps ? I can provide more info if required.

**Comment by kenkendk** [comment]
@Betree I think it is a problem with SSL certificate on your machine. Does any of these apply to your setup:
https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono

**Comment by Betree** [comment]
Mono v4.2.1. Works with https://github.com but throws on https://drive.google.com:

```
[Version]
  V3

[Subject]
  CN=*.google.com, O=Google Inc, L=Mountain View, S=California, C=US

[Issuer]
  CN=Google Internet Authority G2, O=Google Inc, C=US

[Serial Number]
  762238BAB65313FA

[Not Before]
  1/24/2018 1:02:33 AM

[Not After]
  4/18/2018 12:37:00 AM

[Thumbprint]
  2110EFEF12D3BD1998BCDFC7D01031408F197C04

[Signature Algorithm]
  (1.2.840.113549.1.1.11)

[Public Key]
  Algorithm: RSA
  Length: 2048
  Key Blob: 30 82 01 0a 02 82 01 01 00 e4 f5 13 cf e5 82 12 d3 ce 4f 4f b5 b9 f7 e7 e1 6c 04 0a db e4 1a ef 96 ed c2 03 5c 7c ad 6c 89 22 3c 89 66 db b5 ce 31 22 db 74 80 86 48 5a 3f 5e 39 62 83 2e 48 dd 75 c0 27 a7 b6 bf d0 7f e0 8d 1f 5b be 0e ba 97 17 3d f9 eb 0e af 17 ab 71 6f 9d 52 da 49 3e fb 32 85 25 07 da d3 4c 5c 78 00 a8 69 37 75 10 3d 6e 85 1a 32 56 d7 fa 99 2b 3c f5 73 0b 6d 0e 71 d8 af 21 4f 7d 81 12 7d 9c e6 74 1e 1a 09 c4 73 05 72 42 14 b3 57 f1 4b a4 f2 c2 1a 72 dc ae cc 3c ca 87 df ff 24 07 20 98 32 2b c3 2a 67 fe 6a 07 c5 36 4c 17 8a 30 28 bc 8c 37 c6 61 b1 2c c2 4c fa 89 43 e7 d9 32 8e ac 72 99 a2 50 69 75 fb 73 9a 6e af 31 d1 75 a3 06 6f 0c d9 16 64 a3 15 f4 0d d0 9d fc ec 43 aa 2f 49 e1 cf 6f 86 fd c2 e3 cb 8b c9 9d c1 d5 51 da 90 8f 62 96 20 08 a8 39 32 2a 82 06 d3 fe 89 d1 02 03 01 00 01
  Parameters: 05 00

	Valid From:  1/24/2018 1:02:33 AM
	Valid Until: 4/18/2018 12:37:00 AM

Error #-2146762486: CERT_E_CHAINING 0x800B010A
[Version]
  V3

[Subject]
  CN=accounts.google.com, O=Google Inc, L=Mountain View, S=California, C=US

[Issuer]
  CN=Google Internet Authority G2, O=Google Inc, C=US

[Serial Number]
  3343A9842987C930

[Not Before]
  1/24/2018 12:37:04 AM

[Not After]
  4/18/2018 12:36:00 AM

[Thumbprint]
  D56FCB8F5AF6F8F2679E3DC9D39DF4FE4FB84D39

[Signature Algorithm]
  (1.2.840.113549.1.1.11)

[Public Key]
  Algorithm: RSA
  Length: 2048
  Key Blob: 30 82 01 0a 02 82 01 01 00 be 7b 68 b7 db 7f a5 19 20 73 90 3a 0c 06 a8 bb f9 29 85 74 18 79 70 32 64 a8 3c 5f 5b 5f da 08 80 b5 ff e7 ed 76 6b bc 0d 6c 47 c7 21 1f 0e 0f c7 10 7d 52 9b c6 99 8c 23 77 48 17 e2 48 b3 f6 89 0f a2 d7 35 6d 15 fe 68 ce f6 2a 24 4e 7b 35 24 e3 92 37 d1 35 e4 9d c1 ae 7e 71 f9 5f aa 9d e0 3f 84 8f e1 a5 ae 9e 4e 92 83 3a ef e0 1f a5 85 a4 24 98 98 08 b5 23 4b f5 1e 37 88 dd 7b df 3d b3 fe 2f 25 af 6a 3d dc 3b 6a 92 4d e6 4e 67 0c d4 5d 33 2a 0a 34 e4 9f 22 3b 01 a3 e9 fd 3a 2c 63 99 4c b2 75 35 35 70 61 13 aa 1e 1f 21 9e 1d 0d 99 7f b6 c6 4d 67 42 5f 1e 54 67 6d c5 cf 22 ba 67 d0 a8 74 3c dc 9c 18 5c 1b 88 5f b3 df 5c ff ee ff 4c 81 e1 3d 26 f2 bb 3b 72 c8 0c 15 1f d9 2e b0 ab 35 d0 9e 8a c8 d6 8d 6b 8b 8f 68 21 2c ae d3 17 c9 94 5b 99 60 09 3e df 60 1b 0b 02 03 01 00 01
  Parameters: 05 00

	Valid From:  1/24/2018 12:37:04 AM
	Valid Until: 4/18/2018 12:36:00 AM

Error #-2146762486: CERT_E_CHAINING 0x800B010A
```

**Comment by Betree** [comment]
Moving to [MONO repository](http://www.mono-project.com/download/#download-lin) instead of default Ubuntu APT (MONO v5.8.0) fixed it. Thanks for the support :)

And thanks for the great work with Duplicati, it really is an amazing tool !

**Comment by Pectojin** [comment]
Strange that it would not work with v5.8 under Ubuntu. My v4.2.3 (from Ubuntu 16.04) works, so it's broken later... 

I'm glad you got it to work, though!

**Comment by mbarbone1369** [comment]
> Moving to [MONO repository](http://www.mono-project.com/download/#download-lin) instead of default Ubuntu APT (MONO v5.8.0) fixed it. Thanks for the support :)
> 
> And thanks for the great work with Duplicati, it really is an amazing tool !

Thank you !!  I have been having the OAuth issues with everything, until I read your message. I installed the MONO Repository, updated the certificates, I got, "The Connection Worked" this time.
