### ISSUE TITLE
Question about Duplicat 2.0

### ISSUE THREAD

**Issue by b00nish** [duplicati/duplicati#1419]
Hello

I have used Duplicati 1.3.4 to BackUp my Files to Google Drive. Since this doesn't work anymore and will not be fixed, I'm now trying to switch to Duplicati 2.0 Preview where the Google Drive Problems have been fixed.

Now I was able to Start Duplicati 2.0 and create a scheduled BackUp - just: How do I make sure, that the scheduled BackUp really runs.

As far as I can see, after I restart the Computer, no component of Duplicati is started and there is also no entry in Windows Scheduled Tasks. So I fear that just nothing would happen if I leave it like this.

Am I mistaken or do I have to execute further steps to make sure, that the scheduled BackUp really takes place?

**Comment by McBochi** [comment]
Just make sure you start the background service at the start and keeps running, sheduling is built in.
If you would like to have further certainty you probably have to periodically check your backup target and verify the task was run.

**Comment by kenkendk** [comment]
If you want it to run like 1.3.x, just add a shortcut to "Duplicati.GUI.TrayIcon.exe" to the "Startup" folder inside the start menu.

You can also use the NSSM program to start Duplicati.Server.exe as a service, and the use Duplicati.GUI.TrayIcon.exe with the commandline options --no-hosted-server and --hosturl=http://localhost:4200 to connect to the service.

**Comment by b00nish** [comment]
Very well, thanks.
This (adding the Duplicati.GUI.TrayIcon.exe to the Startup folder) is exactly what I tought of. I just wasn't sure if it's the right way.
