### ISSUE TITLE
Cannot recreate local database (OneDrive source)

### ISSUE THREAD

**Issue by solemgar** [duplicati/duplicati#1420]
Hello!

I am trying to recreate my local database or, for instance, recover files from another machine to see if I can get my data back in case of crash.

In my laptop (Windows 8.1) I have configured a backup job to OneDrive, I can backup and restore flawlessly. As a test, I installed a Windows 8.1 virtual machine and ran Duplicati on it. First I tried the restore from option, local database was recreated but I got this error stating that there is no remote files (see screenshot), Creating the backup job and recreating local database throws the same error. I am very concerned of losing the ability to restore the files if my local duplicati profile is lost for some reason (like a hard disk crash).

Someone has any feedback on this?

Thank you so much in advance!
![duplicati_error](https://cloud.githubusercontent.com/assets/13392725/8761382/87a2eb7c-2d4f-11e5-9194-0b555a09d2b9.png)

PS: Running 2.0.0.87- 2.0.0.87_preview_2015-07-03

**Comment by solemgar** [comment]
If it helps, I tried importing the backup job and now I get this error message.
![duplicati_2](https://cloud.githubusercontent.com/assets/13392725/8767129/cf09a54c-2e52-11e5-832b-6e456e31354b.png)

**Comment by kenkendk** [comment]
Most likely cause would be that you have entered a wrong path.

Are you using the same AuthID for both backups? 
(It should not matter, but just a wild guess)

**Comment by solemgar** [comment]
Hi!

I double-checked the path and I am sure it is OK. Actually, I even exported the job from the laptop where it runs fine and imported it into the Virtual Machine, but still throws me the same error.

Not the same AuthID. Should I try with the same one?

**Comment by kenkendk** [comment]
It should work with any AuthID, as it is a gateway to the same identity on OneDrive.

But, just for testing, it would be nice to know if there was something wrong here.

**Comment by solemgar** [comment]
Will try and report back. Thanks!

**Comment by paulinhoocx** [comment]
Hello, I'm from Brazil, I am using Google Translate.

I'm having the same problem when restoring the backup. I checked and the AUTHID is the same. What can it be?

**Comment by solemgar** [comment]
Yeah, same AUTHID, and still same problem. Any hints? Thanks!

**Comment by solemgar** [comment]
Just a quick update. If I try from the Linux version, I am able to see the backups, but they show as empty, I mean, I cannot expand the folder. I tried with --all-versions and -time=now flags.
![duplicati_cannot_expand](https://cloud.githubusercontent.com/assets/13392725/8930945/c145b5b8-3532-11e5-8c67-1daa0a4c06a1.png)

**Comment by solemgar** [comment]
News? :)

**Comment by paulinhoocx** [comment]
News?²

**Comment by kenkendk** [comment]
No news.

I will test the process on a Windows 8 installation and see if I can reproduce.

**Comment by paulinhoocx** [comment]
The only solution I found to do was backup again delete the files one drive and also delete the local database of the task, then sent back and he sent it backup to the onedrive.

Obs.: Google Translate pt-BR to en-US =P

**Comment by paulinhoocx** [comment]
![erro_duplicati](https://cloud.githubusercontent.com/assets/13457803/9170484/ba1de07e-3f39-11e5-9070-9dc745a2f954.JPG)

**Comment by paulinhoocx** [comment]
![erro_duplicati](https://cloud.githubusercontent.com/assets/13457803/9170501/e21dc828-3f39-11e5-9bd0-7a6dc3bbe8f0.JPG)

**Comment by solemgar** [comment]
thanks  kenkendk

**Comment by solemgar** [comment]
paulinhoocx , but that way you deleted the backup completely and started from scracht?

**Comment by paulinhoocx** [comment]
solemgar: Onedrive deleted all files and then deleted the local database, then sent to a new backup, returned to normal. The downside is that I lost all the data that was backed up.

**Comment by solemgar** [comment]
paulinhoocx: thanks!

**Comment by kenkendk** [comment]
Can you try with the new preview build:
http://updates.duplicati.com/preview/duplicati-2.0.0.89_preview_2015-08-24.zip

I think this may be the same issue as in #1437.

**Comment by paulinhoocx** [comment]
Even with the new version can not restore the backup.

**Comment by kenkendk** [comment]
I have a new build with a fixed issue that looks like this:
http://updates.duplicati.com/preview/duplicati-2.0.0.90_preview_2015-09-15.zip

**Comment by paulinhoocx** [comment]
Thank kenkendk, the problem was solved with the update 2.0.0.90.

**Comment by kenkendk** [comment]
Great!

**Comment by solemgar** [comment]
Sorry for not commenting sooner! I am downloading 2.0.090 and will try as well.

**Comment by solemgar** [comment]
Hi kenkendk, I stil have the same issue with preview .90. I think the problem appears when you have more than version of the backup, even if you use the show-all-versions=flag switch. Neither recreating the job or recovering from target work :(

**Comment by alanliu006** [comment]
Hi, I got same problem with "S3 compatible" Target Type.

OS: Windows 7 SP1 (64bit), Windows Server 2008 R2 Standard
Versions:
Duplicati 2.0.0.98- 2.0.0.98_preview_2016-01-27
Duplicati 2.0.0.90- 2.0.0.90_preview_2015-09-15

Restore files from "Google Drive" without problem.
But failed with "S3 compatible", becouse of empty folder tree: 

![2016-02-02_143526](https://cloud.githubusercontent.com/assets/5866681/12741752/4247f452-c9ba-11e5-96ce-e154a36a1b34.png)

**Comment by alanliu006** [comment]
Hi,

"S3 compatible" backup job is configured with '--no-encryption=true' Advanced Options.
"Restore files ..." of the backup job works well. 

Try '--no-encryption=true' Advanced Options in "Restore from target" UI, but seems emtpy Passphrase is not allowed.

![2016-02-03_154359](https://cloud.githubusercontent.com/assets/5866681/12778237/ac018a06-ca9c-11e5-9acc-2da763421a1b.png)

Got similar error message as #1274 when restore by Duplicati.CommandLine.
`Operation Get with file duplicati-20160203T071445Z.dlist.zip attempt 1 of 5 failed with message: The request signature we calculated does not match the signature you provided. Check your key and signing method. => The request signature we calculated does not match the signature you provided. Check your key and signingmethod.`

Thanks.

**Comment by kenkendk** [comment]
There is a logic issue in that the restore will appear to proceed if you do not enter a passphrase but the backup is encrypted. The same happens if you enter a wrong passphrase.

In either case, it will look like there are no files to restore.

For the `does not match the signature you provided` issue, have you checked that you have permissions and that the clock on your machine is correct?

**Comment by alanliu006** [comment]
The clock on the machine is correct. Restore files from backup job works, but not 'Restore from target'.
The error message told: Check your key and signing method.
The key is fine (Restore files from backup job works). Caused by signing method?

According to https://github.com/s3tools/s3cmd/issues/487 (I use the same service: s3.hicloud.net.tw)

> You are using a service that doesn't support the new signature algorithm.
> Please use:
> signature_v2 = True
> in your config file and that should work for you.

Is there similar config for Duplicati?

Thanks.

**Comment by kenkendk** [comment]
@alanliu006 there is not currently, but I can add that.

**Comment by kenkendk** [comment]
@alanliu006: Your issue is different, so I created a new issue for it.

**Comment by alanliu006** [comment]
Many thanks.
