### ISSUE TITLE
Wrong charset in german error message

### ISSUE THREAD

**Issue by gitgordon** [duplicati/duplicati#1421]
Hello,
by testing a FTP connection with the "Test connection" button with a wrong username, an error message is shown. This is correct. But the error string contains the german exception message with german special chars. See the screenshot.

![2015-07-18_14h59_56](https://cloud.githubusercontent.com/assets/13393665/8761700/439221d6-2d5f-11e5-858a-a5c51c0e62f7.png)

I am running Duplicati 2.0.0.87- 2.0.0.87_preview_2015-07-03
Thank you for fixing this issue.
Gordon
##

**Comment by Pectojin** [comment]
The error message seems to have changed (and hasn't been translated to German), so this issue no longer exists in newer versions of Duplicati. 

I'm not sure if it was just the translation or if there was an underlying issue in displaying it, but I'm afraid it's not possible to replicate anymore.
