### ISSUE TITLE
Tooltips are visible after deleting Source Data

### ISSUE THREAD

**Issue by gitgordon** [duplicati/duplicati#1422]
Hello,
by deleting a path in the source data tab the tooltip with the complete path is visible after the path is deleted. If i close the "Edit backup" dialog the tooltips are still visible. Only by reload the site with F5 the hints go away. This is reproducible with Firefox and Inernet Explorer. See the screenshots.

![2015-07-18_15h21_08](https://cloud.githubusercontent.com/assets/13393665/8761751/de56240e-2d61-11e5-9673-ff3a4ab760dd.png)
![2015-07-18_15h21_33](https://cloud.githubusercontent.com/assets/13393665/8761752/e4f9fd08-2d61-11e5-8f38-69d3e2f66d55.png)

I am running Duplicati 2.0.0.87- 2.0.0.87_preview_2015-07-03
Thank you for fixing this issue.
Gordon

**Comment by ltGuillaume** [comment]
It's not just those tooltips. Right now, for example, the "Advanced Options" explanation tooltip is stuck. In any way, a good idea would be to allow the user to click on a blank spot anywhere in the home screen to close any menu (anything opened by a "hamburger" button) and any leftover tooltips. It's a workaround for the tooltips issue, but it's intuitive enough.

**Comment by kenkendk** [comment]
The new ngax UI has fixed this.
