### ISSUE TITLE
Save button on edit backup

### ISSUE THREAD

**Issue by TimeLordmbw** [duplicati/duplicati#1426]
It would be nice if there was a "save" button on all four tabs in the "edit backup" window (Duplicati 
2.0.0.87- 2.0.0.87_preview_2015-07-03). It looks like the same window is used to create new and edit existing backups, so I can see why it is like it is, but I don't think this change would create much of a problem. (As it is, you can tab over to options and hit save without filling everything in, which gives you an error dialog.)

**Comment by kenkendk** [comment]
In the new ngax, you can click the numbers at the top, so I think this is fixed.
