### ISSUE TITLE
Support for Amazon CloudDrive

### ISSUE THREAD

**Issue by scspijker** [duplicati/duplicati#1427]
Amazon has a great service that let's you make infinite backups for a low price. I'd like to see support in Duplicati, and it seems a lot of other people do as well (but they're at the wrong site)

https://www.amazon.com/clouddrive
https://code.google.com/p/duplicati/issues/detail?id=598

**Comment by kenkendk** [comment]
I have migrated the request from Google Code, into issue #598.

**Comment by kenkendk** [comment]
It is working now for 2.0 in the latest preview:
http://updates.duplicati.com/preview/duplicati-2.0.0.96_preview_2015-12-17.zip
