### ISSUE TITLE
Started translating to Dutch (nl-NL)

### ISSUE THREAD

**Issue by scspijker** [duplicati/duplicati#1428]
Lot's of IT people in the Netherlands looking for the perfect cloud backup solution. I love open source, so I want to contribute.
I don't have a lot of time, but I think I should be able to translate everything in max half a year.

I started a translation here: https://docs.google.com/spreadsheets/d/1xoNhCgoL9hmkYfG77ZSz9tTJl6zoywb95zYJvoQpMME/edit?usp=sharing

Please add it to the other translations, and make me a contributor so I can edit directly in the translation on your repo.

Thnx :)

**Comment by devcompl** [comment]
This is not how it works. You have to make pull requests.

**Comment by scspijker** [comment]
Ah, so the easy way from the old site is gone :)
I'll look into it later then...

**Comment by kenkendk** [comment]
The new UI is not ready yet, so starting a translation at this point might end up being wasted timed, if the phrases are not used in the final UI. But thanks for wanting to help; I will get back to you when we are ready.
