### ISSUE TITLE
Restart after update. Program or computer?

### ISSUE THREAD

**Issue by reider-roque** [duplicati/duplicati#1433]
I've just updated the Duplicati using the web interface. Now it prompts me to restart, but not saying what - the program itself or the operating system. I'm almost certain it wants restart itself, but I don't want to risk. Restarting the OS is not always convenient. 

Also, I manually restarted the Duplicati and it still prompts me to restart.

Please disambiguate. For example call the button "Restart Duplicati" or "Reboot OS".

**Comment by renestach** [comment]
I think we call it "activate" now. Will check at next update.

**Comment by kenkendk** [comment]
Yes, it is called "activate"
