### ISSUE TITLE
Google cloud backend fails to authorize

### ISSUE THREAD

**Issue by andrej-zirko** [duplicati/duplicati#1434]
Backup to google cloud ends with error:
"Failed to authorize using the OAuth service: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com/type=gcs"

The same error appears after requesting new token
##

**Comment by gkruschina** [comment]
Hi, see my comment at
**Issue backing up to google drive #1418**
