### ISSUE TITLE
It seems the backup process reads folders outside VSS

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1436]
More details:
https://groups.google.com/d/msg/duplicati/XkVEx4NEshA/0sP7OKsJhJYJ
##

**Comment by ts678** [comment]
groups.google.com link is gone, and Wayback Machine at archive.org doesn't have it either. Is there any point keeping this open?

**Comment by warwickmm** [comment]
No.  Closing this due to lack of details.
