### ISSUE TITLE
Create a simple recovery tool

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1439]
In some cases the backups are damaged and only parts are recoverable making it hard or impossible to rebuild the local database.

A recovery tool could assist in recovering as much data as possible.

The tool should have the following modes:
  * Download: Downloads all files into a local folder
  * Unpack: Decrypts and unzips all files into a new folder
  * List: Lists all files found in the specified dlist file
  * Restore: Takes a dlist file input and optionally a filename and restores it
  * Index: Create a sorted list of all hashes and the path to the blocks

The restore operation should do the following for each matching file:
  * Extract list of blocklist hashes from dlist file
  * Locate all blocklists and append list of hashes into a temporary file
  * For each hash, find the block and insert the data into the file. If not found, print warning.
  * Verify that the restored file has the correct hash

The restore operation could be faster by using the index, but that should be optional.
The unpack operation could also be made optional.

**Comment by gfullmer** [comment]
Thanks again, Kenneth.  Worked as documented.
