### ISSUE TITLE
Unable to restore anything without local db

### ISSUE THREAD

**Issue by dannysu** [duplicati/duplicati#1448]
Version: Duplicati 2.0.0.87- 2.0.0.87_preview_2015-07-03
Operating System: Windows 10, Arch Linux

Preparation:
 - Run Duplicati.GUI.TrayIcon.exe
 - Make 3 folders: Test_Source, Test_Backup, Test_Restore
 - Make a text file with some text and save it to Test_Source folder

Restore Successful Case:
 - Use the Duplicati web interface, create a backup configuration
  - Select Test_Backup folder for "Backup to..."
  - Select no encryption
  - Select Test_Source folder as the source data
  - Deselect repeat schedule
 - Manually trigger a backup
 - Verify duplicati files show up in Test_Backup
 - From the UI, do a restore and choose Test_Restore as the new location
 - Notice that the restore is successful and the text file created earlier is restored

Restore Unsuccessful Case:
 - Use the Duplicati web interface, create another backup configuration
  - Select Test_Backup folder for "Backup to..."
  - Select no encryption
  - Select Test_Source folder as the source data
  - Deselect repeat schedule
 - Don't do a backup, immediately do a restore with this new configuration
 - Got error message: "Failed to get list of backup times: No filesets found on remote target"
 - Do a repair database, then try restore again
 - Got error message: "Failed to get list of backup times"

**Comment by kenkendk** [comment]
There is a parsing issue that has not been fully identified.
See issue #1437 for more details.

If you can shed further light on the problem, it would be much appreciated.

Until the issue is resolved, you can use the 2.0.0.89 version:
  http://updates.duplicati.com/preview/duplicati-2.0.0.89_preview_2015-08-24.zip

This version includes a simpler restore tool:
  https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/RecoveryTool/help.txt

**Comment by dannysu** [comment]
I know for certain that the bug was introduced in 2.0.0.86 and was not there in 2.0.0.85.

**Comment by dannysu** [comment]
This is the culprit: 1be8d16e22711a509be69c5eaf5e35c049c3a224

The last time restore was for sure still working was at commit b08c6df11640dae9491aee32b38318b44e9799cf. Starting from 14413de2c6e6831de6f393e93320402ff352b96d there was several compile errors that were introduced, but they don't seem to be related to the restore bug. I manually fixed the compile errors and narrowed things down to 1be8d16e22711a509be69c5eaf5e35c049c3a224.

**Comment by dannysu** [comment]
Please see PR for possible fix:
https://github.com/duplicati/duplicati/pull/1457

The code had been defaulting to Jan 1, 0001 for ages now even though documentation says otherwise. Stepping through the debugger, the restore used to start with Jan 1, 0001 and then pick up the latest backup date from the drop-down and then goes through the same flow again with the correct latest date. Everything worked fine then.

The code now doesn't seem to do that and so defaulting properly to 'now' is essential it seems.

**Comment by kenkendk** [comment]
Do you want to update this issue with the additional issues you encountered, or should they go into new issued?

**Comment by dannysu** [comment]
Need to find a way to put together test data that reproduces additional issues. Closing this one since the simplistic case should be fixed.

**Comment by gmalouf** [comment]
Danny, can you post the exact commands you are running to get the restore to work right now?  I know you are using --time somewhere.

**Comment by dannysu** [comment]
I wasn't using command line, but it should all be the same. I was using --time in the options. Just give it a date in the future like 2015-11-01.
Kenneth has a new build with a fix for this issue: http://updates.duplicati.com/preview/duplicati-2.0.0.90_preview_2015-09-15.zip

Perhaps see if this fixes things for you. I still have other restore issues when done on a real data set, but maybe yours would be different.

**Comment by gmalouf** [comment]
I can confirm that the .90 build fixes the issue - the local database is
rebuilt properly now and I am able to select the files I wish to re-load.
