### ISSUE TITLE
Commandline.RecoveryTool [version] parameter appears not to work

### ISSUE THREAD

**Issue by gfullmer** [duplicati/duplicati#1454]
I restored the latest backup  from google drive nicely using the Commandline.RecoveryTool "download" command, and restore works fine for the latest version, but if I want to go back to a previous version, it doesn't appear to work both for the "restore" and "list" commands. Perhaps I don't know how to specify the version?  Tried both number and date version specification.
![fullscreen capture 942015 84314 am bmp](https://cloud.githubusercontent.com/assets/1638596/9688495/5f78db92-52e4-11e5-993b-b7ce937fdf17.jpg)

**Comment by kenkendk** [comment]
You can use the number, the timestamp or the filename.

It has to do with the way the "Current directory" is handled internally.
If you specify the full path, it should work:
```Duplicati.CommandLine.RecoveryTool.exe list C:\Users\richd\Dell2Files 1```
