### ISSUE TITLE
Setup is not possile on Windows 10

### ISSUE THREAD

**Issue by timeceeper** [duplicati/duplicati#1459]
On Setup appear a Message that .Net is needed for installing.
But on Windows 10 is .Net 4.5 installed.
##

**Comment by Nixtren** [comment]
Duplicati 2.0? Can you tell me where is the setup file?

**Comment by syrys** [comment]
Is there any updates to this? cannot install 1.3.4 on a windows 10 box

Error: "The .net framework 2.0 must be installed ()"

**Comment by Pectojin** [comment]
.Net 2 is ancient and not supported by Windows 10. It may be possible to get it to work under .Net 3.5, but honestly there's no point in 2018, closing :)
