### ISSUE TITLE
Duplicati 2.0 Build 89 CommandLine.RecoveryTool fails to decrypt files downloaded from remote file url

### ISSUE THREAD

**Issue by gmalouf** [duplicati/duplicati#1460]
I followed the instructions from https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/RecoveryTool/help.txt to try and do a manual restore.  My passphrase has special characters in it - so I put it in double quotes:

mono Duplicati.CommandLine.RecoveryTool.exe download file:///Volumes/MyVolume/GaryMacBackup/ /tmp/TEMPDownload/ --passphrase="MYPASSPHRASE"

I keep getting

downloading (24.60 MB)... - decrypting ... error: System.Security.Cryptography.CryptographicException: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data ---> System.Security.Cryptography.CryptographicException: Invalid password or corrupted data

for each AES file downloaded.  I am very confident that the passphrase is correct - what else could be causing this?

I've been struggling throughout the night to restore my data on a new Mac from backup - all options seem to fail from missing local database (restoring fails) to now invalid passphrase.
##

**Comment by kenkendk** [comment]
If you try this:
`mono Duplicati.CommandLine.exe list --verbose --x="PASSPHRASE"`

Then you should be able to see what Duplicati gets as input for your passphrase.

If that fails, you can try to use the AESCrypt tool to manually decrypt the files:
https://www.aescrypt.com/mac_aes_crypt.html

**Comment by gmalouf** [comment]
Thanks Ken.  It turns out I am using a $ as a part of my passphrase.  Duplicati seems to be cutting out the characters between that and an '*', only seeing part of the passphrase.

**Comment by kenkendk** [comment]
Try using:
`mono Duplicati.CommandLine.exe list --verbose --x="FAKE\$PASS*PHRASE`

That works for me.

**Comment by gmalouf** [comment]
So it resolves correctly but still complains that the password does not
work when I run the actual repair.  I was able to decrypt the data on the
computer that did the backup this morning, but it's not working from this
one..

**Comment by kenkendk** [comment]
Are you using the commandline on the computer you make the backup on?
Is $PASS (or whatever the real password contains) perhaps resolved to something on the other machine?

For example:
'PASS=123 mono Duplicati.CommandLine.exe list --verbose --x="FAKE$PASS*PHRASE`
Would give:
`FAKE123*PHRASE`

If you are using the CLI, there are also cases where * resolves to "all files in the current folder".

Did you try the AESCrypt tool?

**Comment by gmalouf** [comment]
I'm trying once more to restore the local database to the new computer and
then restore via the GUI tonight.  If that fails, I'm going to go through
the new tool that you added recently.

**Comment by kenkendk** [comment]
Was this fixed?

**Comment by agrajaghh** [comment]
closing for now, please comment if you are still having issues
