### ISSUE TITLE
[REQ] Add Proxy Support

### ISSUE THREAD

**Issue by frelis** [duplicati/duplicati#1466]
Hi,

Could you please add proxy support, if not for all at least for auto updater
##

**Comment by kenkendk** [comment]
You should be able to add Proxy support by creating / editing the Duplicati.CommandLine.exe.config (or Duplicati.GUI.TrayIcon.exe.config) file as described here:

https://stackoverflow.com/questions/1938990/c-sharp-connecting-through-proxy

**Comment by Pectojin** [comment]
Closing as duplicate of #290
