### ISSUE TITLE
Document how to manually restore files

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#147]
_From [kenneth....@gmail.com](https://code.google.com/u/117596759558990029378/) on January 15, 2010 21:21:36_

To make it clearer that Duplicati actually works, there should be an easy
to follow guide that explains how to manually restore files without using
Duplicati.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=147_

**Comment by AKovalsky** [comment]
Can please anyone reupload that to current wiki?
