### ISSUE TITLE
Two backups, one location

### ISSUE THREAD

**Issue by kelna** [duplicati/duplicati#1473]
Is it possible to have two backups pointing to the same location? Both would have the same setup, only difference in the bandwidth limit. One would be without limit so it can upload as much as it can, when I don't use the computer. The other would be limited so I have bandwidth to browse. Would this work?
##

**Comment by kenkendk** [comment]
So the two backups would be identical?

That is possible by choosing the same settings for both, and then pointing `--dbpath`to the same database.

But would a better solution be to simply use a bandwidh limiter that could limit the bandwidth used by Duplicati? 

There is support in the code for changing the thottling options while it is running, but it is not exposed in the current interface.

**Comment by kenkendk** [comment]
Closing for lack of feedback
