### ISSUE TITLE
How to change db path?

### ISSUE THREAD

**Issue by LJPapenfort** [duplicati/duplicati#1478]
Hi there,

I am running the latest duplicati 2.0 version on Ubuntu Linux and tried it first in a temporary folder in my home directory. After creating different backup jobs and trying around, I copied the duplicati folder on a different drive/folder, since the dbs are getting quite large.

Unfortunately duplicati still tries to access the dbs at the old location, e.g. /home/user/tmp/duplicati/data. It complains about broken dbs and recreates them there when repairing the dbs.

Can I change somehow the path to the new location, e.g. /media/device/backup/duplicati/data?

This is how I am running duplicati:

TEMP=/media/device/tmp/duplicati mono Duplicati.Server.exe --portable-mode --log-file=./duplicati.log --webservice-port=8200 --webservice-password=XXX --webservice-interface=any
##

**Comment by Tentos** [comment]
One caveat: I am not an expert or developer of Duplicati, just one user.
Still: Have you tried the --dbpath option? You can specify the database path with it in the settings of a backup.
