### ISSUE TITLE
Issue using Duplicati on Windows 10 - Failed while executing "Backup" with id: 1

### ISSUE THREAD

**Issue by AboutBrace** [duplicati/duplicati#1480]
I tried to start a backup on Windows 10, but I encountered an exception:

System.NullReferenceException: Object reference not set to an instance of an object.
at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action`1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

Duplicati: Duplicati.GUI.TrayIcon, Version=2.0.0.87, Culture=neutral, PublicKeyToken=null (Duplicati.Library.Main, Version=2.0.0.87, Culture=neutral, PublicKeyToken=8bfe994a39631a7b)
OS: Microsoft Windows NT 6.2.9200.0
Uname: 
64bit: True (True)
Machinename: BRUCELARSEN-MOV
Processors: 4
.Net Version: 4.0.30319.42000
Mono: False (0.0) ()
Locale: en-US, en-US
SQLite: 3.8.5 - System.Data.SQLite.SQLiteConnection
##

**Comment by kenkendk** [comment]
Can you try to export the backup and send the file to me?
(Please change any passwords in the file before you send it).

**Comment by bruce-larsen** [comment]
Certainly...here you go. 

"C:\duplicati\Duplicati.CommandLine.exe" backup "file://L:\duplicati\brucelaresn-mov" "C:\Users\bruce.larsen\Documents" --backup-name="Bruce Larsen Surface" --dbpath="C:\Users\bruce.larsen\AppData\Roaming\Duplicati\ADSBSBWCEG.sqlite" --encryption-module= --passphrase= --dblock-size="256mb" --no-encryption="True" --prefix="brucelarsen-mov_duplicati" --compression-module="7z" --7z-compression-level="9" --asynchronous-upload-limit="0" --verbose="true" --debug-output="true" --snapshot-policy="auto" --disable-module="console-password-input"
