### ISSUE TITLE
Performance issue in GUI with preview 2.0.0.90

### ISSUE THREAD

**Issue by TonyGLT** [duplicati/duplicati#1481]
I have a backup that's about 400 GB for 100 000 files. The backend is Hubic. The backup is running fine but I find that getting files for restore or expanding each subfolder is slow : it takes about 10 minutes each time.

With the log, I can see this SQL query takes almost all the time :

ExecuteReader: SELECT "C"."Path", "D"."Length", "C"."FilesetID" FROM (SELECT "A"."Path", "B"."FilesetID" FROM "Filenames-885E71B8E24C3A44B6F50EB5F0D0BFF2" A, (SELECT "FilesetID", "Timestamp" FROM "Filesets-BD667E0835AB314A8446A555321047EE" ORDER BY "Timestamp" DESC) B ORDER BY "A"."Path" ASC, "B"."Timestamp" DESC) C LEFT OUTER JOIN (SELECT "Length", "FilesetEntry"."FilesetID", "File"."Path" FROM "Blockset", "FilesetEntry", "File" WHERE "File"."BlocksetID" = "Blockset"."ID" AND "FilesetEntry"."FileID" = "File"."ID" ) D ON "C"."FilesetID" = "D"."FilesetID" AND "C"."Path" = "D"."Path" took 00:08:26.328

I tried 2 optimizations :
- A quick fix : add an index on Filesetentry table : CREATE INDEX "filesetentryIndex" on filesetentry (FilesetID ASC, FileID ASC). With this, it is 3-7 times faster.
- Create a temporary FilesetEntry table restricted to the current FilesetID : CREATE TABLE FilesetEntryTemp as SELECT \* FROM FilesetEntry WHERE FilesetID = ? . With this table, expanding a subfolder is almost instantaneous.

I don't know if that makes sense, but I think that improving the responsiveness of the gui could be a big plus for this great product.
##

**Comment by jarmo** [comment]
Could this be the reason, why my restore process of ~700GB backup took ~14 days? (https://github.com/duplicati/duplicati/issues/1391)

**Comment by TonyGLT** [comment]
I don't know but I don't think so.

My issue is about selecting files through the GUI. The restore in itself doesn't take so long for what I tried. After choosing files and with a local database, I can restore individual files in minutes.

**Comment by jarmo** [comment]
I'm using version `2.0.0.87`. Did you build `2.0.0.90` yourself or where did you get it?

**Comment by TonyGLT** [comment]
I got it here : [http://updates.duplicati.com/preview/duplicati-2.0.0.90_preview_2015-09-15.zip] (http://updates.duplicati.com/preview/duplicati-2.0.0.90_preview_2015-09-15.zip)

It's under "Version bump to v2.0.0.90-2.0.0.90_preview_2015-09-15"

**Comment by kenkendk** [comment]
@TonyGLT: How did you try the optimizations ?

Did you notice any increase in file size after creating the index? I can imagine that other places would benefit from the index as well, so if there are no side-effects I will go ahead and add it.

The temporary table idea is good, but needs some thinking to work. Since the WebUI is only connected through HTTP, there is no knowing when the table can be dropped again. I was thinking that there could be a temporary database associated with the current restore operation, which would be cleared after some time with inactivity. Did you have a simpler solution in mind?

**Comment by TonyGLT** [comment]
I created index in the database of my daily backup. So the backup uses it now and I don't see another side-effect that increased size. The database's size is 1 GB and the index's size is 78 MB (7% of the entire database).

For the temporary table, I copied the database, emptied the FilesetEntry table except for one FiletsetID, and tried to restore a file. I don't have a better idea to delete temporary table : after a period of inactivity or/and at next backup.

**Comment by kenkendk** [comment]
I have the index implemented, but the temporary table is a bit harder.
When working with a temporary database, we can just throw in another table, but if the source database is not temporary, I do not want to mess it up.

It looks like there is an option to copy data from one database to another:
https://stackoverflow.com/questions/2359205/copying-data-from-one-sqlite-db-to-another

This could be used to register a temporary database attached to the original one, such that all queries can be performed against the temporary database. There is already a mechanism that deletes stale db files from the temporary folder, so it should not be too hard to do.

**Comment by TonyGLT** [comment]
If you attach a database or if use the temp database (TEMP keyword), you can use the tables as if they were in the main database. Indeed, it should be easier to clear out.

**Comment by kenkendk** [comment]
I think the TEMP database is destroyed when the connection is closed, so it cannot be used to store the fileset currently being browsed?

**Comment by kenkendk** [comment]
The new build has the added index:
http://updates.duplicati.com/preview/duplicati-2.0.0.91_preview_2015-11-18.zip

**Comment by TonyGLT** [comment]
Yes, the temp database is deleted when the connection is closed. The right way is to attach a database during browsing.
