### ISSUE TITLE
Question: Does file size matter?

### ISSUE THREAD

**Issue by kelna** [duplicati/duplicati#1485]
Is it making any difference in backup speed if I set up bigger file sizes? My backup now contains ~2000 files. I started with 100 MB pieces then I increased it gradually to 512 MB because I thought it will speed up the process. I did it beacuse now starting a backup takes a LOT of time. Repairing the database and verifying the backend data literally takes a day or more. Is it because of the high number of files or the overall size? I use Amazon Cloud Drive as target.
##

**Comment by bruce-larsen** [comment]
Through which facilities are you using ACD as a target (ie. Netdrive, expandrive, etc.)?

**Comment by kelna** [comment]
https://github.com/yadayada/acd_cli

**Comment by kelna** [comment]
Repairing the database now takes 2+ days. This shouldn't be the case. There must be some workaround.

**Comment by ironjohn** [comment]
I have customers (ftp server target) with far more (12k+) files in a single backup set.  No slow downs like you are having.

I also have one customer with a single file (MySQL dump) backup set that spends half an hour "Deleting unwanted files ..." with the same ftp target.

Both sets use 50 MByte chunks.

The only difference I can think of is that the slow one is set to keep 31 versions of this MySQL dump, while the faster job has "1 Month" as it's retention policy.  Perhaps the cleanup logic is harder with an explicit number of versions.

**Comment by ironjohn** [comment]
Update:  Things look worse now that I'm paying closer attention to the slow "Deleting unwanted files" backup set.  It's been doing this for hours.  Could have been this way the whole time.  As long as it doesn't take more than 23.5 hours I would not have noticed a problem.  If I find anything useful I'll open an issue for reference.

**Comment by kelna** [comment]
Thank you for your update! Is it possible to turn off deleting unwanted files? Since I'm using ACD with a theoretical limit of 100 TB, disk usage is not of concern.

**Comment by kenkendk** [comment]
You can try `--no-auto-compact` and also make sure to not set `--keep-time` and `--keep-versions`, that should prevent any delete attempts.

**Comment by kenkendk** [comment]
Closing as I think the question is answered.
