### ISSUE TITLE
Add more members to the duplicati project

### ISSUE THREAD

**Issue by devcompl** [duplicati/duplicati#1488]
I think the project needs more developers. There are a lot of issues reported and feature requests. With current pace the 2.0 release is a looong time from now.

@kenkendk, maybe you could recruit someone to help? Or you want to keep this a personal project?

Also to make sure, I am not hating or whining or something, I just would like duplicati to be more active project.
##

**Comment by kenkendk** [comment]
@devcompl I do not consider Duplicati a personal project.

I am happy to include pull requests from whomever wants to help out.
So far, most contributions have been limited to a single feature or fix, but if someone consistenly provides pull requests, I will ask them to join the project.

I would love to see more people on the project, but I do not have funds to support that.

I only have my spare time to develop on the project, so sometimes I get a lot done, sometimes I get nothing done.

But I agree, at the current pace, it will be a long time before something can be released.

If you (or someone else reading this) happens to be a developer, there are many simple fixes to get started, i.e.: #1487, #1483, #1482.
