### ISSUE TITLE
Duplicati doesn't recognise Mono installation on Mac

### ISSUE THREAD

**Issue by danoc-ttc** [duplicati/duplicati#1489]
Hi all, 

What I am experiencing today, having just downloaded and installed Duplicati and subsequently the latest Mono Framework, is that when I try to run Duplicati, it continues to give me the message:

Duplicati Requires the Mono Framework 2.6 or later 

... and prompting me to (once again) download Mono.

I am using Mac OSX Yosemite 10.10.2 on a MacBook Pro. 

Searching around in previous issues here I found the following command and gave it a try:

mono /Applications/Duplicati.app/Contents/Resources/Duplicati.exe

What happens then is interesting. Duplicati Runs (although with a small message showing up on the top-right of my screen indicating: "Duplicati dummy window". I have no idea if it works or not, I haven't tried yet. 

The Terminal meanwhile gives me the following message: 
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Failed to load Mono.Data.Sqlite.SqliteConnection, reverting to built-in.
 Error message: System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
File name: 'Mono.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
  at System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, Boolean refonly) [0x00000] in <filename unknown>:0 
  at System.AppDomain.Load (System.String assemblyString) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (string)
  at System.Reflection.Assembly.Load (System.String assemblyString) [0x00000] in <filename unknown>:0 
  at Duplicati.GUI.SQLiteLoader.get_SQLiteConnectionType () [0x00000] in <filename unknown>:0 

Any ideas? 

Thanks! 

Dan

**Comment by kencroslin** [comment]
I have had a similar problem but with 10.11.1 el capitan. i have tried v 1.3.4 and 2.0 i had replaced some of the dmg contents with the 2.0 code and edited the variables to make 2.0 work with yosimite. all seemed fine until el capitan.

now i also get the same mono check failure inspite of having mono 4.2.1installed.

I am able to run the script in the application install in text wrangler or in terminal, and it runs fine.  but it will no longer run from launcher with out the mono check failure.

the only thing i can think of is it doesn't want to run the sh stub script as a unix executable and i have been unable to force it to do so.

**Comment by adrian-polglase** [comment]
I had this issue. To solve it, I opened Duplicati using terminal...

I opened terminal and typed in 'open /Applications/Duplicati.app' and then hit enter and it opened without complaining about Mono.

**Comment by hdavy2002** [comment]
Have the issue with duplication 2. I will try the terminal way.

**Comment by kencroslin** [comment]
I've had no issue running through terminal. what i am trying to do and what worked previously was building a dmg and installing as an application and then running from launchpad. the issue with running from a terminal window is you can't start at start up or close the terminal window with out shutting down the application.

**Comment by wolffc** [comment]
Same Issue here on Mac OS X (10.11.4) and Mono 64 Bit Preview package. 
with terminal command `open /Applications/Duplicati.app` the app starts

**Comment by oussjarrouse** [comment]
I am having the same issue as well.
Mac OS X 10.11.5 and the latest Mono for Mac.

**Comment by joshuascottpaul** [comment]
"FIXED" use - open /Applications/Duplicati.app/Contents/MacOS/duplicati

open by itself failed:

$ open /Applications/Duplicati.app/
LSOpenURLsWithRole() failed with error -1712 for the file /Applications/Duplicati.app.
$ open -a /Applications/Duplicati.app/
LSOpenURLsWithRole() failed for the application /Applications/Duplicati.app with error -1712.

**Comment by lodestarops** [comment]
Running into the same issue here...
@joshuascottpaul Thanks! Did you do anything else to get it to work?

Here are my repro steps:

1. Downloaded the following http://duplicati.googlecode.com/files/Duplicati%201.3.4.dmg
2. Installed the Application and tried to run it using Finder
3. Got the following error "Duplicati requires the Mono Framework version 2.6 or later."
4. Went to Terminal and ran $ open /Applications/Duplicati.app
5. See Step 3.
6. Opened file /Applications/Duplicati.app/Contents/MacOS/duplicati 
7. Added: 
export MONO_BIN="/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono"
8. Saved the file and repeated Step 4, Result was Step 3.
9. Repeated Step 2.

This is the machine that I'm using.
Model Name:	MacBook Pro with the following specs:
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

**Comment by lodestarops** [comment]
Followup:
1. Rebooted my system.
2. Tried opening Duplicati via Finder
3. Got the following error "Duplicati requires the Mono Framework version 2.6 or later."
4. Went to Terminal and ran $ open /Applications/Duplicati.app
5. The Duplicati App Icon bounced in my Dock
6. Waited for a while, minimized all my apps to see if it was just hidden in my background (it wasn't)
7. Force quit the application.
8. Opened MonoDevelop 
9. Closed MonoDevelop
10. Repeated Step 4.
11. This time it opened, but the screens are getting messed up (seems like a rendering issue)

![duplicati](https://cloud.githubusercontent.com/assets/14285793/16670206/fdef5656-444d-11e6-9bbb-fce152dc48d7.png)

This shouldn't be that difficult should it?

**Comment by agrajaghh** [comment]
@lodestarops it looks like you're using duplicati 1.3.x which is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.

**Comment by lodestarops** [comment]
Thanks @agrajaghh I'm testing duplicati-2.0.1.17_canary_2016-05-14.dmg from the source you provided. 

Still had to open the app via command line, because of the "Duplicati requires the Mono Framework version 2.6 or later." messaging.

But it's working through my default browser now. Thank you.

**Comment by fixe** [comment]
Using macOS Sierra 10.12 Beta -- adding the `export` mentioned above fixed the `Mono` not found issue.

**Comment by castillar** [comment]
As a note, I ran into this problem and running it from the command-line didn't work because "/usr/local/bin/mono" didn't exist in spite of having installed the MonoFramework-MDK-4.4.1.0.macos10.xamarin.universal.pkg package linked from the Duplicati error.

What _did_ work for me, though, was using Homebrew (running 'brew install mono'), which installs the same 4.4.1.0 version and creates /usr/local/bin/mono, after which Duplicati started working. Is it possible that something in the MonoFramework package doesn't properly install on El Capitan, while Homebrew does?

**Comment by kenkendk** [comment]
@joshuascottpaul: Thanks for the path to the mono binary.

I have used with a clean OSX install and then installed the Mono package, and tested that it works, but something is different in your case.

I have updated the script that attempts to find Mono on OSX, to include your path.

Could you try to replace your `run-with-mono.sh` script inside the installed bundle with this version:
https://github.com/duplicati/duplicati/blob/feature/fix_osx_mono_binary_path/Installer/OSX/run-with-mono.sh

If it works, I will include that version of the script in the next build.

**Comment by kenkendk** [comment]
I have updated the path fix, and tested that it is able to pick up both mono paths on my machine.
I expect to make a new build early next week with this fix.

**Comment by wildwestrom** [comment]
I'm having a similar issue. I installed the latest version of mono and duplicati with homebrew.

After opening:
```
Cannot Launch Duplicati
Duplicati requires the Mono Framework version 5.0 or later.
```

This may have to do with the directory in which Homebrew is installed, `~/homebrew/`.

Should this be a new issue?

**Comment by ts678** [comment]
[Running Duplicati from a USB drive](https://forum.duplicati.com/t/running-duplicati-from-a-usb-drive/12461/11?u=ts678) (if it seems related) calls it a mono installer issue. I don't use a Mac, so have no opinion.
The wrong version number message is probably just someone not knowing to bump that on move to 5.10. Code link [here](https://forum.duplicati.com/t/running-duplicati-from-a-usb-drive/12461/2?u=ts678).
IIRC the major/minor testing was also bad, but I'd guess neither the number or its test are the reason this is failing for you.
