### ISSUE TITLE
Storage destination support for Google Nearline

### ISSUE THREAD

**Issue by Aeyoun** [duplicati/duplicati#1490]
[Storage Nearline](https://cloud.google.com/storage-nearline/) by Google is similar to [Amazon Glacier](https://github.com/duplicati/duplicati/issues/701) but charges just 0,01 USD/GB/month for storage, nothing for uploads, and 0,01 USD/GB for downloads. It's an ideal storage location for highly encrypted backups and a perfect fit for Duplicati.

**Comment by Aeyoun** [comment]
I started a [bounty on this feature request through Bountysource](https://www.bountysource.com/issues/28164009-storage-destination-support-for-google-nearline). Other users who are interested in this feature could chip in through Bountysource to show their interest in this feature and appreciation for the Duplicati project developers.

The bounty is claimable by anyone who implements this feature and closes this issue. Non-project member contributors can [close this issue in a commit](https://help.github.com/articles/closing-issues-via-commit-messages/) and submit that through a [pull request to the project](https://help.github.com/articles/using-pull-requests/) to claim the bounty.

**Comment by kenkendk** [comment]
Not sure what exactly you request, but nearline support is already in Duplicati:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/GoogleServices/GoogleCloudStorage.cs#L58

You can choose "storage class" in the UI, or set the option --gcs-storage-class=NEARLINE.

This works for Duplicati 2.0 only, as there is no support for Google Cloud Storage in 1.3.x.

**Comment by kenkendk** [comment]
No feedback, so I am closing.
