### ISSUE TITLE
Left over artifacts in V2 user interface when deleting a data source

### ISSUE THREAD

**Issue by hcjehg** [duplicati/duplicati#1491]
You are currently running Duplicati 2.0.0.90- 2.0.0.90_preview_2015-09-15
On Windows 10 64 bit in up to date Chrome Version 46.0.2490.80 m

How to reproduce:

1) Add new backup

2) On the "Source Data" tab (Click on the tab, if you use next you will have to put in some data on the first tab) click [Browse] and select a path, for instance C:\
C: (Fixed) now shows up in the gray box above the Enter path... field and Browse button

![image](https://cloud.githubusercontent.com/assets/12269445/11149530/a13ec14c-8a23-11e5-8511-34daaf71f81f.png)

When doing mouse over the path of "C: (fixed)" the path is shown in a popup.

3) Click the red cross (visible only with mouse over) in C: (fixed) to delete the entry.

4) Notice the entry in the gray box disappears, but the popup showing the path does not disappear.

![image](https://cloud.githubusercontent.com/assets/12269445/11149364/7c576894-8a22-11e5-867a-b5a5b03196ed.png)

What should have happened: The path popup should have disappeared when the coresponding deleted item disappeared.

hcjehg
##

**Comment by kenkendk** [comment]
This was fixed with the ngax UI
