### ISSUE TITLE
Duplicati 2.0 UI: "Do you wish to use the existing database?" dialog improvement

### ISSUE THREAD

**Issue by zyryanov** [duplicati/duplicati#1492]
When I create a second backup in Duplicati 2.0.0.87_preview_2015-07-03 UI, it raises a dialog:

![alert](https://cloud.githubusercontent.com/assets/4445490/11171688/bd2e1358-8c17-11e5-9112-e6e2afeb2ebf.png)

* The "OK" and "Cancel" buttons are a bit confusing here. "Yes" and "No" would be more logical, I think. Or even something more user-friendly like "Re-use existing database" and "Create a new database".
* Having a button that brings back to backup creation screen would be also nice.

**Comment by kenkendk** [comment]
That is because it uses the browser function "[confirm()](http://www.w3schools.com/jsref/met_win_confirm.asp)", which does not allow you to specify the button names.

I have changed this in the new UI, which does not use the browser dialogs.
