### ISSUE TITLE
Can't backup to Rackspace UK

### ISSUE THREAD

**Issue by StarsoftAnalysis** [duplicati/duplicati#1493]
I'm unable to use Duplicati 2 on Linux with Rackspace UK.

I've got it working with Duplicati 2.0.0.87_preview_2015_07_03 running on Windows 8.1.

But when I use exactly the same settings on Linux 2.0.0.90_preview_2015-09-15, I get various errors

My settings, exported as a command line, and with private stuff changed, are:

```mono "/opt/duplicati-latest/Duplicati.CommandLine.exe" backup "openstack://tui2?auth-username=<myusername>&openstack-authuri=https%3A%2F%2Flon.identity.api.rackspacecloud.com%2Fv2.0&openstack-apikey=<myapikey>" "/home/chris/POV Scenes/" --backup-name="tui2" --dbpath="/home/chris/.config/Duplicati/UGHRDULVBJ.sqlite" --encryption-module="aes" --keep-time="3M" --passphrase="<mypassphrase>" --dblock-size="50mb" --disable-module="console-password-input"```

Sometimes I get an error message like this:

```Failed to connect: The server certificate had the error RemoteCertificateChainErrors and the hash ACB02FCE39AAD5FD648AC323AF8CE06C916B3AB2
Use the commandline option --accept-specified-ssl-hash=ACB02FCE39AAD5FD648AC323AF8CE06C916B3AB2 to accept the server certificate anyway```

but adding that commandlineoption doesn't help.

Sometimes I get timeout errors.

I've ruled out firewall problems.

Has anyone else had similar problems?

**Comment by StarsoftAnalysis** [comment]
Aha!  Isn't it amazing what you can achieve by reading the documentation (if you can find it)?

The [Linux How-To page for Duplicati 1.3](http://github.comhttps://code.google.com/p/duplicati/wiki/LinuxHowto) says to run:

```mozroots --import --sync```

to tell Mono about the relevant SSL certificates.

I did that, and now Duplicati 2 is running successfully on Linux.

**Comment by kenkendk** [comment]
I will add the tip to use mozroots to the error message

**Comment by StarsoftAnalysis** [comment]
On 17/11/15 11:51, Kenneth Skovhede wrote:
>
> I will add the tip to use mozroots to the error message
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/duplicati/duplicati/issues/1493#issuecomment-157347795>.
>
That will help -- thanks.

Regards,

Chris
