### ISSUE TITLE
Where can I find Duplicati.RecoveryTool.exe?

### ISSUE THREAD

**Issue by Dachu23** [duplicati/duplicati#1495]
Hi everybody,

I am trying to recover an old backup. I have downloaded the latest version of Duplicati 2.0 and extracted the folder. However, I cannot find the file "Duplicati.RecoveryTool.exe" mentioned in: https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/RecoveryTool/help.txt

I also cannot find that file on github.
Can you please tell me, where can I download it? 

Thank you!

Best regards, Dachu

**Comment by kenkendk** [comment]
The latest version (2.0.0.90) has been held back due to lack of testing.
There is now a newer version, which also includes the RecoveryTool.exe here:
http://updates.duplicati.com/preview/duplicati-2.0.0.91_preview_2015-11-18.zip
