### ISSUE TITLE
Ran make.sh but don't see how to launch GUI- Sabayon Linux

### ISSUE THREAD

**Issue by NginUS** [duplicati/duplicati#1497]
Hi,

I overcame all the obstacles which were in the way of running make.sh, & got it to complete w/o errors.

Now I don't see how to run the GUI. I clicked on an exe that suggested it would run the GUI, but it opened in my archive manager & didn't launch the app.

What do I have to do after running make.sh?

I'm on Sabayon Linux.

Thanks!
##

**Comment by kenkendk** [comment]
I am not sure how up-to-date the Makefile is.
You should be able to build everything by running:

xbuild /p:Configuration=Release Duplicati.sln
cp -r Duplicati/server/webroot Duplicati/GUI/TrayIcon/bin/Release

Then the folder Duplicati/GUI/TrayIcon/bin/Release will contain the full
build.

To run it, you need to prefix it with mono, e.g.:
mono Duplicati.TrayIcon.exe

If you would like to be able to double-click it, you need to use the
binfmt package:
http://www.mono-project.com/archived/guiderunning_mono_applications/

Regards, Kenneth


Den fredag den 20. november 2015 skrev NginUS <notifications@github.com>:
