### ISSUE TITLE
Error when a regex filter contains ~

### ISSUE THREAD

**Issue by mtman** [duplicati/duplicati#1500]
`-[^.*~$]`
Error while running Projects: parsing "^.+C:\Users\mtman\Documents$" - Unrecognized escape sequence \U.

`-[^.*~\\$]`
Error while running Projects: parsing "^.+C:\Users\mtman\Documents\\$" - Unrecognized escape sequence \U

Interestingly, Documents are not included among the backup sources.

**Comment by kenkendk** [comment]
Arh, I see... The tilde is expanded to the home folder, but the path needs to be regexp escaped.
