### ISSUE TITLE
displaying "Backup_ProcessingFiles" instead of progressbar

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1504]
I noticed the missing progressbar in the new UI of 2.0.0.92:
![ui](https://cloud.githubusercontent.com/assets/5296073/11556881/c7539f02-99a9-11e5-830d-9e6c4886a8b7.png)
after switching to the greeno theme it looked like that:
![green](https://cloud.githubusercontent.com/assets/5296073/11556857/a4d8db68-99a9-11e5-84ec-7980d1d4c235.png)

**Comment by kenkendk** [comment]
Thanks for reporting it, I have a fix ready!
