### ISSUE TITLE
VirusTotal is reporting a detection ratio of 2/55 on latest.zip as of 04-Dec-15

### ISSUE THREAD

**Issue by PhilR73** [duplicati/duplicati#1505]
Could be false positives, but I thought I should report it.

Attached screenshot.

https://www.virustotal.com/en/file/eeed98d98de4c2ccc8e4d5601516ed83e6cd670b69ae41b0b5d6b89492851c4b/analysis/1449225666/

-Phil

![virtustotal-duplicati-04_dec_15](https://cloud.githubusercontent.com/assets/8330166/11587992/4b260d58-9a75-11e5-91b0-f718fbc96c65.png)

**Comment by kenkendk** [comment]
Thanks for reporting.

Those are most likely false positives.

Duplicati binaries are built on OSX, so injecting Win32 virus/adware/whatever is highly unlikely to happen.

If that page allows you to report that they are false positives, hopefully someone will double check and un-flag Duplicati.

**Comment by kenkendk** [comment]
I think this is now solved as all files are signed with a codesigning certificate.
