### ISSUE TITLE
OVH public object storage support (SWIFT

### ISSUE THREAD

**Issue by pmithrandir** [duplicati/duplicati#1506]
Hello,

I would like to know if you are supposed to support OVH public cloud based on openstack swift.

They provide me a URL like that : 
https://storage.sbg1.cloud.ovh.net/v1/AUTH_*********************/Backup%20photos

and that's it.
Any idea on which section I should choose on Duplicati ?

I don't see swift there even if people seems to think it's supported.

Best regards,
Pierre

**Comment by kenkendk** [comment]
OpenStack / SWIFT (and OVH HubiC) is supported in Duplicati 2.0.
Simply choose OpenStack from the list of providers when editing the URI and type in the required information,

OpenStack support will not be backported to Duplicati 1.3.x.

Howerver, the OpenStack API url usually does not have any auth information, so you may have a WebDAV url, which should work fine in both version.

**Comment by pmithrandir** [comment]
Hello,

Thank you for your quick answer.

It's strange because OVH doesn't give me anything else. I doubt I should use my OVH credential to authenticate on webdav... so I'm missing username and password.

I'm wondering how I'm supposed to use their service...

I will try to gather more details on their side.
Thank you,
Pierre

**Comment by kenkendk** [comment]
OVH has many different services. Which one are you using?

**Comment by pmithrandir** [comment]
Hello

I'm trying this one. Sorry, it's available only in French.

https://www.ovh.com/fr/cloud/storage/object-storage.xml

Based on openshift / Swift I think.
Pierre

**Comment by kenkendk** [comment]
I've found this guide:
https://www.ovh.ie/g1576.dedicated_cloud_swift_start-up_guide

I am not sure if you need to use the "KEYSTONE_ADMINISTRATION_ENDPOINT" or the "SWIFT_ENDPOINT" in Duplicati. But by looking at the guide, it seems that the link you posted is actually a "SWIFT_ENDPOINT", so maybe it just works?

**Comment by pmithrandir** [comment]
Hello.

I managed to access the system.

here are the info I used : 

Bucket name > Backup_photos (your choice)
OpenStack Authuri : https://auth.cloud.ovh.net/v2.0/
Username user created in user interface to access horizon
Password password in user interface to access horizon
Tenant Name : 3640347*********** (Number visible in horizon in the drop down box on top of it, named tenant or project _id)
API Key
Container region SBG1 (or the one you choosed)

Pierre

**Comment by kenkendk** [comment]
OK. I have added the Authuri you found to the list, so hopefully it should be easier for others.
