### ISSUE TITLE
Localization tool not working

### ISSUE THREAD

**Issue by kelna** [duplicati/duplicati#1507]
I was trying to translate Duplicati to Hungarian but I couldn't manage to run LocalizationTool.exe. I also don't understand why I need to run it, though. Isn't it enough to edit the CSV file?
Anyway, I tried to run `$ mono LocalizationTool.exe import fr-FR report.fr-FR.csv`
And I got this message:

```
Missing method get_IsClientLinux in assembly /home/.../Duplicati/Localization/LocalizationTool.exe, type Duplicati.Library.Utility.Utility

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Duplicati.Library.Utility, Version=1.0.1.276, Culture=neutral, PublicKeyToken=8bfe994a39631a7b' or one of its dependencies.
File name: 'Duplicati.Library.Utility, Version=1.0.1.276, Culture=neutral, PublicKeyToken=8bfe994a39631a7b'
  at LocalizationTool.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Duplicati.Library.Utility, Version=1.0.1.276, Culture=neutral, PublicKeyToken=8bfe994a39631a7b' or one of its dependencies.
File name: 'Duplicati.Library.Utility, Version=1.0.1.276, Culture=neutral, PublicKeyToken=8bfe994a39631a7b'
  at LocalizationTool.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```
##

**Comment by kelna** [comment]
I just realized I don't see where I can change the language. I'm using Duplicati 2.0. The localization works only for the older version?

**Comment by kenkendk** [comment]
The translation tool only works for Duplicati 1.3.x.

We do not have a stable version of the 2.0 GUI yet, so it is too soon to start translating it.

I will let you know when there is a sufficiently stable version for translating.
