### ISSUE TITLE
Spurious directories named Duplicati created in working directory 

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1508]
Duplicati.Commandline.exe creates directory named Duplicati in current working directory if user running Duplicati.Commandline.exe does not have write permissions to  the installation directory. 

It would be better to store this information under Duplicati confid directory (~/.config/Duplicati on Linux).

Contents of the created directory:
---------
$ ls -R Duplicati
Duplicati:
updates

Duplicati/updates:
installation.txt  README.txt
---------

OS: Fedora 23
version:2.0.0.91-2.0.0.91_preview_2015-11-18 

How to reproduce:
1. Install Duplicati to a directory not named Duplicati, for example Duplicati-test.
2. #sudo chown root:root Duplicati-test
3. #mono Duplicati-test/Duplicati.Commandline.exe

**Comment by kenkendk** [comment]
Thanks for reporting.

It was looking to see if "ProgramFiles" was write-able, but that folder returned empty on non-windows platforms.
