### ISSUE TITLE
where is the package folder?

### ISSUE THREAD

**Issue by Bummibaer** [duplicati/duplicati#1511]
Hi,
is there a change in the folder structure?
In the *.csproj are references to the thirdparty-modules:  
    <Reference Include="MegaApiClient">
      <HintPath>..\..\..\..\packages\MegaApiClient.1.1.2\lib\net40\MegaApiClient.dll</HintPath>
    </Reference>

But actually, I  don't find the folder packages , but the folder thirdparty.

In earlier compiles I found:

<Reference Include="MegaApiClient">
      <HintPath>..\..\..\..\thirdparty\MegaApi\MegaApiClient.dll</HintPath>
    </Reference>

 Please give me a hint

**Comment by kenkendk** [comment]
It should be:
```xml
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\thirdparty\Json.NET\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="MegaApiClient">
      <HintPath>..\..\..\..\thirdparty\MegaApi\MegaApiClient.dll</HintPath>
    </Reference>
  </ItemGroup>
```

I will fix it in source
