### ISSUE TITLE
UI: Time precision

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1513]
I guess milliseconds are not necessary: :wink: 
![time](https://cloud.githubusercontent.com/assets/5296073/11693439/264846ac-9ea5-11e5-889b-beedfab4002c.png)
(2.0.0.94)

**Comment by renestach** [comment]
This is fixed, isn't it?

**Comment by agrajaghh** [comment]
nope, not for me on 2.0.1.17:
![dup](https://cloud.githubusercontent.com/assets/5296073/15504184/04870f98-21be-11e6-9dd5-e16f98e7cbd1.png)

**Comment by renestach** [comment]
![bildschirmfoto 2016-05-24 um 14 48 41](https://cloud.githubusercontent.com/assets/8270279/15504308/a9ea83f2-21be-11e6-8e3e-41fb9442970c.JPG)
2.0.1.17 on Mac (Mono)

**Comment by agrajaghh** [comment]
hm thats weird. I'm running windows, maybe thats the problem? Did you have miliseconds before as well?

**Comment by kenkendk** [comment]
I think the issue is that the `<input type="time" />` is being interpreted differently by different browsers.
I think the solution is to use a custom input type, but that sucks because it needs to support both 24h format as well as the am/pm method.

**Comment by agrajaghh** [comment]
looks like that isn't supported by firefox (which I use), IE and Safari:
http://caniuse.com/#feat=input-datetime

**Comment by kenkendk** [comment]
Ok, it is an Angular quirk:
https://docs.angularjs.org/api/ng/input/input%5Btime%5D

If I try that page in Chrome it looks like I want it, but in Firefox I get the `.000` value added.

**Comment by agrajaghh** [comment]
https://github.com/angular/angular.js/issues/10721

**Comment by kenkendk** [comment]
Thanks, found it 10 minutes later :)
