### ISSUE TITLE
UI: keep backups

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1514]
I noticed three minor things:
* If you select "forever" the number input field and the unit field shouldn't be visible
* If you select "a specific number" the unit field shouldn't be visible
* the number field should be smaller so everything fits in a single row

![keep](https://cloud.githubusercontent.com/assets/5296073/11693452/3b49bba8-9ea5-11e5-8738-59ae6e7b2da3.png)

(2.0.0.94)

**Comment by deHoeninger** [comment]
Beside the initial "wired" values, these fields never represent the current values and will always show "forever" "3" "days", even though the configuration is completly different.
