### ISSUE TITLE
No access to server directories in remote backends like Hubic.com...

### ISSUE THREAD

**Issue by hcjehg** [duplicati/duplicati#1515]
I just noticed a problem

It seems Duplicati is storing data in application specific storage on for instance Hubic.com - I imagine this is the same in Google Drive and Box.com...

If you use a "Path on server" and then later want to get to it, it seems difficult.

I haven't found a way to access application specific storage in the web interface of for instance Hubic.com, and I don't remember seeing it in any of the others either.

Is there a way to list the directory structure in the application specific part of remote backends like Hubic.com ?

The problem is that  if you use a remote directory, like fs02 and then stop using it, there is no way to copy the files out of there (to move your backup else where), or even to delete them - so the space will stay "lost" till eternity...

Right now I have got 10% occupied storage in Hubic.com but no way of accessing these files... :-/
(I'll get by for now. I suspect deleting Duplicati Backup from "Your Applications" on hubic.com will solve that problem...)

Any ideas how to solve this in a general way?

HC

**Comment by hcjehg** [comment]
The solution is to access the storage with for instance "Swift Explorer"

http://www.619.io/swift-explorer

that supports HubiC

I expect if I enter a path that begins with default/.... Then the files are visible in in the web interface IF a folder with the same name (without default) is created...

**Comment by kenkendk** [comment]
I think this is an inconsistency with the HubiC web interface.
I seem to recall that there was a button somewhere for Google Drive, where you could see application data.

Are you fine with closing this issue, or do you have an idea for something better?

**Comment by hcjehg** [comment]
I agree on closing.

Using HubiC one should just be aware that only the bin "default" is visible in the web interface, but accessible through for instance swift-explorer. If you select a path default/... then the files are also visible in the web interface :-)
