### ISSUE TITLE
Select folder to back up - folders are not sorted....

### ISSUE THREAD

**Issue by hcjehg** [duplicati/duplicati#1517]
The folders in the "Select folders to backup" are not sorted in any way.
That makes it difficult to find a particular one to back up.

HC

![image](https://cloud.githubusercontent.com/assets/12269445/11747335/ffaa91b0-a022-11e5-91d7-db30b058dfc6.png)
##

**Comment by robsonsobral** [comment]
For me, the sort isn't matching the OS behavior. Now, I'm seeing folders sorted as:

- `.folder name`;
- `folder name`;
- `_folder name`.

On Windows, it should be:

- `.folder name`;
- `_folder name`;
- `folder name`.
