### ISSUE TITLE
ngax "MENU" not working in 2.0.0.94

### ISSUE THREAD

**Issue by NickPyz** [duplicati/duplicati#1518]
Very attractive theme. Nicely laid out, and well organized. 

However, the MENU link at the top is not functioning, so many functions are missing. Maybe because this is still experimental?

OS: Windows 10 - 64 bit
BROWSER: Chrome 47.0.2726.80 m

**Comment by kenkendk** [comment]
Yes, I forgot to add that. It works if you make the window larger.

**Comment by NickPyz** [comment]
This issue appears to be fixed in version 2.0.0.98 - at least on my browser and OS.
OS: Windows 10 - 64 bit
BROWSER: Chrome 48.0.2564.97 m

Pretty sure that you can close this issue. Thank you.
