### ISSUE TITLE
Confusing Item: NGAX Theme - Edit Backup > Options 

### ISSUE THREAD

**Issue by NickPyz** [duplicati/duplicati#1519]
In the Greeno theme, under options, I have the the following:

--snapshot-policy=on

When I switch over to the ngax theme, the options screen shows that I selected the snapshot policy, but the "on" option is not shown unless I manually select it from the dropdown box. This is confusing - it looks like switching themes requires additional configuration of the options.

**Comment by kenkendk** [comment]
That is because it is case sensitive, which it should not be.
