### ISSUE TITLE
Question: How much disk space does this use on the local system?

### ISSUE THREAD

**Issue by thejargen** [duplicati/duplicati#1524]
I have a server with more disk used then free, does this backup everything i want to and THEN upload it? Or does it make a few blocks, upload them, delete those blocks, make the next set of blocks, etc. Which would make much more sense on space usage. 
##

**Comment by Pectojin** [comment]
For anyone looking up this isse in the future:

It will depend on `--asynchronous-upload-limit`. By default it's 4, which means it will create 4 volumes locally on disk before stopping to wait for network upload. So 4 times your volume size, which is 50MB would require about 200MB of disk space.
