### ISSUE TITLE
FTPS not working on Win7 if SSLv3 disabled on backend ("A call to SSPI failed, see inner exception.")

### ISSUE THREAD

**Issue by zertrin** [duplicati/duplicati#1529]
If the FTP backend allows only TLS connections (plaintext, SSLv3 and SSLv2 disabled), when trying to use the FTPS backend with Duplicati on Windows the following exception occurs:

`A call to SSPI failed, see inner exception.`

Upon using the Backend tester tool, I got the following stacktrace, but it doesn't give much more insight.

```
.\Duplicati.CommandLine.BackendTester.exe "ftps://example.org:21/backup?auth-username=myuser&auth-password=mypassword"
Starting run no 0
Unittest failed: System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
   --- End of inner exception stack trace ---
   at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   at Duplicati.Library.Backend.FTP.List(String filename)
   at Duplicati.CommandLine.BackendTester.Program.Run(List`1 args, Dictionary`2 options, Boolean first)
   at Duplicati.CommandLine.BackendTester.Program.RealMain(String[] _args)
```

Googling a bit leads to some hints about the `System.Net.FtpClient` from the .NET Framework behaving badly when SSLv3 and SSLv2 is disabled on the backend.

see in particular https://stackoverflow.com/questions/29012747/ftp-tls-on-windows-server-2012-system-net-ftpclient

After allowing SSLv3 and SSLv2 again on the FTP server, the problem disappears.

So the problem doesn't seem to be directly related to Duplicati, but to the FtpClient from the .NET framework. I still decided to file this issue here because at first I really thought it came from Duplicati and I couldn't find any previous bug report about it here. I went up to the source code of the FTP Backend to see if I could do something, but I don't know C#.

I found this comment however (https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/FTP/FTPBackend.cs#L47):

```
            //This can be made better by keeping a single ftp stream open,
            //unfortunately the .Net model does not allow this as the request is 
            //bound to a single url (path+file).
            //
            //To fix this, a thirdparty FTP library is required,
            //this would also allow a fix for the FTP servers
            //that only support SSL during authentication, not during transfers
            //
            //If you have experience with a stable open source .Net FTP library,
            //please let the Duplicati authors know
```

The part about `FTP servers that only support SSL during authentication` seems pretty related to this issue too.

IMHO using a 3rd party FTP library is probably the best way to go.

**Comment by zertrin** [comment]
After diving a bit more in the issues here, I found issue #1350 which seems to be related to this one.

**Comment by kenkendk** [comment]
@zertrin: The comment in the source about `FTP servers that only support SSL during authentication` is that some servers are configured in a way, such that only the login (username and password) can use encryption. After this, the server requires that encryption is disabled before it will allow file transfers. Not sure how many of those servers are in the wild though.

I have not yet found a reliable FTP library with SSL support that could be used, but if you find one, I will be happy to take a look.
