### ISSUE TITLE
SSH Backend should support keyfiles

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#153]
_From [kenneth....@gmail.com](https://code.google.com/u/117596759558990029378/) on January 18, 2010 20:05:10_

The managed SSH backend currently has no support for key files.
SharpSSH apparently supports key files, so it should be a breeze to add this.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=153_

**Comment by grinsted** [comment]
Perhaps this has some clues on how to integrate with pageant: https://github.com/dimov-cz/win-sshfs

**Comment by kenkendk** [comment]
Yes, I think this is the one:
https://github.com/dimov-cz/win-sshfs/commit/8eb20b34ec27c430cf3d235fb588ed4aa71a937f

**Comment by kenkendk** [comment]
I've created issue #1557 to track the authentication agent issue
