### ISSUE TITLE
Can't backup unix root filesystem: "Path cannot contain a zero-length string"

### ISSUE THREAD

**Issue by mach-o** [duplicati/duplicati#1532]
When you try to back up "/", duplicati seems to strip away the slash and the backup fails.

`# mono Duplicati.CommandLine.exe backup $root_target "/."`
`Backup started at 2016-01-04 3:47:47 PM`
`Checking remote backup ...`
`  Listing remote folder ...`
`Scanning local files ...`
`Failed to process path: / => Path cannot contain a zero-length string`
`Parameter name: path`
`Compacting remote backup ...`
`Compacting not required`
`Checking remote backup ...`
`  Listing remote folder ...`
`  Duration of backup: 00:00:05`
`  Files added: 0`
`  Files deleted: 0`
`  Files changed: 0   Data uploaded: 0 bytes`
`  Data downloaded: 0 bytes`
`No files were processed. If this was not intentional you may want to use the "test-filter" command`
`Backup completed successfully!`

See [my post to the mailing list](https://groups.google.com/forum/#!topic/duplicati/DAxQ2UOqKvY) for more details.

**Comment by mach-o** [comment]
So the error happens at [BackupHandler.cs:116](https://github.com/duplicati/duplicati/blob/a51399145b85e8c4cdee835ec852e11a6fd72cec/Duplicati/Library/Main/Operation/BackupHandler.cs#L116) (I'm not sure how to make that link revision-independent, sorry).

I'd be happy to fix this (and other duplicati bugs) if I could get a mono debugger to work properly on Ubuntu. I installed MonoDevelop, which compiles duplicati without issue, but I wasn't able to get its debugger working, and wasn't able to find any documentation explaining how to do so, [as I mention in this mailing list post](http://lists.ximian.com/pipermail/monodevelop-list/2016-January/016445.html). If anyone has pointers to a Ubuntu-compatible mono debugger tutorial, please let me know.

**Comment by kenkendk** [comment]
The BackupHandler.cs link you point to is calling "IsBlockDevice", which is the one stripping the slash:
https://github.com/duplicati/duplicati/blob/a51399145b85e8c4cdee835ec852e11a6fd72cec/Duplicati/Library/Snapshots/LinuxSnapshot.cs#L482

The reason for this is that Duplicati uses a trailing slash to indicate a directory, and the absence of one to indicate a slash. This works well for the most part, but some of the POSIX calls dislike the trailing slash, thus it is stripped, which also works well. In this particular case, it should be enough to check if the path is "/", and in that case not strip the slash.

Perhaps there are other places this needs to be done as well.

For the debugger, I have not had any issues. I just installed MonoDevelop and it worked right away.
Do you have this package: http://packages.ubuntu.com/trusty/monodevelop-debugger-gdb ?

**Comment by mach-o** [comment]
Excellent, thanks. I'll have a look at the code when I get a chance.

I don't have monodevelop-debugger-gdb installed: though it's available in the repository for Ubuntu's "trusty" release, they seem to have removed it for the "vivid" release that followed, as with the subsequent "wily" release, which I'm now on. Perhaps it was integrated into the main monodevelop package?

**Comment by mach-o** [comment]
It turns out that in my case BackupHandler.cs calls the "IsBlockDevice" method in the NoSnapshotLinux class (NoSnapshotLinux.cs). I replaced all of the occurrences similar to:

`file.EndsWith(DIR_SEP) ? file.Substring(0, file.Length - 1) : file`

with

`System.IO.Path.GetFullPath(file)`

which did the trick, sort of. Although I no longer get the error message, it still doesn't seem to recurse into the subdirectories:

```$ mono ./Duplicati.CommandLine.exe backup $root_target / --no-encryption
Backup started at 2016-01-12 2:43:05 PM
Checking remote backup ...
  Listing remote folder ...
Scanning local files ...
Compacting remote backup ...
Compacting not required
Checking remote backup ...
  Listing remote folder ...
  Duration of backup: 00:00:00
  Files added: 0
  Files deleted: 0
  Files changed: 0
  Data uploaded: 0 bytes
  Data downloaded: 0 bytes
No files were processed. If this was not intentional you may want to use the "test-filter" command
Backup completed successfully!```

I'll keep playing around with this, but the problem seems to run deeper than I hoped.

**Comment by mach-o** [comment]
Ok, I think I've got it. Like you suggested, it was just more occurrences of the same problem strewn about the code. I'll submit a pull request soon and you can see if it looks sane to you.
