### ISSUE TITLE
Restore to alternate location in 2.0.0.91- 2.0.0.91_preview_2015-11-18

### ISSUE THREAD

**Issue by mattwhitfield** [duplicati/duplicati#1533]
I have been trying to test restore in 2.0.0.91 and haven't managed to get it to restore anything at all to a new location. I get a result like this in the log (note that the file path mentioned is the path I asked it to restore to, the application was running under an account that had full permissions to that path, and the file did not exist at any point during the process, and duplicati brought up a dialog telling me that the files had been successfully restored after this).

FilesRestored: 0
SizeOfRestoredFiles: 0
FoldersRestored: 0
SymlinksRestored: 0
FilesPatched: 0
FilesDeleted: 0
FoldersDeleted: 0
SymlinksDeleted: 0
VerboseOutput: False
VerboseErrors: False
Messages: [Searching backup 0 (06/01/2016 11:29:11) ..., 1 remote files are required to restore]
Warnings: [Failed to patch file: "C:\Users\Matt Whitfield\Documents\Application Data.7z" with local data, message: Access to the path 'C:\Users\Matt Whitfield\Documents\Application Data.7z' is denied. => Access to the path 'C:\Users\Matt Whitfield\Documents\Application Data.7z' is denied., Failed to patch file: "C:\Users\Matt Whitfield\Documents\Application Data.7z", message: Access to the path 'C:\Users\Matt Whitfield\Documents\Application Data.7z' is denied., message: Access to the path 'C:\Users\Matt Whitfield\Documents\Application Data.7z' is denied. => Access to the path 'C:\Users\Matt Whitfield\Documents\Application Data.7z' is denied., Access to the path 'C:\Users\Matt Whitfield\Documents\Application Data.7z' is denied. => Access to the path 'C:\Users\Matt Whitfield\Documents\Application Data.7z' is denied., Failed to apply metadata to file: "C:\Users\Matt Whitfield\Documents\Application Data.7z", message: Could not find file 'C:\Users\Matt Whitfield\Documents\Application Data.7z'. => Could not find file 'C:\Users\Matt Whitfield\Documents\Application Data.7z'., Could not find file 'C:\Users\Matt Whitfield\Documents\Application Data.7z'. => Could not find file 'C:\Users\Matt Whitfield\Documents\Application Data.7z'.]
Errors: []

Looking at what it's doing in Process Monitor - I see this - the path starting with \\ruby is the original location:

21:13:11.3588542	Duplicati.GUI.TrayIcon.exe	12268	CreateFile	C:\Users\Matt Whitfield\Documents\Application Data.7z	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
21:13:11.9936703	Duplicati.GUI.TrayIcon.exe	12268	CreateFile	\\ruby\backups\Phoenix\Protected\OldWork\Application Data.7z	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
21:13:11.9943418	Duplicati.GUI.TrayIcon.exe	12268	QueryNetworkOpenInformationFile	\\ruby\backups\Phoenix\Protected\OldWork\Application Data.7z	SUCCESS	CreationTime: 02/06/2015 02:02:44, LastAccessTime: 06/01/2016 20:57:31, LastWriteTime: 02/06/2015 02:02:44, ChangeTime: 02/06/2015 02:02:44, AllocationSize: 01/01/1601 00:00:00, EndOfFile: 01/01/1601 00:00:00, FileAttributes: A
21:13:11.9943704	Duplicati.GUI.TrayIcon.exe	12268	CloseFile	\\ruby\backups\Phoenix\Protected\OldWork\Application Data.7z	SUCCESS	
21:13:11.9949938	Duplicati.GUI.TrayIcon.exe	12268	CreateFile	C:\Users\Matt Whitfield\Documents\Application Data.7z	ACCESS DENIED	Desired Access: Generic Read/Write, Disposition: OverwriteIf, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: None, AllocationSize: 0
21:13:24.9090784	Duplicati.GUI.TrayIcon.exe	12268	CreateFile	C:\Users\Matt Whitfield\Documents\Application Data.7z	ACCESS DENIED	Desired Access: Generic Read/Write, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, AllocationSize: 0
21:13:24.9577532	Duplicati.GUI.TrayIcon.exe	12268	CreateFile	C:\Users\Matt Whitfield\Documents\Application Data.7z	ACCESS DENIED	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: None, AllocationSize: 0
21:13:24.9587458	Duplicati.GUI.TrayIcon.exe	12268	CreateFile	C:\Users\Matt Whitfield\Documents\Application Data.7z	NAME NOT FOUND	Desired Access: Generic Write, Read Attributes, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, Write, AllocationSize: n/a
21:13:24.9747638	Duplicati.GUI.TrayIcon.exe	12268	CreateFile	C:\Users\Matt Whitfield\Documents\Application Data.7z	NAME NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, Write, AllocationSize: n/a

If you need any more info or I can run any operations for you please let me know. Note that restoring to the original location does work - but it's obviously much preferable to restore to an alternate location - especially if testing.

**Comment by kenkendk** [comment]
I think this has been fixed
