### ISSUE TITLE
bug in create-lvm-snapshot.sh

### ISSUE THREAD

**Issue by cchris-org** [duplicati/duplicati#1534]
root@ubuntu:~/scripts/bugy# mono Duplicati.CommandLine.exe backup "file:///mnt/nfs/backup/test/bla/" '/home' --snapshot-policy="required" --no-encryption --backup-name="meins"

Backup started at 07.01.2016 12:04:18
Fatal error => Script returned successfully, but the output was missing the tmpdir parameter: Exit code: 0
  Logical volume "duplicati-b1506916-2b82-4af5-be92-e94d508d49fa" created
Error: mount -o ro "" "/tmp/duplicati-b1506916-2b82-4af5-be92-e94d508d49fa" failed!
  Logical volume "duplicati-b1506916-2b82-4af5-be92-e94d508d49fa" successfully removed

looks like a bug in create-lvm-snapshot.sh. 

LV_SNAPSHOT shoud give back the Path only and not name AND the path?

\- LV_SNAPSHOT=`lvdisplay "$LV_GROUP/$NAME" | grep "LV (Name|Path)" | awk '{ print $NF}'`
\+ LV_SNAPSHOT=`lvdisplay "$LV_GROUP/$NAME" | grep "LV Path" | awk '{ print $NF}'

After that little fix, it works without error.
Could it someone verify, please?

Thanks, Chris.

**Comment by kenkendk** [comment]
Ok, there seems to be different versions of lvdisplay.

The change you propose leads to "how it was":
2cfca2d9057c5c1b04b6ca7e831e56160ffc7274

There i s a discussion on the old site:
https://code.google.com/p/duplicati/issues/detail?id=875

As you can see, you are not the only one discovering this, but the comments were added after we migrated to Github: https://github.com/duplicati/duplicati/issues/902

What is the output of the `lvdisplay` command on your system?

**Comment by cchris-org** [comment]
```
lvdisplay 
  --- Logical volume ---
  LV Path                /dev/ubuntu-vg/root
  LV Name                root
  VG Name                ubuntu-vg
  LV UUID                65w1a3-3fdE-HxnM-T3f1-vfTX-E0b1-q3uARQ
  LV Write Access        read/write
  LV Creation host, time ubuntu, 2015-10-11 09:56:05 +0200
  LV Status              available
  # open                 1
  LV Size                6,64 GiB
  Current LE             1699
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           252:0
   
  --- Logical volume ---
  LV Path                /dev/ubuntu-vg/swap_1
  LV Name                swap_1
  VG Name                ubuntu-vg
  LV UUID                M6EvYg-kt1Q-6fxP-ksge-FyAJ-n5S4-IlZKDA
  LV Write Access        read/write
  LV Creation host, time ubuntu, 2015-10-11 09:56:05 +0200
  LV Status              available
  # open                 2
  LV Size                1020,00 MiB
  Current LE             255
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           252:1
```

**Comment by kenkendk** [comment]
Ok, so I think the right way is to first grab the `Path`.
If the result of that is empty, then try `Name` for backwards compatibility.
Would you be willing to write a patch for that (or just paste the modified script here, and I will merge)?

**Comment by kenkendk** [comment]
Could you test if this change works for you?

444922d1dfb5f9b4ee622cd8b4fdcc01a0e4f03d

**Comment by cchris-org** [comment]
thank you!
i will try, as soon as a machine is available :)

**Comment by kenkendk** [comment]
Any updates on this?

**Comment by steilerDev** [comment]
Works for me, but I don’t require the fallback solution (I get a proper path after `grep “LV Path”`)

**Comment by kenkendk** [comment]
Great, thanks for reporting back. I have merged the fix into master and it will be part of the next build.
