### ISSUE TITLE
Create a QNAP package

### ISSUE THREAD

**Issue by francescofoti** [duplicati/duplicati#1535]
Hi, I'm fighting to have duplicati2 work on QNAP NAS boxes since many months now.
One issue I had was that the sqlite3 library used by Duplicati was more recent than the one present on the QNPA boxes (x86_64). I solved the problem by compiling libsqlite3.so.0.8.6, and thanks to the "DllMap" feature of mono (see the discussion on the qnap forum here: http://forum.qnap.com/viewtopic.php?f=15&t=110246) duplicati 2 uses the good one.
So, on one of my customer QNAP NAS box (QNAP TS-559 Pro II), I've got a duplicati2 instance running perfectly since a while now. I used the "fake QPKG" technique (documented in their wiki) to have it start automatically at boot time. That's ok.
However, I can't make it work on another box, I posted this discussion in the group about that: https://groups.google.com/forum/#!topic/duplicati/896Dvo92Kzk .
I had to go back to version 2.0.0.73- 2.0.0.73_preview_2014-11-11, which works for me on the first NAS box. Seemed to be an issue with the mono runtime (Missing method System.Reflection.Assembly::get_DefinedTypes() in assembly /share/MD0_DATA/.qpkg/Mono/lib/mono/4.5/mscorlib.dll).
However, on my second box, duplicati2 doesn't start (Duplicati.Server.exe, no http response from the web interface), but doesn't output any message on the console. I'm lost.
Here's my startup script:
    #!/bin/sh
    TMPDIR=/share/MD0_DATA/devinfo.net/temp
    SQLITE_TMPDIR=/share/MD0_DATA/devinfo.net/temp
    LD_LIBRARY_PATH=/share/MD0_DATA/devinfo.net/backon:$LD_LIBRARY_PATH
    export TMPDIR=$TMPDIR
    export SQLITE_TMPDIR=$SQLITE_TMPDIR
    /share/MD0_DATA/.qpkg/Mono/bin/mono /share/MD0_DATA/devinfo.net/backon/Duplicati.Server.exe --webservice-port=8201 --blockhash-lookup-memory=0 --filehash-lookup-memory=0 --metadatahash-lookup-memory=0 --disable-filepath-cache
My final goal is to make distributable a QNAP package.
Francesco.
##

**Comment by kenkendk** [comment]
The DefinedTypes issue is fixed in 1f9961c919d4bbf588ea08b3d3a53ccea022abb8, so you can try using the latest version, which defaults to not use the lookup and cache.

Can you run the same command in a terminal to see what happens?
Can you see if the port is being listened to and if the process is running?

Duplicati prevents access to the server, by only binding to localhost (127.0.0.1) by default.
For testing, you can try to add `--webservice-interface=any`, to rule out that it is a network issue.
I do not think that Duplicati is safe enough to use the `--webservice-interface=any` option in production.

**Comment by dmitryint** [comment]
Duplicati can be run in Docker. I heard that QNAP supports it.
https://hub.docker.com/r/intersoftlab/duplicati/

**Comment by francescofoti** [comment]
Awsome. The --webservice-interface=any finally solved my problem with the 2.0.0.73 (old) version, I now got the duplicati interface up. I'll test the latest one if it passes the DefinedTypes issues.
Unfortunately Docker (Container station on qnap) is not available for QNAP models I served to my customers (TS-x69).
Anyway, I got another question, regarding the updater. I installed duplicati under the root account on the QNAP boxes, but when I got the new version alert, if I choose "update", the update fails. Any tip to help me find where that happens ?
And yet another question. I would like to update duplicati's web interface to include my company's logo, as we "package" duplicati as a service (called "backon") including setup, monitoring and cloud disk space on our swiss servers. I of course do not want to claim we own anything in duplicati in anyway, but we would like to lightly dress up the interface. To be honest I already did that on the login screen and on the main screen, although making it clear that the software is (powered by) duplicati. Am I infringing something here ? - We're developers and we clearly respect the work of our fellows, so any directions on how to do that respectfully, and in order to survive automatic updates, would be welcome.
Again, thank you very much for your help.

**Comment by kenkendk** [comment]
For the `--webservice-interface=any`, beware that anyone on the local network (including VPNs, SSH forwards, etc) can access the service. The service has not been hardened, and may contain security holes of all kinds. The password helps some, but I do not recommend relying on the password as the only security measure at this time.

Regarding the update error, do you see something in the log? Duplicati will probe a few locations to see if it can find a writeable folder to install updates in, but if it finds none, it will fail.

For the rebranding: Duplicati is open source under the LGPL, and you should consult your lawyer or similar to figure out exactly what that means for you.

My understanding of the license is that you may make any changes you wish to the source (including removal of logos etc). But, if you _distribute_ binaries with modified source code, you must also make the source code with changes available to the customers with the modified binaries.

Rebranding features is a common request, so I have attempted to make it smooth to change the name of the application and add a small "- powered by Duplicati" linie. This work is not complete, and patches for rebranding support are welcome :).

Generally, you can start by editing the files in the `oem` folder. The `oem` files are expected to be included in the update, and are always loaded from the latest update. You can build your own updates, using the script `make-preview-update.sh`, and sign them with your own key. You can then host these updates on any HTTP compliant server.

If you want less involvement in the process, you can change the script and css file in the `custom` folder. This is intended for users who wishes to tweak the UI on their local install only. The `custom` files are always loaded from the source installation folder, not from the update folder.

**Comment by francescofoti** [comment]
So I wanted to try to bind the server to the machine IP, ie something like `--webservice-interface=192.168.1.100`. I reinstalled Duplicati on the QNAP box, tried the update feature that this time...worked. Leaving me unfortunately with the DefinedTypes() issue on the newly auto-installed version.

So I downloaded duplicati's source code (to have your patch). Unfortunately I couldn't compile under VS2013, but I could did it on MonoDevelop (Xamarin Studio) in Ubuntu linux and on windows (tip: don't forget to specify mono as your active runtime or you'll lose your head on the 'System.Security.dll' missing reference...). Anyway, I prefer to stay on Windows if possible.

I took a look inside the 'deploy_debug.sh' script (although I built the release versions), that seems to gather together the binaries in the GUI and Server/webroot folders, for the distribution; is that correct ? I don't really understand what the build-msi.bat batch does (maybe build and msi package, but it seems to delete the Server\webroot folder recursively and I don't need it as I'll copy the files on a QNAP box).

Also, I don't understand the 'oem' build process; I have no 'oem' folder anywhere.
I looked at the 'install_oem.sh' script, but don't really know what to make of it either. A I missing a documentation on all of that to be found somewhere ? Or can you point me in the right directions ?

If I can figure out what I can package together to redistribute the 'built from source' version of Duplicati, I'll be able to try `DefinedTypes` patch and carefully try to make my custom installer.
I spent some time on the update process either, trying to make some sense from the build-preview-update.sh but I still can't really figure it out...

Can I just simply copy the contents of C:\duplicati-master\Duplicati\GUI\Duplicati.GUI.TrayIcon\bin\Release and C:\duplicati-master\Duplicati\Server\bin\Release and C:\duplicati-master\Duplicati\Server\webroot in the same folder on the target machine to have Duplicati work ?

Thanks again, Francesco.

**Comment by kenkendk** [comment]
I will make a new build soon, which fixes the issue with `DefinedTypes`. I think VS2013 is too old, you can try the free VS2015 Community Edition:
https://www.visualstudio.com/vs-2015-product-editions

The installation package is really just taking all files from `Duplicati/GUI/Duplicati.GUI.TrayIcon.exe/bin/Release` and the `webroot` folder from `Duplicati/Server/webroot`. You can delete all the `.mdb` and `.pdb` files if they are present. True "copy-to-install" style :).

The script for `build-preview-release.sh` is what I use to build a package with autoupdate support. Appart from building the project, it also signs the zip file in a special way, using a pre-generated private key, and embeds the update url and public key inside the output. This ensures that the updater will only install updates that are signed with the same key. It is tested for OSX use only, so it may or may not work for you.

The `oem` packaging is not entirely integrated just yet, and the same goes for building installers. The code in `Installer` has not been maintained, but you can see the rough ideas there. The idea is that you put in an oem.js and oem.css file inside the `Installer` folder (should probably be changed to look outside the current source, or use an environment variable). These will then be copied into the `webroot/oem` folder when you build an installer.

**Comment by ts678** [comment]
> Create a QNAP package

> My final goal is to make distributable a QNAP package.

`https://www.qnapclub.eu/en/qpkg/369` offers a third-party QNAP package with the latest Canary and also a list of older versions.

[Branding and OEM customization](https://github.com/duplicati/duplicati/wiki/Branding-and-OEM-customization) is worth reading if you're still pursuing the goal. If not, is there still a need to keep its issue open?
