### ISSUE TITLE
Onedrive internal server error depending on order of entries in parameters-file

### ISSUE THREAD

**Issue by florianbartels** [duplicati/duplicati#1538]
I'm running Duplicati 2.0.0.91_preview_2015-11-18 on a Synology NAS with mono 3.12.1 and following command:
``` _mono Duplicati.CommandLine.exe --parameters-file=runonedrive.conf backup onedrive://backup-nas-test-500/ /volume2/Pics_```

# try 1 of runonedrive.conf
 * content (authid and passphrase are on the top instead at the end):

```
--authid=blabla
--passphrase=blabla
--asynchronous-upload-limit=2
--asynchronous-upload-folder=/volume2/Backups
--auto-cleanup=true
--backup-test-samples=5
--log-file=runbackup.log
--log-level=Information
```
 * Result: Upload **fails** with error 500
 * Error message:

> Operation Put with file duplicati-b1fa504b05ee4430eac0b45e398fb600c.dblock.zip.aes attempt 5 of 5 failed with message: The remote server returned an error: (500) Internal Server Error. => The remote server returned an error: (500) Internal Server Error._

# try 2 of runonedrive.conf (authid and passphrase are on the end instead of the top):
 * content: 
```--asynchronous-upload-limit=2
--asynchronous-upload-folder=/volume2/Backups
--auto-cleanup=true
--backup-test-samples=5
--log-file=runbackup.log
--log-level=Information
--authid=blabla
--passphrase=blabla 
```
 * Result: Upload **succeeds**!

Downloading worked in both cases.
As far as I understood the manual, the order of entries in the configuration file should not be relevant. It would be very interesting to understand the root cause of this issue. :-)

**Comment by florianbartels** [comment]
After playing around for some timee with many different settings, I come to the conclusion that uploading of files to onedrive seems to be a bit unstable at the moment, especially with bigger files like the default 50mb. With 10mb it seems to be working better.

**Comment by kenkendk** [comment]
I would be _very_ surprised if the order matters. Internally the options are stored in a dictionary, which does not retain the order anyway.

Is it the same authid ?
Can you repeat the behavior by switching the files?

**Comment by kenkendk** [comment]
Closing for lack of feedback
