### ISSUE TITLE
web interface not running on raspberry pi

### ISSUE THREAD

**Issue by shashank-g** [duplicati/duplicati#1539]
I'm trying to run duplicati 2.0 on arch setup on raspberry pi. Even though it installed properly, running /usr/bin/mono /opt/duplicati-latest/Duplicati.Server.exe --webservice-port=8200 gives this:

Another instance is running, and was notified

and the web-interface is inaccessible.
##

**Comment by kenkendk** [comment]
That message indicates that another process has created and locked a file in `~/.config/Duplicati/control_dir_v2`.

Is that folder write-able by the current user? Does it contain a file called `lock_v2` ?

**Comment by shashank-g** [comment]
The folder is in the home directory of current user and it does contain lock_v2 file.

**Comment by kenkendk** [comment]
If you are sure there are no running Duplicati processes, try to delete the file and start Duplicati again.

**Comment by shashank-g** [comment]
Ok. Deleted file lock_v2 and ran the same command again. This time I got this:

A serious error occured in Duplicati: System.Exception: Unable to open a socket for listening, tried ports: 8200
  at Duplicati.Server.WebServer.Server..ctor (IDictionary`2 options) <0xb3c11df8 + 0x007fc> in <filename unknown>:0
  at Duplicati.Server.Program.RealMain (System.String[] args) <0xb43085c0 + 0x01d27> in <filename unknown>:0

Running  with a random port sends the terminal in a limbo.

**Comment by kenkendk** [comment]
That seems to indicate that something is listening on port 8200.
It could also be a security feature that prevents Duplicati from listening.

You can try running this command to see if something is using the port:
`netstat -n -p tcp | grep 8200`

**Comment by shashank-g** [comment]
Netstat command doesn't give any thing. Pl help.

**Comment by mohakshah** [comment]
I was getting the same error on my raspberry pi too.
``A serious error occured in Duplicati: System.Exception: Unable to open a socket for listening, tried ports: 8200``

I finally succeeded after changing the port to a higher one (in the 10 thousands) with the argument
``--webservice-port=40000``
