### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by ccontato** [duplicati/duplicati#1540]
I cant configure the e-mail notification. I setup the backup with the browser and the guitrayicon and added this on the Advanced Options:
--send-mail-to="myemail"
--send-mail-from="myemail@gmail.com"
--send-mail-subject="Duplicati %OPERATIONNAME% Report"
--send-mail-body="%RESULT%%"
--send-mail-url="tls://smtp.google.com:587"
--send-mail-username="mayemail@gmail.com"
--send-mail-password="mypassword"
--send-mail-level="Warning"
--send-mail-any-operation="true"

What is wrong?
Im using You are currently running Duplicati

2.0.0.91- 2.0.0.91_preview_2015-11-18
##

**Comment by ccontato** [comment]
In the live log there is: Failed to send email: System.UriFormatException: URI inválido: esquema URI inválido.

**Comment by kenkendk** [comment]
That seems to indicate that "tls://smtp.google.com:587" is not parsed correctly. Do you see more information in the log, like a stack trace or so?

Can you try to add `--verbose=true` to the advanced options to see if there is more information?

**Comment by ccontato** [comment]
I tried --send-mail-url="tls://smtp.gmail.com:587" too.
I added  --verbose=true, but nothing happened.
In the live log there this:  12/01/2016 08:26:44 
Failed to send email: System.UriFormatException: URI inválido: esquema URI inválido.

**Comment by kenkendk** [comment]
What happens if you click on that message?

**Comment by ccontato** [comment]
shows this: [object Object]
