### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by syrys** [duplicati/duplicati#1541]
Unable to install the version 1.3.4 on a windows 10 machine with the provided installers.

Error: "The .net framework 2.0 must be installed ()"

installs fine on a windows 8.1 machine.

**Comment by kenkendk** [comment]
I am no longer maintaining Duplicati 1.3.x. You can try Duplicati 2.0, but it is still in the preview phase.

**Comment by syrys** [comment]
@kenkendk 2.0 runs fine, im just a bit worried about using a "preview" version. Is it stable enough to use for important backups? Is there an ETA on a stable release?

**Comment by agrajaghh** [comment]
version 1.3 is not maintained anymore, but we are working on Duplicati 2.0 to become stable soon

**Comment by stefan-muc** [comment]
Just as the error message says: You need .NET Framework 2.0
So go to Programs and Features -> Turn Windows features on or off -> [x] .NET Framework 3.5 (includes .NET 2.0 and 3.0) -> [OK] -> Download files from Windows Update -> wait a minute -> [Close]

Now you are ready to install Duplicati 1.3.4
