### ISSUE TITLE
Update download location

### ISSUE THREAD

**Issue by tsparber** [duplicati/duplicati#1545]
As Google Code will be dead on [25 Jan](http://google-opensource.blogspot.com.au/2015/03/farewell-to-google-code.html), would you mind to move the [1.3.4 release files](http://www.duplicati.com/news/duplicati134available) to somewhere else? ( eq. [GitHub releases](https://github.com/blog/1547-release-your-software))

(Refs https://github.com/caskroom/homebrew-cask/issues/17075)

**Comment by kenkendk** [comment]
Duplicati 1.3.x is no longer in development, so I would not like host the files somewhere else than Github.

You can reference them from the archive page: 
https://code.google.com/archive/p/duplicati/downloads

Is that sufficient for solving the issue?

**Comment by adidalal** [comment]
Is there a .dmg/ .app release for 2.x?

**Comment by kenkendk** [comment]
No, there are no installers at this moment. The current version 2.0 is still under development. Once we consider it stable, there will be installers for all the major operating systems.

**Comment by tsparber** [comment]
@kenkendk Thanks for pointing me to the google code archive. I'm not sure if google will automatically redirect (after 25.01.) and updated the cask accordingly (https://github.com/caskroom/homebrew-cask/pull/17329). Would you mind to update http://www.duplicati.com/news/duplicati134available too?

**Comment by tsparber** [comment]
@kenkendk Sorry to bother you again. But the google archive links seem to be broken too.
https://storage.googleapis.com/google-code-archive-downloads/v1/code.google.com/duplicati/Duplicati%201.3.4.dmg -> 404.

**Comment by tsparber** [comment]
https://github.com/caskroom/homebrew-cask/issues/17075#issuecomment-172863763

**Comment by kenkendk** [comment]
From what I understand, the archive page will exist for a number of years.

But the bug with spaces is really annoying :)

If they do not manage to fix this, I have a copy of the most recent files and can host them.

**Comment by tsparber** [comment]
I filed a bug there (https://code.google.com/p/support-tools/issues/detail?id=175) and it got accepted, so maybe they will fix it :smiley:
