### ISSUE TITLE
Maybe the database files should not be in the temp folder?

### ISSUE THREAD

**Issue by irregularisnotrandom** [duplicati/duplicati#1550]
HI

It is not uncommon for people to clean their temp folders or use cleaning apps that wipes the temp folders regularly.

I happened to do that and one of my backups got corrupted because of missing some index files.

Thanks
##

**Comment by kenkendk** [comment]
If you delete the files while Duplicati is running, I expect bad things to happen. Otherwise there should be nothing stored in the temp folder. 

What is the exact error message?
How did you conclude that it occurred because of deleting temp files?

**Comment by irregularisnotrandom** [comment]
I do not remember the message to be honest, buti it said something like missing index or database file. 

If the backup is big and takes a long time, it is likely that a cleaning up program might clean files from the temp folder by accident within that time frame. Just saying. 

I backed up about 150gb on the network, and it took a long time naturally.
