### ISSUE TITLE
it does not run on Arm Linux

### ISSUE THREAD

**Issue by irregularisnotrandom** [duplicati/duplicati#1551]
/opt/duplicati_II # mono Duplicati.Server.exe --webservice-port=8200                                                                                                   Missing method .ctor in assembly /opt/duplicati_II/Newtonsoft.Json.dll, type System.Runtime.CompilerServices.ExtensionAttribute
Can't find custom attr constructor image: /opt/duplicati_II/Newtonsoft.Json.dll mtoken: 0x0a000075
* Assertion at class.c:5597, condition `!mono_loader_get_last_error ()' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at Duplicati.Library.AutoUpdater.UpdaterManager.ReadInstalledManifest (string) <0x00103>
  at Duplicati.Library.AutoUpdater.UpdaterManager..cctor () <0x0036b>
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at Duplicati.Server.Program..cctor () <0x0000b>
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

Debug info from gdb:

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

[1]    25308 abort (core dumped)  mono Duplicati.Server.exe --webservice-port=8200

**Comment by kenkendk** [comment]
Which version of Mono is this?

Could you try the tracing options described here:
http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/

Specifically:
`MONO_LOG_LEVEL=debug mono Duplicati.Server.exe --webservice-port=8200`

This should show how the loader finds the `Newtonsoft.Json.dll` assembly and perhaps give a hint as to why it cannot find the constructor it looks for.

**Comment by irregularisnotrandom** [comment]
Thanks for the follow up. 

I do not have the device with me now but it is the version of Mono that comes with Debian .Jessie

I will enable debug options next time I will try it on the device.

**Comment by irregularisnotrandom** [comment]
Mono: AOT module '/opt/duplicati_II/Duplicati.Server.Serialization.dll.so' not found: /opt/duplicati_II/Duplicati.Server.Serialization.dll.so: cannot open shared object file: No such file or directory

Mono: Assembly Loader loaded assembly from location: '/opt/duplicati_II/Duplicati.Server.Serialization.dll'.
Mono: Config attempting to parse: '/opt/duplicati_II/Duplicati.Server.Serialization.dll.config'.
Mono: Config attempting to parse: '/etc/mono/assemblies/Duplicati.Server.Serialization/Duplicati.Server.Serialization.config'.
Mono: Assembly Ref addref Duplicati.Server[0x9d5d20] -> Duplicati.Server.Serialization[0x9dbd98]: 2
Mono: Assembly Loader probing location: '/opt/duplicati_II/Duplicati.Library.Logging.dll'.
Mono: Image addref Duplicati.Library.Logging[0x9de540] -> /opt/duplicati_II/Duplicati.Library.Logging.dll[0x9ddbc8]: 2
Mono: Assembly Duplicati.Library.Logging[0x9de540] added to domain Duplicati.Server.exe, ref_count=1
Mono: AOT module '/opt/duplicati_II/Duplicati.Library.Logging.dll.so' not found: /opt/duplicati_II/Duplicati.Library.Logging.dll.so: cannot open shared object file: No such file or directory

Mono: Assembly Loader loaded assembly from location: '/opt/duplicati_II/Duplicati.Library.Logging.dll'.
Mono: Config attempting to parse: '/opt/duplicati_II/Duplicati.Library.Logging.dll.config'.
Mono: Config attempting to parse: '/etc/mono/assemblies/Duplicati.Library.Logging/Duplicati.Library.Logging.config'.
Mono: Assembly Ref addref Duplicati.Server[0x9d5d20] -> Duplicati.Library.Logging[0x9de540]: 2
Mono: Assembly Loader probing location: '/opt/duplicati_II/Duplicati.Library.AutoUpdater.exe'.
Mono: Image addref Duplicati.Library.AutoUpdater[0x9e3778] -> /opt/duplicati_II/Duplicati.Library.AutoUpdater.exe[0x9e2e28]: 2
Mono: Assembly Duplicati.Library.AutoUpdater[0x9e3778] added to domain Duplicati.Server.exe, ref_count=1
Mono: AOT module '/opt/duplicati_II/Duplicati.Library.AutoUpdater.exe.so' not found: /opt/duplicati_II/Duplicati.Library.AutoUpdater.exe.so: cannot open shared object file: No such file or directory

Mono: Assembly Loader loaded assembly from location: '/opt/duplicati_II/Duplicati.Library.AutoUpdater.exe'.
Mono: Config attempting to parse: '/opt/duplicati_II/Duplicati.Library.AutoUpdater.exe.config'.
Mono: Config attempting to parse: '/etc/mono/assemblies/Duplicati.Library.AutoUpdater/Duplicati.Library.AutoUpdater.config'.
Mono: Assembly Ref addref Duplicati.Server[0x9d5d20] -> Duplicati.Library.AutoUpdater[0x9e3778]: 2
Mono: Assembly Ref addref Duplicati.Library.AutoUpdater[0x9e3778] -> mscorlib[0x99c168]: 4
Mono: Assembly Loader probing location: '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll'.
Mono: Image addref System[0x9f3368] -> /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll[0x9f2c88]: 2
Mono: Assembly System[0x9f3368] added to domain Duplicati.Server.exe, ref_count=1
Mono: AOT module '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll.so' not found: /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll.so: cannot open shared object file: No such file or directory

Mono: Assembly Loader loaded assembly from location: '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll'.
Mono: Config attempting to parse: '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll.config'.
Mono: Config attempting to parse: '/etc/mono/assemblies/System/System.config'.
Mono: Assembly Ref addref Duplicati.Server[0x9d5d20] -> System[0x9f3368]: 2
Mono: Assembly Ref addref System[0x9f3368] -> mscorlib[0x99c168]: 5
Mono: Assembly Ref addref Duplicati.Library.Logging[0x9de540] -> mscorlib[0x99c168]: 6
Mono: Assembly Ref addref Duplicati.Library.AutoUpdater[0x9e3778] -> Duplicati.Library.Utility[0x9d9fb0]: 3
Mono: Assembly Loader probing location: '/usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll'.
Mono: Image addref Mono.Security[0xa41958] -> /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll[0xa4b480]: 2
Mono: Assembly Mono.Security[0xa41958] added to domain Duplicati.Server.exe, ref_count=1
Mono: AOT module '/usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll.so' not found: /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll.so: cannot open shared object file: No such file or directory

Mono: Assembly Loader loaded assembly from location: '/usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll'.
Mono: Config attempting to parse: '/usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll.config'.
Mono: Config attempting to parse: '/etc/mono/assemblies/Mono.Security/Mono.Security.config'.
Mono: Assembly Ref addref Mono.Security[0xa41958] -> mscorlib[0x99c168]: 7
Mono: Assembly Loader probing location: '/opt/duplicati_II/Newtonsoft.Json.dll'.
Mono: Image addref Newtonsoft.Json[0xa895d8] -> /opt/duplicati_II/Newtonsoft.Json.dll[0xab31f8]: 2
Mono: Assembly Newtonsoft.Json[0xa895d8] added to domain Duplicati.Server.exe, ref_count=1
Mono: AOT module '/opt/duplicati_II/Newtonsoft.Json.dll.so' not found: /opt/duplicati_II/Newtonsoft.Json.dll.so: cannot open shared object file: No such file or directory

Mono: Assembly Loader loaded assembly from location: '/opt/duplicati_II/Newtonsoft.Json.dll'.
Mono: Config attempting to parse: '/opt/duplicati_II/Newtonsoft.Json.dll.config'.
Mono: Config attempting to parse: '/etc/mono/assemblies/Newtonsoft.Json/Newtonsoft.Json.config'.
Mono: Assembly Ref addref Duplicati.Library.AutoUpdater[0x9e3778] -> Newtonsoft.Json[0xa895d8]: 2
Mono: The request to load the assembly mscorlib v2.0.0.0 was remapped to v4.0.0.0
Mono: Assembly Ref addref Newtonsoft.Json[0xa895d8] -> mscorlib[0x99c168]: 8
Mono: Assembly Ref addref Duplicati.Library.AutoUpdater[0x9e3778] -> System[0x9f3368]: 3
Mono: The request to load the assembly System.Core v3.5.0.0 was remapped to v4.0.0.0
Mono: Assembly Loader probing location: '/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll'.
Mono: Assembly Loader probing location: '/opt/duplicati_II/System.Core.dll'.
Mono: Assembly Loader probing location: '/usr/lib/System.Core.dll'.
Mono: Assembly Loader probing location: '/usr/lib/mono/4.5/Facades/System.Core.dll'.
Mono: Assembly Loader probing location: '/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.exe'.
Mono: Assembly Loader probing location: '/opt/duplicati_II/System.Core.exe'.
Mono: Assembly Loader probing location: '/usr/lib/System.Core.exe'.
Mono: Assembly Loader probing location: '/usr/lib/mono/4.5/Facades/System.Core.exe'.
Mono: The following assembly referenced from /opt/duplicati_II/Newtonsoft.Json.dll could not be loaded:
     Assembly:   System.Core    (assemblyref_index=3)
     Version:    3.5.0.0
     Public Key: b77a5c561934e089
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (/opt/duplicati_II/).

Mono: Failed to load assembly Newtonsoft.Json[0xa895d8]

Mono: Could not load file or assembly 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
Missing method .ctor in assembly /opt/duplicati_II/Newtonsoft.Json.dll, type System.Runtime.CompilerServices.ExtensionAttribute
Can't find custom attr constructor image: /opt/duplicati_II/Newtonsoft.Json.dll mtoken: 0x0a000075
* Assertion at class.c:5597, condition `!mono_loader_get_last_error ()' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at Duplicati.Library.AutoUpdater.UpdaterManager.ReadInstalledManifest (string) <0x00103>
  at Duplicati.Library.AutoUpdater.UpdaterManager..cctor () <0x0036b>
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at Duplicati.Server.Program..cctor () <0x0000b>
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:


Debug info from gdb:


=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

[1]    6754 abort (core dumped)  MONO_LOG_LEVEL=debug mono Duplicati.Server.exe --webservice-port=8200

**Comment by kenkendk** [comment]
I think you need "System.Linq" which is found in the Mono assembly "System.Core".
The debian package is this:
https://packages.debian.org/wheezy/libmono-system-core4.0-cil

You may want to do: `sudo apt-get install mono-complete` to pull in all Mono packages.
At the moment I do not have a complete list of all required dependencies, but `mono-complete` covers everything in one go.

**Comment by kenkendk** [comment]
This should be fixed now, and the required libraries are listed in the debian package:
https://github.com/duplicati/duplicati/blob/master/Installer/debian/debian/control#L12
