### ISSUE TITLE
S3 Bucket name issues

### ISSUE THREAD

**Issue by ERamseth** [duplicati/duplicati#1553]
On Linux I'm backing up via command line with something like:

```mono "/opt/duplicati-latest/Duplicati.CommandLine.exe" backup s3://bucket/backup-duplicati "backup_root" --aws_secret_access_key="xxx" --aws_access_key_id="xxx"```

I wanted to browse/test the backup in windows but when I put all the relevant info into the duplicati web interface I get:

```The bucket name should start with your username, append automatically?```

And whether I say yes or no I then get

```The folder does not exist 
Create it now?```

But in linux I can backup, list, restore, etc using the credentials as shown. So how do I access my backups from windows?

**Comment by kenkendk** [comment]
Instead of using the edit page try just pasting the connection url into the restore dialog.

Since you get "folder does not exists", I assume there is something different in the url?

**Comment by kenkendk** [comment]
Closing due to lack of feedback
