### ISSUE TITLE
Warnings: [Failed to process path: {FilenameRemoved}.mdb => Too large metadata, cannot handle more than 102400 bytes]

### ISSUE THREAD

**Issue by radeonorama** [duplicati/duplicati#1554]
Hey,

Very new to this rather handy app and seem to be having an issue backing up a particular file. 

The log just reads as the title says. 

Is there a limit i can increase to fix it to resolve the problem or is it a bug?

The file size is just  159mb with other files being larger and happily backed up fine. 

Currently running Duplicati 2.0.0.91- 2.0.0.91_preview_2015-11-18

Any help would be greatly appreciated.

Thanks very much in advance. 
##

**Comment by radeonorama** [comment]
So I think I have the solution of adding the option param with an increased blocksize to 250kb. Frustratingly but understandably having to rerun the entire backup with the new blocksize to find out. 16gb's to go and I'll be able to confirm if it's fixed the issue.

**Comment by kenkendk** [comment]
There is nothing architecturally that needs to change to accomodate larger metadata blocks. But there is a lot of code that needs to be updated to no longer assume metadata can fit in a single block.

Do you know what kind of metadata is stored on the file to take up so much space?

**Comment by gtangt** [comment]
Have had same problem backing up from our NAS from a range of file types; jpg's, psd's, indd's . Tried among other things to open each file and over-save the old files - that seems to have helped.

**Comment by kenkendk** [comment]
Do you know what metadata is attached to the files since it takes up so much space?

**Comment by gtangt** [comment]
Check these two files. Duplicate was able to back up the file after it was reserved from photoshop. 

![studiox_005 same but resaved](https://cloud.githubusercontent.com/assets/16959761/13419461/1e07f898-df87-11e5-99c0-243cfff270b2.jpg)
![studiox_005 too large metadata](https://cloud.githubusercontent.com/assets/16959761/13419475/2cf9bb7a-df87-11e5-8d21-b96a434e2d07.jpg)

**Comment by ohthetrees** [comment]
I am getting many metadata errors (so far 50) which are perhaps related. There seem to be two types:

```
Failed to process path: /Users/cedar/Documents/AWS_Starcluster HOWTO/Icon
System.IO.InvalidDataException: Too large metadata, cannot handle more than 102400 bytes
  at Duplicati.Library.Main.Operation.BackupHandler.AddFileToOutput (Duplicati.Library.Main.BackendManager backend, System.String filename, Int64 size, DateTime lastmodified, IMetahash metadata, IEnumerable`1 hashlist, System.String filehash, IEnumerable`1 blocklisthashes) <0x9471070 + 0x00277> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) <0x93e5cd8 + 0x022eb> in <filename unknown>:0 
```
and

```
Failed to process metadata for "/Users/cedar/Documents/local_python_env/include/python2.7", storing empty metadata
UnixSupport.File+FileAccesException: Unable to access the file "/Users/cedar/Documents/local_python_env/include/python2.7" with method llistxattr, error: ENOENT (2)
  at UnixSupport.File.GetExtendedAttributes (System.String path) <0x93e9138 + 0x000e7> in <filename unknown>:0 
  at Duplicati.Library.Snapshots.SystemIOLinux.GetMetadata (System.String file) <0x93e8e80 + 0x000bb> in <filename unknown>:0 
  at Duplicati.Library.Snapshots.NoSnapshotLinux.GetMetadata (System.String file) <0x93e8e40 + 0x0002b> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata (ISnapshotService snapshot, System.String path, FileAttributes attributes) <0x93e89c0 + 0x00095> in <filename unknown>:0 
```

**Comment by ohthetrees** [comment]
4 months later... I have 934 files that can't back up because of this issue, and I'm beginner to wonder if Duplicati is the software for me. Real shame, because it is so close to what I'm looking for!

:(

**Comment by jheyneman** [comment]
This bug is the only thing preventing me from using duplicati 2 to backup my Mac. No problems on my Linux box or Windows machines. I am getting a ton of errors with an Apple Photos Library where a bunch of the pictures have larger metadata.

**Comment by kenkendk** [comment]
This will be fixed with once #2022 is merged.

**Comment by randy3k** [comment]
With the fix, do we need to a restart the entire build from scratch? Or just hitting the backup button is sufficient?

**Comment by kenkendk** [comment]
It is sufficient to just install the update and run the backup as normal, and it should then continue without errors.

**Comment by kenkendk** [comment]
This has been merged, and reported elsewhere to work
