### ISSUE TITLE
exclusions not working ver 2

### ISSUE THREAD

**Issue by gtangt** [duplicati/duplicati#1560]
probably I am doing something very basic wrong but backing up from my NAS to Google Drive I cannot manage to excluded certain folders it seems. Please see screen short attached. Sorry for lack of competence!
![screen shot 2016-01-29 at 5 46 49 pm](https://cloud.githubusercontent.com/assets/16959761/12680201/1becaf3e-c6b1-11e5-9ef3-ef2b6f588fb9.png)

**Comment by kenkendk** [comment]
The filters always match the whole path, and are case-sensitive on Linux.

Try
```
-*/_ARCHIVE/
-*/_OFFICE/
...
```

**Comment by gtangt** [comment]
works, thanks!
