### ISSUE TITLE
Backup fails following "Sharing violation": all subsequent files fail with "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by mach-o** [duplicati/duplicati#1561]
I am still experimenting backing up my entire root partition on Linux. I am at the point where this sometimes succeeds, with a few error messages about Duplicati files, e.g.:
`Failed to process path: /tmp/Duplicati.Library.Main.Volumes.VolumeWriterBase_.ctor_20160129T171935Z_397b1acc => Path doesn't exist!`
`Failed to process path: /tmp/Duplicati.Library.Main.Volumes.VolumeWriterBase_.ctor_20160129T171935Z_6fba6412 => Path doesn't exist!`
`Failed to process path: /root/.config/Duplicati/LFIAUMUUMK.sqlite-journal => Unexpected result count: 0, expected 1`
But no real problems.

Other times, however, I get a "Sharing violation" error on what seems to be an internal Duplicati file, and every subsequent path on the destination fails, e.g.:
`Failed to process path: /tmp/Duplicati.Library.Main.Volumes.VolumeWriterBase_.ctor_20160129T200533Z_c7f76a26 => Sharing violation on path /tmp/Duplicati.Library.Main.Volumes.VolumeWriterBase_.ctor_20160129T200533Z_c7f76a26`
`Failed to process path: [some_file] => Object reference not set to an instance of an object`
`Failed to process path: [next_file] => Object reference not set to an instance of an object`
etc.
##

**Comment by kenkendk** [comment]
The sharing violation usually happens because the file is open, and usually Duplicati itself has opened the file and forgotten to close it.

The "path doesn't exist" error seems to indicate that something has deleted the temporary folder?

**Comment by mach-o** [comment]
Thanks for the clarification. I've worked around this problem by using the --tempdir option to specify a temporary working directory that is in a directory branch that's excluded from the backup.

**Comment by hifihedgehog** [comment]
I am receiving this issue as well, repeatedly, and the tmp folder is not included in the folders that I selected for backup. What is the fix?

[Report.txt](https://github.com/duplicati/duplicati/files/3153898/Report.txt)
