### ISSUE TITLE
Selecting target folder with file browser not working

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1562]
It is impossible to select target (local folder or drive) for a new backup using graphical browser. Only displayed library folders can be opened, Computer can not be opened. Even after highlighting one of the available entries, "Test connection" reports: 
"The folder undefined does not exist Create it now?" 

Note that file browser for selecting folders to bebacked up works as expected.

Version: Duplicati 2.0.0.98- 2.0.0.98_preview_2016-01-27 
Browser: Google Chrome and Edge
OS: Windows 10

**Comment by kenkendk** [comment]
This was fixed with d78b536d2703e2813af16f6c3a6a178fa670a465
