### ISSUE TITLE
Installation failures on OSX10.11EC

### ISSUE THREAD

**Issue by vavalt** [duplicati/duplicati#1563]
I can't say how pleased I was to find out about Duplicati, because it will let me make private backups to OneCloud from OSX, apparently quite painlessly.

However, I just can't get Duplicati to install. It seems like if I wanted to use OneDrive as a backup backend, I would need to use the 2.x release, right? The "stable" version wouldn't work? Which version would others recommend I try?

My OS X version is 10.11 El Capitan, and I have the latest `mono` package installed in home`brew`. However, when I try to run `export PATH=/Library/Frameworks/Mono.framework/Versions/4.2.0/bin/:${PATH} mono Duplicati.GUI.TrayIcon.exe`, I get varying results. A few times I got pages in my browser that seemed like web interfaces to the program. But I tried refreshing the pages because they seemed like they lacked some graphics or something, and I figured why not, because in general initial GET requests should be idempotent. But then the program crashed with a stacktrace in the terminal. Then I tried downloading and installing another release with a graphical installer, and the installer wouldn't recognize my installation of Mono, and it prompted me to install some version of mono separately. But that mono installer refuses to succeed.

Anyway, I've been sent down a few different paths, and if I could clear the blockages making any one of them a dead end, it seems like it would solve the problem, unless OneDrive-as-backend-support is confined to the 2.x release series.

Does anyone have any feedback for getting me up and running?

Thanks

**Comment by kenkendk** [comment]
I am aware of issues with OSX.

Best path seems to be to remove the homebrew version and install from the binaries on monoproject.org. Make sure you get the 32bit version.

I will have a look at why it fails with homebrew at some later time.

And yes, OneDrive only works with 2.0.
Version 2.0 does not have a stable release yet, just a preview.

**Comment by vavalt** [comment]
Success! These tips solved the problem :) :)
