### ISSUE TITLE
(ngax) Long lines in log not showing properly 

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1564]
Long filenames overflow the grey backgound and the side of the browser window when vieving a log. There is no scroll bar to show them. Only way is to increase browser window size. The problem seems to be long filenames where browser does not find logical place to split them to text width. 

This happens when viewing a log for a backup (url: http://127.0.0.1:8200/ngax/#/log/1). 
Both Google Chrome and Edge have the same problem. 

 Duplicati 2.0.0.98- 2.0.0.98_preview_2016-01-27
Windows 10

![2016-01-31](https://cloud.githubusercontent.com/assets/13969439/12702207/34e659b6-c82a-11e5-9495-9b08bfc9be90.png)

**Comment by kenkendk** [comment]
I think this was fixed at some point, it looks correct in my tests, and the screenshot in issue #1912 clearly shows a scroll bar.

**Comment by kakoskin1** [comment]
Yes, this was fixed at some point. I have not seen this for some time.
