### ISSUE TITLE
aws_ is not supported and will be ignored/command line backup S3  from Duplicity 2.0

### ISSUE THREAD

**Issue by wkisielewicz** [duplicati/duplicati#1565]
Hi,

I want to make a backup on my account S3, I use Duplicati 2.0 and all the time I get the following output:

Backup started at 2016-02-01 13:14:59
The supplied option --aws_access_key_id is not supported and will be ignored
The supplied option --aws_secret_access_key is not supported and will be ignored
The supplied option --aes-encryption-dont-allow-fallback is not supported and will be ignored
The supplied option --full-if-older-than is not supported and will be ignored

Earlier, I performing  backup to S3 using Duplicati 1.3 and everything was fine. 

And last, I have a problem with the path to S3:
Invalid path: "s3://test_duplicati/test" (Format specified path is not supported.)

**Comment by kenkendk** [comment]
The commandline format for Duplicati 2.0 has changed, and some options changed names.

The two last options are not supported anymore and should just be removed.
The login information should be set with `--auth-username` and `--auth-password`.

Try `duplicati.exe help backup` or `duplicati.exe help s3`:
```
Duplicati.CommandLine.exe backup s3://test C:\source-data --auth-username=abc --auth-password=xyz
```

**Comment by wkisielewicz** [comment]
Thanks for the answer!
I did as you told and it should work... That's my hunch! :) 
But now I get an error: Operation List with file  attempt 1 of 5 failed with message: Access Denied => Access Denied
I'm sure that my credentials are ok.
My run command: Duplicati.CommandLine.exe backup s3://duplicati_test C:\Users\kisiel\Pictures\ --auth-username="my_username" --auth-password="my_apssword" --passphrase=test --aws_access_key_id=MY_KEY --aws_secret_access_key=MY_SECRET_KEY

**Comment by kenkendk** [comment]
You should not specify both `--auth-username` and `--aws_access_key`. Same goes for the password.

**Comment by wkisielewicz** [comment]
yup. I  tried: Duplicati.CommandLine.exe backup s3://duplicati_test C:\Users\kisiel\Pictures\ --auth-username=my_username --auth-password=passwd 

But then:
Operation List with file  attempt 1 of 5 failed with message: The AWS Access Key Id you provided does not exist in our records. => The AWS Access Key Id you provided does not exist in our records.

**Comment by wkisielewicz** [comment]
Ok, I think, I know what a problem.
I received Access Denied because of the buckets placed in different regions,
for version 1.3 is not a problem, at least in my case. Backups have done normally.

As for "The AWS Access Key Id you provided does not exist in our records." I'm guessing that there is a problem from the Amazon.

I was able to do a backup, which ended successfully using:
Duplicati.CommandLine.exe backup s3: // duplicati_test C: \ Users \ kisiel \ Pictures \ --aws_access_key_id = MY_KEY --aws_secret_access_key = MY_SECRET_KEY --passphrase = test.

Thanks for the help
