### ISSUE TITLE
Change remote address

### ISSUE THREAD

**Issue by steilerDev** [duplicati/duplicati#1566]
Hi everyone,

is there a way to change the remote address (move the files from one folder to another), without the need of re-creating the whole local database?

Since this is not a common thing to do, I would be happy about a pointer which part of the local database I need to manipulate in order to achieve this.

Thanks for your help and effort!

**Comment by kenkendk** [comment]
There is nothing in the (backup) database that is refering to the target.
If you are using the commandline you can edit the dbconfig.json file in your appdata or ~/.config folder, or manually set --dbpath.
If you are using the GUI, it keeps track of the path so it just works.

**Comment by kenkendk** [comment]
I assume this has been answered

**Comment by steilerDev** [comment]
Yes, thank you!

**Comment by autumnwalker** [comment]
Sorry to reopen this, but I have the same question and just want to clarify @kenkendk's comment.

I'm using the WebUI, if I want to move an existing backup set (on the destination) from /backup to /backup/newfolder can I just change the "path on server" setting in the configuration and Duplicati will take care of the move?

Will this just move the files on the server or will it start a whole new backup?

**Comment by agrajaghh** [comment]
@autumnwalker this won't move the files. You have to manually move the files and then change the path in duplicati
