### ISSUE TITLE
Question about keep-time and keep-versions

### ISSUE THREAD

**Issue by albertgouws** [duplicati/duplicati#1568]
Hi, I have been using Duplicati 2 for a while now and love it, thanks for the hard work!

I have a question about the keep-time and keep-versions command line settings.

Is this what you're talking about which defaults to 1 month by default?

Just to be 100% clear on what this does:
If I set this setting to 2 days, run a backup of 10 files and delete 5 of those files after the backup, will Duplicati delete those 5 files from the backup set when I run a backup after say 3 days?

Can the keep-version setting be used at the same time as the keep-time? e.g. set a keep-versions to 5, and keep-time to 2 months. If I then run a backup every day, it will only keep the last 5 **changes** to my files.  If I deleted my my files, **each version** will then stay in the backup set until that version is 2 months old?

Thanks for your time!
Albert

**Comment by kenkendk** [comment]
If you specify both `--keep-time` and `--keep-versions` you get whichever is smaller.
I think you want the opposite.

The default for `--keep-time` and `--keep-version` is zero, meaning that old backups are never deleted.

Each time you run a backup (and files have changed), a new "dlist" (a snapshot, or a backup description) file is created on the remote store. The two options determine when these dlist files are deleted.

Once a dlist file is removed, that particular backup/snapshot cannot be restored anymore.

**Comment by kenkendk** [comment]
I changed this such that you can no longer specify both, because it was not obvious how it should work with two values.
