### ISSUE TITLE
mixed database versions

### ISSUE THREAD

**Issue by Bummibaer** [duplicati/duplicati#1571]
I backup hourly with the commandline-client, and give a database (
DLTCEEKDUR.sqlite) by option.

I have since last week the following error:

>Backup started at 06.02.2016 19:51:43
>The database has version 4 but the largest supported version is 3.
>This is likely caused by upgrading to a newer version and then downgrading.
>If this is the case, there is likely a backup file of the previous database version in the folder C:\Users\Foo\AppData\Roaming\Duplicati.

The AppData Folder looks like that:
>01.02.2016  19:54            36.864 Duplicati-server.sqlite
>01.02.2016  19:54       707.052.544 DLTCEEKDUR.sqlite
>01.02.2016  10:10             2.965 dbconfig.json
>25.11.2015  19:37             2.576 TKKYLFVXGX.sqlite-journal
>25.11.2015  19:37       193.429.504 TKKYLFVXGX.sqlite
>25.11.2015  07:06       497.002.496 backup 20151205095314.sqlite
>24.11.2015  21:30       192.794.624 backup 20151125071913.sqlite

Why this occurs? Where are the backups( Nov. last year seems not adäquate).
What the best solution?

I have once run the GUI (from the same folder), can this be the cause?

Thanks for any hint.

Version:
http://www.duplicati.com/              Version: 2.0.0.87- 2.0.0.87_preview_2015-07-03

**Comment by kenkendk** [comment]
I am guessing something has caused an updated version of Duplicati to run, or you are now running an older version.

You can use the latest version, and the problem will go away:
http://updates.duplicati.com/preview/latest.zip
