### ISSUE TITLE
Can't restore :  The requested folder does not exist 

### ISSUE THREAD

**Issue by GuillaumeSmaha** [duplicati/duplicati#1572]
Hi !

On a new computer, I try to call :

    "%ProgramFiles%\Duplicati2\Duplicati.CommandLine.exe" restore "googledrive://DuplicatiPhotos2.0" --authid=XXX --dry-run --passphrase=XX --log-file="C:\duplicati.log" --log-level=Profiling --restore-path="C:\photoDuplicati" --backup-name="DuplicatiGoogle"
But it returns :

    Checking remote backup ...
      Listing remote folder ...
    Operation List with file  attempt 1 of 5 failed with message: The requested folder does not exist => The requested folder does not exist

And when I use list command, it work's !

    "%ProgramFiles%\Duplicati2\Duplicati.CommandLine.exe" list "googledrive://DuplicatiPhotos2.0" --authid=XXXX --passphrase=XXXX --log-file="C:\duplicati.log" --log-level=Information --backup-name="DuplicatiGoogle" 

    Listing filesets:
    0      : 01/02/2016 12:00:47 (57113 files, 173,75 GB)
    ...

I imported the file from AppData\Roaming\Duplicati :

dbconfig.json :
    
      {
        "Type": "googledrive",
        "Server": "DuplicatiPhotos2.0",
        "Path": "",
        "Prefix": "duplicati",
        "Username": null,
        "Port": -1,
        "Databasepath": "C:\\Users\\Administrateur\\AppData\\Roaming\\Duplicati\\DuplicatiGoogle.sqlite",
        "ParameterFile": null
      }

How can I restore my backup ?

**Comment by GuillaumeSmaha** [comment]
This is the same with the tool Duplicati.CommandLine.RecoveryTool.exe :

	Listing files on backend: googledrive ...
	Program crashed:
	Duplicati.Library.Interface.FolderMissingException: The requested folder does not exist
	   à Duplicati.Library.Backend.GoogleDrive.GoogleDrive.GetFolderId(String path, Boolean autocreate)
	   à Duplicati.Library.Backend.GoogleDrive.GoogleDrive.get_CurrentFolderId()
	   à Duplicati.Library.Backend.GoogleDrive.GoogleDrive.List()
	   à Duplicati.CommandLine.RecoveryTool.Download.Run(List`1 args, Dictionary`2 options, IFilter filter)
	   à Duplicati.CommandLine.RecoveryTool.Program.RealMain(String[] _args)

**Comment by GuillaumeSmaha** [comment]
Crazy !! I found why it doesn't work !

I used a credential key for GoogleDrive instead of a key for GoogleDocs ...

But may be there is an error in the code with the API ?

**Comment by GuillaumeSmaha** [comment]
Other questions : Will recovery tools extract all data to get the last version ?

**Comment by kenkendk** [comment]
I think this happens because the GoogleDrive access is (intentionally) limited such that it can only see files created with Duplicati. That means that even if the folder exists, it will appear that it does not.

With the recovery tool you can choose which version you want to restore from, so yes.
