### ISSUE TITLE
Display first line of log data by default in GUI

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1573]
Currently log viever displays only timestmpd and word "Message" or "Result". User has to click on each of these to see what they are about. It would be better if view contained the first line of log message for user to determine what each message is about. There could even be an arrow symbol to indocate that each log message can be expanded to show more information.  
##

**Comment by darrenkenny** [comment]
I was just about to log an issue w.r.t. this too, it's really not user friendly to have to expand each individual message to see what it was about - and there is nothing to differentiate an informational message vs an error - e.g. 'no remote datasets were deleted' vs 'error accessing fil...'.

At least including the first line in the unexpanded text would be useful at a glance.

What would also be nice, is if the UI could recognize errors like 'Error accessing file' and provide a button to quickly add this file (via a dialog popping up with an editable path) to the exclusion list.

**Comment by Pectojin** [comment]
I'm not sure exactly when, but these lines have been added in the various logs locations (live, remote, stored). The only log that does not display this now is the general server log, which writes "Result".

I don't think we can get a more concise message for these, though, as they're the result of the backup run. This message may have multiple warnings/errors or none at all and usually has several messages in as well.
