### ISSUE TITLE
Enhancement: Change "Live Log" to be a floating window in stead of application modal

### ISSUE THREAD

**Issue by hcjehg** [duplicati/duplicati#1574]
Live Log is very practical, but when the window is open the rest of the interface is "blacked out" presumably because the live log is application modal. Does it have to be so? It would be practical to be able to keep the window open while interacting with the ongoing backup's.

HC
##

**Comment by kenkendk** [comment]
You can have two windows open if you like.

The new user interface has this a bit different, so it is not blacked out.

**Comment by warwickmm** [comment]
This doesn't seem to be that big of an issue anymore, especially since one can have to browser tabs/windows open.
