### ISSUE TITLE
Neither --debug-output nor --verbose give any indication of email failure/success

### ISSUE THREAD

**Issue by utdrmac** [duplicati/duplicati#1575]
Attempting to use the following (sanitized):

```
--send-mail-to=user@domain.com \
--send-mail-url=tls://smtp.myserver.com:587 \
--send-mail-username=user@domain.com \
--send-mail-password=foobarbaz1234 \
```

These are the same settings as in my email client which has no issues sending emails through this server. Specifying "--debug-output" and "--verbose", neither are giving any indication that the email was successfully sent, had error, wrong password, etc.

Because TLS is encrypted, I cannot packet-sniff-debug the problem.

Please add debugging output of the steps email taken to assist in diagnosing problems.
##

**Comment by kenkendk** [comment]
This would also help for #1540

**Comment by utdrmac** [comment]
FTR, I did use ngrep on port 587 to sniff packets and I can see that data is being transmitted to my mail host but, obviously, I cannot read the encrypted packets so I cannot deduce any possible error messages.

**Comment by kenkendk** [comment]
With e692be5 you can now just add --log-level=profiling and it will dump the entire SMTP conversation, something like:
```
Duplicati.CommandLine.exe 
  send-mail 
  --send-mail-to=abc@example.com 
  --send-mail-url=smtps://smtp.gmail.com 
  --send-mail-username=abc@gmail.example.com 
  --send-mail-password=app-specific-password 
  --log-level=profiling
```
