### ISSUE TITLE
Expose more S3 options

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1581]
There are a few S3 options that could be handy to support.

https://github.com/duplicati/duplicati/issues/1420#issuecomment-184102969

**Comment by alanliu006** [comment]
May I use the function in v2.0.0.99-2.0.0.99_preview_2016-02-15?
Web UI blocks 's3-ext-SignatureVersion' option. Duplicati.CommandLine does not support yet.
`The supplied option --s3-ext-signatureversion is not supported and will be ignored`

**Comment by kenkendk** [comment]
The fix came in after v99 was built:
https://github.com/duplicati/duplicati/commits/master

It will be part of the next build.

**Comment by alanliu006** [comment]
Thanks a lot.
