### ISSUE TITLE
CommandLine client cannot handle whitespace in source file names

### ISSUE THREAD

**Issue by mach-o** [duplicati/duplicati#1588]
I've tried various combinations of double-quotes and backslashes, but backing up a source file containing a space character on Linux seems to inevitably lead to: 

`The source folder <truncated_filename> does not exist, aborting backup`.

This may be related to #928.

**Comment by kenkendk** [comment]
@mach-o can you give an example?
I normally enclose paths in double quotes, e.g. `"/my folder"`.

**Comment by mach-o** [comment]
Yes, you're right. The problem is related to the way I'm invoking duplicati. To save myself the trouble of typing "/path/to/mono Duplicati.CommandLine.exe ..." each time, I created the the following script as /usr/local/bin/duplicati-cli:

`#!/bin/bash
cd /usr/local/bin/duplicati
mono Duplicati.CommandLine.exe $@`

The problem must be in the way I pass parameters through this script, because spaces work fine if I invoke Duplicati directly without this script.

**Comment by kenkendk** [comment]
Let me know if you figure this out. I would like to provide such as script with the install too.

**Comment by mach-o** [comment]
It works for me if I change the last line in the script to this:

`mono Duplicati.CommandLine.exe "$@"`

I haven’t thought at all about whether other problems might remain with this approach, but maybe this page on [bash parameters and parameter expansions](https://www.ibm.com/developerworks/library/l-bash-parameters/index.html) could help shed some light on the subject.
