### ISSUE TITLE
Version 2.0.0.99- 2.0.0.99_preview_2016-02-15 ignores --symlink-policy.

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1591]
Versions 2.0.0.99-2.0.0.99_preview_2016-02-15 and 2.0.0.98-2.0.0.98_preview_2016-01-27 ignore option --symlink-policy completely. They will always follow symlinks. 

Version 2.0.0.96-2.0.0.96_preview_2015-12-17 works as expected.

**Comment by kakoskin1** [comment]
Sorry, I forgot this:

OS: Fedora 23
mono: Mono JIT compiler version 4.0.5 (Stable 4.0.5.1/1d8d582 Mon Jan  4 11:09:45 UTC 2016)
(Mono is Fedora from Fedora repositories.)

**Comment by kenkendk** [comment]
This was fixed with b9aacdd24386e48e698c3ed356fb7a2cc5c7b1a9
