### ISSUE TITLE
Restoring individual files are not possible in UI

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#1592]
Hi all,

Will mysql or some other database instead of the current sqlite database increase performance? (Specially Restore)
Restoring 100 GB and above from a local NAS even on a i5 system takes very long with the sqlite database in place.
In disaster recovery situations where data has to be restored rapidly duplicati may take days to complete being block based backup.

Selecting individual files to restore from the backup takes time.
Clicking the side arrow next to any folder in the Restore Files window. gives a pie progress for long.. 
Repeat for the subfolder
Repeat for the sub sub folder. till the final file is selected.

Can XAMPP help in any way https://www.apachefriends.org/index.html

**Comment by FootStark** [comment]
Please note: There also is a discussion on db type, restore and performance here: #1590
Increasing performance for restore operations is currently being worked on. If you want to help improve it you may want to specify some specifics on your setup (machine and storage used, duplicati Version, size and type of files in backup, compression and encryption options used, etc), and some concrete measurements. Thank you.

**Comment by saviodsouza** [comment]
![tmp_13426-bk21328138450](https://cloud.githubusercontent.com/assets/12080676/14466488/b8199444-00f4-11e6-8afd-d09472bf1a63.png)
![tmp_13426-bk924254408](https://cloud.githubusercontent.com/assets/12080676/14466499/c2fea138-00f4-11e6-9eb5-002f9c4e6792.png)

**Comment by saviodsouza** [comment]
See the above screenshots.

The pie progress bar goes on and on for hours making it impossible to restore individual files. :(
Currently I'm using .11 experimental update.

Any help

**Comment by agrajaghh** [comment]
@saviodsouza did you try the new ngax gui?

**Comment by saviodsouza** [comment]
Yes tried both it's the same.

I have done database repair without errors
Backups runs smoothly.

Database size is around 630MB at present.

Initially around  end of December when the number of backups were just 2 or 3 file listing was fast but as the number of incremental backups have increased  its getting bad.

Do increase number of incremental backups delay restore file listing any way?
There is no option to view live log  here to know what's happening in the background.

**Comment by FootStark** [comment]
Too locate whether the issue lies in the UI or in the logic itself, can you try to list using the command line tool?
`Duplicati.CommandLine.exe list <your_backup> "--time=2016-04-05 04:00"`

**Comment by kenkendk** [comment]
I think this has been fixed.
