### ISSUE TITLE
Duplicati Incrimental Backup

### ISSUE THREAD

**Issue by jrosetto** [duplicati/duplicati#1594]
I have computers that backup incrementally nightly.  When there are no file changes no files get written to the backup.  I am using Zabbix to monitor file changes on the ftp server where backups are being stored to be able to tell if the backup is working or not.

Is there a way to have duplicati change the datestamp or send a file reguardless of if the files have changed or not?

Any suggestions are greatly appreciated.

Thanks.

**Comment by kenkendk** [comment]
I think you are looking for `--upload-unchanged-backups`. If you add that option, you will get a new `dlist` file uploaded after each backup run, even if there are no changes.

**Comment by kenkendk** [comment]
Closing for lack of feedback
