### ISSUE TITLE
Get consistent errors with metadata on .eml files

### ISSUE THREAD

**Issue by joolsr** [duplicati/duplicati#1603]
Hi

I've had this issue for about 6 months now. We have a number of .eml mail files stored on a Synology NAS device (which is effectively running samba). The errors have been seen consitently every time the backup is run when using Duplicati 1.34 and 2.00.99 on Manjaro Linux and Mono JIT compiler version 4.2.2 . 

For every .eml I get a similar error. No other files give problems, therefore the backup always completes with errors which is annoying as I have to check the log to check if it is just these files or something else. The error was a little less clear in version 1.3.4 (ie did not mention the storing empty metadata issue and llistxattr etc but an error did occur.

Warnings: [Failed to process metadata for "/home/julianr/aa.eml", storing empty metadata => Unable to access the file "/home/julianr/aa.eml" with method llistxattr, error: ENOENT (2), Failed to process path: /home/julianr/aa.eml => Could not find file "/home/julianr/aa.eml"]

I've chnaged the pathname and file name as it would give away sensitive info, but as this issue occurs for every .eml file stored all over our nas I dont think this is the issue. Googling doesnt provide any clues either. 

Any ideas if its related to the backup or actually the storage of the .eml files themselves? and any ideas to fix /workaround this ?

**Comment by kenkendk** [comment]
It looks like the filesystem (SAMBA I assume) is rejecting the requests to list extended attributes for the .eml files. Why it would do that I do not know.

**Comment by joolsr** [comment]
Hi

Its quite an old bug report - I found the answer. I found that only .eml
files were being affected. I looked closely at these files and filenames.
What happened was that the application that saved these files Thunderbird
 was appending an odd character ( I can't remember which now, some kind of
dash which wasn't properly supported on The Synology Samba server server.
Very odd, but easy to fix in the end.

Thanks anyway you can mark this as closed.

Julian
