### ISSUE TITLE
Unable to backup or repair

### ISSUE THREAD

**Issue by steilerDev** [duplicati/duplicati#1604]
Hello all,

after finishing my initial backup of my NAS (~2.5TB) I am now not able to add additional backups. 

The problem when running the backup (`mono /opt/duplicati/Duplicati.CommandLine.exe backup amzcd:///Duplicati/files --backup-name="files" --prefix="files" /media/files --passphrase="password" --authid="authid" --number-of-retries=25 --encryption-module="aes" --keep-time="3M" --dblock-size="200mb"`) is the following:

```
Backup started at 03/09/2016 17:57:05

Found inconsistency in the following files while validating database:
/media/files/<filepath>.img, actual size 7964983296, dbsize 8406941696, blockset
id: 17190
/media/files/<filepath>.img, actual size 7964983296, dbsize 8420663296, blockset
id: 17192
/media/files/<filepath>.img, actual size 7964983296, dbsize 9370525696, blockseti
d: 22104
/media/files/<filepath>.avi, actual size 1565386752, dbsize 5497546752, blocksetid:
29996
/media/files/<filepath>.avi, actual size 1069
326336, dbsize 5295783936, blocksetid: 30648
... and 1 more. Run repair to fix it.
```

However when I run repair (`mono /opt/duplicati/Duplicati.CommandLine.exe repair amzcd:///Duplicati/files --backup-name="files" --prefix="files" --passphrase="password" --authid="authid" --number-of-retries=25 --encryption-module="aes" --keep-time="3M" --dblock-size="200mb"`) the following error occurs:

```
Found 6 missing blocklisthash entries, repairing

Missing block for blocklisthash: nuEa8I1eg22YJwVAhrX+v2c0QKbGCnzyBwfxe+1wNr4=
```

Any ideas how to fix this?
##

**Comment by kenkendk** [comment]
Which version of Duplicati are you using?

I think I have a bug report with the same problem and I am looking for a way to fixing it.

**Comment by steilerDev** [comment]
I'm not sure which version I was using when I published the issue (I think it was the first amazoncloud supported version). I now upgraded to `2.0.1.1- 2.0.1.1_canary_2016-03-11` and still get the same error, however a line with `No LSB modules are available.` appears, not sure if this is relevant.
