### ISSUE TITLE
Restoring a folder with command line

### ISSUE THREAD

**Issue by hawoken** [duplicati/duplicati#1605]
Hello i have issues when i try to restore a folder from backup.
The steps i did:
1. cd C:\Archivos de programa (x86)\Duplicati
2. duplicati.commandline.exe restore z:\servidores\serverplm y:\serverplm2

And the msg i get:

The folder c:\blablabla not exist

What i'm doing wrong?

**Comment by kenkendk** [comment]
Most likely the windows terminal escapes \s to something.
Try adding `--verbose` and put quotes around your paths.
Also, the syntax is wrong, you cannot supply a destination like that (which I assume you are trying).
Try this:
```
Duplicati.CommandLine.exe restore "z:\servidores\serverplm" --restore-path="y:\serverplm2" --verbose
```

**Comment by kenkendk** [comment]
No feedback, closing
