### ISSUE TITLE
Method not found/Windows Server 2008

### ISSUE THREAD

**Issue by wkisielewicz** [duplicati/duplicati#1606]
Hi,

I'm trying to do backup to S3 on Windows Server 2008 64 bit (VirtualBox). Unfortunately, all the time I get an error:

Method not found: 'Void System.Globalization.CultureInfo.set_DefaultThreadCurrentCulture (System.Globalization.Culture.Info)

The command that I use:

Duplicati.CommandLine.exe backup s3: // testduplicatigpg3 C: \ Users \ jelly \ Desktop \ tt --aws_access_key_id AWS_ACCESS_KEY_ID --aws_secret_access_key=AWS_SECRET_ACCESS_KEY --passphrase=test

Duplicati version 2.0.0.91_preview_2015-11-18

**Comment by kenkendk** [comment]
Hi. Can you try to add the flags `--verbose` and `--debug-output` ?

The last flag should give a stack trace that tells me exactly where the error occurs.

**Comment by wkisielewicz** [comment]
Ok, add this flags. I get something like this:

Method not found: 'Void System.Globalization.CultureInfo.set_DefaultThreadCurrentCulture (System.Globalization.Culture.Info)'.
at Duplicati.Library.Main.Controller.OnOperationComplete(Object result)
at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, Action `1 method)
at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
at Duplicati.CommandLine.Commands.Backup(List `1 args, Dictionary`2 options, IFilter filter)
at Duplicati.CommandLine.Program.RealMain(String[] args)

**Comment by kenkendk** [comment]
Thanks, I will have a look.

**Comment by kenkendk** [comment]
Duplicati should not attempt to call that method unless you set `--force-locale`, have you set that?

**Comment by wkisielewicz** [comment]
Hmm ... I do not have this flag set. I use only: Duplicati.CommandLine.exe backup s3: // testduplicatigpg3 C: \ Users \ jelly \ Desktop \ tt --aws_access_key_id AWS_ACCESS_KEY_ID --aws_secret_access_key=AWS_SECRET_ACCESS_KEY --passphrase=test

**Comment by kenkendk** [comment]
Yes, I see. It attempts to load the functions even though they are not called. What version of the .Net framework are you using?

I will add an indirection so the error does not happen.

**Comment by wkisielewicz** [comment]
net framework 4.0

**Comment by kenkendk** [comment]
Hmm, it should work in 4.0: https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.defaultthreadcurrentculture(v=vs.110).aspx

**Comment by wkisielewicz** [comment]
I check it yet another installation of Windows Server 2008

**Comment by wkisielewicz** [comment]
Ok, I checked it again. New installation Windows Server 2008 (64 bit), all the time I get the same error.

**Comment by wkisielewicz** [comment]
I installed .NET framework 4.5 and it seems to work. But unfortunately for the .NET framework 4 does not work.

**Comment by kenkendk** [comment]
You are correct, I was looking at the wrong version. It is not possible to set this value in .Net 4.0:
https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.currentculture(v=vs.100).aspx

**Comment by wkisielewicz** [comment]
Ok.  I'll use the .NET Framework 4.5
Thanks

**Comment by kenkendk** [comment]
I will make an update which will fix this issue, so it works on .Net 4.0 as well.

**Comment by wkisielewicz** [comment]
Sounds great!
