### ISSUE TITLE
Live log page gets unresponsive as the shown log grows

### ISSUE THREAD

**Issue by renestach** [duplicati/duplicati#1617]
- Run a longer job
- Go to "live log" and set it to profiling
- After quite some time you will see, that the page gets slower and slower and doe not repond to clicks anymore.
##

**Comment by kenkendk** [comment]
It should be restricted to 1000 messages, but perhaps that is too many.
How many did you have (appx.) ?

**Comment by renestach** [comment]
Not sure. From the size of the scroll bar it's been at least 500. Is there some heavy JS blocking the page? I had to open a new browser tab. The live log didn't even reload.

**Comment by renestach** [comment]
Maybe it was just longer. It seem the scroll bar had reached its minimum size already (just playing with it). 

I left it open in the background for quite some while.

**Comment by renestach** [comment]
10 minutes of "profiling" during backup slow the page down significantly.

**Comment by Pectojin** [comment]
I think the max of 1000 messages was thought up more than implemented. 
[duplicati/blob/master/Duplicati/Server/webroot/ngax/scripts/controllers/LogController.js#L35](https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/webroot/ngax/scripts/controllers/LogController.js#L35)

    $scope.LiveData.Length = Math.min(1000, $scope.LiveData.length);

This is set and then `LiveData.Length` is never referenced again.

The logs are definitely not limited to 1000.
![screen shot 2018-02-21 at 01 08 47](https://user-images.githubusercontent.com/1561484/36456219-121c0276-16a4-11e8-9f9b-c117dbf45f34.png)
