### ISSUE TITLE
Hubic "Connection URI" creation bug in the Windows GUI (easy workaround)

### ISSUE THREAD

**Issue by resys** [duplicati/duplicati#1618]
Tested on 3 desktops under Windows 7 64 bits with v2.0.0.91 and and older version (I don't remember)

When doing :
Add new backup --> Backup to --> Target Type --> Hubic --> AuthID --> Hubic login
After Hubic login, the URI is correctly created:
hubic://MyBackup?authid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXX

Test connection is working.

Then click "create URI", the url past to the "Backup to..." field is :
hubic://MyBackup?authid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%3AXXXXXXXXXXXXXXXXXXXXX

BUG --> The ":" is replaced by "%3A" during the copy/past

Just replace the "%3A" by ":" and it is working find.

Thanks for this great tool !!

**Comment by kenkendk** [comment]
That is on purpose. The value shown after clicking on "create uri" should be shown with %3A (urlencoded). Are you saying that the backups fail if the uri has the %3A value ?

**Comment by resys** [comment]
hum...you are right, it backup is working properly...
It wasn't working in an old version and when I genereate the URI with the last version and saw the %3A, it replaced it without testing again.
Sorry for disturbing you.
The issue is be closed

**Comment by kenkendk** [comment]
Good to hear that it is working. The correct way is to encode it as %3A, but it likely works without encoding it as the url parsing is not depending on the : character.
