### ISSUE TITLE
can't restore to original location

### ISSUE THREAD

**Issue by robsonsobral** [duplicati/duplicati#1624]
Hi!

I'm testing Duplicati 2.0.1.3- 2.0.1.3_canary_2016-03-13 and I can't restore to the original location. I have to explicitly set the path.

Running on Windows 10 and backuping to b2.

Thank you.

**Comment by kenkendk** [comment]
How/what error message do you see?

**Comment by robsonsobral** [comment]
There isn't error messages. The files just don't appear.

**Comment by kenkendk** [comment]
So the restore appears to continue, and completes, but no files are restored?

Can you see anything in the log?

**Comment by robsonsobral** [comment]
Wow! I just had a really hard time to configure back the Backups to keep and test it again.

The log follows:

```
FilesRestored: 0 
SizeOfRestoredFiles: 0 
FoldersRestored: 0 
SymlinksRestored: 0 
FilesPatched: 0 
FilesDeleted: 0 
FoldersDeleted: 0 
SymlinksDeleted: 0 
VerboseOutput: False 
VerboseErrors: False 
Messages: [Searching backup 1 (2016-03-14 12:54:48 PM) ..., 1 remote files are required to restore] 
Warnings: [] 
Errors: [] 
```

**Comment by kenkendk** [comment]
Is that because the files are already present? Or do you delete the target files and then attempt a restore?

**Comment by robsonsobral** [comment]
I deleted the files and then tried to recover them

**Comment by bensoibj** [comment]
I have the same issue with Duplicati 2.0.1.7- 2.0.1.7_experimental_2016-03-19 on Windows 7, backup to webdav. After clicking Restore, nothing happens for a few seconds until the message "Your files and folders have been restored successfully." appears. But no matter whether the target file exists at the original location or not, it is neither overwritten nor restored from the backup. Unless the destination is specified ("Pick location").

**Comment by tabakhase** [comment]
- windows 2.0.1.11_experimental_2016-04-08
- plain & aes backup, stored to local disc, 
- from a "configured backup" as well as using the direct restore method

same issue, 
selecting "Original location" reports success, but actually fails as "null/" path.
Picking a location works fine (even if that location is the original location).


@kenkendk i dont get a "error", but here some log:
```
Testing restored file integrity: null\test_file.txt
Patching metadata with remote data: null\test_file.txt
Recording metadata from remote data: null\test_file.txt
Patching file with remote data: null\test_file.txt
Backend event: Get - Completed: duplicati-b76af2ea3fc7148fb9700045fc3a9d91f.dblock.zip (49,90 MB)
Backend event: Get - Started: duplicati-b76af2ea3fc7148fb9700045fc3a9d91f.dblock.zip (49,90 MB)
1 remote files are required to restore
Target file is not patched any local data: null\test_file.txt
Local source file not found: C:\test_origin\test_file.txt
Mapping restore path prefix to "C:\test_origin\" to "null\"
Needs to restore 1 files (5 bytes)
```

**Comment by kenkendk** [comment]
Are there any of these backups that do not have multi-drive backups (i.e. you have both C:\ and D:\ or similar in the backup sources) ?

I have made a new build available in the canary channel (2.0.1.14) that fixes a problem with selecting folders on multi-drive backup sets. It is likely that it fixes this issue as well.

**Comment by bensoibj** [comment]
My backups have only a single folder in it, so it's not a multi-drive backup. I just wanted to test on the larger backup with the current canary channel, but still waiting for the directory listing to appear... (looks like #1715)

**Comment by bobambrosius** [comment]
Using Duplicati 2.0.1.11- 2.0.1.11_experimental_2016-04-08 on WIndows 10, backup to OneDrive.

I have the same problem with restoring to original location. The files are not in the original location, but in C:\progs\duplicati\null\. That is de folder where I unpacked the installation zipfile. I have re-mapped my documents to D:\docs so the original location would be D:\docs\thefolder.

Another observation is that when I restore the original \a\b\c what gets restored is \b\c. There are no files in \a, only subdirectories. One would expect [..]\null\a\b\c, not [..]\null\b\c.

One last observation: When I click on 'Show log', nothing happens.

**Comment by kenkendk** [comment]
@bobambrosius Your second observation happens because Duplicati is actually not restoring to the original location, but instead the "null" folder.
When restoring to another location, Duplicati chooses the least amount of folders possible for preserving the directory structure. I.e. if you backed up `C:\a\b\c\d\e`, and restored the files `C:\a\b\c\d\txt` and  `C:\a\b\c\d\e\txt`, to `D:` the prefix ``C:\a\b\c\` is not required and files are restored as `D:\txt` and `D:\e\txt` instead of creating empty `a\b\c` folders.
