### ISSUE TITLE
Duplicate option no-encryption

### ISSUE THREAD

**Issue by robsonsobral** [duplicati/duplicati#1625]
Hi!

Trying to edit a backup set to use no encryption causes an alert of duplicated option, as the `no-encryption` appears again on Advanced options.

Running Duplicati 2.0.1.3- 2.0.1.3_canary_2016-03-13 on Windows 10.

Thank you!

**Comment by robsonsobral** [comment]
Hi, @kenkendk.

I'm running Duplicati 2.0.1.4_canary_2016-03-14 and this issue remains. It isn't fixed.

**Comment by kenkendk** [comment]
@robsonsobral do you still see this issue?

**Comment by praneethsharma** [comment]
Hello @kenkendk, 

When i try to restore the files form backup i had taken (.aes) files,  i got this error. 

Steps to reproduce :

1) Clicked on restore option in UI
2) selected  "Direct restore from backup files"
3) selected backup location
4) not gave username and password - bacause files are in local system. (tried giving credentials too, but i believe this is not causing this issue)
5) In the encyption part, if i do not select any option, i get error that "backup files are encrypted". 
If i give option "--no-encryption=true" in advanced options, and click "connect", i get "Duplicate option no-encryption" error. I have attached screenshots. 

I am running this on windows server 2012 R2. Please let me know if any details are required.

<img width="325" alt="screen shot 2017-05-17 at 6 25 24 pm" src="https://cloud.githubusercontent.com/assets/2536273/26154968/3c062158-3b2f-11e7-8d3d-0d5e1bdb66f9.png">
<img width="782" alt="screen shot 2017-05-17 at 6 30 48 pm" src="https://cloud.githubusercontent.com/assets/2536273/26154970/3d744998-3b2f-11e7-9ccf-77c69cac2712.png">

**Comment by kenkendk** [comment]
@praneethsharma  If the files are encrypted, you need to enter a passphrase. You cannot restore the files without a passphrase.
If you leave the passphrase field empty, Duplicati adds the option `--no-encryption=true` behind the scenes, which is why you get an error if you use it manually.

**Comment by praneethsharma** [comment]
Thanks @kenkendk , After entering correct passphrase, i was able to restore.
