### ISSUE TITLE
Duplicati Backup report Mail - Add job start and end-date information

### ISSUE THREAD

**Issue by deHoeninger** [duplicati/duplicati#1628]
Hi,
cause I currently have backup jobs running, which takes more than one day (see #1582) it would be helpful to have information to the  start- and end-date as well as the duration available within the Backup Report Mail. Currently it's not possible to know when the job has been started.

Best Jan 
##

**Comment by ts678** [comment]
Sample of current email has both start and end dates:

```
EndTime: 12/21/2020 2:57:14 PM (1608580634)
BeginTime: 12/21/2020 2:52:25 PM (1608580345)
Duration: 00:04:49.9244729
```
