### ISSUE TITLE
No visual feedback when restore-button is clicked

### ISSUE THREAD

**Issue by renestach** [duplicati/duplicati#1629]
Restore files from a backup. When you click "restore" in the last step, nothing seems to happen. The user should get visual feedback, that the restore process was started.

I'd say, go to the start page which has a progress bar. But what happens, when a backup is running already?

**Comment by bobambrosius** [comment]
Same here. At least the button should be disabled to prevent the user from multiple clicks. A progressbar would be nice, but even a simple message 'restoring...' would help.
