### ISSUE TITLE
tray icon is disappearing on windows

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1630]
Running duplicati 2.0.1.4 on Windows 10:

* after startup the tray icon is grey.
* during the backup process the tray icon is green
* when the backup process is finished, the tray icon gets black/transparent: 

![tray](https://cloud.githubusercontent.com/assets/5296073/13773035/876ede1c-ea97-11e5-99a6-41870da440b3.png)

**Comment by NickPyz** [comment]
+1 

Yes, I agree with the original poster. Dark Gray icon on black background in the Win10 tray is very difficult to see.

**Comment by kenkendk** [comment]
Grey means it is in pause mode.

Is the black background the default windows theme?
I think the images would need an outline to make sure they work on all backgrounds.
Would it make sense to use a white icon (with a black outline) as the default?

**Comment by agrajaghh** [comment]
I agree grey isn't ideal. (but this wasn't my original issue, for me its completely hidden after a backup job)

afaik on windows 10 the taskbar is black by default. win 7 is using a transparent taskbar so it depends on the wallpaper (default, but you can select a color as well I think)

White and black outline seems like a good idea :+1: 

If you're already on it, the green icon could use a bit more color, it looks pretty dark on the black background. So I think it should have a black outline as well plus more saturation

**Comment by kenkendk** [comment]
Is it something you would like to contribute? 

The source files are here:
https://github.com/duplicati/duplicati/tree/master/Assets

The .svg file can be opened with InkScape, and exported to a 512x512 png.

I used this site to convert the PNG to a multi-res ico:
http://icoconvert.com

**Comment by agrajaghh** [comment]
@kenkendk just had a look at it and tried to simplify them. The windows tray icons are 16x16 px, thats way too small for all the current details. How big are these icons on linux or mac?

**Comment by kenkendk** [comment]
The windows icon should be multi-resolution, but not all software supports showing multiple versions.

The linux versions are SVG (vector) so they just scale nicely.
The OSX versions are 22px wide I think.

**Comment by agrajaghh** [comment]
where are these icons displayed on OSX? in the top right corner?
<img width="319" alt="mac osx" src="https://cloud.githubusercontent.com/assets/5296073/13829303/8b6f674a-ebc6-11e5-9706-259e66dc083b.png">
are they even supposed to be colorful?

I tried to put the color inside like that:
![big](https://cloud.githubusercontent.com/assets/5296073/13829032/12c6bed4-ebc5-11e5-8b02-366ce19376b6.png)

**resized to 16px:** (bigger looks better anyway)

black / e.g. win10:
![black-01](https://cloud.githubusercontent.com/assets/5296073/13829053/33dc3432-ebc5-11e5-8fb7-751e2b410017.png)

win7 blue:
![win7-aero-01](https://cloud.githubusercontent.com/assets/5296073/13829346/d04d6da8-ebc6-11e5-8f7b-7d2da4f3e552.png)

win2000:
![win2000](https://cloud.githubusercontent.com/assets/5296073/13829350/d68bc39a-ebc6-11e5-8157-6bb769c54c92.png)

OSX:
![macosx-01](https://cloud.githubusercontent.com/assets/5296073/13829360/e358e3be-ebc6-11e5-9621-d815a02fff5d.png)

white:
![white-01](https://cloud.githubusercontent.com/assets/5296073/13829374/fafb7022-ebc6-11e5-8bdd-23c974e86a66.png)

IMHO, it looks good on dark backgrounds but doesn't look that good on bright backgrounds. What do you think?

**Comment by deHoeninger** [comment]
For me this odd feeling is mainly caused by the black symbols (play, pause) insinde the blue and grey icons. What do you think? Did you already try it with white instead?

**Comment by agrajaghh** [comment]
@deHoeninger that looks better, but doesn't solve the background problem

black / e.g. win10:
![black-01](https://cloud.githubusercontent.com/assets/5296073/13841397/fdeee950-ec28-11e5-80eb-31e4c88f31d9.png)

win7 blue (depends on wallpaper):
![win7-aero-01](https://cloud.githubusercontent.com/assets/5296073/13841398/026e9700-ec29-11e5-8932-e0ada99c9f64.png)

win2000:
![win2000-01](https://cloud.githubusercontent.com/assets/5296073/13841400/0726cc2c-ec29-11e5-8a4e-d843c811b707.png)

OSX:
![osx-01](https://cloud.githubusercontent.com/assets/5296073/13841401/0a351658-ec29-11e5-9f56-907a4b7ac4a9.png)

white:
![white-01](https://cloud.githubusercontent.com/assets/5296073/13841404/0e6e52b6-ec29-11e5-9127-a1afa03aff88.png)

**Comment by NickPyz** [comment]
The last posted icon set appears to resolve all the issues.

(1) 4 icon colors. One for each state of the application.
(2) White symbols inside the colored section provides contrast vs. the color.
(3) White borders around each icon for dark tray backgrounds in Win 10 (black), and darker Windows 7 themes.

Suggestion: I wonder if a simple monotone (white) clock symbol inside the black icon will better indicate that Duplicati is waiting for the next scheduled backup. Something like this (in reverse):

![serveimage](https://cloud.githubusercontent.com/assets/7215081/13849600/37e7b26e-ec2d-11e5-8c5b-ea8e1b281ee7.jpg)

**Comment by agrajaghh** [comment]
@NickPyz that are too many details for 16x16 I think:
![black-clock-01](https://cloud.githubusercontent.com/assets/5296073/13850526/9e2486ce-ec5a-11e5-950a-4a119e4d7d1d.png)

in big:
![big-01](https://cloud.githubusercontent.com/assets/5296073/13850566/c247f23e-ec5a-11e5-9c35-d16fd6d5004b.png)

**Comment by FootStark** [comment]
Not sure if a watch is recognizable, maybe a small " Zz ".
I'm not good with images, but I think for the tray icons the green should be a touch darker for better contrast (maybe 0x2C933D) And the play icon minimally cut on the left (leftmost col of pixels would become a shade of green then.)

**Comment by agrajaghh** [comment]
@FootStark I made the green darker:
![darker-01](https://cloud.githubusercontent.com/assets/5296073/13851076/004232be-ec5d-11e5-9030-0df3cb38ddc8.png)
and removed half a pixel from the "play" icon:
![small-play-01](https://cloud.githubusercontent.com/assets/5296073/13851087/09e5cd30-ec5d-11e5-8cc0-e5f48a07a501.png)

Darker looks better to me, but I wouldn't change the size of the play icon. So I prefer the top version. Regarding the clock or "zZ", I don't think its necessary. It should be obvious that this is the normal/standby state I guess.

btw, thanks a lot for your recent optimizations! I really like this project but its a lot of work for kenneth alone, so it could definitely use a second dev :blush:

**Comment by FootStark** [comment]
Fine with me. I thought the smaller play icon improves it on lighter backgrounds. But I'm a Win-user anyway... ;)

**Comment by NickPyz** [comment]
Looks good. The black normal/standby icon is ok as it it. Neither the clock nor the Zz offer much considering the tiny 16x16 limitation.

Thanks.

**Comment by NickPyz** [comment]
Looks good. And I agree that neither the clock nor the Zz enhance the black "standby" icon.

Thanks.

**Comment by kenkendk** [comment]
So I sense that there is a consensus about how the icons should look now?

@agrajaghh  If you are comfortable with it, can you make a pull request?
Otherwise, if you send me the updated svg files (and/or ico files) I will put them into the source.
If you would like to be credited, you can either send a pull request with a a change to the [acknowledgements file](https://github.com/duplicati/duplicati/blob/master/Duplicati/License/acknowledgements.txt), or send a mail with your desired affiliation.

You can send stuff to `@duplicati.com` with my first name in front.

**Comment by agrajaghh** [comment]
hmm, nitpick but the ico I created looks like that (1600%)
![ico](https://cloud.githubusercontent.com/assets/5296073/13905907/f3bce9e0-eecc-11e5-833c-1a0563171f1e.png)

but its displayed for me on windows 10 like that:
![tray](https://cloud.githubusercontent.com/assets/5296073/13905909/f8467ad0-eecc-11e5-843e-23c82309e2b2.png)

The upper left corners are looking really sharp (even not zoomed). Do you have an idea why?

**Comment by kenkendk** [comment]
They are taken from here, and should be a direct copy of your versions:
https://github.com/duplicati/duplicati/tree/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/Resources

And the code loading it should not do any processing:
https://github.com/duplicati/duplicati/blob/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/ImageLoader.cs#L53

Could it be something with the size not fitting 100% so Windows does some scaling?

**Comment by agrajaghh** [comment]
It's displayed as exactly 16x16px for me in the taskbar. And there is a 16x16 version included in the ico file. Maybe windows is using 24x24 (or another version) and is resizing it, but that wouldn't make sense :grin:

**Comment by kenkendk** [comment]
Are you using 2.0.1.8 ? The icons did not make it into the preview (my mistake) but they are in the next canary build.
Also, if something should be changed, this issue should be re-opened or another issue created, otherwise the comments will most likely get lost.

**Comment by agrajaghh** [comment]
yes, I'm using version 2.0.1.8 (and they are included there). I opened #1646

**Comment by tj0xin** [comment]
Hi, 

Duplicati Version: 2.0.6.3

I tried modifying SVG Icons for tray on Windows but they don't work. 

I don't have .ico files in my installation.

Then i tried deleting all the .svg files related to Tray icon under SVGIcons folder but still when the Duplicati.GUI.TrayIcon.exe is executed it  shows the original icon. Technically if the SVG's are delete it should be blank. 

So that points to some other source. 

Can someone please suggest any other location which i failed to look for Icon Files?

**Comment by ts678** [comment]
> Can someone please suggest any other location which i failed to look for Icon Files?

Inside the `.exe` where a source build puts them. You can even see them with [ildasm](https://learn.microsoft.com/en-us/dotnet/framework/tools/ildasm-exe-il-disassembler).
[Custom build - TrayIcon](https://forum.duplicati.com/t/custom-build-trayicon/7046/12?u=ts678) is a detailed forum answer to the same question asked there.
