### ISSUE TITLE
Large number of files at SFTP backup destination freezes browser when trying to "Restore files..."

### ISSUE THREAD

**Issue by daphee** [duplicati/duplicati#1631]
I choose a "Max backup file size" of 20 MB and am backing up my NAS every week.

It's not much data at all - less than 100GB but there are already about 5000 files at the SFTP backup destination.

Clicking on "Restore files..." shows the loading spinner for a few minutes while the memory usage of the single Chrome tab reaches about 1GB. Then the page freezes.
##

**Comment by agrajaghh** [comment]
what version are you using? and what UI?

**Comment by daphee** [comment]
Ah, sorry. 
I am using the Web UI on version "2.0.0.91- 2.0.0.91_preview_2015-11-18". 
Is the "Check for Updates" Button not working?

**Comment by agrajaghh** [comment]
afaik not every version is available through autoupdate. you could try the newest version, there were some optimizations: https://github.com/duplicati/duplicati/commit/77bae078ffae0c33961ce331414d2ac754b778ee

But this is even more experimental, so try it on your own risk ;)
