### ISSUE TITLE
Wrong path separator when restoring windows folders on linux

### ISSUE THREAD

**Issue by aviillouz** [duplicati/duplicati#1633]
Not sure if it's a bug:
when restoring backup  from windows pc on linux, many files are restored to the same folder with **windows path separator prefixed to the filename**:
[Drive name][Folder name][sub folder name]...[filename] 

```
$ls
F\
F\3\
F\3\file.txt

```

![duplicati](https://cloud.githubusercontent.com/assets/1772930/13832317/ead4292e-ebe3-11e5-9156-5544cf4b2704.png)

version: Duplicati 2.0.0.99- 2.0.0.99_preview_2016-02-15
##

**Comment by ts678** [comment]
Not reproducible on current release. I let it use the original pathnames (as it looks like you did) in spite of a popup warning that:

> This backup was created on another operating system. Restoring files without specifying a destination folder can cause files to be restored in unexpected places. Are you sure you want to continue without choosing a destination folder?

```
$ cd /
$ ls -lR C*
'C:':
total 4
drwxr-xr-x 2 root root 4096 Jan 25 18:48 'backup source'

'C:/backup source':
total 4
-rw-r--r-- 1 root root 88 Dec 17  2022 short.txt
$ find C*
C:
C:/backup source
C:/backup source/short.txt
```

Most likely this was fixed over the years. Last call for any additional comments.
