### ISSUE TITLE
WebUI schedule can make Duplicati server busy

### ISSUE THREAD

**Issue by Simpelton** [duplicati/duplicati#1635]
Duplicati 2.0.0.91 just finished a backup. The web UI sais all jobs finished. Debug life log in WebUI sais the same, no more server activity. But the Duplicati-server.exe is consuming 50% of my CPU and the Duplicati-server.sqlite is constantly growing. Every few seconds a Duplicati-server.sqlite-journal file is created and removed again int my users Roaming\Duplicatir directory. Pausing the service via WebUI does not change any thing.Windows 7, fully patched. After this has been going on for half an hour, I kicked the duplicati.server.exe. After restarting the duplicati-server.exe, this picked up again right away. Recheck of life logs, did not show any entry what so ever.

**Comment by kenkendk** [comment]
Do you know what schedule you have selected that makes it go crazy?

**Comment by Simpelton** [comment]
I have tried to recreate the issue, but have not come up with a clear pattern. At least I found a scheduler error message in the stored logs (and not in the live logs):
`System.Exception: Unable to find a valid date, given the start date 24.03.2016 02:05:00, the repetition interval 1W and the allowed days Saturday bei Duplicati.Server.Scheduler.GetNextValidTime(DateTime basetime, DateTime firstdate, String repetition, DayOfWeek[] allowedDays) bei Duplicati.Server.Scheduler.Runner()`

I was under the impression that I need to set a "strange" schedule AND run the backup in order to get the server run wild. But it seems I can not trigger it this way, so maybe the schedule check for the next run is triggered differently.

One of the schedules I suspect can trigger this the attached screen.
![schedule not working](https://cloud.githubusercontent.com/assets/1365007/14155950/4208214c-f6c4-11e5-9f4d-400b68422ec1.PNG)

I have updated to the current build 2.1.0.7, but this does not seem to change this phenomena.

BTW - Great work, thanks for creating and improving this great piece of software :-)

**Comment by renestach** [comment]
Just a side note: Although you have updated, you are still using the old user interface? Do you access it through a bookmark orhow else did you manage not to run the new interface?

**Comment by Simpelton** [comment]
Thx for the hint - I am / was using a bookmark and tripped over the new interface yesterday. The screen shot is a bit older from when I started my experiments to recreate the issue. I have duplicati running as a service on windows and thus do not use the tray icon. In my browser I use a bookmark.

FRQ: It might be worth considering to add a link/button in the old interface that directs people over to the new interface so people who just run the regular update find this cool new feature more easily.

**Comment by Simpelton** [comment]
This is a screen shot of the current schedule that matches the error message. 
![schedule not working 3](https://cloud.githubusercontent.com/assets/1365007/14158097/9fe4b866-f6ce-11e5-917a-2cda68a20651.PNG)

With the duplicati service running 50% of my CPU with the screwed up schedule, I changed the schedule to include every weekday (check mark in every weekday). Saved my change. This did not change the service behavior, still busy. After 5 minutes without any change, I kicked the task Duplicati.Server.EXE and restarted my service. Now the service seems idle as it should be.

**Comment by FGM** [comment]
I gave other details over at #1745 but looking at logs history, I have the same issue: the logs are filled with messages like this one  "2016-06-18 18:04: Scheduler failed to find next date". Page upon page of this is filling the log.

**Comment by FGM** [comment]
Looking at the code, the issue seems to be with the logic in the lines below (take with a grain of salt, I don't know C#):
```
        public static DateTime GetNextValidTime(DateTime basetime, DateTime firstdate, string repetition, DayOfWeek[] allowedDays)
        {
            DateTime res = basetime;

            int i = 50000;

            while ((!IsDateAllowed(res, allowedDays)|| res < firstdate) && i-- > 0)
                res = Timeparser.ParseTimeInterval(repetition, res);
```

The logic is essentially to browse for dates by varying on the interval to build a value of res, then checking if it matches the day criterium. 

However, assuming a 1W interval and only a given day, say Tuesday, as in both cases on this issue, if the scheduling is attempted using this logic any other day besides a Tuesday, say a Saturday the increment will build a Saturday, and fail on the next lines, because Saturday is not an allowed day:

```
            if (!IsDateAllowed(res, allowedDays) || res < firstdate)
```

Whereas the expectation would be that `res` should be the next valid day after `max(basetime, firstdate)`.

As I said, though, I don't know C# and did not look at the whole impressive code base, so maybe I'm wrong here.

**Comment by kenkendk** [comment]
The idea was to compute the next date, based on the start date.
But this can lead to problems if you disallow certain dates, as you may hit something that will never hit a valid day.

I have updated the logic to pick the next valid date.

As an example, if today is Monday, and I only allow running on Fridays, with repeat=3D, then the two approaches differ. 

Both start out by saying today+3D, hitting Thursday.

The old algorithm would then apply +3D repeatedly, hitting Sunday, Wednesday, Saturday, Tuesday, Friday.
So you end up with running only every 7/3=2.3 weeks.
This approach could be written as "Run every 3 days, but only if the date is Friday".

The new approach takes the next matching day, Friday, so you end up running every week.
The new computation can be described as "Run no more than every 3 days, and only Fridays".

I don't think one variation is more intuitive than the other, but at least the new one makes it impossible to schedule an invalid date, where the other would break if you had "7D" as the interval, and the start day was not in the allowed set.
