### ISSUE TITLE
aes-set-threadlevel missing at general settings

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1639]
I'm running 2.0.1.7 but the **aes-set-threadlevel** option is missing from the dropdown menus in the settings. It should be available in 2.0.17, no?
##

**Comment by FootStark** [comment]
It should be, as an advanced option in step 4.
Plaese note that this option is a setting for the AES-encryption module and thus only available, if AES encryption is selected (step 1).

![image](https://cloud.githubusercontent.com/assets/17236227/13904205/24fb2078-ee99-11e5-9688-3d8d562b9e10.png)

**Comment by agrajaghh** [comment]
ah thanks, I just looked at the general settings not at the different jobs. What do you think about setting a default value in the general setttings as well? I have several backup jobs and so its easier to set the options just once instead of configuring everything multiple times...

**Comment by kenkendk** [comment]
You can set the advanced options in the general settings, and they are then applied to all backups.
Also, the multithreading will be default enabled in the next canary build (most likely available tonight).

**Comment by agrajaghh** [comment]
@kenkendk my problem is that its not available there:
![screen](https://cloud.githubusercontent.com/assets/5296073/13904357/18315588-ee9e-11e5-830b-cc0ba74602ee.png)

**Comment by kenkendk** [comment]
Yes, I rememer now. The problem is that if they are set there, then you get warnings on all jobs that are not using AES encryption. I have the infrstructure to support this, but it is not fully implemented.

**Comment by FootStark** [comment]
@agrajaghh `0 (uses default)` is misleading here. It means it will use the library's (that is: `SharpAESCrypt`'s) default (which currently is no multithreading) instead of settng it explicitly.
Coming to think of it, it might be a good idea to extend the library and allow it to load this value via an environment var...

**Comment by kenkendk** [comment]
I have implemented it in the new canary build as default=min(4, processorcount).

**Comment by agrajaghh** [comment]
@kenkendk just an idea, but what do you think about `min(4, processorcount/2)` since duplicati is almost always running in the background and people dont expect it to fully consume all ressources?

**Comment by agrajaghh** [comment]
@kenkendk just an idea, but what do you think about `min(4, processorcount/2)` since duplicati is almost always running in the background and people dont expect it to fully consume all ressources?

edit:

**Comment by ts678** [comment]
> I have implemented it in the new canary build as default=min(4, processorcount).

on Mar 20, 2016 seemingly refers to this Mar 19 commit, in case anyone wondered.

[Enabled streaming and multithreading in encryption by default](https://github.com/duplicati/duplicati/commit/eea33a764958b3f0f3ede286aec8cd2a8fdb87e6)

Maybe this removes this issue's request to set the default using `Default options`?
