### ISSUE TITLE
ngax: "Import Configuration" is missing

### ISSUE THREAD

**Issue by donestefan** [duplicati/duplicati#1640]
The ngax theme offers a way to export the configuration of a backup job to a (encrypted) file. 
But it does not provide a way to re-import  a configuration from a (encrypted) file. 

Please add an "import settings" option to the menu items "Add new backup" and "Restore backup".

**Comment by kenkendk** [comment]
Yes, that one slipped. You can still get it with an url hack.
Click on the "Add new backup ...", then change the `#add` in the url to `#import` and it should work.

@renestach Do you have an opinion on where the link should be placed?

**Comment by renestach** [comment]
I'd say we put it next to "export ...".

**Comment by renestach** [comment]
Maybe on top of the "Add new backup" dialog?

**Comment by donestefan** [comment]
Hi, the URL hack works fine for (permanently) importing Backup Jobs. Thanks for the hint!
I'm looking forward to see it in the menu :)

However it ist not possible to load an exported config file under "http://127.0.0.1:8200/ngax/#/restoredirect" - which would save you from the hassle of filling out the form (e.g. when restoring a backup on a different host). Do you want me to add this as a separate feature request?

**Comment by kenkendk** [comment]
Yes, I have to do some work to add that feature so please add it as a new issue
