### ISSUE TITLE
Enhancement: Restore from exported config file

### ISSUE THREAD

**Issue by donestefan** [duplicati/duplicati#1641]
The "Direct Restore" Feature in the ngax theme (called "Restore from Tagret" in greeno) is very convenient for restoring Backups on a different host.
It would be even more convenient if I would be able to import the necessary settings from an exported (possibly encrypted) configuration file - instead of filling out the form manually.
##

**Comment by kenkendk** [comment]
This is possible in NGAX, but it was hard to find the menu.
With commit e4d8058 it became an option under the "Add backup ..." menu.
