### ISSUE TITLE
Error in updater

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1642]
sorry for the german log (is there a way to show the logs in english?):
```
System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. --->
System.Net.Sockets.SocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 54.231.16.244:443
	bei System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
	bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- Ende der internen Ausnahmestapelüberwachung --- 
	bei System.Net.WebClient.DownloadFile(Uri address, String fileName)
	bei Duplicati.Library.AutoUpdater.UpdaterManager.CheckForUpdate(ReleaseType channel)
```

If I check for updates I always get this. I'm currently running 2.0.1.8 but I can see these entries there since 2016-02-17, so its an older problem I guess?

**Comment by kenkendk** [comment]
Do you have a custom url set up for the updater? Or perhaps a firewall rule?

The error message indicates that the target computer could not be reached, but it is an Amazon S3 machine which are generally stable and online.

**Comment by agrajaghh** [comment]
Ah, I just remembered that I set this environment variable some time ago to get the latest version:
`AUTOUPDATER_Duplicati_URLS=https://updates.duplicati.com/rene/latest.manifest`

I'll remove it and test again....

**Comment by agrajaghh** [comment]
no error anymore, sorry about that :pensive:
