### ISSUE TITLE
exclude filters are not working correctly in the UI

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1643]
no matter what I select here, nothing is applied/saved (running 2.0.1.8):
![exclude](https://cloud.githubusercontent.com/assets/5296073/13907730/59c5801c-eef5-11e5-9908-047b51779d22.png)

they don't work in step 4 either (just tested with  --skip-files-larger-than)

**Comment by agrajaghh** [comment]
The filters are now (2.0.1.10) working for me on the "source data" tab :blush: 

But if I put `--skip-files-larger-than=2gb` in the advaced options and click save, the following is happening the next time I edit the options:
* at the "source data" tab, just "2" is displayed, the unit field is empty (no GByte)
* in the advanced options `--skip-files-larger-than=2gb` disappeared

With `exclude-files-attributes` it's even more weird. After adding `--exclude-files-attributes=System` in the advanced options and saving, the checkbox at "source data" isn't filled and `exclude-files-attributes` is missing from the advnaced options. So there is no indication that this option was set. Adding `--exclude-files-attributes=System` again leads to the popup message "Duplicate option exclude-files-attributes".

This doesn't seem like the expected behaviour. I'm not sure whats best. I think it would make sense to remove `skip-files-larger-than` from the advanced options since it doesn't make sense to integrate it twice. 
But `exclude-files-attribute` is a complicated option which isn't fully available in the UI (yet?) so it is still necessary in the advanced options...

**Comment by kenkendk** [comment]
The `--skip-files-larger-than` issue happens because the dropdown with size is case-sensitive. If you enter `2GB` in the advanced options, it works. But for some reason the advanced option picker dropdown uses "2gb", which is why it fails.

**Comment by kenkendk** [comment]
Same issue with `--exclude-files-attributes=System`, in this case it expects `system`.
