### ISSUE TITLE
constraint failed UNIQUE constraint failed

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1644]
running 2.0.1.8 I'm getting the following error while running the backup (I stopped the initial backup before):
```
2016-03-21 12:06: Message
Fatal error
System.Data.SQLite.SQLiteException (0x80004005): constraint failed

UNIQUE constraint failed: Remotevolume.Name, Remotevolume.State
   bei System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLiteDataReader.NextResult()
   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bei Duplicati.Library.Main.Database.ExtensionMethods.ExecuteScalarInt64(IDbCommand self, String cmd, Int64 defaultvalue, Object[] values)
   bei Duplicati.Library.Main.Database.LocalDatabase.RegisterRemoteVolume(String name, RemoteVolumeType type, RemoteVolumeState state, Int64 size, TimeSpan deleteGraceTime, IDbTransaction transaction)
   bei Duplicati.Library.Main.Database.LocalDatabase.RegisterRemoteVolume(String name, RemoteVolumeType type, RemoteVolumeState state, TimeSpan deleteGraceTime, IDbTransaction transaction)
   bei Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   bei Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   bei Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)
   bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

2016-03-21 12:06: Message
scheduling missing file for deletion, currently listed as Uploading: duplicati-b9e485d70a11e458eb5faedcb7f9a6c62.dblock.zip.aes

2016-03-21 12:06: Message
removing file listed as Temporary: duplicati-20160321T105840Z.dlist.zip.aes
```
If I'm running repair I'm getting the same error.

**Comment by agrajaghh** [comment]
I created another backup job, but during the initial backup (100GB), I stopped duplicati by clicking "Quit" at the tray icon. Duplicati continued uploading, so I killed `Duplicati.GUI.TrayIcon.exe` in the taskmanager after the upload of 8 additional files (dblock & dindex). Now I got the same error message as above. It seems like duplicati doesn't correctly handle aborting the backup process.

**Comment by agrajaghh** [comment]
**Recreate (delte and repair)** fixed it for me at the second job (I kept the first, in case you need some more info). But that can't be the solution everytime you shut down the process...

**Comment by kenkendk** [comment]
The new build should have a fix for the `constraint violation` message:
https://github.com/duplicati/duplicati/releases

**Comment by agrajaghh** [comment]
@kenkendk unfortunately I'm getting another error now with 2.0.1.9 (same backup job):

```
Fatal error
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei System.Data.SQLite.SQLiteDataReader.GetSQLiteType(SQLiteConnectionFlags flags, Int32 i)
   bei System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   bei Duplicati.Library.Main.Database.LocalDatabase.<DuplicateRemoteVolumes>c__Iterator1.MoveNext()
   bei Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   bei Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   bei Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)
   bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

**Comment by kenkendk** [comment]
Ok, that hits inside the new repair code. I will have a look.

**Comment by Leafar3456** [comment]
Having the same problem. First the UNIQUE constraint failed now also this:

`Fatal error
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Data.SQLite.SQLiteDataReader.GetSQLiteType(SQLiteConnectionFlags flags, Int32 i)
   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   at Duplicati.Library.Main.Database.LocalDatabase.<DuplicateRemoteVolumes>c__Iterator1.MoveNext()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)`

**Comment by mylemans** [comment]
Same issue here (as in, getting Index outside of bounds with the 'Canary' build)

**Comment by agrajaghh** [comment]
with 2.0.1.10 I'm getting this error while running the backup:
```
System.Exception: Detected file entries with not associated blocks 
	bei Duplicati.Library.Main.Database.LocalDatabase.VerifyConsistency(IDbTransaction transaction, Int64 blocksize, Int64 hashsize) 
	bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter) 
	bei Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result) 
	bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) 
	bei Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) 
	bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by joolsr** [comment]
I think I have the same issue, sorry i diodnt check for this issue first, you can find my ticket [here ](https://github.com/duplicati/duplicati/issues/1674)

**Comment by kenkendk** [comment]
@agrajaghh Is this from a recreated database or an existing database?

**Comment by agrajaghh** [comment]
@kenkendk existing database

**Comment by kenkendk** [comment]
@agrajaghh Can you send me a bugreport from that database?

**Comment by Leafar3456** [comment]
The latest update fixed the original issue for me. Everything running smoothly now.

**Comment by zertrin** [comment]
I also had the issue in the latest experimental (2.0.1.7_experimental_2016-03-19), and couldn't recreate the database correctly (even after deletion).

I switched to the latest canary version (2.0.1.10_canary_2016-03-31) and the database could be recreated, and my backup could be run again.

**Comment by kenkendk** [comment]
@agrajaghh 
The error message comes from an additional error check that I added.

I looked through the database, and it was created from remote data at some point (with an earlier version of Duplicati).

It has a 8 entries that are incorrectly stored (file-id's here):
"199","794","796","797","798","799","1101"

Does the problem also arise when you recreate with the current Duplicati version?
(Also, this should probably go into its own issue, as it is not related to the original issue).

**Comment by agrajaghh** [comment]
@kenkendk just recreated the db sucessfully with 2.0.1.10. 

weird thing is that all of the "broken" files are movies:
199: C:\Users\User\Pictures\2014-12-30 blubb1\VID_20141231_143111671.mp4
794: C:\Users\User\Pictures\2013-08-15 blubb2\DSC_0194.MOV
796: C:\Users\User\Pictures\2013-08-15 blubb2\DSC_0198.MOV
797: C:\Users\User\Pictures\2013-08-15 blubb2\DSC_0200.MOV
798: C:\Users\User\Pictures\2013-08-15 blubb2\DSC_0202.MOV
799: C:\Users\User\Pictures\2013-08-15 blubb2\DSC_0207.MOV
1101: C:\Users\User\Pictures\2013-12-31 blubb3\blubb3\MVI_8617.MOV

Did you make code changes to the recreation process betwenn 2.0.1.8 and 2.0.1.10? If so I guess we should treat this as fixed (and close it), otherwise I can open a new issue?

**Comment by SpamsAlex** [comment]
Hi, 

I think I have the same issue.I use the 2.0.1.7 on Windows 10 and try to do my first backup. But as it's too big I add to stop the process, but when I try to restart it, I have the messages below:

2016-04-05 16:39: Message
scheduling missing file for deletion, currently listed as Uploading: duplicati-20160403T070749Z.dlist.zip.aes

2016-04-05 16:38: Message
Fatal error
System.Data.SQLite.SQLiteException (0x80004005): constraint failed UNIQUE constraint failed: Remotevolume.Name, Remotevolume.State à System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt) 
à System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt) 
à System.Data.SQLite.SQLiteDataReader.NextResult() 
à System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave) à System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior) 
à Duplicati.Library.Main.Database.ExtensionMethods.ExecuteScalarInt64(IDbCommand self, String cmd, Int64 defaultvalue, Object[] values) 
à Duplicati.Library.Main.Database.LocalDatabase.RegisterRemoteVolume(String name, RemoteVolumeType type, RemoteVolumeState state, Int64 size, TimeSpan deleteGraceTime, IDbTransaction transaction) 
à Duplicati.Library.Main.Database.LocalDatabase.RegisterRemoteVolume(String name, RemoteVolumeType type, RemoteVolumeState state, TimeSpan deleteGraceTime, IDbTransaction transaction) 
à Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log) 
à Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log) 
à Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend) 
à Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

How can I fix it? 

Thank you.

**Comment by zertrin** [comment]
See the [reports](https://github.com/duplicati/duplicati/issues/1644#issuecomment-204805685) above: upgrading to 2.0.1.10, deleting the database and repairing it worked for me.

**Comment by SpamsAlex** [comment]
Where did you get the 2.01.10 version?

**Comment by agrajaghh** [comment]
@SpamsAlex have a look at https://github.com/duplicati/duplicati/releases

**Comment by SpamsAlex** [comment]
Thanks. I installed this version. 
When I do a repair I have the message:" Failed while executing "Backup" with id: 2"

@zertrin did you do a repair after installing the 2.0.1.10 version? Or did you do recreate the database?

**Comment by zertrin** [comment]
@SpamsAlex I deleted the database, and then started a repair. I made sure beforehand that no backup was scheduled.

**Comment by zertrin** [comment]
Hum you were saying that you were trying to do your first backup. In that case I don't think that you can repair because there is no data to repair the database from... ("repair" downloads the metadata from the backup storage and reconstruct the local database based on that metadata, but since you don't seem to have done a full backup yet, there is no metadata to recover from)

Maybe you can try to stop duplicati, delete the database, start duplicati, and start your backup.

**Comment by SpamsAlex** [comment]
OK, thanks

**Comment by agrajaghh** [comment]
> Hum you were saying that you were trying to do your first backup. In that case I don't think that you can repair because there is no data to repair the database from... ("repair" downloads the metadata from the backup storage and reconstruct the local database based on that metadata, but since you don't seem to have done a full backup yet, there is no metadata to recover from)
> 
> Maybe you can try to stop duplicati, delete the database, start duplicati, and start your backup.

afaik, there is still data on the remote storage. Anyway I would just try to use repair wihtout deleting the db first...

**Comment by JonasDralle** [comment]
still doesn't work.  
A few days ago i killed it via the tray and after my ingame ping didn't improve i also killed the process. It's annoying when I need to use the computer but some process just won't make room inside the bandwidth.

Sorry but i thought killing the process was normal software usage

I wanted to open a new issue but this here doesn't seem to be dead and I have additional information to offer.

---

```
System.Data.SQLite.SQLiteException (0x80004005): constraint failed

UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Duplicati.Library.Main.Database.LocalBackupDatabase.AddUnmodifiedFile(Int64 fileid, DateTime lastmodified, IDbTransaction transaction)
   at Duplicati.Library.Main.Operation.BackupHandler.AddUnmodifiedFile(Int64 oldId, DateTime lastModified)
   at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
```

### Bug description
My Backup just crashes with SQLException. Repair routine runs fine and produces no error. I created the Backup (as well as the data) in one of the previous stable builds duplicati 2 (sadly i don't know which exactly, it was within the last year.)

### [Backup (exported as json)](http://pastebin.com/W6atAE14)
### [Backup Results](http://pastebin.com/kk1JbBxq)
### [Log](http://pastebin.com/2ZTerzFh)
Bug report is still being generated (waited 10 min). I will deliver it once it's ready.


I hope this helps

**Comment by JonasDralle** [comment]
Bugreport.zip was generated
[system-info.txt on Pastebin](http://pastebin.com/keik9U3r)
log-database.sqlite was too big to upload on pastebin.

Download bugreport.zip here:
[Mirror 1](http://www.file-upload.net/download-11945061/bugreport.zip.html
), [Mirror 2](http://filer.net/get/labzoffikmzc9jwc)

**Comment by kenkendk** [comment]
@JonasDralle The error you have is slightly different.
It can happen if the same file is attempted to be backed up twice.
There was a fix to prevent a situation where this would happen in the latest canary:
https://github.com/duplicati/duplicati/releases

I think this fixes your problem.

@agrajaghh: You reported this issue originally, but it looks like it has been resolved?

**Comment by agrajaghh** [comment]
> @agrajaghh: You reported this issue originally, but it looks like it has been resolved?

I had tried to recreate the db and restore files with the current canary and it worked without problems on the broken backup :)
