### ISSUE TITLE
exclude filter using %HOME% isn't working on windows

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1645]
If I set the source folder to
`%HOME%`
and use this filter:
`-%HOME%\Pictures\`

the pictures are still included in my backup.

If I use the real path as source folder:
`C:\Users\Username\`
and the corresponding filter:
`-C:\Users\Username\Pictures\`

it is working as expected. Tested on Windows 10 with duplicati 2.0.1.8

**Comment by Zero3** [comment]
I can confirm. Was hit with the same bug on a fresh installation.

**Comment by kenkendk** [comment]
The fix for this is to make the environment variable expansion for filters use the "%HOME% and similar variables used to indicate user profile folders.
