### ISSUE TITLE
Choose File Size

### ISSUE THREAD

**Issue by tkngit** [duplicati/duplicati#1649]
Running 1.3.4, German
Within the options pane for save-destination (sorry for my english translatetion) there is an info that it may make sense to change the filesize - but there is no option to do so, no entry field, up/down button etc.
![duplicati-options](https://cloud.githubusercontent.com/assets/18016275/13968264/1bf45fb4-f07c-11e5-94a8-4dc67308179c.JPG)

**Comment by kenkendk** [comment]
The file size is not on that page. IIRC it is on the next-to-last page where you need to specify "adjust limits, size throttle etc".

**Comment by kenkendk** [comment]
Closing for due to inactivity
