### ISSUE TITLE
Value cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by Kroesss** [duplicati/duplicati#1654]
I'm new to using Duplicati, and I am on 2.0.1.7_experimental_2016-03-19

I used it to backup a test-folder to my WebDav-share, and that went perfectly, so I was going to set it up for the real backups. When I set those up, and pressed "Run now', I get an error message in a red box on the bottom of the browser-screen. It is in Dutch, but it translates to:
`Error while running <backup name>
Value cannot be null. Parameter name: key`
When I click "Show", I get the following message:
`Failed to connect: SQL logic error or missing database no such table: LogData`

I am trying to backup all folders within my user data (My documents, My pictures, Desktop, ...)

Any clues as to what is going wrong?

**Comment by kenkendk** [comment]
If you can get any more information on this issue, that would help.
There is a general "server" log in the menu on the left, where the "show" button leads to the log on the specific backup.

**Comment by Kroesss** [comment]
Hello kenkendk,

When I view that log and open the item, I get the following message;

`
2016-03-24 17:02: Failed while executing "Backup" with id: 1
System.ArgumentNullException: Value cannot be null.
Parameternaam: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Duplicati.Library.Utility.FilterExpression.AnalyzeFilters(IFilter filter, Boolean& includes, Boolean& excludes)
   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   atj Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
`

**Comment by kenkendk** [comment]
Ok, so it is a problem with filters. If you attempt to "export" your backup, you can get a commandline. If you can post that here (without passwords obviously) I can perhaps figure out the cause.

You can also export to a json file, but you need to edit it to make sure there are no passwords or other sensitive information included.

**Comment by Kroesss** [comment]
Hello Kenkendk,

The commandline-export (cleaned for usernames and passwords and such) is this:
'"D:\Duplicati\Duplicati.CommandLine.exe" backup "webdavs://URLtomywebdav.com:443/remote.php/webdav/backups/personal/?auth-username=MyUserName&auth-password=MyPassword" "C:\Users\Kroesss\Documents" "C:\Users\Kroesss\Music" "C:\Users\Kroesss\Pictures" "C:\Users\Kroesss\Videos" "C:\Users\Kroesss\Desktop" "C:\Users\Kroesss\AppData\Roaming" "C:\Users\Kroesss" --backup-name="Personal Files" --dbpath="C:\Users\Kroesss\AppData\Roaming\Duplicati\JZGFZUWMGG.sqlite" --encryption-module="aes" --compression-module="zip" --dblock-size="50mb" --keep-time="3M" --passphrase="MyPassword" --disable-module="console-password-input"'

**Comment by kenkendk** [comment]
Hmm... that does not have any filters. Could you export it to a json file and see if there is a "filter" section?

**Comment by Kroesss** [comment]
There are several instances of "filter", but all of them are empty. Just to make sure I attached the json-file (again after cleaning up usernames and passwords  of course)

[Personal+Files-duplicati-config.json.txt](https://github.com/duplicati/duplicati/files/198049/Personal.Files-duplicati-config.json.txt)

**Comment by Kroesss** [comment]
Hi Kenkendk,

Could you find anything wrong with the filters in the json-file?

**Comment by Kroesss** [comment]
Hello Kenkendk,

I've found out that it does backup when I uncheck "Home" from the items to backup. However, when I create a backup with just the Home-folder, it does perform a backup.

Hope you can work with this info :)

**Comment by Head** [comment]
Same problem here. Have checked all Folders top and no filters. After I added a filter to ignore folders with asdfsdaf it works.

**Comment by ovizii** [comment]
Exactly the same issue here, unchecking HOME works fine. Latest Chrome in use here.

**Comment by kenkendk** [comment]
So it seems that "HOME" is somehow returning an empty folder. I will try to fix that.

**Comment by agrajaghh** [comment]
related to #1645?

**Comment by kenkendk** [comment]
I just tried reproducing on my Windows 10 machine, and I cannot trigger the problem.
I was using Edge.

Based on the descriptions here, it seems that `%HOME%` resolves to an empty string.
I looked in the source, and the mapping is done from `%HOMEDRIVE%%HOMEPATH%`.
This should work, but I can see that there may be some quirks:
https://support.microsoft.com/en-us/kb/101507

I will replace this with the Environment.SpecialFolder.Personal:
https://msdn.microsoft.com/en-us/library/system.environment.specialfolder(v=vs.110).aspx

In my test setup, this folder maps to a network drive instead of a local drive, but I assume that users consider this to be the "correct" home.

@Kroesss @Head or @ovizii : could you report what `%HOMEDRIVE%` and `%HOMEPATH%` is set to on your systems?

**Comment by ovizii** [comment]
If I paste these 2 variables into my explorer I get:

```
%HOMEPATH% => C:\Users\myuser
%HOMEDRIVE% => C:\
```

**Comment by kenkendk** [comment]
Thanks, that explains it, `%HOMEDRIVE%%HOMEPATH%` is expanded to "C:\C:\Users\myuser", which is not a valid path.

**Comment by kenkendk** [comment]
Hmm, it turns out `Personal` is an alias for `Documents`, which is not the root user folder.

**Comment by kenkendk** [comment]
The right one was `UserProfile`, and it returns the expected `C:\Users\username`.

**Comment by Kroesss** [comment]
I could not check earlier because I was at work, sorry. I'm getting the same locations as ovizii.

**Comment by timonoj** [comment]
Hi, I'm getting this same error...but I'm running a headless BananaPi. 
 Failed to connect: SQL logic error or missing database no such table: LogData

**Comment by agrajaghh** [comment]
@timonoj what version are you running?

**Comment by timonoj** [comment]
Version v2.0.1.30_experimental_2016-11-03.

The error:
Mono.Data.Sqlite.SqliteException: SQLite error
no such table: LogData
  at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, UInt32 timeoutMS, System.String& strRemain) [0x00000] in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x00000] in <filename unknown>:0 
Mono.Data.Sqlite.SqliteException: SQLite error
no such table: LogData
  at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, UInt32 timeoutMS, System.String& strRemain) [0x00000] in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x00000] in <filename unknown>:0 

Thanks!

**Comment by agrajaghh** [comment]
can you please try 2.0.1.31?

**Comment by timonoj** [comment]
Can you provide link? The only debian package I see is 2.0.1.30_1:
http://updates.duplicati.com/experimental/duplicati_2.0.1.30-1_all.deb
