### ISSUE TITLE
Local storage gets corrupted, repair is needed but there's no option for it

### ISSUE THREAD

**Issue by borg4242** [duplicati/duplicati#1655]
Loved v1.x, tried v2.
- Created an encrypted backup with just one directory, ran it, all OK with a warning about a file being used that is OK to skip for me.
- Tried restoring to a different directory, all OK.
- Created a second non-encrypted backup with just one file, ran it, got this error: "Found 3 remote files that are not recorded in local storage, please run repair".
- I haven't found a repair option on the screen or in the documentation.
- Googling suggests some directories need to be wiped and/or maybe there's some command line tool somewhere that could be run with some parameters but nothing seemed to be conclusive.

Not sure what has caused the error. Also, maybe repair is there but not implemented in the UI? Maybe it just needs documentation re: missing features? Also, if it turns out repair is to be run from the console, please mention this in the error message, a link to the doc describing how to do that would be even nicer.

Win7, Duplicati 2.0.1.7- 2.0.1.7_experimental_2016-03-19, NTFS

Good luck to your work -- when Duplicati v2 gets stable it's going be a really good tool.

**Comment by renestach** [comment]
Did you run the second backup to the same folder as the first backup? That could explain why Duplicati complains that there more backup files than expected. If so, I recommend to sort the remote files by date and remove the latest backup.

The repair is available when you click the backup and choose "Manage local database...".

**Comment by agrajaghh** [comment]
you can find repair under Advanced -> Manage local database:
![repair](https://cloud.githubusercontent.com/assets/5296073/14017234/63a14a20-f1c6-11e5-99c7-ede410ca0c05.png)

also I think there is bug

**Comment by borg4242** [comment]
@renestach Yes, the destination folders were the same. When I was using 1.x I _think_ I was using the same target folder for all my backups and it was working.

If selecting the same destination folder corrupts the application state, I'd suggest at least warning about this on the UI.

@agrajaghh Oh dear I missed that, haven't gone in there.

Probably Repair could be propagated to this screen or the error message could be extended describing where this can be done.

Thank you both.

**Comment by kenkendk** [comment]
@borg4242 You can store multiple backups in the same folder, but then you need to change the prefix, otherwise there is no way of telling which files belong to which folder. That was the same problem in 1.3.x.

I will add a new issue requesting that the remote folder is checked when creating a new backup and warn if there are existing files there.

**Comment by kenkendk** [comment]
And for the repair, hopefully it will not be required that users go into that menu in the future :)

**Comment by kenkendk** [comment]
Closing as the underlying problem has been moved to #1656
