### ISSUE TITLE
2.0.1.7 System.Globalization Error 

### ISSUE THREAD

**Issue by luni64** [duplicati/duplicati#1659]
After updating to 2.0.1.7 I get the following Error when I start a Backup: 

![image](https://cloud.githubusercontent.com/assets/12611497/14058255/f3e3ea48-f31a-11e5-8751-f0b91f8f95f5.png)

Thanks
Lutz

**Comment by renestach** [comment]
The green bottom bar looks like the old user interface. Does it work if you switch to the new one (which should be default now)?

**Comment by luni64** [comment]
Oh, the new interface looks great, didn't notice this. 

Anyway, same bug: 
![image](https://cloud.githubusercontent.com/assets/12611497/14059065/8b0f120c-f335-11e5-87ee-e4ece549c75b.png)

**Comment by FootStark** [comment]
Same as #1606. Which environment?
Please install .NET Framework 4.5

**Comment by luni64** [comment]
Does it neet to be exactly 4.5? I have installed 4.0 and 4.6.1. 
Environment is Win10, Browser Chrome V49. Duplicati Server runs on a Suse Linux system. 

![image](https://cloud.githubusercontent.com/assets/12611497/14059744/fb475bbc-f34c-11e5-826c-0192fc4c8632.png)

**Comment by FootStark** [comment]
No, 4.6.1 is fine. But the error is happening on the server, so it's the MONO environment which would need an update. Sadly, I am not sure what mono version complies to what .NET Framework version and what is currently available as a package for Suse. We tried to fix the next release, that locales are not set if they are not available. So if an Mono-update does not help, you can try this.

**Comment by luni64** [comment]
Tried to update mono. I now have Version 3.0.6-3.1.3. Error still there.

If I understand you correctly I'll have to wait for the next duplicati update? No problem for me. Any idea when the update will be available?

**Comment by FootStark** [comment]
Not sure if this is compatible, but there are mono versions > 4... ;http://www.mono-project.com/docs/getting-started/install/linux/#opensuse-and-sles
For duplicati there are canary-builds (=experimental nightlys) pretty often that incorporate the latest changes. There might be even one tonight.

**Comment by renestach** [comment]
I think at least 3.10 is required.

**Comment by kenkendk** [comment]
There is a new canary update available now (which should fix the problem):
https://github.com/duplicati/duplicati/releases

**Comment by luni64** [comment]
Tried to install the canary update but I can't switch to the canary update channel. It doesn't keep the setting, and always switches back to default channel..... Do you think a reinstall of duplicati makes sense? If so, can I export my settings somehow?

**Comment by kenkendk** [comment]
Can you provide a screenshot? Are you clicking the "Save" button at the end of the page?

**Comment by luni64** [comment]
There only is an OK Button at the end of the page. Pressing it does not have any visible effect. Switching to another page and switching back to the settings page resets everything back. Is duplicaty logging to syslog? Didn't find anything under /var/log

![image](https://cloud.githubusercontent.com/assets/12611497/14088400/98f9606a-f52f-11e5-9746-55aa75d4c1c3.png)

**Comment by mylemans** [comment]
@luni64 See https://github.com/duplicati/duplicati/pull/1666

**Comment by luni64** [comment]
That fixed the Settings OK Button. Uploading the  last canary then fixed the original issue. 
Thanks for the help
Lutz
