### ISSUE TITLE
working tray icon not displayed

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1663]
on 2.0.1.9 the working icon isn't displayed for me on windows 10

I guess its because of https://github.com/duplicati/duplicati/commit/30846f36ffa0c5bcff1e366f7fddcf961dab20f4

".ico" is missing here: https://github.com/duplicati/duplicati/blob/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/ImageLoader.cs#L82

**Comment by kenkendk** [comment]
Is there no icon then or is it displaying another icon?

**Comment by agrajaghh** [comment]
Its displayed as the `Resources.TrayNormal.ico` instead

**Comment by kenkendk** [comment]
Arh, I did not see the .ico thing in line 82.

**Comment by kenkendk** [comment]
That should fix it.
