### ISSUE TITLE
I can't change settings with the latest 

### ISSUE THREAD

**Issue by irregularisnotrandom** [duplicati/duplicati#1664]
I am trying to change the statistics report to "none"  but it is not working out. I change it to "none" then click on "Ok". However there is no action or no indication of any saving is done on the screen. I see that the settings are at defaults the next time I open the settings page. It looks like the click button function is broken.

I tried it with multiple browsers.

"You are currently running Duplicati 2.0.1.7- 2.0.1.7_experimental_2016-03-19"

**Comment by mattti** [comment]
I have the same issue.
When I click 'OK', Firebug gives me:
`Error: any is not defined
$scope.save@http://127.0.0.1:8200/ngax/scripts/controllers/SystemSettingsController.js:38:13
anonymous/fn@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js line 212 > Function:2:200
Kc[c]</<.compile/</</f@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:252:74
jf/this.$get</n.prototype.$eval@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:134:489
jf/this.$get</n.prototype.$apply@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:135:212
Kc[c]</<.compile/</<@http://127.0.0.1:8200/ngax/scripts/angular/angular.min.js:252:124
n.event.dispatch@http://127.0.0.1:8200/ngax/scripts/libs/jquery.min.js:3:6414
n.event.add/r.handle@http://127.0.0.1:8200/ngax/scripts/libs/jquery.min.js:3:3224`

**Comment by mylemans** [comment]
See https://github.com/duplicati/duplicati/pull/1666

**Comment by kenkendk** [comment]
This was fixed my @mylemans with PR #1666
