### ISSUE TITLE
[feature request] keep number of daily/weekly/monthly backups

### ISSUE THREAD

**Issue by stloewen** [duplicati/duplicati#1668]
At the moment it is only possible to tell Duplicati2 to keep all backups for a specified period of time.

It would be very comfortable to be able to configure duplicati to keep e.g.:
7 daily
4 weekly
3 monthly
1 yearly
backups. This kind of pruning is possible in borgbackup with `borg prune` ([link](http://borgbackup.readthedocs.org/en/stable/usage.html#id20)).

As far as I understand the duplicati2 storage format this should be possible, right?
##

**Comment by renestach** [comment]
Yes, the storage system allows to do this:

Benefits:
1. Reduce number of backups and thus the "complexity" for users.
2. Reduce the backup size

Drawbacks:
1. Required, specific version of a file might get deleted.
2. Deleted data requires stronger compacting resulting in more uploads.

Anything I missed?

**Comment by jayongg** [comment]
About Drawback #1 - why would that be more of an issue with this feature compared to the current retention strategy?

**Comment by JonMikelV** [comment]
I believe this is handled by the `--retention-policy` parameter which was added to the GUI with v2.0.2.17 canary (https://forum.duplicati.com/t/release-2-0-2-17-canary-2018-01-23/2194) so I have closed the issue.  Please let me know if you disagree that it has been resolved.
