### ISSUE TITLE
Cannot restore from S3-compatible storage

### ISSUE THREAD

**Issue by rurku** [duplicati/duplicati#1677]
When restoring from a third party S3-compatible storage I'm getting error log messages:
`Operation Get with file duplicati-20160401T181003Z.dlist.zip.aes attempt 1 of 5 failed with message: Invalid S3 URI - hostname does not appear to be a valid S3 endpoint => Invalid S3 URI - hostname does not appear to be a valid S3 endpoint`

Same errors pop up during backup in the verification stage.

I investigated and found that AWSSDK 2.3.10.0 (the version used by Duplicati) validates the endpoint hostname against this regex: `^(.+\.)?s3[.-]([a-z0-9-]+)\.`. https://github.com/aws/aws-sdk-net/blob/2.3.10.0/AWSSDK_DotNet35/Amazon.S3/Util/AmazonS3Uri.cs#L79
In case of my storage provider the hostname does not match. 

This is fixed since AWSSDK 3.0.4.0: https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Internal/AmazonS3KmsHandler.cs#L82

I built Duplicati with the latest AWSSDK from NuGet and it fixes the problem for me.
Can the library be updated? I could submit a pull request but I'm not sure about the preferences regarding 3rd party libraries. I don't see NuGet being used anywhere in the project.

I'm running v2.0.1.7_experimental

**Comment by cootem** [comment]
I am seeing a similar problem in my logs. Strangely, sometimes this produces a pop-up error message and other times it doesn't, but it seems to always be present in the logs as a message, see specifics below. I tested restoring a single file and it worked without complication.

I am using Amazon S3 type storage at Dreamhost, server objects-us-west-1.dream.io. My update channel is set to 'Canary'.

Does anyone know of a fix that does not involve me modifying the source code?

```
Failed to process file duplicati-be2609945994a40969235de57f4fa7423.dblock.zip.aes
System.ArgumentException: Invalid S3 URI - hostname does not appear to be a valid S3 endpoint
  at Duplicati.Library.Main.BackendManager.GetForTesting (System.String remotename, Int64 size, System.String hash) <0x416b1380 + 0x0011f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.TestHandler.DoRun (Int64 samples, Duplicati.Library.Main.Database.LocalTestDatabase db, Duplicati.Library.Main.BackendManager backend) <0x416aca90 + 0x00dfb> in <filename unknown>:0 
```

**Comment by kenkendk** [comment]
I had not noticed that the AWSSDK had split into a new v3.
I will update with the new library.
