### ISSUE TITLE
Accidentally deleted folder "%APPDATA%\Duplicati", cannot import backups

### ISSUE THREAD

**Issue by lucatrv** [duplicati/duplicati#1681]
As mentioned in the subject, I accidentally deleted the folder "%APPDATA%\Duplicati". I still have the backup destination folders but I cannot find out how to import my backups. I guess the backup configuration is stored in the destination folder, so this should be possible.
I even tried creating a new identical backup, and then manually repairing the local database before running it but I get an error...
##

**Comment by agrajaghh** [comment]
> I even tried creating a new identical backup, and then manually repairing the local database before running it but I get an error..

this should normally work. What is your error message?

**Comment by lucatrv** [comment]
I am currently running Duplicati 2.0.1.7- 2.0.1.7_experimental_2016-03-19.

This is the error I get:
"Found inconsistency in the following files while validating database: d:\Virtual Machines\FolderName\Foo-flat.vmdk, actual size 42949672960, dbsize 23592960, blocksetid: 12 . Run repair to fix it."

Can I try to run the backup over the old one without first repairing the local database or will it overwrite everything in the remote folder?

Thanks

**Comment by lucatrv** [comment]
I found out that if I dismiss the error message and then verify the backup everything goes fine.
I have a second backup (same files, compressed with 7z instead of zip), so I tried the same with it and got exactly the same behavior, so I believe this is a bug.

**Comment by FootStark** [comment]
You are correct, there was a bug in 2.0.1.7 failing on recreation with very large files. Please recreate your dB with the latest canary, there it is fixed.

**Comment by kenkendk** [comment]
I assume this is now fixed.
