### ISSUE TITLE
Enhancement: ease restoring a certain version of a file

### ISSUE THREAD

**Issue by bensoibj** [duplicati/duplicati#1682]
In the file restore dialogue it would be nice to see, in addition to the file name, also the modification time and maybe also the file size. This would ease the case when one want to restore a certain version of a file or the file version _before_ the latest one in the backup (for instance, because you messed up the current file some time ago and need the last clean version). In the current program version (Duplicati 2.0.1.7- 2.0.1.7_experimental_2016-03-19), one has to restore the file from the latest backup, then check its modification time, and in a second restore step select the last backup before this modification time and do again a restore.
##

**Comment by warwickmm** [comment]
I think issue #72 would take care of this.
