### ISSUE TITLE
Backup did not end - Repair not working

### ISSUE THREAD

**Issue by nanoxi** [duplicati/duplicati#1685]
I use following version : 2.0.0.81_preview_2015-02-06 and use commandline batch files to run my backups.

I have a problem with a backup which could not complete because system drive where duplicati backup databases are stored (roaming folder) was full. I decided to move the sqllite backup databases to another drive by editing the json.config file. Now when I run the backup command I get following message :

```
Fatal error => Found 2176 remote files that are not recorded in local storage, p
lease run repair 
```

So far I think it's ok. As the previous backup could not complete I would expect to run a repair command

Then when I run repair I get following message : 
`The process cannot access the file because it is being used by another process.` 

and --log-level=information :

```
2016-04-07 11:27:10Z - Information: The operation Repair has started
2016-04-07 11:27:10Z - Information: Renaming existing db from D:\DuplicatiDB\RSDUZLSXAS.sqlite to D:\DuplicatiDB\RSDUZLSXAS.backup-1
2016-04-07 11:27:10Z - Error: Terminated with error: The process cannot access the file because it is being used by another process.
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.<Repair>c__AnonStorey3.<>m__0(RepairResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
```

It's strange because it generates a new non existing filename "RSDUZLSXAS.backup-1" but somehow the file seems to be locked. I rebooted the server and don't have any other duplicati.commandline.exe processes running

Thanks for your help
##

**Comment by Zero3** [comment]
I just ran into this issue as well :-1:.

None of these things are now possible with my backup job:

* Run backup
* Restore files
* Repair database

@nanoxi Did you find a solution to the problem?

**Comment by nanoxi** [comment]
@Zero3 No fix found. I moved the current backup to another location and started a new one.

**Comment by Zero3** [comment]
@nanoxi Alright, thanks for letting me know!

I think this is quite worrysome, especially the part about losing the ability to restore files from ones backup.

**Comment by ts678** [comment]
After the several of these in 2016, I'm not seeing newer reports in GitHub open and closed issues. Maybe something was fixed.

There's still an issue like this if auto-cleanup is specified, but that would need a backup, and at least original post didn't do that:

> I rebooted the server and don't have any other duplicati.commandline.exe processes running

This issue will automatically close unless there's more to say.

**Comment by Zero3** [comment]
@ts678 I gave up on Duplicati many years ago because of issues like this bug, so I am afraid that I will not be able to provide any more feedback on this. I have no objections to closing this issue, for the reason you write above :).
