### ISSUE TITLE
v2.0.1.12 - Amazon S3 exception - Backup Fails

### ISSUE THREAD

**Issue by NickPyz** [duplicati/duplicati#1691]
Since the upgrade to v2.0.1.12-2.0.1.12_canary I am unable to backup to Amazon S3. I get the following popup:

"The type initializer for 'Amazon.AWSConfigs' threw an exception." 

The 1st line in the logs might provide a clue:

System.TypeInitializationException: The type initializer for 'Amazon.AWSConfigs' threw an exception. ---> System.Runtime.Serialization.SerializationException: Type 'CoCoL.ExecutionScope' in assembly 'CoCoL, Version=1.0.5940.39036, Culture=neutral, PublicKeyToken=**************' is not marked as serializable.

Anything I can do at my end to overcome this? Thanks.

OS: Win 10 (64 bit)

**Comment by NickPyz** [comment]
UPDATE:

Just to be sure there wasn't an unrelated issue with my AWS account, I did a fallback installation to v2.0.1.10 canary. With this version, S3 backups are working. So it appears there is a bug in the ***.12 duplicati release.

Thank you.

**Comment by renestach** [comment]
Yes, others have the same issue, too.

**Comment by NickPyz** [comment]
Connection to Amazon AWS is fixed by the new CoCoL.dll in v2.0.1.13. This closes the issue.
