### ISSUE TITLE
Slow Download Speed while recovering Database

### ISSUE THREAD

**Issue by roterBulle** [duplicati/duplicati#1694]
Hi,

i am currently recovering the database for a Backup of 82 GB.
Duplicati build: 2.0.1.9_canary_2016-03-26.
Duplicati is running on a Synology DS-215j NAS.

backup settings are:
```
--tempdir=/volume2/tmp/
--no-auto-compact=true
--zip-compression-level=2
--threshold=90
```

What i recognized is that while retrieving the dblock files:
Started: duplicati-xxxxxxxxxxxxxxxxxxxx.dblock.zip.aes (2.00 GB)

 The network speed is only 270 Kbyte/s, even though i have a 25MBit connection. 
[edit]
RAM usage is: 45%
CPU usage is: 14%
[/edit]

Also tried out to retrieve another file from the webserver with my Synology and he is retrieving the file in full speed (2MB/s).
This means, neither the Synology nor the Webserver is the bottleneck.

Is there any known limitation? Or any setting which is configured to only use 10% of the connection?

Any help would be appreciated. 
If you need any additional information please tell me.

Thanks

**Comment by saviodsouza** [comment]
I really don't know if this `--enable-piped-streaming` option would help

**Comment by FootStark** [comment]
What backend are you running against? There is a possibility that too much multithreading is inefficiently handled by the OS on the NAS. It is by default enabled in 2.1.0.9.
You might want to play with the following options to verify this:
```
--disable-streaming-transfers
--disable-piped-streaming
--set-aes-threadlevel=1
```

`--disable-streaming-transfers` will force duplicati to download remote files to a temp file before processing them. Monitoring network transfer speed should then give you an idea if the download routine itself is the bottleneck.
´--disable-piped-streaming´  and ´--set-aes-threadlevel=1´ will instruct Duplicati to not use multithreaded operation on file processing (last option only if your backup is aes encrypted).

**Comment by roterBulle** [comment]
Thanks for your proposals. 
--disable-streaming-transfers --> No difference in download speed
--disable-piped-streaming      --> less CPU usage but download speed still around 250 KByte
--set-aes-threadlevel=1          --> less CPU usage but download speed still around 250 KByte
All parameters together also don't increase the download speed.

I have now upgraded to 2.0.1.13_canary_2016-04-10 and restarted the process with 
--debug-output

Speed is still around 260 kByte :(

Is there a possibility, to see why duplicati is not downloading quicker.

**Comment by FootStark** [comment]
If the options did not change anything it indicates it's a problem with the backend handler. Can you specify what backend you are using and show the exact commandline (without logins/passwords)?
Furthermore, you can try running with the following options, which produces a logfile that might deliver more insights: `--log-level=Profiling --verbose --log-file=<pathtolog> --debug-output`

**Comment by roterBulle** [comment]
Command is the following :
mono "/volume2/@appstore/Duplicati/Duplicati.CommandLine.exe" backup "ssh://domain.de/duplicati_dir?auth-username=usr&auth-password=" pwd" "/volume2/dir1" "/volume2/dir2" --backup-name="Name" --dbpath="/root/.config/Duplicati/QELNPWALGX.sqlite" --encryption-module="aes" --compression-module="zip" --dblock-size="2gb" --keep-time="3M" --passphrase="xxxxXXXXXX" --tempdir="/volume2/tmp/" --no-auto-compact="true" --zip-compression-level="2" --threshold="90" --debug-output="True" --disable-module="console-password-input

Backend is a synology DS-215j with DSM6.0 7321 running mono 4.2.1.

**Comment by FootStark** [comment]
I found this: https://github.com/ShareX/ShareX/issues/136, which uses the same library with pretty much the same symptoms. So It seems to be the library. An update to a newer version for the backend might bring some mitigation as described there, but that would mean to update to a beta. The project looks to not be maintained anymore...

**Comment by roterBulle** [comment]
Hi FootStark,

thanks for your investigation, i found in the discussions that they have moved to github:
https://github.com/sshnet/SSH.NET

BUT they have no stable release as of now.

BUT the good news is that they are still working on that project, so hope is there that there will be a new stable release somewhen:
https://github.com/sshnet/SSH.NET/issues/1

Migrating the library when they release a stable release might be a future to-do.

**Comment by FootStark** [comment]
Didn't see that, but good to know. Please keep an eye on that and give notice on SSH.NET updates. if a stable release is available, we will update duplicatis backend.

**Comment by kenkendk** [comment]
SSH has some issues in its design that cause it to have a lower speed:
http://stackoverflow.com/questions/8849240/why-when-i-transfer-a-file-through-sftp-it-takes-longer-than-ftp

> The nature of SFTP and its ACK for every small data chunk it sends, makes an initial naive SFTP implementation suffer badly when sending data over high latency networks. If you have to wait a few hundred milliseconds for each 32KB of data then there will never be fast SFTP transfers. This sort of naive implementation is what libssh2 has offered up until and including libssh2 1.2.7.

There are fixes, but it requires an updated SSHD as well as an updated client.

But, 270kb/s sounds really slow. Can you try with CyberDuck or some other SSH tool (scp, putty, sftp, etc) and see what max speed you get?

**Comment by FootStark** [comment]
270Kb/s is realisitic if you have to wait for 9 IP roundtrips per second (32KB blocks).
There is a [BufferSize property for SftpClient](http://www.nudoq.org/#!/Packages/SSH.NET/Renci.SshNet/SftpClient/P/BufferSize) that can be set. Maybe if we expose it via an option that will already do the trick. It's a wild guess, but it won't hurt. Yet, I can't test it and don't know if it should be set before or after connecting...

**Comment by roterBulle** [comment]
SFTP from Midnight Commander brought me 2MB/s, so it shouldn't be related to normal SSH. 
:(

**Comment by renestach** [comment]
2.0.1.16 has an update to the built-in SSH library. Does it help?

**Comment by roterBulle** [comment]
Hi Rene,

i have tested the recovery on the weekend and it has now improved speed. I think now the CPU of my NAS is the limiting factor as it was running with 90% usage. 
This i would like to confirm the next days with running a recovery on my Workstation. 
But for now from my point of view the change looks good.

**Comment by renestach** [comment]
So, let's close this for now. If you think your first impression was wrong, please reopen this.

**Comment by irstmon** [comment]
Just dropping in: Started switching to SFTP from local Backend and I can't max out my bandwith. I have 200Mbit Up/Down at the target and 25/5 at the first site and 100/40 at the second site. Site 1 maxes out upload, Site 2 makes ~8Mbit upload. Downloading is "too slow" too: At site 1 I get about the same 8Mbit at download I'm seeing on site 2 as upload (so it looks like it's the cap) - using Winscp gets me the ~2,5MB/s site 1 is capable of, so the Target is not the bottleneck (since it's a Xeon Server I don't think it will hit the CPU Limit as fast as the NAS of roterBulle did probably).

**Comment by irstmon** [comment]
Any way to re-open this?
