### ISSUE TITLE
Update github Wiki with examples of all command-line options

### ISSUE THREAD

**Issue by utdrmac** [duplicati/duplicati#1697]
There is a seemingly endless number of options in duplicati. Most are not described in any online manuals or HOWTOs. Behavior/command-line arguments must be scoured from reading the source code or other people's issues and through trial-and-error.

It would be really nice if some documentation could be created with plenty of examples on how to properly use each backend service, gpg encryption, etc.

Surely your build process has automated testing of every option to ensure proper usage. Could you just dump all those commands out?
##

**Comment by kenkendk** [comment]
For general options you can use:
```
Duplicati.CommandLine.exe help options
```

For other options, they are listed under the module that supports them, e.g.:
`Duplicati.CommandLine.exe help zip` or `Duplicati.CommandLine.exe help ftp`.

For examples, we only have a limited set of examples:
```
Duplicati.CommandLine.exe help examples
```

If you wish to contribute examples, it is very easy. Simply edit this file, and send it back (pull request is prefered, but an attached file is also fine):
https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/help.txt

**Comment by warwickmm** [comment]
Closing this (rather old) issue.  Descriptions of the command line options can be obtained via the `help` command, or via the online [documentation](https://duplicati.readthedocs.io/en/latest/).
