### ISSUE TITLE
Error on repair database

### ISSUE THREAD

**Issue by jonniewhite** [duplicati/duplicati#1699]
Hi!

I'm using Duplicati 2.0.1.11- 2.0.1.11_experimental_2016-04-08 and having exported, deleted and then imported a configuration profile, I get the following error when repairing the database.

> System.Data.SQLite.SQLiteException (0x80004005): constraint failed UNIQUE constraint failed: BlocksetEntry.BlocksetID, BlocksetEntry.Index at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt) at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt) at System.Data.SQLite.SQLiteDataReader.NextResult() at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave) at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior) at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior) at Duplicati.Library.Main.Database.ExtensionMethods.ExecuteNonQuery(IDbCommand self, String cmd, Object[] values) at Duplicati.Library.Main.Database.LocalRecreateDatabase.FindMissingBlocklistHashes(Int64 hashsize, Int64 blocksize, IDbTransaction transaction) at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor) at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor) at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter) at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter) at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) at Duplicati.Library.Main.Controller.Repair(IFilter filter) at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

If I try running a backup I get the following error message:

> 2016-04-14 13:32: Terminated with error: The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.
> {"ClassName":"System.Exception","Message":"The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)\r\n   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)\r\n   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nRun\nDuplicati.Library.Main, Version=2.0.1.11, Culture=neutral, PublicKeyToken=8bfe994a39631a7b\nDuplicati.Library.Main.Operation.BackupHandler\nVoid Run(System.String[], Duplicati.Library.Utility.IFilter)","HResult":-2146233088,"Source":"Duplicati.Library.Main","WatsonBuckets":null}

I'm creating this issue as requested by Kenneth Skovhede in the post https://groups.google.com/d/msg/duplicati/w-0Rk3tIWvA/Hcxfi1Q_FQAJ

I've created a bug report (112MB). If anyone cares to look at this issue, I'll provide a download link.
##

**Comment by kenkendk** [comment]
I have made a new build that should fix the issue:
https://github.com/duplicati/duplicati/releases/tag/v2.0.1.43-2.0.1.43_canary_2017-01-19

**Comment by jonniewhite** [comment]
Thanks Kenneth.

**Comment by verybadsoldier** [comment]
Happened today too for me:
```
Duplicati: Duplicati.GUI.TrayIcon, Version=2.0.1.43, Culture=neutral, PublicKeyToken=null (Duplicati.Library.Main, Version=2.0.1.43, Culture=neutral, PublicKeyToken=null)
Autoupdate urls: https://updates.duplicati.com/canary/latest.manifest;https://alt.updates.duplicati.com/canary/latest.manifest
Update folder: C:\Users\vbs\AppData\Local\Duplicati\updates
Base install folder: C:\Program Files\Duplicati 2
Version name: "2.0.1.43_canary_2017-01-19" (2.0.1.43)
Current Version folder C:\Users\vbs\AppData\Local\Duplicati\updates\2.0.1.43
OS: Microsoft Windows NT 6.2.9200.0
Uname: 
64bit: True (True)
Machinename: BEN
Processors: 4
.Net Version: 4.0.30319.42000
Mono: False (0.0) ()
Locale: de-DE, de-DE, de-DE
Date/time strings: dddd, d. MMMM yyyy - HH:mm:ss
Tempdir: C:\Users\vbs\AppData\Local\Temp\
Environment variable: TEMP = C:\Users\vbs\AppData\Local\Temp
Environment variable: TMP = C:\Users\vbs\AppData\Local\Temp
SQLite: 3.8.5 - System.Data.SQLite.SQLiteConnection
SQLite assembly: C:\Users\vbs\AppData\Local\Duplicati\updates\2.0.1.43\SQLite\win64\System.Data.SQLite.dll
```

Also posted on the forums:
https://groups.google.com/forum/#!topic/duplicati/Hds3VocdESw

**Comment by kenkendk** [comment]
I am considering this fixed, and collecting performance related issues under #2302

**Comment by gernotpokorny** [comment]
I cannot make backups since I deleted my files only in the web-client of Dropbox. I did a repair. The message after the repair is "Found 1 files at the remote storage, but none that could be parsed". After that I'm unable to start my backup "The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.".

I'm perfectly fine that no files are found to repair. I just want to backup my files now. Is there any way to do that? Is this a bug?

**Comment by binarybum** [comment]
Any help?

This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.

[
{"Name":"duplicati-i0253121b4d7c47efa7979b42d9f652c3.dindex.zip.aes","LastAccess":"2018-04-08T22:10:46.4860571-04:00","LastModification":"2018-04-08T22:10:46.5016838-04:00","Size":706221,"IsFolder":false},
{"Name":"duplicati-i2e9af62438274846830c566491e0af14.dindex.zip.aes","LastAccess":"2018-04-08T22:42:09.4755255-04:00","LastModification":"2018-04-08T22:42:09.4755255-04:00","Size":707773,"IsFolder":false},
{"Name":"duplicati-i37463187b2a34faf93fa8cd0970d9864.dindex.zip.aes","LastAccess":"2018-04-08T22:29:40.4248412-04:00","LastModification":"2018-04-08T22:29:40.4248412-04:00","Size":703117,"IsFolder":false},
{"Name":"duplicati-i45f79db6eeff47ddb93756935284db9b.dindex.zip.aes","LastAccess":"2018-04-08T21:45:27.7072014-04:00","LastModification":"2018-04-08T21:45:27.7072014-04:00","Size":739597,"IsFolder":false},
{"Name":"duplicati-i4f5ce0e3e9d041ac85d1e64f42c06472.dindex.zip.aes","LastAccess":"2018-04-08T23:09:36.8949945-04:00","LastModification":"2018-04-08T23:09:36.8949945-04:00","Size":825133,"IsFolder":false},
{"Name":"duplicati-i5074d346aa57482d9159a75acb8b9a30.dindex.zip.aes","LastAccess":"2018-04-08T23:02:26.9474682-04:00","LastModification":"2018-04-08T23:02:26.9474682-04:00","Size":890189,"IsFolder":false},
{"Name":"duplicati-i524f5dfc172e4972b675c24b53a4d413.dindex.zip.aes","LastAccess":"2018-04-08T22:04:34.5413538-04:00","LastModification":"2018-04-08T22:04:34.5413538-04:00","Size":710925,"IsFolder":false},
{"Name":"duplicati-i655a1b0caa884d599871203826d9cb4a.dindex.zip.aes","LastAccess":"2018-04-08T22:35:54.650639-04:00","LastModification":"2018-04-08T22:35:54.650639-04:00","Size":711405,"IsFolder":false},
{"Name":"duplicati-i65c5a3f1ee2d4fc08b0cbfce7b576383.dindex.zip.aes","LastAccess":"2018-04-08T21:51:27.0163602-04:00","LastModification":"2018-04-08T21:51:27.0163602-04:00","Size":667053,"IsFolder":false},
{"Name":"duplicati-i72d46c66147845419ac32500463b2f61.dindex.zip.aes","LastAccess":"2018-04-08T21:39:06.0650174-04:00","LastModification":"2018-04-08T21:39:06.0670188-04:00","Size":1001565,"IsFolder":false},
{"Name":"duplicati-i9a7761ac2c774a9881556013c8b5f546.dindex.zip.aes","LastAccess":"2018-04-08T22:48:24.0180089-04:00","LastModification":"2018-04-08T22:48:24.0180089-04:00","Size":707613,"IsFolder":false},
{"Name":"duplicati-ib441629033c044a4b328de091d830d92.dindex.zip.aes","LastAccess":"2018-04-08T22:17:06.1725129-04:00","LastModification":"2018-04-08T22:17:06.1725129-04:00","Size":728445,"IsFolder":false},
{"Name":"duplicati-ic66d30f7fdb6461ba91716bd9e4ba72e.dindex.zip.aes","LastAccess":"2018-04-08T22:23:20.646191-04:00","LastModification":"2018-04-08T22:23:20.646191-04:00","Size":709693,"IsFolder":false},
{"Name":"duplicati-if4060fc1e3324572b690fcc71cda30a4.dindex.zip.aes","LastAccess":"2018-04-08T21:58:19.0526369-04:00","LastModification":"2018-04-08T21:58:19.0526369-04:00","Size":835133,"IsFolder":false},
{"Name":"duplicati-if85cc895f4914834993a69c05b088cca.dindex.zip.aes","LastAccess":"2018-04-08T22:54:38.7828387-04:00","LastModification":"2018-04-08T22:54:38.7828387-04:00","Size":709709,"IsFolder":false}
]
