### ISSUE TITLE
backup to a fileshare - Error: Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by justincm** [duplicati/duplicati#1701]
This had been running successfully for months

but now.

```
Error: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
   at Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
   at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
   at Duplicati.Library.Main.RSync.RSyncDir.InitiateMultiPassDiff(Boolean full, Options options)
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
Cleanup output:
```
##

**Comment by huste** [comment]
With 2.0.1.20 on Win10 64bit, this fails as well.

Running C:\Progs\duplicati\Duplicati.Library.Snapshots.exe gives me an error message:

```
Creating file C:\Progs\duplicati\testfile.bin
Attempting to read locked file C:\Progs\duplicati\testfile.bin
The file C:\Progs\duplicati\testfile.bin was correctly locked, message: Der Prozess kann nicht auf die Datei "C:\Progs\duplicati\testfile.bin" zugreifen, da sie von einem anderen Prozess verwendet wird.
Creating snapshot for folder: C:\Progs\duplicati
If this fails, try to run as Administrator
The snapshot tester failed: System.UnauthorizedAccessException: Es wurde versucht, einen nicht autorisierten Vorgang auszufhren.
   bei Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
   bei Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
   bei Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   bei Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
   bei Duplicati.Library.Snapshots.Program.Main(String[] _args)
* Test failed
```
testfile.bin  has a timestamp from right now.

The volume shadow service is set to automatic and running. It was set to manual and I tried starting it as I read the comment by mbrum he posted for the issue #1905  Still, this does not resolve the issue.
My Windows user hast administrative rights.

**Comment by huste** [comment]
Running the .exe "as administrator" via Explorer works. Question how do I do this, when I want duplicati started at system startup in Windows 10?
I do have a batchfile right now that launches several tools. But I can't have it run as administrator without entering a password.

**Comment by agrajaghh** [comment]
@huste so I guess this is fixed for you.
regarding autostart: you can create a service with NSSM to start duplicati with admin rights (installer which will create the service is on the roadmap)

@justincm is it working for you with 2.0.1.20?

**Comment by huste** [comment]
I guess so, although it's not a satisfying solution. Anyway I'll head back to the no-snapshot policy. As the snapshots are made by ma Acronis True Image anyway :)

**Comment by kenkendk** [comment]
@huste: Agree, possible solutions and drawbacks are discussed in #1768 and #1738
