### ISSUE TITLE
Large Duplicati-server.sqlite file, can I delete old logs?

### ISSUE THREAD

**Issue by TonySturch** [duplicati/duplicati#1707]
I have an extremely large Duplicati-server.sqlite file, on the order of 11.5 GB and growing.  It takes an extremely long time to access the stored log data.  Is it possible to delete older logs to trim this file down?  Thanks.
##

**Comment by agrajaghh** [comment]
how big is your backup and how many files?

**Comment by GuitsBoy** [comment]
Pretty big.  I have 30 or so individual backups, about 300K images, 200K mp3s, and give of take 500 video files totaling 2.5 TB.

**Comment by kenkendk** [comment]
The log data should be removed every 30 days. Do you have any idea why there is so much data in the log file?

**Comment by TonySturch** [comment]
I had debugging on for an old backup that has now been broken into multiple smaller backups.    I was running into the "unexpected number of deleted filesets" issue, and decided it would be better to break the backup into smaller pieces.  My guess is there is still data from that old backup.  Hopefully it will be reduced in a month or so.  Thanks for the response.

**Comment by NickPyz** [comment]
I also have a question about log data retention. Version 2.0.1.16_canary. 

In the Default options settings, I set the log-retention variable = 15 days. However, the UI shows log items as old as 27 days. 

Bug, or am I misunderstanding the log-retention function? Thanks.

**Comment by kenkendk** [comment]
Sounds like a bug. I think it only cleans on exit IIRC.

**Comment by GuitsBoy** [comment]
My duplicati-server.sqlite file has reduced from nearly 12GB down to just over 5GB after removing the verbose logging options and waiting a couple of weeks, so I guess mine is working as it should.

**Comment by warwickmm** [comment]
This is related to issue #1298, and I think is no longer a problem.  If you're still experiencing this issue, please feel free to reopen.
