### ISSUE TITLE
Disk full error for Duplicati 2.0 with a local USB backup destination

### ISSUE THREAD

**Issue by Chrescht** [duplicati/duplicati#1711]
After setting up my first (USB drive) backup, Duplicati didn't give any errors but nothing happened except a lot of CPU was used for two processes of `Duplicati.GUI.TrayIcon.exe`.
After I stopped the backup, there was the following message:

`Disk full. Path /tmp/dup-e81ec681-2edb-4b4f-9d30-1a98c1513e8a`

The backup size is over 200GB.
My /tmp is 4GB, shouldn't that be sufficient?
#1710
##

**Comment by warwickmm** [comment]
The amount of tmp needed depends on several options, including volume size, number of concurrent workers, etc.  Several improvements have been made to better clean up temp files after they have been used.  If this is still an issue, feel free to reopen.
