### ISSUE TITLE
April 10 Canary release Duplicati.Tray.icon.exe positive on many virus checkers

### ISSUE THREAD

**Issue by chris-cashin** [duplicati/duplicati#1714]
My Mcafee enterprise flagged this file as a TROJAN. The below scanners also show positive

Antivirus	Result	Update
AegisLab	Troj.W32.Generic!c	20160420
Antiy-AVL	Trojan[:HEUR]/Win32.AGeneric	20160420
Avast	Win32:Malware-gen	20160420
Avira (no cloud)	TR/Dldr.Agent.jvmr	20160420
GData	Win32.Trojan.Agent.CJZKLF	20160420
Ikarus	Trojan-Downloader.Agent	20160420
Jiangmin	fhg	20160420
Kaspersky	HEUR:Trojan.Win32.Generic	20160420
McAfee	Artemis!E05AA14A2411	20160420
McAfee-GW-Edition	Artemis	20160420
Qihoo-360	Win32/Trojan.97a	20160420
Rising	PE:Malware.Generic/QRS!1.9E2D [F]	20160420
Symantec	Trojan.Gen	20160420
Tencent	Win32.Trojan.Generic.Aheg	20160420

**Comment by agrajaghh** [comment]
damn snakeoil, just tried t find you which file is causing the false positives at virustotal.com

**win-tools/iconv.dll** 1/57:
AegisLab 	Troj.Atraps.Gen2!c 	20160420 

**Duplicati.Server.exe** 1/57:3
Rising 	PE:Malware.Generic/QRS!1.9E2D [F] 	20160420

**Duplicati.GUI.TrayIcon.exe** 14/57:
AegisLab 	Troj.W32.Generic!c 	20160420
Antiy-AVL 	Trojan[:HEUR]/Win32.AGeneric 	20160420
Avast 	Win32:Malware-gen 	20160420
Avira (no cloud) 	TR/Dldr.Agent.jvmr 	20160420
GData 	Win32.Trojan.Agent.CJZKLF 	20160420
Ikarus 	Trojan-Downloader.Agent 	20160420
Jiangmin 	Trojan.Generic.vpky 	20160420
Kaspersky 	HEUR:Trojan.Win32.Generic 	20160420
McAfee 	Artemis!E05AA14A2411 	20160420
McAfee-GW-Edition 	Artemis 	20160420
Qihoo-360 	Win32/Trojan.97a 	20160420
Rising 	PE:Malware.Generic/QRS!1.9E2D [F] 	20160420
Symantec 	Trojan.Gen 	20160420
Tencent 	Win32.Trojan.Generic.Aheg 	20160420

**Comment by kenkendk** [comment]
The metadata changes for each build, so it is strange that this picked up.
Strangely there is almost no code in the TrayIcon executable, but it references a bunch of GUI stuff.
Hopefully this will die out a bit when we have an installer instead.

**Comment by renestach** [comment]
It seems that many anto-virus checkers are going bananas at the moment. I also have false alarms with other pieces of software. :-(

I do not know if it worth to report this to the AV companies because our software changes weekly.

**Comment by chris-cashin** [comment]
the Issue went away for me with the April 21 release.
Thanks

**Comment by kenkendk** [comment]
I think this was caused by the executable not having an icon. Due to a bug in the xbuild tool, the executables were built without a trayicon, an I would guess that some malware ships without an icon :).

The iconv.dll is used by GPG to support unicode and is quite common, so I have no idea why that is flagged.

**Comment by agrajaghh** [comment]
just checked 2.0.1.14 with virustotal: 1/55

just one AV is going crazy:
DrWeb 	Program.Unwanted.1110
