### ISSUE TITLE
Can only select root dir for restore in new ngax GUI/skin

### ISSUE THREAD

**Issue by Shellfishgene** [duplicati/duplicati#1716]
If I unfold the directories in the restore window I can only select the root checkbox, all directories get the check as expected.
However clicking a sub directory or file does not do anything. Doing the same thing in the greeno skin with the same backup works fine.

Also, in ngax the root directory does not have the backup name as in greeno, but this is just cosmetic...

This is in 2.0.1.11_experimental_2016-04-08, using Chrome.

**Comment by kenkendk** [comment]
This is the same as #1672 and has been fixed in source.
