### ISSUE TITLE
Restore to "Original Location" fails

### ISSUE THREAD

**Issue by ohthetrees** [duplicati/duplicati#1718]
I'm using Duplicati 2.0.1.13- 2.0.1.13_canary_2016-04-10

Restoring to the "Original Location" reports success via the GUI, but no files are in fact restored. If I "Pick Location" and then browse to that same original location, restore works as expected.

**Comment by bensoibj** [comment]
Already reported in #1624 "can't restore to original location".

**Comment by agrajaghh** [comment]
closing as duplicate
