### ISSUE TITLE
2.0.1.11 reports "Backup: 0 bytes" on fine backups

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1723]
I am seeing 0 bytes reported as backup size  in the overview
![1](https://cloud.githubusercontent.com/assets/9739281/14763420/69f7cf5c-0995-11e6-8175-c16e47b2179d.png)

This is with a "local path" destination which points to a hidden SMB-Share on my Synology:
\\SYNOLOGY\BACKUP\stefan\

I tried mounting the share as Z: and using that one, ran a backup, repaired the local database. Still, duplicati showed "0 bytes".

Side Information: The reason I don't use SSH is simply that I can't change to /volume2/backup/.... via SCP. I don't know why, but Synology fails to do so with pcsp. I can cd to that location perfectly when logging in via SSH. But that's a different story.

Cheers
Stefan

**Comment by kenkendk** [comment]
The "0" bytes is reported when the backend does not report back how large the files are.
I have not had issues with SMB mounts not reporting size before, but maybe that helps you.

**Comment by huste** [comment]
Not really. I wouldn't know why there should be no result. As I can see size information in Windows Explorer, I wonder what really happens here.

**Comment by huste** [comment]
At work, I also use Duplicati (latest build 2.0.1.11) and even local file backups report "0 bytes". The destination is shown as "file://D:\backup\VirtualBoxLokal"
D: is a local drive, not a network share.

**Comment by kenkendk** [comment]
Could you make a "bugreport" from the UI and send it to me?

Then I will see if there are hints in the database as to why it does not report the size.

**Comment by huste** [comment]
I sent you a message to your main mail address. Interesting enough: I returned to work and found this:
On my Windows 10 host machine, I have 5 backups, all report 0 bytes. 1 of which is a local drive letter, 4 are mapped network shares with drive letters.
On my Windows 10 virtual machine, I have 1 backup to a mapped network share which reports the backup size properly.

**Comment by lokety** [comment]
Is this also a limitation of this feature for AWS Glacier storage? I have 0 bytes for all of my backups to AWS.

**Comment by kenkendk** [comment]
I had a look at the database from @huste , and the problem is not with the backend. I can see that it correctly reports the size of files, so the information is lost somewhere else.

**Comment by huste** [comment]
The greeno-UI also reports 0 bytes, BTW. Is there anything I can do?

**Comment by huste** [comment]
FYI: Still an issue in 2.0.1.19 canary. I have one machine which lists all backup sizes as 0 and one machine which lists all source data as 0 bytes. Both are local drives (mapped network drives as backup targets, one even a local drive; local drives as backup sources)

**Comment by huste** [comment]
Update: Having the "no-backend-verification" option set produces the 0 byte display. Is this a bug or a feature? See my comments to #1905

**Comment by kenkendk** [comment]
@huste : Thanks for finding this! I have been looking everywhere to find the problem!

**Comment by huste** [comment]
You're welcome.
Now it's still about the asynchronous upload folder :)

BTW: It would be nice to have a "finished" log file entry when a backup job actually finishes.
