### ISSUE TITLE
Show duration and/or speed

### ISSUE THREAD

**Issue by EleRas** [duplicati/duplicati#1725]
A feature request:
Show the duration how long a backup/restore took and the average upload speed (or for restores of the download). Currently it is only possible to see this in About -> System info -> lastPgEvent, but this is impractical since it is only temporary and disappears after a few seconds.
##

**Comment by kenkendk** [comment]
Should this be reported permanently in the same place as "backup size" or more like a "lingering popup" that disappears after a while?

**Comment by EleRas** [comment]
I'd liked to see it similar to backup - size, since a popup may be missed

**Comment by agrajaghh** [comment]
duration is implemented in 2.0.1.17. Should this be closed or do you want to add avg. speed as well?

**Comment by EleRas** [comment]
Speed would be nice, but this already looks quite sufficient and helps a lot, thanks!

**Comment by saviodsouza** [comment]
It should show average upload/download speed contiously & pending waiting to upload block files, size. (at "waiting for upload" status)

I frequently open the system manager to see the upload speeds.

**Comment by autumnwalker** [comment]
It would be nice to see in progress data - current speed, ETA, etc.

**Comment by autumnwalker** [comment]
duplicate / related? #1402

**Comment by agrajaghh** [comment]
yes, thanks @autumnwalker
