### ISSUE TITLE
Rewrite the throttle code

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#1729]
The throttle code is overly complicated and uses too many resources.

It should be rewritten to use a simple exponential weighted moving average.
##

**Comment by jerrac** [comment]
What's the difficulty level of this issue? 

How well do you need to know the Duplicati codebase? How skilled in C# do you need to be?

**Comment by kenkendk** [comment]
This should have been fixed with 0190a9994e55c0e4c6b7c7eaac43ec25dd811fc5.
It does not require any knowledge of Duplicati, but you need to understand how streams work in .Net (and C#).
Looking at the two referenced issues, it is possible that there is another error somewhere that breaks the throttle stuff.
