### ISSUE TITLE
first backup fails with filename not allowed

### ISSUE THREAD

**Issue by Bowhunter62** [duplicati/duplicati#1734]
this issue reproducible !
thanks in advanced

env:
Source : Windows 10 
Dest. : Speedport with ftp connection

BackupType      : Full
TypeReason      : Ein vollständiges Backup wird durchgeführt, da keine Backup-Ketten im Backup-Ziel gefunden wurden
BeginTime       : 04/27/2016 20:37:41
EndTime         : 04/28/2016 00:29:42
Duration        : 03:52:00.5326095
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 0
AddedFiles      : 7676
AddedFolders    : 792
ExaminedFiles   : 7676
OpenedFiles     : 7676
SizeOfModified  : 0
SizeOfAdded     : 60554724463
SizeOfExamined  : 60554724463
Unprocessed     : 25532
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 61811427641
BytesDownloaded : 0
RemoteCalls     : 16397
NumberOfErrors  : 1
****************
Misserfolg nach dem Hochladen von 5460 Volumes. Fehlermeldung: Fehler Der Remoteserver hat einen Fehler zurückgegeben: (553) Dateiname nicht zulässig. beim Hochladen der Datei "duplicati-full-signature.20160427T183741Z.vol5461.zip.aes"
****************
NumberOfRetries : 15
RetryOperations : 15

Ergebnis des Aufräumens:

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
