### ISSUE TITLE
Log filled with "System.ArgumentException: invalid user id"

### ISSUE THREAD

**Issue by EleRas** [duplicati/duplicati#1737]
Due to various reasons, on my system I have many files, which do not belong to a valid user on that system, so the assigned userid is invalid.
Duplicati doesn't seem to like this and spams the errorlog with this:

> Failed to process metadata for "<REMOVED>", storing empty metadata
> System.ArgumentException: invalid user id
> Parameter name: user
>   at Mono.Unix.UnixUserInfo..ctor (UInt32 user) [0x00000] in <filename unknown>:0 
>   at Mono.Unix.UnixFileSystemInfo.get_OwnerUser () [0x00000] in <filename unknown>:0 
>   at UnixSupport.File+FileInfo..ctor (Mono.Unix.UnixFileSystemInfo fse) [0x00000] in <filename unknown>:0 
>   at UnixSupport.File.GetUserGroupAndPermissions (System.String path) [0x00000] in <filename unknown>:0 
>   at Duplicati.Library.Snapshots.SystemIOLinux.GetMetadata (System.String file) [0x00000] in <filename unknown>:0 
>   at Duplicati.Library.Snapshots.NoSnapshotLinux.GetMetadata (System.String file) [0x00000] in <filename unknown>:0 
>   at Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata (ISnapshotService snapshot, System.String path, FileAttributes attributes) [0x00000] in <filename unknown>:0 

Additionally, in the logfile I only see the text "Message" without details and have to click on each text to see if it is the same error, making this useless, since I can't find real problems. I attached a screenshot showing the problem.

I see two ways how this situation could be improved:
- Display the title of the message directly
- Silence these exceptions

Version: 2.0.1.15_canary_2016-04-27 on Linux (both ubuntu and synology)
![screenshot_20160429_105019](https://cloud.githubusercontent.com/assets/820659/14911830/3ffdc65e-0df8-11e6-8401-b85e8e7237ab.png)
##

**Comment by neersighted** [comment]
I am also having this issue, which is causing massive growth of the sqlite database (over half a million files)...

**Comment by justinasjaronis** [comment]
+1. With these messages it's just impossible to use Duplicati in docker deployment, because user id's will vary a lot.

**Comment by mprasil** [comment]
It would be nice if there was an option to just backup user ID, rather than the user name which would avoid this issue. 

@justinasjaronis - as a workaround for Docker container if the UID/GID mapping on the host itself is fine, you can mount bind (`--volume`)read-only `/etc/passwd` and `/etc/group` inside the container. Depending how you run Duplicati inside, that should work. Definitely not something I'd like to do, but ~~resolves~~ avoids the issue. (Alternatively if there's only few users missing, you can add them with proper uid/gid build time or run time - again not perfect, but gets stuff done with minimal effort)

**Comment by ts678** [comment]
> It would be nice if there was an option to just backup user ID, rather than the user name which would avoid this issue.

Please look at code below. It looks like it tests for a user or group that can't be reversed into a name, but it needs testing.

[Fix exceptions when users and groups are not defined on the local system (such as when a system is bound to Active Directory or a user or group has been deleted). #2056](https://github.com/duplicati/duplicati/pull/2056) in [2.0.1.29_canary_2016-10-27](https://github.com/duplicati/duplicati/releases/tag/v2.0.1.29-2.0.1.29_canary_2016-10-27) might have fixed this. Is anyone still seeing the messages?
