### ISSUE TITLE
SFTP fails to connect "Connection was aborted"

### ISSUE THREAD

**Issue by dudheit** [duplicati/duplicati#1746]
I am using Duplicati Canary and trying to connect to an SFTP (SSH) server. The server is running Ubuntu 16.04 with openssh. The ssh/sftp command is working normal on other systems but Duplicati yields ``Failed to connect: An established connection was aborted by the software in your host machine.``. The server error log gives the following error:

    $ grep 'sshd' /var/log/auth.log
    sshd[1789]: fatal: mm_answer_moduli: bad parameters: 2048 2048 1024

I tested a connection to a different Ubuntu 14.04 server, which worked well, so I am not quite sure whether this is really an Duplicati issue. However, SFTP connection with other clients seem to work without problem.

**Comment by kenkendk** [comment]
Is this the same as #1687 ?
I have fixed it in the latest canary (released just before you created this issue).

Is it fixed in the latest canary, or is it a new issue with the latest canary?

**Comment by dudheit** [comment]
Yes, that fixed the issue! Thanks a lot, great work here!
