### ISSUE TITLE
Back-up via ftp doesn't finnish

### ISSUE THREAD

**Issue by marianpavel** [duplicati/duplicati#1748]
Question: I am receiving this error when trying to back-up via FTP:

The remote server returned an error: (450) File unavailable (e.g., file busy).

I need some guide to know where to look, I couldn't find the error where is located in the code, I took a look over the Backend.FTP but everything look ok. Duplicati tries to make something when it finishes because the archive is uploaded on FTP.

On remote log data I have this:

2016-05-05 09:14: put duplicati-b680f53ae531149ccb0a8677635eb33eb.dblock.zip
2016-05-05 09:14: list
##

**Comment by marianpavel** [comment]
Ok, doing some debugging I found where the system error is:
In BackendManager.cs on the WaitForComplete() method that is called in FilelistProcessor.cs

After calling this:                 DoneEvent.WaitOne();

I get all of these in log:

Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Utility.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Utility.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
The thread 0x3d0 has exited with code 0 (0x0).
The thread 0x25c8 has exited with code 0 (0x0).
The thread 0x1d64 has exited with code 0 (0x0).
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Utility.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Utility.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
The thread 0x1068 has exited with code 0 (0x0).
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Utility.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
Exception thrown: 'System.Net.WebException' in Duplicati.Library.Backend.FTP.dll
The thread 0x4c4 has exited with code 0 (0x0).

**Comment by ts678** [comment]
Is this 2016 problem still of interest and happening on later release?
It's not reproducible by me with a simple backup. Any specific steps?
