### ISSUE TITLE
Duplicate file entries detected - right after full backup

### ISSUE THREAD

**Issue by Simpelton** [duplicati/duplicati#1751]
For some time I have the issue that I this error (v2.0.1.11, Windows8.1):
`
Fatal error
System.IO.InvalidDataException: Duplicate file entries detected, run repair to fix it ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Duplicati.Library.Main.Database.LocalBackupDatabase.BuildLookupTable(Options options)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Main.Database.LocalBackupDatabase.BuildLookupTable(Options options)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
`

I can't seem to get rid of the error. I did delete the local DB, removed the backup files (NAS over LAN) and ran the backup again (config stayed the same). Backup seemed to work ok:

`DeletedFiles: 0 DeletedFolders: 0 ModifiedFiles: 0 ExaminedFiles: 161634 OpenedFiles: 161634 AddedFiles: 161634 SizeOfModifiedFiles: 0 SizeOfAddedFiles: 546135070005 SizeOfExaminedFiles: 546135070005 SizeOfOpenedFiles: 546135070005 NotProcessedFiles: 0 AddedFolders: 15986 TooLargeFiles: 0 FilesWithError: 0 ModifiedFolders: 0 ModifiedSymlinks: 0 AddedSymlinks: 0 DeletedSymlinks: 0 PartialBackup: False Dryrun: False VerboseOutput: False VerboseErrors: False Messages: [No remote filesets were deleted] Warnings: [] Errors: []`

Log shows the error above popping up three minutes after the result log entry.

Advanced options I use
`
--snapshot-policy=auto
--usn-policy=auto
--auto-cleanup=true
--disable-filepath-cache=false
--number-of-retries=10
--run-script-before=C:\Program Files (x86)\Duplicati-2\CustomScripts\WakeNAS.bat
`

Running a repair does not help. RemoveDB and recreate DB also does not help.

Any ideas?
##

**Comment by Simpelton** [comment]
Error goes away by removing this parameter:
--disable-filepath-cache=false

I doublechecked, put it back in, error returns. Take it out, error goes away.

**Comment by warwickmm** [comment]
The `disable-filepath-cache` option is no longer used and has been deprecated.  If this is still an issue, feel free to reopen with more details.
