### ISSUE TITLE
The supplied option --quiet-console is not supported and will be ignored

### ISSUE THREAD

**Issue by steilerDev** [duplicati/duplicati#1752]
Hi Kenneth,

this is only a minor issue, but the documented option "quiet-console", which should suppress all output to the console and relay it to the log file is not working. When starting duplicati with the option `--quiet-console="true"`, the log file states: `Warning: The supplied option --quiet-console is not supported and will be ignored`

Thanks!
##

**Comment by ts678** [comment]
Not reproducible on Windows with either 2.0.5.111 Canary or 2.0.2.1 Beta using Duplicati.CommandLine.exe backup test.
Original report does not say what was being used, or how it was used, but I don't see any similar Issues or forum reports.
[Display Duplicati 2.0.2.1 beta command line help](https://forum.duplicati.com/t/display-duplicati-2-0-2-1-beta-command-line-help/1166/2?u=ts678) does show it under Duplicati.CommandLine.exe

**Comment by warwickmm** [comment]
I don't see any indication that `quiet-console` is being ignored or deprecated.  If this is still occurring, please reopen with more details on how you are providing the option during startup.
