### ISSUE TITLE
404 when trying to backup to Google Drive

### ISSUE THREAD

**Issue by jaredcaputo** [duplicati/duplicati#1753]
Hi, I get the following error when I try to backup to Google Drive: 

`Failed to retrieve file listing: Execution of authentication request returned unexpected result: 404`
From the log file:

```
Information: The operation Backup has started
Error: An error occurred while running the backup, no files were uploaded: Failed to retrieve file listing: Execution of authentication request returned unexpected result: 404
```

I'd appreciate any help in fixing this! Thanks!

Note, this is after Duplicati told me to use `--accept-specified-ssl-hash=xxxxxx`

**Comment by kenkendk** [comment]
We are not maintaining version 1.3.x anymore.
