### ISSUE TITLE
Restore does not work: Access to the path 'null' is denied

### ISSUE THREAD

**Issue by Zero3** [duplicati/duplicati#1759]
I tries restoring a file from a fresh backup from yesterday, but got this troubling message instead:

![image](https://cloud.githubusercontent.com/assets/82504/15127384/bca2aa94-1636-11e6-895e-0829db77c0b9.png)

Nothing happens when I click "Show", and nothing is logged in the General or Remote log.
##

**Comment by kenkendk** [comment]
I think this is issue #1624 ?

**Comment by Jaerock** [comment]
I am experiencing the same issue. It looks like #1624, but this is happening on v2.0.1.17_canary. It only fails when selecting 'original location', manually entering the original location (or another location) works fine. Also nothing to find in the logs here.

**Comment by ts678** [comment]
Not reproducible (but a lot of time has passed).

> I tries restoring a file from a fresh backup from yesterday, but got this troubling message

Works for me.

> It only fails when selecting 'original location'

Works for me.

I'm deleting `needs testing` label, and adding `pending user feedback` to see if this is relevant and happens on a later release.

**Comment by Zero3** [comment]
I am the original bug reporter. However, I gave up on Duplicati many years ago because of issues like this bug, so I am afraid that I will not be able to provide any feedback on whether this issue still exists in later releases. It seems like I was not the only one though, based on the comments above, so perhaps others can assist.
