### ISSUE TITLE
Backup of large files completely broken

### ISSUE THREAD

**Issue by buengese** [duplicati/duplicati#1763]
In my testing duplicati is unable to restore large files. The restore runs forever but no errors or warnings appear in the log. During the restore there is also almost no I/O activity by Duplicati.

Version: 2.0.1.16 canary

**Comment by agrajaghh** [comment]
how big is the file? how big is the full backup? how many files? what machine are you running duplicati on?

**Comment by kuroshi099** [comment]
I, too, am experiencing an issue with backing up large files. Only in my case, I see a total failure upon attempting to even create the backup. The file in question is 800MB.

**Comment by agrajaghh** [comment]
@kuroshi099 what failure? what is the error message? what version are you running? what are your settings?

**Comment by kuroshi099** [comment]
My command line setting is:

    mono "/Applications/Duplicati.app/Contents/Resources/Duplicati.CommandLine.exe" backup "s3://kode54-imac-home/?s3-server-name=s3.amazonaws.com&s3-location-constraint=us-west-1&s3-storage-class=&auth-username=<redacted>&auth-password=<redacted>&use-ssl=true" "/Users/Chris" --backup-name="My Home Directory" --dbpath="/Users/Chris/.config/Duplicati/LFIILTNHUM.sqlite" --encryption-module="aes" --compression-module="zip" --dblock-size="50mb" --keep-time="3M" --passphrase="<redacted>" --throttle-upload="250" --disable-module="console-password-input"

The error message is:

    System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
      at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) <0x113106860 + 0x025b2> in <filename unknown>:0 
      at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend) <0x113105e50 + 0x006fd> in <filename unknown>:0 
      at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) <0x11189c630 + 0x0106e> in <filename unknown>:0 

But then I realized this was just a firewall error, as reinstalling the software and allowing it through the firewall permanently and immediately made it continue to run without error. So disregard, sorry.

**Comment by agrajaghh** [comment]
closing since @kuroshi099 issue is solved and @buengese doesnt respond

**Comment by kode54** [comment]
Please re-open, as the issue is occurring for me again. (@kuroshi099 was a temporary account)

I have the following command line:

The following error pops up on screen when attempting to back up a large file:

    Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.

And the logged message is:

    System.ObjectDisposedException: Cannot access a disposed object.
    Object name: 'System.Net.Sockets.NetworkStream'.
      at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) <0x40ab5650 + 0x0236f> in <filename unknown>:0 
      at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend) <0x40ab4d10 + 0x0064b> in <filename unknown>:0 
      at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) <0x409f88e0 + 0x00eb7> in <filename unknown>:0 

With the following messages in the general log:
    removing file listed as Temporary: duplicati-20161012T014054Z.dlist.zip.aes
    scheduling missing file for deletion, currently listed as Uploading: duplicati-b3fcbedab494b497f83847fd0fb4772df.dblock.zip.aes
    scheduling missing file for deletion, currently listed as Uploading: duplicati-i342b91329e1744e3b0f43994e0be8a46.dindex.zip.aes
    scheduling missing file for deletion, currently listed as Uploading: duplicati-bf0a20ca2c21540669b377847fc47390a.dblock.zip.aes
    scheduling missing file for deletion, currently listed as Uploading: duplicati-i8ee202f426b74ac4832567e2bdbaa39f.dindex.zip.aes
    removing file listed as Deleting: duplicati-b10220c38df4241b3871af70f8c832cfa.dblock.zip.aes
    scheduling missing file for deletion, currently listed as Uploading: duplicati-b99bc9bdac6e34fb4ba694e24a091f3c7.dblock.zip.aes
    scheduling missing file for deletion, currently listed as Uploading: duplicati-i4eb37afaf6574fb9b1fd0dafff78d92b.dindex.zip.aes
    removing file listed as Deleting: duplicati-b9a862ed833dd4ec695746564d06085fa.dblock.zip.aes

And in remote:
    Oct 11, 2016 6:49 PM: list
    [
    
    ]
    Oct 11, 2016 6:50 PM: put duplicati-b13f7bdc850eb485c8f09a8d360d19f6e.dblock.zip.aes
    {"Size":52399389,"Hash":"xueLMWHQez+APr/VYVwBXxk8MksCQZaEyUBdR+bBmSQ="}
    Oct 11, 2016 6:50 PM: put duplicati-bd1933945bb22458591c4a7b58866330b.dblock.zip.aes
    {"Size":52399389,"Hash":"xueLMWHQez+APr/VYVwBXxk8MksCQZaEyUBdR+bBmSQ="}

If it serves any purpose, I find that when I use signature v4 with s3cmd, it has to upload files twice, or even repeatedly, while v2 works fine.

**Comment by kode54** [comment]
Adding that now that I've since updated the container to an image based on 2.0.1.26_canary_2016-09-29, which for some reason is the latest that the container is based on, it seems to also be observing my signature version 2 override, and is managing to upload the backup blocks to my S3 bucket.

I'll post further news if it manages to fail again.
