### ISSUE TITLE
 non standard s3 connections

### ISSUE THREAD

**Issue by MourIdri** [duplicati/duplicati#1767]
Hi, 

My object store solution is listening on a specific port : https://my.s3.objectstore.corp:8082
Plus, I need to have the possibility to check path style. 
Is that panned to integrate it in future release ?

**Comment by kenkendk** [comment]
What do you need for the "path style" option?
Is it that you need to use a dns-name for the bucket, like `https://bucket.server.com` ?

**Comment by MourIdri** [comment]
Hi KenKendk, 

thanks for your reply. 
for the path style, I meant something like this ( it is an example for a file ) : 
https://myS3endpointdomainname.domain.com:8082/bucket/folder/winapp2.ini is that possible to add this ? 
Plus the possibility to add a port ( in my case 8082 ).


May 15 20:03:58 debianfuse s3fs[10994]:       URL changed is https://lab-g1.demofr.netapp.fr:8082/sambas3/Ccleaner/winapp2.ini

**Comment by MourIdri** [comment]
Hi KenKendk,

thanks for your reply.
for the path style, I meant something like this ( it is an example for a file ) :
https://myS3endpointdomainname.domain.com:8082/bucket/folder/winapp2.ini is that possible to add this ?
Plus the possibility to add a port ( in my case 8082 ).

Thank you.

**Comment by kenkendk** [comment]
I would think all of it is fairly standard, except the port.
But you should be able to just set the server, incl. the port:
`--s3-server-name="mys3endpointdomainname.domain.com:8082"

In the UI, set the "custom server" option, and then paste `mys3endpointdomainname.domain.com:8082`

**Comment by kenkendk** [comment]
Closing due to missing activity
