### ISSUE TITLE
Feature: Documentation of local database

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#1769]
Hi, is there some documentation of database structure? How all this things relate togethers? Like files, blocks, blocksets, hashes, filesets etc? How local database documenting state of remote volumes. I think I can  repair many problem my self, but Im failing to understand basic high level picture :)

Thanks

**Comment by ulicky** [comment]
Trying to reconstruct DB entity relations. Why there are no foreing keys to maintain integrity?

**Comment by ulicky** [comment]
I tried to visualize schema, Is it correct?

![schema](https://cloud.githubusercontent.com/assets/2264442/15273409/40f5ada8-1a99-11e6-8c61-441c0efa986a.png)

**Comment by kenkendk** [comment]
The schema looks correct.

There are no foreign keys because I am not a db-pro and I did not need FKs to get it to work :)

Cascading deletes are manually implemented.

**Comment by kenkendk** [comment]
@mnaiman Would you be willing to put this into a Wiki page?

**Comment by mnaiman** [comment]
Of course, I had better one - found one more relation.
![schema](https://cloud.githubusercontent.com/assets/2264442/17464239/ace31662-5cda-11e6-8f90-2bb5f3e36610.png)

**Comment by btriffles** [comment]
@mnaiman That looks really nice!

@kenkendk Duplicati has no foreign key constraints right now?  This seems like something that would be relatively easy to add, and it could help prevent inconsistent/incorrect databases.  I don't have any experience with SQLite, but it might be as easy as adding a few keywords to your database definitions [FOREIGN KEY(X) REFERENCES Y(Z)] and making sure related database changes happen in one transaction.

**Comment by kenkendk** [comment]
@mnaiman: I started the Wiki page here:
https://github.com/duplicati/duplicati/wiki/Local-database-format

@btriffles: All operations are done in transactions. The foreign keys can provide some performance speedups and help with cascading deletes, but we already use local indices and handle the cascading deletes manually.

**Comment by mnaiman** [comment]
Nice, thanks.
