### ISSUE TITLE
 High Bug: Recovery dont respect target path

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#1770]
Hi,
during my experiments, I found, that under specific circumstances Duplicati.CommandLine.RecoveryTool.exe dont respect "targetpath" option, which lead to fact, that my source files were overwritten by old version from backup.

Command was
Duplicati.CommandLine.RecoveryTool.exe" restore "E:\Daily_Repair\\" 470 --targetpath="E:\Daily_Repair_Restore\\"

Command itself is not problem, but in backuped files are files from multiple harddrives like:
C:\Data1\DB\aaa.cbu
D:\Data2\DB\bbb.cbu

When all files are from same drive letter problem did not occured.
When debugged, I found problem  here https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/RecoveryTool/Restore.cs: (detail code block at the end)

when comparing Library.Utility.Utility.ClientFilenameStringComparer.Equals(parts[ni], largestprefixparts[ni] and drive letters are different ni is set to 0 and largestprefix = string.Empty;

when largestprefix = string.Empty than it is not used in combining with targetpath and restore is done to source files, which could led to file overwrite like my case

when restoring all files from GUI to target folder it is working ok

```
foreach(var f in List.EnumerateFilesInDList(filelist, filter, options))
                {
                    if (largestprefix == null)
                    {
                        largestprefix = f.Path;
                        largestprefixparts = largestprefix.Split(new char[] { Path.DirectorySeparatorChar });
                    }
                    else if (largestprefix.Length > 1)
                    {
                        var parts = f.Path.Split(new char[] { Path.DirectorySeparatorChar });

                        var ni = 0;
                        for(; ni < Math.Min(parts.Length, largestprefixparts.Length); ni++)
                            if (!Library.Utility.Utility.ClientFilenameStringComparer.Equals(parts[ni], largestprefixparts[ni]))
                                break;

                        if (ni != largestprefixparts.Length)
                        {
                            if (ni == 0)
                            {
                                largestprefixparts = new string[0];
                                largestprefix = string.Empty;
                            }
                            else
                            {
                                Array.Resize(ref largestprefixparts, ni - 1);
                                largestprefix = string.Join(Path.DirectorySeparatorChar.ToString(), largestprefixparts);
                            }
                        }
                    }
                    filecount++;
                }
```

**Comment by ulicky** [comment]
Or may be code block above is ok, but then problem occurs in here because prefixpath = string.Empty

```
        private static string MapToRestorePath(string path, string prefixpath, string restorepath)
        {
            if (string.IsNullOrWhiteSpace(restorepath) || string.IsNullOrWhiteSpace(prefixpath))
                return path;

            return Path.Combine(restorepath, path.Substring(prefixpath.Length));
        }
```

**Comment by kenkendk** [comment]
Thanks for reporting.

Do you have a fix? Feel free to submit a pull-request, otherwise I will have a look and see if I can fix it.

**Comment by ulicky** [comment]
Ok, try to fix by myself, just review my logic:
Going to use logic I found here (it is even described in comment :) that this is special case):
 public void SetTargetPaths(string largest_prefix, string destination)
if (string.IsNullOrEmpty(largest_prefix))
					{
						//Special case, restoring to new folder, but files are from different drives
						// So we use the format <restore path> / <drive letter> / <source path>
						// To avoid generating paths with a colon
						cmd.ExecuteNonQuery(string.Format(@"UPDATE ""{0}"" SET ""Targetpath"" = ? || CASE WHEN SUBSTR(""Path"", 2, 1) == "":"" THEN SUBSTR(""Path"", 1, 1) || SUBSTR(""Path"", 3) ELSE ""Path"" END", m_tempfiletable), destination);
					}
	                

And apply it to private static string MapToRestorePath(string path, string prefixpath, string restorepath)

**Comment by mnaiman** [comment]
Submitted pull request

**Comment by HRomie** [comment]
I can also confirm this issue in windows 8.1 x86 running installed version of 2.0.1.17_canary_2016-05-14

Also possibly, related: https://github.com/duplicati/duplicati/issues/1759

If i choose a manual location in the web interface, it works. however choosing to restore the files to the original location, causes Duplicity to try restoring files to "C:\Program Files\Duplicati 2\null\" . you can confirm this by running Duplicity as admin and actually observe the restored files being put there. running as non-admin user, due to UAC being activated for Duplicati (This is by the way something else that should also be taken care of) , it tries to write to "%USERPROFILE%\AppData\Local\VirtualStore\Program Files\Duplicati 2\null\" , however, it seems to fail to actually deliver the files there and only creates the folder.

**Comment by kenkendk** [comment]
Thanks for the fix, sorry for the delay :)

**Comment by kenkendk** [comment]
@HRomie: The other issue you mention with restoring to the original folder is detailed in issue #1624
