### ISSUE TITLE
First Backup fails with error 553

### ISSUE THREAD

**Issue by chrmoeller** [duplicati/duplicati#1773]
Can't write on a ftp-server running on WDMyCloud. The following error occurs:

Fehler: Dateiauflistung nicht aufrufbar: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.

Error: System.Exception: Dateiauflistung nicht aufrufbar: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
   bei System.Net.FtpWebRequest.CheckError()
   bei System.Net.FtpWebRequest.GetResponse()
   bei Duplicati.Library.Backend.FTP.List(String filename)
   bei Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   bei Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   bei Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   bei Duplicati.Library.Main.Interface.Backup(String[] sources)
   bei Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
   bei System.Net.FtpWebRequest.CheckError()
   bei System.Net.FtpWebRequest.GetResponse()
   bei Duplicati.Library.Backend.FTP.List(String filename)
   bei Duplicati.Library.Main.BackendWrapper.ListInternal()
Ergebnis des Aufräumens:
Error: System.Exception: Dateiauflistung nicht aufrufbar: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
   bei System.Net.FtpWebRequest.CheckError()
   bei System.Net.FtpWebRequest.GetResponse()
   bei Duplicati.Library.Backend.FTP.List(String filename)
   bei Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   bei Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   bei Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   bei Duplicati.Library.Main.Interface.DeleteAllButNFull()
   bei Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
   bei System.Net.FtpWebRequest.CheckError()
   bei System.Net.FtpWebRequest.GetResponse()
   bei Duplicati.Library.Backend.FTP.List(String filename)
   bei Duplicati.Library.Main.BackendWrapper.ListInternal()

What has to be done?
##

**Comment by Stackable1** [comment]
Having the Exact same problem  with FTP  to WDMyCloud 2 Device:
The remote server returned an error: (553) File name not allowed.   Duplicati 1.3.4 worked fine to FTP to this device.  Any ideas as to how to fix this issue?

**Comment by kenkendk** [comment]
More of a workaround, but there is another FTP backend: aFTP.
Can one of you try to change the url from `ftp://` to `aftp://` ?
(I know this is an old issue)

**Comment by vaclavbartos** [comment]
I had the same issue with my WD MyCloud, changing the storage type to "FTP (Alternative)" (aFTP) helped.
