### ISSUE TITLE
duplicati for synology. Error 'Bad gateway'

### ISSUE THREAD

**Issue by bobambrosius** [duplicati/duplicati#1776]
Installed 'duplicati-2.0.1.17_canary_2016-05-14.spk'  on synology. No errors reported and starts up okay. Then an error box comes up with 'Bad Gateway'. Have to look quickly because right after that this error box is partially obscured by another error box which says 'the connection to the server is lost'. Countdown repeats indefinitely.
I have successfully used duplicati-2.0.1.17_canary_2016-05-14-x64.msi on my pc, which works just fine.
In the attachment are my synology NAS specifications.
##

**Comment by bobambrosius** [comment]
Hmm. Forgot the attachment ;-(
![synology diskstation specs](https://cloud.githubusercontent.com/assets/16958141/15403231/4b4735bc-1df8-11e6-9d09-3854897cfe25.png)

**Comment by m5x** [comment]
For me the reason for the same error was that `mono` wasn't in the `PATH`. Adding link to it to `/usr/local/bin` fixed the problem.

**Comment by bobambrosius** [comment]
Hi Martin,

Thanks for the update. It doesn't help me, though. I have a synology 
DS212j which comes with a Marvell Kirkwood mv6281 processor. I can only 
install a very limited set of linux programs, and mono is not one of 
them. I am planning to by a synology DS216+ which, I believe, has a 
normal processor: Intel Celeron N3050 SoC. Installation of mono will 
then be possible.

Regards,
Bob

Op 23-6-2016 om 2:04 schreef Martin Dvořák:

**Comment by kenkendk** [comment]
There is a new way of handling the requests on Synology in the latest release, so this issue should be fixed. If a new/similar issue exists, please open a new issue.
