### ISSUE TITLE
Debugging OpenDrive webdavs problems

### ISSUE THREAD

**Issue by hcjehg** [duplicati/duplicati#1778]
Hello Kenneth

I am experimenting with the unlimited OpenDrive.com plan (https://www.opendrive.com/pricing $US12.95/month $US129/year) with webdav access :-O

I have some problems though. For instance Duplicati claims that the target directory is empty even though 3 files were written to the directory by Duplicati, visible through ther web inteface and MS Explorer's webdav connection. It returns _very quickly_ with a "No files found" or "Directory does not exist" message.

Their webdav solution is in Beta so it is quite possible that the problem is in their end, but I would like to  to debug the communication. Is there a way of activating debug messages/log of all communications/backend actions as an alternative to setting up a http/https proxy and wiresharking...

I have also got the problem that the opendrive webdavs url doesn't get recogniced properly by the "Backup To" helper (You are currently running Duplicati - 2.0.1.17_canary_2016-05-14).

![image](https://cloud.githubusercontent.com/assets/12269445/15420563/c118eb62-1e6d-11e6-9372-cdf3b773f877.png)

![image](https://cloud.githubusercontent.com/assets/12269445/15420592/ebacc7f4-1e6d-11e6-9cce-6cbabfdfd7b3.png)

I am imaginig that the two problems are related since the return on "No Files found/Directory does not exist" is very quick - as in if the system thinks that is is really a file it is looking for - as the "Backup To" helper proposes... Would it be possible that there is a problem with the url parser?

Any ideas?

HC

**Comment by hcjehg** [comment]
I can already confirm the problem with webdavs/local folder. I found folders like s5.opendrive.com/Duplicati/ws03-jehg-dk inside the program directory.

**Comment by kenkendk** [comment]
Logging can be done automatically by .Net, as described here:
https://msdn.microsoft.com/en-us/library/ty48b824(v=vs.110).aspx

(Copy the first example file and name it `Duplicati.GUI.TrayIcon.exe.config`, place it next to the executable and restart, the look in `log.txt`).

I can reproduce the problem if I use "webdavs" as the protocol. If I use `webdav://server/path?auth-username=user&auth-password=pass&use-ssl=true` instead, it works correctly, but editing the path looses the "use-ssl" option.

**Comment by hcjehg** [comment]
Hmm, I got the log to work on one of the older versions2.0.1.11 I think, but it does not seem to work on 
Duplicati - 2.0.1.17_canary_2016-05-14 (database upgraded from 5 to 6 so I need to test on 2.0.1.17 :-/)
Are there any tips on making it work? Is debug compiled into 2.0.1.17?
Any ideas are very welcome :-)
HC

**Comment by hcjehg** [comment]
Hmmm here is upstart from an empty backend on an ssl webdav on 2.0.1.17

![image](https://cloud.githubusercontent.com/assets/12269445/15675928/88a892c0-2744-11e6-814e-3c3b9a584038.png)

List shows empty even though all other implementations of webdav shows the files present

![image](https://cloud.githubusercontent.com/assets/12269445/15676025/f00da6da-2744-11e6-9ae6-02bfdf6c27ec.png)

![image](https://cloud.githubusercontent.com/assets/12269445/15676064/11a49a38-2745-11e6-85b2-ae1d7735ece5.png)

I also tried to run against duplicati against webdav (with ssl) on my own owncloud server. No luck either...

Did anyone successfully run 2.0.1.17_canary_2016-05-14 against an ssl enabled webdav ?

HC

**Comment by kenkendk** [comment]
I think this has to do with how the returned filenames are parsed.
The DAV specs are very vague on how to do this, so all servers have their own quirks.
Can you try with the option `--debug-propfind-file=C:\somwhere\writeable\propfind.txt` and send me the `propfind.txt` file?

**Comment by hcjehg** [comment]
Working on this I noticed that the service/backend does not honor requests to Force Stop during retrys.

[propfind.txt](https://github.com/duplicati/duplicati/files/330808/propfind.txt)

and the corresponding log messsages

2016-06-23 22:56: Terminated with error: Found 2 files that are missing from the remote storage, please run repair
{"ClassName":"System.Exception","Message":"Found 2 files that are missing from the remote storage, please run repair","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)\r\n   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)\r\n   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nVerifyRemoteList\nDuplicati.Library.Main, Version=2.0.1.17, Culture=neutral, PublicKeyToken=8bfe994a39631a7b\nDuplicati.Library.Main.Operation.FilelistProcessor\nVoid VerifyRemoteList(Duplicati.Library.Main.BackendManager, Duplicati.Library.Main.Options, Duplicati.Library.Main.Database.LocalDatabase, Duplicati.Library.Main.IBackendWriter)","HResult":-2146233088,"Source":"Duplicati.Library.Main","WatsonBuckets":null}
2016-06-23 22:56: Running Backup took 00:00:05.517
2016-06-23 22:56: Fatal error
2016-06-23 22:56: PreBackupVerify took 00:00:05.437
2016-06-23 22:56: Found 2 files that are missing from the remote storage, please run repair
2016-06-23 22:56: Missing file: duplicati-i304152d868cf4b0c93a84376cb07436d.dindex.zip.aes
2016-06-23 22:56: Missing file: duplicati-b55964aef82714ee695cf563b72d6c7b4.dblock.zip.aes
2016-06-23 22:56: ExecuteReader: SELECT DISTINCT "Name", "State" FROM "Remotevolume" WHERE "Name" IN (SELECT "Name" FROM "Remotevolume" WHERE "State" IN ("Deleted", "Deleting")) AND NOT "State" IN ("Deleted", "Deleting") took 00:00:00.000
2016-06-23 22:56: Starting - ExecuteReader: SELECT DISTINCT "Name", "State" FROM "Remotevolume" WHERE "Name" IN (SELECT "Name" FROM "Remotevolume" WHERE "State" IN ("Deleted", "Deleting")) AND NOT "State" IN ("Deleted", "Deleting")
2016-06-23 22:56: RemoteOperationList took 00:00:01.003
2016-06-23 22:56: Backend event: List - Completed: ()
2016-06-23 22:56: Backend event: List - Started: ()
2016-06-23 22:56: Starting - RemoteOperationList

I hope this is useful :-)

By the way: You are currently running Duplicati - 2.0.1.17_canary_2016-05-14

HC

**Comment by kenkendk** [comment]
The WebDav server has prefixed the path with double slash, //, which is causing the parser to reject the filename.

**Comment by hcjehg** [comment]
Thank you for taking the time to look at this. 
Is that also the case for the file duplicati-20160619T084820Z.dlist.zip.aes that duplicati is not complaining about?
Does anyone know if this is in violation of for instance rfc4918 ?
...or is it normal behavior as it is an absolute path within the service name space?
Is this, in your opinion, an issue to be fixed in duplicati or in the webdav implementation at OpenDrive?

I guess what I am asking is: is this something to bring to the attention of OpenDrive ?

:-)

HC

**Comment by hcjehg** [comment]
Ah, I just noticed that, somewhere along the road in the webdavs / use-ssl a double slash had snug into the uri for the backup so it was webdav://webdav.opendrive.com:443//Duplicati/ws03... That double slash is reflected in the returned properties it seems. Now, the difficult question, is that an error 40 (in violation of rfc4918) or something that needs fixing in OpenDrive or Duplicati ?

:-D

It seems the backup to OpenDrive is running now :-)  https://www.opendrive.com/ - USD12.95/Month Unlimited Personal :-O

**Comment by kenkendk** [comment]
Great that you figured out what the problem is.
As for "what is correct", the description is here:
http://www.webdav.org/specs/rfc4918.html#rfc.section.8.3.1

I cannot determine which is correct, but it explicitly states that you can return both relative and absolute results. And each WEBDAV server returns different kinds of "relative".

I have added an extra check that also allows double leading slashes, that should fix it if others have an extra stray slash.
