### ISSUE TITLE
Problem backing up PST files from AppData

### ISSUE THREAD

**Issue by Celerbit** [duplicati/duplicati#1781]
Hey there and great job so far with Duplicati!

I was testing the file backup with .ost files from Outlook when I realized that if the .ost files are in the AppData\Local\Microsoft\Outlook folder, the backup won’t work.

I tried moving the .ost file out of that folder into my desktop, tried to backup the copy and everything worked properly.

It literally just doesn’t detect the .ost file from the AppData\Local\Microsoft\Outlook directory.

What should I do?

Thanks in advance.

**Comment by SARG04** [comment]
You need to use Volume Shadow Copy Services (VSS) on Windows to backup in use files.

Run Duplicati with admin rights and set snapshot-policy to auto or on.
https://github.com/duplicati/duplicati/wiki/FAQ
http://www.duplicati.com/howtos/howto-backup-opened-files-e-g-outlook-pst

**Comment by Celerbit** [comment]
I have that running and working but still doesn't back up.

I am using the latest duplicati version by the way.

**Comment by SARG04** [comment]
Have you started Duplicati explicit with admin rights (right click run as ..)?
Starting it as user how has admin rights is not enough. Duplicati doesn't use UAC in this case to get full admin rights.

Try snapshot-policy=required so that the backup doesn't run without VSS.

**Comment by Celerbit** [comment]
Hi there,

I did run the software with admin rights and I did add the snapshot-policy=required bit and it still ignores the file.

If I try to backup any other file it works, but with this specific one, it just gets ignored.

**Comment by Celerbit** [comment]
Any news regarding this situation?

**Comment by Celerbit** [comment]
I found the source of the problem: The files I'm trying to backup are .OST files which aren't backed up by the VSS.

Anyone got throught this matter?

**Comment by agrajaghh** [comment]
https://blogs.technet.microsoft.com/filecab/2007/01/24/why-completepc-backup-does-not-include-ost-files-in-the-backup-image/

> A Microsoft employee contacted us after he discovered that his 4-GB Microsoft Outlook .ost file was not present after he restored an image made by Complete PC Backup. Given the feature name “Complete PC Backup,” he expected that all files would be restored and was concerned about having to regenerate his giant .ost file. No doubt other Windows Vista users will encounter this behavior, so we wanted to explain why .ost files are not part of Complete PC Backup images.
> 
> Maintaining changes to .ost files within shadow copies is expensive in terms of space and I/O activity. The performance impact doesn’t occur during the image backup itself–the only extra work at backup time is backing up the .ost file as part of the image. Instead, the performance impact occurs during the ongoing, everyday I/O to the .ost file when Outlook is running. If the .ost changes were kept in shadow copies, then every time Outlook writes to the .ost file, the result is a copy-on-write I/O hit (2 writes, 1 read). Although we have worked to reduce the impact of copy-on-writes on shadow copies,   a heavily churned file like an .ost file could still cause problems. For these reasons, and the fact that .ost files can be regenerated, we chose to delete .ost files from the shadow copy before the image is created.
> 
> Even if the performance issues didn’t exist, there are situations where Exchange will, after an .ost is restored, detect a “future” version of the .ost file and force you to delete and then regenerate the local .ost file. Therefore, it’s still preferable to regenerate an .ost file instead of restoring it.
