### ISSUE TITLE
Repair is failing System.Exception: Unable to create zip (1) decompressor on file

### ISSUE THREAD

**Issue by golserma** [duplicati/duplicati#1783]
Last successful run: was several days ago. I was asked to run repair.

If i start repair I'm getting:
Failed to accept new index file: duplicati-ifc336cf8287f4a498db353e4f5be07c9.dindex.zip (1).aes, message: Unable to create zip (1) decompressor on file C:\Users\x\AppData\Local\Temp\dup-7995f44a-dba7-4b40-b43b-1ae19645f5e2
System.Exception: Unable to create zip (1) decompressor on file C:\Users\x\AppData\Local\Temp\dup-7995f44a-dba7-4b40-b43b-1ae19645f5e2
   bei Duplicati.Library.Main.Volumes.VolumeReaderBase.LoadCompressor(String compressor, String file, Options options)
   bei Duplicati.Library.Main.Volumes.IndexVolumeReader..ctor(String compressor, String file, Options options, Int64 hashsize)
   bei Duplicati.Library.Main.Operation.RepairHandler.RunRepairRemote()

ReportBug Data:
Duplicati: Duplicati.Server, Version=2.0.1.11, Culture=neutral, PublicKeyToken=8bfe994a39631a7b (Duplicati.Library.Main, Version=2.0.1.11, Culture=neutral, PublicKeyToken=8bfe994a39631a7b)
Autoupdate urls: http://updates.duplicati.com/experimental/latest.manifest;http://alt.updates.duplicati.com/experimental/latest.manifest
Update folder: C:\Program Files\Duplicati2\updates
Base install folder: C:\Program Files\Duplicati2
Version name: "2.0.1.11_experimental_2016-04-08" (2.0.1.11)
Current Version folder C:\Program Files\Duplicati2\updates\2.0.1.11
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
Uname: 
64bit: True (True)
Machinename: QUADCORE-PC
Processors: 4
.Net Version: 4.0.30319.34209
Mono: False (0.0) ()
Locale: de-DE, de-DE, de-DE
Date/time strings: dddd, d. MMMM yyyy - HH:mm:ss
Tempdir: C:\Users\x\AppData\Local\Temp\
Environment variable: TEMP = C:\Users\x\AppData\Local\Temp
Environment variable: TMP = C:\Users\x\AppData\Local\Temp
SQLite: 3.8.5 - System.Data.SQLite.SQLiteConnection
SQLite assembly: C:\Program Files\Duplicati2\updates\2.0.1.11\SQLite\win64\System.Data.SQLite.dll
##

**Comment by ts678** [comment]
Not reproducible using current Duplicati. Could you post your experience?
