### ISSUE TITLE
Duplicati doesn't wake up my NAS

### ISSUE THREAD

**Issue by jspille** [duplicati/duplicati#1784]
Duplicati, both versions 1.3.4 and 2.0.1.17, are not able to wake up my NAS - WD MyBookLive to backup my data. While all other programs, Windows Explorer, Total Commander, MS Office etc. wake up and store data on my NAS, Duplicati tells my that the folder does not exist. 
If I, e.g. open a folder on the NAS with the Windows Explorer first, and the NAS is running, Duplicati works fine. 

Failed to create folder: The folder Z:\Duplicati2Jens does not exist
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "Z:\Duplicati2Jens" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   bei System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   bei System.IO.Directory.CreateDirectory(String path)
   bei Duplicati.Library.Backend.File.CreateFolder()
   bei Duplicati.Library.Main.BackendManager.ThreadRun()
##

**Comment by warwickmm** [comment]
Duplicati relies on the .NET framework or the Mono implementation to access the filesystem.  I haven't heard any other cases of this, so I'm going to assume it's been fixed.  If it's still an issue, feel free to reopen.
