### ISSUE TITLE
Duplicati crashes at end of first backup

### ISSUE THREAD

**Issue by RafaelSchridi** [duplicati/duplicati#1786]
> Newtonsoft.Json.JsonSerializationException: Error converting value "createdDate" to type 'Duplicati.Library.Backend.AmazonCloudDrive.AmzCD+ResourceModel'. Path 'data[123]', line 1, position 67485. ---> System.ArgumentException: Could not cast or convert from System.String to Duplicati.Library.Backend.AmazonCloudDrive.AmzCD+ResourceModel.
>    at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
>    at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
>    --- End of inner exception stack trace ---
>    at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
>    at Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
>    at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
>    at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
>    at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
>    at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
>    at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

2.0.1.17_canary_2016-05-14
##

**Comment by warwickmm** [comment]
Support for the Amazon Cloud Drive backend has been removed.  See the discussion [here](https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391).
