### ISSUE TITLE
Backend for OpenDrive

### ISSUE THREAD

**Issue by hcjehg** [duplicati/duplicati#1790]
Here is a proposal for making a backend for OpenDrive that has an unlimited account at USD12.95/md or USD129/year

https://www.opendrive.com/api

They are also working on a webdav interface, but it is not working (yet) and it seems slow, but it is on the way. This proposal should probably be prioritized low :-)

HC
##

**Comment by warwickmm** [comment]
OpenDrive should be now be supported via WebDAV.
