### ISSUE TITLE
The supplied option --enable-piped-streaming is not supported and will be ignored

### ISSUE THREAD

**Issue by Quack6666** [duplicati/duplicati#1793]
According to the news here:
http://www.duplicati.com/news/majorupdatecoming

There is a parameter named **--enable-piped-streaming** that we can use to increase the speed of our backup in Duplicati 2.0.

The issue is that the logs shows that the command is either not recognised or invalid 

`Warnings: [The supplied option --enable-piped-streaming is not supported and will be ignored]`
##

**Comment by Dikay900** [comment]
well the news states this option under the heading "restore speed" so i assume this is for restoring only.

**Comment by agrajaghh** [comment]
@CharlesErickT what version of duplicati are you running?

**Comment by CharlesErickT** [comment]
@agrajaghh 2.0.1.17_canary_2016-05-14

**Comment by gpatel-fr** [comment]
This option has been changed in eea33a764958b3f0f3ede286aec8cd2a8fdb87e6 to reverse the default.
