### ISSUE TITLE
Overriding asynchronous-upload-folder does not seem to work

### ISSUE THREAD

**Issue by giejay** [duplicati/duplicati#1795]
The default upload folder for the temp files on Windows 10 is C:\Users\Username\AppData\Local\Temp. 

My C: drive on my laptop has limited space, that is why I want to override the folder to: D:\Backups (or something like that). Unfortunately, whatever I try, the temp files are still being stored in the user tmp directory, which results in backups being terminated due to unsufficient diskspace.. 

Am I doing something wrong or is this a bug on Windows 10? Or is the asynchronous-upload-folder not meant for this?

Version: 2.0.1.17_canary_2016_05-14
Windows 10
Size of upload: 44GB

**Comment by huste** [comment]
I think there are more issues to options. See #1914

**Comment by kenkendk** [comment]
Is this because the options are listed in the "global options" area and not on the backup?
There is currently a bug where the options listed under "Settings" are not applied.
