### ISSUE TITLE
Can´t start duplicati on Synology (DSM 6) > "ForbiddenException"

### ISSUE THREAD

**Issue by Calmero** [duplicati/duplicati#1796]
Hi guys

Synology: DS215j
DSM 6.0-7321
Mono 4.2.1-0088
duplicati-2.0.1.17_canary_2016-05-14

I have install MONO and duplicati-2.0.1.17_canary_2016-05-14.spk
There are no problems to start duplicati. If i open IP-ADD:8200 I can see the following error in a popup window. > "ForbiddenException"

Can every body help me to fix this?
Thx. 
Best Regards,
Calmero
##

**Comment by kaasszje** [comment]
By default the webserver only listens to localhost.
You have to adjust this setting first before accessing it remotely.
So you would need to start it with something like:
mono Duplicati.Server.exe --webservice-interface:any

After that you should be able to access the web interface.

**Comment by kenkendk** [comment]
Closing for lack of feedback, and I think @kaasszje has the right answer
