### ISSUE TITLE
Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by fbernardez** [duplicati/duplicati#1801]
When I run the task returns this error "Exception has been thrown by the target of an invocation."

The connection string is:
webdavs://www.cloudstorage.es:443/vdxxxxx/Directory?auth-username=user@domain.com&auth-password=mypassword&accept-any-ssl-certificate=true

When I write the form of connection, set these parameters
Storage type: WebDAV
Use SSL
Server: www.cloudstorage.es
Port: 443
Path on server: vdxxxxx/Directory
Username: user@domain.com
Password: mypassword
Accept-any-ssl-certificate

In Test Connection answer "Connection worked"

When I go to modify the task I get this 
Path on server: www.cloudstorage.es/vd16991/DinoServer
If I test the connection then returns this error "Failed to connect: The remote server returned an error: (405) Method Not Allowed."

Sorry I d'ont speak English. I use google translate
##

**Comment by ts678** [comment]
Is this still a problem on current Duplicati?
