### ISSUE TITLE
Upload into MEGA is slow

### ISSUE THREAD

**Issue by JonasDralle** [duplicati/duplicati#1805]
Hello Kenneth and other people who want to improve duplicati

I use _Duplicati - 2.0.1.17_canary_2016-05-14_ with [these system stats](http://pastebin.com/A4DFMvFk) to backup Data into Mega.nz ([backup configuration in json format](http://pastebin.com/XbDtAUFk))

The folder I'd like to backup is about 13 GB in size and I expect it to grow in the future.
Duplicati isn't able to upload the data into the Mega account

Every day I start my computer in the morning and shut it down in the evening to give Duplicti the time to upload all data but yet I have done this for multiple days in a row it was still unable to upload the data in mega.
When I look into the logs I can only see that it wraps everything up correctly and then launches an async uploader thread and waits for it.
I don't know if the data is just too big or the uploader too slow but I can tell you that it's not working.

My Windows Computer is configured to go back to the login screen after 15 min of inactivity. Duplicati is configured to pause 10 min after start.
(Duplicati should work fine even if Windows goes to the login screen)

Maybe you cannot upload 13 GB within a day but you could at least split it into smaller packages and upload those. Or do some other trickery to mage MEGA.nz upload working

the folder in question: (german)
![12.9 GB - 3944 Files - 535 Subfolders](http://i.imgur.com/tJwgwIy.png)

![](http://i.imgur.com/KZRFMzy.png)

Thanks. Have a good day

**Comment by JonasDralle** [comment]
Here's what I'd like to be able to do:

I have a folder of 100 GB of content and my PC is online only for an hour each day but Duplicati is such a good program that it syncs anyway.

I don't ask you to upload *all* of it within an our but at least make *progress* on it. Because when you cannot even make slight progress on the case above this software is pretty much useless for the casual laptop user

**Comment by btriffles** [comment]
I don't have much experience with using Duplicati, but it looks like your dblock-size might be set to 50 GB.  If that's the case, then I wouldn't be surprised if Duplicati is struggling to create a multi-gigabyte file, or your network connection is failing to upload it.  Try setting dblock-size to the default (maybe "50mb"?) to see if it helps.

**Comment by JonasDralle** [comment]
**_Oh_**
Big mistake on my part

I thought that was similar to the "never let the backups grow larger than _x_" from the v1

**Comment by agrajaghh** [comment]
@JonasDralle Is your porblem fixed with a smaller dblock size?

**Comment by JonasDralle** [comment]
I can confirm that my upload is able to succeed now with dblock size of 50 MB

![proof](http://i.imgur.com/LnMpvF1.png)
