### ISSUE TITLE
duplicati2: login password encrypts backup configuration?

### ISSUE THREAD

**Issue by chaos-prevails** [duplicati/duplicati#1807]
Dear all,

does the login password on the duplicati2 login screen encrypt the local backup configuration including the backup passphrase with which I encrypt my backups? 

If you make a backup of your laptop on a USB stick and somebody finds both, can the person restore everything because of access to the local backup configuration (e.g. by installing duplicati2 somewhere else, copy my config over and plug in the USB stick)? I know that you can move the metadata-DB to the backup location itself, but this doesn't move the backup passphrase, I still see it and can restore without entering the backup passphrase.

If not, what does the login password do?

thanks,

**Comment by kenkendk** [comment]
Closing and merging into #2024.
