### ISSUE TITLE
Better backup status reporting

### ISSUE THREAD

**Issue by balazer** [duplicati/duplicati#1808]
The most important questions I have about any backup are:
1. Have all of my files been backed up?
2. How many of my files still need to be backed up? (relative to the total number of files in my backup set)
3. What's the total size of those files?
4. How long will it take to back them up?

Duplicati 2.0.1.17 makes it surprisingly difficult to answer these questions.  Under the configured backup, it says "Last successful run" even if that run did not complete normally.  It lists the backup size, but that can differ substantially from the source due to compression or files having many versions.  The only way I can determine that all of my files have been backed up is to actually watch the currently running backup task while it is running, and watch the "files to go" count drop to 0.

I propose that the backup, in addition to showing "last successful run", "next scheduled run", the source size, and the backup size, also show:
1. The number of files in the backup set (and their total size)
2. The number of files that still need to be backed up (and their total size)

These numbers could reflect the end of the last backup task, or better yet, they could be updated in real time to reflect the status of the currently running backup task.

And for the currently running backup task, in addition to just showing a count of "files to go" and their total size, also show the total number of files in the set and their total size,
E.g:  "346 of 11,567 files to go (98 MB of 12.3 GB)", and also an ETA, based on the total size of the files remaining to be backed up and the number of bytes that were backed up in the last 10 seconds, or something like that.  Such a simple estimation could be grossly inaccurate depending on whether files need to have blocks uploaded or not, but it would be far better than nothing.

Thanks for your consideration.  I appreciate all of the hard work that has been put into Duplicati.
##

**Comment by warwickmm** [comment]
The UI for displaying backup statistics was improved in pull request #3538 (released in 2.0.4.6).  If there are further improvements to make, please open a new issue with additional details.
