### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by LiPoPower** [duplicati/duplicati#1810]
[Uploading bugreport.zip…]()

Getting an SQL Error on manually starting a Backup and display the logs
Installed duplicati-2.0.1.17_canary_2016-05-14-x64.msi on Windows 10 1511 .

[Uploading Duplicatierror.pdf…]()
##

**Comment by agrajaghh** [comment]
the upload didn't work. Can you please try it again? (you need to wait until the uplaod is finished before posting the comment)

**Comment by warwickmm** [comment]
Closing due to lack of information.  If this is still an issue, please reopen with new details.
