### ISSUE TITLE
SFTP/SSH connections should verify the server's fingerprint

### ISSUE THREAD

**Issue by HRomie** [duplicati/duplicati#1812]
To eliminate the possibility of Man-in-the-middle attack, it is required for the client to verify the servers fingerprint with the pre-defined hash value provided by the user. This should happen before sending the login credentials and the client must disconnect if it could not validate the server. right now, without this verification, Duplicati is ignoring a very important part of the SSH protocol and exposing the user to the possibility of man-in-the-middle attacks.

**Comment by kenkendk** [comment]
I agree, this should be added.

**Comment by mnaiman** [comment]
Submitted pull request #1823

**Comment by kenkendk** [comment]
This was fixed with 4ac829147e47a2a5782d2c29581643559f0dd1ef
