### ISSUE TITLE
OD4B - password?

### ISSUE THREAD

**Issue by zappe** [duplicati/duplicati#1813]
How is the password stored?
When I edit the backup I see it in cleartext, is it possible to hide that?
##

**Comment by zappeee** [comment]
Any updates?

**Comment by zappeee** [comment]
Another thing.
After adding the connection the password is shown in clear text under step 1, General, and under "Backup to >"

**Comment by kenkendk** [comment]
Sorry about the labels, this is actually a duplicate of #2024
