### ISSUE TITLE
SMTP(TLS) Authentication is not working

### ISSUE THREAD

**Issue by HRomie** [duplicati/duplicati#1817]
I have setup Duplicati to send email to my webserver after each backup. The server requires authentication. however, no matter what i do, Duplicati does not seem to be authenticating.
Here's the email setting that I've used in the web gui (my real domain name has been replaced with example.org):

```
--send-mail-from=Duplicity Test <test@example.org>
--send-mail-level=All
--send-mail-password=pass123
--send-mail-to=admin@example.org
--send-mail-url=tls://smtp.example.org
--send-mail-username=user123
```
 Since, this is my own server, i am able to provide you with the actual smtp conversation:

```
 Out: 220 mail-smtp.example.org ESMTP ready
 In:  EHLO theclient
 Out: 250-mail-smtp-tls.example.org
 Out: 250-PIPELINING
 Out: 250-SIZE 20971520
 Out: 250-STARTTLS
 Out: 250-ENHANCEDSTATUSCODES
 Out: 250-8BITMIME
 Out: 250 DSN
 In:  STARTTLS
 Out: 220 2.0.0 Ready to start TLS
 In:  EHLO theclient
 Out: 250-mail-smtp-tls.example.org
 Out: 250-PIPELINING
 Out: 250-SIZE 20971520
 Out: 250-AUTH PLAIN
 Out: 250-ENHANCEDSTATUSCODES
 Out: 250-8BITMIME
 Out: 250 DSN
 In:  MAIL FROM:<test@example.org>
 Out: 553 5.7.1 <test@example.org>: Sender address rejected: not logged in
```

Please note that it is perfectly legal to advertise 'AUTH PLAIN' only after TLS negotiation. It however does not seem to be the problem here anyway, as I've activated it also before TLS, or even tried to use the normal non-TLS connection and still Duplicity did not authenticate. 

I am testing Duplicity v2.0.1.17_canary_2016-05-14 on windows 8.1 x86

**Comment by mnaiman** [comment]
Why your server accept only AUTH PLAIN and on AUTH LOGIN? I have AUTH LOGIN and it works fine. Can you create test account and send me connection info to debug against your server?

**Comment by HRomie** [comment]
Hi mnaiman,

You seem to be on the right track. after activating AUTH LOGIN, duplicati tried to authenticate. about why it's not activated on my server, it's simply because it's not a requirement. not but my clients nor by standard. the AUTH LOGIN method is not mandatory. in fact i doubt that the SMTP LOGIN authentication method is standard at all. from what i could gather, this method seems to have gotten its popularity from Microsoft Outlook (Express). AUTH PLAIN on the other hand, is rfc standard and even mandatory over TLS.

from [rfc4954](https://tools.ietf.org/html/rfc4954):
>    To ensure interoperability, client and server implementations of this
>    extension MUST implement the [PLAIN] SASL mechanism running over TLS
>    [TLS] [SMTP-TLS].  See also Section 15 for additional requirements on
>    implementations of [PLAIN] over [TLS].

which is exactly what my server is offering.

It seems that the safest (and likely the best) course of action, is that between PLAIN and LOGIN method, PLAIN should be the preferred one if it's available (it MUST be over TLS. however, even though sending plain text AUTH over a non-secure channel is discouraged, if it needs to be, supporting PLAIN don't seem to be mandatory)

I have no problem of creating you a test email account if you need more debugging. But I'm not sure how to send you the info as I can't find any PM functionality in github.

**Comment by mnaiman** [comment]
I have created one time email zvblnlaf@imgof.com, you can send me address and test login details there. Of course after debugging disable test access.

**Comment by HRomie** [comment]
@mnaiman 
Check the email please.

**Comment by mnaiman** [comment]
First finding: .NET framework does not support PLAIN AUTH.
I have debugged framework itself and find out only these AUTH modules.
            SmtpAuthenticationManager.Register(new SmtpNegotiateAuthenticationModule());
            SmtpAuthenticationManager.Register(new SmtpNtlmAuthenticationModule());
            SmtpAuthenticationManager.Register(new SmtpDigestAuthenticationModule());
            SmtpAuthenticationManager.Register(new SmtpLoginAuthenticationModule());

So not easy solution to enable some switch. But I continue digging, keep me access to your server, it is crucial.

**Comment by HRomie** [comment]
Thank you for your effort. you will have the access till it's done.

**Comment by mnaiman** [comment]
This was difficult, because .net framework cannot support that.
So I added another free library for that. Benefit is that we can you ssl smtp (not starttsl) which is not supported in .net framework too. 

Confirm pls, that you received some mail.
Submitted pull request #1827.

**Comment by HRomie** [comment]
Confirmed. I have received couple of emails, all starting with:

> Failed: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

which I'm guess is the intended result.

Thank you very much for working on this. you've done a wonderful job fixing this issue instead of just giving up because .net did not provide a direct support for it (which is quite troublesome thinking about it. that how they could ignore a rfc standard method and yet include a likely-non-standard one anyway).
You have my respect, well done.

**Comment by mnaiman** [comment]
@HRomie if all ok, you can close this bug
