### ISSUE TITLE
No backup

### ISSUE THREAD

**Issue by HDInfautre** [duplicati/duplicati#1819]
Hello,
The backup works well on some files but not on a large directory. 

The backup does not start and I have this message
"_The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again_."

I realize  operations (delete, repair ...)
No improvement

See my config in the bugreport
[bugreport.zip](https://github.com/duplicati/duplicati/files/322365/bugreport.zip)

Regards
##

**Comment by HDInfautre** [comment]
Hello
+ 1 please

**Comment by ts678** [comment]
> but not on a large directory

If this is still of interest and still happens -- how large a directory?

> See my config in the bugreport

It doesn't contain the config, and the config wouldn't say how big the directory is. But reports shows three files in the backup.
