### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by zappe** [duplicati/duplicati#1820]
A setting to make Duplicati auto start after a reboot would be great.

**Comment by jvook** [comment]
Add Duplicati shortcut to startup folder
\To find the Startup folder, the quickest way is to do the following:
Hold down the Windows key, and type R.
Type: shell:startup.
Click OK.

**Comment by agrajaghh** [comment]
a service is on the roadmap

**Comment by zappe** [comment]
@jvook, yeah, that's what I've done until now.

@agrajaghh, good! any ETA on that?

**Comment by antonpiatek-imanage** [comment]
@agrajaghh link? 
This is bothering me on linux too

**Comment by tarbib** [comment]
@antonpiatek-imanage Hello, have you found a solution?
