### ISSUE TITLE
Exclude doesn't work.

### ISSUE THREAD

**Issue by zappe** [duplicati/duplicati#1821]
I'm running a backup on my %HOME% and inside that folder I have the OD4B folder which I excluded with "%HOME%\OneDrive - X X X".

But that doesn't seem to work since it backups that folder anyway.
How can I solve that?

If now tried to add "C:\Users\stalhamm\OneDrive - X X X" as an exclusion instead to see if that helps.
Or should I exclude directories whose name contain "OneDrive" maybe?

**Comment by agrajaghh** [comment]
this will be fixed in the next release, see #1645

If you still encounter this bug in the next release please post again.
