### ISSUE TITLE
Support for Differential backup

### ISSUE THREAD

**Issue by adeorato** [duplicati/duplicati#1825]
Duplicati should support differential backup [1].

Differential backups are like incremental backup. The only difference is, that it is always compared against the last full backup and not against the last incremental backup.  The advance is, that combined with incremental backup, not every incremental file has to be loaded. I backup to the internet and with the differential approach I could enlarge the time distance between full backups. Most of my files never changes and the once who changes, changes frequently.

== Example
The following example illustrates the difference:
Daily backup, I want to restore the 8th day. With incremental backup, the full backup is loaded, all 7  incremental backup files have to be loaded and then the backup can be executed.
With a differential backup instead only the full backup has to be loaded and one differential backup file.

Also the differential can be combined with the incremental.approach. In this case, the restore can work this way:
- Load the full backup
- Load the closest differential backup
- Load the incremental backup files until the wanted day is reached.

With the above example (and weekly differential ) it has to be loaded:
- One full backup, differential from day 7, incremental from day 8.

[1] https://en.wikipedia.org/wiki/Differential_backup

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore.

Duplicati 2.0 is not using full backups anymore, all the data is stored as blocks. During backup new/changed blocks are uploaded, during restore all blocks necessary to restore the specified file revision are downloaded.

A detailed description can be found here:
https://github.com/duplicati/duplicati/wiki/Developer-Documentation
http://www.duplicati.com/news/theduplicati20storageengineishere
