### ISSUE TITLE
Duplicati Verify all?

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#1826]
Duplicati.commandline.exe verify %beckend% %dbpath%
The above command verifies only 3 files how to verify all dblock files

Duplicati.com... verify all %backend% %dbpath%
Duplicati.com... verify --all %back.....
Duplicati.... verify all %back.....

None of the above verifies any files just gives errors saying like ignoring not supported option.

What is the correct command to verify all dblocks?

Savio

**Comment by agrajaghh** [comment]
you have to put "all" or the number of dblocks at the end, look at the help output:

```
Duplicati.CommandLine.exe help verify

Usage: test <storage-URL> [<samples>] [<options>]

  Verifies integrity of a backup. A random sample of dlist, dindex, dblock files is downloaded, decrypted and the content is checked against recorded size values and data hashes.
  <samples> specifies the number of samples to be tested. If "all" is specified, all files in the backup will be tested. This is a rolling check, i.e. when executed another time
  different samples are verified than in the first run. A sample consists of 1 dlist, 1 dindex, 1 dblock.

  --time=<time>
    Checks samples from a specific time.
  --version=<int>
    Checks samples from specific versions. Delimiters are , -
```

Does this work for you?

**Comment by saviodsouza** [comment]
Thank you adding "all" at the end worked.

Wanted to know one more thing how will it handle bad dblocks. Will they be deleted.

Because I received errors something like 'bad block hashes...' when testing a restore operation recently.

**Comment by kenkendk** [comment]
Testing does not modify data, it only verifies integrity.
You may want to try with the `--full-remote-verification` flag as well, if you see "bad block hashes".

I will update the documentation to indicate that `<samples>` is mandatory, and add a hint with the full verfication.
