### ISSUE TITLE
How do the global options work?

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#1830]
I did put --upload-verification-file=true to global options, so I think that it will be applied to all backups on server. But nothing happens. It is bug, or feature?

**Comment by sftwrengnr** [comment]
I reported this a while ago, but no feedback: #1720

**Comment by mnaiman** [comment]
@kenkendk what is meaning of these 2 constants in Duplicati.Server.Database.Connection?
        public const int ANY_BACKUP_ID = -1;
        public const int APP_SETTINGS_ID = -2;

**Comment by mnaiman** [comment]
Ok, it seems, that global options are saved to DB as -2, but they should be -1. If I change them manually to -1 it works.

**Comment by mnaiman** [comment]
These global settings are in bigger mess than i thought. :-)
Too many things has same names, ServerSettings, Default Options, ApplicationSettings, SystemWideSettings, BackupDefaults.
It is hard to change/refactor something, because it has large impacts.

**Comment by kenkendk** [comment]
@mnaiman : I agree, it is a total mess :D

`APP_SETTINGS_ID` should mean "settings that relate to the Server", something like `--listen-interface` and similar.

`ANY_BACKUP_ID` should be the global options.

`ApplicationSettings` is a typed instance that exposes the `APP_SETTINGS_ID` items from the database, and `SystemWideSettings` is the `ANY_BACKUP_ID` items.

`ServerSettings` is used to report server config, and includes things like operating system, backend modules loaded, etc.

`BackupDefaults` is a set of options applied to a new backup.

`DefaultOptions` is only used in the unittests.

**Comment by kenkendk** [comment]
There are a few errors related to this.

I can see that the advanced options are indeed merged into the ApplicationSettings/ServerSettings.

I will rename ApplicationSettings to ServerSettings, and look at how to fix the rest.

**Comment by mnaiman** [comment]
Ok, thx for explanation. I will test that in new build.
