### ISSUE TITLE
Backup fails on system requiring FIPS compliant algorithm even with encryption disabled

### ISSUE THREAD

**Issue by rprego** [duplicati/duplicati#1833]
Using v1.3.4 on a security-hardened Windows 7 machine, backups fail with the error message: "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms." The backups are set to not be encrypted, so the backup should not fail due to a non-FIPS algorithm being used.
The relevant group policy setting is this one: https://support.microsoft.com/en-us/kb/811833. 
##

**Comment by FredericMa** [comment]
I've also seen this issue on my Windows Server 2012.
I've found a workaround which is adding "<enforceFIPSPolicy enabled="false"/>" to the Duplicati.Server.exe.config

**Comment by rprego** [comment]
This is almost 8 years old, and unfortunately I can't provide any of the requested feedback.
