### ISSUE TITLE
Webdav over ssl on a OwnCloud Server

### ISSUE THREAD

**Issue by glannes31** [duplicati/duplicati#1836]
Hello , I try to understand why Duplicati is not working with Webdav over SSL
```
System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (IAsyncResult asyncResult) <0xad96338 + 0x000e3> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (IAsyncResult ar, Boolean ignoreEmpty) <0xad96290 + 0x0001f> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (IAsyncResult result) <0xad93de8 + 0x0019b> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (IAsyncResult result) <0xad96d38 + 0x000ab> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) <0xad96b48 + 0x0005f> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (IAsyncResult asyncResult) <0xad93440 + 0x00133> in <filename unknown>:0 
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (IAsyncResult asyncResult) <0xad933c0 + 0x00037> in <filename unknown>:0 
  at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation) <0xad8f440 + 0x00050> in <filename unknown>:0 
```

**Comment by glannes31** [comment]
It's very important for me to solve this issue . It's a bug...

**Comment by mnaiman** [comment]
Do you have test address of webdav server to debug?

**Comment by glannes31** [comment]
Duplicati runs on Mac ( test do on yosemite and el capitan).  The webdav connection is Ok . and duplicati works on linux and windows.

**Comment by glannes31** [comment]
Hello , more precision : all mac users of this webdav server  are impacted. 
Owncloud server is on version 7 . In september we upgrade the version.

**Comment by glannes31** [comment]
Hello @mnaiman i built a webdav server with ssl ( Ubuntu 16) and the issue is the same.

**Comment by mnaiman** [comment]
Can you put such kind of test machine on internet? Send me address and I try to debug root cause.

**Comment by glannes31** [comment]
@mnaiman  I create you an account on our cnrs platform ( mycore.core-cloud.net)
log in : duplicati
password : Duplicati1@

Webdav is used on 443 port . Please tell me when you finished .

**Comment by glannes31** [comment]
For the webdav server with ssl , i used this : http://www.jovicailic.org/2013/10/how-to-install-apache-with-ssl-webdav-on-ubuntu/

**Comment by mnaiman** [comment]
I tired to connect via WinSCP(free) to server and got "405 Method Not Allowed". Does it works for you?

**Comment by glannes31** [comment]
Do you tick use ssl  ? and choose 443 port ?

**Comment by mnaiman** [comment]
Yeah, it is covered by some "Janus" system for login. Isnt that some firewall/proxy for connectins from internet?

**Comment by glannes31** [comment]
Oh I am sorry , there are a remote directorie  : remote.php/webdav/

**Comment by mnaiman** [comment]
Thats better, it asks for user/pass but when provided it throws "
  Sabre\DAV\Exception\NotAuthenticated
  Username or password does not match
  1.8.12"

**Comment by glannes31** [comment]
Could you retry please?    I use Wireshark and i see errors  : handshake failure et internal error .

**Comment by mnaiman** [comment]
Using firefox, winscp, both says access denied

**Comment by mnaiman** [comment]
Same duplicati Failed to connect: The remote server returned an error: (401) Unauthorized.

**Comment by mnaiman** [comment]
Do you have reverse proxy before your webdav server? I saw similar error "handshake failure et internal error" if certificates between reverse proxy and http/webdav server were in mismatch or TLS was not properly configured.

**Comment by glannes31** [comment]
I enquire this and i come back to you . tks for your test , i tks tha is not possible in other country ...  Try to mak an ubuntu webdav server with ssl withe the link, you would have the same error

**Comment by glannes31** [comment]
@mnaiman  I see in wiresharck a client hello in tls1.0 while a choose tls1 1 in allowed ssl versions . How to force duplicati use tls 1.1 or 1.2 ?

**Comment by mnaiman** [comment]
https://github.com/duplicati/duplicati/issues/1350 There is a feature for that based on my request.

**Comment by glannes31** [comment]
It's what i do , i choose allowed ssl tls 1.2 and it's the same . I see TlsV1 in protocol . On windows , i see Tlsv1.2

**Comment by mnaiman** [comment]
Ok, may be it is not propagated to webdav, let me check that.

**Comment by glannes31** [comment]
Tks for all @mnaiman .i 'm waiting

**Comment by mnaiman** [comment]
It looks like it should work. It would be super easy to have such kind of server to debug against.

**Comment by glannes31** [comment]
I said that you can built an ubuntu server with webdav . It's the same problem, i see the same thing . the TLSv1 is used .

**Comment by mnaiman** [comment]
I know, but have little time to do that. :(

**Comment by glannes31** [comment]
I understand . When i write --allowed-ssl-version=tls , on wiresharck i see tlsv1. I have the impression that the command is not be understand by duplicati

**Comment by glannes31** [comment]
I can give an acces on my test MAC with teamviewer if you want.

**Comment by mnaiman** [comment]
These are option for parameter, try that or any variation
--allowed-ssl-version=Tls,Tls11,Tls12

**Comment by glannes31** [comment]
i tried all version and i setup this in the default option but i have the same problem. It's possible to have another person with more time ? SSL3 is disabled on our server for security reason.

**Comment by glannes31** [comment]
It's possible to have the application  in use to be debug with a debugger ?

**Comment by glannes31** [comment]
I am very sorry .... I 
try on windows , duplicati 2.0 , and i see tlsV1 .   The difference is that i see a change cipher from the server . On mac i see a failure

[Duplicati_problem_mac.zip](https://github.com/duplicati/duplicati/files/349790/Duplicati_problem_mac.zip)

**Comment by kenkendk** [comment]
The SSL feature should work in the latest canary build (anything released after the April 27th).

**Comment by glannes31** [comment]
@kenkendk  tks for your answer , i precised my issue . Duplicati 2.0 talk with tls v1.0 in all versions .

**Comment by kenkendk** [comment]
What do you get from:
```
mono Duplicati.CommandLine.exe help --allowed-ssl-version```
```

Regards, Kenneth

**Comment by glannes31** [comment]
For your information , client hello is not the same between mac and windows . 
I have 12 for windows and 6 for MAC
![tls](https://cloud.githubusercontent.com/assets/20032648/16619405/34836204-438e-11e6-8c30-70e48a283961.PNG)
![tls_mac](https://cloud.githubusercontent.com/assets/20032648/16619408/370b453c-438e-11e6-8f88-7908f28e7ec0.PNG)

Command line not work on mac.

**Comment by kenkendk** [comment]
The commandline works fine on Mac, I use it all the time.

It is possible that OSX supports the protocol, but the Mono version does not. 
The command I listed will output what values Mono reports as available.

Due to the .Net implementation, it might choose another version than what you want if it has multiple options. Hence, you need to know what choices you have, and select only the right one.

You can try to set the advanced option "allowed-ssl-version" in the GUI, and then see what choices you have there.

**Comment by glannes31** [comment]
@kenkendk i tried all possibilities and it's not working . I use wiresharck to analyse the packet and i see that Client Hello is not the same. I have not all TLS_ 

I am not a mac user . I write the command line on bash directlly but it's returned that no shuch file or directory . the command mono only say me it's missing an argument

**Comment by glannes31** [comment]
@kenkendk @mnaiman  could you explain me why i havent not all TLS

**Comment by kenkendk** [comment]
If you get `topic not found` you are using an older version of Duplicati without TLS setting support.
You can get the latest build here:
https://github.com/duplicati/duplicati/releases

**Comment by glannes31** [comment]
@kenkendk  Hello , I have the last version .  I reinstalled it . And i have the same message .
<img width="574" alt="capture d ecran 2016-07-07 a 08 37 05" src="https://cloud.githubusercontent.com/assets/20032648/16644567/42676218-441e-11e6-92a6-d4e67c8bffb0.png">

**Comment by glannes31** [comment]
Using Finder , i have no problem to connect. In WIreshark , i see a correct client Hello in TLSV1.2 . It's strange because in duplicati i can choose allowed ssl version but it's have no impact.  I can let you try with teamviewer on my mac

**Comment by glannes31** [comment]
@kenkendk  The command line miss an "s" on version . But it's not explain why doesnt work on MAC...

**Comment by glannes31** [comment]
I choose allowed ssl version TLS 1 2 on windows Duplicati .  I see on WIresharck TLSV1.2 . Why , on Mac Duplicati, the change is not OK ?  It's very important to me to solve the problem  because it's a very use application here.

**Comment by glannes31** [comment]
How the cipher suite is choosen by Duplicati ?

**Comment by mnaiman** [comment]
I found out this, may be it will be helpful https://bugzilla.xamarin.com/show_bug.cgi?id=18222

**Comment by mnaiman** [comment]
@glannes31  Try to compile and test this https://github.com/mono/mono/blob/master/mcs/class/Mono.Security/Test/tools/tlstest/tlstest.cs
@kenkendk On Mono (Linux&Mac) there is different namespace that on Windows - Mono.Security.Protocol.Tls.SecurityProtocolType, may be this could be the problem

**Comment by glannes31** [comment]
@mnaiman Tks but how i can compile this in Mac ?

**Comment by mnaiman** [comment]
Try that guide http://stackoverflow.com/questions/29688436/how-to-compile-single-c-sharp-file-on-mac-console-using-mono
I dont have Mac, only Windows

**Comment by glannes31** [comment]
I compile this and return namespace Protocol doesnt not exist

**Comment by mnaiman** [comment]
There is makefile https://github.com/mono/mono/tree/master/mcs/class/Mono.Security/Test/tools/tlstest

**Comment by glannes31** [comment]
@mnaiman  It's return the same error in my first message . Fail with all arguments possible --any, tls1 , sslv3 .

**Comment by glannes31** [comment]
@mnaiman  @kenkendk For us , it's impossible to add TLS_RSA cypher suite because it's out to date for security. How add up to date cypher suite in the Client Hello ?

**Comment by glannes31** [comment]
For your information , i have open an issue on bugzilla https://bugzilla.xamarin.com/show_bug.cgi?id=42399 . Tks for your cooperation with Mono dev

**Comment by mnaiman** [comment]
This explains why this is not Duplicati, but Mono problem: http://tirania.org/blog//archive/2015/Aug.html

**Comment by mnaiman** [comment]
Fix is already in Mono 4.6, which is not ready for production use.

**Comment by glannes31** [comment]
@mnaiman Okay .... I prepare a communication for our mac users . Tks for your answer. On bugzilla, they said it's possible to switch on Apple Tls

**Comment by glannes31** [comment]
I close this issue . Tks for all and i waiting your further version .
