### ISSUE TITLE
2.0.1.11: FTP Backup frequently fails with code 550

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1839]
Hi!

I am using a Synology DSM 6.0 as backup target. Since it has severe performance issues with SMB-Shares, I created an FTP backup job. Transfer speed is away better but the backup itself frequently fails with the following stack dump:

System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (550) Datei nicht verfügbar (z.B. nicht gefunden oder kein Zugriff). bei Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes) bei Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend) bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter) bei Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result) bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) bei Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

Repairing the local DB and repeating the job works once. A second run fails. Is there anything I can try to pinpoint this issue?

EDIT: I tested again: 
0) FTP Destination
1) Repair database
2) Backup works
3) Another backup fails
4) Change Destination to SMB-Share (same storage location, but accessed via SMB)
5) Backup works.

Stefan
##

**Comment by ts678** [comment]
Is there anything I can try to pinpoint this issue?

Code 550 is pretty vague -- ` Requested action not taken.
             File unavailable (e.g., file not found, no access).`

Does it still happen on current Synology? The error code is from them, but it was Duplicati's request.

`Der Remoteserver hat einen Fehler zurückgegeben` is `The remote server returned an error`

For error using Duplicati's [FTP](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#ftp), one can now also test [FTP (Alternative)](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#ftp-alternative), which is a different FTP client.

[Duplicati.CommandLine.BackendTester.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlinebackendtesterexe) could be tried to see if the erratic behavior can be forced.
