### ISSUE TITLE
when users want to delete file, how to show file name?  

### ISSUE THREAD

**Issue by bing8** [duplicati/duplicati#1841]
##

**Comment by agrajaghh** [comment]
can you explain your issue a bit more detailed please?

**Comment by bing8** [comment]
I have some files, I  want to delete some of them which are  unwanted . how to select files ,show the file name and complete delete anction . could  u help me .

**Comment by umgfoin** [comment]
> I have some files

IMHO, a comprehensive explanation looks different...

If your aim is to remove single files from a backup-snapshot: 
You can't and you don't want.

**Comment by bing8** [comment]
Thank you  for your help , umgfoin! 
if the file passed the expiration date, duplicati will to delete file , I need to show the file names for those had been deleted.

**Comment by kenkendk** [comment]
There is nothing in the user interface that will do this.
You can do the delete on the commandline and add the `--dry-run` option to have it show what it will do.
But I think you want it to show something like:
```
After deleting fileset "nnn", the following files will no longer be available in any version:
  file1.txt
  file2.abc
  ...
```

There is nothing that gives this functionality right now.
