### ISSUE TITLE
1.3.4 on Windows 10 showing a 404 when trying to backup to Google Drive

### ISSUE THREAD

**Issue by mostlybob** [duplicati/duplicati#1842]
When I try to set up a job to backup to a folder in Google Drive, I get an error:

Connection Failed: Execution of authentication request returned unexpected result: 404

I gather from [this thread](https://github.com/duplicati/duplicati/issues/1753?_pjax=%23js-repo-pjax-container) that 1.3.x is no longer being supported, but it's the version that the website lists as the latest stable. I'm not opposed to using the RC, but is there any indication of how stable/reliable it is? I know that's a loaded question, being a RC, but if you have any thoughts, I'm interested to hear them.

Thanks for all the great work!

**Comment by kenkendk** [comment]
It is hard to measure stability, but there are a few thousand backups running each day with Duplicati 2.0:
https://usage-reporter.duplicati.com

If you look at the number of open issues, I'd say it is fairly stable, but of course not everybody reports problems.

As for the website, we are moving to a new website asap, but we keep getting delayed for various reasons:
http://duplicati.github.io

We were planning for a beta release a month ago, but then I got hit work a ton of work, and I have not picked up on that again.

**Comment by mostlybob** [comment]
Thanks for the quick feedback, Ken. I hear you about the work :-)

I got a download of a .zip off the repo page and set it up. I have a couple of questions about the scheduling yet, but if I get ambitious, I might crack open the source and see what I can suss out myself. It looks good so far, but I am wondering what the rationale was for moving from a standard desktop app to a locally hosted web service. I suppose it does mitigate cross-platform UI development. 

Again, thanks for a great project.
