### ISSUE TITLE
Need to take another full backup, or remove the last incremental.

### ISSUE THREAD

**Issue by nameanyone** [duplicati/duplicati#1846]
I accidentally added a large number of files that don't belong in a directory that I backup regularly. I then took a backup. I've since moved the files elsewhere. I'd like to take a full backup, or, maybe, delete the last incremental and make another incremental. Any suggestions?

**Comment by kenkendk** [comment]
If this is for 1.3.x. you can make a new full backup, and then delete the older ones.

For 2.0, you need to delete all versions that contains the unwanted files, and then perform a compact function to free up the space.

There is currently no UI features to delete versions, so you need to use the commandline with something like:

```
Duplicati.CommandLine.exe delete backend://remote/path --version=4,5,6
```
