### ISSUE TITLE
Decentralized Backups via Sia ? 

### ISSUE THREAD

**Issue by ghost** [duplicati/duplicati#1848]
Any chance to add support for Sia? It's a decentralized backup system (which I think is quite cool) :-)

See http://sia.tech/

https://github.com/NebulousLabs/Sia/tree/master/doc
##

**Comment by golere** [comment]
I'm also interested in this. Any news?

**Comment by kenkendk** [comment]
No updates, but it looks simple enough:
https://github.com/NebulousLabs/Sia/blob/master/doc/API.md

**Comment by etrigan63** [comment]
I too am interested in this.

**Comment by Ajedi32** [comment]
Seems like this exists now: https://github.com/duplicati/duplicati/pull/2677

**Comment by warwickmm** [comment]
Sia should be supported now.
