### ISSUE TITLE
UNIQUE file constraint failed

### ISSUE THREAD

**Issue by advpk** [duplicati/duplicati#1855]
Running backup to webdav (or SFTP) gives a huge number of UNIQUE constraint failed errors:

```
Messages: [No remote filesets were deleted, removing file listed as Temporary: duplicati-bfd56a87dd27f4a4e97b85d43c69fd76c.dblock.zip.aes, removing file listed as Temporary: duplicati-ic25865f02411498aa71c3d347e5e75c4.dindex.zip.aes]

UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process path: B:\xxxxxxx_app_owncloud\68B822EF-0BEE-4489-8A82-5565814396DE\files_trashbin\files\directx_Jun2010redist.exe.d1460986436 => constraint failed

UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process path: B:\xxxxxxx_app_owncloud\68B822EF-0BEE-4489-8A82-5565814396DE\files_trashbin\files\Multipage_2016-06-07_165826.pdf.d1467194534 => constraint failed
```

In total 205 error messages like these
These occurred on initial backup as well as on following incremental backups
Delete/Repair db does does not change anything
##

**Comment by agrajaghh** [comment]
what version are you running?

**Comment by advpk** [comment]
sorry, forgot to mention: 2.0.1.17_canary_2016-05-14 on Win2012R2

**Comment by advpk** [comment]
Is there any hints how we could investigate on our side to provide more helpful details?

**Comment by tedbeer** [comment]
I'm running 2.0.1.17_canary_2016-05-14 on x64 Windows 8.1
I have specified constraint - --skip-files-larger-than="100MB"
In logs it generates a message for each file to be ignored (>100Mb):
```
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
```
It's maybe related to the issue starter message.

**Comment by advpk** [comment]
Yes, I was also using the --skip-files-larger-than option here, so I guess its related to this
If a file is skipped due to this parameter, it should be info(?) in log, but neither warning nor error

**Comment by batal1** [comment]
I've got the same issue : it appears on "big" files (larger than 50MB). I'm also using the --skip-files-larger-than="100MB" constraint ...
Windows 7 x64, Duplicati version: 2.0.1.18_canary_2016-08-10
