### ISSUE TITLE
Upload phase says "waiting for upload" for hours

### ISSUE THREAD

**Issue by bencarlos** [duplicati/duplicati#1857]
First I want to say thank you for this new Duplicati version. I adore the idea of a backup SERVICE!
So I went and started a 50GB backup over SSH and everything went well.

First I thought the GB numbers dropping down after initializing ment that it's already transfering, although I couldn't see any action on the wifi adapter. I thought that's beacuse of the loopback...

Anyhow, I then figured out that it started a single zip file under /appdata/local/temp at about 40GB in the end. After that it uploads it. However, now I see the bar saying "waiting for upload ..." while actually uploading (aprox. 15MBit/s). I don't know how long it'll take or something like that. So far the process began at about 2pm, now it's 11 and it's still not done.

Compared to Duplicati 1.3.4 it's finally over the 2MBit/s mark.

So, is the progress bar a known issue?
Does it have to store a plain zip file in the /temp folder? That would mean that the hard drive needs to have at least the amount of to be backuped data as free space to backup?

![unbenannt](https://cloud.githubusercontent.com/assets/20499627/16899747/910d19a0-4c0f-11e6-9fda-fec90d235edd.JPG)

**Comment by agrajaghh** [comment]
> Anyhow, I then figured out that it started a single zip file under /appdata/local/temp at about 40GB in the end.

what did you specify for "Max backup file size"?

**Comment by bencarlos** [comment]
> what did you specify for "Max backup file size"?

I set it to 100GB!

**Comment by agrajaghh** [comment]
that is way too high. Try setting it to something around 200MB...

**Comment by bencarlos** [comment]
Oh, alright! I'll try that!
Can you explain why?

**Comment by agrajaghh** [comment]
the *max backup file size* is the size of the encrypted zip archives. With a max size of 100GB you were zipping and encrypting all of your files in one archive. With a size of 200MB the backup is split up in several files with 200MB, so you don't need such a big temp folder, and stopping/resuming the backup should be faster as well.

It should also help with the progress bar issue I think. Please let us know if its fixed for you with a smaller size

**Comment by bencarlos** [comment]
So I set the size to 100MB and the zips are now splittet into 100mb pieces!
The behavior is strange I think: it says " ... xxx files to go" and stuff during the creation of those zips in that temp folder and also copying those to the destination. After that it says completing backup while still copying zips and also during "waiting for upload" phase. However, in the end I can see a last succesful run! I must say that Allwaysync works better for me though! I'll walk by another time and do some testing and let you guys know!
