### ISSUE TITLE
Application is not codesigned

### ISSUE THREAD

**Issue by renep** [duplicati/duplicati#1858]
Neither Duplicati 1.3.4 nor 2.0 prereleas is codesigned therefor you get the following error message when try to open the app:
“Duplicati.app” can’t be opened because it is from an unidentified developer.

Codesigning the app is not that hard, and the $ 99 you have to pay to Apple should not be a reason not to.

**Comment by mnaiman** [comment]
Really this is not huge issue. Devs are working on app in free time, its hard to ask them to pay money to whatever company for ability to deliver great free app to us.
There is donate button, I think you could do specific donation to cover yearly certificate fee.

**Comment by kenkendk** [comment]
I have recently purchased a codesigning certificate to sign the MSI installers, and I plan to do the same with the dmg/pkg files.

**Comment by kenkendk** [comment]
This is now implemented and will be part of the next build:
a3f8f875b0cfa82700a9eb94110f7c13e1342835
