### ISSUE TITLE
Hubic auth stability

### ISSUE THREAD

**Issue by remydev** [duplicati/duplicati#1861]
Hello,

I use diplicati with Hubic.
When creating a backup, I checked the connection, everything is ok.
Data is downloaded Hubic.
So I think everything is good but sometimes I have a 401 error code.
I made a new test, the connection is ko.
I have to generate a new auth id

Maybe the key is no longer valid, but not possible to know this information is not on my account Hubic

Thanks

**Comment by remydev** [comment]
This is a hubic problem
sorry

**Comment by mneiger** [comment]
Hi,
I understand this is a Hubic issue, but can you provide some information about the solution or progress you made? you can reply privately at marc@neiger.org

Thanks

**Comment by remydev** [comment]
Sorry, I juste stop use hubic, i had got some corrupted data with this cloud!
To dangerous for backup
