### ISSUE TITLE
Missing Hidden Folders

### ISSUE THREAD

**Issue by patrickhousley** [duplicati/duplicati#1862]
I have "Show hidden folders" checked but none of them are showing up under my user profile.

<img width="721" alt="screen shot 2016-07-24 at 09 56 36" src="https://cloud.githubusercontent.com/assets/3984979/17084507/04e522c6-5185-11e6-9132-da44ab256a69.png">
##

**Comment by agrajaghh** [comment]
@patrickhousley @marceldev89 can you still reproduce this with the latest version?

**Comment by marceldev89** [comment]
@agrajaghh with 2.0.1.22_experimental_2016-09-12 the issue is still present haven't tested the canary builds. Dot folders are shown but hidden folders aren't. I'm using Windows 10.

**Comment by agrajaghh** [comment]
oh, I just tried the destination folder picker (there its showing hidden files), but the source folder picker isn't showing them!

**Comment by marceldev89** [comment]
Thank you 😃
