### ISSUE TITLE
1.3.4 started crashing on Windows 8.1 x64

### ISSUE THREAD

**Issue by fafikulus** [duplicati/duplicati#1863]
Hello. In the recent days Duplicati ceased to work on my Windows 8.1 64-bit. I suspect something to do with recent Windows updates.
When I try to run Duplicati.exe I get:

Description:
  Stopped working

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Duplicati.exe
  Application Version:	1.3.4.0
  Application Timestamp:	510a74e3
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.18340
  Fault Module Timestamp:	57366075
  Exception Code:	e0434f4d
  Exception Offset:	0000000000008a5c
  OS Version:	6.3.9600.2.0.0.256.72
  Locale ID:	1031

Please help as I cannot access my backup and can't make new backups.

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
