### ISSUE TITLE
S3 bucket getting zipped files

### ISSUE THREAD

**Issue by NareshDealer** [duplicati/duplicati#1868]
Hi,
Your software is really great piece.

The only issue i have is currently when the backup starts, it creates zip files and puts them into the bucket.
However if i need to just grab a single file from the bucket then i need to download whole zip file and extract to find that file. Currently i have a script which is scheduled to run and just copy all files into s3 bucket.

Is there any way where i can just copy all the files as it is without any compressing(zip). This will help me to get rid of my scheduled task with script.

Thanks.

**Comment by agrajaghh** [comment]
what version are you running? 1.3 is not suported / in development anymore. Duplicati 2 is using a block-based backup mechanism.

> However if i need to just grab a single file from the bucket then i need to download whole zip file and extract to find that file
This is impossible with 2.0

you can read more about the backup mechanism here: 
http://www.duplicati.com/news/theduplicati20storageengineishere
