### ISSUE TITLE
tempdir not respected

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1870]
I am using 2.0.1.11_experimental_2016-04-08 and specified a tempdir variable in duplicati's general settings: D:\temp

I know that sqlite doesn't use this, but I'd expect all the zip-files that Duplicati creates to be created there. Instead, they are still produced in %TEMP%.
##

**Comment by kenkendk** [comment]
I think this is related to the general settings not being propagated to each backup.
If you set the tmpdir on the individual backup it should work.
Can you confirm that the problem is only with general settings?

**Comment by mr-flibble** [comment]
I can confirm that - problem is witch general setting only. If i set tmpdir for individual backup, everything is OK as expected.

**Comment by huste** [comment]
Yes, I can confirm that, too.

**Comment by ts678** [comment]
Is this still reproducible? I've tested as far back as 2.0.2.1_beta_2017-08-01, and Settings `Default options` --tempdir successfully moved the `dup-*` files for the backup to the specified location. I could not find a claimed fix in the records, but it seems OK now...

**Comment by huste** [comment]
No, it works with a newly created backup job and a specifically set tempdir in the general options with 2.0.5.111. I'll close it now
