### ISSUE TITLE
Does Duplicati have a server version, if yes how can I install it on Debian 8?

### ISSUE THREAD

**Issue by AchuM** [duplicati/duplicati#1871]
Hello, 
I would like to use Duplicati for my backup solution and I was wondering if Duplicati has a server version. In general, would be interested in using on both sides, from client and server sides. 

Thanks

**Comment by kenkendk** [comment]
Duplicati is "client side only" in that it does not have a server component, but instead relies on standard protocols (SSH, WEBDAV, etc) to connect to the server.

But you can run Duplicati from the commandline without any GUI if you like.
