### ISSUE TITLE
duplicati cmd restore sub folder

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#1873]
D drive is a scheduled backup. How to restore a sub folder example D:\folder1\folder2\*

Duplicati.comandline.exe restore backend  D:\folder1\folder2\* --restore-path=c:/restore

Will this command work

**Comment by kenkendk** [comment]
Yes, but you might want to use double quotes to ensure that the shell does not expand the asterisks:
```
Duplicati.comandline.exe restore "backend" "D:\folder1\folder2*" --restore-path="c:\restore"
```
