### ISSUE TITLE
Unknown header: 566000939

### ISSUE THREAD

**Issue by egoitzau** [duplicati/duplicati#1877]
Good morning mates,

I'm running a Canary version and suffering issues like the following one after reconstructing local database and running repair and so. Have too checked backup files with the existing possibility. The error is always a "Unkown header" when trying to run a backup but with different codes like 1638055059.

I receive first a : 
# 

System.Exception: Found 1 files that are missing from the remote storage, please run repair
   en Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   en Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)
   en Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   en Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   en Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
#    en Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter

Later I regenerate local database and verify backup files.... launch a new backup job and seems to do... but :
# 

And ends with : 

System.NotSupportedException: Unknown header: 1638055059
   en SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader)
   en SharpCompress.Common.Zip.SeekableZipHeaderFactory.<ReadSeekableHeader>c__Iterator0.MoveNext()
   en SharpCompress.Archive.Zip.ZipArchive.<LoadEntries>c__Iterator0.MoveNext()
   en SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()
   en Duplicati.Library.Compression.FileArchiveZip.GetEntry(String file)
   en Duplicati.Library.Compression.FileArchiveZip.OpenRead(String file)
   en Duplicati.Library.Main.Volumes.VolumeReaderBase..ctor(ICompression compression, Options options)
   en Duplicati.Library.Main.Volumes.VolumeReaderBase..ctor(String compressor, String file, Options options)
   en Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   en Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)
   en Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   en Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   en Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   en Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   en Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
#    en Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

OR
# 

System.NotSupportedException: Unknown header: 1638055059
   en SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader)
   en SharpCompress.Common.Zip.SeekableZipHeaderFactory.<ReadSeekableHeader>c__Iterator0.MoveNext()
   en SharpCompress.Archive.Zip.ZipArchive.<LoadEntries>c__Iterator0.MoveNext()
   en SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()
   en Duplicati.Library.Compression.FileArchiveZip.GetEntry(String file)
   en Duplicati.Library.Compression.FileArchiveZip.OpenRead(String file)
   en Duplicati.Library.Main.Volumes.VolumeReaderBase..ctor(ICompression compression, Options options)
   en Duplicati.Library.Main.Volumes.VolumeReaderBase..ctor(String compressor, String file, Options options)
   en Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)
   en Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)
   en Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   en Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   en Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   en Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   en Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
#    en Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

I have to say once I had the space totally full and the backup couldn't end....

What could be happening here?. Does exist a way to solve it and avoid starting from zero?.

Best regards,
##

**Comment by kenkendk** [comment]
Can you create a bug-report from the UI or the commandline?

The error message "invalid header" seems to indicate that the zip file is corrupt.

**Comment by teoxrr** [comment]
here's my log running on ```2.0.1.11- 2.0.1.11_experimental_2016-04-08: ```

{"ClassName":"System.NotSupportedException","Message":"Unknown header: 3508805749","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   in SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader)\r\n   in SharpCompress.Common.Zip.SeekableZipHeaderFactory.<ReadSeekableHeader>c__Iterator0.MoveNext()\r\n   in SharpCompress.Archive.Zip.ZipArchive.<LoadEntries>c__Iterator0.MoveNext()\r\n   in SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()\r\n   in Duplicati.Library.Compression.FileArchiveZip.GetEntry(String file)\r\n   in Duplicati.Library.Compression.FileArchiveZip.OpenRead(String file)\r\n   in Duplicati.Library.Main.Volumes.VolumeReaderBase..ctor(ICompression compression, Options options)\r\n   in Duplicati.Library.Main.Volumes.VolumeReaderBase..ctor(String compressor, String file, Options options)\r\n   in Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)\r\n   in Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)\r\n   in Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)\r\n   in Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)\r\n   in Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)\r\n   in Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   in Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   in Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nReadHeader\nSharpCompress, Version=0.11.3.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b\nSharpCompress.Common.Zip.ZipHeaderFactory\nSharpCompress.Common.Zip.Headers.ZipHeader ReadHeader(UInt32, System.IO.BinaryReader)","HResult":-2146233067,"Source":"SharpCompress","WatsonBuckets":null}

**Comment by kenkendk** [comment]
I need a "bug-report" which is a zip file that can be created from the UI, under the item "Create bug report" or with the commandline option `create-report`.

**Comment by teoxrr** [comment]
ok, but it seems a 1GB file....
maybe I give you a wetransfer link, ok?

2016-09-05 10:51 GMT+02:00 Kenneth Skovhede <notifications@github.com>:

**Comment by kenkendk** [comment]
@teoxrr, I just realized that this could be a deeper problem.

Is it possible for you to reproduce this problem?

If so, can you run with the option `--verbose` and see what file is broken?
And can you share a broken file with me for diagnostics?

**Comment by kenkendk** [comment]
Also, I just pushed out a new canary (2.0.1.50) today, which has an updated zip library. With a little luck, the file is intact by the zip reader has a bug.

**Comment by kenkendk** [comment]
@teoxrr : I have reproduced a similar issue with files larger than 4GiB. Do you recall if your files are larger than 4GiB?

**Comment by teoxrr** [comment]
Yes, larger than 4GB

2017-03-13 11:12 GMT+01:00 Kenneth Skovhede <notifications@github.com>:

**Comment by kenkendk** [comment]
Great, then this is fixed with 360a90b2ce7f0523e1b51608ebdac8e87151fcbf
