### ISSUE TITLE
Backup to S3 : several UI things when recalling a previous configuration

### ISSUE THREAD

**Issue by pc-explore** [duplicati/duplicati#1879]
A. When I edit a previously saved configuration for a S3 backup scheme, there are several things which are not displayed correctly in the UI :
- the Storage type is automatically set to 'Local folder or drive'
- the bucket name is prepended to the folder path
- the checkbox 'Use SSL' is not selected anymore

B. When you click on 'test connection', there is a popup 'Adjust bucket name ? The bucket name should start with your username, prepend automatically ?'
But it does not work when the bucketname starts with the username. It will only work when the bucket name does not start with the username.
##

**Comment by pc-explore** [comment]
If a live demo is required, just let me know. I can easily reproduce the issue.
Kind regards,
Danny

**Comment by Vaporizer8** [comment]
The first three issues should be fixed with #1852. Though you'll probably have to wait for a new public build or build from source yourself.

**Comment by pc-explore** [comment]
Indeed, 2.0.1.18_canary_2016-08-10 does solve the first 3 issues. Many thanx.
