### ISSUE TITLE
Scheduled bandwidth management

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#188]
_From [freaky2000@gmail.com](https://code.google.com/u/freaky2000@gmail.com/) on March 19, 2010 10:26:06_

Hi there,

I would like to be able to 'schedule' bandwidth management. Schedule might
be a big word for it. Basically what we would like is the following:

Limit bandwidth (up/down) between 08:00 - 18:00 and give it full bandwidth
the rest of the time.

This would allow for throttling the backup during working hours and giving
it full access to the internet line outside working hour windows. Which
would be awesome :).

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=188_

**Comment by utdrmac** [comment]
Why did this get closed? This would be a great option! If I upload at full speed, my inbound internet suffers (pages load slow, downloads crawl, etc). Would be nice to tell duplicati "run full speed between 1am and 8am; run 20K/sec between 8:01am and 11pm"

**Comment by utdrmac** [comment]
ah. duplicate of #611
