### ISSUE TITLE
[UI-2.0.1.18_canary_2016-08-10] Cannot expand file path  

### ISSUE THREAD

**Issue by benchen100** [duplicati/duplicati#1880]
I cannot expand the folders path when creating a backup, the virsion is the latest (2.0.1.18_canary_2016-08-10) and the system is Windows Server 2012R2, is there any suggestion? thanks a lot.
![cannot expand](https://cloud.githubusercontent.com/assets/20393349/17582992/507759ce-5fe1-11e6-9925-cd532e643a27.PNG)

**Comment by kenkendk** [comment]
Hi @benchen100 do you see any error messages?

If you use IE then press F11 to see the developer console, on chrome press ctrl+shift+i.

**Comment by f0xxxxxy** [comment]
Same issue for me with 2.0.1.18. Rolled back to .17 and it works again. Tried in IE/FireFox/Chrome/Safari and all the same. No errors reported in console. 'Computer' expands fine, but you cannot expand drives etc.

**Comment by huste** [comment]
I can confirm this problem on Win10 x64 with 2.0.1.18_canary_2016-08-10.
No errors in the developer console in MS Edge. Doesn't work in Firefox neither.

**Comment by benchen100** [comment]
Hi @kenkendk, I opend the google developer console but not seeing any error messages when expanding the folder. I rooled back to .17 and used the same configuration and it works.
![no error log](https://cloud.githubusercontent.com/assets/20393349/17657049/c9f91d46-62f2-11e6-8d34-4bcc8b350d1e.PNG)

**Comment by MrPozor** [comment]
Same here on Win7 x64 and Win10 x64.

**Comment by kenkendk** [comment]
This was likely the same as in #1888 which has been fixed in 2.0.1.19.
