### ISSUE TITLE
Very slow restore speed

### ISSUE THREAD

**Issue by oliwiak82** [duplicati/duplicati#1881]
Hello,
I have to restore 500GB of data done by duplicati 2.0.1.17_canary_2016-05-14. The restore is very slow, avg speed is 450KB/s. Backup is done via SFTP (SSH). I am able to download raw encrypted backup file with the speed of 3MB/s so I am sure that my bandwidth pipe is not a bottle neck. CPU on both server and client is very low so this is also not a case. I restore to SSD drive. Why there is so slow restore performance? Anyone had similar experience ?
![firefox_2016-08-11_12-51-55](https://cloud.githubusercontent.com/assets/20964738/17586506/78cac9a2-5fc2-11e6-9d23-e500f530e4cf.png)

![firefox_2016-08-11_12-48-31](https://cloud.githubusercontent.com/assets/20964738/17586431/08d18a46-5fc2-11e6-983a-8188f07f537a.png)
##

**Comment by jarmo** [comment]
It might be related to https://github.com/duplicati/duplicati/issues/1391

**Comment by warwickmm** [comment]
Pull request #4297 should greatly improve restore performance.  If this is still an issue, please feel free to reopen and provide more details.
