### ISSUE TITLE
duplicati-2.0.1.18_canary_2016-08-10-x64 cant't find SharpAESCrypt Version 1.3.0.0

### ISSUE THREAD

**Issue by gemanio** [duplicati/duplicati#1887]
### Version info
**Duplicati Version:** 2.0.1.18_canary_20160810
**Operating System:**Windows 10 x64
**Backend:**

### Bug description
duplicati-2.0.1.18_canary_2016-08-10-x64 cant't find SharpAESCrypt Version 1.3.0.0

### Steps to reproduce
- trying to run a backup inmediatly appears the error message 
- that reproduce the bug

### Screenshots
![duplicatierror](https://cloud.githubusercontent.com/assets/20989942/17621381/430e2e60-6069-11e6-9db6-8fd65b37b37f.png)

**Comment by huste** [comment]
can't reproduce. I am also on  2.0.1.18_canary_2016-08-10 on Win10 x64 and I have two backups with AES256 builtin encryption enabled.

**Comment by kenkendk** [comment]
Was this an upgrade or running directly from installer/zip ?

**Comment by vradmilovic** [comment]
FWIW, I have identical problem, Win10 x64. Tried with both, upgrade and the installer.

**Comment by mnaiman** [comment]
Do you have installed .NET framework 2.0?

**Comment by gemanio** [comment]
I Updated from 2.0.1.17.
Well, after manually running SharpAESCrypt.exe from C:\Program Files\Duplicati 2, the error didn't appear anymore. Does it makes sense?

**Comment by kenkendk** [comment]
Even though SharpAESCrypt.exe is built agains .Net 2.0, it should load just fine with .Net 4.5.

@vradmilovic: Did you try running the executable manually as suggested by @gemanio ?

**Comment by mnaiman** [comment]
@kenkendk On newer system, .NET 2.0 is not installed by default. but .NET4.5 is. So without manual installation of .NET 2.0 it is not working.
Another possible solution is to include sharpaes.exe.config with content

```
<?xml version="1.0" encoding="utf-8"?>
<configuration><startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6"/></startup></configuration>
```
