### ISSUE TITLE
2.0.1.18 doesn't see any files

### ISSUE THREAD

**Issue by nameanyone** [duplicati/duplicati#1888]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.18
**Operating System:** Windows 7 64bit
**Backend:** huh?

### Bug description
Describe here the issue that you are experiencing.
Duplicati does not see any source files. In web interface, when I click the triangle to expand a drive, there is nothing under it. Backups execute without error, but nothing is written. Command line test says "0 files need to be examined". Command line backup says something similar, I did not capture it before uninstalling. Something like "no files were processed, is that intentional?"

### Steps to reproduce
- install duplicati-2.0.1.18_canary_2016-08-10-x64.msi
- try backing up anything

**Actual result:** the destination is empty
**Expected result:** backup files are there

### debug log

I did not capture it, but I looked at it and there were no errors. It was happily reporting 0 source files.

**Comment by nameanyone** [comment]
Also, if an update was previously downloaded, version 2.0.1.17 msi silently and automatically updates the program to 2.0.1.18. Took me a few times to uninstall/reinstall, before it occurred to me to hunt down and delete anything "duplicati" on C:.

**Comment by zpiman** [comment]
Having same issue!

**Comment by Mynyx** [comment]
Same issue on Windows 10 with new installation of 2.0.1.18_canary_2016-08-10.

**Comment by mrsarge** [comment]
Same issue on Windows 7 x64 with 2.0.1.18_canary_2016-08-10.

Tested on two computer.  With an update from 2.0.1.17 and with a clean installation.

**Comment by ovizii** [comment]
I can confirm, running Win 10 Enterprise and  2.0.1.18_canary_2016-08-10. Also updated from 2.0.1.17

**Comment by jrlambs** [comment]
Any way to install 2.0.1.17 and keep it from updating to .18? I'd love to try this program out but don't really want to wait for a fix :)

**Comment by nameanyone** [comment]
> Any way to install 2.0.1.17 and keep it from updating to .18?

@jrlambs, if you haven't figured it out yet, see https://github.com/duplicati/duplicati/issues/1891#issuecomment-239677781

**Comment by huste** [comment]
Same here. I upgraded Duplicati by unzipping it over the existing installation (same procedure as every time before)

**Comment by kaasszje** [comment]
Having same problem.
All files in the backup are deleted in the count.
0 files in backup.

Mails say all files deleted from backup:
DeletedFiles: 18479
DeletedFolders: 295
ModifiedFiles: 0
ExaminedFiles: 0
OpenedFiles: 0
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 0
SizeOfOpenedFiles: 0
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
VerboseOutput: False
VerboseErrors: False
Messages: [Deleting 1 remote fileset(s) ..., Deleted 1 remote fileset(s), Compacting not required]
Warnings: []
Errors: []

Looks like it doesn't see the files on my computer.

**Comment by huste** [comment]
Works again in 2.0.1.19 canary. Thanks Kenneth!

**Comment by kaasszje** [comment]
Same for me :)

Op 28 aug. 2016 09:35 schreef "huste" <notifications@github.com>:

**Comment by agrajaghh** [comment]
thanks for reporting back
