### ISSUE TITLE
Backblaze B2 domain migration

### ISSUE THREAD

**Issue by SebiH** [duplicati/duplicati#1889]
### Version info
**Duplicati Version:** 2.0.1.18_canary
**Operating System:** Irrelevant
**Backend:** Backblaze B2

### ~~Bug~~ description
Backblaze has migrated their domains from ``api​.​backblaze​.​com`` to ``api​.​backblazeb2​.​com``. The transition period ends on 2017/02/17. More information in [their blogpost][1].

Can't test B2 at the moment, but it's probably best if you're aware of this change.

[1]:https://help.backblaze.com/hc/en-us/articles/224959187-B2-Domain-Migration-Plan

**Comment by kenkendk** [comment]
Thanks for reporting!
