### ISSUE TITLE
Usagereporter crashing with System.InvalidOperationException

### ISSUE THREAD

**Issue by Andrey-dc** [duplicati/duplicati#1894]
Duplicati stopped working today on my system for some reason. I am running duplicati-2.0.1.11_experimental_2016-04-08 on Win7 machine. I've tried downloading same build from github again, in case my was corrupted, as well as latest canary build duplicati-2.0.1.18_canary_2016-08-10. It reports similar errors.
Other thing i've tried is to delete %appdata%/duplicati . In case database or some configs were corrupted. No effect either.
Is there any other place where duplicati might store some essential data i haven't cleaned?

Here is the error i'm getting in about 2 minutes after launching Duplicati.GUI.TrayIcon.exe (i have russian locale, sorry for some probably unfamiliar characters) :

  Имя события проблемы:   CLR20r3
  Сигнатура проблемы 01:   Duplicati.GUI.TrayIcon.exe
  Сигнатура проблемы 02:   2.0.0.87
  Сигнатура проблемы 03:   0
  Сигнатура проблемы 04:   mscorlib
  Сигнатура проблемы 05:   4.6.1076.0
  Сигнатура проблемы 06:   56d79d90
  Сигнатура проблемы 07:   3f5a
  Сигнатура проблемы 08:   18
  Сигнатура проблемы 09:   System.InvalidOperationException
  Версия ОС:    6.1.7601.2.1.0.256.48
  Код языка:    1049
  Дополнительные сведения 1:  8688
  Дополнительные сведения 2:  8688fd3eb4f3f21405eaef802ff70783
  Дополнительные сведения 3:  5bb1
  Дополнительные сведения 4:  5bb1cd60dd66c6632036c6eb7e9d1359

And here are two events from Event Logger:

.NET Runtime

Приложение: Duplicati.GUI.TrayIcon.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.InvalidOperationException
   в System.Threading.Tasks.TaskCompletionSource`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(Boolean)
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()

Application Error

Имя сбойного приложения: Duplicati.GUI.TrayIcon.exe, версия: 2.0.0.87, отметка времени: 0x00000000
Имя сбойного модуля: KERNELBASE.dll, версия: 6.1.7601.23418, отметка времени 0x5708a89c
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000001a06d
Идентификатор сбойного процесса: 0xe6c
Время запуска сбойного приложения: 0x01d1f7ca32d27dca
Путь сбойного приложения: C:\Program Files (x86)\Duplicati 2.0 preview\Duplicati.GUI.TrayIcon.exe
Путь сбойного модуля: C:\Windows\system32\KERNELBASE.dll
Код отчета: b8d35242-63bd-11e6-8b58-00e052f537be

Also here is \updates\Duplicati-crashlog.txt content

System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> System.Net.WebException: GetResponse timed out ---> System.Net.WebException: Запрос был прерван: Запрос отменен.
   в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   в Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.OnAsync(IAsyncResult r)
   --- Конец трассировки внутреннего стека исключений ---
   в Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   в Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   в Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequestInternal[T](String method, String endpoint, Dictionary`2 queryparams)
   в Duplicati.GUI.TrayIcon.HttpServerConnection.PerformRequest[T](String method, String urlfragment, Dictionary`2 queryparams)
   в Duplicati.GUI.TrayIcon.HttpServerConnection.UpdateStatus()
   в Duplicati.GUI.TrayIcon.HttpServerConnection..ctor(Uri server, String password, Boolean saltedpassword)
   в Duplicati.GUI.TrayIcon.Program.RealMain(String[] _args)
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(MethodInfo method, String[] args)

Only way i've managed to run Duplicati is to erase updates folder. This way it doesn't crash but my backup database is not compatible with older version, so it's not really a solution.
If there anything else i should try or additional information i can provide, please let me know.
##

**Comment by Andrey-dc** [comment]
I was able to recreate database and successfully restored some files from couple days ago to test it, so my backups are fine. But i still can't use latest duplicati builds.

**Comment by kenkendk** [comment]
I have uploaded a new 2.0.1.19 that fixes a bug in 2.0.1.18 which prevented pretty much everything from working. Could you try the new version?

**Comment by Andrey-dc** [comment]
No luck. The errors are pretty much the same.

![crash](https://cloud.githubusercontent.com/assets/16253156/18127550/c1a4bbc0-6f89-11e6-88a8-92ce3ea04d0a.png)

It seems that latest version i can run on my system without crashing is 2.0.0.91_preview_2015-11-18. At least oldest version form github duplicati-2.0.0.98_preview_2016-01-27 crashing in the same way for me.
Was there some specific change made shortly after 2.0.0.91, that could cause conflicts with something in my system?

**Comment by kenkendk** [comment]
I cannot see anything that I would think causes your crash from .91 to .92.

Do you see extra information in the EventLog?
What version of .Net framework do you have installed?
Also, can you try to start the `Duplicati.TrayIcon.exe` with this environment variable:
`SET AUTOUPDATER_Duplicati_SKIP_UPDATE=1` ?

**Comment by Andrey-dc** [comment]
> Do you see extra information in the EventLog?

These are 2 errors from event log i see every time i run newer versions. It seems that they are no different from the ones in initial post. 
![err1](https://cloud.githubusercontent.com/assets/16253156/18198308/6dee533e-7104-11e6-8005-e305a55eaf9e.jpg)
![err2](https://cloud.githubusercontent.com/assets/16253156/18198367/710bcd26-7104-11e6-8672-85d029fb54db.jpg)

>  What version of .Net framework do you have installed?

Bunch of them. This is list i get when i run [netfx_setupverifier](https://blogs.msdn.microsoft.com/astebner/2008/10/13/net-framework-setup-verification-tool-users-guide/). I was checking installation integrity of .Net frameworks but netfx_setupverifier found no errors.
Install state for .NET Framework 1.0: not installed.
Install state for .NET Framework 1.1: not installed.
Install state for .NET Framework 2.0: installed with service pack 2.
Install state for .NET Framework 3.0: installed with service pack 2.
Install state for .NET Framework 3.5: installed with service pack 1.
Install state for .NET Framework 4 Client: installed with no service packs.
Install state for .NET Framework 4 Full: installed with no service packs.
Install state for .NET Framework 4.5: installed with no service packs.
Install state for .NET Framework 4.5.1: installed with no service packs.
Install state for .NET Framework 4.5.2: installed with no service packs.
Install state for .NET Framework 4.6: installed with no service packs.
Install state for .NET Framework 4.6.1: installed with no service packs.

>  Also, can you try to start the Duplicati.TrayIcon.exe with this environment variable:
SET AUTOUPDATER_Duplicati_SKIP_UPDATE=1 ?

I hope i did it correctly. I've created .cmd file in duplicati's folder containing
```
SET AUTOUPDATER_Duplicati_SKIP_UPDATE=1
Duplicati.GUI.TrayIcon.exe
```
then ran it

I suspect that clean reinstall of my system might help, but if there's any way to avoid it i would rather try that.

**Comment by kenkendk** [comment]
My best guess is that there is some conflict.
It looks like TrayIcon.exe is running with .Net 2.0, due to the `CLR20r3` mention.
The error messages do not really help as they just show that some thread crashes.
The crashlog.txt file just fails to connect to the server (as it has crashed in a thread).

Another thing to try is to disable the usage reporter with:
`set USAGEREPORTER_Duplicati_LEVEL=none`

Can you run the commandline version?
`Duplicati.CommandLine.exe help`

If you can run that, I think there is something other than .Net versions going wrong, perhaps some permission stuff.

**Comment by Andrey-dc** [comment]
First, apologies for not responding for a while, i didn't have access to my computer for 2+ weeks.

I have tried running  `Duplicati.CommandLine.exe help` with newer versions and it crashed in similar way.

But running from a batch with  `set USAGEREPORTER_Duplicati_LEVEL=none` actually worked. I was able to run duplicati-2.0.1.23_canary_2016-09-16 without any problem, then got latest duplicati-2.0.1.23_canary_2016-09-16 and it also running normally.

Hope this helps. If there's any log file i can attach, or try running with different parameters, to help you find cause of this problem please ask.

**Comment by kenkendk** [comment]
There is a chance this will be fixed with 60f3255ddb6a38f5fee5dc382d8f341f572978c5 as I re-wrote the way the usage reporter worked, but I am still not sure what caused the problem in the first place.

**Comment by agrajaghh** [comment]
@Andrey-dc could you please try version 2.0.1.34 from https://github.com/duplicati/duplicati/releases and report back if this fixes your problem? Thanks!

**Comment by Andrey-dc** [comment]
Hello.
Unfortunately it still crashes for me. Here are screenshots from event manager.
![image](https://cloud.githubusercontent.com/assets/16253156/21140819/a7443ca0-c142-11e6-93fc-b7455e72d71d.png)
![image](https://cloud.githubusercontent.com/assets/16253156/21140834/b6d33be4-c142-11e6-8ee1-fe8f6887eaf9.png)

And it's still runs fine with USAGEREPORTER_Duplicati_LEVEL=none. Tried that just in case.

**Comment by rrzaripov** [comment]
Same issue with version 2.0.1.44, same platform version and exception code.

**Comment by jb790419** [comment]
Hi,
I am affected by this bug too. It has to be related to some user setting or environment. For me, duplicati crashes only when run as a service under local system account. USAGEREPORTER_Duplicati_LEVEL=none prevents the crash.

Under my own user it works well even without the USAGEREPORTER environment variable.

I do not use the Duplicati.GUI.TrayIcon.exe but run Duplicati.Server.exe on Windows 10.

**Comment by rrzaripov** [comment]
@jb790419 this is interesting, because when I'm starting Duplicati.GUI.TrayIcon.exe without administrator privileges, exception was not raised. Thanks for your notes!

**Comment by kenkendk** [comment]
Could it be something with the local system account not being allowed to make network connections?

**Comment by matjazpotocnik** [comment]
I have the same problem: I managed to start it by running it as a different user (local administrator account)

**Comment by ts678** [comment]
Is anyone still seeing these? The Issues history shows the CLR20r3 ones went away after around 2017, though admittedly reporting that only shows that in images would evade my text search attempt. I'm also not seeing UsageReporter crashes elsewhere in Issues, and new cases have stopped being reported on this issue. We do ask openers of new issues to search.
