### ISSUE TITLE
amzcd: List after put fail

### ISSUE THREAD

**Issue by mb300sd** [duplicati/duplicati#1897]
When uploading large files, amazon will often return a 408 but actually successfully upload the file. It might be better to list and check if it's there before retrying. I'm using a 5GB dblock size.

Operation Put with file duplicati-b5fbfeb3b4d5d4aaeb740cc14f7eda014.dblock.zip.aes attempt 1 of 5 failed with message: The remote server returned an error: (408) Request Timeout. => The remote server returned an error: (408) Request Timeout.
Renaming "duplicati-b5fbfeb3b4d5d4aaeb740cc14f7eda014.dblock.zip.aes" to "duplicati-bd8d722e6b927453abd4fc22e120970ca.dblock.zip.aes"
##

**Comment by agrajaghh** [comment]
just out of interest, why do you use such a big dblock size?

**Comment by mb300sd** [comment]
It's a 8TB backup with the smallest file being 64GB.

**Comment by mb300sd** [comment]
It happens with 512MB and 1GB dblock as well

**Comment by warwickmm** [comment]
Support for Amazon Cloud Drive has been removed.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
