### ISSUE TITLE
CPU limited, parallel hashing

### ISSUE THREAD

**Issue by mb300sd** [duplicati/duplicati#1898]
Hashing multiple blocks in parallel would give a significant speedup. Looking at disk reads, I'm only managing to get 20-30MB/sec, and that's after changing the blocksize to 128mb and hash algo to MD5 (3x speedup over sha256).

**Comment by kenkendk** [comment]
I have a working implementation in the "concurrent_processing" branch.

I need to rewrite some of the other operations to work with this before it can be merged.

**Comment by mb300sd** [comment]
It is working for backups now, and compatible with the old database/file format?

**Comment by kenkendk** [comment]
Yes, database format is unchanged.

The backend controller is rewritten too, so it enables compression and encryption in parallel as well.

I need to fix the restore/repair processes to use the new controller, and then I will merge it in.

**Comment by gruselglatz** [comment]
What is the current status of the parallel processing.

I see some significant slowdown due to many small files and only running on a single core.
