### ISSUE TITLE
Ftp Backup stopped working - The server committed a protocol violation

### ISSUE THREAD

**Issue by plarner30** [duplicati/duplicati#1899]
**Duplicati Version:** 2.0.1.18_canary_2016-08-10
**Operating System:** Windows 10 x64

Hi, my backup now stops working soon after it starts, here is the full error.

{"ClassName":"System.Net.WebException","Message":"The underlying connection was closed: The server committed a protocol violation.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Duplicati.Library.Main.BackendManager.List()\r\n   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)\r\n   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)\r\n   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)\r\n   at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)\r\n   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)\r\n   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)\r\n   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nList\nDuplicati.Library.Main, Version=2.0.1.18, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Main.BackendManager\nSystem.Collections.Generic.IList`1[Duplicati.Library.Interface.IFileEntry] List()","HResult":-2146233079,"Source":"Duplicati.Library.Main","WatsonBuckets":null}

I have checked the ability to list the files / folders for the backup with a separate FTP client and it seems ok. (~1200 files presently)  I am backing up a single file of 256gb with a block size of 500mb. It takes a while analyzing the file but this has run successfully many times so im not sure why it has started failing. I also tried a second time with the newest canary release. My ftp is passive mode only.

{
  "CreatedByVersion": "2.0.1.18",
  "Schedule": null,
  "Backup": {
    "ID": "1",
    "Name": "disk",
    "Tags": [],
    "TargetURL": 
    "DBPath": "C:\Users\phili\AppData\Roaming\Duplicati\FWEUGZBYDQ.sqlite",
    "Sources": [
      "D:\Image\"
    ],
    "Settings": [
      {
        "Filter": "",
        "Name": "encryption-module",
        "Value": "aes",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "compression-module",
        "Value": "zip",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "dblock-size",
        "Value": "10tb",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "passphrase",
        "Value": 
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--ftp-passive",
        "Value": "true",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--dblock-size",
        "Value": "500mb",
        "Argument": null
      }
    ],
    "Filters": [],
    "Metadata": {
      "LastDuration": "02:03:52.8008011",
      "LastStarted": "20160805T013021Z",
      "LastFinished": "20160805T033413Z",
      "SourceFilesSize": "274877906944",
      "SourceFilesCount": "1",
      "SourceSizeString": "256.00 GB",
      "LastBackupStarted": "20160805T013021Z",
      "LastBackupFinished": "20160805T033413Z",
      "LastBackupDate": "20160805T013021Z",
      "BackupListCount": "15",
      "TotalQuotaSpace": "0",
      "FreeQuotaSpace": "0",
      "AssignedQuotaSpace": "-1",
      "TargetFilesSize": "310251148815",
      "TargetFilesCount": "1211",
      "TargetSizeString": "288.94 GB",
      "LastErrorDate": "20160820T234900Z",
      "LastErrorMessage": "The underlying connection was closed: The server committed a protocol violation."
    },
    "IsTemporary": false
  },
  "DisplayNames": {
    "D:\Image\": "D:\Image"
  }
}
##

**Comment by bunion** [comment]
Sorry - I thought my FTP connection was only passive mode but it seems to work without it now. I will try tonight again with passive mode disabled and see what happens.

**Comment by bunion** [comment]
Ok with passive mode disabled i get a different error: 

Fatal error
System.Net.WebException: The remote server returned an error: (451) Local error in processing.
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)


Could this be something to do with too many files in the backup folder?

**Comment by kenkendk** [comment]
There has definitely been issues with too long file lists on FTP before.

Can you list all the 1211 files with another FTP client, like FileZilla or CyberDuck?

**Comment by bunion** [comment]
Yeah i can list the destination backup files ok with WinSCP. Would it be a good idea to change to a bigger dblock size and start again for the time being? 

My backup is of a 256gb system image file which worked fine for about 20 or so backups then this occurred.

**Comment by kenkendk** [comment]
Are you using SFTP from WinSCP?

If you can change to SFTP, that would rule out any issues with the FTP protocol.

**Comment by bunion** [comment]
SFTP is available i will try to run backup tonight with SFTP and update here

**Comment by bunion** [comment]
Works with SFTP. I'm now on 2.0.1.21_experimental_2016-09-09 so there's been a few versions since, i was getting the new Source: 0 bytes problem until resolved with the latest one. Not sure if the FTP error is still there. Sorry bit of an arse to go back to FTP to reverify if the original problem is still there as its a large backup and i need access to the image file. I might do it if one of the devs asks.

**Comment by ts678** [comment]
> My backup is of a 256gb system image file which worked fine for about 20 or so backups then this occurred.

> Could this be something to do with too many files in the backup folder?

[FTP only lists a max 2000 files, is it possible to use subfolders? #1957](https://github.com/duplicati/duplicati/issues/1957#issuecomment-1915359643) has comment, if this was an FTP `list` length problem.

> Sorry bit of an arse to go back to FTP to reverify if the original problem is still there

Unless more is known, it's probably best to let issue close by itself. There have also been a lot of Duplicati changes since 2016.
