### ISSUE TITLE
Anti-Virus false positive at 2.0.1.18 Duplicati.CommandLine.BackendTool.exe

### ISSUE THREAD

**Issue by hanjo** [duplicati/duplicati#1900]
Compare https://www.virustotal.com/file/51e7d7f6290364e3a3af488c82ae68378c59aaca97ab2d01b3a961b2704eba42/analysis/1471798563/

**Comment by umgfoin** [comment]
Can't confirm:
Download from official source
http://updates.duplicati.com/canary/duplicati-2.0.1.18_canary_2016-08-10.zip
Safe in context of NOD32 9.0.386.1 db 13997.
bg umgfoin.

**Comment by kaasszje** [comment]
Even the official source gives the virus error.
Kaspersky says it has a virus inside.

**Comment by mnaiman** [comment]
Yeah, even duplicati.server was deleted by microsoft defender false positive action

**Comment by omeinusch** [comment]
Same here for Kaspersky 16.0.1.445(e) and Dupicati 2.0.1.19:

>  28.08.2016 11.24.06
> Detected object (file) not processed.
> C:\Program Files\Duplicati 2\Duplicati.CommandLine.BackendTool.exe
> C:\Program Files\Duplicati 2\Duplicati.CommandLine.BackendTool.exe
> HEUR:Trojan.Win32.Generic;Trojan program
>

**Comment by mnaiman** [comment]
duplicati.server is clean in 2.0.1.19

**Comment by mnaiman** [comment]
It has to be connected with compilator, because when I compiled from source, virustotal find no "viruses".

**Comment by agrajaghh** [comment]
There are still 5 false positives:

https://www.virustotal.com/de/file/488b1540fdd638dd1be7a3cebd58952c50a81c2421d182057636df1a45866d88/analysis/1472396663/

```
Antivirus 	Ergebnis
AegisLab 	Troj.W32.Generic!c
Antiy-AVL 	Trojan[:HEUR]/Win32.AGeneric
DrWeb 		Program.Unwanted.1110
Kaspersky 	HEUR:Trojan.Win32.Generic
McAfee 		Artemis!537E3AF24FEB 
```

**Comment by hanjo** [comment]
Looks like 2.0.1.20 is clean again:
https://www.virustotal.com/file/d9591b8d718283ef1530bbcec14f4b3b7509c210f330da39710e115aa334b68c/analysis/

**Comment by agrajaghh** [comment]
there is still one false positive for 2.0.1.20 (I don't know in which file though, I uploaded the whole zip file):
https://virustotal.com/de/file/ad489b99e7b9973560991a8bef5f9c98c06c08e05b84da8e3dc74c0657b3631f/analysis/1472901460/
```
DrWeb 	Program.Unwanted.1110 	20160903 
```

**Comment by kenkendk** [comment]
Hopefully this will be resolved once I get the MSI files signed with my key.

**Comment by agrajaghh** [comment]
> Hopefully this will be resolved once I get the MSI files signed with my key.

you have to sign the exe files, not the msi, no?

**Comment by umgfoin** [comment]
In my experience, code-signatures won't be the universal remedy against false positives: In particular, heuristic-strategies by design shouldn't get too impressed by assumptions on an attached certificate.
