### ISSUE TITLE
Feature Request:  Add support for Google Auth via web browser OAuth

### ISSUE THREAD

**Issue by rbeede** [duplicati/duplicati#1902]
It would be nice if instead of asking for a Google username and password the UI simply had a Connect to your Google Account button that launched a web browser to OAuth authorize Duplicati to my Google account Authorized Apps list.

Some organizations use SSO so I have no Google password.  I add apps by authorizing the application which is issued an OAuth token from Google.

This also reduces the work for 2FA users who would have to use an app specific password.  That would not be required in the web browser auth model.

**Comment by kenkendk** [comment]
Which version is this for?

Duplicati 2.0 uses OAuth so it does not ask for Google username/password, and should work with 2FA etc.

**Comment by rbeede** [comment]
1.3.4.   If support is only available in the 2.x releases that would be fine too.

**Comment by agrajaghh** [comment]
yes sorry, Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
