### ISSUE TITLE
Invalid size value: settings and parser do not match

### ISSUE THREAD

**Issue by andy012345** [duplicati/duplicati#1906]
Settings menu lets you pick a terabyte value but /Library/Utility/Sizeparser.cs does not contain code to handle this.

If this setting is used backups will fail with an invalid size value error.

**Comment by agrajaghh** [comment]
@kenkendk just saw that you're using tab instead of space indent again :laughing:

**Comment by kenkendk** [comment]
@agrajaghh: Thanks for noticing!
