### ISSUE TITLE
(ngax) "Add a path directly" field ignored

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1907]
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** Duplicati - 2.0.1.19_canary_2016-08-27
**Operating System:** Windows 10 (Insider preview build 14905)
**Backend:** File
### Bug description

I am starting Duplicati with Duplicati.GUI.Trayicon.exe. When I try to create a new backup in WebUI I am offered two ways to enter source paths, the applet with most common paths and below it a text field with description: "Add a path directly". I used the latter to set a valid path and left all choises in former unselected. When I save on the final screen of the wizard I get error dialog with text: "You must choose at least one source folder." 
### Steps to reproduce
- Start WebUI.
- Create new backup
- Leave all predifend paths unselected and insert valid path to lower (text)field. 
- Click through the rest of the wizard.
- Save the backup.

**Actual result:** Error dialog with text: "You must choose at least one source folder." 

**Expected result:** New backup job is created that will back up given path.
### Screenshots

![duplicati-path-wizardp2](https://cloud.githubusercontent.com/assets/13969439/18034298/29c33794-6d42-11e6-9c09-b9683d79b9ff.PNG)
![duplicati-path-dialog](https://cloud.githubusercontent.com/assets/13969439/18034300/2cc5cb00-6d42-11e6-8827-5c884c688c03.PNG)
##

**Comment by kenkendk** [comment]
This is caused by a mis-understanding (i.e. the UI is not as obvious/clear as it should be).

You need to click the "add path" button, to add the path to the list of paths that are backed up.
Not sure how to make it better though...

**Comment by kakoskin1** [comment]
If I click on "Add path" button nothing seems to happen unless I have scrolled upper selection field with the tree view to bottom. Also no other text field requires clicking a button to conferm the action. Even the source field, after clicking "Show advanced editor" does not require a confirmation. 

Minimal way to make this work woould be to make clicking "Add path" button optional and add inserted path when user moves to the next page. 

Better way would be to remove entirely the lower text field since upper field can be changed to a text field with "Show advanced editor".
