### ISSUE TITLE
Can't restore files/folders with semicolon in name

### ISSUE THREAD

**Issue by TheCake21** [duplicati/duplicati#1908]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.19_canary_2016-08-27
**Operating System:** Windows 10 x64
**Backend:** Any

### Bug description
When trying to restore a file or directory with a semicolon ";" in name Duplicati detects this filename as Wildcard a nothing is restored. Restoring the parent folder does work fine and the file the semicolon in the name is restored.

### Steps to reproduce
- Create file or directory with a semicolon in name e.g. "Foo;Bar"
- Backup it and try to restore it.

### debug log
```
2016-08-28 19:46:39Z - Error: Terminated with error: Filter for list-folder-contents must be a path prefix with no wildcards
Parametername: filter
System.ArgumentException: Filter for list-folder-contents must be a path prefix with no wildcards
Parametername: filter
   bei Duplicati.Library.Main.Database.LocalListDatabase.FileSets.<SelectFolderContents>c__Iterator1.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
```

**Comment by agrajaghh** [comment]
@kenkendk tab indent again :stuck_out_tongue_closed_eyes:
