### ISSUE TITLE
Minor GUI improvement: Backup Summary Result: insert line breaks between Error Msg.

### ISSUE THREAD

**Issue by martin54** [duplicati/duplicati#1912]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------
### Version info
**Duplicati Version:** 2.0.1.17_canary_2016-05-14
**Operating System:** Win.7 64 bit
**Backend:** Google Drive

### Problem description
When looking at the results of a backup job via "Reporting:  Show log ..." (-> http://127.0.0.1:8200/ngax/index.html#/log/1  "Log data" / General), the "Result" text box is hard to read if multiple problems occurred during a backup jobs, because all (error) messages appear in one single line, without line breaks between the error messages.
Example:
`DeletedFiles: 22`
`...`
`Messages: [<msg1>]`
`Warnings: [<warn1>, <warn2>, <warn3>, ...]`
`Errors: []`

### Steps to reproduce
- Run backup job having multiple warning/error messages
- Look at the "Results" text box via "Show Log ..."

**Actual result:** Concatenated string of messages:
`Warnings: [<warn1>, <warn2>, <warn3>, ...]`
 
**Expected result:** Message delemiter "," replaced by CRLF, so that new messages appear in column 1:
`Warnings: [<warn1>`
`<warn2>`
`<warn3>]`

### Screenshots
![duplicati feature request - line breaks in end-of-job summary message](https://cloud.githubusercontent.com/assets/21290778/18071332/4f48d87a-6e55-11e6-8a30-ac7293545110.PNG)

**Comment by kakoskin1** [comment]
Yes, this appears to have been fixed. I have not been seeing this for quite some time.
