### ISSUE TITLE
Backup won't run: "Error while running <backupname> Value cannot be null. Parameter name: key"

### ISSUE THREAD

**Issue by osvaldsson** [duplicati/duplicati#1913]
I have:
- [x] searched open and closed issues for duplicates
---
### Version info

**Duplicati Version:** 2.0.1.19_canary_2016-08-27
**Operating System:** Windows 10 64bit
**Backend:** S3
### Bug description

Describe here the issue that you are experiencing.
I created two backup configs and one works fine but this one doesn't and there is no difference between the two except for the file path within the same bucket.
The only difference is that I had a previous duplicati backup in the same S3 folder as the one that is failing but I've tried changing the path, recreating the backup and database without any change.
### Steps to reproduce
- Happens every time I try to create a backup of my user directory

**Actual result:** The backup won't run and returns an error: `Error while running <backupname> Value cannot be null. Parameter name: key`
If I try to recreate the database it gives this message: `
Error while running <backupname>
Found 1 files at the remote storage, but none that could be parsed
` (but the remote storage path is empty.
**Expected result:** The backup should run
### Screenshots

Error messages are above.
### debug log

```
System.ArgumentNullException: Value cannot be null. Parameter name: key at
    System.Collections.Generic.Dictionary`2.FindEntry(TKey key) at
    System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) at
    Duplicati.Library.Utility.FilterExpression.AnalyzeFilters(IFilter filter, Boolean& includes, Boolean& excludes) at
    Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result) at
    Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) at
    Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) at
    Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```
##

**Comment by kenkendk** [comment]
Are you sure you are running 2.0.1.19?

This sounds like #1654 which was fixed some time ago.

**Comment by osvaldsson** [comment]
The about page states: `You are currently running Duplicati - 2.0.1.19_canary_2016-08-27` but there is an update running and I'll apply that today.

I do however agree that this seems to be the exact same problem as #1654 and unchecking the home directory fixes the problem to the point where it now only complains about locked files but does not completely fail.

I'm running Windows 7 btw.

**Comment by spmadden** [comment]
Windows 7 with Duplicati - 2.0.1.20_canary_2016-09-01.  I just experienced this issue as well.  Same solution for #1654 worked as well for me.

**Comment by kenkendk** [comment]
I have put up a new canary build that should fix this. 
If any of you that have this problem could try that and report if the problem is fixed, I would appreciate it.
The new canary reports what the "Home" folder maps to, if you go into "About" and "System info".

**Comment by kenkendk** [comment]
No feedback on this?

Can one of you please try 2.0.1.29 from:
https://github.com/duplicati/duplicati/releases

**Comment by osvaldsson** [comment]
I'm sorry for the slow response but I was experiencing issues after the upgrade but it happened at the same time as I rotated my IAM credentials.
The backup runs "successfully" now but reports errors every time due to locked files and snapshot won't work to fix that.

**Comment by agrajaghh** [comment]
> The backup runs "successfully" now but reports errors every time due to locked files and snapshot won't work to fix that.

did you try `--snapshot-policy=Required`? Did you start duplicati with admin rights?

**Comment by osvaldsson** [comment]
You pointed out the problem, I had not set it to be run with admin privileges. No errors now.
