### ISSUE TITLE
2.0.1.19: Options not working: log-file, asynchronous-upload-*

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1914]
### Version info
**Duplicati Version:** 2.0.1.19
**Operating System:** Windows 10 64bit
**Backend:** SMB share

### Bug description
I have backup jobs with log files and other options: It seems at least three options have no effect. Here's the complete list of options set for the given backup job.

--allow-sleep=false
--snapshot-policy=off
--auto-cleanup=true
--log-file=c:\temp\duplicati-D.log
--log-level=Profiling
--asynchronous-upload-folder=D:\temp
--asynchronous-upload-limit=4

Issues:
1) There are no files created in D:\temp, so I guess the upload-folder setting is not respected. I can see files in %TEMP% being created and used.

2) the log file is being created but despite having profiling verbosity, the log file remains empty.

Side question: Why is auto-cleanup obviously not a default setting?

Cheers
Stefan

**Comment by kenkendk** [comment]
`auto-cleanup` is not on by default as it will delete files it thinks are wrong.
Everything should run without needing the cleanup option, and the user is warned if cleanup is required.

The log-file issue is new to me. Are you using this from the GUI or the commandline?

**Comment by huste** [comment]
Thanks for the clarification. How does the warning work? In a sense that one can simply say "ok, go ahead, do your cleanup tasks?" Or is it just a warning where one has to select the option manually.

as for the log-file issue: That's launched manually or scheduled through the ngax-UI. Here's the exported backup job showing the issue.
```
{
  "CreatedByVersion": "2.0.1.20",
  "Schedule": {
    "ID": 2,
    "Tags": [
      "ID=2"
    ],
    "Time": "2016-09-06T06:37:00Z",
    "Repeat": "1D",
    "LastRun": "2016-09-05T06:28:07Z",
    "Rule": "AllowedWeekDays=Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
    "AllowedDays": [
      "mon",
      "tue",
      "wed",
      "thu",
      "fri",
      "sat",
      "sun"
    ]
  },
  "Backup": {
    "ID": "2",
    "Name": "Work",
    "Tags": [],
    "TargetURL": "file://Z:\\stefan\\workWS13\\",
    "DBPath": "C:\\Users\\stefan\\AppData\\Roaming\\Duplicati\\XFQUKTZJKS.sqlite",
    "Sources": [
      "C:\\Users\\stefan\\work\\"
    ],
    "Settings": [
      {
        "Filter": "",
        "Name": "encryption-module",
        "Value": "",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "keep-time",
        "Value": "1Y",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "passphrase",
        "Value": "",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "dblock-size",
        "Value": "1gb",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--no-encryption",
        "Value": "true",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--log-level",
        "Value": "Information",
        "Argument": null
      },
      {
        "Filter": "",
        "Name": "--log-file",
        "Value": "c:\\temp\\duplicati-work.log",
        "Argument": null
      }
    ],
    "Filters": [
      {
        "Order": 0,
        "Include": false,
        "Expression": "*\\arbeit-ungesichert\\"
      },
      {
        "Order": 1,
        "Include": false,
        "Expression": "*\\__history\\"
      },
      {
        "Order": 2,
        "Include": false,
        "Expression": "*\\dcus\\"
      }
    ],
    "Metadata": {
      "LastDuration": "00:11:19.6329294",
      "LastStarted": "20160905T062907Z",
      "LastFinished": "20160905T064027Z",
      "SourceFilesSize": "4158375988",
      "SourceFilesCount": "35618",
      "SourceSizeString": "3,87 GB",
      "LastBackupStarted": "20160905T062907Z",
      "LastBackupFinished": "20160905T064027Z",
      "LastBackupDate": "20160905T062912Z",
      "BackupListCount": "100",
      "TotalQuotaSpace": "0",
      "FreeQuotaSpace": "0",
      "AssignedQuotaSpace": "-1",
      "TargetFilesSize": "3276696414",
      "TargetFilesCount": "132",
      "TargetSizeString": "3,05 GB",
      "LastErrorDate": "20160329T062647Z",
      "LastErrorMessage": "Der Thread wurde abgebrochen."
    },
    "IsTemporary": false
  },
  "DisplayNames": {
    "C:\\Users\\stefan\\work\\": "work"
  }
}
```

**Comment by kenkendk** [comment]
The "warning" stops the backup and asks the user to run repair... which is not the best solution :).

I will see if I can reproduce the log-file issue.

**Comment by huste** [comment]
Concerning the log-file issue: I just noticed that when switching to the UI live log and waiting a little bit, the log file is being populated again.

**Comment by huste** [comment]
Now it's still about the asynchronous upload folder :) 

BTW: It would be nice to have a "finished" log file entry when a backup job actually finishes.

**Comment by kenkendk** [comment]
Is this because the options are listed in the "global options" area and not on the backup?
There is currently a bug where the options listed under "Settings" are not applied.

**Comment by huste** [comment]
Thank Kenneth! I think, this one can be closed now and for the log file not being populated, I'd open a new one.
