### ISSUE TITLE
Mac backup to FTP never completes

### ISSUE THREAD

**Issue by stfreak02** [duplicati/duplicati#1915]
I have:
- [X] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.19_canary_2016-08-27
**Operating System:**  OS X Yosemite v 10.10
**Backend:**  proftpd on NAS4Free 10.2.0.2 (FreeBSD 10.2-RELEASE #0 r286738M: Thu Aug 13 21:32:58 CEST 2015) requiring TLS
### Bug description

The backup takes the snapshot of the data properly, then during upload the ftp server receives incomplete transfers.
Duplicati error message states: The file <FileNameRemoved> was uploaded but not found afterwards, the file listing returned end ngIf: item.Action != 'update:new' ngIf: item.Action != 'update:new'
Other times another error message pops up: Operation is not valid due to the current state of the object. end ngIF: item.Action!= 'update:new' ngIF: item.Action != 'update:new'
proftpd log indicates the file transfer completed for the file specified, but the other files created for a new backup are incomplete and have no data

Windows clients on the same network and same backend operate without incident.
### Steps to reproduce
- install duplicati on macbook pro
- start duplicati from terminal
- add new backup to FTP using SSL with authentication
- accept any ssl hash (or specified hash if you know it)
- test connection, with success
- advanced options: I have tried no other advanced options, and also attempts with one, multiple, and all of the following: auto-cleanup, disable-streaming-transfers, no-backend-verification, skip-file-hash-checks, and no-connection-reuse

**Actual result:** incomplete file transfers, failure of backup cycle
**Expected result:** successful backup
### Screenshots

This is a screenshot of the log on the ftp server
![capture](https://cloud.githubusercontent.com/assets/21372984/18149344/3746b016-6fa5-11e6-82fb-7b449674d214.PNG)
##

**Comment by kenkendk** [comment]
Does FTP work from the Mac with another FTP client, like CyberDuck?

It sounds like there is a delay after uploading the files, such that it appears they are not uploaded.
Could you try the advanced option `disable-upload-verify` which will disable the check?

**Comment by stfreak02** [comment]
FTP does work from the Mac (FileZilla).
Attempted using disable-upload-verify and got "Operation is not valid due to the current state of the object."
The FTP log file also shows that there were zero completed transfers 
All five files created on the backend are just names with size of zero.

**Comment by ts678** [comment]
A brief search in the GitHub issues isn't finding open reports like this. [https://usage-reporter.duplicati.com/](https://usage-reporter.duplicati.com/) shows lots of FTP.
Probably something got fixed.

> Windows clients on the same network and same backend operate without incident.

[Future of Mono's .NET Code Sharing](https://www.mono-project.com/news/2016/11/29/mono-code-sharing/) was written after their Microsoft acquisition, and occasional progress news has emerged.
Current `mono` releases might function more like .NET Framework, but unless issue gets active again, it will automatically close,
