### ISSUE TITLE
snapshot-policy not working

### ISSUE THREAD

**Issue by devnull** [duplicati/duplicati#1916]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.19
**Operating System:** Windows Server 2012R2
**Backend:**

### Bug description
I can run a backup with all the default settings fine, however I need to take a backup of the whole disk. I tried to enable the --snapshot-policy argument, and run the backup. Status changes to 'Starting..' and then flicks back to 'Next Scheduled Scan..' Like it didn't do anything.

I downloaded the old version 1.3.4, to see if that worked and I can confirm, the old version does work as expected.

### Steps to reproduce
- New Backup with default settings
- Enable snapshotting by including --snapshot-policy=required or on
- Try to run backup

**Actual result:** Backup doesn't occur at all after enabling --snapshot-policy
**Expected result:** To back up the disk and calling VSS where needed

### debug log

Sep 1, 2016 1:54 PM: Result
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 0
OpenedFiles: 0
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 0
SizeOfOpenedFiles: 0
NotProcessedFiles: 0
AddedFolders: 1
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
VerboseOutput: False
VerboseErrors: False
Messages: [No remote filesets were deleted, Compacting not required]
Warnings: []
Errors: []
 
Sep 1, 2016 1:54 PM: Message
Compacting not required

Sep 1, 2016 1:54 PM: Message
No remote filesets were deleted

-----------------------------

Sep 1, 2016 1:54 PM: Running Backup took 00:00:05.163

Sep 1, 2016 1:54 PM: ExecuteNonQuery: VACUUM took 00:00:00.015

Sep 1, 2016 1:54 PM: Starting - ExecuteNonQuery: VACUUM

Sep 1, 2016 1:54 PM: ExecuteNonQuery: DELETE FROM "RemoteOperation" WHERE "Timestamp" < ? took 00:00:00.000

Sep 1, 2016 1:54 PM: Starting - ExecuteNonQuery: DELETE FROM "RemoteOperation" WHERE "Timestamp" < ?

Sep 1, 2016 1:54 PM: ExecuteNonQuery: DELETE FROM "LogData" WHERE "Timestamp" < ? took 00:00:00.000

Sep 1, 2016 1:54 PM: Starting - ExecuteNonQuery: DELETE FROM "LogData" WHERE "Timestamp" < ?

Sep 1, 2016 1:54 PM: ExecuteNonQuery: UPDATE "RemoteVolume" SET "VerificationCount" = MAX(1, CASE WHEN "VerificationCount" <= 0 THEN (SELECT MAX("VerificationCount") FROM "RemoteVolume") ELSE "VerificationCount" + 1 END) WHERE "Name" = ? took 00:00:00.000

Sep 1, 2016 1:54 PM: Starting - ExecuteNonQuery: UPDATE "RemoteVolume" SET "VerificationCount" = MAX(1, CASE WHEN "VerificationCount" <= 0 THEN (SELECT MAX("VerificationCount") FROM "RemoteVolume") ELSE "VerificationCount" + 1 END) WHERE "Name" = ?

Sep 1, 2016 1:54 PM: RemoteOperationGet took 00:00:00.000

Sep 1, 2016 1:54 PM: Backend event: Get - Completed: duplicati-b20db2aeedb9d4f528241e7816403aeb5.dblock.zip (530 bytes)

Sep 1, 2016 1:54 PM: Downloaded 530 bytes in 00:00:00, -9223372036854775808 bytes/s

Sep 1, 2016 1:54 PM: Backend event: Get - Started: duplicati-b20db2aeedb9d4f528241e7816403aeb5.dblock.zip (530 bytes)

Sep 1, 2016 1:54 PM: Starting - RemoteOperationGet

Sep 1, 2016 1:54 PM: ExecuteNonQuery: UPDATE "RemoteVolume" SET "VerificationCount" = MAX(1, CASE WHEN "VerificationCount" <= 0 THEN (SELECT MAX("VerificationCount") FROM "RemoteVolume") ELSE "VerificationCount" + 1 END) WHERE "Name" = ? took 00:00:00.015

Sep 1, 2016 1:54 PM: Starting - ExecuteNonQuery: UPDATE "RemoteVolume" SET "VerificationCount" = MAX(1, CASE WHEN "VerificationCount" <= 0 THEN (SELECT MAX("VerificationCount") FROM "RemoteVolume") ELSE "VerificationCount" + 1 END) WHERE "Name" = ?

Sep 1, 2016 1:54 PM: RemoteOperationGet took 00:00:00.000

Sep 1, 2016 1:54 PM: Backend event: Get - Completed: duplicati-ia4fd088ae77941b5a46b052747492dbc.dindex.zip (567 bytes)

Sep 1, 2016 1:54 PM: Downloaded 567 bytes in 00:00:00, -9223372036854775808 bytes/s

Sep 1, 2016 1:54 PM: Backend event: Get - Started: duplicati-ia4fd088ae77941b5a46b052747492dbc.dindex.zip (567 bytes)

Sep 1, 2016 1:54 PM: Starting - RemoteOperationGet

Sep 1, 2016 1:54 PM: ExecuteNonQuery: UPDATE "RemoteVolume" SET "VerificationCount" = MAX(1, CASE WHEN "VerificationCount" <= 0 THEN (SELECT MAX("VerificationCount") FROM "RemoteVolume") ELSE "VerificationCount" + 1 END) WHERE "Name" = ? took 00:00:00.000

Sep 1, 2016 1:54 PM: Starting - ExecuteNonQuery: UPDATE "RemoteVolume" SET "VerificationCount" = MAX(1, CASE WHEN "VerificationCount" <= 0 THEN (SELECT MAX("VerificationCount") FROM "RemoteVolume") ELSE "VerificationCount" + 1 END) WHERE "Name" = ?

Sep 1, 2016 1:54 PM: RemoteOperationGet took 00:00:00.031

Sep 1, 2016 1:54 PM: Backend event: Get - Completed: duplicati-20160901T135433Z.dlist.zip (431 bytes)

Sep 1, 2016 1:54 PM: Downloaded 431 bytes in 00:00:00.0156246, 26.94 KB/s

Sep 1, 2016 1:54 PM: Backend event: Get - Started: duplicati-20160901T135433Z.dlist.zip (431 bytes)

Sep 1, 2016 1:54 PM: Starting - RemoteOperationGet

Sep 1, 2016 1:54 PM: ExecuteReader: SELECT "ID", "Name", "Size", "Hash", "VerificationCount" FROM "Remotevolume" WHERE "Type" = ? AND "State" IN (?, ?) took 00:00:00.000

Sep 1, 2016 1:54 PM: Starting - ExecuteReader: SELECT "ID", "Name", "Size", "Hash", "VerificationCount" FROM "Remotevolume" WHERE "Type" = ? AND "State" IN (?, ?)

**Comment by devnull** [comment]
Error while running test24

Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies. The specified module could not be found.

**Comment by kenkendk** [comment]
Ok, it appears there are some issues with loading the AlphaVSS file.

Can you try running the tool `Duplicati.Library.Snapshots.exe` from the commandline?
It attempts to create a snapshot and read from it, maybe it has further hints on what fails.

Also, do you see the file `AlphaVSS.60.x64.dll` in the `alphavss` folder?

**Comment by agrajaghh** [comment]
VSS is working for me with 2.0.1.20 (clean install, no update) on Win10x64. The `Source: 0 bytes` bug is fixed as well :)

**Comment by huste** [comment]
So this issue can be closed, can't it?
