### ISSUE TITLE
feature missing  ?

### ISSUE THREAD

**Issue by helmutdux** [duplicati/duplicati#1917]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version: 2.0.1.18
**Operating System: Windows 7
**Backend: WebDav

### Bug description
When backing up a Dataset it needs app. 5 GB in the Web-Storage.
Daily backups are made and the Space needed grows up to 10 GB within 2 months.
Congratulation: I do a monthly restore and a binary compare with the original data 
Up to now , that gives no errors!  Now I can trust the System !

### Steps to reproduce
Only one Version of the Data is stored (no multilpe Versions selected).

When deleting all Data inc. local Database, a new backup needs 5 GB again.

I would expect some grow due to fragmentation and other effects, but no doubling .

My Question:
Is there any possiblity to avoid this increase or is there any procedure like a "garbage collection" to reduce the amount of storage space ??

**Comment by renestach** [comment]
What do the general options for you backup say? "Keep backups for 3 months"? If so, Duplicati keeps all old date for three months before old data gets deleted. Change this setting to a much smaller value and your backup should become smaller again after some days.

**Comment by helmutdux** [comment]
Hi Thanks for the quick answer. I use the command line interface .
I did not explicit use the keep-option, my parameters are as shown below
"C:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" backup ^
--auth-username=xxxxxxx ^
--auth-password=yyyyyyyy ^
--use-ssl ^
--passphrase=zzzzzzzzzz ^
--backup-name="Praxdatcloud" ^
--backup-test-samples=0 ^
--list-verify-uploads=true ^
--auto-cleanup=true ^
--Quota-size=24GB ^
--DBlock-size=100MB ^
--prefix=Praxdat ^
--dbpath="C:\logs\DuplicatiDB.sqlite" ^
--disable-module="console-password-input" ^
--encryption-module="aes" ^
--exclude="*\System Volume Information\*" ^
--exclude=*\$RECYCLE.BIN\* ^
webdavs://webdav.mediencenter.t-online.de:443/Praxdat T:\ | C:\bin\backup\wtee %log%

Is there perhaps an implicit parameter causing th effect described above??

**Comment by renestach** [comment]
For example --keep-versions="1" or --keep-time="2w".

Does that solve your problem?

**Comment by helmutdux** [comment]
It looks like !

I added --keep-versions="1"  to the command line above and started a backup with no data changed.
He is still working, but already reduced he amount of storage significantly .

Thanks!!

**Comment by helmutdux** [comment]
The workaround did his job.
Now storage consumption  shrinked approximatlily to the initial value.
Would be nice to eliminate this littel bug.
By the way--what means peding information ??
Helmut

**Comment by agrajaghh** [comment]
thanks for reporting back. I don't think this is a bug, duplicati's default settings are to store old file version and deleted files for 3 month. IMHO, thats a good default setting... Of course this requires some additional storage space.

I just added the "pending information" label to point out that there is information missing for us to fix this issue (or to see if it even is a bug)
