### ISSUE TITLE
CommandLine help not correct

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#1927]
### Version info

**Duplicati Version:** 2.0.1.21
**Operating System:** Win10x64

### Bug description
This is the output of `C:\duplicati>Duplicati.CommandLine.exe`:

```
See duplicati.commandline.exe help <topic> for more information.
  General: example, changelog
  Commands: backup, find, restore, delete, compact, test, compare, repair
  Debugging: debug, logging, create-report, test-filters, system-info
  Targets: aftp, amzcd, azure, b2, box, cloudfiles, dropbox, file, ftp, gcs, googledrive, hubic, mega, onedrive, openstack, s3, od4b, mssp, ssh, tahoe, webdav
  Modules: aes, gpg, zip, 7z, console-password-input, http-options, sendmail, runscript, sendxmpp, check-mono-ssl
  Formats: date, time, size, encryption, compression
  Advanced: mail, advanced, returncodes, filter, <option>

http://www.duplicati.com/              Version:  - 2.0.1.21_experimental_2016-09-09
```

**example** isn't working:
```
C:\duplicati>Duplicati.CommandLine.exe example
Command not supported: example
```

also I noticed that **affected** is missing

**Comment by kenkendk** [comment]
If you want to fix it, it is here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/help.txt

**Comment by agrajaghh** [comment]
added a PR (#1938) for `affected` but I didn't know how to make `Duplicati.CommandLine.exe example` working. It should display the same as `Duplicati.CommandLine.exe help example` I guess

**Comment by kenkendk** [comment]
Oh, I missed that part ... it should work without the `help` keyword
