### ISSUE TITLE
Dropbox backend slow upload speed.

### ISSUE THREAD

**Issue by wvc** [duplicati/duplicati#1929]
The dropbox backend is working, but uploads are currently slow (tag v2.0.1.21-2.0.1.21_experimental_2016-09-09). This is in my opinion caused by the chunked upload, with chunk size defaulting to Utility.Utility.DEFAULT_BUFFER_SIZE that is currently only 64 KiB. 

According to this post: https://github.com/ncw/rclone/issues/103#issuecomment-134688176 , at 64 KiB chunks we can only expect roughly 80 KiB/s uploads, due to the api-overhead.    This should be increased, but not too high as well since otherwise requests may time out.  I would suggest in the order of 16MB to 32MB chunks.
##

**Comment by wvc** [comment]
As already mentioned by @kenkendk  in [https://github.com/duplicati/duplicati/pull/1835](url), DEFAULT_BUFFER_SIZE is not used for determining the chunk size, but for copying to the network stream. So this can't be the cause.  The current chunk size is 10 MB so this should be sufficient for dropbox uploads.

The problem may actually lie with the dropbox (web)api. It seems uploading through the dropbox-website gives me similar speeds (2-3 Mbps), so dropbox may be limiting bandwidth for individual connections. The dropbox-client is faster, but that apparently uses private api's (not accessible) and more intelligent delta-uploads.


So this issue may not be resolvable, unless we can upload files in parallel (I'm not sure if duplicati supports uploading volumes in parallel)

**Comment by warwickmm** [comment]
Parallel upload was implemented in pull request #3684 (released in version 2.0.4.16).  If this is still an issue, please reopen with new details.
