### ISSUE TITLE
Bundled GPG executable not found

### ISSUE THREAD

**Issue by ItEndsWithTens** [duplicati/duplicati#1931]
I have:
- [x] searched open and closed issues for duplicates

The closest issue is #532, but this is happening in Duplicati 2.0, and seems to have a different cause on top of that.

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.22_experimental_2016-09-12
**Operating System:** Windows 10 64-bit, version 1607
**Backend:** File based or Amazon Cloud Drive

### Bug description
When attempting to run a backup using GnuPG encryption in Windows, with Duplicati's built-in distribution of GPG, the included executable is not found and backups using that encryption method fail.

### Steps to reproduce
- Create a new task, give it any name and local destination.
- Choose "GNU Privacy Guard, external" from the Encryption drop-down, and enter a passphrase.
- Select any source data, leave all other options at their defaults, and click Save on page four.
- Find the newly added task and click "Run now".

**Actual result:** An error message appears:
`Failed to execute GPG at ""gpg" --batch --passphrase-fd 0 --symmetric": The system cannot find the file specified`

**Expected result:** Duplicati compresses, encrypts and uploads the files with no warnings or errors.

----------------------------------------

Process Monitor shows Duplicati looking inside the win-tools directory for gpg.exe, failing to find it because it doesn't search the gpg subdirectory, then moving on to my system PATH only to fail there as well since I don't have any other copies of the software on my system.

As a result, the issue can be worked around by editing the task to add the "gpg-program-path" advanced option. Setting it to gpg/gpg lets Duplicati work as expected.

Looking inside [GPGEncryption.cs, at line 97](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Encryption/GPGEncryption.cs#L97), it seems m_programpath is set only to "gpg", and [elsewhere in that same class](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Encryption/GPGEncryption.cs#L228) the ProcessStartInfo used to execute GPG doesn't explicitly set its WorkingDirectory member. Changing m_programpath to "gpg/gpg" works, and I imagine simply storing gpg.exe one level up in the directory tree would also be effective.

My apologies for not offering a pull request to help out, but I'm only a novice when it comes to this stuff. If I was certain the code I mentioned was the issue, and that the problem was due to the software and not just some stupid mistake I've made, I'd gladly have done so, but I'm not too sure of myself. Does this look like an actual bug, or am I doing something incredibly dumb?

**Comment by kenkendk** [comment]
It sounds as a genuine bug :).

I think it would be easier to just move gpg out of the subfolder, then everything would work.

**Comment by kenkendk** [comment]
Should be fixed with together with #1921
