### ISSUE TITLE
Help describes unimplemented switch --backend-log-database

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1941]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.22_experimental_2016-09-12
**Operating System:** Fedora 24

### Bug description
Help topic debug contains section:
 --backend-log-database = <path>
    Duplicati can log all actions related to storing, deleting files on the
    backend. <path> specifies where this log is written e.g.
    "D:\duplicati\backend.xml".

Using swiitch --backend-log-database produces warning: "The supplied option --backend-log-database is not supported and will be ignored"

Also "duplicati-cli help --backend-log-database" gives only:
Topic not found: backend-log-database

**Comment by kenkendk** [comment]
This was fixed with 6907258
