### ISSUE TITLE
ftp password open in the json configuration file

### ISSUE THREAD

**Issue by u-fischer** [duplicati/duplicati#1942]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.24_canary_2016-09-21
**Operating System:** Windows 10
**Backend:** ? ftp?

### Bug description
When I store my ftp-password in a backup with the `--auth-password` option and then export the configuration to a json-file the password is not encrypted but can be read. I do find this unsecure. 

If I don't store the password the backup fails (I'm not asked for it when I run the backup). 

**Expected result:** I would like to store the password in the backup configuration, but it should be encrypted and not exported as clear text to some file. I don't mind if this means that I will have to reenter the password every time I create a new backup.

**Comment by kenkendk** [comment]
Closing and merging into #2024.
