### ISSUE TITLE
No more backups after wrong system time (i.e. BIOS battery failure)

### ISSUE THREAD

**Issue by Septa9** [duplicati/duplicati#1943]
![Uploading Capt.jpg…]()

I have:
- [ x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:**1.3.4
**Win 8.1**
**won't matter**
### Bug description

Stops making backups after wrong system time (i.e. BIOS battery failure)
### Steps to reproduce
- Set system date to something in the past, as if the BIOS battery had failed. (Some date in the last century will do, and this can probably only happen on systems that don't contact a time server via Internet.)
- Let Duplicati run a backup.

**Actual result:** This will be the last backup ever, since Duplicati will record a time far in the future, see screenshot.
**Expected result:** Should at least record the wrong time given, so that it can continue making backups after the system time has been fixed.
### Screenshots

[Sorry, uploading screenshot failed: "Something went really wrong, and we can’t process that file."]  
##

**Comment by ts678** [comment]
> 1.3.4

1.3.4 has been out of maintenance for years, however I did find another report and explanation about what is going on here. Primary motivation for that was to see if Duplicati 2 has a similar issue. All that I could find was on the old version, but info is

[Invalid future time causes manifest errors #656](https://github.com/duplicati/duplicati/issues/656#issuecomment-51173680)

> Yes, that is actually not easy to fix.
Duplicati relies on the time to figure out where what goes in the sequence.

etc. but Duplicati 2 work consumed developer resources, so it never got fixed.

If there is nothing more posted here, issue will automatically close, eventually.
