### ISSUE TITLE
JottaCloud backend request

### ISSUE THREAD

**Issue by soniariv** [duplicati/duplicati#1945]
I have:
- [x ] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.0.0
**Operating System:** Windows 7
**Backend:** JottaCloud
### Bug description

I would like some support for Jottacloud, please. https://www.jottacloud.com/
It is a Norwegian cloud with good privacy support and one of the few cloud services with servers in Europe. It already provides AES-256 of data traffic but apparently not the encryption on-site. So Duplicati could be an interesting companion to secure all data before it is uploaded.
Thank you!
##

**Comment by jkaberg** [comment]
@kenkendk You can close this one :smile: (its implemeneted, ref #2355)

**Comment by kenkendk** [comment]
Thanks!
