### ISSUE TITLE
[Debian] Web-Ui only accessible from localhost

### ISSUE THREAD

**Issue by henfri** [duplicati/duplicati#1947]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:**  2.0.1.24-1_all.deb
**Operating System:**  Debian Jessie
**Backend:** None yet

### Bug description
Web-Interface is accessible from localhost (It is a headless server), e.g. via wget, but not from other machines.

### Steps to reproduce
I run 
- /usr/lib/duplicati# mono Duplicati.Server.exe --webservice-port=8200
This returns (only): No LSB modules are available.

**Actual result:** web-ui accessible from local host
**Expected result:** web-ui also accessible from other hosts.

By the way:
Where do I find *any* documentation?

**Comment by lucwuyts** [comment]
Did you make a firewall rule to allow this communication from your network?
It is working on my machines.

**Comment by deHoeninger** [comment]
@henfri, thats the intended behavior. You have to use the aditional "--webservice-interface" parameter to define the interfaces, duplicati should listen to.
For example in your situation something like:

`usr/lib/duplicati# mono Duplicati.Server.exe --webservice-port=8200 --webservice-interface=any`

But please have in mind that the connection is not secure in that setup.

**Comment by henfri** [comment]
Thanks, that was it.
I am sorry about this -apparently- basic question. But I really cannot find the documentation at the moment.
Besides, don't you think that an output "Duplicati Server started. Listening on Port 8200 on Interface xyz (only)" would be useful?

**Comment by henfri** [comment]
Thanks!
