### ISSUE TITLE
send-mail options not working

### ISSUE THREAD

**Issue by RightOnTrack** [duplicati/duplicati#1948]
I have:
searched both closed and open issues for duplicates
tried both pop and email server settings

---
### Version info

**Duplicati Version:** 2.0.1.24 canary
**Operating System:**Win 10
**Backend:**Google Cloud Platform
### Bug description

The send-mail options were working for me on all my computers with 2.0.1.17 canary. I just upgraded to 2.0.1.24 canary and now no email is received for backup success or warnings. When I downgraded back to 2.0.1.17, the send-mail functions worked again. My configuration is below. I blocked out my email address and password here for privacy.

--send-mail-any-operation=false
--send-mail-level=Success,Warning
--send-mail-to=*****_@gmail.com
--send-mail-from=no-reply ***_**@gmail.com
--send-mail-subject=%backup-name% - Backup Report
--send-mail-body=%RESULT% Remote server url %LOCALPATH%
--send-mail-url=smtp.gmail.com:465
--send-mail-username=*****_@gmail.com
--send-mail-password=**_*********
### Steps to reproduce
1. set similar send-mail options into advanced options in v2.0.1.17 canary
2. run backup job and check for success-warning email
3. if email is received, upgrade to 2.0.1.24 canary
4. rerun backup job and again check for success-warning email

**Actual result:** success-warning email is not received after 2.0.1.24 canary
### debug log

<!-- No "Failed to send email" is present in the live log
##

**Comment by deHoeninger** [comment]
I have the same issue for all versions after 2.0.1.17 but had no time to reprort it so far. No mails are sent.

**Comment by kenkendk** [comment]
I think this is the cause of the the problems:
1659aa77724a6238b93be8c4c5f4af2f00a19d9d

**Comment by RightOnTrack** [comment]
Just installed 2.0.1.26 and everything is working fine. However, send-mail options still not working. Also, forgot to mention before that using Secure SSL/TLS Settings with port 465 has never worked. Tried with Google and my domain. But using Non-SSL Settings with port 26 does work (ex: mail.mydomain.com).

Is something wrong with mailkit?

**Comment by RightOnTrack** [comment]
Just installed 2.0.1.27 and tested send-mail options, still not working. Tried using  "smtps://smtp.gmail.com:465" as suggested from another user and the MailKit documentation (http://www.mimekit.net/docs/html/M_MailKit_MailService_Connect_2.htm).

**Comment by kenkendk** [comment]
If you use non-ssl, you should use:
`--send-mail-url="smtp://mail.mydomain.com:26"`

**Comment by RightOnTrack** [comment]
Kenneth, I tried that as well. I have to speak in laymen's terms because I don't have the programming knowledge and experience that you and the other developers/contributors have.

It seems the mailkit script is just not executing after a backup job completes. Even if I enter the wrong smtp values in the advanced section, wouldn't Duplicati produce a "Failed to send email" error after a scheduled backup job?

I completely understand that these are pre-releases and constant debugging is required. Unfortunately, I cannot use any other version except 2.0.1.17 because the send-mail options work only in that version. Every single version released after that, the send-mail is "broken".

Here are the latest settings I tried using my domain email address as the "send" server(I obscured my email address & pw):

--send-mail-any-operation=false
--send-mail-level=Success,Warning
--send-mail-to=*******@gmail.com
--send-mail-from=no-reply *******@gmail.com
--send-mail-subject=%backup-name% - Backup Report
--send-mail-body=%RESULT% Remote server url %LOCALPATH%
--send-mail-url=smtp://mail.*******.com:26
--send-mail-username=support@*******.com
--send-mail-password=*********
--snapshot-policy=Auto

These settings are located in step 5 (Options) in the setup wizard. I noticed that there are advanced options in step 2 (Destination) as well.

Thanks for the hard work that you and everyone else who contributes to this project.

Charles
