### ISSUE TITLE
Progress indicators not working in 2.0.1.24_canary WebUI.

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1949]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** Duplicati - 2.0.1.24_canary_2016-09-21
**Operating System:** Windows 10 x64
**Backend:** File

### Bug description
WebUI displays only "Running ..." in progress bar. The blue striped progress indicator is missing and there are no more reports like "N files (X MB) to go". These work in 2.0.1.23_canary.

### Steps to reproduce
- Let autoupdater to update you to 2.0.1.24_canary.
- Open the WebUI and run a backup.

**Actual result:** I get only blank progress bar with text "Running ..." for the duration of entire backup.
**Expected result:** Pretty blue bar scrolling to completion and status messages like "N files (X MB) to go"

### Screenshots
![duplicati- 24_canary-missing_progreess_bar](https://cloud.githubusercontent.com/assets/13969439/18832831/364853f8-83f6-11e6-8de2-b84de46f5fdb.jpg)

**Comment by kenkendk** [comment]
This is probably caused by the new translation layer I added.

**Comment by kakoskin1** [comment]
I just verified that this is fixed in  Duplicati - 2.0.1.26_canary_2016-09-29.
