### ISSUE TITLE
2.0.1.25 - Duplicati cannot recover if all files are deleted from the "Backup to >" destination folder.

### ISSUE THREAD

**Issue by Smallous** [duplicati/duplicati#1951]
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.25_canary_2016-09-26 and previous version.
**Operating System:** Window 10 Home ver. 1607
**Backend:** ???
### Bug description

Duplicati cannot recover if all files are deleted from the "Backup to >" destination folder.
### Steps to reproduce
- Currently the "Backup to >" destination folder is set to a local hard drive.
- To reproduce simply delete all files from the "Backup to >" destination folder.
- As a additional test individual data files (not just indexes) should be deleted from the destination folder, though I suspect the same outcome.

**Actual result:** Duplicati recognises that files are missing and requests a "Repair". A "Repair" replaces what I assume are Index files, but not any data files. Further attempts to run the backup result in "Files are missing, run repair" messages only.  

**Expected result:** I expected Duplicati to replace any and all missing files including data files in the destination folder. However, all the options "Repair, Delete & Recreate" appear to be Database specific only, none of these options resulted in "data" files being recreated.  
##

**Comment by icterine** [comment]
I had same issues when found that some files missing at backend and had to reset backup to scratch.
Workaround.

What I did as workaround.

1. Delete local database
2. Stop duplicati server
3. Open sqllite console and delete rows from Metadata table
sqlite3  Duplicati-server.sqlite
.headers on
select * from Backup;
--- locate backup id
delete from Metadata where Backupid=XXX;
4. Additionally I removed local backup sqllite
 rm MXVBHDCWOB.sqlite
5. Start duplicati server
6. Run backup and it start as fresh new one

**Comment by Smallous** [comment]
Hello, 

Thank you for the work-around. I am going to wait until this bug is fixed at the very least before having another look at this software. The bug is too fundamental and I am disappointed that the software fails this test. I cannot program so testing is the only way I can contribute. Hopefully the bug will be fixed soon.

**Comment by kenkendk** [comment]
I don't understand what you think should happen in the case you are describing.
If you are deleting all files from the "Backup to >" folder, then you are erasing the backup.

There is no way you can recover the backup files, as the source files have changed. In other words, the data required to recreate the database may no longer exist on your machine.

The local database is not a copy of you data on your local machine, it is an index of what is supposed to be in the "Backup to >" folder.

**Comment by Smallous** [comment]
Hello,

I currently do not have Duplicati installed, so this is written from memory.

What I was trying to do was test to see what would happen if something went wrong with the destination folder. The simplest test I could think of was to set-up the destination folder on a separate local hard drive, run a backup, then delete the destination folder (all source data etc. is still intact). 

My understanding is that Duplicati in its "simplest" form is syncing software, so I would have expected Duplicati to re-sync the source data (I understand that previous file versions could be lost at this stage). However, version 2.0.1.25 cannot recover from the above scenario and remains stuck in a "requests a Repair" loop.

Now how Duplicati should behave if something goes wrong with the destination folder (corrupt file, deleted file/folder, disk failure etc.) is open to discussion. especially for those who need versioning. I am not a software developer myself but Duplicati has to be able to cope with these situations otherwise it is not a Backup.

**Comment by icterine** [comment]
Hi,

The problem raised when destination had missing backupsets. It can happen due different reason, like removing accidentally, changing disk etc.

In such situation, repair action should fix it by removing orphan entries and basically reset backup. But it only through error. Workaround was to clear entries from db manually.

Or delete backup definition and recreating it.

**Comment by kenkendk** [comment]
Ok, I re-read the issue and think I understand it now.

I have recently introduce the commandline operation `purge-broken-files`, which recovers from a partially broken state, where some files are deleted from the remote destination (or broken somehow). The `purge-broken-files` and related `list-broken-files` will detect what files have blocks inside the missing remote files, and write new filelists where these files are no longer present. It will then remove the old filelists such that the missing blocks are no longer referenced.

This should allow you to recover from most scenarios, but it does not handle the case where all the remote files are lost. In this case there is not much to recover anyway, so I think it would be fine to require manual intervention in this case (delete the local database).

**Comment by comodoro** [comment]
I have run into this, after deleting backups on the remote and falsely assuming that Duplicati can just force overwrite the backup. I got error messages asking to repair, then that remote files cannot be found, but no option to recreate them. My workaround in the GUI:

- Delete local database (The Database... link)
- From the GUI select the Command line link and among the options (displayed as edits) just clear the Database edit and press backup

This sequence might have a dedicated launch option in the GUI, since loss of remote backup, whether accidental or not, is not so uncommon. Maybe some warnings are in order. Plus I do not know whether or not some remnants like database metadata are orphaned in the AppData folder.

**Comment by warwickmm** [comment]
Duplicati does not simply sync files, since it maintains a history of backup versions, files, etc.  As such, missing files from the destination folder is not an event that should be simply ignored.  The `purge-broken-files` and `list-broken-files` opens mentioned above should hopefully help the user diagnose the problem.
