### ISSUE TITLE
Help for command affected is incomplete

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1952]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.25_canary_2016-09-26
**Operating System:** Fedora 24
**Backend:** File

### Bug description
Help text for the command *affected* seems to be incomplete. Note the dangling *you*.
$ mono /opt/Duplicati/Duplicati.CommandLine.exe help affected

Usage: affected <storage-URL> <remote-filename> [<remote-filenames>]
[<options>]

  Returns a report explaning what backup sets and files are affected by a
  remote file. You

**Comment by agrajaghh** [comment]
the affected command (including this helptext) was introduced with https://github.com/duplicati/duplicati/commit/f97bdedac9008181ad9081464375ed57a3ae670f.

@kenkendk just remove the "You"?

**Comment by kenkendk** [comment]
@agrajaghh : I will add some more text :)

**Comment by agrajaghh** [comment]
typo: "damahed"

**Comment by kenkendk** [comment]
Dooh!
