### ISSUE TITLE
2.0.1.25 - GUI breaks when returning from Live Log to Duplicati icon if job is running.

### ISSUE THREAD

**Issue by Smallous** [duplicati/duplicati#1954]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.25_canary_2016-09-26
**Operating System:** Windows 10 Home ver. 1607
**Backend:** ???

### Bug description
I have noticed that when navigating the GUI if I click back to the Duplicati icon (top left) this often breaks the GUI. I have found 1 method of re-creating the error, but I think there could be more ways. I have not experienced this problem in the previous version. 

### Steps to reproduce
- Whilst a backup is running (I found if a job was not running I did not encounter the problem).
- Select Show log - Live - Warning - Duplicata icon.

**Actual result:** I return back to the main area, but the GUI is broken.
**Expected result:** Return back to main area.

### Screenshots

![derror](https://cloud.githubusercontent.com/assets/22129332/18870416/6c253826-84a8-11e6-98b6-10fcd29c52ee.jpg)
### debug log
Please let me know if you need logs.

**Comment by kenkendk** [comment]
Is this from Internet Explorer / Edge?

**Comment by agrajaghh** [comment]
I can reproduce this with firefox

**Comment by kenkendk** [comment]
I think this was related to #1949, it does not crash for me with that fix.
I will make a new build shortly.

**Comment by Smallous** [comment]
I was using G-Chrome when I encountered the error.
