### ISSUE TITLE
Cannot connect to Box

### ISSUE THREAD

**Issue by zack-hable** [duplicati/duplicati#1956]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.25
**Operating System:** Windows 10 Anniversary Update
**Backend:** Box.com

### Bug description
When trying to setup a source for storage of backups, box.com does not allow for an authid to be obtained.  (as in the button on popup on authid does not show at all for box.com)

### Steps to reproduce
- Make/edit a backup
- Select Source to backup to
- change storage type to box.com
- click on auth id
- see lack of button to obtain auth id for duplicati

**Actual result:** no button is shown, therefor no auth id obtained
**Expected result:** button that gets auth id is shown and works

**Comment by kenkendk** [comment]
That was an issue on the OAuth handler side of it.
It works now.

If something like this happens again, you can manually visit the page and get the ID:
https://duplicati-oauth-handler.appspot.com
