### ISSUE TITLE
[Windows] NET framework 4 issue

### ISSUE THREAD

**Issue by luispabon** [duplicati/duplicati#1961]
### Version info

**Duplicati Version:** v2.0.1.26-2.0.1.26_canary_2016-09-29 windows x64
**Operating System:** Windows 7 x64
**Backend:**

### Bug description
Describe here the issue that you are experiencing.
New install.

![image](https://cloud.githubusercontent.com/assets/6388823/18976255/66ed1700-86a8-11e6-9929-40987a6769ed.png)

If I try to install NET 4, I get this

![image](https://cloud.githubusercontent.com/assets/6388823/18976264/773ecf72-86a8-11e6-99a7-e48c175befb6.png)

I installed 4.5 just prior as Duplicati installer required it.

**Comment by huste** [comment]
Did you reboot after installing dotnet? It shouldn't matter, but who knows.

**Comment by luispabon** [comment]
That worked! I didn't think that would've mattered, that's why I didn't try at the time. Thank you.
