### ISSUE TITLE
Log files not being populated

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1965]
As mentioned first in #1914, I have several backup jobs with log files. Some of those do create a log file but it remains at 0 bytes in size.

Only after switching to the live log and enabling any log level in the web ui, the log file is being populated with entries. That's with 2.0.1.26
##

**Comment by kakoskin1** [comment]
This seems to be related to what I noticed recently.

Default log-level seems to be Error. At least I get only errors  logged if I do not specify option --log-level=Warning or lower with Duplicati.Commandline.exe. 

This happens both on Fedora 24 and Windows 10 with Duplicati 2.0.1.26_canary_2016-09-29.

**Comment by martin54** [comment]
2.0.1.28_canary_2016-10-19 probably also has the "empty logfile" bug (Win.7).
And my previous version 2.0.1.17_canary_2016-05-14 typically also only created empty logfiles.
I've activated the logfile option within the job as:
--log-file=C:\Users\jm\AppData\Local\Temp\duplicati-backup-jm.log
--log-level=Information
When activating the GUI live log, also the logfile is populated.

**Comment by warwickmm** [comment]
The logging system was rewritten, and I don't think this has been an issue since.  If this is still a problem, please reopen with new details.

https://forum.duplicati.com/t/new-log-system-with-filters/2913
