### ISSUE TITLE
Question: Localization already works partially?

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1967]
It's rather a question than an issue:

I just upgraded to 2.0.1.26 and found that some messages are already translated on the UI into German. like log-messages to Log-Meldungen. Or the buttons on the log-viewing page. Or the text from an error message, but not its heading.
Do these messages come from dotnet? Or is there already a file that I didn't see yet?

**Comment by agrajaghh** [comment]
we are currently trying to set up the localization process, its not done yet, there will still be some changes.
You can find some files e.g. here: https://github.com/duplicati/duplicati/tree/master/Localizations

Are you interested in translating?

**Comment by huste** [comment]
Sure, if you don't mind, I'll just translate the German one and send it to you. Or can I commit files to the repository, too? If so, which URL would I be allowed to check out? (I am new to git, but experienced with SVN)

**Comment by agrajaghh** [comment]
nice 😊  We'll probably use a webservice to manage the translations, so it will be easy to contribute. I'll ping you once we are set up. Please don't start yet with the translation, since there might be some changes which might lead to double work 😉
