### ISSUE TITLE
2.0.1.26 unexpected update count

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#1968]
EDIT 2016-10-02: I posted the wrong stackdumps. Sorry.

I get the following error message when running a backup job.
Note that I am using D:\temp as 
  tempdir
and
  asynchronous-upload-folder
in the global settings, now that it finally works :)

D:\temp is a directory that gets wiped when I log into my account. Could that be a problem?

I ran a backup job which at some  point gave

```
System.IO.InvalidDataException: Found 1 file(s) with missing blocklist hashes bei Duplicati.Library.Main.Database.LocalDatabase.VerifyConsistency(IDbTransaction transaction, Int64 blocksize, Int64 hashsize) bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter) bei Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result) bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) bei Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

this is reproducible. When trying to repair the DB, I get

```
System.Exception: Unexpected update count: 0 bei Duplicati.Library.Main.Database.LocalRepairDatabase.FixMissingBlocklistHashes(String blockhashalgorithm, Int64 blocksize) bei Duplicati.Library.Main.Operation.RepairHandler.RunRepairCommon() bei Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter) bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) bei Duplicati.Library.Main.Controller.Repair(IFilter filter) bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

Removing the settings for D:\temp the issue remains.
##

**Comment by huste** [comment]
Ah, I forgot copying the message that is logged before the backup result:
```
Failed to process path: D:\temp\dup-131127e9-2e3e-45cb-8385-0d02d53065ec
System.Exception: Unexpected result count: 0, expected 1

   bei Duplicati.Library.Main.Database.LocalBackupDatabase.AddBlockset(String filehash, Int64 size, Int32 blocksize, IEnumerable`1 hashes, IEnumerable`1 blocklistHashes, Int64& blocksetid, IDbTransaction transaction)

   bei Duplicati.Library.Main.Operation.BackupHandler.AddFileToOutput(BackendManager backend, String filename, Int64 size, DateTime lastmodified, IMetahash metadata, IEnumerable`1 hashlist, String filehash, IEnumerable`1 blocklisthashes)

   bei Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotServic
```
Why is Duplicati still trying to access a file in D:\temp? I completely removed this setting from the backup job and the main settings. I still use D:\temp but only as asynchronous upload folder.

**Comment by agrajaghh** [comment]
> D:\temp\dup-131127e9-2e3e-45cb-8385-0d02d53065ec

that looks like a file in the async upload folder but I don't why its failing

**Comment by huste** [comment]
You mean: "the file name looks like something that should exist in the upload folder but doesn't"? Are there any circumstances where Duplicati thinks that a file remains there. Like network outages while backup? I somtimes lose the connection to my Synology backend. Especially, when several backups from several machines are ongoing at the same time. I don't recall if such a thing happened. Or maybe an unclean termination? I used a "force terminate" once, but I can't recall which backup job that was. FWIW, I used the forced termination several times in the past on several backup jobs. If that's a problem, I think, this option should be removed from the UI or at least a little bit more hidden or with a menacing warning :)

**Comment by agrajaghh** [comment]
I was just mentioning it because you said:
> Why is Duplicati still trying to access a file in D:\temp?

Force termination should not be a problem I think (at least in theory)

> I somtimes lose the connection to my Synology backend.

This could be the issue. Duplicati is creating the files in this folder to later upload them. If the folder becomes inaccessible during the backup operation it might fail like that I guess.

**Comment by huste** [comment]
Is there any chance that I remove this file from the upload queue? I do have SQLiteDatabaseBrowserPortable at hand...

**Comment by huste** [comment]
As the backup job didn't work out any more, I removed it completely and recreated it from scratch. So I can't reproduce the issue any more. And I won't use D:\temp as my temporary folder any more...Feel free to close it.
