### ISSUE TITLE
Default passphrase not being used by new backup jobs

### ISSUE THREAD

**Issue by surashu** [duplicati/duplicati#1980]
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.22_experimental_2016-09-12
**Operating System:** Windows 10 Pro 1607 (64-bit)
**Backend:** Mega.nz
### Bug description

When setting the passphrase via default settings, it doesn't get applied on new backup jobs.
### Steps to reproduce
- Go to `Settings`
- Under `Default options`, add an entry for `passphrase`
- Then add a new backup

**Actual result:** The `passphrase` section on the new backup is empty
**Expected result:** The `passphrase` section on the new backup should contain the default one set earlier.
##

**Comment by warwickmm** [comment]
Closing this in favor of issue #4353.  It sounds like none of the default options are being respected.
