### ISSUE TITLE
restore from backup -- seems to work on Windows, not on Linux?

### ISSUE THREAD

**Issue by jonathanproteowizard** [duplicati/duplicati#1983]
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.1.0.22
**Operating System: Ubuntu 16.04 / Win 7**
**Backend:**
### Bug description

Duplicati used to create a windows backup to ACD.  Backup is not encrypted.
Attempt to read backup on Win and on Linux:
  Both generate an error: "Detected File Entries Not Associated with Blocks"
  Linux (chrome and firefox) also generates an error "Object reference not set to an instance of an object"

Windows (in explorer), I can still navigate thru the dir tree.
Linux, I get a triangle, checkbox, folder icon, but, if I try to expand the icon I get a repeat of the object reference error.
### Steps to reproduce
- Create backup under windows
  - backup to ACD /Some/Dir
  - no enription
- Try to load backup under linux
### Screenshots

![screenshot from 2016-10-06 12-00-21](https://cloud.githubusercontent.com/assets/22666318/19166479/88d1336a-8bbc-11e6-826c-5462ac614874.png)
##

**Comment by kenkendk** [comment]
There is a cross-os issue at the moment (something to do with `/` vs `\` ), meaning that you cannot restore from another OS than the one you created the backup with.

**Comment by Nerdy314159265** [comment]
I also can confirm this bug. I'm testing backing up Duplicati from a machine running FreeNAS (based on FreeBSD) to a machine running Windows and have the same error. The reverse also has the same issue.
