### ISSUE TITLE
Help for --disable-time-tolerance copied from version 1.

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#1985]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:**  Version:  - 2.0.1.26_canary_2016-09-29
**Operating System:** Windows 10 build 1493.rs_prerelease.160916-1700
**Backend:** N/A

### Bug description
Help for the option --disable-time-tolerance speaks of incremental and full backups. It appears that this help text was copied from version 1 without editing.

"C:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" help --disable-time-tolerance
  --disable-time-tolerance (Boolean): Deactivates tolerance when comparing times
    When deciding if a full backup should be made or an old backup should be
    deleted, Duplicati will adjust the times by a small fraction to ensure that
    minor time differences do not interfer with expected operation. If the
    backup is set to produce a full backup each day, and a full backup is made
    at, say 12:00:01, and the backup is executed again at 12:00:00, a full day
    has not passed and thus an incremental backup is performed. To avoid this,
    Duplicati inserts a 1% tolerance (max 1 hour). Use this option to disable
    the tolerance, and use strict time checking
    * default value: false

**Comment by kakoskin1** [comment]
The fixed text seems to contain a couple of typos:

s/updated/updates/ 
s/a the/the

**Comment by kenkendk** [comment]
Thanks for noticing my sloppy typing :smile:
