### ISSUE TITLE
Need an option to stop upload after a certain time window

### ISSUE THREAD

**Issue by babykaboom** [duplicati/duplicati#2001]
Hello,

It would be useful ton have an option for stopping transfer after a certain period of time or time window when working with slow WAN connection and huge amount of data.
##

**Comment by agrajaghh** [comment]
Why would you like to stop the upload?

**Comment by babykaboom** [comment]
On slow WAN connections with very slow upload rates (~1Mb/s), when upload is fully in use, internet navigation is not possible.

If I can interrupt and restart upload at certain hours, let say at work hours, I can handle large amount of data, like full backup of a server in the cloud, without harming users internet experience.

**Comment by agrajaghh** [comment]
you could use the throttle settings to limit the upload speed. But this is just a general setting or a setting per backup job, you cant specify different throttle settings for specific time frames.
Another possible idea would be to have specific times where the backups are allowed to run.

**Comment by babykaboom** [comment]
Does this option already exist or would you consider implementing it ?

Anyway, keep up the good work, it's very promising 👍

**Comment by agrajaghh** [comment]
the general or job related throttle options already exists. Settings regarding specific time frames don't

**Comment by babykaboom** [comment]
Ok, Thanks.

**Comment by extremeshok** [comment]
How would one force the job to pause uploading at 7am ? and then restart
it at 11pm

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by agrajaghh** [comment]
> How would one force the job to pause uploading at 7am ? and then restart it at 11pm

that's currently not possible

**Comment by JonMikelV** [comment]
I know this is stale, but it's not a singular request:
https://github.com/duplicati/duplicati/issues/2921

**Comment by warwickmm** [comment]
Closing this in favor of issue #2921, which has a bounty attached to it.
