### ISSUE TITLE
Failed to connect: SQL logic error or missing database no such table: RemoteOperation

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [duplicati/duplicati#2007]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** v2.0.1.26-2.0.1.26_canary_2016-09-29
**Operating System:** Windows 10 Pro
**Backend:** Local Folder that's uploaded automatically to the cloud

### Bug description
I can't start the backup.

### Screenshots
![duplicati 2 - can t start the backup](https://cloud.githubusercontent.com/assets/16560332/19343908/da94f3e2-9140-11e6-87b8-635da0e20f0d.png)

### debug log
I changed the target directory for the backup, now I'm getting this:

System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database no such table: RemoteOperation at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain) at System.Data.SQLite.SQLiteCommand.BuildNextCommand() at System.Data.SQLite.SQLiteDataReader.NextResult() at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave) at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior) at Duplicati.Server.WebServer.RESTMethods.LogData.DumpTable(IDbCommand cmd, String tablename, String pagingfield, String offset_str, String pagesize_str) at Duplicati.Server.WebServer.RESTMethods.Backup.FetchRemoteLogData(IBackup backup, RequestInfo info) at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

**Comment by Laurentiu-Andronache** [comment]
Whut? You think this is a bug? I'm sure I'm just being a noob with something.

**Comment by kenkendk** [comment]
This sounds like #1913 (and #1654)?

**Comment by Laurentiu-Andronache** [comment]
That solution didn't work for me. I used the search before posting.

**Comment by kenkendk** [comment]
The "value cannot be null" issue should be fixed in 2.0.1.29:
https://github.com/duplicati/duplicati/releases

**Comment by Laurentiu-Andronache** [comment]
Fixed indeed. kenkendk is God.
