### ISSUE TITLE
Restoring changes timestamp to actual time

### ISSUE THREAD

**Issue by st-anton** [duplicati/duplicati#2009]
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.22_experimental_2016-09-12
**Operating System:** Win10 64bit
**Backend:**
### Bug description

After restoring files of a backup, many - but not all - of the files and folders have the timestamp of the restoration time and date, not the original time. Happens with various versions of the backup. I can't distinguish (i.e. can't see a reason), when a file date / time is modified and when the original time / date is restored.
![duplicati_time](https://cloud.githubusercontent.com/assets/2517417/19378144/562c8db2-91eb-11e6-9213-281d90164624.png)
##

**Comment by agrajaghh** [comment]
how old is your backup job? maybe the old files don't include meta data yet?

**Comment by st-anton** [comment]
Quite new: I started 2016-10-10 and it contains 4 backups now:
![duplicati_versions](https://cloud.githubusercontent.com/assets/2517417/19408861/41485d04-92c7-11e6-804d-e25421b7c833.png)

**Comment by davegold24** [comment]
I also encountered this. Using 2.0.2.12_canary_2017-10-20, original install was 2.0.2.1_beta_2017_08_01. Backup was post upgrade to 2017-10-20 version.
I restored to original location and set it to restore permissions.

**Comment by mr-flibble** [comment]
Same problem on Duplicati - 2.0.2.13_canary_2017-11-22

**Comment by warwickmm** [comment]
I am unable to replicate this using v2.0.4.4-2.0.4.4_canary_2018-11-14 on Linux.  Are people still experiencing this, and if so, is it a Windows-only problem?

**Comment by mikaelmello** [comment]
WIndows user here since 2.0.3.7, noticed multiple times that the original timestamps were restored.

**Comment by mikaelmello** [comment]
I guess so. Haven't seen this reported since I got here.

**Comment by warwickmm** [comment]
Ok.  Assuming that this has been fixed.
