### ISSUE TITLE
Editing existing tasks does not backup new additions

### ISSUE THREAD

**Issue by navigonic** [duplicati/duplicati#2019]
I have:
- [X] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:**  2.0.1.22_experimental_2016-09-12
**Operating System:** Windows 10
**Backend:** Amazon Cloud Drive
### Bug description

When adding new files to backup on a previously run task, the new files don't get added to the cloud storage. For example, I've backed up 400 Gb to ACD, afterwards I modified the task to add another 200 Gb. Source shows at 600 Gb, while the remote backup remains at 400 Gb, despite Running the task, Repairing, Removing and Rebuilding the database and Verifying files.
##

**Comment by kenkendk** [comment]
If you attempt to export to commandline, can you see the extra folders being listed?

I assume the 200GB is "new data", so it is not just de-duplication that saves the space?

**Comment by navigonic** [comment]
Hmm..does the De-Duplication span between different "Tasks" that are located in different folders?

**Comment by silversword411** [comment]
This is still an issue. Just doing a super simple backup for testing.

- Select single file. Run backup. Backup good.
- Modify profile, add a 2nd file to backup. Run Backup. Backup good.
- Modify profile, add new folder to backup. Run Backup. Backup **doesn't** backup new folder selected.

[bugreport.zip](https://github.com/duplicati/duplicati/files/1481101/bugreport.zip)

**Comment by warwickmm** [comment]
I'm unable to reproduce this in version v2.0.4.4-2.0.4.4_canary_2018-11-14.  I followed @silversword411's guide:
1. Create a backup of a single file.  The backup runs successfully.
2. Add another file to the backup.  The backup runs successfully.
3. Add a folder to the backup.  The backup runs successfully.

Is anyone still experiencing this?

**Comment by warwickmm** [comment]
I'm assuming this has been fixed, since I can't reproduce it.  If someone finds that the problem still persists, please re-open this issue.
