### ISSUE TITLE
sorting file tree in folders first way

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#2021]
It would be good to sort tree like explorer is doing in folders first way:

![test2](https://cloud.githubusercontent.com/assets/2264442/19421117/70f6b702-93f9-11e6-9102-f68d7b7abaa3.png)

**Comment by ts678** [comment]
[2.0.5.106_canary_2020-05-11](https://github.com/duplicati/duplicati/releases/tag/v2.0.5.106-2.0.5.106_canary_2020-05-11) change log shows this done:

Sorting files and folders in the WEB UI, thanks @drwtsn32x

PR [Sort file and folder listing in web UI #4150](https://github.com/duplicati/duplicati/pull/4150) talked about:

> I suggest grouping and showing folders first before files. Both groups will be sorted alphabetically.

2.0.5.111 test on Windows seems to show sorting list folders first, with case-insensitive sort inside it.

This looks to me like it can be closed.
