### ISSUE TITLE
deleting backup config not possible - missing captcha

### ISSUE THREAD

**Issue by 1aladdin1** [duplicati/duplicati#2023]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.27_canary_2016-10-14
**Operating System:** Win7 Enterprise
**Backend:** External HDD using USB interface

### Bug description
Attempting to delete a backup config results in error message 'missing captcha'

**Comment by kenkendk** [comment]
Can you add a screenshot? the captcha should only be required if you check to delete all remote files.

**Comment by kenkendk** [comment]
Nevermind ... found the problem ...
