### ISSUE TITLE
AlphaVSS.Common.dll requirement

### ISSUE THREAD

**Issue by a1ezzz** [duplicati/duplicati#2025]
Good day. There is a error in the lates deb-package build: http://updates.duplicati.com/experimental/duplicati_2.0.1.22-1_all.deb

This command:
mono /usr/lib/duplicati/Duplicati.CommandLine.exe backup "file:///etc" "/tmp" --snapshot-policy=required --no-encryption 
returns this error:
Could not load file or assembly 'AlphaVSS.Common....

This error is gone if I copy AlphaVSS.Common.dll file from zip-file (http://updates.duplicati.com/experimental/duplicati-2.0.1.22_experimental_2016-09-12.zip) to /usr/lib/duplicati

Debian version is 8.1

**Comment by kenkendk** [comment]
Could I get you to run (without AlphaVSS.Common.dll) and with the extra commandline option --debug-output?

This will give me a stack trace, so I can see where it attempts to load the library.

**Comment by kenkendk** [comment]
I tried it myself, and have a fix ready.

**Comment by a1ezzz** [comment]
Sorry for late response. Thank you

**Comment by angellafuente** [comment]
Confirmed when duplicati-server is started in:
-CentOS 7.2
-Mono 4.2.4
-Duplicati 2.0.1.30

System.IO.FileNotFoundException: Could not load file or assembly 'AlphaVSS.Common, Version=1.2.4000.3, Culture=neutral, PublicKeyToken=959d3993561034e3' or one of its dependencies.
File name: 'AlphaVSS.Common, Version=1.2.4000.3, Culture=neutral, PublicKeyToken=959d3993561034e3'
  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) <0x42273420 + 0x007bf> in <filename unknown>:0

Will the fix be included in the next release?

Thank so much.

**Comment by agrajaghh** [comment]
@angellafuente can you please try 2.0.1.35 from https://github.com/duplicati/duplicati/releases and report back if this fixes your problem?

**Comment by angellafuente** [comment]
Sorry about delay.

I have tested it after upgrade and it works. :-)

Here go the test output

```
[root@www tmp]# yum info duplicati
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: s3-mirror-eu-west-1.fedoraproject.org
 * extras: ftp.heanet.ie
 * updates: ftp.heanet.ie
Installed Packages
Name        : duplicati
Arch        : noarch
Version     : 2.0.1.35
Release     : 2.0.1.35_experimental_20161213
Size        : 22 M
Repo        : installed
From repo   : /duplicati-2.0.1.35-2.0.1.35_experimental_20161213.noarch
Summary     : Backup client for encrypted online backups
URL         : http://www.duplicati.com
License     : LGPLv2+
Description : Duplicati is a free backup client that securely stores encrypted,
            : incremental, compressed backups on cloud storage services and remote file
            : servers.  It supports targets like Amazon S3, Windows Live SkyDrive,
            : Rackspace Cloud Files or WebDAV, SSH, FTP (and many more).
            :
            : Duplicati has built-in AES-256 encryption and backups be can signed using
            : GNU Privacy Guard.  A built-in scheduler makes sure that backups are always
            : up-to-date.  Last but not least, Duplicati provides various options and
            : tweaks like filters, deletion rules, transfer and bandwidth options to run
            : backups for specific purposes.

[root@www tmp]# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
[root@www tmp]# duplicati-server
Server has started and is listening on 127.0.0.1, port 8200




```

**Comment by JohnDelisle** [comment]
Same issue persists on Centos7 and Ubuntu - https://forum.duplicati.com/t/ubuntu-failed-to-load-process-type-duplicati-library-common-io-vssbackupcomponents/9305
