### ISSUE TITLE
update dialog too small

### ISSUE THREAD

**Issue by agrajaghh** [duplicati/duplicati#2033]
It look's like the update dialog is too small for some languages:

![dialog](https://cloud.githubusercontent.com/assets/5296073/19517687/fca5dcdc-9602-11e6-8eb5-fb017dde8e33.png)
##

**Comment by tudacs** [comment]
I feel a bit sorry for hijacking your self-assignment and hope that's okay for you :).

**Comment by agrajaghh** [comment]
@tudacs dont worry 😊 I had no time yet to fix it, help is always welcome 😊 

but please keep in mind that the layout should work for small screens (like smartphones) as well. I think the design goal was to have it from screensizes like iphone4 upwards

**Comment by kenkendk** [comment]
This was fixed with 3208a1d
