### ISSUE TITLE
impossible to delete a backup configuration: missing captcha

### ISSUE THREAD

**Issue by rinaldi6109** [duplicati/duplicati#2035]
### Version info
Sorry, I haven't the pc next to me.

### Bug description

Backup > Configuration: Delete > Delete Backup > Confirm delete: Yes > Missing Captcha! 
but there is NO captcha

**Comment by kenkendk** [comment]
You have 2.0.1.27 and this was fixed with 2.0.1.28.
You can update to get the new bersion.
