### ISSUE TITLE
missing assembly System.Management on Ubuntu 16.04

### ISSUE THREAD

**Issue by yymsc** [duplicati/duplicati#2037]
----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.28_canary_2016-10-19
**Operating System:** Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-45-generic i686)
**Backend:** Windows 10, Firefox 49.0.2 

### Bug description
After updating Duplicati on Ubuntu 16.04 to the latest version 2.0.1.28_canary_2016-10-19 I'm getting an error as soon as I try to run a backup:
'Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.'
I did not have any problems with the previous version 2.0.1.27_canary_2016-10-14.

### Screenshots

![screenshot 12 2016-10-21](https://cloud.githubusercontent.com/assets/4045703/19595809/f4736e00-978b-11e6-840f-4ada49e16e26.jpg)

### debug log
System.IO.FileNotFoundException: Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. File name: 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at Duplicati.Library.Main.Controller.SetupCommonOptions (ISetCommonOptions result, System.String[]& paths, IFilter& filter) <0xb0e2e538 + 0x00988> in <filename unknown>:0 at Duplicati.Library.Main.Controller.RunAction[T] (Duplicati.Library.Main.T result, System.String[]& paths, IFilter& filter, System.Action`1 method) <0xb0e2e0e8 + 0x00113> in <filename unknown>:0

**Comment by yymsc** [comment]
manually installing the assembly fixed the problem:
`sudo apt-get install libmono-system-management4.0`

**Comment by yymsc** [comment]
I don't think this issue should be closed because I still consider this as a bug and it should be fixed somehow in the installation/update process.

**Comment by agrajaghh** [comment]
yeah, I guess you're right. Did you install the .deb package?

**Comment by yymsc** [comment]
I used the internal 'Check for updates now' link and then followed the steps to download and activate the new version. After a restart I got the above error anytime when I tried to run a backup. Then I manually installed the missing assembly 'libmono-system-management4.0' and everything seems to be running fine now.

**Comment by kenkendk** [comment]
I think this might be caused by something related to hyper-v or the "generic source" handling that is loading System.management where it should not.
