### ISSUE TITLE
Duplicati v2.0.1.22: issue restoring very large file (45 Gb)

### ISSUE THREAD

**Issue by lucatrv** [duplicati/duplicati#2048]
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** v2.0.1.22-2.0.1.22_experimental_2016-09-12
**Operating System:** Windows 7 64-bit
**Backend:** Local
### Bug description

I have a Duplicati backup with two large Virtual Machine disk images (about 45 Gb each one). If I verify the backup I get no issues. However I cannot restore one of the two disk images, and this is a big problem for me because I lost it. I copied the backup files locally in order to exclude any other element which may trigger the issue. When I click on "Restore backup" and select the backup folder, I get the following error "Detected file entries with not associated blocks". If I try to go on anyway, after waiting a few minutes (which apparently seems to work through "Building partial temporary database" and "Restoring files") Duplicati outputs the following error: "constraint failed UNIQUE constraint failed: BlocksetEntry.BlocksetID, BlocksetEntry.Index".
Please notice that I can restore the other disk image file, which however has never changed since the first time I created the Duplicati backup.
Please let me know how I could possibly provide further information on the issue if needed (e.g. how I could create a debugging log or other).
Thanks
##

**Comment by lucatrv** [comment]
Is anyone going to look into this and give me some suggestions or should I forget about my data??

**Comment by kenkendk** [comment]
You can use the `RecoveryTool.exe` to restore your virtual machine file from the commandline.
It might be a bit slow, but at least you get your data.

If you can create a bug report from the UI, I can look and see if I can find the cause of the error.

After you have created and sent the bug report, you can try to rename the local database and then rebuild it to see if that fixes things for you.

**Comment by lucatrv** [comment]
Hi, using the RecoveryTool I could finally restore my data, many thanks!!
Then I tried to re-import the local copy of the backup and to build the local database but I get the same error. I am going to send you the bug report by email, please let me know if you need other information.
I am going to keep my backup data unchanged until you tell me otherwise, just in case you need to test anything new.
Thanks

**Comment by kenkendk** [comment]
This is the same as #1699 #2140 #2178

**Comment by kenkendk** [comment]
I have made a new build that should fix the issue:
https://github.com/duplicati/duplicati/releases/tag/v2.0.1.43-2.0.1.43_canary_2017-01-19

**Comment by lucatrv** [comment]
This is the result of my test:

1. I made a clean new installation removing previous AppData/Roaming data.
2. I clicked on "Restore backup" and selected the first disk image file (which had never changed, see my original post), everything went smooth with no error messages. I could restore the file in about 1 hour.
3. I repeated the same but selecting the other disk image file (which I could not restore before). The result has only partially improved. Now I do not get any errors through the "Building partial temporary database" phase (I verified that a new database is actually created under temp files), however it gets stuck under the "Restoring files... / Scanning for local blocks..." phase. Now it has been working for about 8 hours with no results, light disk activity and CPU at 25% (my CPU has 4 logical cores).

It is still running, what should I do?
Thanks

**Comment by lucatrv** [comment]
After about 20 hours "thinking" with one core fully loaded, the "Downloading files..." phase started, and after another hour writing to disk now I have my disk image file fully recovered and verified. So at the end it worked but it took a lot of time... is this expected?
Thanks!

**Comment by kenkendk** [comment]
I was hoping the update made this faster. The "20 hours thinking" is probably the recreate phase where each file layout is built again. If you have the patience to repeat this, you can try with `--log-level=profiling --log-file=C:\logdata.txt`, then you can see exactly where the time is spent.

**Comment by lucatrv** [comment]
When I click on "Restore Backup", I see two pages (first one and second one) where I can set advanced options, where should I put `--log-level=profiling --log-file=C:\logdata.txt`?
BTW I think the difference between those two places should be better clarified in the label, or otherwise they should be unified.
Thanks

**Comment by lucatrv** [comment]
I tried to add it under "Advanced options" in the first page and did not get any log file, please let me know

**Comment by kenkendk** [comment]
I am collecting performance related issues under #2302

**Comment by kenkendk** [comment]
@lucatrv The first area is for options relating to the destination (e.g. `--use-ssl`), the second area is for the restore operation. I am surprised if you did not get any warnings about `--log-level` not being a valid advanced option on the first page?

The options for logging should be set on the second page :/.

**Comment by lucatrv** [comment]
I updated to version 2.0.1.45 and I confirm I still do not get any warnings when I put those options on the first page, and I do not get the logdata file (while I get it if I put those options on the second page).

On I side note, I noticed that clicking on the "Cancel" button while restoring does not work, should I open a new issue?
