### ISSUE TITLE
FTP Error 220

### ISSUE THREAD

**Issue by gorbiWTF** [duplicati/duplicati#2051]
I have:
- [x] searched open and closed issues for duplicates
---
### Version info

**Duplicati Version:** 2.0.1.28
**Operating System:** Windows 10 Education x64
### Bug description

I want to do a backup on my NAS, but I can only use a FTP connection. Username and password seem to work (I can connect to the share via FileZilla without any problems), the SSL certificate seems to work too.
Nonetheless I get this error message:

System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (220) **220 Client IP is in private IP address space**.
`bei Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()`
`bei Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()`
`bei Duplicati.Library.Backend.FTP.List(String filename)`
`bei Duplicati.Library.Backend.FTP.Test()`
`bei Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)`
`bei Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)`

I guess I should not use a local FTP connection? However, there is no other way for me. And I don't know why it shouldn't be allowed to use FTP in a local network.
##

**Comment by kenkendk** [comment]
I am fairly sure that is a configuration issue with your FTP server.
Try setting/unsetting the "Passive mode" checkbox and see if that fixes things.

**Comment by gorbiWTF** [comment]
But I can connect to it with FileZilla without any problems.
I tried enabling/disabling ftp-passive and ftp-regular in all combinations, same error. I tried disabling SSL, same error. I tried different ports instead of 21, same error...
When I try "FTP (Alternativ)" instead, Duplicati just crashes after some time, without any error log.

**Comment by kenkendk** [comment]
I don't know why FileZilla works, but generally it is really good at working around FTP quirks.

The error message indicates that the server attempts to connect to you IP, but then figures out it is a "private IP" and refuses to connect. Normally such a check makes sense to prevent cases where a public FTP attempts to connect back through a NAT router which does not work.

In your case, the IP is correct as the connection is on the same LAN, so I am fairly sure you need to change a setting in the FTP server.

**Comment by gorbiWTF** [comment]
Well, the NAS is really cheap so I can't change any settings. Thank you anyway 👍
