### ISSUE TITLE
There is no logout button...

### ISSUE THREAD

**Issue by macgeneral** [duplicati/duplicati#2052]
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.22_experimental_2016-09-12
**Operating System:** CentOS Linux release 7.2.1511
**Backend:**
### Bug description

There's no logout button in the Web Interface.

I run duplicati behind nginx (as reverse proxy), because of three reasons:
- duplicati runs as root (required for full system backups, dangerous for web applications with user input esp. if they are in beta/alpha state)
- duplicati is a Mono/.NET application with no separated front/backend
- duplicati brings an own webserver with minimal configuration options and minimal trust from my side ;) (+ nginx is already configured to use strong encryption algorithms only etc.)

The problem is, that I have to enable Proxy-Connection "Keep-Alive" because else nginx loses connection to the duplicati server after some time and I have to restart nginx to get it working again (else I get 404s etc.). And because http-basic Auth mechanisms are a pain with password managers I saved it in my browser -> no matter when I access the site I'm always logged in after the first login, even when changing browsers etc. (So never run duplicati behind a reverse proxy without an additional basic auth! - Everyone could access it once you logged in).
### relevant nginx configuration (in case someone is interested)

  server {
    listen [::]:443 ssl http2;

```
server_name duplicati.somewhere.tld;

client_max_body_size 128m;

root "/usr/lib/duplicati/webroot/";
access_log "/var/www/duplicati.somewhere.tld/logs/proxy_access_ssl_log";
error_log "/var/www/duplicati.somewhere.tld/logs/proxy_error_log";

# require authentication to access duplicati
auth_basic "Restricted Remote";
auth_basic_user_file "/var/www/duplicati.somewhere.tld/.htpasswd";

location / {
    # Proxy all requests to Duplicati
    proxy_pass http://127.0.0.1:8000;

    # Proxy Settings
    proxy_http_version 1.1;
    # timeouts
    proxy_connect_timeout 300s;
    proxy_send_timeout 300;
    proxy_read_timeout 300;
    # buffer
    proxy_buffer_size 32k;
    proxy_buffers 4 64k;
    proxy_busy_buffers_size 128k;
    # header sizes
    proxy_headers_hash_bucket_size 128;
    proxy_headers_hash_max_size 1024;
    proxy_redirect off;
    proxy_hide_header Vary;
    # headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #proxy_set_header Connection "Keep-Alive";
    proxy_set_header Proxy-Connection "Keep-Alive";
}
```

  }
### Steps to reproduce
- set up duplicati, run the duplicati server on localhost
- set up nginx with a configuration similar to the one above
- log in to duplicati
- switch browser and/or computer/device

**Actual result:**
 -> you are still logged in.

**Expected result:**
-> you are logged out (if duplicati was aware it's behind a proxy) or you could at least manually log out if there was a button
### Screenshots

not needed
### debug log

will create one if needed
### workaround
- restart duplicati when finished using the webinterface
- change the password in the duplicati webinterface (even if it's the same) -> you get logged out
  -> btw. you shouldn't be able to change the password without typing a) the old one and b) retyping the new one ^^
- use a SSH Tunnel instead instead of proxying with nginx
  
  `ssh -N root@server.tld -L 8000:localhost:8000`

I know this is an edge case this is why I don't ask for proxy awareness or even a separated front/backend (which is requested already and would be awesome - especially if you could just set up Apache/nginx for the web part instead of trusting some Mono/.NET server) - for now I would be happy with a simple logout button!!

Thanks for the besides great program and keep up the good work! I already restored some files from my Amazon Cloud Drive without any troubles! (never delete a folder named ~ (as root at 2 am) without escaping the character first - the recreation of the database and restoring of /root/ worked perfectly and fast :))
##

**Comment by kenkendk** [comment]
I have added a logout button now, but there are multiple issues in this issue :).

I do not understand why/how the proxy enables the authentication?
The authentication works by setting a cookie in your browser (`session-auth`), and you need to pass that to every request or it gets rejected.

Is it perhaps because nginx caches the response from the `login.cgi` call, thus giving the same login token to all users?

**Comment by macgeneral** [comment]
ok it's propably me to blame:

I have a configuration for each domain that:
  * apache hosts each website (and proxies to php-fpm if needed)
  * nginx serves static files and proxies to apache

for the duplicati domain I altered the behaviour of nginx to proxy to the duplicati server instead of apache - but I forgot to remove the basic apache configuration.

-> it seems that apache interfered with nginx and duplicati which was leading to the problem above.

Now that I've removed the apache configuration everything is as expected (switching browsers/device makes duplicati ask for a password again)


But don't ask me how this happened in first place >.<
