### ISSUE TITLE
Feature Request : show Network speed and progress bar.

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2053]
Feature Request :

Web UI should show progress of upload / Download progress bar similar to 1.3x
This can make it clear what is happening in the backgroud. I quite offen open the system monitor to see the upload or download benchmarks.

I addition also show how much data was uploaded / downloaded in the last backup / restore action in status, something like how you see in a downlod manager

**Comment by agrajaghh** [comment]
closing as duplicate of #1725 and #1808
