### ISSUE TITLE
Windows Service Installer fails

### ISSUE THREAD

**Issue by cdrfun** [duplicati/duplicati#2057]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.22_experimental_2016-09-12
**Operating System:** Windows Server 2012 Datacenter

### Bug description
When I try to install the Service as mentioned in #1768 an error occurs:
> Connot start service from command line or a debugger. A Windows Service must be installed (using installutil.exe) and then started with the ServerExplorer, Windows Service Administratice tool or the NET START command.

### Steps to reproduce
- Open console
- Go to the duplicati installation directory
- run `Duplicati.WindowsService.exe install --webservice-interface=loopback --log-retention=3M
`

**Actual result:** See bug description
**Expected result:** Installation of the service should be successful.

### Screenshots
![000014](https://cloud.githubusercontent.com/assets/146877/19716013/83cd36e6-9b59-11e6-9b47-bc5163bc494c.png)

**Comment by kenkendk** [comment]
The changes added to `Duplicati.WindowsService.exe` were introduced in 2.0.1.23.
You need at least that version to use the install feature.
Also, since `Duplicati.WindowsService.exe` does not auto-update like the other components, you need to use at least 2.0.1.23 as your "base install" version.
