### ISSUE TITLE
[Feature Request] Pause (disable) task

### ISSUE THREAD

**Issue by ashum81** [duplicati/duplicati#2058]
I have:
- [x ] searched open and closed issues for duplicates

---

I need temporary disable some tasks and continue run all others.
Now I can unschedule that task to not run.
But it will be better to disable a task with its schedule and not edit its schedule settings.

**Comment by kenkendk** [comment]
Something like a "Freeze this backup" option.

**Comment by warwickmm** [comment]
Duplicates #2765.
