### ISSUE TITLE
Using older autoupdater installed version after updating system wide installation.

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#2061]
I have:
- [x] searched open and closed issues for duplicates
---
### Version info

**Duplicati Version:** Duplicati - 2.0.1.29_canary_2016-10-27
**Operating System:** Fedora 24
**Backend:** File
### Bug description

I installed Duplicati using rpm package. After that allowed autoupdater to update to version 2.0.1.28. Then I updated rpm package to version 2.0.1.29_canary_2016-10-27.  Running Duplicati after updating the system wide installation (with duplicati-cli) gave me version 2.0.1.28. 

Removing ~/.local/share/Duplicati/ removed autoupdater versions and allowed me to use updated system version. 
### Steps to reproduce
- Install Duplicati system wide (eg. with rpm)
- Let autoupdater update the installation at least once.
- Update system wide installation to a newer version than installed by autoupdater. 
- Run Duplicati by any way that uses autoupdater versions. 

**Actual result:** Running Duplicati after updating the system wide installation (with duplicati-cli) gave me version 2.0.1.28. 

**Expected result:** Newer version installed system wide is used instead of older autoupdater installed versions. 
##

**Comment by kenkendk** [comment]
It should check the version in the auto-update folder and see that the base is newer, but I probably assumed that the user would never update the base version :).

**Comment by kakoskin1** [comment]
I just verified that this is fixed on Fedora 24. I autoupdated from 2.0.1.29 to 2.0.1.30 and upgraded base version to 2.0.1.31.
