### ISSUE TITLE
Scrollbar Down Arow not working in File Selection Dialog

### ISSUE THREAD

**Issue by telemaxx** [duplicati/duplicati#2063]
I have:
- [X] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.28_canary_2016-10-19
**Operating System:** Win7-64 with Firefox 49
**Backend:**
### Bug description

When i edit/create a Backupset inside Step2 i have the File Selection Dialog.
I can move the Filelist up with a click on the up arrow.
but the down arrow is overlaped with the resize button.
### Steps to reproduce
- edit a backupset, go to step 2.
- move a long filelist up and down

**Actual result:**  down is not possible, you have to move the slider directly.

shortlist, no scroll bar necessary , only the resize button
![scrollbar1](https://cloud.githubusercontent.com/assets/22706487/19820939/fb3d9be0-9d5b-11e6-8890-86609d27bf62.PNG)

longer list with scroll bar. down arrow is "behind" the resize button
![scrollbar2](https://cloud.githubusercontent.com/assets/22706487/19820970/2ee14082-9d5c-11e6-93d8-d61a1285e7e8.PNG)
##

**Comment by warwickmm** [comment]
This is still an issue in 2.0.5.110.
