### ISSUE TITLE
create-report appends zip even if output-file name already ends with .zip

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#2066]
I have:
- [x] searched open and closed issues for duplicates

---
### Version info

**Duplicati Version:** 2.0.1.29_canary_2016-10-27
**Operating System:** Fedora 24
**Backend:** File
### Bug description

Command "duplicati-cli create-report <output-file> appends .zip to output-file name even if output-file name already ends with .zip
### Steps to reproduce
- duplicati-cli create-report <path-to-some-backup> output-file.zip

**Actual result:** 
Duplicati produces .zip file named output-file.zip.zip.

**Expected result:** 
Duplicati produces .zip file named output-file.zip.
##

**Comment by albertony** [comment]
This issue could be closed, I guess?

**Comment by ts678** [comment]
Can this be closed based on above fix? 2.0.5.111 on Windows tests fine using `.zip`, `.ZIP`, and no suffix. You get a single suffix.
