### ISSUE TITLE
After switching from summer to winter time the next backup task is scheduled one hour too early.

### ISSUE THREAD

**Issue by cdrfun** [duplicati/duplicati#2069]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.28_canary_2016-10-19
**Operating System:** Windows NT 6.2.9200.0
**Backend:** Local Filesystem

### Bug description
After switching from summer to winter time (-1 hour) the next backup task is scheduled one hour too early.

### Steps to reproduce
- create backup task for 8:00 PM during summer time
- switch from summer to winter time

**Actual result:** backup tasks are scheduled for 7:00 PM
**Expected result:** backup tasks should be scheduled for 8:00 PM

### Screenshots
![000023-](https://cloud.githubusercontent.com/assets/146877/19851426/1c20ba82-9f5e-11e6-813b-b3a4c8f7f5b7.png)
(Older backups have the time stamp 8:00 PM, the current is scheduled for 7:00 PM. There are also other issues in this screenshot for which I'll create separate issues)

**Comment by gorbiWTF** [comment]
Same problem still occurred here in Central Europe this Sunday. Switching from UTC+1 to UTC+2 locally shouldn't change the backup schedule.

**Comment by frelis** [comment]
+1

**Comment by shoeper** [comment]
Is the schedule only changed once or multiple times? If it is only once it's imho something one can live with.

**Comment by gorbiWTF** [comment]
It changes twice a year so it's not that bad. But still annoying if you have to change the schedule on a lot of computers.

I hope they get rid of this useless summer/winter time change...

**Comment by shoeper** [comment]
Ah sorry, I did express myself badly. The question was whether for each time change the schedule is wrong exactly one time or if it is wrong permanently. In the second case it's indeed an annoying bug, in the first case I'd think it's not perfect but something one can live with.

**Comment by kenkendk** [comment]
Same as #1364  ?

**Comment by gorbiWTF** [comment]
Yes, same as #1364.

**Comment by warwickmm** [comment]
I'm going to close this as it duplicates issue #1364, which contains more discussion on possible fixes.
