### ISSUE TITLE
loading HyperV on OS X

### ISSUE THREAD

**Issue by scottscreations** [duplicati/duplicati#2077]
I have:
- [X ] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** v2.0.1.29-2.0.1.29_canary_2016-10-27
**Operating System: macOS Sierra 10.12.1 / macbook pro**
**Backend: ?**
**Mono: 4.6 Service Release 0.1 (4.6.1.5)**
### Bug description

I had my team setup duplicati 2.0 for their backups to google drive today and we have two mac users. They are both on sierra and had them first download the dmg from the website which is v2.0.1.22. They had to install mono, which is fine and that was from the mono website, version listed above. After installing both dmg applications they launched duplicati and received a no connection error. I thought that was odd and since I don't run a mac I cant debug it. I told them to go to github and download the latest under releases, that fixed it. New problem is this error, Cannot Load Type: "Duplicati.Library.Snapshots.HyperVUtility" see attachment.

I was able to have them backup just fine so I am not sure if this will affect recovery? But thought i should report my problems on the mac.

### Steps to reproduce
- Install released version 2.0.1.22 and no connection found, installed latest from github releases and it worked with a slight warning.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots
![20161101_081629](https://cloud.githubusercontent.com/assets/186373/19904207/58ada328-a037-11e6-855d-a6779c6f49a5.jpg)

### debug log
System.TypeLoadException: Could not load type 'Duplicati.Library.Snapshots.HyperVUtility' from assembly 'Duplicati.Library.Snapshots, Version=2.0.1.29, Culture=neutral, PublicKeyToken=8bfe994a39631a7b'. at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x0015d] in <f986280cc65f4d6bbf312bb4710e5538>:0

**Comment by mnaiman** [comment]
Yeah, thats my bad, I will submit fix for version 20.

**Comment by mnaiman** [comment]
It should be fixed in #2079

**Comment by kenkendk** [comment]
I merged in #2079 so this should be fixed.
There is a new experimental out now that fixes the crash-on-start for OSX, but the fix for the dialog did not make it into the experimental build.
