### ISSUE TITLE
More informations on filters

### ISSUE THREAD

**Issue by Alex131089** [duplicati/duplicati#2091]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.30_experimental_2016-11-03
**Operating System:** Win10 x64
**Backend:** ACD

### Bug description
Not sure this is a bug, but filters should get better explanation at least.
I'm trying to exclude files on a new backup. The config is like this : 
```
To backup : 
G:\To Backup\

To filter : 
-Unwanted (folder)\
-Folder\unwanted_mask1*.zip
-Unwanted mask2*.TXT
-G:\To Backup\Unwanted (folder)\
-G:\To Backup\Folder\unwanted_mask1*.zip
-G:\To Backup\Unwanted mask2*.TXT

To exclude : 
(nothing)
```

As you can guess, the idea is to exclude those paths, but according to the Count (at beginning) and the Progress shown, those files are not excluded from the backup. Are those numbers accurate from the start ? If so, my filters are not taken.

I suppose this is not correct, but I might misunderstand something.
I'm not even sure which form of the filter I should/can use, so I tried relative and absolute form.
Is there a relative form ?
Like "(root)\ToExclude\" where "(root)\" is relative to the folder(s) to backup ?

**Actual result:**
According to the progress, files seems to be backuped.

**Expected result:**
G:\To Backup\Unwanted (folder)\
G:\To Backup\Folder\unwanted_mask1*.zip
G:\To Backup\Unwanted mask2*.TXT
are excluded and progress (&count at start) doesn't count those files.

**Comment by agrajaghh** [comment]
does this help you? https://github.com/duplicati/duplicati/wiki/How-do-filters-work%3F

But I agree, we should probably offer some kind of help in the UI

**Comment by Alex131089** [comment]
~~@agrajaghh : not really, I read it and just reread it, and I couldn't understand what could be wrong in the filter rules I mentionned.
I checked the backup : the file that should have been excluded are included. The only one that worked is `Unwanted mask2*.TXT` (or `G:\To Backup\Unwanted mask2*.TXT`I don't know).
`Unwanted (folder)\` is present
`Folder\unwanted_mask1*.zip` are presents~~
I'm just stupid, I missed a character in the folder name, sorry about that.
Absolute vs relative notation can still be enlightened though. Maybe a file/folder selector for the filters too ?
This is a nice project, thank you for this !

**Comment by agrajaghh** [comment]
> Maybe a file/folder selector for the filters too ?
> This is a nice project, thank you for this !

what do you mean exactly? You can already deselect a subfolder in the treeview which will automatically create a filter

**Comment by Alex131089** [comment]
@agrajaghh well, I said nothing :) I must have been very tired when I did this because I didn't even tried to uncheck the subfolder ..

**Comment by fabricioobregon** [comment]
Thank you guys! I didn't use the complete path too. Duplicati is always surprising me, never thought that I could uncheck the subfolder.
