### ISSUE TITLE
Every file is rescanned entirely instead of timestamp comparison when resuming

### ISSUE THREAD

**Issue by rstein** [duplicati/duplicati#2101]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.31_canary_2016-11-03
**Operating System:** Ubuntu 14.04.5 LTS
**Backend:** ACD

### Bug description
When resuming an initial backup duplicati seems to rescan every file instead of comparing the timestamps of the files that have already been processed before. This takes (in my case for a 2TB backup nearly finished) about 20 hours. After that duplicati continues the upload normally with the files that have not been uploaded yet.

### Steps to reproduce
- Create a new backup
- Let it run for a while
- Stop it
- Resume it

**Actual result:** duplicati seems to be rechecking every file entirely (at least the progressstate in the webinterface is indicating so with changing file names and offsets).
**Expected result:** duplicati should compare the timestamps of the files that have already been uploaded with those on the local filesystem to determine whether a file has changed / needs to be uploaded.

### debug log
Profiling live log gets a couple hundred of these every minute:
> 6. Nov. 2016 13:48: ExecuteScalar: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
> 6. Nov. 2016 13:48: Starting - ExecuteScalar: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?

Information live log has these for every file:
> 6. Nov. 2016 13:50: Checking file for changes /mnt/XX.mkv, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 03/05/2016 09:59:48 vs 01/01/0001 00:00:00
> 6. Nov. 2016 13:50: New file /mnt/XX.mkv

**Comment by axelvugts** [comment]
I'm also having this issue (mentioned in #2047)

**Comment by kenkendk** [comment]
The idea is that the paths are matched with the database to see if there is an existing version of the file, and then skips the check if the time stamps have not changed.

The trace shows `new: True`, which indicates that somehow, a file with that path was not found in the database.

For one of the paths that report `new: True` could you look in the local database to see if the file is really not present? You can use any SQLite editor for it, like this: http://sqlitebrowser.org/
You can see the local database path if you export the backup to commandline and look for `--dbpath=/path/name.sqlite`


You should be able to find the path in the `File` table, under the `Path` column.
Since you are both on Linux (with case-sensitive file systems) I am guessing this is related to the problem.

**Comment by rstein** [comment]
@kenkendk, I have checked the database, here is what I found:

`SELECT * FROM File WHERE Path = '/mnt/data3/Files/Xyz/Abc 1/abcDEF.dat';`

| ID | Path | BlocksetID |MetadataID |
|---|------|------------|------------|
| 1943 | /mnt/data3/Files/Xyz/Abc 1/abcDEF.dat | 3529 | 1730 |

---

`SELECT * FROM Blockset WHERE ID = 3529;`

| ID | Length | FullHash |
|---|--------|----------|
| 3529 | 2192602307 | AVG3V4wJO9oe/l4gczQLrv0SzT5OYt4OXWGfp2wiASI= |

---

`SELECT * FROM Metadataset WHERE ID = 1730;`

| ID | BlocksetID |
|---|------------|
| 1730 | 3528 |

---

I have checked a couple of entries. They always look similar and the files are exactly named like on the filesystem.

**Comment by kenkendk** [comment]
@rstein: The actual query that is used is a bit more complex, and looks like this:

```
SELECT "File"."ID" AS "FileID", "FilesetEntry"."Lastmodified", "FileBlockset"."Length", "MetaBlockset"."Fullhash" AS "Metahash", "MetaBlockset"."Length" AS "Metasize"
  FROM "File", "FilesetEntry", "Fileset", "Blockset" "FileBlockset", "Metadataset", "Blockset" "MetaBlockset"
 WHERE "File"."Path" = "/mnt/data3/Files/Xyz/Abc 1/abcDEF.dat"
   AND "FilesetEntry"."FileID" = "File"."ID" AND "Fileset"."ID" = "FilesetEntry"."FilesetID"
   AND "FileBlockset"."ID" = "File"."BlocksetID"
   AND "Metadataset"."ID" = "File"."MetadataID" AND "MetaBlockset"."ID" = "Metadataset"."BlocksetID"
 ORDER BY "Fileset"."Timestamp" DESC
 LIMIT 1
```

Not sure how well-versed you are with SQL, but if you can try that query, it can maybe help troubleshoot the problem.

Do you have something for:
`SELECT * FROM FilesetEntry WHERE FileID = 1943`

**Comment by rstein** [comment]
@kenkendk The complex query returns 0 rows because the query for the FilesetEntry already returns 0 rows.

`SELECT * FROM FilesetEntry WHERE FileID = 1943;`
> 0 rows returned

As a matter of fact:
`SELECT COUNT(*) FROM FilesetEntry;`

| COUNT(*) |
|-----------|
| 0 |

Could it be the case that FilesetEntries are not written until the backup completely finishes?

**Comment by kenkendk** [comment]
Yes, that would explain it.

What about  the`Fileset` table, is that empty as well?

Then it is related to #2038.

**Comment by rstein** [comment]
`SELECT COUNT(*) FROM Fileset;`

| COUNT(*) |
|-----------|
| 0 |

Indeed, that one is empty, too.

**Comment by rstein** [comment]
I had a look on the issue you referenced, which states that the backups fail to continue. This is not the case here because after comparing every file hash duplicati indeed resumes the backup.
I guess this one could be fixed by saving the timestamp of each file in the local database directly when the backend confirms the upload as completed.
My backup should complete tomorrow if it does not get stuck before, so I should be able to test stopping and resuming to provide some more data from the sqlite database then.

**Comment by kenkendk** [comment]
I think I figure out the problem.

If you stop the backup, Duplicati will produce a "synthetic" filelist, which is "previous filelist" + "current files". Since there is no "previous filelist", the result is 0 files instead of just "current files".

**Comment by rstein** [comment]
Yes, sounds like that could be the problem.

The initial backup of my drive is finished now. Also, the queries now return reasonable results:

`SELECT "File"."ID" AS "FileID", "FilesetEntry"."Lastmodified", "FileBlockset"."Length", "MetaBlockset"."Fullhash" AS "Metahash", "MetaBlockset"."Length" AS "Metasize"
  FROM "File", "FilesetEntry", "Fileset", "Blockset" "FileBlockset", "Metadataset", "Blockset" "MetaBlockset"
 WHERE "File"."Path" = "/mnt/data3/Files/Xyz/Abc 1/abcDEF.dat"
   AND "FilesetEntry"."FileID" = "File"."ID" AND "Fileset"."ID" = "FilesetEntry"."FilesetID"
   AND "FileBlockset"."ID" = "File"."BlocksetID"
   AND "Metadataset"."ID" = "File"."MetadataID" AND "MetaBlockset"."ID" = "Metadataset"."BlocksetID"
 ORDER BY "Fileset"."Timestamp" DESC
 LIMIT 1`

| FileID | Lastmodified | Length | Metahash | Metasize |
|-------|--------------|--------|-----------|----------|
| 1941 | 635433052600000000 | 2389508466 | 6xE9qGLooUo7BNuqxm1AWbWBJ8bRkO8aylfX69wEDv4= | 196 |

Stopping and resuming the backup now works as expected without hash verification. So it is safe to say that this issue indeed only affects the initial backup.
