### ISSUE TITLE
Error in "Add new backup"

### ISSUE THREAD

**Issue by pascalBokBok** [duplicati/duplicati#2106]
My first click in duplicati ('add new backup') gave the following error. 
![image](https://cloud.githubusercontent.com/assets/639487/20042518/8cfc6d2e-a47b-11e6-90ba-47a4017c598d.png)
Clicking away and clicking 'add new backup' again gave the following error:
![image](https://cloud.githubusercontent.com/assets/639487/20042547/352c14ea-a47c-11e6-8b03-e12dc3ca1062.png)

The log is showing something about hyperv which in my world is a windows hypervisor but it might be something else here:
Nov 6, 2016 11:53 PM: Request for http://127.0.0.1:8200/api/v1/hyperv gave error
Nov 6, 2016 11:53 PM: Reporting error gave error
Nov 6, 2016 11:52 PM: Request for http://127.0.0.1:8200/api/v1/hyperv gave error
Nov 6, 2016 11:52 PM: Reporting error gave error
Nov 6, 2016 11:45 PM: Request for http://127.0.0.1:8200/api/v1/hyperv gave error
Nov 6, 2016 11:45 PM: Reporting error gave error

### Version info
**Duplicati Version:** 2.0.1.30
**Operating System:** Ubuntu 16.04 / KDE Neon
**Backend:** Stock / default. don't really know about this. It's my first time using 2.0

**Comment by agrajaghh** [comment]
@mnaiman

**Comment by mnaiman** [comment]
Im going to replicate that on Ubuntu

**Comment by mnaiman** [comment]
@pascalBokBok can you try to update to 31? It is working on my ubuntu machine

**Comment by mnaiman** [comment]
![screenshot from 2016-11-07 22-22-37](https://cloud.githubusercontent.com/assets/2264442/20076475/cd655156-a538-11e6-9075-a5d2a2c1abbf.png)

**Comment by thrnz** [comment]
Here's a screenshot from 30 showing the offending request:
http://imgur.com/8Cv0Oho

In my case, updating to 31 fixes it. It was only an issue on Ubuntu 16.04 x64 for me, and not in Windows 10 x64.
