### ISSUE TITLE
SFTP & command line via batch file = server fingerprint ssh-rsa failed 

### ISSUE THREAD

**Issue by vitekf** [duplicati/duplicati#2109]
### Version info

**Duplicati Version:** 2.0.1.30_experimental_2016-11-03
**Operating System:** Windows 7
**Backend:**

### Bug description
Exporting task as Command Line return HTML URL Encoded string for RSA key (...&ssh-fingerprint=ssh-rsa%202048%206B%3AD6%3AB0%3A86%3AAE...)
It works fine only if you copy and paste it directly to command line.
If you save it to backup.bat and run it from batch file, it returns Error: "Validation of server fingerprint failed. Server returned fingerprint "ssh-rsa 2048 6b:d6:b0:86:ae..."

### Solution:
- replace %20 by space " "
- replace %3A by colon ":"
It shoud look like "...&ssh-fingerprint=ssh-rsa 2048 6B:D6:B0:86:AE..." and this works both ways (directly to command line or batch file

### Expected solution:
Do not use HTML URL Encoding for RSA key

**Comment by kenkendk** [comment]
I think I will fix this the other way around: Support URL encoded input, as the "connection uri" is supposed to look like a real url.

**Comment by lupinehorror** [comment]
hi.
still getting this with version 2.0.1.35 released 13/12/16. should i wait for the next release?

**Comment by agrajaghh** [comment]
@lupinehorror the patch should be included in 2.0.1.35. Can you try the newest release (2.0.1.40) just to be sure please?

**Comment by warwickmm** [comment]
This should be fixed.  If not, please feel free to reopen.
