### ISSUE TITLE
New backup only when enrcypted option selected // not possible to delete backup - no captcha

### ISSUE THREAD

**Issue by rodnheli** [duplicati/duplicati#2110]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------
**Duplicati Version:** v2.0.1.31-2.0.1.31_canary_2016-11-03
**Operating System:** Linux Mint 18 x64

### Bug description
After fresh install i can't create new backup on local folder (or also sftp/ssh) without choosing "encryption" on general backup settings page.

### Steps to reproduce
- create new backup (choose no encryption)
- storage path is e.g. local folder (also tried sftp /ssh)
- at the end of backup wizard i want to click save - nothing happens (also no output in error log)
- if i change encryption (e.g. AES) i can save and run backup

--> tried e.g with v2.0.1.22, creating new backup works without choosing encrpytion.

issue 2:
if i want to delete the backup there's no captcha - see picture.

![delete](https://cloud.githubusercontent.com/assets/20946404/20072451/b5621ad6-a528-11e6-99ff-72db9d6febed.JPG)

**Comment by telemaxx** [comment]
i can confirm this 2 Bugs.
1.captcha is not shown, backup can be deleted so.
2. new backups cant be created, without encryption

**Comment by kenkendk** [comment]
@telemaxx It will be fixed in the next build
