### ISSUE TITLE
Headless duplicati

### ISSUE THREAD

**Issue by timonoj** [duplicati/duplicati#2112]
Hi, I'm trying to run this on a headless Banana Pi which already has a nginx running for a different app, Seafile.
When I try this, it just crashes with:

 

>    $ duplicati --webservice-interface=192.168.0.5 --webservice-password=testing
>     Server has started and is listening on 192.168.0.5, port 8200
>     Crash!
>     System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
>     at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x00000] in :0
>     at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in :0
>     --- End of inner exception stack trace ---
>     at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in :0
>     at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.OnAsync (IAsyncResult r) [0x00000] in :0
>     --- End of inner exception stack trace ---
>     at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in :0
>     at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in :0
>     at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod (System.Reflection.MethodInfo method, System.String[] args) [0x00000] in :0
> 
>     Unhandled Exception:
>     System.Net.WebException: Error: ConnectFailure (Connection refused)
> 
>     Server stack trace:
>     at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in :0
>     at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.OnAsync (IAsyncResult r) [0x00000] in :0
> 
>     Exception rethrown at [0]:
>     ---> System.Net.Sockets.SocketException: Connection refused
>     at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x00000] in :0
>     at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in :0
>     --- End of inner exception stack trace ---
>     at (wrapper xdomain-invoke) System.AppDomain:ExecuteAssemblyByName (string,string[])
>     at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
>     at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) [0x00000] in :0
>     at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) [0x00000] in :0
>     [ERROR] FATAL UNHANDLED EXCEPTION: System.Net.WebException: Error: ConnectFailure (Connection refused)
> 
>     Server stack trace:
>     at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in :0
>     at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.OnAsync (IAsyncResult r) [0x00000] in :0
> 
>     Exception rethrown at [0]:
>     ---> System.Net.Sockets.SocketException: Connection refused
>     at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x00000] in :0
>     at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in :0
>     --- End of inner exception stack trace ---
>     at (wrapper xdomain-invoke) System.AppDomain:ExecuteAssemblyByName (string,string[])
>     at (wrapper remoting-invoke-with-check) System.AppDomain:ExecuteAssemblyByName (string,string[])
>     at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent (System.Reflection.MethodInfo method, System.String[] cmdargs, AutoUpdateStrategy defaultstrategy) [0x00000] in :0
>     at Duplicati.GUI.TrayIcon.Program.Main (System.String[] args) [0x00000] in :0
> 
> 

If I specify --webservice-interface=any, it says it listens on 0.0.0.0, and it doesn't really work. But if I use the server's own IP, I get a connection refused, I reckon because it's in use by nginx (even though it's not the same port). Is there a way around this?

**Comment by ts678** [comment]
I searched all GitHub issues for ConnectFailure refused, but (ignoring the same report in another issue), found only one with a different stack trace, so whatever is going on is rare, and the release (which was not named) is old. Is this issue still happening?

Specific remarks:

>  I get a connection refused, I reckon because it's in use by nginx (even though it's not the same port). Is there a way around this?

The Connect failure in the stack trace probably means nothing is listening. Port conflicts generally show up on server listen side.

> If I specify --webservice-interface=any, it says it listens on 0.0.0.0, and it doesn't really work.

That isn't very clear.

To pursue this, one option might have been to try to figure out the port 8200 activity which possible involves several interfaces. Duplicati currently lets one change the interface as you did, and that would show up in, say, a `netstat` or `lsof` info for 8200. Sometimes one can see leftover TCP states too, even after the processes have gone down. It's not clear what that connect is for.

When running a TrayIcon (as you are -- but why on a headless server?), it connects to a server component hosted in its process. Typically I would expect a headless setup to run `duplicati-server`, and then maybe a Connect error would not have occurred.
