### ISSUE TITLE
Submit B2 integration

### ISSUE THREAD

**Issue by robsonsobral** [duplicati/duplicati#2113]
It would be good to see Duplicati listed among other [B2 integrated apps](https://www.backblaze.com/b2/integrations.html).

There's a [checklist for it](https://www.backblaze.com/b2/docs/integration_checklist.html):

- [ ] Uploading files
- [ ] Multithreading uploads
- [ ] Multithreading downloads
- [ ] Handling error response status codes
- [ ] Managing metadata for interoperability
- [ ] Deleting file versions

**Comment by JonMikelV** [comment]
I think this is still a valid suggestion and we may have naturally moved closer to satisfying the requirements, but I think we're still not "there" in some areas such as multithreading uploads/downloads and large file support.

**Comment by warwickmm** [comment]
Duplicati is listed, and I believe satisfies the requirements.
