### ISSUE TITLE
 Failed to connect: SQLite error no such table: LogData 

### ISSUE THREAD

**Issue by timonoj** [duplicati/duplicati#2116]
Hi guys,

I'm trying to run my first backup, but I hit repeatedly this error and I'm not allowed to continue:
Mono.Data.Sqlite.SqliteException: SQLite error
no such table: LogData
  at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, UInt32 timeoutMS, System.String& strRemain) [0x00000] in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x00000] in <filename unknown>:0 
Mono.Data.Sqlite.SqliteException: SQLite error
no such table: LogData
  at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, UInt32 timeoutMS, System.String& strRemain) [0x00000] in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x00000] in <filename unknown>:0 

Running duplicati-server on ARM-based BananaPi, running Ubuntu.

**Comment by agrajaghh** [comment]
did you delete the issue template or did you use a mobile device to create this issue?

What version are you using? What backup settings? What backend? What OS?

**Comment by timonoj** [comment]
Issue template...You refer to the backup schedule I added? I created it using the browser. I deleted it several times, but each time I create a new backup, at runtime I get the error again.
Duplicati - 2.0.1.31_canary_2016-11-03 (ARM)
Backup settings...
Backup to ACD with AES256 Encryption. Backup source is several NFS mapped folders (around 1.3TB). No filters. Upload size 100MB. Advanced options: tempdir and dbpath remapped to a path in another drive to avoid getting the main drive full.

**Comment by doktorjw** [comment]
I'm having this same issue running Duplicati - 2.0.2.1_beta_2017-08-01.

It took me a while to create a backup configuration that used a tempdir, etc., where I wanted, so I did go through several cases of deleting profiles, creating new ... and once the backup completed, I was confronted with this error when attempting to look at the log (to inspect the 83 errors that occurred during the backup).

**Comment by ts678** [comment]
> Running duplicati-server on ARM-based BananaPi, running Ubuntu.

I only have an Ubuntu derivative on x86-64, and it can run a backup.

> I was confronted with this error when attempting to look at the log

Job log and server log work. It's likely that code is better than in 2017.

Anybody still interested in this, and seeing it? Might need steps again.
