### ISSUE TITLE
"Please run repair" - how do I do that?

### ISSUE THREAD

**Issue by ronnyle** [duplicati/duplicati#2118]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.30_experimental_2016-11-03
**Operating System:** Win10
**Backend:** AWS S3

### Bug description
```
Error while running <MyBackup>
Found 1 remote files that are not recorded in local storage, please run repair
```

I couldn't find out what I should do..

**Comment by bithost** [comment]
@ronnyle, to run database repair, press on your created backup set and under advanced you will see Manage database:
![image](https://cloud.githubusercontent.com/assets/4540096/20208901/b8c2d32c-a7f9-11e6-81cb-871e5a55b2e3.png)

I hope that helps.

**Comment by ronnyle** [comment]
@bithost thanks for the prompt reply, it helped :)
I didn't expect to find the repair under "manage database"...

**Comment by agrajaghh** [comment]
@ronnyle did repair solve your problem?

**Comment by ronnyle** [comment]
it did, thanks

**Comment by CottonEaster** [comment]
Forgive me, but this constitutes a fairly gross 'user inferface fail' - no?

**Comment by kenkendk** [comment]
@CottonEaster Do you have a suggestion for how to structure the menu?

**Comment by CottonEaster** [comment]
@ kenkendk 
It seems to me that the main thing is telling the user where to find the operation to which the program is referring him/her. That is: it doesn't matter so much where you put it, as that you tell the user where you've put it. Better still would be providing a mechanism - some sort of link or button - that would take the user there, directly from the error message.

**Comment by MatejKovacic** [comment]
I had similar issue. Maybe there should be a button (when warning is displayed) - "run repair now" or something similar?

**Comment by iBobik** [comment]
The easiest interface will be like this:
<img width="514" alt="snimek obrazovky 2017-09-19 v 14 30 22" src="https://user-images.githubusercontent.com/614232/30592601-b35c4500-9d47-11e7-9139-1167f9bbd6a7.png">
Error message will contain a button Repair (in place of Show what will show logs - nothing helpful) and this button will immediately start repair process.

**Comment by comodoro** [comment]
UI bug confirmed on Duplicati - 2.0.2.1_beta_2017-08-01. I consider myself being able to find things around 
in the system but had to go here to find the repair option, you cannot expect that from an average user.

**Comment by dptsolutions** [comment]
Yeah, this confused the heck out of me too. If at the very least add some sort of indicator that the repair option is under database. 

Maybe Advanced -> Database -> Repair instead of just "repair in the message?

**Comment by davidearl** [comment]
I just had to look this up as well (and found this thread), didn't know where to find it. Repair as an option on the dialog would be the best IMO, but it needs to be in the menus somewhere as well.

But why is there an error in the first place?

But having found repair, it still complains, but when I click "Show" to see the errors, there's nothing there, only old ones. It started off complaining "3 files missing" now it's saying "1 Files missing", but with no clue as to what, why or where.

**Comment by mongolianmiller** [comment]
Still an issue with current experimental build. 1.21.18.

**Comment by nuhll** [comment]
wow still not fixed. sad.

**Comment by just-ak** [comment]
Had the same problem, and running repair fixed the problem. 
As I want to use this on PC's with novice users if a presumption of repair is needed then run the repair automatically on detection of the problem, report the problem only if something still exists.  Set and Forget should always be the aim when tools will be used by unskilled users.

**Comment by AGSPhoenix** [comment]
@kenkendk This issue is not fixed in 2.0.3.3_beta_2018-04-02. No Repair button appears:
![image](https://user-images.githubusercontent.com/450785/39095339-ebfac936-460c-11e8-92bc-0f182c01a733.png)

**Comment by DreamFlasher** [comment]
@kenkendk This is not fixed -- there is no repair button, also in the UI there is missing a description what happens when you do the repair. Will any data on the remote be deleted?

**Comment by rorrison** [comment]
Just got the same message in 2.0.3.3, and had to Google to find this thread to find out what to do.  There's still no clue in the message that to run repair as advised you need to go into the database settings.

**Comment by rctneil** [comment]
I too had too look this up when i hit this problem. A tweak to the UX would help dramatically.

**Comment by rsenn1** [comment]
I just got this error and had to come here to find out how to run Repair.

**Comment by veleek** [comment]
@rorrison - Just wanted to quickly point out that this has already been fixed but there has not been a beta release since the change was made.  Next release should include the fix.

**Comment by mrtumnus** [comment]
I just got this error and had to come here to find out how to run Repair.

**Comment by deKay01** [comment]
Found this thread looking for the same thing - repair, where it is, is not intuitive at all.

**Comment by freaktechnik** [comment]
With the new UI it's now in the ⋮ menu under "Database" and then you get the repair option. (but yeah, still not discoverable or obvious from the error)

**Comment by mpdunlop** [comment]
Found this on google while trying to determine where the "Repair" feature was hidden. Even just updating the error message to include the word "Database" ("Run Repair to fix it" -> "Run Database Repair to fix it") would help.
