### ISSUE TITLE
Export Config option repeat passphase

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2120]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2..0.30
**Operating System:*Any*
**Backend:*Any*

### Bug description
Exporting backup configuration with password should have a repeat field.
 
### Steps to reproduce
- Click export.
- To File
- Encrypt file
There should be 2 password fields here, to conform and avoid problems when importing again when needed.

**Comment by ts678** [comment]
[added passphrase confirmation #3557](https://github.com/duplicati/duplicati/pull/3557) seems to resolve this. Can issue be closed?

**Comment by warwickmm** [comment]
Yes, I think so.  Thanks @ts678.
