### ISSUE TITLE
Actual Calendar Dates in "Last successful run" / "Next scheduled run" [$20]

### ISSUE THREAD

**Issue by NickPyz** [duplicati/duplicati#2124]
Requests adding the ability to display actual calendar dates (November 10th) versus "Last Thursday" as a configurable option.

"Tomorrow" and "Last Tuesday" is fine when the user has a few backup jobs, but it's more difficult to visualize the big picture when there are many scheduled jobs. 

This is purely a cosmetic request. It isn't intended to change functionality in any way.

**Comment by hausmonarch** [comment]
I'd go a bit farther than this being purely cosmetic; it is actually confusing. Where I grew up, "Last Wednesday" (for example) means the Wednesday prior to the immediately preceding Wednesday (in other words, more than a week ago). I am writing this on a Friday; I have a machine that backed up two days ago (Wednesday) but failed last night, and the backup log says the last successful backup was "Last Wednesday". To my English that means the backup hasn't happened in 9 days. It would be clearer to just have a date and/or "X days ago" for the last successful backup.

**Comment by sNiXx** [comment]
I absolutely agree, this would be a lot clearer. That is why I backed this issue on bountysource!

**Comment by mikaelmello** [comment]
In case you didn't know, the actual date is displayed when you hover the mouse over the dates of each backup and the progress bar.
