### ISSUE TITLE
Option to list files modified/added to a version

### ISSUE THREAD

**Issue by sftwr-ngnr** [duplicati/duplicati#2128]
I have:
- [X ] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.32
**Operating System:** Windows 7, x64
**Backend:** local drive

### Feature description
I'd like to have an option to see which files/folders were marked as modified or added in a version ('version' as the same definition as for the 'find' command). 
As far as I tried and understood, this is not possible right now (please correct me if I am wrong and show me how).
I know about the option to start the server with debug log information, but I'd like to retrieve the information from the backup data and not from huge debug log files.

Thanks.

**Comment by warwickmm** [comment]
I believe this can be done using the [compare command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-compare-command).
