### ISSUE TITLE
Securing Web-UI via SSL-Certificate is not working

### ISSUE THREAD

**Issue by deHoeninger** [duplicati/duplicati#2133]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.32_canary_2016-11-12
**Operating System:** Ubuntu 14.04.5 LTS
**Backend:** not relevant

### Bug description
I'm currently trying to secure Duplicati's WebInterface with a Let's encrypt SSL Certificate but I could not get it to work until now. The Interface is still accessible via http.

### Steps to reproduce
I'm starting the server with the following parameters:

mono Duplicati.Server.exe --webservice-port=8200 --webservice-interface=any --webservice-sslcertificatefile=/etc/letsencrypt/live/***/cert.pem --webservice-password=***

**Actual result:** Server is starting and accessible via http but not via https on port 8200. No error-messages are shown during startup
**Expected result:** Server is only accessible via https.

### debug log

Nothing related, just telling server has been started.

**Comment by mnaiman** [comment]
certificate file should be pfx format

**Comment by Tischi86** [comment]
Hi,

I try to start the server with a self signed cert.
If I try to start the server with a pfx certificate:
````
mono /usr/lib/duplicati/Duplicati.Server.exe --webservice-port=40000 --webservice-interface=any --webservice-sslcertificatefile=/root/YOURPKCS.pfx --webservice-password=foobar
A serious error occurred in Duplicati: System.NotSupportedException: Operation is not supported.
  at System.Security.Cryptography.X509Certificates.X509Certificate.Export (X509ContentType contentType, System.Byte[] password) [0x00000] in <filename unknown>:0
  at System.Security.Cryptography.X509Certificates.X509Certificate.Export (X509ContentType contentType) [0x00000] in <filename unknown>:0
  at Duplicati.Server.Database.ServerSettings.set_ServerSSLCertificate (System.Security.Cryptography.X509Certificates.X509Certificate2 value) [0x00000] in <filename unknown>:0
  at Duplicati.Server.WebServer.Server..ctor (IDictionary`2 options) [0x00000] in <filename unknown>:0
  at Duplicati.Server.Program.RealMain (System.String[] args) [0x00000] in <filename unknown>:0
````

With the `pem` file the server starts, but https not working and no errors displayed anywhere.

**Comment by mnaiman** [comment]
Hi, on first look, it is Linux/mono issue because it is not implemented in mono.
[https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate20.cs](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Security.Cryptography.X509Certificates/X509Certificate20.cs)

I will take a look on alternatives

**Comment by Tischi86** [comment]
My first workaround is:
* start the duplicati server only on `127.0.0.1`
* install nginx with SSL and proxy it

```
location / {
        proxy_pass http://127.0.0.1:8200;
}
```

**Comment by mnaiman** [comment]
I have added support for certificates under Linux.
https://github.com/duplicati/duplicati/pull/2314

**Comment by mnaiman** [comment]
It should be working now in latest release.

**Comment by warwickmm** [comment]
I think this can be closed.
