### ISSUE TITLE
Duplicati doesn't install with Mono

### ISSUE THREAD

**Issue by Petrouchka** [duplicati/duplicati#2135]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:**duplicati-2.0.1.30_experimental_2016-11-03-x64
**Operating System:**Windows 7 Pro SP1
**Backend:**

### Bug description
When installing Duplicati, I've got a message "The .NET Framework 4.5 must be installed".

### Steps to reproduce
- Install mono-4.6.2.7-x64-0.msi and mono-4.6.2.7-gtksharp-2.12.38-win32-0.msi
- Install duplicati-2.0.1.30_experimental_2016-11-03-x64.msi

**Actual result:** When installing Duplicati, I've got a message "The .NET Framework 4.5 must be installed".
**Expected result:** Should install without error.

### Screenshots
![capture du 2016-11-21 09-59-20](https://cloud.githubusercontent.com/assets/3955499/20476618/351959ca-afd2-11e6-92f6-06347aa277f5.png)

![capture du 2016-11-21 10-08-40](https://cloud.githubusercontent.com/assets/3955499/20476690/811e70ee-afd2-11e6-89bf-bfd3154fa698.png)

**Comment by kenkendk** [comment]
You can use the zip distribution instead. The MSI just copies in the files, the same as the zip, and adds a shortcut to `Duplicati.GUI.TrayIcon.exe` in the Start Menu's "Startup" folder.

**Comment by Petrouchka** [comment]
I downloaded duplicati-2.0.1.32_canary_2016-11-12.zip and launched Duplicati.GUI.TrayIcon.exe, same error :
![capture du 2016-11-21 10-42-30](https://cloud.githubusercontent.com/assets/3955499/20477831/d2ea5316-afd7-11e6-86a7-70f828d883f2.png)

**Comment by kenkendk** [comment]
Yes, to run with mono, you must invoke "mono" and then the application.

An easy way is to press cmd+R (to get the "Run ..." dialog up).
Then type `mono` in the box, and drag the executable into the dialog to get the path filled.
Then press `ENTER` and it should run.

**Comment by Petrouchka** [comment]
I'm testing Duplicati before distributing it in next version of http://www.numopen.fr/compilibre
I will wait until Mono works out-of-the-box with Duplicati. For the moment, I will recommand to use .NET.
