### ISSUE TITLE
Unable to restore files after crash

### ISSUE THREAD

**Issue by silverfern999** [duplicati/duplicati#2138]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version: 2.0.1.30
**Operating System: ubuntu 16.04
**Backend: 

### Bug description
When issuing duplicati-cli restore for a file, the following messages are received:

Operation Get with file duplicati-be4f18555a1cc4a34bf77ec2169803248.dblock.zip.aes attempt 5 of 5 failed with message: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection. => Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

Could not find file "/home/xxxxxxxxxx/.gourmet/recipes.db". => Could not find file "/home/xxxxxxxx/.gourmet/recipes.db".
Failed to restore 1 files, additionally the following files failed to download, which may be the cause:
duplicati-be4f18555a1cc4a34bf77ec2169803248.dblock.zip.aes

Had to rebuild DB by using to get around the hash size issue
AUTOUPDATER_Duplicati_SKIP_UPDATE=1 duplicati-:cli repair /mnt/backups/Kubuntu/duplicati

**Comment by silverfern999** [comment]
After also installed libmono-system-management4.0 libmono-microsoft-csharp4.0-cil

**Comment by kenkendk** [comment]
Can you try again with `--debug-output`?
That should give a stack trace that tells where the problem is found.

**Comment by silverfern999** [comment]
Kenneth,

This is the error I got:

Jan 23, 2017 4:42 PM: Failed to patch with remote file: "duplicati-
b9c8ce751a6274f43b2a95f31b8d83821.dblock.zip.aes", message: Offset and length 
were out of bounds for the array or count is greater than the number of 
elements from index to the end of the source collection.
{"ClassName":"System.Security.Cryptography.CryptographicException","Message":"Offset 
and length were out of bounds for the array or count is greater than the 
number of elements from index to the end of the source 
collection.","InnerException":
{"ClassName":"System.ArgumentException","Message":"Offset and length were out 
of bounds for the array or count is greater than the number of elements from 
index to the end of the source 
collection.","InnerException":null,"HelpURL":null,"StackTraceString":"  at 
System.Buffer.BlockCopy (System.Array src, Int32 srcOffset, System.Array dst, 
Int32 dstOffset, Int32 count) <0x401faa10 + 0x0024b> in <filename unknown>:0 \n  
at Mono.Security.Cryptography.SymmetricTransform.InternalTransformBlock 
(System.Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, System.Byte[] 
outputBuffer, Int32 outputOffset) <0x40576350 + 0x0013e> in <filename unknown>:
0 \n  at Mono.Security.Cryptography.SymmetricTransform.FinalDecrypt 
(System.Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) <0x4068bff0 + 
0x00094> in <filename unknown>:0 \n  at 
Mono.Security.Cryptography.SymmetricTransform.TransformFinalBlock 
(System.Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) <0x4069fcd0 + 
0x00081> in <filename unknown>:0 \n  at 
System.Security.Cryptography.CryptoStream.FlushFinalBlock () <0x4069fa70 + 
0x0004d> in <filename unknown>:0 \n  at 
System.Security.Cryptography.CryptoStream.Dispose (Boolean disposing) 
<0x4069f930 + 0x00038> in <filename unknown>:0 \n  at 
SharpAESCrypt.SharpAESCrypt+ClosingCryptoStream.Dispose (Boolean disposing) 
<0x406a2c90 + 0x00024> in <filename unknown>:0 
","RemoteStackTraceString":null,"RemoteStackIndex":
0,"HResult":-2147024809,"Source":"mscorlib","ExceptionMethod":null,"Data":null,"ParamName":null},"HelpURL":null,"StackTraceString":"  
at Duplicati.Library.Main.AsyncDownloader+AsyncDownloaderEnumerator
+AsyncDownloadedFile.get_TempFile () <0x406a3760 + 0x0002f> in <filename 
unknown>:0 \n  at Duplicati.Library.Main.Operation.RestoreHandler.DoRun 
(Duplicati.Library.Main.Database.LocalDatabase dbparent, IFilter filter, 
Duplicati.Library.Main.RestoreResults result) <0x406cd810 + 0x00e29> in 
<filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":
0,"HResult":-2146233296,"Source":"Duplicati.Library.Main","ExceptionMethod":null,"Data":null}

**Comment by ts678** [comment]
The "after crash" in the title isn't described later, but interruption testing (i.e. killing Duplicati) has led to various improvements.

Does the problem happen on a current release?
