### ISSUE TITLE
"Object reference not set to an instance of an object" error when trying to restore backup from SFTP (SSH) storage

### ISSUE THREAD

**Issue by xpertuse** [duplicati/duplicati#2139]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.0.7
**Operating System: ** Windows Server 2012R2

### Bug description
When selecting to restore files the connection to the SFTP (SSH) folder cannot be completed and I am getting the following message "Object reference not set to an instance of an object". 

**Actual result:** "Object reference not set to an instance of an object"
**Expected result:** List the backup folder tree

**Comment by agrajaghh** [comment]
can you please post the full error message? You can click on it on the log section

**Comment by kenkendk** [comment]
Closing for lack of feedback
