### ISSUE TITLE
Consider updating System.Data.Sqlite

### ISSUE THREAD

**Issue by kunom** [duplicati/duplicati#2144]
Duplicati 2.0.1.30 bundles System.Data.SQLite version 1.0.93.0.

When recreating the local DB (e.g. #2050) and taking a snapshot of the main thread's call stack, then I frequently see
```
6, System.Data.SQLite.UnsafeNativeMethods.CheckAssemblyCodeBase(System.Reflection.Assembly, System.String ByRef) + 0x39 <-- 0x7fe96edfb39
7, System.Data.SQLite.UnsafeNativeMethods.GetAssemblyDirectory() + 0x44 <-- 0x7fe96edf9b4
8, System.Data.SQLite.UnsafeNativeMethods.GetXmlConfigFileName() + 0x49 <-- 0x7fe96edf919
9, System.Data.SQLite.UnsafeNativeMethods.GetSettingValue(System.String, System.String) + 0x135 <-- 0x7fe96edf625
10, System.Data.SQLite.SQLiteConvert.GetDefaultDbType() + 0x14 <-- 0x7fe96ef9b84
11, System.Data.SQLite.SQLiteConvert.TypeNameToDbType(System.Data.SQLite.SQLiteConnection, System.String, System.Data.SQLite.SQLiteConnectionFlags) + 0x35 <-- 0x7fe96ef9835
12, System.Data.SQLite.SQLiteDataReader.GetSQLiteType(System.Data.SQLite.SQLiteConnectionFlags, Int32) + 0xc7 <-- 0x7fe96ef90f7
13, System.Data.SQLite.SQLiteDataReader.VerifyType(Int32, System.Data.DbType) + 0x35 <-- 0x7fe96f00485
14, System.Data.SQLite.SQLiteDataReader.GetInt64(Int32) + 0x6b <-- 0x7fe96f0040b
```

This corresponds to [this](https://system.data.sqlite.org/index.html/tktview/25d53b48f6f26c523fd8) and [this](https://system.data.sqlite.org/index.html/tktview/58ed318f2fadb5e0feff) tickets of System.Data.SQLite. Both tickets are now closed.

Therefore, I suggest updating System.Data.Sqlite and maybe consider using the NoConvertSettings connection flag (see section 1.0.94.0 of the [release notes](https://system.data.sqlite.org/index.html/doc/trunk/www/news.wiki)).

**Comment by kenkendk** [comment]
That was an old version I had found there :)

From what I can read, using the latest version (1.0.104.0) there is no need to use `NoConvertSettings` as that is applied automatically?

**Comment by kunom** [comment]
Based on the last two comments of https://system.data.sqlite.org/index.html/tktview/58ed318f2fadb5e0feff and with some testing with 1.0.104.0 in Visual Studio, I'd say that 
a) With just upgrading you get the caching behaviour (per connection) for free
b) `NoConvertSettings` has to be activated explicitly. However, it is not yet clear to me what functionality is turned off (something related to _DefaultDbType_) and how expensive that functionality is after the changes with 1.0.94.0 and later.
