### ISSUE TITLE
"Object reference not set to an instance of an object" error when restoring on a windows 7 a backup from a linux docker image

### ISSUE THREAD

**Issue by resys** [duplicati/duplicati#2146]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

**Duplicati Version:** 2.0.1.22 and 2.0.1.31
Tests was perfomed with 
- 2.0.1.22 **or** 2.0.1.31 as backuping and restoring computer at the same time.
- No mixing of versions

**Operating System:** 
- Backup : Docker image running on open media vault 2.0 (debian 3.16.0-0.bpo.4-amd64 )
- Restore : Windows 7 computers (tried several) - Duplicati is lunch from the directory extracted from the .zip (no installation)

**Backend:** Amazon cloud drive

### Bug description
info : All operations are manage over the web interface
info : **Backup and restoration performed from the docker image are OK**

When restoring from windows 7 : 
- Duplicati can connect to the amazon cloud to get the DB
- When the available dates are listed, I get the error return "Object reference not set to an instance of an object" (in french)
- The list of available files is empty

![duplicati error](https://cloud.githubusercontent.com/assets/14292898/20623606/ad4e5164-b308-11e6-92ec-b3e6150914c1.PNG)

### Steps to reproduce
info : Performed from several docker image and several windows 7 desktops.
- create backup from linux on docker image
   options used  : 
--skip-metadata=true
--zip-compression-level=0
--tempdir=/media/duplicati/temp

- restore from windows

**Actual result:** error message
**Expected result:** list of available files for restoration

**Comment by resys** [comment]
t seems that I have badly looked in the open bug list. I just found the bug # 1983.

Sorry

If you confirm, I will close this issue request.

**Comment by agrajaghh** [comment]
yeah looks like #1983 

closing as duplicate
