### ISSUE TITLE
Running Duplicati on Qnap NAS

### ISSUE THREAD

**Issue by drod3763** [duplicati/duplicati#2150]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.32
**Operating System:** QNAP Firmware 4.2.2
**Backend:** Mono 4.6.2.7

### Bug description
Installed a copy of Mono and Duplicati. Was able to upload a small 140kb file to Amazon Cloud Drive. Updated my configuration and added a second folder which caused a "Previous volume not finished, call FinishVolume before starting a new volume".

### Steps to reproduce

1. Start a backup using Run Now with a small File.
2. Wait for it to finish.
3. Edit the config and add another File/Folder.
4. Start a second backup using Run Now.

**Actual result: Files fail with two errors.
**Expected result: Files upload successfully.

From Stored Log Data:
* Nov 29, 2016 9:52 PM: Failed while executing "Backup" with id: 2
`
System.InvalidOperationException: Previous volume not finished, call FinishVolume before starting a new volume
  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.StartVolume (System.String filename) [0x00016] in <54974545e0184c8fa11b54d8d57d094f>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.UpdateIndexVolume () [0x00043] in <54974545e0184c8fa11b54d8d57d094f>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes (Duplicati.Library.Main.BackendManager backend) [0x0016c] in <54974545e0184c8fa11b54d8d57d094f>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x00424] in <54974545e0184c8fa11b54d8d57d094f>:0 
`

From Live Log data (2 errors)
* Nov 29, 2016 9:52 PM: Failed disposing index volume
`
{"ClassName":"System.InvalidOperationException","Message":"Attempted to dispose an index volume that was being written","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.Dispose () [0x00016] in <54974545e0184c8fa11b54d8d57d094f>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.Dispose () [0x00045] in <54974545e0184c8fa11b54d8d57d094f>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Duplicati.Library.Main"}
`

* Nov 29, 2016 9:52 PM: The operation Backup has failed with error: Previous volume not finished, call FinishVolume before starting a new volume
`{"ClassName":"System.InvalidOperationException","Message":"Previous volume not finished, call FinishVolume before starting a new volume","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.Volumes.IndexVolumeWriter.StartVolume (System.String filename) [0x00016] in <54974545e0184c8fa11b54d8d57d094f>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.UpdateIndexVolume () [0x00043] in <54974545e0184c8fa11b54d8d57d094f>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.FinalizeRemoteVolumes (Duplicati.Library.Main.BackendManager backend) [0x0016c] in <54974545e0184c8fa11b54d8d57d094f>:0 \n  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x00424] in <54974545e0184c8fa11b54d8d57d094f>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Duplicati.Library.Main"}
`

Anyone here can make sense of this? Tried searching in the Google Group and Github (open and closed) for answers and couldn't find much. 

I tried repairing the database and didn't run into any issues. It completes with a "Destination and database are synchronized, not making any changes" message.

Deleting the config and starting a new one appears to work fine until I try a second backup.

**Comment by free-ed** [comment]
I face exactly the same issue. Tested with all version since 2.0.1.29 on QNAP T-251 (v4.2.2)

Mono Version:
`Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Sat Nov 21 10:02:10 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen`

**Comment by Tischi86** [comment]
Hi,

this problem is caused by the tmp path. Duplicati's default path is `/tmp/` and is to small in your qnap.
Just move it to your HDD

1. Create a new shared folder in qnap called `tmp` (set invisible, no recycler ...)
2. In Duplicati under settings -> Default options -> add `tempdir` and set to `/share/tmp/`

now it should work

**Comment by drod3763** [comment]
That worked for me thanks!
