### ISSUE TITLE
How to merge multiple backups with same passphase

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2152]
I have:
- [\/ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.0.32
**Operating System:**
**Backend: Windows Share

I had a backup with about 120 versions, later due to some connectivity issues backups began to fail and i created an new backup job with the same sources and passphrase to a new target.
I have now rebuilt the database of the old backup job.

Can I merge both backups in a single target and maintain all versions that would be (120+4) 124 versions.

**Comment by kenkendk** [comment]
I have not considered this before, but I think you can.

Delete the local database, then put all the remote files into the same folder.
Then run a `repair` operation to build a local database.
The local database should now contain 124 versions.
If there is duplicated data, you can run the `compact` command to flush out unused duplicated data.
