### ISSUE TITLE
Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by jkaberg** [duplicati/duplicati#2154]
So I tried installing latest Duplicati from GH and everything went smooth until I tried to run an backup job of my HyperV VM's, where I got the `Could not load file or assembly 'AlphaVSS.60.x64.dll' or one of its dependencies.`

Thanks to @quincunx at the Gitter channel I found out that I need the .NET 3.5 framework and "Microsoft Visual C++ 2010 Redistributable Package (x64)" 

After installing these the HyperV backup was successfull.

Point of this issue is to bring this to light, and perhaps these dependencies should be bundled with the official Windows installer? Or at the very least mention it somewhere that these are needed

**Comment by kenkendk** [comment]
I have added a note here:
https://github.com/duplicati/duplicati/wiki/FAQ#user-content-windows-vss

But we should add a more prominent note somewhere, preferably augment the error message to hint that this could be the problem. Maybe we can even check for C++ Redist, so we can say for sure if it is missing.

**Comment by crystalgreen** [comment]
I ran into the same issue

> Could not load file or assembly 'AlphaVSS.x64.dll' or one of its dependencies.

I updated to Duplicity version 2.0.1.61_experimental_2017-05-30. I figured out that it uses [AlphaVSS v1.4.0.0 ](https://github.com/alphaleonis/AlphaVSS/releases/tag/1.4.0)
The release notes of that library state:

> Now requires Visual C++ Redistributable for Visual Studio **2017**

I installed the x64 version I found [here](https://go.microsoft.com/fwlink/?LinkId=746572) and then it worked.

It seems, your [FAQ](https://github.com/duplicati/duplicati/wiki/FAQ#user-content-windows-vss) entry is out of date. The better solution would be to ensure those dependencies are checked/installed by your MSI. Of course you need to update this if you update libraries like AlphaVSS.

**Comment by mr-flibble** [comment]
I think this issue can be closed. [Visual C++ 2015 redist package](https://www.microsoft.com/en-us/download/details.aspx?id=52685) is solution.

PS: I tried to make the [FAQ](https://github.com/duplicati/duplicati/wiki/FAQ#user-content-windows-vss) about AlphaVSS clearer

**Comment by crystalgreen** [comment]
As I wrote, I don't believe you need the Visual C++ 2015 redist but the Visual C++ __2017__ redist package. This is stated in the release notes of AlphaVSS 1.4.0.0 (which you are using) and it worked for me.

**Comment by mr-flibble** [comment]
@crystalgreen Hi, in last week I tried Duplicati (latest beta) on two servers (2008 and 2016) and 2015 C++ was only thing i needed. But I guess using a newer version will not hurt :)

**Comment by crystalgreen** [comment]
@mr-flibble [This](https://developercommunity.visualstudio.com/content/problem/14701/visual-c-redistributable-for-visual-studio-2015-ca.html) explains why it seems to work with 2017:

> The Visual C++ 2017 RC Redistributable is a binary-compatible in-place upgrade of the Visual C++ 2015 Redistributable and shares the same registry keys. 

IMO one is save side using 2017 as demanded by AlphaVSS.

Why don't you add a test in the Windows installer that checks if the correct vcredist is installed? This way the user knows what is missing. (Not everyone reads the FAQ before install.)
Here some links how to do it: 
[Example check for vcredist 2010](http://www.davidmoore.info/blog/2010/06/30/how-to-detect-if-the-visual-c-2010-redistributable-package-is-installed-with-wix-2/)
[Registry keys to check for different vcredist installs](https://stackoverflow.com/a/34209692/1654527)
Of course there are more fancy ways building a bootstrapper that downloads and installs the vcredist if missing but at least the above would be very helpful.

**Comment by hepter** [comment]
Manual solution of the problem.

Open the *.csproj file with your own notepad

     <PropertyGroup Condition="............">
    .....other props...
    
    <Prefer32Bit>false</Prefer32Bit>
    
     </PropertyGroup>

**Comment by StefanBrand** [comment]
I got this warning in Ubuntu 20.04:

```
Warning-Duplicati.Library.DynamicLoader.DynamicLoader`1-SoftError]: Failed to load process type Duplicati.Library.Common.IO.VssBackupComponents assembly /usr/lib/duplicati/Duplicati.Library.IO.dll, error message: Could not load type of field 'Duplicati.Library.Common.IO.VssBackupComponents:_vssBackupComponents' (1) due to: Could not load file or assembly 'AlphaVSS.Common, Version=1.4.0.0, Culture=neutral, PublicKeyToken=959d3993561034e3' or one of its dependencies.
```

Any way to suppress this warning?

**Comment by drwtsn32x** [comment]
@StefanBrand 

That error was fixed in PR https://github.com/duplicati/duplicati/pull/4178  - you can have access to the fix on the latest Canary version.

If you don't want to jump from Beta to Canary, you can get rid of the warning but manually copying a dll from the zip per this post here:

https://github.com/duplicati/duplicati/issues/4149#issuecomment-650839821

**Comment by warwickmm** [comment]
Was this issue addressed by #4178?

**Comment by warwickmm** [comment]
I believe this was fixed by pull request #4178.

**Comment by pbnelson** [comment]
I solved this on my Linux Mint 20.1 system by downloading `AlphaVSS.Common.dll` (version v4.0.30319, 68096 bytes) and moving it to `/usr/lib/duplicati/AlphaVSS.Common.dll`. Note that the command `duplicati-cli system-info` actually reproduced the warning for me, making it much easier to resolve.

**Comment by lowski** [comment]
@pbnelson where did you download `AlphaVSS.Common.dll` (version v4.0.30319) from?

**Comment by ts678** [comment]
> where did you download AlphaVSS.Common.dll (version v4.0.30319) from?

I can't speak for anyone else, but see [earlier post](https://github.com/duplicati/duplicati/issues/2154#issuecomment-703870396) to obtain .zip file of binaries.
