### ISSUE TITLE
Ftp to Router (Fritz!Box) failes

### ISSUE THREAD

**Issue by schludi63** [duplicati/duplicati#2158]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 1.3.4.0
**Operating System:** Win10
**Backend:** FRITZ!Box 7490

### Bug description
I'm having problems with duplicati 1.3.4 while saving via ftp to my FRITZ!Box router with attached USB-harddisk. It failes always with the following error. No problems with other ftp-clients on that device. Found the same problem from other users in the net, but no solution :-(. Any hints?

### Steps to reproduce
- both, full and incremental backup fail with below message
- "test" of the ftp-credentials works correctly

**Actual result:** Backup fails (no connection)
**Expected result:** "normal" backup to ftp-device

### debug log
 BackupType : Incremental
TypeReason : Ein vollständiges Backup wird durchgeführt, weil das letzte vollständige Backup vom 10.07.2016 10:28:34 ist und das nächste Voll-Backup am 1M erfolgen soll.
BeginTime : 07/10/2016 13:00:00
EndTime : 07/10/2016 13:02:58
Duration : 00:02:58.1662092
DeletedFiles : 0
DeletedFolders : 0
ModifiedFiles : 0
AddedFiles : 7
AddedFolders : 0
ExaminedFiles : 7
OpenedFiles : 7
SizeOfModified : 0
SizeOfAdded : 173332355
SizeOfExamined : 173332355
Unprocessed : 30153
TooLargeFiles : 0
FilesWithError : 0
Executable : Duplicati, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library : Duplicati.Library.Main, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName : Backup
BytesUploaded : 94481810
BytesDownloaded : 5651
RemoteCalls : 34
NumberOfErrors : 1
****************
Misserfolg nach dem Hochladen von 8 Volumes. Fehlermeldung: Fehler Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. beim Hochladen der Datei "duplicati-inc-manifestA.20160710T110005Z.manifest.aes"
****************
NumberOfWarnings: 1
****************
Auto-Bereinigung wurde angegeben, aber es gibt 3 verwaiste Dateien, und es sollten nicht mehr als 2 sein
****************
NumberOfRetries : 5
RetryOperations : 5

Ergebnis des Aufräumens:
Error: System.Exception: Dateiauflistung nicht aufrufbar: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
bei System.Net.FtpWebRequest.CheckError()
bei System.Net.FtpWebRequest.GetResponse()
bei Duplicati.Library.Backend.FTP.List(String filename)
bei Duplicati.Library.Main.BackendWrapper.ListInternal()
--- Ende der internen Ausnahmestapelüberwachung ---
bei Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
bei Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
bei Duplicati.Library.Main.BackendWrapper.GetBackupSets()
bei Duplicati.Library.Main.Interface.DeleteAllButNFull()
bei Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
bei System.Net.FtpWebRequest.CheckError()
bei System.Net.FtpWebRequest.GetResponse()
bei Duplicati.Library.Backend.FTP.List(String filename)
bei Duplicati.Library.Main.BackendWrapper.ListInternal()

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
