### ISSUE TITLE
Remove old caching settings

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#2163]
There was an in-memory cache system prior to optimizing the database queries.

This is no longer maintained and should be deleted, this affects the following options:
```
blockhash-lookup-memory
filehash-lookup-memory
metadatahash-lookup-memory
old-lookup-memory-defaults
disable-filepath-cache
```

**Comment by warwickmm** [comment]
I believe this was removed in revision d8972b0f2b0b8fdc851c2c680876c8d2e2ba0bf2.
