### ISSUE TITLE
Exception (Crash) when cancelling running backup task

### ISSUE THREAD

**Issue by fishhead2567** [duplicati/duplicati#2164]
I have:
- [-] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** Current Master from source [57c42f0]
**Operating System:** Raspbian Jesse
**Backend:** Google Drive

### Bug description
When cancelling a backup of my 1tb MyBookLive while the status still reads "counting files", the server will crash with the exception attached at the bottom. 

### Steps to reproduce
- Start backup of large database
- while "counting files", cancel the backup.
- Duplicati crashes.

**Actual result:** Duplicati Crashes and loses connection to web gui
**Expected result:** Duplicati will exit the backup and inform me of its success

### debug log
Server has started and is listening on 192.168.1.202, port 8200
STATE CUE CARD: (? means a positive number, usually 1 or 2, * means any number)
        0x0     - starting (GOOD, unless the thread is running managed code)
        0x1     - running (BAD, unless it's the gc thread)
        0x2     - detached (GOOD, unless the thread is running managed code)
        0x?03   - async suspended (GOOD)
        0x?04   - self suspended (GOOD)
        0x?05   - async suspend requested (BAD)
        0x?06   - self suspend requested (BAD)
        0x*07   - blocking (GOOD)
        0x?08   - blocking with pending suspend (GOOD)
--thread 0x748ca560 id 0x6b5ff450 [(nil)] state 1
--thread 0x74875a30 id 0x6bae8450 [(nil)] state 105
--thread 0x748c5ea0 id 0x6d7ff450 [(nil)] state 1
--thread 0x7489c970 id 0x6d8ff450 [(nil)] state 1
--thread 0x748cb018 id 0x6f843450 [(nil)] state 1
--thread 0x748967f8 id 0x705ff450 [(nil)] state 1
--thread 0x748d0210 id 0x722ff450 [(nil)] state 1
--thread 0x748ca0d8 id 0x725ff450 [(nil)] state 1
--thread 0x7489eb70 id 0x72ba3450 [(nil)] state 1
--thread 0x73411850 id 0x72c0b450 [(nil)] state 1
--thread 0x73108f80 id 0x72d62450 [(nil)] state 1
--thread 0x7300aeb8 id 0x72eff450 [(nil)] state 1
--thread 0x8ae858 id 0x72fff450 [(nil)] state 1  GC INITIATOR
--thread 0x7489cf08 id 0x732ff450 [(nil)] state 1
--thread 0x73100478 id 0x733ff450 [(nil)] state 1
--thread 0x73700478 id 0x73915450 [(nil)] state 1
--thread 0x748c1a28 id 0x73e40450 [(nil)] state 1
--thread 0x73d00478 id 0x73f9b450 [(nil)] state 1
--thread 0x74800478 id 0x76aef450 [(nil)] state 1
--thread 0x2f5e00 id 0x76d4d000 [(nil)] state 1
WAITING for 1 threads, got 0 suspended
suspend_thread suspend took 200 ms, which is more than the allowed 200 ms
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Threading.Thread.Abort_internal (System.Threading.InternalThread,object) <0x0003f>
  at System.Threading.Thread.Abort () <0x0001b>
  at Duplicati.Library.Main.Operation.BackupHandler.Run (string[],Duplicati.Library.Utility.IFilter) <0x00fcf>
  at Duplicati.Library.Main.Controller/<Backup>c__AnonStorey0.<>m__0 (Duplicati.Library.Main.BackupResults) <0x009bf>
  at Duplicati.Library.Main.Controller.RunAction<T_REF> (T_REF,string[]&,Duplicati.Library.Utility.IFilter&,System.Action`1<T_REF>) <0x0011b>
  at Duplicati.Library.Main.Controller.Backup (string[],Duplicati.Library.Utility.IFilter) <0x001d3>
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner/IRunnerData,bool) <0x00c9b>
  at Duplicati.Server.Program.<RealMain>m__1 (Duplicati.Server.Runner/IRunnerData) <0x00017>
  at Duplicati.Library.Utility.WorkerThread`1<Tx_REF>.Runner () <0x004ab>
  at System.Threading.ThreadHelper.ThreadStart_Context (object) <0x0009f>
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x001fb>
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x0002b>
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) <0x0005b>
  at System.Threading.ThreadHelper.ThreadStart () <0x0002f>
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <0x000c7>

Native stacktrace:

Debug info from gdb:

[New LWP 6264]
[New LWP 6261]
[New LWP 6260]
[New LWP 6259]
[New LWP 6258]
[New LWP 6257]
[New LWP 6256]
[New LWP 6249]
[New LWP 6245]
[New LWP 6180]
[New LWP 6179]
[New LWP 5805]
[New LWP 5804]
[New LWP 5803]
[New LWP 5802]
[New LWP 5800]
[New LWP 5797]
[New LWP 5796]
[New LWP 5793]
[New LWP 5792]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x76ec77a4 in __pthread_cond_wait (cond=0x2ee028, mutex=0x2ee00c) at pthread_cond_wait.c:187
187     pthread_cond_wait.c: No such file or directory.
  Id   Target Id         Frame
  21   Thread 0x763ff450 (LWP 5792) "SGen worker" 0x76ec77a4 in __pthread_cond_wait (cond=0x2509f8, mutex=0x2509e0) at pthread_cond_wait.c:187
  20   Thread 0x76aef450 (LWP 5793) "Finalizer" 0x76ec9a40 in do_futex_wait (isem=isem@entry=0x2489b8) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
  19   Thread 0x73f9b450 (LWP 5796) "Main" 0x76e10830 in read () at ../sysdeps/unix/syscall-template.S:81
  18   Thread 0x73915450 (LWP 5797) "Timer-Scheduler" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x2edb60, mutex=0x2edb44, abstime=0x73914338) at pthread_cond_timedwait.c:199
  17   Thread 0x733ff450 (LWP 5800) "UpdatePollThrea" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x2ee0b0, mutex=0x2ee094, abstime=0x733fe300) at pthread_cond_timedwait.c:199
  16   Thread 0x72fff450 (LWP 5802) "WorkerThread<IR" 0x76ecbef8 in __libc_waitpid (pid=6270, stat_loc=0x72ffd59c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
  15   Thread 0x72eff450 (LWP 5803) "TaskScheduler" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x2ee4f0, mutex=0x2ee4d4, abstime=0x72efe1b0) at pthread_cond_timedwait.c:199
  14   Thread 0x72d62450 (LWP 5804) "Main" 0x76ec77a4 in __pthread_cond_wait (cond=0x2ee688, mutex=0x2ee66c) at pthread_cond_wait.c:187
  13   Thread 0x72c0b450 (LWP 5805) "Main" 0x76e15b80 in poll () at ../sysdeps/unix/syscall-template.S:81
  12   Thread 0x725ff450 (LWP 6179) "Backend Async W" 0x76ec77a4 in __pthread_cond_wait (cond=0x2f28f0, mutex=0x2f28d4) at pthread_cond_wait.c:187
  11   Thread 0x6bae8450 (LWP 6180) "Read ahead file" 0x76d7c298 in do_sigsuspend (set=0x2512e4) at ../sysdeps/unix/sysv/linux/sigsuspend.c:31
  10   Thread 0x705ff450 (LWP 6245) "Threadpool work" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x705fed78) at pthread_cond_timedwait.c:199
  9    Thread 0x6b5ff450 (LWP 6249) "Threadpool work" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x6b5fed78) at pthread_cond_timedwait.c:199
  8    Thread 0x6f843450 (LWP 6256) "Threadpool work" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x2ef018, mutex=0x2eeffc, abstime=0x6f841b98) at pthread_cond_timedwait.c:199
  7    Thread 0x732ff450 (LWP 6257) "Threadpool work" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x732fed78) at pthread_cond_timedwait.c:199
  6    Thread 0x6d8ff450 (LWP 6258) "Threadpool work" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x6d8fed78) at pthread_cond_timedwait.c:199
  5    Thread 0x6d7ff450 (LWP 6259) "Threadpool work" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x6d7fed78) at pthread_cond_timedwait.c:199
  4    Thread 0x72ba3450 (LWP 6260) "Threadpool work" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x72ba2d78) at pthread_cond_timedwait.c:199
  3    Thread 0x722ff450 (LWP 6261) "Threadpool work" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x722fed78) at pthread_cond_timedwait.c:199
  2    Thread 0x73e40450 (LWP 6264) "Main" 0x76ec7b30 in __pthread_cond_timedwait (cond=0x2511d8, mutex=0x2511c0, abstime=0x73e3fd3c) at pthread_cond_timedwait.c:199
* 1    Thread 0x76d4d000 (LWP 5790) "Main" 0x76ec77a4 in __pthread_cond_wait (cond=0x2ee028, mutex=0x2ee00c) at pthread_cond_wait.c:187

Thread 21 (Thread 0x763ff450 (LWP 5792)):
#0  0x76ec77a4 in __pthread_cond_wait (cond=0x2509f8, mutex=0x2509e0) at pthread_cond_wait.c:187
#1  0x00163398 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 20 (Thread 0x76aef450 (LWP 5793)):
#0  0x76ec9a40 in do_futex_wait (isem=isem@entry=0x2489b8) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
#1  0x76ec9af4 in __new_sem_wait (sem=0x2489b8) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:69
#2  0x0011f37c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 19 (Thread 0x73f9b450 (LWP 5796)):
#0  0x76e10830 in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x74320038 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 18 (Thread 0x73915450 (LWP 5797)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x2edb60, mutex=0x2edb44, abstime=0x73914338) at pthread_cond_timedwait.c:199
#1  0x00167d48 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 17 (Thread 0x733ff450 (LWP 5800)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x2ee0b0, mutex=0x2ee094, abstime=0x733fe300) at pthread_cond_timedwait.c:199
#1  0x00167d48 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 16 (Thread 0x72fff450 (LWP 5802)):
#0  0x76ecbef8 in __libc_waitpid (pid=6270, stat_loc=0x72ffd59c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00082928 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 15 (Thread 0x72eff450 (LWP 5803)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x2ee4f0, mutex=0x2ee4d4, abstime=0x72efe1b0) at pthread_cond_timedwait.c:199
#1  0x00167d48 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 14 (Thread 0x72d62450 (LWP 5804)):
#0  0x76ec77a4 in __pthread_cond_wait (cond=0x2ee688, mutex=0x2ee66c) at pthread_cond_wait.c:187
#1  0x00167e00 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 13 (Thread 0x72c0b450 (LWP 5805)):
#0  0x76e15b80 in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00110092 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 12 (Thread 0x725ff450 (LWP 6179)):
#0  0x76ec77a4 in __pthread_cond_wait (cond=0x2f28f0, mutex=0x2f28d4) at pthread_cond_wait.c:187
#1  0x00167e00 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 11 (Thread 0x6bae8450 (LWP 6180)):
#0  0x76d7c298 in do_sigsuspend (set=0x2512e4) at ../sysdeps/unix/sysv/linux/sigsuspend.c:31
#1  __GI___sigsuspend (set=0x2512e4) at ../sysdeps/unix/sysv/linux/sigsuspend.c:45
#2  0x00184b40 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 0x705ff450 (LWP 6245)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x705fed78) at pthread_cond_timedwait.c:199
#1  0x0010e842 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 9 (Thread 0x6b5ff450 (LWP 6249)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x6b5fed78) at pthread_cond_timedwait.c:199
#1  0x0010e842 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 8 (Thread 0x6f843450 (LWP 6256)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x2ef018, mutex=0x2eeffc, abstime=0x6f841b98) at pthread_cond_timedwait.c:199
#1  0x00167d48 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (Thread 0x732ff450 (LWP 6257)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x732fed78) at pthread_cond_timedwait.c:199
#1  0x0010e842 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (Thread 0x6d8ff450 (LWP 6258)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x6d8fed78) at pthread_cond_timedwait.c:199
#1  0x0010e842 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0x6d7ff450 (LWP 6259)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x6d7fed78) at pthread_cond_timedwait.c:199
#1  0x0010e842 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0x72ba3450 (LWP 6260)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x72ba2d78) at pthread_cond_timedwait.c:199
#1  0x0010e842 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0x722ff450 (LWP 6261)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x893208, mutex=0x893238, abstime=0x722fed78) at pthread_cond_timedwait.c:199
#1  0x0010e842 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x73e40450 (LWP 6264)):
#0  0x76ec7b30 in __pthread_cond_timedwait (cond=0x2511d8, mutex=0x2511c0, abstime=0x73e3fd3c) at pthread_cond_timedwait.c:199
#1  0x00183798 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x76d4d000 (LWP 5790)):
#0  0x76ec77a4 in __pthread_cond_wait (cond=0x2ee028, mutex=0x2ee00c) at pthread_cond_wait.c:187
#1  0x00167e00 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted

**Comment by warwickmm** [comment]
Support for interrupting a backup should be much improved now (since 2.0.5.104).  If this is still an issue, please feel free to reopen with new details.
