### ISSUE TITLE
Log timestamps have wrong time zone

### ISSUE THREAD

**Issue by kakoskin1** [duplicati/duplicati#2165]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.34_canary_2016-12-05
**Operating System:** Fedora 25 and Windows 10
**Backend:** File

### Bug description
Timestamps in the log file have time zone indicator Z, which means that they are UTC timestamps. Timestamps are actually using local time.

**Actual result:** Timestamps in the log file have Z indicating UTC time zone but are in local time.
**Expected result:** Timestamps have correct time zone indicator, either still in local time zone or are converted to UTC timestamps. Another way to deal with this is to drop entire time zone indicator to indicate local time.

See for example the output of followng command:
```
$duplicati-cli backup ~/temp/Duplicati-test/ ~/Asiakirjat/git/ --no-ecryption=1 --log-file=Duplicati.log --log-level=Information --dbpath=test.sqlite && date

Backup started at 8.12.2016 23.24.08
Checking remote backup ...
  Listing remote folder ...
----Snip------
  Data downloaded: 45,31 MB
Backup completed successfully!
to 8.12.2016 23.27.15 +0200
```

Compare this to the last log entries in the generated log file:
```
2016-12-08 23:27:11Z - Information: Backend event: Get - Completed: duplicati-icceef07eeabc4f799d9b11375f980d6f.dindex.zip (133,13 KB)
2016-12-08 23:27:11Z - Information: Backend event: Get - Started: duplicati-b4249d08f37ce43cfaef22fc2ef435832.dblock.zip (44,98 MB)
2016-12-08 23:27:13Z - Information: Backend event: Get - Completed: duplicati-b4249d08f37ce43cfaef22fc2ef435832.dblock.zip (44,98 MB)
```

Note that local time has UTC offset +2 hours but Duplicati claims that to be UTC time.

**Comment by irstmon** [comment]
Confirming this on Windows, too. Noticed my emails having UTC instead of GMT+1

**Comment by Panja0** [comment]
Still the same problem here with v2.0.1.53 on Ubuntu 16.04.2 LTS.
I'm on GMT+2 timezone, the logs and backup reports (sent by mail) are on UTC.

**Comment by Athep** [comment]
I have the same issue with version 2.0.1.55_canary_2017-04-06. Windows.

**Comment by NoLooseEnds** [comment]
@kenkendk I still have this issue in latest canary build from 1th of october.

**Comment by Ric878** [comment]
I am also still having this issue
