### ISSUE TITLE
ERROR : Failed to fetch path information Filter for list-folder-contains must be a path prefix.......

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2166]
I have:
- [Yes] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.34
**Operating System:*Windows 2008*
**Backend:*Windows Share*

### Bug description
I get a error like 

> ERROR : Failed to fetch path information Filter for list-folder-contains must be a path prefix with no wildcards Parameter name : filter

### Steps to reproduce
- Select a backup for restore in ngax or greeno (both)
- click restore files
- see the bug

**Actual result:** Failed to fetch path information Filter for list-folder-contains must be a path prefix with no wildcards Parameter name : filter
**Expected result:** Should list directories and files in backup

### Screenshots

![dup](https://cloud.githubusercontent.com/assets/12080676/21039958/c22adb8e-be07-11e6-9ab9-f73b899cc95a.png)

**Comment by kenkendk** [comment]
Is this a cross-os issue (i.e. created on Linux, restore on Windows) ?

Or does the path contain special characters? like `;` ?

**Comment by ts678** [comment]
No response to 2017 question.

> click restore files

definitely does not always error. Can we get a more current, more specific update for this? If not, it probably can't be pursued.
