### ISSUE TITLE
Could not load type 'Duplicati.Library.Snapshots.HyperVUtility' from assembly 'Duplicati.Library.Snapshots, Version=2.0.1.30

### ISSUE THREAD

**Issue by free2open** [duplicati/duplicati#2169]
I have:
- [x] searched open and closed issues for duplicates
https://github.com/duplicati/duplicati/issues/2077
https://github.com/duplicati/duplicati/pull/2079

By the way, potential typo:
- Duplicati computes a SHA-256 has value -> (hash) value
http://www.duplicati.com/articles/Backup-Process/

- think, we it deserves -> think (that) it deserves
http://www.duplicati.com/news/Updates-and-website/
----------------------------------------

### Version info

**Duplicati Version: duplicati-2.0.1.30_experimental_2016-11-03.dmg
**Operating System: OS X El Capitan 10.11.6 (15G1108)
**Backend: MonoFramework-MDK-4.6.2.7.macos10.xamarin.universal.pkg

### Bug description
1. This is my first time installing Duplicati for trial.  On opening it for the first time, an error message popups on http://127.0.0.1:8200/ngax/index.html#/add

2. After closing Duplicati, it cannot restart even AFTER killing all the three processes listed in the debug log.

 
### Steps to reproduce
- Double click on Duplicati in /Applications with a Standard user privilege.

**Actual result: Cannot open Duplicati again after closing the web UI, even after killing the processes below.

**Expected result: Duplicati should be able to restart and open the web UI.

### debug log
Could not load type 'Duplicati.Library.Snapshots.HyperVUtility' from assembly 'Duplicati.Library.Snapshots, Version=2.0.1.30, Culture=neutral, PublicKeyToken=8bfe994a39631a7b'.
Describe here the issue that you are experiencing.

After closing the above web page, Duplicati cannot restart with the following error message:
You can’t open the application “Duplicati” because it is not responding.

ps output AFTER the web UI has closed:

beta          15848   0.0  0.0  2438504    804   ??  S     8:00am   0:00.01 /bin/bash /local/stow/duplicati-2.0.1.30/bin/Duplicati.app/Contents/MacOS/duplicati
beta          15875   0.0  0.3  2547400  23352   ??  S     8:00am   0:00.94 /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /local/stow/duplicati-2.0.1.30/bin/Duplicati.app/Contents/Resources/OSXTrayHost/osx-trayicon-rumps.py
beta          15852   0.0  0.7   775184  58780   ??  S     8:00am   0:03.61 Duplicati Duplicati.GUI.TrayIcon.exe

**Comment by agrajaghh** [comment]
can you please try 2.0.1.34 at https://github.com/duplicati/duplicati/releases and report back if your issue is solved?

It should be fixed in the newest version 😊

**Comment by free2open** [comment]
Thanks, it works.  I just ran a complete backup users files on a laptop unto a USB HD with the above version.
