### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2183]
I wanted to clarify few things. Maybe not the right place.

What is control file parameter what can it be used for?

Key based gpg encryption. How?
What are the parameters to be used
Where should the private/public key kept on disk.

Do Email alerts still don't work.

Thank in advance.

**Comment by kenkendk** [comment]
The control file is used to store additional information inside the `dlist` files.
It is not currently used in 2.0, but it was used in 1.3.x to store the backup configuration inside the backups, such that you could restore the backup configuration by pointing to the remote server.

I have not had the time to write a document describing how to set it up with GPG keys. Basically, you can use the `--gpg-encryption-switches` and `--gpg-decryption-switches` to set up the commandline.

A user had figured out how to do it with asymmetric encryption, so maybe you can use this:
```
--encryption-module=gpg
--gpg-encryption-command=--encrypt
--gpg-decryption-command=--decrypt
--gpg-encryption-switches=--recipient xxx@zzz.com
--passphrase=unused
```
