### ISSUE TITLE
Some Advanced Options are listed twice

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2184]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35
**Operating System:** Windows 10 Professional / Windows 10 Enterprise

### Bug description
Under Settings, the advanced options in the section "Configure http requests" are listed twice.

### Steps to reproduce
- Open the web interface
- Click Settings
- Open the  drop-down menu Add advanced option

**Actual result:** All entries in this section are listed twice.
**Expected result:** All entries should be listed once.

### Screenshots

![duplicati - configure http requests](https://cloud.githubusercontent.com/assets/24669568/21345590/229a21cc-c6a1-11e6-8c6b-2e9f3328d930.png)

**Comment by warwickmm** [comment]
Resolved in pull request #3511.
