### ISSUE TITLE
Duplicati logon screen is using the Greeno theme

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2186]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35
**Operating System:** Windows 10 Professional / Windows 10 Enterprise

### Bug description
When a password is set on the UI, the logon screen is presented using the Greeno theme. As far as I know, this theme is depricated and will be removed in a future version. For this reason and for cosmetic reasons, the default theme for the logon screen should be changed to the NgAx theme.

### Steps to reproduce
- Set a password on the user interface (click Settings, select Password and enter a new password).
- Log off and re-open the Duplicati web interface.
- The logon screen is displayed in the Greeno theme style.

**Actual result:** Logon screen in Greeno style.
**Expected result:** Logon screen in NgAx style.

### Screenshots

![duplicati logon screen](https://cloud.githubusercontent.com/assets/24669568/21346362/67d3f166-c6a4-11e6-8efd-d7cb23364aaa.PNG)

**Comment by agrajaghh** [comment]
related #2162

**Comment by agrajaghh** [comment]
login is impossible after https://github.com/duplicati/duplicati/commit/264a9801f09780fdcc3246fffa8a561a432fbf1a
