### ISSUE TITLE
Negative "files remaining" in status indicator

### ISSUE THREAD

**Issue by gerco** [duplicati/duplicati#2188]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.34_canary_2016-12-05
**Operating System:** Mac OS X 10.10.5 (Yosemite)
**Backend:** SFTP/SSH

### Bug description
Close to completing the backup, the status indicator reports a negative number of files remaining to finish the backup.

### Steps to reproduce
Happens semi-randomly, not sure what the cause may be.

**Actual result:** Negative number of files remaining is displayed
**Expected result:** Correct number of files remaining is displayed

### Screenshots
![screen shot 2016-12-21 at 10 42 33 am](https://cloud.githubusercontent.com/assets/663635/21395562/eb2d27be-c76a-11e6-9b58-e83a9227756a.png)

**Comment by rkarlsba** [comment]
Just seeing the same now, on Linux, Debian Stretch
![skjermbilde 2017-09-12 kl 21 46 57](https://user-images.githubusercontent.com/4253147/30345093-29c5140e-9804-11e7-974f-1c3b356dfcec.png)

**Comment by comodoro** [comment]
I can confirm on Duplicati Beta 2.0.1.67 on Windows 10

**Comment by abrow169** [comment]
I have this issue on Duplicati 2.0.0.7 on Windows 7, was anyone able to resolve this?

**Comment by kenkendk** [comment]
Duplicati does a file scan and computes the number of files it expects to encounter. If you add files after the scan, but before the backup has completed, you can see negative numbers. I think the smartest way to handle this is perhaps to simply display ... instead of a negative number. 

What are your thoughts on this idea? Is it better to display negative numbers? Or `1` or `*`?

**Comment by warwickmm** [comment]
#4362 describes a similar issue (negative bytes).

**Comment by ts678** [comment]
[2.0.3.10_canary_2018-08-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.10-2.0.3.10_canary_2018-08-30) release notice says

> Fixed an issue where the number of remaining files would be negative

There are some other open and closed issues on negative bytes, but I think files is fixed. This will close unless we hear otherwise.
