### ISSUE TITLE
Question on delta uploads

### ISSUE THREAD

**Issue by nickbe** [duplicati/duplicati#2201]
Since I couldn't find any documentation on this, I'd ask this question here:

Does Duplicati make delta uploads or does it try to upload the complete file when it has changed?
in other words: How effective is duplicati on files like truecrypt containers or other large files when only parts of the files have changed?

Thanks in advance for some information about this.

**Comment by kenkendk** [comment]
You can read about the approach here:

http://www.duplicati.com/articles/Storage-Engine/
http://www.duplicati.com/articles/Backup-Process/
