### ISSUE TITLE
Database corrupted

### ISSUE THREAD

**Issue by zhuanyi** [duplicati/duplicati#2203]
Hi,

Had the following issue while attempt to run a brand-new backup job:
```
Error while running ***BACKUPJOBNAME***

The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.
```

Raw log shows the following while trying to repair the DB:

`System.Exception: No files were found at the remote location, perhaps the target url is incorrect? at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor) at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor) at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter) at Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter) at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) at Duplicati.Library.Main.Controller.Repair(IFilter filter) at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)`

And here is the raw log while trying to run the backup job:

`System.Exception: The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again. at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter) at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result) at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)`

Tried to uninstall and reinstall Duplicati, tried to delete the sqlite file and let Duplicati to recreate it. 

System OS is Windows 10

Duplicati version:

> You are currently running Duplicati - 2.0.1.35_experimental_2016-12-13

Seems the only way to fix it as what I have Googled so far is to delete and recreate the entire backup job and deleting all remote files during the process. Probably less ideal since this means everything has to be backed up again.

**Comment by kenkendk** [comment]
Not sure what is going on here.
It looks like the remote files are deleted from the storage.

If you know why or how to fix that, you can use the "repair" page to delete and recreate the local database.

**Comment by zhuanyi** [comment]
Just want to let everyone know I managed to resolve this by export the backup, delete the backup job and re-import the backup file.
