### ISSUE TITLE
Remote Volume size question

### ISSUE THREAD

**Issue by nickbe** [duplicati/duplicati#2205]
I'm still not comfortable with the blocksize/volume sizes. 
When using FTP as my backup target with a blocksize of 150kb and a volume size of 50MB - does it have to rewrite the complete 50MB when 3 blocks have changed or can FTP handle partial uploads? 

Sorry for asking, but until now I always thought FTP uploads can only be sequential.

**Comment by agrajaghh** [comment]
Duplicati doesn't change the .dblock files after they are written. So if there are changes to three blocks, duplicati will upload a new .dblock file containing these 3 blocks (~450 KB). 

You can also find more information here:
http://www.duplicati.com/articles/Backup-Process/
http://www.duplicati.com/articles/Storage-Engine/

**Comment by nickbe** [comment]
So are these additional dblock files integrated at some point? Is there an "original size"/"updated dblock" ratio limit when duplicati decides it's better to do a full upload again? 

Right now I'm thinking about very large files like truecrypt/veracrypt volumes which 50 or more GB each. The size of truecrypt volumes will stay consistent and only the file date changes. In time everything that changes will be uploaded as additional dblocks. Therefore I imagine I'll have thousands of additional dblocks in the FTP folder. Would the SCP protocol be capable of partial uploads instead?

**Comment by kenkendk** [comment]
It is not "integrated".

If you delete filesets, some blocks will be unwanted (not used in any files).

This will cause some wasted spaced to be used. When a threshold is reached, Duplicati will "compact" it.

Compacting involves downloading the dblock files with waste, and writing fresh ones.

**Comment by nickbe** [comment]
Ok, so does that mean lots of small dblocks will be merged into fewer large ones?

**Comment by kenkendk** [comment]
Yes, small dblocks are merged into larger ones.

This happens automatically after a backup, unless you set `--no-auto-compact`.

You can also run compact manually ifyou like.
