### ISSUE TITLE
Usage statistics

### ISSUE THREAD

**Issue by nickbe** [duplicati/duplicati#2206]
Currently I'm not able to switch any other option except **System default (Information)**
Seems to be a bug.

**Comment by agrajaghh** [comment]
Its working for me:
![grafik](https://cloud.githubusercontent.com/assets/5296073/21520346/0af3d870-ccf4-11e6-84af-784ed189aa41.png)

Can you give some more information please? What version? What OS? What browser?

**Comment by nickbe** [comment]
Windows 7 - Firefox (latest version).
Everything else can be set/changed, while nothing I select in the dropdown is saved. At least when I reenter the settings then I always see the "System Default"

**Comment by kenkendk** [comment]
Can you post a screenshot?

If you have disabled usage reports from the environnent variable, then you cannot set (and thus enable) usage reports. But it should hide the setting completely in this case.

Are you on the latest experimental or canary?

**Comment by nickbe** [comment]
I just changed the update channel just to try out changing the settings. Also I tried to set the stats to "Errors and crashes". After reentering the settings I see this:

![grafik](https://cloud.githubusercontent.com/assets/10890765/21522213/d5ab3658-cd03-11e6-8fcf-937d1d8f2ff1.png)

This is my current version:

![grafik](https://cloud.githubusercontent.com/assets/10890765/21522243/0ffdf912-cd04-11e6-853b-e41a4bfaeb2c.png)

**Comment by kenkendk** [comment]
So you see the options, but the changes do not stick?

**Comment by nickbe** [comment]
Exactly

**Comment by kees-z** [comment]
I can confirm this issue is still present in v2.0.1.44.
Somehow I changed the usage reports to "Crashes Only" in a prior version.
When I make a change, for example to "Usage statistics, warnings, errors and crashes" I don't get an error message, but when I re-open the Settings menu, I still see "Crashes only" is selected.

Apart from that, I notice that the System default has also changed to "Crash". Which mechanism determines what is the system default for usage reports?

## _Screenshots_
"Crashes only" is the current setting and cannot be changed anymore:
![usagestatistics1](https://cloud.githubusercontent.com/assets/24669568/22291308/e0f4a860-e305-11e6-99be-d607533d68a9.PNG)

System default changed to "Crash":
![usagestatistics2](https://cloud.githubusercontent.com/assets/24669568/22291310/e3b70656-e305-11e6-8eb4-31026f498930.png)

**Comment by ElRico** [comment]
I am seeing the same issue with version 2.0.1.53_experimental_2017-03-13 on Windows 10.

**Comment by kenkendk** [comment]
The option listed in `System default (....)` is taken from the environment variable `USAGEREPORTER_Duplicati_LEVEL`. If that environment variable is set to `None` it should not be possible to override it in the UI.

It is possible that this environment variable also overrides the UI chosen one too. Are any of you seeing the issue also when this environment variable is not set?

**Comment by kees-z** [comment]
I have checked 3 Duplicati installations. All are running V2.0.1.53 Experimental. On 2 of them version 2.0.1.35 was installed, the other one had an initial version of 2.0.1.30. All 3 are updated to V2.0.1.53. On all 3 systems Duplicati runs as a Windows service under the SYSTEM account on Windows 10 Professional.

None of the 3 systems have an environment variable ` USAGEREPORTER_Duplicati_LEVEL `. At least, I don't see a variable with that name when I type SET in a normal or an Administrative command prompt.

On the first system, the system standard is Crash, on the second one Error and on the third one it's set to Information.
No idea how Duplicati determines the System standard level. Maybe I've fiddled with this setting in the past and Duplicati kept that setting as Default. Anyway, there doesn't seem to be an option in the GUI to change the default setting.

**Comment by paya-cz** [comment]
I am running `Duplicati - 2.0.1.53_experimental_2017-03-13` on `Win 10` and I also experience the same issue.

**Comment by Mikiya83** [comment]
2.0.1.58 here on QNAP nas and i have the same issue.

**Comment by kenkendk** [comment]
I was finally able to reproduce!

The problem is that the value is being set in another (Angular) scope because there is an `ng-if` around the drop-down that hides in in case it is disabled.
