### ISSUE TITLE
OneDrive for Business: OAuth support [$10]

### ISSUE THREAD

**Issue by xko** [duplicati/duplicati#2210]
I was happy to learn that duplicati supports od4b. But with requirement to store password, I'm still hesitant to use it (and I believe many others as well). If only duplicati was able to use [OAuth mechanism](https://dev.onedrive.com/auth/aad_oauth.htm), that would truly enable the  feature. 

I think for the beginning there's enough to introduce advanced options for necessary paramenters (auth code, app key etc..). There are [tutorials](https://www.sepago.com/blog/2016/10/05/Access-OneDrive-for-Business-with-PowerShell-as-an-Azure-AD-App) online about generating these without needing 3rd party hosted app.

**Comment by Thaurin** [comment]
I was about to create an issue for this myself, before I found this one. I agree wholeheartedly. The od4b support is a perfect solution for my personal and work backup needs, but I cannot responsibly use it when the password is stored in plain text.

This is an older issue, but this needs to get some love and priority. I'll see if I can up the bounty to raise interest, or I may look into the issue myself when I have time.

**Comment by xyzlabc** [comment]
Sorry if this isn't useful, but rclone has an implementation here that might be useful as a reference:
https://github.com/ncw/rclone/blob/2f63a9f81cd5fae993be6f5fa57c705ddd1da465/backend/onedrive/onedrive.go

I can't code so I don't know if this is useful, so sorry if not.

**Comment by ts678** [comment]
This can be closed as done, right? See @tygill link above. I don't know how bounties are handled though.

**Comment by warwickmm** [comment]
Yes, I believe this is done.  I'm not sure exactly how the bounties work now, but @tygill can claim it.

**Comment by tygill** [comment]
Well, I don't really know how the bounty system works, but I've just tried to submit the claim there...we'll see how it goes...
