### ISSUE TITLE
Restoring Queries

### ISSUE THREAD

**Issue by brad-pea** [duplicati/duplicati#2213]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2
**Operating System:** Windows 7

### Bug description

When restoring a folder, application does not restore the parent folder, only the files / folders underneath - is this what should happen ? I would imagine it would be best to always restore the parent folder too ?

### Steps to reproduce
Run a backup which contains root folder

**Actual result:** Parent folder missing but child objects resore
**Expected result:** Parent folder would be restored along with child objects

### Side Note

When restoring an encrypted backup, if choosing to do a restore by dropping down the backup and selecting restore files, I am not prompted for the password, but if I do a restore via the left hand menu of restore backup, I am prompted for the password - shouldn't I always be prompted for the password?**

**Comment by warwickmm** [comment]
This is by design, but I believe the `dont-compress-restore-paths` option should recreate all the parent folders if so desired.
