### ISSUE TITLE
[Q] How to configure/run Duplicati 2 on Linux server

### ISSUE THREAD

**Issue by 4integration** [duplicati/duplicati#2215]
I have installed Duplicati 2.0.1.35 on Ubuntu Server 16.04 i.e. headless.

How can I configure Duplicati e.g. setting port number?
How can I run Duplicati as service?

Regards
Joacim

**Comment by kenkendk** [comment]
With the latest debian package you should be able to run Duplicati as a normal service, i.e.: `sudo systemctl start duplicati`.

To run it manually, you can run `duplicati-server --webservice-port=1234 --webservice-interface=loopback`. If you want to access the server from outside, set the interface to `any`, but  make sure you have a protected network before doing this.

**Comment by ifeelingz** [comment]
can start service in background ?

**Comment by ifeelingz** [comment]
CentOS 7, Can start service in background ?

**Comment by NiborIS** [comment]
I'm in the same position as ifeelingz above. Wanting to run Duplicati as a service on CentOS 7 (preferably with --webservice-interface=any argument).

Any advice please?

**Comment by mmiat** [comment]
how to install as a daemon in ubuntu/debian ?

**Comment by neilmunday** [comment]
Hi,

For my CentOS 7 desktop I am using the following systemd service as defined at /etc/systemd/system/duplicati.service:

```
[Unit]
Description=duplicati back-up service

[Service]
Environment=INSTALLDIR=/usr/lib/duplicati
Environment=LD_LIBRARY_PATH="${INSTALLDIR}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
Environment=MONO_PATH="${MONO_PATH}:${INSTALLDIR}"

ExecStart=/usr/bin/duplicati-server --webservice-port=8200 --webservice-interface=loopback

[Install]
WantedBy=multi-user.target
```
To start:
```
systemctl start duplicati.service
```
To stop:
```
systemctl stop duplicati.service
```
To enable at boot time:
```
systemctl enable duplicati.service
```

@NiborIS you can of course change the `--webservice-interface` option to `any` above to make duplicati listen on all interfaces.

Hope this helps,

Neil.
