### ISSUE TITLE
repair backup with missed some dblock files 

### ISSUE THREAD

**Issue by NCNecros** [duplicati/duplicati#2216]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System:** Windows 7
**Backend:**

### Bug description
How can I recreate losed dblock files

### Steps to reproduce
- create backup with 
```
Duplicati.CommandLine.exe backup --no-encryption=true --compression-module=7z "d:\Temp\duplicati-bak" "d:\DirWithData"
```

- delete one dblock file from backup repository
- run repair and get:
```
Repair cannot acquire 517 required blocks for volume duplicati-b90a0044388934dacaa85425cb70dffc5.dblock.7z, which are required by the following filesets:
duplicati-20161229T094833Z.dlist.7z
duplicati-20161229T132237Z.dlist.7z
This may be fixed by deleting the filesets and running repair again
Failed to perform cleanup for missing file: duplicati-b90a0044388934dacaa85425cb70dffc5.dblock.7z, message: Repair not possible, missing 517 blocks!!! => Repair not possible, missing 517 blocks!!!
```

How can I recreate missed block?

**Comment by kenkendk** [comment]
There is currently no way to recreate the missing block. Since the data is no longer present on the machine, the dblock file itself cannot be recreated.

Once #1337 is implemented, it will be possible to purge affected files from the remote volumes to recreate a subset of the dblock file.

**Comment by NCNecros** [comment]
But if I have local data from which I did backup.
