### ISSUE TITLE
Using Hubic - After AuthID creation and running successful backup no folder or files found

### ISSUE THREAD

**Issue by BlueFalcon10** [duplicati/duplicati#2217]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version: 2.0.1.38_canary_2016-12-27
**Operating System: Windows 10
**Backend: Hubic

### Bug description
After creating an AuthID and setting up a backup, when I go to Hubic the directory does not exist.  During the Test connection process it ask to create the directory.  I accept and retest.  All passes. I run the backup job and it reports everything is successful.  But I can not find the folder or files in Hubic.  If I delete the job and remote files it comes back successful.

### Steps to reproduce
- Add backup
- Enter Passphrase
- Reenter Passphrase
- Next
- Pick Storage Type - Hubic
- Enter Path on Server: Backup_Files
- Click AuthID link
- Click Hubic Login in the popup window
- Enter credentials and click Accept
- Hash created and automatically entered into the AuthID field of the setup window/page
- Click Test Connection
- Window pops up saying "Testing Connection"
- Create Folder? Window comes up and I click Yes
- Success Connection worked comes up - click OK
- I click Test Connection Again to make sure
- Success Connection worked comes up - click OK
- Click Next
- Choose My Pictures and the Next
- Check "Automatically Backup", Time is 13:00 and Date is next Day "2016-12-30"
- Click Next
- General Options - I fill in the name - "My Pictures" and click "Save"
- on main window click "Run Now" next to backup job
- Jobs runs and says successful

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Login to Hubic, but can not find the folder created or the file(s) that was backed up.
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behavior)

### Screenshots

![image](https://cloud.githubusercontent.com/assets/24832663/21555435/f8ea0fbc-cdcc-11e6-84a8-a9cf2cf89cef.png)

**Comment by rygel** [comment]
Could you try and prefix the server path with "default/". It could be the same as this issue by rclone:
[https://github.com/ncw/rclone/issues/248](https://github.com/ncw/rclone/issues/248)

**Comment by BlueFalcon10** [comment]
Yes this worked.  Adding "default/" as suggested in the path did provide me visibility.  Sorry I don't know how I didn't see this in my search. 

Thanks!!!

**Comment by rygel** [comment]
Glad I could help!
I just had the same problem with rclone 4 hours ago :)
