### ISSUE TITLE
"Exclude files whose names contain" causes error

### ISSUE THREAD

**Issue by moltenform** [duplicati/duplicati#2220]
Hi,
I'm seeing an error message when I try to use a "Exclude files whose names contain" filter.

### Version info

**Duplicati Version:** both 2.0.1.35 and github latest (e1a989ca3...)
**Operating System:** Win 8.1 x64
**Backend:** any

### Steps to reproduce
- Start duplicati.server.exe
- From the web interface,
- Menu->Add backup
- Enter a name, choose "No encryption"
- Choose a local folder path destination
- Use "Add a path directly" to provide a source path, include trailing \.
- Add filter of type
- "Exclude files whose names contain" and value "example"
- Click next, using default settings for all other settings.
- Click Run Now.

**Actual result:**

A red error immediately appears saying:

    Error while running simple-test-exclude
    parsing ".*example.*[^\]" - Unterminated [] set.

Here are the command line arguments that were created

    "...\Duplicati.CommandLine.exe" backup "file://C:\testduplic\simpletestexcludes" "C:\testduplic\testexcludes--input\\" --backup-name="simple-test-exclude" --dbpath="C:\...\Duplicati\Server\bin\Debug\OXXLAXDONK.sqlite" --encryption-module= --compression-module="zip" --dblock-size="50mb" --keep-time="3M" --no-encryption="true" --disable-module="console-password-input" --exclude="[.*example.*[^\]]"

I did look at AppUtils.js to investigate. Problem looks straightforward, the dirsep character \ is inadvertently escaping the ]. I would also have expected the generated regex to look something like

    .*example[^!]*

(using AppUtils.js's convention that ! is replaced with dirsep)

I am able to work around this by using a raw regular expression but thought I would notify that this feature doesn't seem to be working as intended,

**Comment by agsfbm6** [comment]
After just having installed version 2.0.2.1 on Windows 10 64bit I have replicated the above error.

**Comment by Cyberwizzard** [comment]
Version 2.0.3.3 still has this issue; the automatically generated regex is invalid

**Comment by ts678** [comment]
Some forum discussion was in [A bug on regular expression when creating filters (Windows platform)](https://forum.duplicati.com/t/a-bug-on-regular-expression-when-creating-filters-windows-platform/4543?u=ts678) with reference citations and a proposed one-character fix, but it would of course need multi-platform testing.

**Comment by downpoured** [comment]
I recommend this be fixed - it is unprofessional. At the very least, can there be a friendlier error message as a stopgap measure? Like saying "Not yet supported in Windows"?

**Comment by drwtsn32x** [comment]
If the intent of this exclusion is to ONLY match filenames, shouldn't the regex be:

Windows:  `.*xxx[^\\]*`
Other:  `.*xxx[^/]*`

(where xxx is the text entered by the user)
We can keep it simple and just escape the path character either way.  Escaping is needed on Windows and will have no effect on Other.

In any case this seems to be wrong:  `.*xxx.*[^\\]` because it will end up excluding files files in a folder whose name contains xxx even if the file itself does not contain xxx.

**Comment by kenkendk** [comment]
I have added PR #3967 which should solve the issue. My Windows debugging environment freezes frequently, so I have not tested it fully.

It seems to generate the correct expressions after the fix, and the broken ones before the fix, if I emulate a Windows setup from MacOS.

**Comment by kenkendk** [comment]
Fixed with #3967
