### ISSUE TITLE
Duplicati stalls indefinitely on renaming remote file on ACD while trying to recover from error

### ISSUE THREAD

**Issue by maxcynicle** [duplicati/duplicati#2221]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35-1
**Operating System:** Debian Jessie
**Backend:** Amazon Cloud Drive

### Bug description
When using the Amazon Cloud Drive (ACD) as a backend and Duplicati encounters a "REQUEST_TIMEOUT" from ACD, Duplicati attempts to recover from the error by renaming the remote file but stalls indefinitely. I then proceed to force stop the task and delete the remote file that Duplicati tried to rename. When I run it again, it will start over and check against the backend for any changes and continue the task.

If I remember correctly, in the event I continue without deleting the remote file, Duplicati will just complain that the remote backend has more files than in the local database and attempt a repair.

### Steps to reproduce
- Start a backup task
- Pray that ACD doesn't throw back any errors
- Notice eventually an uploading job returns the "REQUEST_TIMEOUT" error, and find that Duplicati stalls indefinitely trying to rename the remote file

**Actual result:** Stalls indefinitely
**Expected result:** Duplicati should resync the remote file tree to see if what has changed after a preset amount of time. Also, I do not know if Duplicati is using the API correctly to rename the remote file. For all I know it could be "attempting" to rename but even that is throwing an error.

### Screenshots
![2017-01-01 00_09_24-greenshot](https://cloud.githubusercontent.com/assets/3303801/21578520/4a9c82d4-cfbe-11e6-9d83-c16781622485.png)

Do note that there are no other messages that appear after the topmost message. **No** disk/CPU/network activity happens related to mono or Duplicati happens at this point of time.

### debug log
Happened again

`Jan 1, 2017 1:01 AM: Backend event: Put - Started: duplicati-bc49d4a4c68fa4cc0bd6d33e23d01a909.dblock.zip.aes (149.97 MB)`
`Jan 1, 2017 1:01 AM: Starting - RemoteOperationPut`
`Jan 1, 2017 1:01 AM: Renaming "duplicati-b6deacb71e7bd4576a48fcfd0cbf1609a.dblock.zip.aes" to "duplicati-bc49d4a4c68fa4cc0bd6d33e23d01a909.dblock.zip.aes"`
`Jan 1, 2017 1:01 AM: Backend event: Put - Rename: duplicati-bc49d4a4c68fa4cc0bd6d33e23d01a909.dblock.zip.aes (149.97 MB)`
`Jan 1, 2017 1:01 AM: Backend event: Put - Rename: duplicati-b6deacb71e7bd4576a48fcfd0cbf1609a.dblock.zip.aes (149.97 MB)`
`Jan 1, 2017 1:01 AM: Backend event: Put - Retrying: duplicati-b6deacb71e7bd4576a48fcfd0cbf1609a.dblock.zip.aes (149.97 MB)`
`Jan 1, 2017 1:01 AM: Operation Put with file duplicati-b6deacb71e7bd4576a48fcfd0cbf1609a.dblock.zip.aes attempt 1 of 5 failed with message: The remote server returned an error: (408) REQUEST_TIMEOUT.
{"ClassName":"System.Net.WebException","Message":"The remote server returned an error: (408) REQUEST_TIMEOUT.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () [0x00056] in <45e7a8bd12a349498d4f398ccb643c2e>:0 \n  at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () [0x0004a] in <45e7a8bd12a349498d4f398ccb643c2e>:0 \n  at Duplicati.Library.JSONWebHelper.GetResponse (Duplicati.Library.Utility.AsyncHttpRequest req, System.Object requestdata) [0x000c7] in <b4e57b7b18854d15b94fcad823e198e8>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Duplicati.Library.Utility"}`
`Jan 1, 2017 1:01 AM: RemoteOperationPut took 00:01:39.623`

Thank you for your time. Happy New Year!

**Comment by mmiat** [comment]
I'm afraid I've the same problem....

my email with error:

`Failed: Errore del server remoto: (408) Timeout richiesta.
Details: System.Net.WebException: Errore del server remoto: (408) Timeout richiesta.
   in Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry(ISnapshotService snapshot, BackendManager backend, String path, FileAttributes attributes)
   in Duplicati.Library.Main.Operation.BackupHandler.RunMainOperation(ISnapshotService snapshot, BackendManager backend)
   in Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   in Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
   in Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
`

**Comment by mmiat** [comment]
I've found this: https://github.com/duplicati/duplicati/commit/f9e5eeae0caa3ca238fe1df768b5999b455df024
related to #2320 and #2432

but in my Linux installation there is no AsyncHttpRequest.cs file

**Comment by warwickmm** [comment]
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
