### ISSUE TITLE
Failed to create snapshot on Windows 10

### ISSUE THREAD

**Issue by zappeee** [duplicati/duplicati#2223]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System:** Windows 10 64bit
**Backend:** HP EliteBook 745 G2

### Bug description

> Failed to create a snapshot: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
>    at Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
>    at Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
>    at Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
>    at Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)
>    at Duplicati.Library.Snapshots.SnapshotUtility.CreateSnapshot(String[] folders, Dictionary`2 options)
>    at Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log) => Attempted to perform an unauthorized operation.

### Steps to reproduce
Run a backup

**Actual result:** Backup completes with warnings
**Expected result:** Backup to complete without warnings

### debug log
See above

**Comment by agrajaghh** [comment]
did you start duplicati with admin priviliges?

**Comment by zappeee** [comment]
I did restart it as admin and then it worked.
When it start automatically, will it start with admin rights?

**Comment by arbeitskollege** [comment]
from: [https://sites.google.com/a/duplicati.com/duplicati/howtos/howto-backup-opened-files-e-g-outlook-pst](https://sites.google.com/a/duplicati.com/duplicati/howtos/howto-backup-opened-files-e-g-outlook-pst)

Automatically run Duplicati as administrator at startup
If you are working with your system with administrator priviliges, there is nothing to be done. Duplicati will be started with adminisrator priviliges at startup so that VSS is available. But if you are not working with administrator priviliges on your system, it is a little bit tricky to get Duplicati automatically executed at startup with administrator priviliges. Here is what you do:

    Delete the existing shortcut in the autostart folder (it starts Duplicati with user priviliges).

    Open the Windows Scheduler and create a new task: At system start execute Duplicati. Before you close the dialog to save the new task, check the little box to open the properties dialog.

    In the properties dialog, change the user account that is used to start Duplicati to an account with administrator priviliges. That's it. At startup the scheduler will start Duplicati with an administrator account, so that it will be possible to make backups of opened files like e.g. the Outlook PST file while Outlook is running.

**Comment by zappeee** [comment]
@arbeitskollege, I'm working as an admin and I still get this error message.
How can I solve this?

**Comment by agrajaghh** [comment]
@zappeee are you just logged in as a admin or did you also explicitly start duplicati with admin rights?

**Comment by zappeee** [comment]
@agrajaghh,
I'm logged in with an account that's part of Administrators.
Isn't that enough for the autostart to work?

**Comment by arbeitskollege** [comment]
No, it's not. Follow these steps as mentioned above:

> Delete the existing shortcut in the autostart folder (or Task Manager in Win 10) (it starts Duplicati with user priviliges).

> Open the **Windows Scheduler** and create a new task: At system start execute Duplicati. Before you close the dialog to save the new task, check the little box to open the properties dialog.

> In the properties dialog, change the user account that is used to start Duplicati to an account with administrator priviliges. That's it. At startup the scheduler will start Duplicati with an administrator account, so that it will be possible to make backups of opened files like e.g. the Outlook PST file while Outlook is running.

It is important to create a task with the windows task scheduler in order to start duplicati with admin rights. Creating an autostart task with the task manager won't do the job, even if you are logged in with an admin account.

**Comment by agrajaghh** [comment]
If you just want to start duplicati manually with admin rights you can also right click on the .exe file (or the shortcut) and select "run as administrator"

**Comment by zappeee** [comment]
@arbeitskollege, I'm afraid that's not really how it looks like in Windows 10.
It's more like this, http://winaero.com/blog/wp-content/uploads/2016/07/Windows-10-Create-Task-window-run-elevated-checkbox.png

Shall I check that box?

**Comment by zappeee** [comment]
I ran into this issue again on another machine, wouldn't be good if the Duplicati installer did this?
