### ISSUE TITLE
The folder was not found

### ISSUE THREAD

**Issue by jposert** [duplicati/duplicati#2227]
### Version info

**Duplicati Version:** duplicati-2.0.1.35_experimental_2016-12-13-x64
**Operating System:** Windows 10x64 Pro

### Bug description
When trying to do a backup on WebDav the message occurs "The folder <dir> was not found. Server response 404."
I'am 100% sure that given path exists.

**Comment by agrajaghh** [comment]
which service are you using? What is the path? Does it contain some special characters? Can you connect to the webdav folder with another tool?

**Comment by Posio** [comment]
I use my own WebDav server hosted on Windos Server 2016 and yeah it works. I can connect to my webdav service via WinSCP and even Windows Explorer (Add network location) without any problem.
Path does not contain any special characters. For example https://domain.com/lenovo, and the "lenovo" folder exists. 
During configuration it pass connection test.

**Comment by ts678** [comment]
> During configuration it pass connection test.

For most storage types, this means that a `list` was possible to do successfully, however there's no validation of what came back.
There's also a `list` at the start of most operations, for example a backup, or `Verify files` button for the job on its home area.
If this is not yet resolved but is still of interest, you can go to \<job> --> Show log --> Remote. Click `list` to see was visible to it.
This might show how aim went wrong. You can also [Export As Command-line](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#exporting-a-backup-job-configuration) for [Duplicati.CommandLine.BackendTester.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlinebackendtesterexe) tests.

**Comment by ts678** [comment]
Assuming that issue is WebDAV-specific, there's actually a special debugging option for problems with [WebDAV](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#webdav) `list`:

> --debug-propfind-file To aid in debugging issues, it is possible to set a path to a file that will be overwritten with the PROPFIND response

I'll remove `bug` label, and this issue will eventually close if there's no more feedback.
