### ISSUE TITLE
"Failed to process" messages after backup "the file had size x but was expected to be y"

### ISSUE THREAD

**Issue by juriansluiman** [duplicati/duplicati#2232]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System:** Kubuntu 16.04.1 LTS (GNU/Linux)
**Backend:** local folder based on cifs-autofs mount

### Bug description
Installed Duplicati on January 4th (2017). The day after (5th) I directly got some error messages about invalid file size. The latest errors of today (they vary sometimes) were:

```
Operation Get with file duplicati-b1dfc153c23894fe6b96d2bf2638abc94.dblock.zip.aes attempt 5 of 5 failed with message: The file duplicati-b1dfc153c23894fe6b96d2bf2638abc94.dblock.zip.aes was downloaded and had size 65536 but the size was expected to be 52367709
System.Exception: The file duplicati-b1dfc153c23894fe6b96d2bf2638abc94.dblock.zip.aes was downloaded and had size 65536 but the size was expected to be 52367709
  at Duplicati.Library.Main.BackendManager.GetForTesting (System.String remotename, Int64 size, System.String hash) <0x41a18080 + 0x0011f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.TestHandler.DoRun (Int64 samples, Duplicati.Library.Main.Database.LocalTestDatabase db, Duplicati.Library.Main.BackendManager backend) <0x41a13510 + 0x00f8f> in <filename unknown>:0 
```
And finally (after 5 retries)
```
Failed to process file duplicati-b1dfc153c23894fe6b96d2bf2638abc94.dblock.zip.aes
System.Exception: The file duplicati-b1dfc153c23894fe6b96d2bf2638abc94.dblock.zip.aes was downloaded and had size 65536 but the size was expected to be 52367709
  at Duplicati.Library.Main.BackendManager.GetForTesting (System.String remotename, Int64 size, System.String hash) <0x41a18080 + 0x0011f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.TestHandler.DoRun (Int64 samples, Duplicati.Library.Main.Database.LocalTestDatabase db, Duplicati.Library.Main.BackendManager backend) <0x41a13510 + 0x00f8f> in <filename unknown>:0 
```

I have twice "repaired"  the database, but after file verification the errors kept. Might be related to #1583, but in that issue so many different bugs are mentioned I thought to open a fresh/clean new one. I am not sure to recreate the database; will I loose some information about my recent backups?

More relevant information:

1. Since the backups only run for a few days, I am happy to delete all backup files and start over when necessary. The current risk is not that large
2. The backup files are written to a local folder on my system (`/mnt/nas/backup`). This is a mount point for a CIFS share, mounted with autofs. So the underlying file system is not ext4 or something, but is a share over SMB. Volume size is set to the default 50MB.
3. Currently is backup up my home directory with various exclude filters. 1,89GB source size with backup 165,31 MB / 3 Versions.

### Steps to reproduce
- instantiate backups
- run them a few days
- notice the failure message in the backup log

**Actual result:** After backup logs contain failure messages
**Expected result:** No failures should happen during backup process

### debug log
I have not a live log available. Can do that when requested, I have only the stored backup log to my availability.

**Comment by juriansluiman** [comment]
I had too many errors, recreating database just gave me a multitude of new errors. I didn't trust the files anymore, so I deleted everything. Duplicati is now creating a new clean backup.

**Comment by juriansluiman** [comment]
I got a full replica again with some new error message:

```
Operation Get with file duplicati-bdf39b5b88023466284cb2c9f45fe1b3b.dblock.zip.aes attempt 1 of 5 failed with message: Hash mismatch on file "/tmp/dup-caf0f065-7c7d-4a93-8e2e-d21124e7405b", recorded hash: QYXIduQSPwx/EAIr8KyqBOq3IZW0omfWx24is2UPYhk=, actual hash H5Qv8nKgqDyZN7OtyBeWf7fYUS4yd9xR9apJAItWZao=
Duplicati.Library.Main.BackendManager+HashMismatchException: Hash mismatch on file "/tmp/dup-caf0f065-7c7d-4a93-8e2e-d21124e7405b", recorded hash: QYXIduQSPwx/EAIr8KyqBOq3IZW0omfWx24is2UPYhk=, actual hash H5Qv8nKgqDyZN7OtyBeWf7fYUS4yd9xR9apJAItWZao=
  at Duplicati.Library.Main.BackendManager.DoGet (Duplicati.Library.Main.FileEntryItem item) <0x416f9580 + 0x009ab> in <filename unknown>:0 
```

```
Failed to process file duplicati-bdf39b5b88023466284cb2c9f45fe1b3b.dblock.zip.aes
Duplicati.Library.Main.BackendManager+HashMismatchException: Hash mismatch on file "/tmp/dup-bb33ee6e-131e-4152-bb04-49c95810bfbe", recorded hash: QYXIduQSPwx/EAIr8KyqBOq3IZW0omfWx24is2UPYhk=, actual hash H5Qv8nKgqDyZN7OtyBeWf7fYUS4yd9xR9apJAItWZao=
  at Duplicati.Library.Main.BackendManager.GetForTesting (System.String remotename, Int64 size, System.String hash) <0x416f93b0 + 0x0011f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.TestHandler.DoRun (Int64 samples, Duplicati.Library.Main.Database.LocalTestDatabase db, Duplicati.Library.Main.BackendManager backend) <0x416f3410 + 0x00f8f> in <filename unknown>:0 
```

**Comment by kenkendk** [comment]
Those errors seem to indicate something wrong with the storage destination.
The first error indicated that the files was somehow truncated to 64KB.

The second error message indicates that the file has been changed since it was created.
Since the files are encrypted, decrypting them should reveal that they are modified.

Can you attempt to decrypt the file `duplicati-bdf39b5b88023466284cb2c9f45fe1b3b.dblock.zip.aes` with this tool:
https://www.aescrypt.com/

Do you have any idea why the files would change on the destination?

**Comment by juriansluiman** [comment]
> Those errors seem to indicate something wrong with the storage destination.
> The first error indicated that the files was somehow truncated to 64KB.

This is not the case for all files though

```cmd
jurian@kaia:/mnt/kari/backup/Kaia$ ls -alh
totaal 888M
drwxr-xr-x 2 jurian jurian    0 jan 24 20:03 .
drwxr-xr-x 2 jurian jurian    0 jan  4 16:16 ..
-rw-r--r-- 1 jurian jurian 1,8M jan 10 22:33 duplicati-20170110T203945Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 11 21:15 duplicati-20170111T201429Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 14 08:34 duplicati-20170114T073303Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 14 21:14 duplicati-20170114T201306Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 16 07:38 duplicati-20170116T063619Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian  653 jan 16 21:26 duplicati-20170116T202559Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 17 20:01 duplicati-20170117T190000Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 18 22:18 duplicati-20170118T211655Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 19 21:27 duplicati-20170119T202408Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 21 09:01 duplicati-20170121T075741Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 21 23:45 duplicati-20170121T224317Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 23 18:53 duplicati-20170123T175021Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 23 20:02 duplicati-20170123T190000Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 1,8M jan 24 20:03 duplicati-20170124T190000Z.dlist.zip.aes
-rw-r--r-- 1 jurian jurian 128K jan 10 22:09 duplicati-b00199a3902e848eea2d0cf6a6cde3317.dblock.zip.aes
-rw-r--r-- 1 jurian jurian 128K jan 10 22:06 duplicati-b0080bf663d194ad1b5c51e67663de2e1.dblock.zip.aes
-rw-r--r-- 1 jurian jurian 128K jan 10 22:17 duplicati-b0157d307440e4d16bab374ce88d40b16.dblock.zip.aes
-rw-r--r-- 1 jurian jurian 128K jan 10 22:08 duplicati-b01b9640f0b9d416aab8a8a353f13e3cf.dblock.zip.aes
-rw-r--r-- 1 jurian jurian 3,6M jan 10 22:26 duplicati-b0406603497164806b497eb8bd0d6e69e.dblock.zip.aes
-rw-r--r-- 1 jurian jurian  19M jan 10 21:41 duplicati-b0818688c3d0e43ffb90f2eaf0f3a247d.dblock.zip.aes
-rw-r--r-- 1 jurian jurian 128K jan 10 22:06 duplicati-b0c64ac9e06ac44188fb9305736b563e3.dblock.zip.aes
-rw-r--r-- 1 jurian jurian 128K jan 10 21:49 duplicati-b13f2359e5ad74b969f491e0918e191e1.dblock.zip.aes
```

> The second error message indicates that the file has been changed since it was created.
> Since the files are encrypted, decrypting them should reveal that they are modified.
> 
> Can you attempt to decrypt the file duplicati-bdf39b5b88023466284cb2c9f45fe1b3b.dblock.zip.aes with this tool:
> https://www.aescrypt.com/

```cmd
jurian@kaia:~$ aescrypt -d -p ******** duplicati-bdf39b5b88023466284cb2c9f45fe1b3b.dblock.zip.aes 
Error: Input file is corrupt (3:4).
```
PS. My password is not only alphanum and I have tried to escape all chars in bash which needed it. Might have done something wrong with it, but trying to decrypt with fake passwd gives me the message `Error: Message has been altered or password is incorrect`, so I guess the password is accepted as the correct one.

> Do you have any idea why the files would change on the destination?

The destination is a Synology NAS, mounted with autofs over smb. For now, I have no other problems with this method accessing my files on my NAS, so not sure what could be the cause in this case.

If I can help any further, please let me know.

PS. I have restored a few random files via the web interface and verified the data with md5 checksums. They all came back valid. So, decrypting AES files via the web interface *does* work, despite of the error messages. Does this make any sense?

**Comment by montizzl3** [comment]
I'm getting the exact same thing.  I backup from my MacBook Pro to OneDrive for Business.  It says backup successful but there are 3 files it says it failed to process.  I do a restore and everything comes back fine.  Not sure why it thinks the destination is having issues.  I have other Duplicati jobs going to the same destination on a Windows 7 machine and a Server 2012 R2 box with no such errors.  It makes me wonder if it has something to do with Duplicati on my Mac.  I have recreated several different backup jobs with different source locations on my Mac and I always get 3 files that throw the "failed to process" error.

**Comment by ts678** [comment]
> but there are 3 files it says it failed to process.

There is no detail given, but this sounds like [Verifying backend files](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#verifying-backend-files) where 1 set of 3 files is downloaded for an integrity check.
[The TEST command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-test-command) explains a bit more. The output from this in the job log looks like this if successful -- maybe yours wasn't:

```
    "MainOperation": "Test",
    "VerificationsActualLength": 3,
    "Verifications": [
      {
        "Key": "duplicati-20240207T144957Z.dlist.zip.aes",
        "Value": []
      },
      {
        "Key": "duplicati-iab8c96e7e1a743b29da7fea15877010c.dindex.zip.aes",
        "Value": []
      },
      {
        "Key": "duplicati-b93e8d7367f604dd784d86ef7cc9ab274.dblock.zip.aes",
        "Value": []
      }
    ],
```

Logging for that looks nicer now. Above was in the old-style `Complete log`. The current GUI log would display a section like:

![image](https://github.com/duplicati/duplicati/assets/40771998/776dc5e7-df6a-4f7c-a604-a1df5bb89291)

I don't know why OneDrive for Business was returning seemingly bad files, it's possible it's fixed, and original post wasn't on it:

> Backend: local folder based on cifs-autofs mount

tells the story very well of original post situation. Duplicati isn't doing the CIFS. As far as it's concerned, it's just using local files.
Nevertheless, somewhere in the virtual drive thus provided, something goes wrong, and troubleshooting tries have been futile.
What's added instead is a length check after the upload, and a retry if it looks wrong then. This may or may not catch all cases.

[2.0.6.103_canary_2022-06-12](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.103-2.0.6.103_canary_2022-06-12) (and so also 2.0.7.1_beta_2023-05-25 and later Beta):

> Added check to detect partially written files on network drives, thanks @dkrahmer

Is issue still of interest, and present? If there's nothing to add, the issue will be closed.
