### ISSUE TITLE
'compare' causes exception if no version numbers are provided

### ISSUE THREAD

**Issue by citybar** [duplicati/duplicati#2233]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35
**Operating System:** Windows 10
**Backend:** Windows 10

### Bug description
Describe here the issue that you are experiencing.

'compare' command causes exception if no version numbers are provided.
When using the 'compare' command without versions, I get a System.NullReferenceException. 
When providing the default version numbers (compare "backup_set" 1 0) it works as expected. 

The exception occured after upgrade to 2.0.1.35 (windows). With my previous version 2.0.0.87 this error did not appear. 

### Steps to reproduce
I tried to inspect which changes were detected within the most recent backup using the command:
Duplicati.Commandline.exe" compare "name_of_backup_set" --verbose "--log-level=Profiling" "--debug-output" "--passphrase=xyz"
which caused the exception. 
Using
Duplicati.Commandline.exe" compare "name_of_backup_set" 1 0 --verbose "--log-level=Profiling" "--debug-output" "--passphrase=xyz"
instead succeeds. 
The error occurred for all of my backup sets.

**Actual result:** 
	System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
	   bei Duplicati.Library.Modules.Builtin.MSSQLOptions.<ContainFilesForBackup>m__10(String x)
	   bei System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
	   bei System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
	   bei Duplicati.Library.Modules.Builtin.MSSQLOptions.ContainFilesForBackup(String[] paths)
	   bei Duplicati.Library.Main.Controller.SetupCommonOptions(ISetCommonOptions result, String[]& paths, IFilter& filter)
	   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
	   bei Duplicati.Library.Main.Controller.ListChanges(String baseVersion, String targetVersion, IEnumerable`1 filterstrings, IFilter filter)
	   bei Duplicati.CommandLine.Commands.ListChanges(List`1 args, Dictionary`2 options, IFilter filter)
	   bei Duplicati.CommandLine.Program.RealMain(String[] args)
**Expected result:** no exception (documentation says: "If no versions are given, changes are shown between the two latest backups.")

**Comment by kenkendk** [comment]
Iy is cause by the `MSSQL` and `HyperV` modules not expecting no inputs. I have made a fix for this.
