### ISSUE TITLE
Failed to enumerate Microsoft SQL Server databases

### ISSUE THREAD

**Issue by fokodk** [duplicati/duplicati#2235]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System:** Windows 10 64bit
**Backend:**

### Bug description
when I try to make a new backup job I get this error 
Failed to enumerate Microsoft SQL Server databases: Attempted to perform an unauthorized operation.

### Steps to reproduce
when I try to make a new backup job

**Actual result:** I can make the backup job, and it seams to be working, but I cant filter

**Comment by agrajaghh** [comment]
@mnaiman is this maybe related to the mssql backup?

@fokodk Can you post a full log please?

**Comment by fokodk** [comment]
Do you mean the system-info-txt log ? 
[system-info.txt](https://github.com/duplicati/duplicati/files/692356/system-info.txt)

**Comment by mnaiman** [comment]
do you use MS SQL database on your system?

**Comment by agrajaghh** [comment]
@fokodk no, but if you click on your backup job and then click on "show log" (below "Reporting") you may be able to see some more information

**Comment by fokodk** [comment]
yes I have a MSsql on my system 
the Log is only show the process of the work, no error message.

**Comment by mnaiman** [comment]
Do you run Duplicati as Administrator?

**Comment by fokodk** [comment]
I have try to run it as Administrator

**Comment by mnaiman** [comment]
Still failing?

**Comment by fokodk** [comment]
Yes

**Comment by mnaiman** [comment]
Please take a look on that: https://github.com/duplicati/duplicati/issues/638
It throws error when it tries to enumerate SQL databases using VSS.

**Comment by fokodk** [comment]
It seems it was Admin privilege I was missing, after a reboot and start as Administrator no error.
