### ISSUE TITLE
Can a Public IP ?

### ISSUE THREAD

**Issue by ifeelingz** [duplicati/duplicati#2236]
"Server has started and is listening on 127.0.0.1, port 8200"

Can a Public IP ?
*I set it on my Linix (CentOS 7)

Thank you.

**Comment by agrajaghh** [comment]
have a look at https://github.com/duplicati/duplicati/issues/2215#issuecomment-269704506

does this answer your question?

**Comment by ifeelingz** [comment]
duplicati-server --webservice-port=1234 --webservice-interface=any

thank 👍
