### ISSUE TITLE
[Q] Are Duplicati jobs tied to the user account who created them?

### ISSUE THREAD

**Issue by Kharnivora** [duplicati/duplicati#2239]
Hi,

we use Duplicati 2 to backup some stuff from our Windows SBS 2011. This backup stopped running properly, I´m currently trying to figure out why. I wanted to restart Duplicati first, but I have a problem:

Three users actually do stuff on the server (usually connect via rdp): 
User A can see the backup job. If he double clicks the tray icon http://127.0.0.1:8200/ is opened.
User B can not see the backup job. If he double clicks the tray icon http://127.0.0.1:8300/ is opened.
User C can not see the backup job. If he double clicks the tray icon http://127.0.0.1:8400/ is opened.

Question:
What happens if I kill the process of user A and all other Duplicati processes?
- If I start Duplicati 2 , can I see the backup job, because my GUI will run on Port 8200?
- Can only user A see the job, regardless on which port his GUI is accessible?
- Is the job lost?

**Comment by kees-z** [comment]
I assume you are using Duplicati by starting Duplicati.GUI.TrayIcon.exe.
If no options are specified when starting up Duplicati, it will use the folder %APPDATA%\Duplicati to store information like backup configurations.
So in that case, Duplicati is indeed tied to the currently logged-on user account.

However, there are some possibilities to change this. When running Duplicati on a server, like you do, the best way to use Duplicati is to install it as a Windows Service.
To do this, open an administrative command prompt, change to the Duplicati installation folder and type the following command:

`Duplicati.WindowsService.exe install --webservice-interface=loopback --webservice-port=8200`

This will install a Windows Service named Duplicati that starts the webservice in the background using the Windows SYSTEM account. Before any user logs on to the console, Duplicati is already active and can execute scheduled backups.

If you want to store local databases at the same location as the program, add `--portable-mode` to the above command.
If you want to be able to access the web interface from another host in your network, change `--webservice-interface=loopback` to `--webservice-interface=any` in the command above.

**Comment by Kharnivora** [comment]
Thank you for your detailed answer :)
