### ISSUE TITLE
Mobile UI does not properly display progress

### ISSUE THREAD

**Issue by autumnwalker** [duplicati/duplicati#2243]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.39_canary_2017-01-08
**Operating System:** Ubuntu 16.04
**Backend:** Amazon Cloud Drive

### Bug description
When viewing the Duplicati WebUI on a mobile device (e.g. iPad), the "running task" progress bar does not correctly update - shows correct number of files and size, but never updates to show progress. Blue progress bar does not appear / advance.

**Comment by kees-z** [comment]
I have the same symptoms in any Duplicati version when using Internet Explorer.
All other web browsers I tried show the blue progress bar, IE doesn't.

**Comment by idotj** [comment]
Microsoft finally retired Internet Explorer this year. Should this issue be closed?

**Comment by ts678** [comment]
The original issue was about a mobile device, however it was five years ago. Chrome on Android currently works fine for me.
Internet Explorer (genuine or Edge with the tab in Internet Explorer mode) shows the problem, and I agree that it's obsolete.
Is there still a mobile browser that doesn't work? Asking for feedback before closing (people can still search for it of course).
