### ISSUE TITLE
Huge time increase running backup from version 2.0.1.39

### ISSUE THREAD

**Issue by Athep** [duplicati/duplicati#2244]
Huge time increase running backup from version 2.0.1.39

Version 2.0.1.39: Duration: **01:46:51**.3696116
Version 2.0.1.38: Duration: **00:04:24**.2819620

Windows 10 with local network backend. 

When I'm reverting to version 2.0.1.38, speed is normal again.

`Version: 2.0.1.39_canary_2017-01-08
======================================

DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 99490
OpenedFiles: 0
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 69071059104
SizeOfOpenedFiles: 0
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults: null
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20160914T163909Z.dlist.zip.aes
        Value: [],
        Key: duplicati-ic381187982e6430490dfd2735038bc4d.dindex.zip.aes
        Value: [],
        Key: duplicati-bb514a3d598a142a2a094a5b1b4ec6308.dblock.zip.aes
        Value: []
    ]
    EndTime: 2017-01-10 10:43:02
    BeginTime: 2017-01-10 10:42:59
    Duration: 00:00:03.3271390
    BackendStatistics:
        RemoteCalls: 5
        BytesUploaded: 0
        BytesDownloaded: 124095303
        FilesUploaded: 0
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 285
        KnownFileSize: 23952601193
        LastBackupDate: 2017-01-09 22:35:05
        BackupListCount: 39
        TotalQuotaSpace: -1
        FreeQuotaSpace: -1
        AssignedQuotaSpace: -1
EndTime: 2017-01-10 10:43:03
BeginTime: 2017-01-10 08:56:11
Duration: 01:46:51.3696116
Messages: [
    removing file listed as Temporary: duplicati-b32571711dcfb4b6983b487db22a017c8.dblock.zip.aes,
    removing file listed as Temporary: duplicati-i603a61879a4343818de090c2861035cc.dindex.zip.aes
]
Warnings: []
Errors: []

----------------------------------------------------------------------------
Version 2.0.1.38_canary_2016-12-27
====================================

DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 99490
OpenedFiles: 0
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 69071059104
SizeOfOpenedFiles: 0
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults: null
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20160927T160820Z.dlist.zip.aes
        Value: [],
        Key: duplicati-ic4b76973905e44858e954c40b845ae24.dindex.zip.aes
        Value: [],
        Key: duplicati-bd7fe6dd3b5e146a3b66fbe5b596ba77f.dblock.zip.aes
        Value: []
    ]
    EndTime: 2017-01-10 08:54:38
    BeginTime: 2017-01-10 08:54:31
    Duration: 00:00:07.2343534
    BackendStatistics:
        RemoteCalls: 5
        BytesUploaded: 0
        BytesDownloaded: 217068263
        FilesUploaded: 0
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 285
        KnownFileSize: 23952601193
        LastBackupDate: 2017-01-09 22:35:05
        BackupListCount: 39
        TotalQuotaSpace: -1
        FreeQuotaSpace: -1
        AssignedQuotaSpace: -1
EndTime: 2017-01-10 08:54:39
BeginTime: 2017-01-10 08:50:14
Duration: 00:04:24.2819620
Messages: [
    removing file listed as Temporary: duplicati-bb15cad8a3a604d848bf47b5c226ef99b.dblock.zip.aes,
    removing file listed as Temporary: duplicati-i7547c392528644b491f68fec39a98066.dindex.zip.aes
]
Warnings: []
Errors: []`

**Comment by kenkendk** [comment]
This is most likely cause by 76aae5de7bf7bb2e5ae966aed1ae585344bd6215, which was supposed to make it faster :/

**Comment by dsutil** [comment]
I have huge time increase too. 

Linux Backup with network drive: 

Version 2.0.1.38: Duration: 00:18:13
Version 2.0.1.39:  Duration More than ten hours... :-(

**Comment by kenkendk** [comment]
Did version 2.0.1.40 fix the slowdown issue?

**Comment by dsutil** [comment]
For me yes:

Jan 14, 2017 1:14 PM: Result
DeletedFiles: 1174
DeletedFolders: 0
ModifiedFiles: 828
ExaminedFiles: 590829
OpenedFiles: 2719
AddedFiles: 1857
SizeOfModifiedFiles: 2614316314
SizeOfAddedFiles: 93647562
SizeOfExaminedFiles: 530685431160
SizeOfOpenedFiles: 2719669660
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 34
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults:
    DeletedFileCount: 8
    DownloadedFileCount: 0
    UploadedFileCount: 0
    DeletedFileSize: 419679880
    DownloadedFileSize: 0
    UploadedFileSize: 0
    Dryrun: False
    MainOperation: Compact
    EndTime: 14/01/2017 12:13:21
    BeginTime: 14/01/2017 12:12:55
    Duration: 00:00:25.1435490
    BackendStatistics:
        RemoteCalls: 29
        BytesUploaded: 767836035
        BytesDownloaded: 142228119
        FilesUploaded: 15
        FilesDownloaded: 3
        FilesDeleted: 9
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 6279
        KnownFileSize: 325623845339
        LastBackupDate: 14/01/2017 13:00:00
        BackupListCount: 7
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: -1
DeleteResults:
    DeletedSets: [
        Item1: 7
        Item2: 08/01/2017 13:00:06
    ]
    Dryrun: False
    MainOperation: Delete
    EndTime: 14/01/2017 12:13:21
    BeginTime: 14/01/2017 12:12:08
    Duration: 00:01:12.9314840
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170114T120000Z.dlist.zip.aes
        Value: [],
        Key: duplicati-ibd7ff0cadb4b4db193133a8c6c12e5e0.dindex.zip.aes
        Value: [],
        Key: duplicati-b33445605ae42403eae1ffdc3c3986eb0.dblock.zip.aes
        Value: []
    ]
    EndTime: 14/01/2017 12:14:46
    BeginTime: 14/01/2017 12:14:25
    Duration: 00:00:20.7249510
EndTime: 14/01/2017 12:14:46
BeginTime: 14/01/2017 12:00:00
Duration: 00:14:46.8575530
