### ISSUE TITLE
Change color of "running task" text or progress bar

### ISSUE THREAD

**Issue by autumnwalker** [duplicati/duplicati#2247]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.39_canary_2017-01-08
**Operating System:** Ubuntu 16.04
**Backend:** Amazon Cloud Drive

### Bug description
As progress bar scrolls across the "to go" text, the green text on the blue background becomes ... difficult.

### Suggestions
- Change color of text so that it can be read on either background color (with or without progress bar behind it).
- Change color of progress bar to a lighter color so that there is more contrast between it and text (#ededed - see sample)
- Take text out of progress bar and place below the bar to remove conflict
- Remove box shadow? :)

### Screenshots
![font_color](https://cloud.githubusercontent.com/assets/11489678/21818104/ef158d6c-d73c-11e6-9e6a-2abb0cc5e1a9.jpg)

![sample](https://cloud.githubusercontent.com/assets/11489678/21818533/9a343102-d73e-11e6-8205-043b66839fc1.jpg)

**Comment by kenkendk** [comment]
This was fixed with addff70f1008566fdf80ce4eee430710e10a4d48
