### ISSUE TITLE
Feature suggestion: non-encrypted, non-wrapped, individual file/folder synchronizing

### ISSUE THREAD

**Issue by chovan** [duplicati/duplicati#2248]
Hi 
Love the software. Thank you for your work.

Is it possible to add an option when backing up to cloud destination, no encryption, no wrap files into volumes, simply sync the files (with folder structure)? This will make it much easier to view the files on the cloud side. Especially for videos and photos.

Thanks!
Chovan

**Comment by kenkendk** [comment]
Nope. Syncing looks the same but is very different.
Please see: https://github.com/duplicati/duplicati/wiki/FAQ
