### ISSUE TITLE
Invalid blocks can not be cleaned up

### ISSUE THREAD

**Issue by BlackEdder0815** [duplicati/duplicati#2251]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.40
**Operating System:** Linux ARM
**Backend:** ACD via Filesystem Mount

### Bug description
Got verify error:
remote file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes is listed as Verified with size 0 but should be 52366653, please verify the sha256 hash "vWuHB9Dr2nljgFy1fvyNpjcfbiE/aVVCZtXINdwl3XM="
remote file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes is listed as Verified with size 0 but should be 52364333, please verify the sha256 hash "NiRc8Mdpp6nu6cnh1n+YUt9p5BtHJEpYyPxsa0Y0pdQ="
remote file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes is listed as Verified with size 0 but should be 52366077, please verify the sha256 hash "ITg3wx22AXu237fJl9pclG9FFr4q4A/CfwDLl9wZ/OQ="

I'm not able to clean up this error. I tried repair, purge, compact, delete the files.... no luck

### Steps to reproduce
- Make an backup
- replace a block-file with an empty (0 bytes) file.
- run a verify

**Actual result:** verify failed, no possibility to correct the backup
**Expected result:** a way to correct the backup, if the source-data is still present. All warnings/errors have to be cleaned, when the backup is successfully "repaired"

### debug log
Verify:
  Listing remote folder ...
remote file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes is listed as Verified with size 0 but should be 52366653, please verify the sha256 hash "vWuHB9Dr2nljgFy1fvyNpjcfbiE/aVVCZtXINdwl3XM="
remote file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes is listed as Verified with size 0 but should be 52364333, please verify the sha256 hash "NiRc8Mdpp6nu6cnh1n+YUt9p5BtHJEpYyPxsa0Y0pdQ="
remote file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes is listed as Verified with size 0 but should be 52366077, please verify the sha256 hash "ITg3wx22AXu237fJl9pclG9FFr4q4A/CfwDLl9wZ/OQ="
  Downloading file (241,04 KB) ...
  Downloading file (35,34 KB) ...
  Downloading file (49,95 MB) ...
Examined 3 files and found no errors

Repair:
  Listing remote folder ...
remote file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes is listed as Verified with size 0 but should be 52366653, please verify the sha256 hash "vWuHB9Dr2nljgFy1fvyNpjcfbiE/aVVCZtXINdwl3XM="
remote file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes is listed as Verified with size 0 but should be 52364333, please verify the sha256 hash "NiRc8Mdpp6nu6cnh1n+YUt9p5BtHJEpYyPxsa0Y0pdQ="
remote file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes is listed as Verified with size 0 but should be 52366077, please verify the sha256 hash "ITg3wx22AXu237fJl9pclG9FFr4q4A/CfwDLl9wZ/OQ="
  Downloading file (unknown) ...
Operation Get with file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes attempt 1 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes attempt 2 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes attempt 3 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes attempt 4 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes attempt 5 of 5 failed with message: Invalid header marker => Invalid header marker
Failed to perform verification for file: duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes, please run verify; message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes attempt 1 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes attempt 2 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes attempt 3 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes attempt 4 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes attempt 5 of 5 failed with message: Invalid header marker => Invalid header marker
Failed to perform verification for file: duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes, please run verify; message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes attempt 1 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes attempt 2 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes attempt 3 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes attempt 4 of 5 failed with message: Invalid header marker => Invalid header marker
  Downloading file (unknown) ...
Operation Get with file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes attempt 5 of 5 failed with message: Invalid header marker => Invalid header marker
Failed to perform verification for file: duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes, please run verify; message: Invalid header marker => Invalid header marker

**Comment by canove** [comment]
Did you tried the "Recreate (delete and repair)" option?

**Comment by BlackEdder0815** [comment]
Yes, but to get a fresh report, I just created it again - without success :-( :

DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 1
ExaminedFiles: 3323
OpenedFiles: 1
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 9314378320
SizeOfOpenedFiles: 402
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults:
    DeletedFileCount: 0
    DownloadedFileCount: 0
    UploadedFileCount: 0
    DeletedFileSize: 0
    DownloadedFileSize: 0
    UploadedFileSize: 0
    Dryrun: False
    MainOperation: Compact
    EndTime: 01/12/2017 22:36:59
    BeginTime: 01/12/2017 22:36:55
    Duration: 00:00:03.3708180
    BackendStatistics:
        RemoteCalls: 8
        BytesUploaded: 248887
        BytesDownloaded: 52664343
        FilesUploaded: 3
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 313
        KnownFileSize: 7868625102
        LastBackupDate: 01/12/2017 23:35:30
        BackupListCount: 3
        TotalQuotaSpace: 109951162777600
        FreeQuotaSpace: 109932410044416
        AssignedQuotaSpace: -1
DeleteResults: null
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170112T102032Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i91bdc30c264b4200a4ecb78a78788d8f.dindex.zip.aes
        Value: [],
        Key: duplicati-bed3e8c9748db4e169c43f34a6a27a3b2.dblock.zip.aes
        Value: []
    ]
    EndTime: 01/12/2017 22:39:23
    BeginTime: 01/12/2017 22:37:26
    Duration: 00:01:57.1450080
EndTime: 01/12/2017 22:39:23
BeginTime: 01/12/2017 22:35:29
Duration: 00:03:53.7719320
Messages: [
    Compacting not required
]
Warnings: [
    remote file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes is listed as Verified with size 0 but should be 52366653, please verify the sha256 hash "vWuHB9Dr2nljgFy1fvyNpjcfbiE/aVVCZtXINdwl3XM=",
    remote file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes is listed as Verified with size 0 but should be 52364333, please verify the sha256 hash "NiRc8Mdpp6nu6cnh1n+YUt9p5BtHJEpYyPxsa0Y0pdQ=",
    remote file duplicati-bade5355cd40b43bb8364ff38a7e283a8.dblock.zip.aes is listed as Verified with size 0 but should be 52366077, please verify the sha256 hash "ITg3wx22AXu237fJl9pclG9FFr4q4A/CfwDLl9wZ/OQ=",
    remote file duplicati-b4c3d40ad78e4413ab710fd7e16324922.dblock.zip.aes is listed as Verified with size 0 but should be 52366653, please verify the sha256 hash "vWuHB9Dr2nljgFy1fvyNpjcfbiE/aVVCZtXINdwl3XM=",
    remote file duplicati-b88f6126905784408ac0ae596c362aac6.dblock.zip.aes is listed as Verified with size 0 but should be 52364333, please verify the sha256 hash "NiRc8Mdpp6nu6cnh1n+YUt9p5BtHJEpYyPxsa0Y0pdQ=",
...
]
Errors: []

**Comment by BlackEdder0815** [comment]
I studied a "related" solved bug: #1122

So I tried now a few different things:
- I deleted the related aes.zip files. Without luck
- I deleted the related dlist-files, in hope, that the files would be recreated without the missing block-files. Without luck
- I restored the before deleted files and tried to purge the affected files. This ended (with a tryrun) in following message:
```
Refusing to purge 3531 files from fileset with ID 1, as that would remove the entire fileset.
To delete a fileset, use the "delete" command.
```
So, now I'm out of ideas.....

**Comment by kenkendk** [comment]
I just noticed that you wrote "filesystem mount".
Does that mean that you have mounted ACD via FUSE?
If yes, I think there is a problem with reporting the size of files from FUSE.
If you go into the folder and issue `ls -lah` do you see the file sizes then?

**Comment by BlackEdder0815** [comment]
You are completely right. I'm using the FUSE driver for mounting the ACD.

I checked the sizes and checked it against the sizes, which are the amazon cloud webapp reports. The sizes are in sync.
I see the mentioned three files, which are zero. The rest seems to be fine.
Maybe, there was a problem while uploading via fuse, so the file-size is zero.
But that's not, what the bug-report is about.
The issue is about: I have a backup, which seems to be broken. The source-files are still present and I want to "repair" it, without deleting the complete 10 GB backup and run it again, just because one (three) files are invalid.
Duplicati seems to bring all relevant tools: purge-broken-files should do the job, and remove the invalid files from the backup. After this, the backup should be valid again.
Another run of the Backup will try to add the file again, if the file is still present in the source.

This is just my view.

**Comment by kenkendk** [comment]
It looks like the files are actually broken? 
The "invalid header marker" happens when the first few bytes of the file are not the AESCrypt header. Can you see what the first few bytes of the files are?

The tool to fix broken remote files is `purge-broken-files`. However, I expect that people will use it and loose more data than they expected, so I put in a safeguard that stops if the purge will drop an entire fileset, which is what you are seeing.

You can try `list-broken-files` to see what files will be removed.
Another command `affected` can show you what filelists are affected if you have a broken `dblock` file.

To recover, you need to drop the fileset with the error, as that is what is not working.

**Comment by kenkendk** [comment]
If I understand your question, you are asking: "why not just fix this automatically?".

The reason is, that is something is wrong, and I want human intervention in such a situation.
On a daily basis, the backup should just run, and you should never be forced to look at it.

However, when things go wrong, they need to be fixed somehow.
If Duplicati were to do this automatically, you would never know there was a problem.
But the "fixing" would cause some data to be delete.

That means you can have a situation where the backup runs and completes.
But each time it is actually broken, and then deleted.
This means that you end up having less working backups than you expected, and you only discover this when you really need it not to be broken.

Another reason for not doing automatic repair is that Duplicati can only detect "something" is wrong, not "why" it has happened. The "why" could be caused by different things:

  - Faulty backend
  - Duplicati bug
  - User change
  - Temporary failures
  - etc

Each of these "why" scenarios need different handling. You do not want to delete stuff if the problem is temporary. If the backend is faulty, you do not want to just delete stuff and keep going, you want to switch backend and so on.

In your case, you have the problem that the files are of length zero. This is problematic because some backends return length zero as a placeholder, if the length is unknown. This causes the error message that you see. Had they had a single byte, Duplicati would flat out reject them, but with zero bytes, it simply warns you that it should not be like this.

If the files are empty, I suggest removing them, as that will stop that part of the problem.

After you have removed the zero-length files, `purge-broken-files` will identify them as missing and attempt to delete the related files. However, this will hit the same limitation as before, that the purge will not allow you to delete all files in a fileset.

Maybe that part should be changed, such that `purge-broken-files` automatically removes the faulty sets completely. After all, the user is actively trying to remove stuff, so the check here is perhaps a bit to overprotective. Alternatively, the "refusing to delete" command should perhaps state exactly what command you need to run to remove the filesets.

You can remove the fileset by running something like:

```
mono Duplicati.CommandLine.exe delete /path/to/acd/mount 0 1 --dry-run
```

Remove `--dry-run` to have it actually happen. After that, your database should be in order again. The `0 1` indicates that sets `0` and `1` are dropped, and I took those numbers from your list above the `affected` command.

If you have input to make Duplicati better (and less frustrating) in these error scenarios, I would love to hear it.

**Comment by BlackEdder0815** [comment]
First: Thank you, for your discussion!!

> If I understand your question, you are asking: "why not just fix this automatically?".
No, I don't want to do this automatically, and I understand, why you do this not automatically!

I give you an example:
You want to backup 150GB of data. This will initially take 4 days, till the backup is uploaded to a dedicated backup drive.
After this run, in the log is a message, that some files are not matching the checksum.
You inspect the files, and see, there are 3 files (of 3000) which are zero. You don't know, why they are zero, maybe due an interruption of your internet connection, or whatever.
Now, you want to fix your initial backup-run, _without doing it from scratch again_. So, just upload the missing 3 files, instead of purging the full backup, waiting another 4 days and see, that maybe 2 files are zero again, due an interruption of your internet connection.

Currently (for me) duplicati **cannot** repair my backup and just upload the missing files. I have no way found, to do this either manual or automatically.
The only way currently seems to be to purge the file-sets 0 and 1, which will result in an completely purge of my whole backup, because there are no other file-sets than the set "0" and "1".

Maybe this example helps you, to understand my issue...
Best Regards

**Comment by kenkendk** [comment]
I understand it now (or I think I do :) ).

First, remove the zero-length files as that messes everything up.
Then run the "repair" command:

```
mono Duplicati.CommandLine.exe repair /path/to/acd/mount
```

Duplicati will then notice that 3 files are missing and start to rebuild them. If you have all the data that is required to rebuild the missing files, then the files will be rebuilt and put in their place.

In some cases, you are missing data, most likely a timestamp has changed on a file, and then repair will not work. It would be nice if there was some "drop the stupid metadata and move along" option, but there is no such thing at the moment.

It sounds strange that you have 3000 remote files, but `purge-broken-files` will completely drop the fileset if only 3 blocks are missing. If you can run:

```
mono Duplicati.CommandLine.exe repair /path/to/acd/mount report.zip
```

If you send me the `report.zip`, I can have a look and see if I can figure out why it wants to drop the entire fileset.

**Comment by BlackEdder0815** [comment]
So, I want to give a final feedback.
Now on duplicati v2.0.1.44.
To solve the issue above, you have to do the following (in this order!):

- Remove the 0-bytes-file by deleting it by hand
- run a `repair`
- run a `list-broken-files` (just for your information, which file(s) are affected)
- run a `purge-broken-files`
- run a `verify`. This have to report no errors or warnings.
- run the backup again. Duplicati will now try to collect the missing file(s)

This worked for me.

I think, I have another issue, that duplicati crashes always with the same file, but for this I will open a new ticket, to prevent confusion.

@kenkendk Very much thank you for the support! Maybe this ticket can be used for a feature request to simplify the steps above.
I will close this ticket, because it's not a bug, yet.

**Comment by NCNecros** [comment]
`purge-broken-files` is a useful command. But if I `purge-broken-files` and make a new backup set, duplicati  don't recreate this files in previous backup sets.

By step:

- run `PS D:\Temp\2017-02-07> & 'C:\Program Files\Duplicati 2\Duplicati.CommandLine.exe' backup "D:\Temp\2017-02-07\bak" "D:\Dropbox" --no-encryption=true`
- delete one `dblock.zip`
-run `list-broken-files`

```
No broken filesets found in database, checking for missing remote files
  Listing remote folder ...
Marked 1 remote files for deletion
2       : 07.02.2017 14:18:15   (1 match(es))
        D:\Dropbox\StacMct201607280900.zip (910,32 MB)
1       : 07.02.2017 14:44:12   (1 match(es))
        D:\Dropbox\StacMct201607280900.zip (910,32 MB)
0       : 07.02.2017 15:13:50   (1 match(es))
        D:\Dropbox\StacMct201607280900.zip (910,32 MB)
```
- run `purge-broken-files`
- run `backup`
- run `list "D:\Temp\2017-02-07\bak" "D:\Dropbox\StacMct201607280900.zip" --all-versions=true --no-encryption=true` 

```
Listing files and versions:
D:\Dropbox\StacMct201607280900.zip
0       : 07.02.2017 15:26:34 910,32 MB
1       : 07.02.2017 15:13:51  -
2       : 07.02.2017 14:44:13  -
3       : 07.02.2017 14:18:16  -
```

It didn't recreate in previous backup sets. It will be fine if the duplicati recreate this files in previous backups if the hash of files match.

**Comment by BlackEdder0815** [comment]
My experience was: always do a `verify` with help of the cli, after the `purge-broken-files`. If no error or warning is printed anymore, the next backup will collect the files again.
