### ISSUE TITLE
2.0.1.40 does not offer a ZIP download any more?

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#2252]
Minor one not related directly to Duplicati, but the publishing process:

On https://github.com/duplicati/duplicati/releases, you could download a ZIP archive up to version 2.0.1.39. With 2.0.1.40, there's no (binary) ZIP any more.

**Comment by kenkendk** [comment]
Thanks for reporting. The Github upload is a bit unstable, so this file was omitted during the automatic upload.
I have uploaded the correct file now.
