### ISSUE TITLE
Duplicati crashes when altering block or volume size

### ISSUE THREAD

**Issue by autumnwalker** [duplicati/duplicati#2253]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.40_canary_2017-01-12
**Operating System:** Ubuntu 16.04
**Backend:** Amazon Cloud Drive (ACD)

### Bug description
I have successfully run ~ 140GB of backup to ACD using the default block and volume sizes where the backup tasks consisted of "regular" sized files.

I started a new task which contained > 4.5TB of data where most files are > 5GB. With the 100kb block and 50MB volume the backup was taking forever, I tried increasing the block to 500MB and the volume to 500MB to match and Duplicati will crash after attempting to upload the first volume. Watching the system monitor I can see that it consumes all available RAM (3GB physical, 2GB swap). The file is never uploaded to ACD.

I tried to ratchet down the volume / block size to various sizes including 250MB, 100MB and different combinations of block and volume, but anything over the defaults of 50MB / 100kb will cause Duplicati to crash.

I'm looking at the logs in the WebUI, but I don't see anything of relevance. I'm not sure where to look to help you diagnose.

**Comment by kenkendk** [comment]
Generally, you can choose large `--dblock-size` aka volume size. I think there was a reported problem if `--blocksize` was 50MB or larger. I think there is some computation that overflows 32 bit, that causes this.

Can you try with `--blocksize=1MB --dblock-size=250MB` and see if it still crashes?

**Comment by autumnwalker** [comment]
Thanks @kenkendk! It seems to be chugging along happily now. I will have benchmark to see if there is a speed improvement. It has been running overnight and has not crashed.

You mention an overflow of 32bit; however, this is a 64bit system.

**Comment by kenkendk** [comment]
The 32bit overflow is caused by the default number type in C# being 32 bit. It does not matter what architecture/operating system you use.

**Comment by autumnwalker** [comment]
Ok, that makes sense.

Unfortunately Duplicati just crashed again. Any suggestions on how I can get you useful info to diagnose?

**Comment by warwickmm** [comment]
Support for Amazon Cloud Drive has been removed.  If you're still experiencing this with other backend, please reopen this with new details.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
