### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by daest** [duplicati/duplicati#2255]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.40-1
**Operating System:** Ubuntu 14.04
**Backend:**

### Bug description
System crash after round about 30s. I get following output when executing duplicati from cammand line:

[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: timeout
  at System.Threading.WaitHandle.WaitOne (TimeSpan timeout, Boolean exitContext) [0x00000] in <filename unknown>:0 
  at Duplicati.Server.UpdatePollThread.Run () [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 

### Steps to reproduce
- Executing duplicati
- wait for 30s

Some days before, I changed the system time for some tests to a date in future, while duplicati was running. Could this be the reason for this behavior?

**Comment by kenkendk** [comment]
I think it has something to do with the date being in the future. Maybe there is somewhere that "time to wait" is computed and returns a negative value.

**Comment by ts678** [comment]
> wait for 30s

My Duplicati stays up well past this. Are there some specific steps required? Does it still happen? Maybe something got fixed...

**Comment by ts678** [comment]
If a time change is involved, I need more details. It's not even stated what sort of operation was only staying up for 30 seconds.
The 'time to wait' going negative sounds like the kind of thing that would happen if time changed during the run, not between.
Removing the `bug` label until a little more is known about this. If nothing more comes, issue will then eventually close by itself.
