### ISSUE TITLE
Upload to Amazon S3 very slow (different regions, only S3 backend)

### ISSUE THREAD

**Issue by nibblerrick** [duplicati/duplicati#2256]
- [x] searched open and closed issues for duplicates
Found nothing really relevant, hopefully I searched it really all
----------------------------------------

**Duplicati Version:** 2.0.1.35 and 2.0.1.40
**Operating System:** Windows Server 2008 and 2008 R2

I ran Duplicati on two machines and tried to back up several gigs. CPU and Disk IO were OK, no bottleneck here.
Uploadspeed was most of the time 1-2 Mbit/s. My upstream is 10 MBit/s.
When using Cloudberrybackup to backup to S3 from the same machines I max out my upstream.
When I tried Google Drive as Backupspeed Duplicati maxed out the bandwith.
When testing the S3 upload-acceleration-test it maxes out my upstream to almost all S3 regions with and without acceleration.
I tried also to create buckets in different regions (Frankfurt, London, Ireland, different US-locations, I am based in germany). Uploadspeed from duplicati everytime 1-2 MBit/s.

So it seems that is something related between Duplicati and S3.
At the moment with the S3-problem it isn't so usable for bigger backups which sucks, because Duplicati 2 runs really good (why hasn't someone told me before of this?)

Is there anything I can test or try to debug this?

**Comment by nibblerrick** [comment]
Anythin on this? Behaviour is the same now.

**Comment by eyal0** [comment]
I'm seeing this, too.  Maybe other services use multiple threads or upload multiple files at a time?

**Comment by nibblerrick** [comment]
Any news on your tests?

**Comment by eyal0** [comment]
I didn't have a chance to test further.  I did test with Google Drive, however, and it's just as slow.  It might simply be my uplink which is slow.

**Comment by nibblerrick** [comment]
I've tested last month and this month and the uploadspeed is now max speed my connection allows. I don't know what has changed but it seems to work now, so I'll close this.
