### ISSUE TITLE
Parsed result "Succesful", however errors/warnings are logged

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2257]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35 Experimental
**Operating System:** Windows 10
**Backend:** WebDAV

### Bug description
One of my backup jobs is a single folder with about 40 GB data located in subfolders. The content of this folder is not changed frequently, so after a number of backup sessions, there still is 1 version.

The last backup job also didn't upload any new data to the backend and I got an email with the subject "Success: Duplicati Backup report for _backup job name_".

However, when I browse through the log file, I see a line: "FilesWithError: 3" and 3 warning messages "Failed to process path ... constraint failed".

To check if anything is corrupted at the backend side, I did a restore of all files to an empty folder. Before I started the restore (with Restore Backup, so the local database will not be used), I renamed the root folder of the backup source, to force Duplicati to download all files from the backend, without using local blocks.
The restore task completed successfully, all files and folders were recreated without any problem.

So I think something went wrong when reading the source files, which caused the warnings and my backup files are not corrupted.
However, there were some problems when running the backup task, so the parsed result should not be "Successful", but "Warning", indicating that there were issues when running the backup.

**Actual result:** After running a backup task that had issues, sometimes (always?) the parsed result is "successful".
**Expected result:** If there are any issues, including issues that don't affect the integrity of files at the remote side, the parsed result should become "Warning" or "Error".

### Logfile

DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 18103
OpenedFiles: 5735
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 45205110367
SizeOfOpenedFiles: 41688225785
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 3
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    CompactResults: null
    EndTime: 15-1-2017 01:31:50
    BeginTime: 15-1-2017 01:31:47
    Duration: 00:00:02.7810105
    BackendStatistics:
        RemoteCalls: 23
        BytesUploaded: 0
        BytesDownloaded: 526166241
        FilesUploaded: 0
        FilesDownloaded: 21
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 1663
        KnownFileSize: 43562694707
        LastBackupDate: 4-1-2017 17:09:37
        BackupListCount: 1
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: -1
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170104T160937Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i61df4281440b46ef8a13ff10954b59ca.dindex.zip.aes
        Value: [],
        Key: duplicati-i723444dcfd104c9285f9d62ae8cb3e10.dindex.zip.aes
        Value: [],
        Key: duplicati-i7866e43586b2414d9f60cd60f73e3396.dindex.zip.aes
        Value: [],
        Key: duplicati-i7be2a030caf94d9ea8b8825907ea3bd0.dindex.zip.aes
        Value: [],
...
    ]
    EndTime: 15-1-2017 01:33:46
    BeginTime: 15-1-2017 01:31:58
    Duration: 00:01:48.3451681
EndTime: 15-1-2017 01:33:46
BeginTime: 15-1-2017 01:10:14
Duration: 00:23:32.6767271
Messages: [
    No remote filesets were deleted,
    removing file listed as Temporary: duplicati-b94ee8de5d5ac405aa59e4c4946b2be39.dblock.zip.aes,
    removing file listed as Temporary: duplicati-i0deaa0cd37d144f68905ca06c2371ed6.dindex.zip.aes
]
Warnings: [
    Failed to process path: D:\Path\to\a\source\folder\ => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID,
    Failed to process path: D:\Path\to\another\folder\somefile.exe => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID,
    Failed to process path: D:\Path\to\a\small\textfile.txt => constraint failed
UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID
]
Errors: []

**Comment by CottonEaster** [comment]
I have just had a similar experience (on Linux, but I imagine it might happen on other platforms too). To wit: a restore was successful, but there was a message about multiple warnings - but I cannot actually see the warnings.

![image](https://user-images.githubusercontent.com/9998846/29592083-b090a8aa-8791-11e7-8062-af456eaaf4c8.png)


Also, I think that the file's execute-bits were not restored correctly. I could report that as a seperate issue, but I think I'll just abandon Duplicati.

**Comment by kenkendk** [comment]
There is another report on issues with restoring the permissions on Linux here: https://forum.duplicati.com/t/linux-permission-not-restored-even-if-i-use-restore-permissions/129

**Comment by kenkendk** [comment]
To see the warnings, you need to expand the "Result" item. But yes, it is not good enough.

**Comment by CottonEaster** [comment]
I thought I did expand the 'result' item, and that, there, I discovered some informational messages but nothing that seemed like, or was labelled, a warning.

**Comment by CottonEaster** [comment]
As to restoring permissions (execute-bits): the problem may be that Duplicati doesn't itself have full permissions for the executable text files in question. Maybe. I'd have to experiment some more to know.
