### ISSUE TITLE
Amazon Cloud Drive OAuth test failing on Synology DS214+

### ISSUE THREAD

**Issue by Brandieee** [duplicati/duplicati#2258]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.40
**Operating System:** Synology NAS DS214+ with Mono 4.2.1.124
**Backend:** Amazon Cloud Drive

### Bug description
OAuth authentication test to Amazon Cloud Drive fails. Testing on Windows 10 x64 to same Amazon Cloud Drive does not.
Consistently getting the same error each time I attempt this. De-authing and going through same AuthID steps each time to force new token generation.

### Steps to reproduce
- Add new backup
- Create authentication token using AuthID link in setup
- Test newly created authentication

**Actual result:** Test fails consistently, even when creating new token
**Expected result:** Test should pass

### Error log
`Duplicati.Library.Interface.UserInformationException: Failed to authorize using the OAuth service: GetResponse timed out. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=amzcd ---> System.Net.WebException: GetResponse timed out ---> System.Net.WebException: Aborted. at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x2debcb60 + 0x00164> in <filename unknown>:0 at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.OnAsync (IAsyncResult r) <0x2e290a98 + 0x000ab> in <filename unknown>:0 --- End of inner exception stack trace --- at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () <0x2e28fd30 + 0x00124> in <filename unknown>:0 at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () <0x2ef4cd68 + 0x0012b> in <filename unknown>:0 at Duplicati.Library.JSONWebHelper.GetResponse (Duplicati.Library.Utility.AsyncHttpRequest req, System.Object requestdata) <0x2ef4c778 + 0x0040b> in <filename unknown>:0 --- End of inner exception stack trace --- at Duplicati.Library.OAuthHelper.get_AccessToken () <0x2ef4b9a8 + 0x00660> in <filename unknown>:0 at Duplicati.Library.OAuthHelper.CreateRequest (System.String url, System.String method) <0x2ef4b6c8 + 0x0006b> in <filename unknown>:0 at Duplicati.Library.JSONWebHelper.GetJSONData[T] (System.String url, System.Action`1 setup, System.Action`1 setupreq) <0x2ef4b5c0 + 0x00033> in <filename unknown>:0 at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.RefreshMetadataAndContentUrl () <0x2ef4b200 + 0x00177> in <filename unknown>:0 at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.get_MetadataUrl () <0x2ef4b0e8 + 0x0001f> in <filename unknown>:0 at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.List () <0x2ef4a650 + 0x0001f> in <filename unknown>:0 at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.Test () <0x2ef4a610 + 0x00013> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) <0x2ef47a30 + 0x002c3> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) <0x2ef475e0 + 0x001b7> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) <0x2e24fbf8 + 0x00e83> in <filename unknown>:0 `

**Comment by Brandieee** [comment]
This is probably unrelated but I just noticed that when opening the duplicati interface from the Main Menu of DSM for the first time after logging in I get a  "Missing XSRF Token" and UI elements such as drop down menus are missing entries, closing and reopening the interface seems to solve this issue.

**Comment by wjansenw** [comment]
I'm experiencing similar behavior when trying to use duplicati on Synology with webdav.

`Fatal error
System.Net.WebException: GetRequestStream timed out ---> System.Net.WebException: Aborted.
  at System.Net.HttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) <0x733593c8 + 0x000e8> in <filename unknown>:0 
  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.OnAsync (IAsyncResult r) <0x733589c8 + 0x00063> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Duplicati.Library.Main.BackendManager.List () <0x7124edf0 + 0x00134> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, IBackendWriter log) <0x7124c000 + 0x0024f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, IBackendWriter log) <0x71266150 + 0x000b7> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend) <0x71265130 + 0x00133> in <filename unknown>:0 `

Also, missing XSRF token and missing UI elements. It is not a network issue; as on the same network it is working fine with my windows machine.

XSRF token issue seems to be workarounded by following suggestion: https://support.todoist.com/hc/en-us/articles/208951085-What-to-do-when-you-see-Invalid-or-missing-CSRF-token-

**Comment by wjansenw** [comment]
2.0.1.44 fixed my main issue.
XSRF token still there

**Comment by Brandieee** [comment]
I unfortunately still have the problem. I've updated to 2.0.1.45 and the XSRF token issue persists, however I got a different error message, namely:
`Duplicati.Library.Utility.SslCertificateValidator+InvalidCertificateException: The server certificate had the error RemoteCertificateChainErrors and the hash F0C5FEC166685EBD85226ADB087A9C9D60B6F5C0 If you trust this certificate, use the commandline option --accept-specified-ssl-hash=F0C5FEC166685EBD85226ADB087A9C9D60B6F5C0 to accept the server certificate anyway. You can also attempt to import the server certificate into your operating systems trust pool. You may want to import a set of trusted certificates into the Mono certificate store. Use the command: cert-sync /etc/ssl/certs/ca-certificates.crt #for Debian based systems cert-sync /etc/pki/tls/certs/ca-bundle.crt #for RedHat derivatives Read more: http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync at Duplicati.Library.Utility.SslCertificateValidator.Deactivate () <0x2f66b6e0 + 0x00074> in <filename unknown>:0 at Duplicati.Library.Utility.SslCertificateValidator.Dispose () <0x2f66b690 + 0x00023> in <filename unknown>:0 at Duplicati.Library.Modules.Builtin.HttpOptions.Dispose () <0x2f66b5f8 + 0x00077> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) <0x2f644708 + 0x00713> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) <0x2f6442b8 + 0x001b7> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) <0x2e360000 + 0x00e7b> in <filename unknown>:0 `


Running **cert-sync from mono with sudo** fixed this issue, however the original one still persists:

`Duplicati.Library.Interface.UserInformationException: Failed to authorize using the OAuth service: GetResponse timed out. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=amzcd ---> System.Net.WebException: GetResponse timed out ---> System.Net.WebException: Aborted. at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x2f64f140 + 0x00164> in <filename unknown>:0 at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.OnAsync (IAsyncResult r) <0x2ef3edb8 + 0x000ab> in <filename unknown>:0 --- End of inner exception stack trace --- at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () <0x2e7c6d20 + 0x00124> in <filename unknown>:0 at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () <0x2f64a4c0 + 0x0012b> in <filename unknown>:0 at Duplicati.Library.JSONWebHelper.GetResponse (Duplicati.Library.Utility.AsyncHttpRequest req, System.Object requestdata) <0x2f649ed0 + 0x0040b> in <filename unknown>:0 --- End of inner exception stack trace --- at Duplicati.Library.OAuthHelper.get_AccessToken () <0x2f648ee0 + 0x00660> in <filename unknown>:0 at Duplicati.Library.OAuthHelper.CreateRequest (System.String url, System.String method) <0x2f648ab8 + 0x0006b> in <filename unknown>:0 at Duplicati.Library.JSONWebHelper.GetJSONData[T] (System.String url, System.Action`1 setup, System.Action`1 setupreq) <0x2f6489b0 + 0x00033> in <filename unknown>:0 at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.RefreshMetadataAndContentUrl () <0x2f648590 + 0x00177> in <filename unknown>:0 at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.get_MetadataUrl () <0x2f648478 + 0x0001f> in <filename unknown>:0 at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.List () <0x2f6479e0 + 0x0001f> in <filename unknown>:0 at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.Test () <0x2f6479a0 + 0x00013> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) <0x2f644708 + 0x002c3> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) <0x2f6442b8 + 0x001b7> in <filename unknown>:0 at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) <0x2e360000 + 0x00e7b> in <filename unknown>:0 `

**Comment by mhellmeier** [comment]
Same problem here:
OAuth test fails with Amazon Cloud Drive on an Ubuntu 16.04 server.

Hope to see an update soon - Duplicati isn't working without it.

**Comment by Narcolapser** [comment]
I'm running into this error as well. the weirdest part is I had duplicati working. I have about 20 or so gb in my amazon cloud drive a testing to the fact that it was working. But now it has stopped working. I'm confused. Any ideas one what's wrong?

**Comment by timothyparez** [comment]
OAuth failed with Amazon Cloud on DS416

**Comment by warwickmm** [comment]
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
