### ISSUE TITLE
Service Unavailable: Back-end server is at capacity

### ISSUE THREAD

**Issue by autumnwalker** [duplicati/duplicati#2264]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.40_canary_2017-01-12
**Operating System:** Ubuntu 16.04
**Backend:** Amazon Cloud Drive (ACD)

### Bug description
Received an error that "back-end server is at capacity" using Amazon Cloud Drive; space should be unlimited.

### debug log
System.Net.WebException: Service Unavailable: Back-end server is at capacity
  at Duplicati.Library.Main.BackendManager.WaitForComplete (Duplicati.Library.Main.Database.LocalDatabase db, IDbTransaction transation) <0x41dfe1f0 + 0x000ff> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) <0x41cf0870 + 0x01b0b> in <filename unknown>:0

**Comment by kenkendk** [comment]
I think this is related to the Amazon CloudDrive servers being in a bad state.
I don't think it is related to your account, nor Duplicati.

Does the problem persist?

**Comment by autumnwalker** [comment]
I fired it up again and seems to be running ok. I had the same thought that the issue being the ACD servers simply bailed.

Would it be worth putting something into Duplicati to silently retry or to perhaps clarify the error for ACD users? In testing another ACD backup solution, it does not experience this problem; however, I'm thinking it just doesn't display the issue to end users.

**Comment by ts678** [comment]
All comments so far sound like issue requires ACD. [Amazon Cloud Drive discontinued](https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391) removes the need for issue, I suppose.

**Comment by warwickmm** [comment]
I'm going to close this since support for Amazon Cloud Drive has been removed.  If this is still occurring with a different backend, please open a new issue.
