### ISSUE TITLE
start from commandline on server?

### ISSUE THREAD

**Issue by brafi** [duplicati/duplicati#2273]
How do I start duplicati from commandline on a ubuntu server with no desktop?

It keeps saying 
# duplicati
Server has started and is listening on 127.0.0.1, port 8200

(Duplicati.GUI.TrayIcon:31028): Gtk-WARNING **: cannot open display:

**Comment by kenkendk** [comment]
If you want to use the commandline, you can run:

```
duplicati-cli
```

If you want to run the server, and connect to it with a browser, you can run:
```
duplicati-server --webservice-interface=any
```

The `--webservice-interface` option enables you to connect from another machine than the one you are hosting it on.

There is some more information here:
http://www.duplicati.com/articles/Way-To-Make-A-Backup/
