### ISSUE TITLE
Some typos in Command Line tools and website

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2278]
A list of typos in the command line utilities:

Command: Duplicati.CommandLine.exe help find
Output: besearched
Expected: be searched

Command: Duplicati.CommandLine.exe examples
Output: onemonth
Expected: one month

Command: Duplicati.CommandLine.exe help affected
Output: explaning
Expected: explaining

Command: Duplicati.CommandLine.exe help s3
Output: european
Expected: European
Output: Northen
Expected: Northern

Command: Duplicati.CommandLine.exe help od4b
Output: timouts
Expected: timeouts

Command: Duplicati.CommandLine.exe help mssp
Output: timouts
Expected: timeouts

Command: Duplicati.CommandLine.exe help gpg
Output: Privary
Expected: Privacy

Command: Duplicati.CommandLine.exe help 7z
Output: cores..
Expected: cores.

Command: Duplicati.CommandLine.exe help console-password-input
Output: a encryption password
Expected: an encryption password
Output: commandline
Expected: command line
Output: atomatically
Expected: automatically

Command: Duplicati.CommandLine.exe help mssql-options
Output: internaly
Expected: internally
Output: atomatically
Expected: automatically

Command: Duplicati.CommandLine.exe help hyperv-options
Output: internaly
Expected: internally
Output: atomatically
Expected: automatically

Command: Duplicati.CommandLine.exe help http-options
Output: atomatically
Expected: automatically
Output: effeciently
Expected: efficiently

Command: Duplicati.CommandLine.exe help sendmail
Output: atomatically
Expected: automatically
Output: adresses
Expected: addresses
Output: seperated
Expected: separated
Output: adress
Expected: address
Output: commandline
Expected: command line
Output: seperator
Expected: separator

Command: Duplicati.CommandLine.exe help runscript
Output: atomatically
Expected: automatically

Command: Duplicati.CommandLine.exe help sendxmpp
Output: atomatically
Expected: automatically
Output: seperated
Expected: separated
Output: commandline
Expected: command line
Output: seperator
Expected: separator

Command: Duplicati.CommandLine.exe help check-mono-ssl
Output: atomatically
Expected: automatically

Command: Duplicati.CommandLine.exe help advanced
Output: commandline
Expected: command line
Output: plugable
Expected: pluggable
Output: more that one
Expected: more than one
Output: seperate
Expected: separate
Output: prefixed with with either
Expected: prefixed with either
Output: usefull
Expected: useful
Output: successfull
Expected: successful
Output: This settings controls
Expected: This setting controls
Output: linux
Expected: Linux

Command: Duplicati.CommandLine.RecoveryTool.exe help
Output: (in the Restore section): Duplicati.RecoveryTool.exe index <localfolder> [version] [options]
Expected: Duplicati.RecoveryTool.exe restore <localfolder> [version] [options]

Command: Duplicati.CommandLine.BackendTester.exe help
Output: valus
Expected: value

Command: Duplicati.Server.exe help
Output: commandline
Expected: command line
Output: --webservice-sslcertificatefile: The port The webserver listens on. Multiple values may be supplied with a comma in between.
Expected: Text from command line option --webservice-port is specified here.
Output: --webservice-sslcertificatepassword: The port the webserver listens on. Multiple values may be supplied with a comma in between.
Expected: Text from command line option --webservice-port is specified here.

On the website under Articles:

URL: http://www.duplicati.com/articles/Windows-Drive-Letters/
Output: driver letters
Expected: drive letters

**Comment by kenkendk** [comment]
Thanks for the comprehensive list!
