### ISSUE TITLE
Backups don't run on schedule

### ISSUE THREAD

**Issue by SBoat** [duplicati/duplicati#2280]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35
**Operating System:** Mac OS Sierra
**Backend:**
MS OneDrive
Box Sync

### Bug description
I have two backups of a file that is on a network shared drive. I backup to MS OneDrive and BoxSync. I have them scheduled to run at 3:00 AM and 4:00 AM respectively. The file is 1GB and the backups take between one and two minutes each. I have verified they are successful and can be restored.

The backups never run at their specified times. They run at a variety of times, e.g. 7:30 AM, 12:45 PM and so on. Sometimes one will run immediately after the other or other times they run hours apart. Sometimes they miss a day and run the following day.

### Steps to reproduce
- Setup two separate backups scheduled to run at 3:00 and 4:00 AM
- Check the backups i
**Actual result:** 
- On checking around 8:00 AM they may or may not have run. If they did the time will be other than when specified. 
- Sometimes they begin to run when I'm checking at 8:00 AM
 
**Expected result:** 
- I expect them to run at their specified times

**Comment by agrajaghh** [comment]
I think I read a smiliar bug report but can't find it anymore...

**Comment by SBoat** [comment]
I'd found issue #1935 that is about making changes to a schedule not working properly. I think my issue is different.

**Comment by SBoat** [comment]
OK - I should close this. Both backkups ran on time for two days in a row now. I hadn't done anything so I'm not sure what changed. I'll keep an eye on it to see if it starts happening again.

**Comment by SBoat** [comment]
close #2280

**Comment by SBoat** [comment]
OK - I'm going to reopen this. This morning when checking, the backup scheduled for 3AM had run at 6:05. The one scheduled for 4AM began running when I opened Duplicati to check at 7:35. The schedule seems to work randomly.

**Comment by SBoat** [comment]
I'm going to close this again. The two backups have run on schedule for the last three days. Originally I'd set "disable-filetime-chedk" in Settings. The change I'd made was to set it individually in both backups. I'm not sure why this would impact the schedule but for now it seems to be working. I've also upgraded to 2.0.1.45 and that may have done something as well. For now all is good.
