### ISSUE TITLE
Wrong temp folder crash.

### ISSUE THREAD

**Issue by KiUserExceptionDispatcher** [duplicati/duplicati#2283]
Duplicati Version: 1.3.4
Windows XP SP3

I had a RAM disc where I kept %temp% folder (x:\temp). Once time I removed it from my system (no more x:\) and restored %temp% to c:\temp. After that duplicate crashes every time, because of invalid temp/signature cache settings (x:\temp).

**Comment by kenkendk** [comment]
Yes, that is a known issue with 1.3.x. We are no longer maintaining the 1.3.x version.
