### ISSUE TITLE
New icons too small

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2284]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.44 Canary
**Operating System:** Windows 10

### Bug description
The new icons "Home" and "About" in the web interface have a size of 16x16 pixels.
They should be 26x26 pixels to be in line with the other icons.

### Screenshots
Current menu:
![menu1](https://cloud.githubusercontent.com/assets/24669568/22248965/4ef8f21e-e241-11e6-922a-0f87fa0aba13.PNG)

Home and About icons should be something like this:
![menu2](https://cloud.githubusercontent.com/assets/24669568/22248970/5267d2c6-e241-11e6-9b3c-8ebb42d87a57.PNG)

**Comment by kenkendk** [comment]
This was fixed with https://github.com/duplicati/duplicati/commit/9ba58cfbb4b848d382bcb95cba0f78d1d70dcd1b
