### ISSUE TITLE
No Duplicati logo / Menu inaccessible on low resolution systems

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2286]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35
**Operating System:** Windows 10

### Bug description
Design improvement suggestions:
1) The nice looking Duplicati logo is missing from the web interface. If the logo is added to the title bar, Duplicati could look something like this:

![duplicatiwithlogo](https://cloud.githubusercontent.com/assets/24669568/22310187/ad95d8e2-e34e-11e6-81ee-25788ce2b782.png)

2) This solves another issue with the web interface. When reducing the horizontal resolution, the menu options on the left side disappear and a menu button in the upper right corner is displayed. But when the resolution is reduced a bit more, the menu button disappears, making it impossible to access the main menu options. This is the case with my mobile phone (Samsung Galaxy S4).
The reason for this is probably that the word Experimental overlaps the space needed to display the menu button.
Placing the text "Experimental", "Canary" etc. under the word Duplicati (see screenshot above) generates more free space to display the menu button.
Additionally the menu button should have priority over the other content in the title bar, so it is always possible to choose a menu option, regardless of the resolution.

Menu button upper right corner when using lower resolution:
![duplicatimenuvisible](https://cloud.githubusercontent.com/assets/24669568/22310562/e60d04d8-e34f-11e6-8cc4-9e293b07b759.PNG) 

Menu button disappears when horizontal resolution is slightly reduced:
![duplicatimenuinvisible](https://cloud.githubusercontent.com/assets/24669568/22310575/ed5a56aa-e34f-11e6-972b-7d0a43646cd3.PNG)

3) The About screen is displayed twice in the main window: in the main menu and in the lower left corner. One of them can be removed. For me, the link in the lower left corner is good enough, this is the obvious location for me. The new link in the main menu makes the list unnecessary longer, thus more confusing. But removing it from the footer should be ok too.

**Comment by kenkendk** [comment]
This was fixed with e4d8058
