### ISSUE TITLE
C ommandline export might substitute ascii in auth for hex

### ISSUE THREAD

**Issue by topsey** [duplicati/duplicati#2288]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.44_canary_2017-01-24
**Operating System:** win 10
**Backend:**

### Bug description
Export as commandline might substitute ascii in auth for hex

### Steps to reproduce
Set up a backup job
Amazon cloud destination
Place : at the start of the AuthId in destination
Save job
Export as commandline
Check AuthId you will see : has been replaced with %3A

**Comment by kenkendk** [comment]
The "connection string" passed to the commandline should be a proper URL, although it accepts many "improper" things.

In other words, this conversion is intentional. Does it fail to work if you use the URL encoded value on the commandline?

**Comment by topsey** [comment]
Hi Ken, yes it will fail with the url encoded version.

It's the AuthId as below the eg a colon is replaced with the hex %3A in the export function.

"amzcd://DuplicatiPath?authid=%3A6d4528tdb57143d4140158z433587e8176%3ACo0uS3k8kBiTh7OoBh-7Da"

You would probably need to do something like **%3A** so as to avoid a situation where the AuthId contains a hex value or just don't url encode the AuthId part therefore not having to alter the passing of the `var backend = args[0];`

**Comment by kenkendk** [comment]
I just tested this again today, and it works fine for me, so I am not sure where it breaks for you.

If I generate a new authID, it will look something like `abc:1234`.
The export will then create a string like `amzcd://test?authid=abc%3A1234`
If I pass that value to the commandline, it will correctly decode back into `abc:1234`.

In your version you have a leading `:`, which I don't think should be there?

**Comment by kenkendk** [comment]
Is the problem that the command prompt sees `%3A......%3A` and substitutes `%3A......%` with an environment variable of that name, which naturally does not exist and thus gives back an empty string?

On the commandline, you can use the `--verbose` flag to see how Duplicati has received the values, and that could hint to what goes wrong.

**Comment by ts678** [comment]
[URL encoded authid fails oauth #1736](https://github.com/duplicati/duplicati/issues/1736#issuecomment-1907073990) said:

Not reproducible in current release. Maybe this was fixed. Amazon Cloud Drive is gone. I tested backup with OneDrive authid.
An actual colon is also accepted, in place of the %3A from the export. Please post if there still seems to be a problem with this.
