### ISSUE TITLE
With google drive: Failed to connect: The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by Yoshi8765** [duplicati/duplicati#2292]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** Duplicati - 2.0.1.35_experimental_2016-12-13
**Operating System:** Win 10 Pro
**Backend:** 

### Bug description
Trying to use Google Drive as a destination results in a 400 error even with a proper OAuth generated with no issues. I am pretty sure the connection to Drive is the problem somehow. Note: I am using a google drive through a University institution. I have used this google drive with previous versions of Duplicati.

### Steps to reproduce
- Try to create a new backup with Google drive
- Generate OAuth, pick destination (I picked a folder in the root directory for my Google Drive).
- Click test connection.

**Actual result:** 400 error.
**Expected result:** Good connection

### Screenshots
![](https://a.pomf.cat/nusjgv.png)

**Comment by Yoshi8765** [comment]
I have figured out the problem. I was typing in a google drive path using `\` instead of `/`. Once I started using the forward slash it worked fine.

**Comment by KoalaBear84** [comment]
Great, also got this problem. It would be very nice if there could be a warning for this in the GUI.

**Comment by JiHeR91** [comment]
Helped me 8years later ! TY
