### ISSUE TITLE
Pick "Restore destination" directly from backup jobs

### ISSUE THREAD

**Issue by MrCodeB** [duplicati/duplicati#2293]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.44_canary_2017-01-24
**Operating System:** Windows 7 SP1
**Backend:**

### Bug description
I need to pick a "Backup destination" when i want to restore something. IMHO it would be more user friendly if i could just pick one of the tasks i want to backup from, since they hold all the information i need. Currently i need to know where each task stores the backup.

### Steps to reproduce
- Restore Backup
- Pick "Backup destination"

**Actual result:** I need to pick e.g. a drive where a backup is stored.
**Expected result:** Pick one of the backup tasks which where created in "Home" and take the metadata from there.

### Screenshots
![firefox_2017-01-30_14-13-25](https://cloud.githubusercontent.com/assets/25217143/22424347/8bead462-e6f6-11e6-84d7-f43ca62d6ecc.png)
![firefox_2017-01-30_14-15-55](https://cloud.githubusercontent.com/assets/25217143/22424491/10de5f90-e6f7-11e6-9808-89e82dd688e4.png)

**Comment by agrajaghh** [comment]
I think what you are looking for is already possible:
![restore](https://cloud.githubusercontent.com/assets/5296073/22434409/2fced996-e71c-11e6-8a24-8464606fd9de.PNG)

Or are you talking about something else?

**Comment by MrCodeB** [comment]
Yes, thats what i was talking about.
Didn't see it :-(
IMHO it would be good to implement this into the "Restore" page also. Seems more consistent and intuitive to me.

Von meinem iPhone gesendet

**Comment by kenkendk** [comment]
This could be fixed with #2282, were we discuss having sub-menus.
I guess the "Restore" menu could have a sub menu, like "from existing", "from scratch".

**Comment by kenkendk** [comment]
I think this was fixed with e4d8058
