### ISSUE TITLE
[NOT A BUG] Backend that needs prepending data

### ISSUE THREAD

**Issue by carmebar** [duplicati/duplicati#2299]
_Sorry for opening a bug for a developing question._

I'm trying to add a backend that requires some data prepended to the file when uploading. I've managed to properly upload and download the data but when verifying Duplicati complains that the file size is not correct.

I tracked the problem and found it's the stream wrapper that tracks progress and the download size checks happening after download.

The question is: **Is there a clean way to instruct Duplicati that the file has a bigger size in the backend than in the local db/filesystem?**

I think I could just prepend the data to the file regardless of the backend but that won't be very clean.

Thank you for your work.

**Comment by kenkendk** [comment]
Duplicati has checks to ensure that things locally are the same as remotely.
 One of these checks is to download the remote file and verify that it has the same hash as when it was uploaded.

These checks are there to ensure that you do not get at surprise failure when you attempt to restore.

For that reason, I do not recommend disabling or bypassing the checks, and for that reason there is no clean way to do so.

If you simply want to insert extra data into the backup, the option `--control-files` can be used to inject files into the `dlist` files before compression.

If you need to prepend a fixed amount of data, you can "mask" this by reporting the file sizes minus the prepended data. I assume you will need to add/remove the data in the backend too, so this makes the backend appear consistent.

If the size is not fixed (or computeable), you can return the filesize as `-1` which indicates "unknown". This will disable a few checks, so I do not recommend it if you can avoid it.

A completely different approach could be to write a custom encryption (or compression) module that simply uses the existing module, but writes the header to the file.
