### ISSUE TITLE
Restore from SMB share: "Testing connection" forever

### ISSUE THREAD

**Issue by KommX** [duplicati/duplicati#2301]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System:** Windows 10
**Backend:**

### Bug description
I created a backup and moved the backup "by hand" to a remote location which is accessible via SMB through VPN.
Now I wanted to test restore form there, but "testing connection" hangs forever.

### Steps to reproduce
- Connect to the VPN
- check if SMB share is available through Windows Explorer
- In Duplicati: "Restore Backup"
- Select the SMB share folder
- Hit "Test connection"

**Actual result:** The "testing" dialog is shown without error or success message
**Expected result:** Failure or success message

**Comment by kenkendk** [comment]
The "Test" operation is simply doing a "directory list" of the folder, so there is no reason it should hang.

Are you running Duplicati and Windows Explorer as the same user? Are you using a mapped drive?

**Comment by KommX** [comment]
> Are you running Duplicati and Windows Explorer as the same user?

Yes, I am.

>  Are you using a mapped drive?

Yes, I am. The resource is available via \\IP\folder and I mapped this one to a single-letter drive.

**Comment by KommX** [comment]
I will be gone for a week. So, please be patient if I don't answer for some days.

**Comment by KommX** [comment]
This issue is still present in 2.0.1.49_experimental_2017-02-23.

Can I provide any log files to locate the problem?

**Comment by ts678** [comment]
> Can I provide any log files to locate the problem?

I'm not sure why (possibly different code path to reach backend), but logging works worse on `Test connection`.
Ordinarily, operations with the destination make log output visible in About --> Show log --> Live --Information.
Job menu `Verify files` looks like below. Start is at the bottom, with `List`. Maybe yours can''t be Completed?
Looking lower could be attempted using Sysinternals Process Monitor to see what activity there is on your folder.
```
Jan 31, 2024 10:18 AM: The operation Test has completed
Jan 31, 2024 10:17 AM: Successfully verified 3 remote files
Jan 31, 2024 10:17 AM: Backend event: Get - Completed: duplicati-b7b757ea358f64d4b8812bfbef6803bda.dblock.zip (49.96 MB)
Jan 31, 2024 10:15 AM: Backend event: Get - Started: duplicati-b7b757ea358f64d4b8812bfbef6803bda.dblock.zip (49.96 MB)
Jan 31, 2024 10:15 AM: Backend event: Get - Completed: duplicati-i5e7e34b1b487442c9aa4e524a48eaa91.dindex.zip (18.66 KB)
Jan 31, 2024 10:15 AM: Backend event: Get - Started: duplicati-i5e7e34b1b487442c9aa4e524a48eaa91.dindex.zip (18.66 KB)
Jan 31, 2024 10:15 AM: Backend event: Get - Completed: duplicati-20240117T165155Z.dlist.zip (721 bytes)
Jan 31, 2024 10:15 AM: Backend event: Get - Started: duplicati-20240117T165155Z.dlist.zip (721 bytes)
Jan 31, 2024 10:15 AM: Backend event: List - Completed: (20 bytes)
Jan 31, 2024 10:15 AM: Backend event: List - Started: ()
Jan 31, 2024 10:15 AM: The operation Test has started
```

Duplicati does neither SMB (that's Windows) nor VPN, so there are lots of places that things could be going wrong.

Did this get resolved,? Is it still of interest and happening? If nothing more to say, this issue will automatically close.

**Comment by KommX** [comment]
I opened this bug nearly 7 years ago. I think, I gave up on that approach back then.
