### ISSUE TITLE
Build failure: 'NGettext' already has a dependency defined for 'Microsoft.CSharp'.

### ISSUE THREAD

**Issue by robbat2** [duplicati/duplicati#2307]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.44-2.0.1.44_canary_2017-01-24
**Operating System:** Gentoo Linux
**Backend:**

### Bug description
Compile failure.

### Steps to reproduce
- Install Mono dev environment
- Grab tarball
- run `make build` in Installer/Makefile/

**Actual result:** 
nuget restore fails:
 ```
$ make build 
nuget restore "../.././Duplicati.sln"
Installing 'AWSSDK.S3 3.3.1.1'.
Installing 'AlphaVSS 1.2.4000.3'.
Installing 'Microsoft.Azure.KeyVault.Core 1.0.0'.
Installing 'Microsoft.Data.OData 5.8.1'.
Installing 'Microsoft.WindowsAzure.ConfigurationManager 3.2.3'.
Installing 'Newtonsoft.Json 9.0.1'.
Installing 'SharpAESCrypt.exe 1.3.2'.
Installing 'agsXMPP 1.1.1.0'.
Installing 'AWSSDK.Core 3.3.4'.
Installing 'NGettext 0.6.2'.
Installing 'CoCoL 1.5.0'.
Installing 'AlphaFS 2.1.2'.
Installing 'MimeKit 1.10.0'.
Installing 'AWSSDK.IdentityManagement 3.3.0.2'.
Installing 'WindowsAzure.Storage 7.2.1'.
Installing 'SSH.NET 2016.0.0'.
Installing 'System.Spatial 5.8.1'.
Installing 'MegaApiClient 1.3.1'.
Installing 'MailKit 1.10.1'.
Installing 'Microsoft.Data.Services.Client 5.8.1'.
Installing 'NUnit 3.5.0'.
Installing 'Microsoft.Data.Edm 5.8.1'.
Installing 'BouncyCastle 1.8.1'.
Successfully installed 'Microsoft.WindowsAzure.ConfigurationManager 3.2.3'.
Successfully installed 'SharpAESCrypt.exe 1.3.2'.
Successfully installed 'Microsoft.Azure.KeyVault.Core 1.0.0'.
Successfully installed 'CoCoL 1.5.0'.
Successfully installed 'agsXMPP 1.1.1.0'.
Successfully installed 'Newtonsoft.Json 9.0.1'.
Successfully installed 'AWSSDK.S3 3.3.1.1'.
Successfully installed 'AlphaVSS 1.2.4000.3'.
Successfully installed 'System.Spatial 5.8.1'.
Successfully installed 'MegaApiClient 1.3.1'.
Successfully installed 'Microsoft.Data.OData 5.8.1'.
Successfully installed 'AWSSDK.Core 3.3.4'.
Successfully installed 'Microsoft.Data.Edm 5.8.1'.
Successfully installed 'NUnit 3.5.0'.
Successfully installed 'SSH.NET 2016.0.0'.
Successfully installed 'BouncyCastle 1.8.1'.
Successfully installed 'Microsoft.Data.Services.Client 5.8.1'.
Successfully installed 'AlphaFS 2.1.2'.
Successfully installed 'MailKit 1.10.1'.
Successfully installed 'AWSSDK.IdentityManagement 3.3.0.2'.
Successfully installed 'MimeKit 1.10.0'.
Successfully installed 'WindowsAzure.Storage 7.2.1'.
'NGettext' already has a dependency defined for 'Microsoft.CSharp'.
```

Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Should build.

### debug log
This the latest version of NuGet 2.8.7 from https://github.com/mrward/nuget/releases

**Comment by markeclaudio** [comment]
I've the same problem

**Comment by robbat2** [comment]
As a followup, it seems that the mrward nuget is greatly lagging behind the main upstream NuGet

**Comment by kenkendk** [comment]
What about using the official NuGet binaries?

https://dist.nuget.org/index.html

They work on Linux too, despite the names.

**Comment by troxor** [comment]
Same issue here as @robbat2 , so I used the following:

`curl https://dist.nuget.org/win-x86-commandline/v4.1.0/nuget.exe -L -o /somewhere/in/path/nuget ; chmod +x /that/somewhere/nuget`

and followed the Mono guide to make it "natively" executable: http://www.mono-project.com/archived/guiderunning_mono_applications/#registering-exe-as-non-native-binaries-linux-only

**Comment by ts678** [comment]
> Operating System: Gentoo Linux

Are all of you on Gentoo, doing a build from source? I've never done that, but I worry about `mono` tools since the sale to MS.
Duplicati is still using `.NET Framework` and `mono`, although a move to new `.NET` is underway (but slow due to lack of help).

Basically, is this issue still relevant in today's build environment? What's an alternative for Gentoo? Can it run a Docker image?
