### ISSUE TITLE
Error:  Found X files that are missing from the remote storage, please run repair

### ISSUE THREAD

**Issue by fink42** [duplicati/duplicati#2308]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version: 2.0.1.46**
**Operating System: Windows 10 64-bit build 4394**
**Backend: Local NAS**

### Bug description
Running the backup yields the following error messages: 
`Fatal error
Duplicati.Library.Interface.UserInformationException: Found 9 files that are missing from the remote storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)`
and
`Found 9 files that are missing from the remote storage, please run repair`

Running the repair from the GUI doesn't work and in the log it says (for 9 different files):
`Error: Failed to perform cleanup for missing file: duplicati-b65a6aa0822804d628e4065573e202ce1.dblock.zip.aes, message: Repair not possible, missing 511 blocks.
If you want to continue working with the database, you can use the "list-broken-files" and "purge-broken-files" commands to purge the missing data from the database and the remote storage.
Duplicati.Library.Interface.UserInformationException: Repair not possible, missing 511 blocks.
If you want to continue working with the database, you can use the "list-broken-files" and "purge-broken-files" commands to purge the missing data from the database and the remote storage.
   at Duplicati.Library.Main.Operation.RepairHandler.RunRepairRemote()`

I then run the list-broken-files and purge-broken-files from the CLI, both of which give me:
`No broken filesets found in database, checking for missing remote files
  Listing remote folder ...
Marked 9 remote files for deletion
No broken filesets found`

But the backup still cant be completed and just provides the same error messages as before...
I don't quite get how to delete those 9 remote files that are marked for deletion.

**Comment by BlackEdder0815** [comment]
Hi,
I had the same issue.
After the purge, try again a verify on the console. Maybe the will solve your issue.

**Comment by BlackEdder0815** [comment]
See #2251 for details

**Comment by fink42** [comment]
Verifying after purge-broken-files just provides me with:
`Missing file: duplicati-bc24a1bce6cd0465f875f726e651644ed.dblock.zip.aes
Missing file: duplicati-b6d48dfd104df49dcafa43b31e253d50c.dblock.zip.aes
Missing file: duplicati-bf8118aca520f4a76903b116dd01b7444.dblock.zip.aes
Missing file: duplicati-bdeb9e73095d64574b49a86b676e48951.dblock.zip.aes
Missing file: duplicati-b37ad0e3b4d504456b19caa316735e524.dblock.zip.aes
Missing file: duplicati-b446d974f177d4733a4d46211be7ec1b0.dblock.zip.aes
Missing file: duplicati-b65a6aa0822804d628e4065573e202ce1.dblock.zip.aes
Missing file: duplicati-b3209c2c6ff404ee38d0c8a7b461ef644.dblock.zip.aes
Missing file: duplicati-b4975416318bf4d468468ef846f6f9317.dblock.zip.aes
Found 9 files that are missing from the remote storage, please run repair`

The backup still fails with the same message as before...

**Comment by saviodsouza** [comment]
Same case with me

Deleting database and rebuilding also doesn't work.

Finally deleted the files at back end and rerun from scratch again.

**Comment by fink42** [comment]
Unfortunately I gave up on the problem and ended up deleting the backup from the server (moved all the files into a folder so I still have the backup, should I need something from within the last 3 months, as I run the backup with 3 months backward view).

**Comment by BlackEdder0815** [comment]
weird.
With exact following the steps in #2251, I got all my backups repaired.
Not: the `verify`, `repair`, `list-broken-files`, `purge-broken-files`, `verify` was done with help of the console (duplicati-cli).
Also note: When using the cli, always give the path for the db-file, do not get stuck into other issues, because the cli can not find your db-file. So, my tip: always use `--dbpath` with each duplicati-cli-command. The exact path of the db-file can be found in the frontend below "manage database"

**Comment by fink42** [comment]
I actually didn't specify the db-path when running commands from the cli.
If the problem comes up again I will try that, thanks.
