### ISSUE TITLE
ZFS support

### ISSUE THREAD

**Issue by fubarbaz** [duplicati/duplicati#2313]
I would like to use Duplicat to duplicate a list of ZFS datasets from one machine to another ZFS machine via some backup schedule in an incremental fashsion.  Perhaps you consider this to be out of scope for this project, but I would like to hear that too then.

**Comment by maciekb** [comment]
Hi,

Why can't you use ZFS Send/Receive? This feature looks like exactly what You need.

Best regards,
Maciek

**Comment by kenkendk** [comment]
I think this sounds as the "mirror" feature, where there is no compression?
If so, then it is out-of-scope:
https://github.com/duplicati/duplicati/wiki/FAQ

**Comment by kenkendk** [comment]
Closing for lack of feedback
