### ISSUE TITLE
PM not being displayed in Schedule in latest version of Edge Browser

### ISSUE THREAD

**Issue by itdude** [duplicati/duplicati#2316]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.45
**Operating System: 10.0.14393
**Backend: ZDFS file store

### Bug description
Describe here the issue that you are experiencing.

When using the edge browser (38.14393.0.0) I want to modify the Next Time in the schedule. The Hour is shown as a 12 hour clock and I can only select AM. PM does not appear, even when I try to scroll up or down.
(My region format is : German (Switzerland))

When use other browsers, I see the following behavior:
•Internet Explorer 11.447.14393.0 -> I can simply type in the time directly
•Firefox 51.0.1 -> I can simply type in the time directly
•Google Chrome 56.0.2924.87 -> the hours, minutes and merideam are navigated with up and down arrows. AM and PM can both be selected

In the previous version of Edge (20.10240.17146.0), I was able to simply type in time.

However, when I change my Region to English (US) I am able to see the AM and PM in the latest version of Edge.

So it seems that there is an issue with the region handling.

### Steps to reproduce
- Set region to German Switzerland
- Launch Duplicati in Edge Browser (38.14393.0.0, windows ver 10.0.14393)
- Edit existing configuration
- Go to the schedule tab
- Click on the time

**Actual result: See a 12 hour time and only PM selectable
**Expected result:** I would expect one of the following:
                             - able to put in the time myself,
                             - Able to see the PM as well
                             - Have a 24 hour clock to select the time
### Screenshots
![nopmvisible](https://cloud.githubusercontent.com/assets/6398084/22877197/89929d60-f1d4-11e6-88f1-e17161925ff9.jpg)

**Comment by idotj** [comment]
Support for Microsoft Edge Legacy ended on March 9th 2021.
https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge

Impossible to reproduce with the new Edge based on Chromium.

**Comment by ts678** [comment]
Not reproducible here either, on current Edge version:

![image](https://github.com/duplicati/duplicati/assets/40771998/2e2700ab-26bd-485a-8554-5fa45671ab70)

If nobody can reproduce it, I guess this will get closed.
