### ISSUE TITLE
Feature Request: Optional adding a describition to backup

### ISSUE THREAD

**Issue by TKaluza** [duplicati/duplicati#2319]
## Feature Request
Adding a option for cataloguize of (individuall) backups to help identifing backups easier and to improve the overall usability, especially when making a extraordinary backup in relation to the backup schedule.

## Gui suggestion for implementing
![webgui_improvement_example2](https://cloud.githubusercontent.com/assets/17787801/22920467/78f73dd2-f295-11e6-8722-0ab6a162abb2.png)
(May I help with improving the gui? ) 

### How to store the options? 
- one not ideal but maybe very easy possibility would be to append the description to the Filename of the save file. Therefore it would be visible without using the gui. But there would be perhaps some security issues because of the visability. Personally I don't see this as a bad thing. 
- Easy readabile data table, txt, csv where the Information can be seen. 
- Somewhere within a new ziped file, secure.
- Within the database of duplicati

### Limitations and type of description

- UTF Text
- Keywords/Tags? (Would not need this but could become handy in some case)

**Comment by saviodsouza** [comment]
Another feature

Add comments manually to backup versions.

**Comment by warwickmm** [comment]
Closing this in favor of #2153.
