### ISSUE TITLE
Unsupported change of passphrase error

### ISSUE THREAD

**Issue by masaru-ryumae** [duplicati/duplicati#2322]
I have:
- [X ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.47_canary_2017-02-14 and 2.0.1.45_experimental_2017-02-03
**Operating System:** Mac
**Backend:**

### Bug description
Unsupported change of passphrase error

### Steps to reproduce
- If I create a new policy on the GUI, and run the exported command in a terminal, it succeeds. If I then go to the web GUI to run the same policy, I get "Unsupported change of passphrase" error. 

- On the other hand, if I create a new policy on the GUI and run it in the GUI, it succeeds. If I then go to a terminal to run the same policy, then I get "Unsupported change of passphrase" error.

**Actual result:** Unsupported change of passphrase error happens.
**Expected result:** I would have expected I "should" be able to run the same policy either from the GUI or terminal.

**Comment by kenkendk** [comment]
It should certainly work the same from GUI and CLI. 
Are there any special characters in the passphrase? Something else than A-Z and numbers?

**Comment by masaru-ryumae** [comment]
In fact, the passprhase did have special characters like ' or !. I
initially suspected it, and removed ' and retried with the same result.

The strong passphrase was generated from the GUI, though, including some
special characters. Is it correct that I should only be using A-Z and
numbers without any special characters?

I will try without any special characters and report out.

Thank you for responding!

**Comment by kenkendk** [comment]
You can use any character (it is UTF-8 encoded), but sometimes the commandline encodes special characters differently, or needs escape symbols.

Using only A-Z narrows down the possible errors that can cause the problem. Once we know what causes the problem, it is easier to fix.

**Comment by masaru-ryumae** [comment]
On Mac, it appears some special characters do cause problems running under command line. Command arguments are enclosed in " and if a special character is part of the storage string or in passphrase, it fails. Without special characters, I confirmed I could run from both command line and GUI. 

This may be just a note to add for Mac usage. 

Thank you for your help. I consider this to be closed.
