### ISSUE TITLE
Scheduling a Backup does not store "Allowed Days"

### ISSUE THREAD

**Issue by basrieter** [duplicati/duplicati#2324]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.45_experimental_2017-02-03
**Operating System:** Windows 10 x64
**Backend:** WebDAV

### Bug description
Scheduling a Backup does not store "Allowed Days".

### Steps to reproduce
- Schedule a backup for *Run again every 1 weeks*
- Set *Allowed Days* to be Monday
- Save the profile
- Open the profile
- At the Schedule step, no *Allowed Days* are shown
- In the *Next scheduled run* an incorrect date/time is shown

**Actual result:** no *Allowed Days* are shown
**Expected result:** The allowed days that were configured are shown and the *next run at* should have the correct date.

### Screenshots
n.a.

### debug log
A backup is running, so I can't filter out the exact lines.

I did get a Javascript console error while selecting days:
```
16:43:06.139 Error: lst is undefined
$scope.toggleArraySelection@http://192.168.2.90:8200/ngax/scripts/controllers/EditBackupController.js:154:13
anonymous/fn@http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js line 212 > Function:2:591
Kc[c]</<.compile/</</f@http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js:252:74
jf/this.$get</n.prototype.$eval@http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js:134:489
jf/this.$get</n.prototype.$apply@http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js:135:212
Kc[c]</<.compile/</<@http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js:252:124
n.event.dispatch@http://192.168.2.90:8200/ngax/scripts/libs/jquery.min.js:3:6414
n.event.add/r.handle@http://192.168.2.90:8200/ngax/scripts/libs/jquery.min.js:3:3224
 1 angular.min.js:108:318
	e/< http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js:108:318
	Ze/this.$get</< http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js:80:416
	jf/this.$get</n.prototype.$apply http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js:135:235
	Kc[c]</<.compile/</< http://192.168.2.90:8200/ngax/scripts/angular/angular.min.js:252:124
	n.event.dispatch http://192.168.2.90:8200/ngax/scripts/libs/jquery.min.js:3:6414
	n.event.add/r.handle http://192.168.2.90:8200/ngax/scripts/libs/jquery.min.js:3:3224

```

**Comment by 5YHgB** [comment]
I have this problem too, cannot save allowed days.
