### ISSUE TITLE
Special Characters in source path cause backup failure

### ISSUE THREAD

**Issue by rjbarber** [duplicati/duplicati#2325]
I have:
- [x] searched open and closed issues for duplicates
Not, I cant figure out how to do a search in the issue list. Sorry. 

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.45_experimental_2017-02-03
**Operating System:** WIn7 Ultimate 64 Updated
**Backend:** ACD

### Bug description
Describe here the issue that you are experiencing.
I use special characters in my file names: ~Virtual Filing Cabinet. Duplicati errors out on this. 
"Invalid path: "D:\Users\Roland\Documents\C:\Users\Roland.RJBATHOMEPaperPort Inbox\" (The given path's format is not supported.)"
It appears Duplicati is droping the ~ character and the preceding \ character.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
-Create backup with a folder name that has the ~ character.
-Run the backup.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Backup fails with error
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Backup should have completed with no errors.
![duplicati error screen shot](https://cloud.githubusercontent.com/assets/10442659/23107456/90edba1c-f6b2-11e6-9212-062015e5b350.jpg)

### Screenshots

Attached.
### debug log

Feb 19, 2017 2:46 PM: Failed while executing "Backup" with id: 1
Feb 19, 2017 2:42 PM: Failed while executing "Backup" with id: 1
Feb 19, 2017 2:41 PM: Failed while executing "Backup" with id: 1
Feb 19, 2017 2:41 PM: Failed while executing "Backup" with id: 1
Feb 19, 2017 2:39 PM: Request for http://127.0.0.1:8200/api/v1/backup/1/log?pagesize=100 gave error
Feb 19, 2017 2:39 PM: Reporting error gave error
Feb 19, 2017 2:39 PM: Failed while executing "Backup" with id: 1

**Comment by kenkendk** [comment]
This happens because Duplicati expands `~` to the users home path.
Not sure how we should fix it.

One idea could be to check if the file/folder with the tilde actually exists before expanding.

**Comment by TekkiWuff** [comment]
Could this get closed, cause tilde expansion isn't supported anymore since PR #2836?

**Comment by rjbarber** [comment]
If it’s not supported then sounds like there is no reason to keep it open. Who closes it, me or you?

 

Thank you,

RJ

**Comment by TekkiWuff** [comment]
> Who closes it, me or you?
That ... is a good question. I can't close it. I just happened to stumble upon several issues discussing the problem with replacing the tilde character and thought i'll leave a comment that these might be solved.

**Comment by rjbarber** [comment]
Closing this issue based on the above comments.
