### ISSUE TITLE
Can't repair database, bug report 441 Mb, anyone can help?

### ISSUE THREAD

**Issue by Hawaga** [duplicati/duplicati#2326]
Hello, I have this bug, Backup database can't be repaired. Duplicati asks to send bug report to developpers, but it is 441 mb. Anyone can help?

I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.46
**Operating System:**ADM 2.6.6.RCF2 (Asustor AS-608T Nas)
**Backend:**Amazon Cloud Drive

### Bug description
Can't rebuild database

### Steps to reproduce
- Start backup 
- Backup fail with "repair database" message
- Repair fails, says to send bug report to developpers

**Actual result:** message says to send bug report to developpers
**Expected result:** Database rebuild successful

### Screenshots

![capturebug](https://cloud.githubusercontent.com/assets/23527788/23136455/1570df90-f79d-11e6-869d-5b017287e530.JPG)

### debug log

Bug report (log database) is 441mb thus can't be attached here. Wetransfer link : https://we.tl/uLom9g6dyK

 Here is my [system-info.txt](https://github.com/duplicati/duplicati/files/788176/system-info.txt)

**Comment by kenkendk** [comment]
Sorry, I was a bit slow, the WeTransfer link has expired.
Can you create it again?

**Comment by Hawaga** [comment]
Sure, here you go: https://we.tl/M4abA0cSH4

**Comment by ts678** [comment]
I don't know if the above link was used in 2017, but it's failing now. Is recreate problem still happening on the current release?
Given the long passage of time, and various fixes introduced, this seems like it should be closed until when/if it happens again.
Any counter-proposal?
