### ISSUE TITLE
Duplicati does not show scheduled details using a different user

### ISSUE THREAD

**Issue by Pingperfect** [duplicati/duplicati#2328]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

2.0.1.45_experimental_2017-02-03
Windows Server 2012R2
**Backend:**

### Bug description
When the backup is configured by UserA User B cannot see any details of the scheduled backup despite having the same permissions as User A and running the web gui.

### Steps to reproduce
- set up a backup as one user
- log on as another user and open web interface
- no scheduled tasks will be found.

When User B logs on no scheduled tasks are found nor can he/she see running details
When User B logs on he/she should see the same details as User A

### Screenshots
User A - https://www.dropbox.com/s/k64m6jf11brlv1a/duplicati.jpg?dl=0
User B - https://www.dropbox.com/s/xb7k0d58ty0uz1p/Screenshot%202017-02-21%2010.14.09.png?dl=0

**Comment by kees-z** [comment]
This is related to / discussed in issue #2222.
Duplicati stores backup configs in the user's %appdata% folder, which gives each user a separate Duplicati environment.
Quick fix is to start Duplicati with the --portable-mode switch. This will store all Duplicati program- and backup settings in a subfolder of the Duplicati program files.
Note that using this command line option, User1 potentionally can restore personal files of User2. This could be a security issue is multiple people are using a single computer.

**Comment by Pingperfect** [comment]
Testing this on a new server, installed the program and edited the desktop shortcut to show the following
"C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe" --portable-mode

UserA see's backups fine
UserB still does not.

Am I missing something?

**Comment by kees-z** [comment]
I don't know if Duplicati.GUI.TrayIcon.exe supports the --portable-mode command line option.
Try `Duplicati.Server.exe --portable-mode` or `Duplicati.WindowsService.exe install --portable-mode` to install Duplicati as a Windows service.
Running Duplicati as a Windows service has some advantages: it is already active before any user logs on and Duplicati has administrative privileges, which eliminates possible issues when creating a volume shadow copy.

**Comment by Pingperfect** [comment]
Ended up with the following
Duplicati.WindowsService.exe install --portable-mode --webservice-interface=loopback --log-retention=3M which sorted the issue out

**Comment by kenkendk** [comment]
I think the issue was that the trayicon just connected to the server/service which was not using `--portable-mode`. I am closing the issue, as you have a workaround, and the real fix lies with #1739.
