### ISSUE TITLE
Duplicati crashes on Windows 2008 server 32bit non-R2

### ISSUE THREAD

**Issue by Corbett81** [duplicati/duplicati#2337]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.49
**Operating System:** Windows Server 2008 32bit Non-R2
**Backend:**

### Bug description
Application crash

The error I receive is : Duplicati.GUI.TrayIcon has stopped working.

I receive this error on two completely separate servers at separate offices.

### Steps to reproduce
On Startup

**Actual result:** 
I have installed Duplicati on two servers.  Both running Windows 2008 server (Non-R2 version) 32bit and the application installs properly but it errors out when it loads up on startup. It will not allow me to open the program whatsoever

The error I receive is : Duplicati.GUI.TrayIcon has stopped working.

**Expected result:** 
Program Opens

### Screenshots
None

### debug log
None

**Comment by kenkendk** [comment]
Try to look in the event log for more details on what has caused the crash.
Often the problem is something with permissions/location of `%APPDATA%`.

**Comment by Corbett81** [comment]
I have checked %appdata% and it is in standard location under administrator folder.  I do have rights to the Duplicati folder inside that.  Here is the error from event log
Application: Duplicati.GUI.TrayIcon.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.NullReferenceException Stack: at Duplicati.GUI.TrayIcon.Windows.WinFormsRunner.UpdateUIState(System.Action) at Duplicati.GUI.TrayIcon.TrayIconBase.InvokeExit() at Duplicati.GUI.TrayIcon.Program+<RealMain>c__AnonStorey0.<>m__1() at Duplicati.GUI.TrayIcon.HostedInstanceKeeper+<HostedInstanceKeeper>c__AnonStorey0.<>m__0(System.Object) at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by Corbett81** [comment]
And here is the error from event log on different server.
Application: Duplicati.GUI.TrayIcon.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.NullReferenceException Stack: at Duplicati.GUI.TrayIcon.Windows.WinFormsRunner.UpdateUIState(System.Action) at Duplicati.GUI.TrayIcon.TrayIconBase.InvokeExit() at Duplicati.GUI.TrayIcon.Program+<RealMain>c__AnonStorey0.<>m__1() at Duplicati.GUI.TrayIcon.HostedInstanceKeeper+<HostedInstanceKeeper>c__AnonStorey0.<>m__0(System.Object) at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by kenkendk** [comment]
The error seems to happen because the tray-icon is asked to close itself before it has been displayed. The reason for this seems to be that the server fails to start, and then immediately asks the tray icon to close.

Can you try starting "Duplicati.Server.exe" directly and see if you get another error message?

**Comment by Corbett81** [comment]
Thanks.  I opened command line on both machines and manually launched Duplicati.Server.exe and let it run in the backgroud.  Then when I try to open the GUI icon it does nothing at all.  I can however still visit the localhost web address and use the backup properly, just no gui icon.  Please advise.  Thanks!

**Comment by Corbett81** [comment]
Can we try to figure out the gui icon issue?  I do not get any error logs when i manually run duplicati.server.exe but the icon just does not open.

**Comment by kenkendk** [comment]
If the server is running, can you then start the trayicon with:

```
Duplicati.GUI.TrayIcon.exe --no-hosted-server
```

That should make the tray icon connect to the server, instead of hosting the server inside the tray icon.

**Comment by Corbett81** [comment]
ok I finally tried that and it still crashed.  Here is the error log
Application: Duplicati.GUI.TrayIcon.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Net.WebException Stack: at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(MethodInfo method, String[] args) at Duplicati.Library.AutoUpdater.UpdaterManager.<RunFromMostRecent>c__AnonStorey7.<>m__0() at Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater(AutoUpdateStrategy defaultstrategy, Action wrappedFunction) at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(MethodInfo method, String[] cmdargs, AutoUpdateStrategy defaultstrategy) at Duplicati.GUI.TrayIcon.Program.Main(String[] args) at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args) at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args) at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[]) at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy) at Duplicati.GUI.TrayIcon.Program.Main(System.String[])

**Comment by KiLLeRRaT** [comment]
I too run into this when running 

`Duplicati.GUI.TrayIcon.exe --no-hosted-server`

My service is definitely running, as I can manually visit the url in a browser.

I tried running it as administrator, but still crashes.

Here is my event log stack trace:

```
Application: Duplicati.GUI.TrayIcon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

Exception Info: System.Net.WebException
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(MethodInfo method, String[] args)
   at Duplicati.Library.AutoUpdater.UpdaterManager.<RunFromMostRecent>c__AnonStorey7.<>m__0()
   at Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater(AutoUpdateStrategy defaultstrategy, Action wrappedFunction)
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(MethodInfo method, String[] cmdargs, AutoUpdateStrategy defaultstrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(System.String[])
```

**Comment by kenkendk** [comment]
@KiLLeRRaT Does the service go down when you visit it? What browser do you use?

**Comment by KiLLeRRaT** [comment]
Hey @kenkendk,
The service stays up, and everything works in the browser.  The tracy icon app (Duplicati.GUI.TrayIcon.exe) is the only thing that crashes, but because it's not the 'real' web host, it doesn't take anything down with it.

I'm using Chrome 58.

**Comment by ts678** [comment]
> Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent

This was changed to not use the implementation in this issue, which possibly explains why reports are no longer coming.

[2.0.2.11_canary_2017-10-20](https://github.com/duplicati/duplicati/releases/tag/v2.0.2.11-2.0.2.11_canary_2017-10-20)

> Changed the way the auto-updater works. It now spawns a new version of the executable instead of attempting to run it in an AppDomain
It is possible to revert to the old version by setting the environment variable AUTOUPDATER_USE_APPDOMAIN=true

so in theory the theory could be tested, but Windows Server 2008 is out of support too, and interest might not be there.
Regardless of whether or not theory is right, other things have changed as well. With no more action, this issue will close.
