### ISSUE TITLE
The supplied option --region is not supported and will be ignored,

### ISSUE THREAD

**Issue by damian123** [duplicati/duplicati#2338]
I am gettng warnigs when I backup to S3.
    **The supplied option --region is not supported and will be ignored,
    The supplied option --bucket is not supported and will be ignored**

You are currently running Duplicati - 2.0.1.49_experimental_2017-02-23

From the log file I have:
26 Feb 2017 15:45: Result
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 2
ExaminedFiles: 1530471
OpenedFiles: 457
AddedFiles: 455
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 2869562802
SizeOfExaminedFiles: 595749432274
SizeOfOpenedFiles: 2869562866
NotProcessedFiles: 0
AddedFolders: 14
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    CompactResults: null
    ParsedResult: Success
    EndTime: 2/26/2017 2:40:41 PM
    BeginTime: 2/26/2017 2:39:30 PM
    Duration: 00:01:11.4213490
    BackendStatistics:
        RemoteCalls: 116
        BytesUploaded: 2988815235
        BytesDownloaded: 186646887
        FilesUploaded: 111
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 12881
        KnownFileSize: 339736737837
        LastBackupDate: 2/26/2017 2:00:00 PM
        BackupListCount: 29
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: -1
        ParsedResult: Success
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170226T130000Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i077becd0f4fa4b939e9549f4b1852757.dindex.zip.aes
        Value: [],
        Key: duplicati-b38d742fe4fc945af908e08683670fd94.dblock.zip.aes
        Value: []
    ]
    ParsedResult: Success
    EndTime: 2/26/2017 2:45:52 PM
    BeginTime: 2/26/2017 2:45:07 PM
    Duration: 00:00:44.6438367
ParsedResult: Warning
EndTime: 2/26/2017 2:45:52 PM
BeginTime: 2/26/2017 1:00:00 PM
Duration: 01:45:52.5731983
Messages: [
    No remote filesets were deleted
]
Warnings: [
    **The supplied option --region is not supported and will be ignored,
    The supplied option --bucket is not supported and will be ignored**
]

**Comment by kenkendk** [comment]
The region option is called `--s3-location-constraint`.
The bucket is encoded in the url, so it is `s3://bucket/folder`.

Hope that fixes things, otherwise feel free to re-open.
