### ISSUE TITLE
new question about --keep-versions and --version

### ISSUE THREAD

**Issue by vlepetit** [duplicati/duplicati#2339]
I have:
- [x] searched open and closed issues for duplicates
especially https://github.com/duplicati/duplicati/issues/1568
----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.35_experimental_2016-12-13
**Operating System:** ubuntu 16.04 LTS
**Backend:**

### Bug description
I need to keep always 3 versions of each files that i backup. enven if i delete it and make more that 3 new backup.
so for my test i put 2 files in a folder. setup duplicati to backup this folder.
file1.txt never change
file2.txt always change between each backup
after the 3 backup i delete file1.txt from source folder and make 3 news backup session.

so
if i use --keep-versions=3
i have acces to only 3 last backup set of all folder and not to 3 last versions to each file.
file1.txt is delete from backup  after 3 news backup session and i can't restore it
in this case i can restore the last 3 versions of file2.txt

if i use --version=3
in this case i can see all backup set and not only the 3 last.
But file1.txt  does not appear anymore from any backup set after 3 news backup session and i can't restore it
in this case i can restore the last 3 versions of file2.txt

Could you help me ? or explain to me ?
I hope to found an option to always keep the 3 or n last versions of a file even if i delete it to mix file security and space save...

regards,
vlepetit

**Comment by kenkendk** [comment]
There is no option to always keep 3 versions of a file. There are currently only two options: 

  - `--keep-versions=N`, which keeps the last `N` backup filesets
  - `--keep-time=X`, which keeps backups newer than `X`, where `X` could be `3M` for 3 months

There are suggestions to make a new strategy in #2084, but nothing that would keep track of individual file versions.
As Duplicati stores "snapshots" of the disk contents, storing individual versions would lead to some strange "keep-the-old-version-snapshot" files.

**Comment by vlepetit** [comment]
Thanks a  lot for answer. #2084 is most interesting. I hope That You can implement it. 

Vlepetit
