### ISSUE TITLE
Can see mounted folders on OMV

### ISSUE THREAD

**Issue by ETNY-Y** [duplicati/duplicati#2340]
Hello, 
It is certainly newbee issue but i cannot see mounted data folders that i want to save. I can only see system folders.
Can you help me please?
Yannick

**Comment by kenkendk** [comment]
You can add paths manually if they do not show up automatically.
Just type in the path and click the "Add" button.

**Comment by ETNY-Y** [comment]
Thank for you answer. I Know but when i wrote "/Videos/" it says it does not exist.

**Comment by azraelomega** [comment]
If this is in WindowsI get around this by using a drive mapping

**Comment by ETNY-Y** [comment]
Can you tell me wich system account is used by duplicati for the permission?

**Comment by kenkendk** [comment]
The account depends on how you run Duplicati.
If you run from the TrayIcon without a service, then your normal user account is used (or whatever account you used to start it). If you are using a service, then it would normally be the "SYSTEM" user, which cannot see the mapped drives.

**Comment by ETNY-Y** [comment]
Ok, I use it as a pluggin on OpenMediaVault, that means it is a service?
