### ISSUE TITLE
Unable to filter files that contain a literal tilde character?

### ISSUE THREAD

**Issue by lightvector** [duplicati/duplicati#2342]
I have:
- [x] searched open and closed issues for duplicates

Duplicati Version: 2.0.1.49_experimental_2017-02-23
Operating System: Windows 7

### Bug description
I typically get warnings during backup like:
Failed to process path: C:\Foo\\\~$Bar.xlsx => The process cannot access the file 'C:\Foo\\\~$Bar.xlsx' because it is being used by another process
because I have a file open in Microsoft Excel in the directory being backed up. I would like to have Duplicati ignore these files rather than noisily throw a warning on every single backup, since I expect to have a running instance of Excel on one or more files most or all of the time.

However, I can't find a way to do this cleanly. This file does not appear to be considered as a temporary or system file, so configuring the backup in "3 - Source Data" to exclude system or temporary files does not work. The file is hidden, but I would like to exclude only these particular files rather than excluding all hidden files. And I haven't found a way to get a custom filter expression, such as "\~$" or "\\\~\$" or "^\~\$" or "[^\~\$]" or "[^\\\~\$]" to work, because in all cases, I think Duplicati is replacing the tilde with the home directory, like "C:\\Users\\username" prior to evaluating the expression.

### Steps to reproduce
- Set up Duplicati to backup a vanilla directory with no excludes or filters.
- In Microsoft Excel, create a new "foo.xlsx" or similar file and save it in that directory, and verify via a normal file explorer that when Excel has that file open, there is also a file named "~$foo.xlsx" there as well and that this file is locked by Excel.
- Attempt to run Duplicati to backup the directory. It should complete and report a warning like the one above.
- Add a filter like "Exclude files whose name contains" with a value of "\~$".
- Attempt to run Duplicati again to backup the directory.

**Actual result:** Duplicati complains about a failure to parse the filter string ".*\\C:\\\\Users\\\\username\\$.*[^\\]". And if such as during a scheduled run it proceeds anyways despite the error, it continues to attempt to backup "\~$foo.xlsx" and report a warning.
**Expected result:** It should due to the filter avoid attempting to backup "~$foo.xlsx", and therefore run cleanly with no warning.

**Comment by kenkendk** [comment]
Yes, you are correct, Duplicati replaces `~` with the users home folder.

I am not sure there is a way to escape that replace, but we should fix that.

You can work around it by using a filter such as this (wow, unreadable!):
```
-[.*\\\0x7E\$[^\\]+]
```

This would be "anything, then backslash, then tilde, then dollar, then anything without a backslash"

**Comment by lightvector** [comment]
That's a reasonable workaround for now. I had to use '\\x7E' rather than '\\0x7E', but that works. Thanks!

**Comment by fbsdmon** [comment]
Can you please write the exclude expression for excluding all files that start with ~$ anywhere in the folder structure.

**Comment by kenkendk** [comment]
That would be `-[.*\x7E\$.*]`

**Comment by TekkiWuff** [comment]
Was this maybe fixed with PR #2836 as well, which removed the tilde expansion?

**Comment by warwickmm** [comment]
Yes.  Tilde expansion was removed as it was causing too many issues like this one.
