### ISSUE TITLE
Request: Allow deletion of specific historical backup out of a sequence

### ISSUE THREAD

**Issue by harald14** [duplicati/duplicati#2347]
### Version info
**Duplicati Version:** 2.0.1.49_experimental_2017-02-23
**Operating System:** Win10/64
**Backend:** Any

### Request
Currently it is not possible to delete or invalidate a single backup set out of a sequence of backups.

It could happen that a huge set of data was placed into the backup source directories by accident, which was never planned to be stored there and never was planned to get backup.

After a backup of that (e.g. daily, retention 6 month), this data will stay on the destination for the next 6 month until the retention time is reached. This assumes, that the data in the source was deleted after the mistake was detected.

This does waste potentially a lot of space.

To get rid of that wasted space, it would be nice to have a function to explicitly delete single backup sets.

The already existing "cleanup" features would automatically take care of the deletion of related content at the backup destination.

To make it easier to identify such cases, it would be nice to see the total size of backuped files next to the backup set.

A kind of a "backup-set-browser" would help here to navigate.

**Comment by kenkendk** [comment]
You can delete specific versions with the commandline tool, just not in the UI.

Click the backup name in the overview, then click the "Export ..." option.
On the next page, choose "As commandline" and click "Export".

You get something like:
```
Duplicati.CommandLine.exe backup ppp://server/folder?opt1=a --dbpath=xyz
```

Open a Command Prompt, and do something like:

```
cd "C:\Program Files\Duplicati 2"
Duplicati.CommandLine.exe list ppp://server/folder?opt1=a --dbpath=xyz
```

This will show you the versions, and what "numbers" Duplicati has assigned (easier than working with the dates).

The run"
```
Duplicati.CommandLine.exe delete ppp://server/folder?opt1=a --dbpath=xyz --version=3,4,5 --dry-run
```

And Duplicati will report what it intends to delete when you specify versions `3,4,5`. Remove the `--dry-run` part and Duplicati will delete the files, and kick off a "compact" operation that will reclaim the wasted space.

A more advanced operation is to selectively drop the files, which can be done with the purge command like:

```
Duplicati.CommandLine.exe purge ppp://server/folder?opt1=a --dbpath=xyz "*.txt" --dry-run
```

**Comment by kenkendk** [comment]
And yes, a "backup set browser" would be nice. The "Restore" page is the closest to that right now.

**Comment by harald14** [comment]
Thank you very much for this hint. I will give it a try.

**Comment by kenkendk** [comment]
Closing and assuming fixed

**Comment by BlueNinja0** [comment]
I incurred in this same problem today. It would be a very nice feature to have on the GUI, but for now the command line tool will do.
