### ISSUE TITLE
windows user profile error (1509) caused by duplicati lock file in user default

### ISSUE THREAD

**Issue by pmarat-sqrt0** [duplicati/duplicati#2348]
I have:
- [x] searched open and closed issues for duplicates

### Version info
**Duplicati Version:** 2.0.1.45
**Operating System:** Windows Server 2012 

### Bug description
Login as new user failed with:
Winlogon 6004 <Profiles>, User Profile General 1509
file \\?\C:\Users\Default\AppData\Roaming\Duplicati\control_dir_v2\lock_v2 could not be copied

### Steps to reproduce
- start Duplicati as admin
- try to login with a new user 

**Actual result:** C:\Users\Default\ is template for new user
Better move lock file to %ProgramData%\duplicati  (C:\ProgramData\Duplicati)

**Comment by kenkendk** [comment]
I think this is in line with #2222

**Comment by pmarat-sqrt0** [comment]
I don't think it is the same like #2222.
While moving everything to %programdata% would also solve this problem,  i think it isn't necessary for this particular problem.
The directory C:\Users\Default\AppData\Roaming\ is us used as template for a new user profile. 
%programdata% should be better suited for such things as an global lock file  i think.

**Comment by kenkendk** [comment]
I see, you experience that the file is created in `Default`, and clearly it should not be.
Is the file created when you log in as `Administrator` and start Duplicati ?

**Comment by pmarat-sqrt0** [comment]
I was not aware that creating the lock file in _Default_ was faulty behavior.
I have tested starting Duplicati as admin on different Server Versions 2008, 2008r2 and 2012R2 and could not reproduce this bug.
After deleting the Duplicati directory from _default_ it was not recreated after restart as admin.

**Comment by pmarat-sqrt0** [comment]
The lock file is recreated after server 2012r2 restart. 
It seams like there is an **_Duplicati .GUI.TrayIcon_** process already running before login after server restart. And it seams this process uses _default_ **appdata**.
If this process is killed and **_Duplicati .GUI.TrayIcon_**  started as admin this lock file is not longer used.
