### ISSUE TITLE
Cert-Sync how to instal on OMV

### ISSUE THREAD

**Issue by ETNY-Y** [duplicati/duplicati#2353]
Hello, 
I've got a issue with certificat :
"option --accept-specified-ssl-hash=XXXXXXXXXXXX" does not seems to works and
when i do on ssh : 
root@heolya-omv:~# cert-sync /etc/ssl/certs/ca-certificates.crt
-bash: cert-sync : commande introuvable

which plugging is missing? where can i found it to install?
Thank you

**Comment by kenkendk** [comment]
I have written this general guide:
https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono

Feel free to update it if you find out something related to OMV.

**Comment by kenkendk** [comment]
Closing and assuming fixed
