### ISSUE TITLE
Can't Install on Centos 7

### ISSUE THREAD

**Issue by canove** [duplicati/duplicati#2354]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] reinstall the system (centos7) and try again 

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.49
**Operating System:** CentOS 7
**Backend:** no metter

### Bug description
Error with dependencies while instaling.

### Steps to reproduce
- Install a fresh CentOS 7 minimal installation (headless)
- Add mono repos from official guide
- Install mono (yum install mono-complete)
- Install Duplicati by these steps:
1-) wget https://github.com/duplicati/duplicati/releases/download/v2.0.1.49-2.0.1.49_experimental_2017-02-23/duplicati-2.0.1.49-2.0.1.49_experimental_20170223.noarch.rpm -O duplicati.rpm
2-) yum localinstall duplicati.rpm

**Actual result:** 
[root@server /]# yum localinstall duplicati.rpm
Plugins carregados: fastestmirror
Examinando duplicati.rpm: duplicati-2.0.1.49-2.0.1.49_experimental_20170223.noarch
Marcando duplicati.rpm para ser instalado
Resolvendo dependências
--> Executando verificação da transação
---> O pacote duplicati.noarch 0:2.0.1.49-2.0.1.49_experimental_20170223 será instalado
--> Processando dependência: libappindicator para o pacote: duplicati-2.0.1.49-2.0.1.49_experimental_20170223.noarch
Loading mirror speeds from cached hostfile
 * base: centos.xpg.com.br
 * extras: centos.xpg.com.br
 * updates: ftp.unicamp.br
--> Processando dependência: mono(appindicator-sharp) para o pacote: duplicati-2.0.1.49-2.0.1.49_experimental_20170223.noarch
--> Resolução de dependências finalizada
Error: Pacote: duplicati-2.0.1.49-2.0.1.49_experimental_20170223.noarch (/duplicati)
           Requer: mono(appindicator-sharp)
Error: Pacote: duplicati-2.0.1.49-2.0.1.49_experimental_20170223.noarch (/duplicati)
           Requer: libappindicator
 Você pode tentar usar o parâmetro --skip-broken para contornar o problema
 Você pode tentar executar: rpm -Va --nofiles --nodigest
[root@server /]# 

**Expected result:** Install sucefull

Can someone help?

**Comment by canove** [comment]
At the time, im using it from the extracted zip file and it seems to run ok. There is any problem on use duplicati without installation? (RPM)

**Comment by kenkendk** [comment]
The RPM just has the dependencies, so you can avoid `mono-complete`.

The thing it fails on is `appindicator-sharp` which is a library that is used to display the TrayIcon on Gnome3. It works fine without this library, but the TrayIcon is then displayed using GTK which Gnome3 hides by default.

**Comment by canove** [comment]
When i tried to install it from .rpm, with "yum localinstall duplicati.rpm", the dependencies wont resolved well and installation fails.
I think It occur because "yum" is deprecated, i tried it with "dnf install duplicati.rpm" and it worked well.

But in tests, i got some "GET" erros on the "Verify" stage of backup, such as in restore tests.

After some time, i figured out! The mono version 4.8.0 its not working well, at least with Azure-Blob backend. I installed the version 4.6.2 and it works well.

Thanks!

**Comment by kenkendk** [comment]
Ok, lets hope the Mono issue gets fixed before 4.8 is more widespread.

**Comment by jerrac** [comment]
I recently had to enable the epel repo in order to get ```appindicator-sharp``` to install on centos 7.

**Comment by gene1wood** [comment]
Here's what worked for me on CentOS 7.

```
# Add the mono yum repo as described here : http://www.mono-project.com/download/#download-lin-centos
yum install epel-release yum-utils
rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
yum-config-manager --add-repo http://download.mono-project.com/repo/centos7/
# Install the dependencies
yum install libappindicator libappindicator-sharp
# Install duplicati
yum localinstall duplicati.rpm
```

# Notes

* Here in December 2017 this process gets mono `5.4.1.6` and I didn't encounter any of the `4.8.0` vs `4.6.2` issues @canove mentions [above](https://github.com/duplicati/duplicati/issues/2354#issuecomment-285020748)
* I found in CentOS 7 the `appindicator-sharp` package to be called `libappindicator-sharp` not `appindicator-sharp` as @jerrac mentioned [above](https://github.com/duplicati/duplicati/issues/2354#issuecomment-308227378)
* I didn't need to use `dnf` to deal with the dependencies as suggested [above](https://github.com/duplicati/duplicati/issues/2354#issuecomment-285020748), yum worked fine
* I didn't need to install `mono-complete` as @kenkendk mentioned [above](https://github.com/duplicati/duplicati/issues/2354#issuecomment-284990542) as yum correctly resolved the mono dependencies triggered by installing `libappindicator-sharp` and by not installing `mono-complete` you avoid 10 unnecessary packages being installed

**Comment by jerrac** [comment]
To advertise myself a bit, I've had decent success using this Ansible role I wrote a while back: https://github.com/LaneCommunityCollege/aspects_duplicati 

Just in case it is useful for anyone.
