### ISSUE TITLE
Error while uploading on Hubic

### ISSUE THREAD

**Issue by ETNY-Y** [duplicati/duplicati#2356]
Hello, 
Anybody to explain me what does it mean and how to resolve : 
Error while running Videos
Previous volume not finished, call FinishVolume before starting a new volume.

It happens when i upload my backup after several percent.

Thank you !
Yannick

**Comment by kenkendk** [comment]
That is an internal error in Duplicati.

Can you provide a stack trace for this?

**Comment by kenkendk** [comment]
I think this is the same as #2358 which has a stack trace.
I am closing and assuming duplicate.
