### ISSUE TITLE
restore-permissions does not work for linux

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [duplicati/duplicati#2360]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** Duplicati - 2.0.1.51_canary_2017-03-03
**Operating System:**
 - backup creation: mono:4 based docker image https://hub.docker.com/r/intersoftlab/duplicati/
 - backup restore on host system: linux arch 4.9.11-1-ARCH; Mono JIT compiler version 4.8.0

### Bug description
I create backups of other mounted docker volumes using the restore-permissions flag. When i restore the backup all files and folders are owned by root:root, instead of the original user and group. Additionally it seems that the files lost the write permission for the user. 

### Steps to reproduce
- run duplicati with https://hub.docker.com/r/intersoftlab/duplicati/, update to Duplicati - 2.0.1.51_canary_2017-03-03 using the webupdater
- create backup with activated `restore-permissions` advanced option
-  restore the backup on host machine with: `sudo mono ${DUPLICATIFOLDER}/Duplicati.CommandLine.exe restore ${backup} --restore-path=${volumePath} --overwrite=true`

**Actual result:** The backup is restored with root:root ownership for all folder and files and corrupted permission flags.
**Expected result:** I expected to have user and group ownership information restored as in front of the backup. Additional i expect the same permission flags for the original files and the restored files. 

### debug log
 - no log entries present

**Comment by kenkendk** [comment]
The `--restore-permissions` needs to be applied to the restore process. The permissions are always stored in the backup.

Does it work if you run:
```
sudo mono ${DUPLICATIFOLDER}/Duplicati.CommandLine.exe restore ${backup} --restore-path=${volumePath} --overwrite=true --restore-permissions
```

**Comment by cguentherTUChemnitz** [comment]
Thanks for the suggestion. I will test it soon. I wonder why those cli options are not listed with:
`mono ${DUPLICATIFOLDER}/Duplicati.CommandLine.exe help restore`

**Comment by cguentherTUChemnitz** [comment]
Thx for the feedback. Yes is works as intended when the `--restore-permissions` flag is added to the restore cli call. Nevertheless it would be beneficial to show those options in the help output.

**Comment by kenkendk** [comment]
What help output are you referring to?

This one maybe?
https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/help.txt#L112

**Comment by cguentherTUChemnitz** [comment]
Exactly this one.
