### ISSUE TITLE
Resource not found: http://127.0.0.1:8200/

### ISSUE THREAD

**Issue by JeffreyPFD** [duplicati/duplicati#2364]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.49
**Operating System:** Windows 10, 32bit, Google Chrome

### Bug description
When I open up Duplicati 2 I get "Resource not found: http://127.0.0.1:8200/"  and in the url bar it says, "http://127.0.0.1:8200/"

### Steps to reproduce
- Tried to reinstall twice

**Actual result:** Same results occurred

### Screenshots
![image](https://cloud.githubusercontent.com/assets/26304387/23754402/744b4d4a-04a2-11e7-8e56-0e3223a28163.png)

**Comment by kenkendk** [comment]
Can you try `http://localhost:8200/` instead?

**Comment by JeffreyPFD** [comment]
Hi Kenkendk,

Thank you for trying to help.  I tried your suggestion and received similar results.

![image](https://cloud.githubusercontent.com/assets/26304387/23799048/b6564e90-056c-11e7-8e3d-ba52b00f5cac.png)

**Comment by JeffreyPFD** [comment]
It is now working.

**Comment by kamal734** [comment]
Hi JeffreyPFD,
Please share how were you able to resolve this? I'm facing similar issue but cannot make out on how to overcome this. Tried reinstalling Duplicati multiple times but it yielded no good results.
Regards,
Kamal
