### ISSUE TITLE
Repair missing

### ISSUE THREAD

**Issue by ysamjo** [duplicati/duplicati#2369]
----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.49_experimental_2017-02-23
**Operating System: Mac
**Backend:**

### Bug description
After changing the Target-Directory, Client needs "Repair". Where do I find repair?

**Comment by kenkendk** [comment]
If you change the target directory (and the new directory is empty), you need to delete the local database. The button to do this is the same place as the "Repair" button, on the "Local database" page.

**Comment by ysamjo** [comment]
Sorry, where do I see "Local Database"?

**Comment by kenkendk** [comment]
If you click the backup, you should see a menu like this:
<img width="628" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1510755/23922447/b319ae36-0902-11e7-8e28-7576b3056227.png">

It is called "Manage database".
