### ISSUE TITLE
Multiple backup target locations

### ISSUE THREAD

**Issue by jkaberg** [duplicati/duplicati#2371]
It would be beneficial if one could specify multiple target locations where one has critical data. I'd like to see an option where by default one target location is mandatory, and then one can add up to several additional locations depending on need

**Comment by kenkendk** [comment]
Yes, I think this is in line with #479

**Comment by NeoMatrixJR** [comment]
@jkaberg - Do you mean RAIDing multiple locations like #479 or full backups to multiple points?  I would like to see the latter.  I like to keep a full local backup on my network and send a full backup offsite as well.

**Comment by rorrison** [comment]
This sounds very different from #479 .  I would like this suggestion - multiple redundant copies of a single backup (for me it would be one in the cloud and one on a local external HD).

Spreading a single copy of a backup (#479) across multiple destinations is not useful to me. Would such a backup even be usable if one of the services was unavailable?
