### ISSUE TITLE
Backup from SMB\CIFS share with spécific crédentials

### ISSUE THREAD

**Issue by vlepetit** [duplicati/duplicati#2372]
Hi,
What is the best way to backup data from cifs share to sftp share without connected users on windows server ?
- the sftp destination is not the problem..
Do i have to use : 
- duplicati windows service ?
- duplicati command line with windows task scheduler ?

How can i give a good crédential to duplicati to open smb share source ? 
with scripts launch before backup to mount network drive with good crédential ?
or maybe execute the duplicati windows service with spécific account ?

Regards,
vlepetit

**Comment by vlepetit** [comment]
Yes !!
I test this with succes : 
1 - I had install duplicati windows service
2 - i launch service with an account who have read/write right on source smb share

**Comment by vlepetit** [comment]
I had found for windows server but how can we done the same with other platform ? to launch DUplicati as a serve without opened user session ?
Linux ?
Mac Os x ?

Regards,
vlepetit

**Comment by kenkendk** [comment]
Yes, you have to do something like that. In the current version, Duplicati expects files to be accessible locally, there is no good support for reading files in other ways.
