### ISSUE TITLE
Can't restore files - duplicati showing encrypted files only

### ISSUE THREAD

**Issue by WitchDoctorAmI** [duplicati/duplicati#2374]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.49_experimental_2017-02-23
**Operating System:** Win 10 Edu
**Backend:** HDD

### Bug description
Hey,
I have problems restoring my backup. I had 4 different backup jobs on my backup drive. After I lost my data I wanted to restore those, on the first screenshot you see the  4 different folders which contain my backups. The one I am interested in is the folder "BackupOrdner". 

![1](https://cloud.githubusercontent.com/assets/17800347/23867745/2eb60314-081d-11e7-8d36-b3ac479c1304.png)

When I try restoring "Fotos" for example, the filelist looks just like I thought it would work, I could already pick my files:

![2](https://cloud.githubusercontent.com/assets/17800347/23867777/52a88878-081d-11e7-9068-33983aca92b7.png)

But when I try restoring the important folder, I just get to see this:

![3](https://cloud.githubusercontent.com/assets/17800347/23867791/61f8ed9a-081d-11e7-8738-9959d4a1d5ab.png)

There are only crypted zip files in there.

I already tried using the command line, which produced the same outcome, the system more or less copied the files from my drive to my restore folder. 
I tried removing the encryption with AES crypt. 
Files looked like that afterwards:

![4](https://cloud.githubusercontent.com/assets/17800347/23867896/b73b51da-081d-11e7-933d-d934006b9cf1.png)

When I tried restoring from that I only got errors (I think it was a failed hash or filesize, sorry, have no screenshot of that anymore). 

### Steps to reproduce
- choose restore folder
- choose the folder i need
-  try restoring

**Actual result:** everytime I only geht the crypted/part lists

**Expected result:** get my data back

### Screenshots

See above

### debug log

Sorry, dont really have a logfile, 3 of my 4 archives work, they all got the same password and settings though :(

**Comment by kenkendk** [comment]
I am not sure what was supposed to be in `BackupOrdner`, but it looks like there is another backup inside that folder.

Since you have all the files decrypted now, can you try to make Duplicati restore from the decrypted files? That is, use the folder with the decrypted files as the "remote location"?
Hopefully the files you seek are inside that backup.

**Comment by WitchDoctorAmI** [comment]
I'll give that a shot tomorrow, thanks for the idea :)

**Comment by WitchDoctorAmI** [comment]
Hey, I tried your idea.. unfortunatley, every "backup in backup" showed another one of those duplicati backup files. i tried doing that 5 times, the fifth times duplicati told me "no filesets found on remote target".

there were 5 different versions of the backup, maybe because of that? any other ideas? :(

**Comment by kenkendk** [comment]
Can you look inside one of the `dlist` files? (unzip first).

Inside you should find a file which lists all the filenames it knows. I am hoping that you see filenames you recognize there, and not just more Duplicati backup filenames.

**Comment by ts678** [comment]
The first screenshot of the backup-in-backup showed five dlist files, so five versions. Five un-nests leaves none, so "no filesets".
I have a bad feeling that the source screen was configured with the destination path. This is exactly what would result from it...

**Comment by warwickmm** [comment]
Possible misconfiguration is my guess as well.  Given the age, and since I haven't heard of this occurring elsewhere, I'm going to close this issue.  If you are still experiencing this, please reopen and provide more details.
