### ISSUE TITLE
duplicati service or server whitout user opened session ?

### ISSUE THREAD

**Issue by vlepetit** [duplicati/duplicati#2376]
How to launch Duplicati as a server without opened user session ?
I had found for windows server with duplicati.WindowsService #1768  but how can we done the same with other platform ? 
Linux ?
Mac Os x ?

Regards,
vlepetit

**Comment by kenkendk** [comment]
On Ubuntu there is a service script: `systemctl start duplicati` should get it running.

You do not really need anything special on non-Windows, as a "service" here is just a process. In other words, you can just run `mono Duplicati.Server.exe` inside a `screen` session or similar.

**Comment by kenkendk** [comment]
This article might shed some more light on the question: https://www.duplicati.com/articles/Way-To-Make-A-Backup/

**Comment by umgfoin** [comment]
Linux/ OSX e.g.: 

Call from a terminal-console:
`nohup mono Duplicati.Server.exe --enable-piped-streaming &`

Or set a cron-job to start duplicati at boot-time:
`crontab -e`

add the following entry:
`@reboot      /usr/share/duplicati/mono Duplicati.Server.exe --enable-piped-streaming &`

++umgfoin.

**Comment by kheischer** [comment]
My solution for OS X:

Create a directory to store the database e.g. "/etc/duplicati":
```sudo mkdir /etc/duplicati```

Create a file named "/Library/LaunchDaemons/com.duplicati.app.launchdaemon.plist" with this in it:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.duplicati.app.launchdaemon</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Duplicati.app/Contents/MacOS/duplicati-server</string>
		<string>--webservice-port=8200</string>
		<string>--server-datafolder=/etc/duplicati</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

To start it run the following, or reboot:
```sudo launchctl load /Library/LaunchDaemons/com.duplicati.app.launchdaemon.plist```

This runs duplicati as superuser, so do it at your own risk and I recommend to protect it with a password.
