### ISSUE TITLE
Can't store backup to Amazon Cloud Drive

### ISSUE THREAD

**Issue by Vrumfondel** [duplicati/duplicati#2378]
I have:

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53
**Operating System: debian **
**Backend:**

### Bug description
GATEWAY_TIMEOUT
Backup fails after ~10 Minutes with error "Gateway Timeout".
In my ACD I see that a file with only 653B is existing.

### Steps to reproduce
Start any kind of Backup to ACD - no matter how much files or size.

**Actual result:** Duplicati stops after some while with error "GATEWAY TIMEOUT". On ACD a new file with size 653B was created (always exactely this size)
**Expected result:** Working Backup with 50MB Filechunks

**Comment by shoeper** [comment]
Gateway Timeout pretty much looks like there​ is an issue on Amazon's end while downloading at least one of the files.

**Comment by Vrumfondel** [comment]
Well - one would think so at first sight, but the problem is only occuring with Duplicate, but not with rclone.

So Duplicati as such must have some influence there ....

**Comment by shoeper** [comment]
Is it possible in the webinterface to see which file is classified as which type?

**Comment by Vrumfondel** [comment]
Well, kind of.
I can at lease say that the files show not up in the "Fotos" section - but of course I don't see any possible internals.
I'm not sure if this classification is really an issue - but it would be the only obvious thing outside of Duplicati I see to be different to the other solutions .

**Comment by wintersolutions** [comment]
I'm having the same issue, also with Amazon cloud drive.

I can see in the log that the upload starts, but the actual upload rate is 0 byte/s. After a while the log shows errors that the Socket has been closed.

I tried to create a new backup. There I could see that duplicati is creating the folder on ACD but no files get written to it.

I have this issue on all 3 of my Linux machines.

For me the files show up under "Dateien"/Files in the ACD interface.

**Comment by Vrumfondel** [comment]
Some more input: I gave the WIN64 version a try: The issue is not occuring there.

One more thought: It it possible that this only occurs to useres of German ACD - at least there was no report from other regions here so far ....

**Comment by r100gs** [comment]
I´m running duplicati on ubuntu 12.04 and have the same issue. 
Backup starts but after a while I get the error "GATEWAY TIMEOUT" and duplicati crashes and I have to restart it.

r100gs

**Comment by philosifer** [comment]
And the same here. Debian 8.7 Jessie using duplicati-cli

Operation Put with file duplicati-b1e23b579e125549fc9e32b6016c5685e7.dblock.zip.aes attempt 3 of 5 failed with message: GATEWAY_TIMEOUT => GATEWAY_TIMEOUT
Renaming "duplicati-b1e23b579e125549fc9e32b6016c5685e7.dblock.zip.aes" to "duplicati-b01b513fb91e054fbf9cee529bfb4b201a.dblock.zip.aes"

Two machines windows 10 are backing up fine.

**Comment by airbillion** [comment]
Same here...using docker version and cannot Banjul to avid...same error!

**Comment by warwickmm** [comment]
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
