### ISSUE TITLE
Unable to import settings in  Duplicati 2.0.1.53_experimental_2017-03-13

### ISSUE THREAD

**Issue by itdude** [duplicati/duplicati#2380]
I have:
- [X ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version: 2.0.1.53_experimental_2017-03-13
**Operating System: Windows 7/Windows 10 (Google Chrome/Firefox)
**Backend: ZFS Share

### Bug description
When I try to import a pre created json backup, the import fails when trying to save with "Unable to parse backup or schedule object: Cannot convert Integer value to System.DayOfWeek"
The initial file I used was from the previous version.

I then created a new configuration manually and exported that. However, the import failed with the same problem.
Also, in the configuration file I had selected to choose all the days of the week, however none were selected when I got to the schedule page.

I tried changing the to different formats, but none worked:
03/16/2017
2017-03-16
(However, changing the date for the manually created entry works)
### Steps to reproduce
- Create a new configuration in Duplicati
- Export to file
- Import file

**Actual result:
- Error message "Unable to parse backup or schedule object: Cannot convert Integer value to System.DayOfWeek", when trying to save
- None of the days are selected, even though they were selected when the export was done. (In the json file all the days are configured)

**Expected result: Import should succeed

### Screenshots
![unabletoimport](https://cloud.githubusercontent.com/assets/6398084/23955454/316abb58-099a-11e7-8abb-125b15e99a11.jpg)

### debug log

I've added two JSON files with the exported configuration. I've removed any personal information such as the server where the backup would be.
[Test.config.anon.2.0.1.49.txt](https://github.com/duplicati/duplicati/files/844951/Test.config.anon.2.0.1.49.txt)
[Test-duplicati-anon.config.2.0.1.53.txt](https://github.com/duplicati/duplicati/files/844952/Test-duplicati-anon.config.2.0.1.53.txt)

**Comment by kees-z** [comment]
I can confirm this is a bug in 2.0.1.53. Exactly the same symptoms with my setup: an exported backup job cannot be imported in the same version of Duplicati (2.0.1.53). After importing, all weekdays are deselected, but they were selected when creating the job. Importing ends with the same error message.

**Comment by katasun** [comment]
Confirm the error message. In my case it lost the size of the upload file, too.

**Comment by Pingperfect** [comment]
Same issue here as well. Is there a fix/workaround?

**Comment by kenkendk** [comment]
Thanks for the test files, it was easy to reproduce.

The workaround is to check the "Save immediately" box, as that bypasses the new editing system. Alternatively, edit the file, and remote the "AllowedDays" setting.

The problem was that the serialized json had converted "mon" to "1" etc, after loading the file and sending it back to the browser for editing.

@katasun : I was not able to reproduce the loss of upload size, can you make a test file?

**Comment by itdude** [comment]
Hi kenkedk,

thanks for the update. Will the import/export function then be fixed in a later version?

Regards,
Dean

**Comment by kenkendk** [comment]
Yes, it will be part of the next canary build, and then the experimental a little later.

**Comment by itdude** [comment]
Thank you very much!

On March 23, 2017 12:57:38 PM GMT+01:00, Kenneth Skovhede <notifications@github.com> wrote:
>Yes, it will be part of the next canary build, and then the
>experimental a little later.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/duplicati/duplicati/issues/2380#issuecomment-288696382

-- 
Dean Bakker
