### ISSUE TITLE
Amazon Cloud Drive connection Errors in Debian 8.3

### ISSUE THREAD

**Issue by Kharnivora** [duplicati/duplicati#2386]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.49_experimental_2017-02-23
**Operating System:** Debian 8.3
**Backend:**

### Bug description
Backups fail with "Error getting response stream (Write: The authentication or decryption has failed.): SendFailure"

### Steps to reproduce
- Get the .deb package from duplicati.com
- Install it using dpkg -i and apt-get install -f 
- Start the Duplicati daemon
- Add a new backup, backup destination Amazon Cloud Drive
- Click "Test connection" and add the necessary certificate hashes to the command line parameters on the backup destination page, until the connection goes through
- Start the backup

**Actual result:** 
Backup fails with Error getting response stream (Write: The authentication or decryption has failed.): SendFailure, nothing is uploaded to Amazon Cloud Drive
**Expected result:** 
Backup is uploaded to Amazon Cloud Drive

**Question**
Do I need to extract cert-sync out of mono-complete to fill Monos certificate store, or is this a bug? If it´s necessary to fill Monos certificate store, I´d suggest to remove the note about addind the certificate hashes manually as command line parameter.

**Comment by shoeper** [comment]
Looks similiar to https://github.com/duplicati/duplicati/issues/2378

**Comment by Vrumfondel** [comment]
No - this is different to #2378.
I ran into authentication issue aswell - but only when using Amazon S3. Importing any keys to mono certificate storage did not fix it. In this failure mode the transfer does not even start.
I ended up in using "accept-any-ssl-certificate" for these Jobs.

**Comment by Kharnivora** [comment]
Using --accept-any-ssl-certificate works. But this is an ugly workaround, no real solution ;)

**Comment by erikkaashoek** [comment]
Using amazon cloud drive 
Where to add the "--accept-any-ssl......." parameter? Adding at the end does not solve the certificate problem for me. 
TlsTest.exe shows no problems

**Comment by Kharnivora** [comment]
Go to backup destination, scroll down to advanced options. Now you can either choose accept-any-ssl-certificate from the dropdown, or click on the three points, choose edit as text and add the full paramter "--accept-any-ssl-certificate=true"

**Comment by erikkaashoek** [comment]
That worked!!!! Thanks!!!

**Comment by kenkendk** [comment]
I finally figured out how to get working SSL on Debian 8:
https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono#debian-jessie-80

This will fix things without needing the `--accept-any-ssl-certificate` workaround.

Please let me know if this fixes it.

**Comment by Kharnivora** [comment]
After adding the ppa and installing the latest .deb package (2.0.1.53) getting the dependencies using apt-get install -f totally screwed up my dependency tree. I had to install mono-complete with aptitude and some more dependencies to be able to install duplicati correctly.

Anyway, it´s working now, without adding "--accept-any-ssl-certificate=true". Thanks :)

**Comment by Kharnivora** [comment]
Update:
The automatic jobs failed, the error is the same. Any idea how to get the certificate the Amazon Cloud Drive server use, to import them into the Debian certificate store and then into mono?

**Comment by kenkendk** [comment]
Amazon uses a few different servers, so it might be hard to figure out what is where.

They mention `https://api.amazon.com` and `https://content-na.drive.amazonaws.com` in the documentation, so you need at least those.

**Comment by Kharnivora** [comment]
Alright. The key was to manually import the certificates using cert-sync.

Putting the certificates into /usr/local/share/ca-certificates/, running update-ca-certificates and then cert-sync /etc/ssl/certs/ca-certificates.crt apparently didn´t import the certificates into the mono certificate store... I guess this is a mono issue.

Sadly I can´t tell you exactly which certificate did the trick...

**Comment by ElRico** [comment]
@Kharnivora I had a similar issue on a QNAP NAS. [The workaround I found](https://github.com/duplicati/duplicati/issues/2431#issuecomment-295889229) might work for you as well.

**Comment by warwickmm** [comment]
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
