### ISSUE TITLE
Volume size cannot be set to 1 MB

### ISSUE THREAD

**Issue by dessant** [duplicati/duplicati#2387]
### Version info

**Duplicati Version:** 2.0.1.53
**Operating System:** Windows 10

### Bug description
Setting 1 MB for `Upload volume size` under General options produces this error: DBlock size must be at least 1MB.

**Expected result:** Being able to set a volume size of 1 MB.

**Comment by kenkendk** [comment]
I guess there is a `<` that should be changed to `<=`.

But is there a use case where you want/need to use such small remote volumes?

**Comment by dessant** [comment]
I'm not familiar enough with the project to know if there is a use case for it, I've mostly reported the bug because of the inconsistency between the code and error message.

**Comment by kenkendk** [comment]
Fixed with 687731e
