### ISSUE TITLE
Renamed files always present in recent backups

### ISSUE THREAD

**Issue by TonyGLT** [duplicati/duplicati#2390]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53
**Operating System:** Windows 8.1
**Backend:** Hubic

### Bug description
Files that I rename are always present in subsequent backups. When I try to restore the folder with theses files, I can see them twice in the restore GUI : one time with their actual name and another time with their old name.

### Steps to reproduce
- backup some files
- rename them
- do another backup
- open the restore GUI and list the folder
- files are listed twice

**Actual result:** files are listed twice
**Expected result:** only see files with their new names

**Comment by kees-z** [comment]
Did you by any chance use the `--all-versions` command line option? If so, disable it. This will show only files that are included in the selected backup task.

**Comment by TonyGLT** [comment]
I don't use the command line. I use the web GUI to restore files and I don't see where I can put an option.

**Comment by kenkendk** [comment]
Can you post a screenshot? I am not sure I understand exactly how the files are "listed twice".

**Comment by TonyGLT** [comment]
A screenshot before renaming a file :

![capture before rename](https://cloud.githubusercontent.com/assets/15320629/24396566/ef6c9a82-13a3-11e7-92ad-6f752597a78c.JPG)

and a screenshot after renaming IMG_0005.JGP into IMG_0005_Renamed.JPG :

![capture after rename](https://cloud.githubusercontent.com/assets/15320629/24396646/38257032-13a4-11e7-9ff7-c3ea4049628c.JPG)

**Comment by kenkendk** [comment]
Thanks, that makes it very clear.

And you are sure that the `IMG_0005.JPG` file is not in the folder when you make the backup?
Do you see any errors or warnings when running the backup?

**Comment by TonyGLT** [comment]
Yes I am sure that the file IMG_0005.JPG is not in the folder when I make the Backup.

And, I don't see error or warning during the backup.

**Comment by ts678** [comment]
Not reproducible, testing with current Duplicati, Windows 10, and local folder destination. Maybe this has been fixed over time?

![image](https://github.com/duplicati/duplicati/assets/40771998/73249553-5084-4ab3-8387-8ddc3b99ead7)

![image](https://github.com/duplicati/duplicati/assets/40771998/f3447e79-a937-427c-9f14-f96b340fd877)

A rename from a file point of view looks like a deleted old file and an added new file, but deduplication avoids file data re-upload.

![image](https://github.com/duplicati/duplicati/assets/40771998/889f2b09-8e12-4997-ae40-685f07d6e153)

Can anyone reproduce issue currently?
