### ISSUE TITLE
umask for Linux duplicati-cli backup

### ISSUE THREAD

**Issue by rbeede** [duplicati/duplicati#2395]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.53_experimental_2017-03-13
**Operating System:** Ubuntu 16.10 64-bit Desktop
**Backend:**

### Bug description
When running duplicati-cli backup the log & backup files are created with a permission set of u=rw,g=rw,o= (0660).   However my bash shell is set with a  umask=0007  that is not honored.

### Steps to reproduce
- umask 0007
- duplicati-cli backup

**Actual result:** Backup files are created on Linux filesystem with permissions of 660.
**Expected result:** Was expecting files to be created with permission of 600.

I can change the permission after the backup runs or even change the backup directory destination parent folder to restricted permissions, but I would like to have the desired restricted permissions applied at time of creation.

1. Ideally honor the current umask
2. An alternative would be to add to the help documentation that the permissions applied will always be 660 regardless of the umask

**Comment by kenkendk** [comment]
You can add `--restore-permissions` to get the uid/gid and permissions. It is not enabled by default, because it can be problematic if the users do not exist on the target machine.
