### ISSUE TITLE
Backup crashes under Ubuntu 14.04

### ISSUE THREAD

**Issue by jarmo** [duplicati/duplicati#2396]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.50_canary_2017-02-28
**Operating System:** Ubuntu 14.04.5 LTS
**Backend:** webdav

### Bug description
duplicati-cli backup crashed with the attached output in log file:
[backup.txt](https://github.com/duplicati/duplicati/files/857646/backup.txt)

**Comment by jarmo** [comment]
Here's also a profiling log, which might not help too much:
[backup-today.txt.zip](https://github.com/duplicati/duplicati/files/857677/backup-today.txt.zip)

**Comment by warwickmm** [comment]
Due to lack of recent reports of issues with Ubuntu, I'm going to assume this has been resolve.  If not, feel free to reopen with new details.
