### ISSUE TITLE
Duplicate instance

### ISSUE THREAD

**Issue by Ragonz2** [duplicati/duplicati#2397]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

Duplicati - 2.0.1.49_experimental_2017-02-23
Windows Server 2012R2
Google Drive

### Bug description
Not really a bug but is there a way to stop the program from running in the notification area/auto launching after the program is installed as a service. Users are getting confused when it pops up saying there are no scheduled tasks

### Steps to reproduce
- Install duplicati
- Install as a service
- launch webpage to get to service version and doubleclick on desktop version, both have different ports so are essentially seperate

**Actual result:** 2 instances of software running
**Expected result:** 1 instance of software should be running (the service)

**Comment by kenkendk** [comment]
Yes, just remove the shortcut from the "Startup" folder inside the start menu.

Alternatively, edit the shortcut and add `--no-hosted-server --serverurl=http://localhost:8200` to have it connect to the service.

**Comment by kenkendk** [comment]
Does this solve the issue?

**Comment by kenkendk** [comment]
Closing for lack of feedback
