### ISSUE TITLE
Backup time does not reflect summertime change.

### ISSUE THREAD

**Issue by pascalBokBok** [duplicati/duplicati#2407]
Last week my backup ran every day at 14. This week it runs at 15. We've changed to summertime but I would expect Duplicati to still run at 14 since that's what I told it to.

Duplicati 2.0.1.53_experimental_2017-03-13
OS: KDE Neon (ubuntu derivative)

**Comment by shoeper** [comment]
Duplicate of https://github.com/duplicati/duplicati/issues/2069

**Comment by kenkendk** [comment]
Yes.
