### ISSUE TITLE
Deleting remote files is slow on Amazon cloud drive

### ISSUE THREAD

**Issue by hypertridion** [duplicati/duplicati#2408]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.52
**Operating System:** Windows 10
**Backend:** Amazon Cloud drive

### Bug description
"Deleting remote files" seems to be quite slow.. it takes long time. (Amazon cloud)

### Steps to reproduce

Here is our earlier chat on duplicati/Lobby:

> @hillopurkki_twitter 15:27
> "Deleting remote files" seems to be quite slow.. it takes long time. (okay, i'm trying this for 50 GB database). (Amazon cloud)
> @hillopurkki_twitter Can you see if the files are actually being deleted on AMZ? Do you have high CPU usage?
> @hillopurkki_twitter Mar 27 20:56
> Yes, files are actually being deleted...but slowly. Over 1000 files still left (upload volume size is 50 MB). Cpu usage is very low.
> @hillopurkki_twitter: Yes, I see the problem now. There is a 15 second delay, due to an issue with AMZCD not syncing correctly. So you get no more than 4 files/min with delete. Please add an issue, and I will try to fix it:

**Comment by warwickmm** [comment]
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
