### ISSUE TITLE
When I run duplicati service in Windows

### ISSUE THREAD

**Issue by Moad118** [duplicati/duplicati#2410]
Hi,
First of all thanks for your work!

When I run my service "Duplicati" in windows, that work but the service opens me duplicati windows at infinity, I have to stop the service to stop it. I'm on a 2008R2 server. I use the command  "Duplicati.WindowsService.exe install" to install the service.

 The problem occurs when I run the service with the administrator account with which I created the backup. When I put another account in the connection tab, it does not open the windows anymore but the cpu load increases.

Thanks

**Comment by kenkendk** [comment]
The service should not open any windows. The thing that opens the window is the TrayIcon, so I am guessing that the TrayIcon is not connecting to the service?

There is a brief description for connecting the two here:
https://www.duplicati.com/articles/Way-To-Make-A-Backup/#the-trayicon-package

**Comment by Moad118** [comment]
Thank you for your reply, 
I put the following command "Duplicati.GUI.TrayIcon.exe --no-hosted-server" then delete duplicati service and reinstall.
Now the service works without problem 
thanks
