### ISSUE TITLE
Incremental Backup: TypeReason log line seams wrong

### ISSUE THREAD

**Issue by ThomasMeschke** [duplicati/duplicati#2413]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 1.3.4.0 (German)
**Operating System:** Windows 
**Backend:** What does backend mean? 

### Bug description
After an incremental backup, the backup log seams to show some wrong information in the TypeReason line: 
- It states that a complete backup has been run, even though an incremental backup has been run
- The date of the next planned complete backup is missing, instead it shows the timespan indicator (3M in this case)

### Steps to reproduce
- Run a complete backup
- Run an incremental backup
- View the backup log

**Actual result:** 
The line (in german) reads: "Ein vollständiges Backup wird durchgeführt, weil das letzte vollständige Backup vom 24.03.2017 14:10:06 ist und das nächste Voll-Backup am 3M erfolgen soll."

**Expected result:** 
It should read: "Ein inkrementelles Backup wird durchgeführt, weil das letzte vollständige Backup vom 24.03.2017 14:10:06 ist und das nächste Voll-Backup am TT.MM.YYYY erfolgen soll."

### debug log
BackupType      : Incremental
TypeReason      : Ein vollständiges Backup wird durchgeführt, weil das letzte vollständige Backup vom 24.03.2017 14:10:06 ist und das nächste Voll-Backup am 3M erfolgen soll.
BeginTime       : 03/29/2017 20:13:13
EndTime         : 03/29/2017 20:27:07
Duration        : 00:13:54.3014679
DeletedFiles    : 0
DeletedFolders  : 348
ModifiedFiles   : 466
AddedFiles      : 3461
AddedFolders    : 70
ExaminedFiles   : 147297
OpenedFiles     : 4588
SizeOfModified  : 1290103061
SizeOfAdded     : 1785172887
SizeOfExamined  : 3100641335
Unprocessed     : 0
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 1011936914
BytesDownloaded : 592
RemoteCalls     : 5
NumberOfErrors  : 551
****************

**Comment by kenkendk** [comment]
Yes, that looks strange that it reports incremental and gives a "full" message.

I am no longer maintaining 1.3.x.
