### ISSUE TITLE
incremental backup takes several hours even with no changes

### ISSUE THREAD

**Issue by wjansenw** [duplicati/duplicati#2416]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.49
**Operating System:** Synology DSM6
**Backend:** webdav @ stackstorage.com

### Bug description
Running back-up job with no or few changes takes more then 5hours

### Steps to reproduce
- run the backup
- wait for several hours
- backup finishes indicating 0 or few changes

**Expected result:** Backup should finish in much less time.

### debug log

[profiling.txt](https://github.com/duplicati/duplicati/files/885765/profiling.txt)

**Comment by kenkendk** [comment]
Ok, that clearly shows the problem:

```
SELECT COUNT (*) FROM (SELECT DISTINCT "Block"."Hash", "Block"."Size" FROM "Block", "RemoteVolume" WHERE "RemoteVolume"."ID" = "Block"."VolumeID" AND "RemoteVolume"."State" NOT IN (?,?,?,?)) took 05:28:46.057
```

**Comment by wjansenw** [comment]
`no-backend-verification` reduced it to approx .5hr. Am I taking risks with that option?

**Comment by kenkendk** [comment]
It is slightly risky, as you may end up having the local and remote sets out-of-sync.
You can mitigate that problem by periodically running the "test" command (called "Verify" in the UI).

**Comment by saviodsouza** [comment]
Hello,

Some thing Similar here too Takes more than 1 hour for 97.17 GB
DB size 1 GB.

Config 
i5, 4GB RAM, 

> DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 8
ExaminedFiles: 197902
OpenedFiles: 14
AddedFiles: 6
SizeOfModifiedFiles: 1487679
SizeOfAddedFiles: 30919211
SizeOfExaminedFiles: 104340829078
SizeOfOpenedFiles: 32593770
NotProcessedFiles: 0
AddedFolders: 2
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults:
    DeletedFileCount: 0
    DownloadedFileCount: 0
    UploadedFileCount: 0
    DeletedFileSize: 0
    DownloadedFileSize: 0
    UploadedFileSize: 0
    Dryrun: False
    MainOperation: Compact
    ParsedResult: Success
    EndTime: 19-04-2017 05:31:52
    BeginTime: 19-04-2017 05:28:50
    Duration: 00:03:01.9394064
    BackendStatistics:
        RemoteCalls: 11
        BytesUploaded: 19232087
        BytesDownloaded: 126904926
        FilesUploaded: 3
        FilesDownloaded: 6
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 1
        KnownFileCount: 4392
        KnownFileSize: 112004922104
        LastBackupDate: 19-04-2017 10:00:08
        BackupListCount: 118
        TotalQuotaSpace: -1
        FreeQuotaSpace: -1
        AssignedQuotaSpace: -1
        ParsedResult: Success
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    ParsedResult: Success
    EndTime: 19-04-2017 05:31:52
    BeginTime: 19-04-2017 05:26:47
    Duration: 00:05:04.2964048
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170419T043008Z.dlist.zip.aes
        Value: [],
        Key: duplicati-20170202T040935Z.dlist.zip.aes
        Value: [],
        Key: duplicati-i346174956b7f40feb2ca65e9c73ac02b.dindex.zip.aes
        Value: [],
        Key: duplicati-i88f5b77b6e4844f787c7222af9edd4f4.dindex.zip.aes
        Value: [],
        Key: duplicati-b30e9f34e85b24abaa7693c45d0ce47d6.dblock.zip.aes
        Value: [],
...
    ]
    ParsedResult: Success
    EndTime: 19-04-2017 05:32:24
    BeginTime: 19-04-2017 05:32:18
    Duration: 00:00:06.3053606
ParsedResult: Success
EndTime: 19-04-2017 05:32:26
BeginTime: 19-04-2017 04:30:01
Duration: 01:02:24.3101623
Messages: [
    No remote filesets were deleted,
    Compacting not required
]
Warnings: []
Errors: []



Looks like the more the incremental count the slower, the same with file listing when restoring files.


Regards,
Savio D'souza

**Comment by wjansenw** [comment]
I ran a backup with reducing the number of backups to 1. After that finished (took a while because my local database had to be restored for another issue), I am now running the backup a 2nd time. Seems like this remote verification is again taking a lot of time, showing no progress...

Also, with the switch  `no-backend-verification` set to `true`

**Comment by Danstahr** [comment]
I removed the culprit select in ae314f85c03bbe2b5ff5f222ca53a1a1670df715.

**Comment by saviodsouza** [comment]
Purged out some unwanted files which reduced the backups to less 28GB, compacted to database which didn't make difference and now the  backup took little more then 30 minutes from previous more than 1 hour.

in addition File listing in restore now takes around 15 min for each folder expand compared to previous endless.

**Comment by wjansenw** [comment]
seems to be fixed here as well

Installed the latest canary build few days ago, and reconfigured everything as my configuration was gone in the gui (due to synology upgrade of DSM). 

Now, backup runs smoothly.

Thanks for providing the solution!!!
