### ISSUE TITLE
Moving backup set from hard drive to google drive

### ISSUE THREAD

**Issue by Athep** [duplicati/duplicati#2417]
I have made a backup to a hard drive. The whole backup was then uploaded to Google Drive. I want to continue the backup using Google Drive as the destination, but duplicati can’t access the folder and files. So I created a new folder with duplicati and tested the connection OK. I moved all files to this folder, but duplicat still does not see any of files. It’s like empty new folder.  

Any solution to this ?

**Comment by kenkendk** [comment]
This is a security feature for Google Drive. Duplicati can only see files that it has created itself, which prevents Duplicati for messing with your documents.

There are two ways to work around it.

1) Use the `Duplicati.CommandLine.BackendTool.exe` to upload the files, which uses the same identity as the main program.
2) Use the (Google Docs login)[https://duplicati-oauth-handler.appspot.com/?type=googledocs]  which will give Duplicati access to all your files.

The first option is "safer", but the second option is "easier". Let me know if that fixes the problem.

**Comment by Athep** [comment]
For option 1, I'm trying the LIST command to start with, but get error:

`Command failed: You need an AuthID, you can get it from: https://duplicati-oauth
-handler.appspot.com?type=googledrive`

Auth ID is working within the GUI. Connection test OK.

**Comment by Athep** [comment]
This is the first time I am using the command line tool. Got it to work now, could create folder. OK. 

But uploading does not work: 

C:\Program Files\Duplicati 2>Duplicati.CommandLine.BackendTool.exe PUT f:\test\abc.txt googledrive://backup_test --authid=*****

Command failed: The folder f:\test\abc.txt does not exist

The folder does exist.  What am I doing wrong ?

**Comment by kenkendk** [comment]
The tool is less flexible than it should be. It requires that you supply filenames only, and no paths.
You need to do something like:
```
F:
cd \test
"C:\Program Files\Duplicati 2\Duplicati.CommandLine.BackendTool.exe" PUT "googledrive://backup_test --authid=*****" abc.txt
```

**Comment by Athep** [comment]
Is wildcard for filenames supported ?

**Comment by Athep** [comment]
With your suggestion, I get the AuthID errror again:

`Command failed: You need an AuthID, you can get it from: https://duplicati-oauth-handler.appspot.com?type=googledrive`

**Comment by Athep** [comment]
I have tried everything now. It is impossible to upload. Either Auth error or folder does not exists error. Folder error even when supplying a single file name.

**Comment by kenkendk** [comment]
It does not support wildcards.

I can see that I made a small typo, the last line should have been:
```
"C:\Program Files\Duplicati 2\Duplicati.CommandLine.BackendTool.exe" PUT "googledrive://backup_test" --authid="*****" abc.txt
```

**Comment by kenkendk** [comment]
Alternative version:
```
"C:\Program Files\Duplicati 2\Duplicati.CommandLine.BackendTool.exe" PUT "googledrive://backup_test?authid=*****" abc.txt
```

**Comment by Athep** [comment]
No go:

Command failed: The requested folder does not exist

**Comment by kenkendk** [comment]
That error indicates that the `backup_test` folder does not exist on Google Drive.

Try:
```
"C:\Program Files\Duplicati 2\Duplicati.CommandLine.BackendTool.exe" CREATEFOLDER "googledrive://backup_test?authid=*****"
```

**Comment by Athep** [comment]
OK, I re-created a new folder and now it works. Single file uploaded OK. But trying to upload with wildcard (*.aes) gives error:

`Command failed: Illegal characters in path.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATT
RIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Duplicati.Library.Backend.GoogleDrive.GoogleDrive.Put(String remotename, String filename)
   at Duplicati.CommandLine.BackendTool.Program.RealMain(String[] _args)`

**Comment by Athep** [comment]
I've made a cmd-file to copy all files.  Working, but copying is slow of course ..

**Comment by Athep** [comment]
It worked just for a while:  

`Appdomain` unload error: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(MethodInfo method, String[] cmdargs, AutoUpdateStrategy defaultstrategy)

**Comment by kenkendk** [comment]
You can fix that by disabling the auto updater:

```
export AUTOUPDATER_Duplicati_SKIP_UPDATE=1
```

**Comment by Athep** [comment]
All files is now successfully uploaded. 

When starting a new backup at a place that have a slow internet connection, the only way is to do the initial backup to a hard drive and then move it to a location with a fast internet connection and upload the files to the destination. And then continue the daily backup from the “slow” place.

I think it it is important to have a back-end-tool that is easy to use for this purpose.

**Comment by kenkendk** [comment]
Normally you would use the storage provider tools (i.e. the web-upload with Google Drive), but in this case this does not work well due to the access limitation.

Feel free to register a new issue requesting that the tools are improved.
I have improved it slightly based on your feedback already, such that you can now use full paths.
Wildcard support would be the next thing to add I think.
