### ISSUE TITLE
Manage database vs db-path in options

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2418]
Hello

What is the difference between db-path and manage database?

Sounds stupid, but just wanted to know the difference.

Entering path in manage database is not saved in exported config file. What if the same path is put under db-path in options will that saved in exported config file ?

**Comment by kenkendk** [comment]
The option `--dbpath` is used by the commandline to point specifically to a database.

The GUI stores the path to the database, and always overrides the `--dbpath` even if you set it in the advanced options.

The "Manage database" is a way to change the path stored for the GUI, along with some basic maintenance operations.

The import/export will not use the database path, as it is assumed that the machine you import on is not the same as the one you exported from. If you set it manually in the file, it will be ignored on import.
If you need to manage the local database, you need to use the "Manage database" page after importing the configuration.

Let me know if this answers the question.

**Comment by saviodsouza** [comment]
Yes tested it out

Manage database path is reset on import.
