### ISSUE TITLE
Restore warning: invalid handle to path

### ISSUE THREAD

**Issue by SBoat** [duplicati/duplicati#2422]
I have:
- [X] searched open and closed issues for duplicates
----------------------------------------
**Version info**
Duplicati Version: 2.0.1.53
Operating System: MacOS 10.12.4 Sierra
Backend: MS OneDrive and Box Sync

**Question, not bug description**
I've performed successful restores from MS OneDrive and Box Sync to test that things work correctly. The file I'm backing up was encrypted prior to backup and again with Duplicati. The restores work properly; I can unencrypt the file and its contents are correct.

My question is that I get a warning that Duplicati was unable to patch the original file and that there was an invalid handle to the path.

This is not a problem since the restore worked but I was interested to understand why the warning.

**Steps to reproduce**
Restoring a single, encrypted file from cloud storage services.

**Actual result:** Receive warning
**Expected result:** No warning

**Comment by ts678** [comment]
> Actual result: Receive warning

Not reproducible now, restoring from OneDrive. My file wasn't encrypted, but I doubt it matters. I'm testing using Windows.

Does it work for you on some later version or current version?
