### ISSUE TITLE
Loki IOC gives Alert

### ISSUE THREAD

**Issue by Daigz** [duplicati/duplicati#2423]
When using Loki (https://github.com/Neo23x0/Loki) to scan for indicators of Comprimise I get the following:

[ALERT]
FILE: C:\Program Files\Duplicati 2\agsXMPP.dll SCORE: 100 TYPE: EXE SIZE: 516096
FIRST_BYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ
MD5: fee34da6f30a17e1fcc5a49fd0987169
SHA1: 69d945e8dcec321856da146f4623ba829f4df7c6
SHA256: 0259f40597e26703c77c228875e7ebc61a0758e043d65492ccb178592ec1f5d8 CREATED: Fri Feb 03 12:05:14 2017 MODIFIED: Fri Feb 03 12:05:14 2017 ACCESSED: Sat Feb 18 09:09:19 2017
REASON_1: Malware Hash TYPE: MD5 HASH: fee34da6f30a17e1fcc5a49fd0987169 SUBSCORE: 100 DESC: Operation Transparent Tribe https://www.proofpoint.com/sites/default/files/proofpoint-operation-transparent-

![loki-duplicati2](https://cloud.githubusercontent.com/assets/21195534/24835561/c1c54474-1d05-11e7-9047-855074a395e7.JPG)

**Comment by kenkendk** [comment]
Not sure why it flags that file, is it the file name or the contents?

It is an XMPP library used to send messages via XMPP if you have that configured.
It is possible that some malware has used the library as a communication foundation at some point, and that is why it is flagged.

**Comment by Daigz** [comment]
I have tried to ask, and you are probably right. Close this.
