### ISSUE TITLE
Local database grows too large?

### ISSUE THREAD

**Issue by jarmo** [duplicati/duplicati#2426]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.55_canary_2017-04-06
**Operating System:** Ubuntu 14.04 LTS
**Backend:** WebDAV

### Bug description
I've noticed that my local database has gotten quite large - 37GB already. Backup size itself is 250GB. Backups have been done daily at least for the last 6 months. Is it possible that VACUUM is not done after deleting rows in local database or why has it gotten so big in time?

**Comment by kenkendk** [comment]
Can you try to call `VACUUM` and see if it shrinks? (using `sqlite3`, http://sqlitebrowser.org/ or similar).

**Comment by jarmo** [comment]
I suspected that VACUUM will decrease the size of that database, but unfortunately it doesn't seem to have done any difference. Any other ideas why it has gotten that big?

**Comment by Danstahr** [comment]
Can you run sqlite_analyzer (http://www.sqlite.org/2017/sqlite-tools-win32-x86-3180000.zip) for the database and post the results?

**Comment by jarmo** [comment]
Sorry, cannot do this anymore since I ended up deleting database and rebuilding a new one from scratch, which takes now 2.6 GB. Closing this issue until it appears again.

**Comment by kuro68k** [comment]
I have a similar issue and was able to run sqlite_analyzer. My databases are only about 4GB each though. I have vacuumed them recently. Output attached.

[data.zip](https://github.com/duplicati/duplicati/files/7650744/data.zip)
