### ISSUE TITLE
Backup to Amazon S3 fails on first attempt

### ISSUE THREAD

**Issue by ajungar** [duplicati/duplicati#2433]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53
**Operating System:  Win 10**
**Backend: Amazon S3**

### Bug description
The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.
Did Delete and Repair

### Steps to reproduce
- Run Now

**Actual result:** Error message above.
**Expected result:** Make the first backup.

### debug log
<!-- posting a debug log helps the developers to fix your issue -
[bugreport.zip](https://github.com/duplicati/duplicati/files/921112/bugreport.zip)
->

**Comment by kenkendk** [comment]
This indicates that you are somehow connected to an existing database for the destination?

Are you using the GUI or the commandline? If you are using the GUI, you can delete the local database through the "Manage database ..." option.

**Comment by kenkendk** [comment]
Closing for lack of feedback
