### ISSUE TITLE
Suggestion: Continous intergration

### ISSUE THREAD

**Issue by damian123** [duplicati/duplicati#2435]
What about running continuous integration over the code, for example https://travis-ci.org/ ?

**Comment by Danstahr** [comment]
We already do: https://travis-ci.org/duplicati/duplicati among others. See the main readme for more links.

**Comment by kenkendk** [comment]
Yes, links are:
https://travis-ci.org/duplicati/duplicati
https://ci.appveyor.com/project/kenkendk/duplicati
