### ISSUE TITLE
computer name as part of title

### ISSUE THREAD

**Issue by pmarat-sqrt0** [duplicati/duplicati#2437]
Would you reconsider to add the computer name to the title element of the web gui.
I remember it was there in the old duplicati 2 interface.
---
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=44299565)](https://www.bountysource.com/issues/44299565-computer-name-as-part-of-title?utm_source=44299565&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Pectojin** [comment]
By "title element" I think you mean so that it shows up in the browser tab?

![image](https://user-images.githubusercontent.com/1561484/30515433-d8e51030-9b27-11e7-80f7-d888e8e852d8.png)

I created a pull request.
