### ISSUE TITLE
Frequent Upload Retries Needed to ACD

### ISSUE THREAD

**Issue by robdennehy** [duplicati/duplicati#2438]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53_experimental_2017-03-13
**Operating System: Linux Mint 18.1 x64**
**Backend: Amazon Cloud Drive**

### Bug description
Doing a large initial upload with 1GB file sizes. Today it is having to retry most uploads once before it works reliably on the second attempt, doubling upload time for the data. The same issue was not happening before on the same upload nor other backup sets that have uploaded recently. The backup continues, just slower.

### Steps to reproduce
- run backup
- watch live logs showing "warning" level.

**Actual result:** As bug description states. The error message it displays is always the same, except of course for the file name and date:

```
21 Apr 2017 15:36: Operation Put with file duplicati-b44a18da030f744de99d5609f7e4c6b72.dblock.zip.aes attempt 1 of 5 failed with message: Bad Request
{"ClassName":"System.Net.WebException","Message":"Bad Request","InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () <0x40648d80 + 0x0010b> in <filename unknown>:0 \n  at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () <0x40641d70 + 0x0016b> in <filename unknown>:0 \n  at Duplicati.Library.JSONWebHelper.GetResponse (Duplicati.Library.Utility.AsyncHttpRequest req, System.Object requestdata) <0x40757ab0 + 0x003fb> in <filename unknown>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233079,"Source":"Duplicati.Library.Utility","ExceptionMethod":null,"Data":null}
```

**Expected result:** This not to happen and to successfully save each file on first upload.

If it's a simple thing I can fix, or a temporary issue with ACD then great, but I can't tell myself from the error details. Please let me know if there is any more information I can supply to help solve the issue.

**Comment by shoeper** [comment]
What is your upload speed?

**Comment by ElRico** [comment]
This might be similiar or the same as #2297?

**Comment by robdennehy** [comment]
@shoeper My connection upload speed is about 18mbps, with Duplicati managing to upload a 1GB file in just over 10 mins.

@ElRico - I did see that one, but it didn't seem the same. This doesn't actually fail, it continues going just retrying many of the files at least once before the put operation succeeds. Some will work first time, others occasionally require two retries. Admittedly however, it looks like last night it might have failed with some of those messages described in #2297.

**Comment by robdennehy** [comment]
As a workaround, I tried changing the upload size to 900mb instead of 1024. I have not been getting this problem this morning, possibly as a result. It also seems to be preventing what I think may have been a memory leak possibly related to #2320.
Could the ACD backend not be happy with 1GB upload sizes?

**Comment by ElRico** [comment]
I don't think that it's the 1GB size specifically. I saw the same aborting
error with another backup set that is configured with a volume size of
500MB.

Am 24.04.2017 12:00 nachm. schrieb "robdennehy" <notifications@github.com>:

**Comment by robdennehy** [comment]
Indeed, I deleted the comment as seconds after I posted it I got another warning of a retry. It kept happening throughout yesterday. I am now trying it on 750mb, which is the volume size I used for another backup set that has been working without this issue.

**Comment by robdennehy** [comment]
Looking through the timings of the uploads to Amazon for the last several hours, it doesn't look like it's retried any today with the 750mb volume size.

**Comment by robdennehy** [comment]
Though it did have lots of retries overnight.

**Comment by warwickmm** [comment]
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
