### ISSUE TITLE
Option for mounting backup archive under windows/linux file system

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#244]
_From [telead...@gmail.com](https://code.google.com/u/105532666284975590557/) on August 07, 2010 22:17:13_

it's will great if under linux command line shell we can mount with fuse the duplicati archive under a directory.
I imagine you can make a racine with some dated directory for put inside the different increment as the way you prensent inside duplicati restore  explorer.
Eventually we can after share with samba or other and access from windows explorer.

Under windows it's less important since windows is only graphique and maybe harder to do since fuse does not exist.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=244_
##

**Comment by ltGuillaume** [comment]
Any news on this? Old request, but this would really be perfect!

**Comment by ajthemacboy** [comment]
I second this request, I could see this as a very great alternative to rclone, acd_cli, or similar.

**Comment by NoLooseEnds** [comment]
Ditto, would be awesome.

**Comment by warwickmm** [comment]
Closing this in favor of #3081, which has more discussion regarding implementation details.
