### ISSUE TITLE
Include/Exclude filters not available to run-script

### ISSUE THREAD

**Issue by nsrussell** [duplicati/duplicati#2440]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53
**Operating System:** Windows 10 64-bit
**Backend:** Any

### Bug description
Include/Exclude filters not available to run-script

### Steps to reproduce
- Create a backup job and add an exclude filter, eg -[.AppData.]
- Add a run-script-before batch file that redirects 'set' to a file, eg set >C:\Temp\debug.log
- Execute the job

**Actual result:** Gets lots of environment variables including many DUPLICATI__* ones, however not DUPLICATI__FILTER as per the run-script-example or any other variable containing the exclude filter.
**Expected result:** A DUPLICATI__FILTER environment variable containing "-[.AppData.]" for the example filter mentioned above.

**Comment by kenkendk** [comment]
Oh, that is an omission on my part :/

It also does not allow you to modify the filters.

The output sent to the script should be added here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/RunScript.cs#L185

And the readback here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/RunScript.cs#L267

We might want to do something like the parsing done from the parameters file (prependfilter and appendfilter):
https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/Program.cs#L349

**Comment by IGTHORN** [comment]
Hi @kenkendk 

I think I have solved this issue. However, when performing a restore operation from the GUI, I get an error saying that filters are not supported. It seems that during restore, it also runs the startup script and reads in the supplied filters. Should I prepare a pull request so you can see the issue? I think that another change would be need to either not add filters from the startup script during restore; or, not run the startup script at all during restore (though that would change existing behaviour and is probably less desirable).

**Comment by nsrussell** [comment]
Getting an error when setting the filter for a restore operation would seem to be correct behaviour to me. The run script should be using the DUPLICATI__OPERATIONNAME environment variable to determine what to do and only setting filters when this is "Backup".

**Comment by kenkendk** [comment]
This is closed with e88afa4
