### ISSUE TITLE
No files display when try to restore from local external drive to local internal drive

### ISSUE THREAD

**Issue by vfulco** [duplicati/duplicati#2441]
I have:
- [X ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.X
**Operating System: Ubuntu 16.04
**Backend:**

### Bug description
Backup daily from local machine to external USB drive, no errors occur.  Can see dlist.zip files when I use file manager to access the drive.  Using restore feature of duplicati, can get file manager to folder with backup files but when click on, date of backup displays and no files are shown.  Tried searching for *dlist.zip in app and nothing surfaces. No encryption was used.

### Steps to reproduce
-Go to restore/choose drive/folder
- Choose date of backup from field of choices
- No files

**Actual result:** App finds no files, search (within Duplicati) finds no files
**Expected result:** See backup files and launch restore

**Comment by kenkendk** [comment]
What is the size of the `dlist.zip` files? Are the perhaps empty?

**Comment by kenkendk** [comment]
Closing for lack of feedback
