### ISSUE TITLE
Backups with large file count slow due to SQLite query?

### ISSUE THREAD

**Issue by sjonez** [duplicati/duplicati#2442]
### Version info

**Duplicati Version:** 2.0.1.56_canary_2017-04-21
**Operating System:** Windows 7 x64
**Backend:** Amazon Cloud Drive

### Bug description
I've found an issue with performing database backups on a large amount of files (>50,000) where the SQLite query that's performed on each file during the backup to retrieve its modified date starts going slower and slower as the backup progresses.

I found the problematic query to be this from LocalBackupDatabase.cs

m_selectfilelastmodifiedCommand.CommandText = @"SELECT ""File"".""ID"", ""FilesetEntry"".""LastModified"" FROM ""File"", ""FilesetEntry"" WHERE ""Path"" = ? AND ""File"".""ID"" = ""FilesetEntry"".""FileID"" AND ""FilesetEntry"".""FilesetID"" = ? LIMIT 1";

For example, running this against a specific file on a local database that has around 100,000 file entries in it results in:

"1 rows returned in 225ms"

But in random testing I've seen this go as high as 700ms. This kind of delay between *each individual file* slows my backup to a crawl (e.g. the 225ms delay on its own on 100,000 files is over 6 hours!) 

If I run a "explain query plan" on that select statement this is the reason:

"0"	"0"	"1"	"SEARCH TABLE FilesetEntry_Original USING PRIMARY KEY (FilesetID=?)"
"0"	"1"	"0"	"SEARCH TABLE File USING INTEGER PRIMARY KEY (rowid=?)"

The query appears to be searching both tables via the primary keys, which I guess is pretty slow on a large table. Oddly, if you just change that last operator on the FileSetID to a LIKE instead of =, so the query becomes:

m_selectfilelastmodifiedCommand.CommandText = @"SELECT ""File"".""ID"", ""FilesetEntry"".""LastModified"" FROM ""File"", ""FilesetEntry"" WHERE ""Path"" = ? AND ""File"".""ID"" = ""FilesetEntry"".""FileID"" AND ""FilesetEntry"".""FilesetID"" LIKE ? LIMIT 1";

The query plan then becomes:

"0"	"0"	"0"	"SEARCH TABLE File USING COVERING INDEX FilePath (Path=?)"
"0"	"1"	"1"	"SEARCH TABLE FilesetEntry_Original USING INDEX FilesetentryFileIdIndex (FileID=?)"

And now, as we're using our indexes even on a huge table the lookup takes just 1ms at most.

I also managed to "fix" this without the code change by recreating the FilesetEntry table but without a primary key, e.g.

CREATE TABLE `FilesetEntry` ( `FilesetID` INTEGER NOT NULL, `FileID` INTEGER NOT NULL, `Lastmodified` INTEGER )

This forces the original query to also use the index and results in lookups of 0-1ms, a pretty huge improvement on very large backups.

This could just be an issue on my system I guess, but this is what I've found with 3 of my backups (one of which has almost 600,000 files so really needs this improvement!)

Thanks!

**Comment by airbillion** [comment]
Can this patch be implemented in the next update?

I have noticed very slow backups also and hope that this might alleviate the issue!

Thanks!

**Comment by sjonez** [comment]
The backup of my NAS (over samba) with over 600,000 files reduced from 2 days to 9 hours after making this change (very few, if any, actual changed files to backup - slowness is just the scanning)

**Comment by airbillion** [comment]
How did you fix your installation of Duplicati?

Can you post how to implement this?

**Comment by sjonez** [comment]
Your slow backups are not necessarily caused by this specific issue so your mileage may vary, but if you have a large number of files my guess is this will certainly help...

The easiest way is to modify your backup database using something like [SQLite Browser](http://sqlitebrowser.org/)

1. In Duplicati, go to your backup job. Expand it and click Advanced -> Database
2. Make a note of the `Local Database Path`
3. It might be best to shut duplicati down at this point
4. Create a copy of the file from step 2 (just in case something goes wrong)
5. Open SQLite Browser and click `Open Database`
6. Browse to and open the file you identified in step 2
7. Click `Execute SQL` and paste in the following:

`CREATE TABLE FilesetEntry2 ( FilesetID INTEGER NOT NULL, FileID INTEGER NOT NULL, Lastmodified INTEGER );
INSERT INTO FilesetEntry2 SELECT * FROM FilesetEntry;
DROP TABLE FilesetEntry;
ALTER TABLE FilesetEntry2 RENAME TO FilesetEntry;
CREATE INDEX "FilesetentryFileIdIndex" on "FilesetEntry" ("FileID");`

8. Click the play button or press F5 to execute (This might take a while if your database is large)
9. When it finishes it should say something like `Query executed successfully` in the bottom pane
10. Click `Write Changes` to save the changes and then close SQLite Browser

**If you ever recreate your database (e.g. via the Delete and Repair option in Duplicati) you will have to make this change again.**

**Comment by airbillion** [comment]
Thanks!  I will give this a test and see if it helps...

**Comment by kenkendk** [comment]
@sjonez Is your take that `CONSTRAINT "FilesetEntry_PK_FilesetIdFileId" PRIMARY KEY ("FilesetID", "FileID")` is causing this dual-index issue?

For the query plan it seems that the `LIKE` trick makes it start with `File` instead of `FilesetEntry`, it can do this lookup into `File` fast (with the covering index) and the lookup into `FilesetEntry` is also indexed.

For the slow one, it is using the `PRIMARY KEY` which covers `(FilesetID, FileID)` so maybe there are too many hits in this table, causing the slowdown when joining with the `File` table.

Anyways, it seems a bit of a hack to use the `LIKE` operator, so can you try something like this to see if it forces the query planner to use the `File` table index first:

```
SELECT "A"."ID", "B"."LastModified" FROM
    (SELECT "ID" FROM "File" WHERE "Path" = ?) A,
    "FilesetEntry" B
WHERE
  "A"."ID" = "B"."FileID"
  AND
  "B"."FilesetID" = ?
```

Alternatively:

```
SELECT "A"."ID", "B"."LastModified" FROM
    (SELECT "ID" FROM "File" WHERE "Path" = ?) A,
    (SELECT "LastModified", "FileID" FROM "FilesetEntry" WHERE "FilesetID" = ?) B
WHERE
  "A"."ID" = "B"."FileID"
```

**Comment by sjonez** [comment]
Ah, I never even realised the order of the tables had been switched in the faster query plan, that now makes much more sense.

I tried both of your new queries with the same slow results. I think SQLite is optimizing out the query to what it believes to be the best method regardless of how you structure it. The query plan for both of those queries is the same:

"0"	"0"	"1"	"SEARCH TABLE FilesetEntry USING PRIMARY KEY (FilesetID=?)"
"0"	"1"	"0"	"SEARCH TABLE File USING INTEGER PRIMARY KEY (rowid=?)"

I found that if you add a LIMIT to the File lookup you again get a fast response, e.g. either:

`SELECT "A"."ID", "B"."LastModified" FROM
    (SELECT "ID" FROM "File" WHERE "Path" = ? LIMIT 1) A,
    "FilesetEntry" B
WHERE
  "A"."ID" = "B"."FileID"
  AND
  "B"."FilesetID" = ?`

or

`SELECT "A"."ID", "B"."LastModified" FROM
    (SELECT "ID" FROM "File" WHERE "Path" = ? LIMIT 1) A,
    (SELECT "LastModified", "FileID" FROM "FilesetEntry" WHERE "FilesetID" = ?) B
WHERE
  "A"."ID" = "B"."FileID"`

both result in a query plan of:

"1"	"0"	"0"	"SEARCH TABLE File USING COVERING INDEX FilePath (Path=?)"
"0"	"0"	"0"	"SCAN SUBQUERY 1 AS A"
"0"	"1"	"1"	"SEARCH TABLE FilesetEntry AS B USING PRIMARY KEY (FilesetID=? AND FileID=?)"

So the workarounds so far are either:

1. Use LIKE statement on original query
2. Add LIMIT to alternative queries
3. Recreate FilesetEntry table without primary key

**Comment by kenkendk** [comment]
Ok, I opted for (2) (using `LIMIT 1` as it really is supposed to only return one row)

**Comment by kenkendk** [comment]
I was a bit too fast there, the `File` table returns multiple rows, so the `LIMIT 1` solution does not work.
The `LIKE` workaround does not work with case-insensitive filesystems, so that is out too.
And I need the primary key to enforce that no duplicates are created.

According to point 6.3 in the SQLite guide, the hint tot use is "CROSS JOIN":
https://www.sqlite.org/optoverview.html

Can you try this and see what speeds you get:
```
SELECT 
    "A"."ID", "B"."LastModified" 
FROM 
    (SELECT "ID" FROM "File" WHERE "Path" = ?) A 
    CROSS JOIN
    "FilesetEntry" B
WHERE 
    "A"."ID" = "B"."FileID"
    AND
    "B"."FilesetID" = ?
```

This gives the correct query plan on my machine.

**Comment by kenkendk** [comment]
I merged in the CROSS JOIN query into the latest canary build.

Reopen the issue if it is not fixed.

**Comment by sjonez** [comment]
Yes that does the trick, rows return in 1ms regardless of the size of the File table when using the CROSS JOIN
