### ISSUE TITLE
Socket read operation has timed out after -1 milliseconds

### ISSUE THREAD

**Issue by datalandsoftware** [duplicati/duplicati#2445]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** Various (issue is present for months, regularly updated)
**Operating System:** Windows 10
**Backend:** CentOS 6.9, SFTP (SSH)

### Bug description
Since several months ago, backup attempts often (not always) fail at the end with message `Failed while executing "Backup" with id: 1`, with error `Socket read operation has timed out after -1 milliseconds`. I have task scheduled daily, and roughly, only 10-15% attempts succeed.

I know the report is vague, but that's what I have for now. Hopefully someone will have an idea what I could try to pinpoint a problem.

### Steps to reproduce
I couldn't figure out any pattern. It happens with manual run too.

**Actual result:** Even everything seems to be running correctly until the very end, backup fails and I'm unable to restore from the dates in question.

### debug log
```
Renci.SshNet.Common.SshOperationTimeoutException: Socket read operation has timed out after -1 milliseconds.
 at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout) at Renci.SshNet.Channels.Channel.Close(Boolean wait)
 at Renci.SshNet.Channels.ChannelSession.Close(Boolean wait)
 at Renci.SshNet.SubsystemSession.Disconnect()
 at Renci.SshNet.SftpClient.OnDisconnecting()
 at Renci.SshNet.BaseClient.Disconnect()
 at Renci.SshNet.BaseClient.Dispose(Boolean disposing)
 at Renci.SshNet.SftpClient.Dispose(Boolean disposing)
 at Duplicati.Library.Backend.SSHv2.Dispose()
 at Duplicati.Library.Main.BackendManager.Dispose()
 at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
 at Duplicati.Library.Main.Controller.<Backup>c__AnonStorey0.<>m__0(BackupResults result)
 at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
 at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
 at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by fink42** [comment]
I'm having the exact same problem. Also with a SFTP-backend.
One client might show this error, while another client successfully completes a backup task to the same backend.

**Comment by vradmilovic** [comment]
Some additional information that could be important. Just now, I ran backup manually and watched what's happening. The process went normally, it switched to "Verifying", progress bar went to 100% (at least visually), then after 3-4 minutes, progress bar reported "Finished!", then another 1-2 min pause and then the error. Live log just shows "Fatal error", no other warnings or information.

Seems like backup works, but it doesn't "mark" it as success from some reason. But as I said earlier, I cannot restore from this backup (it just shows me those few that were completed correctly), so the consequences are not just cosmetic.

**Comment by fink42** [comment]
I discovered that by enabling "no-backend-verification" the backup will complete.
Possibly because it skips the verification part...

**Comment by vradmilovic** [comment]
Thanks, I'll try that. But it's just a temporary solution, as skipping verification doesn't feel particularly right. :)

**Comment by vradmilovic** [comment]
Unfortunately, "no-backend-verification" make no difference in my case, so I'm back to using local disk and upload files by other means.

More than a month since issue is opened, I fear that this bug will never be fixed. :/

**Comment by Palten69** [comment]
Hi, I have also this problem running Bitvise as a remote SSH server, the backup verifies and says Finished in the progress bar and after about 2 min I receive "Socket read operation has timed out after -1 milliseconds". The backup says "Last successful run: Never" although it seems to finish.
I can restore files from the backup with no problem.
Backup to local usb drive no problem.

**Comment by Luto73** [comment]
I seem to have a similar problem. I am using Strato HiDrive as SFTP-Server and one of my backups (I have two) fails with the following error:
```
19. Mrz. 2018 20:09: Message
Fatal error
Renci.SshNet.Common.SshOperationTimeoutException: Socket read operation has timed out after -1 milliseconds.
   bei Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   bei Renci.SshNet.Channels.Channel.Close(Boolean wait)
   bei Renci.SshNet.Channels.ChannelSession.Close(Boolean wait)
   bei Renci.SshNet.SubsystemSession.Disconnect()
   bei Renci.SshNet.SftpClient.OnDisconnecting()
   bei Renci.SshNet.BaseClient.Disconnect()
   bei Renci.SshNet.BaseClient.Dispose(Boolean disposing)
   bei Renci.SshNet.SftpClient.Dispose(Boolean disposing)
   bei Duplicati.Library.Backend.SSHv2.Dispose()
   bei Duplicati.Library.Main.BackendManager.Dispose()
   bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
``
I am using the public beta (Duplicati - 2.0.2.1_beta_2017-08-01) on Windows 10 Pro 1709 Build 16299.192

The other backup with almost same parameter but another fileset runs flawless?!

**Comment by ts678** [comment]
[Added extra options to SSH that exposes the operation timeout and keep-alive properties.](https://github.com/duplicati/duplicati/commit/81d5b77c8ee9e447a18652cb036c6b942676371e) was added in [2.0.2.2_canary_2017-08-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.2.2-2.0.2.2_canary_2017-08-30). That includes [ssh-operation-timeout](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#sftp-ssh), and maybe a default fix for this issue?

The underlying [SSH.NET library](https://github.com/sshnet/SSH.NET) has probably been upgraded to improved versions several times as well...

Regardless, it's been quiet on this issue lately. Is anyone still seeing this strange -1 milliseconds timeout?
