### ISSUE TITLE
Failed to process path: F:\*\****

### ISSUE THREAD

**Issue by naverpeec** [duplicati/duplicati#2446]
I have:
- [ x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:2.0.1.55canary** 
**Operating System:windows 7 64 bit**
**Backend:**

### Bug description
Failed to process path: F:\HPB_SHALLOW_VELMOD_20FEB_2017\01_INPUT\01_WELLS\
System.NullReferenceException: Object reference not set to an instance of an object. at Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock(String hash, Byte[] data, Int32 offset, Int32 size, CompressionHint hint) at Duplicati.Library.Main.Operation.BackupHandler.AddBlockToOutput(BackendManager backend, String key, Byte[] data, Int32 offset, Int32 len, CompressionHint hint, Boolean isBlocklistData)
![error](https://cloud.githubusercontent.com/assets/28087114/25476337/80888268-2b57-11e7-82f6-a5abef0aa1dc.jpg)

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### debug log

![error](https://cloud.githubusercontent.com/assets/28087114/25476519/0b79d11a-2b58-11e7-9cdb-8abdb88162ee.jpg)

**Comment by warwickmm** [comment]
Unfortunately, there's not enough information here for us to reproduce this issue.  I'm assuming the root cause of this may be already fixed, or is captured in other issues.  If there's more information available specific to this issue, please feel free to update and re-open.
