### ISSUE TITLE
Duplicati cannot access files with a special character in the path

### ISSUE THREAD

**Issue by fanis** [duplicati/duplicati#2447]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53_experimental_2017-03-13
**Operating System:** Windows 8.1 X64
**Backend:** Windows Server 2003 over NFS

### Bug description
Duplicati cannot access files with some special characters in the path. Examples:

`C:\cygwin64\home\fanis\.nvm\test\slow\Running nvm current should display current nvm environment`
`C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm deactivate should unset the nvm environment variables`

The codepoint being used is [U+F022](http://www.charbase.com/f022-unicode-invalid-character) 

### Steps to reproduce
- Install NodeJS/NVM within Cygwin on Windows
- Attempt a backup in the Cygwin directory via Dupliciti
- See the warnings appearing

**Actual result:** Some files with special characters in the path don't get processed
**Expected result:** All files should have gotten processed

### Screenshots

Files appearing in Windows Explorer with the special characters
![2017-04-28 13_03_42-c__cygwin64_home_fanis_ nvm_test_slow_nvm run](https://cloud.githubusercontent.com/assets/562545/25524420/2e7c3728-2c13-11e7-88bc-b93598e38dba.jpg)

### debug log

Log of backup:

Warnings: [ Error reported while accessing file: C:\cygwin64\home\fanis\.nvm\test\slow\Running nvm current should display current nvm environment. => Could not find file 'C:\cygwin64\home\fanis\.nvm\test\slow\Running nvm current should display current nvm environment'., Error reported while accessing file: C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm alias should create a file in the alias directory. => Could not find file 'C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm alias should create a file in the alias directory'., Error reported while accessing file: C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm current should display current nvm environment. => Could not find file 'C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm current should display current nvm environment'., Error reported while accessing file: C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm deactivate should unset the nvm environment variables. => Could not find file 'C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm deactivate should unset the nvm environment variables'., Error reported while accessing file: C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm unalias should remove the alias file. => Could not find file 'C:\cygwin64\home\fanis\.nvm\test\fast\Running nvm unalias should remove the alias file'., ... ] 

Also:

Error reported while accessing file: C:\cygwin64\home\fanis\.nvm\test\fast\Listing paths\Running nvm which 0.0.2 should display only version 0.0.2.
System.IO.FileNotFoundException: Could not find file 'C:\cygwin64\home\fanis\.nvm\test\fast\Listing paths\Running nvm which 0.0.2 should display only version 0.0.2'.

File name: 'C:\cygwin64\home\fanis\.nvm\test\fast\Listing paths\Running nvm which 0.0.2 should display only version 0.0.2'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Duplicati.Library.Snapshots.SystemIOWindows.GetFileAttributes(String path)
   at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>c__Iterator0.MoveNext()

**Comment by dferreyra** [comment]
I want to report that I tried a simple backup and restore of a file, `abcxyz.txt`, containing the same Unicode code point mentioned in this ticket and both operations were successful for me.  My details:

## Environment info


- **Duplicati version**: Duplicati 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10
- **Backend**: Local folder or drive

**Comment by warwickmm** [comment]
Thanks @dferreyra.  I'm going to assume this has been fixed then.  If not, please feel free to re-open this.
