### ISSUE TITLE
can't send mail

### ISSUE THREAD

**Issue by mmiat** [duplicati/duplicati#2448]
I can't send mail from duplicati, I suppose because certificate is not valid
I've tried to set accept-any-ssl-certificate but nothing changes
how can I check what's the problem?
I've setted:
smtp://mail.mydomain.com:587/?starttls=when-available
send-mail-username and send-mail-password

**Comment by saviodsouza** [comment]
Try ....starttls=always

**Comment by mmiat** [comment]
mmm it seems that with "when-available" it works but is very slow to send, with "always" it's faster
however, my fault was accept-any-ssl-certificate not checked
thanks
