### ISSUE TITLE
Mysterious change of backup config (ftp user2 is changed to a formerly used user1)

### ISSUE THREAD

**Issue by joostieLikesBackingup** [duplicati/duplicati#2450]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 1.3.4.0
**Operating System:** Windows 7 Starter 32-bit
**Backend:** ?

### Bug description
I'm using FTP upload for backup with Duplicati. First I set up a trial backup config, using _user1_ to log on my FTP server. After I checked that it works fine I deleted this try-out backup config and started to set up different backup configs (in total 7 different backup are defined, e.g. separate backups for Documents, Pictures, Music etc. to spread backup load over several week days). For these backups I used _user2_ to log in on my FTP server into a different user directory (of _user2_). Everything works like a charm, in the beginning....

After a couple of days I checked if everything works fine and I find out that one of the 7 backup definitions has undergone a spontaneous change of settings:

1. the directories be backed-up has changed to a different one (e.g. in the backup for Photos now Application Data is backed up, although initially it was defined that Photo directory should be backed up)

2. instead of _user2_ now the FTP login settings have changed to _user1_ (the one that was only used for the initial trial)

3. the directory on the FTP server, to which the backup is to be uploaded, has also changed to the one used during the trial run.

Very miraculous!

I changed this spontaneously redefined backup to the intended configuration and then after some time the same spontaneous change happened again. After that I completely removed all existing backup definitions in the GUI and set up the whole set of backups again from scratch (also removing the backup files on the FTP server by hand).

Again after a couple of days one of the backup definitions has undergone the same changes as described above.

Obviously somewhere hidden the old FTP login data is still present (although the backup using these has been deleted) and due to a bug or a corrupt database  this FTP data is used for a newly setup backup (and not the first time after the backup is defined but possibly at the second time that the particular backup is run).

**Comment by kenkendk** [comment]
Wow, I have no good explanation for this :/.

We are no longer maintaining 1.3.x, so I am closing the issue though.

**Comment by joostieLikesBackingup** [comment]
Hi Kenneth,
Pity that you have no fix for this.

Maybe you can give me a hint how to completely remove a user's duplicati settings so that I can start over again with a "virgin" setup. I recon then the issue I've encountered cannot take place anymore, because there are no previous settings that can interfere with present backup defs.

I would just delete any duplicati folder in the Application Data folders. Is that the right procedure for a fresh start?

Thanks
Joost
