### ISSUE TITLE
Zip archive appears to have a broken Central Record Header

### ISSUE THREAD

**Issue by mmiat** [duplicati/duplicati#2453]
my last backup has this warnings:

> Zip archive appears to have a broken Central Record Header, switching to stream mode => Could not find Zip file Directory at the end of the file.  File may be corrupted.,
    Zip archive appears to have broken records, returning the 1290 records that could be recovered => Unable to read beyond the end of the stream.,
    Zip archive appears to have a broken Central Record Header, switching to stream mode => Could not find Zip file Directory at the end of the file.  File may be corrupted.,
    Zip archive appears to have broken records, returning the 1227 records that could be recovered => Unable to read beyond the end of the stream.

**Comment by kenkendk** [comment]
This happens if the files are larger than 4GiB: https://github.com/duplicati/duplicati/issues/1877

The problem is fixed in the latest canary, but the written files are damaged.
It appears that in your case, the fallback code was not able to recover the contents either.

**Comment by mmiat** [comment]
do you intend the source files? because I've configured duplicati to make zip file of 1GB
in my remote folder all files are max 1GB

**Comment by kenkendk** [comment]
No, I mean the destination file. If the `...dblock.zip` file is larger than 4GiB the error occurs.
I have not heard of this happening with zip files smaller than 4GiB.

**Comment by mmiat** [comment]
ok with v59
