### ISSUE TITLE
Tray Icon: Resume/Pause w/o function

### ISSUE THREAD

**Issue by telemaxx** [duplicati/duplicati#2454]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info
2.0.1.56_canary_2017-04-21

### Bug description
I configured duplicati to pause for 5min. after start.
When i try to start duplicati direct from the Tray Icon, nothing happend.

### Steps to reproduce
Right click on the tray icon and select "resume"
If i click on "open" duplicati opens correct in the browser. Here i can start and stop.

**Actual result:** nothing, icon symbol does not change
**Expected result:** Icon change to Pause Symbol and duplicati pauses.

### Screenshots
not  neccercary

**Comment by telemaxx** [comment]
Win7/64. Firefox last Version.

**Comment by kenkendk** [comment]
Do you see high CPU usage as well ?
If so, I think this is related to #1276

**Comment by telemaxx** [comment]
no, cpu is 0%
Tray Icon is working, green when backup is running. black when idle.

only the pause/resume function is not working.

**Comment by telemaxx** [comment]
With 2.0.1.60_canary_2017-05-23 the bug is fixed.
Can be closed.
Thanks.
