### ISSUE TITLE
Add option to skip backup on battery power

### ISSUE THREAD

**Issue by mdekstrand** [duplicati/duplicati#2464]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.53
**Operating System:** Windows
**Backend:** WebDAV

### Bug description
For laptops, it would be useful there could be an option to have Duplicati interact with power status, and only start running if the computer is plugged in.

### Steps to reproduce
- create a backup
- leave laptop unplugged

**Actual result:** The backup runs, and uses more power!

**Expected result:** The backup does not run; once the machine is plugged back in, the backup runs like a skipped backup.

**Note:** I don't know that 'wait for AC power' should be the default, but it'd be nice to have it as an option.

**Comment by benjamindaines** [comment]
Would like to see this on Linux too.  +1

**Comment by tiagoboldt** [comment]
@benjamindaines implementation should apply to all OSs.

**Comment by warwickmm** [comment]
This duplicates #2666.  I'm going to close this issue as there is more discussion in #2666.  Note that the hooks to detect the power supply source have been implemented (Linux and Windows in pull request #2785, Mac in 7ccd05348e), but they are not being used yet.
