### ISSUE TITLE
Duplicati backup job fills hard drive with "dup-...." files in C:\Windows\Temp folder 

### ISSUE THREAD

**Issue by Stackable1** [duplicati/duplicati#2465]
I have:
[X ] searched open and closed issues for duplicates

----------------------------------------

### Version info
2.0.1.53_experimental_2017-03-13
**Duplicati Version: 2.0.1.53
**Operating System:  Windows 2008 R2 x64
**Backend:  Western Digital  My Cloud EX2 NAS

### Bug description
Each time a Scheduled job runs to back up a few folders on the Windows server to a WD NAS the job is successful and I can restore files from the NAS however the Windows Servers hard drive in C:\Windows\Temp has a bunch of files named similar to this:  dup-ef93005f-89a0-45ea-a5f7-0c1ad613d5f4  that never go away, after 3 or 4 runs of the backup job they fill the hard drive.   They don't seem to be needed as I can delete them, at least the ones that are not in use by Duplicati and still restore files.   Why does it do this?  Is there a way to set Duplicati to clean up after each run so the drive is not filled with these files?    

Also it may be related that even thought the backups are successful  I get this error each run: 
Error while running Terrahomes SRV Backup  
Unknown header:  362831837  

### Steps to reproduce
- clear the C:\Windows\Temp file of all files 
- let the Scheduled backup jobs run or run manually
-  happens every time after 3 or 4 scheduled backups the hard drive is fulll of files with no extention that all start with dup-  and a bunch of what looks like hex code. 

**Actual result: Hard drive fills up if the files in the C:\Windows\Temp folder created by Duplicati backup then fails next run as there is no space left on the hard drive. 
**Expected result: Duplicati 2 should clean up these files and all temp files written to the hard drive after each run. 

### Screenshots
Before job runs before a backup job runs - there are a few "dup- " files and logs that are in use and can't be deleted but they are like 1 KB unless I reboot then I can delete them all pretty much.
![image](https://cloud.githubusercontent.com/assets/25444169/25815103/a199c694-33d4-11e7-97ab-139d2b10fbba.png)

After one run that I kicked off manually there is now more dup-... file and one of them is quite large 32,063,845 KB  this file will not automatically go away and each time the job is run it will add another until the drive is full.  
![image](https://cloud.githubusercontent.com/assets/25444169/25817190/6d65af9e-33db-11e7-9a81-30a1d49a6593.png)
I got the same error as described above here is the screen shot: 
![image](https://cloud.githubusercontent.com/assets/25444169/25817253/a1265b58-33db-11e7-849a-3f7c55b234a5.png)

### debug log
<I would like to provide you with the Debug Log but I have no idea where to find it or how to generate it, little help?

**Comment by WalidLej** [comment]
I'm excecuting Duplicati - 2.0.1.53_experimental_2017-03-13
I got these errors after update of May, 2017 Security and Quality Rollup for .NET Framework 3.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2 on Windows 7 and Server 2008 R2 for x64 (KB4019112)

**Comment by kenkendk** [comment]
@Stackable1 Does it work if you update to the canary build?
https://github.com/duplicati/duplicati/releases

I have a similar report from another user (#2415) but I have not found the reason.

**Comment by richardhughes260** [comment]
I am having the identical issue with my MAC running Mavericks. The drive filled to 100%, I quit duplicati and deleted the file, got back down to 88% then started again, stopped it when it went up to 95%. I deleted the file, but the space did not report back as free.

**Comment by jonocodes** [comment]
I am also getting this on version 2.0.3.6-1 in Linux. No is larget then 1GB.

**Comment by Kasheen** [comment]
I've also just noticed this issue (temp files mounting up). I'm not certain when this started, but it could have been a couple of weeks ago, I changed storage provider from Hubic to Stack (Webdav). Not sure if that has something to do with it.

I've updated to 2.0.37 and manually deleted the files (wish I had checked the file dates before I had done that now). I've also set the `tempdir` duplicati variable so that these large files hopefully aren't being written to SSD anymore.

I'll keep an eye on it. Any diagnostic logs that I can post that would be useful?

**Comment by Vaear** [comment]
I am also experiencing the same issue using "Duplicati - 2.0.3.7_canary_2018-06-17". My tmp directory on Debian is filling up to enormous sizes, with a huge amount of dup-* files. Resulting in"{"ClassName":"System.IO.IOException","Message":"Disk full. Path /tmp/dup-53b"

**Comment by warwickmm** [comment]
A [fix](https://github.com/duplicati/duplicati/commit/be6093b7a61eca8152cb4babcc61011461be66fb) was implemented in version 2.0.3.8.  If someone finds that this issue has not been resolved, we can re-open this.
