### ISSUE TITLE
Unable to restore backups

### ISSUE THREAD

**Issue by aflemos** [duplicati/duplicati#2469]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.56_canary_2017-04-21
**Operating System:** Windows Server Standard 2012
**Backend:**

### Bug description
Duplicati performs the backup with no errors but we are unable to restore any data from it.
When we select the backup to restore from, we get an error popup with the message:
 
Failed to fetch path information: The index was out of range. Must be non-negative and less than collection size. Parameter name: startIndex

It doesnt allow us to search the backup repository for any files or folders.

### Steps to reproduce
Click the Restore menu.
Select any repository location/type and click next.

**Actual result:** We get the error: Failed to fetch path information: The index was out of range. Must be non-negative and less than collection size. Parameter name: **startIndex**

**Expected result:** We should be able to choose from the backups we have and select/search for data to recover.

### Screenshots
![duplicatierror1](https://cloud.githubusercontent.com/assets/28451576/25895874/aa1cf380-3579-11e7-88f6-840cf6c1e5fc.PNG)

### debug log
May 10, 2017 12:02 PM: Failed while executing "List" with id: 1

System.ArgumentOutOfRangeException: O índice estava fora do intervalo. Tem de ser não negativo e inferior ao tamanho da colecção.
Nome do parâmetro: startIndex
   em System.String.LastIndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   em Duplicati.Library.Main.Database.LocalListDatabase.FileSets.GetLargestPrefix(IFilter filter, String prefixrule)
   em Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)
   em Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   em Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)
   em Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

-----------------------------------
May 10, 2017 12:02 PM: Request for http://127.0.0.1:8200/api/v1/backup/1/files/*?prefix-only=true&folder-contents=false&time=2017-05-08T19:00:00%2B01:00 gave error
System.ArgumentOutOfRangeException: O índice estava fora do intervalo. Tem de ser não negativo e inferior ao tamanho da colecção.
Nome do parâmetro: startIndex
   em System.String.LastIndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   em Duplicati.Library.Main.Database.LocalListDatabase.FileSets.GetLargestPrefix(IFilter filter, String prefixrule)
   em Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)
   em Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   em Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)
   em Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
   em Duplicati.Server.WebServer.RESTMethods.Backup.SearchFiles(IBackup backup, String filterstring, RequestInfo info)
   em Duplicati.Server.WebServer.RESTMethods.Backup.GET(String key, RequestInfo info)
   em Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
-------------------------------------
May 10, 2017 12:02 PM: Reporting error gave error
System.ObjectDisposedException: Não é possível escrever num TextWriter fechado.
   em System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   em Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

**Comment by okoetter** [comment]
I also see this. I am on Windows 10 Pro and tried 2.0.1.56_canary_2017-04-21 and 2.0.1.53_experimental_2017-03-13.

Logs:

> May 17, 2017 3:34 PM: Failed while executing "List" with id: 10
> System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Auflistung sein.
> Parametername: startIndex
>    bei System.String.LastIndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
>    bei Duplicati.Library.Main.Database.LocalListDatabase.FileSets.GetLargestPrefix(IFilter filter, String prefixrule)
>    bei Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)
>    bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
>    bei Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)
>    bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
> 
> May 17, 2017 3:34 PM: Request for http://127.0.0.1:8200/api/v1/backup/10/files/*?prefix-only=true&folder-contents=false&time=2017-05-17T15:33:29%2B02:00 gave error
> System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Auflistung sein.
> Parametername: startIndex
>    bei System.String.LastIndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
>    bei Duplicati.Library.Main.Database.LocalListDatabase.FileSets.GetLargestPrefix(IFilter filter, String prefixrule)
>    bei Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter)
>    bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
>    bei Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)
>    bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
>    bei Duplicati.Server.WebServer.RESTMethods.Backup.SearchFiles(IBackup backup, String filterstring, RequestInfo info)
>    bei Duplicati.Server.WebServer.RESTMethods.Backup.GET(String key, RequestInfo info)
>    bei Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
> 
> May 17, 2017 3:34 PM: Reporting error gave error
> System.ObjectDisposedException: In einen geschlossenen TextWriter kann nicht geschrieben werden.
>    bei System.IO.__Error.WriterClosed()
>    bei System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    bei Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

**Comment by praneethsharma** [comment]
I was unable to restore due error "Duplicate option no-encryption" which has been discussed in #1625. I have updated the details in there. Please check.

**Comment by okoetter** [comment]
The bug also persists in the brand new 2.0.1.57_canary_2017-05-17.

**Comment by okoetter** [comment]
@praneethsharma: What does that have to do with this issue?

**Comment by okoetter** [comment]
This bug only comes up if you backup from an UNC path ("\\server\share\path\").
I submitted [this pull request](https://github.com/duplicati/duplicati/pull/2526) that fixes it for me.

**Comment by aflemos** [comment]
Thanks for fixing this issue!
How soon will the patched build be released? Or is there some other way for us to download the fix and test?
Thanks

**Comment by codinandhaulin** [comment]
Please release this, so I can restore my backups.  Thank you.

**Comment by okoetter** [comment]
Did you backup UNC paths? v2.0.1.65-2.0.1.65_canary_2017-06-09 can now be downloaded and contains this fix.

**Comment by codinandhaulin** [comment]
Thank you, Oliver.  I'll give it a try right now.

**Comment by aflemos** [comment]
I have updated to v2.0.1.65-2.0.1.65_canary_2017-06-09 and have verified that we can now restore those backups!
My thanks to everyone involved.
Keep up the great work!

**Comment by okoetter** [comment]
@aflemos Thanks for your confirmation!

**Comment by ilikecake** [comment]
This issue seems to have resurfaced in v2.0.3.7-2.0.3.7_canary_2018-06-17. I reverted to v2.0.3.5-2.0.3.5_canary_2018-04-13 and it seems to be working again. Let me know if you need me to provide more information.

**Comment by tomwaldnz** [comment]
I'm trying Duplicati again now that [2323](https://github.com/duplicati/duplicati/issues/2323) is fixed. Disappointingly there's another restore bug. I ran a backup on Amazon Linux, copied the files to my PC, then did a restore from the backup files. A google found this bug so I'm commenting here rather than opening a new one, as it's possibly related

Here's the screenshot

![duplicati-1](https://user-images.githubusercontent.com/8381145/42152276-b8db4cc4-7e33-11e8-9357-1dfc24b2bc91.png)

Here's the error detail

MainOperation: Repair
ParsedResult: Success
Version: 2.0.3.9 (2.0.3.9_canary_2018-06-30)
EndTime: 2/07/2018 8:04:54 PM (1530518694)
BeginTime: 2/07/2018 8:04:54 PM (1530518694)
Duration: 00:00:00.4353142
Messages: [
    2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Repair has started,
    2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),
    2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (6 bytes),
    2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.Operation.RecreateDatabaseHandler-RebuildStarted]: Rebuild database started, downloading 1 filelists,
    2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-20180702T035619Z.dlist.zip.aes (1.50 KB),
...
]
Warnings: []
Errors: []
TaskReader:
    ProgressAsync:
        Result: True
        Factory:
            CancellationToken:
                IsCancellationRequested: False
                CanBeCanceled: False
                WaitHandle:
                    Handle: 4516
                    SafeWaitHandle:
                        IsInvalid: False
                        IsClosed: False
            Scheduler: null
            CreationOptions: None
            ContinuationOptions: None
        Id: 37
        Exception: null
        Status: RanToCompletion
        IsCanceled: False
        IsCompleted: True
        CreationOptions: None
        AsyncState: null
        IsFaulted: False
    TransferProgressAsync:
        Result: True
        Id: 38
        Exception: null
        Status: RanToCompletion
        IsCanceled: False
        IsCompleted: True
        CreationOptions: None
        AsyncState: null
        IsFaulted: False
BackendStatistics:
    RemoteCalls: 2
    BytesUploaded: 0
    BytesDownloaded: 1533
    FilesUploaded: 0
    FilesDownloaded: 1
    FilesDeleted: 0
    FoldersCreated: 0
    RetryAttempts: 0
    UnknownFileSize: 0
    UnknownFileCount: 0
    KnownFileCount: 0
    KnownFileSize: 0
    LastBackupDate: 1/01/0001 1:00:00 PM (-62135596800)
    BackupListCount: 0
    TotalQuotaSpace: 0
    FreeQuotaSpace: 0
    AssignedQuotaSpace: 0
    ReportedQuotaError: False
    ReportedQuotaWarning: False
    ParsedResult: Success
    Version: 2.0.3.9 (2.0.3.9_canary_2018-06-30)
    Messages: [
        2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Repair has started,
        2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),
        2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (6 bytes),
        2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.Operation.RecreateDatabaseHandler-RebuildStarted]: Rebuild database started, downloading 1 filelists,
        2018-07-02 20:04:54 +12 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-20180702T035619Z.dlist.zip.aes (1.50 KB),
...
    ]
    Warnings: []
    Errors: []
    TaskReader: null
