### ISSUE TITLE
Onedrive for Business connection issues

### ISSUE THREAD

**Issue by zappeee** [duplicati/duplicati#2474]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.53_experimental_2017-03-13
**Operating System:** Windows 7 x64 Enterprise
**Backend:** OneDrive for Business

### Bug description
From time to time I have issues that Duplicati cannot backup to O4B, it says that the path/username/password is not working.
Even if I do test connection it still fails.

If I quit and start it again, test connection works and backup too.

### Steps to reproduce
Backing up

**Actual result:** System.Net.WebException: No SharePoint web could be logged in to at path 'https://XXX.sharepoint.com/personal/XXX/Documents/XXX/XXX/'. Maybe wrong credentials. Or try using '//' in path to separate web from folder path.
   at Duplicati.Library.Backend.SharePointBackend.getSpClientContext(Boolean forceNewContext)
   at Duplicati.Library.Backend.SharePointBackend.Test()
   at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)
   at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
**Expected result:** Connection to be working.
### Screenshots
-

### debug log
-

**Comment by guimchevalier** [comment]
Same issue for me
### Version info

**Duplicati Version:** 2.0.1.56_canary_2017-04-21
**Operating System:** QNAP 4.3.3
**Backend:** One drive for Business

First job running with success form 16 May 0:00 AM to 16 May 0:53 AM (UTC +2 time)
Second job on same account failed at around 16 May 3:30 AM (UTC +2 time)
Other jobs on this acound also failed
Testing connexion is not working any more either (same error message)

Jobs were running good (with only warning) the previous day

After NAS reboot, connection test and job is working again (with only warning).
Closing web interface doesnt help of course.

### debug log
```
Failed: No SharePoint web could be logged in to at path 'https://XXXX-my.sharepoint.com/personal/Y_ZZZZZ_XXXX_be/Documents/Backup_NAS/Administration'. Maybe wrong credentials. Or try using '//' in path to separate web from folder path.
Details: System.Net.WebException: No SharePoint web could be logged in to at path 'https://XXXX-my.sharepoint.com/personal/Y_ZZZZZ_XXXX_be/Documents/Backup_NAS/Administration'. Maybe wrong credentials. Or try using '//' in path to separate web from folder path.
  at Duplicati.Library.Main.BackendManager.List () [0x00041] in <9a0761fc41944a4eac9c10dbd966092c>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x0000d] in <9a0761fc41944a4eac9c10dbd966092c>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x00000] in <9a0761fc41944a4eac9c10dbd966092c>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend, System.String protectedfile) [0x0006c] in <9a0761fc41944a4eac9c10dbd966092c>:0 
```

**Comment by guimchevalier** [comment]
Occurs again tonight.
Logs available on request

**Comment by jma89** [comment]
I left some notes on issue #1788 

This header appears in the reply from OneDrive for Business:

`X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.`

I used Fiddler to force a UserAgent, but now it's just redirecting to the authentication page. Based on what I found from that error in the header Duplicati needs to handle Forms-based authentication to SharePoint. Not sure exactly what method it's attempting to use right now.

**Comment by oden63** [comment]
Running on CentOS7 i had the same issue. I got it working from the command line by running it using sudo. 

sudo duplicati-cli backup od4b://<company>-my.sharepoint.com:443/personal/<firstname>_<lastname>_<company>_com/Documents/Linux_Backup --auth-username=<email address> --auth-password=<password> --passphrase=<strong password> /home/<Unix Username>/Documents

Now, how to get it running from the GUI...

**Comment by MrChunky** [comment]
The same issue for me. I followed instructions carefully and still get this
 `Failed to connect: No SharePoint web could be logged in to at path 'https://xxx-my.sharepoint.com/personal/xxx_xxx_xx//Documents/Duplicati'. Maybe wrong credentials. Or try using '//' in path to separate web from folder path.`

**Comment by jeanpaulrh** [comment]
Same here.
Ubuntu 16.04, updated to the latest Mono from Mono aptitude repository.
I still can't connect, with the same error of the other people
`Invalid type Microsoft.WindowsAzure.Storage.Blob.BlobEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions:<EncryptionPolicy>k__BackingField
Invalid type Microsoft.WindowsAzure.Storage.Queue.QueueEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Queue.QueueRequestOptions:<EncryptionPolicy>k__BackingField
Invalid type Microsoft.WindowsAzure.Storage.Table.TableEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Table.TableRequestOptions:<EncryptionPolicy>k__BackingField
System.Net.WebException: No SharePoint web could be logged in to at path 'https://XXXXXXXX-my.sharepoint.com/personal/YYYYYYYY_onmicrosoft_com/Documents/duplicati'. Maybe wrong credentials. Or try using '//' in path to separate web from folder path.
  at Duplicati.Library.Backend.SharePointBackend.getSpClientContext (System.Boolean forceNewContext) [0x00070] in <1e96623231d94ecd98631cef66e60b62>:0 
  at Duplicati.Library.Backend.SharePointBackend.Test () [0x00000] in <1e96623231d94ecd98631cef66e60b62>:0 
  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x000b7] in <a6c0c2089b9a44ec9be5057a44f12116>:0 
  at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x00091] in <a6c0c2089b9a44ec9be5057a44f12116>:0 
  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x0026e] in <a6c0c2089b9a44ec9be5057a44f12116>:0 
`
I have no clue...

**Comment by albertony** [comment]
I tried the UserAgent fix, but it did not solve the OD4B connection problem for me.

OD4B has been worked for me for a long time, but when my company introduced multi-factor authentication a few days ago it stopped working with the same error as described here. I have generated an "app passord" that I use instead of my account password. Just before MFA was introduced I was successfully backing up to OD4B using Duplicati 2.0.2.15_experimental. After it stopped working I applied the UserAgent patch to my local 2.0.2.15_experimental build to see if that solved it, but it did not, unfortunately.

**Comment by albertony** [comment]
Tried some debugging on my own: The call to ctx.ExecuteQuery() in testContextForWeb returns an Microsoft.SharePoint.Client.ldcrlException with message "The partner returned a bad sign-in name or password error. For more information, see Federation Error-handling Scenarios." I updated the SharePoint.CSOM dependency to latest version (16.1.7206.1200) from nuget, without any effect. I also tried tracing the traffic with Fiddler, and I am not being able to see that the UserAgent is being set.

**Comment by lenar** [comment]
Still no luck with latest canary release on linux.

**Comment by heaje** [comment]
@tygill Thanks for mentioning the OneDrive v2 backend.  I just tried it out with the latest canary build and it appears to be working much better for me.

**Comment by Symbiot78** [comment]
It insists on using an O365 admin account to connect :(

**Comment by Symbiot78** [comment]
the Onedrive v2 backend.

**Comment by montizzl3** [comment]
How do I know if I am using the Onedrive v2 backend?  Maybe a better question is how do I select that so I can test to see if I get better results?

**Comment by zappeee** [comment]
@montizzl3, you choose it in the backup settings.

**Comment by warwickmm** [comment]
Microsoft has ended support for the old OneDrive API.  All users must use OneDrive v2 from now on.

**Comment by montizzl3** [comment]
So my options for Microsoft are:
Azure blob
Microsoft OneDrive
Microsoft OneDrive for Business
Microsoft SharePoint

Are you saying I should no longer use the Storage Type Microsoft OneDrive
for Business? Can I use the Microsoft SharePoint Storage Type with a
OneDrive for Business account?

**Comment by tygill** [comment]
Are you using the latest version of Duplicati? The latest Canary releases (for the last few months at least - I don't remember exactly what version) have a OneDrive v2 (and SharePoint v2) which are separate backends from the old OneDrive and SharePoint backends based on APIs that are still supported. OneDrive v2 works for both OneDrive for Business and personal OneDrive accounts. You'll need to log in to it separately (the existing credentials for the old backend won't work), but it should see existing files just fine.

I'm not sure if any of the beta releases are new enough to include these backends, and if you're on Linux or something that is getting an older release (some snaps I think are stuck on old releases). But if you don't see them as options, you need to find a way to update.

**Comment by montizzl3** [comment]
Ok I'll check out updating and I'll try out the v2 back end. Thank you!
