### ISSUE TITLE
Duplicati 1.3.4 Stall/Freezes/Hangs in Backup to Amazon S3 on Windows 10

### ISSUE THREAD

**Issue by Feenrai** [duplicati/duplicati#2476]
I have:
- [x ] searched open and closed issues for duplicates.
As far as I can tell, the other issues about stalling or freezing are not the same one I am having.

----------------------------------------

### Version info
Duplicati Version: 1.3.4
Operating System: Windows 10
Backend: Amazon S3

### Bug description
My Duplicati backup to Amazon S3 stalls or hangs. I've been using Duplicati for about a year now without issue. I run three backups; two small, and one of about 140 GB. The large one for 140 GB has stopped working. First, it froze repeatedly on "Reading incremental data" and would never continue on. I deleted the bucket from Amazon S3, and deleted the profile and made a fresh new backup profile to run the backup. From this point on I still am not able to complete the backup, but it now stalls or hangs further on. 

If I start brand new with a new bucket it will run for 5 to 15 minutes before it stalls or hangs. I do not get any error information in the log, it just stops reporting. It will actually stop mid line in the log, with one of the "Information: File snapshot" lines, but it won't be a complete line, it'll have cut off in the middle of giving the file location, and there won't be anything else even after waiting hours for it to continue.

If I stop the backup manually at this point and then run it again, it will run for up to 20 minutes reading as if it is processing and uploading, but again it will eventually stall and freeze usually on the "uploading" step and never continue. Additionally, if I check the Amazon S3 bucket, there will be nothing new in it from this backup attempt, only the volumes added in the first backup attempt with a fresh bucket.

### Steps to reproduce
Original Problem:
- I ran my weekly, incremental backup profile to Amazon S3

Actual result: The backup never got passed the "Reading incremental data step"
Expected result: The backup should have read incremental data fairly quickly and continued on to actually backup the new data.

I tried this a few times with the same result, before clearing the signature cache, deleting the old bucket from Amazon S3 as well as the backup profile on Duplicati, and starting completely fresh where I ran into the following problems instead:

Problem Two: Fresh Backup
- I delete the old bucket from Amazon S3
- I delete the backup profile from Duplicati
- I create a new backup profile on Duplicati
- I create the bucket for Amazon S3 through Duplicati
- I run the backup

Actual result: The backup will run for 5-15 minutes then then stall or hang. Only a very small amount of the backup will complete.
Expected result: The backup should be running completely and finishing like normal after backing up all of the data.

Option Two: Continuing from a Previously Stalled Backup
- I stop the stalled backup (see above)
- I run the backup again

Actual result: The backup will run for up to 20 minutes, processing files supposedly, and then it will stall or hang. As far as I can tell, no new volumes are actually added to Amazon S3. It is possible previously incomplete volumes are being added to (the log denotes lots of files as "...is partial from byte offset 123456789", but the time stamp on Amazon S3 is not reflecting this so I am not sure.
Expected result: The backup should be running completely and finishing like normal after backing up all of the data to Amazon S3.

### Debug Log
Though I have waited on a stalled backup for several hours, it does not error itself out or produce any error I can see in the debug log. Instead, at the point where it stalls out, it simply stops reporting to the log mid-line if it was a fresh bucket and backup, or after the previous line if it was a repeat attempt on a previously stalled backup.

### Additional Notes
- As mentioned, I have run this backup without prior issue for about a year. 
- My other two backups went through as normal this week. I will note they are both pretty small, so if the error is one that happens partway in, they may just be completing too quickly to encounter it.
- I did uninstall and reinstall Duplicati 1.3.4 to no effect. I noticed the backup profiles remained between installs however.
- Windows 10 had some updates earlier this week. This was my first backup since those updates so they might be relevant, or might just be coincidental.

**Comment by kenkendk** [comment]
We are no longer maintaining Duplicati 1.3.x and it has a rather old version of the S3 API at this point, so it is possible that something no longer work.

Please try with Duplicati 2.0 and see if the problem persists.

**Comment by g33k247** [comment]
I'm seeing the same issue with my install. I'm running Duplicati - 2.0.2.1_beta_2017-08-01. Any ideas on how to resolve the broken Amazon S3 backup?

**Comment by TheFatherMind** [comment]
I am backing up a about 1.7TB from a local servers sharepoint to a local SFTP server from my workstation.  I too am having stalling issues.  It stalls during the transfer.  Just sits on "Backup_ProcessingFiles".

**Comment by Feenrai** [comment]
As recommended above, I upgraded to Duplicati 2.0 and have been grateful to not have any issues since.

**Comment by TheFatherMind** [comment]
I am using the most current stable version.  2.0.4.5_beta_2018-11-28

**Comment by Pectojin** [comment]
@TheFatherMind If you're seeing a similar issue on Duplicati 2, please open a new issue. It's entirely different code from version 1 so developers will have a hard time figuring out what's causing trouble :)
