### ISSUE TITLE
Stupid question about "Keep backups"-option

### ISSUE THREAD

**Issue by zin105** [duplicati/duplicati#2482]
If I set this value to 1 week, what happens to files that hasn't been changed in that time? Do they get removed? Re-backedup?

**Comment by kenkendk** [comment]
Each backup is considered a "snapshot". You can restore all files that were present at the time of the snapshot, essentially allowing you to "go back" to the time the backup was made.

If you set the value to "1 week" you will be able to "go back" one week. It does not matter if the files have changed within the week, it only matters if they were present at the time the backup was made.
