### ISSUE TITLE
FTPS Upload fails System.InvalidCastException: Specified cast is not valid 

### ISSUE THREAD

**Issue by SamiLehtinen** [duplicati/duplicati#2483]
I have:
- [x] searched open issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.57_canary_2017-05-17
**Operating System:** Ubuntu 16.04 LTS
**Backend:** FTPS

### Bug description
Upload fails with FTPS backed to server giving error message:
Fatal error => System.InvalidCastException: Specified cast is not valid.

Checked and confirmed - temp path is valid, temp files are created and the upload and download to the server works perfectly. Configuration hasn't been changed lately. I think it's the 57 version which is broken. This occurred immediately after update.

### Steps to reproduce
- Just run the backup as usual.

**Actual result:** Put fails as described in the error message.
**Expected result:** Uploading of the files to the server should work.

### debug log

Operation Put with file duplicati-b274e82311e764aefb81e623a25c8b776.dblock.zip.aes attempt 5 of 5 failed with message: Specified cast is not valid. => System.InvalidCastException: Specified cast is not valid.
  at Duplicati.Library.Utility.AsyncHttpRequest.GetRequestStream (Int64 contentlength) <0x40d83c40 + 0x000ae> in <filename unknown>:0 
  at Duplicati.Library.Backend.FTP.Put (System.String remotename, System.IO.Stream input) <0x40d83270 + 0x0016f> in <filename unknown>:0 
  at Duplicati.Library.Main.BackendManager.DoPut (Duplicati.Library.Main.FileEntryItem item) <0x40d7e690 + 0x006c4> in <filename unknown>:0 
  at Duplicati.Library.Main.BackendManager.ThreadRun () <0x40cb7f50 + 0x0033f> in <filename unknown>:0 
Fatal error => System.InvalidCastException: Specified cast is not valid.
  at Duplicati.Library.Main.BackendManager.WaitForComplete (Duplicati.Library.Main.Database.LocalDatabase db, IDbTransaction transation) <0x40da0990 + 0x000fb> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) <0x40c93270 + 0x01abf> in <filename unknown>:0 

System.InvalidCastException: Specified cast is not valid.
  at Duplicati.Library.Main.BackendManager.WaitForComplete (Duplicati.Library.Main.Database.LocalDatabase db, IDbTransaction transation) <0x40da0990 + 0x000fb> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) <0x40c93270 + 0x01abf> in <filename unknown>:0 

I'm happy to provide additional and more detailed information if required.

**Comment by kenkendk** [comment]
This is caused by my length check:
https://github.com/duplicati/duplicati/blob/bf7d36e380de8b3bafe7440d54f417e2f156dc7d/Duplicati/Library/Utility/AsyncHttpRequest.cs#L120

It should also check if the connection is HTTP based, instead of assuming that it is.

**Comment by SamSirry** [comment]
I've had this issue today in a job that contains a 70.5 GB file. This is the first time I attempt to back up a file this big, and this is the first time I see this error.
According to @kenkendk 's comment, I'm assuming this might be related to the large size of the file. So I'm reporting that this is happening in ver 2.0.4.12

Here's the error log:

    System.InvalidCastException: Specified cast is not valid. at 
    System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ) at 
    System.Data.SQLite.SQLiteDataReader.GetString(Int32 i) at 
    Duplicati.Library.Main.Database.LocalBackupDatabase.AppendFilesFromPreviousSetWithPredicate(IDbTransaction transaction, Func`3 exclusionPredicate, Int64 fileSetId, Int64 prevFileSetId, DateTime timestamp) at 
    Duplicati.Library.Main.Database.LocalBackupDatabase.AppendFilesFromPreviousSetWithPredicate(IDbTransaction transaction, Func`3 exclusionPredicate) at 
    Duplicati.Library.Main.Operation.Common.SingleRunner.<>c__DisplayClass3_0.<RunOnMain>b__0() at 
    Duplicati.Library.Main.Operation.Common.SingleRunner.<DoRunOnMain>d__2`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at 
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at 
    Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__12.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at 
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at 
    Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown --- at 
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at 
    CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task) at Duplicati.Library.Main.Controller.<>c__DisplayClass13_0.<Backup>b__0(BackupResults result) at 
    Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) at 
    Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter) at 
    Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
