### ISSUE TITLE
Ports used? (QoS)

### ISSUE THREAD

**Issue by zin105** [duplicati/duplicati#2488]
What ports does duplicati use for uploading? Is it random? Was hoping to apply QoS (traphic shaping) in pfSense.

**Comment by kenkendk** [comment]
That depends on the backend you use. Most backends use https (443).

**Comment by zin105** [comment]
Google Drive. Is it possible to change the port used (guessing not)? Don't really wanna traphic shape 443.

**Comment by shoeper** [comment]
> Edit: I can assign a unique IP to my Duplicati container and traphic shape it that way so I can work around the issue if need be.

that's what you want to do.

**Comment by kenkendk** [comment]
Yes, using the source IP seems like the way to go. Google decides what IP and ports they offer, and it can change when they feel like it.
