### ISSUE TITLE
RansomWare Resistance

### ISSUE THREAD

**Issue by saviodsouza** [duplicati/duplicati#2489]
Hi all,

Can the extension of duplicati files be customized to protect from ramsomware attacks.

This is required if the backend is local drive or similar, it is safe if it is a remote backend. As per this document http://www.odisha.gov.in/portal/CERT-In%20Advisory-Wannacry.pdf even aes and gpg files get affected.

**Comment by zin105** [comment]
Usually ransomware spreads through network locations that you have saved credentials for (for example network drive in Windows is a no-no if you mount it with write permission). I use a SFTP destination and AFAIK that would be resistant to ransomware as long as it's the only way to reach the destination folder.

**Comment by saviodsouza** [comment]
the only thing i wanted to know just like we set prefix name in backup settings can't we set extension name.

**Comment by shoeper** [comment]
There is no value of setting an extension.

**Comment by kenkendk** [comment]
Duplicati uses the suffix/file extension to decide what kind of file it is, so there is no option to change that.

I think it would be a very short-term guard to change the file extension, as other ransomware variants encrypt all files.

So far, the ransomware has not attempted to delete remote backups, so for now you can simply make sure that the remote destination is not writeable through the normal filesystem.

To be safer, you need to get a remote destination that supports "write once only" as that will ensure an active attacker cannot remove your backups.
