### ISSUE TITLE
Duplicati 2.0 high memory usage after backups finish - Windows 10

### ISSUE THREAD

**Issue by tomwaldnz** [duplicati/duplicati#2491]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** Duplicati - 2.0.1.53_experimental_2017-03-13
**Operating System:** Windows 10
**Backend:** Don't know what this means

### Bug description
RAM usage after a backup is high. I ran three backups 12 hours ago, of around 50GB of data. RAM usage is 2GB.

### Steps to reproduce
- Run a variety of backups (I did 7 runs of 4 sets) to local disks and Amazon S3

**Actual result:** 2.6GB of RAM used once backup finished
**Expected result:** RAM is freed after backup is finished, or some time later

### Screenshots
![dup-memory](https://cloud.githubusercontent.com/assets/8381145/26260291/c6dd6a00-3d20-11e7-9537-9507733efbba.jpg)

### debug log
Can supply if required, I don't know where to find it.

**Comment by kenkendk** [comment]
Can you try the latest canary build, as that has some improvements to memory usage:
https://github.com/duplicati/duplicati/releases

Also, the memory handling in .Net looks at how much memory the system needs, so it can choose not to free memory until other processes request memory.

**Comment by tomwaldnz** [comment]
I'll keep an eye on it to see if memory is released if the ram is needed by other software.

I'm using Duplicati as my main backup system, is Canary stable enough? Is experimental? I do have multiple backups in multiple formats and location though, plus online backups, so I'm not 100% relying on it yet.

**Comment by tomwaldnz** [comment]
I think you're right. If memory is required by the OS it's released. I'll keep an eye on it but for now it seems ok.

**Comment by kenkendk** [comment]
We call them "canary" and "experimental" to reflect the fact that they are still new (for a backup system). I think we are now at a place where they appear to be stable, but it depends on what you need.

We do have recovery scripts that can extract data even from very broken backups, but there are users reporting issues still, so at least not all have an unproblematic experience.

**Comment by tomwaldnz** [comment]
I experienced a significant issue with a restore, which I added to an [existing case](https://github.com/duplicati/duplicati/issues/2323). It seems odd that it fails due to a block size mismatch, given Duplicati should be able to work that kind of thing out itself.

Is there documentation on those recovery scripts? Or on the command line? I've found [help.txt](https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/help.txt) but it's quite high level. For example, if I want to restore an encrypted backup from S3, with custom block and dblock sizes, how would I do that? The help documentation only says you give it the storage URL and options. The storage URL isn't defined (how do you use a URL for a local file vs S3), and how do you give parameters like the S3 access key?

Duplicati has the potential to be better than any of the currently available backup products, it just needs a few fixes, a few enhancements, and some documentation.
