### ISSUE TITLE
The operation couldn’t be completed. (OSStatus error -67071.)

### ISSUE THREAD

**Issue by free2open** [duplicati/duplicati#2494]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version: duplicati-2.0.1.58_canary_2017-05-19.dmg
**Operating System: OS X El Capitan 10.11.6 (15G1108)
**Backend: MonoFramework-MDK-4.6.2.7.macos10.xamarin.universal.pkg

### Bug description
"The operation couldn’t be completed. (OSStatus error -67071.)" message shows up immediately after trying to open the app (duplicati-2.0.1.58_canary_2017-05-19).  However, my last working Duplicati-2.0.1.34 is able to open normally.

### Steps to reproduce
- Double click on Duplicati in /Applications with a Standard user privilege.

**Actual result: The message box shows up with the error message.
**Expected result: I expect the app to run normally.

### Screenshots
None

### debug log
The operation couldn’t be completed. (OSStatus error -67071.)

**Comment by kenkendk** [comment]
What is the size of the .dmg file? What is the size of the `Duplicati.app` ?
Are you moving the app into the `Applications` folder before starting?

**Comment by free2open** [comment]
duplicati-2.0.1.58_canary_2017-05-19.dmg is 13,506,144 bytes.  The Duplicati.app is 31,672,496 bytes.  I moved into a folder before starting it.  duplicati-2.0.1.57_canary_2017-05-17.dmg has no problem running.

**Comment by kenkendk** [comment]
I have no idea why that is. I was guessing that the DMG was damaged on download, but the size checks out. Can you use the later versions? There was nothing special changed in 2.0.1.58 that I would imagine could cause this.

**Comment by free2open** [comment]
duplicati-2.0.1.64_canary_2017-06-02.dmg runs without the error messages.  Thanks.

**Comment by kenkendk** [comment]
Ok, I am closing then, hoping it does not happen again.
