### ISSUE TITLE
Add default filters on new backups in Windows that exclude `$RECYLE.BIN` and `System Volume Information` folders

### ISSUE THREAD

**Issue by TonyToews** [duplicati/duplicati#2495]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**2.0.1.58_canary_2017-05-19:**  Has happened for the last year or two in al the 2.0 versions I have installed and updated.
**Windows 7**
**OneDrive**

### Bug description
In Windows 7 I have created a data partition Q: drive exclusively for all my data files.  I then backup the entire partition rather than selected folders on C drive such as Windows's default My Documents folder.   (I've been doing this since dual booting OS/2 Warp and Windows 95.)   As a result of this I get the following messages as Duplicati can't view the contents of several system folders.  And neither should it as those folders aren't relevant for backup purposes.

 Failed to process metadata for "Q:\System Volume Information\", storing empty metadata => Attempted to perform an unauthorized operation.,
 Error reported while accessing file: Q:\System Volume Information\ => Access to the path 'Q:\System Volume Information' is denied.,
 Error reported while accessing file: Q:\$RECYCLE.BIN\S-1-5-21-883612559-880012020-1611292523-1000\ => Access to the path 'Q:\$RECYCLE.BIN\S-1-5-21-883612559-880012020-1611292523-1000' is denied.,

I would suggest that, if running under Windows, the following system folders automatically be ignored:
"\System Volume Information\"
"\$RECYCLE.BIN"

I would assume there are localized names for these folders so hard coding the values would almost certainly be a bad idea.   Yes,, I know the folks reading this are experienced devs but I felt it best to point this out.   I do not know how to search for such localized values in the .Net world.

This is not a big deal as I just ignore the 7 messages but what happens some day if there are a different set of messages which I don't realize for a while.

### Steps to reproduce
- create an empty partition in Windows
- create some files in the partition to backup using Duplicati

### debug log

May 21, 2017 12:13 AM: Message
Error reported while accessing file: Q:\$RECYCLE.BIN\S-1-5-21-3555086663-3173750201-1926638125-1000\
System.UnauthorizedAccessException: Access to the path 'Q:\$RECYCLE.BIN\S-1-5-21-3555086663-3173750201-1926638125-1000' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at Duplicati.Library.Snapshots.NoSnapshotWindows.ListFolders(String folder)
   at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>c__Iterator0.MoveNext()

Error reported while accessing file: Q:\System Volume Information\
System.UnauthorizedAccessException: Access to the path 'Q:\System Volume Information' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Duplicati.Library.Snapshots.NoSnapshotWindows.ListFiles(String folder)
   at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>c__Iterator0.MoveNext()

**Comment by saviodsouza** [comment]
Try 
Run Duplicati as Admin
Under advanced options set snapshot policy to required
 Hope it helps

**Comment by TonyToews** [comment]
When I read the text for the snapshot policy  option it states "Setting it to "required" will make Duplicati abort the backup if the snapshot creation fails.".      But I want the backup to proceed.  Just don't warn me about those two particular system folders failing.   And I don't want those folders to be backed up either.

**Comment by sjonez** [comment]
I assume you've already excluded them yourself in your backup configuration and so are no longer receiving these warnings? In which case this is simply a feature request to have them excluded by default like various other backup software does?

FYI "System Volume Information" and "$Recycle.Bin" are two of the few folders that aren't localised, so they should be the same across all language packs.

**Comment by TonyToews** [comment]
No, I didn't know how I can exclude those folders. as I want to back up all folders on Q: drive other than those two systems folders.   I don't want to explicitly add the current list of folders as I might create a folder next month and forgot to add the new folder to Duplicati.

I just reviewed the Exclude section and see the exclude Hidden and System files check boxes.   I'm embarrassed to state I never thought of looking in that area.  I'll post tomorrow after my backup if this solves my problem.

**Comment by sjonez** [comment]
If that doesn't work in addition to the Hidden/System option you can include the entire Q: drive as you currently are but then add specific folder excludes under the "Filters" section. Doing that will still automatically back up any new folders that are added.

**Comment by kenkendk** [comment]
@TonyToews You can click the green check mark next to `$RECYCLE.BIN` and it should change to red (and add the filter below for you). You can do the same with the `System Volume Information` folder.

I have renamed the issue to indicate that it is a request to have these filters automatically added to newly created backups.

**Comment by vkapas** [comment]
I've a similar situation: separate logical drive Z: which backuping to Yandex.Disk (WebDAV) by Duplicity.
$RECYCLE.BIN and System Volume Information folders are [excluded with filters](http://storage5.static.itmages.ru/i/17/0530/h_1496171627_9146060_5773c7be9f.png).
However, error about denied access still appear every backup:
```
Failed to create a snapshot: System.UnauthorizedAccessException: Попытка выполнить несанкционированную операцию.
   в Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
   в Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
   в Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   в Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)
   в Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
System.UnauthorizedAccessException: Попытка выполнить несанкционированную операцию.
   в Alphaleonis.Win32.Vss.VssBackupComponents..ctor()
   в Alphaleonis.Win32.Vss.VssImplementation.CreateVssBackupComponents()
   в Duplicati.Library.Snapshots.WindowsSnapshot..ctor(String[] sourcepaths, Dictionary`2 options)
   в Duplicati.Library.Snapshots.SnapshotUtility.CreateWindowsSnapshot(String[] folders, Dictionary`2 options)
   в Duplicati.Library.Main.Operation.BackupHandler.GetSnapshot(String[] sources, Options options, ILogWriter log)
```
I used 2.0.1.53_experimental_2017-03-13 version.

P.S. _Попытка выполнить несанкционированную операцию_ = _Attempted to perform an unauthorized operation_ (on Russian).

**Comment by sjonez** [comment]
That seems more like an issue creating a VSS snapshot rather than accessing any particular folder. As per the first reply in this thread make sure Duplicati is running as an admin (not just an admin user, but make sure its running elevated, e.g. right click and Run as administrator). Either that or run Duplicati as a service.

**Comment by kenkendk** [comment]
@vkapas: Yes, what @sjonez writes is correct.

**Comment by vkapas** [comment]
@sjonez Thx, running Duplicati [as service](https://www.duplicati.com/articles/Way-To-Make-A-Backup/#service-component) (and installing [Visual C++ Redistributable](https://www.microsoft.com/en-US/download/details.aspx?id=48145)) is solved my problem.
