### ISSUE TITLE
Possibly broken inplace-updater with duplicati 2.0.1.60

### ISSUE THREAD

**Issue by umgfoin** [duplicati/duplicati#2505]
Hello folks,
the whole thing is described in @shoodle's post [Debian 2.0.1.60 backup abortion #2503](https://github.com/duplicati/duplicati/issues/2503).
As I suspect the updater being the rebel, I filed a separate issue. If you need further input, my stacktrace is available, too, but it looks essentially the same as in the above thread.
++umgfoin.

**Comment by kenkendk** [comment]
I have commented on #2503
