### ISSUE TITLE
Change all path inputs and filters with `/` to `\` on Windows machines

### ISSUE THREAD

**Issue by jarmo** [duplicati/duplicati#2509]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.43_canary_2017-01-19
**Operating System:** Windows 10 Pro
**Backend:** Local filesystem

### Bug description
I'm trying to exclude some sub-directories from backup, but failing to do so regardless of the syntax used. I'm using a command line interface. Script to reproduce this problem follows.

### Steps to reproduce
- Create a script **backup-test.cmd** in the same directory as **Duplicati.CommandLine.exe** resides with the following content:
```
@echo off
mkdir c:\backup-test
mkdir c:\backup-test\excluded-dir
echo 1 > c:\backup-test\backupped-file
echo 2 > c:\backup-test\excluded-dir\excluded-file
Duplicati.CommandLine backup "c:/backup-of-backup-test" "c:/backup-test" --exclude="c:/backup-test/excluded-dir/" --passphrase="foobar" --dbpath="c:/backup-of-backup-test/db" && Duplicati.CommandLine restore "c:/backup-of-backup-test" "*" --passphrase="foobar" --no-local-blocks --dbpath="c:/backup-of-backup-test/db" --restore-path="c:/backup-test-restore" && tree /F c:\backup-test-restore
rmdir /s /q c:\backup-test
rmdir /s /q c:\backup-of-backup-test
rmdir /s /q c:\backup-test-restore
```
- run the script

**Actual result:** **excluded-directory** is part of the backup (output of the tree command):
```
C:\BACKUP-TEST-RESTORE
│   backupped-file
│
└───excluded-dir
        excluded-file
```
**Expected result:** It should not be part of backup.

I've tried different syntax for excluding that directory, but failing to do so. Is it broken or have I misunderstood something? I'm pretty sure that it worked long time ago.

**Comment by kenkendk** [comment]
Duplicati does string matching, so I think you need to use `--excude="c:\backup-test\excluded\dir\\"` for it to work.

**Comment by jarmo** [comment]
This seems to work indeed!

If it does string matching, then how do wildcards and regexp work within these filters? I would suggest Duplicati to take input with "/" or "\" so that it would work on any platform in the same way - especially since other paths (backup path for example) can be specified with forward-slashes already.

**Comment by kenkendk** [comment]
It has both regexp support and a custom wildcard matcher for non-plain string matching.

I know that windows supports both `/` and `\` but Duplicati expects the `\` version.

I have changed the title to suggest that it does a fixup and changes all `/` to `\` on all inputs, if it is running on Windows.

**Comment by jarmo** [comment]
Why not change it to the other way around (from "\\" to "/") since there are more OS-es with the "/"? :)

**Comment by kenkendk** [comment]
I want it to "look native" on all platforms, and Window users expect to see `\`.
