### ISSUE TITLE
duplicati 2.0.1.61 / macOS : Missing assemblies in package

### ISSUE THREAD

**Issue by gillesgagniard** [duplicati/duplicati#2513]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Mono Version:** 5.0.1.1
**Operating System:** macOS Sierra 10.12.5
**Backend:** SFTP (SSH)

### Bug description
The macOS installation package for Duplicati 2.0.1.61 is missing some needed assemblies.

When trying to backup to a SFTP target, the following error (extract from logs) prevents duplicati to connect :

    System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.Services.Client, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
    File name: 'Microsoft.Data.Services.Client, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
      at Renci.SshNet.Session.WaitOnHandle (System.Threading.WaitHandle waitHandle, System.TimeSpan timeout) [0x00041] in <1fab08b1278e43dabeb31c481785219b>:0

Full log : [duplicati_ssh_fail.txt](https://github.com/duplicati/duplicati/files/1040639/duplicati_ssh_fail.txt)

Manually nugetting the Microsoft.Data.Services.Client assembly (and its dependencies) and injecting the .dll directly in Duplicati.app/Contents/Resources fixes the issue.

### Steps to reproduce
- install duplicati 2.0.1.61 on macos
- setup a backup with SFTP as destination
- run backup, and watch it fail

**Actual result:** backup failure (see log attached above)
**Expected result:** backup runs

**Comment by kenkendk** [comment]
I do not see how the SSH library could attempt to load `Microsoft.Data.Services.Client`.
The project does not even seem to mention it: https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet.NET35/Renci.SshNet.NET35.csproj

**Comment by gillesgagniard** [comment]
No idea either ...

Also, downgrading to 2.0.1.53 fixes the issue (same OS, same mono version, same user profile) so the root cause is definitely in the build / packaging of 2.0.1.61.

**Comment by cyrilpawelko** [comment]
Exact same thing here, on an linux-based asustor NAS, with mono 4.6.2., for a sftp backup.

**Comment by vlepetit** [comment]
Duplicati Version: 2.0.1.61_experimental_2017-05-30
Mono Version: 5.0.1.1
Operating System: Ubuntu 16.04.2 LTS server 64 bits
Backend: SFTP (SSH)

I encountered the same problem this morning. When i tried the "test connexion" button i had this message :

"Failed to connect: Could not load file or assembly 'Microsoft.Data.Services.Client, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. "

In first time it's crash duplicati service. After install mono-complete package, duplicati don't crash but it give me error message in duplicati web interface.

To resolve this problem i'll try to take duplicati 2.0.1.53 like gillesgagniard and i'll come back if it's fixes issue for me.

Regards

**Comment by vlepetit** [comment]
Ok with downgrade to Duplicati - 2.0.1.53_experimental_2017-03-13 that fixe the issue.

But i hav not tried with version between 2.0.1.53 and 2.0.1.6.

So it's seem to the cause is in the current package.

Regards,

**Comment by cyrilpawelko** [comment]
No more error after upgrading to 2.0.1.66_canary_2017-06-15

Regards.

**Comment by kenkendk** [comment]
@cyrilpawelko Thanks for reporting!

I will make a new experimental soon, that has the updates included.

**Comment by tiagoboldt** [comment]
@kenkendk shouldn't this issue be kept open until a new experimental is available? 

Thanks
