### ISSUE TITLE
Failed to process metadata on mapped drives

### ISSUE THREAD

**Issue by jniggemann** [duplicati/duplicati#2518]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** Duplicati - 2.0.1.53_experimental_2017-03-13
**Operating System:** Windows 7 64
**Backend:** Windows, unkown Version, via UNC

### Bug description
Source files on mapped network drives (from am Windows Server 2012) are properly backed up, but create the following log entries:
```
Failed to process metadata for "O:\FILENAME.docx", storing empty metadata
System.InvalidOperationException: Unerwarteter Methodenfehler 58.
   bei System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   bei System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   bei System.Security.AccessControl.FileSecurity..ctor(String fileName, AccessControlSections includeSections)
   bei Duplicati.Library.Snapshots.SystemIOWindows.GetAccessControlFile(String path)
   bei Duplicati.Library.Snapshots.SystemIOWindows.GetMetadata(String path, Boolean isSymlink, Boolean followSymlink)
   bei Duplicati.Library.Main.Operation.BackupHandler.GenerateMetadata(ISnapshotService snapshot, String path, FileAttributes attributes)
```

### Steps to reproduce
- run same backup set again

### Debug log
see above, can give more info if needed

**Comment by kenkendk** [comment]
This is caused by the remote filesystem (or something in between) not supporting ACL (permission control), or at least not supporting part of it.

If you do not need it, you can disable it with `--skip-metadata` but this will also not store modification timestamps.

Is this sufficient for your use?

**Comment by jniggemann** [comment]
Ahh, knowing this is suficcient for my use. Thank you for the information and for Duplicati!
