### ISSUE TITLE
Unstable upload speed (ACD)

### ISSUE THREAD

**Issue by Bazzu85** [duplicati/duplicati#2520]
I'm using
Duplicati - 2.0.1.61_experimental_2017-05-30
on Windows 10 64 bit

Setted 1gb volume upload.

When uploading to ACD the speed higly unstable.

here's a screenshot.
![2017-06-02_151820](https://cloud.githubusercontent.com/assets/7345587/26727320/b97e8fc0-47a6-11e7-9d3c-dafad3665b87.jpg)

I have a 20MB connection

**Comment by kenkendk** [comment]
Not sure there if this is a problem that is on Duplicati's side or on ACD.
Can you get stable speeds with other ACD tools?

**Comment by Bazzu85** [comment]
At the moment I'm using Arq with ACD and the speed is stable..

Il 07 giu 2017 09:58, "Kenneth Skovhede" <notifications@github.com> ha
scritto:

**Comment by warwickmm** [comment]
Closing this since the Amazon Cloud Drive API has been discontinued.

https://forum.duplicati.com/t/amazon-cloud-drive-discontinued/7391
