### ISSUE TITLE
Random connection lost

### ISSUE THREAD

**Issue by czqlfy** [duplicati/duplicati#2523]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

Duplicati Version: 2.0.1.61_experimental_2017-05-30
Operating System: Windows 10, Ubuntu 16.04

### Bug description
Random connection lost on Firefox, can happen on localhost and remote server.

### Steps to reproduce
- Play around with the Web UI
- And all in a sudden it happens
- Click reconnect it stucks as the screenshot shown below

**Actual result:** Intermittent connection lost
**Expected result:** No connection lost, especially on localhost

### Screenshots

![capture](https://cloud.githubusercontent.com/assets/7358362/26769571/002bcbb2-497e-11e7-9aa6-0186066afea4.JPG)

**Comment by kenkendk** [comment]
Usually this happens if the server/trayicon crashes.
Can you try to start the server/trayicon from the commandline and then provoke the crash to see if you can get a stack trace?

**Comment by czqlfy** [comment]
@kenkendk 
The server/trayicon did not crash. After a web page refresh the webui work fine for another several minutes

**Comment by kenkendk** [comment]
Ok, can you then try to use some "Developer Console" view in the browser:
https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

When the error message occurs, you should see some failures in the network connection.
Once you see them, can you report back what the errors are?

**Comment by czqlfy** [comment]
Hello,
It seems that this happens when GET request of http://[whatever]/api/v1/serverstate/ fails.
However, the GET request of http://[whatever]/api/v1/progresstate is working just fine

**Comment by kenkendk** [comment]
What error code do you see when the `serverstate` call fails? Is it a timeout or does the server report an error code?

**Comment by czqlfy** [comment]
Hello,
I have captured a screenshot.
![screenshot 2](https://user-images.githubusercontent.com/7358362/27486689-62977a14-57ff-11e7-95d0-173017ce8d68.png)

**Comment by kenkendk** [comment]
Great!

The one you have expanded is the one that is "hanging". Can you expand the previous one (where it says 0ms)?

**Comment by czqlfy** [comment]
Hello,
the hanging GET request has succeeded after 185675ms and the web ui recovered to normal.
Please check out the screenshot
![screenshot 4](https://user-images.githubusercontent.com/7358362/28242119-6d53224a-6971-11e7-939a-c3fd9eb67237.png)
![screenshot 5](https://user-images.githubusercontent.com/7358362/28242120-6eb0707a-6971-11e7-815c-25dcdea8ae6f.png)

**Comment by kenkendk** [comment]
I think I just found this error yesterday.

It happens if the XSRF token expires, and the client does a reconnect.
However, the re-connect works, but this causes a long-poll request to happen, such that everything appears to hang.

This is fixed with dd86dfa32d912fc97c506cde9e76564e3f517898
