### ISSUE TITLE
'compare' fails with exception System.ArgumentNullException

### ISSUE THREAD

**Issue by citybar** [duplicati/duplicati#2525]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61
**Operating System:** Windows 10 Pro 1703
**Backend:** Windows 10 Pro 1703

### Bug description
The 'compare' command fails with exception System.ArgumentNullException on all of my backup sets.
This error also occurs for backup sets that were last updated using an older version of duplicati 2 and that yielded reasonable 'compare' result when using that older version. So I assume (and hope) that the backup sets are not corrupt but only the 'compare' command is somehow broken in the new version. 

### Steps to reproduce
From the command line I ran one of the following commands:

Duplicati.Commandline.exe compare "name_of_backup_set" --verbose "--log-level=Profiling" "--debug-output" "--passphrase=xyz"

or

Duplicati.Commandline.exe compare "name_of_backup_set" 1 0 --verbose "--log-level=Profiling" "--debug-output" "--passphrase=xyz"

or with any other combination of version numbers. 

**Actual result:** 
The output is as follows: 
---
Input command: compare
Input arguments:
        name_of_backup_set
        1
        0

Input options:
verbose:
log-level: Warning
passphrase: xyz

Listing changes
  1: 29.05.2017 00:15:52
  0: 04.06.2017 14:11:19

Size of backup 1: 1,21 GB

System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: source
   bei System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   bei Duplicati.CommandLine.Commands.<>c__DisplayClass14_0.<ListChanges>b__0(IListChangesResults result, IEnumerable`1 items)
   bei Duplicati.Library.Main.Operation.ListChangesHandler.Run(String baseVersion, String compareVersion, IEnumerable`1 filterstrings, IFilter compositefilter, Action`2 callback)
   bei Duplicati.Library.Main.Controller.<>c__DisplayClass31_0.<ListChanges>b__0(ListChangesResults result)
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   bei Duplicati.CommandLine.Commands.ListChanges(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   bei Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)

**Expected result:** No exception but a list of changes.

**Comment by kenkendk** [comment]
It looks like it can report the changes, but something fails when listing the actual changes files.

**Comment by kenkendk** [comment]
Highly unlikely that this means the data is broken, most likely just a fault in the command.

**Comment by kenkendk** [comment]
This was fixed with #2534
