### ISSUE TITLE
Crash when trying to setup sftp connection to restore from remote backup

### ISSUE THREAD

**Issue by pascalBokBok** [duplicati/duplicati#2532]
Duplicati crashes when I try to setup the sftp connection to restore my backup from another computer.
A fresh installed Duplicati 2.0.1.61 on KDE Neon (ubuntu 16.04 based)
I clicked "Restore" -> Direct restore from backup files -> Storage type: sftp (ssh).
Filled in all the details and click test connection.
Then the connection to Duplicati is gone and I can see the process is gone. Repeated 4 times to see if it was a certain type of details that made it crash.

I've attached the crashlog.
[Duplicati-crashlog.txt](https://github.com/duplicati/duplicati/files/1062312/Duplicati-crashlog.txt)

From the crashlog I looked at the gtk-sharp2 package, but it is already installed.
Details:
Package: gtk-sharp2
Priority: optional
Section: universe/libs
Installed-Size: 144
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian CLI Libraries Team <pkg-cli-libs-team@lists.alioth.debian.org>
Architecture: all
Version: 2.12.10-6
Depends: gtk-sharp2-examples (= 2.12.10-6), gtk-sharp2-gapi (= 2.12.10-6), libglade2.0-cil-dev (= 2.12.10-6), libglib2.0-cil-dev (= 2.12.10-6), libgtk2.0-cil-dev (= 2.12.10-6), monodoc-gtk2.0-manual (= 2.12.10-6)
Filename: pool/universe/g/gtk-sharp2/gtk-sharp2_2.12.10-6_all.deb
Size: 1816
MD5sum: 75b01f53c8f6eef81a59f890aa5e3ae3
SHA1: acfe7c0bd0c1e950491eaa6f1d40d0c68d222578
SHA256: 8703ec652be3b437796f2568b7d10ae4567fa8bcc9f51572060b4932de3dc2c0
Description: GTK# 2.10 suite, CLI bindings for GTK+
Description-md5: cdd354d227029cf80635fa9731cc87b1
Homepage: http://www.mono-project.com/GtkSharp
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

**Comment by pascalBokBok** [comment]
It seems I might have attached the wrong crashlog since it's from the updates folder.

**Comment by pascalBokBok** [comment]
I've now run it in the terminal and copied the quite large stacktrace into a file.
[Stacktrace.txt](https://github.com/duplicati/duplicati/files/1062357/Stacktrace.txt)

**Comment by kenkendk** [comment]
I think this is the same as #2425.

I have put up an updated Canary build which should fix the problem:
https://github.com/duplicati/duplicati/releases

**Comment by kenkendk** [comment]
Actually, this sounds more like #2503, but the same underlying problem and should also be fixed in the canary build.

**Comment by ts678** [comment]
Above-linked issue was closed and verified in 2017, so assuming the issue here is no longer a bug unless it's known otherwise.
