### ISSUE TITLE
Backup warnings cause mail to be sent even when send-mail-level is set to Error

### ISSUE THREAD

**Issue by WeaponsGradeAutism** [duplicati/duplicati#2533]
I have:
- [ x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61
**Operating System:** Windows 7
**Backend:** S3

### Bug description
Send mail will send mail for backup warnings even when send-mail-level is set to Error. The only example I've seen so far involves a "The process cannot access the file because another process has locked a portion of the file" warning.

### Steps to reproduce
Create a backup configured to send emails on the Error level. Run a backup with one of the files in the dataset locked by another program. Duplicati sends an email even though the file lock only generates a warning.

**Actual result:** Duplicati sends an email containing the file lock warning.
**Expected result:** Duplicati does not send an email because the file lock is a warning and not an error.

### debug log
This is the email that Duplicati sent concerning the file locks:

DeletedFiles: 8567
DeletedFolders: 1027
ModifiedFiles: 1579
ExaminedFiles: 93907
OpenedFiles: 30689
AddedFiles: 29108
SizeOfModifiedFiles: 349208353
SizeOfAddedFiles: 106666927889
SizeOfExaminedFiles: 227917601701
SizeOfOpenedFiles: 107023456536
NotProcessedFiles: 0
AddedFolders: 3544
TooLargeFiles: 0
FilesWithError: 2
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
ParsedResult: Error
VerboseOutput: False
VerboseErrors: False
EndTime: 6/8/2017 11:43:43 PM
BeginTime: 6/8/2017 2:51:04 AM
Duration: 20:52:38.6120741
Messages: [
    Deleting 30 remote fileset(s) ...,
    Deleted 30 remote fileset(s),
    Compacting because there are 156 fully deletable volume(s),
    Deleted 312 files, which reduced storage by 6.88 GB,
    removing file listed as Temporary: duplicati-b5ae25c450a4d4c0da6b5379f214aa201.dblock.zip.aes,
    removing file listed as Temporary: duplicati-ib65141145b9f467cb2b7f066590ff693.dindex.zip.aes
]
Warnings: [
    Failed to process path: C:\Program Files\CZM\FORUM\server\glassfish\domains\archive\osgi-cache\felix\cache.lock => The process cannot access the file because another process has locked a portion of the file.
,
    Failed to process path: C:\Program Files\CZM\FORUM\FORUM-logs\server.log.lck => The process cannot access the file because another process has locked a portion of the file.

]
Errors: []

**Comment by flafleur** [comment]
Did some tests, this issue could be closed.  I didn't get any mail on warning with send-mail-level is set to Error.

**Comment by ts678** [comment]
I couldn't reproduce the issue with a similar test on Duplicati's `control_dir_v2\lock_v2`. Lock specifics were a little different:

"it is being used by another process." instead of "another process has locked a portion of the file.", but it's likely close enough.

 @WeaponsGradeAutism is this still happening for you, using recent software? Maybe something got fixed since original issue.
