### ISSUE TITLE
[Feature Request] Let me delete a file or directory from all backup versions

### ISSUE THREAD

**Issue by jerrac** [duplicati/duplicati#2536]
It would be awesome if I could delete a specific file or directory from all versions of a backup job.

Say I accidentally add my Virtualbox VM directory to my backup job. I don't notice until there are 5 different versions of the job with the unwanted directory in it. I would like to be able to delete the directory from all 5 versions of the job.

Or maybe I live in a fantasy land where I can legally sell the movies I buy digitally. Since I'm paranoid, I have my movies backed up, but once I sell one, I really really shouldn't have that movie any more. So I want to go in and delete it from all my backups.

**Comment by kenkendk** [comment]
That feature has not made it to the UI, but it is in the commandline with the name "purge".
You can invoke it from the new "Commandline UI" from the main page, and stay in the browser.
