### ISSUE TITLE
"Unknown header: 715428368" error

### ISSUE THREAD

**Issue by KCony** [duplicati/duplicati#2541]
I have:
- [ x] searched open and closed issues for duplicates; similar issues were described in #2444 but for backup files larger than 4 GiB (which is not my case) and marked as fixed in canary

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Operating System: Windows 7 Enterprise x64**
**Backend:**

### Bug description
Backup repeatedly fails to finish with "Failed while executing "Backup" with id: 1", specifically "System.NotSupportedException: Unknown header: 715428368 at SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader, Boolean zip64) "

Repairing the database (Advanced - Database - Repair) finishes successfully but doesn't resolve the problem, i.e., subsequent backups fail with the same error as above.

### Steps to reproduce
- Start backup ("Run now")
- Observe the "Error while running [...]" message "Unknown header: 715428368"

**Actual result: Backup job terminates with the error quoted above ** 
**Expected result: Backup completes successfully (without any errors) **

### Screenshots

![2017-06-15_14-58-45](https://user-images.githubusercontent.com/7108039/27197214-699e8c82-51db-11e7-8c40-29fb408862ea.png)

### System info

System properties

    APIVersion : 1
    PasswordPlaceholder : **********
    ServerVersion : 2.0.1.61
    ServerVersionName : - 2.0.1.61_experimental_2017-05-30
    ServerVersionType : Experimental
    BaseVersionName : 2.0.1.35_experimental_2016-12-13
    DefaultUpdateChannel : Experimental
    DefaultUsageReportLevel : Information
    ServerTime : 2017-06-15T01:10:58.9512408-04:00
    OSType : Windows
    DirectorySeparator : \
    PathSeparator : ;
    CaseSensitiveFilesystem : false
    MonoVersion :
    MachineName : ASUSM50VM
    NewLine :
    CLRVersion : 4.0.30319.42000
    CLROSInfo : {"Platform":"Win32NT","ServicePack":"Service Pack 1","Version":"6.1.7601.65536","VersionString":"Microsoft Windows NT 6.1.7601 Service Pack 1"}
    ServerModules : []
    UsingAlternateUpdateURLs : false
    LogLevels : ["Profiling","Information","Warning","Error"]
    SuppressDonationMessages : true
    SpecialFolders : [{"ID":"%MY_DOCUMENTS%","Path":"C:\\Users\\Konstantin Kuzmin\\Documents"},{"ID":"%MY_MUSIC%","Path":"C:\\Users\\Konstantin Kuzmin\\Music"},{"ID":"%MY_PICTURES%","Path":"C:\\Users\\Konstantin Kuzmin\\Pictures"},{"ID":"%MY_VIDEOS%","Path":"C:\\Users\\Konstantin Kuzmin\\Videos"},{"ID":"%DESKTOP%","Path":"C:\\Users\\Konstantin Kuzmin\\Desktop"},{"ID":"%APPDATA%","Path":"C:\\Users\\Konstantin Kuzmin\\AppData\\Roaming"},{"ID":"%HOME%","Path":"C:\\Users\\Konstantin Kuzmin"}]
    BrowserLocale : {"Code":"en-US","EnglishName":"English (United States)","DisplayName":"English (United States)"}
    SupportedLocales : [{"Code":"de","EnglishName":"German","DisplayName":"Deutsch"},{"Code":"en","EnglishName":"English","DisplayName":"English"},{"Code":"es","EnglishName":"Spanish","DisplayName":"español"},{"Code":"fi","EnglishName":"Finnish","DisplayName":"suomi"},{"Code":"fr","EnglishName":"French","DisplayName":"français"},{"Code":"nl-NL","EnglishName":"Dutch (Netherlands)","DisplayName":"Nederlands (Nederland)"},{"Code":"pl","EnglishName":"Polish","DisplayName":"polski"},{"Code":"ru","EnglishName":"Russian","DisplayName":"русский"},{"Code":"zh-CN","EnglishName":"Chinese (Simplified, PRC)","DisplayName":"中文(中华人民共和国)"}]
    BrowserLocaleSupported : true
    backendgroups : {"std":{"ftp":null,"ssh":null,"webdav":null,"openstack":"OpenStack Object Storage / Swift","s3":"S3 Compatible","aftp":"FTP (Alternative)"},"local":{"file":null},"prop":{"s3":null,"azure":null,"googledrive":null,"onedrive":null,"cloudfiles":null,"gcs":null,"openstack":null,"hubic":null,"amzcd":null,"b2":null,"mega":null,"box":null,"od4b":null,"mssp":null,"dropbox":null,"jottacloud":null}}
    GroupTypes : ["Local storage","Standard protocols","Proprietary","Others"]
    Backend modules:

    aftp

    amzcd

    azure

    b2

    box

    cloudfiles

    dropbox

    file

    ftp

    googledrive

    gcs

    hubic

    mega

    onedrive

    openstack

    s3

    od4b

    mssp

    ssh

    tahoe

    webdav
    Compression modules:

    zip

    7z
    Encryption modules:

    aes

    gpg 
	
	
Server state properties

    lastEventId : 360
    lastDataUpdateId : 3
    lastNotificationUpdateId : 1
    estimatedPauseEnd : 0001-01-01T00:00:00
    activeTask :
    programState : Running
    lastErrorMessage :
    connectionState : connected
    xsfrerror : false
    connectionAttemptTimer : 0
    failedConnectionAttempts : 0
    lastPgEvent :
    updaterState : Waiting
    updatedVersion :
    updateReady : false
    updateDownloadProgress : 0
    proposedSchedule : [{"Item1":"2","Item2":"2017-06-17T19:00:00Z"}]
    schedulerQueueIds : []
    pauseTimeRemain : 0

### debug log

A detailed bug report is over 400 GiB, so here's a link to it: https://yadi.sk/d/RPbW09yC3KAhhA

Jun 12, 2017 5:58 AM: Failed while executing "Backup" with id: 1
System.NotSupportedException: Unknown header: 715428368

   at SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader, Boolean zip64)

   at SharpCompress.Common.Zip.SeekableZipHeaderFactory.GetLocalHeader(Stream stream, DirectoryEntryHeader directoryEntryHeader)

   at SharpCompress.Common.Zip.SeekableZipFilePart.LoadLocalHeader()

   at SharpCompress.Common.Zip.SeekableZipFilePart.GetCompressedStream()

   at SharpCompress.Archives.Zip.ZipArchiveEntry.OpenEntryStream()

   at Duplicati.Library.Compression.FileArchiveZip.OpenRead(String file)

   at Duplicati.Library.Main.Volumes.BlockVolumeReader.ReadBlock(String hash, Byte[] blockbuffer)

   at Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction)

   at Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact)

   at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)

   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

   at Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)

   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

   at Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)

   at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

**Comment by kenkendk** [comment]
It sounds like a zip file is broken.
I cannot see from the database which file is causing the problems.
Can you see what file it is failing with?

If we can figure out which file is causing the problems, maybe I can fix it.

**Comment by KCony** [comment]
I manually tested all files in the backup and the only one that fails the CRC check is duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zip of size 1,048,182,424. I assume it is the file that the backup is failing with.

So, what do you think can be done next?

**Comment by kenkendk** [comment]
According to the database, the file should have SHA256 hash `lqq7vlv3tz1D2+4UHXzaW+oKBuxjHiBjLKIi2c6JYug=`.
Can you verify that it has this hash value?

I would very much like a copy of that file, but I realize that it may contain sensitive data.
Are you able/willing to share the file with me?

If not, can you run a tool such as `zipinfo` on the file?
https://superuser.com/questions/120354/analyzing-properties-of-a-zip-file

**Comment by KCony** [comment]
The SHA256 that I get for this file is different. Namely:
96aabbbe5bf7b73d43dbee141d7cda5bea0a06ec631e20632ca222d9ce8962e8

One other observation is that the corrupted file is from 04/13. However, there was a number of backups after 04/13 that completed successfully. The problem with the unknown header first occurred on 06/09, as far as I can tell (unless the log got truncated preventing me from seeing earlier events).

I don't mind sharing the file, if it doesn't contain sensitive data. Could you please point me to a description of how I can check the contents of that zip file. I mean, I can see the contents but I need to know the mapping between the files in the zip and my actual files that were backed up into that zip.

Meanwhile, the zipinfo file is attached.
[duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zipinfo.txt](https://github.com/duplicati/duplicati/files/1088673/duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zipinfo.txt)

**Comment by kenkendk** [comment]
The hex string you have is actually the same as the one I provided (yours is in hex, mine is in base 64). There is a conversion tool here:
http://tomeko.net/online_tools/hex_to_base64.php?lang=en

This indicates that the file was created by Duplicati, uploaded and unchanged. This means the error could only happen due to an error in the zip library, or if the temporary zip file was damaged (due to disk issues) after being written, but before being uploaded.

A problem in the zip library is more likely than a sudden disk hick-up.

Looking at the zipinfo output, it appears that the central-directory-record is correct and read-able. This is surprising as the error from Duplicati indicates that the central-directory-record is damaged.

It is possible that there are actually two (or more) problematic files.
Can you try the following in the WebUI:
1. Click the backup name
2. Click "Commandline ..." in the menu that appears
3. Choose the command "Test" in the dropdown
4. Remove all text from the "Commandline Arguments" field and replace it with the text "all" (without quotes)
5. Click the "Run "test" command now"

This will check each file against the database and sample 20% of the blocks stored inside each archive, and reveal if there is more than a single file that has issues. It is also possible that there is a file that is perfectly valid, but cannot be read by Duplicati's zip library.

**Comment by kenkendk** [comment]
To see what file data the zip volume contains, use the same "Commandline ..." dialog, but choose the "affected" command in the dropdown, and enter the full filename in the "Commandline arguments" text box.

**Comment by KCony** [comment]
You are right, the SHA256 is the same. It was dumb of me to notice that you quoted the hash value in base64.

I tried running the Test command:
![2017-06-21_13-30-04](https://user-images.githubusercontent.com/7108039/27405912-55e8151c-56a1-11e7-85cf-7e0cb2877aff.png)

and it was running fine for about 3 hours. Then I had to restart my Web browser (Mozilla Firefox), for the reasons not related to Duplicati. I didn't expect any problems since I thought that WebUI should not affect how the core application is running. However, after restarting the browser I got this:
![2017-06-21_16-42-22](https://user-images.githubusercontent.com/7108039/27405924-5bff249a-56a1-11e7-9c17-dd787390414a.png)

I will try to execute the Test command over again, making sure the Web browser is not restarted until the command finishes. As soon as I get the results, I will update the post.

Just a side note, the zip file that we started with (duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zip) does appear to be broken. Here's what I get if I try to run "unzip -t "duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zip" > "duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.unzip -t.txt"" on it:
---------------------
file #7787:  bad zipfile offset (local header sig):  797704539
file #7789:  bad zipfile offset (local header sig):  797708996
file #7792:  bad zipfile offset (local header sig):  797713831
---------------------
The full output is attached below:
[duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.unzip -t.txt](https://github.com/duplicati/duplicati/files/1092862/duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.unzip.-t.txt)

**Comment by KCony** [comment]
I tried running the Affected command but obviously I'm doing something wrong since I'm getting that no files are affected. See the screen shots below:
![2017-06-21_13-28-51](https://user-images.githubusercontent.com/7108039/27406127-f8442148-56a1-11e7-976d-6b07d26626e2.png)
![2017-06-21_13-29-11](https://user-images.githubusercontent.com/7108039/27406132-fb6a15a8-56a1-11e7-90e2-393ffdb38c7c.png)

**Comment by kenkendk** [comment]
For the "Affected", you need to run it with just the filename in the arguments area, i.e. remove the `I:\` text.

**Comment by KCony** [comment]
Tried it 
![2017-06-21_19-42-19](https://user-images.githubusercontent.com/7108039/27411146-e04a51d0-56b9-11e7-9e98-63ce9ab162d5.png)

but still no luck:
![2017-06-21_19-42-32](https://user-images.githubusercontent.com/7108039/27411152-eaec9576-56b9-11e7-861d-e2401d90f927.png)

**Comment by kenkendk** [comment]
I was being unclear, you need to remove this `I:\`:
![27406127-f8442148-56a1-11e7-976d-6b07d26626e2](https://user-images.githubusercontent.com/1510755/27422036-10e3ff26-572d-11e7-9abf-46ad27d02498.png)

And keep the target path

**Comment by KCony** [comment]
Test command finished successfully, and it looks like the zip file we've been dealing with is the only broken one:
![2017-06-22_09-45-33](https://user-images.githubusercontent.com/7108039/27437278-c378176a-572f-11e7-83a6-763fb272d110.png)

Here's the full command output:
[Duplicati_test.txt](https://github.com/duplicati/duplicati/files/1094960/Duplicati_test.txt)

**Comment by KCony** [comment]
Thank you for detailed directions! I was able to get the list of files from that zip. Unfortunately, it does contain personal data which I would not like to share...

**Comment by kenkendk** [comment]
Ok, then we must play a bit of find-the-needle-in-the-haystack remotely :)

I will write a small diagnosis program that tries to read through the file, and tells where the problem occurs. Hopefully we can use that to pinpoint the error.
I would appreciate if you can keep a copy of the broken zip file somewhere,

To recover from the error, start by deleting the file from the backup folder (and please keep a copy for more diagnosis).
Then run the "repair" command (under "Database"), and see if it is possible to re-create the file.

If this is not possible, go to the commandline UI again, and use the command `list-broken-files` (leave the "Commandline arguments" field empty).
The output shows you what will happen when you run the `purge-broken-files` command, so run that command next to have all references to the affected files purged from the remote destination.

Then run a backup to have the files re-inserted into the backup.

**Comment by kenkendk** [comment]
Ok, I wrote a small tool for this:
https://dl.dropboxusercontent.com/u/15251537/ZipFileDebugger.zip

Run it on the commandline, with the broken zip file as input, and it will output debug information for each file. I will then compare this to the output from zipinfo and see if I can pinpoint the exact problem(s).

**Comment by KCony** [comment]
Here are the results of running the ZipFileDebugger tool.
Command line:
ZipFileDebugger.exe ..\duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zip > duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zipfiledebugger.txt

Output:
[duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zipfiledebugger.txt](https://github.com/duplicati/duplicati/files/1099062/duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.zipfiledebugger.txt)

Will report how the repairing went later tonight.

**Comment by kenkendk** [comment]
Thanks. It clearly shows that there are three defects in the zip file:
```
MNaVpdIf88YtSBurF94dVYMkOyucZ_iK1euGzwz1Voc=
Lq4jbn8KaPH-6_NeXGQcoTJwTx3MoBSRSeAyODiKHxM=
bS2aFzrSRqZtIPWkrqc8DYoWTfsZa37XUInTT66O5F8=
```

If I look at these files in the `zipinfo` report, it says `There are an extra 148 bytes preceding this file.`, with the second file only having `74` bytes (half).

I will see if I can find out more with the data I have.

**Comment by KCony** [comment]
OK, here's what happened when I tried to do "Repair" (first part of your message from 20170623T0403Z-0400).

I deleted the faulty file from the backup folder, and ran Database -> Repair. Just a few seconds later (perhaps a minute), got the following error:
![2017-06-23_17-16-12](https://user-images.githubusercontent.com/7108039/27500906-761c33b6-5838-11e7-91cc-f9cab16434fa.png)

Clicked "Show" in the error message and got this:
![2017-06-23_17-17-01](https://user-images.githubusercontent.com/7108039/27500968-bcb0178e-5838-11e7-9edc-12425003d47c.png)

As you can see, no message was logged here for the Repair command (today is June 23). Then I switched to the "Remote" log and got this:
![2017-06-23_17-17-46](https://user-images.githubusercontent.com/7108039/27501005-de03b364-5838-11e7-889d-e8e8f97d029e.png)

The full text of this message is below:
[duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.repair.20170623T1714.txt](https://github.com/duplicati/duplicati/files/1099103/duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.repair.20170623T1714.txt)

This is the only even from today, as can be seen here:
![2017-06-23_17-25-54](https://user-images.githubusercontent.com/7108039/27501042-11be5dee-5839-11e7-970a-57f739a4431b.png)


Do you want me to proceed with the second part of your directions from the same message (i.e., doing "list-broken-files")?

**Comment by KCony** [comment]
Yes, and the results of running your zip debugging tool seem to be consistent with the standard unzip -t which I posted earlier (duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.unzip -t.txt).

**Comment by KCony** [comment]
Executing list-broken-files followed by the purge-broken-files was successful:

[duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.purge-broken-files.20170623T2248.txt](https://github.com/duplicati/duplicati/files/1099818/duplicati-b47589dcc08af42af980f6d619d10d42d.dblock.purge-broken-files.20170623T2248.txt)

A subsequent backup also completed without any errors.

**Comment by kenkendk** [comment]
Great! I continue to attempt to locate the problem with the original zip file.

**Comment by KCony** [comment]
Awesome! Let me know if/how I can help.

**Comment by ts678** [comment]
This was pretty actively pursued in 2017 but probably infeasible to pick up now. Is the bug still present? I will assume it's gone.
[Upload throttle corrupts backup, especially OneDrive. Analyzed, with code proposed. #3787](https://github.com/duplicati/duplicati/issues/3787) was corrupting headers for awhile.
Whether or not the 2019 fix applies, I think this old issue needs a refresh if it's still of interest. If not, it will eventually be closed.
