### ISSUE TITLE
error restoring

### ISSUE THREAD

**Issue by computermaster21** [duplicati/duplicati#2548]
## Version info

**Duplicati Version:** 2.0.1.61
**Operating System:** Windows 10 Pro x64
**Backend:**

### Bug description
Cannot restore directly from backup files that have a custom backup prefix.

### Steps to reproduce
- Open Duplicati GUI
- Go to restore
- Select restore from backup files
- Under advanced options, a text says that you can use for example "--backup-prefix" like in command line.

**Actual result:** Error says you forget to use backup-prefix.
**Expected result:** No Errors

Found the problem -- is that the example given is wrong, it should say "--prefix" instead of "--backup-prefix"

**Comment by kenkendk** [comment]
Yes, that is confusing. 
Great that you figured it out!

I will fix the text.
