### ISSUE TITLE
Duplicati Rock-on Issue

### ISSUE THREAD

**Issue by cameramanscott** [duplicati/duplicati#2549]
I am trying to configure the Duplicati Rock-on and I am attempting to backup a Samba Share. However when I am in the GUI for Duplicati I can not select the Share. I have attached 2 images, the first one shows the treeview in Duplicati and the second shows the treeview from WINSCP. The Share I want to backup is located under "mnt2", however that location is not visible in Duplicati.

Appreciate any help. I attempted to add the path /mnt2/"share name"/ however I get an error message from Duplicati advising me location doesn't exist.

Cheers

![duplicati-rockstor-issue-image1](https://user-images.githubusercontent.com/29434875/27288870-19aeaa10-54d6-11e7-92cf-7a54bbb5a665.JPG)

![duplicati-rockstor-issue-image2](https://user-images.githubusercontent.com/29434875/27288897-28b18b36-54d6-11e7-9fab-aa9553528f79.JPG)

I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 0.0.0.0
**Operating System:**
**Backend:**

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

**Comment by kenkendk** [comment]
Not sure what is happening here. The screenshot with the folders appears to be from a Windows machine, but Rockstor is Linux based.

Most likely, the mount point is not visible to the container that is running Duplicati.
