### ISSUE TITLE
Include filter being ignored v1.3.4

### ISSUE THREAD

**Issue by heidi-de** [duplicati/duplicati#2550]
I have:
- [x ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 1.3.4
**Operating System:** Windows 2012 R2
**Backend:**

### Bug description
--include filter ignored

### Steps to reproduce
- I have a directory called c:\scripts\backup. In this directory are 3 files: start_backup.cmd start_backup.ps1 and new text document.txt
- I am backing up to softlayer/bluemix object storage using the following command:
duplicati.commandline.exe "c:\scripts\backup" "cloudfiles://Test" --full-if-more-than-n-incrementals=7 --passphrase="***" --cloudfiles-username="***" --cloudfiles-accesskey="***" --cloudfiles-authentication-url="https://fra02.objectstorage.service.networklayer.com/auth/v1.0/" --volsize=100MB --include="\*.ps1"

**Actual result:** including *.ps1 is ignored. If I use exclude="\*.cmd" then the cmd file is correctly excluded
**Expected result:** only the single start_backup.ps1 file should be backed up

**Comment by kenkendk** [comment]
We are no longer maintaining 1.3.x.

Files should be included by default, so adding a single include filter has no effect in 1.3.x.
