### ISSUE TITLE
Building Duplicati for Windows with build-msi.bat: vsvars32.bat, 7z and msbuild not found

### ISSUE THREAD

**Issue by crazy4chrissi** [duplicati/duplicati#2553]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61_experimental_2017-05-30 (version I am trying to build)
**Operating System:** Windows 7 Professional 64bit
**Backend:** (none / build for Windows using build-msi.bat)

### Bug description
I am trying to build a customized version of duplicati. I have read the wiki here:
https://github.com/duplicati/duplicati/wiki/Branding-and-OEM-customization
It says to run Installer/Windows/build-msi.bat, I need msbuild.
I have installed:
- Build Tools for Visual Studio 2017, Version 15.2 (26430.12)
- Visual Studio Community 2017 (2), Version 15.2 (26430.13)
- .NET Framework 4.6.1
- WiX Toolset v3.11.0.1701
- Visual C++ 2017 Redistributable (both x64 and x86, plus older versions)
- 7-Zip 16.04 (x64)

### Steps to reproduce
- I run C:\[...]\duplicati\Installer\Windows\build-msi.bat ..\oem\duplicati-2.0.1.61_experimental_2017-05-30.zip

**Actual result:** 
C:\[...]\duplicati\Duplicati.msi konnte nicht gefunden werden
C:\[...]\duplicati\Duplicati-32bit.msi konnte nicht gefunden werden
Der Befehl ""F:\Programme\MS Visual Studio 14.0\Common7\Tools\vsvars32.bat"" ist
 entweder falsch geschrieben oder konnte nicht gefunden werden.
Der Befehl "7z" ist entweder falsch geschrieben oder konnte nicht gefunden werden.
Installing OEM files
..\oem\duplicati-2.0.1.61_experimental_2017-05-30(1).zip
..\oem\duplicati-2.0.1.61_experimental_2017-05-30-x64.msi
..\oem\duplicati-2.0.1.61_experimental_2017-05-30.zip
3 Datei(en) kopiert
Das System kann die angegebene Datei nicht finden.
Das System kann die angegebene Datei nicht finden.
Der Befehl "msbuild" ist entweder falsch geschrieben oder konnte nicht gefunden werden.
Das System kann den angegebenen Pfad nicht finden.
Der Befehl "msbuild" ist entweder falsch geschrieben oder konnte nicht gefunden werden.
Das System kann den angegebenen Pfad nicht finden.

**Expected result:** 

- I would expect that vsvars32.bat is found somewhere as part of "Build Tools for Visual Studio 2017". Actually, the path it searches for (F:\Programme\MS Visual Studio 14.0) is where I had an older (?) version of Visual Studio installed about a year ago, but this version has long been uninstalled.
I searched my whole drive for vsvars32.bat, but could not find it.
- I would expect that "msbuild" is part of "Build Tools for Visual Studio 2017" and that it adds the required path to PATH if necessary. I can find various MSBuild.exe, especially one in C:\Windows\Microsoft.NET\Framework and  C:\Windows\Microsoft.NET\Framework64
- I guess I need to add the path to the 7-Zip binary to the PATH? Why does the wiki not mention that I need 7z?

Do I need to install something else or some older version of the build tools? Where can I download the correct version?

**Comment by kenkendk** [comment]
`vsvars32.bat` is the batch file setting up the build environment. It should set up the environment variables required to find `msbuild.exe`. You should be able to find the batch file by searching for the "Run Visual Studio Commandline" shortcut in your start menu.

The path you see is from the environment variable `%VS140COMNTOOLS%`:
https://github.com/duplicati/duplicati/blob/master/Installer/Windows/build-msi.bat#L12

I think this version (14) is used because I have an older version of Visual Studio installed in the build machine. Try changing it to `%VS150COMNTOOLS%` and see what happens.

I expected 7z to automatically install itself in `PATH`:
http://www.7-zip.org/download.html

And feel free to change the wiki and add the 7z requirement.

**Comment by crazy4chrissi** [comment]
Thanks a lot for your reply. 

I think `vsvars32.bat` might not be there anymore in Visual Studio 2017. Anyway, I uninstalled Visual Studio 2017 and tried to install 2015. It would not allow me to install anywhere other than `F:\Programme\MS Visual Studio 14.0`, where I had installed it some time ago, but this drive is not there anymore in my system. So there seems to be some leftovers and I used the  [VisualStudioUninstaller](https://github.com/Microsoft/VisualStudioUninstaller/releases) to get rid of everything (attention: this will remove _lots_ of stuff like .NET Framework and MS C++ redistributable, so some programs will be broken until you install these again) . I then installed Visual Studio 2015 successfully.

Now I have a `vsvars32.bat` and the build script is able to find it. I tried installing the newest 7-zip, both the 64bit exe and msi installers don't add 7zip to PATH, so I just adjusted the build script and added the path to 7-zip there. Now I get a new error:

`MSBUILD : error MSB1003: Geben Sie eine Projekt- oder Projektmappendatei an. Das
 aktuelle Arbeitsverzeichnis enthält keine Projekt- oder Projektmappendatei.`

I am not sure if you understand German, the error in English would be:

`error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`

The complete output:

```
C:\[...]>duplicatiGIT\Installer\Windows\build-msi.bat duplicati-2.0.1.61_experimental_2017-05-30.zip
Das System kann die angegebene Datei nicht finden.
C:\[...]\Duplicati.msi konnte nicht gefunden werden
C:\[...]\Duplicati-32bit.msi konnte nicht gefunden werden

7-Zip 17.00 beta (x64) : Copyright (c) 1999-2017 Igor Pavlov : 2017-04-29

Scanning the drive for archives:
1 file, 14204253 bytes (14 MiB)

Extracting archive: duplicati-2.0.1.61_experimental_2017-05-30.zip
--
Path = duplicati-2.0.1.61_experimental_2017-05-30.zip
Type = zip
Physical Size = 14204253

Everything is Ok

Files: 523
Size:       50616994
Compressed: 14204253
Das System kann die angegebene Datei nicht finden.
Das System kann die angegebene Datei nicht finden.
Microsoft (R)-Buildmodul, Version 14.0.25420.1
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

MSBUILD : error MSB1003: Geben Sie eine Projekt- oder Projektmappendatei an. Das
 aktuelle Arbeitsverzeichnis enthält keine Projekt- oder Projektmappendatei.
Das System kann den angegebenen Pfad nicht finden.
Microsoft (R)-Buildmodul, Version 14.0.25420.1
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

MSBUILD : error MSB1003: Geben Sie eine Projekt- oder Projektmappendatei an. Das
 aktuelle Arbeitsverzeichnis enthält keine Projekt- oder Projektmappendatei.
Das System kann den angegebenen Pfad nicht finden.
```

Any idea how to fix this? Where should the project file be coming from?

Once I got this successfully built I will add some more info to the wiki, like that 7-zip is required.

**Comment by kenkendk** [comment]
You need to be in the folder, so try with:
```
C:\[...]>cd duplicatiGIT\Installer\Windows\
C:\[...]\duplicatiGIT\Installer\Windows>build-msi.bat ..\..\..\duplicati-2.0.1.61_experimental_2017-05-30.zip
```

**Comment by crazy4chrissi** [comment]
Ah, thank you very much. Yes, now it compiles successfully :-)

I slightly adjusted the wiki. So I think the issue is solved.

**Comment by kenkendk** [comment]
Thanks for fixing the wiki!
