### ISSUE TITLE
backup does not work with files with a "~" symbol in the file name.

### ISSUE THREAD

**Issue by sunwayru** [duplicati/duplicati#2555]
Duplicati.Library.Interface.UserInformationException: Invalid path: «D:\distr\Quik\C:\Users\DmitryC:\Users\Dmitry.txt» System.NotSupportedException: This path format is not supported..
----------------------------------------
### Version info
2.0.1.61_experimental_2017-05-30

**Comment by kenkendk** [comment]
This happens because Duplicati expands `~` into the "user home" as is custom on Linux-based operating systems.
Where do you enter the path?

**Comment by sunwayru** [comment]
I use Duplicati 2.0.1.61_experimental_2017-05-30 for Windows 10.
File names like 'd:/.../~.txt' valid in OS, but Duplicati can't work with them :(

**Comment by kenkendk** [comment]
Duplicati should not expand the paths inside the backup, it only expands paths from the user.

What backup source paths do you enter?
Can you provide a screenshot of this page (Source Data) on your system:
https://www.duplicati.com/articles/Getting-Started/#lg=1&slide=0

**Comment by sunwayru** [comment]
Source Data:
   D:\distr\Quik\~~.txt
   D:\distr\Microsoft Office\~~.txt
screenshot: http://prntscr.com/fr06bv

throws error: http://prntscr.com/fr07gx

**Comment by warwickmm** [comment]
Related to #2619.

**Comment by TekkiWuff** [comment]
Could this get closed, cause tilde expansion isn't supported anymore since PR #2836?

**Comment by warwickmm** [comment]
Yes.  @kenkendk, can you close this?

**Comment by kenkendk** [comment]
Closed :)
