### ISSUE TITLE
box.com : Backup failed "The requested file does not exist"

### ISSUE THREAD

**Issue by gillesgagniard** [duplicati/duplicati#2557]
I have:
-  [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Operating System:** macOS 10.12.5
**Backend:** Box.com

### Bug description
Upon completing a backup where destination is on Box.com, the verification steps issues several "The requested file does not exist" errors, as can be seen in the debug logs below.
Also, trying to restore the same backup ends up in error, all files with blocks in those missing files fail to restore.

What is strange is that those files actually exist on my Box.com account !

I tried to download the allegedly missing file using the BackendTool, and that fails too:
`
/Applications/Duplicati.fixed.app/Contents/Resources> mono Duplicati.CommandLine.BackendTool.exe list box://user:password@/backup --authid=redacted | grep b232d4d2b21
duplicati-b232d4d2b21f242f59873e5a90ff1ef80.dblock.zip.aes	File	6/19/2017 1:46:29 PM	49.99 MB
/Applications/Duplicati.fixed.app/Contents/Resources> mono Duplicati.CommandLine.BackendTool.exe get box://user:password@/backup/duplicati-b232d4d2b21f242f59873e5a90ff1ef80.dblock.zip.aes --authid=redacted /tmp/test
Command failed: The requested folder does not exist
`

### Steps to reproduce
- backup to a target on Box.com
- read the logs and see verification failures
Also
- try to restore from a Box.com location
- get an incomplete restore because of allegedly missing files on backend

### debug log
[backup-box-failed.txt](https://github.com/duplicati/duplicati/files/1094767/backup-box-failed.txt)

**Comment by kenkendk** [comment]
Is it a sync problem, in that it takes a while before the box.com servers are synced?
In other words, if you try the exact same `GET` command now, are the files still reported as missing?

**Comment by gillesgagniard** [comment]
Sorry the command was wrong the first time, here is the correct output (doesn't change anything though) :

`
/Applications/Duplicati.fixed.app/Contents/Resources> mono Duplicati.CommandLine.BackendTool.exe list box://user:password@/backup --authid=redacted | grep b232d4d2b21
duplicati-b232d4d2b21f242f59873e5a90ff1ef80.dblock.zip.aes	File	6/19/2017 1:46:29 PM	49.99 MB
/Applications/Duplicati.fixed.app/Contents/Resources> mono Duplicati.CommandLine.BackendTool.exe get box://user:password@/backup --authid=redacted duplicati-b232d4d2b21f242f59873e5a90ff1ef80.dblock.zip.aes
Command failed: The requested file does not exist
`

As you can see in the 'list' output, file has been uploaded 4 days ago, but is still reported as missing by the 'get' command, (and it appears in the box.com UI and is downloadable there).

Is there some BackendTool option to get more debugging output ?

**Comment by kenkendk** [comment]
Can you see properties on the file in box's UI ? I am guessing that it is in some kind of protected/guarded state?

There are no more outputs to get from the BackendTool, but you can get the network traffic trace.
To do this, place the attached file [Duplicati.CommandLine.BackendTester.exe.config.txt](https://github.com/duplicati/duplicati/files/1113409/Duplicati.CommandLine.BackendTester.exe.config.txt) in the folder with `Duplicati.CommandLine.BackendTester.exe` and make sure the file is named `Duplicati.CommandLine.BackendTester.exe.config` (remove the .txt I added for GitHub to accept it).

This will create a `network.log` file in the folder that has all the network traffic dumped so you can see each call and response.

**Comment by kenkendk** [comment]
More documentation on the file and format: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing
