### ISSUE TITLE
Duplicati.GUI.TrayIcon.exe crashes after startup

### ISSUE THREAD

**Issue by tkald** [duplicati/duplicati#2560]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** duplicati-2.0.1.67_canary_2017-06-21-x64
**Operating System:** Windows 10 v1703
**Backend:** network share

### Bug description
After trying to upgrade Duplicati over web interface from version 2.0.1.66 to 2.0.1.67 (which failed), I'm not able to start Duplicaty.
Error in Windows event log:

> Application: Duplicati.GUI.TrayIcon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunMethod(MethodInfo method, String[] args)
   at Duplicati.Library.AutoUpdater.UpdaterManager.<>c__DisplayClass53_0.<RunFromMostRecent>b__0()
   at Duplicati.Library.AutoUpdater.UpdaterManager.WrapWithUpdater(AutoUpdateStrategy defaultstrategy, Action wrappedFunction)
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(MethodInfo method, String[] cmdargs, AutoUpdateStrategy defaultstrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(System.String[])

Update itself died with error:

> Application: Duplicati.GUI.TrayIcon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
Exception Info: System.IO.FileLoadException
   at Duplicati.Library.AutoUpdater.UpdaterManager..cctor()
Exception Info: System.TypeInitializationException
   at Duplicati.Library.AutoUpdater.UpdaterManager.set_RequiresRespawn(Boolean value)
   at Duplicati.GUI.TrayIcon.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(System.String, System.String[])
   at Duplicati.Library.AutoUpdater.UpdaterManager.RunFromMostRecent(System.Reflection.MethodInfo, System.String[], Duplicati.Library.AutoUpdater.AutoUpdateStrategy)
   at Duplicati.GUI.TrayIcon.Program.Main(System.String[])

Also uninstalled / reinstalled Duplicaty, same (first) error on startup.

**Comment by jidea** [comment]
had the same problem after trying to update to 2.0.1.61-experimental.
tried upgrading to 2.0.1.67-canary but noluck. duplicati-gui-trayicon crash.
windows 10 x64 uptodate
multiple backend (google,ssh,local)

**Comment by kenkendk** [comment]
I think there might be a partial update lurking around that Duplicati finds, but somehow fails to load.

Try looking in the folder `%APPDATA%Duplicati\updates` and delete the `2.0.1.67` folder.
In the `%APPDATA%Duplicati` folder you should also see a `duplicati-crashlog.txt` file, can you post the contents here?

**Comment by yymsc** [comment]
Hi Kenneth,

I'm having the same problem: after updating from 2.0.1.66 to 2.0.1.67 on Windows 64bit Duplicati.GUI.TrayIcon.exe crashes after a few seconds.
I attached Duplicati-crashlog.txt

[Duplicati-crashlog.txt](https://github.com/duplicati/duplicati/files/1097325/Duplicati-crashlog.txt)

**Comment by tkald** [comment]
I don't remember seeing duplicati-crashlog.txt fail or updates subfolder in %APPDATA%roaming\duplicati folder. 

I was however able to run Duplicati.Server.exe, export my backup conf. Then I renamed Duplicati-server.sqlite file and Duplicati.GUI.TrayIcon.exe started again.

Of course I needed to reimport my backup defination and repair backup database.
But at least I got Duplicati working again.

**Comment by jidea** [comment]
Thanks tkald. followed your instructions and got it. thanks again

**Comment by PJai** [comment]
I had the same issue after updating from 2.0.1.66 to 2.0.1.67. tkald's fix helped me too, thanks

Win 10 v1703 - 15063.413

**Comment by tkald** [comment]
Today I had the same crash issue with new Duplicati v2.0.1.67 installation, not with upgrade.
Everything was working fine until I set UI password. 
After that, I wasn't able to log in with password I just set - error of wrong password.

Tried to restart Duplicati, but Duplicati.GUI.TrayIcon.exe crashed...

**Comment by PJai** [comment]
Same issue here. I just set UI password 2 Minutes ago and now i am not able to start Duplicati.GUI.TrayIcon.exe. I am getting the same two Windows Errors in the Event log as tkald mentioned in the first post. FIX: I had to rename Duplicati-server.sqlite again.

Error after setting UI password:
![2017-06-27 00_54_08-duplicati login](https://user-images.githubusercontent.com/22389964/27563760-d07f09bc-5ad3-11e7-81bf-bb39c4365af4.png)

I also get a Missing XSRF Token Error when starting the GUI for the first time after deleting Duplicati-server.sqlite 

![2017-06-27 00_48_51-duplicati](https://user-images.githubusercontent.com/22389964/27563813-291ca976-5ad4-11e7-9d2b-7554d460176f.png)

Same Error on _Firefox 54.0 64bit_ and _Chrome 58.0.3029.110 (64-bit)_

**Comment by mnaiman** [comment]
@yymsc I have made fix for that at https://github.com/duplicati/duplicati/pull/2558

**Comment by kenkendk** [comment]
I think the original error is fixed with @mnaiman 's patch, I will make a new build with that fix included once it has passed the CI test.

**Comment by jasonnm** [comment]
Thanks Tkald! Worked for me, too!

**Comment by sclukey** [comment]
FWIW, I just got this issue when trying to upgrade from 2.0.1.61_experimental_2017-05-30. I removed the `updates` folder from `C:\ProgramData\Duplicati` (it was not in %appdata%) and Duplicati started fine again. It still says I need to update, presumably because the attempted update didn't actually finish, but it works anyway.

**Comment by sclukey** [comment]
tkald's fix didn't work for me. I just uninstalled/reinstalled then imported/restored my backup. I lost the logs when I did that, so I guess I can't be very helpful anymore, sorry about that

**Comment by Bazzu85** [comment]
so any news about working update??

**Comment by jidea** [comment]
i don't update anymore duplicati with the internal update. i download the new version and i install it. no more problem

**Comment by jlherren** [comment]
I have the same issue. The tray icon disappears shortly after starting up. If I run Duplicati.Server.exe manually I get this after a few seconds:
![image](https://user-images.githubusercontent.com/1890851/36200289-7e8c215c-117c-11e8-95db-535f7d068653.png)

**Comment by ts678** [comment]
Reports of this 2017/2018 issue seem to have stopped. Assuming it's no longer a bug, and giving last call for any objections.
