### ISSUE TITLE
duplicati upload stalls from time to time

### ISSUE THREAD

**Issue by atlas147** [duplicati/duplicati#2561]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61
**Operating System:** Windows 10
**Backend:** Amazon Cloud Drive

### Bug description
Upload speeds are great at the start, then just nothing for several hours before the bar moves again, each time taking another 500mb chunk (i have the upload volume size to be 500mb), before stopping again.

### Steps to reproduce
- every time I run a backup

**Actual result:** upload stalls after the web interface said that it has uploaded some data
**Expected result:** unsure if this is normal behaviour for the uploader>

### Screenshots

![image](https://user-images.githubusercontent.com/29648949/27471001-ce09e466-5828-11e7-9f8b-a8ca4a7865cc.png)

### debug log

Jun 23, 2017 2:20 PM: CommitAddBlockToOutputFlush took 00:00:01.312
Jun 23, 2017 2:20 PM: Starting - CommitAddBlockToOutputFlush
Jun 23, 2017 2:20 PM: ExecuteReader: SELECT DISTINCT "Hash", "Size" FROM "Block" WHERE "VolumeID" = ? took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteReader: SELECT DISTINCT "Hash", "Size" FROM "Block" WHERE "VolumeID" = ?
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jun 23, 2017 2:20 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jun 23, 2017 2:20 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash",

**Comment by kenkendk** [comment]
The backup process creates a maximum of 2 files ahead of time. It sounds like you get "great speed" when there is no uploading going on. As soon as two 500mb volumes are created, the backup process stalls until it has finished an upload.

In other words, it sounds like the upload speed is the limiting factor.
Can you see the upload speeds in TaskManager? Do they seem to fir with the speed of your internet connection?

**Comment by atlas147** [comment]
It seems to be uploading but the speeds are not representative of the speeds I should be getting. Even with the normal amazon cloud drive app I am getting at least 3 MB/s, whereas running duplicati I have been uploading 16GB of data for 4 hours now and still I'm not half way through

**Comment by ts678** [comment]
Amazon Cloud Drive is gone. Unless this happens on a different storage destination which will allow debug, can issue be closed?

Provided `debug log` shows nothing directly related to upload speed. Info is there (including speed stats), just not in that quote.
Reading logs at `retry` level would let you estimate speed from time. Task Manager can show you upload speed and fluctuation, which could happen if uploading gets ahead. It may take Duplicati some time to collect enough data to fill next dblock to upload.

You can look at Temp files.  `dir` doesn't get sizes, but PowerShell `ls $env:TEMP\dup* | sort -Property LastWriteTime` does.

If you decide to look closely, note current Duplicati upload defaults to 4 files concurrently. This logs confusingly, but helps speed.

**Comment by warwickmm** [comment]
Support for Amazon Cloud Drive has been discontinued.  If this is still occurring with a different backend, please reopen and provide new details.
