### ISSUE TITLE
A weird icon in the taskbar tray

### ISSUE THREAD

**Issue by Rushkurdi** [duplicati/duplicati#2565]
everytime i restart my laptop, i see a white icon then it disappears after 2-3 seconds, so i got little worry about it, help if anyone know wat it is ? ( the top icon on the left ).

thanks in [advance.[](url)](url
![untitled](https://user-images.githubusercontent.com/18216215/27519770-97a0b59c-59fb-11e7-8d2c-26e3328fefaa.jpg)
)

**Comment by kees-z** [comment]
That doesn't look like a Duplicati icon. You probably can find out what is it using the Task Manager:
- Start the Task Manager by pressing Ctrl+Shift+Esc
- If you don't see any tabs, click "More details"
- Click the tab "Startup"
- Probably the same icon is listed there. Right click on it and choose "Properties" to view more details.

**Comment by Rushkurdi** [comment]
thanks for the reply ,but i've already done that and scanned the laptop with malwarebyte and antivirus.

**Comment by sjonez** [comment]
What makes you think this is related to Duplicati?

**Comment by kenkendk** [comment]
Very unlikely that this is related to Duplicati, there are no such icons in the Duplicati package.

**Comment by Rushkurdi** [comment]
i did not think it is related to Duplicati, i'm just wondering what is this weird icon that disappears after 2 sec.

**Comment by sjonez** [comment]
But you do realise you're asking this in the duplicati issues forum?

**Comment by Rushkurdi** [comment]
oh ok my bad ! thanks everyone
