### ISSUE TITLE
icon in Gnome notification area does not have a context menu

### ISSUE THREAD

**Issue by timrichardson** [duplicati/duplicati#2568]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** You are currently running Duplicati - 2.0.1.61_experimental_2017-05-30
**Operating System:**
Ubuntu 17.04 Gnome (ubuntu-gnome-desktop)
**Backend:**

### Bug description
Describe here the issue that you are experiencing.
duplicati adds an icon to the notification bar, but it has no context menu. So there is easy way to browse to localhost:8200 or to do other admin actions. 

### Steps to reproduce
install from the debian/ubuntu .deb 

### debug log

APIVersion : 1
PasswordPlaceholder : **********
ServerVersion : 2.0.1.61
ServerVersionName : - 2.0.1.61_experimental_2017-05-30
ServerVersionType : Experimental
BaseVersionName : 2.0.1.61_experimental_2017-05-30
DefaultUpdateChannel : Experimental
DefaultUsageReportLevel : Information
ServerTime : 2017-06-27T12:48:21.176335+10:00
OSType : Linux
DirectorySeparator : /
PathSeparator : :
CaseSensitiveFilesystem : true
MonoVersion : 4.6.2
MachineName : raffles
NewLine :
CLRVersion : 4.0.30319.42000
CLROSInfo : {"Platform":"Unix","ServicePack":"","Version":"4.10.0.24","VersionString":"Unix 4.10.0.24"}
ServerModules : []
UsingAlternateUpdateURLs : false
LogLevels : ["Profiling","Information","Warning","Error"]
SuppressDonationMessages : false
SpecialFolders : [{"ID":"%MY_DOCUMENTS%","Path":"/home/tim"},{"ID":"%MY_MUSIC%","Path":"/home/tim/Music"},{"ID":"%MY_PICTURES%","Path":"/home/tim/Pictures"},{"ID":"%DESKTOP%","Path":"/home/tim/Desktop"},{"ID":"%HOME%","Path":"/home/tim"}]
BrowserLocale : {"Code":"en-US","EnglishName":"English (United States)","DisplayName":"English (United States)"}
SupportedLocales : [{"Code":"de","EnglishName":"German","DisplayName":"Deutsch"},{"Code":"en","EnglishName":"English","DisplayName":"English"},{"Code":"es","EnglishName":"Spanish","DisplayName":"español"},{"Code":"fi","EnglishName":"Finnish","DisplayName":"suomi"},{"Code":"fr","EnglishName":"French","DisplayName":"français"},{"Code":"nl-NL","EnglishName":"Dutch (Netherlands)","DisplayName":"Nederlands (Nederland)"},{"Code":"pl","EnglishName":"Polish","DisplayName":"polski"},{"Code":"ru","EnglishName":"Russian","DisplayName":"русский"},{"Code":"zh-CN","EnglishName":"Chinese (Simplified)","DisplayName":"中文 (中国)"}]
BrowserLocaleSupported : true
backendgroups : {"std":{"ftp":null,"ssh":null,"webdav":null,"openstack":"OpenStack Object Storage / Swift","s3":"S3 Compatible","aftp":"FTP (Alternative)"},"local":{"file":null},"prop":{"s3":null,"azure":null,"googledrive":null,"onedrive":null,"cloudfiles":null,"gcs":null,"openstack":null,"hubic":null,"amzcd":null,"b2":null,"mega":null,"box":null,"od4b":null,"mssp":null,"dropbox":null,"jottacloud":null}}
GroupTypes : ["Local storage","Standard protocols","Proprietary","Others"]
Backend modules: aftp amzcd azure b2 box cloudfiles dropbox ftp file googledrive gcs hubic mega onedrive openstack s3 ssh od4b mssp tahoe webdav
Compression modules: zip 7z
Encryption modules: aes gpg
Server state properties

lastEventId : 9
lastDataUpdateId : 1
lastNotificationUpdateId : 0
estimatedPauseEnd : 0001-01-01T00:00:00
activeTask :
programState : Running
lastErrorMessage :
connectionState : connected
xsfrerror : false
connectionAttemptTimer : 0
failedConnectionAttempts : 0
lastPgEvent :
updaterState : Waiting
updatedVersion :
updateReady : false
updateDownloadProgress : 0
proposedSchedule : []
schedulerQueueIds : []
pauseTimeRemain : 0

**Comment by timrichardson** [comment]
I am not using duplicati at the moment so you should probably close this. Mint is not a derivative of current gnome, it is fork of a very old version of gnome, so absolutely do not rely on Mint to reproduce UI bugs reported by Ubuntu or Fedora users.

**Comment by kenkendk** [comment]
Closing this as Duplicati now uses Avalonia for the tray icon instead of GtkSharp.
