### ISSUE TITLE
The Remoteserver returned an error 460

### ISSUE THREAD

**Issue by Photographix** [duplicati/duplicati#2572]
I have:
- [X ] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.68_canary_2017-06-28
**Operating System:** Windows 10 (1703 / Build 16226.1000)
**Backend:** Jottacloud

### Bug description
Upload Error by Jottacloud

### Steps to reproduce
- Upload Files to Jottacloud

**Actual result:** Error on Upload

**Expected result:** No Error, No Warnings

### Screenshots
![2017-06-29 08_37_42-](https://user-images.githubusercontent.com/16647382/27674635-cdfd3540-5ca6-11e7-8d76-92389bff4c8d.png)

### debug log
```
Operation Put with file duplicati-ba08ed7fff91a421f822f53a5f3cb3cb1.dblock.zip.aes attempt 1 of 5 failed with message: Der Remoteserver hat einen Fehler zurückgegeben: (460) 460.
System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (460) 460.
   bei Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
   bei Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
   bei Duplicati.Library.Backend.Jottacloud.Put(String remotename, Stream stream)
   bei Duplicati.Library.Main.BackendManager.DoPut(FileEntryItem item)
   bei Duplicati.Library.Main.BackendManager.ThreadRun()
```

**Comment by kenkendk** [comment]
It seems to be a problem with Jottacloud's internal stuff.
This page suggests it is a load balancer issue:
https://stackoverflow.com/questions/41986890/status-code-460-on-application-load-balancer

**Comment by Photographix** [comment]
Is this problem fixed in one of the next versions or must this jottacloud solve?

**Comment by kenkendk** [comment]
I think this is a Jottacloud issue. Have you reported it to them?

**Comment by Photographix** [comment]
As far as I know duplicati.jottacloud use a not "official" way (protocol reverse engineering) to get data into their archive. I do not know if it is a good idea to report this error.

**Comment by Photographix** [comment]
I got a ticket at jotta. But do not believe that I get there help. In the net I found the statuscode also here. Https://gist.github.com/IngmarBoddington/5056166 "Error 460 Only Aggregate Operation Allowed (RTSP)" maybe it can be seen again someone. I can not reach Albertony for help.

**Comment by Photographix** [comment]
Answer from jotta "Hi. Unfortunately Jottacloud does not support duplicati. You will need to upload the files trough jottacloud then move/copy the files over to archive.   :(

**Comment by Photographix** [comment]
Error 460 seems to be a "space is full" message in Jotta. I have been able to reproduce this several times. With 95% allocation (5GB Free Account) this message always comes in Duplicati. If I delete something - the message is gone in the next run.
