### ISSUE TITLE
Don't use `VACUUM` automatically

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#2578]
The current implementation uses `VACUUM` freely in an attempt to reduce space used by the local database. This works well for small backups, but the database can grow quite large (+60GiB) and then it becomes a problem, as the `VACUUM` step writes a new clean copy of the database.

To fix this we need multiple steps:
  - Remove all uses of `VACUUM` in the code
  - Add a commandline `vacuum` command that allows manual activation
  - Add a "Reclaim space" button in the UI that calls the `vacuum` operation
  - Add a `--auto-vacuum` option that calls the `vaccum` command after an operation

**Comment by saviodsouza** [comment]
+60GB database ???

**Comment by kenkendk** [comment]
Yes, this is reported in #2382

**Comment by kenkendk** [comment]
I will close this even though the "Add a 'Reclaim space' button ..." is not implemented, as it is possible to execute this from the "Commandline" part of the UI, and the operation is not expected to be used by most users.
