### ISSUE TITLE
Invalid Type errors when calling mono Duplicati.CommandLine.*.exe

### ISSUE THREAD

**Issue by Bruceforce** [duplicati/duplicati#2579]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.69
**Operating System:** Debian 8.8 (Kernel 3.16.0-4-amd64)
**Mono Version:** Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 25 09:19:47 UTC 2017)

### Bug description
Whenever I run a `mono Duplicati.CommandLine.*.exe` Command I get the following error messages

`Invalid type Microsoft.WindowsAzure.Storage.Blob.BlobEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions:<EncryptionPolicy>k__BackingField`
`Invalid type Microsoft.WindowsAzure.Storage.Queue.QueueEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Queue.QueueRequestOptions:<EncryptionPolicy>k__BackingField`
`Invalid type Microsoft.WindowsAzure.Storage.Table.TableEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Table.TableRequestOptions:<EncryptionPolicy>k__BackingField`

After the errors follows the actual output of the called command.

### Steps to reproduce
- run `mono Duplicati.CommandLine.exe`

**Actual result:** 

> Invalid type Microsoft.WindowsAzure.Storage.Blob.BlobEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions:<EncryptionPolicy>k__BackingField
> Invalid type Microsoft.WindowsAzure.Storage.Queue.QueueEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Queue.QueueRequestOptions:<EncryptionPolicy>k__BackingField
> Invalid type Microsoft.WindowsAzure.Storage.Table.TableEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Table.TableRequestOptions:<EncryptionPolicy>k__BackingField
> 
> See duplicati.commandline.exe help <topic> for more information.
>   General: example, changelog
>   Commands: backup, find, restore, delete, compact, test, compare, purge
>   Reparing: repair, affected, list-broken-files, purge-broken-files
>   Debugging: debug, logging, create-report, test-filters, system-info, send-mail
>   Targets: aftp, amzcd, azure, b2, box, cloudfiles, dropbox, ftp, file, googledrive, gcs, hubic, jottacloud, mega, onedrive, openstack, s3, ssh, od4b, mssp, tahoe, webdav
>   Modules: aes, gpg, zip, 7z, console-password-input, mssql-options, hyperv-options, http-options, sendhttp, sendmail, runscript, sendxmpp, check-mono-ssl
>   Formats: date, time, size, encryption, compression
>   Advanced: mail, advanced, returncodes, filter, <option>
> 
> http://www.duplicati.com/              Version:  - 2.0.1.69_canary_2017-06-29

**Expected result:** 

> See duplicati.commandline.exe help <topic> for more information.
>   General: example, changelog
>   Commands: backup, find, restore, delete, compact, test, compare, purge
>   Reparing: repair, affected, list-broken-files, purge-broken-files
>   Debugging: debug, logging, create-report, test-filters, system-info, send-mail
>   Targets: aftp, amzcd, azure, b2, box, cloudfiles, dropbox, ftp, file, googledrive, gcs, hubic, jottacloud, mega, onedrive, openstack, s3, ssh, od4b, mssp, tahoe, webdav
>   Modules: aes, gpg, zip, 7z, console-password-input, mssql-options, hyperv-options, http-options, sendhttp, sendmail, runscript, sendxmpp, check-mono-ssl
>   Formats: date, time, size, encryption, compression
>   Advanced: mail, advanced, returncodes, filter, <option>
> 
> http://www.duplicati.com/              Version:  - 2.0.1.69_canary_2017-06-29
>

**Comment by stellarpower** [comment]
Confirmed 2.0.2.1_beta_2017-08-01 :

duplicati-cli backup --dbpath="/.../" "ssh://backup.home.net:3496/.../" -auth-username=... --no-encryption --ssh-keyfile=~/.ssh/id_rsa --ssh-fingerprint="..." "/home/..."

Backup started at 16/08/2017 13:26:10
No certificates found, you can install some with one of these commands:
    cert-sync /etc/ssl/certs/ca-certificates.crt #for Debian based systems
    cert-sync /etc/pki/tls/certs/ca-bundle.crt #for RedHat derivatives
Read more: http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync
Checking remote backup ...
  Listing remote folder ...
Scanning local files ...
  32 files need to be examined (27.38 MB)
  0 files need to be examined (0 bytes)
Checking remote backup ...
  Listing remote folder ...
removing file listed as Temporary: duplicati-ba7072b89780e466c8895b204068a4efc.dblock.zip
removing file listed as Temporary: duplicati-i390e3a1d63c441e889c92770dfa804cd.dindex.zip
Verifying remote backup ...
Remote backup verification completed
  Downloading file (3.31 KB) ...
  Downloading file (5.21 KB) ...
  Downloading file (4.54 MB) ...
  Duration of backup: 00:00:09
  Remote files: 9
  Remote size: 23.52 MB
  Files added: 0
  Files deleted: 0
  Files changed: 0
  Data uploaded: 0 bytes
  Data downloaded: 4.55 MB
Backup completed successfully!
Invalid type Microsoft.WindowsAzure.Storage.Blob.BlobEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions:<EncryptionPolicy>k__BackingField
Invalid type Microsoft.WindowsAzure.Storage.Queue.QueueEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Queue.QueueRequestOptions:<EncryptionPolicy>k__BackingField
Invalid type Microsoft.WindowsAzure.Storage.Table.TableEncryptionPolicy for instance field Microsoft.WindowsAzure.Storage.Table.TableRequestOptions:<EncryptionPolicy>k__BackingField

**Comment by tyler274** [comment]
same error with current beta

**Comment by Bruceforce** [comment]
Seems to be fixed with Version:  - 2.0.2.6_canary_2017-09-16

**Comment by tobypeschel** [comment]
Same here &mdash; I had this error with 2.0.2.1, and upgrading to 2.0.2.6 resolved it.
