### ISSUE TITLE
The option --zip-compression-method exists more than once, please report this to the developers

### ISSUE THREAD

**Issue by jidea** [duplicati/duplicati#2584]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
Duplicati Version: 2.0.1.71_canary_2017-07-04
Operating System: Windows 10
Backend: google,ssh,local

### Bug description
A warning for each save. 

### Steps to reproduce
make or wait for the completion of a save. There is a warning.

Actual result: a warning
Expected result: no warning

Message from log : 

Warnings: [
    The option --zip-compression-method exists more than once, please report this to the developers
]

**Comment by Athep** [comment]
I have the same issue

**Comment by kenkendk** [comment]
Fixed with 392d833b9090b5f4a4fb036123416a5bd30902b2
