### ISSUE TITLE
2.0.1.72_canary - "About" not showing release info

### ISSUE THREAD

**Issue by NickPyz** [duplicati/duplicati#2585]
I have:
- [x] searched open and closed issues for duplicates
----------------------------------------
**Duplicati Version:** 2.0.1.72_canary
**Operating System:** Windows 10 - 64 bit
**Backend:**

### Bug description

Menu > About > General Tab shows the following message:
"You are currently running Duplicati unknown"

The Changelog tab displays the correct release number.

**Comment by svendhhh** [comment]
I'm seeing this now after updating to 2.0.3.3_beta_2018-04-02
