### ISSUE TITLE
The option --zip-compression-method exists more than once

### ISSUE THREAD

**Issue by batal1** [duplicati/duplicati#2586]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:**  2.0.1.71_canary_2017-07-04
**Operating System:** Windows 7 64 bits
**Backend:**

### Bug description
Backup ends with the following warning message :
Warnings: [ The option --zip-compression-method exists more than once, please report this to the developers ] Errors: []

### Steps to reproduce

**Actual result:** 
**Expected result:** 

### debug log

DeletedFiles: 0 DeletedFolders: 0 ModifiedFiles: 15 ExaminedFiles: 345896 OpenedFiles: 15 AddedFiles: 0 SizeOfModifiedFiles: 16001954 SizeOfAddedFiles: 0 SizeOfExaminedFiles: 99973818268 SizeOfOpenedFiles: 16001954 NotProcessedFiles: 0 AddedFolders: 0 TooLargeFiles: 0 FilesWithError: 0 ModifiedFolders: 0 ModifiedSymlinks: 0 AddedSymlinks: 0 DeletedSymlinks: 0 PartialBackup: False Dryrun: False MainOperation: Backup CompactResults: DeletedFileCount: 0 DownloadedFileCount: 0 UploadedFileCount: 0 DeletedFileSize: 0 DownloadedFileSize: 0 UploadedFileSize: 0 Dryrun: False MainOperation: Compact ParsedResult: Success EndTime: 06/07/2017 10:05:57 BeginTime: 06/07/2017 10:05:20 Duration: 00:00:37.1339253 BackendStatistics: RemoteCalls: 8 BytesUploaded: 32785850 BytesDownloaded: 32819165 FilesUploaded: 3 FilesDownloaded: 3 FilesDeleted: 0 FoldersCreated: 0 RetryAttempts: 0 UnknownFileSize: 0 UnknownFileCount: 0 KnownFileCount: 205 KnownFileSize: 5384988369 LastBackupDate: 06/07/2017 12:00:00 BackupListCount: 55 TotalQuotaSpace: 16492538097664 FreeQuotaSpace: 4084807569408 AssignedQuotaSpace: -1 ParsedResult: Success DeleteResults: DeletedSets: [] Dryrun: False MainOperation: Delete ParsedResult: Success EndTime: 06/07/2017 10:05:57 BeginTime: 06/07/2017 10:05:11 Duration: 00:00:45.7226427 RepairResults: null TestResults: MainOperation: Test Verifications: [ Key: duplicati-20170616T100000Z.dlist.zip Value: [], Key: duplicati-ic6cb336ab7c34a37be0949d35dc16683.dindex.zip Value: [], Key: duplicati-b5ffe174403e64db98c2c74c3a61dd104.dblock.zip Value: [] ] ParsedResult: Success EndTime: 06/07/2017 10:05:59 BeginTime: 06/07/2017 10:05:58 Duration: 00:00:01.2437487 ParsedResult: Warning EndTime: 06/07/2017 10:05:59 BeginTime: 06/07/2017 10:00:00 Duration: 00:05:59.8144485 Messages: [ No remote filesets were deleted, Compacting not required ] Warnings: [ The option --zip-compression-method exists more than once, please report this to the developers ] Errors: []

**Comment by VidalDuval** [comment]
I get the same warning.

### Version info
**Duplicati Version:** 2.0.1.71_canary_2017-07-04
**Operating System:** Linux Mint 18.2

### Bug description
Backup ends with the following warning message :
Warnings: [
    The option --zip-compression-method exists more than once, please report this to the developers
]
Errors: []

### debug log
DeletedFiles: 282
DeletedFolders: 229
ModifiedFiles: 1399
ExaminedFiles: 11038
OpenedFiles: 1426
AddedFiles: 27
SizeOfModifiedFiles: 144714799
SizeOfAddedFiles: 14671978
SizeOfExaminedFiles: 2807599006
SizeOfOpenedFiles: 246711201
NotProcessedFiles: 0
AddedFolders: 1
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults:
    DeletedFileCount: 0
    DownloadedFileCount: 0
    UploadedFileCount: 0
    DeletedFileSize: 0
    DownloadedFileSize: 0
    UploadedFileSize: 0
    Dryrun: False
    MainOperation: Compact
    ParsedResult: Success
    EndTime: 2017-07-07 13:14:33
    BeginTime: 2017-07-07 13:14:30
    Duration: 00:00:02.4338320
    BackendStatistics:
        RemoteCalls: 13
        BytesUploaded: 71227257
        BytesDownloaded: 53115635
        FilesUploaded: 5
        FilesDownloaded: 3
        FilesDeleted: 3
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 179
        KnownFileSize: 2245224513
        LastBackupDate: 2017-07-07 09:12:57
        BackupListCount: 55
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: -1
        ParsedResult: Success
DeleteResults:
    DeletedSets: [
        Item1: 55
        Item2: 2017-04-07 05:04:20,
        Item1: 56
        Item2: 2017-04-06 05:03:37,
        Item1: 57
        Item2: 2017-04-05 05:04:17
    ]
    Dryrun: False
    MainOperation: Delete
    ParsedResult: Success
    EndTime: 2017-07-07 13:14:33
    BeginTime: 2017-07-07 13:14:28
    Duration: 00:00:04.5435400
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20170707T131257Z.dlist.zip
        Value: [],
        Key: duplicati-i960d13e4021e44bfacca82bd0b5bad00.dindex.zip
        Value: [],
        Key: duplicati-be3a7b2d40fd542b5a971eb9320c8ecb8.dblock.zip
        Value: []
    ]
    ParsedResult: Success
    EndTime: 2017-07-07 13:14:50
    BeginTime: 2017-07-07 13:14:34
    Duration: 00:00:15.9529670
ParsedResult: Warning
EndTime: 2017-07-07 13:14:50
BeginTime: 2017-07-07 13:12:57
Duration: 00:01:53.2082210
Messages: [
    Deleting 3 remote fileset(s) ...,
    Deleted 3 remote fileset(s),
    Compacting not required
]
Warnings: [
    The option --zip-compression-method exists more than once, please report this to the developers
]
Errors: []

**Comment by Bruceforce** [comment]
You should at least search for open issues. At least @batal1 is honest and didn't even check "searched open and closed issues for duplicates".

FYI: #2584 is already fixed with 392d833. So you just have to update to version 2.0.1.72.

**Comment by kenkendk** [comment]
What @Bruceforce  said :)
