### ISSUE TITLE
set default source folder in duplicati UI

### ISSUE THREAD

**Issue by lokeshbhandari** [duplicati/duplicati#2587]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.53_experimental_2017-03-13
**Operating System:** Ubuntu
**Backend:**

### Bug description
I want to set default source directory in duplicati web UI. I want to give this solution to my user and I need to set source directory as users home directory of ubuntu. How can this possible to skip source directory by setting default source folder.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

**Comment by kenkendk** [comment]
You can create a backup on your own machine, set up as you like, then export it.
The exported file is in JSON format and can be edited with any text editor.

Change the file to your liking, and send it to your user and ask them to "import" it.
This will open the "Add backup" page, with the information from the JSON file pre-filled.
That way you can choose defaults for your user.

A slightly more complicated way is to provide a file called `newbackup.json` and put it in the install folder for Duplicati, and it will load this file and set defaults when the user creates a new backup. The currently applied default file is here: https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/newbackup.json

Does this answer your question?

**Comment by warwickmm** [comment]
Closing this due to lack of feedback.  If the exported JSON approach is not satisfactory, please feel free to reopen this or create a new issue.
