### ISSUE TITLE
GUI Feature wish

### ISSUE THREAD

**Issue by Photographix** [duplicati/duplicati#2588]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.72
**Operating System:** Windows 10
**Backend:** ACD, Jotta

### GUI Feature wish

- There  is a missing title which backup job you are editing if you already edited it.

- I would wish in the Homescreen more information about the backup job. I have 9 jobs and would like to see at a glance where I have what.

- 

### Screenshots

![bildschirmfoto 2017-07-08 um 11 17 36](https://user-images.githubusercontent.com/16647382/27985153-3bec9fd2-63e6-11e7-924c-f6c188486932.PNG)
![bildschirmfoto 2017-07-08 um 11 17 15](https://user-images.githubusercontent.com/16647382/27985154-42bfc104-63e6-11e7-81d8-e4c593580779.PNG)

**Comment by quctex** [comment]
I missed some kind of detailed jobs info too. But in my opinion, your proposal, @Photographix , is rather knotty. For me it is enough to see detailed settings under the jobs spoilers (when we click on the jobs name). It should be a simple list of all general settings in addition to now existing "Last successful run:", "Next scheduled run:", etc. I wish this list should be placed directly under the jobs name, before the "Operations:", "Configuration:", etc. block.

**Comment by Photographix** [comment]
@quctex I have 10 jobs which are set individually. In many I adjust settings from time to time. For me it is important to see all or at least many settings at once to the job. A mouse overlay would be enough for me. Always click in the job and then switch the configuration through is very complex. Everyone uses duplicati differently ;-)

**Comment by kenkendk** [comment]
I am very open to changing things and adding customization.
The current design is intentionally "minimalistic" as pro users tend to "get it" anyway, so we cater to the inexperienced users who are confused by details.

One way to add more info could be "personal" customizations.
Inside the folder where Duplicati is installed, there is a folder called `customized`. It has two empty files: `customized.css` and `customized.js`. You can use this to modify the look and functionality of Duplicati on your local machine, in a way that survives upgrades.

If we have user contributions that work for multiple users, maybe we can add a simple "plugin repository" where additional things can be enabled. I imagine that we can use something similar to the "theme" selector on the Settings page, where you can enable scripts like "Show extended info".

**Comment by Photographix** [comment]
Ok thanks, I will look at the files.
A "pro theme" in theme selector is enough for me
