### ISSUE TITLE
Are passwords/SSH-keys stored securely?

### ISSUE THREAD

**Issue by zin105** [duplicati/duplicati#2589]
As the title says, are passwords/SSH-keys stored securely? I have a password on the web ui but pressing show reveals my passwords.

Can malicious programs get the passwords and SSH-keys somehow?

**Comment by shoeper** [comment]
Obviously they can.

**Comment by kenkendk** [comment]
Short answer: no!

Duplicati stores the information in an SQLite database, which can be read by anyone with access to the folder (including hackers, malware, etc).

There is another issue tracking this: #2024
