### ISSUE TITLE
FAQ: Which files types exclude this option

### ISSUE THREAD

**Issue by Photographix** [duplicati/duplicati#2592]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.72_canary_2017-07-05
**Operating System:** OSX / Windows / Linux
**Backend:** ACD, Jotta

### Question
Which files types exclude this option (Especially on the Mac and Linux)

![2017-07-10 12_12_45-duplicati](https://user-images.githubusercontent.com/16647382/28013520-94b69c60-6569-11e7-80fe-3754dbf0c82a.png)

**Comment by kenkendk** [comment]
This excludes files with the "System" attribute.
The attributes are described here:
https://msdn.microsoft.com/en-us/library/system.io.fileattributes(v=vs.110).aspx

I am not sure which (if any) files are considered as having this attribute under Linux/macOS.

**Comment by Photographix** [comment]
OK thanks
