### ISSUE TITLE
"The authentication or decryption has failed."

### ISSUE THREAD

**Issue by jfml** [duplicati/duplicati#2598]
I (think I) have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.73_experimental_2017-07-15
**Operating System:** Uh, Debian, I think. A much smarter friend of mine runs that server.
**Backend:** Not sure : ( Using FTP for the actual backup

### Bug description
I've been running backups on experimental Duplicati for over a year now successfully on our server but it stopped working today. Updated to the newest release but not working either. I'm not sure if it's the same as #2250 (it does look like a mono-issue to me in the debug log?) or #1544 (also not sure what the solutions to these were). I always had and have `-- accept-any-ssl-certificate` activated. And the connection seems to work ok when I test it in the settings menu. 

### Steps to reproduce
- Try to run a backup … -___-

**Actual result:** Backup fails with a „The authentication or decryption has failed.“-message.
**Expected result:** Have a cool, functioning backup

### debug log
15. Jul. 2017 17:39: Failed while executing "Backup" with id: 5
System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0x5 at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00040] in <e220be0b0a364427860ee43376ab6f2b>:0 at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <e220be0b0a364427860ee43376ab6f2b>:0 at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <e220be0b0a364427860ee43376ab6f2b>:0 --- End of inner exception stack trace --- at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x0003b] in <e220be0b0a364427860ee43376ab6f2b>:0 at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <e220be0b0a364427860ee43376ab6f2b>:0 --- End of inner exception stack trace --- at Duplicati.Library.Main.BackendManager.WaitForComplete (Duplicati.Library.Main.Database.LocalDatabase db, System.Data.IDbTransaction transation) [0x00056] in <5fa4e21b782245d2a0c0188eac30f7ed>:0 at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x00705] in <5fa4e21b782245d2a0c0188eac30f7ed>:0 

Thanks a lot for this amazing piece of software!

**Comment by kenkendk** [comment]
That sounds like a problem with SSL:
https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono#generic-debian--ubuntu

**Comment by jfml** [comment]
@kenkendk Yeah, I think so too. Not sure what excactly, though. I tried to do it with SFTP/SSH now and that works. Thanks!
