### ISSUE TITLE
Where can I set the fullbackup <--> incremental backup cycle

### ISSUE THREAD

**Issue by thomase1993** [duplicati/duplicati#2599]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.72_canary_2017-07-05
**Operating System:** arch-linux
**Backend:** use the browser with systemctl start duplicati

### Bug description
How many incremental backups does it take until a new fullbackup is created? I do not find any information on your website nor on the issue list. This is not a bug but a question

**Comment by quctex** [comment]
Duplicati 2.0, in contrast to Duplicati 1.x, has the new storage format with no need to do full buckups at all. Described [here](https://www.duplicati.com/articles/Storage-Engine/) and more in some of [this ](https://www.duplicati.com/articles/)articles.

**Comment by kenkendk** [comment]
I assume the question is answered, so I am closing.

**Comment by douglasg14b** [comment]
Oh... it doesn't give you the ability to specify an incremental backup? That... sucks, but is congruent with a lot of modern utilities that are slimming down features and making more assumptions for the user. Time to move on I guess, it was good while it lasted.

**Comment by piegamesde** [comment]
@douglasg14b I don't understand what you want ("specify an incremental backup") and why this feature is missing. Is it full backups? Incremental backups are like full backups, but with great compression.

**Comment by hi2u** [comment]
@douglasg14b You've misunderstood how the newer version with dedupe works (and pretty much all modern backup software works).  Basically all backups you take now are incremental in terms of efficiency, but with the option to do full restores from any backup point.

It's certainly not removing functionality, just a more modern and efficient way of doing backups that gives you the best of both worlds.  There's no downsides.

The way you're whinging is just showing that you're ignorant of how modern (and better) backup systems work overall.

If you still don't understand, explain what you think is missing or worse about deduplicated backups vs the old model and I can explain further.
