### ISSUE TITLE
Duplicati randomly stops in the middle of a job

### ISSUE THREAD

**Issue by chug84** [duplicati/duplicati#2600]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.61_experimental_2017-05-30
**Operating System:** Linux

### Bug description
When I execute a job for a particular folder, the job randomly stops without any notifications or warnings. I've run several other backups (over 1TB in size) with no issue. 

### Steps to reproduce
- Create new job
- Use passphrase
- Set duplicati to use Google Drive
- Point duplicati to local data folder
- Configure Schedule
- Configure block size 

**Actual result:** Once I execute the job, duplicati begins working as normal. At random points in the backup (Have tried multiple times) the job just stops working.
**Expected result:** Backup to complete as has with other folders.

### debug log

No log is generated for this particular backup

**Comment by kenkendk** [comment]
How does it "stop working" ? Does the process crash? Does it just "abort" ? Can you see more if you go to "Show log" -> "Live" and set the level to "Profiling" ?

**Comment by chug84** [comment]
The progress bar just stops so to speak. Here's what I just pulled from the log.

Jul 24, 2017 10:47 PM: CommitAddBlockToOutputFlush took 00:00:00.015
Jul 24, 2017 10:47 PM: Starting - CommitAddBlockToOutputFlush
Jul 24, 2017 10:47 PM: ExecuteReader: SELECT DISTINCT "Hash", "Size" FROM "Block" WHERE "VolumeID" = ? took 00:00:00.000
Jul 24, 2017 10:47 PM: Starting - ExecuteReader: SELECT DISTINCT "Hash", "Size" FROM "Block" WHERE "VolumeID" = ?
Jul 24, 2017 10:47 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jul 24, 2017 10:47 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jul 24, 2017 10:47 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jul 24, 2017 10:47 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jul 24, 2017 10:47 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jul 24, 2017 10:47 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jul 24, 2017 10:47 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jul 24, 2017 10:47 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jul 24, 2017 10:47 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jul 24, 2017 10:47 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jul 24, 2017 10:47 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jul 24, 2017 10:47 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jul 24, 2017 10:46 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jul 24, 2017 10:46 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jul 24, 2017 10:46 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jul 24, 2017 10:46 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jul 24, 2017 10:46 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jul 24, 2017 10:46 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jul 24, 2017 10:46 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jul 24, 2017 10:46 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jul 24, 2017 10:46 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jul 24, 2017 10:46 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();
Jul 24, 2017 10:46 PM: ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ? took 00:00:00.000
Jul 24, 2017 10:46 PM: Starting - ExecuteScalarInt64: SELECT "ID" FROM "Block" WHERE "Hash" = ? AND "Size" = ?
Jul 24, 2017 10:45 PM: ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid(); took 00:00:00.000
Jul 24, 2017 10:45 PM: Starting - ExecuteScalarInt64: INSERT INTO "Block" ("Hash", "VolumeID", "Size") VALUES (?, ?, ?); SELECT last_insert_rowid();

**Comment by chug84** [comment]
I guess I can consider this issue hopeless? :(

**Comment by kenkendk** [comment]
Maybe this is really a UI problem. 
From the log, it looks like it is busy backing up.
When Duplicati has two full volumes that are not yet uploaded, it will pause, waiting for the upload to finish (otherwise it would just pile up uploads). This means that while the upload is running, it will appear to "do nothing".

We should fix the UI to display upload progress as well.

If this is the case, you should be able to see network traffic during the "pause".

**Comment by chug84** [comment]
Hmmm. That may be the case. Maybe it's an issue with Google drive. I had amazon cloud drive briefly before switching to Google drive and I was able to run backups with no issue. I've also noticed when this issue occurs that there will be a few GB of files in my temp directory. Are there any specific log files I should check or look for?

**Comment by chug84** [comment]
So Ken, I've been playing around a bit and I think the google API might have some sort of rate limit built into it which could be causing my issue. Do you know if anyone else using google drive has suffered this sort of problem?

**Comment by chug84** [comment]
System.ObjectDisposedException: The object was used after being disposed.
  at System.IO.StreamWriter.CheckState () [0x00000] in <filename unknown>:0 
  at System.IO.StreamWriter.Flush () [0x00000] in <filename unknown>:0 
  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x00000] in <filename unknown>:0

**Comment by silversword411** [comment]
Google Drive does have a rate limiter built in: https://stackoverflow.com/questions/10311969/what-is-the-limit-on-google-drive-api-usage

This is the API: https://developers.google.com/drive/v3/web/handle-errors
