### ISSUE TITLE
error:  "Database is NOT upgraded." 

### ISSUE THREAD

**Issue by LanceHaverkamp** [duplicati/duplicati#2607]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
newly upgraded Duplicati - 2.0.1.73_experimental_2017-07-15
Xubuntu Linux 16.04.1 (LTS)
Backblaze B2

### Bug description
Failed to execute SQL: CREATE UNIQUE INDEX "BlocklistHashBlocksetIDIndex" ON "BlocklistHash" ("BlocksetID", "Index") Error: Abort due to constraint violation UNIQUE constraint failed: BlocklistHash.BlocksetID, BlocklistHash.Index Database is NOT upgraded.
Dismiss
Show

### Steps to reproduce
Version updated...getting errors

NOTE: local backups also generating red-box warnings, but won't display the  actual errors.

**Comment by kenkendk** [comment]
This means that the database is in an inconsistent state. The update to the database enforces an extra constraint, such that this inconsistency is no longer possible.

You need to re-create the database such that the inconsistency is removed. You can use the "Database ..." -> "Recreate (delete and repair)" option for this.

**Comment by LanceHaverkamp** [comment]
Not sure how well that worked.  Still seeing “Got 17 warning(s)” 

MainOperation: Repair RecreateDatabaseResults: MainOperation: Repair ParsedResult: Success EndTime: 8/4/2017 10:25:52 AM BeginTime: 8/4/2017 3:59:58 AM Duration: 06:25:53.1604220 BackendStatistics: RemoteCalls: 5619 BytesUploaded: 0 BytesDownloaded: 4747816890 FilesUploaded: 0 FilesDownloaded: 5618 FilesDeleted: 0 FoldersCreated: 0 RetryAttempts: 0 UnknownFileSize: 0 UnknownFileCount: 0 KnownFileCount: 0 KnownFileSize: 0 LastBackupDate: 1/1/0001 12:00:00 AM BackupListCount: 0 TotalQuotaSpace: 0 FreeQuotaSpace: 0 AssignedQuotaSpace: 0 ParsedResult: Success ParsedResult: Warning EndTime: 8/4/2017 10:26:04 AM BeginTime: 8/4/2017 3:59:58 AM Duration: 06:26:05.4085600 Messages: [ Renaming existing db from /home/lance/.config/Duplicati/YGAJTKVADA.sqlite to /home/lance/.config/Duplicati/YGAJTKVADA.backup, Rebuild database started, downloading 237 filelists, Filelists restored, downloading 5335 index files, Processing required 46 blocklist volumes, Recreate completed, verifying the database consistency, … ] Warnings: [ Mismatching number of blocklist hashes detected on blockset 78393. Expected 0 blocklist hashes, but found 1, Mismatching number of blocklist hashes detected on blockset 277451. Expected 0 blocklist hashes, but found 1, Failed to process file-entry: /home/lance/.ICEauthority => Abort due to constraint violation UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Failed to process file-entry: /home/lance/.ICEauthority => Abort due to constraint violation UNIQUE constraint failed: FilesetEntry.FilesetID, FilesetEntry.FileID, Mismatching number of blocklist hashes detected on blockset 277477. Expected 0 blocklist hashes, but found 1, … ] Errors: []

**Comment by ts678** [comment]
Whatever this was was observed on an upgrade to a 2017 release. Is it still of interest, and happening on the current releases?
