### ISSUE TITLE
"no such table: LogData", if "dbpath"-option is used

### ISSUE THREAD

**Issue by Mapel** [duplicati/duplicati#2611]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.73_experimental_2017-07-15 
**Operating System:** Windows Server 2012 R2
**Backend:**

### Bug description
Using the "dbpath"-option results in the error "Verbindung fehlgeschlagen: SQL logic error or missing database no such table: LogData" when trying to view the log-file 

### Steps to reproduce
- create backup-job with "dbpath"-option set
- let the job run
- try to view log-file

### debug log
 Request for http://localhost:8200/api/v1/backup/6/log?pagesize=100 gave error
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such table: LogData
   bei System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   bei System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   bei System.Data.SQLite.SQLiteDataReader.NextResult()
   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bei Duplicati.Server.WebServer.RESTMethods.LogData.DumpTable(IDbCommand cmd, String tablename, String pagingfield, String offset_str, String pagesize_str)
   bei Duplicati.Server.WebServer.RESTMethods.Backup.FetchLogData(IBackup backup, RequestInfo info)
   bei Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)

**Comment by kenkendk** [comment]
Are you setting the `--dbpath` in advanced options? That does not work, you need to set the database path via the "Database ..." page.

I should remove the option from the "Advanced options" section.

**Comment by Mapel** [comment]
Indeed I used `--dbpath` in advanced options.

Using the option on the "Database"-Page resolved the issue.

**Comment by DANSI** [comment]
Hello. 

> Indeed I used --dbpath in advanced options.
> Using the option on the "Database"-Page resolved the the issue.

I have the same issue. Used --dbpath option in Job-advanced-settings.
I am getting SQLite-Error "no LogData" if some error occurs while the backup job doing it's work .
Removed the advenced setting (--dbpath) from the job and changed the Database location in the Job-database-settings-page.
Error is gone. --dbpath should be removed from Job-advanced-setting-page or even better "--dbpath and Database-Setting in Jobs" should be the same behind the scenes.

Error reproduced in version 2.0.6.1_beta_2021-05-03 #
