### ISSUE TITLE
Impossible to launch Duplicati on OSX 1.7

### ISSUE THREAD

**Issue by Emmenemoi** [duplicati/duplicati#2613]
### Version info
**Duplicati Version:** 2.0.1.73
**Operating System:** OSX SERVER 10.7.5
**Backend:** SFTP
**Mono:** 5.0.1.1

### Bug description
Impossible to start Duplicati.
Probably a bug in the startup script linked with the tray icon / rumps and the Python version.

### Steps to reproduce
- Launch Duplicati

### debug log
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: Traceback (most recent call last):
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: File "/Applications/Duplicati.app/Contents/Resources/OSXTrayHost/osx-trayicon-rumps.py", line 196, in <module>
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: app = rumps.App('', quit_button=None)
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: File "/Applications/Duplicati.app/Contents/Resources/OSXTrayHost/rumps.py", line 952, in __init__
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: self._menu = Menu()
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: File "/Applications/Duplicati.app/Contents/Resources/OSXTrayHost/rumps.py", line 309, in __init__
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: super(Menu, self).__init__()
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 74, in __init__
27/07/17 15:43:31,992 [0x0-0x49049].com.duplicati.app: Unexpected message: TypeError: update() takes exactly 2 arguments (1 given)
27/07/17 15:43:32,540 [0x0-0x49049].com.duplicati.app: /Applications/Duplicati.app/Contents/MacOS/duplicati: line 7:  2887 Terminated: 15          bash "${SCRIPT_DIR}/run-with-mono.sh" "$@"

**Comment by kenkendk** [comment]
I do not have OSX server to test with.

The crash line is the same in the bundled rumps version as the one in the current latest:
https://github.com/jaredks/rumps/blob/master/rumps/rumps.py#L328
https://github.com/duplicati/duplicati/blob/master/thirdparty/rumps/rumps.py#L309

Can you try if rumps itself needs to be fixed:
https://github.com/jaredks/rumps

**Comment by Emmenemoi** [comment]
I don't know enough python to understand if this is linked.
I succeeded to make Duplicati run once. So The problem may come from the config sent to rumps.
I don't know. Probably not linked to my os version: Python 2.7.1 (r271:86832, Jun 16 2011, 16:59:05)
