### ISSUE TITLE
Duplicati does not launch - Mac OS X El Capitan

### ISSUE THREAD

**Issue by s-allain** [duplicati/duplicati#2614]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.73 Experimental
**Operating System:** Mac OS X 10.11.6 - Darwin 15.6.0 Darwin Kernel Version 15.6.0
**Backend:** Hubic

### Bug description
If I try to launch the Application from the Finder, error message : "The application is damaged and cannot be opened. You should move the application to the Trash"
[Duplicati_Informations.txt](https://github.com/duplicati/duplicati/files/1180391/Duplicati_Informations.txt)

### Steps to reproduce
- Fresh install : 2.0.1.73 Experimental.dmg
- Mono Framework installed : MonoFramework-MDK-5.0.1.1.macos10.xamarin.universal

**Actual result:** 
- If Duplicati is launch from the command-line, it works :-)
$ /Applications/Duplicati.app/Contents/MacOS/duplicati
I was able to setup a backup to a Hubic Storage, delete source files and restore them successfully.

**Expected result:**

### Screenshots
http://i.imgur.com/1jmbqBJ.jpg

### debug log
- Which log files will you need ?

**Comment by kenkendk** [comment]
I think you need to enable GateKeeper to accept files from outside of App Store:
https://cdn1.tekrevue.com/wp-content/uploads/2016/09/gatekeeper-macos-sierra-default-settings.jpg

The setting is called "App Store and identified developers".

**Comment by s-allain** [comment]
Hi **kenkendk**,

I turned off temporary GateKeeper, and this has solved the issue.

After GateKeeper was turn on again, application is now able to launch the UI without issue ;-)

Thanks for help, you can consider this request to be closed.

**Comment by kenkendk** [comment]
You should not have to turn GateKeeper off, just allow "Identified developers".
Duplicati for macOS is signed with a valid Apple certificate, so it should pass GateKeeper, but it cannot go in the App Store as it needs more permissions than the App Store sandbox allows.

**Comment by s-allain** [comment]
GateKeeper is not actually turned off, but I was obliged to turn it off at least for the first launch.

**Comment by kenkendk** [comment]
You re-opened, does this mean that the issue is not resolved?

**Comment by s-allain** [comment]
Issue is solved, closed :-)
