### ISSUE TITLE
 Failed to process element: true

### ISSUE THREAD

**Issue by laithja** [duplicati/duplicati#2615]
I have:
- Duplicati 2.0 

----------------------------------------

### Version info

**Duplicati Version:** Duplicati 2.0
**Operating System:windows server 2012 R2 standard 
**Backend:**

### Bug description
after fresh install and connect to the one drive the test for connection successfully done , but after starting and run task it gave the below error 

Warnings: [
    Failed to process element: true, message: Could not find file 'C:\Program Files\Duplicati 2\true'. => Could not find file 'C:\Program Files\Duplicati 2\true'.
]

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

**Comment by kenkendk** [comment]
Can you try to export the backup task to commandline (via the Export... option) and see if it looks sane ?

**Comment by laithja** [comment]
![untitled](https://user-images.githubusercontent.com/30588575/28824885-c50eee2a-76cc-11e7-9881-34362c40671f.png)


 i have attached screen shot of exported file to cmd

**Comment by kenkendk** [comment]
I removed the image, not sure all sensitive parts were fully covered.

**Comment by kenkendk** [comment]
There is a double backslash at the end of the source folder (`...\SharedFolderAii\\`).
Try removing that and see if it fixes things.

**Comment by laithja** [comment]
it gave error , i remove whole application and want reinstall it again

**Comment by danielblues** [comment]
I've had the same error after exporting and importing a backup configuration.
Removing double backslash solved the issue (thanks), they probably should not be exported.
I'm running version 2.0.2.15

**Comment by warwickmm** [comment]
I'm guessing this has been fixed.  If anyone is still experiencing this issue, please feel free to re-open this with new details.
