### ISSUE TITLE
bb

### ISSUE THREAD

**Issue by Jack-Oliver** [duplicati/duplicati#2618]

**Comment by kenkendk** [comment]
Can you post a screenshot?

**Comment by Jack-Oliver** [comment]
![capture2](https://user-images.githubusercontent.com/17979021/28821258-acec00d2-76ac-11e7-9bea-8cd90593ad2e.PNG)
![capture](https://user-images.githubusercontent.com/17979021/28821259-ad05181a-76ac-11e7-952a-49abdc5f8b23.PNG)

I have tried on Canary with the same issue.

**Comment by kenkendk** [comment]
And nothing happens if you click the "AuthID" link in blue?
In that case, maybe you have a "popup" window floating around behind the normal browser window?

**Comment by kenkendk** [comment]
It looks like you removed the content. I assume this means the issue is fixed.
