### ISSUE TITLE
Don't use SHA256Managed (use the native one)

### ISSUE THREAD

**Issue by GSPP** [duplicati/duplicati#2621]
When profiling Duplicati I sometimes see 100% CPU usage and at that time I see a lot of time spent in SHA256Managed. The .NET Framework also includes a native SHA256 implementation. From earlier experimenting I know that the native version becomes much faster when the data blocks are over a certain size. 4KB would certainly be over the cut-off point. I remember that the threshold was a few hundred bytes with SHA1.

So I suggest simply switching to the native algorithm to improve speed.

I haven't quite understood the source code yet but from profiling I get the impression that the hash function is invoked with blocks that are not very big. I might be wrong about that. Especially when using the native version it pays off to pass bigger chunks of data per call to TransformBlock. That's why I wanted to mention that.

Tested with latest 2.0 version as of today.

**Comment by kenkendk** [comment]
It uses `HashAlgorith.Create`: https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Operation/BackupHandler.cs#L699

AFAIK, this is the correct way to set up the hashing, allowing the framework to choose the optimal version. Is there a better way?

The block size is configureable, but by default it uses 100KiB blocks. The blocks are processed directly from memory, not going through the file-stream: https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Operation/BackupHandler.cs#L1159

**Comment by GSPP** [comment]
I don't think the framework has a lot of smarts here. I think `HashAlgorithm.Create` is basically looking up a configured class for the string. It's app.config configurable. That's its purpose as I understand it.

It is definitely not *wrong* to use `new SHA1Cng()`. These classes are public and will stay compatible in future versions. Testing should be done to determine the fastest provider and use that.

In my mind `HashAlgorithm.Create` *should* pick the best version but it does not.
