### ISSUE TITLE
Email send-http-level function not working. email always sent

### ISSUE THREAD

**Issue by chris-cashin** [duplicati/duplicati#2623]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 0.0.0.0
**Operating System:**
**Backend:**

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

**Comment by chris-cashin** [comment]
Using 200.2.1Beta or earlier versions email is sent on Windows server 2016 or 2012 regardless of values entered in send-http-level. The parsed result is Success but even though I set the send-http-level to fatal or error I still get an email with either the browser version or command line version. As an FYI the web documentation suggests that you can enter more that one parameter separated by , such as "Warning,Error,Fatal" but the string is rejected with an error message saying it is not supported. Any one parameter does not give an error but email is always sent.

**Comment by kees-z** [comment]
Probably you have to set `--send-mail-level` instead of `--send-http-level` to specify when an email should be sent en when not.
You can set it to "Warning,Error,Fatal" to skip email notifications after successful tasks (enter it unquoted).
I've tested it, `--send-mail-level=Warning,Error,Fatal` works for me.

**Comment by chris-cashin** [comment]
Thanks that was the issue. Works as expected when using --send-mail-level.
regards
Chris Cashin
