### ISSUE TITLE
Add an option to ignore empty directories when using --include

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#263]
_From [re...@orange.fr](https://code.google.com/u/109932733271539970261/) on September 07, 2010 17:26:35_

When I do a backup using a --include and --exclude i get all the (sub)directories structure stored in my backup.

An option allowing to store only the path of the directories which contain files found through the --include would be very useful to me.

It should be in my opinion the default behaviour when using the --include and a --store-full-directory-tree option should be included when you want to store the whole directory structure.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=263_

**Comment by xko** [comment]
Doesn't work in 2.0.1.7- 2.0.1.7_experimental_2016-03-19

> >Duplicati.CommandLine.exe test-filters C: --parameters-file="duplicati.params"
> The supplied option --exclude-empty-folders is not supported and will be ignored
