### ISSUE TITLE
Fix loading race condition with XSRF token

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#2635]
When loading the UI, the XSRF token is sometimes delayed a bit.
This causes all the initial requests to be sent without a valid XSRF token and thus they are rejected.

Then the XSRF token is refreshed, but the requests are not re-sent.

This should be fixed by ensuring that a valid XSRF token is emitted with the `index.html` page.

**Comment by LanceHaverkamp** [comment]
I think the synology tag is irrelevant to this.
