### ISSUE TITLE
Add a warning on first run asking the user to set a password on the UI

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#2636]
If the user installs Duplicati in a multi-user setup, this will automatically expose the users files to other users on the machine. To guard against this, the first run should show a dialog asking the user to put a password on the installation.

Suggested wording:

If this is a shared machine, we recommend that you add a password to Duplicati to prevent other users from reading your files.
[ Yes, set a password now ] [ No thanks]

**Comment by warmup72** [comment]
I´m using Duplicati (2.0.2.1_beta) on my Mac 10.12.6. and i´ve tried to set the password for the user-interface. That works fine. 
On Firefox and Safari the UI is protected but for chrome that doesn´t work. After logging out the frontends prompt the pw-request. After restarting chrome i´m logged in without typing the pw!

**Comment by ttr** [comment]
If you're on multi user setup then:
- run server not as a service but as your user (and shut down it when you log out) - this will protect access to your files but will only back up while You're logged in
- run as service and set up password, but anyone who have root access can bypass it, while by normal operation user who set up password will be only one who can access duplicati.
Side note - if you're using it in system wide mode, any user can access any other files (as restore can bypass original permission), so technically mutiuser setup is not secure IMO

**Comment by JonMikelV** [comment]
I could have sworn I saw this message on a test install of the latest canary version, is this considered fixed (but not released)?

**Comment by kenkendk** [comment]
I forgot to close this issue, but yes, I added the message. I will follow up on #2698

**Comment by kenkendk** [comment]
@warmup72 that sounds like another (serious?) issue. Could you make a new issue if there is not one already?
