### ISSUE TITLE
Unscheduled job still runs

### ISSUE THREAD

**Issue by avr7** [duplicati/duplicati#2643]
Hello, 

A job was created initially with a schedule. The schedule was then removed. I discovered that the job still ran.  Editing the job shows the schedule is still unchecked.  A debug log was created, can send privately if needed.

----------------------------------------

### Version info
**Duplicati Version: 2.0.2.1_beta_2017-08-01
**Operating System Windows Server 2012R2
**Backend: B2

**Comment by kenkendk** [comment]
If you export the job to a file, can you see the schedule in the exported file?
Have you restarted Duplicati after deleting the schedule (not required, but could be that a restart purges the schedules).

**Comment by warwickmm** [comment]
I don't think this is an issue anymore.  If you're still experiencing this, feel free to reopen and provide more details.
