### ISSUE TITLE
Increase TCP send size for Mega backend

### ISSUE THREAD

**Issue by GSPP** [duplicati/duplicati#2647]
Using Process Monitor and Wireshark I watched Duplicati upload to Mega. I did this because the program did not fully use all available upload speed of my connection. This could be due to the Mega servers not taking the data faster. But the logs I captures suggest that the `MegaApiClient` could be more efficient.

It seems to send in 8KB chunks:

![image](https://user-images.githubusercontent.com/12032350/29456754-8ab4870a-8417-11e7-8248-330b3278c618.png)

But how does the OS physically send those chunks?

![image](https://user-images.githubusercontent.com/12032350/29456787-b14599b8-8417-11e7-9103-41cae1df44e0.png)

I have marked one send/ACK cycle. It looks like it is introducing a boundary after 8KB and waiting for acknowledgement. It also sets the `PSH` flag indicating that this is deliberate. Also note, that the next 8KB send batch waits for the ACK to fully arrive as can be seen by the time stamps.

These findings suggest that uploading would be more efficient if bigger buffers were used. I think increasing to 64KB buffers is a no-brainer. I could see far bigger sizes make sense. For bulk transfers I believe it is beneficial to enable nagling which might get rid of these boundaries entirely.

That being said I don't know if this is fixable since the actual uploading seem to happen in `CG.Web.MegaApiClient.WebClient.PostRequest` which is third-party code. I still wanted to put this issue here so that it can be understood and tracked at least. Also, other backends might be affected.

This is 2.0.2.1_beta_2017-08-01 on Windows x64.

**Comment by GSPP** [comment]
I also just notice that download speed with the Mega backend ist 1.4MB/sec only. This is because of very inefficient code. Most call stacks I sampled look like this:

![image](https://user-images.githubusercontent.com/12032350/29458956-eb9574b2-8421-11e7-8ecb-a0d5259c7969.png)

Just letting you know. See https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/MegaAesCtrStream.cs. The Read method looks very fragile. A few possible correctness problems come to mind as well (not sure).

**Comment by kenkendk** [comment]
You should report these issues at the MegaApi site, it looks like the project is still active.

**Comment by kenkendk** [comment]
But it looks like the source has been updated to solve the Linq issue:
https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/Stream/MegaAesCtrStream.cs

... and there is a new version of the library, I will update!

**Comment by GSPP** [comment]
@kenkendk As far as I can tell both issues are still present in the latest version of the library. I just reported them.

**Comment by gpailler** [comment]
I published MegaApiClient v1.6.1 to fix reported issues. Please update the package in Duplicati to confirm the improvements
