### ISSUE TITLE
CLI: passphrase fails when it contains the character '!'.

### ISSUE THREAD

**Issue by Tralen** [duplicati/duplicati#2649]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.2.1_beta_2017-08-01
**Operating System:** Arch Linux
**Backend:** Jottacloud

### Bug description
When providing the passphrase to commands in the command line, it fails if it contains the character `!` which is a special character as understood by Bash. This suggests that the commands are being piped unquoted. Quoting the provided passphrase doesn't work, as perhaps the quotes are being interpreted as part of the passphrase.

The only solution is to set the environment variable PASSPHRASE, however, since Duplicati is installed as a service in my distribution, the variable must be set by root, which is worrisome.

### Steps to reproduce
- Setup a backup with a passphrase which contains `!`.
- Try to perform a command that requests it.

**Actual result:** The passphrase is split at the `!`, the rest is interpreted by Bash as a separate command, which crashes the procedure.
**Expected result:** The command issued to Duplicati should recognize the entire passphrase, including the portion after the `!`.

**Comment by ttr** [comment]
This is not a bug but normal for all in bash operation. Just put quotes around your passphrase and it should work

**Comment by Tralen** [comment]
I didn't try single quotes as you did. I understand now that they are necessary to prevent history expansion.
