### ISSUE TITLE
Windows (Windows 8): No tooltip on the tray icon

### ISSUE THREAD

**Issue by CottonEaster** [duplicati/duplicati#2652]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:**  2.0.2.1_beta_2017-08-01
**Operating System:** Windows 8.1
**Backend:** ??

### Bug description
There is no tray tooltip for the duplicati icon in the notification/tray area (the area on the bottom right of the taskbar). This does not affect functionality but is disconcerting.

### Steps to reproduce
- Install Duplicati.
- Hover the mouse over the tray icon.

**Actual result:** There's no tooltip.
**Expected result:** There should be a tooltip showing the name of the program (or that together with something more useful).

### Screenshots

This is the area of the screen that I am talking about:
![image](https://user-images.githubusercontent.com/9998846/29591336-9ec2a99c-878d-11e7-82be-37619aecf4e3.png)

**Comment by kenkendk** [comment]
Thanks for reporting!
