### ISSUE TITLE
Get status of backup job

### ISSUE THREAD

**Issue by ktulkhu** [duplicati/duplicati#2656]
Hello. 
How can I get the status of backup job? 
I want to monitor duplicati backup jobs by Zabbix, and if status of job is Error or Warning the zabbix should send me the message about it. 
I create script with code:
echo "Duplicati ERRORCODE is: %errorlevel%" >> e:\backup\duplicati\log\status.txt
and run this script after job (parameter run-script-after) 
and script returns "Duplicati ERRORCODE is: 0" always, even if ParsedResult: Warning.

Can I get the job status any other way? By API or sctipt or any else...?

**Comment by kenkendk** [comment]
The error code is not reported to the script, but perhaps we should change it so that it is reported.
You can get the status by looking for a line that starts with`ParsedResult: ` in the file pointed to by the environment variable `DUPLICATI__RESULTFILE`.

**Comment by ktulkhu** [comment]
Now I get status by running run-script-after: 

SET FILESTATUS=e:\backup\duplicati\log\%DUPLICATI__backup_name%_STATUS.txt
for /F "tokens=1,2 delims=: " %%i in (%DUPLICATI__RESULTFILE%) do (
	if "%%i"=="ParsedResult" (
		if "%%j"=="Success" (echo SUCCESSFULL > %FILESTATUS%) else (echo UNSUCCESSFULL > %FILESTATUS%)
	)
)

but it is not usable for me.. 
Maybe can I get this ParsedResult directly from database? (Prompt a sql-request if it is not difficult for you)
Or wouldn't you add the environment variable like DUPLICATI__PARSED_RESULT in the next relizes? 

And how many values the ParsedResult has? Error, Warning, Success ....? (for more accurate monitoring)

Thank you.

**Comment by kenkendk** [comment]
Yes, I think we should add `DUPLICATI__PARSED_RESULT` as well.

You can see the possible values here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Interface/ResultInterfaces.cs#L23

You can query the local database with `sqlite3.exe`, you can get the path from `DUPLICATI__DBPATH`.
