### ISSUE TITLE
Never got a login verification email on forum

### ISSUE THREAD

**Issue by linuxgurugamer** [duplicati/duplicati#2657]
I signed up on the forum, verified my email address was correct, and never received a confirming message.
It's a gmail address, so I know it works.

**Comment by kenkendk** [comment]
I tried to re-send the activation email.

**Comment by kenkendk** [comment]
Did it work? I cannot see your account is active? I can send you an email directly if you like?

**Comment by kenkendk** [comment]
Closing for lack of feedback

**Comment by linuxgurugamer** [comment]
Lack of feedback because I never got any emails

**Comment by kenkendk** [comment]
@linuxgurugamer Send me an email directly from your own email and I will manually activate the account.
