### ISSUE TITLE
Long and short description "disable-filepath-cache" swapped

### ISSUE THREAD

**Issue by kees-z** [duplicati/duplicati#2659]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.73 Experimental
**Operating System:** Windows 10 Pro
**Backend:** N/A

### Bug description
In the Web UI, the long and short description of the advanced option "disable-filepath-cache" are swapped. This results in a drop-down menu that is much wider then needed.

### Steps to reproduce
- Click Settings
- Open drop-down menu "Add advanced option".

### Screenshots

The drop-down menu that should contain a short description:
![dropdown](https://user-images.githubusercontent.com/24669568/29689450-842b7874-8923-11e7-9477-010fe257f68b.png)

The menu that should contain a longer description:
![menu](https://user-images.githubusercontent.com/24669568/29689466-8c526c56-8923-11e7-8752-6f15c7a8c061.PNG)

**Comment by kenkendk** [comment]
Thanks for reporting!
