### ISSUE TITLE
Launched from batch file, batch file does not terminate (Windows)

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#2661]
I used to have a Windows batch file that launches other batch files (similar to the init.d directory on Linux).
I launched duplicati via 

start /LOW C:\Progs\duplicati\Duplicati.GUI.TrayIcon.exe

That worked well ever since. I skipped a few versions and I am now on the latest beta. There has been a difference in the behaviour: The batch file does not terminate thus blocking scripts that should be executed afterwards.
I suspect it's because of the messages sent to stdout?

Can I suppress them?

Stefan

**Comment by kenkendk** [comment]
I think this is caused by this change:
https://github.com/duplicati/duplicati/blob/master/Duplicati/GUI/Duplicati.GUI.TrayIcon/Program.cs#L66

There is currently no way to disable it, but we should add that.

**Comment by huste** [comment]
Thanks for the feedback. Just out of curiosity, what's the reasoning behind attaching?

**Comment by kenkendk** [comment]
The reason was to get error messages propagated to the console when launched that way.

**Comment by huste** [comment]
Thanks, works like a charm!
