### ISSUE TITLE
Specifying blocksize in bytes results in very large number of small volumes

### ISSUE THREAD

**Issue by DragonFlux** [duplicati/duplicati#2662]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.2.1_beta_2017-08-01
**Operating System:** Windows 8.1
**Backend:** BackBlaze B2

### Bug description
When setting blocksize in bytes (ex: 131072), the resulting **initial** backup generates a huge number of very small dblock files (much smaller than the set volume size). This happens with any content, but is worse with large numbers of small files. The manifests in the dblocks also report odd block sizes, both small and large (even over 100MB when blocksize=131072 bytes). In such cases the actual blocks also vary greatly in size (incl. much bigger than configured block size)

### Steps to reproduce
Tested with 50MB volumes:
- blocksize=131072 bytes: many small volumes (ie: 128KiB)
- blocksize=128000 bytes: many small volumes (ie: 128kB)
- blocksize=128 KB: correct 50MB volumes

**Comment by kenkendk** [comment]
Are you using 7z compression? It has some issues with creating many small files.

**Comment by DragonFlux** [comment]
No, I'm using the default zip compression. I don't think this is a compression issue; the actual blocks (uncompressed) vary in size if I specify the same size in bytes rather than KB (ie 131072B vs 128KiB). Some go well over the specified block size (or under) and volumes aren't filled properly.

**Comment by ts678** [comment]
Reproducible on 2.0.5.111 if set up just right, in this case with the GUI Options, then using three-dot menu to remove `b` unit which GUI would ordinarily generate from the unit dropdown when set to bytes. I suspect CLI would also offer this surprise when unit-free.

https://github.com/duplicati/duplicati/blob/7d958adb8a71b334834ce42ecc9571c78e8a259e/Duplicati/Library/Utility/Sizeparser.cs#L28-L43

https://github.com/duplicati/duplicati/blob/7d958adb8a71b334834ce42ecc9571c78e8a259e/Duplicati/Library/Main/Options.cs#L1277-L1282

If I set blocksize=128000 without any unit suffix, then look in the DB Configuration table, it's 131072000, which is 128000 * 1024. That's bigger than the default 50 MB blocksize, but I guess the algorithm lets one in (what else can it do?), then decides there's no room for another, so uploads the dblock. Basically, each dblock gets a block. Some blocks (such as metadata or a blocklist) are tiny.

The CLI help for `size`:

```
Whenever a size is required, you can use any of the following suffixes:

  B - Bytes
  kB - Kilobytes
  MB - Megabytes
  GB - Gigabytes
```

but what's not said there is what happens without a unit, but looking at the ParseSize() calls in Options.cs, it's not at all standardized.
Personally I would have thought that unit-free meant no unit multiplier, but any change in default now could break existing backups.

[Skip-files-larger-than ignored](https://forum.duplicati.com/t/skip-files-larger-than-ignored/4112/5?u=ts678) was a similar issue, the options code does use a `mb` default multiplier, and it looks like the GUI added the `b` suffix around August 2018. I'm not sure what CLI does, but GUI popped up a yellow warning for me when I forced unit-free:

> 2020-12-18 15:35:44 -05 - [Warning-Duplicati.Library.Main.Controller-OptionValidationError]: The size "128000" supplied to --blocksize does not have a multiplier (b, kb, mb, etc). A multiplier is recommended to avoid unexpected changes if the program is updated.

OK, I tried CLI and it warned me right away:

```
Backup started at 12/18/2020 4:30:13 PM
The size "128000" supplied to --blocksize does not have a multiplier (b, kb, mb, etc). A multiplier is recommended to avoid unexpected changes if the program is updated.
```

**Comment by ts678** [comment]
I went looking for history, and found [2.0.3.10_canary_2018-08-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.10-2.0.3.10_canary_2018-08-30) release notice:

> Now emits a warning if the option is missing a suffix on sizes (b, kb, mb, gb, tb)

which seems to be from

[Added warning to unqualified size options](https://github.com/duplicati/duplicati/commit/07815c1751c69d65a501d237208dd3cbe7fbfd88)

and I also noticed it got

[Changed the GUI to explictly set the b suffix on size numbers](https://github.com/duplicati/duplicati/commit/b59032552fb946a15a4f5b07fd09fe5ebecb0b5a)

@DragonFlux do those resolve this issue?
