### ISSUE TITLE
Allow empty password field if SSH key is not password protected

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#2664]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.2.1_beta_2017-08-01
**Operating System:** Arch Linux with 4.12.8 kernel
**Backend:**

### Bug description
When a password-less ssh key is provided, the application should not complain that the password field is empty.

### Steps to reproduce
- Add a new backup and choose the SFTP (SSH) storage type
- Go to Advanced Options, and select ssh-keyfile
- Provide the path to an ssh key _that is not password protected_

**Actual result:** When continuing, the application complains that the password field is blank.  If the user then enters anything into the password field, the application continues to work as expected.

**Expected result:** If a password-less ssh key file is provided, the password field should be allowed to be empty.

**Comment by Clete2** [comment]
Was going to propose a PR but then realized that you'd also have to check if the key is password-less as described, so I'll just dump the code I wrote so far:

`EditUriBackendConfig.js` at the bottom:
```
   this.require_username = function(scope) {
        if ((scope.Username || '').trim().length == 0)
            return self.show_error_dialog(gettextCatalog.getString('You must fill in the username'));

        return true;
    };

    this.require_password = function(scope) {
        if ((scope.Password || '').trim().length == 0)
            return self.show_error_dialog(gettextCatalog.getString('You must fill in the password'));

        return true;
    };

    this.require_username_and_password = function(scope) {
        self.require_username(scope);
        self.require_password(scope);

        return true;
    };

    this.require_username_and_password_or_key = function(scope) {
        self.require_username(scope);

        if(scope.AdvancedOptions.find(advancedOption => advancedOption.startsWith('--ssh-keyfile='))) {
            return true;
        }

        self.require_password(scope);

        return true;
    };
```

Line 568 of `EditUriBuiltins.js`:
            ```EditUriBackendConfig.require_username_and_password_or_key(scope);```

At least a first shot will just not check if `--ssh-keyfile=` is present.

**Comment by kenkendk** [comment]
Yes, that would require a callback to the server to have it read the file and guess if it requires a password. I think your solution is good enough, as the "Test" button will give an error like "Password required for encrypted private key".

If you make it a PR as-is, then the user can work with unencrypted private key files.

**Comment by Pectojin** [comment]
I think you might be overcomplicating this slightly... Just remove the password check. 

It's technically possible to ssh into linux boxes with no password and no ssh key using the `PermitEmptyPasswords yes` option. It's insanely insecure, but who are we to decide how people SSH?

Removing the password check on the frontend will enable 2 use cases while removing 2 lines of code.

I've just tested it on my own system. By removing line 107 and 108 in `EditUriBackendConfig.js` I was able to connect to my server over SFTP with a passwordless private key and without declaring any password.

**Comment by Clete2** [comment]
I mean honestly.... I just put "asd" as the password and used my key.

**Comment by Pectojin** [comment]
Lmao, I actually wasn't sure if it would fail in the backend with a password until I tested. Luckily the backend is solid and didn't require changes for unprotected SSH keys.

I still haven't tested ssh keyless and passwordless because, well I don't own such a system, but in principle it should work as well.
