### ISSUE TITLE
Backup broken after shutdown

### ISSUE THREAD

**Issue by gorbiWTF** [duplicati/duplicati#2665]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.72_canary_2017-07-05
**Operating System:** Windows 10 x64 (15063.540)

I had a new very large file in a location that I backed up. Backup was apparently running (for more than 6 hours), but I shutdown my PC. Next backup failed: 

> Duplicati.Library.Interface.UserInformationException: Found 5006 files that are missing from the remote storage, please run repair
>    bei Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
>    bei Duplicati.Library.Main.Operation.BackupHandler.PostBackupVerification()
>    bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
>    bei Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
>    bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
>    bei Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
>    bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

Repair didn't do anything for more than an hour, just said "starting..."

> System.Threading.ThreadAbortException: Der Thread wurde abgebrochen.
>    bei System.Data.SQLite.UnsafeNativeMethods.sqlite3_changes_interop(IntPtr db)
>    bei System.Data.SQLite.SQLite3.get_Changes()
>    bei System.Data.SQLite.SQLiteStatement.TryGetChanges(Int32& changes, Boolean& readOnly)
>    bei System.Data.SQLite.SQLiteDataReader.NextResult()
>    bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>    bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>    bei System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
>    bei Duplicati.Library.Main.Database.ExtensionMethods.ExecuteNonQuery(IDbCommand self, String cmd, Object[] values)
>    bei Duplicati.Library.Main.Database.LocalRepairDatabase.FixDuplicateMetahash()
>    bei Duplicati.Library.Main.Operation.RepairHandler.RunRepairCommon()
>    bei Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
>    bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
>    bei Duplicati.Library.Main.Controller.Repair(IFilter filter)
>    bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

Then I tried to repair and delete:

> Duplicati.Library.Interface.UserInformationException: No files were found at the remote location, perhaps the target url is incorrect?
>    bei Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
>    bei Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run(String path, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
>    bei Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal(IFilter filter)
>    bei Duplicati.Library.Main.Operation.RepairHandler.Run(IFilter filter)
>    bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
>    bei Duplicati.Library.Main.Controller.Repair(IFilter filter)
>    bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)

After just deleting the database I could start a backup. It did a full backup but stopped with this error:

> Fatal error
> Duplicati.Library.Interface.UserInformationException: Found 447 files that are missing from the remote storage, please run repair
>    bei Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
>    bei Duplicati.Library.Main.Operation.BackupHandler.PostBackupVerification()
>    bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

Now I started another repair, it only says "Starting..." but I see the progress bar is moving... Can I save the backup or should I just start a new one?

Edit: What ever happened to it, I had to start a new backup and can't even restore the old one...

**Comment by kenkendk** [comment]
That sounds bad. Not sure what happens here.

The first error message "found 5006 files" indicates that the local database is empty, or that "someone" dumped 5006 Duplicati files in the folder (unlikely).

The message "No files were found" indicates that the folder is empty, which is very odd, given the previous message.

The next message "Found 447 files" really adds to the confusion.

Have you changed the `--backup-prefix` value such that there is more than one backup in the folder, and this trips something?

**Comment by gorbiWTF** [comment]
No, I didn't change anything since April, when I started a new backup. I always create a new folder for a new backup.

**Comment by gorbiWTF** [comment]
I readded the configuration after I deleted it, tried to start a new backup (failed with "Found 265 files that are missing from the remote storage, please run repair") and then I downloaded this [bugreport](https://www.dropbox.com/s/fajtjgpxn4dy0op/bugreport.zip?dl=0). I hope it helps.

**Comment by warwickmm** [comment]
Sorry for the lack of response here.  Duplicati's ability to handle interruptions has since been improved.  I'm going to close this due to lack of activity, but please re-open if you continue to encounter this with newer versions of Duplicati.
