### ISSUE TITLE
Disable on battery

### ISSUE THREAD

**Issue by cjustin88** [duplicati/duplicati#2666]
Hi,

Would it be possible to add an option `disable-on-battery` or `allow-ac-only` that will get the power source from `acpid` or `systemd` and dis-allow the backup from proceeding if the computer is not plugged in? This could be useful for preserving battery life on a laptop. On my Mac, I use Arq, which has this feature and on my Windows machine, I used to use Crashplan, which also has this feature.

It would be best to implement this in a distribution-agnostic way (I think `systemd` has replaced most functions of `acpid` on Fedora, for instance).

Thanks,
Justin

**Comment by kenkendk** [comment]
Yes, I think it would be possible, but it would have to be implemented differently on all platforms.

**Comment by ccoVeille** [comment]
Duplicate for #2464 (or at least related)

**Comment by warwickmm** [comment]
I think Linux exposes enough information through sysfs so that we can detect the power source without assuming the existence of certain user space programs or init systems.  I have some ideas that I might try to mock up and see what people think.

**Comment by hydrian** [comment]
Systemd can definitely stop the service if running the headless daemon. We just need to make sure that duplication stops gracefully from the appropriate SIG* signal. 

Not sure if something more uniform and cross-platform should be thought about too. This is very Linux centric. Not sure how this would be handled in other OSes.

**Comment by warwickmm** [comment]
This was implemented in pull request #3086.
