### ISSUE TITLE
"Failure has occurred while loading a type" when connecting to Azure Storage

### ISSUE THREAD

**Issue by bherila** [duplicati/duplicati#2668]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.2.1_beta_2017-08-01
**Operating System:** OSX
**Backend:** Azure

### Bug description
When I fill in the connection information and click "Test Connection," there is an error message: 

Failed to connect: Failure has occurred while loading a type.

### debug log

{
  "Message": "Failure has occurred while loading a type.",
  "Type": "TypeLoadException"
}

not sure how to get a more complete stack trace?

**Comment by bherila** [comment]
I found https://github.com/duplicati/duplicati/issues/1926 but not sure if it is related?

**Comment by kenkendk** [comment]
I don't think #1926 is related, because Mono on OSX is not so modular, it just has "it all".

To get the full error, run `Duplicati.GUI.TrayIcon.exe` in a terminal like this:
```
MONO_LOG_LEVEL=debug /Applications/Duplicati/Contents/MacOS/duplicati
```

This should give detailed information about where in the code the load error happens.

**Comment by bherila** [comment]
Thank you @kenkendk 

Apologies for the delayed reply. I am out of town until 9/12 and will be able to grab the logs when I get back.

**Comment by kenkendk** [comment]
I figured out the problem with the help from others:
https://forum.duplicati.com/t/backup-stopped-working-on-debian-jessie-with-azure/282/12
