### ISSUE TITLE
Duplicati fails to bind to non-localhost

### ISSUE THREAD

**Issue by rkarlsba** [duplicati/duplicati#2670]
I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.2
**Operating System:** Debian Stretch
**Backend:** Jotta

### Bug description
--webservice-interface:any or --webservice-interface:ens3 are not honored. It still listens to localhost instead, which isn't what I want. I know there are security issues with listening to an open port, but this is easily fixed in the firewall and other stuff. I'd just like to use this as a normal service on my private LAN.

### Steps to reproduce
- Just try to run it as above

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
It still listens to 127.0.0.1:8200

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
It should listen to *:8200

**Comment by kees-z** [comment]
Replace the colon with an equal sign. It's `--webservice-interface=any `, not `--webservice-interface:any `.

**Comment by kenkendk** [comment]
I am closing as I think the original question has been answered.
