### ISSUE TITLE
Google Drive backend should ignore trashed folders and files

### ISSUE THREAD

**Issue by Pectojin** [duplicati/duplicati#2673]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.2.1_beta_2017-08-01
**Operating System:** Ubuntu 17.04
**Backend:** Google Drive

### Bug description
It seems that Duplicati keeps a cached list of directories created in Google Drive and if that directory is deleted the cache prevents duplicati from realizing. 

### Steps to reproduce
- Create new backup
- Set backup directory in Google Drive to be backup/weekly/server
- Test the connection
- Accept creation of folder
- Complete backup creation
- Delete backup folder from Google Drive 
- Edit backup config
- Test the connection again, which results in the error 'Failed to connect: There is more than one item named "server" in the folder'
- Subsequent backup attempts will also fail with said error
- Manually recreating the folder does not resolve the issue.

**Actual result:** I'm unable to backup to a given path or setup a new backup to the path if a duplicati folder was previously deleted from that path
**Expected result:** Duplicati should detect a folder no longer existing and recreate it - ideally even if it finds out during a backup.

### debug log
`Duplicati.Library.Interface.UserInformationException: There is more than one item named "server" in the folder "/backup/weekly/"
  at Duplicati.Library.Main.BackendManager.List () [0x00038] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x0000d] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x00000] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend, System.String protectedfile) [0x00066] in <118ad25945a24a3991f7b65e7a45ea1e>:0 `

**Comment by kenkendk** [comment]
Could it be that Google actually keeps the folder around (in trash perhaps?) and Duplicati sees the folder, even though Google's UI hides it?

**Comment by Pectojin** [comment]
You were right. Undeleting or deleting it completely from trash "fixes" the problem. Apparently, to google cloud, "deleted" items aren't deleted they're just invisible.
Although I'm starting to realize the real problem is google's extremely weird handling of "folders". 

I guess a nicer way to handle it may be to have Duplicati looking at the labels.trashed attribute of a preexisting folder and then either renaming or deleting the folder for good? Possibly prompting to confirm.
I've verified that simply renaming the folder before deleting it (or not deleting it) allows Duplicati to create a new folder.

In Google cloud it seems that Duplicati cannot use or even touch folders I made, so it seems pretty safe to allow it to delete/rename trashed items as that can only be discarded Duplicati folders.

**Comment by kenkendk** [comment]
When using the "Google Drive" login via the OAuth page, Duplicati only gets access to "own files", which ensures that it does not mess up other stuff stored on GDrive. You can use the "Google Docs" login option to get a token that can touch all files.

I have changed the topic to request that Duplicati ignores "trashed" folders.

**Comment by Pectojin** [comment]
Sounds good!

**Comment by warwickmm** [comment]
Fixed in #3856.
