### ISSUE TITLE
Deleting one backup job on WebDAV deletes _ALL_ backup data from _ALL_ sources!

### ISSUE THREAD

**Issue by rhester72** [duplicati/duplicati#2678]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:**  2.0.2.1_beta_2017-08-01
**Operating System:** Windows 10 / Arch Linux
**Backend:** Local WebDAV

### Bug description
When backing up multiple hosts to a single WebDAV back-end, even when using prefixes, deleting any backup job and indicating "yes, I want to delete the data as well" removes *ALL* data from WebDAV, not just the data associated with the backup set

### Steps to reproduce
- Set up local WebDAV backend
- Install Duplicati on two machines
- On each machine, specify a *different* default prefix
- Create a test backup job on each machine using the same WebDAV back-end as a target
- Run the test backup on each machine, validating that the files show up on the DAV host with proper prefixes
- On the machine last backed up, delete the test backup job, including configuration *and* data/content
- Pass the CAPTCHA
- After the job is deleted, look at the DAV directory and observe that it is now empty and no longer contains the backup data from the other host with a different prefix

**Actual result:** All of your backup data, from all jobs, prefixes and hosts, is permanently deleted
**Expected result:** Only the data associated with the deleted backup job for that specific host is deleted

**Comment by kenkendk** [comment]
Ouch! I generally advice people to use two different folders, as it makes it much more transparent what happens, but I had not expected this.
