### ISSUE TITLE
Remove duplicate donate links

### ISSUE THREAD

**Issue by daylightbrightledlight** [duplicati/duplicati#2679]
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.2.1_beta_2017-08-01
**Operating System:** macOS 10.12
**Backend:** ?

### Bug description
The donate links (PayPal and Bitcoin) are found on both the top and bottom bars of the UI. This can be excessive and may be off-putting for users, decreasing the likelihood of receiving donations.

**Comment by hoilc** [comment]
Setting - Donation messages - Donation messages are visible, click to hide

**Comment by kenkendk** [comment]
@renestach care to weigh in? The top ones go away when the screen is small, so maybe we can remove those altogether?

**Comment by renestach** [comment]
We could make the bottom bar always visible/floating so that also the social media links and the "About" link is always reachable easily. In that case we can remove the donation links at the top.

**Comment by daylightbrightledlight** [comment]
@renestach I think the bottom "About" link is useless, because it achieves the same goal of pressing the "About" tab on the left menu.

**Comment by ts678** [comment]
[2.0.2.17_canary_2018-01-23](https://github.com/duplicati/duplicati/releases/tag/v2.0.2.17-2.0.2.17_canary_2018-01-23) appears to have fixed this.

> Updated external links in the UI to be clearly marked

[Reworked the way external links are displayed, such that all external links are clearly marked.](https://github.com/duplicati/duplicati/commit/caf95ff5f7df9dd0b05e083599f83f541f5f4ada) added the "display: none" below, I think.

https://github.com/duplicati/duplicati/blob/019656133a9c5e16d463da600af985911be65f5a/Duplicati/Server/webroot/ngax/less/style.less#L2020-L2024

Regardless, how does it look to you now? In my testing on Windows, using several browsers and window sizes, bottom bar looks OK.

**Comment by warwickmm** [comment]
Thanks @ts678.  I think we can consider this fixed.
