### ISSUE TITLE
systemd fails to start duplicati.service

### ISSUE THREAD

**Issue by jeffrutledge** [duplicati/duplicati#2687]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.2.2-2
**Operating System:** Arch Linux
**Backend:** Google Drive

### Bug description
Running `systemctl --user start duplicati.service` errors.

### Steps to reproduce
- install the arch AUR duplicati-latest package
- run `systemctl --user start duplicati.service`

**Actual result:** It was working fine early this week so I think the recent update must have cause something. Now despite the service being enabled it isn't open at startup and if I try to reset or start the service it is still not running. By not running I mean when I go to `localhost:8200` nothing loads.

**Expected result:** After starting the service duplicati should be running and `localhost:8200` should load the web gui.

### debug log
Output from `systemctl --user status duplicati` after starting the duplicati service:

```
● duplicati.service - Duplicati
   Loaded: loaded (/usr/lib/systemd/user/duplicati.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-09-02 19:59:42 PDT; 15min ago
  Process: 7171 ExecStart=/usr/bin/mono /opt/duplicati-latest/Duplicati.GUI.TrayIcon.exe --webservice-port=8200 (code=exited, status=1/FAILURE)
 Main PID: 7171 (code=exited, status=1/FAILURE)

Sep 02 19:59:41 beignet systemd[380]: Started Duplicati.
Sep 02 19:59:41 beignet mono[7171]: Server has started and is listening on 127.0.0.1, port 8200
Sep 02 19:59:42 beignet mono[7171]: cannot open display: 
Sep 02 19:59:42 beignet systemd[380]: duplicati.service: Main process exited, code=exited, status=1/FAILURE
Sep 02 19:59:42 beignet systemd[380]: duplicati.service: Unit entered failed state.
Sep 02 19:59:42 beignet systemd[380]: duplicati.service: Failed with result 'exit-code'.
```

Interestingly when I execute `/usr/bin/mono /opt/duplicati-latest/Duplicati.GUI.TrayIcon.exe --webservice-port=8200` it opens fine. However, it doesn't have my backup setup (it is like opening a fresh install).

Something that changed on this update is that this now opens a tray icon which was not there in the past. I don't know if this is related.

Let me know if there is more of a debug output I can give.

**Comment by kenkendk** [comment]
When running as a service, it is running as root.
The configuration is stored in `~/.config/Duplicati/Duplicati-server.sqlite`, which is why you see something different when you run it as your normal user.

The tray-icon is optional, but you can start it with:
```
/usr/bin/mono /opt/duplicati-latest/Duplicati.GUI.TrayIcon.exe --no-hosted-server --hosturl=http://localhost:8200
```

This will cause the tray-icon to connect to the server running as root.

The problem running the service seems to be related to `cannot open display` which I don't know why you are getting.

Maybe you can try running:
```
sudo /usr/bin/mono /opt/duplicati-latest/Duplicati.Server.exe
```

And see if you get some error.

**Comment by jeffrutledge** [comment]
Not sure what fixed it, but I my Duplicati works now. I have updated my version to Duplicati - 2.0.2.4_canary_2017-09-09. As well as updated the rest of the my pacman packages.

The service with `systemctl --user start duplicati` still doesn't work.
Output from systemctl --user status duplicati after starting the duplicati service:
```
● duplicati.service - Duplicati
   Loaded: loaded (/usr/lib/systemd/user/duplicati.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-09-10 19:46:39 PDT; 4min 40s ago
 Main PID: 2929 (code=exited, status=1/FAILURE)

Sep 10 19:46:38 beignet systemd[385]: Started Duplicati.
Sep 10 19:46:39 beignet mono[2929]: Server has started and is listening on 127.0.0.1, port 8200
Sep 10 19:46:39 beignet mono[2929]: cannot open display: 
Sep 10 19:46:39 beignet systemd[385]: duplicati.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 19:46:39 beignet systemd[385]: duplicati.service: Unit entered failed state.
Sep 10 19:46:39 beignet systemd[385]: duplicati.service: Failed with result 'exit-code'.
```

Yet `systemctl start duplicati` works fine and makes `http://localhost:8200/` load well:
Output from systemctl --user status duplicati after starting the duplicati service:
```
● duplicati.service - Duplicati
   Loaded: loaded (/usr/lib/systemd/system/duplicati.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2017-09-10 19:47:32 PDT; 9min ago
 Main PID: 3055 (mono)
    Tasks: 14 (limit: 4915)
   CGroup: /system.slice/duplicati.service
           └─3055 /usr/bin/mono /opt/duplicati-latest/Duplicati.Server.exe --webservice-port=8200

Sep 10 19:47:32 beignet systemd[1]: Started Duplicati.
Sep 10 19:47:33 beignet mono[3055]: Server has started and is listening on 127.0.0.1, port 8200
```

I thought it might be a conflict thing, but I have stopped the non `--user` service and the `--user` service still doesn't work.
