### ISSUE TITLE
Duplicate options under 'Configure http requests'

### ISSUE THREAD

**Issue by tygill** [duplicati/duplicati#2688]
### Version info
Duplicati Version: 2.0.2.1_beta_2017-08-01
Operating System: Windows 10

### Bug description
In both the 'Default settings' section of the main Settings page and the 'Advanced options' of the new backup process, the set of options underneath the 'Configure http requests' section are all listed twice.

### Screenshots
![image](https://user-images.githubusercontent.com/1046210/30007759-46b3b800-90d3-11e7-8e45-92c771492c78.png)

**Comment by kees-z** [comment]
This bug is already submitted: #2184

**Comment by tygill** [comment]
Hm. I somehow didn't find that when searching for an existing issue. Thanks for pointing it out!
