### ISSUE TITLE
Interoperability with RSync

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#270]
_From [Henrik68@gmail.com](https://code.google.com/u/Henrik68@gmail.com/) on September 19, 2010 01:56:44_

Duplicati has been designed with different backends (without dedicated backup software) in mind. For comparison Duplicity requires RSync. However, it would be nice if Duplicati would allow better interoperability with RSync; allowing a fixed set of files where only diff needs to be sent to RSync backend (similar to using RSync in the first place on the source files). Requirement is thus that full backups need to be as much alike as possible. The benefit is to allow use of for instance inexpensive NAS devices for backups and still keep multiple copies on the NAS (using RSyncs link command or by running 'cp -al' script on the NAS) while at the same time reducing bandwidth consumption for (full) backups. 

Suggestion is settings that would allow:
a) Consequtive full / incremental backup on the same source file set to produce same encrypted output and that varience in one file doesn't change the whole backup
b) Userdefined naming of files instead of the current fixed date / time format. Suggestions could be to include DMY, HMS as well as Weekday and that these different elements could be mixed and appended to the prefix.

A reoccurring weekly full backup with daily incremental backups to be copied over RSync could thus contain files like 'duplicati-full-content.Mon' and 'duplicati-inc-content.Tue'. Since file names repeat every week, RSync could be used for off-site backups.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=270_

**Comment by kenkendk** [comment]
Closing this, as the 2.0 file format is very RSync compatible

**Comment by agrajaghh** [comment]
still open :stuck_out_tongue_winking_eye:

**Comment by kenkendk** [comment]
:)
