### ISSUE TITLE
UI password changes?

### ISSUE THREAD

**Issue by zappeee** [duplicati/duplicati#2702]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- Duplicati version: 2.0.2.1_beta_2017-08-01
- Operating system: Win10
- Backend: -

## Description
Has there been any changes regarding this?
When I started to use passwords I had to enter it every time I opened the web interface.
But now I rarely have to put it in.

## Steps to reproduce
Right click icon -> Open

- **Actual result:** 
UI opens

- **Expected result:**
I have to enter a password before it opens

## Screenshots
-

## Debug log
-

**Comment by kenkendk** [comment]
Yes, @mnaiman has worked hard to get the tray-icon to work with various password properties.
The tray-icon is connected to the server (it started it after all) so it registers a session and then opens the browser within that sessions so you do not have to type the password.

In other words, if people can click on the tray icon, they can access Duplicati.

If you browse manually to the webpage, you will not be in a session and will be asked for a password.

Does this answer the question?

**Comment by zappeee** [comment]
It does, thanks!
