### ISSUE TITLE
Different password handling between CLI and web GUI

### ISSUE THREAD

**Issue by DivotDigger** [duplicati/duplicati#2703]
## Environment info
- Duplicati version: Multiple, most recently tried on 2.0.2.3_canary_2017-09-08
- Operating system: Centos and Fedora
- Backend: SFTP and local

## Description
The CLI and Web GUI handle passwords differently.  I've read other bug reports where passwords with special characters (eg $) need to be escaped with a \.  However, one would assume that the entered password between both CLI and GUI would handle the input in the same manner.  They don't.

Background:  I used duplicati-cli to backup a server.  The server failed and I attempted to restore it on a separate host with the web GUI.  When trying to import the backup set, it failed saying the encryption password was incorrect. The password works fine when used on the CLI with the '--passphrase=<ComplexPasswordHere> option.

## Steps to reproduce
1. Backup with cli using complex password and special characters
2. Restore with gui and enter exactly the same password.

- **Actual result:** 
GUI complains that the encryption password is incorrect.

- **Expected result:**
It should process as normal.

Please let me know if you need further information.

**Comment by ttr** [comment]
This expected - your shell will interpret those characters before executing desired command (duplicati-cli in this example). https://github.com/duplicati/duplicati/issues/2649 as similar issue.

I'll maybe ask developers to change cli command generation in WebUI to put single quotes around all parameter values (so, if we copy command from web to run manually from cli it will have quotes).

**Comment by kenkendk** [comment]
Yes, I don't think there is anything I can do to mitigate this, except reduce the number of allowed characters, but I would consider that a security issue.

I am closing, but feel free to re-open if you have other input or mitigation suggestions.

**Comment by BumbrT** [comment]
Fuck this. Still can't restore my backup on windows. there should be BIG RED LETTERS WHEN YOU TRYING INPUT PASSWORD WITH SPECIAL CHARACTERS (ACTUALLY 99% OF USERS SHOULD DO THIS)
