### ISSUE TITLE
Backup to S3 starts, uploads between 1 and 3 .dlist files, then hangs 

### ISSUE THREAD

**Issue by richardcookson** [duplicati/duplicati#2705]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Ubuntu 16.4 LTS
- **Backend**: Amazon S3

## Description
Running backup to Amazon S3 using all default settings.
Backup starts and between 1 and 3 (depending on what I ask it to backup) .dlist files are uploaded to S3. The process then hangs for some time and eventually exits with an error:
"Error making request with Error Code BadRequest and Http Status Code BadRequest. No further error information was returned by the service."

## Steps to reproduce
1. Set up backup to S3 with all default settings

- **Actual result**:
Hangs and eventually exits with BadRequest error
- **Expected result**:
Completes backup

## Debug log
[bugreport.zip](https://github.com/duplicati/duplicati/files/1290403/bugreport.zip)

**Comment by kenkendk** [comment]
Are you sure this is to Amazon S3, and not an "S3 compatible" provider?

From the bug report, it appears that you can upload small files, but the large files are rejected or fails. If this is for Amazon S3, could it be that there is some kind of timeout or eager firewall that closes long running connections?

**Comment by richardcookson** [comment]
Thanks for your reply.

Yes, it is Amazon S3.

The final error looks like a timeout, but from observing the backup, the
process appears to hang after only a couple of minutes. There is no sign of
any transfer going on from my limited observations of router lights
flickering etc. The final error comes some time later (many minutes), but
prior to this the process appears to hang and probably does fail with a
time out eventually. I haven't timed how long it takes for the error to
appear but I don't think it could be described as particularly 'eager'.

I will check that I don't have any local timeout settings on my firewall.



Richard Cookson Phd, BSc(Hons), MIOA
Senior Consultant

PDA Ltd
Tel: 01925 759380

**Comment by user55295** [comment]
I have the exact same issue, except running on Mac OS X version 12, Duplicati version 2.0.3.3_beta_2018-04-02.  Smaller backups (a few GB) work, but a larger backup of about 60 GB fails.  Based on the messages, it seems to only run for about two minutes, and it has never succeeded.

**Comment by ts678** [comment]
[https://usage-reporter.duplicati.com/](https://usage-reporter.duplicati.com/) is showing about 6 million S3 backups per year, and there's not (now) a general problem.

Possibly things have been fixed. I'm pretty sure the S3 library (which Amazon offers) has been updated a few times to fix issues.

[Duplicati.CommandLine.BackendTester.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlinebackendtesterexe) is a good way to test suspected problems. It's very configurable, e.g. for test file size.

> Before you start using a particular backend to use as a backup target, you can use the Backend Tester to get an indication of the integrity of that backend.

[Duplicati.CommandLine.BackendTool.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlinebackendtoolexe) is good for manual driving after you think some problem has been somewhat isolated.

Of course, Duplicati itself has had fixes. Is issue still of interest and reproducible?
