### ISSUE TITLE
Duplicati crashes with --webservice-interface=all

### ISSUE THREAD

**Issue by andrewdbate** [duplicati/duplicati#2706]
- [x] I have searched open and closed issues for duplicates.
----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1
- **Operating system**: Ubuntu 16.04 (fresh install, no additional packages, all updates applied)
- **Backend**: N/A (was not able to proceed that far)

I have tried this with both Ubuntu Server 16.04 and Ubuntu MATE 16.04 inside of VMware Workstation 12 Player. For the network configuration of the virtual machines I have tried both NAT and Bridged, and it did not make any difference.

## Description
Starting `duplicati` or `duplicati-server` from the terminal with the `--webservice-interface=all` option specified resulted in a crash and the process does not start.

## Steps to reproduce
1. Install VMware Workstation 12 Player on Microsoft Windows 7 Professional x64.
2. Create a new virtual machine, and install Ubuntu MATE 16.04 using the 'easy install option'.
3. After install, in a terminal run `sudo apt update` and then `sudo apt upgrade` to get all updates.
4. In a terminal, run `wget https://updates.duplicati.com/beta/duplicati_2.0.2.1-1_all.deb`.
5. In a terminal, run `sudo apt install ./duplicati_2.0.2.1-1_all.deb`.
6. In a terminal, run `duplicati-server --webservice-interface=all`.

At this point, the Duplicati program crashes. Trying the above but with Ubuntu Server 16.04 instead results in the same crash. See the screenshots below.

Trying the above but with `duplicati --webservice-interface=all` in Step 7 (i.e., `duplicati` instead of `duplicati-server`) also results in the same crash.

Please note that VMware 'easy install' installs the operating system as an 'unattended install' and automatically installs VMware Tools after the OS install. This is the recommended way to install the OS inside an VMware Workstation 12 Player VM.

- **Actual result**:
The program crashed with the backtrace included in _debug log_ below.

- **Expected result**:
I expect the program to start, and for the web service to be available to access from another computer on the local network (as per the `--webservice-interface=all` flag).

Please note that I am only running Duplicati inside of a VM for testing and evaluation purposes, but I would not expect the program to crash.

## Screenshots

The crash on Ubuntu MATE 16.04 inside VMware Workstation Player 12:
![screenshot](https://user-images.githubusercontent.com/2998569/30251911-07b9dc86-9661-11e7-9d51-2cd92b7342a4.png)

The crash on Ubuntu Server 16.04 inside VMware Workstation Player 12:
![screenshot2](https://user-images.githubusercontent.com/2998569/30251918-48bc23c4-9661-11e7-83a6-aa29cca20bad.png)

## Debug log
```
A serious error occurred in Duplicati: System.FormatException: An invalid IP address was specified.
  at System.Net.IPAddress.Parse (System.String ipString) <0x41c13060 + 0x00053> in <filename unknown>:0 
  at Duplicati.Server.WebServer.Server..ctor (IDictionary`2 options) <0x41c14740 + 0x004e7> in <filename unknown>:0 
  at Duplicati.Server.Program.RealMain (System.String[] args) <0x41bbfae0 + 0x018d7> in <filename unknown>:0 
```

**Comment by andrewdbate** [comment]
Update: Just tired exactly the same thing in bhyve (the BSD Hypervisor) and I get exactly the same crash.

**Comment by kees-z** [comment]
I think `--webservice-interface=all` is the problem. You should specify here one of the following:

- A valid IP address of one of your connected network interfaces
- `loopback`
- `any` or `*`

Probably your problem will be solved after changing `all` to `any`: `--webservice-interface=any`.

**Comment by kenkendk** [comment]
Yes, @kees-z  is correct, use `any`.
I will commit a fix to also allow `all`.

**Comment by andrewdbate** [comment]
I would not however expect the program to crash with an exception if an incorrect parameter was supplied... Wouldn't it be better to print "Unrecognized option" and gracefully exit?
