### ISSUE TITLE
Assembly reference error under mono in Linux

### ISSUE THREAD

**Issue by akontsevich** [duplicati/duplicati#2710]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.0.0
- **Operating system**: openSUSE Linux

## Description
Build error under Linux and probably Mac because file system is case sensitive there: line 45 in `Duplicati/Library/Compression/Duplicati.Library.Compression.csproj` file need to change from lower case `sharpcompress` to `SharpCompress`
```
-      <HintPath>..\..\..\packages\sharpcompress.0.18.0\lib\net45\SharpCompress.dll</HintPath>
+      <HintPath>..\..\..\packages\SharpCompress.0.18.0\lib\net45\SharpCompress.dll</HintPath>
```

**Comment by cblichmann** [comment]
Can confirm, this fixes the build for me.
- **Duplicati version**: 2.0.2.4_canary_2017-09-09
- **Operation System**: Debian Buster

**Comment by kenkendk** [comment]
Mac is actually not case-sensitive by default, so it works for me on Mac.
Interestingly, the Travis-CI server is running Linux and not complaining ....

**Comment by kenkendk** [comment]
Not sure why it fails for you guys, but Travis does not like the CamelCase version:
https://travis-ci.org/duplicati/duplicati/builds/275410020

I can see that I had this problem before, and had to change the file to make it work on Travis: a5df2001ecf69aa970a76c906dd4b09e6241959f

**Comment by kenkendk** [comment]
Is this fixed for you now? I updated SharpCompress and it seems to have fixed the path?

**Comment by akontsevich** [comment]
Sure it fixed.
