### ISSUE TITLE
Cannot select no startup delay

### ISSUE THREAD

**Issue by JoeB99** [duplicati/duplicati#2715]
2.0.2.4_canary_2017-09-09

FreeNAS 11-U2 jail

In the web GUI, once a startup delay has been set, it cannot be set back to "no delay".

I think a new tick box should be added that, when ticked shows the startup delay settings, and when unticked, the startup delay settings are greyed out.

**Comment by kenkendk** [comment]
As a workaround for now, you can set `0s` (0 seconds).
