### ISSUE TITLE
Mega.nz connection fails

### ISSUE THREAD

**Issue by lukasIO** [duplicati/duplicati#2727]
connection was working fine before, then switched location via vpn while uploading (not sure if it's related), since then i cannot establish a connection to mega.nz anymore via duplicati (also with vpn disabled and pc rebooted etc.)

>
Fatal error
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

   bei CG.Web.MegaApiClient.Node.OnDeserialized(StreamingContext ctx)

   --- Ende der internen Ausnahmestapelüberwachung ---

   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   bei Newtonsoft.Json.Serialization.JsonContract.<>c__DisplayClass57_0.<CreateSerializationCallback>b__0(Object o, StreamingContext context)

   bei Newtonsoft.Json.Serialization.JsonContract.InvokeOnDeserialized(Object o, StreamingContext context)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserialized(JsonReader reader, JsonContract contract, Object value)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   bei CG.Web.MegaApiClient.GetNodesResponse.OnDeserialized(StreamingContext ctx)

   --- Ende der internen Ausnahmestapelüberwachung ---

   bei Duplicati.Library.Main.BackendManager.List()

   bei Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)

   bei Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)

   bei Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)

   bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

>

**Comment by lukasIO** [comment]
additional info:

If I try to setup a new backup using Mega.nz, the error message 
`Failed to connect: API response: ResourceNotExists`
appears when trying to test the connection.

**Comment by kenkendk** [comment]
The error happens inside the MegaApiClient library, so I think you should report it there:
https://github.com/gpailler/MegaApiClient/issues

**Comment by lukasIO** [comment]
solved the problem with the help of gpailler.
it was related to an encrypted folder in my shares!
