### ISSUE TITLE
Unable to delete backup

### ISSUE THREAD

**Issue by rkarlsba** [duplicati/duplicati#2734]
I have added a backup set that seems a bit too large to be practical (5+TiB), and having tried a few times, it often stops after a couple of terabytes. When I then start it again, it starts from scratch. Therefore, I've created smaller backup sets to allow smaller parts to finish quicker in case of interruption. Now, this initial backup I created doesn't want to go away. I've clicked delete, captcha, it returns without an error, but hasn't deleted anything. I'd really like to remove this, since it has 1-2TiB of rubbish on my backend, jotta. I can't find anything in the logs AFAICS.

Btw, shouldn't an interrupted backup be continued?

**Comment by kenkendk** [comment]
The "shouldn't it continue" question is answered here:
https://forum.duplicati.com/t/duplicati-initial-backup-finished-then-starts-again/294/9?u=kenkendk

**Comment by kenkendk** [comment]
Can you delete the files via the Jotta interface?

**Comment by rkarlsba** [comment]
no, since this was my first backup, I didn't think of putting it in its own directory, meaning the files are on the root, again, meaning the webthing at jotta times out. 

But then - the main problem isn't the data, but the job. Could it be the job cannot be deleted before the running job is finished? 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Da mihi sis bubulae frustrum assae, solana tuberosa in modo Gallico fricta, ac quassum lactatum coagulatum crassum. Quod me nutrit me destruit.

**Comment by rkarlsba** [comment]
System is idle now, important backups finished, so I've tried once more to remove the initial backup, no errors, nothing in the logs, but it's still there.

**Comment by demolitions** [comment]
I have the exact same problem, both with a successfully completed job, and with any just created jobs.
I cannot delete any backup jobs, no matter the size.
Same as @rkarlsba, no errors in interface nor in logs.
My destination is HubiC, my system is an Arch Linux x86_64 server.

**Comment by starrychloe** [comment]
I cannot delete the backup either! Since Duplicati does not work, I need to delete the backup and delete the files off DreamHost. I want Duplicati to sit idle until they fix it with a new release in a few years. I go through the CAPTCHA and it still has the backup job on the home page. Now I will need to kill the process, delete its directory, and uninstall Duplicati entirely. Such a shame - so much potential, squandered. It only had one job.

**Comment by CmdLnInt** [comment]
Creating a new backup seems to delete the "deleted" backup from the dashboard in the GUI.

**Comment by ts678** [comment]
Not reproducible now. Maybe something got fixed. To also delete the remote files, note that you have to check that as an option.

![image](https://github.com/duplicati/duplicati/assets/40771998/3f2bb727-b5c8-475e-83a3-65ae9ef461c3)

Anybody still having trouble with this on a current release?

**Comment by demolitions** [comment]
It's a 7 year old issue, I suspect most of the impacted people has switched to another backup solution, as I did when Duplicati unfortunately did not work well, the cloud storage I used as destination for Duplicati doesn't even exist anymore.
Thanks for the heads up, it's nice to know it's been (probably) fixed, if/when rsnapshot fails me I'll be giving Duplicati another try.
