### ISSUE TITLE
can't send using gmail

### ISSUE THREAD

**Issue by mauro-miatello** [duplicati/duplicati#2737]
i can't send email with gmail, i've tried from console too:

> C:\Program Files\Duplicati 2>Duplicati.CommandLine.exe send-mail --send-mail-url="smtps://smtp.gmail.com:465" --send-mail-username=myusername@gmail.com --send-mail-password=mypassword --send-mail-to=mydestinatio@fsw.it --verbose --log-level=profiling --accept-any-ssl-certificate=true
Input command: send-mail
Input arguments:

> Input options:
send-mail-url: smtps://smtp.gmail.com:465
send-mail-username: myusername@gmail.com
send-mail-password: mypassword
send-mail-to: mydestination@fsw.it
verbose:
log-level: profiling
accept-any-ssl-certificate: true

> Starting - Running SendMail
Running SendMail took 00:00:00.012
Invio email fallito: System.Security.Authentication.AuthenticationException: Il certificato remoto non è stato ritenuto valido dalla procedura di convalida.
 => Il certificato remoto non è stato ritenuto valido dalla procedura di convalida.

**Comment by NoLooseEnds** [comment]
Did you create an application specific password on your Google Account? I think you need to use that rather than your normal password.

**Comment by mmiat** [comment]
uhm i've only authorize not secure applications. I'll check if i need a password for this specific app. thanks.

**Comment by NoLooseEnds** [comment]
I'm going of memory here, but maybe you only get it if you have two factor authentication enabled.  I'm pretty sure I've solved similar issues where using applications specific password worked.

**Comment by kenkendk** [comment]
This could also be affected by the change to `--accept-any-ssl-certificate` in that the SMTP library does not use the new code, and thus does not ignore certificate failures.

That said, the gmail SSL certificate *is* trusted by Windows, so I am not sure why it gets rejected.

**Comment by mmiat** [comment]
can i add certificate manually?

**Comment by NoLooseEnds** [comment]
I just tested your command on Duplicati - 2.0.2.1_beta_2017-08-01 running on Linux Ubuntu.
And it worked with a gmail account with application specific password. I think I also have authorized not secure applications previously.

**Comment by kenkendk** [comment]
Yes, the beta build should not have issues with the certificates, and it should also be fixed in 2.0.2.8.

**Comment by mmiat** [comment]
from console it works, now i'll try with a scheduled backup

**Comment by mmiat** [comment]
it failed from job:

> 27 set 2017 15:11: Invio email fallito: System.Net.Sockets.SocketException: Il nome richiesto è valido, non sono stati trovati dati del tipo richiesto
{"NativeErrorCode":11004,"ClassName":"System.Net.Sockets.SocketException","Message":"Il nome richiesto è valido, non sono stati trovati dati del tipo richiesto","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   in Duplicati.Library.Modules.Builtin.SendMail.OnFinish(Object result)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nOnFinish\nDuplicati.Library.Modules.Builtin, Version=2.0.2.8, Culture=neutral, PublicKeyToken=null\nDuplicati.Library.Modules.Builtin.SendMail\nVoid OnFinish(System.Object)","HResult":-2147467259,"Source":"Duplicati.Library.Modules.Builtin","WatsonBuckets":null}

**Comment by kenkendk** [comment]
Could it be some firewall or network issue? Then message suggests that it is a DNS lookup failure?

**Comment by mmiat** [comment]
But from console It works



Il 29 settembre 2017 12:42:54 CEST, Kenneth Skovhede <notifications@github.com> ha scritto:
>Could it be some firewall or network issue? Then message suggests that
>it is a DNS lookup failure?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/duplicati/duplicati/issues/2737#issuecomment-333094095

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by mmiat** [comment]
still have this problem with 2.0.2.10
i've added in options:

> --log-level=profiling
--verbose=true
--log-file=C:\Users\fswAdmin\Desktop\duplicati.log

and this is what i find in it:

> 2017-10-13 08:44:40Z - Warning: Invio email fallito: System.Net.Sockets.SocketException: Il nome richiesto è valido, non sono stati trovati dati del tipo richiesto

> System.Net.Sockets.SocketException (0x80004005): Il nome richiesto è valido, non sono stati trovati dati del tipo richiesto
   in Duplicati.Library.Modules.Builtin.SendMail.OnFinish(Object result)

I've tried also to disable firewall and antivirus with no success
from console it works

**Comment by davegold24** [comment]
@mmiat Can you send email to your gmail account? (in other words, the same one as you are logging in as)

My suggestion for the next step is to use blat (www.blat.net) in debug mode, since it'll let you look at the entire connection conversation. The error is more likely to be obvious with blat than duplicati's email feature.

BTW, I've found that at one of my sites using gmail works fine, at another it fails.  I didn't end up troubleshooting, because I have a third party mail service and I know that it doesn't have any of the routing within/outside of googleland issues that gmail sometimes does, at least when using smtp.

**Comment by mmiat** [comment]
with argo mail server i can send, so i've solved my problem, if you want to close...
maybe there is some trouble with gmail filters/controls about spam or secure connection, i dont know

**Comment by mmiat** [comment]
I still have this issue, and also duplicati doesnt send info to duplicati-monitoring throught send-http-url

but from console I can send email, this is what I receive:

> MainOperation: SendMail
Lines: []
ParsedResult: Warning
Version: 2.0.3.11 (2.0.3.11_canary_2018-09-05)
EndTime: 26/10/2018 14:36:42 (1540557402)
BeginTime: 26/10/2018 14:36:41 (1540557401)
Duration: 00:00:00.1930110
Log data:
2018-10-26 14:36:42 +02 - [Warning-Duplicati.Library.Main.Controller-DeprecatedOption]: L'opzione log-level è obsoleta: Usa invece le opzioni log-file-log-level e console-log-level
2018-10-26 14:36:42 +02 - [Warning-Duplicati.Library.Main.Controller-DeprecatedOption]: L'opzione verbose è obsoleta: Imposta invece un livello di registrazione per il metodo di output desiderato
2018-10-26 14:36:42 +02 - [Warning-Duplicati.Library.Main.Controller-UnsupportedDisabledModule]: L'opzione --accept-any-ssl-certificate non è supportata perché il modulo Configura richieste http (http-options) non è attualmente caricato

it should be useful a "sent test mail" from duplicati monitoring....
how can I debug this issue?
thanks

**Comment by mmiat** [comment]
I've just updated to 2.0.4.4 and run my task manually with dry-run option, and I received email ! this noght hope finally has fixed this issue ! stay tuned ;)

**Comment by ts678** [comment]
> how can I debug this issue?

What operating system? Preinstalled tools vary, and if not on Windows, `mono` also has its own certificate store to take care of.

[Secure Socket Layer (SSL) / Transport Layer Security (TLS)](https://www.mono-project.com/docs/faq/security/) is debug help.

A certificate debug tool (can install it on Windows if needed -- other OS might already have it):

`openssl s_client -connect smtp.gmail.com:587 -starttls smtp`

[openssl-s_client](https://www.openssl.org/docs/manmaster/man1/openssl-s_client.html) manual page.

You had DNS problems earlier. `nslookup` is good for those. Changing DNS servers is also sometimes possible, if one has issue.

Although there have perhaps been relevant code changes, I don't know of any general Duplicati bug when sending with Gmail.
I just set it up on Windows without hitting any of the issues here. I did decide to use an app password. I'm not certain I had to.

Is this problem still of interest and happening? Did it ever get debugged further before? If need be, you can also post in forum.

This issue will close if it remains inactive.
