### ISSUE TITLE
Feature request: Pause or prioritise job

### ISSUE THREAD

**Issue by rkarlsba** [duplicati/duplicati#2738]
Hi

I have split my backup into smaller ones in case of crashes, and I'd like to just put some on pause or otherwise prioritise them so that the most important ones are run first. Would it be hard to add this?

Oh - btw - the "parallel" or "multicore" version, does that run jobs in parallel, og just a single job there too? Running them simultanous would be nice if you have sufficient cpu for it.

**Comment by kenkendk** [comment]
The "concurrent_processing" version is only enabling multithreading in a single backup.

**Comment by warwickmm** [comment]
Duplicates #2765.
