### ISSUE TITLE
Failed to repair, after repair 1 blocklisthashes were missing

### ISSUE THREAD

**Issue by Photographix** [duplicati/duplicati#2745]
How can I correct this error?
Duplicati 2.0.2.7
WinSvr 2012R2 x64

also in the WebUI I get errors

![2017-09-20 07_36_43-tools 192 168 200 29 - remote desktop connection manager v2 7](https://user-images.githubusercontent.com/16647382/30628563-5b5b4140-9dd7-11e7-83a8-e91dff982bd3.png)

**Comment by kenkendk** [comment]
You need to delete the local database and then run repair, which will re-build the local database for you.

You can get the path of the local database from the file `%LOCALAPPDATA%Duplicati\dbconfig.json`

If you can create a bug-report before you delete the local database, I would like to have a look to see if I can update Duplicati to not end up in this state again, and possibly also handle the case if it does happen.

**Comment by Photographix** [comment]
Hi, unfortunately I have the backup job re-created because I couldn't help myself. So I don't have any log files anymore.
