### ISSUE TITLE
S3 Compatible backup sets reset to Amazon S3 when editing 

### ISSUE THREAD

**Issue by cedartinkerer** [duplicati/duplicati#2747]
Hi I've noticed that if I create a custom url s3 backup that when I go to edit it the dropdown 'type' reverts back to Amazon S3.  As long as I re-select S3 Compatible before I hit next everything is fine. It just seems the UI makes the wrong assumption/storage of settings.  It would be nice if it correctly selected the type.

I'm using the current release.

**Comment by Indigo744** [comment]
There is a similar problems with OpenStack custom URL.
I selected OVH Cloud Storage (works fine), but when I come back to edit settings, the "OpenStack AuthURI" value is reset to Rackspace US...

**Comment by mmauri** [comment]
I am having the same problem with 2.0.2.1_beta_2017-08-01.
Indeed when you export the config to JSON, it writes Rackspace instead of OVH

**Comment by incyclum** [comment]
Duplicate of #2977?

**Comment by ts678** [comment]
2977 which possibly covers an OpenStack editing issue is now closed. Original S3 issue is not reproducible. Possibly it was fixed.

For S3, tried many scenarios of an Edit of existing configuration, including `Next` all the way through, and Save, then Edit again.
Without recent S3 editing reports, I will assume bug got fixed. It will close automatically unless someone wants to continue this.
