### ISSUE TITLE
More options to fix broken databases in the GUI

### ISSUE THREAD

**Issue by Nama** [duplicati/duplicati#2755]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 8.1
- **Backend**: local

## Description

Hi,
I had this morning a computer-freeze, during a running backup. That messed up with the remote files and the database ofc.
Duplicati was telling to do a repair. But repairing just put out an error with 3 files.

`Remote file referenced as duplicati-bb5009da74aa44638b4de815de90be87e.dblock.zip.aes, but not found in list, registering a missing remote file, Remote file referenced as duplicati-bd668d0bad92a494981b02462fee57e5b.dblock.zip.aes, but not found in list, registering a missing remote file, Remote file referenced as duplicati-b5b74ee314a344dd083a23caf11516d35.dblock.zip.aes, but not found in list, registering a missing remote file`

So I tried to verify. But verify error'd with 3 files, too and told me to repair, which ofc didn't work again.
After some hours of research and try and error, I found a commandline option `purge-broken-files`.
This did it for me.
**I understand, that this release is still beta, but such situations might happen a lot and I hope you plan to add `purge-broken-files` to the GUI as well.**

**Comment by Roadrunneruk** [comment]
This has happened  to me several  times and would be nice touch  to have
this in the gui

**Comment by kenkendk** [comment]
Yes, I would like a UI for it. Lack of time made me add the commandline page instead.

**Comment by Nama** [comment]
Since I switched to duplicacy many years ago and theres this newer issue #4996, I'm closing this.
