### ISSUE TITLE
GetAsync called after backend is shut down (Webdavs)

### ISSUE THREAD

**Issue by kaasszje** [duplicati/duplicati#2759]
- **Duplicati version**: 2.0.2.8_canary_2017-09-20
- **Operating system**: Windows 10
- **Backend**: Webdav (ssl)

Since the last update, I have this issue.
When the planned backup of my photo's runs.
It exists with this error:
Failed: GetAsync called after backend is shut down
Details: System.InvalidOperationException: GetAsync called after backend is shut down
   bij Duplicati.Library.Main.BackendManager.GetAsync(String remotename, Int64 size, String hash)
   bij Duplicati.Library.Main.AsyncDownloader.AsyncDownloaderEnumerator.MoveNext()
   bij Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction, BackendManager sharedBackend)
   bij Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact, BackendManager sharedManager)
   bij Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendManager backend, Int64 lastVolumeSize)
   bij Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
   bij Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(BackupResults result)
   bij Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)

Ran the backup yesterday again from the GUI.
And then it finished normally.

I've enable the debug info, so hopefully I can show the error tomorrow.

**Comment by deHoeninger** [comment]
Hi,
I've the same issue since last version (Duplicati - 2.0.2.8_canary_2017-09-20) with the ACD backend from time to time:
```
Failed: GetAsync called after backend is shut down
Details: System.InvalidOperationException: GetAsync called after backend is shut down
  at Duplicati.Library.Main.BackendManager.GetAsync (System.String remotename, Int64 size, System.String hash) <0x4072b7d0 + 0x0018b> in <filename unknown>:0 
  at Duplicati.Library.Main.AsyncDownloader+AsyncDownloaderEnumerator.MoveNext () <0x4072b220 + 0x00183> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.CompactHandler.DoCompact (Duplicati.Library.Main.Database.LocalDeleteDatabase db, Boolean hasVerifiedBackend, IDbTransaction& transaction, Duplicati.Library.Main.BackendManager sharedBackend) <0x406a7c00 + 0x015e3> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.DeleteHandler.DoRun (Duplicati.Library.Main.Database.LocalDeleteDatabase db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact, Duplicati.Library.Main.BackendManager sharedManager) <0x4069f210 + 0x00b07> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired (Duplicati.Library.Main.BackendManager backend, Int64 lastVolumeSize) <0x4069e930 + 0x0027f> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, IFilter filter) <0x406448b0 + 0x01b7f> in <filename unknown>:0 
```

**Comment by Photographix** [comment]
Same issue. Jotta Backend. Duplicati - 2.0.2.8 Cli & Gui

<code>
Fatal error => GetAsync called after backend is shut down
System.InvalidOperationException: GetAsync called after backend is shut down
   bei Duplicati.Library.Main.BackendManager.GetAsync(String remotename, Int64 s
ize, String hash)
   bei Duplicati.Library.Main.AsyncDownloader.AsyncDownloaderEnumerator.MoveNext
()
   bei Duplicati.Library.Main.Operation.CompactHandler.DoCompact(LocalDeleteData
base db, Boolean hasVerifiedBackend, IDbTransaction& transaction, BackendManager
 sharedBackend)
   bei Duplicati.Library.Main.Operation.DeleteHandler.DoRun(LocalDeleteDatabase
db, IDbTransaction& transaction, Boolean hasVerifiedBacked, Boolean forceCompact
, BackendManager sharedManager)
   bei Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired(BackendM
anager backend, Int64 lastVolumeSize)
   bei Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFil
ter filter)
   bei Duplicati.Library.Main.Controller.<>c__DisplayClass16_0.<Backup>b__0(Back
upResults result)
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths,
 IFilter& filter, Action`1 method)
   bei Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter f
ilter)
   bei Duplicati.CommandLine.Commands.Backup(TextWriter outwriter, Action`1 setu
p, List`1 args, Dictionary`2 options, IFilter filter)
   bei Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWr
iter errwriter, Action`1 setup, String[] args)

**Comment by kenkendk** [comment]
It is caused by this commit:
https://github.com/duplicati/duplicati/commit/e0d8a57ccc81bba71d805c3d5218eefcd14bc9bc

It closes the connection, then attempts to use it :/
