### ISSUE TITLE
DUPLICATI__BACKUP_NAME

### ISSUE THREAD

**Issue by janxbar** [duplicati/duplicati#2767]
Hi,

Could you introduce environment variable DUPLICATI__BACKUP_NAME that will hold backup name? This would be quite useful with run-script-after and other variables like DUPLICATI__PARSED_RESULT to create custom email on backup end.

Thank you for your time.

Kind regards, Jan

**Comment by kenkendk** [comment]
That should already be the case (for scripts):
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/RunScript.cs#L195

And for emails (not using the `DUPLICATI__` prefix):
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/SendMail.cs#L463

**Comment by janxbar** [comment]
thank you, Jan
