### ISSUE TITLE
Backup stuck for an unknown reason

### ISSUE THREAD

**Issue by alonpeer** [duplicati/duplicati#2774]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: `2.0.2.1_beta_2017-08-01`
- **Operating system**: `Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux`

## Description

I running `duplicati-server` and I've set up a backup for my photos and videos. Total of data to back up is about 150GB.
I have many file names with non-English characters, specifically Hebrew ones.
I'm backing up to S3, with all the default configurations.
The backup has been running for 5 days now, everything seems to be in order. I see no errors in the logs and I see files being added to my bucket regularly.
8 files (123MB) before the end of the backup, things seem to halt. The web UI says that the backup is running, but I see in the logs (and in the S3 bucket) that the last file was uploaded 12 hours ago.
I also looked at the `tmp` folder and I see a bunch of files of size 50MB that start with `dup-` - some were created 5 days ago and some 12 hours ago (around the time the last file was uploaded).
I opened the backup sqlite DB and poked around. Running the query `select * from File where BlocksetID < 0;` returns many entries where `BlocksetID` is `-100` (a negative value). All of the files with this value have a `Path` with Hebrew characters in it. I don't know if this matters or not. There are many other entries in that table with Hebrew characters in the `Path` and with a positive `BlocksetID` value.

I'm a newbie to this project. Please let me know what steps I should take to help make this easier to debug and reproduce.

Is it possible to stop the backup and restart the server? Will it reset my backup and start from scratch? Or will it continue from where it stopped?

**Comment by kenkendk** [comment]
The magic value `-100` means a directory, and the magic value `-200` means a symlink in the database, so no problems there. All path handling is using UTF-8 so there should be no problems with special characters.

You can safely stop the backup at any point and then run it again. It knows about the files and data already uploaded (stored in the database) so it will just re-sync the database and continue uploading whatever is missing/new.

**Comment by alonpeer** [comment]
Thank you for clarifying this @kenkendk. I will stop and restart my backup and follow up on this, in case it halts again. If everything's fine, I will close the issue.

**Comment by alonpeer** [comment]
Ok, it took some time (because it's a backup to S3 and not local), but the backup has successfully ended. 
What I did was to simply pause and start the backup again.
Closing this issue. Thanks!
