### ISSUE TITLE
What I go to restore, I'm not able to find all the directories that are supposed to be backed up

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [duplicati/duplicati#2778]
Any idea what's up with this?

**Comment by kenkendk** [comment]
That indicates that the directories are not backed up!

Can you provide some more information on the issue?

Can you provide a screenshot that shows the folder being included as source, and one that shows the restore tree missing the folder?

**Comment by Laurentiu-Andronache** [comment]
I would like to not have them public here. But if you give me your email, I'll email them to you.

**Comment by Laurentiu-Andronache** [comment]
Well? :D

**Comment by Laurentiu-Andronache** [comment]
Bump... this is a very serious issue.

**Comment by Laurentiu-Andronache** [comment]
I deleted the database and the directory where backup is made, and clicked "Run now" to have it done all over again. All directories still not showing up when I click on "Restore".

**Comment by Laurentiu-Andronache** [comment]
Lol, I even tried deleted complete the configuration, the backup, creating a new configuration and choosing the directories again, and some of them still don't show up. People, please don't use this software for backups lol.

**Comment by kees-z** [comment]
This doesn't seem to me a bug in Duplicati to me. I can't find any reported similar issues.
Do you have a filter defined that accidentally excludes some source files or folders?

If you review the selection of source files, are the missing items included in the selection? You can check this by editing your backup, go to step 3 (Source Data), click the "three-dots-menu" and click "Show advanced editor". A list of all selected source folders should appear.

In the same screen, you can check if any filters or excludes are set for your backup job.

**Comment by Laurentiu-Andronache** [comment]
Yeah, the directories are there and there are no filters/exclusions set.

**Comment by kees-z** [comment]
I'm not sure what could be the cause of the missing files in your backup. Maybe the files are backed up, but not registered in the local database? In that case, a rebuild of the local DB would help, but before you do that, it could help by querying the remote files directly by following this procedure:

- In the Web UI, click your backup job and click "Commandline" (under "Advanced"),
- Choose the command "Find" in the pull-down-menu.
- Leave the "Target-URL" textbox unchanged.
- Take a look at the contents of the "Commandline arguments" textbox. Are the missing folders included in this list? If this list represents all source files in the backup job, including the missing files/folders, delete everything in the text box.
Replace it with * to generate a list of all backed up files and folders.
- Remove EVERYTHING under "Advanced options", EXCEPT the Passphrase option.

Your screen should look something like this:

![duplicati commandline-find](https://user-images.githubusercontent.com/24669568/31816987-a3eea0aa-b592-11e7-91e5-5adc57adde43.png)

- Click the "Run find command now" button.

Files are downloaded directly from your remote storage and a list is presented containing all backed up files and folders of the latest backup.

Does this list contain the files and folders you are missing?
Note that there is no guarantee that the list is sorted alphabetically.

**Comment by Laurentiu-Andronache** [comment]
The list did not contain the missing files and folders. Thank you so much for the help.

Anyway, I have deleted the backup again, and this time I've selected as a source just one of the folders that wasn't showing up, clicked run backup now, and.... it shows up when I click restore.

So only one of them seems to be fine lol. Adding one more now.

**Comment by Laurentiu-Andronache** [comment]
**FINALLY, I have isolated and identified the bug.**

So when you have a directory like C:\Bla bla, you add it and it works.
But if you add afterwards to the backup a file named c:\b, the folders disappears, and only C:\b will be in the backup. Ridiculous!

**Comment by kees-z** [comment]
You are right, this is a bug that I can reproduce. After some test-backups, I made these observations:
- Folders disappear from the file browser only if a file is selected, that is the first part of another selected folder. So file "C:\Blast" and folder "C:\Bla bla\" works fine, but file "C:\Bla" and folder "C:\Bla bla\" results in only backups of file "C:\Bla" are available.
- Restoring folder "C:\Blabla\" is still possible from older backups, before file "C:\Bla" was added to the backup set.
- When creating a new backup with file "C:\Bla" and folder "C:\Blabla" both included, only file "C:\Bla" is available in the file picker.

**Comment by kenkendk** [comment]
Thanks for reporting and figuring out how to reproduce.

It is basically a filter that is supposed to remove a subfolder input (i.e. remove `C:\test\abc` if `C:\test\` is already included.
In a previous version, it was not possible to include files, so the code did not check if the shorter path was actually a folder.
The commit efc06b7 also fixes a problem in that the "test-filter" command does not not do the removal in the same way as the "backup" command, and in this case it hides the problem. The two methods now works exactly the same way.
