### ISSUE TITLE
Cannot create new backups not edit existing ones

### ISSUE THREAD

**Issue by GlenHenshaw** [duplicati/duplicati#2784]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

 Amazon Cloud Drive
- **Duplicati version**: Duplicati - 2.0.2.1_beta_2017-08-01
- **Operating system**: ElementaryOS 0.4 Loki
- **Backend**: Amazon Cloud Drive

## Description

As of this afternoon I cannot edit existing backups nor create new ones. Existing backups run fine.

## Steps to reproduce

1. Open Duplicati web interface
2. Click on an existing backup configuration
3. Click "Edit..."
4. Nothing happens at this point.

Exiting and restarting the Duplicati server does not change this behavior.

- **Actual result**:
No new edit or new backup window opens. It is as if the links are not active.
- **Expected result**:
Web interface should open an existing configuration for edit, or a new backup configuration.

**Comment by davegold24** [comment]
@GlenHenshaw What web browser were you using? Any firewall activated in your OS?
And the dreaded question: did you try to reboot?

Elementary OS looks interesting...but basically Ubuntu, so I would suspect a browser issue.

Have you looked at Duplicati logs?

**Comment by GlenHenshaw** [comment]
Elementary OS turned out to be unstable so I installed over it with Debian. The browser I was using at the time was the stock Elementary OS browser.

No problems with Debian... yet...

**Comment by warwickmm** [comment]
Closing this as it sounds like an issue with the browser.  If this issue continues to occur, please feel free to re-open.
