### ISSUE TITLE
Database repair fails if source data dir is read-only

### ISSUE THREAD

**Issue by rkarlsba** [duplicati/duplicati#2789]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Debian 9.1 stretch
- **Backend**: Jotta

## Description
If the backed up data directory is read-only, repairing the database fails. The database is writable. Duplicati goes into some sort of loop trying the same file over and over again, using 100% CPU on a single core. I/O usage is minimal or zero. Please see strace below. The data directory is mounted read-only to help improve security in case of a compromise or bug. There's a separate NFS mounted dir for restores, which is read-write.

## Steps to reproduce

1. Backup data from readonly filesystem (not sure if it was readonly in the first place, though)
2. Restore data

- **Actual result**:
Replace me
- **Expected result**:
Replace me

## From strace
7515  open("/data/Os/backup/utstilling-0.1.img", O_RDONLY) = 19
7515  fstat(19, {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  fstat(19, {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  lseek(19, 383692800, SEEK_SET)    = 383692800
7515  read(19, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 102400) = 102400
7515  close(19)
7515  stat("/data/Os/backup/utstilling-0.1.img", {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  lstat("/data/Os/backup/utstilling-0.1.img", {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  geteuid()
7515  getegid()
7515  access("/data/Os/backup/utstilling-0.1.img", W_OK) = -1 EROFS (Read-only file system)
7515  stat("/data/Os/backup/utstilling-0.1.img", {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  lstat("/data/Os/backup/utstilling-0.1.img", {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  geteuid()
7515  getegid()
7515  access("/data/Os/backup/utstilling-0.1.img", W_OK) = -1 EROFS (Read-only file system)
7515  stat("/data/Os/backup", {st_mode=S_IFDIR|0755, st_size=39, ...}) = 0
7515  lstat("/data/Os/backup", {st_mode=S_IFDIR|0755, st_size=39, ...}) = 0
7515  geteuid()
7515  stat("/data/Os/backup/utstilling-0.1.img", {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  lstat("/data/Os/backup/utstilling-0.1.img", {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  geteuid()
7515  getegid()
7515  access("/data/Os/backup/utstilling-0.1.img", W_OK) = -1 EROFS (Read-only file system)
7515  stat("/data/Os/backup/utstilling-0.1.img", {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0
7515  lstat("/data/Os/backup/utstilling-0.1.img", {st_mode=S_IFREG|0644, st_size=3904897024, ...}) = 0

**Comment by ts678** [comment]
The writeup seems confusing. Description refers to "backed up data directory" which I initially thought was Destination, however the Title and step 1 say it's read-only Source. The title says failure is from database repair, but step 2 says it's during the restore. There's talk of a read-write filesystem for restores, but the strace output looks more like a restore attempt to the read-only area.

Is this issue still of interest, and present currently? If so, is this a database repair problem, a restore problem (to where), or what?
