### ISSUE TITLE
Service crashes during backup runs

### ISSUE THREAD

**Issue by meersjo** [duplicati/duplicati#2792]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1-1 / 2.0.2.9-1
- **Operating system**: Linux Mint 17.3 "Rosa" (~ Ubuntu Trusty) 64-bit
- **Backend**: SSH

## Description

Repeated, but unpredictable crashes. Stackdump at https://gist.github.com/meersjo/d753574e428b99c20c7dec4b776f9fd7

Seems to occur more often when the webgui is open. Original problem seen on Beta; upgraded to latest canary .deb, same problem. 

It appears to have started when I extended the backupset to include more files - it now examines 612563 files.

Backup with the latest canary now just succeeded, with the gui only opened after it finished scanning the fileset. Not been able to determine wether this is consistent, yet. Yesterday morning's backup succeeded (on the Beta still); previous succesful was 22 september, even though the laptop is on every workday. Will continue to monitor.

- **Actual result**: 
Duplicati crashes before completing backup
- **Expected result**: 
Backup completes, software remains active.

## Debug log
Stackdump at https://gist.github.com/meersjo/d753574e428b99c20c7dec4b776f9fd7

**Comment by NoLooseEnds** [comment]
I think this could be the same issue as I have/had: #2791

**Comment by kenkendk** [comment]
This seems to be a crash in the Mono runtime. What version of Mono are you using?

**Comment by meersjo** [comment]
@NoLooseEnds : Thank you. I just tested it (and confirmed in /proc that FH_LIBRARY=managed was set for the process), but it still explodes.

@kenkendk: I'm (mostly...) on mono 3.2.8+dfsg-4ubuntu1.1 .  A full list of all mono-related packages is at https://gist.github.com/meersjo/b7b6e53581f9fd6d6d647828c05a0442 .

**Comment by kenkendk** [comment]
The version of Mono is quite old (the one that Ubuntu supplies), if you can install a more recent version, that will probably fix things: http://www.mono-project.com/download/#download-lin

**Comment by meersjo** [comment]
I just did so, will update later.

However, it bears considering that LTS versions of your target distro's are worth supporting; especially since the kind of people who care about setting up backups are also likely to be the kind of people who prefer an LTS version over having to upgrade every six months.

Incidentally, I worked around the problem by using daemon --respawn in my initscript; given that it does work every so often that sufficed to keep the backups going :-)

**Comment by meersjo** [comment]
/var/log/duplicati-server.err has not been touched since the update; it think it's fair to say that this issue seems to be resolved by the Mono upgrade.

As an aside - and I suppose there's already an issue for it, I'll have a look in a moment - it would be very useful if the Duplicati logfiles were to contain timestamps :-D

Thank you for the assistance.
