### ISSUE TITLE
Duplicati reset after update

### ISSUE THREAD

**Issue by Pectojin** [duplicati/duplicati#2793]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Ubuntu 16.04
- **Backend**:  Local storage and Google drive

## Description

Update 2.0.2.1_beta_2017-08-01 seems to have overwritten the entire Duplicati .config directory on my system. Removing everything from backup jobs to settings (i.e. the server isn't available on remote port anymore).

There isn't really a way for me to restore the config, but the backup targets are okay, so I'm just gonna set up new jobs and keep the old targets around for a while. 
Anyway, just reporting for transparency and in case it turns out to have affected others as well. 

## Steps to reproduce

1. Let Duplicati update from 2.0.1.73_experimental_2017-07-15 to 2.0.2.1_beta_2017-08-01 using the auto updater
2. Presumably the auto updater restarted the service on it's own? I didn't restart it.

## Debug log

There don't seem to be any debug logs left either.

**Comment by kenkendk** [comment]
I think "something else" has happened. Duplicati does not remove the `.config` folder, and there is no code to do so. Yes, the auto-updater will restart the service, but this should not do anything.

I am thinking that something happened that caused Duplicati to use a _different_ `.config` folder, but exactly what I do not know. Maybe you can search the system for files named `Duplicati-server.sqlite` and see what comes up?

**Comment by davegold24** [comment]
@Pectojin were you able to find an alternate .config folder?

**Comment by Pectojin** [comment]
@davegold24 I'm afraid I haven't been able to find anything. 

But, considering most other users must have updated by now and have not reported similar issues, I think it's fair to assume my system was impacted by external factors. 

I think I'll close the issue given that there isn't any code to "fix"
