### ISSUE TITLE
Amazon S3 IAM policy needs "s3:ListAllMyBuckets" permission

### ISSUE THREAD

**Issue by cybaea** [duplicati/duplicati#2794]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 10
- **Backend**: Amazon S3

## Description

The generated IAM policy needs the "s3:ListAllMyBuckets" permission as well.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1390497858034",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetObject",
                "s3:PutObject",
                "s3:ListBucket",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucket/path",
                "arn:aws:s3:::bucket/path/*"
            ]
        }
    ]
}
```

## Steps to reproduce

Set up a new connection. Try it. Enjoy 'Access denied' message

- **Actual result**:
Access denied
- **Expected result**:
Success

**Comment by cybaea** [comment]
Sorry, not (just) that one. "s3:*" works....

**Comment by cybaea** [comment]
Sorry, maybe only access to the bucket, not the bucket/path, as someone else mentioned.

**Comment by kenkendk** [comment]
This should have been fixed in the canary: https://github.com/duplicati/duplicati/commit/81f22826ca6f5c10b8afb22df6d43587ab5a3e87
