### ISSUE TITLE
Upgrade to 2.0.2.9: Object must be root directory or drive letter (on Windows)

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#2797]
After upgrading to 2.0.2.9 on Windows, one of my backup jobs fails with this German message:
Das Objekt muss ein Stammverzeichnis (C:\) oder ein Laufwerksbuchstabe (C) sein.
which must have been something like
 "Object must be root directory or drive letter"

The source files that are backed up by this job are and always have been simply:
  D:\
with some exceptions.

**Comment by tygill** [comment]
I think this should have been fixed by pull request #2790.

**Comment by huste** [comment]
Thanks. I'll close this one and reopen it if it is still there in 2.0.2.10

**Comment by huste** [comment]
Still there in 2.0.2.10

**Comment by huste** [comment]
Weird. A second run of  the same backup worked. without error. I'll close it again

**Comment by tygill** [comment]
As a note, the quota is checked on the destination path, not the source. So even if the source is D:, if the destination was a file path like \\SHARE\BACKUP, it could have been hit previously. Report back if it comes back though.
