### ISSUE TITLE
Database locked even when UI says Finished!

### ISSUE THREAD

**Issue by dptsolutions** [duplicati/duplicati#2803]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Docker container on Ubuntu 17.04
- **Backend**: Local Files

## Description

Backup job says it's finished, but attempting to view logs fails with error "Failed to connect: the database file is locked database is locked". Logs cannot actually be viewed until progress bar displays "Next Scheduled Task" message.

Ultimately, the messaging feels wrong here. Things aren't truly finished. This is confusing to the end user (or at least myself) when I search the error message and encounter posts in the forum like this - https://forum.duplicati.com/t/the-database-file-is-locked-database-is-locked/202/2. In this instance, people say you can't access the logs till the job is finished. But the UI is reporting it finished. It's not really finished till the bar goes white again.

## Steps to reproduce

1. Run backup job
2. Wait till UI says "Finished!" in progress bar
3. Attempt to view backup logs

- **Actual result**:
Get error dialog (see attached screenshot)
- **Expected result**:
I can access the logs

## Screenshots

![image](https://user-images.githubusercontent.com/7376492/31312076-405d575c-ab6f-11e7-9984-c134da9e231c.png)

## Debug log

None

**Comment by dptsolutions** [comment]
I should say that this is low priority. Now that I know what to look for, I'm OK. But it'll confuse new users.

**Comment by Pectojin** [comment]
I believe this issue can be closed as #2819 has been merged.
