### ISSUE TITLE
Separate Backend from trayicon

### ISSUE THREAD

**Issue by rodalpho** [duplicati/duplicati#2805]
I upgraded Ubuntu to 17.10 and to my surprise I saw Duplicati wasn't in my system tray. So I started it up, it came right up, but when I went to the webpage I saw my entire configuration had vanished! I recreated it from scratch, deleted all my archives on google drive, deleted the database, and started taking fresh backups. 

Just now I realized what I had done. The GUI application, while _labeled_ trayicon, is actually the entire Duplicati daemon and its frontend too. Duplicati had already been running as a service, with no trayicon. When I opened the trayicon in X, it started a _second_ copy of Duplicati as my user account rather than root, on port 8300 rather than 8200. 

As of right now, I can't figure out how to have a trayicon to alert me when backups have problems _and_ run as root to backup my entire computer. I suppose I could run it as gksudo or something. 

This whole thing is extremely confusing and could be addressed by having the little trayicon be just that, and not tie it to the entire backend. Just a little program that goes red when there's a problem, dead simple.

**Comment by kenkendk** [comment]
Hi, this page explains how it works:
https://www.duplicati.com/articles/Way-To-Make-A-Backup/

Basically, start the service with `--webservice-port=8200` to ensure it uses that port. Then start the trayicon with `--no-hosted-server --server-url=http://localhost:8200`

**Comment by kenkendk** [comment]
I am closing as I think this explains it, but feel free to re-open or create a new issue if you would like something to change to make it more obvious what should be done.

**Comment by rodalpho** [comment]
Well, I would suggest separating the daemon and trayicon by default because it's less confusing. But thank you for explaining how to configure it myself!

**Comment by penhtech** [comment]
I'm reopening this only so as to maybe make it easier to find by adding a few new key words and bumping it up a bit on search results. I just went through three hours or so of fixing this problem. If I had seen this page or the one linked to above, it would have been more like 15 minutes but it never came up in my search results until just now. To be very specific, here is what I did:

1. I installed Duplicati on Linux Mint 18.3 the recommended way.
2. A couple of days later, after encountering permission errors, I then followed the instructions kenkendk has posted in multiple location for how to run it as a service under the root user.
3. I got the usual problems with not being able to find the existing backup, for which the solution is also pretty easy to find.
4. I still had a tray icon which pointed to the original install at port 8300, which was reporting errors every day.
5. To fix this on Linux Mint 18.3, I did the following:
- **Menu** > **System Settings** > **Startup Applications**
- Find **Duplicati** and click **Edit**
- In the **Command** field, paste `duplicati --no-hosted-server --serverurl=http://localhost:8200`
- Click **Save**
- Log out and log back in

All now appears to be well. The tray icon is connecting to the right port, and my backups are running correctly.

**Comment by penhtech** [comment]
I'm reopening this only so as to maybe make it easier to find by adding a few new key words and bumping it up a bit on search results. I just went through three hours or so of fixing this problem. If I had seen this page or the one linked to above, it would have been more like 15 minutes but it never came up in my search results until just now. To be very specific, here is what I did:

1. I installed Duplicati on Linux Mint 18.3 the recommended way.
2. A couple of days later, after encountering permission errors, I then followed the instructions kenkendk has posted in multiple location for how to run it as a service under the root user.
3. I got the usual problems with not being able to find the existing backup, for which the solution is also pretty easy to find.
4. I still had a tray icon which pointed to the original install at port 8300, which was reporting errors every day.
5. To fix this on Linux Mint 18.3, I did the following:
- **Menu** > System Settings > Startup Applications
- Find Duplicati and click Edit
- In the Command field, paste `duplicati --no-hosted-server --serverurl=http://localhost:8200`
- Click Save
- Log out and log back in

All now appears to be well. The tray icon is connecting to the right port, and my backups are running correctly. Thanks for providing such a nice solution as FOSS. I've been running duplicity with custom scripts on servers for years for my clients whose websites I maintain, and this is a much better and more secure solution that has clearly involved considerable work.
