### ISSUE TITLE
Add "Restart=always" to the duplicati.service file (systemd)?

### ISSUE THREAD

**Issue by NoLooseEnds** [duplicati/duplicati#2806]
The duplicati.service crashed on me again today, so I'm adding "Restart=always" – so it at least starts up again by it self.

The downside of this is that if you don't check your logs you could be led to believe that everything is fine.

**Comment by kenkendk** [comment]
Do you mind making a PR for that? Or just post the script as it looks after change and I will include it.

**Comment by NoLooseEnds** [comment]
Sure, I'll post i there:

duplicati.service:
```
[Unit]
Description=Duplicati web-server
After=network.target

[Service]
EnvironmentFile=-/etc/default/duplicati
ExecStart=/usr/bin/duplicati-server $DAEMON_OPTS
Restart=always

[Install]
WantedBy=multi-user.target
```

More info here:
http://manpages.ubuntu.com/manpages/zesty/man5/systemd.service.5.html (scroll down to `Restart=`. You can also use `RestartSec=`to set how long the wait period is. Defualt is 100ms

I made a copy  of `/lib/systemd/system/duplicati.service` and placed it in `/etc/systemd/system/duplicati.service`. It is afaik best practice as it trumps the default service file. Good for making individual changes.

**Comment by kenkendk** [comment]
I have added that to the script: bed9f3bf3b249cc8012469d7a575ab3a49b9d462
