### ISSUE TITLE
copy of backup configuration shows a last succesful run on creation

### ISSUE THREAD

**Issue by sotto** [duplicati/duplicati#2807]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------
- **Duplicati version**: Duplicati - 2.0.2.7_canary_2017-09-19

## Description
Last succesfull run shows last run from the original backup-configuration.should be never.

export a backup-configuration to file
import it as new, change the name (and some other options)
save

- **Actual result**:
the copy shows with:
Last successful run:    gisteren om 20:01 (took 00:01:11)

- **Expected result**:
Last successful run:    Never - Run now 
as is the case with new backup configurations

**Comment by SoulGit** [comment]
On 2.0.2.15_experimental_2018-01-03, OS X El Capitan.  I see the same 'Last Successful' result as Sotto and also the 'Source' showing the total source size from the exported backup and the 'Backup' showing the total backup size and number of versions from the exported backup.  

Following the first successful backup, the fields are properly updated to reflect the new backup job.

**Comment by Pectojin** [comment]
I guess it depends on the use case for the export/import feature. If you're just recreating your backup job (e.g. reinstalling Duplicati) then showing last successful run makes sense.

It makes less sense if you're using the import as a template for multiple different jobs, but how would Duplicati tell?

**Comment by TwoLikeYou** [comment]
Valid point.  Perhaps Duplicati could "decide" to show historical data based on whether the user changes any specific options such as name, source files, destination, etc.  It makes sense that these items would not change if the user was simply reimporting jobs on Duplicati reinstall vs. the items likely would change if the import is being used as a template.

**Comment by SoulGit** [comment]
Valid point. Perhaps Duplicati could "decide" to show historical data based on whether the user changes any specific options such as name, source files, destination, etc. It makes sense that these items would not change if the user was simply reimporting jobs on Duplicati reinstall vs. the items likely would change if the import is being used as a template.

**Comment by Pectojin** [comment]
The more I think about it, the more it seems to just not make sense to import the last run data...

Deciding whether or not to keep it on a basis on which fields were changed is hard, especially when having to make guesses about external factors.

If we're being really pedantic, it's correct to say that the job has "never" run after you just imported it. It will have a new job id and "be a new job".

**Comment by Pectojin** [comment]
Maybe the solution is easier than guesswork and analysing user input... 

How about we do something crazy and ask the user?
![screen shot 2018-01-28 at 01 28 21](https://user-images.githubusercontent.com/1561484/35477734-adaf3466-03ca-11e8-80a2-d9acb7e874b2.png)
Default is to not import metadata unless the box is explicitly checked.

Here the top entry has imported the metadata while the bottom didn't (default)
![screen shot 2018-01-28 at 01 27 48](https://user-images.githubusercontent.com/1561484/35477735-af2ce734-03ca-11e8-913b-37d29dcd4c9a.png)

**Comment by SoulGit** [comment]
Great idea - perfect solution!
