### ISSUE TITLE
SSH backend does not negotiate the strongest key

### ISSUE THREAD

**Issue by wskinner** [duplicati/duplicati#2808]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: OSX 10.12.6
- **Backend**: SFTP

## Description

The server I'm connecting to has a number of keys - RSA, DSA, and ECDSA. I would prefer to use the strongest one, the ECDSA key. When I connect to my server using my local SSH client, this is the key that is picked. But Duplicati picks the RSA key, and I can't figure out a way to instruct it to pick the stronger ECDSA key.

## Steps to reproduce

1. Create a new backup using SFTP as the backend
2. Test connection to an SSH server that has multiple keys, including RSA and ECDSA

- **Actual result**:
The RSA key fingerprint is shown

- **Expected result**:
The ECDSA key fingerprint should be shown

**Comment by kenkendk** [comment]
I think this is something that needs to be fixed in the SSH library:
https://github.com/sshnet/SSH.NET

Maybe you can create an issue on that project (and link to this) to see what they say?

**Comment by wskinner** [comment]
@kenkendk You're right - SSH.NET doesn't appear to support the stronger authentication methods, like ECDSA. I commented on their existing open [issue](https://github.com/sshnet/SSH.NET/issues/20) to add support for modern ciphers. It's over a year old.
