### ISSUE TITLE
GUI displaying partial Advanced options descriptions

### ISSUE THREAD

**Issue by JonMikelV** [duplicati/duplicati#2823]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-1
- **Operating system**: Windows 7 Prof
- **Backend**: Local internal disk

## Description
As discussed on the forum, when the GUI dynamically pulls commandline descriptions from commandline.exe some info (such as "[DEPRECATED]" lines, "* values:" lists, and "* default value:" lines are not included for some reason.
https://forum.duplicati.com/t/zip-compression-settings/976/9

## Steps to reproduce

1. Edit a backup
2. Go to step 5 (Options)
3. Select the "compression-level" Advanced option from the Zip compression block

- **Actual result**:
Get partial descriptive text...
>This option controls the compression level used. A setting of zero gives no compression, and a setting of 9 gives maximum compression.
- **Expected result**:

 Get same text as produced by running `Duplicati.CommandLine.exe help compression-level`...
>  --compression-level (Enumeration): Sets the Zip compression level
    [DEPRECATED]: Please use the zip-compression-level option instead
    This option controls the compression level used. A setting of zero gives
    no compression, and a setting of 9 gives maximum compression.
    * values: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
    * default value: BestCompression`

**Comment by JonMikelV** [comment]
Oops - should this be merged with [Show default values for advanced options #2810](https://github.com/duplicati/duplicati/issues/2810)?

**Comment by kenkendk** [comment]
Yes, lets keep the other issue open.
