### ISSUE TITLE
Prominently document how to turn off usage reporter

### ISSUE THREAD

**Issue by jniggemann** [duplicati/duplicati#2827]
It occurs to me that very many people have the problem that Duplicati 2 crashes on Windows. I'm one of them (latest beta).

After hours of scouring the internet using search terms like "Duplicati GUI icon error" and related terms, I finally discovered the solution in #2430 .

Please document that, at least in some cases, the usage reporter is at fault and how to turn it off.

**Comment by kenkendk** [comment]
I would rather figure out how to fix the problem 😄 

It would be non-friendly to have a program that requires you to read a how-to that explains how to change the program defaults just to have the program working 🙃 .

**Comment by ts678** [comment]
[2.0.3.3_beta_2018-04-02](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.3-2.0.3.3_beta_2018-04-02) says

> Fixed some crashes that were caused by the usage reporter filling up reports

At end of #2430 is a link to #3020 which ends in a commit link and confirmation that removing files avoids that crash.

This is all speculative, so I'll just ask if your crash seemed to have gone away on [2.0.2.18_canary_2018-02-11](https://github.com/duplicati/duplicati/releases/tag/v2.0.2.18-2.0.2.18_canary_2018-02-11) or newer.

**Comment by jniggemann** [comment]
Haha, wow, hard necrobump :-)
I admit I have forgotten this ticket as I've updated since years. RN, I'm on 2.0.7.2_canary_2023-05-25 and have no issue since quite some time. 
@ts678: Closing this issue, feel free to reopen if you still need it.
