### ISSUE TITLE
End of Backup Fatal Error - Files missing from remote storage

### ISSUE THREAD

**Issue by JonahRS** [duplicati/duplicati#2830]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows Server 2016
- **Backend**: Microsoft OneDrive for Business

## Description

Backing up a folder on my machine about 350GB in size. At the end of the backup I get this message in the job log:

Fatal error
Duplicati.Library.Interface.UserInformationException: Found 10477 files that are missing from the remote storage, please run repair
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)

Found 10477 files that are missing from the remote storage, please run repair

Missing file: duplicati-ibacef8b911104f2cb1350884f3139559.dindex.zip.aes (This follows a large number of similar entries. I am guessing for each of the 10477 files?

## Steps to reproduce

1. Install Duplicate
2. Setup backup of folder
3. Error

I have tried clearing down all the data from the remote/onedrive and removing and reinstalling the backup software. Same result. I am reluctant to do this again as the backup takes approx 4 days to run so would ideally like to resolve.

- **Actual result**:
As above missing files error
- **Expected result**:
Sucess

## Screenshots

![image](https://user-images.githubusercontent.com/32913759/31743048-99cebdf4-b451-11e7-929f-63437c698d23.png)
![image](https://user-images.githubusercontent.com/32913759/31743102-c6c11500-b451-11e7-963d-ca6a0dfdb88c.png)
![image](https://user-images.githubusercontent.com/32913759/31743151-fa79187a-b451-11e7-86f5-4f7cd4f4a221.png)
![image](https://user-images.githubusercontent.com/32913759/31743242-591aafb0-b452-11e7-93cd-983b08c1b2ae.png)

**Comment by kenkendk** [comment]
We are aware of a problem with OneDrive (but not "for business"): 
https://forum.duplicati.com/t/backup-failing-with-key-already-exists-exception-on-onedrive/1157

The error message means that after uploading the files to OneDrive, Duplicati cannot see the files when it lists the folder.

Do you have any idea for permissions, settings etc that might have caused this on OneDrive?

**Comment by ts678** [comment]
> Found 10477 files that are missing from the remote storage

[Manage large lists and libraries](https://support.microsoft.com/en-au/office/manage-large-lists-and-libraries-b8588dae-9387-48c2-9248-c24122f07c59)  (Microsoft) explains the infamous 5000 file list view limit. Beyond that, destination looks empty.
This has been fixed in newer access methods such as Microsoft Graph. Please try [Microsoft OneDrive v2 (Microsoft Graph API)](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#microsoft-onedrive-v2-microsoft-graph-api).
