### ISSUE TITLE
--run-script-after / before fires during Restore

### ISSUE THREAD

**Issue by JonMikelV** [duplicati/duplicati#2832]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**:  2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 7 Pro
- **Backend**: Local disk

## Description

As described at https://forum.duplicati.com/t/run-script-after-fires-during-restore/1081, even opening the list of files to be restored triggers the `--run-script-before` and `--run-script-after` scripts to fire.

## Steps to reproduce

1. Create a script that appends a timestamp to a log file
2. Set said script to run before and after a job
3. Open the Restore menu for a job
4. Review log file & see 6 time entries

- **Actual result**:
Using test script above, log file has 3 sets of timestamps
- **Expected result**:
Rune before / after scripts should NOT fire during a Restore operation.  Actually, they probably shouldn't fire for anything OTHER than a Run operation.

**Comment by kees-z** [comment]
Unti this is fixed, you can test the environment veriable `DUPLICATI__OPERATIONNAME` to check if the script schould continue. 
Add a line something like this to the top of your script:
```
if /i not "%DUPLICATI__OPERATIONNAME%"=="BACKUP" exit 0
```

**Comment by davegold24** [comment]
@kees-z thanks for the workaround. I was wondering why I was getting errors regarding my script running during a restore. Much appreciated.

And the fact that you've already got this running in your example script is really nice too :)

**Comment by kenkendk** [comment]
It appears that @kees-z has answered, so I'll close this issue

**Comment by warmup72** [comment]
I think the problem needs a real fix - this desciptions seems to be only a work around :-(

**Comment by Taomyn** [comment]
@kenkendk please re-open and request a fix at some point - all I have to do is click next after choosing where to restore from, not even starting a restore, and it kicks off the associated script for the main backup. It kicked the job off 4 times just trying to restore one file.

**Comment by kees-z** [comment]
You can use the environment variable `DUPLICATI__OPERATIONNAME` to determine if the script should run during a restore operation. This gives more flexibility (sometimes the script should run on restore operations too, for example to mount a network drive).
See example scripts [run-script-example.bat](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.bat) and [run-script-example.sh](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.sh).

**Comment by Taomyn** [comment]
> You can use the environment variable `DUPLICATI__OPERATIONNAME` to determine if the script should run during a restore operation. This gives more flexibility (sometimes the script should run on restore operations too, for example to mount a network drive).
> See example scripts [run-script-example.bat](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.bat) and [run-script-example.sh](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.sh).

I totally get your point for when the restore job is actually running, but I don't expect the script to be executed repeatedly when I traverse the backup set looking for the file I want to restore and choosing the restoration options.

**Comment by kees-z** [comment]
I agree this is a bit tricky. Duplicati executes the specified script on every operation it does. When browsing your restore points, Duplicati executes a LIST command in the background to populate the list of files and folders.
To prevent running the script while browsing folders, insert something like this at the beginning of the script:
```
if /i "%DUPLICATI__OPERATIONNAME%" equ "List" exit 0
```

or:
```
if /i "%DUPLICATI__OPERATIONNAME%" neq "Backup" exit 0
```

**Comment by Sidelity** [comment]
@kenkendk Please re-open this as it's still an issue.

I run scripts that stop docker containers before backups, then restores them afterwards. However this issue means that the scripts run every time I expand a folder in the Restore view. Completely unnecessary, and it takes forever to browse the file structure.

Nobody expects scripts to run like this when restoring.
