### ISSUE TITLE
2.0.2.12 tray icon crashes on startup

### ISSUE THREAD

**Issue by GSPP** [duplicati/duplicati#2835]
Starting Duplicati the tray icon process simply crashes immediately:

![image](https://user-images.githubusercontent.com/12032350/31852653-abfd8db2-b67b-11e7-845e-cd5864698d74.png)

This is version 2.0.2.12 on Windows 7.

**Comment by kenkendk** [comment]
It is not the same #2850. 

How are you running this? It seems that a project is referencing CoCoL in the 1.5.0 version, but all projects should reference 1.5.1.

**Comment by GSPP** [comment]
Maybe it was a messed up installation installing over a different version. I fixed it with an uninstall and install cycle, so unfortunately the repro is gone now. I also think that I manually deleted the app folder after uninstallation so I would have cleared any additional files.

**Comment by PichlAlex** [comment]
i also experienced this CoCoL.dll missing Error while installing 
v2.0.2.12-2.0.2.12_canary_2017-10-20

my story before:
dumplicati was not reachable anymore via browser -> always HTTP 500
i closed duplicati via tray icon
i tried to start duplicati again -> exited immediately.
restarted the pc -> no change
i reinstalled current stable -> no change
-> reboot
i installed current beta v2.0.2.12-2.0.2.12_canary_2017-10-20.msi -> from this step on duplicati crashed with a crashlog in C:\ProgramData\Duplicati\updates
-> i downloaded beta v2.0.2.12-2.0.2.12_canary_2017-10-20.zip and extracted to installation folder
-> now everything is working fine

**Comment by ts678** [comment]
> Starting Duplicati the tray icon process simply crashes immediately

Not reproducible now. Maybe fixed, install issue, etc. How about you?
