### ISSUE TITLE
Windows 7 WEBDAV test connection fails

### ISSUE THREAD

**Issue by darksworm** [duplicati/duplicati#2840]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1
- **Operating system**: Windows 7
- **Backend**: WEBDAV

## Description
Test connection does not work for WEBDAV on windows 7 and running backups fails

## Steps to reproduce

1. Install Windows 7, duplicati 2.0.2.1
2. Try to add a new WEBDAV backup
3. Press `test connection`

- **Actual result**:
Error pops up:  `Failed to connect: The underlying connection was closed: An unexpected error occurred on a send.`
- **Expected result**:
Connection test is successful/user is prompted whether to create folder

## Screenshots

![ocetfdz](https://user-images.githubusercontent.com/9987548/31891771-09b747dc-b810-11e7-9def-711e0dcef6b4.png)

## Debug log

```
    Oct 23, 2017 4:34 PM: Reporting error gave error
    System.ObjectDisposedException: Cannot write to a closed TextWriter. at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
    Oct 23, 2017 4:34 PM: Request for http://localhost:8200/api/v1/remoteoperation/test gave error
    System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.InvalidOperationException: This operation cannot be performed on a completed asynchronous result object. at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar) --- End of inner exception stack trace --- at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream() at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse() at Duplicati.Library.Backend.WEBDAV.List() at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info) at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST(String key, RequestInfo info) at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
```

NOTE:
reverting `AsyncHttpRequest.cs` to 0c68daff6c2204808c37a79ea4abd2a84f35f79c fixed the issue for me.

**Comment by kenkendk** [comment]
Did you find out what version that introduces the problem? The commit you referenced was a white-space only fix, so I would be surprised if that change caused problems.

**Comment by darksworm** [comment]
No, I have not. But I am certain that the issue appeared within `AsyncHttpRequest.cs` somewhere between (inclusive) commits f9e5eeae0caa3ca238fe1df768b5999b455df024 and 9cdd5ff1e4f969b8040dac31972a86099f9bf5ef. I specifically reverted the file to 0c68daf, because it matched the file in our last build and did not have this issue.

**Comment by DavidVL1982** [comment]
I have the same issue on 1 Win7 RTM pc. Can't update to SP1 due to unknown problem...
I tried the beta & canary of duplicati. I can't find the AsyncHttpRequest.cs file to change this.
I don't know anything about github so don't know how I can compile Duplicati myself...

**Comment by ts678** [comment]
> SOLVED! Updating .NET FW 4.5 to 4.5.2 fixes it

according to second report. If original reporter @darksworm still has an interest and sees it, further testing may be possible.
In particular, [WebDAV](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#webdav) provides the `debug-propfind-file` option to capture the `list` that `Test connection` likely does.
Or maybe it won't get that far. Regardless, this issue is old, and might be fixed by now. Doing check to see if it's still needed.
If no updates come in, it will eventually close.

**Comment by darksworm** [comment]
I no longer have any interest in this issue. If anyone is still using Windows 7, they most certainly have bigger problems than this. I don't think this is worth spending any more time on, but thank you for looking into it!
