### ISSUE TITLE
Solus OS

### ISSUE THREAD

**Issue by ghost** [duplicati/duplicati#2841]
Is there a way to use Duplicati on Solus OS? Snap?

Thanks

**Comment by darksworm** [comment]
I recently tried compiling and running it on Solus with mono.  The server ran, but the backups failed every time.

**Comment by hoilc** [comment]
It works fine with generic package.

1. install mono and sync certs 
``` 
sudo eopkg install mono mono-devel
sudo cert-sync /etc/ssl/certs/ca-certificates.crt
```
2. download the generic package(duplicati-*.zip) from the release page
3. extract it to certain location
4. run duplicati server
```
mono Duplicati.Server.exe
```
5. just open `http://127.0.0.1:8200/`

**Comment by kenkendk** [comment]
@hoilc Thanks for the step-by-step.
@paranoicogm Does this solve your original question?

**Comment by darksworm** [comment]
@hoilc have you also tried running any backups or did you just run duplicati by itself?

**Comment by hoilc** [comment]
I didn't test all functions, but the backup operation works fine.

![screenclip 1](https://user-images.githubusercontent.com/9067094/33227699-4d037bb2-d1e4-11e7-81e4-e5308f8ba0df.png)

Could you share the error info? Or try `cert-sync /etc/ssl/certs/ca-certificates.crt` first

**Comment by warwickmm** [comment]
Closing this due to lack of feedback (and the issue creator seems to no longer exist).
