### ISSUE TITLE
Unable to start duplicati 2.0.2.1

### ISSUE THREAD

**Issue by tiagoboldt** [duplicati/duplicati#2850]
- **Duplicati version**: 2.0.2.1
- **Operating system**: Mac OS 10.13

## Description
Unable to start duplicati. 

## Steps to reproduce
Open duplicati, nothing happens. This has also been discussed here: https://forum.duplicati.com/t/duplicati-wont-startup-after-update-on-macos/69/11

## Debug log
From my logs, I've found the following: 
```
Sandbox: mono-sgen32(87826) System Policy: deny file-write-create /usr/share/.mono
Violation:       System Policy: deny file-write-create /usr/share/.mono 
MetaData: {"build":"Mac OS X 10.13 (17A405)","action":"deny","target":["usr","share",".mono"],"hardware":"Mac","platform_binary":"no","profile":"unknown","process":"mono-sgen32","op":"file-write-create"}

Process:         mono-sgen32 [87826]
Path:            /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono
Load Address:    0x94000
Identifier:      mono
Version:         ??? (???)
Code Type:       i386 (Native)
Parent Process:  bash [87822]
Responsible:     /Applications/Duplicati.app/Contents/MacOS/duplicati [87822]
User ID:         501

Date/Time:       2017-10-27 14:21:48.590 GMT+1
OS Version:      Mac OS X 10.13 (17A405)
Report Version:  8
```

**Comment by tiagoboldt** [comment]
Possible duplicate of #2835.

**Comment by kenkendk** [comment]
No sure why it does that. I do not have a `/usr/share/.mono` folder on my system, do you have it?

If yes, then I guess that you may have installed Mono in some earlier version, and since the folder exists, Mono tries to write to it which breaks things. To see if this is the case, try renaming the folder temporarily.

**Comment by corpamini** [comment]
ok,  thanks! I'll try.

2017年11月5日 22:28，"Kenneth Skovhede" <notifications@github.com>寫道：

**Comment by tiagoboldt** [comment]
I do not have a `/usr/share/.mono`. My guess is that it only exists inside the sandbox environment created by mono, but I know nothing about the language.

**Comment by tiagoboldt** [comment]
Hey, so, I've installed the latest Mac OS upgrade, which asked for a reboot. After rebooting, duplicati started normally, tray icon included. Probably it was from the reboot. Not sure what was going not but I'm now unable to reproduce. Should we close the issue?

**Comment by kenkendk** [comment]
Yes, if it works for you, lets close it. If others report it again, we can re-open.
