### ISSUE TITLE
Slow folder browsing during restore

### ISSUE THREAD

**Issue by dgold9670** [duplicati/duplicati#2852]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 7 Pro 32-bit; disk is SSD
- **Backend**: Minio
Duplicati is running as a service.

## Description
Browsing for file restores is very slow. 
This was discussed in https://forum.duplicati.com/t/very-slow-folder-browsing-during-restore/430

## Steps to reproduce
1. Open Duplicati, go to restore window
2. Select restore from existing backup job
3. Browse in window. Opening a folder takes a minimum of a minute; watching disk monitor shows very heavy IO.

## Debug log
Pending. Given the large amount of discussion in the link above, the issue is clearly understood by dev.

## Thoughts on solutions
It seems that the current method of creating browsing views is to extract significant portions of the database into a temporary database ("list") and then use that temporary sqllite database. 
Each time a new folder is opened, a separate list operation is run.
I can think of three types of solutions:
1. Create index at end of backup, so that the list does not need to extract significant amounts of data
--possible issue is index corruption and increased IO requirements. Code would have to exist to recover from failures.
2. Reuse the temporary SQL database, so only a single list is required.
3. Extract data from database into a different structure, such as CSV or TSV. This could be ordered by directory structure, and would load into the GUI faster.
--main issue would be scalability

**Comment by davegold24** [comment]
Additional thoughts:

**Comment by davegold24** [comment]
Another few thoughts on options to make the restore faster:
1. After selecting the restore to pull from, start by showing versions only, and not versions and file tree. The amount of database work to pull the entire list of files is significant, but the amount to show restore from versions is not. The next screen could show the file tree.
2. Run the complex query that finds all the files that are part of a give point in time once, and keep those results (temp database) around for the entire restore session. There is a single query that takes most of the time, and after each step its results are deleted, then recreated.
3. Add a depth field and/or parent path to help speed up browsing, and simplify queries. ie use the temp filelist from step 2, and query on either to make the query run faster. 
I think both could be done during step 2, without modifying the backup portion of the database (ultimately modifying the backup is better, but using the step 2 results would be easier, IMHO)

I wish I had the programming chops to write the code. I'd certainly be willing to kick in some funds if that would help (although my sense is that isn't the major motivating factor here)

If someone does want to work on this, I'm glad to help in any way I can though.

**Comment by nickamis** [comment]
This is a critical issue. It takes too long to find and restore files.

**Comment by DerRidda** [comment]
I'm encountering this too with the backups at my company.

I think we might be an extreme case because our source data is ~3TB+.
All clicks are in the range of many minutes.

I have a mind to potentially work on something akin to @davegold24's second idea in his original issue.
Building an index file that would then be the first thing to be browsed.

Nothing concrete yet and certainly no ETA because I would first like to know if a PR for that idea would be welcome.

**Comment by githubldvx** [comment]
Hi,
I have the same problem here. We have ~450GB+, with a high number of files.
All clicks on a folder took ~15 to 20 minutes.

Is there an update done for this issue ?

**Comment by tbergeron** [comment]
Anyone has an idea why Windows-based installation performance is WAY faster to browse than my smaller Linux-based installation?

- Loading a folder's content on the Windows based setup (500GB) takes less than a second.
- Loading a folder's content on the Linux based setup (100GB) takes about 30 seconds avg.

Anyone has an idea? I can't find a specific issue about that so I might have to open my own. Thanks

**Comment by davegold24** [comment]
@tbergeron Could you provide some specs on your systems?
Windows OS, CPU, RAM and disk type (SSD versus spinning)
Linux OS, CPU, RAM and disk type (SSD versus spinning)
Version of Duplicati on both.

**Comment by tbergeron** [comment]
> @tbergeron Could you provide some specs on your systems?
> Windows OS, CPU, RAM and disk type (SSD versus spinning)
> Linux OS, CPU, RAM and disk type (SSD versus spinning)
> Version of Duplicati on both.

I made it a whole lot quicker by removing hundred of thousands of files (git repositories, node_modules directories etc) and it is now much faster. It really seems to depend on the number of different paths as talked on the forums here: https://forum.duplicati.com/t/why-is-fetching-path-info-for-restore-so-slow/3838/21

Here's my info anyway:

Windows box CPU (the one that has the fastest Restore browse) is a Intel Core i5 4670 Quad Core 3.4GHZ Processor LGA1150 Haswell 6MB Cache.
Linux laptop (workstation) has a 8th Generation Intel® Core™ i7-8550U Processor (8M Cache, up to 4.0 GHz).

All on SSDs.

**Comment by dgold9670** [comment]
Thanks for the update. Since this ticket was resolve a while ago, I'm going to close it.

**Comment by ajayyy** [comment]
So, the solution is just to not backup node modules and git repos?

Maybe the UI should be able to ignore hidden files in that menu to speed it up
