### ISSUE TITLE
Some issues with build-msi.bat

### ISSUE THREAD

**Issue by honggu025** [duplicati/duplicati#2854]
I got some trouble when using duplicati-2.0.2.12-2.0.2.12_canary_2017-10-20\Installer\Windows\build-msi.bat in Windows server 2008 R2. I'm not sure if other operating systems have the same problems.
The first problem was that when operating the 18th command line "xcopy ..\oem\* Duplicati\webroot\oem /e /s /y /i", the two folder "ngax" and "root" under "..\oem" entered directly into "Duplicati\webroot" instead of "Duplicati\webroot\oem". As a result, the user-defined code can't be loaded. This problem might be caused by the lack of "\" which is supposed to be at the end of the aim path.
The second problem was that when I operated the 33th command line "xcopy ..\oem-app-name.txt Duplicati\ /e /s /y /i", an error "Loop replication cannot be performed" occurred,which was caused by the usage of "/e /s /i". The program worked again after I revised it to "copy".

I'm really sorry that some of the expressions might be confused. Because I'm not a fluent English speaker,I have to ask my friend to write this letter who is unfamiliar with IT nomenclature.

**Comment by kees-z** [comment]
I've taken a look to the script and to be honest, I don't know how any part of the script could work without problems.

- For me it looks like the destination path in line 18 (`Duplicati\webroot\oem`) is correct, but `\oem` should be added to the destination path in line 23 and 28.
- All Xcopy commands will fail. Copying from a parent folder (`..\`) to a child folder (`Duplicati`) is an impossible cyclic copy. Changing `xcopy` to `copy` as you suggested works, but this is just because `/s` and `/e` are not supported by the `copy` command, and are ignored.

I've rewritten the script, but I can't tackle the cyclic copy problem until I know how the exact file structure is supposed to be.

I've tried to download build tools for VS15, and WiX (as suggested [here](https://github.com/duplicati/duplicati/wiki/Branding-and-OEM-customization)), but can't get it to work, probably because the tools should be expected to be copied to a specific location.

Can anyone give a step by step instruction on what to download, where to install and how to use the build tools?

**Comment by kenkendk** [comment]
@kees-z I think you are correct. It is indeed lines 23 and 28 that needs to be updated. 
I think I wanted to copy the `oem` directory, but then ended up choosing to copy the files instead, which caused the problem.

I think the `/e /s` works correctly if the source is a file (but then they are not required).
I don't see the cyclic part. It should work if you have something like this:

```
C:\oem\example.js
C:\build\duplicati.zip
```

Then you need to do:
```
> C:
> cd \build
> C:\duplicati-source\build-msi.bat duplicati.zip
```

The batch file will then create `C:\build\Duplicati` and put the zip file contents in there.

The xcopy command should then be resolving as:
```
xcopy C:\oem\* C:\build\Duplicati\webroot\oem /e /s /y/ i
```

**Comment by kees-z** [comment]
> I don't see the cyclic part

Now I understand it, I ran into the same issue as the OP.
You call `build-msi.bat` from another folder than where the batch file is located. If you navigate to the folder containing `build-msi.bat` and run it by just typing the name (`cd \duplicati-souce` and `build-msi.bat`), a cyclic copy is performed.

I've tried to make a more flexible and fail-safe batch file.
DISCLAIMER: Use with care! I did not test it, the required tools are not installed on my current system.

Feel free to add/change as many comments and commands as you like.
```
@echo off
setlocal

: This script merges OEM files with the default Duplicati binaries
: and create MSI installer packages for Windows 32 and 64 bit operating systems.

rem Specify OEM and Build locations here, as well as the location of the Duplicati source Zip file.
rem Value ASK will ask for a location.
set "OEMFolder=ASK"
set "BuildFolder=ASK"
set "ZipFile=ASK"

rem check if variable VS140COMNTOOLS is set.
if "%VS140COMNTOOLS%" EQU "" (
	echo Variable %%VS140COMNTOOLS%% is empty, VS14 Common Tools not installed?
	goto :EOF
)

rem check if 7-Zip command line tool can be found.
7z.exe > nul 2> nul
if errorlevel 1 (echo 7-Zip CLP Utility not found. && goto :EOF)

rem check if MSBUILD tool can be found.
msbuild.exe /version > nul 2> nul
if errorlevel 1 (echo MSBUILD not found. && goto :EOF)

rem set parameters for XCOPY command.
set "XcopyParams=/e /s /y /i"

rem Ask file and folder locations if not specified.
if /i "%OEMFolder%" EQU "ASK"   (set /p "OEMFolder=OEM files location     : ")
if /i "%BuildFolder%" EQU "ASK" (set /p "BuildFolder=Build files location : ")
if /i "%ZipFile%" EQU "ASK"     (set /p "ZipFile=Duplicati Source Zip file: ")
echo OEM files location:   %OEMFolder%
echo Build files location: %BuildFolder%
echo Duplicati Zip file:   %ZipFile%
echo.

rem abort script if not all files and folders can be found.
if not exist "%OEMFolder%\." (echo %OEMFolder% not found. && goto :EOF)
if not exist "%BuildFolder%\." (echo %BuildFolder% not found. && goto :EOF)
if not exist "%ZipFile%" (echo %ZipFile% not found. && goto :EOF)

rem remove old files and folders.
if exist "%BuildFolder%\Duplicati" (rd "%BuildFolder%\Duplicati" /s /q)
if exist "%BuildFolder%\Duplicati.msi" (del "%BuildFolder%\Duplicati.msi")
if exist "%BuildFolder%\Duplicati-32bit.msi" (del "%BuildFolder%\Duplicati-32bit.msi")

rem set variables
call "%VS140COMNTOOLS%vsvars32.bat"

rem extract Duplicati Zip file.
7z x -oDuplicati "%ZipFile%"

if exist "%OEMFolder%\oem\." (
	echo Installing OEM files
	xcopy "%OEMFolder%\oem\*" "%BuildFolder%\Duplicati\webroot\oem" %XcopyParams%
)

if exist "%OEMFolder%\oem-app-name.txt" (
	echo Installing OEM override file App Name
	xcopy "%OEMFolder%\oem-app-name.txt" "%BuildFolder%\Duplicati" %XcopyParams%
)

if exist "%OEMFolder%\oem-update-url.txt" (
	echo Installing OEM override file Update URL
	xcopy "%OEMFolder%\oem-update-url.txt" "%BuildFolder%\Duplicati" %XcopyParams%
)

if exist "%OEMFolder%\oem-update-key.txt" (
	echo Installing OEM override file Update Key
	xcopy "%OEMFolder%\oem-update-key.txt" "%BuildFolder%\Duplicati" %XcopyParams%
)

if exist "%OEMFolder%\oem-update-readme.txt" (
	echo Installing OEM override file Update Readme
	xcopy "%OEMFolder%\oem-update-readme.txt" "%BuildFolder%\Duplicati" %XcopyParams%
)

if exist "%OEMFolder%\oem-update-installid.txt" (
	echo Installing OEM override file Update Install ID
	xcopy "%OEMFolder%\oem-update-installid.txt" "%BuildFolder%\Duplicati" %XcopyParams%
)

pushd

rd "%BuildDir%\obj" /s /q
rd "%BuildDir%\bin" /s /q

msbuild /property:Configuration=Release /property:Platform=x64
move "bin\x64\Release\Duplicati.msi" ".\Duplicati.msi"

msbuild /property:Configuration=Release /property:Platform=x86
move "bin\x86\Release\Duplicati.msi" ".\Duplicati-32bit.msi"

rd "%BuildFolder%\Duplicati" /s /q

popd
```

**Comment by kenkendk** [comment]
Closing this as the the `.bat` files have been removed in favor of `ReleaseBuilder`.
