### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Meannux** [duplicati/duplicati#2858]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 7 Pro
- **Backend**: amzcd

## Description

When attempting a restore, I get the error "Object reference not set to an instance of an object". I've noticed another issue opened on this but it was related to Linux and didn't notice a fix for Windows. These backups are stored on S3 and AES encrypted.

## Steps to reproduce

1. Attempt to restore a backup.
2. Get to select files, wait a second or two and the error pops up both in the window at the bottom and also a system tray bubble on Windows.

- **Actual result**:
Result is not being able to select the files I want to restore.
- **Expected result**:
Being able to restore the files that have already been backed up. The backup function itself seems to run fine and sends everything to the S3 bucket without issue.

## Screenshots

![duplicatierror1](https://user-images.githubusercontent.com/28171505/32192109-9342f0d6-bd89-11e7-83fb-00035c4e66e4.PNG)

## Debug log

Most recent error log entry:

System.NullReferenceException: Object reference not set to an instance of an object.
at Duplicati.Library.Utility.FilterExpression.FilterEntry..ctor(String filter) 

```at Duplicati.Library.Utility.FilterExpression.<>c.<.ctor>b__10_0(String n) ```

```at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext() ```

```at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() ```

```at Duplicati.Library.Utility.FilterExpression.Compact(IEnumerable`1 items) ```

```at Duplicati.Library.Utility.FilterExpression..ctor(IEnumerable`1 filter, Boolean result) ```

```at Duplicati.Library.Main.Operation.ListFilesHandler.Run(IEnumerable`1 filterstrings, IFilter compositefilter) ```

```at Duplicati.Library.Main.Controller.<>c__DisplayClass23_0.<List>b__0(ListResults result) ```

```at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method) ```

```at Duplicati.Library.Main.Controller.List(IEnumerable`1 filterstrings, IFilter filter)```
 
```at Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)```

**Comment by Meannux** [comment]
I found another issue, but it was related to Box backup, figured I would create this one myself due to it being a different backup method, not sure if that makes a difference. Let me know what else I can provide, thanks!

**Comment by kenkendk** [comment]
From the stack trace, I can see that this error is caused by a filter not being correct.
I spent some time looking at the code, and it turns out there was a missing `else` keyword.
I am not sure why you are one of the only people seeing this, as it should happen the same way for everybody.

**Comment by Meannux** [comment]
Sorry to bother again, just wondering, if I change the Update Channel to something other than Default (Experimental perhaps) , would I be able to have this issue fixed by updating that way? Sorry, just trying to get these backups working. Thanks!

**Comment by archon810** [comment]
Same issue with duplicati 2.0.3.3_beta_2018-04-02 and Box destination. I can't even complete a basic backup, and my initial experience with duplicati has been abysmal as a result.
