### ISSUE TITLE
restored files is different from source (original)

### ISSUE THREAD

**Issue by mdsmdsmds** [duplicati/duplicati#2865]
duplicati duplicati-2.0.2.12_canary_2017-10-20-x64

For testing, I've restored 18956 files on a temp path and I've compared all these with the original sources.
All files are identical, except for one: "someName.pdf" (I cannot post because it's a private receipt).

That's incredible. They are CRC-different and they are really different (see image "different section.png")
- CRC of original one https://ibb.co/haytHb
- CRC of restored one https://ibb.co/fp2sAw
- different section.png   https://ibb.co/c1uNAw

So, I've done backup also with CrashPlan and then I restored it... Same result with same restored-file-differences.

2 identical unfaithful restore with 2 different technology. 

How can it be?

**Comment by davegold24** [comment]
@mdsmdsmds Interesting...could be some kind of shared technology (compression or hashing algorythms), or specific to your system.

Lets start with some questions:
what is your OS
Do you have AV running on it.
If so, did you try to disable AV during restore test?
Have you tried to restore to a different machine and check CRC there?

This feels to me like the file is being modified on the write, but that is a gut sense only, and has no technical backings.

**Comment by mdsmdsmds** [comment]
OS=Windows Server 2012 R2
AV=no
OK, restored on different machine and different OS.
Same identical situation with same identical CRC-difference.

I've tested restore and compared CRC many time also on 200.000 files. This is the first time I get a CRC difference between pre-saved and post-restored.
May be a common algorithm-bug on even different  tecnologies.

**Comment by davegold24** [comment]
Have you tried to back up that file from another system? It still seems possible that there is something computer specific that is causing the issue with this file. 

While theoretically I wonder if you are hitting a hash conflict, that just seems really unlikely.
Note that deduplication is core to duplicati though, so I don't believe it can be disabled. See https://www.duplicati.com/articles/Storage-Engine/, plus the link to the whitepaper for more details.

I haven't been able to find info on how Crashplan does dedup, but I know they do, so it may be they are also using a similar method.

My gut says that this is computer specific, and there is something installed that is the cause. But that is just supposition.

**Comment by mdsmdsmds** [comment]
Tested on different contexts:
- source file is now deposited on other PC and other disk
- I ran backup with CrashPlan AndAlso Duplicati and then I restored it
- NOW all is OK. Same CRC!
So, @davegold24 you're right. It's a that-server problem.

On that server, the source data resides on an iSCSI disk. Even though I would like to know why, on 200.000 files, this reading problem is only on 1 file... I'll investigate futher.

So, I must suppose no tecnology issue here but rather disk-reading-problem on that iSCSI disk.

**Comment by davegold24** [comment]
@mdsmdsmds just curious, what kind of iscsi disk?

Glad we were able to identify it was what I call 'site specific' and not a general product issue.

**Comment by mdsmdsmds** [comment]
StarWind 8

**Comment by davegold24** [comment]
My impression is that Starwind engineering is pretty good. Interesting observation about the 4K sector size. If you ever figure it out, please let me know.
