### ISSUE TITLE
Add litecoin for donations - Very small transaction fees (around $0.01)

### ISSUE THREAD

**Issue by contenidosonline** [duplicati/duplicati#2869]
I would like to suggest that litecoin be added as an option for donations. Litecoin transfer fees are a hundred times lower than bitcoin and that in small amounts is important.

**Comment by kenkendk** [comment]
Thanks for the request. I was thinking that we add a new donation page that lists addresses for different coins.

**Comment by Pectojin** [comment]
I believe this is resolved but the issue hasn't been updated/closed.
https://www.duplicati.com/donate/#crypto

**Comment by kenkendk** [comment]
Yes, this is now fixed with the link posted by @Pectojin
