### ISSUE TITLE
Default filters excluding .rbf files

### ISSUE THREAD

**Issue by mortisj** [duplicati/duplicati#2886]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: Latest master
- **Operating system**: WIndows 10
- **Backend**: 

## Description

It see that Duplicati has borrowed some of the default Windows exclude filters from CrashPlan.  In the process you have copied a bug I have complained to CrashPlan about, namely you are excluding "*.rbf" files.  This filter was intended to exclude Windows Rollback Files but there is a least one application that I know about (PCLaw) that stores some of its application data in files ending with .rbf.

I'd suggest you be a little more selective with .rbf files.  Maybe use "config.msi/*.rbf" instead.

I understand that using the default filters is optional (unlike with CrashPlan where they are mandatory), but people will use them without fully exploring the details, assuming they are safe.  I'd say better to err on the side of backing up too much, rather than too little.  

Thanks.

**Comment by kenkendk** [comment]
I am not familiar with "Rollback files", but we can easily change the filter.

When I read your description, it seems that the rollback files are created in a subfolder?
So I would see `C:\Test\config.msi\xyz.rbf`?

If that is correct, the current `*.rbf` filter could be changed to `*\config.msi\*.rbf`.

**Comment by mortisj** [comment]
Hi:

The config.msi directory and contained .rbf files are created by Windows
Installer when installing new applications on a computer.  Theoretically
they are temporary, but problems with an install can leave them lying
around.  They will be located on the same drive as the program being
installed, so not necessarily on C:.  I believe the config.msi directory is
in the root directory of the associated drive, but of course it might be
referenced using a network path, so you can't assume the filename begins
with a drive letter.

I think *\config.msi\*.rbf is what you want, assuming the rule is
case-insensitive.

Thanks.

On Sun, Nov 19, 2017 at 10:21 AM, Kenneth Skovhede <notifications@github.com
