### ISSUE TITLE
Helpfull message box [feature request]

### ISSUE THREAD

**Issue by mr-flibble** [duplicati/duplicati#2887]
Hello this is feature request.

I often get this message box:
![image](https://user-images.githubusercontent.com/5197625/32619475-3460b950-c57b-11e7-8d65-64815597c153.png)

But when i click on "show" I get this screen with last 100 messages. But I don't know where to look. - I don't know if error is from today or last week, last month....

Can message box in future version be more helpfull ? Thanks

![image](https://user-images.githubusercontent.com/5197625/32619589-849b2090-c57b-11e7-8026-55013ecbf07f.png)

**Comment by kees-z** [comment]
I agree. It's hard to find out to which log entry a notification popup belongs. There is no clue which line to expand to see the warning or error. If at least the lines are grouped by operation and it's easy to identify the jobs containing warnings or errors, it will be much easier to find the actual error message.
Discussion about this at the forum:
https://forum.duplicati.com/t/feature-request-better-reporting/46/6

**Comment by mr-flibble** [comment]
Hello, maybe alternative way can be display job status in backup log?  So we can see immediately jobs status (maybe   ParsedResult: Success/Warning... ?) 

![image](https://user-images.githubusercontent.com/5197625/35510008-971d668c-04f6-11e8-9575-7b1c7dbc1e24.png)

## Maybe the simplest option:

What about button to expand all backups results on page? After than, user can simply search text from browser....
This avoids the problem of having to click on all the backups.

Thanks.

**Comment by kees-z** [comment]
According to @kenkendk, grouping and adding a status indicator should be not difficult to implement:

https://forum.duplicati.com/t/feature-request-better-reporting/46/6

**Comment by kenkendk** [comment]
My plan is to add a "run-id" to the log messages, which will make it trivial to group items.

This will also make it more simple to collect all messages in one place (one log for all message, but with the option to "dive into" a specific backup, or run).

The current log system is a bit of a mess, with at least three levels of logging happening, so I will rewrite that as well.

**Comment by warwickmm** [comment]
I believe this was much improved in pull request #3510.  If there are further improvements to make, I think we should create a new issue with details relevant to the current user interface.
