### ISSUE TITLE
Autoupdater process spawning error arguments

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#2891]
Hi,

I was investigating an issue why after update TrayIcon was spawning hosted server even when nohosted was specified.
I found this issue, which is more broad.

https://github.com/duplicati/duplicati/blob/50a23c85d192e1d69222a23977d9bbe3bccc7654/Duplicati/Library/AutoUpdater/UpdaterManager.cs#L1073
```

            var args = Environment.CommandLine;
            var app = Environment.GetCommandLineArgs().First();
            args = args.Substring(app.Length);

            if (!Path.IsPathRooted(app))
                app = Path.Combine(InstalledBaseDir, app);

            var executable = Path.GetFileName(app);

            while (true)
            {
                var best = GetBestUpdateVersion(true);
                var folder = best.Key;

                var pi = new System.Diagnostics.ProcessStartInfo(Path.Combine(folder, executable), args)
                {
                    CreateNoWindow = true,
                    UseShellExecute = false,
                    RedirectStandardError = true,
                    RedirectStandardInput = true,
                    RedirectStandardOutput = true,
                    ErrorDialog = false,                    
                };

```

These are debug variable content during my debug session.

**Environment.CommandLine** = "D:\Projects\Duplicati\Duplicati\GUI\Duplicati.GUI.TrayIcon\bin\Debug\Duplicati.GUI.TrayIcon.exe" --no-hosted-server --read-config-from-db --server-datafolder="D:\dup\data"  --accept-any-ssl-certificate

**var app** = D:\Projects\Duplicati\Duplicati\GUI\Duplicati.GUI.TrayIcon\bin\Debug\Duplicati.GUI.TrayIcon.exe

args after substring **args** = e" --no-hosted-server --read-config-from-db --server-datafolder="D:\kerbdup\data"  --accept-any-ssl-certificate

Issue is clearly there, that path in commandline is quoted in double quotes, but Environment.GetCommandLineArgs().First() returns result without quotes.

Than substring returns wrong portion of string, and spawn process starts with incorrect arguments and ignore them.

**Comment by mnaiman** [comment]
Found that double quote stripping happens even in arguments:
so -server-datafolder="D:\dup\data" is converted to -server-datafolder=D:\dup\data

There is one reference to this "bug"
http://www.mobzystems.com/code/bugingetcommandlineargs/

**Comment by mnaiman** [comment]
Hope that help for fixing, my dev machine is broken. :(

**Comment by kenkendk** [comment]
The link has a mistake, the stripping happens from the commandline, not C#.
You can try the same with a batch script and see the results.

I can see the problem though... the `Environment.CommandLine` property is actually constructed, and I was assuming that it was the `GetCommandLineArgs` property that was parsed.
