### ISSUE TITLE
reverts excluded local files to previous versions on backup (?)

### ISSUE THREAD

**Issue by simonhermann** [duplicati/duplicati#2899]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 10
- **Backend**: Google Drive

## Description

While working I stumbled upon the problem that changes I make are gone. 
I am not totally sure if this is caused by duplicaty, but the "changed" timestamp on files matches my backup time. I am allso not sure if it only happened with excluded files.
Maybe it has to do with the setup that my user/Documents/ folder is not actually located on C: drive but on D: with a symlink?

## Steps to reproduce

(uncertain)

- **Actual result**:
when a backup is done some files get reverted to old version
- **Expected result**:
No local files / excluded local files should be changed when a backup is running

## Debug log

no log is shown in frontend

**Comment by kenkendk** [comment]
Sounds very strange. Duplicati does not open any files with write permission during the backup, so it should not be able to change any files. Is it perhaps something with a file that is open (say in Notepad++) and after the backup you get an older copy?

**Comment by ts678** [comment]
@simonhermann any later conclusion? "Steps to reproduce" were originally listed as "uncertain", and other cause was suggested.
If Duplicati backup runs were truly reverting source files, we'd probably be hearing from lots of people, and that's not happening.

**Comment by warwickmm** [comment]
Duplicati does not modify any source files (if it did, that would be terrible).  Due to the age, and since we haven't heard of this occurring elsewhere, I'm going to close this issue.  If this is still occurring, please reopen and provide new details.

**Comment by simonhermann** [comment]
@ts678 I did not use duplicati a lot after having this issue, so I can't say anything more. I guess the problem was not related to duplicati after all..
