### ISSUE TITLE
E-Mail notifications

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#29]
_From [fre...@gmail.com](https://code.google.com/u/108325204777532938056/) on March 14, 2009 14:44:16_

Introduce in the settings and setup process a way to configure e-mail
notifications with the results of backup jobs.

The configuration dialog could have the following fields:
- SMTP Server
- SMTP User Name
- SMTP Password
- Sender's Address
- Target Addresses (more than one, separated by comma)
- E-Mail Subject Prefix
- Send on Success (checkbox)
- Send on Failure (checkbox)
- Test E-Mail (button to test these settings)

Considering that Duplicati is to be run silently in the background, this
feature brings too benefits:
- I can be notified by e-mail on failure, so I know that I need to check it.
- The IT department of my company can be notified about my backup, being
  sure that things are working properly at my side.

The e-mail message could even include a summary about the backup job.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=29_

**Comment by PehrGit** [comment]
> Test E-Mail (button to test these settings)

I very much want this button! Now I have to run a dummy backup and check the logs over and over so get the settings right.
