### ISSUE TITLE
Backed up files missing in restore

### ISSUE THREAD

**Issue by susnick** [duplicati/duplicati#2905]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**:2.0.2.1_beta_2017-08-01
- **Operating system**: Windows Server 2012
- **Backend**: gcs

## Description

Using Duplicati.Commandline.exe to perform an initial backup and restore to test, the restored files are less than what was backed up.
 
Duration of backup: 20:55:25
  Remote files: 6291
  Remote size: 153.63 GB
  Files added: 549588
  Files deleted: 0
  Files changed: 0
  Data uploaded: 153.63 GB
  Data downloaded: 114.85 MB
Backup completed successfully!

Restore started at 11/21/2017 4:53:31 PM
Checking remote backup ...
  Listing remote folder ...
Searching backup 0 (11/21/2017 12:35:25 AM) ...
  549336 files need to be restored (182.18 GB)

I need to understand why all files would not be restored, and how to restore them all. If there is any other info you need, let me know

**Comment by kees-z** [comment]
My guess is that the files that were are missing in the restored files total already exist on your local system. By default Duplicati backups all files in selected sources, including Hidden and System files. If a number of (hidden) files already exist (for example desktop.ini) and are the same as the version in the backup, the file is skipped during the restore operation.

**Comment by susnick** [comment]
I do not think Duplicati checks directories outside of selected sources. In my test, I had one directory. I backed up, I then removed the source directory to a different disk. I expect when running restore, Duplicati would restore all files to their original location. if not at least notify me which files it thinks it already has.

**Comment by susnick** [comment]
I found out what the issue is. The 252 files that failed to restore do not have a file extension. Can this be corrected?

**Comment by kenkendk** [comment]
Can you see the files in the file list when you go to restore? Do you get any warnings?

**Comment by kees-z** [comment]
Using the GUI, I can restore extension-less files fine. I didn't have time to try it from the commandline, like OP does.

**Comment by susnick** [comment]
I made a much smaller test case. 

Backup started at 11/28/2017 9:02:28 AM
Checking remote backup ...
  Listing remote folder ...
Scanning local files ...
  8 files need to be examined (4.61 MB)
  0 files need to be examined (0 bytes)
  Uploading file (4.46 MB) ...
  Uploading file (5.54 KB) ...
  Uploading file (1.73 KB) ...
Compacting remote backup ...
Compacting not required
Checking remote backup ...
  Listing remote folder ...
Verifying remote backup ...
Remote backup verification completed
  Downloading file (1.73 KB) ...
  Downloading file (5.54 KB) ...
  Downloading file (4.46 MB) ...
  Duration of backup: 00:00:17
  Remote files: 3
  Remote size: 4.46 MB
  Files added: 8
  Files deleted: 0
  Files changed: 0
  Data uploaded: 4.46 MB
  Data downloaded: 4.46 MB
Backup completed successfully!


Then the restore

Restore started at 11/28/2017 9:03:18 AM
Checking remote backup ...
  Listing remote folder ...
Searching backup 0 (11/28/2017 2:02:33 PM) ...
  7 files need to be restored (4.55 MB)
Checking existing target files ...
1 remote files are required to restore
  Downloading file (4.46 MB) ...
Creating missing folder E:\Backup\testbackup\4567832 for  file E:\Backup\testbackup\4567832\ATR 59416 LEGGIN.pdf
  0 files need to be restored (0 bytes)
Verifying restored files ...
Restored 7 (4.55 MB) files to original path
Duration of restore: 00:00:08

So as you can see Duplicati backed up 8 files, but only restored 7 files. The file missing did not have a file extension. I do not see any warnings.

**Comment by susnick** [comment]
Keez-z reply also made me look closer at the problem. When I was restoring I was using "*.*" which tells me it has to have an extension. I changed to just "*" and it restored all files.

**Comment by warwickmm** [comment]
It sounds like this has been resolved.  The issue was due to using a filter that only included files with extensions.
