### ISSUE TITLE
Large memory foot print

### ISSUE THREAD

**Issue by charlesverge** [duplicati/duplicati#2908]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1 
- **Operating system**: Mac OS X 10.10.5, Ubuntu 16.04
- **Backend**: sftp, local file directory

## Description

I've tested duplicati 2.0.2.1 on Mac OS X 10.7, Linux ubuntu 16 and found the memory foot print of 2.5 gig + requirement to be impracticable to be used on a long term basis. Esp if it was to be used on a smaller instance on aws where a vm might only have 1 gig of memory to start with.

Is there any way to reduce the foot print of this application or is there alternatives which are more suitable to use in production environment.

From a design preceptive, I'm not entirely sure where the reason is to have a daemon running requiring that much memory.

## Steps to reproduce

1. Install
2. Setup
3. Backup files over 100 Gig
4. Check memory usuage

- **Actual result**:
2.5 gig ram requirements for duplicati

- **Expected result**:
Less than 100 megs

**Comment by mnaiman** [comment]
Hi,
How many files do you have in backup?
Are you using ZIP or 7z? 
When I used 7z, it used 2GB RAM, using ZIP less than 100MB.

**Comment by djtm** [comment]
Can you please test with a current verrsion (2.0.0.3+)? I'm doing large backups with under 100 MB memory usage (RSS) on a rpi.

**Comment by warwickmm** [comment]
See other reported memory issues in #4108, which appear to be fixed.  If this is still an issue, please open a new issue.
