### ISSUE TITLE
E-mail notifications working only in specific conditions

### ISSUE THREAD

**Issue by ParHelia12** [duplicati/duplicati#2913]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows 10
- **Backend**: SSH / Qnap

## Description

E-mail notifications do only work in specific conditions:

## Steps to reproduce

1a) does not work with a scheduled backup
or
1) click on "Home"
2) Click on "Run now"

On the other hand it does work when:
1) clicking on "home"
2) Expand the backup configuration
3) Clicking on "run now" under "operations".

Following options are used

--send-mail-from=xxx@posteo.de
--send-mail-url=smtp://posteo.de:587/?starttls=always
--send-mail-username=xxx@posteo.de
--send-mail-password=xxx
--send-mail-subject=%PARSEDRESULT%: Duplicati %OPERATIONNAME% report for %backup-name%
--send-mail-level=All
--send-mail-to=xxx@posteo.de
--accept-specified-ssl-hash=HASH_for_Posteo

Sidenotes:
- when specifying the above additional options under "Settings", they will not be parsed correctly in the GUI when expanding the backup configuration in "home" and going in "command line".
- When specifying the above additional options directly in the backup config, they will be displayed correctly but in both cases behaviour is the same -> mail notification will only be sent under described condition.

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by ParHelia12** [comment]
Issue is already solved by using option accept-any-ssl-certificate.

The parsing issue in the GUI is the only issue remaining but it does not seem to affect backup execution including the correct handling of the different options.

**Comment by ts678** [comment]
> The parsing issue in the GUI is the only issue remaining

Not reproducible. Pasting shown options to Settings --> Default options --> Edit as text displayed OK in Commandline.
I wonder if there were any special characters in the non-redacted original that threw it off? Or maybe parsing was fixed?
Any recollection of what "will not be parsed correctly in the GUI" looked like? Does issue happen on the current release?
