### ISSUE TITLE
SRPM? where?

### ISSUE THREAD

**Issue by x09** [duplicati/duplicati#2915]
where can I get the srpm package? For rebuild for other rpm-based OS

**Comment by kenkendk** [comment]
Not sure exactly what you want, but there is a script to build an srpm here:
https://github.com/duplicati/duplicati/tree/master/Installer/fedora

You basically call this script, and it will checkout the source and build a rpm+srpm:
https://github.com/duplicati/duplicati/blob/master/Installer/fedora/build-package.sh
