### ISSUE TITLE
error while running backup  Access to the path "/xxx/xxx/xxx/xxxx/duplicati-b8bfd56dcaaa24cc3859aaac417741ff8.dblock.zip.aes" is denied.

### ISSUE THREAD

**Issue by KarthickSJ** [duplicati/duplicati#2916]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 0.0.0.0
- **Operating system**: Replace me
- **Backend**: Replace me

## Description

Replace me

## Steps to reproduce

1. Replace me
2. Replace me
3. ...

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by Pectojin** [comment]
It's 99% certainly an OS issue. Check the file permissions :)
