### ISSUE TITLE
Emails notifications not sending for larger backups

### ISSUE THREAD

**Issue by BackupMann** [duplicati/duplicati#2920]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
Running latest Linux XFCE 4.12. 
Backend - runs to our FTP server on another linux machine (within the network)
- **Duplicati version**: Latest
- **Operating system**: Linux XFCE 4.12
- **Backend**: Latest Linux (no gui, just running vsftpd)

## Description

Just to start  I think duplicati is a great tool and we are looking to use it to replace our current backup system which is a bit shakey. The problem is that I am not receiving email notifications from larger backups. All smaller test backups send email notifications fine but when I have ran 50gb or 200gb backups I just don't receive them. Currently the linux machine that it is running duplicati is acting as its own smtp server essentially (for itself) to communicating through our exchange server to then send out the emails to only us within the network. It does work great (after many hours trying to configure it) but it just doesn't seem to send for the larger backups. I have wondered though if an error occurs after a backup will the email still send? because the two large backups I ran (50gb and 230gb) had two errors on each (couldn't grab certain files). Any help would be great!

**Comment by ts678** [comment]
> I have wondered though if an error occurs after a backup will the email still send?

It does in recent versions at least. I'm not sure what version this was on. Did the email problem ever get figured out or solved?
If you really need to look into it, set a log-file at `profiling` level (it will be very large), and near the end should be email work.

Here's the start of SMTP server sending for an error:

```
2020-11-17 20:23:11 -05 - [Profiling-Timer.Finished-Duplicati.Library.Main.Controller-RunBackup]: Running Backup took 0:00:02:48.288
2020-11-17 20:23:13 -05 - [Profiling-Duplicati.Library.Modules.Builtin.SendMail-SendMailResult]: Whole SMTP communication: Connected to smtp://smtpauth.earthlink.net:587/?starttls=always
S: 220-elasmtp-dupuy.atl.sa.earthlink.net ESMTP Exim 4 #1 Tue, 17 Nov 2020 20:23:12 -0500
S: 220-NO UCE.  EarthLink does not authorize the use of its computers or network
S: 220 equipment to accept, transmit, or distribute unsolicited e-mail.
C: EHLO [192.168.0.109]
```

**Comment by ts678** [comment]
If this is still of interest, please give feedback on the above reply.
