### ISSUE TITLE
Backup Failed: Hash mismatch on file "/tmp/dup-784369fc-6e9e-4f19-82cf-caaa827b65e0"

### ISSUE THREAD

**Issue by ammannbe** [duplicati/duplicati#2924]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Debian GNU/Linux 9.1 (stretch)
- **Backend**: local (mounted NFS Storage)
- **Encryption**: No

## Description

Running backup in the web interface (after some days) produces an exception and does not end up with a successful backup. After the backup ends, I get an email with the following error:
```
Failed: Hash mismatch on file "/tmp/dup-784369fc-6e9e-4f19-82cf-caaa827b65e0", recorded hash: qB8p61teLBUwIZQL3X+qsjLUh4zrOk+ZCa3I1An39yE=, actual hash EJ+Wuvt5T0f/aN5MB7EPw9Rrg/hJMMoeNlLWZZAOy4Y=
Details: Duplicati.Library.Main.BackendManager+HashMismatchException: Hash mismatch on file "/tmp/dup-784369fc-6e9e-4f19-82cf-caaa827b65e0", recorded hash: qB8p61teLBUwIZQL3X+qsjLUh4zrOk+ZCa3I1An39yE=, actual hash EJ+Wuvt5T0f/aN5MB7EPw9Rrg/hJMMoeNlLWZZAOy4Y=
  at Duplicati.Library.Main.AsyncDownloader+AsyncDownloaderEnumerator+AsyncDownloadedFile.get_TempFile () [0x00008] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.CompactHandler.DoCompact (Duplicati.Library.Main.Database.LocalDeleteDatabase db, System.Boolean hasVerifiedBackend, System.Data.IDbTransaction& transaction) [0x0025e] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.DeleteHandler.DoRun (Duplicati.Library.Main.Database.LocalDeleteDatabase db, System.Data.IDbTransaction& transaction, System.Boolean hasVerifiedBacked, System.Boolean forceCompact) [0x00334] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.CompactIfRequired (Duplicati.Library.Main.BackendManager backend, System.Int64 lastVolumeSize) [0x00092] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x00734] in <118ad25945a24a3991f7b65e7a45ea1e>:0
```
This error appears since 12/01/2017. On 11/30/2017 ran the last successful backup.

## Backup configuration (export as Command-line)
mono "/usr/lib/duplicati/Duplicati.CommandLine.exe" backup "file:///backup/" "/var/mail/virtual/" --backup-name="eMail" --dbpath="/root/.config/Duplicati/MXDCKQKQHK.sqlite" --encryption-module= --compression-module="zip" --dblock-size="10GB" --keep-time="10D" --no-encryption="true" --send-mail-level="all" --send-mail-to="myEmail" --send-mail-from="duplicati@myDomain" --exclude-files-attributes="temporary" --disable-module="console-password-input"

**Comment by hausmonarch** [comment]
Seeing the same thing on 2.0.2.13_canary_2017-11-22:

`Failed to process file duplicati-b4e99860187e14225b262ca87c065dc1c.dblock.zip.aes => Hash mismatch on file "/tmp/dup-0595915d-c50c-4ce8-9594-43629189571a", recorded hash: oxOTds52+6CjHn0mc7UZ58KbzfhS5lZ1xW9gmewaHuw=, actual hash 3qvqe+jOVP0ktD83p/Mor8UbfasehAKOZa5iA1OVYSQ=`

I'm going to switch back to beta with the same configuration and see what happens. This was a fresh backup (old fileset was moved and database was deleted).

**Comment by ts678** [comment]
The "Hash mismatch" on the temporary file means incorrect data in a downloaded file. as read back from NFS in the original post. Second report doesn't say what the destination was, but the posted message at least gives the name of file downloaded to /tmp.

Whenever these come up, the file in backup  is the one to inspect, not necessarily by hash, but by tools like decryptor or zip tool.  Getting the full story in messages can be awkward, but one good way is to use About --> Show log --> Live --> Error. Example:

![image](https://user-images.githubusercontent.com/40771998/102559630-4c0f1780-409e-11eb-8bad-11b3dd6d2048.png)

The details in the grey aren't shown until the summary is clicked on. In the job log, you'll just see the summary and not the detail.
For the example, I used a hex editor to corrupt a byte in the middle of that .zip file. To research cases here, now, would be difficult.
Original has enough to see that it's in a `compact`, which is after backup and retention deletes to consolidate now-empty dblocks. Some previous file did not read back expected data (Duplicati keeps records) from NFS. I don't know what would be causing that...

**Comment by ts678** [comment]
Issue got a comment above, and is pretty old. Please give feedback if it's still relevant. What's needed are solid reproducible steps.

**Comment by ammannbe** [comment]
I don't use duplicati anymore, so can't say the detailed steps.

**Comment by ts678** [comment]
Thanks. This doesn't seem very actionable, so I'll probably let it auto-close unless the other 2017 poster wants to pick it up.
