### ISSUE TITLE
System.ArgumentException when executing backup on command line with exclude filter containing "~" tilde char 

### ISSUE THREAD

**Issue by kellerassel007** [duplicati/duplicati#2932]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Win10 64bit
- **Backend**: Backblaze B2 Cloud

## Description
System.ArgumentException when executing backup on command line with exclude filter containing "~" char.
Example:
`--exclude="[.*~]"`

## Steps to reproduce
1. Choose any backup settings you want and configure the exclude (regex) filter: 
`--exclude="[.*~]"`
2. Export your configuration for running as cmd command
3. Copy and execute cmd command

## Screenshots
![exception](https://user-images.githubusercontent.com/17928494/34079147-da58504c-e327-11e7-9663-931bddfcbe79.PNG)

## Workaround
Replace " by '
Fail executing on cmd: `--exclude="[.*~]"`
OK: `--exclude='[.*~]'`

**Comment by warwickmm** [comment]
In version 2.0.2.1_beta_2017-08-01, Duplicati is incorrectly replacing `~` with the path to your home directory.  This is fixed in version v2.0.2.13-2.0.2.13_canary_2017-11-22.

**Comment by warwickmm** [comment]
Tilde expansion was removed in pull request #2836, and has been available since version v2.0.2.13-2.0.2.13_canary_2017-11-22.
