### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by mmiat** [duplicati/duplicati#2935]
## Environment info
- **Duplicati version**:  2.0.2.13
- **Operating system**: QNAP 4.3.3.0404
- **Backend**: FTP

## Description
the backup process has became very long....
it's about 1TB of data, but the new daily data are only some MBs (10-100MBs usually)
backup requires 15h
NAS is cheap and poor, but ram is about 60% and cpu 10%

my options are:
--check-filetime-only=true
--blocksize=100MB
--tempdir=/share/CACHEDEV1_DATA/.tmp/
--log-retention=30D
--log-level=Information
--zip-compression-level=9

what can i change to improve performance? change encryption or compression algorithm?
thanks

**Comment by mmiat** [comment]
i've
- folder 1: 32GB of data, 38GB of backup, 67 versions > it tooks 12h
- folder 2: 32GB of data, 37GB of backup, 73 versions > it tooks less than 1h
- folder 3: 957GB of data, 700GB of backup, 63 versions > it tooks 14h
what could be with folder 1 that requires so much time ? how to find ?

**Comment by Pectojin** [comment]
Do you have any stats on how much you upload? 

With 100MB blocks you might be spending a ton of time uploading blocks. Any small change in a block will cause Duplicati to upload 100MB of data.

You may also benefit from the `retention-policy` tag. It allows you to reduce the number of backups kept within time frames. So if you only need regular backups from the last week, and then maybe just a few backups from the last months, then you'll be able to reduce the size of your local database.

**Comment by mmiat** [comment]
folder 1: usually 0, sometimes some hundereds of MB
folder 2: usually some MB, less than 100MB
folder 3: usually some MB, less than 1GB, sometimes a couple of GB
so, i could delete all and use a smaller blocks ?

**Comment by Pectojin** [comment]
Hmm, that isn't too bad. I'm not sure how much a smaller block size will help then. It definitely shouldn't take 14 hours to upload a GB or two.

If CPU and RAM isn't maxed out, is it possible that disk is a limiting factor?

**Comment by mmiat** [comment]
i don't think, folder 2 is similar to folder 1 and require 1/12 of time
i think it's something relative to structure of folder 1 or db

**Comment by Pectojin** [comment]
I would assume folder 1 has many more small files, since that's usually what slows down operations. Each file would need to be stored in the index and checked every backup. Additionally, disks can have a large overhead on reading small files. 

That being said, it still seems extreme. 

If you think it's a database issue, you can try recreating it under advanced -> database -> Recreate (delete and repair). It might take a while to rebuild, though.

**Comment by mmiat** [comment]
recreate requires a lot of time
so it's better if before launch it i reduce blocks to 1MB or 10MB ?

**Comment by Pectojin** [comment]
You can only change block size if you re-upload all your data. Recreating the database won't change the backup data, only the local database (basically indexes of the uploaded files).

**Comment by mmiat** [comment]
i've deleted all, reduced block at 1MB and restart job
it says "128GB to go at 7KB/s"
so there was something with dimension
but it seems to me still too slow...

**Comment by Pectojin** [comment]
I would be interested to see performance with a lower `--zip-compression-level`. 

Could you set up a small test to compare a few different levels?

9 gives the best compression, and thus also slowest, so limited by hardware may see improved performance with a lower setting. Of course this also means your backup destination will use more space.

**Comment by mmiat** [comment]
restarted again
with no option (which is --zip-compression-level default?) after 2 hours is slow as before
now i've restarted again with --zip-compression-level = 0

**Comment by Pectojin** [comment]
I believe default `--zip-compression-level` is 9, so that should behave the exact same as explicitly setting 9.

**Comment by mmiat** [comment]
after 1 hour it shows "7395933 files (128.44 GB) to go at 9.55 KB/s"

**Comment by mmiat** [comment]
i suppose it's a cpu problem....

su NAS232, 73 versions (cpu quad core Intel Atom D2701 bench 720)
SizeOfModifiedFiles: 392572
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 34558302984
SizeOfOpenedFiles: 392572
Duration: 12:37:13.6629010

su NAS234, 1 versions (cpu dual core Intel E4400 bench 1159)
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 34558302984
SizeOfOpenedFiles: 5449738
Duration: 03:14:06.0586670

**Comment by mmiat** [comment]
noway, with new NAS with E4400 folder 3 has passed from 14h to 41h ....

**Comment by mmiat** [comment]
i deleted all backup and restart from scratch in new nas
now folder 1 requires 3-4h (still dont understand why so much) and folder 3 requires 4-5h
maybe some issue with db and cpu
