### ISSUE TITLE
deb file is not a debian format archive

### ISSUE THREAD

**Issue by asim-vax** [duplicati/duplicati#2936]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
Duplicati 2.0.2.2.1 or 2.0.2.13
Ubuntu 16.04

## Description
sudo dpkg -i duplicati_2.0.2.13-1_all.deb 
dpkg-deb: error: 'duplicati_2.0.2.13-1_all.deb' is not a debian format archive
dpkg: error processing archive duplicati_2.0.2.13-1_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 duplicati_2.0.2.13-1_all.deb

## Steps to reproduce

1. Download .deb from homepage or releases on github
2. attempt to install with above command
3. get error

Please help fix this :)

**Comment by hoilc** [comment]
Hi @asim-vax 

I tested the duplicati 2.0.2.13 package and it works fine.

Maybe your package was broken during the download.

Could you check the integrity with the hashes in duplicati-*signatures.zip?

![image](https://user-images.githubusercontent.com/9067094/34286138-bc61f69c-e719-11e7-9478-0dd30a4605f4.png)

**Comment by asim-vax** [comment]
Hah, totally sorry - downloaded it again today, checked the sha1sum, and it installed fine.
Apologies!
