### ISSUE TITLE
duplicati-cli does nothing after 12 hours

### ISSUE THREAD

**Issue by yunesj** [duplicati/duplicati#2941]
- [x] I have searched open and closed issues for duplicates.

`duplicti-cli` uses 100% CPU, but writes no files after 12 hours. This is my first time running `duplicati-cli`.

Command: `sudo duplicati-cli backup file:///mnt/duplicati_backups/apt/ "/home/"`
Version: `duplicati-cli` 2.0.2.14_canary_2017-12-22
OS: Linux host 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

`top` shows 100% CPU utilization.

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                             
    10402 root      20   0  803008  72496  32820 R 100.0  0.2   3:58.65 mono-sgen 
```

`strace` attached:

```
sudo strace -p10402
strace: Process 10402 attached
strace: [ Process PID=10402 runs in x32 mode. ]
--- SIGPWR {si_signo=SIGPWR, si_code=SI_TKILL, si_pid=10402, si_uid=0} ---
strace: [ Process PID=10402 runs in 64 bit mode. ]
rt_sigprocmask(SIG_BLOCK, [XCPU], NULL, 8) = 0
futex(0x956ea0, FUTEX_WAKE_PRIVATE, 1)  = 1
rt_sigsuspend(~[XCPU RTMIN RT_1], 8)    = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGXCPU {si_signo=SIGXCPU, si_code=SI_TKILL, si_pid=10402, si_uid=0} ---
rt_sigreturn({mask=~[KILL STOP RTMIN RT_1]}) = -1 EINTR (Interrupted system call)
rt_sigprocmask(SIG_UNBLOCK, [XCPU], NULL, 8) = 0
futex(0x956ea0, FUTEX_WAKE_PRIVATE, 1)  = 1
rt_sigreturn({mask=[]})                 = 140730362033584
```

Not a lot going on according to `lsof` either:

```
mono-sgen 10402 root  mem    REG    0,21     4096        5 /dev/shm/mono.10402
mono-sgen 10402 root    0r  FIFO    0,10      0t0  1495230 pipe
mono-sgen 10402 root    1w  FIFO    0,10      0t0  1495231 pipe
mono-sgen 10402 root    2w  FIFO    0,10      0t0  1495232 pipe
mono-sgen 10402 root    5r   CHR     1,9      0t0       11 /dev/urandom
mono-sgen 10402 root    6u  IPv4 1497329      0t0      TCP a.yunes.us:45370->139.59.135.67:https (CLOSE_WAIT)
mono-sgen 10402 root    7r  FIFO    0,10      0t0  1496319 pipe
mono-sgen 10402 root    8w  FIFO    0,10      0t0  1496319 pipe
```

Adding `--verbose=true` didn't add any output, as far as I could tell.

**Comment by ts678** [comment]
> strace attached:

I don't see a file attachment. Were the posted lines all?

[Embedding Mono](https://www.mono-project.com/docs/advanced/embedding/) explains the part of the little strace I can comment on:

> SIGPWR, SIGXCPU: these are used internally by the GC and pthreads.

Did you ever figure this out? Does it happen currently? Note that current Duplicati is two processes. Your old one might be one.
