### ISSUE TITLE
Recover from partial backup?

### ISSUE THREAD

**Issue by markuskramerIgitt** [duplicati/duplicati#2943]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: duplicati-2.0.2.1_beta_2017-08-01-x64.msi
- **Operating system**: Windows 7
- **Backend**: Local disk

## Description
I started Duplicati, writing to a Local Disk.
At about 30% I stopped.
I need to recover the 30% partial backup.
duplicati Failed to connect: SQL logic error or missing database no such table: LogData

## Steps to reproduce
1. Start Duplicati with the task to backup files from c: to Local Disk.
2. Stop Duplicati at around 30%
3. Try to recover the partial backup from Local Disk
4. Got message duplicati Failed to connect: SQL logic error or missing database no such table: LogData
behavior). 

- **Actual result**:
duplicati Failed to connect: SQL logic error or missing database no such table: LogData

- **Expected result**:
Duplicati shows the the partial backup and allows me to recover data.

(How) can I recover data from a partial backup?

**Comment by Pectojin** [comment]
Are you trying to restore directly from your backup files or from the backup job? 

It's possible that the database used by the job has an error in it, but you should be able to recover the data by using the "Direct restore from backup files" restore option as that will construct a new database from the uploaded files.

If that doesn't work, you can use the [Duplicati Recovery Tool](https://github.com/duplicati/duplicati/blob/9007165139e5c4d060149bc0bdbfa54bef6fb695/Duplicati/CommandLine/RecoveryTool/help.txt) as a last resort.

**Comment by markuskramerIgitt** [comment]
Hi @Pectojin,
I try to restore directly from backup files, not the backup job.

I started a backup and stoped in the middle (26 zip files, 650 MB).
My steps to restore: Menu, Restore, "Direct restore from backup files ...", Next, [Folder Path] chosen, Next, No Passphrase Connect.

Error Failed to connect: No filesets found on remote target
"Show"--> Failed to connect: SQL logic error or missing database no such table: LogData 

Do I need an advanced option to construct the database from the uploaded files?


Thank you

**Comment by Pectojin** [comment]
When you look at the remote files, do you have any `dlist` files? The naming convention is like this:
`duplicati-20180114T130000Z.dlist.zip.aes` 
where the numbers in the middle represent the date you backed up (in UTC).

This file contains the file list, so if it's missing duplicai doesn't know the filename, path, and permissions of the files backed up.

**Comment by markuskramerIgitt** [comment]
I have no ```*.dlist.`*``` file, only ```*.zip```.

What could the Duplicati Recovery Tool do with only ```*.zip``` files?

**Comment by Pectojin** [comment]
I'm not sure it can do much... I think it also looks at the dlist files.

Technically the files stored in the blocks can be extracted, since small files fit within a block and large files are described in "indirection blocks" inside the zip files. But I don't think the tool can do that and even if it could you'd end up with a bunch of unnamed files dumped into a folder.

**Comment by markuskramerIgitt** [comment]
Then I will not attempt to recover my partial backup, because I have no dlist.
A bunch of unnamed files in a single folder is not attractive.


As a potential improvement: Duplicati could  create write the dlist, when the user interrupts the backup.

Thank you.
