### ISSUE TITLE
Feature request: Allow for parallel backups

### ISSUE THREAD

**Issue by rkarlsba** [duplicati/duplicati#2954]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Debian
- **Backend**: jotta.no

## Description

The current code doesn't allow for parallel backups, although often the destination server is a bandwidth, sharing its time with multiple clients. Allowing for simultamous backup jobs will probably speed things up a *lot*. I guess this won't be a very hard thing to implement, with multithreading being quite normal these days.

## Steps to reproduce

1. Start a backup
2. Wait…

- **Actual result**:
It's slow
- **Expected result**:
It runs quickly

**Comment by Pectojin** [comment]
#2775 `Feature request: Run jobs in parallel` sounds a lot like this `Feature request: Allow for parallel backups`. Did you take a look at it to see if it accurately describes your request?
