### ISSUE TITLE
Install et launch duplicati on Windows XP in 2018

### ISSUE THREAD

**Issue by vlepetit** [duplicati/duplicati#2958]
Hi,
I have to install duplicati on old Windows System Windows XP.
Can i do that ?
Maybe with an old version of duplicati ? here : https://github.com/duplicati/duplicati/issues/1310
Other ?

Regards

**Comment by vlepetit** [comment]
I had founded the old duplicati compatible version in archive :
 https://github.com/duplicati/duplicati/releases/tag/v2.0.0.79-2.0.0.79_preview_2015-01-1

**Comment by redec** [comment]
Have you figured out how to install it as a service?  The current documented way doesn’t seem to work...

**Comment by ts678** [comment]
It's 2024. Windows XP support from Microsoft ended in 2014. I'm not seeing a reason to keep this issue open, but I'll check.
Additionally, the second post from original poster seems to have found what was needed.
