### ISSUE TITLE
Server response does not contain SSH protocol identification.

### ISSUE THREAD

**Issue by mdsmdsmds** [duplicati/duplicati#2959]
- **Duplicati version**:  2.0.2.15_experimental_2018-01-03
- **Operating system**: Windows 2012 R2
- **Backend**: SFTP

Upgraded yesterday and now starting with this error:
"Operation List with file  attempt 1 of 5 failed with message: Server response does not contain SSH protocol identification."

**Comment by samirm** [comment]
has this been fixed?

**Comment by warwickmm** [comment]
SFTP is working fine for me and I haven't heard of this happening in the recent beta or canary releases, so I'm assuming it's been fixed.
