### ISSUE TITLE
Duplicati cannot access files on Ubuntu 16.04 when running as a service

### ISSUE THREAD

**Issue by jamesfreeman959** [duplicati/duplicati#2960]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.15_experimental_2018-01-03
- **Operating system**: Ubuntu 16.04.3 LTS
- **Backend**: SFTP

## Description

I have installed Duplicati on my Ubuntu 16.04.3 LTS server simply by running `apt install duplicati_2.0.2.15-1_all.deb` and allowing it to install it's own dependencies. I have enabled the systemd service and started the service. The process table confirms that Duplicati Server is running as root:

```
root      4322     1  0 11:44 ?        00:00:00 DuplicatiServer /usr/lib/duplicati/Duplicati.Server.exe
root      4926  4322  0 11:44 ?        00:00:00 /usr/bin/mono-sgen /usr/lib/duplicati/Duplicati.Server.exe
james    10492  8267  0 11:44 ?        00:00:00 Duplicati /usr/lib/duplicati/Duplicati.GUI.TrayIcon.exe
james    10496 10492 25 11:44 ?        00:00:59 /usr/bin/mono-sgen /usr/lib/duplicati/Duplicati.GUI.TrayIcon.exe
```

I have configured a backup job to back up a data directory, /etc, /home and /root - none of this should be too contentious as the process is apparently running as root. However I see at the end of the run:

```
Jan 12, 2018 1:00 AM: Result
DeletedFiles: 23
DeletedFolders: 0
ModifiedFiles: 85
ExaminedFiles: 7771
OpenedFiles: 309
AddedFiles: 164
SizeOfModifiedFiles: 88473590
SizeOfAddedFiles: 217911
SizeOfExaminedFiles: 58641235451
SizeOfOpenedFiles: 98983069
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 60
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
CompactResults: null
DeleteResults:
    DeletedSets: []
    Dryrun: False
    MainOperation: Delete
    CompactResults: null
    ParsedResult: Success
    EndTime: 12/01/2018 01:00:42
    BeginTime: 12/01/2018 01:00:41
    Duration: 00:00:01.6852890
    BackendStatistics:
        RemoteCalls: 8
        BytesUploaded: 47489085
        BytesDownloaded: 53067825
        FilesUploaded: 3
        FilesDownloaded: 3
        FilesDeleted: 0
        FoldersCreated: 0
        RetryAttempts: 0
        UnknownFileSize: 0
        UnknownFileCount: 0
        KnownFileCount: 770
        KnownFileSize: 20124597134
        LastBackupDate: 12/01/2018 01:00:00
        BackupListCount: 2
        TotalQuotaSpace: 0
        FreeQuotaSpace: 0
        AssignedQuotaSpace: -1
        ParsedResult: Success
RepairResults: null
TestResults:
    MainOperation: Test
    Verifications: [
        Key: duplicati-20180112T010000Z.dlist.zip
        Value: [],
        Key: duplicati-i2e5c2404d45a4f2a92c636d722b0cc2b.dindex.zip
        Value: [],
        Key: duplicati-b018b1a5a91e64b5a84a515d88762ac7b.dblock.zip
        Value: []
    ]
    ParsedResult: Success
    EndTime: 12/01/2018 01:00:49
    BeginTime: 12/01/2018 01:00:43
    Duration: 00:00:05.8777690
ParsedResult: Error
EndTime: 12/01/2018 01:00:49
BeginTime: 12/01/2018 01:00:00
Duration: 00:00:49.3898560
Messages: [
    No remote filesets were deleted
]
Warnings: [
    Failed to process path: /etc/.pwd.lock => Access to the path "/etc/.pwd.lock" is denied.,
    Failed to process path: /etc/at.deny => Access to the path "/etc/at.deny" is denied.,
    Failed to process path: /etc/group- => Access to the path "/etc/group-" is denied.,
    Failed to process path: /etc/gshadow => Access to the path "/etc/gshadow" is denied.,
    Failed to process path: /etc/gshadow- => Access to the path "/etc/gshadow-" is denied.,
...
]
Errors: []
```

These particular files are readable by root and shouldn't be locked, so I'm not sure why Duplicati hasn't been able to back them up. Any suggestions please?

## Steps to reproduce

1. Install latest Duplicati package and run it as a service on Ubuntu 16.04.3 LTS
2. Attempt to back up some files in /etc
3. Fails reliably on my system for some reason

- **Actual result**:
Files are not backed up and an Access Denied error is presented.
- **Expected result**:
Files should be backed up without incident

## Debug log

```
Failed to process path: /etc/at.deny
System.UnauthorizedAccessException: Access to the path "/etc/at.deny" is denied.
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0x41ab7380 + 0x00717> in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) <0x41b5bf20 + 0x00053> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.File.Open (System.String path, FileMode mode, FileAccess access, FileShare share) <0x41efddd0 + 0x0004e> in <filename unknown>:0 
  at Duplicati.Library.Snapshots.NoSnapshot.OpenRead (System.String file) <0x4092f140 + 0x00027> in <filename unknown>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.HandleFilesystemEntry (ISnapshotService snapshot, Duplicati.Library.Main.BackendManager backend, System.String path, FileAttributes attributes) <0x409252f0 + 0x012ee> in <filename unknown>:0 
```

**Comment by Pectojin** [comment]
Do you have app armor installed/enabled? app armor and selinux can often give permission errors if they're enabled and not configured to allow the service.

**Comment by jamesfreeman959** [comment]
Good spot! I come from a mostly Red Hat background so hadn't spotted that app armor was running. Is there a profile available for Duplicati for app armor, or do I need to turn it off for now?

**Comment by Pectojin** [comment]
I hate to advise people to turn it off, but I don't know have a profile handy.

I can take a look at it but strangely apparmor on my Ubuntu machine isn't causing issues.

**Comment by jamesfreeman959** [comment]
Agreed - I think this is something else. I've just disabled apparmor and rebooted, so now there are no profiles loaded at all. I have run my backup set from Duplicati and I'm getting exactly the same error on the same files as before. Really odd - Duplicati almost seems like it is running as an unprivileged user, but it is now running at root with apparmor disabled. Is there anywhere else I can look to further debug this?

**Comment by Pectojin** [comment]
Root should be able to read any file, regardless of it's permissions, unless app armor or selinux prevents it. I'm not sure what else it could be.

**Comment by jamesfreeman959** [comment]
Just doing some additional testing but it looks like this is exactly what was happening. Thank you for the that!

**Comment by jamesfreeman959** [comment]
Thanks everyone for their help with this - work has meant there has been some delay in finalising testing but I'm happy to say Duplicati is working perfectly now, with no spurious errors. The issue was exactly as kenkendk said - I had two servers running, one through systemctl and one when I thought (wrongly) I was launching the tray icon.

Possible RFE: I've love a tray icon on my menu. I edited /usr/share/applications/duplicati.desktop (using XFCE) with the correct parameters to launch a tray icon only, but it gets overwritten when I update to the latest build. I know this is minor - just a thought.
