### ISSUE TITLE
Slow to count files - can it be skipped?

### ISSUE THREAD

**Issue by sjonez** [duplicati/duplicati#2963]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.14
- **Operating system**: Windows 7 x64
- **Backend**: Amazon Drive

## Description

The backup of my NAS which has over 600,000 files seems to spend the first 4-6 hours of the job simply counting the files. I assume the only reason for this is to be able to display/estimate the backup progress once the backup actually starts? Is there a way to skip this process?

## Steps to reproduce

N/A

- **Actual result**:
Slow to count lots of files
- **Expected result**:
Optionally disable counting

**Comment by mr-flibble** [comment]
Interesting idea. 
In Crashplan, we can "verify selection every {number of days} at { time}

Duplicati currently don't have any persistent filesystem watcher as CrashPlan - so counting is mandatory. 

sjonez: Is this your first backup? At first backup, hash of files is computed. 
In later backup, only date modified of files are checked...

**Comment by sjonez** [comment]
It's not my first backup, it's been running for a while now and counting the files has always been slow.

From looking at the code it actually seems like Duplicati recurses through all 600,000 files in a separate parallel thread just to count them, at the same time as it recurses through them to actually do the comparison and back up. I'm guessing once it has the count it can then display current progress.

e.g. from Library/Main/Operation/BackupHandler.cs (Run method)

`parallelScanner = new System.Threading.Thread(CountFilesThread)`

I just feel like this recursion through my entire NAS is slowing the backup down, so it'd be good if it could be prevented with the caveat that I won't be able to see % progress.

**Comment by Pectojin** [comment]
It's certainly an idea. I just tested it by changing the if statement so it never starts the parallel scanner.

It'll just keep saying "Starting" until it's done, but it finished a small (2GB) backup without any problem. So I'd say you're right in your assessment that if you don't care about progress indicators you could certainly avoid looking at all the files twice.

**Comment by kenkendk** [comment]
Yes, the scanner is just for giving a progress estimate, so it can be disabled without problems.

One quick-fix could be to allow disabling the the scanner, and instead just use the number of files/size from the previous backup.

**Comment by maciekb** [comment]
Fix proposed by @kenkendk is in overall good idea, but I have an additional question. Is your Duplicati installed on Windows and are you running backups of your NAS over a network? SMB protocol is very ineffective in listing files. Maybe you can install Duplicati on your NAS and make backups from there?

**Comment by Pectojin** [comment]
I tested without the scanner on the 2.0.2.19 build. It did nothing for my server with an i5-2500k. In fact the time went up from 9 to 10 minutes between two backups run back to back (with no file scanner being 2nd). 

Maybe it got slower because the file scanner makes the disks put info on the files in their internal caches (my server has like a GB of disk cache over it's RAID). But it probably did nothing at all.

It's kind of anecdotal, and my backups usually vary between 9 and 11 minutes, so it probably did nothing for me. But that's just a datapoint for a stronger CPU. It will likely look different on a regular NAS.
