### ISSUE TITLE
Can't move local database file for a backup - ubuntu 17.10

### ISSUE THREAD

**Issue by asim-vax** [duplicati/duplicati#2964]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: ubuntu 17.10
- **Backend**: Amazon S3

## Description
Moving the local database to another folder doesn't work, returns database is locked. Small SSD, larger NAS to store local backup(mounted at /mnt/directory).  Backing up ~1TB to amazon s3, local database fills up local partition too quick and can't move the local database file. Failed to connect: SQLite error no such table: LogData 

## Steps to reproduce

1. Create backup
2. Edit database -> advanced
3. Enter new location, click move existing database. Database gets written at new location.
4. Start backup
5. Error: Database is locked & Failed to connect: SQLite error no such table: LogData 
6. Repeat above steps for original location /home/user/.config/Duplicati and it runs the backup again.

- **Actual result**:
Can't run backup after moving database to a new location
- **Expected result**:
Back up to run as if local database file was in it's original location.

**Comment by Pectojin** [comment]
I was unable to replicate this on Ubuntu (granted, 16.04). 

Is it possible that multiple Duplicati processes were running or that an external program was placing a lock on the database file?

Locks can be inspected on Ubuntu using `lslocks` but the lock should go away by itself or after a reboot.
