### ISSUE TITLE
Backup stuck on 'Starting ...'

### ISSUE THREAD

**Issue by denniskrol** [duplicati/duplicati#2966]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.2.15_experimental_2018-01-03
- **Operating system**: Windows 10 (Duplicati runs as Windows Service.)
- **Backend**: ownCloud (webdav)

## Description

A backup that has been working for months is all of a sudden stuck on 'Starting' when started from the web interface (manual start or schedule). I noticed this when other backups didn't run anymore. At that point the 'broken' backup had been stuck for multiple days.  
The source directory is 70617 files in 3.38GB.

When I export the configuration as command line and run that it completes successfully. 
I exported the config as JSON, removed it from Duplicati (including deleting all backup files), and imported the config again. That didn't help.
Verifying the backup completes successfully.
The only way to stop it is killing Duplicati.Server.exe

The log for the backup job doesn't show anything.
The 'live log' shows the backup starting, then some queries ran, and then nothing...

## Steps to reproduce

- **Actual result**:
Stuck on 'Starting ...'
- **Expected result**:
Backup runs

## Debug log

```Jan 16, 2018 5:27 PM: ExecuteScalarInt64: SELECT COUNT(*) FROM "File" WHERE "BlocksetID" != ? AND "BlocksetID" != ? AND NOT "BlocksetID" IN (SELECT "BlocksetID" FROM "BlocksetEntry") took 00:00:00.046
Jan 16, 2018 5:27 PM: Starting - ExecuteScalarInt64: SELECT COUNT(*) FROM "File" WHERE "BlocksetID" != ? AND "BlocksetID" != ? AND NOT "BlocksetID" IN (SELECT "BlocksetID" FROM "BlocksetEntry")
Jan 16, 2018 5:27 PM: ExecuteScalarInt64: SELECT COUNT(*) FROM (SELECT * FROM (SELECT "N"."BlocksetID", (("N"."BlockCount" + 3200 - 1) / 3200) AS "BlocklistHashCountExpected", CASE WHEN "G"."BlocklistHashCount" IS NULL THEN 0 ELSE "G"."BlocklistHashCount" END AS "BlocklistHashCountActual" FROM (SELECT "BlocksetID", COUNT(*) AS "BlockCount" FROM "BlocksetEntry" GROUP BY "BlocksetID") "N" LEFT OUTER JOIN (SELECT "BlocksetID", COUNT(*) AS "BlocklistHashCount" FROM "BlocklistHash" GROUP BY "BlocksetID") "G" ON "N"."BlocksetID" = "G"."BlocksetID" WHERE "N"."BlockCount" > 1) WHERE "BlocklistHashCountExpected" != "BlocklistHashCountActual") took 00:00:00.047
Jan 16, 2018 5:27 PM: Starting - ExecuteScalarInt64: SELECT COUNT(*) FROM (SELECT * FROM (SELECT "N"."BlocksetID", (("N"."BlockCount" + 3200 - 1) / 3200) AS "BlocklistHashCountExpected", CASE WHEN "G"."BlocklistHashCount" IS NULL THEN 0 ELSE "G"."BlocklistHashCount" END AS "BlocklistHashCountActual" FROM (SELECT "BlocksetID", COUNT(*) AS "BlockCount" FROM "BlocksetEntry" GROUP BY "BlocksetID") "N" LEFT OUTER JOIN (SELECT "BlocksetID", COUNT(*) AS "BlocklistHashCount" FROM "BlocklistHash" GROUP BY "BlocksetID") "G" ON "N"."BlocksetID" = "G"."BlocksetID" WHERE "N"."BlockCount" > 1) WHERE "BlocklistHashCountExpected" != "BlocklistHashCountActual")
Jan 16, 2018 5:27 PM: ExecuteScalarInt64: SELECT Count(*) FROM (SELECT DISTINCT "BlocksetID", "Index" FROM "BlocklistHash") took 00:00:00.000
Jan 16, 2018 5:27 PM: Starting - ExecuteScalarInt64: SELECT Count(*) FROM (SELECT DISTINCT "BlocksetID", "Index" FROM "BlocklistHash")
Jan 16, 2018 5:27 PM: ExecuteScalarInt64: SELECT Count(*) FROM "BlocklistHash" took 00:00:00.000
Jan 16, 2018 5:27 PM: Starting - ExecuteScalarInt64: SELECT Count(*) FROM "BlocklistHash"
Jan 16, 2018 5:27 PM: ExecuteReader: SELECT "CalcLen", "Length", "A"."BlocksetID", "File"."Path" FROM ( SELECT "A"."ID" AS "BlocksetID", IFNULL("B"."CalcLen", 0) AS "CalcLen", "A"."Length" FROM "Blockset" A LEFT OUTER JOIN ( SELECT "BlocksetEntry"."BlocksetID", SUM("Block"."Size") AS "CalcLen" FROM "BlocksetEntry" LEFT OUTER JOIN "Block" ON "Block"."ID" = "BlocksetEntry"."BlockID" GROUP BY "BlocksetEntry"."BlocksetID" ) B ON "A"."ID" = "B"."BlocksetID" ) A, "File" WHERE "A"."BlocksetID" = "File"."BlocksetID" AND "A"."CalcLen" != "A"."Length" took 00:00:00.334
Jan 16, 2018 5:27 PM: Starting - ExecuteReader: SELECT "CalcLen", "Length", "A"."BlocksetID", "File"."Path" FROM ( SELECT "A"."ID" AS "BlocksetID", IFNULL("B"."CalcLen", 0) AS "CalcLen", "A"."Length" FROM "Blockset" A LEFT OUTER JOIN ( SELECT "BlocksetEntry"."BlocksetID", SUM("Block"."Size") AS "CalcLen" FROM "BlocksetEntry" LEFT OUTER JOIN "Block" ON "Block"."ID" = "BlocksetEntry"."BlockID" GROUP BY "BlocksetEntry"."BlocksetID" ) B ON "A"."ID" = "B"."BlocksetID" ) A, "File" WHERE "A"."BlocksetID" = "File"."BlocksetID" AND "A"."CalcLen" != "A"."Length"
Jan 16, 2018 5:27 PM: ExecuteReader: SELECT "Key", "Value" FROM "Configuration" took 00:00:00.000
Jan 16, 2018 5:27 PM: Starting - ExecuteReader: SELECT "Key", "Value" FROM "Configuration"
Jan 16, 2018 5:27 PM: ExecuteReader: SELECT "Key", "Value" FROM "Configuration" took 00:00:00.000
Jan 16, 2018 5:27 PM: Starting - ExecuteReader: SELECT "Key", "Value" FROM "Configuration"
Jan 16, 2018 5:27 PM: ExecuteScalarInt64: SELECT COUNT(*) FROM "Block" WHERE "Size" > ? took 00:00:00.033
Jan 16, 2018 5:27 PM: Starting - ExecuteScalarInt64: SELECT COUNT(*) FROM "Block" WHERE "Size" > ?
Jan 16, 2018 5:27 PM: ExecuteReader: SELECT "Key", "Value" FROM "Configuration" took 00:00:00.000
Jan 16, 2018 5:27 PM: Starting - ExecuteReader: SELECT "Key", "Value" FROM "Configuration"
Jan 16, 2018 5:27 PM: ExecuteReader: SELECT "Key", "Value" FROM "Configuration" took 00:00:00.000
Jan 16, 2018 5:27 PM: Starting - ExecuteReader: SELECT "Key", "Value" FROM "Configuration"
Jan 16, 2018 5:27 PM: ExecuteScalarInt64: INSERT INTO "Operation" ("Description", "Timestamp") VALUES (?, ?); SELECT last_insert_rowid(); took 00:00:00.010
Jan 16, 2018 5:27 PM: Starting - ExecuteScalarInt64: INSERT INTO "Operation" ("Description", "Timestamp") VALUES (?, ?); SELECT last_insert_rowid();
Jan 16, 2018 5:27 PM: Starting - Running Backup

**Comment by arxcode** [comment]
I seem to have the exact same issue. Backup was working fine, but not it hangs at "Starting backup..." with the following  log entries:

```
6. Febr. 2019 10:29: Starting - ExecuteScalarInt64: SELECT COUNT(*) FROM "Block" WHERE "Size" > 102400
6. Febr. 2019 10:29: ExecuteReader: SELECT "Key", "Value" FROM "Configuration" took 0:00:00:00.000
6. Febr. 2019 10:29: Starting - ExecuteReader: SELECT "Key", "Value" FROM "Configuration"
6. Febr. 2019 10:29: ExecuteReader: SELECT "Key", "Value" FROM "Configuration" took 0:00:00:00.000
6. Febr. 2019 10:29: Starting - ExecuteReader: SELECT "Key", "Value" FROM "Configuration"
6. Febr. 2019 10:29: ExecuteScalarInt64: INSERT INTO "Operation" ("Description", "Timestamp") VALUES ("Backup", 1549466975); SELECT last_insert_rowid(); took 0:00:00:00.002
6. Febr. 2019 10:29: Starting - ExecuteScalarInt64: INSERT INTO "Operation" ("Description", "Timestamp") VALUES ("Backup", 1549466975); SELECT last_insert_rowid();
6. Febr. 2019 10:29: Starting - Running Backup
6. Febr. 2019 10:29: The operation Backup has started
6. Febr. 2019 10:29: No certificates found, you can install some with one of these commands: cert-sync /etc/ssl/certs/ca-certificates.crt #for Debian based systems cert-sync /etc/pki/tls/certs/ca-bundle.crt #for RedHat derivatives curl -O https://curl.haxx.se/ca/cacert.pem; cert-sync --user cacert.pem; rm cacert.pem #for MacOS Read more: http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync
6. Febr. 2019 10:29: Server has started and is listening on 127.0.0.1, port 8200

```

I am running Duplicati 2.0.4.5_beta_2018-11-28 on MacOS X Mojave. Unfortunately, I have both upgraded Duplicati to the newest beta release and MacOS X to Mojave, so I don't really know whether this problem is related to the new Duplicati version or to the Mojave upgrade (or to something else entirely).

I have also followed the workaround in #3403 and enabled Full Disk Access for Duplicati, but this does not seem to help for this specific problem.

I am backing up my home folder and some other folders to a remote server via SSH. Let me know if there is anything else that I could provide that would help with this. Thanks for this otherwise great backup tool!

**Comment by arxcode** [comment]
Sorry, I think at least for my case this did not seem to be a real issue but just a matter of waiting long enough... After I ran Duplicati again, after about half a day at this stage it continued with the backup and it seems to have completed now. Sorry for the wrong report!

**Comment by ts678** [comment]
The @arxcode slowdown at `SELECT COUNT(*) FROM "Block" WHERE "Size" > 102400` was probably improved by this change:

[Add indices to Block table to improve query performance #4171](https://github.com/duplicati/duplicati/pull/4171)

> The index on Block.Size improves the performance of the [query](https://github.com/duplicati/duplicati/blob/v2.0.5.104-2.0.5.104_canary_2020-03-25/Duplicati/Library/Main/Database/LocalDatabase.cs#L723) that checks that the user has not altered the block size of the backup configuration.

The @denniskrol original report of

> Jan 16, 2018 5:27 PM: Starting - ExecuteScalarInt64: SELECT COUNT(*) FROM "File" WHERE "BlocksetID" != ? AND "BlocksetID" != ? AND NOT "BlocksetID" IN (SELECT "BlocksetID" FROM "BlocksetEntry")

https://github.com/duplicati/duplicati/blob/8ac6affd2a171710b3172e646a99f3fadd7ae3d7/Duplicati/Library/Main/Database/LocalDatabase.cs#L789-L790

which is one component of the VerifyConsistency safety check at backup startup before backup changes are actually allowed in.

[Add operation phase for verifying database consistency #4671](https://github.com/duplicati/duplicati/issues/4671) has a pull request that isn't quite processed yet.

[Add operation phase for verifying database consistency](https://github.com/Jojo-1000/duplicati/commit/082ca492ff14ef31d22995dfabaf2d1098ddfaec) that might be incomplete or filed incorrectly, but the comment explains:

> The verify consistency step can take some time. Add a separate step for it, because otherwise starting backup is shown which can be confusing.

Any recent test data? Can this close now?

**Comment by denniskrol** [comment]
I haven't had this issue for a long time. I don't remember how I 'fixed' it
Can be closed, as far as I'm concerned
