### ISSUE TITLE
Can't change hibernation pause

### ISSUE THREAD

**Issue by jpschewe** [duplicati/duplicati#2969]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Linux
- **Backend**: Nextcloud/webdav

## Description

One I set the pause after hibernation setting I can no longer unset it.

## Steps to reproduce

1. Set the pause after hibernation value
2. Try to unset it

**Comment by Pectojin** [comment]
Oh, this sounds familiar. This was resolved with #2733 but that's isn't included in 2.0.2.1
