### ISSUE TITLE
Problems with name resolution on all backups

### ISSUE THREAD

**Issue by jpschewe** [duplicati/duplicati#2972]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Linux
- **Backend**: Nextcloud/webdav

## Description

I setup a backup job to reference my webdav server and it worked great for a couple of weeks. Starting about a week ago I started getting errors and they all say NameResolutionFailure. I checked and the hostname properly resolves. 

Is there a way to get more details on what host the server is trying to talk to? Perhaps my settings got corrupted? The UI still shows the correct host address.

I'm running duplicati as a service on Linux.

```
Operation List with file  attempt 5 of 5 failed with message: Error: NameResolutionFailure
System.Net.WebException: Error: NameResolutionFailure
  at Duplicati.Library.Main.BackendManager.List () [0x00038] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x0000d] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x00000] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend, System.String protectedfile) [0x00066] in <118ad25945a24a3991f7b65e7a45ea1e>:0 
```

## Debug log

Turning on the live logging at level Information shows the following error:
```
{"ClassName":"System.Net.WebException","Message":"Error: NameResolutionFailure","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () [0x0004d] in <1cb5198b00f34ae59d97ee7fe7a3a16c>:0 \n at Duplicati.Library.Utility.AsyncHttpRequest.GetRequestStream (System.Int64 contentlength) [0x0007f] in <1cb5198b00f34ae59d97ee7fe7a3a16c>:0 \n at Duplicati.Library.Backend.WEBDAV.List () [0x0004a] in <fce6c1cbe34c4991be07b95fa0e7a551>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Duplicati.Library.Utility"}
```

**Comment by jpschewe** [comment]
I just tried version 2.0.2.16 and I get the same error.

**Comment by jpschewe** [comment]
I ran into this again. 2 days ago I put my laptop to sleep while a backup was running. The next day the backup failed to run with the name resolution error. I restarted the service and it still won't run. The error message doesn't show a hostname being looked up, so I'm wondering if the service no longer knows which host to connect to. That information is still in the Backup table though.

```
{"ClassName":"System.Net.WebException","Message":"Error: NameResolutionFailure","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () [0x0004d] in <1cb5198b00f34ae59d97ee7fe7a3a16c>:0 \n  at Duplicati.Library.Utility.AsyncHttpRequest.GetRequestStream (System.Int64 contentlength) [0x0007f] in <1cb5198b00f34ae59d97ee7fe7a3a16c>:0 \n  at Duplicati.Library.Backend.WEBDAV.List () [0x0004a] in <fce6c1cbe34c4991be07b95fa0e7a551>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"Duplicati.Library.Utility"}
```

I then went back through the settings for the backup job. When I got to the destination I clicked test connection and got the name resolution error. I cleared the hostname and typed it in again, then tried test connection and it worked. So either the settings are messed up or the name resolution error is cached somewhere.

**Comment by Pectojin** [comment]
You can try working around the issue by changing DNS servers in /etc/resolv.conf or alternatively defining the DNS entry in /etc/hosts.

The error is happening all the way down in the C# `WebRequest` library, which usually doesn't have problems unless there's an underlying issue on the machine.

**Comment by jpschewe** [comment]
However the machine running duplicati can lookup the host just fine. So I don't see how changing the DNS or hosts entries would help. This issue is really isolated to the duplicati process.

**Comment by Pectojin** [comment]
I know the workarounds don't seem very logical, but changing the WebRequest library is kind of tricky as it's a C# core library. If it has issues they would need to be solved in the mono/C# implementation and it has to be possible to replicate the issue. 

I'm not sure how else I can help since I can't replicate the issue and I can't find any articles about the WebRequest library having on going issues with DNS resolution.

**Comment by jpschewe** [comment]
Is there a way to force the library to refresh it's cache? It is acting like the library is caching a DNS failure from when my laptop is offline. Adding the host to /etc/hosts appears to have allowed the job to start again. Next time it hangs I'll try taking the entry out and see what happens.

**Comment by Pectojin** [comment]
If it's cached inside the library then we might be able to handle the issue by forcing it to reset it's cache and try again on failures. Or alternatively we could periodically clear the cache, if it doesn't already.

**Comment by jpschewe** [comment]
Perhaps just setting the cache policy would take care of it. Although these may be more about caching the response to the page.
  * https://msdn.microsoft.com/en-us/library/system.net.webrequest.defaultcachepolicy(v=vs.110).aspx
  * https://msdn.microsoft.com/en-us/library/system.net.webrequest.cachepolicy(v=vs.110).aspx

An article on the aggressive caching done by WebRequest: https://blog.sverrirs.com/2016/04/webrequest-caching-in-csharp.html

Here's a post on how to clear the DNS cache https://stackoverflow.com/questions/7277582/how-do-i-clear-system-net-client-dns-cache

**Comment by kenkendk** [comment]
The `WebRequest` module is over-engineered IMO. It probably makes sense to use pools etc on large-scale deployments, or when running inside a web-service (like ASP.Net), but for a client-only application like Duplicati, there are no real benefits, only problems.

Unfortunately, it is very entrenched in .Net and all libraries use it, so even if I were to add my own `HttpClient`, all the libraries (S3, GDrive, etc) would still use the built-in. And there are no mechanisms to provide an alternative implementation, aside from building the entire .Net framework manually.

**Comment by jpschewe** [comment]
Got this error again yesterday.My laptop was on and connected to the internet, it wasn't sleeping. So not sure what made the WebRequest library unhappy. 
Things I recently tried to solve this:

- I tried touching /etc/resolv.conf (the destination of the sym link acrually) and that didn't help
- I tried swapping the lines in the file (search and nameserver) and that didn't help.
- Touching /etc/hosts took care of the problem.

So it sems that WebRequest can sometimes get into a confused state and causing a file that it checks to be modified fixes the issue. I wonder if forcing a flush of the cache before a backup would also take care of it?

**Comment by Pectojin** [comment]
If it always happens in the backup handler then I suppose we can do a localized cache update on just the backend url.
Something like https://github.com/Pectojin/duplicati/commit/6054b226c680353279ee65cada77ebb88c51d1fe
>            // Force update dns cache for backend url
>            System.Net.Dns.GetHostEntry(backendurl);

Of course this is pretty low level and not very useful it it's happening multiple places in the code. 
But if it's only happening here there is no point doing a bunch of DNS lookups any other place in the code.

**Comment by jpschewe** [comment]
This time here's what I did to get the backup to run, perhaps this will help narrow down there to put the flush.

I tried touching /etc/hosts and /etc/resolv.conf, that didn't fix it. So I went into the settings for the backup job to where I specify the destination. I clicked test connection and got the name resolution failure. I tried changing the hostname and to something incorrect, test connection, then back (test connection) and still same error. I tried changing the port and got an expected error about SSL connection failed. I then changed the port back and got name resolution failure. I just kept clicking test connection and eventually the test passed. After that my backup worked.

**Comment by jpschewe** [comment]
Something else to note, my laptop is connected to the same network via wired and wireless.

**Comment by kenkendk** [comment]
@Pectojin We could add some code to the retry logic:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/BackendManager.cs#L507

If the error is a `NameResolutionFailure`, then we issue the DNS flush?

But the `backendurl` is not required to be a hostname, for instance the S3 backend uses `s3://bucket`, so there might need to be some interface to the backend to ask that to do the flush?

**Comment by jpschewe** [comment]
Here is an old post on StackOverflow that suggests doing the name resolution explicitly and passing the IP to the web request. That seems kind of ugly, but if you make it a method that can be called everywhere, it shouldn't be too bad. 
https://stackoverflow.com/questions/8999616/httpwebrequest-nameresolutionfailure-exception-in-net-with-mono-on-ubuntu

**Comment by Pectojin** [comment]
I've got something, on a test branch, that I think will work well.
https://github.com/Pectojin/duplicati/commits/DNS_resolution_failure
I updated the backend interface to expose a get method for `DNSName`. Then I made the backend manager catch `WebException` and try to resolve the DNS name.

Currently it only works for webdav because all the other backends throw `NotImplementedException`. However, the backend manager will just log a warning and continue as usual.

The biggest problem is, I couldn't figure out how to check if the `WebException` was a `NameResolutionFailure`, so right now it'll check in any `WebException`case.

**Comment by jpschewe** [comment]
Looking at https://social.msdn.microsoft.com/Forums/en-US/5bdeabf9-8b56-4071-bc41-39892e33ec2f/nameresolutionfailure-until-i-restart-application?forum=netfxcompact it seems that you can check kthe status property on the exception to determine if it's a name resolution failure.

**Comment by Pectojin** [comment]
Aaaaah. It wasn't a `WebException` at compile time, so I couldn't check the `Status` field because it's not defined on general exceptions. I have to cast it first.

**Comment by kenkendk** [comment]
The fix from @Pectojin  is now merged, and this will be part of the next canary.

**Comment by Pectojin** [comment]
It should be noted I had no way to verify if this will fix @jpschewe's issue, but it should. Otherwise I do not know what to do :)

Should we use this issue to track implementation for the other, relevant, backends? Or should I create a new issue. I'd like for it to be done eventually, but it didn't seem urgent.

**Comment by Pectojin** [comment]
This should be safe to close with the new canary versions out. @kenkendk even had time to add DNSName code to the other backends.

@jpschewe I hope it helps with your DNS issues :)

**Comment by ldb1619** [comment]
Installed duplicati on a Netgear ReadyNAS102, which had debian wheezy, ran into this problem. Updated the OS to latest jessie version form Netgear, updated duplicati to latest canary, all to no avail.
As a workaround I thought to install on a raspberry Pi and attach that somewhere in the network, but same errors:

~~~
System.Net.WebException: Error: NameResolutionFailure
  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () [0x0004d] in <0828ce86ffa94a4bbbb2da4331bcc67b>:0 
  at Duplicati.Library.Utility.AsyncHttpRequest.GetRequestStream (System.Int64 contentlength) [0x0007f] in <0828ce86ffa94a4bbbb2da4331bcc67b>:0 
  at Duplicati.Library.Backend.WEBDAV.ListWithouExceptionCatch () [0x0004a] in <ec9f949b0df54518b0942b8af2b00a3f>:0 
  at Duplicati.Library.Backend.WEBDAV.List () [0x00000] in <ec9f949b0df54518b0942b8af2b00a3f>:0 
~~~

Been looking around on the net, seen this error also in xamarin-forums. Since i also saw some reference to xamarin, when installing mono/duplicati might this be the same problem?
Seems to be solved to give permission to INTERNET in some Android-Manifest.
Could not find it here (of course), but could this be related to permissions??
Tested the Pi here in the local network, works with the IP instead of a fqdn.
IP-address is not an option when I am going to run this thing on the internet, so still trying to find the solution.

**Comment by jpschewe** [comment]
I've made 2 changes since this occurred. One is to update duplicati to 2.0.3.3-1. The second is to update mono to 5.12.0.226.

**Comment by ldb1619** [comment]
I now have this working:

~~~
ServerVersion : 2.0.3.6
ServerVersionName : - 2.0.3.6_canary_2018-04-23
ServerVersionType : Canary
StartedBy : Server
BaseVersionName : 2.0.3.6_canary_2018-04-23
DefaultUpdateChannel : Canary
DefaultUsageReportLevel : Information
ServerTime : 2018-05-30T19:45:38.909434+02:00
OSType : Linux
DirectorySeparator : /
PathSeparator : :
CaseSensitiveFilesystem : true
MonoVersion : 5.12.0.226
MachineName : NetgearNAS
~~~

Will see what it does when it goes into scheduled backups, and hope I will not encounter too many bugs :-)

Thanks so far.

**Comment by njfox** [comment]
Not sure if related, but I just started getting NameResolutionErrors backing up to Amazon Cloud Drive on Arch Linux. Manually going to edit configuration and clicking "Test Connection" seems to have resolved it for now.
