### ISSUE TITLE
Show current Up/Download speed in Webinterface

### ISSUE THREAD

**Issue by Skaronator** [duplicati/duplicati#2973]
- [x] Github Search is a pain but I didn't found a issue for this
----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Docker, Debian 9
- **Backend**: Google Drive

## Description

Would be good to show the current upload and download speeds in the webinterface.

## Screenshots
Something like this:
![image](https://user-images.githubusercontent.com/2886913/35197730-0c6ce70a-fee4-11e7-9430-d9ad458931c6.png)

**Comment by Pectojin** [comment]
This was added a while ago, but probably after the august beta. It's in my Canary version, so as soon as that goes into beta you'll have it.

<img width="722" alt="screen shot 2018-01-21 at 21 00 48" src="https://user-images.githubusercontent.com/1561484/35198385-73591588-feee-11e7-95b7-9f37645c5096.png">

**Comment by Skaronator** [comment]
Oh.. awesome!

It'd good if the latest beta release is not so old to get faster feedback on bugs or new features.
