### ISSUE TITLE
Force schedule pause or end backup time or schedule throttle download/upload to save bandwidth during work day

### ISSUE THREAD

**Issue by vlepetit** [duplicati/duplicati#2980]
Hi,

Can i Force schedule pause or end backup time or schedule throttle download/upload to save bandwidth during work day.

And if is not possible at this time, this function could be integrated in futur update ?

Regards,
vlepetit

**Comment by Pectojin** [comment]
There is a feature request for scheduled bandwidth throttle here #2980, but not much activity on it yet.

I'd say it's going to be integrated eventually, but I haven't seen much progress on it yet.

**Comment by warwickmm** [comment]
Closing this in favor of:
* Issue #2921 (limit bandwidth during certain times)
* Issue #611 (pause backup during certain times)
