### ISSUE TITLE
SFTP (SSH) [Test Connection] button does nothing. [Save] button does nothing, throws javascript exception. Cannot create new backup for SSH storage.

### ISSUE THREAD

**Issue by pbnelson** [duplicati/duplicati#2982]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.17_canary_2018-01-23
- **Operating system**: Linux Mint 18.3, kernel 4.13.0-31
- **Browser**: Chrome 63.0.3239.132
- **Backend**: Linux Mint 18.3, kernel 4.4.0-104 (separate server)

## Description

_tldr; there's a javascript bug in this version that breaks ssh setup and quite possibly other things as well, see the end of this report for a hack/workaround_

I am trying and failing to setup a new backup having Storage Type "SFTP (SSH)". I know I have all the parameters setup properly as I can get it working from the command line interface. But even when I enter identical parameters in the web interface and click the [Test Connection] button, nothing happens. If I ignore that glitch and proceed to the final setup screen and click the [Save] button, nothing happens. 

In short, there seems to be no way to save the SSH configuration. I tried to hack it by exporting a local file system backup's configuration, editing the JSON to change all parameters to ssh, then creating a new backup by importing the edited JSON. This fails in the same way - that is, it forces me to use the web interface to complete the setup, the [Test connection] button does nothing, and on the final page the [Save] button does nothing.

This does not seem related to the "Missing XSRF Token" bug because A) I didn't get that message, B) I refreshed the page anyway, just to be sure, and C) if I change the "Storage Type" to something else like local storage the [Test connection] and [Save] buttons immediately start working.

I do have other backups setup and working well using a samba server with cifs shares auto-mounted to my local file system. But having gotten that to work I wanted to see if SSH could be used instead, as a simpler and more secure approach. I did manage to get it working under 2.0.2.1 back in September, but have since reformatted that computer so I can't export/import from there to test it. I have not tried reverting my current setup to 2.0.2.1 because, well, even if it did work I'd still want to write up this bug report for 2.0.2.17.

## Steps to reproduce

Try to setup an SSH storage type backup destination, like this:

![image](https://user-images.githubusercontent.com/7568782/35452078-09321402-028b-11e8-8987-9303f7fef6a0.png)

<br>--------------------------------------<br>

![image](https://user-images.githubusercontent.com/7568782/35452141-33de04b8-028b-11e8-9ef0-7645a52d6d85.png)

1. Click [Test connection] and nothing happens
2. Ignore that, proceed with setup, click [Save] and nothing happens

- **Expected result**:
Using the same server/key/password from the command line I get successful backup. Here's what works:

```duplicati-cli backup ssh://PE1950A/home/pbnelson/duplicati/foo/ *.ods --no-encryption --verbose --ssh-keyfile=/home/pbnelson/.ssh/id_rsa_newpassword --ssh-fingerprint="ssh-rsa 2048 d8:51:6c:ec:d9:6d:3c:b5:a1:b2:e2:fc:18:cd:f2:a8" --auth-password=neverusespecialcharacters --auth-username=pbnelson```

```Input command: backup
Input arguments: 
	ssh://PE1950A/home/pbnelson/duplicati/foo/
	Untitled 1.ods

Input options: 
no-encryption: 
verbose: 
ssh-keyfile: /home/pbnelson/.ssh/id_rsa_newpassword
ssh-fingerprint: ssh-rsa 2048 d8:51:6c:ec:d9:6d:3c:b5:a1:b2:e2:fc:18:cd:f2:a8
auth-password: neverusespecialcharacters
auth-username: pbnelson

Backup started at 1/26/2018 11:23:29 AM
Checking remote backup ...
  Listing remote folder ...
Scanning local files ...
Including source path: /home/pbnelson/Untitled 1.ods
  1 files need to be examined (19.22 KB)
Skipped checking file, because timestamp was not updated /home/pbnelson/Untitled 1.ods
  0 files need to be examined (0 bytes)
removing temp files, as no data needs to be uploaded
Checking remote backup ...
  Listing remote folder ...
Verifying remote backup ...
Remote backup verification completed
  Downloading file (524 bytes) ...
  Downloading file (611 bytes) ...
  Downloading file (19.90 KB) ...
DeletedFiles: 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 1
OpenedFiles: 0
AddedFiles: 0
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 0
SizeOfExaminedFiles: 19683
SizeOfOpenedFiles: 0
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
ParsedResult: Success
VerboseOutput: True
VerboseErrors: False
EndTime: 1/26/2018 11:23:31 AM (1516987411)
BeginTime: 1/26/2018 11:23:29 AM (1516987409)
Duration: 00:00:01.9817690
Messages: []
Warnings: []
Errors: []Backup completed successfully!
```

## Debug log
There are no log entries, either under "Stored" or under "Live" set to log level "Warning" or to log level "Profiling"

However! thinking about debug logs got me to check the Chrome javascript console, and I discovered the source of the problem. _Too bad I didn't do that before all my diagnostics, but, hey, now I know a lot more about the command line interface, and y'all have an example of a working ssh command line backup._

The Chrome javascript console shows this error, half a dozen times. Every click of [Test connection] throws a new one. Likewise, every click of the [Save] button throws the same error.

```
TypeError: EditUriBackendConfig.require_username is not a function
    at Object.EditUriBackendConfig.validaters.ssh (EditUriBuiltins.js:644)
    at builduri (backupEditUri.js:26)
    at n.$scope.testConnection (backupEditUri.js:247)
    at fn (eval at compile (angular.js:13145), <anonymous>:4:233)
    at f (angular.js:23298)
    at n.$eval (angular.js:15846)
    at n.$apply (angular.js:15945)
    at HTMLAnchorElement.<anonymous> (angular.js:23303)
    at HTMLAnchorElement.dispatch (jquery.min.js:3)
    at HTMLAnchorElement.r.handle (jquery.min.js:3)
```

## SOLUTION (WORKAROUND)

Use the Chrome JS Console to edit line 644 of `EditURiBuiltins.js` to read `EditUriBackendConfig.require_username_and_password(scope);` and save changes. Now the [Test connection] and [Save] buttons will work fine.

I was going to issue a pull request, but I see that someone has already added the `require_username` function to `EditUriBackendConfig.js` in the master branch, so there's no need. The ultimate solution would be for the leaders of this project to release a new version containing this fix. 

In the meantime I am submitting this issue anyway, so others who are having this problem can see a workaround/hack, and not waste any more time on it.

**Comment by pbnelson** [comment]
I forgot to mention that in order to get a clean SSH connection from the command line I also had to install a package that was apparently missing from the linux mint (i.e. ubuntu, i.e. debian) package dependency list.

```
sudo apt-get install ca-certificates-mono
```

Despite the error message I got from the command line, after installing that package it was *not* necessary to run ~`cert-sync /etc/ssl/certs/ca-certificates.crt`~

**Comment by Pectojin** [comment]
I'm not quite sure I understand. 

The `require_username` function has been in the code for 4 months and was first released in v2.0.2.8_canary. Additionally line 644 of `EditURiBuiltins.js` is blank, adding to my confusion.

**Comment by pbnelson** [comment]
It started working for me, now, all by itself. At this time my line 644 of EditUriBuiltins.js still shows require_username()

![image](https://user-images.githubusercontent.com/7568782/35478968-98dad1b8-03b0-11e8-8c9f-d8dc02f16591.png)

But line 113 of EditUriBackendConfig.js now defines the require_username() function, unlike yesterday

![image](https://user-images.githubusercontent.com/7568782/35478978-bf7160d0-03b0-11e8-9c14-512162e9a53a.png)

And just to confirm the version I'm running

![image](https://user-images.githubusercontent.com/7568782/35479027-04bfc626-03b2-11e8-95bd-80397781a435.png)

If I had to guess, I'd say that yesterday my browser was serving up some old cached 2.0.2.1 pages along with the new 2.0.2.17 pages. I can't prove this, however, because it has started working for me. Mind you, I certainly did refresh the page and close/reopen the browser any number of times. But I did *not* try explicitly clearing the browser cache. I'm an angular developer myself, and I've seen this happen once before, so I know it's at least a theoretical possibility. 

If anyone else sees this bug, my advice is to try clearing the cache, by going to chrome://settings/clearBrowserData and clearing `Cached images and files`

![image](https://user-images.githubusercontent.com/7568782/35479045-7e77bda2-03b2-11e8-940c-5253752caa44.png)

**Comment by kenkendk** [comment]
I have seen a few of such related issues, so I think we really need to fix the browser cache issues.

**Comment by Pectojin** [comment]
A solution might be to append the version number as a query string on each request.
>http://localhost:8200/ngax/scripts/controllers/EditURiBuiltins.js?version=2.0.2.17

That would still give caching benefits, but you'd have to reload every element once after upgrading Duplicati.

I was looking into implementing this by doing a string replace on a placeholder in the index file as it's served by the HttpServer in C#. I got it to work on the `webroot/index.html` file, but then I realized all the files are loaded inside the `webroot/[theme]/index.html` file. 

I'm guessing we'd have to make a similar `IndexHtmlHandler.cs` file for the theme index file in order to override processing of the HttpServer?

**Comment by huste** [comment]
Referencing #2988, I am asking a maybe lame question: Does it make any sense to cache pages in Duplicati at all? Shouldn't there be a no-cache header in any request?

**Comment by Pectojin** [comment]
I think it makes good sense. 

The website is barely a website and more of an application. First load makes around 120 requests for a total of 2.9MB transferred. When cached only 256KB is transferred and it loads nearly twice as fast in my browser.

Majority of this content is only ever changed in new version releases.

**Comment by kenkendk** [comment]
I've just added 9a41cf286712fe025ca07bdc7406eeb672c272d8, which introduces `no-cache` on `index.html` to fix the XSRF errors, and 1241a7747dc6a91bd05dd6809ce7595269701ed3 adds these to all dynamic content, and a 1-day cache for static content.

To really fix it, we should add some on-the-fly rewrite of the "index.html" page, such that it adds the version number to all static resources (could also be done as part of the build process). Then we could set the expiration time to a year or so.

**Comment by Pectojin** [comment]
Uh, that's clever with the index.html caching. Is that 1 down, 3 to go on the experimental milestone?

I guess the 1 day cache is a good remedy, but it would definitely be cool to have version-specific id's on static resources.

**Comment by kenkendk** [comment]
After thinking some more, the real solution is to implement `ETag` support, as the browser will then be able to query the resources and figure out that they are unchanged. Then we can have a 5 second cache and still get good performance.

I have added it to the webserver I plan on using in Duplicati, so once I switch it over, it should just work:
https://github.com/kenkendk/ceenhttpd/commit/591eae37b2ecb4ef202da58a1be5d221f2e5551a

**Comment by warwickmm** [comment]
I believe this has been resolved.  Please feel free to reopen if that's not the case.
