### ISSUE TITLE
retention not there in 2.0.2.17_canary_2018-01-23

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#2988]
Am I too blind to see it? But there isn't any retention policy in the latest 2.0.2.17_canary_2018-01-23 buld that I'm using.
I first thought, maybe it's because I am using the German localization, but switching to English still doesn't show the mentioned options in the backup job's setup.

I can see, that Steve_Hanson1 also mentioned this on https://forum.duplicati.com/t/new-retention-policy-deletes-old-backups-in-a-smart-way/2195/13

**Comment by Pectojin** [comment]
It's there on my install (was on both 2.0.2.17 and 2.0.2.16). 

it's possible it's a caching issue like Tapio seems to indicate.

If you clear your browser cache, use ctrl+F5, or disable the cache using the web tools you should see the option.

**Comment by huste** [comment]
yep, you're right. Strange, as the versoin information is not cached. Thanks, closing the issue

**Comment by Pectojin** [comment]
I think it's a general problem across multiple different reports lately. We were just discussing it on #2982, which seemed to also be caused by stale caches.
