### ISSUE TITLE
DuplicatiVerify.ps1 and false warnings

### ISSUE THREAD

**Issue by mr-flibble** [duplicati/duplicati#2992]
## Description

Hello, I tried Powershell script DuplicatiVerify.ps1 from C:\Program Files\Duplicati 2\utility-scripts

Unfortunately when I tried "big" json file (4MB). I getting this error:
```
Verifying file: duplicati-verification.json
ConvertFrom-Json : Error during serialization or deserialization using the JSON JavaScriptSerializer. The length
 string exceeds the value set on the maxJsonLength property.
Parameter name: input
At E:\DuplicatiVerify_json_lenght.ps1:47 char:59
+     $remoteVolumes = (Get-Content $filename) -Join "`n" | ConvertFrom-Json
+                                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

After some googling, it appears that function ConvertFrom-Json has hardcored 2MB(?) size limit from JSON 

Workaround can be use something like System.Web.Extensions instead of ConvertFrom-Json:
For example:
https://social.technet.microsoft.com/Forums/windows/en-US/833c99c1-d8eb-400d-bf58-38f7265b4b0e/error-when-converting-from-json?forum=winserverpowershell

https://stackoverflow.com/questions/46514512/convertfrom-json-error-during-serialization-or-deserialization-using-the-json?rq=1

Or maybe splitting json file?:-)
Can you please look at this sometimes? Maybe @mnaiman 
Thanks

**Comment by mnaiman** [comment]
Hi, what version of Powershell do you have? I was able now to ConvertFrom-Json 45MB file

**Comment by mr-flibble** [comment]
Hello, I have version 4 on 2012R2

Should I try update to Powershell 5? Thanks

`Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2`

**Comment by mnaiman** [comment]
Please it with higher version, mine is:

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

You can test it from client machine, script dont need Duplicati installed

**Comment by mr-flibble** [comment]
Thanks!
I just update to Powershell 5.1 and problem is gone:-)

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mnaiman** [comment]
I will make new version with #Requires -Version 5.1
This will enforce to use it or throw error.

**Comment by mr-flibble** [comment]
@mnaiman Can you please look also at https://github.com/duplicati/duplicati/issues/2989 ?
