### ISSUE TITLE
IPv6 not working

### ISSUE THREAD

**Issue by dominiqueroux** [duplicati/duplicati#2993]
- [ x] I have searched open and closed issues for duplicates.

## Environment info

- **Duplicati version**: 2.0.2.17
- **Operating system**: Arch Linux
- **Backend**: SFTP (SSH)

## Description

If I try to backup my data using duplicati to an IPv6 only host, I always get the "could not resolve" error.

## Steps to reproduce

1. Add a IPv6 only destination
2. Try to backup

- **Actual result**:
Could not resolve <host>
- **Expected result**:
Backup runs through

## Debug log

> Fatal error
> System.Net.Sockets.SocketException (0x80004005): Could not resolve host 'backup.ungleich.ch'
>   at Duplicati.Library.Main.BackendManager.List () [0x00049] in <4ba6789697e24783ae57b0acf97a6486>:0 
>   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x0000d] in <4ba6789697e24783ae57b0acf97a6486>:0 
>   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x00000] in <4ba6789697e24783ae57b0acf97a6486>:0 
>   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend, System.String protectedfile) [0x000fd] in <4ba6789697e24783ae57b0acf97a6486>:0 
>   at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter) [0x0038b] in <4ba6789697e24783ae57b0acf97a6486>:0 `

**Comment by TekkiWuff** [comment]
This might actually be a bug in Mono.

I've tried it with the latest Mono build 5.8.0.108 and Ubuntu 17.10.1 and got the same error with an IPv6 only host. Apon digging deeper into the Mono source code, I found a test which checks if the host supports IPv6. It looks like it's using some obsolute variable there, which always returns false.

I opened a ticket in the mono project to see what they say about it.
https://github.com/mono/mono/issues/6940

**Comment by greendeath** [comment]
Thanks a lot!

**Comment by ts678** [comment]
[Mono 5.14.0 Release Notes](https://www.mono-project.com/docs/about-mono/releases/5.14.0/)

> #6940 - DNS lookup of IPv6-only hosts fails

I don't know if above description fits your case, but you might try a recent mono (and check `mono --version`) to see if it's OK.

**Comment by warwickmm** [comment]
I think has been fixed in mono.
