### ISSUE TITLE
Improve duration formatting

### ISSUE THREAD

**Issue by gene1wood** [duplicati/duplicati#2997]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Description
The duration feature was added in [2.0.1.17](https://github.com/duplicati/duplicati/issues/1725#issuecomment-221597248) in response to #1725 however the formatting of the duration value is very confusing when the value grows beyond 24 hours.

For example, I just completed a backup that reported

```
Last successful run: Yesterday at 1:56 PM (took 1.01:46:55.139231)
```

I believe this means that the backup took
```
1.01 days
46 minutes
55.139231 seconds
```

but I could be wrong. This backup definitely took well over `1.01` hours.

If it means 1.01 days then I guess `0.01` days is the same as `46 minutes`?

Anyhow, I think this should be changed to

* Not display milliseconds. This is just confusing. Nobody needs to know how many milliseconds a backup took
* All fields should be integers. A time field of `1.01` is confusing
* For durations over 1 day, continue to display in hours until some threshold like 3 days (or something). For example display `30:22:15` instead of `1.3:22:15` (if that's even what it would currently display)
* When the duration exceeds that threshold display in a format like `3 days and 3 hours` and put the raw exact time in `hours:minutes:seconds` as a tooltip mouseover text

It looks like currently the [`LastDuration` value is rendered from the `Direction` attribute using the `ToString` method](https://github.com/duplicati/duplicati/blob/79d67ed3cdfeaaead4e84439c76317cf27deb12c/Duplicati/Server/Runner.cs#L715
). I believe this is where the change would need to happen (which I would PR if I wrote C# but I don't)

## Steps to reproduce
1. Do a backup that takes more than a few hours, maybe over a day

- **Actual result**:
A value like `1.01:46:55.139231` is displayed

- **Expected result**:
A value like `36:46:55` should be displayed

## Screenshots

[Screenshot of how it's displayed](https://screenshots.firefox.com/TNs2aNfQMqGGH8Y9/eva.duplicati)

**Comment by Pectojin** [comment]
What version are you running? It looks old

This is what it looks like in 2.0.2.17
![screen shot 2018-02-01 at 22 37 39](https://user-images.githubusercontent.com/1561484/35704707-a596b720-07a0-11e8-8516-ac813f54300c.png)
Lucky coincidence that it took 10 min and 10 sec

**Comment by gene1wood** [comment]
I'm on `Duplicati - 2.0.2.1_beta_2017-08-01` which I believe is the current version on the [download page](https://www.duplicati.com/download)

@Pectojin I think the reason it looks good to you is the short run time. When I do backups that run for less than an hour they also display well. It's only when they run for a day like this one that I get this output.

**Comment by Pectojin** [comment]
Ah, funny. It's an issue with the `formatDuration` function in the frontend, no C# required :)

What you got is a C# timespan, as it's stored in the database. Because C# timestamp has the syntax `[d’.’]hh’:’mm’:’ss[‘.’fffffff]` the frontend can't "parse" the days so it just passes it along.

When i say parse, I mean it tries to strip the miliseconds. Which works perfectly as long as no backup takes more than 24 hours.

I have a fix that parses it like this:
![screen shot 2018-02-01 at 23 46 54](https://user-images.githubusercontent.com/1561484/35707522-5cbabef2-07aa-11e8-8a72-927f0a1104c9.png)
It handles timespans up to around 114 years long, if your backup takes longer consult your computer doctor.
