### ISSUE TITLE
v2.0.2.17 (64 bit) not starting on Win10

### ISSUE THREAD

**Issue by BurninLeo** [duplicati/duplicati#3009]
- **Duplicati version**: 2.0.2.17 (canary_2018-01-23) 64bit
- **Operating system**: Windows 10 (64 bit)
- **Backend**: SFTP

## Description

After setting up the canary version (64 bit version), an running "Duplicati.GUI.TrayIcon.exe", the process starts (accorting to Process Explorer), and opens some child-processes, but then vanishes.

I cannot find any error log so far. The `Duplicati-server.sqlite` requires a password to open, so I cannot check that for further information.

After removing the 64 bit version, and setting up the 32 bit version, Duplicati 2 starts as expected.

**Comment by ts678** [comment]
Does this happen on a recent version?

> I cannot find any error log so far.

[Duplicati.GUI.TrayIcon.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/) shows how to set log using the `--log-file` and `--log-level` options.

> The Duplicati-server.sqlite requires a password to open

Use the `--unencrypted-database` option, but I don't know if there would be anything interesting...
