### ISSUE TITLE
Error Msg: "Failed to enumerate Hyper-V virtual machines: Invalid class"

### ISSUE THREAD

**Issue by vegar** [duplicati/duplicati#3012]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.17_canary_2018-01-23
- **Operating system**: Windows 10 Enterprise 1709, 64bit
- **Backend**: SFTP (SSH)

## Description

I've done two changes lately, and I'm not 100% sure which one changed the behavior.
I've updated to new canary version (I *think* my prev version was 2.0.2.13_canary_2017-11-22), and I've started running duplicati as a service.

Whenever I edit the backup profile, I get the following error message:

> Failed to enumerate Hyper-V virtual machines: Invalid class

Hyper-v is not installed on my computer.

## Steps to reproduce

1. Open duplicati web page
2. Expand backup configuration
3. Click `Edit...` link

- **Actual result**:
Error message pops up
- **Expected result**:
No error was expected

## Screenshots

![image](https://user-images.githubusercontent.com/764517/35908846-1b3224f6-0bf2-11e8-99fb-1576b7dd640c.png)

**Comment by mael2** [comment]
I got the same error after running the first backup with the option to turn on VSS snapshot-policy=required and running the EXE with admin privileges. When entering the configuration of a backup set the message appears.

**Comment by mael2** [comment]
Hi @mnaiman 
I tried to start the server with these command line options:
 --log-level=Profiling --log-file=C:\duplicati.log
But the logfile doesn't fill with with actions from the browser.
Is there a way to enable debugging of the webserver itself?

Anyway, the browser console shows this error:

`HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request. (XHR)GET - http://localhost:8200/api/v1/hyperv`

Does this help?`
Let me know if I can try something different.
Note that this is only a minor issue as everything else still works.

**Comment by mnaiman** [comment]
Can you open in one tab "logging feature of GUI" set to profiling and in other tab perform this step to produce error. It should log to GUI.

**Comment by mael2** [comment]
with the latest release version, I got this when entering the configuration:
```
Mar 25, 2018 1:03 PM: Using WMI provider \\localhost\root\virtualization\v2
Mar 25, 2018 1:03 PM: Cannot find any MS SQL Server instance. MS SQL Server is probably 
```

I tried **v2.0.3.1-2.0.3.1_experimental_2018-03-16** but it crashes on startup (service and also GUI):

Faulting application name: Duplicati.Server.exe, version: 2.0.3.1, time stamp: 0x5aab7cf6
Faulting module name: KERNELBASE.dll, version: 10.0.16299.334, time stamp: 0x6369e29f
Exception code: 0xe0434352
Fault offset: 0x0000000000014008
Faulting process id: 0x2a94
Faulting application start time: 0x01d3c42819fe3dce
Faulting application path: C:\Program Files\Duplicati 2\Duplicati.Server.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c72a00cf-fcb0-4826-9499-915eb6854a82
Faulting package full name: 
Faulting package-relative application ID: 



Faulting application name: Duplicati.GUI.TrayIcon.exe, version: 2.0.3.1, time stamp: 0x5aab7cf8
Faulting module name: KERNELBASE.dll, version: 10.0.16299.334, time stamp: 0x6369e29f
Exception code: 0xe0434352
Fault offset: 0x0000000000014008
Faulting process id: 0x3680
Faulting application start time: 0x01d3c42838f5375e
Faulting application path: C:\Program Files\Duplicati 2\Duplicati.GUI.TrayIcon.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 674537ae-848a-454e-9047-2186e2790d67
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mnaiman** [comment]
Thats the problem, you have there something which should not be there.
This key is present only if you have Hyper-V installed.

**Comment by vegar** [comment]
Are you saying that
* duplicati doesn't work if you have hyper-v installed, or
* duplicati thinks I have hyper-v installed and tries to use it for something?

I do currently not have hyper-v installed. I did, though, at some point earlier (long before starting with duplicati). 

![image](https://user-images.githubusercontent.com/764517/37953050-0a47a0e6-31a2-11e8-9a6a-3d838390d30e.png)

**Comment by mnaiman** [comment]
That is weird.
I tried to install and uninstall Hyper-v and root\virtualization\v2 was installed and uninstalled.
Can you install it and uninstall to see if it disappear?

Before that please click on root\virtualization\v2 if some classes will be listed.

To your questions:
Duplicati works well with Hyper-v installed in fact backup of hyperv is supported feature of Duplicati
Yes, it thinks that you have hyper-v installed even if it is not, because of this root\virtualization\v2 provider which should be uninstalled when hyper-v is uninstalled.

**Comment by jmclaren7** [comment]
I'm seeing the same thing on a 2008R2 machine which has previously had the Hyper-V role installed but was uninstalled at some point (I think before Duplicati was ever installed). For me the key I see is just root\virtualization\ms_409 but I assume that the v2 is missing because this is 2008R2

**Comment by mnaiman** [comment]
yes, v2 missing because of 2008
can you list classes in root\virtualization? searching for way how to detect, that hyper-v is uninstalled on those "partial uninstalled" systems.

**Comment by jmclaren7** [comment]
I'm not very familiar with this but it seems In my case, the only classes that exist in ROOT\virtualization or ROOT\virtualization\ms_409 are many "System Classes" (hidden by default) but no other types. The system classes that appear all start with "__",  let me know if these are relevant and I will post them if needed.

**Comment by mnaiman** [comment]
@vegar 
@jmclaren7 
Please post screenshot what you can see as classes under ROOT\virtualization or \root\virtualization\v2

**Comment by vegar** [comment]
![image](https://user-images.githubusercontent.com/764517/41942511-fa83b92e-799f-11e8-839e-2949a70c9c8e.png)

**Comment by mnaiman** [comment]
![image](https://user-images.githubusercontent.com/2264442/41942735-d9321184-79a0-11e8-8fce-80e2ad6fc27d.png)
this is how it should look like, in my case when hyper-v role is installed - 281 classes (excluding system)

**Comment by jmclaren7** [comment]
@mnaiman I did, the grey (or blue if the windows is active) is currently selected, green just means its been enumerated since the program launched.

@vegar I checked all the options to include class types that are normally hidden, not sure if that matters

**Comment by vegar** [comment]
`\ROOT\virtualization`
https://i.imgur.com/y5yRCIl.png

`\ROOT\virtualization\v2`
https://i.imgur.com/vHvesVu.png

**Comment by mnaiman** [comment]
Ok, so both, If you exclude all - you have zero classes found?

![image](https://user-images.githubusercontent.com/2264442/41942961-e0f4d662-79a1-11e8-9572-6a4351db6ebd.png)

**Comment by jmclaren7** [comment]
Yes, that's my case. Just a reminder my case is with 2008R2 and hyper-v role previously installed and then removed

**Comment by mnaiman** [comment]
I know, if @vegar confirm same thing it means 2 things.
1)Both of you have broken system (probably not properly uninstalled hyper-v role and there are some leftovers).
2)I can prepare check, that if no classes are detected, it will log some complain that system is broken, but will go forward without any error screens.

**Comment by jmclaren7** [comment]
@mnaiman I'm not so sure I have a broken hyper-v role... I did just did a clean install of 2008R2 and 2012R2 (under vmware wokstation with nesting enabled) then added and removed the hyper-v role. On 2008R2 \ROOT\virtualization was still present but empty and on 2012R2 it removed the entire namespace. 

I'm wondering if this is expected behavior for 2008R2... I can test more scenarios/os versions if it would help.

**Comment by vegar** [comment]
I can confirm that there are none classes found when all checkboxes are cleared.
I can confirm that I once had hyper-v installed.
I'm on windows 10 enterprise 1709

**Comment by mnaiman** [comment]
Working on check
can you run this powershell command?

`gwmi -Query "SELECT * FROM meta_class" -Namespace "ROOT\virtualization" | ? { $_.Name.StartsWith("Msvm_") } | measure`

`gwmi -Query "SELECT * FROM meta_class" -Namespace "ROOT\virtualization\v2" | ? { $_.Name.StartsWith("Msvm_") } | measure`

On systems where hyper-v is really installed it should return Count > 0
In your cases it should return Count = 0

**Comment by vegar** [comment]
![image](https://user-images.githubusercontent.com/764517/42002112-6cded69a-7a66-11e8-8174-d0e26968a123.png)

**Comment by mnaiman** [comment]
https://github.com/duplicati/duplicati/pull/3301 fixed in this pull request

**Comment by mnaiman** [comment]
if working pls close issue

**Comment by jmclaren7** [comment]
All good here!

**Comment by vegar** [comment]
I'm not able to test until end of vacation. I put my trust in both of you, though, and close the issue ;-)
