### ISSUE TITLE
File Restore ignores option "Save different versions with timestamp in file name" in the web GUI, restored files are created without time stamp

### ISSUE THREAD

**Issue by hamlet42** [duplicati/duplicati#3043]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: v2.0.2.19-2.0.2.19_canary_2018-02-12
- **Operating system**: Windows 10 Fall Creators Update 1709 16299.248
- **Backend**: ftp backend

## Description
When restoring a file (or several files at once) ticking the option in the GUI ""Save different versions with timestamp in file name" does not lead to that a time stamp is added to the file name of the restored file(s). They are always created with the original file name only.
This is independent of other options like "Restore to original Location" or "Restore to a different file location"

## Steps to reproduce
1. Restore a file with the option ""Save different versions with timestamp in file name" set
2. The file is restored without an added time stamp
3. ...

- **Actual result**:
File is restored without a time stamp added to the file name
- **Expected result**:
file should be restored with an added time stamp in the file name

## Screenshots
n/a

## Debug log
no special log entries are generated. Sometimes a message "... 0 warnings" pops up, but the log shows no warnings or errors

**Comment by Pectojin** [comment]
I *think* the intention may be to create new files with a timestamp in the name if the restored files were going to overwrite existing files.

**Comment by hamlet42** [comment]
When testing this, I also did the restore to the original location where the original file was present. Still nothing was created.

**Comment by hamlet42** [comment]
BTW this is occurring in the latest Canary, Version info was a copy&Paste and not updated

**Comment by TekkiWuff** [comment]
From my understanding of the code, this option really only attaches a timestamp to the filename if there is already a file with the same name in the target folder which is different though.

If you restore for example into an empty folder, there is no "different" version in there which conflicts and the restored file does not get a timestamp. And if you restore into the original folder where exactly the same file (same name, same size, same hash) already exists, then that also does not count as "different" version and duplicati happily reports `Target file exists and is correct version: <filename>`

So technically "Save different versions with timestamp in file name" does exactly what is says, but admittedly I also first thought that it would simply always attach a timestamp, no matter what.

**Comment by Pectojin** [comment]
>exactly the same file (same name, same size, same hash) already exists, then that also does not count as "different" version and duplicati happily reports Target file exists and is correct version: <filename>
I think you're right. In my own testing I can only produce timestamped files if I restore from different versions where I *know* that the file has changed.

**Comment by hamlet42** [comment]
Yes. I retested and it is as TekkiWuff and Pectojin described. I expected that the file is always created, but the implemented solution is more intelligent and makes sense. Alas, no issue, works as designed.

Thx to you two for your help :-)
