### ISSUE TITLE
Disable or fix 7z/LZMA2

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#3054]
This is a placeholder issue to discuss what we should do with the lzma2/7z compression module for the next experimental release.

**Comment by Pectojin** [comment]
Is there a specific issue you had in mind? It seems like there have been *many* different issues with 7z in Duplicati. 

I haven't gotten too much into it, but if it's many issues and we want it to be stable then it might be best to disable it and split into a new branch for testing/fixing 7z until it's ready to be enabled again.

**Comment by kenkendk** [comment]
There are quite a few problems with 7z. @weltkante did a bunch of fixes in this copy:
https://github.com/weltkante/duplicati/tree/lzma-update

But it needs some more work before we can merge it in. I know he also rewrote most of the 7z library, so one better fix would be be to write the 7z module from scratch, but both approaches requires some work.

**Comment by Pectojin** [comment]
I don't think it would be out of place to disable it until we're at a stable state.

**Comment by kenkendk** [comment]
I have implemented a fix in fe7f9cf67a32af00f71526b7a93e3ea5cd6e49e3

**Comment by Pectojin** [comment]
Looks good 👍 
Let's close the issue and ship a release :)

**Comment by Poincare1** [comment]
so ... all previous LZMA issues are resolved and LZMA can be selected as a compression method without problem?
