### ISSUE TITLE
Fix or disable default filters

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#3056]
This is a placeholder issue to discuss specifically what we should do with the default filters.
There are a number of ideas in #3030, but to avoid delaying the experimental release, we should perhaps just change the default in the experimental, such that the filters are not automatically applied.

Alternatively, we remove them completely from the experimental until we decide what to do.

**Comment by Pectojin** [comment]
I think #3052 entirely addresses my concerns for #3030, so I'd vote for *fix* and package #3052 into the experimental release.

**Comment by kenkendk** [comment]
I have a suggestion for what to do with the experimental here: c9be6516904f7e196a22fc2d7e009e90095b5383

**Comment by Pectojin** [comment]
Should we perhaps hide the UI from the frontend as well, @kenkendk?

The major *argument* in #3030 ended up being about how the current UI doesn't let the user know what it does. And displaying non-functioning functionality in the frontend doesn't improve that feel :)

**Comment by renestach** [comment]
We should remove the filters "Windows, Mac, Linux" from the UI and deactivate their functionality. That way we are back to the state of the previous expermimental and nothing surprising will happen with any existing backup.

Afterwards, we should get back to #3030 and get this done.

**Comment by Pectojin** [comment]
I've hidden the default filters from the UI and created a PR into the `duplicati:feature/disable_default_filters` branch.

That should be all we need to close this issue and ship the next experimental release.
