### ISSUE TITLE
Error message when backup interrupted backup by user

### ISSUE THREAD

**Issue by Toto5931** [duplicati/duplicati#3061]
- [ X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Windows
- **Backend**: All

## Description

When the user manually interrupts a backup it leads to an error message "Thread was being aborted.". It shouldn’t be the case. It scares the user whereas everything works well.

## Steps to reproduce

1. Start a backup
2. Stop it before the end by clicking the cross at the right of the status bar
3. You get the error message

- **Actual result**:
 Error message "Thread was being aborted."
- **Expected result**:
Nothing, or confirmation that the interruption has happened

**Comment by Germs2004** [comment]
I agree.  I think Exceptions are for unhandleable situations where the software is broken and doesn't know what it should do.  In this case, the message should be more like "A user clicked the Stop button while a backup job was in progress, so the job was safely aborted."  IMO, a notification email should not be sent to the user about this; just add an entry to the job log.

**Comment by warwickmm** [comment]
Backups interrupted via "Stop now" or "Stop after current file" should be handled more gracefully now.
