### ISSUE TITLE
SSL with FTP does not support unencrypted data channels

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#307]
_From [kenneth....@gmail.com](https://code.google.com/u/117596759558990029378/) on November 25, 2010 00:18:10_

If the FTP server only supports protecting the command channel with SSL, it will issue a response like "534 Fallback to [C]" when the "PROT" command is issued.

According to the Wikipedia page, the thing to do is to send a "CDC" command: http://en.wikipedia.org/wiki/FTPS This should disable SSL on the data channel.

The .Net framework FTP client does not support this, and there appears to be no easy/reliable way to add additional features/commands.

This means that the solution will likely require the use of a thirdparty FTP client.

I have looked at these two: http://www.codeproject.com/KB/macros/ftp_class_library.aspx http://www.codeproject.com/KB/IP/FtpClient.aspx They both look promising (although, I think there is a race in the first one with a streamreader and the socket...).
But it does not look like any of them support SSL...

If anyone knows a workaround or a better library, please let me know.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=307_
##

**Comment by kenkendk** [comment]
Updated list of potential libraries:
https://github.com/higty/higlabo
https://github.com/ArxOne/FTP

**Comment by mylemans** [comment]
Fyi, AlexFTPS isn't flawless, we use it but had to make some changes to make it work on some specific FTP servers.

So don't just use it and expect it to work everywhere ;)

**Comment by renestach** [comment]
https://github.com/duplicati/duplicati/pull/1690 could fix this.

**Comment by warwickmm** [comment]
This should be addressed in #1690.
