### ISSUE TITLE
Backup job database not deleted when deleting job

### ISSUE THREAD

**Issue by Pectojin** [duplicati/duplicati#3072]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.20
- **Operating system**: Ubuntu 16.04 & macOS High Sierra
- **Backend**: Any

## Description

The `Delete the local database` checkbox on the `Delete backup` page does not actually cause the database to be deleted.

I can manually delete the database on the `Database` page, so it's definitely not a permission issue.

## Steps to reproduce

1. Go to the delete backup config page
2. Check the `Delete the local database` checkbox
3. Delete the database config

- **Actual result**:
The backup is deleted as if I had not checked the delete db checkbox
- **Expected result**:
DB deleted

## Debug log
no logs seem to be generated during the deletion of the backup relating to the database

**Comment by sylerner** [comment]
I am having the same issue with version 2.0.3.3_beta_2018-04-02 running on openSUSE Linux Leap 15.0.
