### ISSUE TITLE
Job edit wizard not loading in Internet Explorer

### ISSUE THREAD

**Issue by Ant1x** [duplicati/duplicati#3075]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.20_canary_2018-02-27
- **Operating system**: Windows Server 2012 R2 & Windows 10 1709
- **Backend**: Irrelevant

## Description

I have noticed that the job settings wizard does not display in the GUI after updating to the latest 2.0.2.20 canary, when using Internet Explorer. I came across this since I don't have an alternate browser installed on my server. Symptoms are the 5 wizard steps appear as per normal, but nothing else. Attempting to click on one of the wizard steps does not load any further wizard pages.
Confirmed on my desktop using IE on Windows 10 also. Problem does not exist using Firefox or Edge. Also from memory the problem did not exist in 2.0.2.19.

## Steps to reproduce

Must be using Internet Explorer. (Tested with IE 11)
A. Click Edit... under the configuration section of a backup job
OR
B. Click Add Backup, Configure a new backup.

- **Actual result**:
The backup job configuration wizard does not load
- **Expected result**:
Wizard should display as normal

## Screenshots

![image](https://user-images.githubusercontent.com/37016240/36933739-7054d8cc-1f32-11e8-8428-5030c3918754.png)

## Debug log

Opening IE dev tools, I see the following script errors in the console
![image](https://user-images.githubusercontent.com/37016240/36933741-87d1c82a-1f32-11e8-87f1-e5acdd0acab9.png)

**Comment by kees-z** [comment]
Same for me. Same symptoms in IE11, other browsers (Edge, Chrome) work like expected.
