### ISSUE TITLE
Graphic glitch: Buttons not visible

### ISSUE THREAD

**Issue by BlackEdder0815** [duplicati/duplicati#3083]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.20
- **Operating system**: Windows / Browser: Chrome 
- **Backend**: N/A

## Description

Buttons in settings not always visible

## Steps to reproduce

1. Go to settings
2. add a global retention policy
3. see the missing buttons

- **Actual result**:
No buttons visible (or at least a small rest)

- **Expected result**:
Buttons are visible

## Screenshots

![image](https://user-images.githubusercontent.com/25084261/36980021-7b95077c-2089-11e8-9fdc-852439af1321.png)

**Comment by Pectojin** [comment]
Hmm, this shouldn't be possible. There is 120 pixels of padding below the bottons and the bar is only 75 pixels tall (and stuck to the bottom of the screen). 

I thought it may have been related to the "Option für Profis hinzufügen" text breaking onto a new line in German, but that renders fine when I change locale.

What resolution are you using? And does it happen in other browsers than chrome? (I tested with chrome, but perhaps it's specific to some version of chrome)

**Comment by BlackEdder0815** [comment]
Display resolution is 1920x1200
Browser-zoom doesn't matter. The behavior is visible with 100%, but also with 150% and 75%. The behavior doesn't change.
Chrom Version: 64.0.3282.186

In Firefox 58.0.2, I have no problem. Here the buttons are displayed as expected.

So seems to be a browser-dependent issue

**Comment by BlackEdder0815** [comment]
After updating Chrome to Version 65.0.3325.146, the issue still existing.

**Comment by Pectojin** [comment]
Hmm, I'm running the exact same chrome version on a Windows 10 box (and also on a macOS box) while running Duplicati in german and adding `--retention-policy` as the only global parameter, but I just cannot get it to display the same way.

Does it happen in incognito mode? Is there any way it's a caching/add-on/custom 3rd-party style issue?

**Comment by Pectojin** [comment]
This is a copy of the original description of #3122, posted by @sklein, to keep information pertaining to this issue in one place.





- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info


- **Duplicati version**: 2.0.3.1
- **Operating system**: Windows 7 Pro SP1
- **Backend**: Wasabi

## Description

Using Chrome Version 65.0.3325.181 (Official Build) (64-bit) the OK and Cancel buttons are cut off by the page footer. Works fine with Firefox 59.0 64-bit.

## Screenshots



![duplicati bug 20180323](https://user-images.githubusercontent.com/1835090/37850920-302f08cc-2e9a-11e8-825d-c7a1251afd60.png)

**Comment by sklein** [comment]
Using the Chrome Inspector, the footer height is shown as 144.2px when the buttons are partially obscured. If I use the inspector to change the footer height to 75px, the buttons are correctly displayed.

Subsequently reloading the page, opening the page in an incognito window, or changing the footer height back to 144px does not obscure the buttons again, so appears to be a caching issue of some sort...

**Comment by BlackEdder0815** [comment]
Oh, this issue got quite old. 
I just checked the issue, and it’s not appearing anymore on my system. So I close it, can be reopened if anyone has still this issue.
