### ISSUE TITLE
[feature request] Use password manager / keystore

### ISSUE THREAD

**Issue by piegamesde** [duplicati/duplicati#3093]
I'd like to have the option of not having the passwords stored in a plain text file on my computer. Instead, the application should ask me for the password every time or request the password from an external keyring or password manager.

Ways to get the password:
 - Ask in a dialog in the browser. For those who are using a password manager with browser integration this won't be a problem, as well as for those with autotype
 - Write a custom plugin (like for KeePass)
 - Request the password from the keyring software provided by the system (like Gnome, KDE, ...). They must have a common API to talk to that is distro dependent.

**Comment by kenkendk** [comment]
This is related to #2024

**Comment by warwickmm** [comment]
Closing this in favor of #2024.
