### ISSUE TITLE
Error in updater

### ISSUE THREAD

**Issue by akyag** [duplicati/duplicati#3098]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.20_canary_2018-02-27
- **Operating system**: Fedora 27 x86_64
- **Backend**: Replace me

## Description

Tried checking for updates, found an error. Then I manually updated using the latest rpm. this version throws he same error too.

## Steps to reproduce

1. Just check for updates
 ...

## Debug log

`System.Net.WebException: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED) ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00054] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncProtocolRequest asyncRequest, Mono.Net.Security.AsyncOperationStatus status) [0x00033] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (Mono.Net.Security.AsyncOperationStatus status) [0x00086] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation () [0x0000d] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at Mono.Net.Security.AsyncProtocolRequest.StartOperation () [0x00000] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <373b6e083d6e45e498c9082a8eebd27f>:0 at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Net.LazyAsyncResult lazyResult) [0x00083] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at Mono.Net.Security.MobileAuthenticatedStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000c] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at Mono.Net.Security.Private.MonoSslStreamWrapper.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x00006] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x0006a] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 --- End of inner exception stack trace --- at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x000c9] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) [0x00019] in <f8255d9ef0594d18ae2c0d97286b9a80>:0 at (wrapper remoting-invoke-with-check) System.Net.WebClient:DownloadFile (string,string) at Duplicati.Library.AutoUpdater.UpdaterManager.CheckForUpdate (Duplicati.Library.AutoUpdater.ReleaseType channel) [0x000ee] in <d5dcb5d2cc844a3ca33e876280091f4b>:0 `

**Comment by Pectojin** [comment]
It appears to be a problem with the mono installation not having the right certificates to validate internet sites.

There is some advice on how to fix it here: https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono

**Comment by akyag** [comment]
Running `sudo cert-sync /etc/pki/tls/certs/ca-bundle.crt` imported all cerrtificates. and the problems with other file hosting services seem to have fixed too.. Thanks a lot

**Comment by Pectojin** [comment]
No problem! 👍
