### ISSUE TITLE
Amazon Drive excluded from backup using exclude system files tag

### ISSUE THREAD

**Issue by alexander0042** [duplicati/duplicati#3099]
- [x] I have searched open and closed issues for duplicates.
----------------------------------------
## Environment info
- **Duplicati version**: 2.0.2.1
- **Operating system**: Windows Server 2016
- **Backend**: SFTP

## Description
When the "Exclude System Files" parameter is used, a folder named "Amazon Drive" and used for Amazon Drive sync client is excluded from the backup.

## Steps to reproduce
1. Create folder named "Amazon Drive"
2. Use the "Exclude System Files" parameter 
3. On my system, this excludes it from the backup, despite not being a system file

Thanks for the help! It took me a while to isolate why this folder was being excluded, and it's definitely the system files tag. It's an easy workaround, but I thought I would report it to save someone else the troubleshooting time

**Comment by Pectojin** [comment]
I wasn't able to replicate this on MacOS when backing up a folder called `Amazon Drive` with `Exclude System Files` enabled.

However, the `Exclude System Files` argument relies on C#'s [File Enumeration](https://msdn.microsoft.com/en-us/library/system.io.fileattributes(v=vs.110).aspx) definitions, which could be different on Windows.

With that said I'm not sure it matters what the name is, but rather the folder might be tagged as a system file. You may be able to [inspect the file attributes](https://superuser.com/questions/304781/viewing-all-file-attributes-in-windows-7-explorer#304800) to verify it. Alternatively you could try renaming the folder or creating a new folder in it's place to see if the name matters.

**Comment by warwickmm** [comment]
Closing this due to lack of feedback.
