### ISSUE TITLE
Can't restore hidden files and folders

### ISSUE THREAD

**Issue by JapSeyz** [duplicati/duplicati#3103]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Fedora 27
- **Backend**: Backblaze B2

## Description
When restoring files, there's no checkbox to show hidden files, and they doesn't show up by default.
Searching for the specific file doesn't work either.

## Steps to reproduce

1. Backup a hidden file/folder
2. Try to restore it

## Screenshots

![duplicati](https://user-images.githubusercontent.com/2234034/37478319-2daa40ec-287a-11e8-9879-1b436be25390.png)

**Comment by Pectojin** [comment]
Hidden files are *supposed* to always be there when restoring. Are you running with any kind of filters on your backup?

**Comment by JapSeyz** [comment]
No, I explicitly selected some hidden folders, like my editor config and some config files, which is why I am rather surprised that I can't restore those

**Comment by Pectojin** [comment]
Could you double check the `Filters` and `Exclude` options on your backup on the `Source Data` page?

It could both be the filters or the exclude `Hidden files` rule.

**Comment by JapSeyz** [comment]
The exclude is setup to exclude any directory with a name that includes vendor or node_modules, that's it.

This is from the config

```json
"Filters": [
      {
        "Order": 0,
        "Include": false,
        "Expression": "*node_modules*/"
      },
      {
        "Order": 1,
        "Include": false,
        "Expression": "*vendor*/"
      }
    ],
```

**Comment by Pectojin** [comment]
The `Hidden files` attribute won't be under filters, it will show up under `Settings` like this

    - Argument: null
      Filter: ''
      Name: --exclude-files-attributes
      Value: system,hidden

**Comment by JapSeyz** [comment]
"-exclude-files-attributes" is not present in the config, did a search for it.

I can't reproduce it, and the config is a bit old, so I may have activated it later on by a mistake.
I'll chalk it up to me doing something wrong, since my trials at reproducing it failed.

Thank you for the quick responses

**Comment by vegar** [comment]
I have the same problem. My config does not exclude hidden files, and when selecting what to backup, hidden files and folders are selected.

When trying to restore, nothing with the hidden attribute shows.

**Comment by t4nec0** [comment]
I have the same problem. 
Using Duplicati 2.0.4.5_beta_2018-11-28 on Windows Server 2008. I selected a folder to be backed up. This folder contains another folder which is hidden. When editing the details of the backup job, I can see this folder as checked (marked for backup) if I select the "show hidden files" checkbox.
However, when browsing through the (metadata) files tree in the UI, there's no way to see this hidden directory. This means I cannot backup even a single file in it...
