### ISSUE TITLE
Broken link to Mono Framework

### ISSUE THREAD

**Issue by hamiltont** [duplicati/duplicati#3105]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1
- **Operating system**: OS X 10.10.5 (14F2511)
- **Backend**: NA

## Description

Link to mono installation is wrong. 

## Steps to reproduce
1. First time install 
2. Launch, see window with Cannot launch Duplicati - Duplicati requires the Mono Framework version 3.0 or later.
3. Click download..., be directed to http://www.go-mono.com/mono-downloads/download.html 

- **Actual result**:
This page is a 404

- **Expected result**:
This page is not a 404 ;-)

**Comment by warwickmm** [comment]
This was fixed in revision https://github.com/duplicati/duplicati/commit/34f318b94abbd933873403f98ec9ba4bcf70f373, which was included in the [v2.0.2.20-2.0.2.20_canary_2018-02-27](https://github.com/duplicati/duplicati/releases/tag/v2.0.2.20-2.0.2.20_canary_2018-02-27) release.

**Comment by hamiltont** [comment]
Awesome thanks
