### ISSUE TITLE
KB/s missing off full screen in firefox

### ISSUE THREAD

**Issue by Roadrunneruk** [duplicati/duplicati#3106]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.3.2_canary_2018-03-16

- **Operating system**: windows 10 with firefox
- **Backend**: Replace me

## Description

When running a backup and  firefox is at maximum the KB/s is cut off the display bar, but when the screen is made smaller the full display is shown, see pictures
![max size](https://user-images.githubusercontent.com/9529362/37554407-da4b054c-29cf-11e8-9579-1c978826037a.JPG)
![reduce size](https://user-images.githubusercontent.com/9529362/37554408-da6498c2-29cf-11e8-9228-90864a0d14cd.JPG)

## Steps to reproduce

1. run in firefox
2. 
3. ...

- **Actual result**:
look at pictures
- **Expected result**:
look at pictures

**Comment by SanduRajapakse** [comment]
Alright, seems like an easy fix. Not sure why a fixed width was set, but I will correct it.

**Comment by SanduRajapakse** [comment]
I'll take a look at this when I get a chance. The fix is straightforward, but it has a negative effect on the pause and throttle button. I will see what I can do to minimize the effect.

**Comment by SanduRajapakse** [comment]
I made the necessary changes to fix this issue in pull request #3162. 

This will:
1) Truncate the length of the name (in the state bar) to keep the state fully visible
2) Show the full name (as a title) if the user hovers over the name

Once merged, this problem should be resolved.

**Comment by warwickmm** [comment]
Resolved in pull request #3162.
