### ISSUE TITLE
Disable backends

### ISSUE THREAD

**Issue by bdrayer** [duplicati/duplicati#3116]
Hi,

Is there a way, using OEM branding to disable some of the backends?

Best regards and thank you for this amazing software

**Comment by Pectojin** [comment]
I don't believe there currently is a way, so it would have so be developed first.

**Comment by jkiebzak** [comment]
If I were to compile my own copy of Duplicati, but first removing the unnecessary backend files from here `duplicati/Duplicati/Library/Backend/`, would that effectively disable unneeded backed ends?

**Comment by ts678** [comment]
[Branding and OEM customization](https://github.com/duplicati/duplicati/wiki/Branding-and-OEM-customization) talks about backends. I can't answer questions, but I'll quote:

> One use of the resigning option would be to remove unwanted backends, so only approved backends are present. Since the backends are loaded dynamically this would simply require that the unwanted backend files are deleted before repacking and signing.

so there might be a way, however the above sounds rather involved unless it's already planned.

I'd have thought the build would break if you're talking about deleting source, but I don't build.

**Comment by jkiebzak** [comment]
Excellent reference, which seems to support my idea. I had missed that
paragraph. In coming days, I'll be testing this out.

>

**Comment by warwickmm** [comment]
I believe removing the assemblies for the unwanted backends should work.
