### ISSUE TITLE
Asymmetric GPG fails when running from systemd

### ISSUE THREAD

**Issue by piegamesde** [duplicati/duplicati#3117]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.2_canary_2018-03-16
- **Operating system**: Arch Linux
- **Backend**: Chromium Browser

## Description

I migrated to a new laptop and need to recreate the database of my backups. They are encrypted using asymmetric GPG. The GPG private key has been transferred. But when trying to recreate the database, instead of asking me for the GPG password, it fails after 5 tries.

## Steps to reproduce

1. Have a backup with asymmetric GPG encryption
2. Delete and recreate the local database

- **Actual result**:
It will try to decrypt the first file, fail, try another four times and then stop the action.
- **Expected result**:
It will ask me for the key's password and recreate the database

## Debug log

```
{"ClassName":"System.Security.Cryptography.CryptographicException","Message":"Failed to decrypt data (invalid passphrase?): Decryption failed: gpg: encrypted with RSA key, ID C099A83C9989618B\ngpg: decryption failed: No secret key\n","Data":null,"InnerException":{"ClassName":"System.Security.Cryptography.CryptographicException","Message":"Decryption failed: gpg: encrypted with RSA key, ID C099A83C9989618B\ngpg: decryption failed: No secret key\n","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Encryption.GPGStreamWrapper.Dispose (System.Boolean disposing) [0x00086] in <c73322bc8c1f4276b94df83c507190be>:0 \n  at System.IO.Stream.Close () [0x00000] in <fd8e55540b2e42a38c15ac8ada2f6b8b>:0 \n  at System.IO.Stream.Dispose () [0x00000] in <fd8e55540b2e42a38c15ac8ada2f6b8b>:0 \n  at Duplicati.Library.Encryption.EncryptionBase.Decrypt (System.IO.Stream input, System.IO.Stream output) [0x00016] in <c73322bc8c1f4276b94df83c507190be>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233296,"Source":"Duplicati.Library.Encryption"},"HelpURL":null,"StackTraceString":"  at Duplicati.Library.Main.AsyncDownloader+AsyncDownloaderEnumerator+AsyncDownloadedFile.get_TempFile () [0x00008] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun (Duplicati.Library.Main.Database.LocalDatabase dbparent, System.Boolean updating, Duplicati.Library.Utility.IFilter filter, Duplicati.Library.Main.Operation.RecreateDatabaseHandler+NumberedFilterFilelistDelegate filelistfilter, Duplicati.Library.Main.Operation.RecreateDatabaseHandler+BlockVolumePostProcessor blockprocessor) [0x009e4] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.Run (System.String path, Duplicati.Library.Utility.IFilter filter, Duplicati.Library.Main.Operation.RecreateDatabaseHandler+NumberedFilterFilelistDelegate filelistfilter, Duplicati.Library.Main.Operation.RecreateDatabaseHandler+BlockVolumePostProcessor blockprocessor) [0x00037] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Library.Main.Operation.RepairHandler.RunRepairLocal (Duplicati.Library.Utility.IFilter filter) [0x000ba] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Library.Main.Operation.RepairHandler.Run (Duplicati.Library.Utility.IFilter filter) [0x00012] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Library.Main.Controller+<>c__DisplayClass21_0.<Repair>b__0 (Duplicati.Library.Main.RepairResults result) [0x0001c] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x001e3] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Library.Main.Controller.RunAction[T] (T result, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x00007] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Library.Main.Controller.Repair (Duplicati.Library.Utility.IFilter filter) [0x0001a] in <cad7b2bda0054aeb8800ccf4b5d3bb31>:0 \n  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00575] in <ffc12c0247864a30950a40182d2107b6>:0 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233296,"Source":"Duplicati.Library.Main"}
```

**Comment by piegamesde** [comment]
Two additional notes:

1. This also applies to only verifying the backup
2. On my Debian machine with the same version it works perfectly fine.

Is there a dependency for those dialogs I have to install? Something else I've missed?

**Comment by wjansenw** [comment]
Are you running the same gpg client on both machines?

**Comment by piegamesde** [comment]
No, since Arch (gpg 2.2.5, libgcrypt 1.8.2) is always ahead of Debian (gpg 2.1.18, libgcrypt 1.7.6-beta). Both are the newest version available.

**Comment by piegamesde** [comment]
I tried creating a new backup for testing with GPG encryption. Here's what running it returned:

> Failed to execute GPG at ""gpg" --batch --passphrase-fd 0 --recipient piegames --encrypt": gpg: piegames: skipped: No public key gpg: [stdin]: encryption failed: No public key

My assumption is that because I run Duplicati as systemd module, it doesn't look at the user folder for the keys but somewhere else instead (something system wide) where there are no keys.

**Comment by warwickmm** [comment]
How are you running the systemd service?  I think the AUR Duplicati package by default runs the service using the `duplicati` user and group.  You can use the drop-in feature to change this to be root, or some other user if desired.  Alternatively, you can try starting it with the `systemctl --user` option.

**Comment by piegamesde** [comment]
I modified the systemd unit to have the same user and group as me, and it now runs in the correct folder, but it still doesn't show the dialog. Running it directly from the commandline as user still works fine. I tried it out with different applications (Server, Service, TrayIcon) and every time it's the same.

I didn't get the --user option to work though.
