### ISSUE TITLE
Default Filters and Exclusions

### ISSUE THREAD

**Issue by piegamesde** [duplicati/duplicati#3125]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Description

Apparently, there is no information about what the default filters (Windows, OSX, Linux, All) do, neither in the wiki nor in the manual.

The same applies to the Exclusion options, but except the "System files" they are all self-explaining.

**Comment by tygill** [comment]
The default filters are currently going through some revising (there's been some discussions in #3030 about how exactly to do it). Until that is all settled, the default filters have actually been disabled under the covers.

Once they're revived, I've written up a revision to the recently added [Duplicati manual](https://docs.duplicati.com/)'s page on filters, which adds documentation on the new filter groups.

I believe the other exclusion options are talked about already on the manual's filter page.

**Comment by piegamesde** [comment]
> The latter is able to exclude files that have any of the following attributes: ReadOnly, Hidden, System, Directory, Archive, Device, Normal, Temporary.

There is no definition what each attribute _exactly_ means. While some like "ReadOnly" and "Hidden" are quite self-explaining, others aren't. What is an "Archive file" for example? Does it include all compressed files? Only compressed tar files? What about .jar files and other archives with custom ending? How does it determine which is compressed? On the ending, or the MIME type? What if the compression algorithm is not known?

**Comment by tygill** [comment]
I believe those are attributes based on the [NET FileAttributes enum](https://msdn.microsoft.com/en-us/library/system.io.fileattributes%28v=vs.110%29.aspx). So for Archive, it's the file system Archive attribute.

**Comment by Pectojin** [comment]
Should we conclude that this issue is *handled* by #3030?

In that case I'd close this issue to keep discussion under one issue.
