### ISSUE TITLE
Red tray icon

### ISSUE THREAD

**Issue by vers-one** [duplicati/duplicati#3126]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.2_canary_2018-03-16
- **Operating system**: Windows 10

## Description
During the first setup I made a mistake in the backup task configuration, so it failed on the first run and tray icon became red. After that I fixed the mistake. There were a few successful runs within the last couple of days but the tray icon still stays red even there are no errors in UI. I tried everything: starting the task manually, starting it on schedule, restarting the service, clicking on the all log items, repairing and rebuilding the database, but the icon is still red (when the task is idle) no matter what.

**Comment by vers-one** [comment]
Just installed it again from scratch on a totally different PC (also Windows 10). This time I didn't do any mistakes in the backup task configuration, but the tray icon turned red after the first successful run anyway.

**Comment by warwickmm** [comment]
Does [this suggestion](https://forum.duplicati.com/t/windows-10-tray-icon-always-red-failed/835/3) help?  Nevertheless, we still need to figure out what is causing this.

**Comment by vers-one** [comment]
Yep, interrupting the running task and dismissing the error notification did help. Thank you.

I still have this situation on my second PC, I'll leave it as is and will try to debug it to find out what is causing it.

**Comment by vers-one** [comment]
Just installed duplicati-2.0.3.2_canary_2018-03-16-x64.msi on Windows 10 virtual machine and immediately got a red tray icon. I think I know what is the problem.

During the first start the database file doesn't exist so it gets created and initialized via
`DataConnection.FixInvalidBackupId()` (https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Program.cs#L282)
which eventually calls `ServerSettings.SaveSettings()` (https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Database/ServerSettings.cs#L105)

However the `ServerSettings` class constructor sets all the settings values to `null` (https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Database/ServerSettings.cs#L74) before that which means that `unacked-error` parameter (https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Database/ServerSettings.cs#L47) will be empty in the database.

Later when the server reads the settings and `UnackedError` in particular it tries to parse this empty string as a boolean value (https://github.com/duplicati/duplicati/blob/master/Duplicati/Server/Database/ServerSettings.cs#L227) which uses `true` value in case of the parsing failure (https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Utility/Utility.cs#L687).

So initial state of the database always leads to the red tray icon.

**Comment by warwickmm** [comment]
Thanks @vers-one for looking into this.  That was helpful.  Pull request #3166 attempts to resolve this.

**Comment by warwickmm** [comment]
Fixed in pull request #3166.

**Comment by vers-one** [comment]
Just checked this in 2.0.3.5_canary_2018-04-13. It works.
Thanks @warwickmm!
