### ISSUE TITLE
Symlink restoration incorrectly writes owner and mode through the link

### ISSUE THREAD

**Issue by mhorowitz** [duplicati/duplicati#3127]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.2.1_beta_2017-08-01
- **Operating system**: Ubuntu 16.04
- **Backend**: B2

## Description
Symlink restoration is not handled properly.  [SetMetaData](https://github.com/duplicati/duplicati/blob/4abc2f832f7069abe4e3cf2104ce238bd36bf152/Duplicati/Library/Snapshots/SystemIOLinux.cs#L226) blindly calls UnixSupport.File.SetUserGroupAndPermissions regardless of type.  For symlinks, this results in the target of the symlink having its owner, group, modes changed.

## Steps to reproduce
1. In a directory you back up, create a symlink to `/an/absolute/path/somewhere`
2. Back up.
3. chown and chmod `/an/absolute/path/somewhere`
4. restore the directory to a different location, with restore file permissions set.

- **Actual result**:
See the restored symlink is owned by root, and `/an/absolute/path/somewhere` has had its owner and modes reverted.

- **Expected result**:
The original file is not changed; the restored symlink has the original owner.  On OSs which support it, it also has the original mode.

I've never done any programming in c# or mono, but it looks like there's an lchown call.  Setting permissions on symlinks is not portable between different unix variants, and I don't see an lchmod calls, but maybe there's another way.

## Debug log
The hint to me this was happening was an error in the backup logs for a dangling symlink:
```
Failed to apply metadata to file: "/tmp/restore-marc/foo/.#bar", message: Could not find file "/tmp/restore-marc/foo/.#bar" => Could not find file "/tmp/restore-marc/foo/.#bar"
```

**Comment by Pectojin** [comment]
Good detective work. This is definitely not ideal behavior.

I believe most systems completely disregard symlink permissions and just check the targets permissions, so perhaps setting the permissions for symlinks should just be completely skipped?

**Comment by mhorowitz** [comment]
Yeah, setting symlink permissions is less important than the rest.  But it is possible on some supported platforms (like OSX, which has lchmod() and fchmodat(), and a -h arg to chmod(1)), so if it's not difficult, it's unlikely to hurt.

**Comment by Pectojin** [comment]
There's bit a bit of discussion on this bug on the [forum](https://forum.duplicati.com/t/bug-in-symbolic-link-handling/3728) and there should be a fix coming soon.
