### ISSUE TITLE
ISSUE - 'Too many requests for this key, wait 60 minutes.'

### ISSUE THREAD

**Issue by A-Frantyk** [duplicati/duplicati#3131]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2
- **Operating system**: Windows
- **Backend**: Not changed.

## Description

I've tried to create a backup and save it to google drive. 
After several usages, I've got the issue: 'Too many requests for this key, wait 60 minutes. ...'

## Screenshots

![image](https://user-images.githubusercontent.com/11341743/37955161-8395a412-31b0-11e8-8da4-e2ca8942fd7e.png)

**Comment by Pectojin** [comment]
#3153

**Comment by A-Frantyk** [comment]
Pectojin - you references this issue to closed issue which has not any comments which explains solution to fix this issue, or why it's happen.

**Comment by Pectojin** [comment]
Both issues report the same error and provide more or less the same information. 

They're essentially duplicates so I closed one in order to keep information and discussion about the bug collected under one issue report.

**Comment by A-Frantyk** [comment]
Do you have any idea why this issue happens?
