### ISSUE TITLE
cannot restore backups

### ISSUE THREAD

**Issue by robdumont** [duplicati/duplicati#3132]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- Duplicati - 2.0.3.2_canary_2018-03-16
- Legacy version: 1.3.4 (not sure what version i had before failure but it looks the same)
- **Operating system**: Windows 10
- **Backend**: Dreamhost S3 DreamObjects

## Description
Hello, i've had backups running using an older version of Duplicati (1.x) or something and have tested the restore previously with success. I backup to Dreamhost S3 environment. My computer died a couple days ago and i'm not able to restore from the Duplicati backups with either the new web version (2) or a legacy version (1) which i managed to find and download. I have screenshots of my previous config which i have followed.

I was able to download the Dreamhost objects to my local drive, duplicati-xxxxxxx.vol1.zip.aes and tried restoring directly from there and the legacy version of Duplicati goes through the motions but then says no backups found.

## Steps to reproduce

1. Replace me
2. Replace me
3. ...

- **Actual result**:
Replace me
- **Expected result**:
Replace me

## Debug log
Mar 27, 2018 1:17 PM: Request for http://localhost:8200/api/v1/backup/78ff5f96-5623-40f3-9dc1-c69f0e785b9f/log?pagesize=100 gave error
Mar 27, 2018 1:17 PM: Reporting error gave error
Mar 27, 2018 1:17 PM: Failed while executing "List" with id: 78ff5f96-5623-40f3-9dc1-c69f0e785b9f
Mar 27, 2018 1:17 PM: Request for http://localhost:8200/api/v1/backup/78ff5f96-5623-40f3-9dc1-c69f0e785b9f/filesets gave error
Mar 27, 2018 1:17 PM: Reporting error gave error
[Legacy Duplicati.docx](https://github.com/duplicati/duplicati/files/1853478/Legacy.Duplicati.docx)
[Duplicati Canary.docx](https://github.com/duplicati/duplicati/files/1853479/Duplicati.Canary.docx)

**Comment by Pectojin** [comment]
Backups created with version 1 will not work with version 2. However, you should definitely be able to restore version 1 backups with version 1 software.

I'm not too familiar with the layout of the version 1 backup, but could you check what files are available? The `No backups found` error could suggest that it's looking for a file that it can't find.

**Comment by robdumont** [comment]
Thanks Rune, what you said made sense, i was just trying different options. I'm not really fluent in this area but when i go to Dreamhost it shows me all the backups and that is what i downloaded. There does not appear to be any other file options but i have logged a call with Dreamhost as well.
Some of my googling has suggested things like missing database but i think that was more for version 2.

**Comment by Pectojin** [comment]
There are a couple of references to the `no backups found` error: 
#515
#513
But they seem to just indicate that it was fixed in an update. If you're running the newest 1.3 update then I'm afraid we might have to hope for someone with Duplicati 1.3 experience to chip in here with advice.

**Comment by warwickmm** [comment]
Unfortunately, Duplicati 1.x is no longer being supported.  If this is still an issue, I'd suggest posting in the forums to see if anyone has encountered a similar issue that can help.

https://forum.duplicati.com/
