### ISSUE TITLE
[minor] Synology prepends backslash (\) to pipe (|) in (command line) password

### ISSUE THREAD

**Issue by ConradHughes** [duplicati/duplicati#3135]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.2_canary_2018-03-16
- **Operating system**: Synology DSM 6.1.6-15266
- **Backend**: Mono 5.8.0.108-11

## Description

Specifying a password containing the pipe symbol (|) on the command line using --webservice-password results in an *actual* password requirement of backslash-pipe (\\|).  This looks like a shell metacharacter quoting error and may even be a problem with mono-sgen.  I cannot replicate this on Debian 9.4 running duplicati 2.0.2.1-1 on mono-runtime 4.6.2.7+dfsg.

## Steps to reproduce

1. Execute (for example) `/volume1/@appstore/mono/bin/mono-sgen /volume1/@appstore/Duplicati/Duplicati.Server.exe --webservice-interface=any --webservice-port=8200 --webservice-password='|'`
2. Try to log in to the server using | as password.
   * This won't work.
3. Try to log in to the server using \\| as password.
   * This will work.
4. Running "ps" will show two mono-sgen processes, the second of which has a "\\" before the | in the --webservice-password switch: `--webservice-password=\|`

- **Actual result**: (see above) only \\| works as password, while just | was specified.
- **Expected result**: (see above) | should work alone as password.

**Comment by arberg** [comment]
This issue I created (later) is identical (in the underlying cause): https://github.com/duplicati/duplicati/issues/3891

**Comment by warwickmm** [comment]
Duplicates #3891.
