### ISSUE TITLE
Remove "Don't use with important data." from update channel description

### ISSUE THREAD

**Issue by renestach** [duplicati/duplicati#3139]
* Go to settings
* Scroll down to the update channels
* Description for beta channel says "Try out the new features we are working on. Don't use with important data."

We should change that to something like "The currently most stable version available. Restore data before using this in productive environments."

**Comment by SanduRajapakse** [comment]
I agree, and also add: "Don't use with important data." to the Experimental and Canary builds.

**Comment by SanduRajapakse** [comment]
I made the necessary text changes in pull request #3152. The localizations may need to be updated but should be more clear since there is no current stable build.

**Comment by SanduRajapakse** [comment]
With the merge, I recommend closing of this issue (#3139) as it should be resolved.

**Comment by kenkendk** [comment]
Yes, issue fixed.
