### ISSUE TITLE
rclone backend error on linux/amd64

### ISSUE THREAD

**Issue by Bruceforce** [duplicati/duplicati#3142]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.4_canary_2018-04-02
- **Operating system**: 3.16.0-5-amd64 Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux
- **Backend**: rclone (since version 1.40)
- **Mono version**: Mono JIT compiler version 5.10.1.20 (tarball Thu Mar 29 11:13:12 UTC 2018)

## Description

After rclone update to version 1.40 I get the following error, when I click on "test connection"
```
Failed to connect: 
2018/04/03 14:52:35 ERROR : Couldn't find home directory or read HOME or XDG_CONFIG_HOME environment variables.
2018/04/03 14:52:35 ERROR : Defaulting to storing config in current directory.
2018/04/03 14:52:35 ERROR : Use -config flag to workaround.
2018/04/03 14:52:35 ERROR : Error was: user: Current not implemented on linux/amd64
```

I tried to add `--config /root/.config/rclone/rclone.conf` and `--rclone-option=--config /root/.config/rclone/rclone.conf` to the advanced settings, but that doesn't seem to make a difference. If I use rclone without Duplicati it works.
@wjansenw Do you have an idea?

## Steps to reproduce

1. Install (or update to) rclone version 1.40
1. Create a new Backup with the rclone backend
1. Fill in the forms and click "test connection"

- **Actual result**:
Aforementioned error occurs.
- **Expected result**:
Backup should run without errors.

**Comment by wjansenw** [comment]
All working OK here. Had to reconfigure everything including reinstalling rclone due to synology removing the config db. 
I'm not sure I ever tested the option parameters being handles correctly...

It looks like the user running duplicati does not have access to the rclone config.

Wim

**Comment by wjansenw** [comment]
Did you configure rclone as root? Maybe rclone lost its configuration as part of the upgrade?

**Comment by Bruceforce** [comment]
No problem if you haven't got that much time. I hope I can reproduce the behavior on a fresh debian installation this weekend.

Yes I configured rclone as root and the config is under "/root/.config/rclone/rclone.conf". If I run `rclone config` the remotes are there and if I run `rclone ls remote:path` it lists the path.

**Comment by cvillabrille** [comment]
Hi,

I'm facing same issue. Duplicati installed through OpenMediaVault plugin.

If I run the backup through the GUI, or select the "test connection" button, it shows the error "ERROR : Couldn't find home directory or read HOME or XDG_CONFIG_HOME environment variables" and no matter how you specify the -config path. rclone is installed under /usr/bin. rclone.conf is under /root/.config/rclone/rclone.conf.

If I run the command on CLI, I receive the error (Duplicati.Library.Interface.UserInformationException: Backend not supported: rclone at Duplicati.Library.Main.BackendManager..ctor)

If you link the rclone conf file under /.rclone.conf (i.e  /.rclone.conf -> /root/.config/rclone/rclone.conf) the error about config dissapear but, it stil shows ( Use -config flag to workaround.2018/04/05 17:08:31 ERROR : Error was: user: Current not implemented on linux/arm)

Any idea?

Duplicati is running as root.

**Comment by cvillabrille** [comment]
BTW,

the error looks is comming from rclone, as per the config.go file of rclone (https://github.com/ncw/rclone/blob/master/fs/config/config.go)

	// Default to ./.rclone.conf (current working directory)
	fs.Errorf(nil, "Couldn't find home directory or read HOME or XDG_CONFIG_HOME environment variables.")
	fs.Errorf(nil, "Defaulting to storing config in current directory.")
	fs.Errorf(nil, "Use -config flag to workaround.")
	fs.Errorf(nil, "Error was: %v", err)
	return hiddenConfigFileName
}

However, no matter how we setup the rclone variables under Duplicati. rclone fails with same error.

I have three ARM Openediavault NAS where it's failing (bananaBerry, oDroidXU4, bananaPro) is that true?: "Current not implemented on linux/arm". 

I'm using rclone correctly to sync, but I would like to use Duplicaty in those repositories where Duplicati does not have config (i.e. openDrive)

**Comment by Bruceforce** [comment]
Hi @cvillabrille can you try with this commit? https://github.com/Bruceforce/duplicati/commit/c3f94ec6cbd2495f00f451c82c3910aa1dd0aaa9

It should honor the advanced options in rclone now. So you have to set advanced options to "--config [where your config is].conf"

**Comment by wjansenw** [comment]
I still do not understand why you are getting the error... it might be fixed by the config option but should work without as well if rclone is configured as the same user duplicati is using and if rclone is in the path.

It works on my linux based synology with the latest rclone and beta duplicati.

**Comment by Bruceforce** [comment]
Okay I reproduced it on a clean debian 9.4.0 x64 headless install with rclone 1.40 and duplicati 2.0.3.4.

1. Install duplicati 2.0.3.4
1. Install rclone 1.40
1. run `rclone config` **as root** and set up a local remote and call it "local"
1. create a new backup job and set: local repository = local, remote repository = local, remote path = /tmp/new_folder
1. start duplicati **as root** click on "test connection"
1. get error message

But as I wrote above I think it's not an issue with your code, but with rclone getting called from a third party application. In the issue I linked above the same thing happens if you call rclone from systemd.

Also I think starting those applications as root may cause the problem. If I run them both as normal user the backend can find the config. Maybe I should do this anyways (I think it's unnecessary to run those as root anyway). Maybe these information can help you.

**Comment by cvillabrille** [comment]
@Bruceforce #3156 

I would like to apply this, however I cannot find how/where. 
I have only one backend.rclone file under /usr/share/Duplicati/updates/2.0.3.3/Duplicati.Library.Backend.Rclone.dll  which is a binary file.

I have installed Duplicati over the OMV (OpenMediaVault) plugin.

BTW: following ncw/rclone#747, if we unset the $HOME variable rclone shows the error

	 root@dataDroid:~# unset HOME
	 root@dataDroid:/root# rclone version
	 2018/04/06 10:24:37 ERROR : Couldn't find home directory or read HOME or XDG_CONFIG_HOME  environment variables.
	 2018/04/06 10:24:37 ERROR : Defaulting to storing config in current directory.
	 2018/04/06 10:24:37 ERROR : Use -config flag to workaround.
	 2018/04/06 10:24:37 ERROR : Error was: user: Current not implemented on linux/arm
	 rclone v1.40-040-g6e11a25dβ
	 - os/arch: linux/arm
	 - go version: go1.10

	 root@dataDroid:/root# export HOME=/root
	 root@dataDroid:~# rclone version
	 rclone v1.40-040-g6e11a25dβ
	 - os/arch: linux/arm
	 - go version: go1.10		
	 root@dataDroid:~# rclone listremotes   
	 Montecerrao:                           
	 oDroidB2:                              
	 oDroidHub:                             
	 oDroidOpenDrive:                       
	 root@dataDroid:~#

**Comment by cvillabrille** [comment]
I have added an advanced option for rclone-executable with a script (/usr/local/bin/rclone_duplicati) which contains:

	 [root@databananaBerry:~]# cat /usr/local/bin/rclone_duplicati
	 #!/bin/bash
	 export HOME=/root
	 /usr/bin/rclone  $*

that basically call rclone and it exports the $HOME variable. 

well, it works, and it passes the parameters to rclone as well as the $HOME variable.

`Output running...: Rclone_test: 5 files (28.00 MB) to go`

`Output done: Last successful run:    Today at 11:10 AM (took 00:01:37)`

**Comment by cvillabrille** [comment]
Another update.

running the job in a console reports backend not supported, any clue?

  	[root@databananaBerry:~]# mono /usr/lib/duplicati/Duplicati.CommandLine.exe backup "rclone://Bberry-opendrive//Duplicati/Odroid/rclone?rclone-local-repository=local&rclone-executable=%2Fusr%2Flocal%2Fbin%2Frclone_duplicati" /data/PiTimeCapsule/ --backup-name=Rclone_openDrive_Berry_PitimeCapsule --dbpath=/data/duplicati_db/rclone_opendrive_timecapsule_berry.sqlite --encryption-module=aes --compression-module=zip --dblock-size=50mb --keep-time=6M --passphrase="XXXYYYZZZ" --disable-module=console-password-input
	Backup started at 06/04/2018 11:33:26
	The supplied option --rclone-local-repository is not supported and will be ignored
	The supplied option --rclone-executable is not supported and will be ignored
	Fatal error => Backend not supported: rclone
	
	Backend not supported: rclone
	Update "2.0.3.3_beta_2018-04-02" detected

**Comment by Bruceforce** [comment]
@cvillabrille to apply the fix you would have to build from source as described in here https://github.com/duplicati/duplicati/wiki/How-to-build-from-source. 

However since you managed to create a workaround by yourself I think it's not necessary for you to build from source and you could run with your helper script and/or wait until the PR is merged and apply the config path as an rclone advanced option. The benefit of the second approach is that you will be able to export your backup job, without manually carrying the script.


For your second post: Whats the output of `mono /usr/lib/duplicati/Duplicati.CommandLine.exe | grep Version`

**Comment by cvillabrille** [comment]
Hi BruceForce, 

thanks for your quick reply.

Base version is:

	[root@databananaBerry:~]# mono /usr/lib/duplicati/Duplicati.CommandLine.exe | grep Version
	http://www.duplicati.com/              Version:  - 2.0.2.1_beta_2017-08-01


                   

I have applied the latest update available for beta version the keeps the version in (through web)

	You are currently running Duplicati - 2.0.3.3_beta_2018-04-02

**Comment by Bruceforce** [comment]
Can you try with ` mono /usr/share/Duplicati/updates/2.0.3.4/Duplicati.CommandLine.exe ...` if this file exists for you?

**Comment by cvillabrille** [comment]
I guess you are referring to 2.0.3.3 instead 2.0.3.4 (that I do not have it).

With this .exe file under the updates, it works. Thanks a lot.

	# mono /usr/share/Duplicati/updates/2.0.3.3/Duplicati.CommandLine.exe backup "rclone://Bberry-opendrive//Duplicati/Odroid/rclone?rclone-local-repository.....
	Backup started at 06/04/2018 12:37:17
	Checking remote backup ...
	  Listing remote folder ...

**Comment by Bruceforce** [comment]
@kenkendk Can you please re-open this? It seems this isn't fully fixed (sorry for that).
I think I don't know the duplicati workflow good enough to fix this. If I build the current version from source with monodevelop it seems to be working. 

The strange thing is, if I follow my own steps to reproduce https://github.com/duplicati/duplicati/issues/3142#issuecomment-379013241 I still get an error which I don't fully understand.

1. Install duplicati 2.0.3.5
2. Install rclone 1.40
3. run `rclone config` as root and set up a local remote and call it "local"
4. create a new backup job and set: local repository = local, remote repository = local, remote path = /tmp/new_folder **(please choose a path which is currently not existing)**
5. click on 'Test connection' and you will be asked "The folder new_folder does not exist. Create it now?
6. choose 'yes' to create the folder
7. click on 'Test connection' again
8. get error message

Step 5 tells me, that the advanced-options can be read correctly. But I don't get why it errors out if the folder is existing.

What I don't understand is: If I save the backup job despite of the error message and then export it as command line to run it it's working. So the advanced rclone-options seems to work but somehow in the webinterface it isn't happy.

Any ideas @wjansenw?

**Comment by wjansenw** [comment]
What is the error message you get?

**Comment by wjansenw** [comment]
+ do you get the error also when using a different backend in rclone? Which
backend are you using?

I'm currently also having issues with OD4B as backend in rclone. But this
is OD4B related I think.

~~~~
Failed to copy: generalException: An unspecified error has
occurred.2018/04/13 19:15:31 ERROR : Attempt 1/3 failed with 1 errors and:
generalException: An unspecified error has occurred.
~~~~

**Comment by Bruceforce** [comment]
I'm getting the exact same error message as posted in the original issue. It's definitely not od4b related, since I only used local filesystem in my steps to reproduce.

I also tried the new Onedrive v2 (with Graph API) and this one is working.

I just don't get why the rclone backend can read the config, create the folder and then somehow doesn't seem to find the config anymore.
