### ISSUE TITLE
Feature Request: see what versions of a particular file are available during restore

### ISSUE THREAD

**Issue by francobarber** [duplicati/duplicati#3155]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3
- **Operating system**: Linux
- **Backend**: B2

## Description

This is a feature request.
I would like to see a way to see distinct/unique versions of a chosen file that are included in a backup set.
From what I can see in the restore dialog and from the command line "list" command, currently I can see that a file is included in the backup set, but I cannot tell if there is actually any change for a given file between various instances of that backup set (which I think are called versions of snapshots, I'm not sure about the terminology.)

For example, say I have a backup set defined that has two files in it, A and B.  And say that on 3 occasions that the backup set ran file B was changed, so duplicati shows 3 versions/backups/snapshots created for that backup set. But file A may be the same in all 3 of those versions/backups/snapshots.   I would like to have a way to see, given a specific file in a backup set, how many unique versions of that file are present in all the versions/backups/snapshots created for that backup set.

If this is available currently I haven't figured out how to access it.  It would be particularly useful to be able to see this during the restore operation.

**Comment by kees-z** [comment]
This could be a useful feature, but it is already requested more than once:
See issue https://github.com/duplicati/duplicati/issues/72 and [this](https://forum.duplicati.com/t/show-file-specific-backup-history-when-restoring/277) forum topic.

**Comment by francobarber** [comment]
I did search for duplicates, but my search wasn't good enough.
Closing this one as a dup.
