### ISSUE TITLE
WebUI: "Repeat passphrase" field stores Chrome autocomplete values

### ISSUE THREAD

**Issue by qqrs** [duplicati/duplicati#3165]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Ubuntu Linux
- **Backend**: local

## Description

Passphrases for previously-created backup configurations can appear in the "Repeat passphrase" autocomplete list under Chrome.

On one hand, someone with access to a Duplicati installation can simply use the "export configuration as command line" to see a backup passphrase from the WebUI. It does not appear that the WebUI is intended to avoid revealing the passphrase to someone with local access. So the autocomplete behavior described here may not a critical issue.

On the other hand, I do see https://github.com/duplicati/duplicati/issues/2024 which indicates that there is movement in making the WebUI more secure in revealing of passphrases. So I'm reporting this issue in case it is not otherwise known.

## Steps to reproduce

1. Open Duplicati Web UI in Chromium 63
2. Navigate to `Add Backup` -> `Configure a new backup` -> `Next` -> `General backup settings`.
3. Click `Show`
4. Click in the `Repeat passphrase` text field and enter a passphrase, e.g., "abcd"
5. Click on the page somewhere outside the text field to remove focus
6. Navigate to `Home`. (Or you could finish setting up the backup configuration here.)
7. Return to `Add Backup` -> `Configure a new backup` -> `Next` -> `General backup settings`.
8. Click `Show`
9. Click in the `Repeat passphrase` text field
10. Press the down arrow. Your passphrase (e.g., "abcd") will be displayed as an autocomplete option.

- **Actual result**:
Passphrases for previously-created backup configurations appear in the "Repeat passphrase" autocomplete list.
- **Expected result**:
"Repeat passphrase" should not have an autocomplete list, even after clicking "Show" to reveal the password.
- **Workaround**:
Run Duplicati WebUI in a Chrome Incognito window

**Comment by ts678** [comment]
[Password saver may autofill too many places, getting --auth-password is not supported #4102](https://github.com/duplicati/duplicati/issues/4102) wrestled with how to fix this.
[Fix unwanted password manager autofill #4402](https://github.com/duplicati/duplicati/pull/4402) tried one plan, including on "Repeat Passpharase". Does it resolve this issue?
