### ISSUE TITLE
Attribute IsFSCaseSensitive is expensive to get

### ISSUE THREAD

**Issue by ltfish** [duplicati/duplicati#3167]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.2_canary_2018-03-16
- **Operating system**: Windows 10
- **Backend**: Local hard drive

## Description

I did a profiling using Intel VTune on Duplicati 2 for a backup run. During the initial file counting phase, the profiler tells me that `System::Environment::GetEnvironmentVariable()` takes ~24% of the execution time. Further investigation shows that `FilterEntry::Matches` calls `Utility::get_IsFSCaseSensitive`, which calls `GetEnvironmentVariable()` for every file path, and this is not a fast operation.

I think a quick and hackish solution is simply caching the value of `GetEnvironmentVariable("FILESYSTEM_CASE_SENSITIVE")` because it should not change after the program starts. I'm posting this issue to see a) if this is a real performance issue, and b) if this proposed solution is acceptable. If answers to both questions are yes, I'll go ahead and prepare a PR to address this issue. Thanks.

## Steps to reproduce

a. Perform a profiling on Duplicati 2 using the "Basic Hotspots" profile in Intel VTune.
b. Start a backup job in Duplicati 2.
c. Wait for a while, and then terminate the backup task when Duplicati 2 is still counting files.
d. Stop profiling and take a look at the profiling result.

- **Actual result**:
`Utility::get_IsFSCaseSensitive` shows up as a hotspot taking ~24% of execution time in the profiling result.
- **Expected result**:
`Utility::get_IsFSCaseSensitive` should not show up as a hotspot in the profiling result.

## Screenshot

![get_isfscasesensitive_slow](https://user-images.githubusercontent.com/5071575/38543003-3973282a-3c58-11e8-82a3-5aa23809fe16.png)

**Comment by Pectojin** [comment]
This seems pretty sane. I don't see any reason to not change it.
