### ISSUE TITLE
Implement multi-core processing option

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#3174]
Multi-core processing allows us to utilize as much as possible of the CPU time, essentially making the disk access the bottleneck.

This is implemented in the `concurrent_processing` branch, which should be merge into master.

The implementation supports choosing the number of threads, and we can even add a rate-limiter to throttle the throughput as well.

**Comment by renestach** [comment]
Just a thought: Can we use the throttle to reduce the local resource usage to a friedly level?

**Comment by mayou36** [comment]
Hi all, what's the status of this?

**Comment by ts678** [comment]
[v2.0.3.6-2.0.3.6_canary_2018-04-23](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.6-2.0.3.6_canary_2018-04-23)

~~~
This update adds concurrent processing for the backup. With this update, the backup will now use multiple cores to perform checking and compressing.
Use the advanced option --concurrency-max-threads to toggle how many threads to use.
The options --concurrency-block-hashers and --concurrency-compressors can be used to adjust the number of hashers and compressors to use.

Beware that this update contains a lot of new code, and should only be used in test environments.
~~~

[Merging in concurrent_processing](https://forum.duplicati.com/t/merging-in-concurrent-processing/3308) has some developer insights and technical details. I think this is done.

**Comment by mayou36** [comment]
Great, thanks a lot for the work!

**Comment by warwickmm** [comment]
This was added in v2.0.3.6.
