### ISSUE TITLE
403 Forbidden - Quota Limits with GDrive

### ISSUE THREAD

**Issue by idlesys** [duplicati/duplicati#3186]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3
- **Operating system**: Windows 10
- **Backend**: Google Drive

## Description

I am getting 403 forbidden errors when trying to back up to Google Drive. The first and second errors I got were different, but unfortunately, I uninstalled the program and removed the original back up because it just sat on "rebuilding database" when I killed the program and restarted it hours ago.

I'm attempting to back up a NAS with 1TB+ storage. Around 750gb was uploaded in ~18 hours. After that, the program seized up around 5 hours ago because Google returned a 403 message. I have since been unable to get Duplicati to restart the upload. 

This could very well be an issue on Google's end, but it's mind boggling to me. I'm getting: 403- forbidden: Backend quota has been exceeded: Using 0 bytes of 10.00 TB (0 bytes available)

## Steps to reproduce

1. End processes for Duplicati and relaunch
2. Restart PC involved
3. Reinstall Duplicati
4. Remove original backup from Google Drive and Duplicati and create a new back up in Duplicati

- **Actual result**:
Quota Errors
- **Expected result**:
Files to upload to Google Drive

## Debug log

`Backend quota has been exceeded: Using 0 bytes of 10.00 TB (0 bytes available)`

**Comment by idlesys** [comment]
It has started to work at the scheduled backup time. I'll see if it errors out later tonight/tomorrow.

**Comment by AGSPhoenix** [comment]
Google Drive has an undocumented limit of 750 GB uploaded per day. The Drive backend in Duplicati should account for this, and more gracefully handle the limit.

Additionally, the limit is per account, not per application, so simply uploading ~740 GB per day then stopping won't be sufficient, as other uploads to that account will contribute to the limit. Duplicati needs to be able to detect the 403 and back off for a few hours and continue automatically.

**Comment by idlesys** [comment]
@AGSPhoenix Thank you for your response - I *figured* it was a GDrive limitation but I couldn't find any documentation anywhere or anything from any source about a limit on how much you can upload per day. The only other backup program I used was Arq and it took like 1-2 weeks to upload 3tb so I never was able to hit 750GB+ a day on it.

**Comment by warwickmm** [comment]
Sounds like this is an issue with Google Drive, so I'll go ahead and close this issue.

The 750 GB per day limit seems to be documented [here](https://support.google.com/a/answer/172541?hl=en).
