### ISSUE TITLE
Official Docker images for ARM

### ISSUE THREAD

**Issue by fkrull** [duplicati/duplicati#3196]
Duplicati now has [official Docker images](https://hub.docker.com/r/duplicati/duplicati/), but only for amd64. The ARM build works for me (using QEMU in a Linux VM), but apparently doesn't work with Docker for Mac (see PR #3029). But I'd still like official ARM images as well. This is a followup to #2309, for tracking the ARM aspect.

----

These were the last suggestions I made. I can't try any of it since I don't have a Mac.

* You could try my QEMU binaries: [fkrull/qemu-user-static](https://hub.docker.com/r/fkrull/qemu-user-static/):
    ```
    docker run --rm --privileged fkrull/qemu-user-static enable
    ```
    These are the ones I use on my VMs for cross-building. Docker for Mac has a feature like that built-in, so I don't know what'll happen when you run that command, but it shouldn't break anything that can't be fixed with a Docker restart. Besides, I'm curious. :D Maybe it'll help.

* If that doesn't work, you might have to use an actual Linux VM with Docker and QEMU emulation. I have [my own that I currently use](https://github.com/fkrull/docker-gui-host), but anything should work.

**Comment by fkrull** [comment]
@kenkendk Oh, these are in the latest builds now; so you've managed to fix the ARM images?

**Comment by warwickmm** [comment]
ARM images are being built.
