### ISSUE TITLE
Warnings for Metadata Not Changed in v2.0.3.6-2.0.3.6_canary_2018-04-23

### ISSUE THREAD

**Issue by asterr** [duplicati/duplicati#3204]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
Duplicati Version: v2.0.3.6-2.0.3.6_canary_2018-04-23
Operating System: Windows 10
Backend: Local

## Description
After upgrading to 2.0.3.6_canary (from 2.0.3.5_canary), backup logs now report warnings like:

2018-05-03 08:44:59 +09 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-UnexpextedMetadataLookup]: Metadata was reported as not changed, but still requires being added?
Hash: qiXpeARtaA74dA2Dfm3lvB4qLcYInb2hASVEtTjVP2U=, Length: 5, ID: 250318

## Steps to reproduce
1. Run the backup

- **Actual result**:
Warnings appear like this:
2018-05-03 08:44:59 +09 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-UnexpextedMetadataLookup]: Metadata was reported as not changed, but still requires being added?
Hash: qiXpeARtaA74dA2Dfm3lvB4qLcYInb2hASVEtTjVP2U=, Length: 5, ID: 250318

- **Expected result**:
No warnings about Metadata not changed.
Replace me

- ** Notes**
My own quick and amateur investigation leads me to suspect that maybe the new parallel processing of metadata and file backup is happening out of order.  But I am not certain and don't really understand the code base.

The error message is in: Duplicati/Library/Main/Operation/FilelistProcessor.cs and seems to have been added in this commit: 79f7b22e0f05f56ddf638d4e731f47ab6f97672d

**Comment by mmiat** [comment]
me too, i downgraded to 2.0.3.2

**Comment by mr-flibble** [comment]
I have this problem after upgrading to 2.0.3.7 (from 2.0.3.5)
Also _Modified data_ and _New data_ showing 0.00 B

**Comment by ethauvin** [comment]
Same problem upgrading to 2.0.3.7. Backups that used to take minutes now take hours.

**Comment by JonMikelV** [comment]
Note that this is also being discussed on the Duplicati forum @ https://forum.duplicati.com/t/metadata-was-reported-as-not-changed-but-still-requires-being-added/3320.
