### ISSUE TITLE
Backing up to Shared folder of OneDrive Personal?

### ISSUE THREAD

**Issue by rdae** [duplicati/duplicati#3207]
## Environment info
- **Duplicati version**: 2.0.3.5_canary_2018-04-13
- **Operating system**: Windows 10
- **Backend**: OneDrive v2

## Description
Is there a way to back up to a [Shared folder of another OneDrive](https://support.office.com/en-us/article/share-onedrive-files-and-folders-9fcc2f7d-de0c-4cec-93b0-a82024800c07)?

**Comment by tygill** [comment]
I believe it will work, but I haven't personally tested it. For it to work, I believe you will need to add the shared folder to your own drive. Then, if you specify the path to the shared folder, I believe the OneDrive v2 backend should just work (as according to the [MS Graph API docs](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/onedrive#shared-folders-and-remote-items), shared items appear as regular items with just an extra facet indicating they are remote items).

Note that in this case, I believe the contents of the folder will still count against your own account's quota - so I don't think this will work as a way to link an account with a larger quota to an account with a smaller quota.

There might technically be a way to modify the backend to work against a shared drive without adding it to your own account, but I'm not really sure what the MS Graph REST path for that would look like.

**Comment by rdae** [comment]
The real need is to spread the back up over multiple cloud drives of varying sizes (OneDrive 1 TB plans or free tiers). Or, would backing up to a [Stablebit CloudDrive](https://stablebit.com/CloudDrive) and [DrivePool](https://stablebit.com/DrivePool) which then takes care of uploading the file. It is two more layers however.

**Comment by ts678** [comment]
As part of GitHub Issues cleanup, I'm going to ask if the answer from the expert takes care of your original question.
The follow-on question sounds like there's either a workaround or a feature request (not likely to get done) in mind.
[The RAID backend #479](https://github.com/duplicati/duplicati/issues/479#issuecomment-1879412911) were my recent thoughts (among others) on the wish to aggregate multiple cloud storages.
