### ISSUE TITLE
Incremental backup seems to be slow

### ISSUE THREAD

**Issue by jmarceli** [duplicati/duplicati#3212]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Mac OS X High Sierra
- **Hardware**: MacBook Pro (Mid 2014)
- **Backend**: Backblaze B2

## Description
Is it normal that incremental backup of my home dir executed once a day takes about 1:40 hour to finish? (I would expect it to take no more than 15min)
My backup source size is 50GB / ~ 1.5M files (which is not so big I think).
Most of the time is spent on the "Counting files" step.
Is it possible that this behavior is caused by the number of exclusions I've made?
Is it better to build one big regex or several smaller?

My filters look as follows:
```
-[.*\.DS_Store]
-[.*\.tmp]
-[%HOME%/Work/vagrant/www/shops/.*/(serialization|cache|logs)/\S+]
-[%HOME%/Work/vagrant/www/shops/.*/lib/(Doctrine|HTMLPurifier|OAuth|PasswordHash|Symfony|Twig|imageGD|jsonRPCClient|phpmailer|tcpdf|xajax|zip)\S+]
-[%HOME%/Work/vagrant/www/shops/.*/_js_libs/\S+]
-[%HOME%/Work/vagrant/www/shops/.*/_gallery/_[^orginal]\S+]
-[%HOME%/Work/vagrant/www/shops/.*themes/.*\.zip]
-[.*/node_modules.*]
-[.*/bower_components.*]
-[%HOME%/Work/vagrant/www/presta/.*/?cache/\S+]
-[%HOME%/Work/vagrant/www/wordpress/.*/?cache/\S+]
-[%HOME%/Work/vagrant/www/wordpress/.*app/themes/.*dist.*]
-[%HOME%/Work/vagrant/www/wordpress/.*app/themes/.*vendor/.*]
-[%HOME%/Work/vagrant/www/wordpress/.*(vendor|fly-images)/.*]
-[%HOME%/Work/ruby/.*log/\S+]
-[%HOME%/Work/ruby/.*tmp/\S+]
-%HOME%/Library/Saved Application State/
-%HOME%/Dropbox/
-%HOME%/Calibre Library/
-%HOME%/Azure/
-%HOME%/Movies/
-%HOME%/Music/
-%HOME%/VboxShared/
-%HOME%/VirtualBox VMs/
-%HOME%/backup_test/
-%HOME%/tmp/
-%HOME%/.babel-cache/
-%HOME%/.cache/
-%HOME%/.composer/
-%HOME%/.cordova/
-%HOME%/.cups/
-%HOME%/.dropbox/
-%HOME%/.docker/
-%HOME%/.electron/
-%HOME%/.electron-gyp/
-%HOME%/.fontconfig/
-%HOME%/.gem/
-%HOME%/.ghost/
-%HOME%/.grip/
-%HOME%/.heroku/
-%HOME%/.ievms/
-%HOME%/.ionic/
-%HOME%/.kayak-installer/
-%HOME%/.kube/
-%HOME%/.jspm/
-%HOME%/.meteor/
-%HOME%/.local/
-%HOME%/.ngrok/
-%HOME%/.node-gyp/
-%HOME%/.npm/
-%HOME%/.nvm/
-%HOME%/.oracle_jre_usage/
-%HOME%/.pachyderm/
-%HOME%/.pgadmin/
-%HOME%/.prisma/
-%HOME%/.putty/
-%HOME%/.raygun/
-%HOME%/.reaction/
-%HOME%/.rvm/
-%HOME%/.subversion/
-%HOME%/.vagrant.d/
-%HOME%/.wireshark/
-%HOME%/.wireshark-etc/
-%HOME%/.wp-cli/
-%HOME%/.yarn/
-%HOME%/.Trash/
-%HOME%/Downloads/
-%HOME%/Library/Logs/
-%HOME%/Library/iMovie/
-%HOME%/Library/iTunes/
-%HOME%/Library/WebKit/
-%HOME%/Library/VirtualBox/
-%HOME%/Library/Dropbox/
-%HOME%/Library/Caches/
-%HOME%/lib/azure-cli/
-%HOME%/Library/SafariSafeBrowsing/
-%HOME%/Library/Audio/
-%HOME%/Library/Developer/
-%HOME%/Library/Internet Plug-Ins/
-%HOME%/Library/Keyboard/
-%HOME%/Library/Keyboard Layouts/
-%HOME%/Library/KeyboardServices/
-%HOME%/Library/LanguageModeling/
-%HOME%/Library/LaunchAgents/
-%HOME%/Library/Maps/
-%HOME%/Library/Spelling/
-%HOME%/Library/Speech/
-%HOME%/Library/Suggestions/
-%HOME%/Library/Voices/
-%HOME%/Library/Address Book Plug-Ins/
-%HOME%/Library/Dictionaries/
-%HOME%/Library/Application Support/
-%HOME%/Work/vagrant/www/presta/prestashop_clean_1614/
-%HOME%/Work/vagrant/www/presta/prestashop_1.6.1.6.zip
-%HOME%/Work/vagrant/www/presta/prestashop_1.6.1.6/
-%HOME%/Work/vagrant/www/presta/prestashop_1.6.1.4.zip
-%HOME%/Work/vagrant/www/presta/kotm_1614/
-%HOME%/Work/vagrant/www/presta/demo17/
-%HOME%/Work/vagrant/www/presta/demo/
-%HOME%/Work/vagrant/www/drupal/
-%HOME%/.azure/
-%HOME%/.android/
```

**Comment by mr-flibble** [comment]
Hello, problem probably is 1,5M of files
Duplicati have to scan each of them to see if they changed (by date modified)

Try add this parametr to backup:
**--disable-file-scanner=true** 
_When this flag is enabled, the scanner that computes the size of source files is disabled, and instead the reported size is read from the database. Using this flag can speed up the backup by reducing disk access, but will give a less accurate progress indicator._

**Comment by jmarceli** [comment]
Hi, Thanks for the reply.
I've switched on `disable-file-scanner` (in backup configuration > options > advanced options), but progress information (e.g. `1335247 files (49.99 GB) to go`) is still there an I see no performance boost.
Maybe 1.5M file is too many to be performant?

**Comment by mr-flibble** [comment]
Hello, with disable-file-scanner you will still see progress information, but data for that are from DB/last backup - so it is not exact. 

1.5M of files is a lot.
Until Duplicati have some filetracking change ability like Crashplan, we can't expect huge environment. Every backup have to compare metadata of every file with internal sqlite DB, so it take time. 

My backup with 1,4M files is taking 5 hours every day (on 7200 raid1 server 2,5 disks). Maybe DB on SSD drive can speed that up.

Sometimes is take longer (screenshot from https://www.duplicati-monitoring.com )
![image](https://user-images.githubusercontent.com/5197625/39966924-c9812848-56b3-11e8-94ad-b70101f4f34d.png)

**Comment by jmarceli** [comment]
Thanks for the clarification. I have only SSD drive, so there is no chance for hardware-based improvement. Do you think that excluding more files through filtering can help? (I mean adding more exclusions)

The idea (maybe bad):
How about a folder size based comparison? If folder size changes the program should scan folders inside it repeating this step recurrently, if not, folder may be skipped (possibly ignoring thousands of files inside it).
It should improve performance tremendously and a case where file size after modification doesn't change is (probably) rare.

**Comment by mr-flibble** [comment]
I would try to visualize (for example http://www.jgoodies.com/freeware/jdiskreport/ ) number of files in my source folders and then maybe create multiple backup jobs. So my most important data could be backed up faster/more often and other data maybe less often. 


Folder size based comparison should be fast, but I think it can be very dangerous in general. For example if you in text document change single character, size remain same. I don't know if some backup program uses it. 

Your backup/scanning speed is (if I count correctly) 297 files per second, that is relative fast :)

**Comment by jmarceli** [comment]
Thanks for the guidance. I like your solution with infrequent backups for part of my data (that should work fine).
