### ISSUE TITLE
Backblaze B2 - 400 - bad_request: File names must not contain '\'

### ISSUE THREAD

**Issue by ABonner** [duplicati/duplicati#3214]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3
- **Operating system**: Windows 10 Insider
- **Backend**: Backblaze B2

## Description

After configuring a backup to Backblaze B2, it fails when trying to write files to B2 with the following error:

Operation Put with file duplicati-20180511T214615Z.dlist.zip.aes attempt 1 of 5 failed with message: 400 - bad_request: File names must not contain '\'

## Steps to reproduce

1. Create a new Backup
2. Configure to send to BackBlaze B2
3. Click "Run Now"
4. Error shows up as a red message popup, no files are posted to B2

- **Actual result**:
Files are scanned and backup to B2 starts, but no files are written and it fails
- **Expected result**:
Files are successfully written to B2, or a more useful error message is displayed if the error is not related to the filename.

**Comment by warwickmm** [comment]
This probably suggests that some path separator normalization that should be performed.

In the meantime, does the suggestion in [this post](https://forum.duplicati.com/t/solution-to-b2-cloud-error-file-name-must-not-contain-on-windows/2326) help?

**Comment by ABonner** [comment]
@warwickmm Thank you, that was indeed the issue. Sorry for not searching the forum as well (didn't know it existed and Google didn't pick it up).

I'd be interested in fixing this for future users, I had "c:\backup" in that field, the name "Folder Path" was confusing and I thought it was looking for a local directory.

If you have any insight on a good fix, I could think of 2:
- Validation on the field based on the endpoint
- Better description of the field

**Comment by warwickmm** [comment]
Additional validation of the B2 fields was introduced in revision  af3e9cdfdc5efce82e77971ca7752ea727cb9249 and included in the [2.0.3.7](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.7-2.0.3.7_canary_2018-06-17) release.
