### ISSUE TITLE
Uninstallation instructions for supported platforms

### ISSUE THREAD

**Issue by 13am** [duplicati/duplicati#3217]
How do I uninstall Duplicati? Where are the uninstallation instructions?

**Comment by piegamesde** [comment]
Which platform are you using?

**Comment by 13am** [comment]
I'm using (Fedora) Linux. It would be useful to have the instructions in one place for all platforms!

**Comment by 13am** [comment]
Done! Here: https://github.com/kees-z/DuplicatiDocs/issues/10
