### ISSUE TITLE
Steadily using 25% CPU and service trying to restart continuously.

### ISSUE THREAD

**Issue by capgros** [duplicati/duplicati#3222]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.4_canary_2018-04-02
- **Operating system**: Windows 2008R2
- **Backend**: SFTP

## Description

Duplicati.Server.Exe is steadily using 25% CPU even when not doing backups.
An event is being issued every 7 seconds approx: 

- Attempting to restart server process: C:\Program Files\Duplicati  2\Duplicati.Server.exe

Backups are informed as being done once a day as scheduled.

## Steps to reproduce

- **Actual result**:
To much CPU usage, Duplicati trying to restart.
- **Expected result**:
Cpu usage when doing a backup. Duplicati not trying to restart.

## Screenshots

![image](https://user-images.githubusercontent.com/12518582/40120415-6882e144-591f-11e8-934a-d9610970d94f.png)

**Comment by Germs2004** [comment]
Is there any relevant information in the Duplicati main log?  Click About > Show Log.

Also, in services.msc, open the Duplicati service, and tell us what you have selected for First Failure, Second Failure, Subsequent Failures, Reset Fail Count After, and Restart Service After.

**Comment by capgros** [comment]
Thank you for your answer!
I've updated from 2.0.3.4 to 2.0.3.6_canary_2018-04-23 and now I don't see this peaks. 
I was hesitant due to the new changes introduced but finally did and now it's working flawlessly (I did today)
I'll keep an eye and report updates if any.

Again, thank you for your kind help.

Miguel
