### ISSUE TITLE
Prompting for encryption passphrase uses 100% of CPU

### ISSUE THREAD

**Issue by mhorowitz** [duplicati/duplicati#3245]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: macOS 10.12.6
- **Backend**: b2, ssh

## Description
Running cli commands which prompt for encryption key spin using 100% of the CPU.  I get the prompt `Enter encryption passphrase:`, then before I even type the password, the process starts using 100% of the CPU.  If I type a password here, it echos.  At this point, nothing ever seems to happen again.

This did not happen with 2.0.2.1

## Steps to reproduce
1. duplicati-cli test b2://... 1

- **Actual result**:
100% CPU in Activity Montor
- **Expected result**:
whatever the command is supposed to do.  Not echoing my encryption key.

Also repros with `ssh://` url, or with `list-broken-files` command.  `help` works fine.

If I use the `--passphrase` cli flag, instead of entering the key interactively, everything appears to work fine.

## Debug log
I tried using the --logfile option, but it wasn't created.

**Comment by verhoek** [comment]
I also encountered this behavior and implemented a fix. The reason this happens: a child process is started that uses Console.ReadKey within a while(true) loop, but the standard input is never correctly redirected to the child process. I am still checking if there are other places in the code where similar things happen, and will then open a pull request.

**Comment by warwickmm** [comment]
Fixed in pull request #3267.
