### ISSUE TITLE
Slow Download speed with Jottacloud in case of recovery

### ISSUE THREAD

**Issue by theincogtion** [duplicati/duplicati#3248]
- **Duplicati version**: 2.0.3.5
- **Operating system**: QNAP QTS (Linux)
- **Backend**: RJottacloud

## Description
Download from one file only is incredibly slow
Download one single file from Jottacloud gives you maximum 2MB/s
With Jottacloud Software it is possible to Download 6x faster because it allows 6 parellel downloads

## Steps to reproduce
Restore files from Jottacloud

## Screenshots
Duplicati performance
![grafik](https://user-images.githubusercontent.com/10852327/40731157-c0e62690-6430-11e8-9bb4-fb6700dfd180.png)

Jottacloud Software Download 6x streams

![grafik](https://user-images.githubusercontent.com/10852327/40731293-043abe92-6431-11e8-9a03-e6f85d57642d.png)

Jottacloud Software single Download
![grafik](https://user-images.githubusercontent.com/10852327/40731418-4a2f2f1e-6431-11e8-8ecf-ac9a2ba16504.png)

Looks for me if parallelity would solve the issue.

**Comment by albertony** [comment]
This seems to be similar to #2026 (that one is more focused on upload, but it does also mention download), and then it is not something specific to this backend implementation but more a general issue -  and not a trivial one: 

> My conclusion: it is not an easy extension, I think it requires a complete rewrite of the BackendManager and that possibly has repercussions on the rest of Duplicati. Not sure if anyone is up for such a daunting task.

That being said, Jottacloud seem to be moving to a newer API in their own clients. Upgrading our backend to that could perhaps speed things up, although I think they use it only for uploads. Unfortunately I haven't figured out all the necessary details about how it works yet..
