### ISSUE TITLE
Cachedir tag support [feature request]

### ISSUE THREAD

**Issue by djtm** [duplicati/duplicati#3250]
- [x ] I have searched open and closed issues for duplicates.

## Description

You can create a file in directories you don't want to back up:
http://www.brynosaurus.com/cachedir/spec.html

## Steps to reproduce

1. `cachedir tag /tmp/`
2. start backup
3. backup ignores /tmp

**Comment by warwickmm** [comment]
I think issue #1482 describes the same feature.  I'm going to close this as a duplicate, as there's more discussion happening in #1482.  If you think this is a different issue, please feel free to re-open.
