### ISSUE TITLE
Fedora Install Fails

### ISSUE THREAD

**Issue by LanceHaverkamp** [duplicati/duplicati#3258]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3
- **Operating system**: Fedora 28 KDE Plasma desktop
- **Backend**: Didn't get that far
## Description

Install fails repeatedly.  Error message: Bad GPG Signature
...and no installation has taken place:
$ duplicati
bash: duplicati: command not found

## Steps to reproduce
1. Click on your fedora link
2. Open with "Discover" (the KDE package manager)
3. read error message

- **Actual result**:
Install fails
- **Expected result**:
that the software manager installs the duplicati & all needed dependencies.

**Comment by oedm** [comment]
Hi Lance,

I got it installed via `sudo dnf install ./duplicati-2.0.3.3-2.0.3.3_beta_20180402.noarch.rpm` on Fedora 28.
Maybe you can give it a try.

Best,
Marcel

**Comment by LanceHaverkamp** [comment]
Yes that did work for me as well.  I am liking Fedora & KDE (having spent more than a decade in Debian based distro's), but have found the the GUI Package installer "Discover" to be reliable with widely used programs, but far less reliable on lesser used programs.
