### ISSUE TITLE
Ignore log out - starts from tray w/o password request even after logout

### ISSUE THREAD

**Issue by SaintDI** [duplicati/duplicati#3260]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: `2.0.3.3_beta_2018-04-02`
- **Operating system**: Windows 10, 1803
- **Backend**: local

## Description

Ignore log out - starts from tray w/o password request even after logout

## Steps to reproduce

1. Log out
2. Open duplicati from a tray icon
3. Login w/o password request

- **Actual result**:
Login w/o password request
- **Expected result**:
Must request a password if it were setted

## Screenshots

[duplicati-logoff-bug.zip](https://github.com/duplicati/duplicati/files/2074781/duplicati-logoff-bug.zip)

**Comment by SaintDI** [comment]
Thanks for the link to discussion.

I generally agree with [JonMikelV](https://forum.duplicati.com/t/tray-icon-bypasses-ui-password/3727/8) suggestion:

>Of course some people will like it one way and others the other way, so maybe there should be a “Tray-icon requires password” checkbox (defaulted to false) that is enabled when a password is entered into settings.
>
>And going down that rabbit hole brings up the question of should there be a timeout on the password login (e.g. Logout X mins after last interaction)… :slight_smile:

**Comment by ts678** [comment]
The original problem appears to have been corrected (per forum discussion) by having Settings give a choice:

![image](https://github.com/duplicati/duplicati/assets/40771998/a6feafd0-1635-40a5-8f51-53d0fd1a9c0f)

Checking above option prevents the original problem, so this issue will close unless more discussion happens.
