### ISSUE TITLE
the source folder does not exist - but it does indeed

### ISSUE THREAD

**Issue by klevstul** [duplicati/duplicati#3261]
## Environment info

- **Duplicati version**: Duplicati - 2.0.3.6_canary_2018-04-23 - [aur](https://aur.archlinux.org/packages/duplicati-latest)
- **Operating system**: Manjaro Linux 17.1.10 Hakoila
- **Backend**: Amazon S3

## Description
when i try to set up a backup of a specific folder duplicati states the folder doesn't exist. however, it does exist. there are several folders that do not exist. i am for example also unable to browser through my home directory.

note: i am not sure if this is related to the [aur package](https://aur.archlinux.org/packages/duplicati-latest) only, and hence not a duplicati related problem.

## Steps to reproduce
1. install duplicati on arch / manjaro
2. start: `$ systemctl start duplicati`
3. open http://localhost:8200
4. set up new backup
5. forward to the step where you chose files and folders to be backed up

- **Actual result**:
`The source folder /run/media/klevstul/raid/local-drive/ does not exist, aborting backup`

- **Expected result**:
sucessful backup.

## Screenshots
cli:
![image](https://user-images.githubusercontent.com/216850/41095702-94f1ed44-6a52-11e8-98e3-000d9b011043.png)

folder:
![image](https://user-images.githubusercontent.com/216850/41095679-7eabde8c-6a52-11e8-86d0-1faac1d83c1f.png)

![image](https://user-images.githubusercontent.com/216850/41096119-edcbf26a-6a53-11e8-9b11-f3c02a136c2c.png)

error:
![image](https://user-images.githubusercontent.com/216850/41095654-6962277a-6a52-11e8-8397-e31074112094.png)

## Debug log
Jun 7, 2018 1:09 PM: Request for http://localhost:8200/api/v1/backup/1/log?pagesize=100 gave error
```
Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error no such table: LogData at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x001f8] in <9c1af81eae9346d4aa4db3ad33a9a5af>:0 at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x000d3] in <9c1af81eae9346d4aa4db3ad33a9a5af>:0 at Mono.Data.Sqlite.SqliteCommand.GetStatement (System.Int32 index) [0x00008] in <9c1af81eae9346d4aa4db3ad33a9a5af>:0 at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteCommand.GetStatement(int) at Mono.Data.Sqlite.SqliteDataReader.NextResult () [0x000b3] in <9c1af81eae9346d4aa4db3ad33a9a5af>:0 at Mono.Data.Sqlite.SqliteDataReader..ctor (Mono.Data.Sqlite.SqliteCommand cmd, System.Data.CommandBehavior behave) [0x0004e] in <9c1af81eae9346d4aa4db3ad33a9a5af>:0 at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteDataReader..ctor(Mono.Data.Sqlite.SqliteCommand,System.Data.CommandBehavior) at Mono.Data.Sqlite.SqliteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00006] in <9c1af81eae9346d4aa4db3ad33a9a5af>:0 at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader (System.Data.CommandBehavior behavior) [0x00000] in <9c1af81eae9346d4aa4db3ad33a9a5af>:0 at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader () [0x00000] in <36fccbb4931a4810ae300115d76905ac>:0 at Duplicati.Server.WebServer.RESTMethods.LogData.DumpTable (System.Data.IDbCommand cmd, System.String tablename, System.String pagingfield, System.String offset_str, System.String pagesize_str) [0x000da] in <62a3c38a5c9c4c6181771976288a28b1>:0 at Duplicati.Server.WebServer.RESTMethods.Backup.FetchLogData (Duplicati.Server.Serialization.Interface.IBackup backup, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x00054] in <62a3c38a5c9c4c6181771976288a28b1>:0 at Duplicati.Server.WebServer.RESTMethods.Backup.GET (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x001e4] in <62a3c38a5c9c4c6181771976288a28b1>:0 at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x00140] in <62a3c38a5c9c4c6181771976288a28b1>:0 
```
Jun 7, 2018 1:09 PM: Reporting error gave error
```
System.ObjectDisposedException: Cannot write to a closed TextWriter. at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x00008] in <cae080c8689e4af39d0ab2b313d012f5>:0 at System.IO.StreamWriter.Flush () [0x00006] in <cae080c8689e4af39d0ab2b313d012f5>:0 at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x003a5] in <62a3c38a5c9c4c6181771976288a28b1>:0 
```

**Comment by verhoek** [comment]
What are the permissions of the source folder?

**Comment by klevstul** [comment]
@verhoek 

i run `systemctl start duplicati` as root, hence all folder should be accessible.

by the way, in the gui i get these warning icons for heaps of directories:
![image](https://user-images.githubusercontent.com/216850/41196052-97e25786-6c38-11e8-9c93-29658f08e0d9.png)
so by some reason, duplicati is unable to access these directories.

**Comment by verhoek** [comment]
The fact that you run systemctl start duplicati as root, does not automatically imply duplicati runs as root. Also that your user account can access these files does not mean that duplicati can. I am not sure, but it sounds like duplicati is running with some technical user account and this account does not have access to all files.

**Comment by klevstul** [comment]
@verhoek 

once again, thanks a lot for your assistance. you were absolutely right in your suggestion. duplicati ran as user `duplicati` which hadn't the sufficient access rights. i changed the user to my normal user and re-ran duplicat, which then worked.

for the record, changed user editing the `.service` file:
`$ sudo nano /usr/lib/systemd/system/duplicati.service`

thanks for this great tool!
