### ISSUE TITLE
Upload speed issues 

### ISSUE THREAD

**Issue by SudoUser-Sam** [duplicati/duplicati#3269]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.5_canary_2018-04-13
- **Operating system**: Lubuntu 18.04
- **Backend**: Google Drive

## Description

Frequent upload speed dips, With some stalls.

**(5GB Test file used)**
Upload speed directly to **Google Drive**: **18MB/s**
Upload speed from **Duplicati** to Google Drive: **12MB/s** (with constant stalls and dips to the KB/s)

There is no other device connected to this network besides the machine using Duplicati all bandwidth is available.

options used: 
--dblock-size=100MB
--use-block-cache=true
--no-encryption=true (disabled to reduce variable of issues)

## Screenshots

Not using all available bandwidth.
![max upload reached](https://user-images.githubusercontent.com/25883052/41356859-9ddeb5e6-6ed9-11e8-92ff-012bb7d47e77.png)

Frequent stalls visual graph on the right showing it, top is WAN bottom is LAN (nas connection).
![stall](https://user-images.githubusercontent.com/25883052/41356860-9e0d159e-6ed9-11e8-8afb-e2229f867c32.png)

Dips into the low KB/s very often use graph as visual.
![kb dip](https://user-images.githubusercontent.com/25883052/41356861-9e30c19c-6ed9-11e8-9f74-4c75861afefe.png)

**Comment by junderhill** [comment]
Forgive my ignorance but what would immediately jump to mind as a possible cause is the overhead of the compression and splitting of the blocks perhaps?

**Comment by warwickmm** [comment]
Yes, there are several operations that would be cpu bound that can prevent full upload bandwidth from being used.
