### ISSUE TITLE
stdio output completely suppressed / missing

### ISSUE THREAD

**Issue by SamiLehtinen** [duplicati/duplicati#3284]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: v2.0.3.7
- **Operating system**: Windows 64x
- **Backend**: Irrelevant

## Description

Output to stdio is being completely suppressed. There's no output whatsoever. Even when running simple commands like help.

PS C:\Program Files\Duplicati 2> .\Duplicati.CommandLine.exe help
PS C:\Program Files\Duplicati 2>

## Steps to reproduce

1. Install latest version
2. Open PowerShell / cmd
3. Run Duplicati.CommandLine.exe help
4. Nothing, nothing at all.

Remark, also the configured log file is completely empty. But the backup itself with correct parameters did run successfully.

- **Actual result**:
[null]
- **Expected result**:
The usual help text.

## Discussion
https://forum.duplicati.com/t/no-console-output-in-v2-0-3-7/3867

**Comment by ulipp** [comment]
UNDER WINDOWS, its the same to me. (no output)
UNDER LINUX output is correct. (output)

**Comment by kees-z** [comment]
This issue is discussed [here](https://forum.duplicati.com/t/no-console-output-in-v2-0-3-7/3867?u=kees-z).
.

**Comment by warwickmm** [comment]
I believe this was resolved in version 2.0.3.8.
