### ISSUE TITLE
Support for Backend "Zoolz"

### ISSUE THREAD

**Issue by khasenklever** [duplicati/duplicati#3290]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Debian Stretch
- **Backend**: Zoolz

## Description

Add support for Backend [Zoolz](https://home.zoolz.co.uk/)
1TB for 39.95€/Year seems like an attractive offer for most home-users.

**Comment by djtm** [comment]
Workaround: use jottacloud: 75 € / Year for unlimited.

**Comment by Pectojin** [comment]
There doesn't seem to be any API for uploading or downloading files for Zoolz. The only available API is for resellers to [manage accounts](http://wiki.zoolz.com/category/reseller/reseller-api/)

Without an explicit developer API I don't see any way to add this backend without basically guessing and reverse-engineering the entire client.

That's all assuming it's even a simple get/put/delete interface. Their client looks pretty complex feature-wise, so it might be much more complicated.
