### ISSUE TITLE
Error accessing file when using VSS on drive root

### ISSUE THREAD

**Issue by JonMikelV** [duplicati/duplicati#3300]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.7 & 2.0.3.8
- **Operating system**: Windows
- **Backend**: N/A

## Description

When using as VSS setting such as `--snapshot-policy=auto` on a backup that includes the root folder of a drive, the backup "succeeds" with the WARNING `[Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: E:\ `

## Steps to reproduce

1. Create a backup job with `--snapshot-policy=auto` that includes a drive root as source
2. Run the job

- **Actual result**:
 Warnings: [ 2018-06-28 12:22:35 -05 - [Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: E:\ ] 
- **Expected result**:
VSS should work as expected even on a drive root.

## Debug log

```json
Jun 28, 2018 12:32 PM: Error reported while accessing file: E:\
{
"ClassName":"System.IO.IOException",
"Message":"(123) The filename, directory name, or volume label syntax is incorrect: [\\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy26]",
"Data":null,
"InnerException":null,
"HelpURL":null,
"StackTraceString":"  
 at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)  
 at Alphaleonis.Win32.Filesystem.File.GetAttributesExCore[T](KernelTransaction transaction, String path, PathFormat pathFormat, Boolean returnErrorOnNotFound)  
 at Duplicati.Library.Snapshots.SystemIOWindows.GetFileAttributes(String path)  
 at Duplicati.Library.Utility.Utility.<EnumerateFileSystemEntries>d__23.MoveNext()",
"RemoteStackTraceString":null,
"RemoteStackIndex":0,
"ExceptionMethod":"8
ThrowException
AlphaFS, Version=2.1.0.0, Culture=neutral, PublicKeyToken=4d31a58f7d7ad5c9
Alphaleonis.Win32.NativeError
Void ThrowException(UInt32, System.String, System.String)",
"HResult":-2147024773,
"Source":"AlphaFS",
"WatsonBuckets":null
}
```

**Comment by ts678** [comment]
Not reproducible. Maybe something got fixed.

> When using as VSS setting such as --snapshot-policy=auto on a backup that includes the root folder of a drive

Tested with `--snapshot-policy=On` and `C:\`

I got some other expected warnings, all `System.UnauthorizedAccessException` (2.0.7.100 Canary log has details).

Anything else? If not, this will eventually close.
