### ISSUE TITLE
Retention policy code

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#3306]
Im playing with retention-policy. I was looking to code if backups older than specified timeframe are deleted.

This is code which is by my understanding deleting.
https://github.com/duplicati/duplicati/blob/e70f15287e77708a475471a5a24596ac2fa79f13/Duplicati/Library/Main/Operation/DeleteHandler.cs#L219

But the description commend confuses me  "Backups that are not within any of the specified time frames will will NOT be deleted."
https://github.com/duplicati/duplicati/blob/e70f15287e77708a475471a5a24596ac2fa79f13/Duplicati/Library/Main/Operation/DeleteHandler.cs#L297

I think comment L219 is wrong.

**Comment by Pectojin** [comment]
@TekkiWuff

**Comment by ts678** [comment]
> I think comment L219 is wrong.

It was right at first, then plan changed so it's wrong now.

[New retention policy deletes old backups in a smart way](https://forum.duplicati.com/t/new-retention-policy-deletes-old-backups-in-a-smart-way/2195/34?u=ts678)

> **Heads up!:**
We decided to change the `--retention-policy` option a bit: It now deletes backups older than any timeframe by itself, so there is no need anymore to also use `--keep-time` . And to not have any confusing situations with people combining `--retention-policy` with `--keep-time` and `--keep-versions` , these are now all mutual exclusive, meaning you get an error if you have them combined in any way.

[Feature/issue 3008 retention optimizations #3026](https://github.com/duplicati/duplicati/pull/3026)

> As discussed in #3008:
>
>    --retention-policy now deletes backups that are outside of any time frame. No need to specify --keep-time as well. Help text was changed accordingly.
>    --retention-policy is now mutual exclusive to the other retention options --keep-time and --keep-version. Help text was changed accordingly.
>    --retention-policy now complies with --allow-full-removal, deleting even the most recent backup, if it's outside of any time frame
