### ISSUE TITLE
Double database size

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#3310]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.9
- **Operating system**: win
- **Backend**: file

## Description
Im investigating why I have so big database
Using this excel [calculator ](https://docs.google.com/spreadsheets/d/1woKfEqtTHxSidztNqjfmQELyIHu_yE1z0NLBZ8dxOCE/edit#gid=699513107) I should have around 1,3 mio blocks (correct, 100KB block size, 141GB of data), but in database there is 2,6mio blocks

SELECT 
       sum(Size)
  FROM Remotevolume  where type='Blocks' ;

**141718381070 - correct, on remote volume there are 141GB data**
  
SELECT sum(Size)
  FROM Block ;

**275317485976 - incorrect, how this could happened?**

SELECT Block.ID,
       Block.Hash,
       Block.Size,
       Block.VolumeID
  FROM Block INNER JOIN Remotevolume ON  Block.volumeid = Remotevolume.ID
where Remotevolume.state  = 'Deleted'

**Nothing - ok**

**So I tried this to compare blocks to remote blocks - first and last column should be same no?**

SELECT sum(Block.Size), Block.volumeid, Remotevolume.Name, Remotevolume.Size
  FROM Block  INNER JOIN Remotevolume ON  Block.volumeid = Remotevolume.ID where type='Blocks' group by Block.volumeid 

1268326400	2180	Backup_Daily-bf8f3cb2a37d94bd9beed81fcc6d9a96c.dblock.zip.aes	1073656253
1518694400	2182	Backup_Daily-b69ddb46015b448d6984795bcbcb3cfa3.dblock.zip.aes	1073659805
1428377600	2184	Backup_Daily-b78efc7a13a96491981ff8918f25ebdd2.dblock.zip.aes	1073659933
462029074	2343	Backup_Daily-bbdeeb41bdf6849ea84ec949178250eee.dblock.zip.aes	469800893
278528000	2378	Backup_Daily-b45ab2ce5bf4345328d006763a07380d2.dblock.zip.aes	945806829
563302400	2381	Backup_Daily-b3e21c80a83e343fa8fe740461dc0c306.dblock.zip.aes	1073676493
1986048297	2386	Backup_Daily-b983684d6c00040099b7eac967d95072e.dblock.zip.aes	924954669
1797017897	2389	Backup_Daily-b79416e68e1fe47d9bf5a4894956a0c3a.dblock.zip.aes	805500013
2046464297	2392	Backup_Daily-bad9ec4adfa764ff39d004bc74e521ea9.dblock.zip.aes	971630381
1983590697	2395	Backup_Daily-bf4b6a5f481414991ba12c26b47ef0f97.dblock.zip.aes	944895597
1992909097	2398	Backup_Daily-b265355cb244b4eeebece9c77f0546367.dblock.zip.aes	952855773
2551091200	2401	Backup_Daily-bfd9b8b9016de4607aca5edc4b207e5da.dblock.zip.aes	1073643757
2653696000	2403	Backup_Daily-bedf295f357194234bf195e73bbb552cf.dblock.zip.aes	1073643389
1832448000	2405	Backup_Daily-b79d481e7592c4ac187489f1b09ba5a0a.dblock.zip.aes	1073657565
1538457600	2407	Backup_Daily-b3af0577ea5da4f8c9866c4adce55dcc4.dblock.zip.aes	1073680733
1378099200	2409	Backup_Daily-bb489bbc7c4704e03a26fc33c85ca54c9.dblock.zip.aes	1073686925
391898651	2411	Backup_Daily-bb3d963f3e09249cc895be652f1071b43.dblock.zip.aes	392490765
1894502697	2414	Backup_Daily-ba4e33740dbd44f339d034e20b7ec372e.dblock.zip.aes	891160029
2057625897	2417	Backup_Daily-b04fa3961ce9a4486913ce16fb4443d02.dblock.zip.aes	1014864797
1823437097	2420	Backup_Daily-bbe2dae13ba9d4dab85e5f59ae90da42a.dblock.zip.aes	862576269
2174464000	2423	Backup_Daily-b6fac46d9bf044ae2a41da0d9a22801a1.dblock.zip.aes	1073690669
2136985897	2428	Backup_Daily-b22bfbd99b34945caadf42a9cfafba227.dblock.zip.aes	1045003485
1792512297	2431	Backup_Daily-bb1c612f1f91444f1b1da47e0fa3673af.dblock.zip.aes	845910957
1830195497	2434	Backup_Daily-b70f1806dd1af4d72a3b27bb3e9ceedec.dblock.zip.aes	872401965
2631782400	2437	Backup_Daily-b370e9d4a3ade4568b57b80fd1cab3fc1.dblock.zip.aes	1073658029
2616627200	2439	Backup_Daily-b83af2385c19344cebe7afea0f27cb124.dblock.zip.aes	1073643469
1774796800	2441	Backup_Daily-b6b0b917378b1420d9c6598911881dab7.dblock.zip.aes	1073646717
1681305600	2443	Backup_Daily-bc756a9a9ce0a498c8166ffd83a81854e.dblock.zip.aes	1073657261
688858651	2445	Backup_Daily-bdf0169d08674486f8e91a41c74f08d59.dblock.zip.aes	650004205
2002329897	2448	Backup_Daily-bd5c3687c31da41fbb294f02452acdd63.dblock.zip.aes	950854093
2004889600	2451	Backup_Daily-b32705f96848f482b9bbe8d551b7dcd05.dblock.zip.aes	1073652813
2177922313	2456	Backup_Daily-b5e9c9fb7923c4d5ab646317981b2115d.dblock.zip.aes	1055661757
1842562313	2459	Backup_Daily-b856ac874d5c0481794961cba5a589fd2.dblock.zip.aes	845865981
1902978313	2462	Backup_Daily-b98ed40c592a54549814e07b72b67cef6.dblock.zip.aes	867914413
1871951113	2465	Backup_Daily-b30a68de009374f88adc572028d65b04a.dblock.zip.aes	865777021
2102760713	2468	Backup_Daily-b078f45d52fff4aeabf75693f21be3f0c.dblock.zip.aes	1031915053
2025960713	2471	Backup_Daily-ba4107d658a1b4e4e998c227ef7bfee8f.dblock.zip.aes	979535949
1893967113	2474	Backup_Daily-b0aea3f5193444fed86b45fd3cba8d0fb.dblock.zip.aes	880722605
2143823113	2477	Backup_Daily-b90412b94057b4071a99c87c6897b39fc.dblock.zip.aes	1043597821
2073781513	2480	Backup_Daily-bd0eaa2007bb14a7fa762b6fcc44e6d0c.dblock.zip.aes	998253773
2108392713	2483	Backup_Daily-b68c93f3a4a59494da25dba0442972e9f.dblock.zip.aes	1010683805
2180403200	2486	Backup_Daily-be10fac6931e8426ba94cbdf97ae2198a.dblock.zip.aes	1073683501
2107368713	2491	Backup_Daily-be94be9457b67422193e19d97433b70e1.dblock.zip.aes	1034931901
2163381513	2494	Backup_Daily-bb09a5b9941ff4b42b88657595a9f8593.dblock.zip.aes	1065134413
1904002313	2497	Backup_Daily-b11527017beaa479694f4ada6105cc7dc.dblock.zip.aes	887674621
1952744713	2500	Backup_Daily-b9941778396ab4f778a15a31e4e23501d.dblock.zip.aes	932138813
1853928713	2503	Backup_Daily-b80ea6e366beb45f6a5e6c8a52678d818.dblock.zip.aes	875372397
1857307913	2506	Backup_Daily-b842b9560fe024c4d86a93f94492862e4.dblock.zip.aes	876882269
2597068800	2509	Backup_Daily-b992da4be58c74788825900931a70388c.dblock.zip.aes	1073654221
2622873600	2511	Backup_Daily-bcd2b5487f8d840919c344a942b27e2d4.dblock.zip.aes	1073640445
1724723200	2513	Backup_Daily-babd7244ad2c842368408ba717f44d76a.dblock.zip.aes	1073712029
1830707200	2515	Backup_Daily-b6d29d6b045d84491a21af778277ccf9d.dblock.zip.aes	1073711869
1055958953	2517	Backup_Daily-b2af4afa67e4b4af28618633e0b10e163.dblock.zip.aes	1011119805
2375987200	2520	Backup_Daily-b460d8df1f91f44d99b30345a0840336c.dblock.zip.aes	1073706269
2073768507	2522	Backup_Daily-b7893d1c002684895b0d9e8d2e60333a3.dblock.zip.aes	970427421
2235699497	2525	Backup_Daily-bca8cfa28cffb48809a02d51ebbf90f11.dblock.zip.aes	1040602397
2153062400	2528	Backup_Daily-b5c2583c5d1184ac3a9bf6815928a3481.dblock.zip.aes	1073673261
427929897	2530	Backup_Daily-b6df16c5b57d7423580a329c4cde8b23e.dblock.zip.aes	239093037
2203648000	2533	Backup_Daily-b3b5af2417c864ac6ba101b28a2157d78.dblock.zip.aes	1073650541
2192998400	2538	Backup_Daily-b6ead1c7c28b948b4a075d2bcee5df4c8.dblock.zip.aes	1073696237
2163609600	2543	Backup_Daily-b3b8dda85aac94205b6c059dd21638138.dblock.zip.aes	1073673309
1968230697	2548	Backup_Daily-b9963d56ddb3e4a1ea71e8fea196dfc48.dblock.zip.aes	942108829
2207539200	2551	Backup_Daily-b15cb347ce66041458340c41c17ea135a.dblock.zip.aes	1073666813
2275123200	2556	Backup_Daily-b2e5e6801edb24e1eb199bb26eb7ed2a7.dblock.zip.aes	1073653469
2575052800	2561	Backup_Daily-b9d82d49786f84e2d8632f8637c694891.dblock.zip.aes	1073665149
2616729600	2563	Backup_Daily-b6bfd172674744df18b2e585b55402841.dblock.zip.aes	1073724413
2178867200	2565	Backup_Daily-b7cd8dd01fa9b49b6b5ff24f66c087f2c.dblock.zip.aes	1073649421
1627033600	2567	Backup_Daily-b0e884dd3af8a437598205249fef2faae.dblock.zip.aes	1073650845
616853993	2569	Backup_Daily-b50f95a1568e44b21993f86464452d178.dblock.zip.aes	617844845
2292326400	2572	Backup_Daily-be0a15c3459c44dd5837cd94ba097c2c2.dblock.zip.aes	1073662525
2139816507	2574	Backup_Daily-bc40823b0f6844ca089584bf3585a35cf.dblock.zip.aes	895221661
2205900800	2577	Backup_Daily-bd7bf58eca4224f07bfeec6d95e30028a.dblock.zip.aes	1073685149
455530683	2579	Backup_Daily-be8440be932a74c1db540b5cde3180cf7.dblock.zip.aes	239945725
2132787497	2582	Backup_Daily-baa66e9b2c68c4444bcc8f9be2516dcf8.dblock.zip.aes	1002208237
2108313897	2585	Backup_Daily-b46b8cf2f562d4fc996a6fd440b212976.dblock.zip.aes	989564685
2189824000	2588	Backup_Daily-bc4aad5a86f4540a2a2ecfd4a76c471d5.dblock.zip.aes	1073642861
2147840000	2593	Backup_Daily-b2f3ec1d86094428b96b220ab9ad35de1.dblock.zip.aes	1073694765
1675161600	2597	Backup_Daily-b9378c909b874459ba106aa4c3b1cabd1.dblock.zip.aes	1073782477
1809510400	2599	Backup_Daily-b238c9b0c6f434578afe73ee8a078ae2a.dblock.zip.aes	1073768557
1458688000	2603	Backup_Daily-bd9bedb9a7abb415386c149be9ec56bd4.dblock.zip.aes	1073749037
455782994	2623	Backup_Daily-b50bd0c1e90d6494a9327d0f9d5ea5f8f.dblock.zip.aes	302831245
2051686697	2626	Backup_Daily-b6819ed0a14bf46569c9a7339ca5210e2.dblock.zip.aes	949747773
2015641897	2629	Backup_Daily-b0557a0763518408a9fa92d77becec2a4.dblock.zip.aes	910193021
2132582697	2632	Backup_Daily-b5fafbcba3fb5429084ab728687aa3ed6.dblock.zip.aes	977373613
2194329897	2635	Backup_Daily-b23ec9d365b434b559be16832d96f1bce.dblock.zip.aes	1059677517
2240102697	2638	Backup_Daily-b9983df2806104e908fbdfce95db9ad6a.dblock.zip.aes	1061022525
2168422697	2641	Backup_Daily-b4d4d87b62712406183f30c7a7ff5fb31.dblock.zip.aes	1038606621
2195968000	2644	Backup_Daily-b5b464b584af140a28c0151df142684ac.dblock.zip.aes	1073652013
2182144000	2649	Backup_Daily-b49c8be7654da45f29d8333b75faf6825.dblock.zip.aes	1073708349
2232627200	2654	Backup_Daily-bda8912df09c3483db58222bc9c685420.dblock.zip.aes	1073687037
2238566400	2659	Backup_Daily-b23402c373697402a971a030ebf214a95.dblock.zip.aes	1073669229
2178048000	2664	Backup_Daily-b71342dcc4c3b42459ecc9a5a79bfe14e.dblock.zip.aes	1073642477
2201292800	2669	Backup_Daily-b8aa74af25f844b6fb8cdeae9c72415b8.dblock.zip.aes	1073654445
2200576000	2674	Backup_Daily-bcf76a5c0cd1f4c639145a7994c08ba04.dblock.zip.aes	1073672397
2251161600	2679	Backup_Daily-b6224748d28ff4de3b651bc38228918cf.dblock.zip.aes	1073704445
2220646400	2684	Backup_Daily-ba93da098f18f4521b89a8b7c7b309de2.dblock.zip.aes	1073645549
2234777600	2689	Backup_Daily-b21eadfaa249c40ddbf022c83e2e8d905.dblock.zip.aes	1073669085
2064589097	2694	Backup_Daily-b38fefb7c7a694437898fadb0357cd1f2.dblock.zip.aes	985242957
2187673600	2697	Backup_Daily-b13f755cbba0347b7bcc5c29012df23f0.dblock.zip.aes	1073653565
2226278400	2702	Backup_Daily-b93379b367f344964acd50668386f0413.dblock.zip.aes	1073654157
2634342400	2707	Backup_Daily-b8ac6913f08bc4725aa33e9ced25afcd2.dblock.zip.aes	1073654589
2580377600	2709	Backup_Daily-b2879359c7a924367bd151f1bcc03fd5f.dblock.zip.aes	1073659437
2157568000	2711	Backup_Daily-b0915b09841fe49c69f893cded81073d5.dblock.zip.aes	1073646125
1905766400	2713	Backup_Daily-b74c341d018ca47e581186266a1f9c46e.dblock.zip.aes	1073642077
1125376000	2715	Backup_Daily-b8a32e7b71d7e46909567f14770f7feb8.dblock.zip.aes	1073698749
617484859	2717	Backup_Daily-bc767e938d31c427e947ffbdf39548e1c.dblock.zip.aes	607069485
2250444800	2720	Backup_Daily-bb7488532bfaf4f53b5039d96990dd925.dblock.zip.aes	1073653085
2176204800	2725	Backup_Daily-b3792c82e850d4425a1f3773240ae6924.dblock.zip.aes	1073669485
447795497	2727	Backup_Daily-bb11a895d89b74f3b9a05838e0365f434.dblock.zip.aes	243914525
2159718400	2730	Backup_Daily-ba54d6f08931e478abed6bee7802166e0.dblock.zip.aes	1073659341
2016770434	2750	Backup_Daily-bee87a4ec06e3486cbaf88b59327aa7df.dblock.zip.aes	1073749213
2129715497	2755	Backup_Daily-bec8fbc9ad87047089badd37fe8ff52fe.dblock.zip.aes	992691229
2193510400	2758	Backup_Daily-b49b8a8528c25415b85feb839f1937c75.dblock.zip.aes	1073646093
2170777897	2763	Backup_Daily-bd0f0ba32b92941e39e0cf35abc658d2c.dblock.zip.aes	1002315053
2121625600	2766	Backup_Daily-b754415d97c664874b953814c178c28b1.dblock.zip.aes	1073678973
2194293307	2771	Backup_Daily-ba18252bd0a59442db879f39dc1dee641.dblock.zip.aes	1013080285
2542080000	2774	Backup_Daily-bdb2daa4f106b4e249bf1ed9d19c1bb02.dblock.zip.aes	1073640829
2655027200	2776	Backup_Daily-bf360b8b66758437c9c8a0e6714e8bdd5.dblock.zip.aes	1073664413
2170982400	2778	Backup_Daily-b80a79b9964da448ca35fbfe48a4f0b9b.dblock.zip.aes	1073660413
1871974400	2780	Backup_Daily-ba496a110fcff42b294971a4338be1700.dblock.zip.aes	1073716829
1097625600	2782	Backup_Daily-bd06da6ea1a0a4dbd9334557d54842af5.dblock.zip.aes	1073731997
314278459	2784	Backup_Daily-b3901218583d44d9c9b058e005ae2f79f.dblock.zip.aes	314571581
2165760000	2787	Backup_Daily-b82f59afcb85047b683d197044b079353.dblock.zip.aes	1073691469
2151628800	2792	Backup_Daily-b353860a3b0b24594b87adb3bacc69f70.dblock.zip.aes	1073648093
2156441600	2797	Backup_Daily-b905462efac4a4dca8951b2b1b2ff1774.dblock.zip.aes	1073641693
2179481600	2802	Backup_Daily-b6bddec5eb5c140eb9bac51a3cc501ec5.dblock.zip.aes	1073646269
593203497	2804	Backup_Daily-bb38f25029a2e4a6790fbc7650c53bc0f.dblock.zip.aes	390799581
2280857600	2807	Backup_Daily-b0a040ad872c04e1c8aa90693f60b735e.dblock.zip.aes	1073664765
829134921	2822	Backup_Daily-bea5530f843d84f4aa1f313a43627bfa1.dblock.zip.aes	409046333
2188493074	2823	Backup_Daily-bcbaf42f0a64a4142b7638e183ab7205b.dblock.zip.aes	1073654365
2225254697	2828	Backup_Daily-bfe1ff094daa647c192c6deab2d749b11.dblock.zip.aes	1073641821
2187571497	2854	Backup_Daily-b569c5cd9fcb44fef896676382308f828.dblock.zip.aes	1073727917
2337689600	2858	Backup_Daily-b4c03f200175c426bb3df12a2d26cf614.dblock.zip.aes	1073814909
2382848000	2860	Backup_Daily-b395892a84b8946eaae3d0a5a833e0386.dblock.zip.aes	1073829901
1398988800	2862	Backup_Daily-b1e9690413a5c4ea59e19ee67e3adf616.dblock.zip.aes	1073743085
1279078400	2864	Backup_Daily-b6444a41fdc3545e3acdd4637552251b1.dblock.zip.aes	1073813085
1566412800	2866	Backup_Daily-b11c74dc75436421181c9add1b2e41477.dblock.zip.aes	1073759501
1448960000	2868	Backup_Daily-b9158c6eadf74474db56f635ef1029ec1.dblock.zip.aes	1073751309
2163609600	2870	Backup_Daily-bf50ca14203f740ccb080397541324bab.dblock.zip.aes	1073749197
1982156800	2872	Backup_Daily-bcc5d0f751e13488387d92e61b49fe79c.dblock.zip.aes	1073800077
1796619008	2874	Backup_Daily-b57224e469fdb4ee69c8d91f6eb8430e8.dblock.zip.aes	1073758925
2266931497	2876	Backup_Daily-b5151fc1b7e0b4de3b8ba5522ff691460.dblock.zip.aes	1073745261
2048322695	2878	Backup_Daily-b335b7e6fe1a54b9b85ec949187e73364.dblock.zip.aes	1073767021
721663094	2880	Backup_Daily-b55e6024300f64b928cae520c0c3ce212.dblock.zip.aes	388250717
2276045097	2892	Backup_Daily-b9f96175c26494462b1925b5980ae0a69.dblock.zip.aes	1067693613

**Comment by tygill** [comment]
A few thoughts:

First, not all blocks will be the full blocksize. For example, a 10kb file will be packed into a 10kb block, and a 140kb file will be packed into one 100kb block and one 40kb block.

Also, some metadata is stored in blocks. When a file consists of multiple blocks, Duplicati stores the list of block hashes in another block, and then stores only the hash of the block listing the actual hashes in the dlist json file.

**Comment by ts678** [comment]
It's not clear that anything is wrong, but it does depend on the data. Compression can store 100 KB blocks very compactly:

![image](https://user-images.githubusercontent.com/40771998/102040339-8fb20a80-3d9a-11eb-90f8-f1efaae00cfb.png)

That was a big profiling log file. Home screen of Duplicati calls it Source:254.04 MB Backup:15.94 MB. Computed using SQL:

```
Block
sum(Block.Size)
266464803

Remotevolume
sum(Size)
16543956
```

> Using this excel calculator I should have around 1,3 mio blocks (correct, 100KB block size, 141GB of data), but in database there is 2,6mio blocks

Block count for multiple backups of given source size may increase with retained versions, but deduplication reduces growth.
Files might change their data while keeping the same name, files might come and go, and all can add up to additional blocks.
One of my backups of highly changing data with a lot of versions is at 8 times the source size, and that's not at all surprising.
