### ISSUE TITLE
SSL_ERROR_RX_MALFORMED_SERVER_HELLO when using webservice-sslcertificatefile

### ISSUE THREAD

**Issue by fergbrain** [duplicati/duplicati#3331]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Debian 9.5
- **Backend**: Backblaze B2 (irrelevant for this issue though)

## Description

When using a self-signed certificate, I get the following error when trying to connect to Duplicati using Firefox 61.0.1 on OSX 10.13.6:

> Secure Connection Failed
> 
> An error occurred during a connection to atlas.ferg.ferguson.pw:2600. SSL received a malformed Server Hello handshake message. Error code: SSL_ERROR_RX_MALFORMED_SERVER_HELLO 
> 

## Steps to reproduce

1. Create Root CA and install certificate into Firefox.
1. Create and install a PKCS #12 certificate (signed by self-Root CA) to /etc/ssl/private/my-cert.p12
2. Start duplicati service: `Duplicati.Server.exe --webservice-port=2600 --webservice-interface=0.0.0.0 --webservice-sslcertificatefile=/etc/ssl/private/my-cert.p12`
3. Using Firefox, visit site: https://my.server:2600

- **Actual result**:
Firefox does not load page and display SSL_ERROR_RX_MALFORMED_SERVER_HELLO error
- **Expected result**:
Firefox loads page

## Screenshots

![image](https://user-images.githubusercontent.com/1291387/43678186-61e0c4c0-9806-11e8-8bac-e11e9d5a8178.png)

## Debug log

- Using Safari 11.1.2 does not result in the same error
- Using Firefox 52.9.0 on Debian 9.5 does not result in the same error
- Running `echo "GET / HTTP/1.0" | openssl s_client -connect my.server:2600 -servername my.server -CAfile /etc/ssl/certs/ca-chain.cert.pem` outputs the following:

```
...<STUFF ABOUT CERTIFICATE>...
 ---
 No client certificate CA names sent
 ---
 SSL handshake has read 1455 bytes and written 675 bytes
 ---
 New, TLSv1/SSLv3, Cipher is AES256-SHA
 Server public key is 2048 bit
 Secure Renegotiation IS NOT supported
 Compression: NONE
 Expansion: NONE
 No ALPN negotiated
 SSL-Session:
     Protocol  : TLSv1
     Cipher    : AES256-SHA
     Session-ID: 
     Session-ID-ctx: 
     Master-Key: 06C7F2C1C2294F235ED520ED1697C942E28B6F6FC4699ECC0827D8264021A977485616FDE084E3E5A10128C9BA2E8962
     Start Time: 1533397279
     Timeout   : 300 (sec)
     Verify return code: 0 (ok)
 ---
 DONE
```

**Comment by mnaiman** [comment]
Its a Firefox problem https://www.reddit.com/r/firefox/comments/8k8z6m/firefox_randomly_failing_to_securely_connect_to/
There are lot of users report in past months on that in Firefox.

**Comment by fergbrain** [comment]
I saw that same issue too, however, this occurs _every_ time...which I think may be a different issue.

**Comment by ts678** [comment]
I searched in open and closed GitHub issues for SSL_ERROR_RX_MALFORMED_SERVER_HELLO and found no other reports.
Is this still of interest? You can also try the forum (although there are no reports of this there either) for support assistance.

If there's nothing more to say, issue will automatically close.
