### ISSUE TITLE
Negative "Bytes to go"

### ISSUE THREAD

**Issue by PerMildner** [duplicati/duplicati#3335]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.9_canary_2018-06-30
- **Operating system**: macOS 10.13.6 (17G65)
- **Backend**: Jottacloud

## Description

The "Bytes to go" starts at zero and then becomes negative. The number of files is also incorrect (1, but should be thousands).

Theses symptoms are not in the official release 2.0.3.3

## Steps to reproduce

1. Replace me
2. Replace me
3. ...

- **Actual result**:
Negative bytes to go, and only "1" file to go.
- **Expected result**:
Positive, decreasing, bytes to go (and a unit larger than "bytes").

## Screenshots

![screen shot 2018-08-10 at 16 42 02](https://user-images.githubusercontent.com/1358238/43964135-73e24418-9cbc-11e8-92ed-6f62ba9002f4.png)
![screen shot 2018-08-10 at 16 41 43](https://user-images.githubusercontent.com/1358238/43964136-73fd91dc-9cbc-11e8-89d2-74d3c6081e80.png)

**Comment by dudelson** [comment]
I also have this problem with the latest Canary on arch linux. However, I think it was discussed and fixed in #3305.

**Comment by warwickmm** [comment]
Yes, this was fixed in revision 5d6c612.
