### ISSUE TITLE
Translation not replaced from ENG -> GER

### ISSUE THREAD

**Issue by sfahrenholz** [duplicati/duplicati#3341]
## Environment info
- **Duplicati version**: 2.0.3.9_canary_2018-06-30
- **Operating system**: Wind 10
- **Backend**: <none>

- **Actual result**:
![grafik](https://user-images.githubusercontent.com/6977657/44297729-adf4c200-a2d6-11e8-8388-debda8a4b0e4.png)

- **Expected result**:
There is the translated String for the language... Yes im checking in transifex and there is the translation

**Comment by warwickmm** [comment]
The translations were updated in revision 291604943698d483735278ceff5f9f0101402618 and should be available in the next release.
