### ISSUE TITLE
Size exceeded

### ISSUE THREAD

**Issue by mnuman** [duplicati/duplicati#3343]
Failed to process file duplicati-b365035a36c1c45879296a9032f980640.dblock.zip.aes
System.IO.IOException: De bestandsgrootte heeft de toegestane limiet overschreden en kan niet worden opgeslagen.

   bij Duplicati.Library.Main.BackendManager.GetForTesting(String remotename, Int64 size, String hash)
   bij Duplicati.Library.Main.Operation.TestHandler.DoRun(Int64 samples, LocalTestDatabase db, BackendManager backend)
----------------------------------------

## Environment info
Win10x64, creating backup to locally mounted WebDAV share.
## Description
When creating a backup from local disk onto a locally mounted webdav location, the exception above is generated. The file is present on the target (size = 49,9MB, 52.349.549 bytes; blocksize was set to 50MB in UI).
Verifying the created file with AESCrypt (v3.1, x64) yields the same result - the file size is too big.

**Comment by mnuman** [comment]
[bugreport.zip](https://github.com/duplicati/duplicati/files/2300534/bugreport.zip)
Reproduced the issue yet another time, filenames have of course changed: see attached bugreport

**Comment by warwickmm** [comment]
It sounds like earlier versions of Windows had [limits](https://github.com/duplicati/duplicati/issues/3343) on the transfer size over WebDAV.  Not sure if it also affects Windows 10, but it appears that there are Windows 10 users that experience the [same issue](https://community.netgear.com/t5/Using-your-ReadyNAS/Error-0x800700DF-The-file-size-exceeds-the-limit-allowed-and/td-p/1229672).

**Comment by ts678** [comment]
> Verifying the created file with AESCrypt (v3.1, x64) yields the same result - the file size is too big.

Got a message? This is especially surprising. I had AES Crypt 3.10 encrypt and decrypt a 12 GB file.
If however you mean you did it on the Explorer window looking live at WebDAV, then it's WebDAV.
You could certainly try some other tests with it to see what it does or doesn't do. If it's just too big,
then turn down the Duplicati `Remote volume size` on Options screen 5 to test if smaller works...

> The file is present on the target (size = 49,9MB, 52.349.549 bytes

> Reproduced the issue yet another time, filenames have of course changed: see attached bugreport

The file sizes in it are on the order of 68,000,000 bytes which is larger than I'm used to seeing done.

There's a little more information in the log. You probably could have gotten it too (in the right spot):

```
System.IO.IOException: De bestandsgrootte heeft de toegestane limiet overschreden en kan niet worden opgeslagen.

   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bij Duplicati.Library.Backend.File.Get(String remotename, Stream stream)
   bij Duplicati.Library.Main.BackendManager.coreDoGetPiping(FileEntryItem item, IEncryption useDecrypter, Int64& retDownloadSize, String& retHashcode)
   bij Duplicati.Library.Main.BackendManager.DoGet(FileEntryItem item)
   bij Duplicati.Library.Main.BackendManager.ThreadRun()
```

which looks like Duplicati tried to download the file, and got an error from .NET Framework+Windows.
Is this issue still of interest and happening? I'm not sure how Duplicati can handle a hard error better...
