### ISSUE TITLE
Question about restoring multiple files at once in the commandline

### ISSUE THREAD

**Issue by Hand-of-Cthulhu** [duplicati/duplicati#3349]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.9
- **Operating system**: Windows 10
- **Backend**: Backblaze B2

## Description

Since duplciati stores files in pieces of 50mb or so zip files, when I want to restore multiple files from commandline I'm currently just calling "Duplicati.Commandline.exe restore" multiple times with different file names. This means a lot of the time it just downloads the same 50mb archive for each file, which seems pretty wasteful. 

Is there a way to restore multiple files at once in the commandline? (Something more specific than the wildcard *). I tried separating paths with semicolons or commas, but neither worked.

**Comment by warwickmm** [comment]
I think you can restore multiple files by providing the paths to each of the files before the command options:
```
Duplicati.CommandLine.exe restore <storage-URL> ["<filename 1>"] ["<filename 2>"] ... [<options>]
```
