### ISSUE TITLE
Overall progress, processed file count and processed file size not updating

### ISSUE THREAD

**Issue by mikaelmello** [duplicati/duplicati#3350]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
"ServerVersion": "2.0.0.7", (which is really weird because I've cloned the latest commit, https://github.com/duplicati/duplicati/commit/258c5a6fa2e072ac5851d66f0537538345b5b329)
"ServerVersionName": " - debug",
"ServerVersionType": "Debug",
"StartedBy": "Tray icon",
"BaseVersionName": "Current",
"DefaultUpdateChannel": "Stable",
"DefaultUsageReportLevel": "Disabled",
"ServerTime": "2018-08-29T11:33:03.2298349-03:00",
"OSType": "Windows",
"DirectorySeparator": "\\",
"PathSeparator": ";",
"CaseSensitiveFilesystem": false,
"MonoVersion": null,

## Description

During backup, those 3 variables are never updated in the progressstate API call. I did some digging and  the `UpdatefilesProcessed` function is never called during backup, only during restore.

What I find weird is that when I download the latest release on the website, it works as it should. I haven't checked the Network tab to see if the API call has the correct response but the progress bar does get updated.

I managed to fix it here https://github.com/LacunaSoftware/duplicati/commit/d9445f7aafbb4d6f4a38e0280c68adffe8070491

## Steps to reproduce

- Clone the latest commit and run using Visual Studio 2017 on Debug.
- Make a large backup on any Backend and see that the progress bar is not updated, always hanging on the total file count.

## Screenshots
Imagine a lot of API calls to `progressstate` with everything being updated except for 
```
  "OverallProgress": 0.0,
  "ProcessedFileCount": 0,
  "ProcessedFileSize": 0,
```

**Comment by huste** [comment]
I am also not seeing progess updates in 2.0.3.10. I didn't compile myself but used the ZIP archive to install.

**Comment by mikaelmello** [comment]
@kenkendk could you chime in? Is my temp fix good enough or is there a better approach?

**Comment by warwickmm** [comment]
Thanks @mikaelmello.  If you create a [pull request](https://github.com/duplicati/duplicati/pulls), it will be easier for other developers to provide feedback and consider merging your fix.

**Comment by kenkendk** [comment]
@mikaelmello Fix looks good! I think it was supposed to do that.

**Comment by mikaelmello** [comment]
Thanks! I've created the PR

Em sex, 7 de set de 2018 03:53, Kenneth Skovhede <notifications@github.com>
escreveu:

**Comment by mikaelmello** [comment]
Also @kenkendk , another problem I've encountered is that when all files are finished processed but there is still work to do on the backend dblock files. The progress bar calculates the bytes left to upload as `totalSize - processedSize - currentFileOffset` or something like that.

This means that when `uploadedSize == totalSize`, the progress bar will display a negative number of bytes to be uploaded. My fix for that was to simply use a `Math.max(0, that value)`, instead.

https://github.com/LacunaSoftware/duplicati/commit/616d366dd52c96d2d1ca1390619f82eab0314512#diff-a727eb2559d90e2245e74705f59e9adaL38
