### ISSUE TITLE
Extreme performance issues with 2.0.3.10 (after 2.0.3.9). Using TEST_QUERY_VERSION=2 is fine, though.

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#3357]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.10
- **Operating system**: Win10 64bit
- **Backend**: local folder (SMB Share on a Synology)

## Description
I upgraded from 2.0.3.9. The backups that run on a daily basis now take over 4 hours instead of only several minutes. The verbose live log mainly shows
2. Sept. 2018 09:05: Skipped checking file, because no metadata was updated D:\java\sdk-AndroidStudio\platforms\android-23\data\res\drawable-xxhdpi\spinner_76_inner_holo.png
2. Sept. 2018 09:05: Including path as no filters matched: D:\java\sdk-AndroidStudio\platforms\android-23\data\res\drawable-xxhdpi\spinner_ab_activated_holo_dark.9.png
2. Sept. 2018 09:05: Skipped checking file, because no metadata was updated D:\java\sdk-AndroidStudio\platforms\android-23\data\res\drawable-xxhdpi\spinner_48_outer_holo.png

There are many files (252000 with abourt 110GB) to backup but only very few actually change between backups.

## Steps to reproduce
1. Well, just launch an older backup job.

- **Actual result**:
Counting files, checking files for an *eternity* (currently at about 8 files per second, according to the log. A vast majority of them are skipped because of no metadata changes)

- **Expected result**:
Counting files, checking files, uploading what is necessary

## Debug log
I am creating a verbose debug log and can upload it somewhere, if that is needed. But it is already about 100MB and still growing.

**Comment by Athep** [comment]
I have the same issue. From the change log: Set the environment variable `TEST_QUERY_VERSION=1` to revert to the old version for speed comparison, or `TEST_QUERY_VERSION=2` for an alternate version.

For me `TEST_QUERY_VERSION=1` resulted in normal performance again.

**Comment by ItEndsWithTens** [comment]
Count me in this group as well. Windows 10 x64, 1803, backing up to a local folder that's really a Samba share on a NAS4Free (or "XigmaNAS" now) system. A backup with just over 200,000 files, that had taken 20 or 30 minutes at worst in 2.0.3.9, was taking 4 to 6 hours after the 2.0.3.10 update.

In my case, setting TEST_QUERY_VERSION to 1 brought that time to ~15 minutes, and version 2 down to about 7 minutes. I only ran one backup with each setting, so it wasn't a terribly scientific test, but it does seem the query version environment variable helps tremendously.

**Comment by Athep** [comment]
I did not try  `TEST_QUERY_VERSION=2`  before.  I have now tested on 2 PC's  running Windows-10 , and yes, version 2 is the fastest in my case too.

**Comment by kenkendk** [comment]
@huste No issues expected, they do the same, but query in different ways.

It seems that most people report version 2 as the fastest, so I will update to using that version by default.

Not sure why it suddenly performs so poorly, as it should simply limit the query to only looking at one single fileset (current default), rather than looking at all filesets (version  1).

**Comment by kenkendk** [comment]
There is also a discussion here, where one user reports that the new version is faster: https://forum.duplicati.com/t/release-2-0-3-10-canary-2018-08-30/4497/15

**Comment by Athep** [comment]
https://forum.duplicati.com/t/release-2-0-3-10-canary-2018-08-30/4497/15
Oops! That page doesn’t exist or is private.

**Comment by gabriele-v** [comment]
@kenkendk 
I've noticed that v2 is faster, but regarding differences, code is commented with:

> The original command (v==1) finds the most recent entry of the file in question, but it requires some large joins to extract the required information. To speed it up, we use a slightly simpler approach that only looks at the previous fileset, and uses information here. If there is a case where a file is sometimes there and sometimes not (i.e. filter file, remove filter) we will not find the file. We currently use this faster version, but allow users to switch back via an environment variable such that we can get performance feedback

Does it mean that v2 query will backup a file again (instead of just change reference\index) if for example was there, then deleted, the re-added again? Or was included by filter, then excluded and then reincluded again?

**Comment by kenkendk** [comment]
@Athep It was accidentially deleted :)

I have un-deleted it so the link should work now.

@gabriele-v 

> Does it mean that v2 query will backup a file again (instead of just change reference\index) if for example was there, then deleted, the re-added again? Or was included by filter, then excluded and then reincluded again?

If the file was removed, and then included again, it would be scanned again, as if it was a new file. But if the file is unchanged, this only adds scanning time, it does not upload any new data blocks.

**Comment by kenkendk** [comment]
I will soon send out a v2.0.3.11 with changes to the query.
For those interested in profiling the queries, I have explained what different queries are possible here:
https://forum.duplicati.com/t/slow-backup-in-version-v2-0-3-10-downgrade-to-version-2-0-3-5/4528/8

**Comment by huste** [comment]
My observations with the same backup set (250 000 files, about 110GB), running each one onnce only, are:
* 2.0.3.10 with TEST_QUERY_VERSION=2: 9 minutes (with retention rules active at that time)
* 2.0.3.11 with TEST_QUERY_VERSION=1: 6 minutes 30 seconds (with NO retention rules active)
* 2.0.3.11 with TEST_QUERY_VERSION=2: 7 minutes (with NO retention rules active)
* 2.0.3.11 with TEST_QUERY_VERSION=3: 5 hrs 8 minutes (with NO retention rules active)
* 2.0.3.11 with TEST_QUERY_VERSION=4: running already since 40 minutes (with NO retention rules active)  I just have to shut down the computer now, I'll update the report when the last backup job has run through...

Where's the OpenedFiles and ExaminedFiles information? Not in the verbose-level logfile...

**Comment by kenkendk** [comment]
The OpenedFiles and ExaminedFiles are in the result (the Log area in the WebUI).
But you have a good point: why not report the results in the log file as well...

**Comment by huste** [comment]
Ah, thanks. The numbers are *quite* different: 4 vs 224235.

**Comment by huste** [comment]
I think, this one can be closed. I don't have any environment variable on my Windows machine set any more, I still have the same old backup job running, but I cannot observe such poor performance, using 2.0.4.31. And in fact, I completely forgot about this open issue...
