### ISSUE TITLE
Box backend broken because of server public.boxcloud.com

### ISSUE THREAD

**Issue by oduis** [duplicati/duplicati#3359]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.10_canary_2018-08-30
- **Operating system**: Windows 10
- **Backend**: Backend

## Description

Constant errors on verify or backup to box.com. The error is always that public.boxcloud.com is not resolvable. The server is really not there any more. I assume the Box API has changed or something.

## Steps to reproduce

1. Do any backup to a Box.com account

- **Actual result**:
Error (see log below)

## Screenshots
No screens

## Debug log

<code>
MainOperation: Test
Verifications: [
    Key: duplicati-20180903T173526Z.dlist.zip.aes
    Value: [
        Key: Error
        Value: Der Remotename konnte nicht aufgelöst werden: 'public.boxcloud.com'
    ],
    Key: duplicati-i67b9986f0a06467a9719d577dfa1ae3b.dindex.zip.aes
    Value: [
        Key: Error
        Value: Der Remotename konnte nicht aufgelöst werden: 'public.boxcloud.com'
    ],
    Key: duplicati-b8e44a61a32b64b9ebd6c308cfee545ef.dblock.zip.aes
    Value: [
        Key: Error
        Value: Der Remotename konnte nicht aufgelöst werden: 'public.boxcloud.com'
    ]
]
ParsedResult: Error
Version: 2.0.3.10 (2.0.3.10_canary_2018-08-30)
EndTime: 04.09.2018 12:28:30 (1536056910)
BeginTime: 04.09.2018 12:25:44 (1536056744)
Duration: 00:02:46.1127614
Messages: [
    2018-09-04 12:25:44 +02 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Test has started,
    2018-09-04 12:25:44 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),
    2018-09-04 12:25:51 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (282 bytes),
    2018-09-04 12:25:51 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-20180903T173526Z.dlist.zip.aes (4,87 MB),
    2018-09-04 12:25:52 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-20180903T173526Z.dlist.zip.aes (4,87 MB),

…</code>

**Comment by warwickmm** [comment]
I don't have any issues with the Box backend using version 2.0.3.10_canary_2018-08-30 on Linux.  My configuration has a destination URL that looks like `box://<path on server>`, and I don't see the URL `public.boxcloud.com` anywhere in the source code.  Can you provide more details about your configuration?

**Comment by oduis** [comment]
Here is the configuration (I remove the password of course).
I guess the server name is build dynamically from the parts, or it is part of an outdated SDK.

[ODuisDuplicatiEssentials-duplicati-config.txt](https://github.com/duplicati/duplicati/files/2351248/ODuisDuplicatiEssentials-duplicati-config.txt)

**Comment by warwickmm** [comment]
Is it possible that your authid is no longer valid?  If you edit your configuration, and in step 2 click on "Test connection", does it say "Connection worked!"?

**Comment by oduis** [comment]
Test connection is OK. To make sure I re-enter my password and re-generated the authID. Same problem.

**Comment by warwickmm** [comment]
Are you able to ping public.boxcloud.com?  For me, the URL seems ok.
```
$ ping public.boxcloud.com
PING dl.boxcloud.com (107.152.25.200) 56(84) bytes of data.
64 bytes from 107.152.25.200 (107.152.25.200): icmp_seq=1 ttl=55 time=9.64 ms
64 bytes from 107.152.25.200 (107.152.25.200): icmp_seq=2 ttl=55 time=9.87 ms
64 bytes from 107.152.25.200 (107.152.25.200): icmp_seq=3 ttl=55 time=9.81 ms
64 bytes from 107.152.25.200 (107.152.25.200): icmp_seq=4 ttl=55 time=9.75 ms
64 bytes from 107.152.25.200 (107.152.25.200): icmp_seq=5 ttl=55 time=9.72 ms
```

**Comment by oduis** [comment]
I now pinged it right now, DNS error. Might be BOX infrastructure problems.
```
C:\Users\oduis>ping public.boxcloud.com
Ping-Anforderung konnte Host "public.boxcloud.com" nicht finden. Überprüfen Sie den Namen, und versuchen Sie es erneut.

C:\Users\oduis>ping www.microsoft.com

Ping wird ausgeführt für e13678.dspb.akamaiedge.net [104.108.45.230] mit 32 Bytes Daten:
Antwort von 104.108.45.230: Bytes=32 Zeit=28ms TTL=54
Antwort von 104.108.45.230: Bytes=32 Zeit=27ms TTL=54
Antwort von 104.108.45.230: Bytes=32 Zeit=27ms TTL=54 
```

Easycounter had it offline yesterday also:
![snipaste_2018-09-06_06-39-18](https://user-images.githubusercontent.com/16719086/45135570-6e681a00-b1a0-11e8-92a9-d30897210b6a.png)
