### ISSUE TITLE
Restore is failing - Failed to patch with remote file: .... message: Failed to decrypt data (invalid passphrase?): Message has been altered, do not trust content 

### ISSUE THREAD

**Issue by alexlauerman** [duplicati/duplicati#3363]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Windows 10
- **Backend**: FTP (local network)

## Description

Many attempts at restoring produces the following error:

```
Failed to patch with remote file: "duplicati-b3beb2a7624b24d979be34963605e8150.dblock.zip.aes", message: Failed to decrypt data (invalid passphrase?): Message has been altered, do not trust content => Failed to decrypt data (invalid passphrase?): Message has been altered, do not trust content 
```

Duplicati.CommandLine.RecoveryTool.exe also throws the same error.

````
23: duplicati-b399c9016a2f44d1ca13dc6fc72f1dde7.dblock.zip.aes - downloading (1.29 GB)... - decrypting ... done!
24: duplicati-b3beb2a7624b24d979be34963605e8150.dblock.zip.aes - downloading (361.47 MB)... - decrypting ... error: System.Security.Cryptography.CryptographicException: Failed to decrypt data (invalid passphrase?): Message has been altered, do not trust content ---> SharpAESCrypt.SharpAESCrypt+HashMismatchException: Message has been altered, do not trust content
   at SharpAESCrypt.SharpAESCrypt.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Duplicati.Library.Utility.Utility.CopyStream(Stream source, Stream target, Boolean tryRewindSource, Byte[] buf)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   --- End of inner exception stack trace ---
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(Stream input, Stream output)
   at Duplicati.Library.Encryption.EncryptionBase.Decrypt(String inputfile, String outputfile)
   at Duplicati.CommandLine.RecoveryTool.Download.Run(List`1 args, Dictionary`2 options, IFilter filter)
25: duplicati-b3c3b9fa891e142f690ff8d786b0ab023.dblock.zip.aes - downloading (1.46 GB)... - decrypting ... done!
````

Decrypting directly with AESCrypt (which I understand is the back-end provider throwing this error), works fine and leaves me with a zip file that opens fine:
```
SharpAESCrypt.exe d ********** "C:\\apath\\duplicati-b3c3b9fa891e142f690ff8d781b0ab011.dblock.zip.aes" "C:\\apath\\duplicati-b3c3b9fa891e142f690ff8d781b0ab011.dblock.zip" 
```

Although with AESCrypt I'll have additional steps to get the data out of that.

## Additional Information

All other blocks work fine. Duplicati stops the entire recovery process instead of handling this exception more cleanly.

The code that is throwing this error is here:
https://github.com/duplicati/duplicati/blob/b855e4c6869ffd3ca2a5f6261d8855d3e0485941/Duplicati/Library/Main/Operation/RestoreHandler.cs#L449

And here in AESCrypt:
https://github.com/kenkendk/sharpaescrypt/search?q=DataHMACMismatch&unscoped_q=DataHMACMismatch

There is a thread with a similar issue here, although this failed during Backup. My backups were fine, but my restore is having issues: https://forum.duplicati.com/t/error-failed-to-decrypt-data/1717/14

I would think shouldn't be the case, since duplicati should verify everything, especially across multiple backups, and this file has not been modified in 6 months. It's possible that this file is not used, but when I removed it the database complained about it not existing. Also, if it was not associated with this backup, I would think it wouldn't be an HMAC problem.

## Current Status & Questions

I don't need any active support (although that would be great). I have a few more ideas to try. I mostly wanted to document this in case anyone else is experiencing it. I have not figured out where the actual HMAC is, that is failing. I'm also not sure if AESCrypt.exe is called directly by Duplicati (if so I could patch out the HMAC checking in that standalone AESCrypt.exe). Any insight is appreciated.

## Steps to reproduce

1. I do not know how to reproduce this without providing my backup

**Comment by alexlauerman** [comment]
I decrypted this using AEScrypt, then ran Duplicati.CommandLine.exe restore to restore from backup, and that appears to have recovered most files, but 430 files are not restoring, unfortunately I don't know which files or why they didn't restore, since it was restored using a repaired DB (which I think is necessary because my original db points to encrypted files).

```
...
Restore started at 9/5/2018 4:56:27 PM
No local database, building a temporary database
...
Recreate completed, verifying the database consistency

System.IO.InvalidDataException: Found inconsistency in the following files while validating database:
C:\<removed>, actual size 805306368, dbsize 0, blocksetid: 230279
C:\<removed>, actual size 21187803, dbsize 0, blocksetid: 230285
C:\<removed>, actual size 501507, dbsize 0, blocksetid: 230313
C:\<removed>, actual size 1621671, dbsize 0, blocksetid: 230315
C:\<removed>, actual size 371852, dbsize 0, blocksetid: 230337
... and 431 more. Run repair to fix it.
   at Duplicati.Library.Main.Database.LocalDatabase.VerifyConsistency(IDbTransaction transaction, Int64 blocksize, Int64 hashsize, Boolean verifyfilelists)
   at Duplicati.Library.Main.Operation.RecreateDatabaseHandler.DoRun(LocalDatabase dbparent, Boolean updating, IFilter filter, NumberedFilterFilelistDelegate filelistfilter, BlockVolumePostProcessor blockprocessor)
   at Duplicati.Library.Main.Operation.RestoreHandler.Run(String[] paths, IFilter filter)
   at Duplicati.Library.Main.Controller.<>c__DisplayClass18_0.<Restore>b__0(RestoreResults result)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.Restore(String[] paths, IFilter filter)
   at Duplicati.CommandLine.Commands.Restore(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)

```

**Comment by Pectojin** [comment]
Did all the remote files decrypt successfully? 430 files not restored sounds like it could be a corrupted volume, but then it shouldn't decrypt at all.

**Comment by alexlauerman** [comment]
At this point, I think so.  All I can say is that I have not yet found one file that is _missing_. I couldn't tell from the error messages what files may be missing to check to see if they exist, so I can't say for sure whether they all exist.

**Comment by alexlauerman** [comment]
Thanks for the suggestions, but I'm fine with my current restoration for now.  I'll keep this in mind for my next steps with Duplicati soon, and it may be helpful for others, although I don't need active support anymore since I think I have all of my files back. I am leaving the issue open since there are bunch of serious issues with restoration identified here.

**Comment by irstmon** [comment]
I'm having the same issue - I can't restore because of this. I can decrypt the files via aescrypt and the passphrase - this means that the passphrase is right. However my situation is a bit different as it seems ALL my zip files show up as bad when restoring - not just one. Listing the Files and recreation of the DB however works without a problem

**Comment by chris-y** [comment]
I'm having a similar issue.  Backend is B2, all attempts to restore give the above error, however the files do actually restore fine.

Error:
`2020-04-15 11:33:37 +01 - [Error-Duplicati.Library.Main.Operation.RestoreHandler-PatchingFailed]: Failed to patch with remote file: "duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes", message: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data`

Full log:
`{
  "RestoredFiles": 1,
  "SizeOfRestoredFiles": 168879,
  "RestoredFolders": 0,
  "RestoredSymlinks": 0,
  "PatchedFiles": 0,
  "DeletedFiles": 0,
  "DeletedFolders": 0,
  "DeletedSymlinks": 0,
  "MainOperation": "Restore",
  "RecreateDatabaseResults": null,
  "ParsedResult": "Error",
  "Version": "2.0.5.104 (2.0.5.104_canary_2020-03-25)",
  "EndTime": "2020-04-15T10:33:37.055277Z",
  "BeginTime": "2020-04-15T10:30:31.861192Z",
  "Duration": "00:03:05.1940850",
  "MessagesActualLength": 15,
  "WarningsActualLength": 0,
  "ErrorsActualLength": 1,
  "Messages": [
    "2020-04-15 11:30:32 +01 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Restore has started",
    "2020-04-15 11:30:35 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()",
    "2020-04-15 11:30:50 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (5.97 KB)",
    "2020-04-15 11:30:51 +01 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 0 (15/04/2020 03:00:00) ...",
    "2020-04-15 11:30:58 +01 - [Information-Duplicati.Library.Main.Operation.RestoreHandler-RemoteFileCount]: 1 remote files are required to restore",
    "2020-04-15 11:30:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:31:10 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:31:20 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:31:45 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:31:55 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:32:21 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:32:31 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:32:58 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:33:08 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)",
    "2020-04-15 11:33:37 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Failed: duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes (49.96 MB)"
  ],
  "Warnings": [],
  "Errors": [
    "2020-04-15 11:33:37 +01 - [Error-Duplicati.Library.Main.Operation.RestoreHandler-PatchingFailed]: Failed to patch with remote file: \"duplicati-b3ab94c668e3348b5a796ea89680942f4.dblock.zip.aes\", message: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data"
  ],
  "BackendStatistics": {
    "RemoteCalls": 6,
    "BytesUploaded": 0,
    "BytesDownloaded": 0,
    "FilesUploaded": 0,
    "FilesDownloaded": 0,
    "FilesDeleted": 0,
    "FoldersCreated": 0,
    "RetryAttempts": 4,
    "UnknownFileSize": 0,
    "UnknownFileCount": 0,
    "KnownFileCount": 6116,
    "KnownFileSize": 158225451492,
    "LastBackupDate": "2020-04-15T04:00:00+01:00",
    "BackupListCount": 14,
    "TotalQuotaSpace": 0,
    "FreeQuotaSpace": 0,
    "AssignedQuotaSpace": -1,
    "ReportedQuotaError": false,
    "ReportedQuotaWarning": false,
    "MainOperation": "Restore",
    "ParsedResult": "Success",
    "Version": "2.0.5.104 (2.0.5.104_canary_2020-03-25)",
    "EndTime": "0001-01-01T00:00:00",
    "BeginTime": "2020-04-15T10:30:31.861208Z",
    "Duration": "00:00:00",
    "MessagesActualLength": 0,
    "WarningsActualLength": 0,
    "ErrorsActualLength": 0,
    "Messages": null,
    "Warnings": null,
    "Errors": null
  }
}`

**Comment by chris-y** [comment]
Hmm, created a new backup (new database, new empty destination) because my previous one seemed quite screwed up, did a test restore and immediately I'm getting the "message: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data".  Files are restoring, so this bogus error is coming from somewhere.

{
  "RestoredFiles": 1,
  "SizeOfRestoredFiles": 7473790,
  "RestoredFolders": 0,
  "RestoredSymlinks": 0,
  "PatchedFiles": 0,
  "DeletedFiles": 0,
  "DeletedFolders": 0,
  "DeletedSymlinks": 0,
  "MainOperation": "Restore",
  "RecreateDatabaseResults": null,
  "ParsedResult": "Error",
  "Version": "2.0.5.104 (2.0.5.104_canary_2020-03-25)",
  "EndTime": "2020-04-28T17:23:16.724923Z",
  "BeginTime": "2020-04-28T17:21:15.118933Z",
  "Duration": "00:02:01.6059900",
  "MessagesActualLength": 15,
  "WarningsActualLength": 0,
  "ErrorsActualLength": 1,
  "Messages": [
    "2020-04-28 18:21:15 +01 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Restore has started",
    "2020-04-28 18:21:17 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()",
    "2020-04-28 18:21:22 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (6.02 KB)",
    "2020-04-28 18:21:23 +01 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 0 (28/04/2020 15:52:33) ...",
    "2020-04-28 18:21:29 +01 - [Information-Duplicati.Library.Main.Operation.RestoreHandler-RemoteFileCount]: 1 remote files are required to restore",
    "2020-04-28 18:21:29 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:21:39 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:21:49 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:22:03 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:22:13 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:22:28 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:22:38 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:22:52 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Retrying: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:23:02 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)",
    "2020-04-28 18:23:16 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Failed: duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes (49.93 MB)"
  ],
  "Warnings": [],
  "Errors": [
    "2020-04-28 18:23:16 +01 - [Error-Duplicati.Library.Main.Operation.RestoreHandler-PatchingFailed]: Failed to patch with remote file: \"duplicati-b98a022f44587466a868c5044511610ab.dblock.zip.aes\", message: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data"
  ],
  "BackendStatistics": {
    "RemoteCalls": 6,
    "BytesUploaded": 0,
    "BytesDownloaded": 0,
    "FilesUploaded": 0,
    "FilesDownloaded": 0,
    "FilesDeleted": 0,
    "FoldersCreated": 0,
    "RetryAttempts": 4,
    "UnknownFileSize": 0,
    "UnknownFileCount": 0,
    "KnownFileCount": 6169,
    "KnownFileSize": 161689464357,
    "LastBackupDate": "2020-04-28T16:52:33+01:00",
    "BackupListCount": 3,
    "TotalQuotaSpace": 0,
    "FreeQuotaSpace": 0,
    "AssignedQuotaSpace": -1,
    "ReportedQuotaError": false,
    "ReportedQuotaWarning": false,
    "MainOperation": "Restore",
    "ParsedResult": "Success",
    "Version": "2.0.5.104 (2.0.5.104_canary_2020-03-25)",
    "EndTime": "0001-01-01T00:00:00",
    "BeginTime": "2020-04-28T17:21:15.118945Z",
    "Duration": "00:00:00",
    "MessagesActualLength": 0,
    "WarningsActualLength": 0,
    "ErrorsActualLength": 0,
    "Messages": null,
    "Warnings": null,
    "Errors": null
  }
}

**Comment by ts678** [comment]
If you ever allow a browser or password saver to password-autofill, perhaps they're [doing it wrong](https://github.com/duplicati/duplicati/issues/3700#issuecomment-620873594).

**Comment by neduz** [comment]
Wow, well this just saved me a hearth attack, I was trying to restore files, getting this Failed to patch with remote file ...  Failed to decrypt data (invalid passhphrase?) message...
I had run through the restore process again (from the existing configuration, with good database) but there wasn't any password prompt visible. But I did get the message in the log for every single file, and the SharpAESCrypt.exe tool does decrypt them fine. Reading these last few messages, I tried running duplicati from a private browsing window, hoping Firefox would not fill out any (hidden) password prompts and that works!

**Comment by ts678** [comment]
I'm glad it worked. There's an open issue on a similar autofill problem. Let me cross-reference:

[Password saver may autofill too many places, getting --auth-password is not supported #4102](https://github.com/duplicati/duplicati/issues/4102)

I don't know enough about web pages and password autofilling to know if the cause is similar.

**Comment by ts678** [comment]
[Restore does not work](https://forum.duplicati.com/t/restore-does-not-work/9856/5?u=ts678) was a similar case. I don't know if it's identical, but I'll mention it anyway.

> Chrome browser saved the password and that caused the issue! OMG.
> 
> To fix it, just delete all saved passwords from Chrome browser for Duplicati WebGUI.(http://localhost:8200/)

**Comment by ts678** [comment]
This problem has fortunately died down, so let's see where the several old reports might be standing at this point.

[2.0.5.112_canary_2021-01-20](https://github.com/duplicati/duplicati/releases/tag/v2.0.5.112-2.0.5.112_canary_2021-01-20) helped some of these with "Fixed password manager autofill, thanks @drwtsn32x".

@neduz seems to be due to a Firefox password manager autofill. @chris-y reported the same from Chrome [here](https://github.com/duplicati/duplicati/issues/3700#issuecomment-620873594).
@irstmon could be this. All files are affected on restore, yet database recreate (without user password field) works.
Original poster @alexlauerman case is the least clear but may be password autofill. Files were decrypted manually.
That led to a satisfactory outcome, so I'm not sure there's anything left to pursue. Issue will close if it remains idle.
