### ISSUE TITLE
Backblaze B2 Application Keys fail to authorize

### ISSUE THREAD

**Issue by sshaikh** [duplicati/duplicati#3366]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3
- **Operating system**: Debian
- **Backend**: Backblaze B2

## Description
Connection test fails when trying to use application keys - using the master key works.

## Steps to reproduce
Create new B2 bucket
Create and note new master key
Create and note new application key that is restricted to use the above bucket
Create a new backup job in Duplicati that backs up to this bucket
Use master key - connection test works
Use application key - connection test fails

- **Actual result**:
Connection test fails with "Failed to connect: 401 - unauthorized:"
- **Expected result**:
Connection test passes

## Notes
The use of B2 application keys differs from the master key, so needs explicit support (I suspect this support isn't present)

**Comment by ts678** [comment]
There are reports of success, e.g. [here](https://forum.duplicati.com/t/linux-mint-19-and-backblaze-b2/4465/3?u=ts678) and [here](https://forum.duplicati.com/t/new-user-with-duplicati-feedback/4565/6?u=ts678).   It also works for me, although I haven't tested extensively.

Do you have specific information on what sort of support is needed? I was hoping it's just docs and labels.

**Comment by sshaikh** [comment]
I can confirm that using the key id as the account id makes application keys work - but I had to ask on the forum as it wasn't clear.

So yes, perhaps the change is for docs/labels or a hint on the setting screen?

**Comment by bph84** [comment]
FWIW, Googling and the above comment was how I got past the issue.

**Comment by poleguy** [comment]
This should be re-opened. It's still an issue for any new users who haven't stumbled here. On the backup destination page, the box reads "B2 Account ID" and "B2 Cloud Storage Account ID" and they should be changed to read: "B2 Application Key ID" and "B2 Cloud Storage Application Key ID" as that's what's actually required.

In addition the error messages if you get it wrong are not helpful. Change those to add 'Be sure to enter the application key ID, not the account ID in the "B2 Application Key ID" field.'

**Comment by ts678** [comment]
This is a [new](https://www.backblaze.com/blog/b2-application-keys/) B2 scheme, the old one still works, and wording should probably offer a choice as [B2 does](https://www.backblaze.com/b2/docs/b2_authorize_account.html):

>  You can use either the master application key or a normal application key.
>
> You'll find the master key on the B2 Cloud Storage Buckets page on the web site. When using the master key, the "key id" is your account ID, and the "application key" is the one you got from the web site.

Their terminology is admittedly confusing now, and possibly could be better explained than above does.

**Comment by loslosbaby** [comment]
I was similarly confused and because I didn't have access to the B2 console, I spend 3hrs going ping-pong with my coworker to figure out if I needed the application-framework-inductor-array-signature-warp-core-key or the key-key-has-a-talking-cat-key.  I'm serious: it was a subtle piece of obfuscation and promoted several "argh!".  All in all, authorization took a day.

**Comment by nemobis** [comment]
> I can confirm that using the key id as the account id makes application keys work

Thanks. I had the same issue with duplicity 0.7.18.2 and b2 1.3.8. IMHO what needs fixing is the upstream docs: https://help.backblaze.com/hc/en-us/articles/115001518354-How-to-configure-Backblaze-B2-with-Duplicity-on-Linux . I've sent a support request (or at least I hope it went through), you may want to comment there as well.

**Comment by ikjadoon** [comment]
**_This issue needs to be re-opened_**. Duplicati's GUI has been deemed incorrect by Backblaze in a follow-up reply:

![image](https://user-images.githubusercontent.com/3848795/52308448-553fe100-296b-11e9-93f3-acf88d03f76f.png)

For new B2 users: use (2) and (3). (1) does not work with B2 & Duplicati.

![image](https://user-images.githubusercontent.com/3848795/52307976-1cebd300-296a-11e9-9cd5-d4eac6bcbc06.png)

![image](https://user-images.githubusercontent.com/3848795/52308031-46a4fa00-296a-11e9-8d4e-3c289436fd8a.png)

**Change "B2 Account ID or Application ID" to "Application ID" only.** 

The B2 Account ID (1) always results in a "Failed to connect: 401 - unauthorized". There may be an underlying issue in some documentation, but the reply from Backblaze is clear.

**Comment by Pectojin** [comment]
#3647 should address the cosmetic side of this.

**Comment by ikjadoon** [comment]
Thank you, @Pectojin. The issue is really with B2's vague documentation, but Duplicati would benefit from being more clear.  It's `Account ID` + `Master Application Key` _**or**_ `Application Key ID` + `Application Key`. Either set will work (all buckets vs one bucket, respectively), but it needs to be that set.

I followed up in #3647 with [a _more accurate_ suggestion](https://github.com/duplicati/duplicati/pull/3647#issuecomment-461290833) vs my [above comment](https://user-images.githubusercontent.com/3848795/52307976-1cebd300-296a-11e9-9cd5-d4eac6bcbc06.png).

**Comment by borfast** [comment]
Is this still an issue? I'm trying out Duplicati web GUI on Linux but I can't get the connection test to connect to my B2 bucket. It always says:
>  Failed to connect: Error: TrustFailure (The authentication or decryption has failed.) 

I already tried using the `Master Application Key ID` + `Master Application Key`, as well as an `Application Key ID` + `Application Key` but nothing seems to work.

I even tried fumbling with the B2-specific options in the advanced settings section but no joy.

Is this still working for everyone? What could I be doing wrong?

**Comment by ts678** [comment]
> What could I be doing wrong?

From Google search on that error, I wonder if your mono certificate store has been set up.

[Secure Socket Layer (SSL) / Transport Layer Security (TLS)](https://www.mono-project.com/docs/faq/security/#secure-socket-layer-ssl--transport-layer-security-tls) gives some troubleshooting tips.

I'm not sure which mono package has the needed tools, but [mono-complete](https://www.mono-project.com/download/stable/#download-lin) has them all.

**Comment by borfast** [comment]
Bingo, right on. In that case, I think the Duplicati Debian package needs an extra package. Tomorrow I'll try to figure out exactly which one it is and see about opening a pull-request with the necessary changes.

**Comment by makuto** [comment]
I don't want to cause spam on such an old thread, but on 2023-02-03 this issue was the first that came up when I was hitting what looked like the same problem.
The new issue for fixing the trust error is https://github.com/duplicati/duplicati/issues/4721 and a workaround is in the comments.
