### ISSUE TITLE
error every run

### ISSUE THREAD

**Issue by jprokopowich** [duplicati/duplicati#3382]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: ubuntu 18.04.1
- **Backend**: google drive

## Description
errors are generated and the backup does not complete

## Steps to reproduce
1. just let duplicati run on a "twice a day" schedule

- **Actual result**:
Duplicati.Library.Interface.UserInformationException: Found 1 files that are missing from the remote storage, please run repair at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList (Duplicati.Library.Main.BackendManager backend, Duplicati.Library.Main.Options options, Duplicati.Library.Main.Database.LocalDatabase database, Duplicati.Library.Main.IBackendWriter log, System.String protectedfile) [0x001aa] in <ae134c5a9abb455eb7f06c134d211773>:0 at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify (Duplicati.Library.Main.BackendManager backend, System.String protectedfile) [0x00066] in <ae134c5a9abb455eb7f06c134d211773>:0 
- **Expected result**:
no errors and a successful backup

**Comment by sfahrenholz** [comment]
Hey,

which version of duplicati did you use?
have you run the repair function?

![grafik](https://user-images.githubusercontent.com/6977657/45587521-08e5fd00-b907-11e8-86fa-2364b1f450ab.png)
![grafik](https://user-images.githubusercontent.com/6977657/45587531-2a46e900-b907-11e8-9f5a-0090c35a60e8.png)

**Comment by warwickmm** [comment]
Have you tried looking in Google Drive to see if the reported missing file is actually missing?

[This](https://forum.duplicati.com/t/a-diabolic-error-loop-backup-reports-1-missing-file-but-list-broken-files-reports-0/3816) post sounds related (similar error and backend).

**Comment by jprokopowich** [comment]
So i scrapped backing up to Google drive and now backing up to local NAS 
and still getting errors,

Failed to process file 
duplicati-b26c2db5de68147deb3b796d7043d1332.dblock.zip.aes
System.Exception: The file 
duplicati-b26c2db5de68147deb3b796d7043d1332.dblock.zip.aes was 
downloaded and had size 5242880 but the size was expected to be 52341213 
at Duplicati.Library.Main.BackendManager.GetForTesting (System.String 
remotename, System.Int64 size, System.String hash) [0x00065] in 
<ae134c5a9abb455eb7f06c134d211773>:0 at 
Duplicati.Library.Main.Operation.TestHandler.DoRun (System.Int64 
samples, Duplicati.Library.Main.Database.LocalTestDatabase db, 
Duplicati.Library.Main.BackendManager backend) [0x003f7] in 
<ae134c5a9abb455eb7f06c134d211773>:0

**Comment by warwickmm** [comment]
Do you have the same problem if you back up to a local folder?

**Comment by jprokopowich** [comment]
doesn't seem to be after running for a day.

**Comment by warwickmm** [comment]
Just for clarification, are you saying that backing up to a local folder worked initially, but now errors after every run?  Can you provide the error log for this case as well?

**Comment by jprokopowich** [comment]
Thus far the local backup runs okay except for some files that disappear with a live file system.

DeletedFiles: 1738 DeletedFolders: 0 ModifiedFiles: 1338 ExaminedFiles: 102925 OpenedFiles: 7434 AddedFiles: 6096 SizeOfModifiedFiles: 1525223463 SizeOfAddedFiles: 225424564 SizeOfExaminedFiles: 10060618575 SizeOfOpenedFiles: 1761629335 NotProcessedFiles: 0 AddedFolders: 0 TooLargeFiles: 0 FilesWithError: 0 ModifiedFolders: 0 ModifiedSymlinks: 0 AddedSymlinks: 0 DeletedSymlinks: 0 PartialBackup: False Dryrun: False MainOperation: Backup CompactResults: DeletedFileCount: 0 DownloadedFileCount: 0 UploadedFileCount: 0 DeletedFileSize: 0 DownloadedFileSize: 0 UploadedFileSize: 0 Dryrun: False MainOperation: Compact ParsedResult: Success EndTime: 2018-10-12 6:02:37 AM (1539342157) BeginTime: 2018-10-12 6:02:36 AM (1539342156) Duration: 00:00:00.8480060 BackendStatistics: RemoteCalls: 17 BytesUploaded: 218923839 BytesDownloaded: 60014615 FilesUploaded: 11 FilesDownloaded: 3 FilesDeleted: 1 FoldersCreated: 0 RetryAttempts: 0 UnknownFileSize: 0 UnknownFileCount: 0 KnownFileCount: 254 KnownFileSize: 6476453350 LastBackupDate: 2018-10-12 5:57:13 AM (1539341833) BackupListCount: 2 TotalQuotaSpace: 79132893184 FreeQuotaSpace: 58912632832 AssignedQuotaSpace: -1 ReportedQuotaError: False ReportedQuotaWarning: False ParsedResult: Success DeleteResults: DeletedSets: [ Item1: 1 Item2: 2018-10-11 12:04:36 PM (1539277476) ] Dryrun: False MainOperation: Delete ParsedResult: Success EndTime: 2018-10-12 6:02:37 AM (1539342157) BeginTime: 2018-10-12 6:02:34 AM (1539342154) Duration: 00:00:02.8864840 RepairResults: null TestResults: MainOperation: Test Verifications: [ Key: duplicati-20181012T105713Z.dlist.zip.aes Value: [], Key: duplicati-i75d6b02818b640369b1f77250bd9aac6.dindex.zip.aes Value: [], Key: duplicati-bc85de2d73bde4f01a2dca2d0258f337b.dblock.zip.aes Value: [] ] ParsedResult: Success EndTime: 2018-10-12 6:02:37 AM (1539342157) BeginTime: 2018-10-12 6:02:37 AM (1539342157) Duration: 00:00:00.3368790 ParsedResult: Warning EndTime: 2018-10-12 6:02:38 AM (1539342158) BeginTime: 2018-10-12 5:57:13 AM (1539341833) Duration: 00:05:24.4273740 Messages: [ Deleting 1 remote fileset(s) ..., Deleted 1 remote fileset(s), Compacting not required ] Warnings: [ Error reported while accessing file: /home/user1/.cache/mozilla/firefox/vfmgsn6s.default/cache2/entries/60662CFA2B8EEE754E7ED981D3D8AA963163FCB5 => Could not find file "/home/user1/.cache/mozilla/firefox/vfmgsn6s.default/cache2/entries/60662CFA2B8EEE754E7ED981D3D8AA963163FCB5", Failed to process path: /home/user1/.cache/mozilla/firefox/vfmgsn6s.default/cache2/entries/60662CFA2B8EEE754E7ED981D3D8AA963163FCB5 => Path doesn't exist!, Error reported while accessing file: /home/user1/.cache/mozilla/firefox/vfmgsn6s.default/cache2/entries/60E5DF2AFB40EC347144256F768F3550BB510686 => Could not find file "/home/user1/.cache/mozilla/firefox/vfmgsn6s.default/cache2/entries/60E5DF2AFB40EC347144256F768F3550BB510686", Failed to process path: /home/user1/.cache/mozilla/firefox/vfmgsn6s.default/cache2/entries/60E5DF2AFB40EC347144256F768F3550BB510686 => Path doesn't exist!, Error reported while accessing file: /home/user1/.cache/mozilla/firefox/vfmgsn6s.default/cache2/entries/617037790B094FE8B061CD67EEC8FDE8DF42391C => Could not find file "/home/user1/.cache/mozilla/firefox/vfmgsn6s.default/cache2/entries/617037790B094FE8B061CD67EEC8FDE8DF42391C", ... ] Errors: []

**Comment by warwickmm** [comment]
When you were backing up to a NAS, what backend did you configure Duplicati with?

**Comment by jprokopowich** [comment]
Storage type I choose was "local folder or drive".

Note, The samba share on the NAS is mounted via CIFS.

**Comment by ts678** [comment]
> had size 5242880 but the size was expected to be 52341213

5242880 is 500000 hexadecimal. Even values are a symptom of filesystem or SMB problems.
Duplicati uses SMB from the OS as if it were a local folder or drive, but systems can mess up.

[2.0.6.103_canary_2022-06-12](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.103-2.0.6.103_canary_2022-06-12) (and so also 2.0.7.1_beta_2023-05-25 and later Beta):

> Added check to detect partially written files on network drives, thanks @dkrahmer

It's a size verification which is on by default. It may or may not catch everything that may fail.

Is the issue still of interest and reproducible? If there's nothing to say, the issue will be closed.
