### ISSUE TITLE
AlphaVSS Files missing in Visual Studio build

### ISSUE THREAD

**Issue by mikaelmello** [duplicati/duplicati#3384]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.11
- **Operating system**: Windows 10

## Description

I got the `Failed to enumerate Microsoft SQL Server databases` error and after some debugging, I found it happened while trying to load `alphavss/AlphaVSS.x64.dll`.

Apparently the files `AlphaVSS.Common.dll`, `AlphaVSS.x64.dll` and `AlphaVSS.x86.dll` are not being copied into a folder called `alphavss` as it should. Actually the folder does not even exist in the final build. The closest file is `AlphaVSS.Common.dll`, but it is on the root directory of the build folder.

The solution is built using Visual Studio 2017.

While searching for similar problems, I see that you are manually adding the files in the build script used in Linux? Explicitly saying that `xbuild` is not picking them up: https://github.com/duplicati/duplicati/commit/4d4661ce165838c8503eb5c5ba48d8d3f11fb93a. Perhaps something similar should be done in Windows.

To get the error you must be running Duplicati as an administrator in Windows.

In the following code, we can see that whenever the user is not an administrator, it just returns OK:  https://github.com/duplicati/duplicati/blob/0901d3f62f7fbd9d76cd609c62c08ee7c22e5d5c/Duplicati/Server/WebServer/RESTMethods/MSSQL.cs#L44-L48

Meanwhile, if it is one, Duplicati needs to load AlphaVSS under the `<build>/alphavss/` repository, these files however are not copied during the build. In my case, I happen to both have MSSQL and be an administrator, thus needing AlphaVSS and not finding it.

I believe this has gone unnoticed because in the distributed binaries the maintainer uses `build-release.sh` which takes care of this for any possible Windows users running Duplicati as admin while no one developing on Windows did 1. Run VS as an admin 2. See the error and 3. Report it

## Steps to reproduce

1. Clone the repository
2. Make sure you are using Windows and have MSSQL installed
2. Open Visual Studio as an Administrator and build the solution
3. Open the Add Backup page. It will probably show the above-mentioned error.

- **Actual result**:
No errors
- **Expected result**:
Error

## Screenshots

![image](https://user-images.githubusercontent.com/17488630/45621989-e3690880-ba58-11e8-8a88-87d465ae092e.png)
![image](https://user-images.githubusercontent.com/17488630/45622035-0f848980-ba59-11e8-8ea3-586fdac27556.png)
![image](https://user-images.githubusercontent.com/17488630/45622051-1a3f1e80-ba59-11e8-86d8-1a7c167d4266.png)
![image](https://user-images.githubusercontent.com/17488630/45622067-26c37700-ba59-11e8-8c29-33b7e038301f.png)
![image](https://user-images.githubusercontent.com/17488630/45622132-54102500-ba59-11e8-96f6-3a9e52f601b4.png)

**Comment by warwickmm** [comment]
I don't think I'm experiencing this, although I'm using MonoDevelop on Linux.  I believe that `AlphaVSS.x64.dll` is obtained via NuGet, and I think MonoDevelop restores the NuGet packages when loading the solution.  Does the file exist anywhere in your directory tree?  In my repository, I see
```
$ find . -type f -name AlphaVSS.x64.dll
./packages/AlphaVSS.1.4.0/build/net45/AlphaVSS.x64.dll
./packages/AlphaVSS.1.4.0/build/net40/AlphaVSS.x64.dll
./Duplicati/Library/Snapshots/bin/Release/AlphaVSS.x64.dll
```

**Comment by mikaelmello** [comment]
> I don't think I'm experiencing this, although I'm using MonoDevelop on Linux. I believe that `AlphaVSS.x64.dll` is obtained via NuGet, and I think MonoDevelop restores the NuGet packages when loading the solution. Does the file exist anywhere in your directory tree? 

Yes, those files exist under the directory `Duplicati\Library\Snapshots\bin\Debug` (or the Release equivalent).

The problem is that they do not exist under the TrayIcon build directory. So when there is an attempt to open the path `<build directory>/alphavss/AlphaVSS.*.dll`, neither the files or the folder exist, hence the thrown exception.

> I don't think I'm experiencing this, although I'm using MonoDevelop on Linux.

Linux is probably the reason why it works for you. I believe you are using the `build-release.sh` script to build the project, which takes care of it for you by manually creating the folder and copying the files as I've said in the PR that this was added in the commit https://github.com/duplicati/duplicati/commit/4d4661ce165838c8503eb5c5ba48d8d3f11fb93a.

**Comment by warwickmm** [comment]
That's interesting.  I'm not using `build-release.sh` (confirmed by deleting the file) and have no problems building with either MonoDevelop or on the command line with `mdtool`, creating a backup, and running it.

Are you seeing any errors/warnings in the build output?

**Comment by mikaelmello** [comment]
@warwickmm No, none at all. What makes me even more confused is that I've spent a couple weeks developing and never encountered this problem, I seriously don't know what could've been changed.

The problem persists on a fresh clone of the repository, I'll try some old commit from when I started with Duplicati.

**Comment by warwickmm** [comment]
:+1:  @mikaelmello.

**Comment by mikaelmello** [comment]
Closing this because it is not an issue for normal users, only happens when you build it from VS and ship it. The solution is to use `build-release.sh` when building.
