### ISSUE TITLE
Web service hostname check, blocks access to existing installations

### ISSUE THREAD

**Issue by Taomyn** [duplicati/duplicati#3386]
## Environment info
- **Duplicati version**: v2.0.3.11-2.0.3.11_canary_2018-09-05
- **Operating system**: Windows, Fedora Server (but probably all others as well)
- **Backend**: n/a

## Description
After upgrading from beta to latest canary, the "web service hostname check" defaults to not allowing any remote hostnames. This is fine for a new installation, but for existing installs where remote management has already been working this is a problem as you then have to visit each machine and change the setting.

## Recommendation
For existing installations, set the hostname to "*" to continue previous behaviour.

**Comment by Taomyn** [comment]
I just got bitten by this on my headless Fedora Server, I upgraded it by accident (thought I was on another machine), and was left with a system I could not manage by browser.

Couldn't find any documentation on how to set the allowed hostnames by command-line, so in the end had to copy the SQLite config database to my Windows machine, edit the setting there and upload the database back to the server.

I can also confirm the GUI does not show the "allowed hostnames" when connected remotely, so I'm completely unable further change this option without my SQLite tool.

**Comment by pcross616** [comment]
I just ran in to this.. any work around yet for headless servers and upgrade which block access remotely.  Can we get a flag we can pass in via the cli?

**Comment by TreeBranches** [comment]
Was about to configure this on our headless server but wanted to check if there was a work around in case our team changed hardware and forgot to update this setting.

Thankfully I came across this issue... guess I'll be using the * entry until this is implemented.

**Comment by Taomyn** [comment]
Yes it looks fixed, I've not had the issue for some time now.
