### ISSUE TITLE
Files to-go counter not working

### ISSUE THREAD

**Issue by Puugi** [duplicati/duplicati#3407]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.11_canary_2018-09-05
- **Operating system**: Qnap QTS 4.3.4.0695
- **Backend**: Jottacloud

## Description
I'm running several backup jobs, and it seems that web-interface counter for files (and size) is not getting lower during backup process. It just shows the total amount and size it started the backup job with. Live upload speed measurement seems to work, and it is changing normally on web-interface. Backup itself work ok, but it is not possible to see what is the progress of backup job.

## Steps to reproduce
1. Create backup job towards Jottacloud, using 100MB chunks.
2. Run backup job.

- **Actual result**: Web-interface counter of files and size to go is not getting smaller (even if running backup for days).

- **Expected result**:
Files and size to go counter should get smaller to be able to estimate how many files still to go.

**Comment by huste** [comment]
Still there in 2.0.4.18. Furthermore, as my bakup includes over 100000 files amounting up to 150GB of data, the "backup started" phase takes very long without giving any UI feedback. There were versions of Duplicati that continuosly increased the file and size counter until the real backing up of files started and the counter decreased again. I'd really like to see that behaviour back
