### ISSUE TITLE
Usn-policy setting not respected

### ISSUE THREAD

**Issue by NTWarrior** [duplicati/duplicati#3418]
----------------------------------------

- **Duplicati version**: v2.0.3.11-2.0.3.11_canary_2018-09-05
- **Operating system**: Windows 10 1803 x64
- **Backend**: Google Drive

## Description
My NTFS backups are failing due to #3311 so I wanted to disable usn-policy, but I found that the default is still set to off yet usn-policy is used anyway. This may have been the case since v2.0.3.7-2.0.3.7_canary_2018-06-17?

- **Actual result**:
usn-policy is set to off by default, but Duplicati uses USN anyway.
- **Expected result**:
usn-policy to be set to auto by default, and changing it to off disables it.

**Comment by warwickmm** [comment]
How are you setting this option?  I'm not familiar with the usn-policy code, but at a quick glance it looks like it's parsing the options correctly.

**Comment by Pectojin** [comment]
This sounds like a bug. The default value is definitely "off" and default values (should) always apply unless explicitly declared.

**Comment by warwickmm** [comment]
From the discussion in issue #3311 and the fix implemented in afe389ff5d338f5a59a061d6d99dec0606e862d1, it looks like the issue resided in the `USNJournal.GetVolumeRootFromPath` method.

I stepped through the debugger and can confirm that with the default usn policy, the `USNJournal.GetVolumeRootFromPath` method is never invoked.  This is with revision 6550a699096b6a1127672507a6f62ed86b645762 on Linux.  I wouldn't think the behavior would be different on Windows, but I can't be certain.

Is it possible that a different part of the code is also throwing the `System.IO.PathTooLongException`?

**Comment by verhoek** [comment]
@NTWarrior your assumption that the setting of the option was based on the fact that Duplicati crashed no matter what?
If so, can you try the new canary release and tell me if the problem still resides?

**Comment by NTWarrior** [comment]
My backup got interrupted so I installed the latest canary before resuming and removed the advanced setting option where I had explicitly set it to off. It is taking a long time on the verifying backend data stage (I restarted the backup about 18hrs ago) but has not crashed yet, I will update this depending on how it goes.

**Comment by warwickmm** [comment]
@NTWarrior, just curious if you're still experiencing this issue or if it can be closed?  It seems that we are unable to reproduce it and no one else appears to have experienced this.

**Comment by ts678** [comment]
> I will update this depending on how it goes.

@NTWarrior See above request. Any updates?

**Comment by NTWarrior** [comment]
I haven't tried used Duplicati in years and can't recall whether there was a change so I've closed this
