### ISSUE TITLE
Question (and problem?) regarding successive updates

### ISSUE THREAD

**Issue by mikaelmello** [duplicati/duplicati#3427]
From what I can tell, everytime you upgrade Duplicati via Duplicati itself, it downloads the zip file, unzips it under `updates/` and from them on, it will execute the executables from this new directory. Is that how it really works?

This can become a problem when the number of successive updates starts to increase, making Duplicati take a lot of space.

Is there a working mechanism to delete old versions of Duplicati? Or to simply replace the files when an update is downloaded?

Follow-up question: when downloading a MSI installer from a new version, I suppose it replaces all outdated files, is that also correct?

Thanks in advance

**Comment by Pectojin** [comment]
Seeing as we have no rollback functionality, I think it would make sense to clear out all old updates after successfully upgrading.

I usually upgrade from the packages on my Mac and Linux machines because it's cleaner just overwriting the entire installation. I believe the MSI works the same way.

**Comment by mikaelmello** [comment]
> I think it would make sense to clear out all old updates after successfully upgrading.

Great, do you have any directions on how/where to do that? After reading a bit I imagine it is going to be something like this

```
if (INSTALLDIR != null && System.IO.File.Exists(System.IO.Path.Combine(INSTALLDIR, CURRENT_FILE)))
{
    try
    {
        var current = System.IO.File.ReadAllText(System.IO.Path.Combine(INSTALLDIR, CURRENT_FILE)).Trim();
        if (!string.IsNullOrWhiteSpace(current))
        {
            // get all directories from INSTALLDIR where name < current
            // delete them
        }
    }
    catch (Exception ex)
    {
        if (OnError != null)
            OnError(ex);
    }
}
`

I just don't really know the best way to delete them and where in the startup stack to put this code

**Comment by mikaelmello** [comment]
Following on the previous comment, what do you think about this?

https://github.com/LacunaSoftware/duplicati/commit/4d851030b5e30cd42c6ba118ff94999355dc5722

**Comment by Pectojin** [comment]
I like it. 
I was thiking of putting the solution in the [Update Poll Thread class](https://github.com/duplicati/duplicati/blob/681f4ee33b0c165ed95ef8b3010567394c9de73a/Duplicati/Server/UpdatePollThread.cs) class, but that's probably an abstraction layer too high.

I think we might need some additional error handling so we don't prevent startup if we're unable to delete old updates.

**Comment by mikaelmello** [comment]
So basically a new try catch all?

What does `OnError()` do in that case? I'm not familiar with it

**Comment by mikaelmello** [comment]
Also, the way it is, if someone with an existent installation upgrades via Duplicati itself, then it will never execute this clean-up because everytime it runs from the latest update, it will stop at this condition:

https://github.com/duplicati/duplicati/blob/e1fb6d43c3728c34dd0fad14fae314e80f261039/Duplicati/Library/AutoUpdater/UpdaterManager.cs#L1082-L1094

Any ideas?

**Comment by Pectojin** [comment]
`OnError` is an event pattern, so it just executes whatever function it was given. 
In this case it's [a logging function](https://github.com/LacunaSoftware/duplicati/blob/4d851030b5e30cd42c6ba118ff94999355dc5722/Duplicati/Library/AutoUpdater/Program.cs#L52)
```
UpdaterManager.OnError += (ex) => Console.WriteLine("Error detected: {0}", ex);
```

If it won't execute in every desired scenario, then perhaps we might need to go slightly further up? Or modify the handling to trigger the cleanup even if we have the right version?

**Comment by ts678** [comment]
To comment on the opening question about "from them on, it will execute the executables from this new directory. Is that how it really works?", you wind up there, but you start at the base version such as would install into Windows "Program Files". The "About" --> "System info" screen has base and current versions.

The base version picks the latest installed update that [seems intact](https://github.com/duplicati/duplicati/issues/2717#issuecomment-401916516), sets an [env var](https://forum.duplicati.com/t/updating-via-web-interface-vs-installing-deb-package/3331/6?u=ts678) (look in your file to see what IsRunningInUpdateEnvironment() does inside) to prevent an infinite loop of that, then restarts at the newest version of itself (which might just be the base version, so be careful about "update" in the names).

This is why you see most [Duplicati processes](https://forum.duplicati.com/t/solved-is-it-ok-that-i-see-5-processes-of-duplicati-in-windows-task-manager/3948/20?u=ts678) in pairs. The parent spawns the child, the child does the work including checking for updates and installing them. The activate plan seems to be that MAGIC_EXIT_CODE from the child tells the parent to scan the installed updates again, however Duplicati.Server.exe isn't paired on Windows Service installs, so its UI activate [silently fails](https://github.com/duplicati/duplicati/issues/3371), forcing one to manually restart Duplicati service.

If one [forces a pairing](https://forum.duplicati.com/t/activate-downloaded-upgrade-sometimes-fail/4588/5?u=ts678), activate works, but I/O fails, and I'm not sure what else might go against the design. Updates are a complex business. Above was a heavy introduction, but please feel free to verify and pursue.

Thanks!

**Comment by mikaelmello** [comment]
> however Duplicati.Server.exe isn't paired on Windows Service installs, so its UI activate silently fails, forcing one to manually restart Duplicati service.

So that's why it does not work under Windows Services, thanks, I couldn't find out the reason. What do you mean by I/O fails?

@Pectojin 
> If it won't execute in every desired scenario, then perhaps we might need to go slightly further up? Or modify the handling to trigger the cleanup even if we have the right version?

What about this?

https://github.com/duplicati/duplicati/compare/master...LacunaSoftware:delete-old-updates

**Comment by mikaelmello** [comment]
Interesting, I didn't know that's the way how it is done.

> so maybe the I/O behavior for this got rearranged as part of the big 2.0.3.6 concurrency rewrite?

No idea, I arrived here at 2.0.3.10
