### ISSUE TITLE
Backups with an empty description are not possible

### ISSUE THREAD

**Issue by jeroenmeulenaar** [duplicati/duplicati#3433]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: debug, 2018.10.14
- **Operating system**: Win7/32bits
- **Backend**: n/a

## Description
The "description" field should be non-empty, but the GUI doesn't check on this.

## Steps to reproduce
Add a new backup, but leave "Description" empty. The GUI doesn't check this, but the final step 5 will reply with "Unable to save schedule or backup object: constraint failed".

- **Actual result**:
An error is thrown
- **Expected result**:
Backups with an empty 'description' should be allowed.

**Comment by Pectojin** [comment]
Yup. This one is related too #3428

There are some issues with default values.

**Comment by jeroenmeulenaar** [comment]
> Yup. This one is related too #3428
Hmm, I thought I searched the open issues :).

To me the simplest option would be to remove the "NOT NULL" constraint from the database; looks better than tricking it with an empty string.

**Comment by mikaelmello** [comment]
@jeroenmeulenaar While I agree with you, @Pectojin said:

> That way we don't need to deal with null exceptions other places in the application since it should always be a string.

And in my opinion having an empty description makes more sense than a NULL value.

Regarding the error displayed when the description is not filled, I made a quick hack here: https://github.com/LacunaSoftware/duplicati/commit/8634c85c6fdc45f86ad88066b17712f1fbf17547

**Comment by jeroenmeulenaar** [comment]
> @jeroenmeulenaar While I agree with you, @Pectojin said:
> 
> > That way we don't need to deal with null exceptions other places in the application since it should always be a string.
> 
> And in my opinion having an empty description makes more sense than a NULL value.

Okay, I agree with the annoyance of having a NULL value, so let's make it indeed into an empty string.
 
> Regarding the error displayed when the description is not filled, I made a quick hack here: [LacunaSoftware@8634c85](https://github.com/LacunaSoftware/duplicati/commit/8634c85c6fdc45f86ad88066b17712f1fbf17547)

Maybe it's then good to update the UI as well, and display "Description (optional)" instead of "Description"?

**Comment by mikaelmello** [comment]
> Maybe it's then good to update the UI as well, and display "Description (optional)" instead of "Description"?

Great suggestion, thanks. I'll make all those changes in a separated branch and create a PR.
