### ISSUE TITLE
Synology DS218+ Dropbox Failed to connect: Error reading JObject from JsonReader. Path '', line 0, position 0. 

### ISSUE THREAD

**Issue by progers885** [duplicati/duplicati#3434]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: DSM6.2.1-23824
- **Backend**: Dropbox

## Description

Dropbox fails connection test

## Steps to reproduce

1. Load Mono and Duplicati
2. Configure new backup to dropbox
3. get an auth id
4. click test connection

- **Actual result**:
Failed to connect: Error reading JObject from JsonReader. Path '', line 0, position 0. 
![image](https://user-images.githubusercontent.com/12861245/47039291-89ed1a00-d17b-11e8-9a6c-c2aad5ab0086.png)

- **Expected result**:
I expect it connect and make the backup directory
- **Further info - Workaround**:
If I set the advanced options and accept-any-ssl-certificate it works and I can set up the backup
I did try accept-specified-ssl-hash instead, Default value: "" but get the same error
I have a Mac using dropbox on the same network and this does not have any problems so its not a router problem.

Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0. at Newtonsoft.Json.Linq.JObject.Load (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Linq.JsonLoadSettings settings) [0x00026] in <dc86da7fc46c487ba6c7ab826da479cc>:0 at Newtonsoft.Json.Linq.JObject.Parse (System.String json, Newtonsoft.Json.Linq.JsonLoadSettings settings) [0x0000c] in <dc86da7fc46c487ba6c7ab826da479cc>:0 at Newtonsoft.Json.Linq.JObject.Parse (System.String json) [0x00000] in <dc86da7fc46c487ba6c7ab826da479cc>:0 at Duplicati.Library.Backend.DropboxHelper.handleDropboxException (System.Exception ex, System.Boolean filerequest) [0x000db] in <5574f031befb42a98fe12b07aec6b39b>:0 at Duplicati.Library.Backend.DropboxHelper.ListFiles (System.String path) [0x0002b] in <5574f031befb42a98fe12b07aec6b39b>:0 at Duplicati.Library.Backend.Dropbox.<List>b__14_0 () [0x00000] in <5574f031befb42a98fe12b07aec6b39b>:0 at Duplicati.Library.Backend.Dropbox.HandleListExceptions[T] (System.Func`1[TResult] func) [0x00000] in <5574f031befb42a98fe12b07aec6b39b>:0 at Duplicati.Library.Backend.Dropbox+<List>d__14.MoveNext () [0x00040] in <5574f031befb42a98fe12b07aec6b39b>:0 at Duplicati.Library.Interface.BackendExtensions.TestList (Duplicati.Library.Interface.IBackend backend) [0x00017] in <b7a5128865b14f37a66544de6a7ae6fb>:0 at Duplicati.Library.Backend.Dropbox.Test () [0x00000] in <5574f031befb42a98fe12b07aec6b39b>:0 at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection (System.String url, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x000b7] in <670b0e4a9ae144208688fcb192d20146>:0 at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.POST (System.String key, Duplicati.Server.WebServer.RESTMethods.RequestInfo info) [0x00091] in <670b0e4a9ae144208688fcb192d20146>:0 at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x0026e] in <670b0e4a9ae144208688fcb192d20146>:0

**Comment by sfahrenholz** [comment]
Reference to #3374

**Comment by warwickmm** [comment]
I believe this was fixed in pull request #4195.
