### ISSUE TITLE
Show Warning Only Shows Logs Page

### ISSUE THREAD

**Issue by Darkknight33** [duplicati/duplicati#3449]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.11_canary_2018-09-05
- **Operating system**: Ubuntu 18.04
- **Backend**: S3 Comp

## Description
Open GUI, dialog box at that bottom says there was "1 Warning". Click show, it takes you to the log page where there are 10's of different logs, and it's unclear where the warning is coming from. Either dialog box should take you to the specific log, or logs list should have conditional coloring for logs containing warnings (yellow) or errors (red). UI Enhancement?

## Steps to reproduce
Perform operation that produces a warning.
Click 'Show' on dialog box from main UI. 
Try to find problem log in a list of 50 events.

- **Actual result**:
Taken to logs list, unclear where problem is.
- **Expected result**:
Taken to actual log containing warning message so you can find what went wrong.

**Comment by mikaelmello** [comment]
+1

Adding to that, whenever a backup outputs errors or warnings, when we click OK it takes us to the logs general page instead of the logs specific to that backup.

**Comment by warwickmm** [comment]
This has been much improved in pull request #3538.  The warnings are now more explicit and highlighted in a different color.
