### ISSUE TITLE
Can't restore files from .dblock.zip.aes and .dindex.zip.aes (no database and no remote)

### ISSUE THREAD

**Issue by joe307bad** [duplicati/duplicati#3463]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.12_canary_2018-10-23
- **Operating system**: Ubuntu 16.04 64bit / Linux 4.9.80-rancher
- **Backend**: Backblaze

## Description

My hard drvie crashed and I had a hard drive of my backed up files sent to me by Backblaze. They sent me a hard drive that contains a series of .dblock.zip.aes and .dindex.zip.aes files. There are no other files on the hard drive. I am unable to restore any of these files using the Duplicati docker image/container.

## Steps to reproduce

1. Running a `repair` command returns the following error:
```
  Listing remote folder ...

ErrorID: EmptyRemoteLocation
No filelists found on the remote destination
Return code: 100
```
2. Running a `restore` command returns the list of all the files as `Extra unknown file`

- **Actual result**:
None of the commands seem to have any effect
- **Expected result**:
Decryption and restoration of my files

**Comment by Pectojin** [comment]
Without any dlist files or a local database the rest of the data is useless. 

But there should have been a dlist file for each restore point. What was your retention policy? How many backups did you have?

**Comment by joe307bad** [comment]
Thanks for the feedback @Pectojin.

I was using Backblaze and it seems my bucket only has dblock and dindex files and nothing else. 

> What was your retention policy? How many backups did you have?

I had a lot of data to back up (>2tb) and I was using a method of pausing the backup and resuming it once a month because my wifi has an upload/download limit of 1tb. Since I never fully finished the backup (I got about 1.3tb through), could that be why I didn't get the proper dlist files generated?

**Comment by joe307bad** [comment]
I appreciate the insight @Pectojin. That is unfortunate but at least I now know the issue.

**Comment by Pectojin** [comment]
I'm not familiar with ddrescue, but in principle if the entire Duplicati DB is recoverable the uploaded data should be recoverable.

**Comment by TimetravelerDD** [comment]
not sure if this is still relevant, but based on this [article ](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/)I come to the following conclusion:

with the dlist file missing the file names and the file location is gone. however it would be theoretically imaginable to restore the raw file content. You could try to interpret each block that is a multiple of 32 bytes as a blocklist and then attempt to restore the raw file from the other blocks. You would end up with all your files with random names in a single folder.

However I doubt this is implemented in software yet.
