### ISSUE TITLE
Icon on settings page seems to have no function

### ISSUE THREAD

**Issue by sNiXx** [duplicati/duplicati#3469]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.3.3
- **Operating system**: Windows 10
- **Backend**: Local

## Description
An information icon in general settings seems to have no function. Maybe you could add an explanation explaining what this option actually does. What is its startup impact (Windows startup)?

## Steps to reproduce
1. Open Duplicati
2. Go to "Settings" page
3. Try to click or hover over info icon next to "Pause after startup or hibernation"

- **Actual result**:
No effect when trying to click or hover over the icon
- **Expected result**:
Show information regarding this setting upon clicking or hovering

## Screenshots
![infoicon](https://user-images.githubusercontent.com/3066873/47964250-42013a80-e037-11e8-8894-69f1ef7e83a4.png)

**Comment by Pectojin** [comment]
I never even noticed that one. What's curious is that I can't find any other place in the UI featuring an info icon. 

There isn't really a defined behaviour for such a button, so I tried putting a title on it that would show up when hovering over it. It didn't feel very dynamic and it was actually a bit uncomfortable using.

I am thinking to do something like this instead:
<img width="698" alt="screenshot 2018-11-04 at 14 29 44" src="https://user-images.githubusercontent.com/1561484/47964724-1f265480-e03e-11e8-941c-54756d668455.png">

**Comment by ts678** [comment]
I found another of these at MENU --> Restore --> Direct restore from backup files --> Encryption --> Advanced Options, from search for relevant source to see how common this design was (or was not).

![image](https://user-images.githubusercontent.com/40771998/48132516-da7b0300-e261-11e8-8039-9b9868f8aba3.png)

**Comment by Pectojin** [comment]
Good find! I've removed it in #3475

**Comment by warwickmm** [comment]
I think this has been resolved in pull requests #3470 and #3475.
