### ISSUE TITLE
Filters GUI not detecting some regular expressions

### ISSUE THREAD

**Issue by maforshaw** [duplicati/duplicati#3473]
- [x] I have searched open and closed issues for duplicates.

## Environment info
- **Duplicati version**: 2.0.3.13_canary_2018-10-31
- **Operating system**: Windows 10, Firefox 63

## Description
The "Filters" web GUI when editing a backup job does not correctly identify some filters which are valid regular expressions. The backup engine correctly parses the regular expression so this is just a GUI issue.

## Steps to reproduce
1. Click "Edit as text" in the Filters section under Source Data.

2. Enter the following:
`-[.:\\Users\\[^\\]+\\OneDrive\\]`

3. Click "Edit as list".

- **Actual result**:
The GUI shows the entry as "Exclude File" instead of "Exclude regular expression". It also keeps the square brackets, which are usually removed for "Exclude regular expression".

- **Expected result**:
The GUI should show "Exclude regular expression" on the left and `.:\\Users\\[^\\]+\\OneDrive\\` on the right. It appears to be checking for the existence of * in the string to decide whether it is a regular expression or not. Shouldn't it just check if it starts with -[ and ends with ].

**Comment by warwickmm** [comment]
Is this related to #2220 at all?

**Comment by maforshaw** [comment]
I don’t think so. The issue reported here just affects the GUI. It didn’t cause a run time error.
