### ISSUE TITLE
Cache busting for new versions

### ISSUE THREAD

**Issue by mikaelmello** [duplicati/duplicati#3481]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

This is both a question and a suggestion:

How is browser caching handled on new updates? If I'm not mistaken, the cache lasts for only a day, so it's not that big of a problem.

However I did have some problems when launching new updates, where the cache had to be manually busted so the user could see the new changes made on the front-end.

My solution was to add version query strings to each front-end file and update them via the `UpdateVersionStamp` project on the new release.

Here they are:

https://github.com/LacunaSoftware/duplicati/commit/a1f1d84a019e15db611b3f5dd0f90bf3c792aeae

https://github.com/LacunaSoftware/duplicati/commit/ad03820260f42039079fe2eb5a713ec8eb268c10

and some older commits.

Just like the other issue I've just created, I can also create a PR with these changes if wanted.

**Comment by Pectojin** [comment]
We did some work on caching a while back (v2.0.2.18) due to some issues with XSRF token on the index.html page. That's when the cache date was set.

I don't remember our exact considerations for the CSS/JS caching back then but I think version tags will be a welcomed change as long as it's fairly dynamic.

**Comment by mikaelmello** [comment]
> I think version tags will be a welcomed change as long as it's fairly dynamic.

I believe they are. I used the same project meant to update the versions of all assembly files, so everything is updated in one go.

**Comment by mikaelmello** [comment]
A PR is made
