### ISSUE TITLE
Successful Backup not writing to Eventlog since latest update

### ISSUE THREAD

**Issue by irstmon** [duplicati/duplicati#3492]
Hi,

Since the upgrade to "2.0.4.1_experimental_2018-11-08" duplicati now logs to eventlog that it has send the email (1339) - but before there was an event that I could check with nagios: "Duplicati Backup erfolgreich" (1338). Since the email entry does not reflect wether the backup was successful or not - is there any chance to get 1338 back again?

Thanks!

**Comment by ts678** [comment]
I downloaded source code for [2.0.4.1_experimental_2018-11-08](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.1-2.0.4.1_experimental_2018-11-08) but could find nothing that is mentioning 1339 or 1338.
[EventLog Class](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.eventlog?view=netframework-4.8.1) seems to be how .NET Framework writes to the Windows event log, and you can see examples currently in
[https://github.com/duplicati/duplicati/blob/master/Duplicati/WindowsService/ServiceControl.cs](https://github.com/duplicati/duplicati/blob/master/Duplicati/WindowsService/ServiceControl.cs)
I'm not sure what Event ID is made if it's not explicitly given (as is so here), but I find no `WriteEntry` elsewhere in 2.0.4.1.
Do you happen to have an old sample event around, in the chance it gives further clues? Is this issue  even still of interest?

Note that you can use a [run-script-after](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#run-script-after) to study the backup results and do whatever you like, using tools you can obtain.

**Comment by irstmon** [comment]
I don't have an old sample anymore since eventlogs have rolled over since then multiple times and even the computers are not existent anymore. For me it's no longer important since I've since switched to not using duplicati.

Thanks anyway for taking a look at this - and sorry for not closing it
