### ISSUE TITLE
Last successful run duration is wrong

### ISSUE THREAD

**Issue by RalfZim** [duplicati/duplicati#3493]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3
- **Operating system**: Ubuntu 16.04 (Same issue on Windows10)
- **Backend**: Synology NAS

## Description

Being on the page "Home", I see my configuration "Test". There it now says: "Last successful run: Today at 10:18 AM (took 00:00:01)". However, when I loaded this page earlier today, the duration was displayed as "took 00:05:??", which is realistic.
So, this is a minor display issue only.

## Steps to reproduce

Not sure how to reproduce this. It always happens when I visit the page more than once after a backup.

- **Actual result**:
"took 00:00:01" (or "took 00:00:00", it changed after a few actions on the page)
- **Expected result**:
"took 00:05:??"

## Screenshots

![screenshot from 2018-11-13 14-56-14_duplicati](https://user-images.githubusercontent.com/27056047/48417994-7326ec80-e754-11e8-8436-8c2ec734fd2d.png)
![screenshot from 2018-11-13 15-50-34_duplicati](https://user-images.githubusercontent.com/27056047/48421035-fa2b9300-e75b-11e8-9c17-c8ecf8431807.png)

**Comment by cmeil** [comment]
I also have observed this. One way I can reproduce it is by going to the "Restore" page, selecting my backup and clicking "Next" and just allow it to populate the fileset. Then, without proceeding, go to the Home page again where the last duration is displayed, and it will be wrong (like "00:00:01").

**Comment by warwickmm** [comment]
The new [beta version](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.5-2.0.4.5_beta_2018-11-28) has been released.  If possible, can someone verify if this issue has been resolved?

**Comment by cmeil** [comment]
It appears fixed to me with the limited testing I've done so far with 2.0.4.5. I think it can be marked as closed and reopened if anyone finds otherwise.

**Comment by warwickmm** [comment]
Great!  Thanks for the feedback.
