### ISSUE TITLE
Cannot add stuff to HttpInput.Empty

### ISSUE THREAD

**Issue by mikaelmello** [duplicati/duplicati#3516]
Rarely, when trying to pause the server, a error will be thrown "Cannot add stuff to HttpInput.Empty", here is how to reproduce:

There are currently 2 different behaviors when making a POST request (to pause the server). Note that all 2 make the exactly same requests, however the content arriving at https://github.com/LacunaSoftware/duplicati/blob/608e4e7972ebd1308412c92108614b8f3f37d8ed/Duplicati/Server/WebServer/RESTHandler.cs#L129 differs on 2 occasions. I believe it is a bug in https://github.com/duplicati/httpserver

### Behavior 1

1. Close all tabs
2. Pause using the TrayIcon
3. Click on "Open" in the TrayIcon
4. Resume in the Web UI
5. Pause in the Web UI with the "Until resume" option

You will see "Cannot add stuff to HttpInput.Empty"

This happens because `info.Request.Form` will be exactly equal to `HttpServer.HttpForm.EmptyForm`, including `_ignoreChanges = true`. However the comparison will fail because, I guess, it is comparing references and not the content of the object.

Therefore when getting to the `else` clause, it will try to add an item to the object and since it has `_ignoreChanges = true`, it will throw an exception.

### Behavior 2

Right after testing Behavior 1, try pausing again.

This time `info.Request.Form` will be exactly equal to the previous one, but the comparison will evaluate to true and no exception is thrown.

### Behavior 3

For some reason, one time I got an HttpForm that already had the `duration` key in it, however I did not investigate why and am not sure the requests were the same as before, but they probably were.

**Comment by kenkendk** [comment]
This is fixed since we moved to Kestrel.
