### ISSUE TITLE
Computer goes into standby mode while backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#352]
_From [philipp....@googlemail.com](https://code.google.com/u/100686719337925947011/) on January 23, 2011 13:42:47_

What steps will reproduce the problem? Set your power options in windows to standby or hibernate and start a backup.
The computer goes into standby if you don't move your mouse or use your keyboard, even if a backup is running. What is the expected output? What do you see instead? Duplicati should prevent the computer to go into standby or hibernate while running a backup. I don't want to deactivate standby in windows completely for obvious reasons. What version of the product are you using? On what operating system? duplicati 1.2b, windows 7. What backend (destination) are you using? FTP Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=352_

**Comment by huste** [comment]
Does it really work? I started two backups with 2.0.0.80 yesterday (about 60GB over WLAN) and went to bed. In the morning, both laptops were on standby, the backup resumed with a lot of work to do. The --allow-sleep option ist not explicitly set, but as it defaults to false, it should probably work anyway.
