### ISSUE TITLE
2.0.4.5: No information about status

### ISSUE THREAD

**Issue by KommX** [duplicati/duplicati#3524]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Windows 10
- **Backend**: local

## Description

After updating to 2.0.4.5 I can't see a way to get something like a status. In previous versions I could see something at the top, but now there is simply a "backup name".

## Steps to reproduce

1. Start any backup.

- **Actual result**:
I just see that a task is running, see screenshot below.

- **Expected result**:
I expected to see some kind of information about the status of the current job. In previous versions I could see e.g. something like "file x/2000".

## Screenshots
![image](https://user-images.githubusercontent.com/7859245/49339915-06a75b00-f639-11e8-8806-a31f315fd33f.png)

## Debug log
I guess it isn't necessary in this case.

**Comment by warwickmm** [comment]
What browser are you using?  This is possibly related to issue #3485.

**Comment by warwickmm** [comment]
Ok.  Closing this in favor of issue #3485.
