### ISSUE TITLE
Hostnames field in Settings not reachable with headless deployments

### ISSUE THREAD

**Issue by JohanSF** [duplicati/duplicati#3525]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: https://hub.docker.com/r/linuxserver/duplicati/
- **Backend**: unRaid

## Description

I need to put an "*" in the Hostnames field in the Settings menu in order for my reverse proxy to work. But this is not possible because the Hostnames field is only shown when Duplicati is visited on `127.0.0.1`, however this is not possible because I run Duplicati in a docker container.

## Steps to reproduce

1. Deploy `linuxserver/duplicati:latest` docker container
2. Visit `localip:8200/ngax/index.html#/settings`, where `localip` fx could be `192.168.0.1`

- **Actual result**:
Hostnames field is missing and impossible to reach.
- **Expected result**:
Hostnames field should be available, or there should be some other way to edit that field, for example by editing a file within the docker container.

## Screenshots

- **Actual result**:
![image](https://user-images.githubusercontent.com/6782603/49343524-29eafe00-f66b-11e8-9c89-b633265f805b.png)
- **Expected result (from a friend that is not running Duplicati headless)**:
![image](https://user-images.githubusercontent.com/6782603/49343526-40915500-f66b-11e8-8183-f3c519acd7e7.png)

**Comment by gilbN** [comment]
+1

**Comment by Sergzy** [comment]
I run Duplicati in Docker and never had a problem accessing that field. Did you try using the default (not dark) theme?

**Comment by JohanSF** [comment]
Yes. Andt it is the same with Duplicati installed directly on my windows machine, only if I visit it by typing `127.0.0.1:8200` I see the Hostnames option. If I fx visit it by `localhost:8200` the option is not available.

The option should be available no matter how you visit the webui imo.

**Comment by mikaelmello** [comment]
I can't seem to reproduce this behavior right now (on Windows, debug and release version, both on beta).

Also never saw this before, it is really odd. Could this be something from your browser? An extension perhaps?

**Comment by JohanSF** [comment]
I have solved it for myself and made a suggestion to linuxserver about a fix for the docker container.

Although I still think it is a design flaw that you must be visiting via 127.0.0.1 to see the option in the web-ui. - if indeed this is design and not a bug?

It is not related to my browser. I have tried different browsers, different computers, different deployments and windows too, it seems like design to me.

**Comment by Sergzy** [comment]
@JohanSF have you even read my message?

It appears to be a problem with Docker image by linuxserver, so this hub is not the right one to report that issue. By the way, is there a reason why you do not want to use official Docker image by Duplicati team?

**Comment by JohanSF** [comment]
Yes Sergzy, perhaps it is a problem with the docker container. I am still awaiting a response to my post on the forum about that.
I prefer the docker container by linuxserver because it is officially supported by the Community Applications plugin in unRAID. Meaning it is very easy to add and comes with a nice template ready. Most of my containers are made by linuxserver because of this.

**Comment by Germs2004** [comment]
I had to use 127.0.0.1 to add the asterisk, and now I'm able to access Duplicati via its hostname.  But the hostname field is always empty when I load the settings page.  It seems the hostname field doesn't read/display the existing settings when the page loads.  Running 2.0.4.5_beta_2018-11-28.

**Comment by ts678** [comment]
> So there is some caching problem

[2.0.4.6_canary_2018-12-11](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.6-2.0.4.6_canary_2018-12-11)

> Added cache-buster for all local static files, thanks https://github.com/LacunaSoftware

Although it wasn't commented on, the flawed image in the original post is also missing the "Prevent tray icon automatic login".

[2.0.3.7_canary_2018-06-17](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.7-2.0.3.7_canary_2018-06-17)

> Added an option to disable automatic login from the tray icon

[2.0.3.10_canary_2018-08-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.10-2.0.3.10_canary_2018-08-30)

> Added a hostname check for the webserver

For Beta releases, these would both have arrived in [2.0.4.5_beta_2018-11-28](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.5-2.0.4.5_beta_2018-11-28), with the caching fix in [2.0.5.1_beta_2020-01-18](https://github.com/duplicati/duplicati/releases/tag/v2.0.5.1-2.0.5.1_beta_2020-01-18).

Regardless of whether this explains things correctly, there seem to be no further reports of this, so I'm assuming it's gone now.

If no other feedback arrives, issue will automatically close.
