### ISSUE TITLE
Warning --default-filters is not supported

### ISSUE THREAD

**Issue by jopels** [duplicati/duplicati#3532]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Windows 10
- **Backend**: FTP

## Description
Since the last update, my backup tasks show the following warning:
"Warning-Duplicati.Library.Main.Controller-UnsupportedOption]: The supplied option --default-filters is not supported and will be ignored,"
The backup seems to work but as I have several hourly backup tasks the warning popup gets quite annoying.
The reason seem to be that the default filters were deprecated, but the configs of the backup tasks were not updated by the updater. Unfortunately the UI does not allow to remove the option manually.
I suggest that the next backup removes the "--default-filters" option from the config files to avoid the unnecessary warnings.

## Steps to reproduce
1. Install a pre 2.0.4.5_beta_2018-11-28 release
2. create a bakup task with a default filter
3. update to 2.0.4.5_beta_2018-11-28
4. run the backup task

**Comment by warwickmm** [comment]
Some users had luck with the following.  Does this help at all?

https://forum.duplicati.com/t/default-filters-warning-in-2-0-4-5-beta/5456/2

**Comment by jopels** [comment]
Thank you very much! Ctrl-F5 and removing the option in the advanced options worked.
