### ISSUE TITLE
The requested file does not exist

### ISSUE THREAD

**Issue by bluegeekgh** [duplicati/duplicati#3540]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta
- **Operating system**: Windows 10
- **Backend**: Hubic

## Description

Repairing database gives the error: The requested file does not exist for two files
## Steps to reproduce

1. Repair the database (or Recreate o Delete and create again)

- **Actual result**:
Error while running Hubic..., Got 2 error(s)

**Expected result**:
No Errors

## Debug log

    Verifications: [
        Key: duplicati-i3224853f9f56429c8ae59e323514fff1.dindex.zip.aes
        Value: [
            Key: Error
            Value: The requested file does not exist
        ],
        Key: duplicati-ifa60a47bb672418c843b08d7885f2ce1.dindex.zip.aes
        Value: [
            Key: Error
            Value: The requested file does not exist
        ],-

**Comment by warwickmm** [comment]
Are you able to see if `duplicati-i3224853f9f56429c8ae59e323514fff1.dindex.zip.aes` exists on the backend?

**Comment by bluegeekgh** [comment]
No, it's not in the backend.
After running this old backup I had this problem. I think the new job deleted an old version but maybe the job failed or not completed. I should keeped all the old backups in this case.
Also the backend (hubic) it's showing some problems in its own.
So I close the issue and I'll open another if I can find the exact problem. Thanks.
