### ISSUE TITLE
Unable to restore files to samba/cifs mount

### ISSUE THREAD

**Issue by mongi3** [duplicati/duplicati#3544]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Ubuntu 18.04
- **Backend**: S3 Compatible (Minio)

## Description

I did a backup of numerous files/directories and went to restore a number of them to validate restore capability.  I started by removing a directory and then attempting to restore but it failed with numerous hash compare issues.  Seeking a minimal reproducible sequence I then tried a single file in that directory to restore and it came back good. 
 I then wiped the directory and restored that same file and another, and the other came out fine while the first had a hash issue.  I repeated the same restore of the two files again (not changing anything) and this time first file came back hashed correctly.  For some reason it appears that only one file is restored successfully at a time, even if multiples are selected.

It seems to do fine restoring the two files if I direct it to restore to different folder.

This is pretty basic capability so this seems like a user error of some kind, but I'm not sure where.  The setup is quite basic.  No special options...just taking defaults on everything when setting up the job.  Any ideas on where to look?

## Steps to reproduce

1. Backup directory with several files (each ~10MB in my case)
2. Remove directory that was backed up (prep for restore test)
3. Attempt restore of 2 files in that directory
4. After hash failure, perform the same restore operation again

- **Actual result**:
hash failures when multiple files need to be restored.
- **Expected result**:
Proper restore the first time.

**Comment by warwickmm** [comment]
Are you able to reproduce the issue using a local destination as the backend?

**Comment by mongi3** [comment]
I made a fresh backup job using a local disk mount as the storage and see the same issue with bad file hashes when it thinks its done.

You got me thinking of some other combinations to try.  My original source data is from a samba network mount.  When I move my files off the network mount to local disk things seem to work fine with either Minio or local disk storage backends.

**Are there known issues with SAMBA mounts**?  I'm not having any issues otherwise with the mounts. 
 My fstab entry is below:

`//<IP_ADDR>/data  /mnt/dataserver2  cifs  defaults,vers=1.0,uid=1000,gid=1000,file_mode=0775,dir_mode=0775,credentials=CRED_FILE,iocharset=utf8 0 0`

**Comment by warwickmm** [comment]
That's interesting.  Is it correct to say that the problems only exist if the source or destination is accessed via the samba mount?

Do you experience the same issue when your source and destination are on the local disk, and you try to restore to a folder on the samba mount?

**Comment by mongi3** [comment]
The issue appears to be isolated to **restoring** to samba/cifs mounted location.

I know backups are good since everything restores properly to non samba locations (binary diff against originals).  I further tested by restoring the local disk only backups to a samba location and had the same trouble.

Given the specifics I went searching around and found this thread from earlier in the year that looks to be the same issue (https://forum.duplicati.com/t/restore-failed-2-files/2859/27).  They seemed to work around by disabling caching, and then by just avoiding samba entirely, unfortunately the later is not an option in my case.  The samba mount originates from a USB drive hooked to my router and there's no way to serve via NFS.  I'll try messing with cache settings a bit.

This is pretty concerning.  My setup is pretty bare bones version of most recent LTS Ubuntu.  I use the network share frequently and I've not had any difficulties outside of Duplicati.  Does Duplicati do something special on writes different from normal file stream/copy operations?

```
$/usr/bin/mono-sgen --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
```

**Comment by warwickmm** [comment]
When restoring, Duplicati only requires simple list/read/write operations as abstracted by mono, so it _should_ be pretty agnostic to the type of local storage.  However, there are always special cases that cause issues.

A quick Google search for CIFS truncation yields many people having issues in all sorts of applications, often with no reported errors.  Many of them were able to resolve the issue by disabling caching.  If possible, can you give that a try and see if that yields any improvement?

**Comment by mongi3** [comment]
I added `cache=none` to my mount options in fstab and now the restores are successful.  I'm going to go ahead and close this issue since it seems to be a samba/cifs issue.  For anyone else who may come across an issue like this, my final fstab entry looks as follows:
```
//<IP_ADDR>/data /mnt/dataserver2 cifs defaults,vers=1.0,uid=1000,gid=1000,file_mode=0775,dir_mode=0775,credentials=<CRED_FILE>,iocharset=utf8,cache=none 0 0
```
Once mounted /etc/mtab shows the following (shows more options):
```
//<IP_ADDR>/data /mnt/dataserver2 cifs rw,relatime,vers=1.0,cache=none,username=<USERNAME>,domain=<DOMAIN>,uid=1000,forceuid,gid=1000,forcegid,addr=<IP_ADDR>,soft,unix,posixpaths,serverino,mapposix,acl,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1 0 0

```

Thanks @warwickmm for helping out!
