### ISSUE TITLE
Why low download speed?

### ISSUE THREAD

**Issue by elpedriyo** [duplicati/duplicati#3547]
Hello,

I just wanted to know why when reading the files, or downloading it for later to upload them, the connection is slower than when uploading, considering that download is reading and upload writing. The difference is quite high.

![screenshot_1](https://user-images.githubusercontent.com/3207791/50181401-92dda180-030c-11e9-9727-b1e34891f824.png)

Kind regards

**Comment by warwickmm** [comment]
This can be due to many factors.  If this is still an issue, please reopen with more details regarding version, backend, settings, etc.
