### ISSUE TITLE
In "Export backup configuration" we enter encryption key without verification

### ISSUE THREAD

**Issue by swaldman3** [duplicati/duplicati#3553]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.3_beta_2018-04-02
- **Operating system**: Windows 10
- **Backend**: Backblaze B2

## Description

The "Export backup configuration" screen offers the (necessary) option to encrypt the config file that will be exported. If this option is used, the user is asked to input the encryption key. 

This key is inputted only once, and is done in a hidden password field. At this point a typo would result in a config file which cannot be decrypted. (OK, so a cautious user might test restoring from the file, but we shouldn't rely on this)

RFE: Add a duplicate field here, compare them, and complain if they do not match, as per convention when inputting passwords etc elsewhere.

**Comment by Pectojin** [comment]
Should ship in next release 
![image](https://user-images.githubusercontent.com/1561484/50401845-fb57d300-0791-11e9-87d9-a40f728e4a11.png)
