### ISSUE TITLE
Missing live logs

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#3554]
It seems that the live logs have disappeared:

![image](https://user-images.githubusercontent.com/17345532/50370090-2acdcc00-0555-11e9-822e-ed53a463e191.png)

I was able to bisect this to revision 160e32a7c, which I think first showed up in version 
v2.0.4.6-2.0.4.6_canary_2018-12-11.  Is someone able to replicate this?

This is on Arch Linux with the Brave browser (0.57.18), which is based on Chromium (71.0.3578.80).

**Comment by Pectojin** [comment]
This also happenes on my 2.0.4.8 installation but I thought it was related to the MacOS startup issue I had.

**Comment by Pectojin** [comment]
I found the issue and opened a PR
