### ISSUE TITLE
v2.0.4.9-2.0.4.9_canary_2018-12-22 OS X installer pkg opens web UI twice

### ISSUE THREAD

**Issue by BrettDikeman** [duplicati/duplicati#3558]
Installing v2.0.4.9-2.0.4.9_canary_2018-12-22 on High Sierra (via pkg), the web UI page is loaded twice instead of once.

**Comment by Pectojin** [comment]
I couldn't replicate this when upgrading using the pkg file. Is this a fresh Duplicati installation?

**Comment by BrettDikeman** [comment]
Yes - I had purged the .config/Duplicati folder, app, etc. I'm not 100% sure I purged the LaunchAgent stuff. Give me an hour or two to get through what I'm on right now and I'll see if I can reproduce it myself.

**Comment by warwickmm** [comment]
Haven't heard of this occurring to other users, so I'm assuming this has been fixed.
