### ISSUE TITLE
Signature cache should be stored in Local profile by default instead of Roaming profile

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#356]
_From [icqk...@gmail.com](https://code.google.com/u/100513072317071784238/) on January 30, 2011 23:19:22_

What steps will reproduce the problem? 1. Open settings
2. Open "Advanced" tab
3. Look at Signature cache location What is the expected output? What do you see instead? Expected: C:\Users&#37;username&#37;\AppData\Local\Duplicati\Signature Cache
Instead: C:\Users&#37;username&#37;\AppData\Roaming\Duplicati\Signature Cache What version of the product are you using? On what operating system? Version 1.2b2, Windows 7 Professional

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=356_

**Comment by asteppke** [comment]
With the current 2.0.1.17_canary_2016-05-14 version of Duplicati this issue seems to be current again. In my roaming profile folder Duplicati creates several sqlite files larger than 100MB.

**Comment by kenkendk** [comment]
I think those files are the "local database" files, which are required.
Perhaps they should be stored elsewhere.

Please open a new issue, as this issue has been closed for 2 years and relates to Duplicati 1.3.x.
In the new issue, please list the names of the files so I can determine what they are.
