### ISSUE TITLE
Stored Log Data: Missing on first view

### ISSUE THREAD

**Issue by sfahrenholz** [duplicati/duplicati#3569]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**:  2.0.4.10_canary_2018-12-29
- **Operating system**: Windows 10
- **Backend**: Duplicati

## Steps to reproduce
1. Go To About
2. Go To Show Log
3. The Tab Stored is empty
4. Switch between live and Stored

- **Actual result**:
Aktual the message "Loading ..." is showing

- **Expected result**:
Lists of all stored Log-Informations

## Screenshots

![2018-12-29_10-24-58](https://user-images.githubusercontent.com/6977657/50536427-b8f91200-0b54-11e9-8eb9-35232cac7f27.gif)

**Comment by Pectojin** [comment]
When clicking over to the log page the stored logs do appear, but only after 60 seconds when the background request `/api/v1/serverstate/?lasteventid=11&longpoll=true&duration=299s` finishes.
Curiously, the stored logs appear immediately if you refresh the browser on the log page. 

The actual request to get the logs finish immediately, but the log view seems to be blocked until the pool request finishes.

It's also happening on my other system running 2.0.4.8, so it's not isolated to 2.0.4.10.
