### ISSUE TITLE
Remove the LocalBackupDatabase.BuildLookupTable method?

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#3579]
I was browsing the code and came across the `LocalBackupDatabase.BuildLookupTable` method.  The only usage is in the [BackupHandler class](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Operation/BackupHandler.cs#L462), where it is accompanied by the following comment:
```
// This should be removed as the lookups are no longer used
m_database.BuildLookupTable(m_options);
```
If the method is no longer being used, we should remove it.  Otherwise, we should clarify the comment to avoid any confusion.

**Comment by Pectojin** [comment]
Well, let's try! :) #3584
