### ISSUE TITLE
Update the MegaApiClient package to improve performance for the Mega backend

### ISSUE THREAD

**Issue by GSPP** [duplicati/duplicati#3589]
I have made [significant (~3x) performance increases for the Mega client library](https://github.com/gpailler/MegaApiClient/pull/109). They are available in the 1.7.1 release (https://github.com/gpailler/MegaApiClient/releases).

**Comment by Pectojin** [comment]
I can take a look at it later today

**Comment by GSPP** [comment]
I can confirm that the latest release contains the performance improvements. Nice!
