### ISSUE TITLE
Unable to update due to missing DNS records for update server(s)

### ISSUE THREAD

**Issue by CollinChaffin** [duplicati/duplicati#3598]
Rather than comment on previous closed issue #3571 and hope it gets noticed, considering this is critical enough that all Duplicati systems are unable to check and auto-update I thought it warranted opening a new active issue.

Here is the error shown in all my system logs:
```
System.Net.WebException: The remote name could not be resolved: 'alt.updates.duplicati.com'
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Duplicati.Library.AutoUpdater.UpdaterManager.CheckForUpdate(ReleaseType channel)
```

Here is the centralized tests from major backbone providers recursively:
https://mxtoolbox.com/SuperTool.aspx?action=a%3aalt.updates.duplicati.com&run=toolpage
https://tools.dnsstuff.com/#dnsReport|type=domain&&value=alt.updates.duplicati.com

And here is the query directly to the authoritative DNS server for duplicati showing zero DNS records for the update server being queried:
```
λ dig @ns1.gratisdns.dk alt.updates.duplicati.com

; <<>> DiG 9.9.6 <<>> @ns1.gratisdns.dk alt.updates.duplicati.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 63670
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;alt.updates.duplicati.com.     IN      A

;; AUTHORITY SECTION:
duplicati.com.          43200   IN      SOA     ns1.gratisdns.dk. hostmaster.gratisdns.dk. 2018061401 10800 3600 2419000 43200

;; Query time: 134 msec
;; SERVER: 109.238.48.13#53(109.238.48.13)
;; WHEN: Fri Jan 11 13:41:32 Central Standard Time 2019
;; MSG SIZE  rcvd: 117
```

So clearly this is pretty critical but should be quick to fix.  Of course the DNS propagation time after making the change can still be fairly considerable depending on location etc., so hopefully whomever has the ability can get them restored soon.

**Comment by Pectojin** [comment]
Are you unable to update currently? If so we need to investigate issues on the update server.

`alt.updates.duplicati.com` not being defined is not an issue per se. 

`updates.duplicati.com` is the first url to be checked, so this only becomes an issue when `updates.duplicati.com` is offline.

Since Duplicati does not currently have a secondary update server, there's nothing to set the alternative DNS name to.

**Comment by ts678** [comment]
Here, the `(502) Bad Gateway` is back, which makes it try the alternate server, which isn't there yet...
~~~
C:\Program Files\Duplicati 2>Duplicati.Library.AutoUpdater.exe check
Error detected: System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Duplicati.Library.AutoUpdater.UpdaterManager.CheckForUpdate(ReleaseType channel)
Error detected: System.Net.WebException: The remote name could not be resolved: 'alt.updates.duplicati.com'
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Duplicati.Library.AutoUpdater.UpdaterManager.CheckForUpdate(ReleaseType channel)
No updates found

C:\Program Files\Duplicati 2>
~~~

**Comment by Pectojin** [comment]
Hmm, that's pretty odd. I see the same just going through the browser.

@kenkendk can you see anything on the update server? It looks like the NGINX might be ok, but not the service behind.

**Comment by Pectojin** [comment]
The update server has been functioning since the new release today. Multiple people also confirm it on the forum. Are you able to update now?

**Comment by mgonzales71** [comment]
FYI - earlier noticed that I could not download and install update via the typical web gui (clicking download or install just gave the following error:

> Feb 18, 2019 6:57 PM: Error in updater
> System.Net.WebException: The remote name could not be resolved: 'alt.updates.duplicati.com'
>    at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()
>    at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()
>    at Duplicati.Library.AutoUpdater.UpdaterManager.DownloadAndUnpackUpdate(UpdateInfo version, Action`1 progress)
> 

so jumped to GitHub and downloaded and updated to latest canary build manually.

I am now seeing the above referenced error when checking for updates and the host alt.updates.duplicati.com

> 
> Feb 18, 2019 7:08 PM: Error in updater
> System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
>    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
>    at Duplicati.Library.AutoUpdater.UpdaterManager.CheckForUpdate(ReleaseType channel)
> 
> Feb 18, 2019 7:08 PM: Error in updater
> System.Net.WebException: The remote name could not be resolved: 'alt.updates.duplicati.com'
>   at System.Net.WebClient.DownloadFile(Uri address, String fileName) at Duplicati.Library.AutoUpdater.UpdaterManager.CheckForUpdate(ReleaseType channel)
> 

this is a test install so not worried but wanted to post in case this was still an issue (orig issue)

**Comment by ts678** [comment]
The secondary server has been [set up](https://forum.duplicati.com/t/release-2-0-4-37-canary-2019-12-12/8647/25?u=ts678), due to the need to support sites in countries where the primary server is blocked,
however this may also help cover times when the primary server is giving an error response, e.g. the [(502) Bad Gateway](https://forum.duplicati.com/t/updates-duplicati-com-down/5199).

**Comment by kenkendk** [comment]
Yes, I consider the issue fixed, as the alternate update server is registered.
