### ISSUE TITLE
Not uploading on B2 Cloud after all files scan

### ISSUE THREAD

**Issue by loadcorp** [duplicati/duplicati#3604]
## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Fedora 28
- **Backend**: BackBlaze B2 Cloud

## Description
When I Run the added Backup I see that all files starting scan and when it says "Waiting for uploading" or something like that, I got error (logs below).

## Steps to reproduce

1. Adding B2 Cloud backup (connection in process is good).
2. Clicking on Run (and process starting).

- **Actual result**:
Got error without uploading any files.
- **Expected result**:
I am expecting that files will be uploaded.

## Debug log
DeletedFiles: 0 DeletedFolders: 0 ModifiedFiles: 0 ExaminedFiles: 61 OpenedFiles: 61 AddedFiles: 35 SizeOfModifiedFiles: 0 SizeOfAddedFiles: 20189968284 SizeOfExaminedFiles: 20189968284 SizeOfOpenedFiles: 20189968284 NotProcessedFiles: 0 AddedFolders: 0 TooLargeFiles: 0 FilesWithError: 0 ModifiedFolders: 0 ModifiedSymlinks: 0 AddedSymlinks: 0 DeletedSymlinks: 0 PartialBackup: False Dryrun: False MainOperation: Backup CompactResults: DeletedFileCount: 0 DownloadedFileCount: 0 UploadedFileCount: 0 DeletedFileSize: 0 DownloadedFileSize: 0 UploadedFileSize: 0 Dryrun: False MainOperation: Compact ParsedResult: Warning Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28) EndTime: 1/14/2019 12:25:39 PM (1547486739) BeginTime: 1/14/2019 12:25:39 PM (1547486739) Duration: 00:00:00.1827190 Messages: [ 2019-01-14 12:14:44 -05 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started, 2019-01-14 12:14:44 -05 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started: (), 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed: (), 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-RemoteUnwantedMissingFile]: removing file listed as Temporary: duplicati-20190114T170414Z.dlist.zip, 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-KeepIncompleteFile]: keeping protected incomplete remote file listed as Temporary: duplicati-20190114T171035Z.dlist.zip, ... ] Warnings: [ 2019-01-14 12:14:47 -05 - [Warning-Duplicati.Library.Main.Operation.Backup.UploadSyntheticFilelist-MissingTemporaryFilelist]: Expected there to be a temporary fileset for synthetic filelist (2, duplicati-20190114T171035Z.dlist.zip), but none was found? ] Errors: [] BackendStatistics: RemoteCalls: 8 BytesUploaded: 11092 BytesDownloaded: 0 FilesUploaded: 1 FilesDownloaded: 0 FilesDeleted: 0 FoldersCreated: 0 RetryAttempts: 6 UnknownFileSize: 0 UnknownFileCount: 0 KnownFileCount: 0 KnownFileSize: 0 LastBackupDate: 1/1/0001 12:00:00 AM (-62135578800) BackupListCount: 0 TotalQuotaSpace: 0 FreeQuotaSpace: 0 AssignedQuotaSpace: -1 ReportedQuotaError: False ReportedQuotaWarning: False ParsedResult: Warning Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28) Messages: [ 2019-01-14 12:14:44 -05 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started, 2019-01-14 12:14:44 -05 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started: (), 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed: (), 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-RemoteUnwantedMissingFile]: removing file listed as Temporary: duplicati-20190114T170414Z.dlist.zip, 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-KeepIncompleteFile]: keeping protected incomplete remote file listed as Temporary: duplicati-20190114T171035Z.dlist.zip, ... ] Warnings: [ 2019-01-14 12:14:47 -05 - [Warning-Duplicati.Library.Main.Operation.Backup.UploadSyntheticFilelist-MissingTemporaryFilelist]: Expected there to be a temporary fileset for synthetic filelist (2, duplicati-20190114T171035Z.dlist.zip), but none was found? ] Errors: [] DeleteResults: null RepairResults: null TestResults: null ParsedResult: Warning Version: 2.0.4.5 (2.0.4.5_beta_2018-11-28) EndTime: 1/14/2019 12:25:46 PM (1547486746) BeginTime: 1/14/2019 12:14:44 PM (1547486084) Duration: 00:11:02.4522580 Messages: [ 2019-01-14 12:14:44 -05 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started, 2019-01-14 12:14:44 -05 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started: (), 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed: (), 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-RemoteUnwantedMissingFile]: removing file listed as Temporary: duplicati-20190114T170414Z.dlist.zip, 2019-01-14 12:14:46 -05 - [Information-Duplicati.Library.Main.Operation.FilelistProcessor-KeepIncompleteFile]: keeping protected incomplete remote file listed as Temporary: duplicati-20190114T171035Z.dlist.zip, ... ] Warnings: [ 2019-01-14 12:14:47 -05 - [Warning-Duplicati.Library.Main.Operation.Backup.UploadSyntheticFilelist-MissingTemporaryFilelist]: Expected there to be a temporary fileset for synthetic filelist (2, duplicati-20190114T171035Z.dlist.zip), but none was found? ] Errors: []

**Comment by loadcorp** [comment]
When I changed 50 TB on the 3 Gb in the last step all starts working normal. But I don't know why this choice could cause a mistake.

**Comment by loadcorp** [comment]
http://oi64.tinypic.com/imrxps.jpg

In this step, when I am choose Remote volume size.

**Comment by Pectojin** [comment]
The remote volume size is the size of each .dblock file you upload. Changing it isn't generally advised and setting it to 50TB is a very bad idea.

Your machine will attempt to fit your entire backup into one zip file located in your temp folder before uploading it.

3GB will work provided that you have enough space in the tmp directory to hold a couple of files, depending on your async limit https://duplicati.readthedocs.io/en/latest/06-advanced-options/#asynchronous-upload-limit

I would recommend sticking with the standard 50MB size unless you're getting issue with too many volumes.

**Comment by loadcorp** [comment]
For example I am not use encryption. Is there any way do not use zip and use just original files without any modifications in transfer process?

**Comment by Pectojin** [comment]
No, Duplicati doesn't upload files. It uploades file chunks that can be reassembled to files. The is no way to turn it off.

It sounds like you're looking for a sync tool rather than a backup tool. Maybe something like [rclone](https://rclone.org/)

**Comment by warwickmm** [comment]
This sounds like a use case that Duplicati isn't designed for.  I'm going to close this issue as it appears to be due to a difference in expectations.
