### ISSUE TITLE
Backup to OneDrive stopped working with Error 410 returned from OneDrive

### ISSUE THREAD

**Issue by harald14** [duplicati/duplicati#3607]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Win10_64bit
- **Backend**: OneDrive

## Description

Since multiple days I get shortly after starting a backup with OneDrive as a target the following error:
Failed to connect: Der Remoteserver hat einen Fehler zurückgegeben: (410) Nicht vorhanden.

When I logon to Onedrive I can see all my files. I also can create a new OAuth access key.

no logs are generated to provide more detailed information

When running the backup from the commandline copied via the backup config export I get the following

```
Backup started at 15.01.2019 22:32:39
The database has version 8 but the largest supported version is 7.
This is likely caused by upgrading to a newer version and then downgrading.
If this is the case, there is likely a backup file of the previous database version in the folder C:\Users\xxxxx\AppData\Roaming\Duplicati.
```
This is very strange, as I'm 100% sure that I did not downgrade anything and it was running well with the current version.

## Steps to reproduce

Just run an existing backup, which was working fine for a long time.

or goto the config of the existing backup an do a "test connection"

**Comment by ts678** [comment]
Microsoft retired the prior OneDrive API. See [OneDrive failing : “The remote server returned an error: (410) Gone.”](https://forum.duplicati.com/t/onedrive-failing-the-remote-server-returned-an-error-410-gone/5936) for conversion steps for continued access via OneDrive v2. You do need a recent Duplicati, but your command line doesn't seem to be finding it. You could run Duplicati.CommandLine.exe system-info to see what version got picked up. Command line is separate from the server-based GUI, so can find (or not find) Duplicati updates independently. [Downgrading / reverting to a lower version](https://forum.duplicati.com/t/downgrading-reverting-to-a-lower-version/3393), though you didn't do it, lists some places where updates might have gone. Some people also just uninstall old and reinstall new. Maybe the Program Files version is old, and somehow it's not finding an update GUI got, thus disagreeing with it?

**Comment by harald14** [comment]
Thank you very much. This did resolve my problem. Backup is now working very well again. I can confirm that I had to regenerate a new authentication key to make it work with "OneDrive v2"
