### ISSUE TITLE
docker builds and github releases

### ISSUE THREAD

**Issue by aptalca** [duplicati/duplicati#3610]
Hi, I'm a member of linuxserver.io and we publish docker images for duplicati. I wanted to give you a heads up on a new development and also report a minor issue.

We recently switched over to a new build system and we now provide multi-arch docker builds for duplicati [here](https://hub.docker.com/r/linuxserver/duplicati/tags). We are also publishing the beta builds under the `latest` tag and the canary builds under `development`. We're very excited about it. This was the heads up part ;)

The minor issue is that the latest canary releases (two partial releases) kind of put our jenkins builder in a frenzy due to the latest canary tag not containing the main zip, where jenkins builds are constantly triggered but later fail due to the missing file. We disabled the builder until the next canary release.

I just wanted to kindly ask that the duplicati github releases maintain their structural consistency in terms of the published packages to ease our automation efforts. I'm sure we're not the only group who automate releases based on duplicati's github releases :)

Thanks and keep up the good work

**Comment by flip-bs** [comment]
It's also an issue on the [AUR package](https://aur.archlinux.org/packages/duplicati-latest/) the build does not fail but some features are missing like TrayIcon.exe and maybe others that i don't use.

https://aur.archlinux.org/cgit/aur.git/commit/?h=duplicati-latest&id=32c8e6bf3ee229dfccb14752ed7ceff739992a00

**Comment by warwickmm** [comment]
@kenkendk, would you happen to know why some of the releases (e.g., 2.0.4.12) are missing the zip of the compiled binaries?

**Comment by kenkendk** [comment]
There was a transfer error to github, I have manually uploaded the zip package now.

**Comment by kenkendk** [comment]
If it helps with robustness, the zip file is also uploaded to:
https://updates.duplicati.com/canary/duplicati-2.0.4.12_canary_2019-01-16.zip

The previous "release" failed as we were fiddling with the signature system, so I decided to just abort the build and start over.

**Comment by aptalca** [comment]
Will do, thanks
