### ISSUE TITLE
*.dblock.zip size mismatch

### ISSUE THREAD

**Issue by juraKol** [duplicati/duplicati#3626]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.12
- **Operating system**: Raspbian Stretch 4.14
- **Backend**: see attached system-info.txt

## Description

While running large backup (on less than 50Gig no issues), process continuously slows down and finishes with: [Warning-Duplicati.Library.Main.Operation.FilelistProcessor-MissingRemoteHash]: remote file duplicati-bc910cbb465a74cada11e07424cc4ad51.dblock.zip is listed as Verified with size 37138432 but should be 52400111, please verify the sha256 hash "EwZYachyI7eDweQD8LlA1AbcQidNoxDkh0LTVi2pXms="

## Steps to reproduce

1. Running on Raspberry-Pi model B v1 (512Meg RAM)
2. Source: networked (SMBv1.0), Target: USB-HDD, compression: ZIP, No encryption
3. Well repeatable, but only on large backups (I have 5 backups where 3 are over the critical size)

- **Actual result**:
see Description
- **Expected result**:
no warnings, no errors for backup task

## Screenshots
[system-info.txt](https://github.com/duplicati/duplicati/files/2788945/system-info.txt)

bugreport.zip is unfortunately 106175KB (over uploadable limit). File system-info.txt attached.

## Debug log

Thanks in advance for any reply!

**Comment by juraKol** [comment]
Duplicati: Duplicati.Server, Version=2.0.4.12, Culture=neutral, PublicKeyToken=null (Duplicati.Library.Main, Version=2.0.4.12, Culture=neutral, PublicKeyToken=null)
Autoupdate urls: https://updates.duplicati.com/canary/latest.manifest;https://alt.updates.duplicati.com/canary/latest.manifest
Update folder: /usr/share/Duplicati/updates
Base install folder: /usr/lib/duplicati
Version name: "2.0.4.12_canary_2019-01-16" (2.0.4.12)
Current Version folder /usr/share/Duplicati/updates/2.0.4.12
OS: Unix 4.14.79.0
Uname: Linux raspi-duplicati 4.14.79+ #1159 Sun Nov 4 17:28:08 GMT 2018 armv6l GNU/Linux
64bit: False (False)
Machinename: raspi-duplicati
Processors: 1
.Net Version: 4.0.30319.42000
Mono: True (4.6.2) (4.6.2 (Debian 4.6.2.7+dfsg-1))
Locale: en-US, en-US, en-US
Date/time strings: dddd, MMMM d, yyyy - h:mm:ss tt
Tempdir: /tmp/
SQLite: 3.16.2 - Mono.Data.Sqlite.SqliteConnection
SQLite assembly: /usr/lib/mono/gac/Mono.Data.Sqlite/4.0.0.0__0738eb9f132ed756/Mono.Data.Sqlite.dll

**Comment by warwickmm** [comment]
Related discussion in the forums [here](https://forum.duplicati.com/t/running-duplicati-on-raspberry/6185).
