### ISSUE TITLE
Cache Files filter group doesn't exclude Chrome files on Mac/Linux

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#3633]
The "Cache Files" filter group currently excludes the following pattern for Chrome cache files
```
*/Google/Chrome/*cache*
```
However, this pattern only matches for Chrome on Windows.  See the [documentation](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md#User-Cache-Directory) for the cache location on Mac OS X and Linux.

Forum discussion [here](https://forum.duplicati.com/t/cache-folders-not-being-ignored/6141).

**Comment by rohan013** [comment]
Hello,

I would like to pick up this issue.

**Comment by flafleur** [comment]
Chrome cache files should already filtered on Mac OS X by Cache filter group.  Current filter is "*/Library/Caches/" and documentation refers to "[user cache dir] ~/Library/Caches/Google/Chrome/Default".

I have added ".cache" for Linux to exclude ".cache" when Cache filter group is selected.

**Comment by warwickmm** [comment]
Thanks @flafleur.  Looking at the documentation, it seems that the cache path on Mac OS X can sometimes be the same as the profile dir `~/Library/Application Support/Google/Chrome/Default`, which is not matched by the filter?
> 1. If Library/Application Support is an ancestor of the profile dir, the user cache dir is Library/Caches plus the relative path from Application Support to the profile dir.
> 2. Otherwise, the user cache dir is the same as the profile dir.

I did forget to look at the system-specific filters.  It appears that on Linux, the [existing filters](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Utility/FilterGroups.cs#L557) are simply inadequte.

**Comment by warwickmm** [comment]
#3713 adds the `.cache` folder to the Linux excludes.  We should consider first checking the `$XDG_CACHE_HOME` environment variable.  If it is not set or empty, we can then resort to excluding `.cache`.

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
