### ISSUE TITLE
S3 compatible, "Failed to connect:"

### ISSUE THREAD

**Issue by irCecco** [duplicati/duplicati#3638]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5
- **Operating system**: Windows 10
- **Backend**: s3 compatible ---  https://www.cloud.it/object-storage/object-storage-aruba.aspx

## Description

Connection test to s3 bucket says "Failed to connect:" without further explanation. I've tryed some solutions that i found here or on the forum, for example using s3-ext-forcepathstyle option, but it led to no results.

Using an s3 browser i can connect to the bucket without any problem

i don't know how to proceed

Sorry for my bad english

## Steps to reproduce

1. add new backup
2. on page 2, i insert the following data: 
     S3 compatible
     personalized url: r1-it.storage.cloud.it  
     bucket name: xxx
     bucket area default
     archive default
     folder path empty
     id: y
     pwd: z
3. test connection

- **Actual result**:
prompt message "Failed to connect:"
- **Expected result**:
connection successful

## Debug log
```http://localhost:8200/api/v1/remoteoperation/test gave error
Amazon.S3.AmazonS3Exception ---> Amazon.Runtime.Internal.HttpErrorResponseException: Errore del server remoto: (403) Non consentito. ---> System.Net.WebException: Errore del server remoto: (403) Non consentito.

   in System.Net.HttpWebRequest.GetResponse()

   in Amazon.Runtime.Internal.HttpRequest.GetResponse()

   --- Fine della traccia dello stack dell'eccezione interna ---

   in Amazon.Runtime.Internal.HttpRequest.GetResponse()

   in Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)

   in Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)

   --- Fine della traccia dello stack dell'eccezione interna ---

   in Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)

   in Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)

   in Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)

   in Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)

   in Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request)

   in Duplicati.Library.Backend.S3Wrapper.<ListBucket>d__13.MoveNext()

   in Duplicati.Library.Backend.S3.<ListWithouExceptionCatch>d__30.MoveNext()

   in Duplicati.Library.Interface.BackendExtensions.TestList(IBackend backend)

   in Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)

   in Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)```

**Comment by flafleur** [comment]
Did you try to specify your region (perzonalized region: r1-it) and/or archive class: standard.  And what about using Use SSL option checked?

**Comment by irCecco** [comment]
I've tried it all, but it's still not working.
Other clients still connect without any problem

I've successfully connected to an FTP server instead, but in that case the backup just fails. Don't know what to do now

**Comment by flafleur** [comment]
I will try to get I free trial to test it.

**Comment by irCecco** [comment]
I can create another account to the same sarvice and send it to you, if that helps. It’s pretty easy to do from the cloud panel

**Comment by flafleur** [comment]
Yes sure, I think it will be faster.  You can send it to francois87-github@yahoo.com .

**Comment by flafleur** [comment]
Hi @irCecco , 
I found the problem and I was able to reproduce it with S3 Browser.  It seems cloud.it doesn't support signature version V4 and have a redirection.

You can bypass this problem by adding these avanced options:

s3-ext-allowautoredirect: checked
s3-ext-signatureversion: 2

With these parameters you will be able to use S3 compatible as backend.

Let me know if that fix your problem.

**Comment by irCecco** [comment]
Hello,
sorry for the late reply. I've tryed the solution suggested but it didn't work

What else i'm i doing wrong? I'm puzzled

**Comment by flafleur** [comment]
Hi, 
My guess is you added s3-ext-allowautoredirect advanced option but forget to check the checkbox.  Could you confirm?

**Comment by irCecco** [comment]
Hello
It was checked. I've also tryed all the possible combinations with the other options that you suggested but without different results

**Comment by flafleur** [comment]
Hello, 
Here are my parameters that use with the account you provided to me and working for me.  Make sure your bucket exist.

![image](https://user-images.githubusercontent.com/15882676/56426031-b39b1100-6284-11e9-9fc0-8b671f1d1caa.png)

![image](https://user-images.githubusercontent.com/15882676/56426073-d88f8400-6284-11e9-923e-1da15c005975.png)

And for this question, I answered no
![image](https://user-images.githubusercontent.com/15882676/56426188-56ec2600-6285-11e9-9dd0-914d206ce3eb.png)

Hope this will help

**Comment by irCecco** [comment]
Hello,
i was using the same config with no success; then i deleted the backup and created a new one (entering the same configuration) and now it connects successfully! Thank you
