### ISSUE TITLE
[Feature] Bidirectional sync

### ISSUE THREAD

**Issue by ajvsol** [duplicati/duplicati#3641]
I'm not aware of another tool that allows both encrypted file sync + file backup to cloud storage in the same tool so this would be a fantastic feature.

Basically it would work like a "scheduled restore" job, which would look at your local folder and sync only the differences. Conflicts could only be resolved by using the assumption of "use the file with the last modified timestamp", but I think that's a fair trade to enable file sync capabilities.

**Comment by Pectojin** [comment]
Duplicati is not a sync tool.

There is no way to update the backup data from another machine without breaking the backup. If local and backup does not match you've deleted files or lost data.

It sounds like you're trying to do something that will likely cause you trouble down the road by misusing a tool where another tool would work better.
