### ISSUE TITLE
Warning when file ends in dot

### ISSUE THREAD

**Issue by vagabundmw** [duplicati/duplicati#3642]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.2 
- **Operating system**: Windows 7 Pro (German)
- **Backend**: WebDAV

## Description

When an file ends in a dot, a warning will appear:
    
    Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-FileAccessError]: Error reported while accessing file: D:\backup-daily\server\NetzH\Test\ab\HUGO.
    
This was observed with such files at a deeper directory level. In my case D:\backup-daily is the "main" (and only) directory I'm backing up. Placing the file directly under the top-level did not raise the warning. But in the given `...\Test\ab` directory it did.

This does not / did not occur with any other files in the backup that was scheduled daily for few months now. The entire backup contains >200 GB of data in 1108474 "ExaminedFiles". My config:

    --backup-name=XXX
    --dbpath=B:\duplicati2-db\XXX.sqlite
    --encryption-module=aes
    --compression-module=zip
    --dblock-size=200MB
    --keep-time=12M
    --passphrase=MY_SECRECT_PASSPHRASE
    --blocksize=1024KB
    --disable-module=console-password-input

## Steps to reproduce

1. Place a file with dot at end of name, e.g. "HUGO.", in source directory.
2. Run backup.
3. Remove dot from file name.
4. Run backup.

- **Actual result**:
A new warning after step 2, no new warning after step 4
- **Expected result**:
No new warning after step 2

**Comment by warwickmm** [comment]
I am unable to reproduce this on Linux.  This issue may be specific to windows.

**Comment by flafleur** [comment]
I tried to reproduce on Windows 10.  I get 2 warnings on step 2(maybe Duplicati tries to acces the file 2 times before it gives up), but no warning on your step 4.  

Tested using version 2.0.4.5

**Comment by warwickmm** [comment]
Thanks @flafleur.  Are filenames that end with a dot invalid in Windows?  I wonder if that's the cause of the issue.

[This](https://stackoverflow.com/a/31976060) appears to claim that such filenames are invalid.

[This](https://ourcodeworld.com/articles/read/465/how-to-remove-folders-or-files-whose-name-ends-with-dots-in-windows) appears to claim that such files are invalid and unreadabe.

**Comment by flafleur** [comment]
Files that end with a dot are not created by Windows.  Windows doesn't recognizes these files.  I tried to open a file  with this pattern with notepad and notepad is unable to open it too.  So, files with a dot at end are just not recognized by Windows.  To create a file with a dot at end, I was unable to create it with Win 10.  I created it with a Linux tools on Windows.

**Comment by warwickmm** [comment]
Ok.  I think there's not much we can do then.  If the file is unreadable/invalid according to the OS, then we can't expect Duplicati to be able to read it.

**Comment by vagabundmw** [comment]
Thanks for your feedback. I'm OK with closing this issue. I can indeed confirm that the "dot at end of file name" handling in Windows seems to be inconsistent and not well documented (not that we can do anything about it). 

Somehow my users managed to create the file, robocopy successfully copied it to a backup, however most other Windows tools I tried (after your response) indeed fail with error messages similar to that of Duplicati. Surprisingly the Cygwin / MSYS2 tools do not choke on such files...
