### ISSUE TITLE
OEM Branding customization

### ISSUE THREAD

**Issue by harshilpk** [duplicati/duplicati#3643]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 0.0.0.0
- **Operating system**: Replace me
- **Backend**: Replace me

## Description

I am not able to save the oem.js and oem.css file for rebranding. It would be great if you guys can help me out

## Steps to reproduce

1. Replace me
2. Replace me
3. ...

- **Actual result**:
Replace me
- **Expected result**:
Replace me

## Screenshots

![duplicatiissue](https://user-images.githubusercontent.com/40614543/52153948-3377ee80-2639-11e9-97be-54ecb760944c.PNG)

**Comment by Pectojin** [comment]
It looks like the file might have been saved by an other user or the admin account. You can either update the file by opening Notepad as an administrator or you can [change the file permissions](https://www.howto-connect.com/change-file-permission-grant-ownership-windows-10/)

**Comment by harshilpk** [comment]
Thank you !!
