### ISSUE TITLE
Duplicati phones "home" to Microsoft (13.107.4.50)

### ISSUE THREAD

**Issue by ltGuillaume** [duplicati/duplicati#3657]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Windows 10 x64

## Description

At least once every day, duplicati.gui.trayicon.exe connects to a known Microsoft server (IP = 13.107.4.50). I wonder if people are aware of this, and whether it can be addressed. It looks a lot like Microsoft extended its telemetry to .NET applications as well, but I'll be the first to admit that is currently no more than speculation from my side.

## Steps to reproduce

1. Use a firewall like simplewall that blocks 13.107.4.50 / CurrPorts / Wireshark
2. Start duplicati.gui.trayicon.exe
3. Wait a few seconds
Unfortunately the connection is not attempted on every start, just the first start every day.

## Screenshots

![image](https://user-images.githubusercontent.com/4777345/52517790-f9ae7580-2c40-11e9-966d-f464bbf0f8b6.png)

**Comment by ltGuillaume** [comment]
I can see the same behavior only with Microsoft's Remote Desktop client `mstsc.exe`.

**Comment by Robespeler** [comment]
Ah windows, ah microsoft. How can we take leave of you?
said by me on microsoft github

**Comment by warwickmm** [comment]
Does this occur when using just a local backend, or even when no backups are configured?

**Comment by ltGuillaume** [comment]
I am using just a local backend. This is basically what I do from a batch file:
```
set Duplicati_Home=%~dp0Data
duplicati.gui.trayicon.exe
start http://localhost:8200
```

My current setup has 0 scheduled backups, i.e. they're all manual.

I've set up a separate portable instance without any backups. I'll run it periodically to see whether I can catch the same behavior.

**Comment by warwickmm** [comment]
Not sure if there's anything we can do here.  It would be interesting to see if this occurs on Linux/Mac as well.

**Comment by ltGuillaume** [comment]
I just saw another ping when running a _new instance_ of `duplicati.gui.trayicon.exe`, to 46.101.178.195, which is a DigitalOcean IP in Frankfurt am Main, Germany (according to an IP lookup, there's always a chance it's incorrect).

I really want to understand this. It seems it's easily reproducible by just cleaning up the profile before running it again...

**Comment by warwickmm** [comment]
Are you running from source?  We do have some test data hosted at DigitalOcean, but the tests are not deployed with the releases.  Even then, it should only establish a connection when running the tests.

https://github.com/duplicati/duplicati/blob/c0acaeee20609aa0762e2b39ae3f09d343582b1e/Duplicati/UnitTest/GeneralBlackBoxTesting.cs#L71

Alternatively, I wouldn't be surprised if there's some .NET telemetry involved

https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry

**Comment by ltGuillaume** [comment]
No I have always used the .zip releases from here. In the best case scenario, it's just an update check, but seeing what IPs turn up and considering that those IPs are always blocked by the WindowsSpyBlocker extras list (containing Microsoft services) I always wanted to rule out telemetry, otherwise perhaps something could be done about it...

**Comment by warwickmm** [comment]
Ah, that could be our autoupdater...
```
$ ping updates.duplicati.com
PING updates.duplicati.com (46.101.178.195) 56(84) bytes of data.
64 bytes from 46.101.178.195 (46.101.178.195): icmp_seq=1 ttl=48 time=213 ms
```

**Comment by ltGuillaume** [comment]
Ah that's good to know. Now if only we knew that IP could ever have been 13.107.4.50, too, say on Feb 9, 2019 at around 7:03GMT 😉 then I'd say case closed.

**Comment by warwickmm** [comment]
I'm not sure.  According to [this](https://forum.duplicati.com/t/opencollective-spending/1350/8), the update server has been hosted by Digital Ocean since 2017.

**Comment by ltGuillaume** [comment]
> 
> 
> I'm not sure. According to [this](https://forum.duplicati.com/t/opencollective-spending/1350/8), the update server has been hosted by Digital Ocean since 2017.
I can't reach that page for some reason (`page doesn’t exist or is private`), even when logged in.

**Comment by warwickmm** [comment]
Oops, sorry that was a private page.  Basically, the main website, updates site, and usage reporter are running on a Digital Ocean server.

**Comment by ltGuillaume** [comment]
OK, but I don't know if something of 2017 would explain the current connection. Also, `13.107.4.50` (the original IP this issue was opened for), states it's linked to Microsoft Azure.

**Comment by warwickmm** [comment]
The website, updates site, etc. are still on Digital Ocean.  Is `13.107.4.50` the only connection that we cannot currently explain?  Are you still seeing this connection attempt?

**Comment by warwickmm** [comment]
If I google "13.107.4.50", it sounds like it's related to Win 10 updates.

**Comment by ltGuillaume** [comment]
Correct. So why would `duplicati.gui.trayicon.exe` connect to it?

**Comment by warwickmm** [comment]
I don't know.  Perhaps the .NET Framework runtime is responsible?

**Comment by ltGuillaume** [comment]
> I don't know. Perhaps the .NET Framework runtime is responsible?

Would suck bigtime since you don't even know what's being sent...
