### ISSUE TITLE
Database recreate runs forever

### ISSUE THREAD

**Issue by roterBulle** [duplicati/duplicati#3668]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**:  2.0.4.15_canary_2019-02-06
- **Operating system**: DSM 6.2-23739
- **Backend**: SFTP Webspace

## Description

Hi All,
i currently have a recreate running with a large backup (1TB) in 2GB Blocksize.
Since the recreate hit the 70% it is running really really slow.

Database seems to be not locked ( tried to add the index as mentioned in: #2302 and it tells me that the index is already existing)
SQLite file is almost 2GB in size.

After the first recreate was running for over 10 days, i stopped it and updated from the last beta 2.0.4.5 to Duplicati - 2.0.4.15_canary_2019-02-06 but the issue remains the same.
What i can tell is that he consistently starts to get slow after he hits the 70%.
Is it possible that it is somehow related to a change of blocksize? I changed from 1GB to 2GB and then back to 250MB?

Attached we see the last execution that completed in the logs running for 14 hours.

Is there anything i can do to help you figuring out what the issue is?
Or any ideas what i coud try?

I also found @JonMikelV is investigating on that issue in the forum:
https://forum.duplicati.com/t/database-recreate-performance/5999

Maybe he can shed some light on that topic

and there seems to be a related issue: 
https://github.com/duplicati/duplicati/issues/2537

Thanks.

## Steps to reproduce

1. Run Database repair for bigger backup size

- **Actual result**:
Since the recreate hit the 70% it is running really really slow. 

- **Expected result**:
Repair should finish in a reasonable time

## Debug log

**From 0.7 to 0.7008 the following happened taking over 14 hours**
```
 SELECT
 "E"."BlocksetID",
 "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
 "F"."BlockHash",
 MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
 "E"."Hash",
 "E"."BlocklistSize",
 "E"."BlocklistHash"
 FROM
 (
 SELECT * FROM
 (
 SELECT 
 "A"."BlocksetID",
 "A"."Index" AS "BlocklistIndex",
 MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
 "A"."Hash" AS "BlocklistHash",
 "B"."Length"
 FROM 
 "BlocklistHash" A,
 "Blockset" B
 WHERE 
 "B"."ID" = "A"."BlocksetID"
 ) C,
 "Block" D
 WHERE
 "C"."BlocklistHash" = "D"."Hash"
 AND
 "C"."BlocklistSize" = "D"."Size"
 ) E,
 "TempBlocklist-67A230B430CE0840A9FD88F6ABE018DD" F
 WHERE
 "F"."BlocklistHash" = "E"."Hash"
 ORDER BY 
 "E"."BlocksetID",
 "FullIndex"
 ) UNION SELECT "BlockHash", "BlockSize" FROM "TempSmalllist-AB21E48B925B6E4085B7DBEEE0712FA8" )) A LEFT OUTER JOIN "Block" B ON "B"."Hash" = "A"."FullHash" AND "B"."Size" = "A"."Length" ) WHERE "FullHash" != "Hash" AND "Length" != "Size" took 0:14:10:11.807



16. Febr. 2019 04:39: Starting - ExecuteNonQuery: INSERT INTO "Block" ("Hash", "Size", "VolumeID") SELECT "FullHash" AS "Hash", "Length" AS "Size", -1 AS "VolumeID" FROM (SELECT "A"."FullHash", "A"."Length", CASE WHEN "B"."Hash" IS NULL THEN '' ELSE "B"."Hash" END AS "Hash", CASE WHEN "B"."Size" is NULL THEN -1 ELSE "B"."Size" END AS "Size" FROM (SELECT DISTINCT "FullHash", "Length" FROM (SELECT "BlockHash" AS "FullHash", "BlockSize" AS "Length" FROM ( 
 SELECT
 "E"."BlocksetID",
 "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
 "F"."BlockHash",
 MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
 "E"."Hash",
 "E"."BlocklistSize",
 "E"."BlocklistHash"
 FROM
 (
 SELECT * FROM
 (
 SELECT 
 "A"."BlocksetID",
 "A"."Index" AS "BlocklistIndex",
 MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
 "A"."Hash" AS "BlocklistHash",
 "B"."Length"
 FROM 
 "BlocklistHash" A,
 "Blockset" B
 WHERE 
 "B"."ID" = "A"."BlocksetID"
 ) C,
 "Block" D
 WHERE
 "C"."BlocklistHash" = "D"."Hash"
 AND
 "C"."BlocklistSize" = "D"."Size"
 ) E,
 "TempBlocklist-67A230B430CE0840A9FD88F6ABE018DD" F
 WHERE
 "F"."BlocklistHash" = "E"."Hash"
 ORDER BY 
 "E"."BlocksetID",
 "FullIndex"
 ) UNION SELECT "BlockHash", "BlockSize" FROM "TempSmalllist-AB21E48B925B6E4085B7DBEEE0712FA8" )) A LEFT OUTER JOIN "Block" B ON "B"."Hash" = "A"."FullHash" AND "B"."Size" = "A"."Length" ) WHERE "FullHash" != "Hash" AND "Length" != "Size"
```

**Currently i am at 0.7016 of Overall Progress and this is the current debug log:**
```
19. Febr. 2019 00:52: Starting - ExecuteNonQuery: INSERT INTO "BlocksetEntry" ("BlocksetID", "Index", "BlockID") SELECT DISTINCT "H"."BlocksetID", "H"."Index", "H"."BlockID" FROM (SELECT "E"."BlocksetID" AS "BlocksetID", "D"."FullIndex" AS "Index", "F"."ID" AS "BlockID" FROM ( 
 SELECT
 "E"."BlocksetID",
 "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
 "F"."BlockHash",
 MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
 "E"."Hash",
 "E"."BlocklistSize",
 "E"."BlocklistHash"
 FROM
 (
 SELECT * FROM
 (
 SELECT 
 "A"."BlocksetID",
 "A"."Index" AS "BlocklistIndex",
 MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
 "A"."Hash" AS "BlocklistHash",
 "B"."Length"
 FROM 
 "BlocklistHash" A,
 "Blockset" B
 WHERE 
 "B"."ID" = "A"."BlocksetID"
 ) C,
 "Block" D
 WHERE
 "C"."BlocklistHash" = "D"."Hash"
 AND
 "C"."BlocklistSize" = "D"."Size"
 ) E,
 "TempBlocklist-67A230B430CE0840A9FD88F6ABE018DD" F
 WHERE
 "F"."BlocklistHash" = "E"."Hash"
 ORDER BY 
 "E"."BlocksetID",
 "FullIndex"
 ) D, "BlocklistHash" E, "Block" F, "Block" G WHERE "D"."BlocksetID" = "E"."BlocksetID" AND "D"."BlocklistHash" = "E"."Hash" AND "D"."BlocklistSize" = "G"."Size" AND "D"."BlocklistHash" = "G"."Hash" AND "D"."Blockhash" = "F"."Hash" AND "D"."BlockSize" = "F"."Size" UNION SELECT "Blockset"."ID" AS "BlocksetID", 0 AS "Index", "Block"."ID" AS "BlockID" FROM "Blockset", "Block", "TempSmalllist-AB21E48B925B6E4085B7DBEEE0712FA8" S WHERE "Blockset"."Fullhash" = "S"."FileHash" AND "S"."BlockHash" = "Block"."Hash" AND "S"."BlockSize" = "Block"."Size" AND "Blockset"."Length" = "S"."BlockSize" AND "Blockset"."Length" <= 102400 ) H WHERE ("H"."BlocksetID" || ':' || "H"."Index") NOT IN (SELECT ("ExistingBlocksetEntries"."BlocksetID" || ':' || "ExistingBlocksetEntries"."Index") FROM "BlocksetEntry" "ExistingBlocksetEntries" )
19. Febr. 2019 00:52: ExecuteNonQuery: INSERT INTO "Block" ("Hash", "Size", "VolumeID") SELECT "FullHash" AS "Hash", "Length" AS "Size", -1 AS "VolumeID" FROM (SELECT "A"."FullHash", "A"."Length", CASE WHEN "B"."Hash" IS NULL THEN '' ELSE "B"."Hash" END AS "Hash", CASE WHEN "B"."Size" is NULL THEN -1 ELSE "B"."Size" END AS "Size" FROM (SELECT DISTINCT "FullHash", "Length" FROM (SELECT "BlockHash" AS "FullHash", "BlockSize" AS "Length" FROM ( 
 SELECT
 "E"."BlocksetID",
 "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
 "F"."BlockHash",
 MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
 "E"."Hash",
 "E"."BlocklistSize",
 "E"."BlocklistHash"
 FROM
 (
 SELECT * FROM
 (
 SELECT 
 "A"."BlocksetID",
 "A"."Index" AS "BlocklistIndex",
 MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
 "A"."Hash" AS "BlocklistHash",
 "B"."Length"
 FROM 
 "BlocklistHash" A,
 "Blockset" B
 WHERE 
 "B"."ID" = "A"."BlocksetID"
 ) C,
 "Block" D
 WHERE
 "C"."BlocklistHash" = "D"."Hash"
 AND
 "C"."BlocklistSize" = "D"."Size"
 ) E,
 "TempBlocklist-67A230B430CE0840A9FD88F6ABE018DD" F
 WHERE
 "F"."BlocklistHash" = "E"."Hash"
 ORDER BY 
 "E"."BlocksetID",
 "FullIndex"
 ) UNION SELECT "BlockHash", "BlockSize" FROM "TempSmalllist-AB21E48B925B6E4085B7DBEEE0712FA8" )) A LEFT OUTER JOIN "Block" B ON "B"."Hash" = "A"."FullHash" AND "B"."Size" = "A"."Length" ) WHERE "FullHash" != "Hash" AND "Length" != "Size" took 0:15:06:10.540
18. Febr. 2019 10:05: RemoteOperationGet took 0:00:36:15.034
18. Febr. 2019 10:05: Backend event: Get - Completed: duplicati-bf0da856bbf3a482289d5736afc54ae75.dblock.zip.aes (1,00 GB)
18. Febr. 2019 10:05: Downloaded and decrypted 1,00 GB in 00:36:14.8836840, 482,16 KB/s
18. Febr. 2019 09:46: Starting - ExecuteNonQuery: INSERT INTO "Block" ("Hash", "Size", "VolumeID") SELECT "FullHash" AS "Hash", "Length" AS "Size", -1 AS "VolumeID" FROM (SELECT "A"."FullHash", "A"."Length", CASE WHEN "B"."Hash" IS NULL THEN '' ELSE "B"."Hash" END AS "Hash", CASE WHEN "B"."Size" is NULL THEN -1 ELSE "B"."Size" END AS "Size" FROM (SELECT DISTINCT "FullHash", "Length" FROM (SELECT "BlockHash" AS "FullHash", "BlockSize" AS "Length" FROM ( 
 SELECT
 "E"."BlocksetID",
 "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex",
 "F"."BlockHash",
 MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize",
 "E"."Hash",
 "E"."BlocklistSize",
 "E"."BlocklistHash"
 FROM
 (
 SELECT * FROM
 (
 SELECT 
 "A"."BlocksetID",
 "A"."Index" AS "BlocklistIndex",
 MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
 "A"."Hash" AS "BlocklistHash",
 "B"."Length"
 FROM 
 "BlocklistHash" A,
 "Blockset" B
 WHERE 
 "B"."ID" = "A"."BlocksetID"
 ) C,
 "Block" D
 WHERE
 "C"."BlocklistHash" = "D"."Hash"
 AND
 "C"."BlocklistSize" = "D"."Size"
 ) E,
 "TempBlocklist-67A230B430CE0840A9FD88F6ABE018DD" F
 WHERE
 "F"."BlocklistHash" = "E"."Hash"
 ORDER BY 
 "E"."BlocksetID",
 "FullIndex"
 ) UNION SELECT "BlockHash", "BlockSize" FROM "TempSmalllist-AB21E48B925B6E4085B7DBEEE0712FA8" )) A LEFT OUTER JOIN "Block" B ON "B"."Hash" = "A"."FullHash" AND "B"."Size" = "A"."Length" ) WHERE "FullHash" != "Hash" AND "Length" != "Size"
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "nYf7au2T33xkP4bu2oyWhpnd9ZR28DUB4zlxMvjAeLg=" AND "Size" = 102400 took 0:00:00:00.011
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "nYf7au2T33xkP4bu2oyWhpnd9ZR28DUB4zlxMvjAeLg=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "39jBPhZdpznW3mRY1c5bRJmcRw8hvMttfgCdLAXpVyM=" AND "Size" = 102400 took 0:00:00:00.042
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "39jBPhZdpznW3mRY1c5bRJmcRw8hvMttfgCdLAXpVyM=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "WNIsKKO2Ci2G78ZFz3NVUhrXmiozgHwpVxATHlsKtxw=" AND "Size" = 102400 took 0:00:00:00.005
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "WNIsKKO2Ci2G78ZFz3NVUhrXmiozgHwpVxATHlsKtxw=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "zDLckQGful44lTZ34DL0ZGAW5914H2GW1eiPbJ159Qc=" AND "Size" = 102400 took 0:00:00:00.000
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "zDLckQGful44lTZ34DL0ZGAW5914H2GW1eiPbJ159Qc=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "HSKKs1yGG1IEOfK7/bBSBTSEZW4p6w2N7A+nZ3QhaY8=" AND "Size" = 102400 took 0:00:00:00.000
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "HSKKs1yGG1IEOfK7/bBSBTSEZW4p6w2N7A+nZ3QhaY8=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "bHJVFj4LSeJ1xG3hcjkDoc8+SkGGdp52HaiCyWEjS3M=" AND "Size" = 102400 took 0:00:00:00.017
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "bHJVFj4LSeJ1xG3hcjkDoc8+SkGGdp52HaiCyWEjS3M=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "Kvec6UfNWzdkCAqzaJ0GmSpv2YER12p8lZ1IE84w8hg=" AND "Size" = 102400 took 0:00:00:00.008
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "Kvec6UfNWzdkCAqzaJ0GmSpv2YER12p8lZ1IE84w8hg=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "uZNyltKZRDFcxxB+l4P267tEwi12OomJ+2Syi2hZptU=" AND "Size" = 102400 took 0:00:00:00.000
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "uZNyltKZRDFcxxB+l4P267tEwi12OomJ+2Syi2hZptU=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "RK62KHixn57RHCo2I08sFJE6ODHiC61WKA6T1xOXeyA=" AND "Size" = 102400 took 0:00:00:00.030
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "RK62KHixn57RHCo2I08sFJE6ODHiC61WKA6T1xOXeyA=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "4Gq4+TVF6lMni1xhXCVAcLy5MimOXjJ9pMZzzphWAWU=" AND "Size" = 102400 took 0:00:00:00.010
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "4Gq4+TVF6lMni1xhXCVAcLy5MimOXjJ9pMZzzphWAWU=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "YoqcuEPRpnOn6J+0PifZTeSkh/ZcqvWTMwSo1Mway40=" AND "Size" = 102400 took 0:00:00:00.017
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "YoqcuEPRpnOn6J+0PifZTeSkh/ZcqvWTMwSo1Mway40=" AND "Size" = 102400
18. Febr. 2019 09:33: ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "0y7Q3rbI7UDwW9U74JgfdRd+uq+tFmJcvabQGkwMDSo=" AND "Size" = 102400 took 0:00:00:00.020
18. Febr. 2019 09:33: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "0y7Q3rbI7UDwW9U74JgfdRd+uq+tFmJcvabQGkwMDSo=" AND "Size" = 102400
```

**Comment by roterBulle** [comment]
I tried to investigate further on that issue. 
Here is what i found out until now: 
First of all i copied the setup to a more powerful machine with windows and run the recreate. It also gets slow exactly at 70%.
Then i tried to execute the SQL Statement itself directly. 
The following statement finishes in a reasonable time
```
SELECT
 "E"."BlocksetID",
 "E"."Hash",
 "E"."BlocklistSize",
 "E"."BlocklistHash"
 FROM
 (
 SELECT * FROM
 (
 SELECT 
 "A"."BlocksetID",
 "A"."Index" AS "BlocklistIndex",
 MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize",
 "A"."Hash" AS "BlocklistHash",
 "B"."Length"
 FROM 
 "BlocklistHash" A,
 "Blockset" B
 WHERE 
 "B"."ID" = "A"."BlocksetID"
 ) C,
 "Block" D
 WHERE
 "C"."BlocklistHash" = "D"."Hash"
 AND
 "C"."BlocklistSize" = "D"."Size"
 ) E
```
After that there is this tempsmalllist and so on where i now need to figure out how this temp tables are created and whats the content of it.
Might these temp tables be the issue?
When I started on the more powerfull machine i saw that when it hits the 70% the disk io and the CPU is under heavy load and then the load drops and nothing happens anymore.

Can anyone give me hint how to quickly create the temp tables?

Thanks.

**Comment by torbennehmer** [comment]
I can confirm the behavoir with a OneDrive backend, recreation time of the DB rises exponentially, essentially crippling the backup. As this is a 500 GB Backup, recreating the offsitebackup is time consuming as well, event with a big pipe to the net.

I'm running Duplicati - 2.0.4.15_canary_2019-02-06 on ArchLinux.

Apart from the queries mentioned above, I can see two major entries in the profiling log in the website the one mentioned above takes an average of 3 Minutes(!) while the second one doesn't even log a completion time (so this is fishy):

Mar 8, 2019 8:01 AM: ExecuteNonQuery: INSERT INTO "Block" ("Hash", "Size", "VolumeID") SELECT "FullHash" AS "Hash", "Length" AS "Size", -1 AS "VolumeID" FROM (SELECT "A"."FullHash", "A"."Length", CASE WHEN "B"."Hash" IS NULL THEN '' ELSE "B"."Hash" END AS "Hash", CASE WHEN "B"."Size" is NULL THEN -1 ELSE "B"."Size" END AS "Size" FROM (SELECT DISTINCT "FullHash", "Length" FROM (SELECT "BlockHash" AS "FullHash", "BlockSize" AS "Length" FROM ( SELECT "E"."BlocksetID", "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex", "F"."BlockHash", MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize", "E"."Hash", "E"."BlocklistSize", "E"."BlocklistHash" FROM ( SELECT * FROM ( SELECT "A"."BlocksetID", "A"."Index" AS "BlocklistIndex", MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize", "A"."Hash" AS "BlocklistHash", "B"."Length" FROM "BlocklistHash" A, "Blockset" B WHERE "B"."ID" = "A"."BlocksetID" ) C, "Block" D WHERE "C"."BlocklistHash" = "D"."Hash" AND "C"."BlocklistSize" = "D"."Size" ) E, "TempBlocklist-32EFA57310927A4B9D0A833E57F11338" F WHERE "F"."BlocklistHash" = "E"."Hash" ORDER BY "E"."BlocksetID", "FullIndex" ) UNION SELECT "BlockHash", "BlockSize" FROM "TempSmalllist-AAC2CA1A79968F43B3722B061A0233D8" )) A LEFT OUTER JOIN "Block" B ON "B"."Hash" = "A"."FullHash" AND "B"."Size" = "A"."Length" ) WHERE "FullHash" != "Hash" AND "Length" != "Size" took 0:00:03:08.758

The next query has only a start-entry:


Mar 8, 2019 8:01 AM: Starting - ExecuteNonQuery: INSERT INTO "BlocksetEntry" ("BlocksetID", "Index", "BlockID") SELECT DISTINCT "H"."BlocksetID", "H"."Index", "H"."BlockID" FROM (SELECT "E"."BlocksetID" AS "BlocksetID", "D"."FullIndex" AS "Index", "F"."ID" AS "BlockID" FROM ( SELECT "E"."BlocksetID", "F"."Index" + ("E"."BlocklistIndex" * 3200) AS "FullIndex", "F"."BlockHash", MIN(102400, "E"."Length" - (("F"."Index" + ("E"."BlocklistIndex" * 3200)) * 102400)) AS "BlockSize", "E"."Hash", "E"."BlocklistSize", "E"."BlocklistHash" FROM ( SELECT * FROM ( SELECT "A"."BlocksetID", "A"."Index" AS "BlocklistIndex", MIN(3200 * 32, ((("B"."Length" + 102400 - 1) / 102400) - ("A"."Index" * (3200))) * 32) AS "BlocklistSize", "A"."Hash" AS "BlocklistHash", "B"."Length" FROM "BlocklistHash" A, "Blockset" B WHERE "B"."ID" = "A"."BlocksetID" ) C, "Block" D WHERE "C"."BlocklistHash" = "D"."Hash" AND "C"."BlocklistSize" = "D"."Size" ) E, "TempBlocklist-32EFA57310927A4B9D0A833E57F11338" F WHERE "F"."BlocklistHash" = "E"."Hash" ORDER BY "E"."BlocksetID", "FullIndex" ) D, "BlocklistHash" E, "Block" F, "Block" G WHERE "D"."BlocksetID" = "E"."BlocksetID" AND "D"."BlocklistHash" = "E"."Hash" AND "D"."BlocklistSize" = "G"."Size" AND "D"."BlocklistHash" = "G"."Hash" AND "D"."Blockhash" = "F"."Hash" AND "D"."BlockSize" = "F"."Size" UNION SELECT "Blockset"."ID" AS "BlocksetID", 0 AS "Index", "Block"."ID" AS "BlockID" FROM "Blockset", "Block", "TempSmalllist-AAC2CA1A79968F43B3722B061A0233D8" S WHERE "Blockset"."Fullhash" = "S"."FileHash" AND "S"."BlockHash" = "Block"."Hash" AND "S"."BlockSize" = "Block"."Size" AND "Blockset"."Length" = "S"."BlockSize" AND "Blockset"."Length" <= 102400 ) H WHERE ("H"."BlocksetID" || ':' || "H"."Index") NOT IN (SELECT ("ExistingBlocksetEntries"."BlocksetID" || ':' || "ExistingBlocksetEntries"."Index") FROM "BlocksetEntry" "ExistingBlocksetEntries" ) 

The next thing I see in the logs is this:

Mar 8, 2019 8:16 AM: Starting - ExecuteScalarInt64: SELECT "VolumeID" FROM "Block" WHERE "Hash" = "Zn6dZUQu7qdtXO1cU0DIM9HKzjBbZ3It9QgFL5uSvvM=" AND "Size" = 102400

Given the timestamps, I'd expect this query to take approx. 15 Minutes right now. 

Is it possible, that there is any DB degradation in action here? 

In any way: I find this a quite critical issue, as you can't wait for a few weeks for duplicati to recreate its database in case of a disaster... Is there any way to just download the DB from the backup set? Or the db not part of the backup?

Also, please let me know if you need additional debugging information, I'm a savy C# programmer, so I might be able to get you additional info if you let me know where to look.

Best regards
Torben Nehmer

**Comment by mlpcoder** [comment]
This is a major problem.  I see it on about half of my current backups, over two different computers.  They've been running recreations now for more than a week.  This is the third time I've had to start the process over because Windows updates forces a restart, which causes the process to stop.  The affected backups are not working.  This should not be labeled as a "performance" issue.  It is a major, "the program does not work as intended" issue.  I'm really appreciative of this project, but at the end of the day it is not a functional program for me right now.

**Comment by roterBulle** [comment]
After some analysis i think what could solve also this issue is running an ANALYZE command on that Database. I think it is related also to the long running Verifying backend data.
https://forum.duplicati.com/t/verifying-backend-data/348/65

For me atleast these solved the problems. I still have the not fixed original databases available, if we would need them for analysis.

Thanks

**Comment by roterBulle** [comment]
For now i would close this issue i think with fix #3745 this error should also be handled.
Hopefully i will never again run into that issue ;)

**Comment by PrototypeNM1** [comment]
@roterBulle Sorry if this is documented elsewhere but I'm having a hard time finding which database this should be run against, e.g. in AppData/Local/Duplicati or elsewhere.

I assume it's not the large database in the local folder since that's deleted when you recreate the database, could you clarify?

**Comment by roterBulle** [comment]
sure it is the database which is recreated. 
To be more precise Click on Advanced-->Database of the backup job:
![image](https://user-images.githubusercontent.com/7093321/56837937-936ae380-687c-11e9-8677-2ab775db5142.png)

And then the database from "local database path:
![image](https://user-images.githubusercontent.com/7093321/56838059-04120000-687d-11e9-8613-a9b9e29eee8e.png)

@PrototypeNM1 but i think this the database you were talking about. Did you try running the command (ANALYZE) on the database already?
But for documentation purposes i created the screenshots and manual.

**Comment by PrototypeNM1** [comment]
Yeah, that's the one I was looking at. I'm guessing then that you meant this is something you do after successfully recreating the database so that it doesn't take so long in the future?

In my case I'll get to 90% in a couple hours, but the remainder takes longer to finish than the monthly Windows update cycle so it never finishes.

**Comment by roterBulle** [comment]
If you get to the 90% pause the recreation and try to run analyze on the DB...
