### ISSUE TITLE
accept-specified-ssl-hash Wrong description? SHA256 SHA1

### ISSUE THREAD

**Issue by jonathanmmm** [duplicati/duplicati#3675]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Debian 9 through Openmediavault 4
- **Backend**: WDMyCloud

## Description

In the manual (https://duplicati.readthedocs.io/en/latest/06-advanced-options/#accept-specified-ssl-hash) and also in the webinterface it says:
If your server certificate is reported as invalid (eg. with self-signed certificates), you can supply the certificate hash (**SHA256**) to approve it anyway. The hash value must be entered in hex format without spaces or colons. You can enter multiple hashes separated by commas.

I got the hash by logging in via FileZilla and pressing seeing the certificate verification (or in the lower right corner you have the lock symbol).
There I extracted (by hand) the SHA256 key but this didnt work.
I tried also the Serialnumber but that did not work either.

But the SHA1 Fingerprint worked.
Is this intended or does FileZilla shows them wrongly?
The SHA1 is much shorter than the SHA256 displayed in FileZilla.

## Steps to reproduce

Use FileZilla to extract SHA256 Fingerprint
Enable SSL in FTP mode and click on Connection check (dont know the english wording)

- **Actual result**:
Error: Failed to connect: The authentication or decryption has failed.
- **Expected result**:
Connection Sucessfull

AND as a question:

Below FTP there is:
USE SSL and I can check that.
But in the advanced options:
use-ssl that I can check again.
Why can I do that twice and should I check it only once or twice?

**Comment by flafleur** [comment]
I did a test and I have same issue.  I checked the code and it compares hash string to SHA1 Fingerprint and not to SHA256.  So, we have two way to fix that issue, first, we change information mentionned in advanced option to SHA1 instead of SHA256.  Second option, we calculate the string with SHA256.

**Comment by Pectojin** [comment]
It's best to change the UI so we don't break any existing configurations for users updating to a new version.

I don't see any reason we couldn't use SHA1 either so it's an easier and safer change.

**Comment by warwickmm** [comment]
This was fixed in pull request #3717.
