### ISSUE TITLE
suggestion for improvement duplicati-monitoring 

### ISSUE THREAD

**Issue by Ivan4848** [duplicati/duplicati#3680]
Hello, in Duplicati-monitoring
Can You make the "Overview groups" for "Group (optional)" ?

"Ungrouped" / "Group Name1" / "Group Name2" / "Group Name3" etc.
or
"Group Name1" / "Group Name2" / "Group Name3" etc.

or add in Overview

Menu:
    Overview
    Overview Group
    Backup Sets
    Backup Reports

or

Menu:
    Overview / Overview Group
    Backup Sets
    Backup Reports

Thanks

**Comment by Pectojin** [comment]
Duplicati monitoring is a 3rd party tool developed without the infleence of the duplicati team. 

Any requests for changes on that software is probably better directed to their contact email found on their website https://www.duplicati-monitoring.com/
