### ISSUE TITLE
Displayed backup size different from backup size in destination.

### ISSUE THREAD

**Issue by jdesnos** [duplicati/duplicati#3682]
Hello,

I'm having some issue with the backup size displayed in duplicati web interface. The destination backup size in duplicati is different from the backup size displayed on destination (here Backblaze).

For example the following backup job shows 165.80GB in destination:
![image](https://user-images.githubusercontent.com/29238040/53840713-1cf7e680-3f9b-11e9-990d-8d52c6e101f9.png)

But on Backblaze i see 178.0GB:
![image](https://user-images.githubusercontent.com/29238040/53840907-b2937600-3f9b-11e9-8658-79f43a3e15c7.png)

However in the backup job log it shows 178GB:
![image](https://user-images.githubusercontent.com/29238040/53840979-dc4c9d00-3f9b-11e9-863e-24cb2e746dd2.png)

So, is it just a display bug ?

Regards.

**Comment by Pectojin** [comment]
One is displaying Gigabytes, the other is displaying Gibibytes.

165.8GiB is equal to 178GB.

Looks like the ui might need to be revised to show the proper unit description.

**Comment by jdesnos** [comment]
Hello,

Thanks for your quick answer, i close the issue.

Regards.
