### ISSUE TITLE
Failed to apply metadata to file, message: Invalid parameter on NFS mounted value, Files NOT restored

### ISSUE THREAD

**Issue by MTJoker** [duplicati/duplicati#3698]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5
- **Operating system**: Raspbian Stretch
- **Backend**: QNAP Turbo NAS

## Description

Duplicate runs on Raspberry Pi, and has the volumes that it shall backup mounted via NFS. The volumes are physically on a QNAP Turbo NAS. Backup works fine, but files can not be restored to the original location (note: For reproducing, I used the option "Save different versions with timestamp in file name", as the original file still existed. But also deleting the original file and restoring without this option delivers the same result).

## Steps to reproduce

1. On the Raspberry which runs Duplicati, mount a folder from the QNAP NAS via fstab, e.g.
`192.168.1.47:/Backup      /home/pi/Backup       nfs defaults 0 0`
Folder permission on QNAP NAS is set to unrestricted access from the Raspberry IP.
2. Execute Backup job for the folder
3. Try to restore a file from the backup to the original location

- **Actual result**:
The file is NOT restored at all, Log states:
`FilesRestored: 0`
There is a warning "Invalid parameter" when applying metadata to the file.

Note that this is only a warning and the job completes successful, although the file was not restored at all.
The behavior seems strange to me, as the file shall be restored to the original location, so there should not be issues with different features supported by the original and the restored location.
- **Expected result**:
File is restored successfully

## Debug log

```
Mar 23, 2019 8:22 PM: The operation Restore has completed
Mar 23, 2019 8:22 PM: Failed to apply metadata to file: "/home/pi/Backup/fhempi/fhem/192.168.1.42/database/fhem_dblog_2016.zip", message: Invalid parameter
Mar 23, 2019 8:22 PM: Patching metadata with remote data: /home/pi/Backup/fhempi/fhem/192.168.1.42/database/fhem_dblog_2016.zip
Mar 23, 2019 8:22 PM: Recording metadata from remote data: /home/pi/Backup/fhempi/fhem/192.168.1.42/database/fhem_dblog_2016.zip
Mar 23, 2019 8:22 PM: Backend event: Get - Completed: duplicati-bb711bad6b1744e18b705e68d3efd2454.dblock.zip.aes (49,92 MB)
Mar 23, 2019 8:21 PM: Backend event: Get - Started: duplicati-bb711bad6b1744e18b705e68d3efd2454.dblock.zip.aes (49,92 MB)
Mar 23, 2019 8:21 PM: 1 remote files are required to restore
Mar 23, 2019 8:21 PM: Target file exists and is correct version: /home/pi/Backup/fhempi/fhem/192.168.1.42/database/fhem_dblog_2016.zip
Mar 23, 2019 8:20 PM: Restore list contains 64 blocks with a total size of 6,07 MB
Mar 23, 2019 8:20 PM: Needs to restore 1 files (6,07 MB)
Mar 23, 2019 8:20 PM: Searching backup 0 (16.03.2019 07:12:20) ...
Mar 23, 2019 8:20 PM: Backend event: List - Completed: (7 bytes)
Mar 23, 2019 8:20 PM: Backend event: List - Started: ()
Mar 23, 2019 8:20 PM: The operation Restore has started
Mar 23, 2019 4:06 AM: The operation Backup has completed
```

**Comment by jaypi95** [comment]
Has there been any progress on this? Because this is still happening.

**Comment by ts678** [comment]
> The file is NOT restored at all, Log states:
FilesRestored: 0

It tests to see whether the file is fine already. This avoids effort of needless restore. Was this file fine except for metadata?

> Mar 23, 2019 8:21 PM: Target file exists and is correct version: /home/pi/Backup/fhempi/fhem/192.168.1.42/database/fhem_dblog_2016.zip

I don't know what metadata issue was, and I don't know if NFS is relevant. What does a restore to empty local folder do?
Being empty should force an actual restore (although it will try to obtain blocks locally), and you'll see if its metadata fails.

> Because this is still happening.

If there's a problem in some old backup data, it might persist. Best experimental test is reproducible one on fresh backup.
