### ISSUE TITLE
Enhancement suggestion for custom command before and after backup

### ISSUE THREAD

**Issue by mnheia** [duplicati/duplicati#3702]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.5
- **Operating system**: Windows 7
- **Backend**: WebDav

## Description
Custom command before and after backup is not only run on backup job but also when doing other operations like database repair. I expected this to work in a way custom script before (--run-script-before) and after (--run-script-after) backup should only run before or after actual backup.

## Steps to reproduce
1. Install Duplicati 2.0.4.5
2. Setup Backup Job and add a script before (--run-script-before) and after (--run-script-after) backup 
3. Run Backup
4. Run Database Repair

- **Actual result**:
Custom script before (--run-script-before) and after (--run-script-after) backup is run even when doing database repair or other non-backup operations.
- **Expected result**:
Custom script before (--run-script-before) and after (--run-script-after) backup should only run before or after actual backup or another option in this way should be implemented.

**Comment by ts678** [comment]
[Include/Exclude filters not available to run-script #2440](https://github.com/duplicati/duplicati/issues/2440#issuecomment-306741795)
> The intention is that the same script is run regardless of the operation, and you can use the name of the operation to choose what to do.

There are quite a few environment variables set up. Let %DUPLICATI__OPERATIONNAME% guide the script.

https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.bat

https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.sh

**Comment by mnheia** [comment]
> [Include/Exclude filters not available to run-script #2440](https://github.com/duplicati/duplicati/issues/2440#issuecomment-306741795)
> 
> > The intention is that the same script is run regardless of the operation, and you can use the name of the operation to choose what to do.
> 
> There are quite a few environment variables set up. Let %DUPLICATI__OPERATIONNAME% guide the script.
> 
> https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.bat
> 
> https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.sh

Thank you. This issue is therefore closed as proper enhancement is already done.
