### ISSUE TITLE
Please help me choose a version of duplicati

### ISSUE THREAD

**Issue by rdbox** [duplicati/duplicati#3705]
I have now version 2.0.3.3_beta_2018-04-02
but it seems to me that she is very old.
But at the same time, duplicati itself does not ask for updates.

What is the current working beta version?

**Comment by sfahrenholz** [comment]
Hey,

the current beta-version is 2.0.4.5 (https://www.duplicati.com/download).
When you search after new updates/version, what the logs say? Any Error?

**Comment by rdbox** [comment]
@sfahrenholz 
 here is the update error

```Apr 1 2019, 11:42: Could not load assembly C: \ ProgramData \ Duplicati \ updates \ 2.0.4.5 \ Microsoft.WindowsAzure.Storage.dll, error message: Could not load file or assembly "Microsoft.Data.Services. Client, Version = 5.8.1.0, Culture = neutral, PublicKeyToken = 31bf3856ad364e35 "or one of their dependencies. The found assembly manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)```

**Comment by BrianLakstins** [comment]
Restarting the service was not stopping Duplicati.Server.exe.  Perhaps killing it and then restarting the service would have fixed the problem.

I upgraded to latest release version and my backups are working now.
