### ISSUE TITLE
error trying to make -  "rebuild-missing-dblock-files"

### ISSUE THREAD

**Issue by rdbox** [duplicati/duplicati#3724]
I want to repair files using the command
--rebuild-missing-block-files = true
but I have a mistake
```
Backup started at 08.04.2019 17:27:07
Fatal error => Unexpected difference in fileset version 38: 02.04.2019 15:01:09 (database id: 1), found 5135 entries, but expected 6134

ErrorID: FilesetDifferences
Unexpected difference in fileset version 38: 02.04.2019 15:01:09 (database id: 1), found 5135 entries, but expected 6134
Return code: 100
```
**Version:  Duplicati - 2.0.4.5_beta_2018-11-28**

**Log journal:**
```
Duplicati.Library.Interface.UserInformationException: Unexpected difference in fileset version 38: 04/02/2019 15:01:09 (database id: 1), found 5135 entries, but expected 6134
   in Duplicati.Library.Main.Database.LocalDatabase.VerifyConsistency (Int64 blocksize, Int64 hashsize, Boolean verifyfilelists, IDbTransaction transaction)
   in Duplicati.Library.Main.Operation.Backup.BackupDatabase. <> c__DisplayClass32_0. <VerifyConsistencyAsync> b__0 ()
   in Duplicati.Library.Main.Operation.Common.SingleRunner. <> c__DisplayClass3_0. <RunOnMain> b__0 ()
   in Duplicati.Library.Main.Operation.Common.SingleRunner. <DoRunOnMain> d__2`1.MoveNext ()
--- End of stack trace from previous location where exception occurred ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
   in Duplicati.Library.Main.Operation.BackupHandler. <RunAsync> d__19.MoveNext ()
--- End of stack trace from previous location where exception occurred ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
   in CoCoL.ChannelExtensions.WaitForTaskOrThrow (Task task)
   in Duplicati.Library.Main.Controller. <> c__DisplayClass13_0. <Backup> b__0 (BackupResults result)
   in Duplicati.Library.Main.Controller.RunAction [T] (T result, String [] & paths, IFilter & filter, Action`1 method)
   in Duplicati.Library.Main.Controller.Backup (String [] inputsources, IFilter filter)
   in Duplicati.Server.Runner.Run (IRunnerData data, Boolean fromQueue)
```

what to do?
I have 35 versions of important data backup
How to restore them?

**Comment by ts678** [comment]
> How to restore them?

[Duplicati.CommandLine.RecoveryTool.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlinerecoverytoolexe)

> This tool can be used in very specific situations, where you have to restore data from a corrupted backup. The procedure for recovering from this scenario is covered in [Disaster Recovery](https://duplicati.readthedocs.io/en/latest/08-disaster-recovery).

although it's really for emergency uses -- it's not user friendly enough to be using in place of a nice regular Duplicati routine...

> I want to repair files using the command
--rebuild-missing-block-files = true

[2.0.3.10_canary_2018-08-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.10-2.0.3.10_canary_2018-08-30)

> Removed automatic attempts to rebuild dblock files as it is slow and rarely finds all the missing pieces (can be enabled with --rebuild-missing-dblock-files).

What it doesn't say well is that it's an option on `repair`, but original post looks like you were using it on a backup command.

["Unexpected difference in fileset" test case and code clue #3800](https://github.com/duplicati/duplicati/issues/3800) in June 2019 led to a fix later June 2019. Does this still break?

**Comment by f1h0** [comment]
> > How to restore them?
> 
> [Duplicati.CommandLine.RecoveryTool.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlinerecoverytoolexe)
> 
> > This tool can be used in very specific situations, where you have to restore data from a corrupted backup. The procedure for recovering from this scenario is covered in [Disaster Recovery](https://duplicati.readthedocs.io/en/latest/08-disaster-recovery).
> 
> although it's really for emergency uses -- it's not user friendly enough to be using in place of a nice regular Duplicati routine...
> 
> > I want to repair files using the command
> > --rebuild-missing-block-files = true
> 
> [2.0.3.10_canary_2018-08-30](https://github.com/duplicati/duplicati/releases/tag/v2.0.3.10-2.0.3.10_canary_2018-08-30)
> 
> > Removed automatic attempts to rebuild dblock files as it is slow and rarely finds all the missing pieces (can be enabled with --rebuild-missing-dblock-files).
> 
> What it doesn't say well is that it's an option on `repair`, but original post looks like you were using it on a backup command.
> 
> ["Unexpected difference in fileset" test case and code clue #3800](https://github.com/duplicati/duplicati/issues/3800) in June 2019 led to a fix later June 2019. Does this still break?

Hey, I haven't checked yet. I think we can close this question, it's been a long time. The versions are constantly being updated, so in such situations, you just need to merge these branches as one issue if necessary. Thank you for your response.
