### ISSUE TITLE
UI (dark theme): file name very hard to read when importing configurations

### ISSUE THREAD

**Issue by KommX** [duplicati/duplicati#3726]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.16
- **Operating system**: Windows 10
- **Backend**: doesn't matter

## Description

I can't read the file name in the "Import backup configuration" section because it's dark on dark.

## Steps to reproduce

1. Activate the dark theme.
2. Choose "Add backup".
3. Choose "Import from file".
4. Click on the "Choose File" button
5. Select a file and click Open.

- **Actual result**:
The file name is located next to the "Choose File" button but it's very hard to read.
- **Expected result**:
I can read it, because a brighter color is used for the file name.

## Screenshots

![image](https://user-images.githubusercontent.com/7859245/55752505-81014500-5a48-11e9-96fa-238c4b11e9fc.png)

**Comment by kees-z** [comment]
It looks like this in Chrome and Firefox. Internet Explorer and Edge have a different view:

![image](https://user-images.githubusercontent.com/24669568/56353988-fef4e700-61d2-11e9-85de-bfadee00eca8.png)

**Comment by mithileshz** [comment]
Hey, can I pick this up?

**Comment by warwickmm** [comment]
Of course.  Thanks @mithileshz.
