### ISSUE TITLE
No progress in "Verifying Backend Data"

### ISSUE THREAD

**Issue by KommX** [duplicati/duplicati#3734]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.17
- **Operating system**: Windows 10
- **Backend**: external USB drive

## Description

This _might_ be related to #3205, maybe it's even a duplicate. But I didn't see any solution approaches there and I'm not sure if old tickets get the attention after this long time.
Don't be mad at me if this issue here is superfluous.

One of my backups seems to be "broken". All others are working as expected.
I have succeeded to create a full backup in the past. Now I want to run the backup again, but this backup shows no progress after "Verifying Backend Data" - even if I wait a full day. Usually this backup takes 20-30 minutes. The initial one took longer but the source data doesn't change too much.
The source is my NAS, destination is a local USB drive.
I first noticed this problem with 2.0.4.16 but I still have it in 2.0.4.17.
A downgrade to 2.0.4.15 and 2.0.4.14 didn't resolve the issue.

I guess a downgrade to 2.0.4.5 beta doesn't work because of different DB versions.
So, now I don't know how to repair my backup.

## Steps to reproduce

1. I just want to run the backup.

- **Actual result**:
It seems to be stuck in an infinite loop or other CPU-intensive task (one CPU core is at 100%) but there is no sign of disk or network activity.
- **Expected result**:
The backup finishes after 1 hour max or at least I should see some progress.

## Debug log

The last entries of the verbose live log are these:
```
Apr 12, 2019 7:43 PM: Re-creating missing index file for duplicati-bddefbd2ed7af45b1ba7d905486575691.dblock.zip.aes
Apr 12, 2019 7:43 PM: Backend event: List - Completed: (9.93 KB)
Apr 12, 2019 7:43 PM: Backend event: List - Started: ()
Apr 12, 2019 7:43 PM: Including path as no filters matched: \\NAS\Path\to\file2
Apr 12, 2019 7:43 PM: Including path as no filters matched: \\NAS\Path\to\file1
```

**Comment by KommX** [comment]
I have created a bounty of 50 $ for this issue over at bountysource:
https://www.bountysource.com/issues/72799071-no-progress-in-verifying-backend-data

**Comment by Roadrunneruk** [comment]
Hi
I had the same thing with verifying backend data and after 5 days i had
enough, but after release 17, the backup that i had created with the
previous version 16 would still be stuck verifying data, but all new
backups of different drives would have no problem.
So I delete my original 3 tb backup and deleted database as well I started
a new backup, after a day backing it now all seem fine and the verifying
backend data has gone, so i think if you have made any backup you should
delete and make now ones, hope this helps .

Andy

**Comment by KommX** [comment]
@Roadrunneruk 
Thanks for the hint!
I did this when I was on 2.0.4.16 but didn't repeat it on 2.0.4.17 yet.
Because it's a large backup which took 13 hours, I will first try to delete and repair the local database.

If this doesn't improve the situation I will try your approach with deleting the local database **and** the backup.

I will report back once my tests have finished.

**Comment by KommX** [comment]
Ok, database repair is running since 22 hours, so longer than the whole backup.
I will

- cancel the repair
- delete the local database
- delete the backup
- and then recreate the backup from scratch.

Let's see if this will solve my issues.

**Comment by Roadrunneruk** [comment]
Let my know if that works.

Andy

**Comment by KommX** [comment]
I'm off for two or three days.
Bear with me.

**Comment by KommX** [comment]
I'm back.
Rebuilding the backup from scratch really did the trick for me with 2.0.4.17 (it didn't with 2.0.4.16).

Thanks @Roadrunneruk for the hint!

**Comment by Roadrunneruk** [comment]
Hope the tip saved you £50 and have a Happy Easter.

Andy

**Comment by KommX** [comment]
I already prepaid the bounty. I will try to channel the money to duplicati's maintainers.

**Comment by KommX** [comment]
The 50 $ bounty now got transferred to the duplicati bountysource account. I hope that's in everbody's interest.
