### ISSUE TITLE
Invalid regex pattern used to decode URLs

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#3737]
The regex pattern used [here](https://github.com/duplicati/duplicati/blob/d071d1b4da0b5dc176de7d61900e7ee9f9153633/Duplicati/Library/Utility/Uri.cs#L394) in the `Uri` class appears to be invalid.

![Screenshot from 2019-04-14 19-51-05](https://user-images.githubusercontent.com/17345532/56104921-ada4d900-5eee-11e9-92a8-094828a30f4c.png)

Also reported by @nathanejohnson [here](https://github.com/duplicati/duplicati/issues/1063#issuecomment-476342559).

**Comment by tygill** [comment]
Would a regex like (?<number>((...){2}){1,4}) work?

**Comment by nathanejohnson** [comment]
@tygill that would be make it valid regex, but I suspect {4} would be more appropriate.  That's what it was before it was changed, and according to wikipedia

https://en.wikipedia.org/wiki/Percent-encoding#Non-standard_implementations

this nonstandard encoding is always UTF-16, so 4 bytes.  I'm not sure how accurate that is in practice.

@kenkendk any thoughts?

**Comment by kenkendk** [comment]
@nathanejohnson I worry a bit that we will have a regression, since it is browser dependent. But since the regex matches nothing currently, I guess we should follow the wiki-info and hope it is correct.

**Comment by warwickmm** [comment]
Fixed in pull request #3926.
