### ISSUE TITLE
Error when working on backup: Failed to parse the segment; invalid integer

### ISSUE THREAD

**Issue by pomeloy** [duplicati/duplicati#3771]
## Environment info

- **Duplicati version**: 2.0.4.5
- **Operating system**: Windows 10 x64 1809
- **Backend**: local

## Description

Duplicati refuses to work with one particular backup. Backup, restore and database repairs all produce the same error message: 

    Error while running [backup]
    Failed to parse the segment: ;3, invalid integer

## Steps to reproduce

1. Run an encrypted Duplicati 2.0.4.5 backup with a local drive as the destination and default settings.
2. Try to restore it after some time.

- **Actual result**:
Restore data
- **Expected result**:
Error message as described

## Debug log

No log entries dealing with this particular problem.

**Comment by Pectojin** [comment]
It looks like your config might contain a value that cannot be parsed as an integer but duplicati still tries to.

Could you try exporting your configuration to a json file and seeing if the ";3" value is present?

**Comment by pomeloy** [comment]
Thank you! I accidentally used a semicolon instead of a comma as a separator for my custom retention policy.

**Comment by Pectojin** [comment]
Could I get you to post an example? We might be able to catch that on the form and return an obvious error to the user :)

**Comment by pomeloy** [comment]
Sure :) 

    1W:1D,4W:1W;3Y:1M

The last list separator was the culprit here.
