### ISSUE TITLE
Hash mismatch download corruption, likely from throttle buffer offset being reused

### ISSUE THREAD

**Issue by ts678** [duplicati/duplicati#3782]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5
- **Operating system**: Windows 10 or Linux
- **Backend**: File or other

## Description

Throttling downloads low enough gets a "Hash mismatch" error and gives up after 5 (default) tries, so breaks things like restores and remote volume verifies done after backups. The bug is probably in the ThrottledStream [Write](https://github.com/duplicati/duplicati/blob/c46dbbe58f3aaeba9aa32ed9d2c7a5af11881c6c/Duplicati/Library/Utility/ThrottledStream.cs#L155) code where the same input buffer and offset are reused if calling conditions set that up. It's not a network timeout, and even local files will do this. This is not a new issue, but reliably getting it appears to take very low throttle rates, so I hadn't looked at it before. There's a maybe more serious corruption on throttled uploads making files with missing data. Unclear if and how it's related.

One would expect buffer reuse to output the same data repeatedly, instead of getting new data. This is what's observed using the 4MiB known-data file from [Issue 3772](https://github.com/duplicati/duplicati/issues/3772). It contains lines starting with BLOCK NUMBER ##. Below are the original and copied file, to the left and right of the slash respectively. It looks like source data gets output repeatedly at fixed intervals, instead of new data (offset not moved). To get copied /tmp file required Linux (OSX could probably also do this) because Windows locks out file reading while it's in writing. Helping to make sure I got the whole file, I put the copy in a loop and let it go until file vanished. After that was some work with hexdump -Cv and less as the viewer. I searched for BLOCK and noted all addresses (rounded to 0x10) then NUMBER to do the same thing, avoiding the text splits.

~~~
BLOCK NUMBER 00 000001b0 / 000001b0 000051b0 0000a1b0 0000f1b0
BLOCK NUMBER 01 00040260 / 00040260 00045260 0004a260 0004f260
BLOCK NUMBER 02 0004e2b0 / missing
BLOCK NUMBER 03 00075310 / missing
BLOCK NUMBER 04 00083360 / 00083360 0008d360
BLOCK NUMBER 05 000aa3c0 / missing
BLOCK NUMBER 06 000b8420 / missing
BLOCK NUMBER 07 000df470 / missing
BLOCK NUMBER 08 000ed4d0 / missing
BLOCK NUMBER 09 000fb520 / missing
BLOCK NUMBER 0A 00122580 / 00122580 0012c580 
BLOCK NUMBER 0B 001305d0 / 001305d0 001355d0 0013a5d0 0013f5d0
BLOCK NUMBER 0C 00157630 / missing
BLOCK NUMBER 0D 00165690 / missing
BLOCK NUMBER 0E 0018c6e0 / missing
BLOCK NUMBER 0F 0019a740 / missing
~~~

The bad file is missing a bunch of data, having other data replicated an extra 1 to 3 times in a constant-spaced sequence, as if the inner loop were writing the same input buffer position repeatedly to output. Code solution is probably to advance buffer offset variable as data chunks get written out of the buffer.

[New clue for the Fatal Failed: 400 - bad_request: Sha1 did not match data received](https://forum.duplicati.com/t/new-clue-for-the-fatal-failed-400-bad-request-sha1-did-not-match-data-received/2800) is a somewhat similar issue, including useful kenkendk remarks, but I'm hesitant to call it a duplicate because symptoms differ.
## Steps to reproduce

1. Run `test` command on a small backup with --throttle-download=10KB, using local file backend.
Larger backups could also fail, but maybe at higher throttle rates. Network backups may also. Due to [issue 3272](https://github.com/duplicati/duplicati/issues/3272) you probably need to set --throttle-upload instead of --throttle-download, and you might want [--number-of-retries](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#number-of-retries)=1 to save time. I did copy two tmp files from different retries and got same content, so corruption might be algorithmic per caller invocation, not timing or random.

- **Actual result**:
Hash mismatch errors, retries, eventual failure.
- **Expected result**:
Success.

## Debug log

~~~
  Listing remote folder ...
  Downloading file (569 bytes) ...
  Downloading file (2.68 KB) ...
  Downloading file (1.76 MB) ...
Failed to process file duplicati-b58ee3554508846ec9e2d4af169dee876.dblock.zip => Hash mismatch on file "/tmp/dup-bb44e0e8-3a65-4d41-b22c-f6524e5a4a53", recorded hash: Isph8DDm89x6JrxOm5zXX5wDIxQRJWs2TuIgo7Vdhrs=, actual hash lpx3EUm3D6ZE7hOS97549ESpjfMxpJk50sMAEU8vAio=
duplicati-b58ee3554508846ec9e2d4af169dee876.dblock.zip: 1 errors
	Error: Hash mismatch on file "/tmp/dup-bb44e0e8-3a65-4d41-b22c-f6524e5a4a53", recorded hash: Isph8DDm89x6JrxOm5zXX5wDIxQRJWs2TuIgo7Vdhrs=, actual hash lpx3EUm3D6ZE7hOS97549ESpjfMxpJk50sMAEU8vAio=

Return code: 3
~~~

Here are the original backend dblock and the /tmp folder download renamed with .zip suffix:

[duplicati-b58ee3554508846ec9e2d4af169dee876.dblock.zip](https://github.com/duplicati/duplicati/files/3224800/duplicati-b58ee3554508846ec9e2d4af169dee876.dblock.zip)
[dup-db434dbb-860b-459c-b39c-b46f9a123180.zip](https://github.com/duplicati/duplicati/files/3224806/dup-db434dbb-860b-459c-b39c-b46f9a123180.zip)

**Comment by Pectojin** [comment]
Merged #3811 but I'd like to keep this issue open until we've got some more confirmations that it resolves the problem once the canary ships.

**Comment by ts678** [comment]
> confirmations that it resolves the problem once the canary ships.

[Repair does not work over FTP (alternative): Zip archive appears to have a broken Central Record Header, switching to stream mode #3807](https://github.com/duplicati/duplicati/issues/3807) might be a prime candidate. I didn't (and still don't) think that very slow speeds are common, but here's "15KB" giving the right symptoms at the right time, except for a vacation.

Thanks to you both for getting this in. After it's out I can worry about other causes, if a corruption occurs. From a test case point of view, it will also let me test with smaller amounts of data, but at slower speeds...

**Comment by ts678** [comment]
[Restore failing on 3 separate servers on B2](https://forum.duplicati.com/t/restore-failing-on-3-seperate-servers-on-b2/6780/21?u=ts678) would be another prime candidate, but first a canary is needed.

**Comment by warwickmm** [comment]
@ts678, do you think this has been fixed in the newest canary release?
