### ISSUE TITLE
"Stop"-ing the Duplicati Synology Package Does Not Stop Duplicati.Server.exe

### ISSUE THREAD

**Issue by GuyPaddock** [duplicati/duplicati#3788]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5
- **Operating system**: Synology DSM 6.2.2-24922 on DS1618+
- **Backend**: N/A

## Description
Stopping the "Duplicati" package inside DSM Package Center removes only the Duplicati UI from being accessible in the DSM UI but does not actually stop the backend service. This causes confusion when trying to start Duplicati again, because DSM reflects that status as "Stopped" after attempting to start it. This appears to be because the original instance is still running, so the "new" instance can't start successfully.

## Steps to reproduce
1. Ensure Duplicate is installed and running in Synology DSM.
2. SSH into the Synology NAS.
3. Run `ps aux | grep Duplicati.Server.exe`.
4. Take note of the process ID for `Duplicati.Server.exe` (the command might be listed as something like `/volume1/@appstore/Mono/usr/local/bin/mono-sgen /volume1/@appstore/Duplicati/Duplicati.Server.exe`).
5. Log-in to the DSM UI in a web browser.
6. Open Package Center.
7. Open the "Duplicati" package.
8. Click "Stop".
9. Back in the SSH session from step 2, repeat steps 3 and 4.
10. Back in Package Center from step 6, click "Start" to attempt to start Duplicati again.
11. Wait for DSM to start Duplicati.
12. Examine the status shown for Duplicati in Package center.

- **Actual result**:
- At step 4, `Duplicati.Server.exe` is running (as expected).
- When step 4 is repeated as part of step 9, the same `Duplicati.Server.exe` process from step 4 is still running (not expected).
- At step 12, DSM reflects the status of Duplicati as "Stopped" even though the backend for the app is still running. You can actually launch the Duplicati UI through the DSM UI and it will launch, illustrating that the backend is running. *It looks like the stop script might just be stopping the top-level parent process rather than stopping both it and the child `sgen` process.*
- If you stop Duplicati through the DSM Package Center UI AND kill the `Duplicati.Server.exe` process with the `kill` CLI command over SSH, then you can start Duplicati through DSM Package Center and it will start successfully.

- **Expected result**:
- At step 4, `Duplicati.Server.exe` should be running.
- When step 4 is repeated as part of step 9, no `Duplicati.Server.exe` processes should be running.
- At step 12, DSM should reflect the status of Duplicati as "Running".

### Step 4
![image](https://user-images.githubusercontent.com/2631799/58827713-aad28480-8611-11e9-8fe6-371cfeaac7a5.png)

### Step 9 (Repeating Step 4)
![image](https://user-images.githubusercontent.com/2631799/58827799-e5d4b800-8611-11e9-9d5a-c95296dd8518.png)

### Step 12
![image](https://user-images.githubusercontent.com/2631799/58827831-ff75ff80-8611-11e9-9191-ff370a1e006f.png)

**Comment by ts678** [comment]
[2.0.4.10_canary_2018-12-29](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.10-2.0.4.10_canary_2018-12-29)

> Fixed a process shutdown/restart issue on Synology, thanks @drwtsn32x

[Fix Duplicati shutdown issue on Synology #3567](https://github.com/duplicati/duplicati/pull/3567) pull request and discussion. 
Duplicati processes come in pairs. The parent is a launcher for its child which runs the latest installed update and does the work.

Assuming issue is resolved. Issue will automatically close if no further activity.
