### ISSUE TITLE
libappindicator is not part of OpenSUSE - why is it needed?

### ISSUE THREAD

**Issue by nextgenthemes** [duplicati/duplicati#3804]
I saw a old issue about this and it supposedly was fixed by updating I do not think it relates is was from 2017. Ignoring this dep does not work.

```
duplicati     
Gtk-Message: 22:39:15.163: Failed to load module "appmenu-gtk-module"
Unexpected error: System.TypeInitializationException: The type initializer for 'AppIndicator.ApplicationIndicator' threw an exception. ---> System.DllNotFoundException: libappindicator.so.1
```

In openSUSE tumbleweed the package does not exists. Reading what its about it seems its about Unity. But even Ubuntu abandoned it in its recent versions so why is it needed for everyone? 

Just did some quick search about it seems its a pretty controversial lib and indicators for sure can be done differently in every DE except Unity I guess so could this not decoupled or something like only using it when actually on Unity and otherwise use other methods like every single other app is doing? I am on KDE and I do not get why I need a Unity lib installed that is not even in my repos.

And if I have to have it how do I get it?

**Comment by ts678** [comment]
I can't give any design history, but does https://software.opensuse.org/package/libappindicator help any?

**Comment by nextgenthemes** [comment]
No it does not help because I already read that. Lets quote it here.

> A library to allow applications to export a menu into the Unity Menu bar. Based on KSNI it also works in KDE and will fallback to generic Systray support if none of those are available.

It says its also provides a fallback for KDE so IMO duplicati should do it like that fallback is doing with another lib or systray icons then work everywhere I am sure there are those. And **only** if unity is detected use this one. I man arn't 99% of the Linux desktops not on Unity by now? Officially its dead but there are community forks and stuff based on it so its probably not something to drop altogether.

I mean if the lib would exist in the repos in openSUSE I would not care but I get why its not there because Unity is kind of dead so I thought about why this like is even required by everyone.

**Comment by ts678** [comment]
> And if I have to have it how do I get it?

Why do you ask if you know the answer? Or is the link somehow not actually able to get it to you?

This isn't my area, but personally I don't see why Duplicati needs to reinvent what a library can do.

[Welcome to Ayatana Indicators](https://ayatanaindicators.github.io/)
"The Ayatana Indicator project intends to become the new upstream for application indicators and associated projects with a focus on making Ayatana Indicators a desktop agnostic technology."

Sounds good to me, but I'm no expert. Feel free to comment on whether it might meet your needs.

I don't know the OpenSuse direction, but at Debian there's an effort to move to Ayatana Indicators:

[Debian Bug report logs - #895037
libappindicator: deprecated in Debian; AppIndicator based applications, please switch to Ayatana (App)Indicator(s)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037)

[Upcoming shift to Ayatana (App)Indicator(s)](https://lists.debian.org/debian-devel/2018/03/msg00506.html)

[AyatanaIndicatorsTransition
Ubuntu Indicators to Ayatana Indicators Transition](https://wiki.debian.org/Ayatana/IndicatorsTransition)

It looks like Debian's work isn't done. I don't know where OpenSUSE is. Duplicati may not have started however it'd be a good discussion to have (if a suitable person is available) to figure out the direction.

Meanwhile it is what it is. If libappindicator is needed, trying to find and install one might be required. Presumably the problem will get more widespread over time as various distributions do the transition.

**Comment by nextgenthemes** [comment]
> Why do you ask if you know the answer? Or is the link somehow not actually able to get it to you?

I do not know the answer. Its actually the other way around. **You** did not get it! I forget to mention it, because your intention was probably to point me to that fancy install button that is totally misleading and not working, if you click on "show other distros" below on that page you see that the package, like I said is NOT available on openSUSE, they only link the source. And why should it? I said its not in the sources, that website essentially just lists official packages. Its the same as doing a `zypper install xxx` but worse as it lists non existing packages with install buttons.

And for tumbleweed the link leads to a 404 page so not even the source in available there. And I do not like building stuff myself, do not want to spend hours figuring things out. Especially now when I know its deprecated in Debian, I thought its just rolling releaseSUSE issue, makes even a better case to switch to this new thing or whatever.

**Comment by ts678** [comment]
> your intention was probably to point me to that fancy install button that is totally misleading and not working

You're correct about my intention being to point, but I have no way to know if the button works for you. 
On my OS (not an openSUSE), it can download a libappindicator.ymp file for [openSUSE:One Click Install](https://en.opensuse.org/openSUSE:One_Click_Install).
Misleading buttons on the opensuse.org web site aren't something I'm familiar with, or have control of...

https://rpmfind.net/linux/rpm2html/search.php

finds binary RPMs. Tracing one led me to http://download.opensuse.org/tumbleweed/repo/oss/x86_64/

Some binary around there may avoid the need to build, but I don't know why openSUSE can't find them.

On a maybe more productive note for any future move to a different-but-similar still-maintained library:

https://github.com/AyatanaIndicators/libayatana-appindicator/tree/master/bindings/mono

seems worth seeing. It codes `using AyatanaAppIndicator;` which seemingly replaces (if we dare) current:

https://github.com/duplicati/duplicati/blob/c4a72e60bc8d08a32805a8ae87311934269ffe33/Duplicati/GUI/Duplicati.GUI.TrayIcon/AppIndicatorRunner.cs#L19

**Comment by nextgenthemes** [comment]
Actually found out that there is are actually 4 packages in tumbleweed that relate to libappindicator but I guess I tried to install libappindicator directly instead of searching. `libappindicator1` is the package installed now and it seems to work as I see the try icon and the error went away. However:

1. The rpm still does not detect it and requires the wrong package `libappindicator`. So another SUSE specific rpm could be build that is basically a clone of the current one but has `libappindicator1` as requirement or something like `libappindicator` or `libappindicator1` as requirement for a general purpose rpm. I guess this is possible.
2. I still think long term this should be replaced anyway because its a deprecated package.

**Comment by kenkendk** [comment]
Closing this issue as Duplicati no longer relies on GtkSharp (and libappindicator), but uses Avalonia for showing the tray icon.
