### ISSUE TITLE
Backends are not disposed after upload operations

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#3808]
## Environment info

- **Duplicati version**: 2.0.4.16
- **Operating system**: All
- **Backend**: All

## Description

It appears that the backends are not disposed after their use in upload operations.  Previously, their disposal was managed by the `BackendHandler` instance.  However, after pull request #3684, this instance is [no longer used](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Operation/BackupHandler.cs#L403), and it looks like we forgot to ensure that the backends are disposed after their use.  One approach may be to make each `Worker` implement the `IDisposable` interface (each `Worker` [contains](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Operation/Backup/BackendUploader.cs#L149) an [instance](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Operation/Backup/BackendUploader.cs#L446) of an `IBackend`).

There is a related forum discussion [here](https://forum.duplicati.com/t/backups-to-sftp-not-closing-connection/7481/2), where a user noticed that SFTP connections were not being closed and a maximum connection limit was being reached.

**Comment by warwickmm** [comment]
I can see with the SFTP backend that connections remain open after an upload has completed.

**Comment by Pectojin** [comment]
Closed by #3809
