### ISSUE TITLE
Failed to send an email with oulook configured

### ISSUE THREAD

**Issue by keppo070** [duplicati/duplicati#3813]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.4.5_beta_2018-11-28
- **Operating system**: w10pro 1903 and Ubuntu 18.04.2 LTS (linuxserver\duplicati docker)
- **Backend**: Onedrive v2

## Description
email logs from backup are not sending authentication fault

Jul 14, 2019 12:03 PM: Failed to send message: MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.3 Authentication unsuccessful [AM4PR0701CA0007.eurprd07.prod.outlook.com] 

## Steps to reproduce

1. edit text in settings
2. options configured
--send-mail-url=smtp://smtp.office365.com:587/?starttls=when-available
--send-mail-any-operation=true
--send-mail-to=RecievingUsername@hotmail.com
--send-mail-username=SendingUsername@outlook.com
--send-mail-password=apppassword
--send-mail-from=SendingUsername@outlook.com
--send-mail-body=%RESULT%
--send-mail-subject="Duplicati %PARSEDRESULT%, %OPERATIONNAME% report for %backup-name%-cpu"
3. I tried with a small powershell script if uses adresses and password are ok and these are correct.
4. PSscript
'''
$SmtpServer = 'smtp.office365.com'
$SmtpUser = 'SendingUsername@outlook.com'
$smtpPassword = 'apppassword'
$MailtTo = 'RecievingUsername@hotmail.com'
$MailFrom = 'SendingUsername@outlook.com'
$MailSubject = "Test using $SmtpServer" 

$Credentials = New-Object System.Management.Automation.PSCredential -ArgumentList $SmtpUser, $($smtpPassword | ConvertTo-SecureString -AsPlainText -Force) 
Send-MailMessage -To "$MailtTo" -from "$MailFrom" -Subject $MailSubject -SmtpServer $SmtpServer -UseSsl -Credential $Credentials
'''
5. I use an apppassword because of 2FA

- **Actual result**:
Jul 14, 2019 12:03 PM: Failed to send message: MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.3 Authentication unsuccessful [AM4PR0701CA0007.eurprd07.prod.outlook.com] 
- **Expected result**:
An Email in my mailbox

## Debug log
'''
Jul 14, 2019 12:03 PM: Failed to send message: MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.3 Authentication unsuccessful [AM4PR0701CA0007.eurprd07.prod.outlook.com] 
'''

**Comment by keppo070** [comment]
I tried to connect with de commandline version this is the result

C:\Program Files\Duplicati 2>duplicati.commandline send-mail --log-file-log-level=Profiling --send-mail-url=smtp://smtp.office365.com:587?starttls=when-available --send-mail-to=RecievingUsername@hotmail.com --send-mail-username=SendingUsername@outlook.com --send-mail-password=apppassword --send-mail-from=SendingUsername@outlook.com --send-mail-body=body --send-mail-subject=subject
Complete SMTP communicatie: Connected to smtp://smtp.office365.com:587/?starttls=when-available
S: 220 AM4PR07CA0001.outlook.office365.com Microsoft ESMTP MAIL Service ready at Sun, 14 Jul 2019 12:38:22 +0000
C: EHLO [IPv6:2001:1c00:1107:4600:2175:2128:235c:ca0]
S: 250-AM4PR07CA0001.outlook.office365.com Hello [2001:1c00:1107:4600:2175:2128:235c:ca0]
S: 250-SIZE 157286400
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-STARTTLS
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250 SMTPUTF8
C: STARTTLS
S: 220 2.0.0 SMTP server ready
C: EHLO [IPv6:2001:1c00:1107:4600:2175:2128:235c:ca0]
S: 250-AM4PR07CA0001.outlook.office365.com Hello [2001:1c00:1107:4600:2175:2128:235c:ca0]
S: 250-SIZE 157286400
S: 250-PIPELINING
S: 250-DSN
S: 250-ENHANCEDSTATUSCODES
S: 250-AUTH LOGIN XOAUTH2
S: 250-8BITMIME
S: 250-BINARYMIME
S: 250-CHUNKING
S: 250 SMTPUTF8
C: AUTH XOAUTH2 {problaly apppassword}
S: 535 5.7.3 Authentication unsuccessful [AM4PR07CA0001.eurprd07.prod.outlook.com]
C: AUTH LOGIN
S: 334 VXNlcm5hbWU6
C: {username}
S: 334 UGFzc3dvcmQ6
C: {password}
S: 535 5.7.3 Authentication unsuccessful [AM4PR07CA0001.eurprd07.prod.outlook.com]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
Verzenden van bericht mislukt: MailKit.Security.AuthenticationException: AuthenticationInvalidCredentials: 5.7.3 Authentication unsuccessful [AM4PR07CA0001.eurprd07.prod.outlook.com]
 => AuthenticationInvalidCredentials: 5.7.3 Authentication unsuccessful [AM4PR07CA0001.eurprd07.prod.outlook.com]
Update "2.0.4.23_beta_2019-07-14" detected

**Comment by keppo070** [comment]
I created a gmail address with this information. This works. But I had to adjust in the google account to allow 'less secure apps access'

Could it be that this is also the issue with outlook.com? is there such an option


--send-mail-url=smtp://smtp.gmail.com:587/?starttls=when-available
--send-mail-any-operation=true
--send-mail-to=recieving@hotmail.com
--send-mail-username=sending@gmail.com
--send-mail-password=<password>
--send-mail-from=sending@gmail.com
--send-mail-body=%RESULT%
--send-mail-subject="Duplicati %PARSEDRESULT%, %OPERATIONNAME% report for %backup-name%-cpu"
--accept-any-ssl-certificate=true

**Comment by ts678** [comment]
Did you find a solution? If so, what did it take? If not, top Google hit for "5.7.3 Authentication unsuccessful" "smtp.office365.com"

[535: 5.7.3 Authentication unsuccessful](https://answers.microsoft.com/en-us/msoffice/forum/all/535-573-authentication-unsuccessful/cd915151-ae89-4505-8ad3-29680554e710) links to [Enable or disable authenticated client SMTP submission (SMTP AUTH) in Exchange Online](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission) which sounds like Microsoft's reluctant acceptance that some applications still need to use SMTP, even if it's not preferred.

[How to set up a multifunction device or application to send emails using Microsoft 365 or Office 365](https://learn.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365) might offer you other hints.
