### ISSUE TITLE
Database version mismatch

### ISSUE THREAD

**Issue by AimoE** [duplicati/duplicati#3816]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.23
- **Operating system**: Windows 10
- **Backend**: Local disk

## Description

I successfully ran backups yesterday with version 2.0.4.22 and then upgraded to 2.0.4.23. After that, backups on my Ubuntu machine succeeded, but on Windows each backup failed. Duplicati tells me: 

“The database has version 9 but the largest supported version is 8. This is likely caused by upgrading to a newer version and then downgrading. If this is the case, there is likely a backup file of the previous database version in the folder C:\Users\haltia\AppData\Local\Duplicati.”

However, I have never ever downgraded Duplicati on my Windows machine.

I got the problem resolved by doing the first downgrade of Duplicati on this machine (uninstalling Duplicati and then installing version 2.0.4.22). Now backups work again. I still have the version 2.0.4.23 on my Ubuntu machine, as it seems to work there. 

## Steps to reproduce

I have not tried to reproduce this but I would expect it to be 100% reproducible.

- **Actual result**: 
backups do not even start; the job-specific sqlite files are not touched; 
the Duplicati-server-sqlite is the only sqlite file that has gotten modified 
- **Expected result**: 
successful backups as usual 

## Debug log

There is no singe log on this because the backups do not even start.

**Comment by AimoE** [comment]
Additional note: I always run the upgrades (and now did the downgrade) by running installer files downloaded from your download site. I never do upgrades from the web gui.

**Comment by AimoE** [comment]
All right. I have been advised (in https://forum.duplicati.com/t/release-2-0-4-23-beta-2019-07-14/7522/6) that I should not regard version 2.0.4.23 as direct next version to 2.0.4.22. You could use a clearer versioning scheme. And you really should tell about each database (schema?) version update on the download page. And you should link each release on download page to its related change log too.

**Comment by Pectojin** [comment]
Yes, it's very confusing.

Previously "higher" has always been "newer". It's the first time a release hasn't contained all previous changes in e.g. the Canary, so we don't really have a good way of telling users about.

If it's just a one time thing, due to the Amazon Cloud Drive deprecation, then it shouldn't be an issue again in the future.

**Comment by ts678** [comment]
> If it's just a one time thing, due to the Amazon Cloud Drive deprecation, then it shouldn't be an issue again in the future.

I've made a counter-proposal that there will be continuing need to be able to hot-fix beta problems more gracefully, that this will worsen over time, and so perhaps it's time for a bit of upgrading in our approach.

[Release: 2.0.4.23 (beta) 2019-07-14](https://forum.duplicati.com/t/release-2-0-4-23-beta-2019-07-14/7522/20?u=ts678)

**Comment by AimoE** [comment]
The dependency on various cloud services may perhaps require you to consider adding a notification feature to Duplicati. There will be users who do not want to share information about their installations and they cannot receive notifications, but treating this as notification that is dynamically shown to users instead of making a software change seems better to me.

**Comment by AimoE** [comment]
Actually, you already have implemented a notification channel for version updates. Hopefully that mechanism can be enhanced to include another channel for another type of notifications?

**Comment by philippludwig** [comment]
So I am in the same boat and I have no clue which version I need to install to access my "Version 9" backup. I tried: 

* duplicati_2.0.4.21-1_all.deb
* duplicati_2.0.4.22-1_all.deb
* duplicati_2.0.4.23-1_all.deb

All of them complain about this; what is the correct version to install?

**Comment by AimoE** [comment]
I close this as it turned out to be my own error (forgot to shut down the previous version's process).
