### ISSUE TITLE
No backup logging on cli

### ISSUE THREAD

**Issue by Photographix** [duplicati/duplicati#3834]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.22
- **Operating system**: Windows Server 2019
- **Backend**: Jotta

## Description
- no logging over backup operationen (std out or file)
- no verbose debug output
- log in mode DELETE, PURGE, REPAIR works as expected

## Steps to reproduce
1. Jotta account (probably not important)
2. batch file with the following options (customize account data and passwords)
`Duplicati.CommandLine.exe backup "jottacloud://ABCD" "\\aio-pod\Documents\\" --auto-cleanup="true" --auto-update="true" --auto-vacuum="true" --number-of-retries="10" --retry-delay="60s" --use-block-cache="false" --asynchronous-upload-limit="6" --asynchronous-upload-folder=c:\Temp\dupli\Documents\ --asynchronous-concurrent-upload-limit="4" --concurrency-block-hashers="2" --concurrency-compressors="2" --concurrency-max-threads="0" --backup-name="AIO-documents>Jotta" --dbpath="C:\Users\Administrator\AppData\Roaming\Duplicati\jotta-documents.sqlite" --encryption-module="aes" --compression-module="zip" --dblock-size="300MB" --keep-time="6M" --passphrase="ABCD" --disable-module="console-password-input" --exclude=".zfs\" --exclude="*." --disable-filelist-consistency-checks --console-log-level="Profiling" --log-file=Logging\Documents\Documents-jotta-bkp.log --log-file-log-level="Profiling" --debug-output
`

- **Actual result**:
- no debug output, no std backup output, no bkp logfile
- **Expected result**:
- logging as in DELETE, PURGE, REPAIR mode 
- in a previous version, this worked for BACKUP. i can't tell when anymore. since i only need the logfiles sometimes.

## Screenshots
![2019-07-23 11_11_13-Window](https://user-images.githubusercontent.com/16647382/61700406-f0bbe700-ad3c-11e9-9719-6bf0954eee4b.png)

**Comment by ts678** [comment]
Try changing `--exclude=".zfs\"` to `--exclude=".zfs"` or `--exclude=".zfs\\"` (if you want the backslash) otherwise it will probably gather in all the options to its right (meaning they won't be treated as options).

[Parsing C++ Command-Line Arguments](https://docs.microsoft.com/hr-hr/cpp/cpp/parsing-cpp-command-line-arguments?view=vs-2019)

> A double quotation mark preceded by a backslash (\") is interpreted as a literal double quotation mark character (").

> If an even number of backslashes is followed by a double quotation mark, one backslash is placed in the argv array for every pair of backslashes, and the double quotation mark is interpreted as a string delimiter.

**Comment by Photographix** [comment]
Uuuh thanks! It works again ;-) Unfortunately I didn't think of it.
