### ISSUE TITLE
Website 503 bad gateway - Downloading impossible

### ISSUE THREAD

**Issue by TheNewSound** [duplicati/duplicati#3838]
Download button gives either a 503 or fails after a few hundred kB's

**Comment by ewouddemoor** [comment]
I have the same issue here. 
But still able to download from here: https://github.com/duplicati/duplicati/releases

**Comment by warwickmm** [comment]
I believe this has been fixed.

https://forum.duplicati.com/t/download-links-not-working-anymore/7620/15
