### ISSUE TITLE
Feature request:  Additional tray icon status styles

### ISSUE THREAD

**Issue by drwtsn32x** [duplicati/duplicati#3861]
Currently the tray icon will display a "Red X" style not only for error conditions, but also for warning and informational events.

Suggest we add two more styles:
* "Yellow exclamation" style to be used for Warnings (eg, backup job completed with warnings).
* "Blue information" style to be used for Informational events (eg, new version available).

If multiple alerts are active, it should use the style for the most severe alert.

Thoughts?

**Comment by warwickmm** [comment]
What platform?  The GTK notification icons were supposed to be fixed in #3739.

**Comment by drwtsn32x** [comment]
I am thinking of Windows - I had no idea that GTK had additional icons like that!  Would be nice if Windows did as well.

**Comment by drwtsn32x** [comment]
PR 3943 implements the main feature I was looking for
