### ISSUE TITLE
Add a short description to backup filesets 

### ISSUE THREAD

**Issue by rdbox** [duplicati/duplicati#3869]
I often use duplicati and I have a requirement to make a brief description of my copies. Will this be implemented in new versions?

**Example:** when creating a backup, to have an additional field for entering user text
![image](https://user-images.githubusercontent.com/18515862/63641338-26921980-c6b5-11e9-9faa-23a28edf1166.png)

**Comment by Pectojin** [comment]
Descriptions were added in PR #3436, about a year ago, so it's available in every update channel.

They can be added when editing the backup, and are then available when exanding the backup.
<img width="356" alt="Screenshot 2019-08-24 at 22 02 03" src="https://user-images.githubusercontent.com/1561484/63642123-d74ee780-c6ba-11e9-9bc3-1fd620235123.png">

**Comment by rdbox** [comment]
@Pectojin I meant the description for each version.
It often happens that important files change during backup, I need to mark them somehow so that I understand which ones.

**Comment by Pectojin** [comment]
Ah, that's different. I'm not sure there is a good way of storing that, though.

The restore points are automatically generated, so there isn't an interface for creating/updating them. 

And the data is stored in the backup specific databases, so you would lose your descriptions in a database recreate or if restoring from a different machine.

**Comment by BlueBlock** [comment]
The description could be added to the file set. And I'm thinking the database should be copied to the destination after a backup or edit.

**Comment by rdbox** [comment]
@Pectojin @BlueBlock 
is that possible? What would be the new fields when adding a new backup? It will be enough to add a description of 10-80 characters to briefly describe what this version of the copy is

**Comment by BlueBlock** [comment]
> @Pectojin @BlueBlock
> is that possible? What would be the new fields when adding a new backup? It will be enough to add a description of 10-80 characters to briefly describe what this version of the copy is

Each backup run adds a record to fileset. We would add a 'description' text field to fileset.

**Comment by rdbox** [comment]
@BlueBlock Fine, the most important thing is that you've seen my appeal about this need. Will you tell the developers yourself or should I do something about it?

**Comment by BlueBlock** [comment]
> @BlueBlock Fine, the most important thing is that you've seen my appeal about this need. Will you tell the developers yourself or should I do something about it?

I can put this on a list for future enhancements for when out of beta.

**Comment by ts678** [comment]
[Allow user to manually / automatically add note/description to backup #2153](https://github.com/duplicati/duplicati/issues/2153) looks like the same request. Regarding "tell the developers", GitHub Issues and forum [Features](https://forum.duplicati.com/c/features) are the main ways of tracking requests.

**Comment by Pectojin** [comment]
Good catch, I think we should let #2153 track the progress on this.
