### ISSUE TITLE
frequent, inefficient query on "Block" table is very slow on large databases.

### ISSUE THREAD

**Issue by waljohn** [duplicati/duplicati#3884]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------
Relevant forum post:
https://forum.duplicati.com/t/performance-tips-what-is-normal/6471/9 (recent, unknown version, exact duration not recorded)
https://forum.duplicati.com/t/stuck-on-starting/429/4 (2.0.2.1_beta_2017-08-01) took 02:07:24.819

## Environment info

- **Duplicati version**: Unclear, however the latest DDL still has this issue. Presumably, all versions.
- **Operating system**: UNIX (not OS specific)

## Description

The following query is invoked frequently: for example when running a backup, or during compaction:

`SELECT COUNT(*) FROM "Block" WHERE "Size" > 102400`

For very large databases, this query is a major bottleneck because the Block column is not indexed. The discussion board report reported operations hanging for 'several hours.'

## Steps to reproduce

1. Run, compact, etc a backup on a very large database
2. OBSERVE in the Live profiling log, this query is called just before `CREATE TEMPORARY TABLE "UsageReport-....`

- **Actual result**:
Example indicated in forum post:
```
Sep 14, 2017 12:14 PM: ExecuteScalarInt64: SELECT COUNT(*) FROM "Block" WHERE "Size" > ? **took 02:07:24.819**
Sep 14, 2017 10:04 AM: Server has started and is listening on 0.0.0.0, port 8200
```
- **Expected result**:
This will be very, very fast.

## Debug log

I did not personally have this issue, it was reported on a forum, but here is information that shows the way problem happens, though not the actual problem per-se:

```
    SELECT COUNT(1) 
      FROM "Block" 
     WHERE "Size" > 102400;

    /* Result: 1 rows returned in 1528ms
    At line 1:
    SELECT COUNT(1) FROM "Block" WHERE "Size" > 102400; */

    EXPLAIN QUERY PLAN 
    SELECT COUNT(1) 
      FROM "Block" 
     WHERE "Size" > 102400;

      id   parent   notused                         detail                         
     ---- -------- --------- ----------------------------------------------------- 
       3        0         0   SCAN TABLE Block USING COVERING INDEX BlockHashSize  
```
The slowdown is caused by the fact that the "Size" column is non-indexed and the planner is choosing an index which isn't suited for this. This choice is actually correct, it has no better alternative. What's worse, from looking at the code it _appears_ this query is just a 'sanity check' and will normally return zero rows. 

I imported all the data into an equivalent Postgres table for comparison. Postgres did no better:
```
QUERY PLAN                                                                                                                                        
--------------------------------------------------------------------------------------------------------------------------------------------------
Finalize Aggregate  (cost=29634.47..29634.48 rows=1 width=8) (actual time=446.185..446.185 rows=1 loops=1)                                        
  Output: count(1)                                                                                                                                
  ->  Gather  (cost=29634.26..29634.47 rows=2 width=8) (actual time=445.492..479.244 rows=3 loops=1)                                              
		Output: (PARTIAL count(1))                                                                                                                
		Workers Planned: 2                                                                                                                        
		Workers Launched: 2                                                                                                                       
		->  Partial Aggregate  (cost=28634.26..28634.27 rows=1 width=8) (actual time=428.475..428.476 rows=1 loops=3)                             
			  Output: PARTIAL count(1)                                                                                                            
			  Worker 0: actual time=420.373..420.373 rows=1 loops=1                                                                               
			  Worker 1: actual time=421.054..421.055 rows=1 loops=1                                                                               
			  ->  Parallel Seq Scan on public.duplicati_block  (cost=0.00..28634.23 rows=10 width=0) (actual time=428.461..428.461 rows=0 loops=3)
					Output: "ID", "Hash", "Size", "VolumeID"                                                                                      
					Filter: (duplicati_block."Size" > 102400)                                                                                     
					Rows Removed by Filter: 575951                                                                                                
					Worker 0: actual time=420.357..420.357 rows=0 loops=1                                                                         
					Worker 1: actual time=421.040..421.040 rows=0 loops=1                                                                         
Planning Time: 0.655 ms                                                                                                                           
Execution Time: 479.513 ms         
```

This isn't a SQLite bug, it's just inherent in the design of this table.

```
    SELECT 'total' as DETAIL, COUNT(1) as ROWCOUNT
      FROM "Block"
      UNION ALL SELECT 'distinct', count(DISTINCT "Size")
                  FROM "Block" ;

       DETAIL    ROWCOUNT  
     ---------- ---------- 
      total       1727853  
      distinct      50891  
```

This value will benefit from indexing
```
    create index BlockCountSizeIdx on "Block"("Size");

    SELECT COUNT(1) 
      FROM "Block" 
     WHERE "Size" > 102400;

    /* Result: 1 rows returned in 9ms
    At line 17:
    SELECT COUNT(1) FROM "Block" WHERE "Size" > 102400; */

    EXPLAIN QUERY PLAN 
    SELECT COUNT(1) 
      FROM "Block" 
     WHERE "Size" > 102400;

      id   parent   notused                                 detail                                
     ---- -------- --------- -------------------------------------------------------------------- 
       3        0         0   SEARCH TABLE Block USING COVERING INDEX BlockCountSizeIdx (Size>?)  
```

The planner realized it can answer this question solely from the index, so it wouldn't've fetched _any_ pages at all, so hardly any disk IO.

Perhaps Duplicati could monitor the 'speed' of this and maybe other potentially high-impact queries, and create the index only if the query is slow. Or, perhaps this query could be run less frequently, or its result stored etc

**Comment by warwickmm** [comment]
Great analysis @waljohn.  :+1: 


> from looking at the code it appears this query is just a 'sanity check' and will normally return zero rows.

This is an important check to verify that the user has not specified a block size that is incompatible with the current backup.

Note that the existing block size is stored in the `Configuration` table, which could lead to a much simpler query.  However, it's unclear how safe this would be, and scanning the `Block` table may be the most complete check.  In this case, creating an index like you mention may be the best option.

**Comment by BlueBlock** [comment]
Or any frequent check could hit the configuration table and any verification check hit the Block table, if it does not already.

**Comment by warwickmm** [comment]
[Here's](https://forum.duplicati.com/t/repairing-a-big-database/8174/4) another case where a user experienced a dramatic increase in performance after adding an index (went from > 3 hours to 11 ms).

**Comment by asterr** [comment]
I had very poor performance in compact, with this query:

Apr 11, 2020 10:51 AM: Starting - ExecuteReader: SELECT "A"."Hash", "C"."Hash" FROM (SELECT "BlocklistHash"."BlocksetID", "Block"."Hash", * FROM "BlocklistHash","Block" WHERE "BlocklistHash"."Hash" = "Block"."Hash" AND "Block"."VolumeID" = 17078) A, "BlocksetEntry" B, "Block" C WHERE "B"."BlocksetID" = "A"."BlocksetID" AND "B"."Index" >= ("A"."Index" * 3200) AND "B"."Index" < (("A"."Index" + 1) * 3200) AND "C"."ID" = "B"."BlockID" ORDER BY "A"."BlocksetID", "B"."Index"


Following the suggestions above, I added the following index, and have gone from hours to seconds:

CREATE UNIQUE INDEX "BlockHashVolumeID" ON "Block" ("Hash", "VolumeID")

**Comment by rcmaniac25** [comment]
It's been a bit, but I want to just chime in that I added these queries do my Dupliciti DB running on my Synology (~3.5TB data) and backups went from 14h to 6h. Just those 2 queries.
