### ISSUE TITLE
CommandLine test-filters fails on RegExp pipe (or-function) on linux 

### ISSUE THREAD

**Issue by arberg** [duplicati/duplicati#3891]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.23_beta_2019-07-14
- **Operating system**: Linux docker, [linuxserver](https://hub.docker.com/r/linuxserver/duplicati)

## Description
Commandline regExp fails to match if it contains the selection group with `|`, for example `(x|y)`

## Steps to reproduce

All of the command examples below are identical except the ending in the regExp.

* This matches /mnt/user/media/TestDuplicati/A/
`docker exec duplicati mono /app/duplicati/Duplicati.CommandLine.exe test-filters /mnt/user/media/TestDuplicati/ --exclude='[/mnt/user/media/Test(A)/]'`

* This does not (where we now have (A|A)
`docker exec duplicati mono /app/duplicati/Duplicati.CommandLine.exe test-filters /mnt/user/media/TestDuplicati/ --exclude='[/mnt/user/media/Test(A|A)/]'`

Interestingly this 
`docker exec duplicati mono /app/duplicati/Duplicati.CommandLine.exe test-filters /mnt/user/media/TestDuplicati/ --exclude='[/mnt/user/media/TestDuplicati/(A\|Test1)/]'`

gives the output 

    Including path as no filters matched: /mnt/user/media/TestDuplicati/A/
    Excluding path due to filter: /mnt/user/media/TestDuplicati/Test1/ => ([/mnt/user/media/TestDuplicati/(A\\|Test1)/])

which hints that the other problem might be some escaping. The above should not have excluded Test1, as it should match (I think) the folder name 'A|Test1'.

## UI
Entering filters with (A|B) in UI works as expected.

## Docs
I have commented about it in the docs here: https://github.com/duplicati/duplicati/wiki/How-do-filters-work%3F

**Comment by ts678** [comment]
[Bug Regular Expression Filter operator ‘|’ (or) does not work inside parenthesis ()](https://forum.duplicati.com/t/bug-regular-expression-filter-operator-or-does-not-work-inside-parenthesis/7950/8?u=ts678) supports a theory of a general command line escaping issue, with possible workaround of disabling autoupdater mechanism.

**Comment by arberg** [comment]
Identical (earlier) issue: https://github.com/duplicati/duplicati/issues/3135

**Comment by warwickmm** [comment]
Fixed in pull request #3911.
