### ISSUE TITLE
Error: "One or more errors occurred" yet log is empty

### ISSUE THREAD

**Issue by ninjalf2** [duplicati/duplicati#3895]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.23_beta_2019-07-14 running in a Docker container
- **Operating system**: CentOS 7 VM running on Citrix Hypervisor 8
- **Backend**: Jottacloud

## Description

Running backup job fails with "One or more errors occurred". Clicking "Show" gives me a completely empty backup log.

System log says: `8. sep 2019 15:41: Failed while executing "Backup" with id: 1`

I have managed to find what the error actually is but I am going to put that in a different issue. The problem here is that I cannot see the error messages in the GUI. I've seen this before and to go to see the Docker logs or elsewhere.

Edit: In case it's relevant, the error was that the /tmp filesystem in (the Docker container) was full. Old files from incomplete backups were lingering there, totaling about 21GB. My mistake was to set the remote volume size to 2GB, meaning that volumes were created faster than they could be uploaded (I think). Also, old stale files were not being cleared by Duplicati.

Edit 2: Now I get the same error, again, with an empty log. The filesystem is no longer full and I cannot find anything with `Docker logs`. Right now this is keeping me from doing backups at all.

## Steps to reproduce

1. Start backup of 1TB file
2. Receive error "One or more errors occurred"
3. Click show

- **Actual result**:
Descriptive error message(s)
- **Expected result**:
Completely empty log

## Screenshots

![screenshot-2019-09-08-16-00-44_edited](https://user-images.githubusercontent.com/6133724/64489334-3d5a7380-d252-11e9-85d7-5e7a64b2b939.png)

## Debug log

Where do I find this?

**Comment by neekt** [comment]
Possibly in the Live log, as mentioned in [here](https://github.com/duplicati/duplicati/issues/3920#issuecomment-539809547)?

> sometimes warnings show up not in the job log but in the main Live log. After you get the warning, go to the Duplicati Web UI -> About -> Show Log -> Live, and then select Warning from the dropdown.

But replacing Warning with Error.

**Comment by mdio** [comment]
I had the same issue as mentioned above 

> Running backup job fails with "One or more errors occurred". Clicking "Show" gives me a completely empty backup log.

Navigating to the live log and selecting warnings revealed them (a problem with the pre-backup script and some files that could not be processed).

However I'm not sure if that worked only because I first navigated to the live log and then started the job.

In any case: Ideally the "Show" button should show the errors (or warnings) it notifies about.

**Comment by warwickmm** [comment]
Closing this in favor of #1152.
