### ISSUE TITLE
Restore from OneDrive results in 59 warnings and reboot crashes on start with no errors

### ISSUE THREAD

**Issue by JohnGalt1717** [duplicati/duplicati#3898]
- **Duplicati version**: 2.0.4.23_beta_2019-07-14
- **Operating system**: Docker LInux
- **Backend**: OneDrive V2

## Description
Backup works successfully to the cloud.
Restoring a file as a test results in 50 warnings(s) that cannot be dismissed in the web browser.
If I docker-compose down and then docker-compose up -d the webui won't respond after that.

## Steps to reproduce
1. Backup to OneDrive V2
2. Restore single file to a specific location (not original)
3. You'll note "Got 59 warning(s). This prompt won't go away. Dismiss does nothing, refresh of browser does nothing.
4. docker-compose down
5. docker-compose up -d

- **Actual result**:
Duplicati no longer works
- **Expected result**:
Should work normally.

## Debug log
Never created.

Appears to be a permissioning issue on the config files created. Running sudo chmod -R 777 on the config directory on the host appears to fix the problem.

**Comment by ts678** [comment]
> Running sudo chmod -R 777 on the config directory on the host appears to fix the problem.

What were the permissions before? How do they line up with what Duplicati is running as (depends on whose Docker image)? When discussing non-777 permissions, user and group may matter. Some image makers (such as LinuxServer) don't use root.

I don't use Docker, but I'm having a hard time figuring out how Duplicati could make files, then not be able to use them later. Running a regular Linux system with a Duplicati systemd service, I tried to sabotage the root .config/Duplicati by taking away permissions and giving away the folder. I wanted to see if it would set them back. It didn't, and of course it just kept working.

Something running as non-root could get blocked, but I'm not sure what typical scenario would block it from files it created...
Could there have been any external changes that changed permissions? Once changed once, did everything stay happy later?

Is OneDrive restore necessary, or just how it happened? I don't know how a restore could hurt things, but I did one anyway...

Is this still of interest and happening? Any updates? Was there anything specific requested (certainly can't study those errors)?
