### ISSUE TITLE
Duplicati resolves the name each time a volume needs to be sent

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#390]
_From [Baris.E...@gmail.com](https://code.google.com/u/111747904532448020049/) on March 24, 2011 21:12:23_

What steps will reproduce the problem? 1. Take normal backup that takes multiple volumes. What is the expected output? What do you see instead? I expect that once it makes the connection to the back-end service, it doesn't kill that connection or forget about its IP address. What version of the product are you using? On what operating system? 1.2 What backend (destination) are you using? WebDAV on IIS7 Please provide any additional information below. Basically when computers that need to be backed up floats from one network context to another; they could be resolving names in different networks. If Duplicati were to stick to the IP address it found during initial backup job start for the entire duration of multi-volume process, it would be resilient to underlying network changes and could finish the jobs more reliably.

I have a related wish that I'll file separately.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=390_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
