### ISSUE TITLE
Backup job failed (FTP backend): CoCoL.RetiredException: The channel "ProcessedFiles" is retired. or similar errors

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#3900]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.28 (eror first occurred in 2.0.4.23 some days ago, so I upgraded)
- **Operating system**: Windows 10
- **Backend**: FTP (alternative)

## Description
I had a backup job running on my father's machine, backing up through a VPN to an FTP destination. (see #3807 for details about the environment, which ist basically a very slow internet connection)

The jos ran fine for a couple of weeks. A week ago, the backend started givin all kinds of errors.

So I tried to create a new job (which is smaller, about 35MB of data) against the same backend and get the same problems: , see attached output file.

## Steps to reproduce
For me, just run any of the backup jobs against that backend.
I can see files being uploaded to the destination. There are 6 files of 19,9MB each. Which means 120MB of data for a job that ran once with 35MB of data to be backed up. How's that, by the way?

## Debug log
See attached file, this is what I get mailed by Duplicati.
[result.txt](https://github.com/duplicati/duplicati/files/3612717/result.txt)

**Comment by ts678** [comment]
There's not enough info here yet to give comment. Is this still reproducible on current release?
