### ISSUE TITLE
Make use of free static code analysis tools for OSS

### ISSUE THREAD

**Issue by albahrani** [duplicati/duplicati#3907]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 0.0.0.0
- **Operating system**: Win10
- **Backend**: S3

## Description

Make use of static code analysis tools which are free to use for OSS and easy to integrate with Github. While I'm pretty sure everybody here tries pretty hard to delivery the highest code quality possible, nobody is perfect.

I would suggest https://app.codacy.com/login, it supports the languages used for duplicati.

It is especially useful for checking Pull Requests before merging them.

**Comment by warwickmm** [comment]
Thanks!  We are already using codacy.  :smile:
