### ISSUE TITLE
Unable to retry backup jobs

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#391]
_From [Baris.E...@gmail.com](https://code.google.com/u/111747904532448020049/) on March 24, 2011 21:17:03_

What steps will reproduce the problem? 1. Start a backup that will take multiple volumes and long time.
2. In the middle, interrupt the network in any way. 3. What is the expected output? What do you see instead? Duplicati will just end the job without any attempt to retry. I would rather have it offer an option to retry and continue what it was doing when it's in interactive mode. This could be implemented as a prompt with self-timer. If a user doesn't respond, say, in 10 minutes, it can abort. It can even self-try for a few times and then decide to abort. Current behavior is too fragile. What version of the product are you using? On what operating system? 1.2 What backend (destination) are you using? WebDav Please provide any additional information below. For example, I'd like to be able to close the lid on a laptop in themiddle of a backup; later turn it on (feel free to have a timer here that would warrant a complete restart) and have it auto-retry and continue the job.

On large backup volumes, it's taking quite a while for these jobs to finish. Anything you can do to accommodate more reliable backups would help.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=391_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
