### ISSUE TITLE
High CPU while idling v. 2.0.4.29 (17 Sep 2019)

### ISSUE THREAD

**Issue by StevenKSanford** [duplicati/duplicati#3918]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.29 & Mono Framework 6.0.0.334.macos10
- **Operating system**: MAC OSX Mojave 10.14.6
- **Backend**: Google Drive

## Description

A few minutes after starting Duplicati, my CPU fan starts running on high, even though it is not actively running a backup. Activity Monitor shows MONO using 138% of CPU. I've monitored this for over 24 hours, no change (even with a scheduled backup job running during this period)

## Steps to reproduce

1. start Duplicati
2. wait 3-5 minutes
3. fan will speed up, Activity Monitor shows high CPU usage for MONO
4. quit Duplicati and CPU usage returns to normal

 
 
- **Actual result**:
CPU runs hot, even when Duplicati is idle (waiting for next job)
- **Expected result**:
should not run up CPU usage while idling

**Comment by warwickmm** [comment]
This should be fixed in version [2.0.4.30](https://github.com/duplicati/duplicati/releases/tag/v2.0.4.30-2.0.4.30_canary_2019-09-20).  If you still experience this after updating, please let us know by reopening this issue.

**Comment by StevenKSanford** [comment]
Thanks. Will do... Steve

Steven K. Sanford
*email: *ssanford11@su.edu
*web:*  www.*stevenksanford.com* <https://www.stevenksanford.com>
*cell #:* 203-543-7222
