### ISSUE TITLE
Backups containing a single file are not restorable

### ISSUE THREAD

**Issue by drwtsn32x** [duplicati/duplicati#3937]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Affects 2.0.4.24 and greater
- **Operating system**: Affects Windows (not sure about Linux)
- **Backend**: Any

## Description

PR https://github.com/duplicati/duplicati/pull/3846 seems to have introduced a bug for backup sets that contain just a single file.  Backups operate ok, but you cannot restore the file.  It is shown in the file restoration dialog with a folder icon and a trailing backslash.

If you try to restore it, duplicati reports "Restore completed without errors but no files were restored."

## Steps to reproduce

1. Create backup set
2. Select a single file to back up
3. Perform the backup
4. Attemp to restore the file
5. Note the failure

- **Actual result**:
Failure to restore file
- **Expected result**:
File should be restored correctly

## Screenshots
Restore selection dialog for versions before 2.0.4.24. File is displayed properly and is restorable:
![Duplicati 2 0 4 21](https://user-images.githubusercontent.com/39164691/66258857-eff0f980-e75e-11e9-98df-8fc3ab1d0bb0.png)

Restore selection dialog for version 2.0.4.24 and later. File is displayed incorrectly and it is not restorable:
![Duplicati 2 0 4 26](https://user-images.githubusercontent.com/39164691/66258863-00a16f80-e75f-11e9-884f-8ef7f2e32660.png)

Error message if you attempt to restore:
![Duplicati restore error](https://user-images.githubusercontent.com/39164691/66258876-229af200-e75f-11e9-9fcd-f0db8d22f60f.PNG)

## Proposed Solution
Rolling back PR https://github.com/duplicati/duplicati/pull/3846 solves the problem.  This original developer never identified an actual problem that the PR solved, it just seemed like a logical fix.  Per the 3rd post on that PR:

> There doesn't appear to be any negative consequence to the bug

**Comment by warwickmm** [comment]
Thanks @drwtsn32x.  I noticed the strange display in the restore tree but didn't know what the cause was.  I think reverting the changes from #3846 is a good solution for now.

**Comment by drwtsn32x** [comment]
I can go ahead and submit a PR to roll back this change...thanks

**Comment by ts678** [comment]
Thanks for tracking this down. I bumped into it but didn't pause to see if bug was new or old.

[dblock put retry corrupts dindex, using old dblock name for index -- canary regression #3932](https://github.com/duplicati/duplicati/issues/3932)

> Backup two (to avoid a bug) tiny files

when writing up the steps to reproduce.
