### ISSUE TITLE
Support backup to raw full files instead of zip

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#394]
_From [spama...@ajserver.com](https://code.google.com/u/108815414316142964532/) on April 03, 2011 17:39:41_

Support backing up to actual files instead of zip'ed files, i.e. test.doc is send to the server is test.doc.  This may even have been in an earlier version as I would imagine it is a logical stepping stone to send data.

My problem is when my wife calls from the road or parents call because they accidentally deleted a file they have difficulty finding where to restore (not computer savvy at all).  I however have access to the server could go find it and email it back to them, simple easy administrator level access.  We currently are using DeltaCopy however I find Duplicati to be far superior in every way except that I cannot easy send people back their lost files as the server administrator.'

For issues of compression during transfer I use rsync args: --compress-level=9 and this does a great job.

Again I am only asking for an option to be able to write the actual files through to the server, obviously this would be limited to no encryption and perhaps only where it would be used in the case.

I would like to assist in the development of duplicati however I am not much of a programer, sysadmin and software tester is what I do professional.  I can also offer build boxes/hardware to some extent.  Please let me know how I can assist the project.

Thanks,
Aaron Johnson
aaron at same domain as my Google account

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=394_

**Comment by rkarlsba** [comment]
Duplicati should support non-compressed storage. Most of my data is compressed already, so having it go through gzip for just a .1% of compression is just waste.

How can I do this?

**Comment by mwtrigg** [comment]
Another potential reason: using Amazon Cloud Drive.  If I'm backing up picture files, they're all free (do not count against storage limits) when in their native format; however in their compressed format, there is a cost.

**Comment by phendryx** [comment]
:+1: I literally just bought the 100GB for $11.99/yr plan, knowing 95% of my backups are photos. My other backups would fit well under 100GB, but pictures, not so much. The wife loves her 90 slightly different pictures of an unfocused moon :-|.

**Comment by feutl** [comment]
I just do not understand why people would want files being stored 1:1 on the backup location, because there are so many tools out there doing exactly this, and duplicati is great because of being secure and using remote locations securely.

BUT what I really would love to see, and I back @rkarlsba is a way to run the backup without compression. I backup jpg, mpg and other already compressed stuff, my NAS is not happy about the additional compression layer without a usable result.

**Comment by kenkendk** [comment]
First, Duplicati has a list of non-compressible file extensions, and it includes .jpg:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/default_compressed_extensions.txt

Any file on the list will be stored without attempting compression.
You can use your own file (same format as the default one) and supply it with `--compression-extension-file`.

If you _really_ don't want compression, you can add `--zip-compression-method=store` or alternative `--zip-compression-level=0`.

**Comment by james-powis** [comment]
@kenkendk as mentioned by @phendryx the google drive billing $0 on unlimited photo storage makes it a very tempting solution for my wife's close to a terabyte of raw files she insists requires backup... I understand for a "under every other situation such a thing is stupid" but renaming the file, not zipping, and keeping the file extension seems like a very desirable functionality...

I have never touched C#, but damn I would be willing to try and help if I could solve this bloody backup problem the shutter bug has cause for me... 

So the question becomes, is this level of this functionality in a PR desired, or is such a bastardization of common sense going to be rejected with malice?

**Comment by james-powis** [comment]
Actually Looking at the Amazon Drive App it fully supports doing exactly what I need... Lets just call this a RTFM moment...

**Comment by suoko** [comment]
In case of OD4B, this sw is a  nice solution where official client is missing
If it syncs file by file instead of zipping, it would be much appreciated

**Comment by mr-mental** [comment]
Totally agree with you guys, a raw saving model would be great as hell!

**Comment by rkarlsba** [comment]
Well, this ticket is only just short of six years old, so give it another six years, someone might bother to implement it?

**Comment by drwtsn32x** [comment]
@rkarlsba - it will never happen.

The point of using Duplicati is to get you versioning, deduplication, flexible retention, etc.

If you want a synchronization tool use something like rclone - it is pretty amazing if sync is what you're looking for.

**Comment by rkarlsba** [comment]
I know other tools, that's not the point here. The point is that the forced zip compression of things like video files is just stupid, since they can't be compressed anyway.

**Comment by drwtsn32x** [comment]
@rkarlsba - the main reason the files are ZIP on the back end is because they've been chunked, deduplicated, and chunks repackaged into volumes.  Even if the ZIP compression were disabled, you'd still have chunks/volumes.  Duplicati is not a sync tool and will never back up files in native format on the back end.

**Comment by rkarlsba** [comment]
Normal files can also be chunked quite easily, it's just called read() and write() or even something like dd

**Comment by drwtsn32x** [comment]
The chunking is to facilitate deduplication. You can't have deduplication and still have files in native format.

**Comment by rkarlsba** [comment]
still, the point is, again, that chunking is very easy to do in the code, so there's no reason, really, to zip it

**Comment by kees-z** [comment]
In Duplicati, the default size of a chunk (block) is 100 KB. These blocks are packaged in a zip archive (only compressable file types are actually compressed) to reduce the number of files at the remote storage location. Without using archives containing quite a number of blocks, we would end up with tons of files in a single folder at the backend.

**Comment by drwtsn32x** [comment]
@rkarlsba not sure how else to explain this.... but Duplicati will never be a synchronization type program that keeps files in native format.  It is inherently incompatible with its core feature, deduplication.

**Comment by james-powis** [comment]
I don't even remember why I star'ed this... but that was a pretty solid F-You from @drwtsn32x ... I can say that Zipping the hell out of something is very different than deduplication... I know uncompressed output is a very real use case for a lot of my use cases at all of my last employers going back a decade...

**Comment by drwtsn32x** [comment]
@james-powis I certainly didn't mean to come across that way and apologies to @rkarlsba  if that is how it sounded.

Was just trying to emphasize that Duplicati is not a sync tool and will never put files in native format on the back end.

**Comment by drwtsn32x** [comment]
If Duplicati didn't zip at all then all the raw chunks would be on the back end. @kees-z did a nice job explaining.
