### ISSUE TITLE
GCS Storage Provider URL example is incorrect.

### ISSUE THREAD

**Issue by scusack** [duplicati/duplicati#3941]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.23_beta_2019-07-14
- **Operating system**: Ubuntu 18.04
- **Backend**: Google Cloud Storage

## Description
Storage Provider URL example is incorrect.

Example googlecloudstore://bucket/folder should be gcs://bucket/folder

## Steps to reproduce
Duplicati.CommandLine.exe help gcs

- **Actual result**:

`Google Cloud Storage (gcs):
 This backend can read and write data to Google Cloud Storage. Supported format is "googlecloudstore://bucket/folder".
 Supported options:
`

- **Expected result**:

`Google Cloud Storage (gcs):
 This backend can read and write data to Google Cloud Storage. Supported format is "gcs://bucket/folder".
 Supported options:
`

**Comment by warwickmm** [comment]
Thanks @scusack.  This should be fixed in the next release.

**Comment by warwickmm** [comment]
Fixed in pull request #3942.
