### ISSUE TITLE
How do I use --ignore-filenames to specify multiple filenames?

### ISSUE THREAD

**Issue by musq** [duplicati/duplicati#3947]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.5_beta_2018-11-28
- **Operating system**: Linux (Ubuntu 16.04)
- **Backend**: Local directory

## Description

I'm trying to use multiple marker files which will help duplicati ignore that folder. How do I specify that in the command? What is the separator?

e.g. I tried using `,`, but it does not work.
`duplicati-cli test-filters /root/ --ignore-filenames=".nobackup,pip-selfcheck.json"`

**Comment by sfahrenholz** [comment]
Hey @musq ,
as separator the System.separator is used (see https://github.com/duplicati/duplicati/blob/5e39cd06f548f9f8a408ce2d794e35600f9ded85/Duplicati/Library/Main/Options.cs#L1524). In Windows is the Path.PathSeparator the semicolon (;).

**Comment by musq** [comment]
Unfortunately, `;` does not work in Linux.

**Comment by sfahrenholz** [comment]
Please try the colon/double point on the linux system ([Path.PathSeparator: ':'](https://docs.microsoft.com/de-de/dotnet/api/system.io.path.directoryseparatorchar?view=netframework-4.8 ))

**Comment by musq** [comment]
Yes, `:` works on Linux. Thanks!
