### ISSUE TITLE
Duplicati does not support Mono 6.4.0.198

### ISSUE THREAD

**Issue by fwh-dc** [duplicati/duplicati#3964]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.23
- **Operating system**: osx 10.14.6

## Description

Duplicati does not start. It seems like the latest version of mono through brew is unsupported by Duplicati. Would it be possible for you to note the latest version of mono that Duplicati supports? Your website mentions versions later than but not before.

All problems I have experienced have been related to unsupported mono versions after a ```brew upgrade```.

## Steps to reproduce

After updating to mono v. 6.4.0.198 Duplicati is unable to start.
After downgrading to mono v. 6.0.0.334 Duplicati is able to start.

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by warwickmm** [comment]
Are there any useful error messages?  There is evidence that some users were able to use mono 6.4.0.198:

https://forum.duplicati.com/t/a-serious-error-occurred-in-duplicati-2-0-4-23-1/8243/10

**Comment by fwh-dc** [comment]
I got a macOS window saying _The application “Duplicati.app” can’t be opened_ and through a Google search I found the newly resolved #3572 which suggested that 6.0.0.334 was working for them. So I did a downgrade and everything is working fine.

The thread you have listed mentions a Ubuntu install. Perhabs there is different behaviour on different platforms?

**Comment by warwickmm** [comment]
Yes, that's definitely possible.  Let's leave this issue open and see if other Mac users encounter the same problem.  There was a [post](https://github.com/duplicati/duplicati/issues/3572#issuecomment-452909248) that suggested installing mono from [here](https://www.mono-project.com/download/vs/#download-mac) may help.  Is that something you'd be willing to try?

**Comment by fwh-dc** [comment]
Did a ```brew uninstall mono``` and installed mono v. 6.4.0.198 from the source you suggested (mono-project.com). Did a reboot and **Duplicati was able to run**.
Then I uninstalled that version by running the commands they suggested on their website
```
sudo rm -rf /Library/Frameworks/Mono.framework
sudo pkgutil --forget com.xamarin.mono-MDK.pkg
sudo rm /etc/paths.d/mono-commands
```
And then I installed mono v. 6.4.0.198 via brew once more did a reboot and confirmed it was **not working** anymore.

So something in the brew install fails. I will go back to mono v. 6.0.0.334 via brew and pin that version.

I don't know if it is anything you can fix or if it should be fixed via brew.

**Comment by ts678** [comment]
FWIW 2.0.4.23 starts fine here on Linux Mint 18.1 after upgrading mono to mono-project's latest:

~~~
Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:20:30 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
~~~

If you ever see it not starting again, you can also try some other Duplicati commands such as [these](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/).

**Comment by warwickmm** [comment]
I think this indicates that there's an issue with the brew package of mono.  If you don't mind, I'm going to close this issue since it works with the version of mono from the official source.  Feel free to reopen this if you think there's some action that can be taken from our end.
