### ISSUE TITLE
Duplicati fails to install on Fedora 31

### ISSUE THREAD

**Issue by Tobi823** [duplicati/duplicati#3974]
- [x] I have searched open and closed issues for duplicates.
(This issue may be a duplicate of https://github.com/duplicati/duplicati/issues/3950 but I'm not sure)
----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.32_canary and 2.0.4.23_beta
- **Operating system**: Fedora 31, 5.3.7-301.fc31.x86_64
- **Backend**: local

## Description
Duplicati can't be installed on Fedora 31. When I try to install it with dnf, dnf fails due to a missing dependency `mono(appindicator-sharp)` although I've installed mono-complete.

```
$sudo dnf install --allowerasing duplicati-2.0.4.32-2.0.4.32_canary_20191024.noarch.rpm
Letzte Prüfung auf abgelaufene Metadaten: vor 0:12:52 am Do 31 Okt 2019 13:35:50 CET.
Fehler: 
 Problem: conflicting requests
  - nothing provides mono(appindicator-sharp) needed by duplicati-2.0.4.32-2.0.4.32_canary_20191024.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```
Before I upgraded my Fedora 30 to Fedora 31, the system warned me that Duplicati is not compatible with Fedora 31.

## Workarounds 
 - download the zip-file, extract it and start the server with `mono Duplicati.Server.exe`
 - or skip dependencies with `sudo rpm -ivh duplicati-2.0.4.23-2.0.4.23_beta_20190714.noarch.rpm --nodeps` (mentioned in https://github.com/duplicati/duplicati/issues/3950)

## Steps to reproduce
1. Install Fedora 31
2. Try to install Duplicati

- **Actual result**:
Duplicati could not be installed.
- **Expected result**:
Duplicati should be installed.

**Comment by ts678** [comment]
Any idea why your system can't find below? Maybe it's the name difference (with or without `lib` prefix)?

[RPM resource libappindicator-sharp(x86-64)](https://rpmfind.net/linux/rpm2html/search.php?query=libappindicator-sharp(x86-64)) shows [libappindicator-sharp-12.10.0-25.fc31 RPM for x86_64](https://rpmfind.net/linux/RPM/fedora/31/x86_64/l/libappindicator-sharp-12.10.0-25.fc31.x86_64.html)

> From Fedora 31 for x86_64

```
A library to allow applications to export a menu into the Unity Menu bar. Based
on KSNI it also works in KDE and will fallback to generic Systray support if
none of those are available.

This package contains the Mono C# bindings for this library.
```

[libappindicator-sharp-12.10.0-12.el7 RPM for x86_64](https://rpmfind.net/linux/RPM/epel/7/x86_64/Packages/l/libappindicator-sharp-12.10.0-12.el7.x86_64.html) also has an interesting comment

```
Changelog

* Tue Feb 20 2018 Tomas Popela <tpopela@redhat.com> - 12.10.0-12
  - This package was separated from libappindicator when the libappindicator
    was moved to RHEL 7.
```

> I've installed mono-complete.

> nothing provides mono(appindicator-sharp)

[Interpreters and Shells](https://rpm.org/user_doc/more_dependencies.html)
> To prevent module name collisions between interpreters, module names are enclosed within parentheses and a conventional interpreter specific identifier is prepended

which I take to mean that installing mono might not be enough -- you need a module for mono to run, and from above it sounds like it then interfaces to an additional required component -- libappindicator.

**Comment by Stupendoussteve** [comment]
> Any idea why your system can't find below? Maybe it's the name difference (with or without `lib` prefix)?
> 
> [RPM resource libappindicator-sharp(x86-64)](https://rpmfind.net/linux/rpm2html/search.php?query=libappindicator-sharp(x86-64)) shows [libappindicator-sharp-12.10.0-25.fc31 RPM for x86_64](https://rpmfind.net/linux/RPM/fedora/31/x86_64/l/libappindicator-sharp-12.10.0-25.fc31.x86_64.html)
> 
The resource is not libappindicator-sharp(x86-64), it is [mono(appindicator-sharp)](https://rpmfind.net/linux/rpm2html/search.php?query=mono%28appindicator-sharp%29&submit=Search+...&system=&arch=). The [Fedora 30](https://koji.fedoraproject.org/koji/rpminfo?rpmID=16443821) version of this package provides this, [Fedora 31](https://koji.fedoraproject.org/koji/rpminfo?rpmID=18317945) does not.

**Comment by Stupendoussteve** [comment]
I was able to install after using rpmrebuild to add the proper Provides and Requires lines to libappindicator-sharp, the one shipped in Fedora 31 also does not pull in its own mono dependencies like it should.

**Comment by warwickmm** [comment]
This appears to be a Red Hat packaging issue:

https://bugzilla.redhat.com/show_bug.cgi?id=1768157
