### ISSUE TITLE
Duplicati Backup continuing? after backup is paused in the UI

### ISSUE THREAD

**Issue by ThoenigAdrian** [duplicati/duplicati#3981]
- [x] I have searched open and closed issues for duplicates.
#418 seems similar but since i chose a chunk size of 50 MB it should stop uploading after ~1minute , but i observed it for more than 30 minutes and it's still continuing to upload data

After some additional digging in the web, I found two forum posts talking about this:
https://forum.duplicati.com/t/pause-does-not-really-pause/4798/6
and 
https://forum.duplicati.com/t/pause-is-not-pausing/5543/5?u=ts678

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.33
- **Operating system**: Windows 10 1809 17763.805
- **Backend**: Google Drive 

## Description
Duplicati continues to upload Data to the Backend even though the process should be paused
![image](https://user-images.githubusercontent.com/16619270/68535595-e1d95e80-0344-11ea-8440-198d798f3d33.png)
![image](https://user-images.githubusercontent.com/16619270/68535904-0126ba80-034a-11ea-80a4-abbba93bff6f.png)

![image](https://user-images.githubusercontent.com/16619270/68535624-6af09580-0345-11ea-98aa-37b9d4065a50.png)

In the [documentation](https://duplicati.readthedocs.io/en/stable/03-using-the-graphical-user-interface/) it says:
![](https://duplicati.readthedocs.io/en/stable/ss_guicomponents_03.png)
With the Pause button you can temporarily stop Duplicati uploading and downloading any file from and to the backend. With the Throttle button you can limit the bandwidth Duplicati uses by specifying a maximum upload and download speed.

## Steps to reproduce

1. Start a backup process 
2. Pause it 
3. Open task manager to see Duplicati is still uploading
4. Also in the Duplicati WEB UI you can observe the remaining data size to go down.

- **Actual result**:
After hitting the pause button the background process keeps uploading data and reading from my hard disk. 
Which can be verified in 4 different ways:
1. Task Manager
2. Google Drive (when looking at recently added files) 
3. In the Duplicati UI itself (one can see remaining data descreasing)
4. In the Live Log Viewer , many entries are still generated about uploading files
This means i can't safely remove my hard drive.
- **Expected result**:
After hitting the Pause Button I'd expect Duplicati to stop the upload/backup process and give back all the FileHandles it has on the File Source (in my case an external hard drive), so I'm able to disconnect the drive and restart the backup process another time.

## Debug log
LEVEL = verbose

    9. Nov. 2019 23:24: Backend event: Put - Started: duplicati-b9b25346695994360a6e57781e6eb8b0b.dblock.zip.aes (49,99 MB)
    9. Nov. 2019 23:24: Backend event: Put - Completed: duplicati-i42a7a2f3a925428583ceaa05a1dcf2c2.dindex.zip.aes (17,97 KB)
    9. Nov. 2019 23:24: Backend event: Put - Started: duplicati-i42a7a2f3a925428583ceaa05a1dcf2c2.dindex.zip.aes (17,97 KB)
    9. Nov. 2019 23:24: Backend event: Put - Completed: duplicati-b3a7640748e944f75ad61a9c39271586a.dblock.zip.aes (49,99 MB)

Also no Log Entry is created when i click Play or Pause in the UI. 

An additonal thing i noticed is that i don't have a tray icon anymore - not sure if this is related.

**Comment by warwickmm** [comment]
Yes, this is a known issue.  I'm going to close this in favor of the existing issues, #1088 and #3565.
