### ISSUE TITLE
Backup Job connects to SMB using wrong credentials

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#3986]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.34_canary_2019-11-05
- **Operating system**: Windows Server 2019
- **Backend**: SMB share on LAN server that also runs Windows Server 2019

## Description
While configuring a backup job with an SMB destination, clicking "Test connection" succeeds even though it should have failed since I specified a non-existent user account on that screen.  Further, the backup job even runs and completes successfully even though it should have no access to that SMB share.  Duplicati should give a warning or error to the user when the specified account fails to connect, but instead, it silently falls back to trying the local "SYSTEM" account, which in this case, does have permission to access that SMB share.

## Steps to reproduce
1. Create an SMB share on computer1.  Give full control (Share and NTFS permissions) to the computer account named computer2 but make sure there are no other Share Permissions allowed on the share.
2. Create a Duplicati backup job on computer2 using that SMB destination on computer1.
3. While specifying the "Username" and "Password" fields on the "Backup destination" screen, type a random fake username and password, and click "Test Connection".  You'll see that it succeeds.
4. Proceed with that fake username and save the new backup job.
5. Run the backup job.  You'll see that it successfully runs the backup and writes files to the SMB share.

- **Actual result**:
Duplicati automatically and silently tries to connect to the SMB share using the local SYSTEM account without telling the user that anything is wrong with their specified user credentials.
- **Expected result**:
Duplicati should detect that the specified user account is not authorized on the SMB share, and Duplicati should stop the backup job and send a warning or error to the administrator.  It should not automatically attempt the local SYSTEM account or any other account.

Thank you for your great work with this program!

**Comment by Germs2004** [comment]
This might be even worse.  I removed all computer accounts and user accounts from the SMB share permissions except one user account, and I still specified a fake username in Duplicati, and it still passes the "Test connection".  Maybe it's somehow caching previously attempted credentials or something weird on that screen.  I watched the EventLog on my destination computer, and I didn't see any Audit Success or Audit Failures when I clicked the Test Connection button, so maybe Duplicati isn't actually even trying to connect when it says it is.

Let me know if I can help.  It seems confusing.

**Comment by warwickmm** [comment]
[This comment](https://forum.duplicati.com/t/feedback-from-a-new-user-mainly-windows-use/4399/28) sounds related.

Does the `--force-smb-authentication` option do anything?

**Comment by Germs2004** [comment]
> [This comment](https://forum.duplicati.com/t/feedback-from-a-new-user-mainly-windows-use/4399/28) sounds related.
> 
> Does the `--force-smb-authentication` option do anything?

You're a great help!  That comment sounds like the same problem I have, and your recommendation appears to have solved the problem.  On the Destination settings screen, under Advanced Options, if I add Force-SMB-Authentication and then click "Test Connection", it fails the test whenever I give a fake username, which is the correct behavior.

Thank you!
