### ISSUE TITLE
Remove Google+ link from the UI

### ISSUE THREAD

**Issue by bjherbison** [duplicati/duplicati#3988]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.23_beta_2019-07-14
- **Operating system**: Ubuntu
- **Backend**: local (irrelevant)

## Description

At the bottom of http://localhost:8200/ngax/index.html#/ (and many other pages) there is a link to Google+. Following the link and logging in will just tell you G+ has been shut down for not corporate use.

## Steps to reproduce

1. Visit http://localhost:8200/ngax/index.html#/
2. Click the G+ image.
3. Log in.
4. Be annoyed.

- **Actual result**:
Follow the link and be disappointed.
- **Expected result**:
No Google+ link.

## Screenshots

![Screenshot_2019-11-13 willoughby - Duplicati](https://user-images.githubusercontent.com/4101902/68769135-d199db80-05f1-11ea-9255-20d33148a7f7.png)

**Comment by Germs2004** [comment]
I have version 2.0.4.34_canary_2019-11-05 and it appears that this has been fixed.
![image](https://user-images.githubusercontent.com/5519340/68778882-c51d7f00-0601-11ea-98e0-555fd03203de.png)

**Comment by warwickmm** [comment]
This was fixed in 2.0.4.19 and will show up in the next beta.
