### ISSUE TITLE
Duplicati.CommandLine.RecoveryTool.exe crashes (and didn't restore files)

### ISSUE THREAD

**Issue by dolorosus** [duplicati/duplicati#3994]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.34_canary_2019-11-05
- **Operating system**: Win10x64 18363.476
- **Backend**: Replace me

## Description

Duplicati.CommandLine.RecoveryTool.exe doesn't work as expected
```DOSBATCH
c:\Program Files\Duplicati 2>Duplicati.CommandLine.RecoveryTool.exe restore e:\testbck2
Sorting index file ... done!
Program crashed:
System.InvalidOperationException: Die Sequenz enthält keine Elemente.
   bei System.Linq.Enumerable.First[TSource](IEnumerable1 source)
   bei Duplicati.CommandLine.RecoveryTool.Restore.Run(List1 args, Dictionary2 options, IFilter filter)
   bei Duplicati.CommandLine.RecoveryTool.Program.RealMain(String[] _args)
```
OR

```DOSBATCH
c:\Program Files\Duplicati 2>Duplicati.CommandLine.RecoveryTool.exe restore e:\testbck2 0  --targetpath="e:\rest"
Sorting index file ... done!
Valid range for version is 0 to -1
c:\Program Files\Duplicati 2>
```

## Steps to reproduce

Trying desaster recovery.
1. deleted the database
2. deleted the "*.dlist.zip.aes"  and two of the ".dblock.zip.aes" files from the backup.
3. Backup has been downloaded and decrypted
4. index has been created
```DOSBATCH
Duplicati.CommandLine.RecoveryTool.exe index e:\testbck2
Processing 205 files
0: E:\testbck2\duplicati-b00789276f23f449fb7555fdefc6ef7c2.dblock.zip 105 hashes found, sorting ... done!
Merging 105 hashes ... done!
1: E:\testbck2\duplicati-b01a89aa0b301406b9e58a44d2f82e7f5.dblock.zip 165 hashes found, sorting ... done!
`Merging 270 hashes ... done!
....
`Merging 26348 hashes ... done!
204: E:\testbck2\index.txt - Not a Duplicati file, ignoring
Processed 204 files and found 26348 hashes
```

5. Trying to restore to original location:
```DOSBATCH
c:\Program Files\Duplicati 2>Duplicati.CommandLine.RecoveryTool.exe restore e:\testbck2
Sorting index file ... done!
Program crashed:
System.InvalidOperationException: Die Sequenz enthält keine Elemente.
   bei System.Linq.Enumerable.First[TSource](IEnumerable1 source)
   bei Duplicati.CommandLine.RecoveryTool.Restore.Run(List1 args, Dictionary2 options, IFilter filter)
   bei Duplicati.CommandLine.RecoveryTool.Program.RealMain(String[] _args)
```
6. Trying to restore an explicit version:
```DOSBATCH
c:\Program Files\Duplicati 2>Duplicati.CommandLine.RecoveryTool.exe restore e:\testbck2 0  --targetpath="e:\rest"
Sorting index file ... done!
Valid range for version is 0 to -1
c:\Program Files\Duplicati 2>
```

- **Actual result**: Nothing was restored

- **Expected result**: Restore of the remaing files without crash

**Comment by drwtsn32x** [comment]
Just curious about your process here.  I can see deleting the database to test disaster recovery, but why are you deleting some dblocks? That will certainly results in some files being unrestorable.  Are you just trying to simulate some of the back end files being damaged or lost?

**Comment by dolorosus** [comment]
Because I've read the duplicati documentation?
https://duplicati.readthedocs.io/en/latest/08-disaster-recovery/

This is the scenario described in the documentation.

**Comment by drwtsn32x** [comment]
> Because I've read the duplicati documentation?

lmao...thanks! I have never seen that page before.

**Comment by ts678** [comment]
Documentation explains

> There is one .dlist file for each backup version.

so

> deleted the "*.dlist.zip.aes"

means all information about the source files is gone. Can you restore a version if you leave a version?

> Valid range for version is 0 to -1

is telling you that there are none. Ordinarily, I think this follows the usual convention that 0 is newest.

**Comment by dolorosus** [comment]
I've been trying to determine how robust duplicati backups are. Since there is a chapter "Disaster Recovery" in the manual, I tried to find out what happens with missing or damaged archives.

Since archive corruption occurs more often than expected when saving online, I was curious how duplicati handles it, especially since there is a chapter in the documentation for this case.
Erroneous or missing data archives are handled well, but if missing and/or corrupt *.dlist.zip.aes archive means the total loss of the backup, that's an important fact for my evaluation.  

Furthermore, even in such cases, the program should not simply crash or display incomprehensible error messages. Unfortunately my C# knowledge is insufficient to create a pullrequest.

Since it was only an evaluation, the loss of the backup is no problem. Thanks for the fast and competent handling of this problem.

**Comment by ts678** [comment]
> Thanks for the fast and competent handling of this issue.

Well, I hope I got it. If you can break it without deleting all the files, then it would get more attention.
If it only happens in an extreme situation with all versions lost, then there are probably bigger bugs...

> if missing and/or corrupt *.dlist.zip.aes archive means the total loss of the backup

As a side note, lost dlist and dindex files can be regenerated from the database (if it exists) by Repair. Simultaneously losing the remote records and the DB cache is too much. I doubt anything handles it.

> Since archive corruption occurs more often than expected when saving online

This is what the [test command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-test-command) and [--upload-verification-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#upload-verification-file) and [How to verify duplicati-verification.json?](https://forum.duplicati.com/t/how-to-verify-duplicati-verification-json/7413) (if you have direct backend access) can help with. I thought there was also a file-list sanity check always...

**Comment by dolorosus** [comment]
> As a side note, lost dlist and dindex files can be regenerated from the database (if it exists) by Repair.

Good to know, this is an important Information.

> This is what the test command and --upload-verification-file and How to verify duplicati-verification.json? 

That can't be mentioned enough: A backup without verify is not a backup!

To tell you the truth: I think my test has overshoot the mark a little.
So many problems at the same time are rather unlikely. I found Duplicati to be extremely robust compared to other backup solutions. 
There is not only a tool to recover damaged backups, it is also well documented. A special credit for that.
