### ISSUE TITLE
SMTP password through environment variable?

### ISSUE THREAD

**Issue by fwiep** [duplicati/duplicati#4000]
- [x] I have searched open and closed issues for duplicates.
----------------------------------------
## Environment info
- **Duplicati version**: 2.0.4.34_canary_2019-11-05
- **Operating system**: Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
- **Back-end**: SFTP
- **Usage**: shell script using `duplicati-cli backup`

## Description
At this moment the SMTP password has to be specified in plain text at the command line. Using the SMTP notification options, I would like pass the authentication password through an environment variable; just like the Back-end `AUTH_PASSWORD` and `PASSPHRASE` variables. 

## Steps to reproduce
1. Add relevant SMTP settings to the command:
    --send-mail-to="my-mailbox@example.com"
    --send-mail-from="my-sender@example.com"
    --send-mail-url="smtps://smtp.example.com:465/?starttls=always"
    --send-mail-username="my-sender@example.com"
    --send-mail-password="My$uper$ecr3tP@ssw0rD"
2. Run the `backup` command
3. Receive the email containing the job's result.

- **Actual result**:
While executing the command, the commandline arguments (and thus the SMTP password) are visible for any user in the system's process list.
- **Expected result**:
The password should not have to be visible this way. It could be hidden, perhaps using environment variables, as has been done with `AUTH_PASSWORD` and `PASSPHRASE`.

## Note
Thank you very much for this wonderful software!

**Comment by drwtsn32x** [comment]
Environment variable values for a process are viewable by users with administrative (Windows) or root (Linux) permissions, maybe by non-privileged users too (not sure - need to confirm).  So maybe it's not all that more secure than specifying on the command line directly.

Are you only using Duplicati.CommandLine.exe to do your backups?  I'm guessing you have a good reason of using that instead of defining jobs in the Duplicati UI and running them from there.  Backup jobs configured this way store all info in the Duplicati-server.sqlite database and none of the values are visible on command line or in environment variables.

**Comment by fwiep** [comment]
Thank you for the fast response. I didn't know about the environment visibility using root-privileges.

My only reason for using the commandline is the feeling I then have more control about what goes on. I can debug and make edits easier than when using the UI. I am visually impaired and I like my text-editor more than a graphical interface - but that's just me.

Are you saying there is a way to safely store an unencrypted SSH private key, or a passphrase to an encrypted one? And a backup-password as well as an SMTP authentication password? All in the same Duplicati SQLite database? How can this be done?

Thanks!

**Comment by drwtsn32x** [comment]
Yes all those values are stored in the Duplicati-server.sqlite database if you are using the UI to define jobs.  But - especially on Linux - anyone who got a hold of this database could open it and read the values.  Duplicati on Linux doesn't support sqlite encryption.  So if you decide to go this route, make sure the file is only readable/writable by root or the user Duplicati service runs as.

**Comment by drwtsn32x** [comment]
I was thinking another option (if you still prefer command line) is to use the [parameters-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#parameters-file) option, and store your sensitive information there.  This file can be protected by using standard Linux file mode permissions.

**Comment by fwiep** [comment]
Yes, the `--parameters-file` argument would be an option - no pun intended.

As I see it, it would be choosing the lesser evil of protecting one file (the parameter file) over protecting another (database file). I guess there is no absolute security for scripted use of sensitive information. But we can try to minimize the risk, can't we? :)

I consider my question answered, issue solved.
Thanks!
