### ISSUE TITLE
DeleteRemoteFileFailed due to FileNotFound

### ISSUE THREAD

**Issue by chris-y** [duplicati/duplicati#4006]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.34_canary_2019-11-05
- **Operating system**: Raspbian Buster
- **Backend**: B2 Cloud

## Description

Occasionally Duplicati tries to delete a file it must have thought it created in the same session, but it can't find it.

```
2019-12-03 01:07:17 +00 - [Warning-Duplicati.Library.Main.BackendManager-DeleteRemoteFileFailed]: Delete operation failed for duplicati-20191203T010001Z.dlist.zip.aes with FileNotFound, listing contents
```

**Comment by drwtsn32x** [comment]
Hello, this issue was fixed in PR https://github.com/duplicati/duplicati/pull/3993 and is available in Canary 2.0.4.35.  Please upgrade as it should solve your issue.

**Comment by chris-y** [comment]
That isn't being offered as an update when I check for a new version for some reason...

**Comment by chris-y** [comment]
I'm confident when I do manage to update it that this will fix my issue, so closing.
