### ISSUE TITLE
“Invalid Class” Error when creating a new backup: Log Error: Request for http://localhost:8200/api/v1/hyperv gave error

### ISSUE THREAD

**Issue by gg48gg** [duplicati/duplicati#4008]
screenshot of error
https://i.imgur.com/fDEmkU9.png
screenshot of log
https://i.imgur.com/AEpApDF.png

About -> System Properties info:
APIVersion : 1
PasswordPlaceholder : **********
ServerVersion : 2.0.4.23
ServerVersionName : - 2.0.4.23_beta_2019-07-14
ServerVersionType : Beta
StartedBy : Tray icon
BaseVersionName : 2.0.4.23_beta_2019-07-14
DefaultUpdateChannel : Beta
DefaultUsageReportLevel : Information
ServerTime : 2019-12-05T23:07:28.605908-07:00
OSType : Windows
DirectorySeparator :
PathSeparator : ;
CaseSensitiveFilesystem : false
MonoVersion :
MachineName : x
UserName : x
NewLine :
CLRVersion : 4.0.30319.42000
CLROSInfo : {“Platform”:“Win32NT”,“ServicePack”:"",“Version”:“10.0.17134.0”,“VersionString”:“Microsoft Windows NT 10.0.17134.0”}
ServerModules : 
UsingAlternateUpdateURLs : false
LogLevels : [“ExplicitOnly”,“Profiling”,“Verbose”,“Retry”,“Information”,“DryRun”,“Warning”,“Error”]
SuppressDonationMessages : false

ommitted for privacy

BrowserLocale : {"Code":"en-US","EnglishName":"English (United States)","DisplayName":"English (United States)"}
SupportedLocales : [{"Code":"bn","EnglishName":"Bangla","DisplayName":"বাংলা"},{"Code":"ca","EnglishName":"Catalan","DisplayName":"català"},{"Code":"cs","EnglishName":"Czech","DisplayName":"čeština"},{"Code":"da","EnglishName":"Danish","DisplayName":"dansk"},{"Code":"de","EnglishName":"German","DisplayName":"Deutsch"},{"Code":"en","EnglishName":"English","DisplayName":"English"},{"Code":"es","EnglishName":"Spanish","DisplayName":"español"},{"Code":"fi","EnglishName":"Finnish","DisplayName":"suomi"},{"Code":"fr","EnglishName":"French","DisplayName":"français"},{"Code":"hu","EnglishName":"Hungarian","DisplayName":"magyar"},{"Code":"it","EnglishName":"Italian","DisplayName":"italiano"},{"Code":"ja-JP","EnglishName":"Japanese (Japan)","DisplayName":"日本語 (日本)"},{"Code":"ko","EnglishName":"Korean","DisplayName":"한국어"},{"Code":"lt","EnglishName":"Lithuanian","DisplayName":"lietuvių"},{"Code":"lv","EnglishName":"Latvian","DisplayName":"latviešu"},{"Code":"nl-NL","EnglishName":"Dutch (Netherlands)","DisplayName":"Nederlands (Nederland)"},{"Code":"pl","EnglishName":"Polish","DisplayName":"polski"},{"Code":"pt","EnglishName":"Portuguese","DisplayName":"português"},{"Code":"pt-BR","EnglishName":"Portuguese (Brazil)","DisplayName":"português (Brasil)"},{"Code":"ro","EnglishName":"Romanian","DisplayName":"română"},{"Code":"ru","EnglishName":"Russian","DisplayName":"русский"},{"Code":"sk","EnglishName":"Slovak","DisplayName":"slovenčina"},{"Code":"sk-SK","EnglishName":"Slovak (Slovakia)","DisplayName":"slovenčina (Slovensko)"},{"Code":"sr-RS","EnglishName":"Unknown Locale (sr-RS)","DisplayName":"Unknown Locale (sr-RS)"},{"Code":"sv-SE","EnglishName":"Swedish (Sweden)","DisplayName":"svenska (Sverige)"},{"Code":"th","EnglishName":"Thai","DisplayName":"ไทย"},{"Code":"zh-CN","EnglishName":"Chinese (Simplified, China)","DisplayName":"中文(中国)"},{"Code":"zh-HK","EnglishName":"Chinese (Traditional, Hong Kong SAR)","DisplayName":"中文(香港特別行政區)"},{"Code":"zh-TW","EnglishName":"Chinese (Traditional, Taiwan)","DisplayName":"中文(台灣)"}]
BrowserLocaleSupported : true
backendgroups : {"std":{"ftp":null,"ssh":null,"webdav":null,"openstack":"OpenStack Object Storage / Swift","s3":"S3 Compatible","aftp":"FTP (Alternative)"},"local":{"file":null},"prop":{"s3":null,"azure":null,"googledrive":null,"onedrive":null,"onedrivev2":null,"sharepoint":null,"msgroup":null,"cloudfiles":null,"gcs":null,"openstack":null,"hubic":null,"amzcd":null,"b2":null,"mega":null,"box":null,"od4b":null,"mssp":null,"dropbox":null,"sia":null,"jottacloud":null,"rclone":null}}
GroupTypes : ["Local storage","Standard protocols","Proprietary","Others"]
Backend modules: aftp amzcd azure b2 box cloudfiles dropbox file ftp googledrive gcs hubic jottacloud mega msgroup onedrive onedrivev2 sharepoint openstack rclone s3 od4b mssp sia ssh tahoe webdav
Compression modules: zip 7z
Encryption modules: aes gpg
Server state properties
lastEventId : 88
lastDataUpdateId : 4
lastNotificationUpdateId : 0
estimatedPauseEnd : 0001-01-01T00:00:00
activeTask :
programState : Running
lastErrorMessage :
connectionState : connected
xsfrerror : false
connectionAttemptTimer : 0
failedConnectionAttempts : 0
lastPgEvent :
updaterState : Waiting
updatedVersion :
updateReady : false
updateDownloadProgress : 0
proposedSchedule : []
schedulerQueueIds : []
pauseTimeRemain : 0

**Comment by gg48gg** [comment]
I think this may be a related to:
https://github.com/duplicati/duplicati/pull/3301

**Comment by ts678** [comment]
I can create a new backup without this error. Is issue still of interest and present on a current release? Any exact steps to get it?
