### ISSUE TITLE
mega.nz-jobs not working anymore

### ISSUE THREAD

**Issue by bense** [duplicati/duplicati#4011]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.34
- **Operating system**: Synology DSM 6.2.2-24922 Update 4
- **Backend**: mega.nz

## Description

Since a few days (or even longer), my mega.nz-jobs stopped working correctly. I see "Verifying backend data ... " forever. I have 2 mega.nz-jobs and the problem exists on both of them. All other jobs (e.g. Google Drive) are working as expected. After manually stop and restart them, "Database is locked" is shown. When restarting the whole Duplicati-server, starting the job is possible again, but the problem persists.

Other jobs are not starting while this job is still running. So I need to manually check Duplicati-GUI to see if there is a problem, otherwise, my whole backup-solution would stop working.

## Steps to reproduce

1. Start mega.nz-job
2. Wait for message "Verifying backend data ... " to appear

- **Actual result**:
"Verifying backend data ... " is shown forever
- **Expected result**:
Job terminates normally

## Debug log

Nothing happens after clicking "Create bug report". And in the logs, the last entries I can see are from the last successful backup on 25th of november.

**Comment by warwickmm** [comment]
I don't have any issues with Mega.nz.  Can you try again to see if it was a temporary issue with Mega?

**Comment by bense** [comment]
I tried again all my mega.nz-jobs. Still not working. All my other jobs work fine.

I will try again with a "fresh" mega.nz-account later this week...

**Comment by bense** [comment]
Still the same, even with a new job, a fresh mega.nz-account (free one) and the latest canary (2.0.4.37).

@warwickmm are you also on a synology NAS?

Anyone else on a synology NAS having mega.nz-jobs?

**Comment by warwickmm** [comment]
I'm not using synology.  Do you know what version of mono you're using?

**Comment by bense** [comment]
.Net Version: 4.0.30319.42000
Mono: True (4.6.2) (4.6.2 (Stable 4.6.2.16/ac9e222 Fri Oct 27 17:00:56 CST 2017))

**Comment by warwickmm** [comment]
It's possible the version of mono is out of date.  I believe the minimum required version by Duplicati is technically 5.0.0.

**Comment by bense** [comment]
Good hint! I installed Mono-package from SynoCommunity (v5.18.0.240-12) and now the jobs seem to work just fine.

Thanks for your help!
