### ISSUE TITLE
Bug in UI when restoring on a new pc

### ISSUE THREAD

**Issue by mediedata** [duplicati/duplicati#4029]
Bug in web-UI

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.4.37_canary_2019-12-12
- **Operating system**: Win 10 pro
- **Backend**: B2

## Description

Doing a "Direct restore from backup files" on another pc (a clean installed pc with Win 10 pro and 2.0.4.37_canary_2019-12-12). It skips the tab-page with Selects Files and also Restore Options.

## Steps to reproduce
1. Install 2.0.4.37_canary_2019-12-12 on a clean pc.
2. Do a restore; Fill in Backup location; Enter encryption. Hit "Connect".
3. Problem is: Connect. It should be "Continue".

**Comment by drwtsn32x** [comment]
When I click Connect, it does some processing then takes me to the "Select Files" page.

What happens exactly when you click Connect?

**Comment by warwickmm** [comment]
I also cannot reproduce this.  After clicking Connect, I am taken to the "Select files" page.

If you have a large backup with many versions, it can take a long time for the file listing to appear, as it does have to download many files to populate the listing.

**Comment by mediedata** [comment]
Closing the issue. It disappeared after clearing the browser-cache.
