### ISSUE TITLE
Ability to set scheduled time should be on by default

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#403]
_From [leo.ze...@gmail.com](https://code.google.com/u/100699985538181979113/) on April 18, 2011 09:08:39_

What steps will reproduce the problem? 1. Create a new Shedule and run the backup
2. Try to change the date resp. time with 'Edit existing ...'
3. Only summary page appears with the date/time. I am unable to change them.
4. Stopped Duplicati and run the Wizard once more, but result is the same :( What version of the product are you using? On what operating system? 1.2b; Windows 7 What backend (destination) are you using? FTP

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=403_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
