### ISSUE TITLE
upload size too low

### ISSUE THREAD

**Issue by coelner** [duplicati/duplicati#4050]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**:  2.0.4.38_canary_2019-12-29
- **Operating system**: Archlinux 5.4.10-arch1-1 
- **Backend**: local mount point of a smb share through systemd automount
//192.168.2.1/backup on /mnt/speedportBackup type cifs (rw,relatime,vers=1.0,cache=strict,username=XXX,domain=XXX,uid=1000,forceuid,gid=1000,forcegid,addr=192.168.2.1,soft,unix,posixpaths,serverino,mapposix,acl,rsize=61440,wsize=65536,bsize=1048576,echo_interval=60,actimeo=1)

## Description
I ran a backup sync and duplicati failed somehow to finish uploading the file. 

## Steps to reproduce
unknown

- **Actual result**:
 - The file is not saved correctly
- **Expected result**:
 - Try to redo the specific file handling
 - Give an opportunity to the user to fix this by rerun the failed task again
 - Give an opportunity to the user to fix this by rollback the failed task

## Debug log
[bugreport.zip](https://github.com/duplicati/duplicati/files/4049032/bugreport.zip)

**Comment by coelner** [comment]
I reimported a copy of this backup job, modified the destination target and run a new backup. This completely fails because duplicati can't find anything in the destination. The files are available.
1. I tried a repair, but no files were found
2. I deleted the local database and ran again a backup, '70 unknown files are found'
3.  I tried a repair, but no files were found

I would call it a dead lock.

**Comment by coelner** [comment]
The same with version 2.0.5.100_canary_2020-01-18

**Comment by drwtsn32x** [comment]
The user/group context under which Duplicati runs definitely has access to that mount point?  Try running a bash shell under that user context and confirm you can read and write files.

**Comment by coelner** [comment]
```
drwxr-xr-x 2 user user         0 24. Jan 15:20 .
drwxr-xr-x 8 user user         0 11. Jan 07:24 ..
-rwxr-xr-x 1 user user    480477  2. Aug 15:40 duplicati-20190802T132617Z.dlist.zip.aes
-rwxr-xr-x 1 user user    479997  5. Okt 18:02 duplicati-20191005T160239Z.dlist.zip.aes
-rwxr-xr-x 1 user user    480301 17. Nov 08:02 duplicati-20191117T070234Z.dlist.zip.aes
-rwxr-xr-x 1 user user    482717 31. Dez 13:13 duplicati-20191231T121322Z.dlist.zip.aes
-rwxr-xr-x 1 user user    483613 11. Jan 06:15 duplicati-20200111T051459Z.dlist.zip.aes
-rwxr-xr-x 1 user user    484349 24. Jan 15:20 duplicati-20200124T142041Z.dlist.zip.aes
-rwxr-xr-x 1 user user 524246413  2. Aug 15:40 duplicati-b03be81a1176e4313bdb3f1f466510e0d.dblock.zip.aes
-rwxr-xr-x 1 user user    433165 15. Dez 07:23 duplicati-b17149c027c6344bc967f4962f449284e.dblock.zip.aes
-rwxr-xr-x 1 user user    378093  7. Dez 09:10 duplicati-b2eca3777541746db841719cea21bbbc1.dblock.zip.aes
-rwxr-xr-x 1 user user    452173 25. Aug 08:21 duplicati-b414bc4ed59d34c668e62bb02c1eca3e9.dblock.zip.aes
-rwxr-xr-x 1 user user 524233181  2. Aug 15:30 duplicati-b548fad03b2f34c2f92e342436bba5bdb.dblock.zip.aes
-rwxr-xr-x 1 user user 524211501  2. Aug 15:37 duplicati-b54a547b20d744b0199a52bc90cb566c3.dblock.zip.aes
-rwxr-xr-x 1 user user  30040893 31. Dez 13:13 duplicati-b6474748890fa418db383e7a2aca0ebf1.dblock.zip.aes
-rwxr-xr-x 1 user user 524229357  2. Aug 15:35 duplicati-b6c9117e93f894623b0e782beb0fef17d.dblock.zip.aes
-rwxr-xr-x 1 user user 195785309  2. Aug 15:40 duplicati-b72949bd03cc84d7e8c995d5c0ec1fafc.dblock.zip.aes
-rwxr-xr-x 1 user user    414301  5. Okt 18:02 duplicati-ba3c61cae82234ae8b4b0270647c69bb1.dblock.zip.aes
-rwxr-xr-x 1 user user 524213197  2. Aug 15:40 duplicati-bb9e68c0c50554987b367a858f35202b6.dblock.zip.aes
-rwxr-xr-x 1 user user    522765 24. Jan 15:20 duplicati-bc1673925759c4e22b5e1fdd17987762e.dblock.zip.aes
-rwxr-xr-x 1 user user 524248733  2. Aug 15:30 duplicati-bc7154b03ed5e4afb922d536eca4acbb6.dblock.zip.aes
-rwxr-xr-x 1 user user 524217245  2. Aug 15:37 duplicati-bc7dbb5b7eaf04edcaee7b7b16179a8e0.dblock.zip.aes
-rwxr-xr-x 1 user user    495645 17. Nov 08:02 duplicati-bc9295471a3994f2a836fca4d7ceb7ba2.dblock.zip.aes
-rwxr-xr-x 1 user user    655360 11. Jan 06:15 duplicati-bcdd08dd51521472c88d0987c43c3aec8.dblock.zip.aes
-rwxr-xr-x 1 user user    783997 21. Dez 13:31 duplicati-bcf2f146b300f483a9f3904130462c934.dblock.zip.aes
-rwxr-xr-x 1 user user 524241757  2. Aug 15:35 duplicati-bd4196c3c016b4337a580ba7a4155f614.dblock.zip.aes
-rwxr-xr-x 1 user user 524242493  2. Aug 15:32 duplicati-bdb78bf1b7a244b2388ab6c24f65c655c.dblock.zip.aes
-rwxr-xr-x 1 user user 524191677  2. Aug 15:32 duplicati-be160f4f0ec2a4c1ba81cb5e954574d83.dblock.zip.aes
-rwxr-xr-x 1 user user    520509  2. Aug 15:32 duplicati-i03b1b17342154ce3a93dcbed8a4e01f2.dindex.zip.aes
-rwxr-xr-x 1 user user    427789  2. Aug 15:30 duplicati-i1dca24c27abf44b08097adf4b44220ab.dindex.zip.aes
-rwxr-xr-x 1 user user    515405  2. Aug 15:40 duplicati-i2290d4b29ba24e4db71f914e92e0bbb9.dindex.zip.aes
-rwxr-xr-x 1 user user    517437  2. Aug 15:40 duplicati-i27ca630ff6114eb0b847a81ffdaf9d0b.dindex.zip.aes
-rwxr-xr-x 1 user user    204525  2. Aug 15:40 duplicati-i28b19941b87740358ef0cd48390ee964.dindex.zip.aes
-rwxr-xr-x 1 user user     45757 25. Aug 08:21 duplicati-i30a70c227f854201852e1ed3abcaf1ca.dindex.zip.aes
-rwxr-xr-x 1 user user      2221 24. Jan 15:20 duplicati-i3406589262704936b5cc14417e3eb152.dindex.zip.aes
-rwxr-xr-x 1 user user      2205 21. Dez 13:31 duplicati-i37584d9d6cf249818e3a8fa40b11edb5.dindex.zip.aes
-rwxr-xr-x 1 user user    468733  2. Aug 15:35 duplicati-i4ec13268ff7e4c5cb677e0bddf6f3931.dindex.zip.aes
-rwxr-xr-x 1 user user      3821 11. Jan 06:15 duplicati-i4f40e8b6a6bd4c1b9a2be6208e6dab2d.dindex.zip.aes
-rwxr-xr-x 1 user user      1949 15. Dez 07:23 duplicati-i8e303377d8214168b831073f57ec210c.dindex.zip.aes
-rwxr-xr-x 1 user user      2157 17. Nov 08:02 duplicati-i8e4ac9716b8e45c99693017ec8247627.dindex.zip.aes
-rwxr-xr-x 1 user user    323389  2. Aug 15:37 duplicati-i92a8f59d0b1a4a69a6eb27512d0b2ebf.dindex.zip.aes
-rwxr-xr-x 1 user user    485517  2. Aug 15:30 duplicati-i965b05ae486b4ec181a3d17fc3db648c.dindex.zip.aes
-rwxr-xr-x 1 user user    440989  2. Aug 15:32 duplicati-i96e6327b9e184ac7bf17f7fb718f93f0.dindex.zip.aes
-rwxr-xr-x 1 user user      2173  5. Okt 18:02 duplicati-ia146a28a8fac40388738e98448b613d4.dindex.zip.aes
-rwxr-xr-x 1 user user    331645  2. Aug 15:35 duplicati-ib65014c40a0549adac1670e707e79ca4.dindex.zip.aes
-rwxr-xr-x 1 user user    387197  2. Aug 15:37 duplicati-id3b02a15599b4df2b0beafd446c03310.dindex.zip.aes
-rwxr-xr-x 1 user user      1501  7. Dez 09:10 duplicati-ie6a6ab3478a545178dbeb3d2600ede74.dindex.zip.aes
-rwxr-xr-x 1 user user     28365 31. Dez 13:13 duplicati-ifb365f3efc704c3bba397829c12dc974.dindex.zip.aes
```
There is no apparmor or selinux context.

**Comment by ts678** [comment]
> But I can not mark this file as broken and let duplicati ignore this.

If a file breaks, you can delete it or prefix its name to something other than `duplicati-` to hide it.

`duplicati-bcdd08dd51521472c88d0987c43c3aec8.dblock.zip.aes is listed as Uploaded with size 655360 but should be 1466365` in the DB is maybe the file that is being referred to as "single file"?

[The LIST-BROKEN-FILES command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-list-broken-files-command) and [The PURGE-BROKEN-FILES command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-purge-broken-files-command) can be run from the web UI [Commandline](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#using-the-command-line-tools-from-within-the-graphical-user-interface) screen to purge source file backups whose data was lost by the broken file. [Recovering by purging files](https://duplicati.readthedocs.io/en/latest/08-disaster-recovery/#recovering-by-purging-files) gives an example of how to do this, via a demo where a backup was intentionally corrupted.

Duplicati will retry uploads up to [--number-of-retries](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#number-of-retries) if an error is detected during upload. If an upload is reported fine, then the wrong file size won't be noticed until after the backup, when (I think...) a directory listing with size information is run, and [Verifying backend files](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#verifying-backend-files) is done to deeply test sample file contents.

There are very few [Storage Providers](https://duplicati.readthedocs.io/en/latest/05-storage-providers/) that verify immediately after uploads. FTP does. I don't know why. Maybe it had more problems. Your use is probably [Local folder or drive](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#local-folder-or-drive) which is probably usually pretty good, except somehow yours seemingly truncated a file. Interestingly, short size is very even binary. hex A0000, and this often makes me suspect a filesystem issue. It's also 10 times the wsize=65536 in config.

It's not likely practical to keep a copy of all uploaded files locally until the post-backup verification runs.

Deleting the damaged backup for a retry might be possible as an enhancement someday, however if it actually shows up as a backup (although damaged), you might also be able to just manually [delete](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-delete-command) the version (0 would be the latest). Maybe someone who looks at design or code someday has other ideas.

[Problem Backing up to samba share](https://forum.duplicati.com/t/problem-backing-up-to-samba-share/6921) was a similar Samba problem with a short file, and there are more.

**Comment by coelner** [comment]
The PURGE-BROKEN-FILES solved at least the warning. Thank you 
As I can not enforce this behavior to raise again I close the ticket.
