### ISSUE TITLE
Bundle duplicati as nuget package

### ISSUE THREAD

**Issue by Brunni** [duplicati/duplicati#4055]
Hello,

is it possible or reasonable to bundle duplicati as a nuget package.

Use caes:
We have an application which manages its background tasks (e.g. cleanup, backups) by themself (e.g via hangfire). We would like to call the backup-process explicitly from C#.

We could either do this via command line call or via C# classes. In terms of LGPL both variants should be fine.

For the second case it would ease our deployment, if everything was available as one nuget package.
Are there any reasons, that this was not done until now.

Regards
Michael

**Comment by ts678** [comment]
> is it possible or reasonable to bundle duplicati as a nuget package.

Is this still of interest? Running by command line seems better suited.
There's also a third-party [command line client](https://github.com/Pectojin/duplicati-client) interface to the server.

[An introduction to NuGet](https://learn.microsoft.com/en-us/nuget/what-is-nuget) says that a typical way to use a package is:

> add them to their projects, and then call a package's functionality in their project code.

which maybe fits your use, except Duplicati isn't made to be called to.
It's an application offering [many interfaces](https://www.duplicati.com/articles/Way-To-Make-A-Backup/), but not including C# calls.

> it would ease our deployment

I don't know if it helps any, but if you want to just drop the files from a `.zip` file, that works, and is how I install on Windows.

**Comment by ts678** [comment]
Of course a `.zip` file won't do the kind of dependency checking that a typical Linux package manager (e.g. apt) does.
That was recently used as a feature (ancient Duplicati install on a new Linux), but I'm not sure how you how you do it.

I'll note that I'm not familiar with some things you mentioned. I'm questioning whether NuGet is a good fit for its use.

[https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/Program.cs](https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/Program.cs)

shows the main entry point for the application (I think you can only have one -- the one from your application, right?).
Hangfire looks like it wants to call methods, as you suggest too. I don't know if it can also do a standalone application.

**Comment by ts678** [comment]
> We have an application

> it would ease our deployment

I don't know if this means a large-scale internal deployment into known environments (so avoids dependency headaches).
Octopus Deploy might be able to do that, and it appear to include tools to package applications into some NuGet format.

If you mean deployment into variable customer environments, I'm not sure if NuGet can fetch the OS-level dependencies.
