### ISSUE TITLE
 Duplicati - 2.0.5.101 - Failed to connect: SQL logic error no such table: LogData

### ISSUE THREAD

**Issue by gawkla** [duplicati/duplicati#4074]
- **Duplicati version**: 2.0.5.101
- **Operating system**: Windows 7 64bit
- **Backend**: SMB network drive mounted under Windows network drive

## Description
Today I meet strange issue.
After upgrade to last build (Duplicati - 2.0.5.101) I can't perform one of my backup tasks. Only one - all rest are working fine. In this one:
1) I can't see logs - "Failed to connect: SQL logic error no such table: LogData"
2) I can't repair, recreate database

I tried to delete local database, recreate, repair all options. Even delete backup task and import it again. Still she same wrong behaviour. Any ideas what can be wrong?

## Screenshots
![image](https://user-images.githubusercontent.com/10233305/73186877-c3ebf080-4120-11ea-8c79-0918aa8677cc.png)

![image](https://user-images.githubusercontent.com/10233305/73186924-d8c88400-4120-11ea-9af8-05ea4560b984.png)

**Comment by ts678** [comment]
[Error displaying log for backup that has never been run #1814](https://github.com/duplicati/duplicati/issues/1814) may explain the error for the "delete local database" and the "delete backup task and import it again" case. "Show log" shows the `LogData` from the database, but it's not there. As the other issue said,
 "a nicer error message would be nice :)". How the database came to be missing (or an empty file) is a question, but time has passed.

Interesting questions would be what exactly (if anything) was the DB at the time, at the `Local database path` of [Database](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#database-management) screen.
What version came before 2.0.5.101? If it was a  .msi install, there might be no record. If Duplicati autoupdated, see [Downgrading / reverting to a lower version](https://forum.duplicati.com/t/downgrading-reverting-to-a-lower-version/3393) for the possible location of older updates. Was the backup of issue running properly before the update?

What's the story of the red error box on screenshot? That looks like the same backup with missing LogData, and unfortunately the "Show log" logs have no result to log when an error kills the backup, yet the Show button goes to the [usual log](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-log-files-of-a-backup-job) -- known issue -- it should go to [About --> Show log](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-duplicati-server-logs). You wouldn't be able to get the red error without a DB (as it's a DB check), but I don't know the exact sequence of steps done... Not sure what to suggest. Error on the issue title has an open, understood issue, and the rest is old.

What (if anything) resolved this issue? The usual way a DB gets created (so `Show log` has a log) is to finish a successful backup run. Have you been staying on Canary (now at 2.0.5.111 -- thanks for testing) and done some updates? Has the strange issue repeated?

**Comment by ts678** [comment]
No response. Is this still of interest?
