### ISSUE TITLE
S3 Bucket TargetURL wrong (s3s:// instead of s3://)

### ISSUE THREAD

**Issue by Bugahans** [duplicati/duplicati#4086]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1
- **Operating system**: Linux
- **Backend**: S3

## Description

The TargetURL for s3 has a wrong character.
mono /app/duplicati/Duplicati.CommandLine.exe backup "s3s://<mybucket>/foo?s3-server-name=s3.amazonaws.com&..

it should be s3:// and not s3s://

## Steps to reproduce

1. Create new backup Job with S3
2. Try Connection or export job
3. ...

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by drwtsn32x** [comment]
Not sure if this is a bug.  I think Duplicati appends an "s" when you check the "use SSL" option that some protocols support.  S3, FTP, WebDAV, Tahoe, etc.

**Comment by ts678** [comment]
I don't know the code well, but I'll offer the following in support, for somebody to look over closer:

https://github.com/duplicati/duplicati/blob/082a14fc22efdef226c1bee956f85009f7104fb3/Duplicati/Server/webroot/ngax/scripts/services/EditUriBackendConfig.js#L29-L36

https://github.com/duplicati/duplicati/blob/082a14fc22efdef226c1bee956f85009f7104fb3/Duplicati/Library/DynamicLoader/BackendLoader.cs#L81-L96

**Comment by drwtsn32x** [comment]
Yep that confirms it!
