### ISSUE TITLE
Feature Request: Throttle Speed per Backup Task

### ISSUE THREAD

**Issue by hl2guide** [duplicati/duplicati#4096]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10 Pro 1909 X64
- **Backend**: MEGA.nz

## Description

Please consider adding the ability to throttle Download+Upload per backup task. Currently it applies globally.

**Comment by ts678** [comment]
[--throttle-download](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#throttle-download) and [--throttle-upload](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#throttle-upload) are configurable for each backup task, although I think they're confused about direction (just like the throttle button control on the main screen), so set both directions.

**Comment by hl2guide** [comment]
@ts678 ok I'll try that.
