### ISSUE TITLE
backup direct to destination without tmp file creation

### ISSUE THREAD

**Issue by MyUncleSam** [duplicati/duplicati#4113]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows Server 2016 Essentials (as service)
- **Backend**: 

## Description

It is more a question:
Is there a possibility to backup directly to the destination without any tmp files? (Or how to put the tmp folder to the destination so files are moved?)

The reason is simple. My folders to backup are on the same raid as the tmp folder (i only have one raid 10). So the raid is just busy with reading and writing. With that I get an overall speed of around 8MB/s if I try to backup to my NAS (gigabit connected in the same network). If I use another software which is able to directly backup to the NAS, the transfer speeds are about 60-80 MB/s.

So I checked if there is any option to avoid that duplicati writes to the same raid system. All I got was to try to move the temporary directory to the NAS too. But then it uploads the files to the temporary folder, but as soon as it is finished it downloads the temporary files and uploads them to the target directory (even if the temporary directory is a sub folder of the backup target folder).

I also tried_
- disable-streaming-transfers
- use-move-for-put

But it changed notehing.

So does anyone have an idea how to speed up things?

## Steps to reproduce

See description

**Comment by RichieFrame** [comment]
create a ramdisk and use that for temp... if you have available memory that is, i am using half a gig and it works fine

**Comment by MyUncleSam** [comment]
I'll try that.

**Comment by warwickmm** [comment]
A ramdisk is probably the best solution.  The need for a temp location is pretty core to the design.
