### ISSUE TITLE
Alternate Sources

### ISSUE THREAD

**Issue by starik1968** [duplicati/duplicati#4116]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: current beta
- **Operating system**: Win 10 x64 1909
- **Backend**: local drive

## Description

I want to have alternate sources like the alternate targets, because I backup USB-Devices with changing drive letters, is this possible?

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by warwickmm** [comment]
See the following for an explanation of how one might deal with changing drive letters:

https://www.duplicati.com/articles/Windows-Drive-Letters/

**Comment by tudacs** [comment]
I guess the merged PR #2723 is more of help here (specify Windows drives by their volume guid, given by `mountvol`, e.g.), as the initial request was about varying **source** drive letters and the linked article is solely about alternating **targets**, afaik.

**Comment by warwickmm** [comment]
Thanks @tudacs, I misread the original description. This is also related to issue #2036.
