### ISSUE TITLE
Typos in an Article

### ISSUE THREAD

**Issue by bugith** [duplicati/duplicati#4117]
here : https://www.duplicati.com/articles/Way-To-Make-A-Backup/

Commandline Interface:
...for the backup. On common use is to set it up as... should be ... On**e** common use ...

Backup Scheduler:
...script called duplicati-control.py in bundled... should be ... i**s** bundled...

The Web Interface:
...cannot be access from the internet... should be ...cannot be access**ed** from...

Thanks for the soft, guys, I have no time to search if I ever have the possibility to fix this myself (please, handle with caution: I'm not native english speaker).

**Comment by warwickmm** [comment]
Thanks!  The fix is [here](https://github.com/duplicati/duplicati.github.io/pull/17).

**Comment by Sordon** [comment]
Hello maybe I can add another typo in this article:
https://www.duplicati.com/articles/Choosing-Sizes/

In the second last chapter is the following sentence:
If you have large datasets and a stable connection, it is usually desirable to **user** a larger volume size.

Instead of "user" it should say "use"

**Comment by warwickmm** [comment]
Thanks for finding these.   The website is actually a separate project.  Can you create the issues [here](https://github.com/duplicati/duplicati.github.io/issues) instead?

**Comment by Sordon** [comment]
Yes, created an issue there.

**Comment by warwickmm** [comment]
Thanks!  I'm not sure when the website code will get merged and deployed, but I'm going to close this issue since it's not critical to this specific project.
