### ISSUE TITLE
Feature Request: process gitignore files for exclusion

### ISSUE THREAD

**Issue by kinghat** [duplicati/duplicati#4119]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------
for people who work with git it would be nice to automatically not backup stuff that is marked for exclusion in gitignore files that duplicati comes across.

**Comment by warwickmm** [comment]
There's some related discussion [here](https://forum.duplicati.com/t/ignore-file-like-gitignore/5095).

**Comment by Zetanova** [comment]
Any news about it?

Would be nice for a drive containing visual  Studio Projects
to exclude all build artifacts and temp VS files.

**Comment by cal4** [comment]
@kinghat, can you reopen? Still think this feature would be useful

**Comment by ArcticLampyrid** [comment]
Need this features too.
Backing up all files that auto generated just makes it slow and large. In contrast, the cost of scanning file trees can be negligible.
