### ISSUE TITLE
Improve translations to use placeholders for system terms

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#413]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on May 05, 2011 13:10:39_

Some of the strings to translate contains internal terms, such as 'full' or 'manifest' that should not be translated. These strings should be changed to something like: "The option {0} can have the settings '{1}' and '{2}'".

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=413_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
