### ISSUE TITLE
 Failed to enumerate Microsoft SQL Server databases

### ISSUE THREAD

**Issue by Athep** [duplicati/duplicati#4132]
- [x] I have searched open and closed issues for duplicates. There is similar issues.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.103_canary_2020-02-18
- **Operating system**: Windows Server 2012 R2
- **Backend**: Local + Goggle Drive and Google Cloud

## Description

When start editing the configuration i get a pop up saying:

> Failed to enumerate Microsoft SQL Server databases: Microsoft SQL Server VSS Writer not found - cannot backup SQL databases.

The service "SQL Server VSS Writer is running"   

I am not sure if the issue appeared when i started to run SQL on the server or if it is related to the latest canary. The version before upgrade was 2.0.4.38.  I discovered the problem first when i should change some of the configuration.

Snapshot-policy is set to "Required" since long time back and has never had any issues.

## Debug log

Mar 11, 2020 11:08 AM: Failed to signal VSS completion

``{"ClassName":"Alphaleonis.Win32.Vss.VssBadStateException","Message":"The` VSS object was in an incorrect state for the requested operation.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Alphaleonis.Win32.Vss.VssBackupComponents.BackupComplete()\r\n   at Duplicati.Library.Common.IO.VssBackupComponents.Dispose()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nBackupComplete\nAlphaVSS.x64, Version=1.4.0.0, Culture=neutral, PublicKeyToken=959d3993561034e3\nAlphaleonis.Win32.Vss.VssBackupComponents\nVoid BackupComplete()","HResult":-2146233088,"Source":"AlphaVSS.x64","WatsonBuckets":null}``

**Comment by warwickmm** [comment]
Are you running Duplicati as an administrator?  Issue #2235 sounds related.

**Comment by Athep** [comment]
Yes, running as administrator.

**Comment by drwtsn32x** [comment]
I have not used Duplicati to back up SQL before, but I have experience with enterprise backup systems and SQL.  Does the account you run Duplicati under have sufficient permission to the database instance?

**Comment by warwickmm** [comment]
Does the following help?

https://forum.duplicati.com/t/solved-failed-to-enumerate-microsoft-sql-server-databases-microsoft-sql-server-vss-writer-not-found-cannot-backup-sql-databases/9464

**Comment by Athep** [comment]
That did it! Case solved. Maybe this will introduce some security issue, but in my case i don't think it will any problems at all.
