### ISSUE TITLE
Docker image based on Debian version nearing LTS EOL

### ISSUE THREAD

**Issue by jerrac** [duplicati/duplicati#4133]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Description
The `duplicati/duplicati:latest` image is based on Debian Jessie. [Debian's docs](https://wiki.debian.org/DebianReleases) say that Jessie hits LTS EOL ~2020-06-30. 

After looking at your Dockerfile, I tracked down the `mono:5-slim` [Dockerfile](https://github.com/mono/docker/blob/master/5.20.1.34/slim/Dockerfile), it looks like the latest version is based on Debian Stretch.

Could you rebuild your image on a newer version of `mono:5-slim`?

I'm guessing this is already on your todo list, but I didn't find an issue tracking it, so hopefully posting this is helpful.

**Comment by warwickmm** [comment]
I'm not familiar with our Docker builds.  I think `duplicati/duplicati:latest` is the latest beta release.  Are the recent canaries based on stretch?

https://hub.docker.com/layers/duplicati/duplicati/2.0.5.103_canary_2020-02-18/images/sha256-4e7e49c913f5ba07cc71d95e4a8c19e73f7fb7eda0ec238d11352d19870383cf?context=explore

**Comment by drwtsn32x** [comment]
Downloaded the latest canary docker image and confirmed it is running Debian stretch (9.11).

**Comment by jerrac** [comment]
@drwtsn32x Thanks!
