### ISSUE TITLE
duplicati as service cannot find network mappings

### ISSUE THREAD

**Issue by B4rtware** [duplicati/duplicati#4143]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10
- **Backend**: local

## Description

After I have installed duplicati as a service I am not able to backup anymore to my nas. Before the service installation I have used duplicati without service installation where I have manually created a `New-SmbMapping` and duplicati was able to connect to it.
Since the installation of the service, duplicati cant find the mapping.

I mapped it as my current user and as admin with no success. Duplicati is registered to Log On as `Local System`. I have tested my current user and even this did not work.

If I enter the path manually I get an error that the path cannot be found.
"Failed to connect: Could not find a part of the path"
However if I paste that path into the windows explorer it can be found.

I'd appreciate some help :)

**Comment by drwtsn32x** [comment]
LocalSystem has no access to network SMB resources.  You will need to use a regular user account and tie it to the service.  Or you can use an alternate protocol to back up to the NAS. Synology NAS devices support lots of protocols...not sure what brand yours is.

**Comment by B4rtware** [comment]
Thank you for your response. Yes I had also tried to use my current account for the service with no success. (I am using a Western Digital MyCloud NAS). I followed your advice on using a different protocol and choosed ftp but until now I had no success on let duplicati create a folder. I think this is out of scope of this issue.
