### ISSUE TITLE
Site duplicati.com down and cant install duplicati on Buster

### ISSUE THREAD

**Issue by henkiejan1** [duplicati/duplicati#4144]
Hi,

First of all the the site duplicati.com is down. I got a day 502 bad gateway.

Update:

I have duplicati now headless runing on Debian Buster. And i can open the page on port 8200 but get a lot of errors.

The log say: 

`
20 mrt. 2020 19:23: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:23: Reporting error gave error
20 mrt. 2020 19:21: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:21: Reporting error gave error
20 mrt. 2020 19:20: Reporting error gave error
20 mrt. 2020 19:20: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:20: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:20: Reporting error gave error
20 mrt. 2020 19:20: Reporting error gave error
20 mrt. 2020 19:20: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:18: Error in updater
20 mrt. 2020 19:18: Error in updater
20 mrt. 2020 19:17: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:17: Reporting error gave error
20 mrt. 2020 19:17: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:17: Reporting error gave error
20 mrt. 2020 19:13: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:13: Reporting error gave error
20 mrt. 2020 19:11: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:11: Reporting error gave error
20 mrt. 2020 19:07: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:07: Reporting error gave error
20 mrt. 2020 19:07: Reporting error gave error
20 mrt. 2020 19:07: Reporting error gave error
20 mrt. 2020 19:07: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:07: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:02: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:02: Reporting error gave error
20 mrt. 2020 19:01: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:01: Reporting error gave error
20 mrt. 2020 19:01: Reporting error gave error
20 mrt. 2020 19:01: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error
20 mrt. 2020 19:01: Request for http://192.168.2.4:8200/api/v1/systeminfo gave error `

**Comment by henkiejan1** [comment]
The most strange error of the lot of errors is ´Reporting error gave error´.

With inside:

`System.ObjectDisposedException: Can not write to a closed TextWriter.
  at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x00008] in <a1ae6166591d4020b810288d19af38d4>:0 
  at System.IO.StreamWriter.Flush () [0x00006] in <a1ae6166591d4020b810288d19af38d4>:0 
  at Duplicati.Server.WebServer.RESTHandler.DoProcess (Duplicati.Server.WebServer.RESTMethods.RequestInfo info, System.String method, System.String module, System.String key) [0x003bc] in <e69e4c0173384a62bf88cae30cea7f3d>:0 `

**Comment by warwickmm** [comment]
I believe this has been resolved.

https://forum.duplicati.com/t/reporting-error-gave-error/9447/12

**Comment by danielo515** [comment]
Site is down again. Don't want to open a new issue to notify just that
