### ISSUE TITLE
exported configuration is not updated

### ISSUE THREAD

**Issue by pavelxkrejci** [duplicati/duplicati#4156]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.1
- **Operating system**: Windows 10 Pro build 1909
- **Backend**: SSH server

## Description
Exported configuration is not updated according to *some* updated settings. I have no idea what settings are actually in use. Some metadata settings (ie. LastCompactDuration) after maintenance job are updated in exported config. I have only tested "--snapshot-policy" and "--force-locale" settings, none of them is exported as expected. Snapshot policy setting is important for me as it directly influences whether important files are backed up or not.

## Steps to reproduce
1. Set "--snapshot-policy" to On 
2. export configuration A (either command line or json file, same result)
3. change "--snapshot-policy" from On to Off
3. (optional) restart Duplicati application, same result
4. re-export configuration B
5. compare configuration A and B

- **Actual result**: no change in exported configuration, B still shows --snapshot-policy=On
- **Expected result**:  re-exported configuration is updated, B shows --snapshot-policy=Off

## Screenshots
![duplicati-issue-settings](https://user-images.githubusercontent.com/3956353/78121619-e42f7880-740b-11ea-83e8-317ddbd59ae1.png)
![duplicati-issue-export](https://user-images.githubusercontent.com/3956353/78121621-e4c80f00-740b-11ea-9eab-4621c47b901a.png)

## Debug log
```
Duplicati: Duplicati.GUI.TrayIcon, Version=2.0.5.1, Culture=neutral, PublicKeyToken=null (Duplicati.Library.Main, Version=2.0.5.1, Culture=neutral, PublicKeyToken=null)
Autoupdate urls: https://updates.duplicati.com/beta/latest.manifest;https://alt.updates.duplicati.com/beta/latest.manifest
Update folder: C:\ProgramData\Duplicati\updates
Base install folder: C:\Program Files\Duplicati 2
Version name: "2.0.5.1_beta_2020-01-18" (2.0.5.1)
Current Version folder C:\ProgramData\Duplicati\updates\2.0.5.1
OS: Microsoft Windows NT 10.0.18362.0
Uname: 
64bit: True (True)
Machinename: MPC
Processors: 4
.Net Version: 4.0.30319.42000
Mono: False (0.0) ()
Locale: cs-CZ, cs-CZ, cs-CZ
Date/time strings: d. MMMM yyyy - H:mm:ss
Tempdir: C:\Users\User\AppData\Local\Temp\
SQLite: 3.28.0 - System.Data.SQLite.SQLiteConnection
SQLite assembly: C:\ProgramData\Duplicati\updates\2.0.5.1\SQLite\win64\System.Data.SQLite.dll
```

**Comment by drwtsn32x** [comment]
The global settings are not included when you export a job as a json file.  They do seem to be shown when you export a job as command line, but import doesn't support that format - it can only import from json file.

I guess I never considered this a bug - it seems logical to me that settings at the global level aren't exported with the jobs.  When I export my job configs I also "export" the global settings. I do this pretty easily by viewing the global options "as text" and then copying/pasting into a text file.  With the job and global settings exported (and saved safely somewhere), it's easy to recover in case of disaster.

**Comment by pavelxkrejci** [comment]
Thank you for the hints. As a new user I didn't realize the dichotomy of global vs job-specific settings. Maybe a note in the description text could mention that a setting is available at both global and job-specific scale and what the priorities are.

As for exporting global settings - when I click "edit as text" only the extra settings are displayed. Ie. the "Language in user interface" and "Display and color theme" are not, so it is confusing regarding the availability of "export" of the global settings.

The behavior of command line export vs json file is the same for this issue. I have included the command line screenshot as an example with easier readability.

**Comment by drwtsn32x** [comment]
You can also "back up" your entire Duplicati configuration by storing a copy of `Duplicati-server.sqlite` in a safe place.  This gets all global settings and all job configurations.

**Comment by pavelxkrejci** [comment]
Thanks for info. My Duplicati-server.sqlite seems to be encrypted. How can I decrypt it for the purpose of reviewing and/or archiving the settings?

**Comment by drwtsn32x** [comment]
I wouldn't bother.  Just leave it in its encrypted state.  Make a new backup any time you adjust any Duplicati settings.  If you ever have a complete system failure, you can restore this one file (after you rebuild your system) to get your configuration back.

There is a way to have Duplicati store this database in an unencrypted way but it's riskier.

**Comment by pavelxkrejci** [comment]
I am aware of the risks. Can you please provide details or link or hint how to store the configuration unencrypted?

**Comment by drwtsn32x** [comment]
I have never tried it myself, but this post has instructions:  https://forum.duplicati.com/t/which-tool-can-open-encrypted-db/2372/4

**Comment by pavelxkrejci** [comment]
Thanks, I have finally clean and readable configuration backup. Luckily it is simple, just restart Duplicati with command line argument "--unencrypted-database". I have doubts about the security effect of RC4 based scrambling or obfuscation of the configuration database, but thats for another discussion.

**Comment by drwtsn32x** [comment]
Agreed, especially in the default configuration where it's a known password.  Best thing is to protect access to the system (especially that file) using other means.
