### ISSUE TITLE
Feature request: Allow run scripts before and after snapshot creation

### ISSUE THREAD

**Issue by SomebodyOdd** [duplicati/duplicati#4158]
Hello!

I use duplicati to backup Nextcloud server (tl;dr - file storage solution), and right now I have to enable maintenance mode with run-script-before and disable it with run-script-after. 
This is required, because I want my data to be in consistent state at the moment of backup. This means, that my server rejects client requests for entire backup duration - ouch!
I noticed, that Duplicati has option for snapshots. How about adding option for a script before snapshot and after snapshot, so "before snapshot" script could prepare data and make them consistent, then Duplicati takes snapshot, then "after snapshot" script enables whatever services and servers were disabled at that time, allowing them to continue operation while backup is in progress.
I think that could be really useful in setups, where downtime should be as minimal as possible. And that feature might cut downtime to seconds instead of minutes and (potentially) hours.

**Comment by drwtsn32x** [comment]
I like this idea....

**Comment by SomebodyOdd** [comment]
Looks like a dead feature request to me... Oh well...
