### ISSUE TITLE
Add Edge browser cache folder to default excludes

### ISSUE THREAD

**Issue by Nargash** [duplicati/duplicati#4160]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1
- **Operating system**: Windows 10
- **Backend**: Google Drive

## Description

This may have recently changed with Microsoft's Edge browser's updates. It seems Edge's cache on Windows is now being stored in %LOCALAPPDATA%\Microsoft\Edge\User Data\Default\Cache\

This is very similar to where Chrome puts its cache, which is in %LOCALAPPDATA%\Google\Chrome\User Data\Default\Cache\ 

There's already a default exclude pattern for the Chrome cache set in [FilterGroups.cs](https://github.com/duplicati/duplicati/blob/2a497fb854b8ae8b04ad4ab9a9b1f21f67ea0a5f/Duplicati/Library/Utility/FilterGroups.cs#L291).

Edge folders should be excluded with similar logic.

## Steps to reproduce

1. On Windows apply either a default excludes group or Cache group filter
2. Run a backup with your AppData folder selected

- **Actual result**:
Edge cache folder will be available to restore
- **Expected result**:
We'd expect this to be excluded when using a Cache filter group.

**Comment by warwickmm** [comment]
The `CacheFiles` filter collection does have a filter for [SpecialFolder.InternetCache](https://github.com/duplicati/duplicati/blob/2a497fb854b8ae8b04ad4ab9a9b1f21f67ea0a5f/Duplicati/Library/Utility/FilterGroups.cs#L389).  We should see if the Edge cache folder (or folders) have this flag.

**Comment by drwtsn32x** [comment]
`SpecialFolder.InternetCache` returns one specific folder, it's not really a flag that can be checked on just any folder.

I see this return `C:\Users\<username>\AppData\Local\Microsoft\Windows\Temporary Internet Files` which corresponds to the Internet Explorer cache location.

I think we do need to add `%LOCALAPPDATA%\Microsoft\Edge\User Data\Default\Cache\` to the list of folders to exclude.

**Comment by drwtsn32x** [comment]
PR https://github.com/duplicati/duplicati/pull/4166
