### ISSUE TITLE
Duplicati not using the set asynchronous-upload-folder

### ISSUE THREAD

**Issue by DutchEllie** [duplicati/duplicati#4173]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10
- **Backend**: Google drive

## Description

The backup goes through the sdd instead of the dedicated ramdisk. I set both the global and per backup asynchronous-upload-folder to R:/temp and it seems to be using both my SSD and the ramdisk. Why?

## Steps to reproduce

1. Set up a backup
2. Change the asynchronous upload folder to a ramdisk
3. It doesn't work

- **Actual result**:
The temp data is written to both my C: and R: drive

- **Expected result**:
The temp data is written to the R: drive only

## Screenshots

![image](https://user-images.githubusercontent.com/6501187/79463654-64073680-7ff9-11ea-8fb1-314b40275c9e.png)
![image](https://user-images.githubusercontent.com/6501187/79463681-6ec1cb80-7ff9-11ea-9de7-9bf967c7f0ed.png)
![image](https://user-images.githubusercontent.com/6501187/79463738-86994f80-7ff9-11ea-8a10-0604397577b8.png)

**Comment by drwtsn32x** [comment]
Have you also set the `--tempdir` option to point to your RAM drive?  If you set both at the global level, you can remove the settings from individual backups.

**Comment by ts678** [comment]
Look for any files rotating through the upload folder, e.g. here are `dir /od dup-*` runs:

```
04/16/2020  11:05 AM         5,144,330 dup-de505161-f18b-4243-8854-16324ff78b4d
04/16/2020  11:05 AM         5,141,529 dup-2ec6d07e-d735-4bd1-aed5-c18b6d91f3ce
04/16/2020  11:05 AM                 0 dup-578a13fa-f6f2-420c-9a33-acd6910eae70

04/16/2020  11:05 AM         5,144,330 dup-de505161-f18b-4243-8854-16324ff78b4d
04/16/2020  11:05 AM         5,141,529 dup-2ec6d07e-d735-4bd1-aed5-c18b6d91f3ce
04/16/2020  11:05 AM         5,144,502 dup-578a13fa-f6f2-420c-9a33-acd6910eae70

04/16/2020  11:05 AM         5,141,529 dup-2ec6d07e-d735-4bd1-aed5-c18b6d91f3ce
04/16/2020  11:05 AM         5,144,502 dup-578a13fa-f6f2-420c-9a33-acd6910eae70
04/16/2020  11:06 AM                 0 dup-a0507b65-54ca-4488-8947-e47b153198b9

04/16/2020  11:05 AM         5,141,529 dup-2ec6d07e-d735-4bd1-aed5-c18b6d91f3ce
04/16/2020  11:05 AM         5,144,502 dup-578a13fa-f6f2-420c-9a33-acd6910eae70
04/16/2020  11:06 AM         5,148,595 dup-a0507b65-54ca-4488-8947-e47b153198b9

04/16/2020  11:05 AM         5,144,502 dup-578a13fa-f6f2-420c-9a33-acd6910eae70
04/16/2020  11:06 AM         5,148,595 dup-a0507b65-54ca-4488-8947-e47b153198b9
04/16/2020  11:07 AM                 0 dup-f0f5feb5-43db-4f0d-870c-7d36876fd799
```

You full-size dblock files might be the default 50 MB, and your queue length may differ.
It's difficult to tell from file names what sort of file it is, but the file length can be a clue.

**Comment by DutchEllie** [comment]
They're rotating through both folders. I have not set the --temp-dir, I have set it now and it's working! Thank you so much. It's not rotating files in the appdata temp folder anymore. 
I feel you guys should really add that about the SSD problem in the readme

**Comment by drwtsn32x** [comment]
I'm not convinced using SSD for temp is that big of a deal.  I personally have used my SSD since I started using Duplicati 2.5 years ago.  The health is still excellent, according to Samsung Magician.  The SSD is a bit over 4 years old (PRO 950 NVMe).

Someone on the forum did some calculations if I recall to confirm.  But I guess it is up to how much data churn you have with the data being backed up by Duplicati.

That being said using a RAM drive seems like a nice idea and results in less wear on the SSD for sure.  What RAM drive software are you using?

**Comment by DutchEllie** [comment]
I used the one also recommended on the forum [here](https://forum.duplicati.com/t/attention-ssd-users-if-your-temp-directory-isnt-ram-backed-duplicati-will-prematurely-wear-your-ssd/5779). It's called lmDisk. My settings are simply 2GB with AWE physical memory (like the instructions say to make sure it won't use the page file.) I would've probably gone higher, if it wasn't for my ancient set of 2x4GB DDR3 ram XD

**Comment by drwtsn32x** [comment]
Are we ok to close this issue?

**Comment by ts678** [comment]
> Are we ok to close this issue?

Originator seems happy using --tempdir to keep all the processing where desired:

> They're rotating through both folders. I have not set the --temp-dir, I have set it now and it's working! Thank you so much. It's not rotating files in the appdata temp folder anymore.

and I have a tentative explanation for "both folders" based on the tests that I ran. It makes more sense if read in conjunction with:

[asynchronous-upload-limit](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#asynchronous-upload-limit)

> When performing asynchronous uploads, Duplicati will create volumes that can be uploaded. To prevent Duplicati from generating too many volumes, this option limits the number of pending uploads. Set to zero to disable the limit

The volumes are future dblock, dindex, and dlist ` files` that are in `.zip` format. They queue up in [asynchronous-upload-folder](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#asynchronous-upload-folder):

> The pre-generated volumes will be placed into the temporary folder by default, this option can set a different folder for placing the temporary volumes

It looks like later files, such as the encrypted version of the `.zip` file, fall in the general temporary category and so use --tempdir.
All file names begin with `dup-` so it's hard to tell what's in what. An encrypted `.zip` is also only a little bigger than unencrypted.

Knowing this split (assuming it's correct) might actually be a useful debug aid when backup gets stuck, to know what stage it's at.
[Backup stops towards the end](https://forum.duplicati.com/t/backup-stops-towards-the-end/11517/6?u=ts678) had to find out one mixed Temp folder had an encrypted file by having a `.zip` tool fail on it, then looking in notepad to see it was encrypted. Next step to confirm would be to test decrypt. Like I said, it's hard to say what's what.
