### ISSUE TITLE
Feature request: Apt repository to allow automatic updating on Debian/Ubunti

### ISSUE THREAD

**Issue by cyberjacob** [duplicati/duplicati#4179]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Any
- **Operating system**: Debian & derivatives such as Ubuntu
- **Backend**: Any

## Description

Currently, updating Duplicati requires manually browsing the website and downloading the latest `.deb` file. Ideally this should be replaced with an apt repository to allow easier and automatic updates.

**Comment by warwickmm** [comment]
Given the lack of resources, I think this is best done by separate maintainers for the various distributions.

For example, there are people who have volunteered to be maintainers for the beta and canary channel packages for Arch:

https://aur.archlinux.org/packages/duplicati2-beta/
https://aur.archlinux.org/packages/duplicati-latest/

**Comment by samuel-w** [comment]
I created a repository for that:
https://gitlab.com/samuel-w/duplicati-deb-rpm-repo
Based on https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo.
Supports both deb and rpm, it just copies the deb and rpm files from releases. Canary branch only.

**Comment by samuel-w** [comment]
I created a repository for that:
https://gitlab.com/samuel-w/duplicati-deb-rpm-repo
Based on https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo.
Supports both deb and rpm, it just copies the deb and rpm files from releases. Both beta and canary branches supported.

**Comment by samuel-w** [comment]
Should I update the install docs for this and #4185?

**Comment by warwickmm** [comment]
Nice work @samuel-w.  I think a forum post is the best place initially for this type of thing.  My feeling is that we should probably avoid "endorsing" any third-party package repositories in our documentation.  We can ask for more opinions in the forum post to see where the best place for this is.

https://forum.duplicati.com/c/installation/7

**Comment by samuel-w** [comment]
I could try integrating it into duplicati.github.io, if that would be accepted as "official".

**Comment by warwickmm** [comment]
I still think the forum is the best place for this right now.  Again, I don't think we should be "officially" directing users to third-party repositories for their respective distributions.  For example, there's more than one Arch AUR for Duplicati and we don't officially recommend one over the other.

**Comment by ts678** [comment]
> It would require a license change to AGPL since the upstream is licensed as that.

Could you clarify how [AGPL](https://www.gnu.org/licenses/) got into this? Duplicati is licensed GPL v2.1, [it appears](https://github.com/duplicati/duplicati/blob/master/LICENSE.txt).

**Comment by samuel-w** [comment]
I forked it from https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/blob/master/LICENSE. duplicati.github.io is MIT licensed.
