### ISSUE TITLE
Mega.nz as Backend - ResourceNotExists

### ISSUE THREAD

**Issue by Bungeefan** [duplicati/duplicati#4182]
- [ x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1-1
- **Operating system**: Ubuntu 19.10
- **Backend**: Mega.nz

## Description

Can't use my new mega account to backup. Whenever I try to verify the connection it returns:
"Failed to connect: API response: ResourceNotExists"
I also tried to continue but the backup won't run further than "Checking Backend Details". Same error then.
I used a new Mega Account without 2FA!

**EDIT:**
I was using the wrong password, maybe just add a more detailed version of the API response, if available.

## Steps to reproduce

1. Setup Backup
2. Use Mega.nz as Backend
3. Enter details
4. Click "Verify Connection"
5. Wait for the error

- **Actual result**:
Fails because of "ResourceNotExists"
- **Expected result**:
Connection should be successful or fail during invalid credentials

## Screenshots

![grafik](https://user-images.githubusercontent.com/39010966/80549881-a9930e80-89be-11ea-9f56-805148459a54.png)
![grafik](https://user-images.githubusercontent.com/39010966/80549862-9e3fe300-89be-11ea-84f8-9745bfe5779a.png)

**Comment by devops-caspian** [comment]
@Bungeefan  Previously I've used duplicity and it couldn't connect to an account that has been created via Mega web interface(it creates some new type of account). Only account created via api worked. That account works with duplicati.

1. Delete your account
2. Install megatools
3. Create account
`megareg --name=Your Name --email=your@e.mail --password=YourPa$$w0rD`

It should help.

**Comment by Bungeefan** [comment]
Thanks anyway.
Is that a workaround or the way to go?

**Comment by devops-caspian** [comment]
@Bungeefan Forget what I've previously said. I've just created a new account at mega.nz via web interface and used duplicati 2.0.5.1-1 installed on Ubuntu 19.10. It works.

**Comment by Bungeefan** [comment]
@devops-caspian then tell me what I am doing wrong. Did you set something specific in the MEGA account settings? And what did you enter as Username in duplicati? Is it wrong when I am using the email?

**Comment by Bungeefan** [comment]
Omg I am just dumb... @devops-caspian sry for your time.
I used the wrong password on the new account. Now it is working for me. 
Maybe parse the API response better and show the user a detailed version of the error, if available.
