### ISSUE TITLE
'OPENSSH' is not supported ..

### ISSUE THREAD

**Issue by BedoM** [duplicati/duplicati#4184]
Hello i have a problem with backup with ssh-keyfile.

![duplicati-openssh-feature1](https://user-images.githubusercontent.com/25350431/80737236-8463e480-8b13-11ea-9557-b33a9ddfcf4f.png)

path:
/home/mabed.ssh2/duplicati_rsa
[mathieu@Y520 ~]$ ssh-keygen -l -f ~/.ssh2/duplicati_rsa
3072 SHA256:qR8yDBxR83z9nBu2EyD1wprf7fcwsN9omc5TwYqDKW8 mathieu@Y520 (RSA)

But i have generated my key without passphrase with ssh-keygen

I put the public key on the server.

What is the problem ?

thank you 

###
NAME=Fedora
VERSION="32 (KDE Plasma)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (KDE Plasma)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde

Linux Y520 5.6.7-300.fc32.x86_64
###

Duplicati - 2.0.5.1_beta_2020-01-18

**Comment by warwickmm** [comment]
This duplicates issue #3360 (see workarounds in the comments).  We are waiting for SSH.NET to support the new key format.  Once it's available, we can update the dependency in Duplicati.
