### ISSUE TITLE
Feature request: dnf/yum repository to allow automatic updating on redhat like

### ISSUE THREAD

**Issue by BedoM** [duplicati/duplicati#4185]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

Currently, updating Duplicati requires manually browsing the website and downloading the latest .rpm file. Ideally this should be replaced with an apt repository to allow easier and automatic updates.

**Comment by warwickmm** [comment]
Given the lack of resources, I think this is best done by separate maintainers for the various distributions.

For example, there are people who have volunteered to be maintainers for the beta and canary channel packages for Arch:

https://aur.archlinux.org/packages/duplicati2-beta/
https://aur.archlinux.org/packages/duplicati-latest/

**Comment by warwickmm** [comment]
Related to #4179.

**Comment by samuel-w** [comment]
I created a repository for that:
https://gitlab.com/samuel-w/duplicati-deb-rpm-repo
Based on https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo.
Supports both deb and rpm, it just copies the deb and rpm files from releases. Canary branch only.

**Comment by samuel-w** [comment]
I created a repository for that:
https://gitlab.com/samuel-w/duplicati-deb-rpm-repo
Based on https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo.
Supports both deb and rpm, it just copies the deb and rpm files from releases. Both beta and canary branches supported.
