### ISSUE TITLE
[Feature request ] Add estimate time and/or remaining data

### ISSUE THREAD

**Issue by mabed-fr** [duplicati/duplicati#4186]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **2.0.5.1_beta_2020-01-18
- **Fedora release 32 (Thirty Two)
- **Google drive and other cloud provider

## Screenshots

![estimate-time-duplicati](https://user-images.githubusercontent.com/25350431/80800158-179b2980-8ba9-11ea-8071-1cb1bfbc20a4.png)

## Debug log

Hello,

Can you add the remaining time and / or upload progress?

It's possible ?

Thank you verry much for your great job's !

**Comment by ts678** [comment]
> It's possible ?

A wish came up on the forum for an estimated time to completion. You can read why it's generally not possible in [this post](https://forum.duplicati.com/t/show-actual-job-start-time-and-optionally-estimated-time-to-completion/16637/3?u=ts678).

The status bar you post is different from the forum's though. The very end of backup is more possible, but is it still worth it?

BTW if you want to see the remaining upload (in an ugly format), look at About --> System info --> Server state properties.
