### ISSUE TITLE
Feature Request - Add API to web interface

### ISSUE THREAD

**Issue by mmundy1** [duplicati/duplicati#4201]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
Running Duplicati on Windows and FreeNAS

## Description

I'd like to control the jobs via an API so backups can be triggered, blacked out, etc from a central control (in this case Ansible).
This can be done with the commandline tools, which is SUPERB!!
However, adding a Web API, eg Swagger (https://swagger.io/, https://petstore.swagger.io/ ) would also be extremely helpful.

## Steps to reproduce

- **Actual result**:

- **Expected result**:

**Comment by warwickmm** [comment]
Does this provide what you're looking for?

https://github.com/Pectojin/duplicati-client

**Comment by PavelD** [comment]
I see this issue is open already for 4 years. The client as not under maintenance any more and thus latest changes are not propagated into the client.

Isn't good time to reconsider priority and think about the build in solution manged by the developers provided directly by the application?

**Comment by ts678** [comment]
> The client as not under maintenance any more

How so? There was a Canary release yesterday, and a Beta two weeks ago. It looks maintained to me.

[https://github.com/duplicati/duplicati/releases](https://github.com/duplicati/duplicati/releases)

[Forum Releases category](https://forum.duplicati.com/c/releases/10)

**Comment by PavelD** [comment]
It was reaction to the [warwickmm](https://github.com/warwickmm) comment.

From https://github.com/Pectojin/duplicati-client - proposed replacement for the requested swagger:

**A note on maintenance status**

I don't really use duplicati anymore, so maintaining this tool has low priority for me. I probably won't add new features or fix unimportant bugs. I might help out with troubleshooting issues, but I won't make promises.

To my knowledge the tool works fine on all platforms it has been used on, and it is fairly feature complete, so this isn't a declaration of deprecation.. It is just a formal statement about my reprioritization.

**Comment by ts678** [comment]
The 2.1 Beta server doesn't work with that, but has a new [ServerUtil](https://docs.duplicati.com/duplicati-programs/command-line-interface-cli-1/serverutil) command that implements some of what the other does.

[Announcing Remote Backup Management in the Duplicati Console](https://forum.duplicati.com/t/announcing-remote-backup-management-in-the-duplicati-console/19644) from [Duplicati, Inc.](https://forum.duplicati.com/t/introducing-duplicati-inc/17491) may help, depending on the situation.

[Battle plan for dropping `HttpServer`](https://forum.duplicati.com/t/battle-plan-for-dropping-httpserver/18002/34?u=ts678) had discussion that duplicati-client should be easy to update, when/if its dev is up for it.

There's not currently any "ask" that I can find in its [Issues](https://github.com/Pectojin/duplicati-client/issues).

**Comment by ts678** [comment]
[Feature Request - REST API #4100](https://github.com/duplicati/duplicati/issues/4100) (also from 2020) is related.
That has the story of the third-party client. Notably, authentication was its hard part. I don't know if new is easier.

Duplicati devs created ServerUtil (and might take enhancement requests) and some sort of remote management.
I looked at the announcement of that, and at its linked roadmap, and didn't clearly spot new CLI tool in that plan.

@PavelD what are you looking for anyway?

This is all sort of off-topic, as original ask here looks to be for a published stable API (not always easy), not a tool.
There is always more that people would like than can be done. Maybe someone else can do a duplicati-client PR?

**Comment by PavelD** [comment]
[ts678](https://github.com/ts678) I have to say I'm not c# developer.

I was searching what has been changed in the API to get idea what needs to be fixed in the [home assistant integration](https://github.com/txxa/hass-duplicati) with false hope, that it will be easy fix and I will be able to contribute with some simple pull request. When I didn't find any api documentation I was searching for some other python integrations exactly like [duplicati-client](https://github.com/Pectojin/duplicati-client) to gain some inspiration.

One of the easy way how to generate api client is to generate it from swagger ([openapi-python-client](https://github.com/openapi-generators/openapi-python-client)). When I was searching for `swagger and duplicati` I found this feature request.

Next, when I found you point out to the _currently_ not working (in latest beta) and not maintained client I wrote initial comment. I still believe that swagger (open api) is well known and easy way how to provide API documentation - just openapi.json file is enough.

I was looking into the server util source code but as this is completely new tool it was not easy to spot difference between the old API and the current one.

**Comment by ts678** [comment]
> I was searching what has been changed in the API to get idea what needs to be fixed

Please follow my link above for a highly detailed explanation, plus some example code.

> I'm not c# developer.

The cited example code is Python, like project you help, and like duplicati-client project.

> it was not easy to spot difference between the old API and the current one.

Understood. Looking at an existing tool will be easier. I'm not sure if it's enough though.

[https://github.com/duplicati/duplicati/blob/master/Tools/Commandline/pause-resume.py](https://github.com/duplicati/duplicati/blob/master/Tools/Commandline/pause-resume.py)
has a History button, with [Implemented JWT tokens.](https://github.com/duplicati/duplicati/commit/3f29642f6c60304d974df9acd466d09ec64f7dc6) to show a diff of that script's update.

[Increasing security for Duplicati’s web server](https://forum.duplicati.com/t/increasing-security-for-duplicati-s-web-server/18871) describes new scheme, but not at code level.

**Comment by kenkendk** [comment]
@PavelD There is a swagger-exposed API for the debug builds, but it is disabled on release builds for performance/security reasons.

As @ts678 mentions, the replacement for `duplicati-client` is [ServerUtil](https://docs.duplicati.com/duplicati-programs/command-line-interface-cli-1/serverutil).

It does not have all the features found in `duplicati-client`, but you can request the missing features in this github project. 

I do not want to maintain a Python project, but the changes needed are just calling the `/api/v1/login` with the password and extracting the `AccessToken` returned. This token must be inserted as a header on all requests:
```
Authorization: Bearer <token>
```

From there on, everything should work, but the API may change in the future, so reworking the client to using a generated API from the Swagger definition may be nice.

Further [details on the authentication logic](https://docs.duplicati.com/technical-details/server-authentication-model) are also available.

Closing this issue as the requested Swagger definition exists.
