### ISSUE TITLE
Some more typos in the doc

### ISSUE THREAD

**Issue by bugith** [duplicati/duplicati#4211]
Top of all pages : [Edit on squidfunk/mkdocs-material](https://github.com/squidfunk/mkdocs-material/edit/master/docs/03-using-the-graphical-user-interface.md) is a dead link  

[03-usingGUI/#creating-a-new-backup-job](https://duplicati.readthedocs.io/en/stable/03-using-the-graphical-user-interface/#creating-a-new-backup-job)
Last § before the Note : _...selecting Import from a file in the Add backup menu. **N** the next step you can browse..._ should be _...backup menu. **In** the next..._

[04-using-CLU](https://duplicati.readthedocs.io/en/stable/04-using-duplicati-from-the-command-line)
2 dead links to **Storage Providers** (was a chapter, moved to a [new page](https://duplicati.readthedocs.io/en/stable/05-storage-providers/))
1 dead link to **Advanced Options** (was a chapter, moved to a [dedicated page](https://duplicati.readthedocs.io/en/stable/06-advanced-options/))

[/07-other-CLU/#duplicaticommandlinerecoverytoolexe](https://duplicati.readthedocs.io/en/stable/07-other-command-line-utilities/#duplicaticommandlinerecoverytoolexe)
Dead link to **Disaster Recovery**  (was a chapter, moved to a [specific page](https://duplicati.readthedocs.io/en/stable/08-disaster-recovery/))

[08-Disaster recovery](https://duplicati.readthedocs.io/en/stable/08-disaster-recovery/):
_...problems it finds, but **is** there is significant damage_ should be _but **if** there is_

Great soft guys, keep on !

**Comment by warwickmm** [comment]
Thanks!  The user manual is maintained in a separate repository.  Can you move move this issue there?

https://github.com/kees-z/DuplicatiDocs

**Comment by bugith** [comment]
Move ? How do I ? I copied it.
