### ISSUE TITLE
Restore history not working when from S3 "Direct restore from backup files ."

### ISSUE THREAD

**Issue by xp65** [duplicati/duplicati#4219]
- [x] I have searched open and closed issues for duplicates.

## Environment info
- **Duplicati version**: Latest (2.0.5.107_canary_2020-05-26) + earlier versions (tested many). All same result.
- **Operating system**: Windows 10 and Windows Server 2016
- **Backend**: AWS S3 IA

## Description
What works: Restore backup on the machine that created it with selecting the backup as third option and then the history (older backups) can be selected.
What dosen't work: When I choose "Direct restore from backup files" on the system OR on an other system in a different Duplicati installation, then ONLY the latest backup can be loaded, Going back in history always crashes with a warning without that the backup can be restored.

2020-06-09 19:29:28 +02 - [Warning-Duplicati.Library.Main.Operation.RecreateDatabaseHandler-FileProcessingFailed]: Failed to process file: duplicati-20200608T003000Z.dlist.zip.aes

The file duplicati-20200608T003000Z.dlist.zip.aes is available and existing in S3.
This error is on 20+ active backups, none are able to restore as expected this way on an other system from an older backup than the latest.

**Comment by ts678** [comment]
Is this still an issue? If so, please have About --> Show --> Live --> Warning up while causing the issue, and click on the warning.
