### ISSUE TITLE
Invalid URI: The Uri string is too long

### ISSUE THREAD

**Issue by aand18** [duplicati/duplicati#4221]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1
- **Operating system**: Win 10 x64
- **Backend**: Minio

## Description

Monitoring server receives no report. Logs have this error:

```
[Warning-Duplicati.Library.Modules.Builtin.ReportHelper-ReportSubmitError]: Failed to send message: System.UriFormatException: Invalid URI: The Uri string is too long.

System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at Duplicati.Library.Modules.Builtin.SendHttpMessage.SendMessage(String subject, String body)
   at Duplicati.Library.Modules.Builtin.ReportHelper.OnFinish(Object result)
```

## Steps to reproduce

1. Have a really long URL when reporting 

- **Actual result**:
Error and monitoring server receives no report.
- **Expected result**:
No error

See possible solution at https://forum.duplicati.com/t/duplicati-skipping-lots-of-files-folders/6957/8

**Comment by warwickmm** [comment]
This is an issue that affects all .NET framework versions.  The workarounds sound a bit unsatisfactory, but this has been [fixed](https://github.com/dotnet/corefx/pull/41686) in .NET Core 5.0.  There [ongoing work](https://github.com/duplicati/duplicati/pull/3124) to port Duplicati to .NET 5.
