### ISSUE TITLE
Problem with import in development build

### ISSUE THREAD

**Issue by jpschewe** [duplicati/duplicati#4233]
I'm building using monodevelop on Linux. When I build and execute I can create new jobs, but I can't import any jobs. After selecting the file I click on Import and see Importing, but nothing happens after that. Is this expected when running from a development version?
I'm building commit b8e1f8f4d.

**Comment by warwickmm** [comment]
I just tried importing a configuration using a debug build from b8e1f8f4de4514dcd24c544cadb6f184714c4302 and had no issues.

Can you try cleaning and building again?

**Comment by warwickmm** [comment]
If that doesn't work, you can try putting a breakpoint here and step through to see if anything interesting occurs:

https://github.com/duplicati/duplicati/blob/ebf7346960b0d93d2ee74570c2f6d3adffe68bab/Duplicati/Server/WebServer/RESTMethods/Backups.cs#L127

**Comment by jpschewe** [comment]
I put the breakpoint in and then the import succeeded. However monodevelop never stopped me at the breakpoint.

I have also noticed that even when I click the stop button in monodevelop the application keeps running. Is there a better IDE to use or instead use the command line? monodevelop seems to give me random warnings about bad images and it pegs 1 CPU most of the time.

```
=== MonoDevelop ===

Version 7.8.4 (build 2)
Installation UUID: 6216d1fb-a2f6-46f3-8e86-43fdbabe3f6f
	GTK+ 2.24.32 (Ambiance theme)

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.123 (tarball Tue May 12 15:11:57 UTC 2020) (64-bit)

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: Not installed
SDK: Not installed
MSBuild SDKs: /usr/lib/mono/msbuild/15.0/bin/Sdks

=== Build Information ===

Release ID: 708040002
Git revision: 622db12503514afdb641c31615408bfe905a7312
Build date: 2019-07-17 17:02:07-04

=== Operating System ===

Linux
Linux 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
```

**Comment by warwickmm** [comment]
I would encounter a few rare issues with monodevelop, but in general it worked pretty well.  I much prefer Rider, but it isn't free and has its own issues setting breakpoints sometimes as well.
