### ISSUE TITLE
Theme selection is reset. Dark theme vs light theme

### ISSUE THREAD

**Issue by Robespeler** [duplicati/duplicati#4243]
I endured for a long time and decided to share.
Did you pay attention that after choosing dark theme it is reset after next login?
Maybe it is a bug?

Besides, I think light theme is too bright to be distinguishable. Maybe we should change it a little?

Windows x64, Mozilla Firefox
Other settings are good standing

**Comment by warwickmm** [comment]
Thanks @Robespeler.  I think this duplicates issue #3851.
