### ISSUE TITLE
Deleting 1/2 backup jobs to same location deletes all backed up files

### ISSUE THREAD

**Issue by Champ-Goblem** [duplicati/duplicati#4244]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Linux Mint 19
- **Backend**: SFTP Server

## Description

When creating two backups to the same location and deleting one, all backups in that location get deleted even though the deletion message states x files with y size.

## Steps to reproduce

1. Create first backup and run it
2. Create second backup, to the same location with different source files, run it
4. Delete second backup
5. All files deleted

- **Actual result**:
All files get deleted in the remote storage even though the delete confirmation page states only the files from that backup job will be deleted.
- **Expected result**:
Only the files that are exclusive to that backup job should be deleted

## Debug log

Not applicable

This issue sounds quite similar to #3845

**Comment by ts678** [comment]
> Only the files that are exclusive to that backup job should be deleted

[Creating a new backup job](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#creating-a-new-backup-job) in the manual warns:

![image](https://user-images.githubusercontent.com/40771998/86499090-3065be00-bd57-11ea-9782-9b9efacdf37b.png)

although it's actually more operations than just backup. If you absolutely have to use the same folder, use [prefix](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#prefix) option, which is supposed to let Duplicati know which files go with which backup. There are sometimes no other records. for example if DB is lost.

I haven't tried it, but if that case deletes the way it does when both take the same prefix, that'd be a bug. I'm not sure this one is,
aside from the message not matching the actual result in the case of an illegal configuration of two backups to the same location.

My thought. Other Duplicati volunteers may or may not agree. Note help for `prefix` has a typo of `duplicate` for `duplicati`.

**Comment by warwickmm** [comment]
The deletion should respect the prefix
https://github.com/duplicati/duplicati/blob/7a0ffd46e121970b4c6e38c8639803cdb46e1269/Duplicati/Library/Main/Controller.cs#L212-L217
