### ISSUE TITLE
"0 files need to be restored" when restoring from command line

### ISSUE THREAD

**Issue by pomeloy** [duplicati/duplicati#4268]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1
- **Operating system**: Windows 10 2004
- **Backend**: WebDAV

## Description

Restoring from a WebDAV destination via command line yields `Restore completed without errors but no files were restored`, restoring via GUI works.

## Steps to reproduce

1.  Open the GUI
2. Go to the command line interface for the affected backup
3. Copy all options and paste into the command line
4. Run `Duplicati.CommandLine.exe restore` with the aforementioned options and `--no-local-blocks` and `--restore-path=***`

- **Actual result**:
```
Restore started at ***
Checking remote backup ...
  Listing remote folder ...
Checking existing target files ...
  0 files need to be restored (0 Bytes)
Verifying restored files ...
Restore completed without errors but no files were restored
Restored 0 (0 Bytes) files to ***
Duration of restore: 00:00:02
```
- **Expected result**:
Restore completes successfully.
When running the same exact command from the GUI, everythings works.

```
Restore started at ***
Checking remote backup ...
  Listing remote folder ...
  ***files need to be restored (*** GB)
Checking existing target files ...
  Downloading file (*** KB) ...
```

I created a new backup in order to reproduce the issue but it worked flawlessly, just like two of the four backups to this target. I already re-created the database to no avail.

## Cause
User error! I did not enquote some parameters. The GUI backend probably enquotes them automatically.

**Comment by pomeloy** [comment]
I am still trying to understand what happened here. The fix was enquoting the two-part backup name `--backup-name=`. Still, the command worked without quotes for two out of the four backups. Say the command looked like this:
`Duplicati.CommandLine.exe restore webdavs://*** --no-local-blocks --restore-path=*** --backup-name=placeholder name` Would the part `name` then be regarded as the file to restore? What makes this exact constellation work if there is no such file and the command in question yielded a full restore and not just a single file?

**Comment by warwickmm** [comment]
I believe `-backup-name=placeholder name` would try to interpret `name` as a new command line argument, and not part of the value provided to `--backup-name`.

This sounds loosely related to issue #2905.

**Comment by warwickmm** [comment]
`Restore completed without errors but no files were restored` can occur when the target destination already contains a file that matches what is stored on the backend.

Parameter values need to be enclosed in quotes if their values contain spaces or other special characters.

I believe this is working as expected, so I'm going to close this.  If you feel that there is an issue that needs to be fixed, please feel free to reopen this.
