### ISSUE TITLE
Local backup never finishes

### ISSUE THREAD

**Issue by funnym0nk3y** [duplicati/duplicati#4276]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.108_canary_2020-07-09
- **Operating system**: Win10 1909
- **Backend**: Local

## Description
When running a backup-job to a local hard drive Duplicati hangs with the last junk of data (1-5MB) and never finishes. The speed drops constantly. 

- **Actual result**:
The backup does not finish properly bit hangs at the end. 
- **Expected result**:
Backup should finish gracefully.

**Comment by warwickmm** [comment]
Performance depends a lot on configuration, size of source files, hardware, etc.  You'll probably get better support for this type of issue in the forums:

https://forum.duplicati.com/

**Comment by funnym0nk3y** [comment]
In my opinion it's not a performance issue. The backup to a local hard drive runs at speeds of 2-5 MB/s. When getting close to the end, nothing is transferred and it stalls. No matter how long I let the job run, it never finishes. In addition the job can't be cancelled.

**Comment by warwickmm** [comment]
I think you'll still have better luck in the forums.  There are a lot more users over there, and some may have experienced the same issue.  Feel free to create a post in the forums and include a link to the post here.  You'll likely have to capture some logs in order to get some more meaningful help.
