### ISSUE TITLE
Oh dear... last version of 2.0.4 also NOT WORKING: "resource not found localhost:8200"

### ISSUE THREAD

**Issue by Mrodent** [duplicati/duplicati#4282]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.4.38
- **Operating system**: W10
- **Backend**: ?
- Browser: FF

## Description
Oh terrible. I just uninstalled 2.0.5 for the reasons given in the previous issue. Then I downloaded and installed 2.0.4.38... I immediately get a message saying Resource not found: http://localhost:8200/ ... and of course there's nothing in these archives about it, just as there wasn't with the previous issue "passphrases do not match".

Deeply irritating. And no sign of anyone experiencing similar problems.

Please can you state excplicitly what is meant to be **the latest stable version for use on W10**? Thanks

## Steps to reproduce

1. Replace me
2. Replace me
3. ...

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by warwickmm** [comment]
2.0.5.1 is the right version to use.  I haven't heard of this issue before.  You'll might have better luck asking this in the forums.

https://forum.duplicati.com/

**Comment by warwickmm** [comment]
One thing to check is to see if there's an overly aggressive anti-virus program getting in the way.  Again, the best place for this type of question is in the forums.  Feel free to add a link here to your forum post to help others that might encounter this issue.  If we find that there's something in the code that we can fix, we can reopen this issue.
