### ISSUE TITLE
Error when creating mega backup with latest canary version in docker image

### ISSUE THREAD

**Issue by TheEggi** [duplicati/duplicati#4289]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.110_canary_2020-08-10
- **Operating system**: Docker imaage
- **Backend**: Mega.nz

## Description
Following error occurs:
`Could not find method '.ctor' due to a type load error: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:/opt/duplicati/SharpAESCrypt.exe type:SharpAESCrypt member:(null)
`
## Steps to reproduce
1. Get the docker image
2. Create a mega.nz backup job
3. Start it
4. Error is shown

## Screenshots
![image](https://user-images.githubusercontent.com/1206407/90596269-e180c480-e1ee-11ea-8c93-6b5f53a5dd4b.png)

**Comment by warwickmm** [comment]
Which docker image?  The official one or a different one?  Can you see what version of mono is available in the container?  Duplicati 2.0.5.110 requires mono 5.10 or greater.

**Comment by TheEggi** [comment]
Image from dockerhub is the official canary version. (duplicati/duplicat:canary).

**Comment by warwickmm** [comment]
Does using a local backend work, or does that fail as well?

**Comment by pizzaboy75** [comment]
I am having the same issue with the official Docker image for armv7 and amd64 as well.

**Comment by drwtsn32x** [comment]
@warwickmm - sorry, didn't see you ask me a question.

I just tested it and confirmed the issue as well, but I see you were also able to reproduce the issue. Glad you found a solution!

**Comment by warwickmm** [comment]
No problem @drwtsn32x.  I finally fixed my ability to build and test the docker locally. :smile:

**Comment by TheEggi** [comment]
Seems to be fixed in the latest version.

**Comment by mcronce** [comment]
I'm seeing this on a freshly-pulled `duplicati/duplicati:2.0.5.110_canary_2020-08-10` - was an image with the fix ever pushed up to dockerhub?

**Comment by TheEggi** [comment]
At least I still see the error after the update. Guess the issue needs to be reopened.

**Comment by warwickmm** [comment]
The pull request hasn’t been merged yet, but the fix should be part of the next release.

**Comment by mcronce** [comment]
Got it.  I didn't notice that, but saw that it was merged after you made that comment.  Thanks!
