### ISSUE TITLE
Restore file tree icon problem

### ISSUE THREAD

**Issue by drwtsn32x** [duplicati/duplicati#4294]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.110

## Description

When browsing for files to restore, the "wait" animated icon (while the tree is loading) s now not shown properly.  Looks like it's the wrong scale perhaps.

I first noticed this when I installed 2.0.5.110, but it's possible it was present in earlier builds.

## Screenshots
![Untitled](https://user-images.githubusercontent.com/39164691/91103539-90266a00-e620-11ea-89c5-fcf708b92f78.png)

**Comment by drwtsn32x** [comment]
Looks like the problem started with 2.0.5.108.

**Comment by drwtsn32x** [comment]
Perhaps PR https://github.com/duplicati/duplicati/pull/4214 ?

**Comment by warwickmm** [comment]
Are `loader-16.gif` and `loader-32-gif` the relevant files?

https://github.com/duplicati/duplicati/blob/145ef49b91fc43a77dabfb66cd8ae3c8b7ca93c2/Duplicati/Server/webroot/ngax/less/style.less#L2523-L2535

**Comment by drwtsn32x** [comment]
Yes, those are the relevant gifs.

**Comment by warwickmm** [comment]
Interesting.  It looks like in revision e84d332361a1b24729be2c7d8bc789d93c6af071, those files became smaller:
```
$ git show --stat e84d332361a1b24729be2c7d8bc789d93c6af071 | grep loader
 Duplicati/Server/webroot/ngax/img/loader-16.gif    | Bin 1720 -> 1434 bytes
 Duplicati/Server/webroot/ngax/img/loader-32.gif    | Bin 3208 -> 1785 bytes
```

**Comment by warwickmm** [comment]
I tried reverting those two files, but it still didn't behave as expected.  What I then discovered (both with the reverted files and with the `master` branch) was that if I zoomed in the page 125%, then the loading icon appeared normally.  Can anyone reproduce this?

**Comment by drwtsn32x** [comment]
Yep, you're right. If I zoom in the problem goes away.  If it's not with the raw gif files maybe the problem is with the stylesheet or somewhere else in the html code.

**Comment by warwickmm** [comment]
I was able to confirm that the icon appears as expected (at a normal zoom level) with version 2.0.5.107.

Could this be a browser issue?  @drwtsn32x, what browser are you using?  

I'm on Brave Version 1.12.114 Chromium: 84.0.4147.135 (Official Build) unknown (64-bit).

**Comment by drwtsn32x** [comment]
I tested with Chrome, Edge, Firefox, and even IE11.  They all exhibited the issue with >= 2.0.5.108.

**Comment by warwickmm** [comment]
@drwtsn32x, the changes in pull request #4299 fix the problem for me.  Can you test when you get a chance?

**Comment by drwtsn32x** [comment]
Oops, I didn't mean to close this. Was just merging  your pull request into my fork so I could test.

**Comment by drwtsn32x** [comment]
@warwickmm - works great!

**Comment by warwickmm** [comment]
Great!  Thanks for testing.
