### ISSUE TITLE
Unable to restore 40G backup 

### ISSUE THREAD

**Issue by pcmind** [duplicati/duplicati#4296]
## Environment info
* Duplicati version: 2.0.5.110_canary_2020-08-10
* Operating system: Windows 10
* Backend: File

## Description
Created backup successfully of a 40Gb workspace with more or less 2000000 Files. Backup took less than 30min.

Backup was executed twice; on the second run only one file was added (because .pst file was locked on the firt run).

It should be possible to restore files to a **new** location without issue but after multiple hours, we must kill the process because it hangs "forever" and it is not possible to cancel it though web interface.

A similar issue was reported in the past #1391, but in this case a **local database** is present and restore is done to a **different** location.

## Steps to reproduce
1. Backup a folder with 40GB worth of files and folders with more or less 2000000 Files and Folders (in original case: cache files, settings, git repositories)
2. Execute a second backup
3. Restore backup to a new location
4. It should finish successfully in timely manner (at most 1h?), but even after 4h it is still not restoring files.

## Root cause analysis

Restore take a long time to reach this query then nothing for hours:
```
 SELECT DISTINCT "Fileset-DB08F4430E7B9146A67D34B441272B87"."TargetPath", "Fileset-DB08F4430E7B9146A67D34B441272B87"."Path", "Fileset-DB08F4430E7B9146A67D34B441272B87"."ID", "Blocks-DB08F4430E7B9146A67D34B441272B87"."Index", "Blocks-DB08F4430E7B9146A67D34B441272B87"."Hash", "Blocks-DB08F4430E7B9146A67D34B441272B87"."Size" FROM "Fileset-DB08F4430E7B9146A67D34B441272B87", "Blocks-DB08F4430E7B9146A67D34B441272B87", "File", (SELECT "File"."Path", "File"."BlocksetID", MAX("Fileset"."Timestamp") FROM "Fileset", "FilesetEntry", "File" WHERE "FilesetEntry"."FileID" = "File"."ID" AND "FilesetEntry"."FilesetID" = "Fileset"."ID" AND "File"."Path" IN (SELECT DISTINCT "Fileset-DB08F4430E7B9146A67D34B441272B87"."Path" FROM "Fileset-DB08F4430E7B9146A67D34B441272B87", "Blocks-DB08F4430E7B9146A67D34B441272B87" WHERE "Fileset-DB08F4430E7B9146A67D34B441272B87"."ID" = "Blocks-DB08F4430E7B9146A67D34B441272B87"."FileID" AND "Blocks-DB08F4430E7B9146A67D34B441272B87"."Restored" = 0 AND "Blocks-DB08F4430E7B9146A67D34B441272B87"."Metadata" = 0 AND "Fileset-DB08F4430E7B9146A67D34B441272B87"."TargetPath" != "Fileset-DB08F4430E7B9146A67D34B441272B87"."Path" ) GROUP BY "File"."Path" ) S, "Block", "BlocksetEntry" WHERE "BlocksetEntry"."BlocksetID" = "S"."BlocksetID" AND "BlocksetEntry"."BlocksetID" = "File"."BlocksetID" AND "BlocksetEntry"."BlockID" = "Block"."ID" AND "Blocks-DB08F4430E7B9146A67D34B441272B87"."Index" = "BlocksetEntry"."Index" AND "Blocks-DB08F4430E7B9146A67D34B441272B87"."Hash" = "Block"."Hash" AND "Blocks-DB08F4430E7B9146A67D34B441272B87"."Size" = "Block"."Size" AND "S"."Path" = "Fileset-DB08F4430E7B9146A67D34B441272B87"."Path" AND "Fileset-DB08F4430E7B9146A67D34B441272B87"."ID" = "Blocks-DB08F4430E7B9146A67D34B441272B87"."FileID" AND "Blocks-DB08F4430E7B9146A67D34B441272B87"."Restored" = 0 AND "Blocks-DB08F4430E7B9146A67D34B441272B87"."Metadata" = 0 AND "Fileset-DB08F4430E7B9146A67D34B441272B87"."TargetPath" != "Fileset-DB08F4430E7B9146A67D34B441272B87"."Path" ORDER BY "Fileset-DB08F4430E7B9146A67D34B441272B87"."ID", "Blocks-DB08F4430E7B9146A67D34B441272B87"."Index"
```

This happen when restoring all files or even 500000 (25%). Restoring a few files, like 10, is executed successfully.

The aforementioned query is from [#GetFilesAndSourceBlocksFast](https://github.com/duplicati/duplicati/blob/535268d1f7b88028209b76b98008816c1d601219/Duplicati/Library/Main/Database/LocalRestoreDatabase.cs#L1242). 

It is not possible to cancel the operation from web interface because query is still been computed in the DB in `cmd.ExecuteReader(sources)`.

**Comment by warwickmm** [comment]
Thanks for reporting this.  I think this is the same query that is mentioned in #3452.  Let's focus our discussion there.
