### ISSUE TITLE
Execution order of missed backup jobs 

### ISSUE THREAD

**Issue by huste** [duplicati/duplicati#4298]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.110
- **Operating system**: Windows 10
- **Backend**: irrelevant

## Description
I have several backup jobs on my machine. They are scheduled daily on specific times. Some take longer (whole archive hard disk), some take shorter (Thunderbird Mail backup).

The scheduled time of the jobs is
1: 06:00
2: 07:01
3: 05:00

The third job was created last. When I start my computer and all three have not been executed yet, the execution order is 1, 2, 3. I'd expect 3,1,2 as 05:00 was the first missed time

Is there any chance of seeing missed jobs being executed in the order of the missed times?

Thanks for reading
Stefan

**Comment by warwickmm** [comment]
@huste, when you say the execution order is 1, 2, 3, does that mean we can close issue #1476?

**Comment by warwickmm** [comment]
Duplicate if #1476.
