### ISSUE TITLE
Duplicate file reported on network drive

### ISSUE THREAD

**Issue by jpd236** [duplicati/duplicati#4303]
- [x] I have searched open and closed issues for duplicates.

(I found a similar bug where Google Drive is the destination. But nothing for network drives, where the issue seems impossible in nature).

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.0_experimental_2020-01-03
- **Operating system**: Windows 10
- **Backend**: "Local folder or drive," set to `\\10.1.10.9\Public\Backup\Duplicati\`

## Description

My weekly backup is suddenly failing with this error:

```
Found remote files reported as duplicates, either the backend module is broken or you need to manually remove the extra copies. The following files were found multiple times: duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes
```

The remote logs indeed show two identical entries back to back for this file:

```
{"Name":"duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes","LastAccess":"2020-08-30T21:23:46.1546735-07:00","LastModification":"2020-08-09T21:12:29.0477436-07:00","Size":52342077,"IsFolder":false},
{"Name":"duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes","LastAccess":"2020-08-30T21:23:46.1546735-07:00","LastModification":"2020-08-09T21:12:29.0477436-07:00","Size":52342077,"IsFolder":false},
```

but if I run "dir" from the folder from the command line (using the mapped network drive "Z" instead, pointing to the same drive), there is naturally only one file there:

```
Z:\Backup\Duplicati>dir duplicati-b1a597*
 Volume in drive Z is Public
 Volume Serial Number is C1DC-C5A0

 Directory of Z:\Backup\Duplicati

08/09/2020  09:12 PM        52,342,077 duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes
               1 File(s)     52,342,077 bytes
               0 Dir(s)  513,844,117,504 bytes free
```

How is Duplicati listing files in a way that could result in a dupe like this? How do I resolve this? I tried removing and recopying the file over but still have the same problem. (If I delete it, it tells me the backup is out of sync; I'm hesitant to repair it and lose data).

The drive is a Western Digital My Book Live. It has 1.5 TiB of 2 TiB used.

**Comment by jpd236** [comment]
I attempted to delete and recreate the database and got this error:

```
constraint failed UNIQUE constraint failed: Remotevolume.Name, Remotevolume.State
```

and the list operation still showed the duplicate files. So it seems that the problem is the listing from the remote drive rather than corruption in the local database.

**Comment by jpd236** [comment]
Looks like I might have been able to work around it for now by enabling SSH on my drive and using SFTP instead.

**Comment by warwickmm** [comment]
Not sure why this would happen.  Can you check the output of the following to see if the duplicate file appears?
```
Duplicati.CommandLine.BackendTool.exe list \\10.1.10.9\Public\Backup\Duplicati\
```

**Comment by jpd236** [comment]
I ran that command, and the file showed up exactly once in the resulting list - note that this is now after a successful couple backups with SFTP:

```
duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes	File	8/9/2020 9:12:29 PM	49.92 MB
```

So I decided to try reverting my settings away from SFTP and making another backup. That backup seemed to succeed, but at the end I got a warning about a file missing from the backup, which was, of course, this exact file:

```
The backup storage destination is missing data files. You can either enable `--rebuild-missing-dblock-files` or run the purge command to remove these files. The following files are missing: duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes
```

Except... it's there:

```
>dir \\10.1.10.9\Public\Backup\Duplicati\duplicati-b1a597*
 Volume in drive \\10.1.10.9\Public is Public
 Volume Serial Number is C1DC-C5A0

 Directory of \\10.1.10.9\Public\Backup\Duplicati

08/09/2020  09:12 PM        52,342,077 duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes
               1 File(s)     52,342,077 bytes
               0 Dir(s)  826,118,963,200 bytes free
```

Now, when I run the Duplicati list command, the file is indeed not there. And that appears to be the only discrepancy between the "dir" command and that list command.

This is so strange - why is this particular file so consistently problematic?

**Comment by warwickmm** [comment]
This is strange, I'm not sure what could cause this.  We basically (aside from some tweaks to deal with extremely long paths, which I don't think apply here) rely on the .NET framework to retrieve directory listings and are at the mercy of what the storage device reports.  Apparently this check was explicitly put in (0b7e35297ab69845bb1864850e1b7270e3db2251) to notify the user of potential issues with the backend storage, so my guess is that this issue has happened before.

You mentioned deleting the file and recopying it.  Can you instead try rename the offending file to something, and then rename it back to the original name?  Then, see what the `dir` and `list` commands yield?

Also, does the drive have any sort of diagnostic tools that can be run to verify its integrity?

**Comment by jpd236** [comment]
The drive has a diagnostic test to scan for bad sectors. I ran it over the past few hours, but it passed with no detected issues.

After re-running the list command to verify the file still wasn't showing up, I renamed it to "temp" and it showed up:

```
temp	File	8/9/2020 9:12:29 PM	49.92 MB
```

After renaming it back to the correct name, it disappeared again!

**Comment by jpd236** [comment]
In case it's relevant - there are currently 13,066 files in that directory.

**Comment by warwickmm** [comment]
That's really bizarre.  Are you able to try a reboot of everything?

**Comment by jpd236** [comment]
Rebooted the drive and my computer (and also took a bunch of Windows updates for the latter). Still missing from Duplicati list but present in dir list.

**Comment by warwickmm** [comment]
This is strange.  We have recently cleaned up our treatment of UNC and long paths, but I haven't heard of any other reports of something like this.  Do you want to try posting in the forums to see if someone else might have some ideas?

https://forum.duplicati.com/

**Comment by warwickmm** [comment]
What version of the .NET framework do you have installed?  The version of Duplicati you're using (2.0.5.0_experimental_2020-01-03) requires .NET 4.6.2 or greater.

I believe it's possible to invoke .NET library methods from  PowerShell, so you could try something like
```
C:\> [System.IO.Directory]::EnumerateFiles('\\10.1.10.9\Public\Backup\Duplicati\')
```

**Comment by jpd236** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\Release is 528372 which appears to be version 4.8 from a quick search.

The PowerShell command shows the same inconsistency, so it's clearly something unexpected happening at that level:

```
PS C:\Users\Jeff> [System.IO.Directory]::EnumerateFiles('\\10.1.10.9\Public\Backup\Duplicati\') | Select-String -Pattern b1a5979538b6e446f886af67ffc06c145
PS C:\Users\Jeff> dir \\10.1.10.9\Public\Backup\Duplicati\duplicati-b1a5979538b6e446f886af67ffc06c145*


    Directory: \\10.1.10.9\Public\Backup\Duplicati


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          8/9/2020   9:12 PM       52342077 duplicati-b1a5979538b6e446f886af67ffc06c145.dblock.zip.aes


PS C:\Users\Jeff>
```

**Comment by warwickmm** [comment]
Very interesting.  I see that you've created an issue with dotnet so I'm going to close this one.  Feel free to reopen if you think there's anything we can do here.

**Comment by jpd236** [comment]
FYI - per that bug, the issue appears to be limited to .NET Framework (which Duplicati and built-in PowerShell both use) - it is not present in .NET Core, based on my testing with PowerShell Core. Seems like migrating to .NET Core is being considered in #2864 - perhaps this is another argument in favor.

But as instructed there, I did report the bug for .NET Framework at https://developercommunity.visualstudio.com/content/problem/1182792/getfilesenumeratefiles-returns-invalid-results-for.html
