### ISSUE TITLE
Debian RFP (Request For Packaging)

### ISSUE THREAD

**Issue by borisbarbour** [duplicati/duplicati#4305]
Just linking this here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969188

It seems little work would be required to finalise a Debian package that could be included in the distribution. 
The pros include secure and broad distribution, the cons include the long life of older versions.
I think Duplicati would fill a very useful niche in Debian.

**Comment by warwickmm** [comment]
Thanks @borisbarbour.  This sounds related to #4179.  Is this a request for work to be done here, or is this simply informative?

Given our lack of resources, I think this is best done by separate maintainers for the various distributions.

For example, there are people who have volunteered to be maintainers for the beta and canary channel packages for Arch:

https://aur.archlinux.org/packages/duplicati2-beta/
https://aur.archlinux.org/packages/duplicati-latest/

**Comment by borisbarbour** [comment]
This is totally wishlist. I understand that it is likely that neither project has the bandwidth to do this, but I thought it was worth making the suggestion where any interested people could find it and centralise any discussion/work. I did see the other request, but as I understand it the suggestion here is slightly separate - to get Duplicati included in the Debian distribution, not to provide a parallel architecture for distribution of a Debian package.

**Comment by warwickmm** [comment]
While it would be nice to get this into the various distribution package repositories, we unfortunately just don't have the bandwidth for this.  I'm going to close this for now, but if some volunteer wants to take this on and there's any required action/discussion, feel free to reopen this.
