### ISSUE TITLE
Duplicati stuck at 0% backuping own SQLITE database file in appdata

### ISSUE THREAD

**Issue by Naklarsuper** [duplicati/duplicati#4308]
Backup seemed to progress until the file xxxxx.sqlite in Duplicati appdata local folder (the database for this very backup) remained stuck at 0%. Had to stop Duplicati process via task manager, remove medium, and restart from scratch, repair database, then it worked again. 

Could not reproduce so far. 

Latest Windows 10, Duplicati - 2.0.5.1_beta_2020-01-18

**Comment by drwtsn32x** [comment]
You should exclude the Duplicati databases from your backup.  There is no benefit to having a backup job back up its own sqlite database.  If the database ever got deleted or damaged, it would need to be recreated from the back end data before any restores could be done.  And once it's recreated you wouldn't need to restore it anyway!

**Comment by Naklarsuper** [comment]
Understood, thank you. So what I have observed was expected behavior that can be prevented by excluding the databases?

**Comment by drwtsn32x** [comment]
Yes, I recall seeing a couple other reports over the years of Duplicati failing when it tried to back up its own database.

IMO Duplicati should probably auto-exclude the job specific sqlite file from the backup.

**Comment by Naklarsuper** [comment]
Agree. Thank you. Closing the issue.
