### ISSUE TITLE
python-is-python2 is deprecated and can break modern software

### ISSUE THREAD

**Issue by HeRo002** [duplicati/duplicati#4316]
## Description

Actually, not much information is needed to describe this bug. Some may even argue that it's a feature request. 

The thing is that Duplicati (on Ubuntu 20.04) installs the package 'python-is-python2', which creates the file /usr/bin/python which is a symlink to /usr/bin/python2.7. 

This kind of laziness from the developers of Duplicati puts newer software, that need python3 at risk of crashing. I am more or less citing the description of the package - see below.

I am going to develop complex Python3 software on my Ubuntu 20.04, with large amount of dependencies, so Duplicati puts my project at risk of failure or problems that could have been avoided if Duplicati had not installed the /usr/bin/python symlink to /usr/bin/python2.7. I would therefore be very glad if your could correct this as fast as possible. 

Description of python-is-python2:

" In Ubuntu, all python packages use explicit python3 or python2
interpreter and do not use unversioned /usr/bin/python at all. Some
third-party code may still be python2 based, yet may use
/usr/bin/python.

This is a convenience package which ships a symlink to point
/usr/bin/python interpreter at the current default python2. It may
improve compatibility with obsolete 3rd-party software, whilst
breaking some modern software.

This package will be installed upon upgrades to Ubuntu 20.04, if
DEPRECATED python2 was installed.

python2 is DEPRECATED and will not be provided in the future Ubuntu
release. It is recommended to remove python2 and this package after
ensuring that only python3 is in use.

No packages may declare dependencies on this package. "

- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.5.1_beta_2020-01-18
- **Operating system**: Ubuntu 20.04.1 LTS
- **Backend**: Backblaze B2

## Debug log

I DID create a 'bug report' zip file in Duplicati. Here is the content of the 'system-info.txt'-file: 

Duplicati: Duplicati.Server, Version=2.0.5.1, Culture=neutral, PublicKeyToken=null (Duplicati.Library.Main, Version=2.0.5.1, Culture=neutral, PublicKeyToken=null)
Autoupdate urls: https://updates.duplicati.com/beta/latest.manifest;https://alt.updates.duplicati.com/beta/latest.manifest
Update folder: /home/henrik/.config/Duplicati/updates
Base install folder: /usr/lib/duplicati
Version name: "2.0.5.1_beta_2020-01-18" (2.0.5.1)
Current Version folder /usr/lib/duplicati
OS: Unix 5.4.0.47
Uname: Linux henrik-thinkpad-20-04 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
64bit: True (True)
Machinename: henrik-thinkpad-20-04
Processors: 4
.Net Version: 4.0.30319.42000
Mono: True (6.8.0.105) (6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020))
Locale: en-GB, en-GB, en-GB
Date/time strings: dd MMMM yyyy - HH:mm:ss
Tempdir: /tmp/
SQLite: 3.31.1 - Mono.Data.Sqlite.SqliteConnection
SQLite assembly: /usr/lib/mono/gac/Mono.Data.Sqlite/4.0.0.0__0738eb9f132ed756/Mono.Data.Sqlite.dll

**Comment by HeRo002** [comment]
This is how Duplicati installs python-is-python2:

:~$ sudo apt install apt-transport-https sudo nano git-core python software-properties-common dirmngr
[sudo] password for henrik: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
Note, selecting 'python-is-python2' instead of 'python'

**Comment by drwtsn32x** [comment]
```
:~$ sudo apt install apt-transport-https sudo nano git-core python software-properties-common dirmngr
```
Where did you get those instructions?  The debian package itself has no dependency on python.

**Comment by drwtsn32x** [comment]
Never mind I see it here https://duplicati.readthedocs.io/en/latest/02-installation/

It does say "maybe optional".  I don't think you need it at all.  I question what most of those things have to do with duplicati.

**Comment by HeRo002** [comment]
Now I am confused...!

**Comment by HeRo002** [comment]
Isn't large parts of Duplicati written in Python2?

**Comment by HeRo002** [comment]
By the way: 

This is the paragraph on Python in the Ubuntu 20.04 release notes - https://wiki.ubuntu.com/FocalFossa/ReleaseNotes :

Other base system changes since 18.04 LTS

Python3 by default

In 20.04 LTS, the python included in the base system is Python 3.8. Python 2.7 has been moved to universe and is not included by default in any new installs.

Remaining packages in Ubuntu which require Python 2.7 have been updated to use /usr/bin/python2 as their interpreter, and /usr/bin/python is not present by default on any new installs. On systems upgraded from previous releases, /usr/bin/python will continue to point to python2 for compatibility. Users who require /usr/bin/python for compatibility on newly-installed systems are encouraged to install the python-is-python3 package, for a /usr/bin/python pointing to python3 instead.

Due to this transition the legacy python and python-minimal packages might be removed during an upgrade, being replaced by the python2 and python2-minimal packages as dependencies of the python-is-python2 package.

**Comment by drwtsn32x** [comment]
@HeRo002 

> Isn't large parts of Duplicati written in Python2?

No, it is almost entirely C# so uses the .NET framework (which is why mono is a dependency on non-Windows platforms).  The only python stuff included in Duplicati is a few scripts as far as I know, which is why I'm puzzled about the instructions to install python and other things to get Duplicati working -- it isn't needed for core functionality.

**Comment by HeRo002** [comment]
OK... I removed the 'python-is-python2' package and thus the '/usr/bin/python' symlink file. I restarted everything (including Ubuntu 20.04), opened the Firefox browser, deleted its cache, logged into Duplicati and started a backup. It finished without any errors or warnings. Although the small popup-window at the bottom of the screen said 1 warning... 
So far so good... But I would feel more secure if the Duplicati project was updated to insure that non of the Python scripts use /usr/bin/python.

**Comment by HeRo002** [comment]
NB. It would also be very nice if there wasn't all this confusion about whether the documentation is up to date... ;-)

**Comment by warwickmm** [comment]
Feel free to create a ticket to fix the documentation here:

https://github.com/kees-z/DuplicatiDocs/issues

**Comment by warwickmm** [comment]
> But I would feel more secure if the Duplicati project was updated to insure that non of the Python scripts use /usr/bin/python.

I'm not a python expert, so I don't quite understand this.  Isn't it up to the user to decide how the script is called?  For example,
```
$ python2 my_script.py
$ python3 my_script.py
```
It's not clear to me if there's any work to be done here.

**Comment by HeRo002** [comment]
The Duplicati install guide asks you to install python-is-python2. Having done that, you risk breaking modern software, which rely on Python3. I am not the developer of Duplicati, so I don't know if it is just the manual that needs to be changed or if some Python scripts need to be changed too.

**Comment by warwickmm** [comment]
I don't think there's any code changes to make.  Please create an issue to fix the documentation here:

https://github.com/kees-z/DuplicatiDocs/issues

**Comment by HeRo002** [comment]
The file https://github.com/duplicati/duplicati/blob/master/unix2dos.py starts with this:

#!/usr/bin/env python

I am not an expert on this(!), but IF you uninstall python-is-python2 it should probably be changed to

#!/usr/bin/env python2

I don't know how many python files have this possible problem.

**Comment by kenkendk** [comment]
@HeRo002 
> The file https://github.com/duplicati/duplicati/blob/master/unix2dos.py starts with this:

That tool (and some of the others) are build-tools, so not deployed to users. But we should fix them, and actually upgrade to Python3 ASAP.
