### ISSUE TITLE
Can't restore: [Warning-Duplicati.Library.Main.Operation.RestoreHandler-NoFilesRestored]: Restore completed without errors but no files were restored

### ISSUE THREAD

**Issue by dgooijer** [duplicati/duplicati#4319]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18 (docker linuxserver/duplicati)
- **Operating system**: Docker container on Ubuntu within Proxomox VM
- **Backend**: Local directory attached to docker container

## Description
Start a restore job for a single file within a larger backup set via webUI - restore job starts and produces a file in the correct location, which is empty (0 kb). Message shown that restore is completed, but simultanious a warning is generated: Can't restore: [Warning-Duplicati.Library.Main.Operation.RestoreHandler-NoFilesRestored]: Restore completed without errors but no files were restored - log below
I have already tried to restore to different locations to rule out permission issues. As the restore engine is able to write an empty file it looks like permissions are not the issue. The log below doesn't indicate any issue to me - i tried to restore different files to rule out file dependant issues.

## Steps to reproduce

1. Go to Duplicati webUI
2. Select restore
3. Select exisiting backup set and select a file
4. Select a manual folder for restore, and either further restore option gives simular results (overwrite & restore permissions)

- **Actual result**:
A empty file with the correct file name is created at the correct place (0kb)
- **Expected result**:
The original file is restored

## Debug log
``
{
  "RestoredFiles": 0,
  "SizeOfRestoredFiles": 0,
  "RestoredFolders": 0,
  "RestoredSymlinks": 0,
  "PatchedFiles": 0,
  "DeletedFiles": 0,
  "DeletedFolders": 0,
  "DeletedSymlinks": 0,
  "MainOperation": "Restore",
  "RecreateDatabaseResults": null,
  "ParsedResult": "Warning",
  "Version": "2.0.5.1 (2.0.5.1_beta_2020-01-18)",
  "EndTime": "2020-09-18T09:47:57.31136Z",
  "BeginTime": "2020-09-18T09:47:38.782238Z",
  "Duration": "00:00:18.5291220",
  "MessagesActualLength": 7,
  "WarningsActualLength": 1,
  "ErrorsActualLength": 0,
  "Messages": [
    "2020-09-18 11:47:38 +02 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Restore has started",
    "2020-09-18 11:47:39 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()",
    "2020-09-18 11:47:43 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (4.48 KB)",
    "2020-09-18 11:47:43 +02 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 0 (9/17/2020 9:00:00 PM) ...",
    "2020-09-18 11:47:43 +02 - [Information-Duplicati.Library.Main.Operation.RestoreHandler-RemoteFileCount]: 1 remote files are required to restore",
    "2020-09-18 11:47:43 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Started: duplicati-b459d51f078954e38ad475f327baf4b68.dblock.zip.aes (99.94 MB)",
    "2020-09-18 11:47:56 +02 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Get - Completed: duplicati-b459d51f078954e38ad475f327baf4b68.dblock.zip.aes (99.94 MB)"
  ],
  "Warnings": [
    "2020-09-18 11:47:57 +02 - [Warning-Duplicati.Library.Main.Operation.RestoreHandler-NoFilesRestored]: Restore completed without errors but no files were restored"
  ],
  "Errors": [],
  "BackendStatistics": {
    "RemoteCalls": 2,
    "BytesUploaded": 0,
    "BytesDownloaded": 104794605,
    "FilesUploaded": 0,
    "FilesDownloaded": 1,
    "FilesDeleted": 0,
    "FoldersCreated": 0,
    "RetryAttempts": 0,
    "UnknownFileSize": 0,
    "UnknownFileCount": 0,
    "KnownFileCount": 4586,
    "KnownFileSize": 238741990098,
    "LastBackupDate": "2020-09-17T23:00:00+02:00",
    "BackupListCount": 12,
    "TotalQuotaSpace": 0,
    "FreeQuotaSpace": 0,
    "AssignedQuotaSpace": -1,
    "ReportedQuotaError": false,
    "ReportedQuotaWarning": false,
    "MainOperation": "Restore",
    "ParsedResult": "Success",
    "Version": "2.0.5.1 (2.0.5.1_beta_2020-01-18)",
    "EndTime": "0001-01-01T00:00:00",
    "BeginTime": "2020-09-18T09:47:38.782242Z",
    "Duration": "00:00:00",
    "MessagesActualLength": 0,
    "WarningsActualLength": 0,
    "ErrorsActualLength": 0,
    "Messages": null,
    "Warnings": null,
    "Errors": null
  }
}
``

**Comment by warwickmm** [comment]
Is your browser automatically filling in passwords?  That is known to cause issues.

You might want to try asking this in the forums.  Several users have encountered similar sounding issues for varying reasons:

https://forum.duplicati.com/

**Comment by warwickmm** [comment]
@dgooijer, were you able to resolve this?  The "Restore completed without errors but no files were restored" warning can occur when the restore directory already contains the desired file, and hence no restore was necessary.

**Comment by warwickmm** [comment]
Closing due to lack of feedback.  If this is still an issue, please re-open with more details.
