### ISSUE TITLE
Reconnect to a SSH DynDNS remote host that changed IP after an automatic reconnect of the ISP 

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#432]
_From [NSchmid...@gmail.com](https://code.google.com/u/104359551846731490312/) on June 19, 2011 23:03:26_

What steps will reproduce the problem? 1. start a backup
2. reconnect the target Internetconnection which will change the IP and updates the Dynamik DNS entry
3. the interrupted backup does not start again within at least 10 minutes. What is the expected output? What do you see instead? It would be great if Duplicati would do a new DNS lookup for the SSH target and try to reconnect to it if the connection died without notice. What version of the product are you using? On what operating system? 1.2 on Windows What backend (destination) are you using? QNAP NAS 410 as SSH Target. Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=432_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
