### ISSUE TITLE
Change Request: File Version History

### ISSUE THREAD

**Issue by AtrusRiven** [duplicati/duplicati#4320]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10
- **Backend**: local USB device

## Description
Is there a possibility to display a file version history in order to have an overview over the individual file-related change dates? At the moment I only can choose the different backup but can't see when a file has actually been changed. Because of that, I file browser with an additional display of the file version history of a selected file would be very helpful, e.g. like in Areca:

![areca_file_version-history](https://user-images.githubusercontent.com/29101440/93596725-23ea1c80-f9ba-11ea-98e0-a6a759062dd4.jpg)

**Comment by warwickmm** [comment]
I believe this is a similar request to #72.  Closing this as a duplicate.

**Comment by AtrusRiven** [comment]
Thanks for the quick reaction, sorry for overseeing this!
