### ISSUE TITLE
Help with Warnings.

### ISSUE THREAD

**Issue by d848** [duplicati/duplicati#4325]
Hi

I have 13 warnings in the GUI. I ran list-broken-files which gave me the following 4 errors (those 4 dblocks are listed twice in the warnings giving 8 in total for some reason)

What is the next step? Is it OK to run purge-broken-files?

  Listing remote folder ...
remote file duplicati-b837e0f602a6e41d6aa7a25beb4602856.dblock.zip is listed as Uploaded with size 29360128 but should be 52375972, please verify the sha256 hash "QGO00hy9Oga9IML3zIPpXRU7dBa0RImwb+VpoaBptc4="
remote file duplicati-bd1f041d94b534fddb844260c03407581.dblock.zip is listed as Uploaded with size 32505856 but should be 52379656, please verify the sha256 hash "iG1FqFt8hFhHm6lGnxhl8+E9myAl25YpWRTw9h3dfDQ="
remote file duplicati-b6990c58663b1498da9d81a784fc5528f.dblock.zip is listed as Uploaded with size 32243712 but should be 52367281, please verify the sha256 hash "oQSnS62PhZEOXXw5WMkQ5urK51MBJhc3wzfH52WxvBg="
remote file duplicati-b6dd0b42bec6342be9a26130a448bccb6.dblock.zip is listed as Uploaded with size 29360128 but should be 52401640, please verify the sha256 hash "k0EUX+Fl22FWALYuArFbMexajym8740HuTw8qoVLICo="
Return code: 0

**Comment by warwickmm** [comment]
For general help questions, you might have better luck asking in the forums.  I'm going to close this for now, but if it's determined that there are code changes to make, feel free to reopen this with more details.

https://forum.duplicati.com/
