### ISSUE TITLE
sqlite3.OperationalError: no such table: BlockIdToFile

### ISSUE THREAD

**Issue by renoir789** [duplicati/duplicati#4335]
- [ ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: You are currently running Duplicati - 2.0.5.1_beta_2020-01-18
- **Operating system**: Linux
- **Backend**: Replace me

## Description

The duplicati gui is tracking on taking 21 days to restore from a 600 GB backup.

I have decrypted everything manually and am trying to use the commandline tool, but getting this failure.
sqlite3.OperationalError: no such table: BlockIdToFile

## Steps to reproduce

m4:~/duplicati/Tools/Commandline/RestoreFromPython$ sudo python3 restore_from_python.py 
Welcome to Python Duplicati recovery.
Please type the full path to a directory with Duplicati's .aes or .zip files:/mnt/smb/backups/microsoftbackup/
Please type * to restore all files, or a pattern like /path/to/files/* to restore the files in a certain directory)/mnt/disks/192.168.2.2_Seagate_Backup_Plus_Drive/UnRAID/Docker Backup
Please enter the path to an empty destination directory:/mnt/smb/backups/restore2/
Password:(none entered as decrypted manually)
using duplicati-20200826T061502Z.dlist.zip which looks like the most recent dlist.
Traceback (most recent call last):
  File "restore_from_python.py", line 346, in <module>
    main()
  File "restore_from_python.py", line 342, in main
    mainRestore(d, outdir, passw, scope)
  File "restore_from_python.py", line 52, in mainRestore
    db, numberToName = createDb(d, 'py-restore-index.sqlite', passw, cacheDecrypted)
  File "restore_from_python.py", line 190, in createDb
    WHERE BlockId=?''', [filenamesAndSizes.encode('utf8')]).fetchone()
sqlite3.OperationalError: no such table: BlockIdToFile

- **Actual result**:
the error above
- **Expected result**:
I get my files faster than 20 days

**Comment by warwickmm** [comment]
I've never used `restore_from_python.py` before, but I just tested it (from version 2.0.5.1) and had no problems restoring.

It looks like `restore_from_python.py` attempts to create the `py-restore-index.sqlite` database if it doesn't exist.  From your description above, it looks like it's trying to query an existing database that is missing the `BlockIdToFile` table.

Can you try again, but first make sure that the directory containing the `.aes` or `.zip` files _does not_ contain a `py-restore-index.sqlite` file?

Regarding the slow restore from the UI, some causes of this have been fixed in more recent canary versions.  You can try searching the forums for related issues with slow restores:

https://forum.duplicati.com/

**Comment by renoir789** [comment]
> I've never used `restore_from_python.py` before, but I just tested it (from version 2.0.5.1) and had no problems restoring.
> 
> It looks like `restore_from_python.py` attempts to create the `py-restore-index.sqlite` database if it doesn't exist. From your description above, it looks like it's trying to query an existing database that is missing the `BlockIdToFile` table.
> 
> Can you try again, but first make sure that the directory containing the `.aes` or `.zip` files _does not_ contain a `py-restore-index.sqlite` file?
> 
> Regarding the slow restore from the UI, some causes of this have been fixed in more recent canary versions. You can try searching the forums for related issues with slow restores:
> 
> https://forum.duplicati.com/

Really I'm just trying to get one file back from the database, by the fastest means possible. I am using the latest canary version, however we're still tracking on 4-5 days for a 600GB backup (using the GUI), and I just need a 50GB file from that backup.

Is there any way to speed this up?

**Comment by warwickmm** [comment]
> I am using the latest canary version

Can you provide the exact version?

> Is there any way to speed this up?

It depends.  If it's a database issue, then sometimes forcing an `ANALYZE` helps.  You also might have better luck asking in the forums.  There are a lot more eyes over there.

**Comment by warwickmm** [comment]
Related forum discussion here:

https://forum.duplicati.com/t/fastest-way-to-restore-part-of-a-backup/10849

**Comment by renoir789** [comment]
> > I am using the latest canary version
> 
> Can you provide the exact version?
> 
> > Is there any way to speed this up?
> 
> It depends. If it's a database issue, then sometimes forcing an `ANALYZE` helps. You also might have better luck asking in the forums. There are a lot more eyes over there.

I have started that conversation on the duplicati forums.
Version:
You are currently running Duplicati - 2.0.5.111_canary_2020-09-26

**Comment by renoir789** [comment]
> I've never used `restore_from_python.py` before, but I just tested it (from version 2.0.5.1) and had no problems restoring.
> 
> It looks like `restore_from_python.py` attempts to create the `py-restore-index.sqlite` database if it doesn't exist. From your description above, it looks like it's trying to query an existing database that is missing the `BlockIdToFile` table.
> 
> Can you try again, but first make sure that the directory containing the `.aes` or `.zip` files _does not_ contain a `py-restore-index.sqlite` file?
> 
> Regarding the slow restore from the UI, some causes of this have been fixed in more recent canary versions. You can try searching the forums for related issues with slow restores:
> 
> https://forum.duplicati.com/

I have deleted that file, then I get this. There is no other process using this directory:

~/duplicati/Tools/Commandline/RestoreFromPython$ sudo python3 restore_from_python.py 
Welcome to Python Duplicati recovery.
Please type the full path to a directory with Duplicati's .aes or .zip files:/mnt/smb/msbackup2
Please type * to restore all files, or a pattern like /path/to/files/* to restore the files in a certain directory)/backups/192.168.2.2_seagate_backup_plus_drive/UnRAID/Docker Backup/*
Please enter the path to an empty destination directory:/mnt/smb/msbackup2/finalattempt
Password:
using duplicati-20200826T061502Z.dlist.zip.aes which looks like the most recent dlist.
Creating index, this may take some time...
Traceback (most recent call last):
  File "restore_from_python.py", line 346, in <module>
    main()
  File "restore_from_python.py", line 342, in main
    mainRestore(d, outdir, passw, scope)
  File "restore_from_python.py", line 52, in mainRestore
    db, numberToName = createDb(d, 'py-restore-index.sqlite', passw, cacheDecrypted)
  File "restore_from_python.py", line 204, in createDb
    numberToName, filenamesAndSizes)
  File "restore_from_python.py", line 216, in createBlockIdsToFilenames
    FileNum INTEGER)''')
**sqlite3.OperationalError: database is locked**

**Comment by warwickmm** [comment]
It sounds like you were able to [recover your files](https://forum.duplicati.com/t/fastest-way-to-restore-part-of-a-backup/10849/18).  That's good news.

I'm going to close this since there are several existing issues that concern performance issues.
