### ISSUE TITLE
Detect completed backup during shutdown.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#434]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on June 27, 2011 08:38:52_

If the backup is in progress while the UI is being shut down, Duplicati will ask if the backup should be terminated. If the backup ends while the dialog is displayed, Duplicati should dismiss the dialog box automatically.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=434_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
