### ISSUE TITLE
Unexplained missing files error 

### ISSUE THREAD

**Issue by Toto5931** [duplicati/duplicati#4343]
- [ x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1
- **Operating system**: Windows 10
- **Backend**: OVH cloud archive (cold cloud)

## Description
Since the 2 sept 2020, the backup fails with the message :"[Error-Duplicati.Library.Main.Operation.FilelistProcessor-MissingRemoteFiles]: Found 3614 files that are missing from the remote storage, please run repair"
After finding out, it seems the server (OVH.com) has changed the directory of my remote folder. I have updated the correct folder path in the configuration form, but Duplicati is still not finding the files, whereas they exist.

Duplicati should find the files. 
How to explain this behavior? Is the complete path of the remote files stored elsewhere than in the configuration? 

How can I investigate deeper? The profiling level of reporting is not saying more than "missing file". If I can have the SFTP request that have been sent to the server, or know which check is done on the file (date,hash,...?) it could help

I would like to avoid running "repair" because I would need to unfreeze my files (cold cloud), download them and I will be charged for that.

Thanks

- **Actual result**:
Files are not found, even with the correct path

- **Expected result**:
Duplicati should find the files.

## Debug log
```2020-10-13 19:25:03 +02 - [Warning-Duplicati.Library.Main.Operation.FilelistProcessor-MissingFile]: Missing file: duplicati-i9dd40323055d49e0aa29aecea7ffefda.dindex.zip.aes
2020-10-13 19:25:03 +02 - [Error-Duplicati.Library.Main.Operation.FilelistProcessor-MissingRemoteFiles]: Found 3614 files that are missing from the remote storage, please run repair
2020-10-13 19:25:03 +02 - [Error-Duplicati.Library.Main.Operation.BackupHandler-FatalError]: Fatal error
Duplicati.Library.Interface.UserInformationException: Found 3614 files that are missing from the remote storage, please run repair
   à Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   à Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   à Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()```

**Comment by warwickmm** [comment]
You might want to try asking in the forums.  There may be others that have experienced a similar issue.

https://forum.duplicati.com/

**Comment by warwickmm** [comment]
Were you able to resolve this?  "Found 3614 files that are missing from the remote storage, please run repair" makes it sound like Duplicati is still pointing to the wrong destination folder.

**Comment by Toto5931** [comment]
Indeed the problem was on server side. Maybe a restart of Duplicati was needed as well
Thanks for your help anyway
