### ISSUE TITLE
Special character in filename - restore fails!

### ISSUE THREAD

**Issue by GustelDE** [duplicati/duplicati#4345]
Hi,

I found, that files containing special characters e.g. ! (exclamation mark) are not restored.
I does not matter if the folder contains a "!", file from such folders are restored sucessfully.

Is there a way to restore a file with an ! in the filename? I use this a lot to mark files and to pin them on top.
No warnings generated during the backups.

Please see the screenshots:
![hc_004](https://user-images.githubusercontent.com/26502186/96248747-55034000-0fac-11eb-9453-c5e08f65ac69.jpg)
![hc_002](https://user-images.githubusercontent.com/26502186/96248757-57659a00-0fac-11eb-8c72-6a0c30d065e6.jpg)
![hc_003](https://user-images.githubusercontent.com/26502186/96248761-592f5d80-0fac-11eb-8a6c-77f2e7905649.jpg)

The backups are stored locally on two different NAS-Devices.

Duplicati is: 2.0.5.1_beta_2020-01-18
This is reproducable with all files starting with an "!". All other files are successfully restorable.
No exclude rule defined.

**Comment by warwickmm** [comment]
I don't have any problems restoring files with `!` in the name on Linux using versions 2.0.5.1 or 2.0.5.111.  You might want to ask in the forums (there are a lot more users there) to see if there are any users who can reproduce your problem:

https://forum.duplicati.com/

**Comment by ts678** [comment]
What OS is this? Issue not reproducible on Windows 10 with Duplicati 2.0.5.111. Made a new backup, picked two files from a folder, restored folder. The file with an exclamation mark and without it both showed up. I'd note, though, that if you allow your browser or password saver to save passwords for Duplicati, they typically autofill the wrong spots, and can cause failure of files on restores, e.g.:

> 2020-10-17 19:14:14 -04 - [Error-Duplicati.Library.Main.Operation.RestoreHandler-PatchingFailed]: Failed to patch with remote file: "duplicati-b6c30b1de6cec4a57acd6595e1ffe2720.dblock.zip.aes", message: Failed to decrypt data (invalid passphrase?): Invalid password or corrupted data

So please first check your browser password settings and saved password URLs. You can also try [Export As Command-line](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#exporting-a-backup-job-configuration), change `backup` to `restore`, check the passphrase carefully, probably add [--restore-path](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-restore-command)=some_other_folder to protect originals, and run.

**Comment by warwickmm** [comment]
Closing this due to lack of feedback and inability to reproduce the problem.  If this is still an issue, please reopen and provide more details.
