### ISSUE TITLE
Additional default extensions to skip for compression

### ISSUE THREAD

**Issue by jeffrobins** [duplicati/duplicati#4356]
- [x ] I have searched open and closed issues for duplicates.

----------------------------------------

## Description

There are additional file types where compression should be skipped by default, since they won't compress further:
1) ".dar." Disk Archive files (http://dar.linux.free.fr/).  It's like tar, but designed for use on spinning drives and not tapes
2) ".sqlite-journal" I don't actually know that this won't compress, but Duplicati hangs on it for a long time and the throughput drops to about 14KB/s.  It's Duplicati's own sqlite-journal file

**Comment by warwickmm** [comment]
Thanks @jeffrobins.  I think it makes sense to avoid compressing `.dar` files.

The hang is a known issue and it's [not recommended](https://github.com/duplicati/duplicati/issues/4308#issuecomment-687089422) to backup Duplicati's individual job databases (although it [can be useful](https://forum.duplicati.com/t/backup-the-backup-database-and-some-cryptic-messages-in-my-logs/9261) to keep _separate_ backup of `Duplicati-server.sqlite`).
