### ISSUE TITLE
[Feature Request] Support Proxmox Backup Server as a backup destination

### ISSUE THREAD

**Issue by Cerothen** [duplicati/duplicati#4363]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.111
- **Operating system**: All
- **Backend**: Proxmox Backup Server [FR]

## Description

Support Proxmox Backup Server (PBS) as a backup destination. If the backup ideologies are similar enough then supporting PBS gives a great server interface for duplicati to backup to that can manage already uploaded backups. Duplicati's OS support and client side versatility provides a great companion for PBS.

**Comment by ts678** [comment]
> If the backup ideologies are similar enough

There are people here who know Duplicati's. Can you help understand PBS design? I'm not sure "new backend" label says it all.

[Introduction](https://pbs.proxmox.com/docs/introduction.html#introduction) says this is the server side of a backup system tied to `proxmox-backup-client` which is a CLI client optimized for backing up the Proxmox Virtual Environment platform. There is an [API](https://pbs.proxmox.com/docs/backup-protocol.html) however it doesn't appear very complete. Can it [delete](https://github.com/duplicati/duplicati/wiki/Developer-Documentation#overview)?

> The backends encapsulate the actual communication with a remote host with a simple abstraction, namely that the backend can perform 4 operations: GET, PUT, LIST, DELETE. All operations performed by Duplicati relies on only these operations, enabling almost any storage to be implemented as a destination.

> PBS gives a great server interface for duplicati to backup to that can manage already uploaded backups.

[Graphical User Interface](https://pbs.proxmox.com/docs/gui.html#graphical-user-interface) shows some capabilities, but talks little about backups. Do you mean [Maintenance Tasks](https://pbs.proxmox.com/docs/maintenance.html#maintenance-tasks)? If so, which?
Pruning backup snapshots seems dangerous if it actually deletes anything Duplicati put up there. That will corrupt the backup.

See [The backup process explained](https://duplicati.readthedocs.io/en/latest/01-introduction/#the-backup-process-explained) and [How the backup process works](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/). [The COMPACT command](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-compact-command) reclaims storage after deletes.
None of these want anything else changing its files. Could you clarify the interactions and management that you have in mind?

For simply using Proxmox Backup Server for a backup destination (use the hardware you have...), maybe [SFTP (SSH)](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#sftp-ssh) is available.
Possibly you can even find a path that's included in the storage usage records, but which other administration will leave alone...

**Comment by Cerothen** [comment]
Reviewing your comment and my general understanding of the proxmox backup server implementation the backup ideology might not be similar enough.

To my understanding the proxmox backup client chunks up data into 4MB chunks then stores them with a filename that is the SHA256 checksum. The backups are uploaded to the server and not managed locally.
