### ISSUE TITLE
How to migrate backups between users

### ISSUE THREAD

**Issue by Gooberpatrol66** [duplicati/duplicati#4365]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.111
- **Operating system**: Gentoo Linux
- **Backend**: Tardigrade

I have started a backup as one user but now I want to run it in the future as a different user. How can I migrate the backup configuration to a different user?

**Comment by warwickmm** [comment]
One option is to [export](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#exporting-a-backup-job-configuration) the configuration and [import](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#creating-a-new-backup-job) it again as the new user.

You'll probably have better luck searching/asking this in the forums.

https://forum.duplicati.com/

**Comment by Gooberpatrol66** [comment]
Thanks.
