### ISSUE TITLE
Backup job won't pause

### ISSUE THREAD

**Issue by Gooberpatrol66** [duplicati/duplicati#4370]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.111
- **Operating system**: Gentoo Linux
- **Backend**: Tardigrade

## Description

The backup job won't pause

## Steps to reproduce

1. start duplicati-server
2. open web interface
3. start backup job
4. click pause button

- **Actual result**:
backup continues
- **Expected result**:
backup pauses

**Comment by warwickmm** [comment]
Duplicate of #3565.
