### ISSUE TITLE
Multiple Backup Files Detected as Virus

### ISSUE THREAD

**Issue by thelewiss1** [duplicati/duplicati#4373]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10 20H2 64bit
- **Backend**: Local

## Description

Trojans being detected in multiple backup files. PC is thought to be malware free, though some files may contain false positives or tools that may be misdetected.
Kaspersky Total Security, fully up to date
![image](https://user-images.githubusercontent.com/40576482/99837936-40dcd080-2b60-11eb-9517-6c77ec84de79.png)
![image](https://user-images.githubusercontent.com/40576482/99837960-489c7500-2b60-11eb-8cf2-42bfb872d4d7.png)

**Comment by warwickmm** [comment]
You can try submitting a file to Kapersky for further analysis:

https://support.kaspersky.com/1870

I don't think this merits any code changes, so I'm going to close this issue.  I'd suggest searching/posting in the forums to see if others have encountered a similar issue (for example, [this](https://forum.duplicati.com/t/backup-fails-after-bitdefender-detects-virus-created-by-duplicati/10049)).

https://forum.duplicati.com/

**Comment by thelewiss1** [comment]
My apologies, I should have used the forum instead.

Thanks!
