### ISSUE TITLE
B2 exits with 0 when directory unchanged, but Duplicati exits with 1

### ISSUE THREAD

**Issue by luboslives** [duplicati/duplicati#4377]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1 Beta
- **Operating system**: CentOS 8
- **Backend**: Backblaze B2

## Description

When a directory has not changed at all since the last backup, Duplicati is exiting with a value of 1 and systemd is reporting it as a failure. B2 [correctly returns a 0](https://github.com/Backblaze/B2_Command_Line_Tool/blob/1ddcc6e3d062dd15dd99479f0597b4f630553107/b2/console_tool.py#L1324) (at first I thought it was a B2 error but they pointed me to that source code). Duplicati should pick up and return that value.

## Steps to reproduce

1. Back up a test directory which won't change in any way to a B2 bucket.
2. Create a shell script of that same backup job.
3. Create a systemd service which executes that script.
4. Reload the systemd daemon with `systemctl daemon-reload` to register the service.
5. Run the service with `systemctl start mynewservice`.
6. Follow the printed results, or check `systemctl status mynewservice` after the process completes.

- **Actual result**:
An example trace, taken from Cockpit so it's in reverse order:
```
mybackup.service: Failed with result 'exit-code'    systemd
mybackup.service: Main process exited, code=exited, status=1/FAILURE   systemd
Backup completed successfully!    mybackupscript.sh
Data downloaded: 54.04 MB   mybackupscript.sh
Data uploaded: 0 bytes    mybackupscript.sh
Files changed: 0   mybackupscript.sh
Files deleted: 0   mybackupscript.sh
Files added: 0   mybackupscript.sh
```
- **Expected result**:
A silent successful exit after
`Backup completed successfully!    mybackupscript.sh`

**Comment by warwickmm** [comment]
This is intentional.  An exit code of `1` is used to indicate that the backup was successful with no detected file changes.  If possible, you should configure your service to handle these codes as appropriate.

https://forum.duplicati.com/t/what-codes-does-duplicati-cli-return/6106/2
