### ISSUE TITLE
Add SSH support for elliptic-curve cryptography aka ECDSA

### ISSUE THREAD

**Issue by tobiasschuerg** [duplicati/duplicati#4378]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.5.111_canary_2020-09-26
- **Operating system**: Windows 10
- **Backend**: ?

## Description
It seems that duplicati uses a quite old version of **SSH.NET** (of 2016?) in which ssh with elliptic-curves are not yet supported.

https://github.com/duplicati/duplicati/blob/082a14fc22efdef226c1bee956f85009f7104fb3/Duplicati/Library/Backend/SSHv2/Duplicati.Library.Backend.SSHv2.csproj#L39-L41

Elliptic curves where added to SSH.NET in 2018
https://github.com/sshnet/SSH.NET/pull/496

## Steps to reproduce
Create SSH key via `ssh-keygen -t ecdsa -b 521`

- **Actual result**:
Error when trying to connect
> Error message was Key 'EC' is not supported.
- **Expected result**:
Successful connection with the ssh key created.

## Screenshots
![image](https://user-images.githubusercontent.com/1324555/100198363-070f1f80-2efc-11eb-9971-fe0d3bbc6932.png)

**Comment by warwickmm** [comment]
Related to issues #2950 and #3360.

**Comment by warwickmm** [comment]
It looks like support was added to SSH.NET, but it has not been released yet (there is a beta pre-release available).

https://github.com/sshnet/SSH.NET/releases
