### ISSUE TITLE
Support for destinations with limits to number of files

### ISSUE THREAD

**Issue by achims311** [duplicati/duplicati#4391]
- [X ] I have searched open and closed issues for duplicates. 
Similar to #881, but increasing the file size is no real solution
----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.111
- **Operating system**: Debian 
- **Backend**: FTP

## Description

Please support backup destinations with file number restrictions 
Here a "simple" implementation is to use directory structures as normally used with caching  (squid , cache of web browsers, ...)
Even if reading a huge directory once is sometimes very slow, reading the structure might be even slower, , as you might need to read many subdirectories.
Idea would be to use the filename as a sorting criteria:
duplicati-b401534bf34f6406ca54ec889b086e0ab.dblock.zip.aes -> b/duplicati-b401534bf34f6406ca54ec889b086e0ab.dblock.zip.aes

**Comment by warwickmm** [comment]
Thanks @achims311.  This is already covered in issue #1374.  See also pull request #3873, and the forum discussion [here](https://forum.duplicati.com/t/logic-and-usecase-for-remote-subfolders/6511).
