### ISSUE TITLE
"You have changed the encryption mode" on editing options w/ no encryption

### ISSUE THREAD

**Issue by exscape** [duplicati/duplicati#4393]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.111-2.0.5.111_canary_2020-09-26
- **Operating system**: Windows 10 20H2 (build 19042.685)
- **Backend**: Local folder or drive

## Description

I have a backup running with no encryption, since it's stored on a local disk. When I tried to change settings for it, I got a warning about "You have changed the encryption mode", even when I simply opened the backup settings and immediately clicked "save".

I traced the message to EditBackupController.js around line 402 (in v2.0.5.111-2.0.5.111_canary_2020-09-26). The issue itself seems to be a few lines further up:

    var previousEncryptionEnabled = previousEncryptionOpt == null ? true : !AppUtils.parseBoolString(previousEncryptionOpt.Value, true);

I'm guessing this evaluates to true here, making Duplicati attempt to change from no encryption to AES with no user input. My first thought was that previousEncryptionOpt == null was likely, but I'm also not sure why the parsed boolean is negated in the non-null case.  
Simply going to the General page and selecting "No encryption" when you edit the settings works as a workaround.

The next time I went to change my settings to test, it stayed on "No encryption" as expected, so it seems this only happens in certain cases. Perhaps findPrevOpt() could find the key after it had been explicitly saved again?

## Steps to reproduce

Unfortunately, I'm not sure. When I created a new backup with no encryption and edited, it worked as expected.

- **Actual result**:
Warning message about changing encryption mode appears without touching any settings whatsoever.
- **Expected result**:
No warning message as I did not touch the encryption settings at all.

**Comment by warwickmm** [comment]
This is strange, I'm not sure what could have happened.  Like you described, I can't reproduce the issue either.

> ... I'm also not sure why the parsed boolean is negated in the non-null case.

I think `previousEncryptionOpt.Value` contains the value for the `--no-encryption` option.  Hence, it needs to be negated to define `previousEncryptionEnabled`.

**Comment by ts678** [comment]
I searched for the words
changed encryption mode
in Issues and Duplicati forum, both in full text and in title only. I couldn't find another report of this, so whatever it was, it's rare.

Is this still of interest and happening? If not, it will eventually close.

**Comment by exscape** [comment]
I'm pretty sure it only happened this once for me, at least.
