### ISSUE TITLE
Ask for subscription with error : No matching repo to modify: PowerTools.

### ISSUE THREAD

**Issue by Enaakshi** [duplicati/duplicati#4421]
I am getting redhat subscription error on centos 8.3. As per my knowledge centos is an open source and does not require redhat subscription. so can you tell me why i am getting this error

[root@Centos8 yum.repos.d]# sudo dnf config-manager --set-enabled PowerTools
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Error: No matching repo to modify: PowerTools.
[root@Centos8 yum.repos.d]#

**Comment by warwickmm** [comment]
Wrong project?
