### ISSUE TITLE
Telegram-Backend: Very long "break" between blocks

### ISSUE THREAD

**Issue by wicksim** [duplicati/duplicati#4424]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.112_canary_2021-01-20
- **Operating system**: Synology DSM 6.2.3-25426 Update 3
- **Backend**: Telegram

## Description

Telegram-Backend seems to "stop" for a very long time (2-3h) between blocks. This makes the whole backend so slow that it is nearly not possible to use it for a backup. When it finally starts to upload a block, speed itself seems to be fine to me.

## Steps to reproduce

1. Set up a backup to Telegram
2. Start job
3. Look at Live Log (verbose)

- **Actual result**:
Backup to Telegram is extremly slow
- **Expected result**:
Backup should be blazingly fast ;-)

## Debug log

```

Jan 23, 2021 2:56 PM: Starting executing action PutAsync
Jan 23, 2021 2:56 PM: Backend event: Put - Started: duplicati-be671ade3e989449c890a2b28a10e58ec.dblock.zip.aes (49.96 MB)
Jan 23, 2021 2:56 PM: Backend event: Put - Completed: duplicati-i9da6d09d816e45d594bd781e3509490a.dindex.zip.aes (30.81 KB)
Jan 23, 2021 2:56 PM: Done executing action PutAsync
Jan 23, 2021 2:56 PM: Starting executing action PutAsync
Jan 23, 2021 2:56 PM: Backend event: Put - Started: duplicati-i9da6d09d816e45d594bd781e3509490a.dindex.zip.aes (30.81 KB)
Jan 23, 2021 2:56 PM: Backend event: Put - Retrying: duplicati-b4bc38fd9c44d4221a4b1d2f7ce96f4f0.dblock.zip.aes (49.98 MB)
Jan 23, 2021 2:56 PM: Operation Put with file duplicati-b4bc38fd9c44d4221a4b1d2f7ce96f4f0.dblock.zip.aes attempt 2 of 6 failed with message: Couldn't read the packet length
Jan 23, 2021 2:56 PM: Backend event: Put - Retrying: duplicati-i606e5ae62f95479b8928dc0e294c6307.dindex.zip.aes (35.09 KB)
Jan 23, 2021 2:56 PM: Operation Put with file duplicati-i606e5ae62f95479b8928dc0e294c6307.dindex.zip.aes attempt 2 of 6 failed with message: The socket is not connected
Jan 23, 2021 2:56 PM: Backend event: Put - Retrying: duplicati-b4b26e445960049fc8c82e58bda8df983.dblock.zip.aes (49.95 MB)
Jan 23, 2021 2:56 PM: Operation Put with file duplicati-b4b26e445960049fc8c82e58bda8df983.dblock.zip.aes attempt 2 of 6 failed with message: The socket is not connected
Jan 23, 2021 2:56 PM: Starting executing action PutAsync
Jan 23, 2021 2:56 PM: Starting executing action PutAsync
Jan 23, 2021 2:56 PM: Backend event: Put - Completed: duplicati-b0c6070fc848b4323a2f97bf198ee41c2.dblock.zip.aes (49.98 MB)
Jan 23, 2021 2:56 PM: Starting executing action PutAsync
Jan 23, 2021 2:56 PM: Done executing action PutAsync
Jan 23, 2021 2:51 PM: Backend event: Put - Started: duplicati-i606e5ae62f95479b8928dc0e294c6307.dindex.zip.aes (35.09 KB)
Jan 23, 2021 2:51 PM: Renaming "duplicati-id8a742ea0892407ab49d4f10451d86ac.dindex.zip.aes" to "duplicati-i606e5ae62f95479b8928dc0e294c6307.dindex.zip.aes"
Jan 23, 2021 2:51 PM: Backend event: Put - Rename: duplicati-i606e5ae62f95479b8928dc0e294c6307.dindex.zip.aes (35.09 KB)
Jan 23, 2021 2:51 PM: Backend event: Put - Rename: duplicati-id8a742ea0892407ab49d4f10451d86ac.dindex.zip.aes (35.09 KB)
Jan 23, 2021 2:51 PM: Backend event: Put - Started: duplicati-b4bc38fd9c44d4221a4b1d2f7ce96f4f0.dblock.zip.aes (49.98 MB)
Jan 23, 2021 2:51 PM: Renaming "duplicati-b04872309e15047f5a6990ffb6fdd697c.dblock.zip.aes" to "duplicati-b4bc38fd9c44d4221a4b1d2f7ce96f4f0.dblock.zip.aes"
Jan 23, 2021 2:51 PM: Backend event: Put - Rename: duplicati-b4bc38fd9c44d4221a4b1d2f7ce96f4f0.dblock.zip.aes (49.98 MB)
Jan 23, 2021 2:51 PM: Backend event: Put - Rename: duplicati-b04872309e15047f5a6990ffb6fdd697c.dblock.zip.aes (49.98 MB)
Jan 23, 2021 2:51 PM: Backend event: Put - Retrying: duplicati-id8a742ea0892407ab49d4f10451d86ac.dindex.zip.aes (35.09 KB)
Jan 23, 2021 2:51 PM: Operation Put with file duplicati-id8a742ea0892407ab49d4f10451d86ac.dindex.zip.aes attempt 1 of 6 failed with message: Unable to write data to the transport connection: The socket has been shut down.
Jan 23, 2021 2:51 PM: Starting executing action PutAsync
Jan 23, 2021 2:51 PM: Starting executing action PutAsync
Jan 23, 2021 2:51 PM: Backend event: Put - Retrying: duplicati-b04872309e15047f5a6990ffb6fdd697c.dblock.zip.aes (49.98 MB)
Jan 23, 2021 2:51 PM: Operation Put with file duplicati-b04872309e15047f5a6990ffb6fdd697c.dblock.zip.aes attempt 1 of 6 failed with message: Couldn't read the packet length
Jan 23, 2021 12:18 PM: Backend event: Put - Started: duplicati-b4b26e445960049fc8c82e58bda8df983.dblock.zip.aes (49.95 MB)
Jan 23, 2021 12:18 PM: Renaming "duplicati-b87f1b7ca14734a8ebf3aabd43eb3b7bb.dblock.zip.aes" to "duplicati-b4b26e445960049fc8c82e58bda8df983.dblock.zip.aes"
Jan 23, 2021 12:18 PM: Backend event: Put - Rename: duplicati-b4b26e445960049fc8c82e58bda8df983.dblock.zip.aes (49.95 MB)
Jan 23, 2021 12:18 PM: Backend event: Put - Rename: duplicati-b87f1b7ca14734a8ebf3aabd43eb3b7bb.dblock.zip.aes (49.95 MB)
Jan 23, 2021 12:17 PM: Backend event: Put - Started: duplicati-id8a742ea0892407ab49d4f10451d86ac.dindex.zip.aes (35.09 KB)
Jan 23, 2021 12:17 PM: Backend event: Put - Retrying: duplicati-b87f1b7ca14734a8ebf3aabd43eb3b7bb.dblock.zip.aes (49.95 MB)
Jan 23, 2021 12:17 PM: Operation Put with file duplicati-b87f1b7ca14734a8ebf3aabd43eb3b7bb.dblock.zip.aes attempt 1 of 6 failed with message: Couldn't read the packet length
Jan 23, 2021 12:17 PM: Starting executing action PutAsync
Jan 23, 2021 12:17 PM: Backend event: Put - Completed: duplicati-b1b65c7d15e8749b8bcfefe4058ad50dc.dblock.zip.aes (49.95 MB)
Jan 23, 2021 12:17 PM: Starting executing action PutAsync
Jan 23, 2021 12:17 PM: Done executing action PutAsync
Jan 23, 2021 12:15 PM: Including path as no filters matched: /volume1/xx6
Jan 23, 2021 12:15 PM: Checking file for changes /volume1/xx5, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 03/29/2010 16:41:35 vs 01/01/0001 00:00:00
Jan 23, 2021 12:15 PM: New file /volume1/xx4
Jan 23, 2021 12:15 PM: Including path as no filters matched: /volume1/xx3
Jan 23, 2021 12:15 PM: Checking file for changes /volume1/xx2, new: True, timestamp changed: True, size changed: True, metadatachanged: True, 09/19/2010 12:25:03 vs 01/01/0001 00:00:00
Jan 23, 2021 12:15 PM: New file /volume1/xx1
```

**Comment by warwickmm** [comment]
@martikyan, any ideas what might cause this?  Could this be Telegram API limits or flooding protection?

**Comment by wicksim** [comment]
Additional Info: I've tried 2 times and it was always like this:

- First Block successful
- 2-3h stop
- 2 Blocks and 1 Index successful
- 2-3h stop
- 2 Blocks and 1 Index successful

Maybe this info is useful...

**Comment by martikyan** [comment]
Dear @warwickmm & @wicksim. I've tried too and got the same result. The problem is not in the TG backend itself, though it lies inside the NuGet we are using. As I understand changing the current NuGet package for telegram API could solve the problem because TLSharp has lots of bugs. The candidates for new NuGets are [TgSharp](https://github.com/nblockchain/TgSharp) and [tdlib](https://github.com/tdlib/td).

**Comment by ts678** [comment]
> Suggestion: we can unlist Telegram backend for some time until the problem gets resolved.

I guess this means let anyone who's already on it keep using it to the extent it works, while taking it out of GUI dropdown?
There's someone asking about Beta plans (it's been over a year). I'd rather not have anything troublesome go into a Beta...
The alternative would be to disable completely. Is it working well enough that anybody who's on it would be disappointed?

I don't know the code well enough to say which is easier. Lacking feedback, I suppose a pull request can just be submitted.
As a side issue, I'm wondering why the seeming license source work isn't getting all the way to licenses folder in the install.

**Comment by warwickmm** [comment]
It's possible to remove it from the beta and keep it in the canary, but I think it's simplest to just remove it from the canary until we can make it more reliable.  Keeping it in the canary will just lead to more frustrated users.

> As a side issue, I'm wondering why the seeming license source work isn't getting all the way to licenses folder in the install.

Thanks for noticing this.  Pull request #4427 should fix the missing license information.

**Comment by warwickmm** [comment]
Pull request #4449 removes the Telegram backend.  Thanks for your hard work @martikyan.  Perhaps we can revisit this again later with more reliable libraries.

**Comment by martikyan** [comment]
> Pull request #4449 removes the Telegram backend.  Thanks for your hard work @martikyan.  Perhaps we can revisit this again later with more reliable libraries.

Will keep you updated about new backend using better libraries

**Comment by warwickmm** [comment]
Thanks @martikyan.  It was also brought to our attention that it's unclear if the Telegram API [terms of service](https://core.telegram.org/api/terms) is compatible with Duplicati's.  I am not a lawyer...

**Comment by martikyan** [comment]
> Thanks @martikyan.  It was also brought to our attention that it's unclear if the Telegram API [terms of service](https://core.telegram.org/api/terms) is compatible with Duplicati's.  I am not a lawyer...

![Screenshot_20210222-002132_Flamingo.jpg](https://user-images.githubusercontent.com/22702504/108637413-f7c05380-74a3-11eb-87c3-a04b62f8992b.jpg)

**Comment by ts678** [comment]
They answered a different question. The flip side is they want third-party clients, **but** they want complete clients, per API ToS:

"We welcome all developers to use our API and source code to create Telegram-like messaging applications"

"1.3. As a client developer, you must make sure that all the basic features of the main Telegram apps function correctly"

Each end user having to [register as a client developer](https://core.telegram.org/api/obtaining_api_id) also seems a little odd. Do they agree to ToS and bear risk of any ban?
[Security Guidelines for Client Developers](https://core.telegram.org/mtproto/security_guidelines) must also be complied with. I guess Duplicati and chosen library could do research?

Maybe @wicksim can comment on how hard they pushed on such things during signup, but it does seem quite convoluted.
[Storage Providers](https://duplicati.readthedocs.io/en/latest/05-storage-providers/) should give help, if this use is deemed OK. I am not a lawyer either, but this doesn't fit their stated intent...

**Comment by wicksim** [comment]
> Maybe @wicksim can comment on how hard they pushed on such things during signup, but it does seem quite convoluted.

To be honest, I can't remember exactly... :worried:
