### ISSUE TITLE
Pcloud WebDav isn't able to complete backup on Windows 10

### ISSUE THREAD

**Issue by Nirsiel** [duplicati/duplicati#4426]
- [yes] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**:  2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10 20H2
- **Backend**: WebDav PCloud

## Description

I wanted to try WebDav as there is no native backend for Pcloud. But every try ended up with a bunch of missing files that Duplicati wasn't able to deal with.

## Steps to reproduce

1. Select WebDav as backend
2. Set up a backup
3. Run the backup
4. "get an error saying there are missing files"

- **Actual result**:
Got an error regarding missing files at the remote.
- **Expected result**:
complete backup

**Comment by warwickmm** [comment]
Can you try posting in the forum?  There are some users there using pCloud that may be able to help diagnose the issue.  Once it's determined that there are code changes to make, we can re-open this issue with more details.

https://forum.duplicati.com/
