### ISSUE TITLE
Onedrive sync fails to existing folder

### ISSUE THREAD

**Issue by jaburges** [duplicati/duplicati#4428]
- [X] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Docker on Unraid
- **Backend**: OneDrive

## Description

Setting up back up to Onedrive, test completes successfully after connecting the Auth.
When carrying out the actual backup - backup process completes
upload fails to existing folder. Deleting the folder and allowing Duplicati to create it succeeds

## Steps to reproduce

1. Create OneDrive Folder [Backup] in 'MyFiles' (OneDrive root)
2. Setup New Backup process in Duplicati UI
3. Auth to Onedrive
4. Type Folder name created in step 1 [Backup]
5. Test (successful)
6. Save & Run Now = Fails (Apologies didnt capture logs)
7. Delete Onedrive folder [Backup]
8. In Backup workflow back in Duplicati hit test (leaving [Backup] folder there) 
9. Folder does not exist, option to create it
10. Select Yes
11. Backup succeeds
12. Upload succeeds

- **Actual result**:
Unable to backup to existing folder
- **Expected result**:
Should be able to use existing folders I'm assuming (not a huge concern, but figured you'd like to be aware)

**Comment by warwickmm** [comment]
I can't reproduce this.  I created a folder in OneDrive, created a new backup configuration, and both the test and subsequent backup ran without problems.

Did the folder you created have restricted permissions?

**Comment by jaburges** [comment]
No restricted permissions.
I've since tested again and I can't reproduce either now.
May have been a first time set up situation? Or could just have been something on my side.

Either way I'll close the issue, and if someone else has it they can add to the comments.
