### ISSUE TITLE
run-script-before with exit code >5 does not lead to an error

### ISSUE THREAD

**Issue by Bauboo** [duplicati/duplicati#4430]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: 20.04.2
- **Backend**: local

## Description

When using `run-script-before` we can alter the behaviour of Duplicati by giving different exit codes in the script. According to [this](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Modules/Builtin/run-script-example.sh):

```
# - 0: OK, run operation
# - 1: OK, don't run operation
# - 2: Warning, run operation
# - 3: Warning, don't run operation
# - 4: Error, run operation
# - 5: Error don't run operation
# - other: Error don't run operation
```

all other exit codes mean 'Error don't run operation'. However, Duplicati proceeds as if the exit code was one of 0/2/4 and runs the operation.

## Steps to reproduce

1. Setup a simple backup job using the `duplicati-cli` command.
2. Set `run-script-before` to a script that exits with exit code 10.
3. Run the job.

- **Actual result**:
Duplicati runs the job anyways.
- **Expected result**:
Duplicati fails with an error.

**Comment by warwickmm** [comment]
Thanks @Bauboo.  Pull request #4417 should address this.
