### ISSUE TITLE
Program.DataConnection.GetBackup why cant it be public?

### ISSUE THREAD

**Issue by boodzz** [duplicati/duplicati#4433]
Hi,

Is there any specific reason why Program.DataConnection.GetBackup cant be accessible from other modules?

I am trying to use the backup complete event to export the backup config, so that in case of restore we can just point to the config file and it can work on its own from there.

Thanks

**Comment by Xavron** [comment]
It could be done if they wanted to but it would be interesting to see if they actually made that change. My thought is no.

Its possibly better for security to not do what you want but I haven't really looked to see what GetBackup() does here. Looks like its just marked as internal.

I would tell you to just change it yourself but then you have to always have it pulling down changes, etc.

**Comment by ts678** [comment]
> Is there any specific reason why Program.DataConnection.GetBackup cant be accessible from other modules?

That's probably only known to original author, but in general I don't think Duplicati was made to be called into.

As an alternative (somewhat complex, but so is coding this up in C#), the third-party duplicati-client can export:

[Export backups](https://github.com/Pectojin/duplicati-client/tree/master#export-backups)

Is issue still of interest? If not, it will autoclose.
