### ISSUE TITLE
UI - Progress bar is covering the "cancel button"

### ISSUE THREAD

**Issue by jfparis** [duplicati/duplicati#4436]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.112_canary_2021-01-20
- **Operating system**: Ubuntu
- **Backend**: Not relevant

## Description
In the main UI, the progress bar is displayed over the text and the X (circled cross) button. 
As a result, when a task is nearing completion it is impossible to click on the Circled Cross icon to cancel it 

## Steps to reproduce
1. Launch a task and wait for it to reach 95% (or about) completion

- **Actual result**:
Try to click over the X (circled Cross) and you will notice it is impossible 
- **Expected result**:
It should be possible to click on the cross to cancel the task

## Screenshots
![Screenshot from 2021-02-10 10-20-02](https://user-images.githubusercontent.com/48999/107483407-efe5e280-6b78-11eb-9ec6-da04f65b7500.png)

Look at the mouse pointer. It does not allow a click because the bar is displayed above (z-index) the button 
If the task is at 98% then the circle cross is totally covered and it is totally impossible to click

**Comment by jfparis** [comment]
Created a pull request to fix this

**Comment by warwickmm** [comment]
Closed by pull request #4437.

**Comment by warwickmm** [comment]
Reopening because the fix from pull request #4437 caused an issue with the edit backup views.
