### ISSUE TITLE
run-script-before with exit code 3 creates no log

### ISSUE THREAD

**Issue by Bauboo** [duplicati/duplicati#4439]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Windows 10 Home, version 20H2, build 19042.746
- **Backend**: local

## Description

Running a script with `run-script-before` that exits with code `3` causes the backup to stop with a warning, as intended. The popup in the GUI also appears. However, no log entry in the job's log is created.

## Steps to reproduce

1. In the GUI, create a backup job with a `run-script-before` that exits with code `3`.
2. Run it.

- **Actual result**:
Pop-up mentioning 1 warning is displayed, but no log entry is present in the job's log. Note that there is no log entry at all, not even a successful one.
- **Expected result**:
Pop-up mentioning 1 warning is displayed and a log entry is present in the job's log with the warning.

**Comment by warwickmm** [comment]
Thanks @Bauboo.  I see that the entry appears in the server log, not the job-specific log:

![image](https://user-images.githubusercontent.com/17345532/107592281-732b2680-6bc1-11eb-94ba-dd7967ac9651.png)

I'm going to close this in favor of issue #1152, which concerns combining the logs into one location.
