### ISSUE TITLE
Captcha (backup delete) does not load at all

### ISSUE THREAD

**Issue by jonas240** [duplicati/duplicati#4441]
[X] I have searched open and closed issues for duplicates.
- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: TrueNAS-12.0-U2
- **Backend**: OneDrive
## Description

When I try to delete remote files the captcha does not load. At first I encountered this problem: [https://github.com/duplicati/duplicati/issues/3791](url) . However using the given solution by @fireheadman on 11 Nov 20 I was able to 'see' the captcha dialoge, however not the captcha itself. What can I do?

## Screenshots
![2021-02-13](https://user-images.githubusercontent.com/68380809/107848237-0f3b7480-6df2-11eb-84c5-cf38f45ea408.png)

**Comment by jonas240** [comment]
If you look directly at the object:
![2021-02-13 (2)](https://user-images.githubusercontent.com/68380809/107848566-ae616b80-6df4-11eb-94c1-97f4c4348948.png)

**Comment by warwickmm** [comment]
This could be related:

https://forum.duplicati.com/t/font-family-not-found/10287/4

**Comment by jonas240** [comment]
@warwickmm that seems to be the same problem. However do you know a solution?

**Comment by warwickmm** [comment]
Unfortunately, no.  It sounds like a missing font, but hopefully some other TrueNAS users in the forum will be able to help.

**Comment by jonas240** [comment]
I found a solution:
use `pkg install webfonts` to install the missing font. That solved the catcha problem.

**Comment by jonas240** [comment]
I found a solution:
use `pkg install webfonts` to install the missing font. That solved the catcha problem.
