### ISSUE TITLE
[Feature request] UI friendliness

### ISSUE THREAD

**Issue by funnym0nk3y** [duplicati/duplicati#4442]
I like Duplicati for the configurability. But I have a few requests to make it more user friendly. 

1. In the documentation describe not only the default values of the options, but also the possible values. I'm having the compression libraries in mind (AFIAK LZ4 is supported, but mentioned nowhere).
2. Make the options avaiblable not only through a long list, but also through a structured UI

**Comment by ts678** [comment]
> (AFIAK LZ4 is supported, but mentioned nowhere).

It's in the UI now, just not in the manual. I'd note that some of what some UI has is dynamically built, so can't be in manual.
One example of that is "help filter-groups" where the paths in the groups are customized around the user running Duplicati.

![image](https://user-images.githubusercontent.com/40771998/108067906-6e39fd00-702f-11eb-8b23-be97459e09f2.png)

```
C:\ProgramData\Duplicati\duplicati-2.0.5.112_canary_2021-01-20>Duplicati.CommandLine.exe help zip-compression-method
  --zip-compression-method (Enumeration): Sets the Zip compression method
    This option can be used to set an alternative compressor method, such as
    LZMA. Note that using another value than Deflate will cause the
    zip-compression-level option to be ignored.
    * values: None, Deflate, BZip2, LZMA, PPMd
    * default value: Deflate
```

**Comment by funnym0nk3y** [comment]
@ts678 In the latest Canary?

**Comment by ts678** [comment]
> In the latest Canary?

Yes, but I don't think that's necessary. 2.0.5.1 Beta should have all the above, and I just tried 2.0.4.5_beta_2018-11-28 as well.

**Comment by funnym0nk3y** [comment]
Well, with my version (latest canary) I still see the text input.

**Comment by ts678** [comment]
> I still see the text input

What exactly do you see? Where are you seeing it? There's no structured input method other than sections in the dropdown.

![image](https://user-images.githubusercontent.com/40771998/112736075-57d46a80-8f26-11eb-8718-af6a3c4ff00a.png)

Dropdown has a short description. If you choose that one, it then goes into your option list with long description and values.

**Comment by ts678** [comment]
[Compression module supported](https://forum.duplicati.com/t/compression-module-supported/12055/12?u=ts678) details where to find the above screen.

**Comment by funnym0nk3y** [comment]
Okay, found it. Thanks!
