### ISSUE TITLE
S3 Compatible - Choose Region

### ISSUE THREAD

**Issue by lourou** [duplicati/duplicati#4444]
## Environment info

- **Duplicati version**: 2.0.5.1
- **Operating system**: macOS 10.15.7 Catalina
- **Backend**: [Scaleway Object Storage (S3 Compatible)](https://www.scaleway.com/en/docs/object-storage-feature/#-Core-Concepts)

## Description

I found out that the S3-compatible option does not allow to select a custom regions that are used by Scaleway as a S3-compatible providers.

When adding a S3 Compatible Backup destination with custom "Bucket create region". I still get the following error:

`Failed to connect: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'`

How may I add the `nl-ams`, `fr-par` or `pl-waw` regions from Scaleway?

Source: https://www.scaleway.com/en/docs/object-storage-feature/#-Core-Concepts

_Region and Endpoint: Scaleway Object Storage is currently available in three Availability Zones (AZ/Region). The Endpoint to use differs depending on the geographical location of the object storage platform:_

Amsterdam, The Netherlands:
Region: nl-ams
Endpoint: https://s3.nl-ams.scw.cloud

Paris, France:
Region: fr-par
Endpoint: https://s3.fr-par.scw.cloud

Warsaw, Poland:
Region: pl-waw
Endpoint: https://s3.pl-waw.scw.cloud/

## Steps to reproduce

1. Add backup
2. Create new Backup destination "S3 Compatible"
3. Check "Use SSL"
4. Select "Custom Server URL", and enter "s3.nl-ams.scw.cloud"
5. Bucket create region, select "Custom region value" and enter "nl-ams"
6. Storage class: "default"

- **Actual result**:

Clicking on "Test connection" fails with error: `Failed to connect: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'`

- **Expected result**:

Successful backup location added.

## Screenshots

![image](https://user-images.githubusercontent.com/1523837/108399598-9043a300-721a-11eb-9d6c-506cb537fb5e.png)
![image](https://user-images.githubusercontent.com/1523837/108399614-95085700-721a-11eb-9729-3e81c76cd9c1.png)

Thanks a lot!

**Comment by warwickmm** [comment]
Thanks @lourou.  I believe this duplicates issue #3979.  Closing this in favor of the other issue, which has more discussion.

**Comment by lourou** [comment]
Thanks @warwickmm I missed it!
