### ISSUE TITLE
Doesn't work for windows

### ISSUE THREAD

**Issue by DH-Illidan** [duplicati/duplicati#4446]
I selected my user folder to bak, but It seems not work at all.
![image](https://user-images.githubusercontent.com/55729509/108600523-97adac80-73d2-11eb-91d2-a1dd932b5d11.png)

**Comment by warwickmm** [comment]
1. What version of Duplicati?
2. Make sure the user running Duplicati has read access to the files you want backed up
3. Make sure you don't have any [filters](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#creating-a-new-backup-job) that are excluding all your files
4. View the [server logs](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#viewing-the-duplicati-server-logs) to see if there are any errors or other explanations for why files are being excluded
5. You can try and capture the logs to a file using the `log-file` and `log-file-log-level` advanced options
