### ISSUE TITLE
Latest Windows Install Flagged Malware

### ISSUE THREAD

**Issue by steveyeu** [duplicati/duplicati#4450]
Checking the currently available executable via the main site (https://updates.duplicati.com/beta/duplicati-2.0.5.1_beta_2020-01-18-x64.msi) on Virus Total _Yomi Hunter_ comes back as a malware detection:

https://www.virustotal.com/gui/file/bce96441b59350d6e49c75dbe227f26be79a4b657bc3bc858d40ae55f10f0c0b/detection

Is this a false positive?

Looks that the duplicati-2.0.5.112_canary_2021-01-20-x64.msi directly from GitHub reports clean.

**Comment by ts678** [comment]
> Is this a false positive?

Most likely, though the link you cite is also no longer showing a Yomi Hunter opinion at all. It has a newer date than your post.

![image](https://user-images.githubusercontent.com/40771998/108893508-2858d800-75df-11eb-980f-b634fc1695f1.png)

The long hexadecimal value in the link is the SHA256 hash, which you can also compute on your own, e.g. on Windows you can

```
certutil -hashfile duplicati-2.0.5.1_beta_2020-01-18-x64.msi SHA256
SHA256 hash of duplicati-2.0.5.1_beta_2020-01-18-x64.msi:
bce96441b59350d6e49c75dbe227f26be79a4b657bc3bc858d40ae55f10f0c0b
CertUtil: -hashfile command completed successfully.
```

The file I downloaded from your first link is also identical to the copy I downloaded on Jan 20, 2020, so the file has not changed.

On Windows, you can also check the digital signature via right-click --> Properties --> Digital Signatures --> (select) --> Details

![image](https://user-images.githubusercontent.com/40771998/108894417-3f4bfa00-75e0-11eb-9cc8-4afd38f5647e.png)

and this should also provide assurance that the file has not been altered after then.

**Comment by warwickmm** [comment]
As @ts678 showed, this is most likely a false positive.
