### ISSUE TITLE
[Feature Request] ETA for Backup

### ISSUE THREAD

**Issue by JeffResc** [duplicati/duplicati#4457]
- [X] I have searched open and closed issues for duplicates.
- Found similar issue at #589, but it did not solve the request in this issue.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**: Linux using LinuxServer Container [linuxserver/duplicati](https://hub.docker.com/r/linuxserver/duplicati/)
- **Backend**: N/A

## Description

Add an estimated time left in the upload in time. I understand the de-duplication in place, but it already lists the amount of data left to upload and the upload rate, so calculating the ETA should be trivial with that information. This would preferably be displayed in the status bar at the top of the screen with the data left and transfer rate.

**Comment by ts678** [comment]
> it already lists the amount of data left to upload and the upload rate

The amount of data left to upload isn't known until source files have been processed to identify what changes need uploading.
Status bar does show how processing is progressing, but has no way of forecasting the eventual outcome. Do you have ways?

[Estimated time until completion #589](https://github.com/duplicati/duplicati/issues/589#issuecomment-51172970) explains this in more detail, and gives an example of an estimate given near backup end.
Is this what you have in mind, or are you proposing projecting what's coming (which would probably not be a good estimate)?

The big unknown is probably not usually deduplication, but which files will have changes where. See pre-analysis rejection [here](https://github.com/duplicati/duplicati/issues/589#issuecomment-51172975).

> calculating the ETA should be trivial with that information

Yes, but I'm doubtful that we actually have that information. Feel free to say which source you propose for "data left to upload".
There is one on the `System info` screen, but it increases during backup as more changes are gathered that must be uploaded.

**Comment by Xavron** [comment]
@JeffResc  I take it that you mean something like 1GB done in 10 seconds and 2GB to go which is a possibly very incorrect estimate of 20 seconds left but will change as the speed changes?

**Comment by JeffResc** [comment]
I see, I figured maybe having an estimation that automatically updated as the backup took place, but that no longer makes sense. Thanks for the explanations.
