### ISSUE TITLE
Block table indexes and performance

### ISSUE THREAD

**Issue by snamds** [duplicati/duplicati#4458]
Hi,
There is a sql query at the beginning of the backup that is very slow. It's a query to retrieve all Blocks with a size greater than 102400 bytes.
I have opened the database with a sqlite editor and I see that there's no index for "size" column. An index of this column will speed up the query. The execution takes 40 minutes in me computer.

Another problem I've seen is that there is a multicolumn index for Hash,Size (in this order). The "size" part of this index has no 
 sense to me. I've done a query and "hash" seems to be unique so there is no profit to set and index "size" for every "hash". It's only a space waste

**Comment by warwickmm** [comment]
What version are you running?  Pull request #4171 should have addressed the first query.

I'm not as familiar with the second issue, but it's not clear if `Hash` is guaranteed to be unique.

https://github.com/duplicati/duplicati/blob/24990a4011d207ce610b6d5998cdc79c24506e02/Duplicati/Library/Main/Database/Database%20schema/Schema.sql#L172-L184

**Comment by snamds** [comment]
Version is Duplicati - 2.0.5.1_beta_2020-01-18 (windows)

A multicolumn index, as BlockHashSize is, (First "Hash" and second "Size") means: create an index for the first column ("hash") and when for these records that have the same first column value, create an index for the second column ("size"). (this is mor or less the idea)
So, in fact, there is no "size" index and the query is slow. 
I've created a "size" index in the table and the query that took 40 minutes before has taken 0s now.

**Comment by warwickmm** [comment]
Version 2.0.5.106 has this

https://github.com/duplicati/duplicati/blob/e8833c2173f0557b8caea9d0a11eedff2d57e207/Duplicati/Library/Main/Database/Database%20schema/11.%20Add%20Block%20indices.sql#L1

**Comment by snamds** [comment]
Ok, this is correct. Thanks

**Comment by warwickmm** [comment]
This duplicates issue #3884.
