### ISSUE TITLE
My stable version  Duplicati - 2.0.5.103_canary_2020-02-18

### ISSUE THREAD

**Issue by rdbox** [duplicati/duplicati#4460]
I need advice Duplicati version - 2.0.5.103_canary_2020-02-18
Works great for a long time, I decided to upgrade, I'm worried that the update might break something.
Exactly which version can I download?

**Comment by warwickmm** [comment]
This is a better question for the forums.  There are many more users there with different experiences that can give you advice.

https://forum.duplicati.com/
