### ISSUE TITLE
The database was attempted repaired - when remote server unreachable

### ISSUE THREAD

**Issue by mkrzywonski** [duplicati/duplicati#4473]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.114_canary_2021-03-10
- **Operating system**: Ubuntu 5.6.11-050611-generic
- **Backend**: sshfs - linux 5.10.17-v7l+

## Description

When backing up to remote server via sshfs, if the remote server is unreachable the local database becomes corrupt and I must delete and repair it.  If the remote server is unreachable, Duplicati should not touch the database at all.  The job should simply run again at the next scheduled interval.  No database repair should be required.

## Steps to reproduce

1. Configure a backup job (around 1 TB) to a remote server via sshfs
2. Run the job at least one time successfully
3. Remove the network cable from the remote server
4. Run the job again, it will fail and tell you that the database needs to be repaired
5. Drink heavily because it's going to take a couple of days to re-create the database

- **Actual result**:
Failed: The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.
- **Expected result**:
Failed: The remote server was unreachable. Backup aborted.

## Screenshots

N/A

## Debug log

Failed: The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.
Details: Duplicati.Library.Interface.UserInformationException: The database was attempted repaired, but the repair did not complete. This database may be incomplete and the backup process cannot continue. You may delete the local database and attempt to repair it again.
  at Duplicati.Library.Main.Operation.BackupHandler.RunAsync (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x00122] in <e4ba2224a87c42cbadcd524985619ee3>:0 
  at CoCoL.ChannelExtensions.WaitForTaskOrThrow (System.Threading.Tasks.Task task) [0x00050] in <9a758ff4db6c48d6b3d4d0e5c2adf6d1>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x00009] in <e4ba2224a87c42cbadcd524985619ee3>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass14_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x0004b] in <e4ba2224a87c42cbadcd524985619ee3>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x0011c] in <e4ba2224a87c42cbadcd524985619ee3>:0

**Comment by warwickmm** [comment]
Is your backup job configured with a local destination folder that is actually an sshfs mount point?  So when it's unmounted or unreachable, the destination folder will appear empty?  That could be why Duplicati is confused, since it expects to be able to see all the files on the backend.  Duplicati doesn't know that the "local" folder is actually a remote filesystem and is unreachable.  It probably saw that the destination folder is all of a sudden empty (and hence inconsistent with the local database).

In my opinion, this configuration is too fragile.  Is there a reason why you aren't using SFTP instead?

**Comment by ts678** [comment]
> Run the job again, it will fail and tell you that the database needs to be repaired

If this is reproducible from scratch using a tiny backup (not 1 TB) of test data, a [database bug report](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#creating-a-bug-report) and a [log-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file) might be helpful. Potentially [log-file-log-level](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file-log-level) might also need to get heavier later. Were there any other error messages leading to request to repair?

> In my opinion, this configuration is too fragile

That could very well be, but fragile systems might be good test vehicles for reproducing problems that potentially occur other ways. Although it does lead to problems sometimes, people do back up to various network file systems which fail more than local drives...
