### ISSUE TITLE
How to run on QNAP TS-453D

### ISSUE THREAD

**Issue by gcstang** [duplicati/duplicati#4474]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.114
- **Operating system**: QNAP 4.5.2.1594
- **Backend**: qnapclub

## Description
After upgrading to this version going to the URL shows
Resource not found: http://192.168.1.31:8216/login.html
No contact at QnapClub, no support, no help

## Steps to reproduce
1. Uninstalled
2. Reinstalled
3. Same issue

## Debug log
No log located here
/share/CACHEDEV1_DATA/.qpkg/Duplicati/duplicati.log

Process looks like
14340 admin    115240 S   /share/CACHEDEV1_DATA/.qpkg/Qmono/bin/mono-sgen /share/CACHEDEV1_DATA/.qpkg/Duplicati/Duplicati/updates/2.0.5.114/Duplicati.Server.exe --log-file=/share/CACHEDEV1_DATA/.qpkg/Duplicati/duplicati.log --webservice-port=8216 --webservice-interface=* --tempdir=/opt/Duplicati/tmp

Humbly, maybe you could create a version that is stable since this is related to backing up essential files instead of relying on qnapclub as they don't provide support.

**Comment by warwickmm** [comment]
What version of Duplicati were you using previously?  I don't think anything has changed recently regarding the webservice.

You will get better support for this type of question in the forums.

https://forum.duplicati.com/

It looks like there are several users there that run Duplicati on QNAP, and there are posts about similar sounding issues.  The following user found that a reboot solved the problem:

https://forum.duplicati.com/t/duplicati-new-version-2-0-5-0/8810

I'm going to close this for now, but if we determine that there are code changes to make we can reopen this with some more details.
