### ISSUE TITLE
Issue with db naming in dbconfig.json

### ISSUE THREAD

**Issue by funnym0nk3y** [duplicati/duplicati#4475]
----------------------------------------

## Environment info

- **Duplicati version**: 2.0.5.114_canary_2021-03-10
- **Operating system**: Win 10 
- **Backend**: OneDrivev2

## Description
When recreating a database with the UI a db with the name of `LGGXBSAOIQ.sqlite` ist created, but the CLI expects `JVXLBQDUEN.sqlite`. That file is also described in `dbconfig.json` in `Databasepath`. So when specifying a backup name e.g. `Alpha - OneDrive` in the CLI it works on a completely different sqlite database than with the web UI. Also when investigating the issue I tried to open `Duplicati-server.sqlite` with several programs but apparently it is not a sqlite database (at least that is why those programs failed).

**Comment by warwickmm** [comment]
The CLI and UI interfaces are independent.  The CLI does not communicate with the server that the web UI uses:

https://github.com/duplicati/duplicati/issues/2693#issuecomment-327440337
https://forum.duplicati.com/t/cmd-line-backup-does-not-sync-web/1642/6

For a command-line tool to interact with the web server, see 

https://github.com/Pectojin/duplicati-client

> Also when investigating the issue I tried to open Duplicati-server.sqlite with several programs but apparently it is not a sqlite database (at least that is why those programs failed).

I believe `Duplicati-server.sqlite` on Windows is encrypted:

https://forum.duplicati.com/t/which-tool-can-open-encrypted-db/2372

**Comment by funnym0nk3y** [comment]
Okay, this explains everything. Thanks! But why live CLI and UI a seperate life?

**Comment by warwickmm** [comment]
The use case is for people who prefer headless commandline tools.  If you want to interact with the web UI configurations from the command line, take a look at [duplicati-client](https://github.com/Pectojin/duplicati-client).

**Comment by funnym0nk3y** [comment]
Yeah, I read that in one of the mentioned threads. But why don't they operate on the same server?

**Comment by warwickmm** [comment]
I think the server is only started by the TrayIcon program.  The command line tools don't use the server.

**Comment by funnym0nk3y** [comment]
Wouldn't it be more logical that both operate from the server? But anyway, thanks for the clarification!

**Comment by warwickmm** [comment]
For some people yes, for others, no.  It's possible that there are more people who think "yes", but I'm not sure. I wasn't around at the time the decision was made.
