### ISSUE TITLE
No files can be restored

### ISSUE THREAD

**Issue by ReinforcedPanda** [duplicati/duplicati#4477]
- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.5.114_canary_2021-03-10
- **Operating system**: Fedora Server 33
- **Backend**: Local Disk (ZFS FS)

## Description
Testing restoring my backups (WBD!) and for some reason duplicati says the restore completed with Warning and says "Restore completed without errors but no files were restored".
I'm not sure if this is a side effect of me changing the backup path in the "pre-script".

What I do is have pre-script run, which creates a ZFS snapshot, mounts the snapshot, then uses echo "--localpath=" to change the backup path to the snapshot path. The backups work and I can see data successfully being backed up. After the backup completes I run the post-script option which un-mounts the snapshot, and deletes it.

- **Actual result**:
No files are restored and Duplicati instead says "Restore completed without errors but no files were restored."

- **Expected result**:
My files are restored to the custom path I specified.

## Screenshots
![image](https://user-images.githubusercontent.com/4663874/113225154-93d33c80-9252-11eb-9ed8-edfcea895bf6.png)
![image](https://user-images.githubusercontent.com/4663874/113225184-a2215880-9252-11eb-969e-8a26b972cc1e.png)
![image](https://user-images.githubusercontent.com/4663874/113225202-ac435700-9252-11eb-8faf-63d8fb52ade1.png)

## Debug log
> {
>   "RestoredFiles": 0,
>   "SizeOfRestoredFiles": 0,
>   "RestoredFolders": 0,
>   "RestoredSymlinks": 0,
>   "PatchedFiles": 0,
>   "DeletedFiles": 0,
>   "DeletedFolders": 0,
>   "DeletedSymlinks": 0,
>   "MainOperation": "Restore",
>   "RecreateDatabaseResults": null,
>   "ParsedResult": "Warning",
>   "Version": "2.0.5.114 (2.0.5.114_canary_2021-03-10)",
>   "EndTime": "2021-03-31T23:55:21.630444Z",
>   "BeginTime": "2021-03-31T23:55:21.055311Z",
>   "Duration": "00:00:00.5751330",
>   "MessagesActualLength": 11,
>   "WarningsActualLength": 1,
>   "ErrorsActualLength": 0,
>   "Messages": [
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Restore has started",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  ()",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (918 bytes)",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 0 (3/31/2021 3:00:00 AM) ...",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 1 (3/30/2021 3:00:00 AM) ...",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 2 (3/29/2021 3:00:00 AM) ...",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 3 (3/28/2021 3:00:00 AM) ...",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 4 (3/26/2021 3:21:05 AM) ...",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 5 (3/25/2021 3:00:00 AM) ...",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 6 (3/17/2021 3:09:18 AM) ...",
>     "2021-03-31 18:55:21 -05 - [Information-Duplicati.Library.Main.Database.LocalRestoreDatabase-SearchingBackup]: Searching backup 7 (3/17/2021 3:03:00 AM) ..."
>   ],
>   "Warnings": [
>     "2021-03-31 18:55:21 -05 - [Warning-Duplicati.Library.Main.Operation.RestoreHandler-NoFilesRestored]: Restore completed without errors but no files were restored"
>   ],
>   "Errors": [],
>   "BackendStatistics": {
>     "RemoteCalls": 1,
>     "BytesUploaded": 0,
>     "BytesDownloaded": 0,
>     "FilesUploaded": 0,
>     "FilesDownloaded": 0,
>     "FilesDeleted": 0,
>     "FoldersCreated": 0,
>     "RetryAttempts": 0,
>     "UnknownFileSize": 0,
>     "UnknownFileCount": 0,
>     "KnownFileCount": 918,
>     "KnownFileSize": 46779789230,
>     "LastBackupDate": "2021-03-30T22:00:00-05:00",
>     "BackupListCount": 8,
>     "TotalQuotaSpace": 498636361728,
>     "FreeQuotaSpace": 485322657792,
>     "AssignedQuotaSpace": -1,
>     "ReportedQuotaError": false,
>     "ReportedQuotaWarning": false,
>     "MainOperation": "Restore",
>     "ParsedResult": "Success",
>     "Version": "2.0.5.114 (2.0.5.114_canary_2021-03-10)",
>     "EndTime": "0001-01-01T00:00:00",
>     "BeginTime": "2021-03-31T23:55:21.055316Z",
>     "Duration": "00:00:00",
>     "MessagesActualLength": 0,
>     "WarningsActualLength": 0,
>     "ErrorsActualLength": 0,
>     "Messages": null,
>     "Warnings": null,
>     "Errors": null
>   }
> }

**Comment by ReinforcedPanda** [comment]
Here is a copy of my script. I can confirm that the change of localpath is probably what is causing this issue. My duplicati configs that don't change the path, restores work just fine.

> #!/usr/bin/env bash
> 
> ZFS_FS_NAME=$1
> ZFS_SNAPSHOT_NAME=$2
> MOUNT_PATH="/mnt/snapshot"
> 
> if [[ ! -z "$(ls -A $MOUNT_PATH)" ]]; then
>     printf "[ERROR] The backup mount directory, $MOUNT_PATH is not empty.\n"
>     exit 5
> fi
> if [[ -z "$(zfs list 2>/dev/null | grep $ZFS_FS_NAME)" ]]; then
>     printf "[ERROR] The ZFS filesystem $ZFS_FS_NAME does not exist.\n"
>     exit 5
> fi
> if [[ ! -z "$(zfs list -t snapshot 2>/dev/null | grep "$ZFS_FS_NAME@$ZFS_SNAPSHOT_NAME")" ]]; then
>     printf "[ERROR] The ZFS snapshot $ZFS_SNAPSHOT_NAME already exists.\n"
>     exit 5
> fi
> 
> zfs snapshot -r "$ZFS_FS_NAME@$ZFS_SNAPSHOT_NAME"
> mount -t zfs "$ZFS_FS_NAME@$ZFS_SNAPSHOT_NAME" "$MOUNT_PATH"
> echo "--localpath=\"$MOUNT_PATH\""
> 
> if [[ -z "$(ls -A $MOUNT_PATH)" ]]; then
>     printf "[ERROR] Snapshot was created but failed to mount. (empty directory)\n"
>     exit 5
> fi
> 
> printf "[INFO] Snapshot was created and mounted. Ready for duplicati.\n"
> 
> exit 0

**Comment by drwtsn32x** [comment]
How about changing your script so it only does something during Backup operations, but not other operations like Restore?

```
if [[ "$DUPLICATI__OPERATIONNAME" == "Backup" ]] ; then
...
...
fi
```

**Comment by ReinforcedPanda** [comment]
> 
> 
> How about changing your script so it only does something during Backup operations, but not other operations like Restore?
> 
> ```
> if [[ "$DUPLICATI__OPERATIONNAME" == "Backup" ]] ; then
> ...
> ...
> fi
> ```

That was it 🤦‍♂️ I did not realize those scripts ran on restore operations as well. It's working as intended now.
