### ISSUE TITLE
Large Duplicati-server.sqlite file

### ISSUE THREAD

**Issue by sttehh** [duplicati/duplicati#4479]
- [x ] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------
- **Duplicati version**: 2.0.5.1_beta_2020-01-18
- **Operating system**:  Docker on Linux
- **Backend**: onedrive

## Description
for several Weeks my Duplicati-server.sqlite file has geon up to 24 GB, while is now stuck in this size ( it's not growing anymore, but it is much too large i guess 
my loglevel are set to warinig/error, im  am using a logfile too, the retention time is set to 10 days
log-file-log-level: error
log-file:/config/server.log
log-level:error
log-retention:10d

i guess it's a similar erro as described in Issue #1707 &  #1298

**Comment by warwickmm** [comment]
@sttehh, you will likely get better support by asking this in the forums.  Other users may have encountered the same problem and have suggestions.

https://forum.duplicati.com/
