### ISSUE TITLE
File backend does not truncate existing files when overwriting

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#4486]
I tired to validate after while all files produced by Duplicati and run to an issue, that backup-verification.json are not valid.
Each are big 500KB-1MB. Screenshots are showing where is problem

![image](https://user-images.githubusercontent.com/2264442/115414952-cbe8f200-a1f6-11eb-88c2-bf468d3ea039.png)
![image](https://user-images.githubusercontent.com/2264442/115415053-defbc200-a1f6-11eb-821b-bd8063db5ef9.png)
![image](https://user-images.githubusercontent.com/2264442/115415153-f2a72880-a1f6-11eb-89de-0af489ce35f9.png)

Code producing file is pretty straightforward https://github.com/duplicati/duplicati/blob/cda96257dc3d22bbcf34e13f48138a4e2398044f/Duplicati/Library/Main/Operation/FilelistProcessor.cs#L162

So there is either problem in database, or casting problem I think.
Why there is casting to IRemoteVolume https://github.com/duplicati/duplicati/blob/cda96257dc3d22bbcf34e13f48138a4e2398044f/Duplicati/Library/Main/Database/IRemoteVolume.cs
This has smaller set of properties.

GetRemoteVolumes is returning IEnumerable<RemoteVolumeEntry> which has full scope of properties which are in json https://github.com/duplicati/duplicati/blob/cda96257dc3d22bbcf34e13f48138a4e2398044f/Duplicati/Library/Main/Database/RemoteVolumeEntry.cs

Question is if it is explaining JSON corruption and if others have invalid JSON too. 
Not all my backups have invalid JSON (old and big one have).

Last idea, it could be serialization error.

Thanks

**Comment by warwickmm** [comment]
Not sure what's going on here, but if these are really old, it seems that revision 3ff2f1eb98bdcc84776315e854f8ef29b5d218e6 changed the `RemoteVolumeEntry` constructor (different number of arguments).  Perhaps that might have caused some issues?

https://github.com/duplicati/duplicati/commit/3ff2f1eb98bdcc84776315e854f8ef29b5d218e6#diff-981a7c26c6bd5084f799fb97ab2b82ef826c99faca933c209e84a10cbc7ca563

**Comment by mnaiman** [comment]
Ok, I narrowed down cause.

To that line, file is on and valid. So not a problem of casting or serialization.
https://github.com/duplicati/duplicati/blob/cda96257dc3d22bbcf34e13f48138a4e2398044f/Duplicati/Library/Main/Operation/FilelistProcessor.cs#L188

I have intercept tempfile which is generated and content is valid JSON.

Next steps which i took:
Deleted backup-verification.json file at target. After backup run, new backup-verification.json is created and is equal to temp file = valid file, JSON file size 62KB.
So I restored back JSON at target, and it was 700KB.
Run backup again, JSON at target still 700KB (invalid).
So I have created new dummy file full of char X size 1MB at target name backup-verification.json
Run backup, checked content and bum!
![image](https://user-images.githubusercontent.com/2264442/115468851-f5743e80-a233-11eb-818c-96443b7f48cf.png)

This is what was causing corruption, file is not overwritten on target as whole, but only "up to size" of source file.
My target is file based. Going to check if SFTP backups are affected too.

If backend.PutUnencrypted is affected, that could have larger impact not just on verification.json.

**Comment by mnaiman** [comment]
Ok, no SFTP backup is affected with problem all backup-verification.json are ok.

**Comment by warwickmm** [comment]
Could this be a problem?  The File backend calls `systemIO.FileOpenWrite`
https://github.com/duplicati/duplicati/blob/cda96257dc3d22bbcf34e13f48138a4e2398044f/Duplicati/Library/Backend/File/FileBackend.cs#L188-L196

which calls `File.OpenWrite`

https://github.com/duplicati/duplicati/blob/cda96257dc3d22bbcf34e13f48138a4e2398044f/Duplicati/Library/Common/IO/SystemIOLinux.cs#L85-L87

[File.OpenWrite](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.openwrite?view=netframework-4.7.1#remarks)  doesn't truncate if the file exists:

>The OpenWrite method opens a file if one already exists for the file path, or creates a new file if one does not exist. For an existing file, it does not append the new text to the existing text. Instead, it overwrites the existing characters with the new characters. If you overwrite a longer string (such as "This is a test of the OpenWrite method") with a shorter string (such as "Second run"), the file will contain a mix of the strings ("Second runtest of the OpenWrite method").

**Comment by mnaiman** [comment]
https://github.com/duplicati/duplicati/blob/cda96257dc3d22bbcf34e13f48138a4e2398044f/Duplicati/Library/Backend/File/FileBackend.cs#L188-L196
Exactly file I'm reading now :)) 

BTW: Im on Windows.

**Comment by mnaiman** [comment]
But this is root cause, nicely described on MSDN.

**Comment by warwickmm** [comment]
I was afraid that the same problem would occur when restoring (and overwriting), but it seems that we manually truncate here

https://github.com/duplicati/duplicati/blob/cda96257dc3d22bbcf34e13f48138a4e2398044f/Duplicati/Library/Main/Operation/RestoreHandler.cs#L880-L881

**Comment by warwickmm** [comment]
Looks like the bug might have been introduced in revision 71c6aca8a787fe09ea0013732e099b6953e1a83a.  `File.Open` with `FileMode.Create` was changed to `File.OpenWrite`:

![image](https://user-images.githubusercontent.com/17345532/115472301-73adf200-a1ee-11eb-98f9-80ec803e205b.png)


https://github.com/duplicati/duplicati/commit/71c6aca8a787fe09ea0013732e099b6953e1a83a#diff-333572b0bc7cecd26acfe9e3edc43c71ed6b9f614c9a419322549e036c6ff08d

**Comment by warwickmm** [comment]
The fix should be simple (change `systemIO.FileOpenWrite` to `systemIO.FileCreate`).  Do you want to create the PR, or should I?

Thanks for noticing this.

**Comment by warwickmm** [comment]
I submitted pull request #4488.

**Comment by mnaiman** [comment]
Thx for PR, I fell asleep yesterday. I will test that on next canary build.
