### ISSUE TITLE
Bug: Nextcloud folder missing in remote back-up

### ISSUE THREAD

**Issue by rmartensen** [duplicati/duplicati#4487]
Bug: Nextcloud folder missing in remote back-up

## Environment info
- **Duplicati version**: 2.0.5.114_canary_2021-03-10
- **Operating system**: Windows 10 (Build 19042.928)
- **Backend**: onedrivev2 

## Description
I'd an backup integrity check and found that my Nextcloud folder is missing from the remote backup. 

## Steps to reproduce
1. Go to restore tab
2. Select OneDrive backup
3. Select files
4. Restore Nextcloud folder (Should be in this directory: C:\Users\{myuser}\Nextcloud)

- **Actual result**:
The entire Nextcloud folder (C:\Users\{myuser}\Nextcloud) is missing in my home directory.

- **Expected result**:
Since my home directory is selected for back-up, my Nextcloud folder should also be able to restore from this back-up.
I checked the permissions on this folder, those are exactly the same as my home directory.

## Screenshots
I could include screenshots on request, but don't think it's necessary in this case.

## Debug log
-

## Fix
I managed to 'fix' this issue when I'd uncheck the boxes "Hidden files" and "System files" in the back-up's "Source Data" tab.
Now I see my Nextcloud folder is being backed-up properly.

Since this folder isn't a hidden or system folder I think this might be a bug.

**Comment by warwickmm** [comment]
I don't have any experience with nextcloud, but this link seems to indicate that the nextcloud folder can be marked as a system folder.  Can you confirm that it's not a system folder in your case?

https://help.nextcloud.com/t/total-commander-does-not-show-nextcloud-main-folder/71602/3

**Comment by lupinehorror** [comment]
i wonder if this has to do with the recently released virtual file support.
https://nextcloud.com/blog/nextcloud-desktop-client-3-2-with-status-feature-and-virtual-files-available-now/
it changed the behaviour of my client and nextcloud no longer appears as a 'system' directory on my windows 10 install.

**Comment by rmartensen** [comment]
> I don't have any experience with nextcloud, but this link seems to indicate that the nextcloud folder can be marked as a system folder. Can you confirm that it's not a system folder in your case?
> 
> https://help.nextcloud.com/t/total-commander-does-not-show-nextcloud-main-folder/71602/3

Ah yes, it seems to be a system folder. That's a real issue because I sync most important data to Nextcloud and it would be a huge loss if something happens and I don't have a proper off-site back-up of that data.
Is there a way to make some kind of exception for Nextcloud? I could imagine someone might be in trouble because I think most Duplicati users won't know that the Nextcloud folder is actually a system folder.

![Screenshot 2021-04-21 095107](https://user-images.githubusercontent.com/9069215/115518204-339b4d80-a288-11eb-9358-5682e5bfa53c.png)

**Comment by warwickmm** [comment]
I think making an exception for Nextcloud will be confusing, since the "system files" filter will then mean "some system files".  Perhaps it's rare, but what if there are users that do know the Nextcloud folder is a system folder and are relying on that behavior?

If you want to always include this folder, you can try adding an include filter to see if that overrides the "system files" filter.

https://forum.duplicati.com/t/include-filter-on-gui-for-a-range-of-characters/11241

**Comment by rmartensen** [comment]
> 
> 
> I think making an exception for Nextcloud will be confusing, since the "system files" filter will then mean "some system files". Perhaps it's rare, but what if there are users that do know the Nextcloud folder is a system folder and are relying on that behavior?
> 
> If you want to always include this folder, you can try adding an include filter to see if that overrides the "system files" filter.
> 
> https://forum.duplicati.com/t/include-filter-on-gui-for-a-range-of-characters/11241

That makes sense, although I think that something needs to change to make it more obvious for regular users because it just doesn't make sense that there would be a system folder in a user's home directory.
Maybe I'm stupid but when I selected the "system files" checkbox I was thinking that folders like "C:\Windows\" and "C:\Program Files\" would get excluded.

**Comment by warwickmm** [comment]
> it just doesn't make sense that there would be a system folder in a user's home directory.

I don't know why Nextcloud would do that..  Does @lupinehorror's comment above imply that this might change in a recent release?

**Comment by warwickmm** [comment]
I'm actually a bit confused now.  It seems that Duplicati's "System Files" filter doesn't exclude Windows System Folders (Duplicati's "Operating System" does).  However, the "System Files" filter does respect Windows registry entries.

Is it possible that your Nextcloud folder is listed in the registry somewhere, perhaps like the below?

```
<something>\SYSTEM\CurrentControlSet\Control\BackupRestore\FilesNotToBackup
```

**Comment by warwickmm** [comment]
@rmartensen, was your "System files" filter specified using the "Exclude filter group" dropdown, or an "Exclude" check box?

![image](https://user-images.githubusercontent.com/17345532/115618134-1d50ba00-a2a7-11eb-8a24-5d7a22c24b33.png)

If the latter, then that will exclude Windows "System Folders".

**Comment by ts678** [comment]
> when I selected the "system files" checkbox I was thinking that folders like "C:\Windows" and "C:\Program Files" would get excluded.

The `Filters` section is path-based. What's difficult to notice is that the `Exclude` section is based on file attributes and sizes.

[How to Change File Attributes with Attrib from the Windows Command Prompt](https://www.howtogeek.com/205910/how-to-change-file-attributes-with-attrib-from-the-windows-command-prompt/) says how to show or change some attributes.
[dir](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir) command can filter on some. If using File Explorer, there's an `Attributes` column available. Some codes are decoded [here](https://superuser.com/questions/44812/windows-explorers-file-attribute-column-values).
Personally, I find it surprising how Microsoft set some of their attributes (e.g. `system`), but Duplicati goes by what it is given...

Paths are more able to change (though any changes might break existing backups). You can run `help filter-groups` to see
what paths are considered to be in a given group. It's customized to the user, so is best run as them, or in GUI [Commandline](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#using-the-command-line-tools-from-within-the-graphical-user-interface).

**Comment by warwickmm** [comment]
I don't think there's anything that we can do here, so I'm going to close this.  If you want a "less-strict" system files filter, try using the "Exclude filter group -> System Files" filter as opposed to the "Exclude -> System files" checkbox as shown in the [above image](https://github.com/duplicati/duplicati/issues/4487#issuecomment-824343852).
