### ISSUE TITLE
Suggestion: Checkboxes on the treeview when selecting folders to backup 

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#449]
_From [dario.fo...@gmail.com](https://code.google.com/u/104275208564400025811/) on July 10, 2011 04:26:40_

I know we can choose later, in Filters, individual folders or files to backup, but I think it would be more convenient (and easier for the average user) to be able to select folders via checkboxes on the treeview (in the Custom folder list), much like when selecting files to restore.

At work I use another program which has this and an extra checkbox to toggle automatic check/uncheck subfolders. With Duplicati I would have to go through the tree quite a few times, one for each folder to add/exclude, which would be a tedious, time-consuming task.

Unfortunately, my colleagues folder-naming practices makes filters run for their sanity...

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=449_

**Comment by Drolla** [comment]
The usability of Duplicati could indeed be greatly enhanced by providing a directory tree that allows a convenient selection (=inclusion) and exclusion of multiple directories. My preference would be a directory tree where each displayed directory has one of the following 3 selection states:

- Inheritance : This is the default. The directory inclusion/exclusion state corresponds to the one of the parent directory. New directories added to the file system will automatically get this selection state.
- Inclusion : The (sub)directory is included into the backup
- Exclusion : The (sub)directory is excluded to the backup

**Comment by kenkendk** [comment]
@Drolla This is fixed in the latest experimental release:
https://github.com/duplicati/duplicati/releases
