### ISSUE TITLE
Pause did not work

### ISSUE THREAD

**Issue by Hoffenbar** [duplicati/duplicati#4500]
- **Duplicati version**: 2.0.6.1
- **Operating system**: Windows 10
- **Backend**: Harddisk

## Description

Clicking on PAUSE has no visible effect. The progressbar is evolving, information about backed up files are shown.

## Steps to reproduce

1. Start a long running backup, watch the display for changes
2. Click Pause and watch for changes again

- **Actual result**:
Backup continues to run, it seems
- **Expected result**:
Backup should pause as soon as possible (I think a logical unit of work have to be finished, so it's reasonaby if the pause does not happen immediately; but it should after a minute or so)

**Comment by warwickmm** [comment]
Thanks @Hoffenbar.  This is a known issue.  See #3565.
