### ISSUE TITLE
Alternate Destination Marker and -Path

### ISSUE THREAD

**Issue by Hoffenbar** [duplicati/duplicati#4504]
- [ ] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.1 (the same with 2.0.5.1)
- **Operating system**: Windows 10
- **Backend**: Local Disk

## Description

Couldn't get it managed to use different USB-Drives. From time to time I unplug one of my USB drives and plugin another one. Each drive has the same folder structure and the same alternate destination markers. But when the drive which is configured as the primary destination folder path isn't plugged in, the alternate destinations are not consulted, it seems. After several minutes, the attached error message appears.
![2021-05-09 11_12_03-Window](https://user-images.githubusercontent.com/46227007/117566964-03421480-b0ba-11eb-91b7-62544cf8ffa4.jpg)

## Steps to reproduce

1. Make a backup to usb drive X:, everything ok
2. Unplug drive X:
3. Plug drive Y: (wihich contains alternate-dest-markers and identical, yet empty path)
3. Try to make a backup again (to this new drive) through the same "job"

Even if this backup wasn't already made to this drive (destination empty), Duplicaty should notice this and perform a new full backup then.

I really don't know how the manage the use of different destination drives other then configuring different backup-jobs (which have to be identical with the only difference beeing the destination drive), which probably is easiest through the command line.....

- **'Actual result**
See attached error message. No further log is mentioned in the gui, this is the only message.

- **Expected result**:
Duplicati should realize that the primary backup destination isn't reachable, and should switch to one of the other drives available.

## Screenshots

![2021-05-09 11_12_03-Window](https://user-images.githubusercontent.com/46227007/117567240-a2b3d700-b0bb-11eb-9e31-8e3f29ce4c32.jpg)

## This is my config:
[Benutzerordner-duplicati-config.json.zip](https://github.com/duplicati/duplicati/files/6447253/Benutzerordner-duplicati-config.json.zip)

## Duplicati-Log (well, part of it)
![2021-05-09 11_55_35-Window](https://user-images.githubusercontent.com/46227007/117567705-90d33380-b0bd-11eb-90aa-52aab069f460.jpg)

**Comment by warwickmm** [comment]
I think there is some confusion about what the alternate destination marker is for.  It's purpose is to solve the problem where the _same_ physical drive is assigned to a different drive letter.  It is not meant to support different physical drives.  Duplicati expects the destination files from the previous backup to be available (hence the `Found 2755 files that are missing` and `Missing file` errors when you plug in a new drive).

**Comment by Hoffenbar** [comment]
Yes, I thought i can mis-use them for another purpose :-). Thanks.
