### ISSUE TITLE
Cannot restore files with a newline character at the end of the name

### ISSUE THREAD

**Issue by LightCooling** [duplicati/duplicati#4508]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**:
  - _Create_: 2.0.5.1
  - _Restore_: 2.0.6.1_beta_2021-05-03
- **Operating system**: Ubuntu 20.04
- **Backend**: WebDAV

## Description

For some reason, I have several file names ending with newline character `\n` in my backup.
All files exist in the backup and are listed in the restore settings. But after restoring, these files are missing.
After some attempts, I found that files are not restored when the parent folder is fully selected to restore.
These files can be successfully restored if I do not select all files in the folder.

## Steps to reproduce

1. Create files with name ending in `\n`
2. Backup folder
3. Try to restore the entire folder

- **Actual result**:
No files were restore
- **Expected result**:
Successful restore

## Screenshots
![Screenshot bug Duplicatipng](https://user-images.githubusercontent.com/20073774/118310224-c174fc00-b507-11eb-803f-fc1886dc7baf.png)

**Comment by warwickmm** [comment]
Thanks @LightCooling, I am able to reproduce this.  The problem is due to the default behavior of `.` in a regular expression not matching newline characters.  I have a candidate fix that will need some testing and careful review since it does change the behavior of our filtering code.
