### ISSUE TITLE
*.mwb files: ignored?

### ISSUE THREAD

**Issue by JackHewson** [duplicati/duplicati#4517]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.1_beta_2021-05-03
- **Operating system**: Windows 10
- **Backend**:  Harddisk

## Description

MySQL Workbench (https://www.mysql.com/products/workbench/) creates *.mwb files.
Is it possible that these files are not backuped?

## Steps to reproduce

1. create `mwb` file by MySQL Workbench
2. create a backup, Exclude: "[x] Temporary files"
3. run the backup 
4. search backup by `mwb` or the whole filename

- **Actual result**:
The file is not part of the backup.

- **Expected result**:
The file should be part of the backup.

**Comment by warwickmm** [comment]
Looks like mwb files are marked as temporary.  Since you are excluding temporary files, these will be excluded.

https://bugs.mysql.com/bug.php?id=84028

**Comment by JackHewson** [comment]
I see, thank you!
