### ISSUE TITLE
backup source change keeps ssh finger pring string

### ISSUE THREAD

**Issue by ukrolelo** [duplicati/duplicati#4518]
Latest duplicati on linux debian.
When creating the backup rule with destination ssh, after editing it back and changing the destination to something else it still keeps the ssh fingerprint string in the mono command and gives warning.
After deleting and making a new backup,warning doesnt apear and its fine.

**Comment by warwickmm** [comment]
Thanks @ukrolelo.  This is a known issue (see #3082).
