### ISSUE TITLE
duplicati.service doesn't keep Duplicati backups running

### ISSUE THREAD

**Issue by Xavron** [duplicati/duplicati#4519]
Fedora 33
Latest Duplicati version and previous.

## Description
Duplicati's systemd use has two issues:

1) Fails to keep Duplicati running through suspend and resumes despite status of running for Duplicati's systemd use. A few days at best then it fails.

2) Starting Duplicati through the application icon results in failure first time and Duplicati starting, then second use brings up Duplicati. This is in relation to duplicati.service.

## Steps to reproduce
Install Duplicati onto a computer. Setup. Wait a few days.

- **Actual result**:
Duplicati stops running backups whether they be hourly or otherwise. Nothing happens until its manually started.

- **Expected result**:
Duplicati should always run backups as that's what it is supposed to do.

At this time I will not be attempting to attach logs for this. Duplicati.service status shows running but nothing happens. I have to assume the issue is in the direction of `ExecStart=/usr/bin/duplicati-server $DAEMON_OPTS` as that is what the service is using.

If Duplicati is supposed to be using something else to keep running then I have failed to see what is.

Currently testing ~/.config/autostart with Duplicati source and that appears to be working just fine (fixing both points above) but I only just started testing this.

Its possible that with Duplicati installed to system, that another duplicati.service eg "duplicati-start.service" using eg "mono .../Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release/Duplicati.GUI.TrayIcon.exe" might fix the issue as well.

But, if there's something that can be done with duplicati.service and duplicati-server, I haven't looked into it.

If duplicati.service isn't meant to keep backups running then I haven't seen anything that should. Duplicati when installed officially should keep backups running.

**Comment by warwickmm** [comment]
Thanks @Xavron.  Can you create a post in the forums to see if other users have encountered this?  I've never experienced any of the described issues on Arch using the service files [here](https://aur.archlinux.org/cgit/aur.git/tree/?h=duplicati-latest).  I'm not very familiar with configuring systemd services, but perhaps there's something subtle that's missing.

**Comment by Xavron** [comment]
Could be. I will look into it further in about a week.

If I understand correctly, the duplicati-server logs are combined into the regular logs, so will check into that also. Maybe there's something there as I wasn't looking there previously with a focus on that.

**Comment by ts678** [comment]
I am not a systemd expert, but what sort of symptoms are implicating systemd, or duplicati.service, or the ExecStart that it does?
The main one would that it's reportedly working when not under systemd, but in systemd one, is Duplicati seen there, or in `ps`?

> Duplicati.service status shows running

If that's `systemctl status duplicati.service`, does it show two Duplicati processes below it? That might be all systemd does.

```
 systemctl status duplicati.service
● duplicati.service - Duplicati web-server
     Loaded: loaded (/lib/systemd/system/duplicati.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-05-24 10:07:28 EDT; 15min ago
   Main PID: 21857 (mono)
      Tasks: 14 (limit: 2310)
     Memory: 71.7M
     CGroup: /system.slice/duplicati.service
             ├─21857 DuplicatiServer /usr/lib/duplicati/Duplicati.Server.exe
             └─21861 /usr/bin/mono-sgen /usr/lib/duplicati/Duplicati.Server.exe
```

Is the web UI displayed and responding? If so, Duplicati is up. Does its status bar talk about next backup time? Is it already past?
While on that line, look to its right at the pause/resume indicator to see whether Duplicati has somehow not come out of pause.
There are a couple of reports on this in GitHub issues and the forum (but none on Linux), but no clear conclusions were reached.

https://github.com/duplicati/duplicati/blob/0a43410535d89e3e8ca93e78f799b9cec8812310/Duplicati/Server/LiveControls.cs#L344-L349

For each scheduled job on the screen, there should also be a "Next scheduled run" time. Has the time there also already passed?
About --> System info gives some pause information, if a pause/resume problem is suspected. After I hit pause in GUI, it shows

```
estimatedPauseEnd : 2021-05-24T10:36:35.5734868-04:00
activeTask :
programState : Paused
```

What is the Backend? Another possibility may be that you suspended in the middle of a transfer, and wake didn't finish or error.
This would be more likely with a remote destination, but the backup that didn't resume run should be visible on GUI status bar.
These could possibly be seen in the job logs or the server log at About --> Show log --> Stored, but a good server-level view is
[Duplicati.Server.exe](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicatiserverexe) with --log-file=\<path> and --log-level=retry to watch remote action. Edit /etc/default/duplicati and restart.

**Comment by Xavron** [comment]
> does it show two Duplicati processes below it?

I will have to look at that again since you provide an example. Its not in use right now so will look at it next week. However status was running (not failed).

> Is the web UI displayed and responding? If so, Duplicati is up

No. That's the funny thing. The application .desktop (starting Duplicati from Applications) use for the most part forces Duplicati to run backups but fails to produce the UI on first use when its - for what I have to explain it as - is not running since backups no longer run. This is when using systemd after 2-3 days despite systemctl status still showing duplicati-server as running.

First use of .desktop for getting to Duplicati in applications, even though it fails to produce the UI, leads to Duplicati running the backup again.

Second use of .desktop leads to the UI showing up.

So far it only happens when Duplicati is set to run backups via systemd.

> For each scheduled job on the screen, there should also be a "Next scheduled run" time

I have set to never end and hourly. Next run time always shows in 1h. Pause or whatever is never triggered by me. Again... backups start running again on first use of .desktop attempt.

> What is the Backend? Another possibility may be that you suspended in the middle of a transfer, and wake didn't finish or error.
This would be more likely with a remote destination, but the backup that didn't resume run should be visible on GUI status bar.

This happens even with local folder on flash drive that is always attached and mounted. I see not a single issue from another backup software. Backups always run with this drive.

I believe its a problem with Duplicati but yes I could be missing something stupid. I'm not expecting it however.

**Comment by Xavron** [comment]
Little update on this.

`systemctl restart duplicati.service` apparently gets the backups running again.

The status showed the following before I restarted it

```
● duplicati.service - Duplicati web-server
     Loaded: loaded (/etc/systemd/system/duplicati.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2021-06-06 07:08:39 EDT; 1 day 11h ago
   Main PID: 1330 (mono)
      Tasks: 36 (limit: 19037)
     Memory: 587.3M
        CPU: 2min 59.018s
     CGroup: /system.slice/duplicati.service
             ├─1330 DuplicatiServer /usr/lib/duplicati/Duplicati.Server.exe
             └─1445 /usr/bin/mono-sgen /usr/lib/duplicati/Duplicati.Server.exe
```
And the last hourly update was this morning. I gave it an hour or two of time to run again.

The only visible difference looks to simply be that I installed to user .service use path instead of it being in the package installed path since the rpm package doesn't apparently supply the .service file. The rpm post install script does oddly check for it but that's it. I noticed that or something along those lines was brought up years ago.

Will look better into the logs next time it happens.

**Comment by Xavron** [comment]
Oh and the other point is solved by not starting with the .desktop file through Applications as that starts a 2nd Duplicati with a different port. Using browser allows the UI to show on the first try.

**Comment by kenkendk** [comment]
I believe this is fixed with updated RPM packages.
