### ISSUE TITLE
Replace usages of Utility.IsMono

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#4525]
We should remove usages of `Utility.IsMono`, as it will always return `false` in .NET 5.  The usages need to be studied to see if separate code paths are still necessary (most likely not, but there may be some usages that were proxies for os-specific code).

**Comment by drehtisch** [comment]
I would like to take care of this issue. The bottom line is to remove Mono specific code. Have I understood this correctly so far?

**Comment by warwickmm** [comment]
Thanks @drehtisch.  There's an [open question](https://github.com/duplicati/duplicati/pull/3124#issuecomment-850688009) regarding how we plan on dealing with users that still require .NET 4.8 Framework and whether we need to maintain mono-specific code paths or not.  Please feel free to join in on the conversation there, and if you want to get a head start on removing mono-specific code, that would be welcome as well.

**Comment by drehtisch** [comment]
If there are no objections, I would like to start removing the mono-specific code. If there are parts removed that definitely need to be kept, this could be brought up during the review and I will be happy to restore those parts.

**Comment by warwickmm** [comment]
Thanks @drehtisch.  To start, I would base your work off the `netstandard` branch.

**Comment by drehtisch** [comment]
I create a branch from the `netstandard` branch then? Or do i need to fork the repo to be able to create a pull request? I don't know what works or is preferred.

**Comment by warwickmm** [comment]
You should fork the repository and branch off of `netstandard`.
