### ISSUE TITLE
Fix SQLite issues on Linux and MacOS

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#4526]
There are some SQLite issues due to resolve.  The separate code path due to

https://github.com/duplicati/duplicati/blob/bd172d39c87704d1eb8815850add9ef49cdbcdbb/Duplicati/Library/SQLiteHelper/SQLiteLoader.cs#L168

results in errors like
```
Native library pre-loader failed to load native SQLite library "/home/ken/documents/code/duplicati/Executables/net5/Duplicati.GUI.TrayIcon/bin/Debug/net5.0/SQLite/win64/SQLite.Interop.dll" (getLastError = 203): System.DllNotFoundException: Unable to load shared library '__Internal' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: lib__Internal: cannot open shared object file: No such file or directory
   at System.Data.SQLite.UnsafeNativeMethodsPosix.dlopen(String fileName, Int32 mode)
   at System.Data.SQLite.NativeLibraryHelper.LoadLibraryPosix(String fileName)
   at System.Data.SQLite.NativeLibraryHelper.LoadLibrary(String fileName)
   at System.Data.SQLite.UnsafeNativeMethods.PreLoadSQLiteDll(String baseDirectory, String processorArchitecture, Boolean allowBaseDirectoryOnly, String& nativeModuleFileName, IntPtr& nativeModuleHandle)
```

We may be able to simply use the `System.Data.SQLite.Core` package from NuGet.  This already seems to done in https://github.com/tsuckow/duplicati/commit/a759995e7bb3472be524b76b3e0c9d5751a0d68b.

**Comment by warwickmm** [comment]
This is related to issue #4525.

**Comment by warwickmm** [comment]
With some minor changes (related to #4527 and #4526), I was able to get the tests to run:

https://github.com/warwickmm/duplicati/actions/runs/883834505

The macOS tests are failing for the known (weird) timestamp issue that is "fixed" in `master` (by allowing for a larger tolerance).  The UI tests are failing because I think no encryption modules are detected (and hence the "passphrase" element cannot be found).  When I run the tray icon project, I encounter similar issues:

![image](https://user-images.githubusercontent.com/17345532/119912105-9fb84380-bf0f-11eb-835b-8c39641467ef.png)

Sometimes refreshing the page helps, other times it doesn't.

**Comment by ts678** [comment]
Maybe broader use would allow broader DB weak-encryption like Windows gets? One worry is that it's only x86 and x64, right?

**Comment by warwickmm** [comment]
Someone (ideally with an ARM device and the ability to build the project) will need to investigate ARM support for all of our dependencies.  It sounds like .NET support for Apple M1 devices isn't planned until .NET 6.
