### ISSUE TITLE
Replace or remove dependence on libappindicator

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#4529]
The `appindicator-sharp` libraries (e.g., `appindicator-sharp.dll`, `gdk-sharp.dll`, `gtk-sharp.dll`, `atk-sharp.dll`, `glib-sharp`) are not compatible with .NET 5.  We need to replace these with compatible libraries.  The `GtkSharp` NuGet package is a candidate solution.  This appears to already be done in https://github.com/tsuckow/duplicati/commit/e0f966f9f444db5516a68eef8919fcd51e029746.

**Comment by warwickmm** [comment]
This is related to issue #4527.

**Comment by ts678** [comment]
libappindicator seems to be getting scarce, although it's not clear if potential successor [Ayatana Indicators](https://ayatanaindicators.github.io/) is widely used yet.
[Duplicati fails to install at Centos 8 #3950](https://github.com/duplicati/duplicati/issues/3950)
[libappindicator is not part of OpenSUSE - why is it needed? #3804](https://github.com/duplicati/duplicati/issues/3804)
