### ISSUE TITLE
.NET 5 Synology and BSD support

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#4531]
.NET 5 support for Synology and BSD platforms is unclear.  We will use this issue to discuss the potential difficulties and candidate solutions.

**Comment by tsuckow** [comment]
Since Synology runs on linux, the self contained builds /should/ just work. Though making it into something that installs in one click might need some finesse (I'm not that familiar with it).

As for BSD... https://github.com/dotnet/runtime/issues/14537#issuecomment-754991013 
There is supposedly someone who got .net5 runtime to build on FreeBSD but good luck shipping that.

This basically means, as of today, if you want BSD support we must do net5-split.
In theory we can even test it with https://github.com/marketplace/actions/freebsd-vm

If we kick BSD to the curb we can just do net5.

**Comment by warwickmm** [comment]
> I also think it is important we decide soon on net5-split or not. We can't be forking ourselves, we need to find one true mainline for development.

I totally agree.  In the interest of garnering more attention, I'll bring this up again in the huge conversation in #3124.

**Comment by GGG-KILLER** [comment]
About FreeBSD, apparently the Runtime Identifiers (RID) file, [`runtimes.json`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json) has FreeBSD listed.

I don't know how that works though, needs testing.

**Comment by Thefrank** [comment]
couple of things: 
- dotnet5 is not LTS so its only going to be supported until mid 2022...and thats by Microsoft for their official shipping product
- it uses libinotify under FreeBSD which has...issues with monitoring large numbers of files (50k+) due to it being a shim for kqueue
- singlefile does correctly bundle the needed libs under FreeBSD
- dotnet6 currently does not cross-build correctly nor native-build at all

that being said:
- runtime passes all tests
- aspnetcore still has failures but those are under libuv which is going away in dotnet6 anyways

so:
If you MUST move to dotNET ASAP and don't want to drop FreeBSD users, you have a temporary solution

you can get FreeBSD SDKs (or just NuGet pkgs if not building on FreeBSD) from https://github.com/Thefrank/dotnet-freebsd-crossbuild or https://github.com/Servarr/dotnet-bsd

**Comment by ts678** [comment]
Some of the FreeBSD use seems indirect, e.g. via FreeNAS or TrueNAS (which more recently is creating a Linux variant of it).
[https://usage-reporter.duplicati.com/](https://usage-reporter.duplicati.com/) shows zero FreeBSD use, but it might just be low. Maybe a better stat can be gotten.

**Comment by Thefrank** [comment]
> other: 1

if you really only have 1 remaining non-windows/linux user its pretty safe to drop support. 

it also appears from that you only ever had a max of 8 "other" classed users and never had any "FreeBSD" classed users

**Comment by GGG-KILLER** [comment]
I might be overlooking something but aren't those users being registered as Linux users?

I don't see a path for detecting BSD in <https://github.com/duplicati/duplicati/blob/beaf03562fdcf4425e962085bdf7175d6a465f49/Duplicati/Library/UsageReporter/OSInfoHelper.cs> (I'm not sure how `/etc/*-release` works in BSD).

**Comment by Thefrank** [comment]
> I might be overlooking something but aren't those users being registered as Linux users?
> 
> I don't see a path for detecting BSD in https://github.com/duplicati/duplicati/blob/beaf03562fdcf4425e962085bdf7175d6a465f49/Duplicati/Library/UsageReporter/OSInfoHelper.cs (I'm not sure how `/etc/*-release` works in BSD).

`/etc/os-release@ -> ../var/run/os-release` 

```
NAME=FreeBSD
VERSION=12.2-RELEASE-p6
VERSION_ID=12.2
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 12.2-RELEASE-p6"
CPE_NAME=cpe:/o:freebsd:freebsd:12.2
HOME_URL=https://FreeBSD.org/
BUG_REPORT_URL=https://bugs.FreeBSD.org/
```

**Comment by GGG-KILLER** [comment]
> > I might be overlooking something but aren't those users being registered as Linux users?
> > I don't see a path for detecting BSD in https://github.com/duplicati/duplicati/blob/beaf03562fdcf4425e962085bdf7175d6a465f49/Duplicati/Library/UsageReporter/OSInfoHelper.cs (I'm not sure how `/etc/*-release` works in BSD).
> 
> `/etc/os-release@ -> ../var/run/os-release`
> 
> ```
> NAME=FreeBSD
> VERSION=12.2-RELEASE-p6
> VERSION_ID=12.2
> ID=freebsd
> ANSI_COLOR="0;31"
> PRETTY_NAME="FreeBSD 12.2-RELEASE-p6"
> CPE_NAME=cpe:/o:freebsd:freebsd:12.2
> HOME_URL=https://FreeBSD.org/
> BUG_REPORT_URL=https://bugs.FreeBSD.org/
> ```

I see, that explains it. Thanks

**Comment by ts678** [comment]
My C# isn't that good. If the conclusion is that FreeBSD is distinguishable, it's possible that usage reporter has it in its [records](https://github.com/duplicati/usage-reporter).

The existing graphs might just be showing what's sent as `ostype`, There only seem to be three. `osversion` likely varies a lot.
The original Duplicati author seems to have a better query tool. I wonder if it can extract osversion data if relevant data exists?

Looking to .NET 5 future, I wonder if Duplicati also needs to become more aware of the CPU architecture that it's running on?

https://github.com/duplicati/duplicati/blob/8ee90fdf641072b1ebb6a079de351755efd953bc/Duplicati/Library/UsageReporter/ReportSet.cs#L48-L61

https://github.com/duplicati/duplicati/blob/8ee90fdf641072b1ebb6a079de351755efd953bc/Duplicati/Library/Common/Platform/Platform.cs#L39-L44

[PlatformID Enum](https://docs.microsoft.com/en-us/dotnet/api/system.platformid?view=net-5.0)

**Comment by GGG-KILLER** [comment]
Ok so, it has been a while and I've had to do OS detection recently and I've found [`RuntimeInformation`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation) and [`RuntimeInformation.IsOSPlatform`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform).
Maybe we could use it after the .NET 5 migration to do OS detection? Not saying that the current check is bad but would be less code to maintain.
(also, it seems `OSPlatform.FreeBSD` only exist in .NET Core 3.0 and up so if we need to keep mono support we might need to add our own check for FreeBSD)

**Comment by tsuckow** [comment]
My schedule this last month has been nuts, I think I left off getting FreeBSD installed in a VM and was about to try to run an sdk from @Thefrank . If I get a chance this afternoon I'll look at that some more. If that goes well, try to bake it into a github action for automated builds.

**Comment by tsuckow** [comment]
I did manage to build the server at least on freebsd. It doesn't run for lack of a sqllite interop dll.

But I should have known that System.Data.SQLite uses an esoteric version control system based on SQLite... Joy to me to try and build it so I can publish a nuget package with the freebsd build.

**Comment by Thefrank** [comment]
does the pkg version of `sqlite3` work?

**Comment by tsuckow** [comment]
The c# library uses a native SQLite.Interop.dll shim that wouldn't be in the system package.

**Comment by Thefrank** [comment]
oh yuck, it looks like the `SQLite.Interop.dll` on nuget.org is windows only :(

**Comment by tsuckow** [comment]
The core varient on the .net5 branch has windows, Linux and Macos builds in it. Freebsd is afaik the only extra one we need.

**Comment by Thefrank** [comment]
if it can already build on those platforms it should not be too hard to build under FreeBSD

**Comment by tsuckow** [comment]
I (or someone else) just need to verify the system.data.sqlite.core library is on trunk or find the appropriate tag assuming fossil even has tags. Then building should hopefully be straight forward.

**Comment by warwickmm** [comment]
I was [experiencing problems](https://github.com/duplicati/duplicati/pull/3124#issuecomment-860822835) with `SQLite.Interop.dll` on the `experimental/nett5-split` branch when trying to use the .NET 4.8 executables with Linux.  I haven't had any luck figuring out the cause.

**Comment by Thefrank** [comment]
blame microsoft's naming conventions; .net framework (aka the 4.x named stuff) is windows only afaik.
https://dotnet.microsoft.com/platform/dotnet-standard#versions

**Comment by warwickmm** [comment]
I was trying to get it to run under mono, similar to our current releases.

**Comment by Thefrank** [comment]
mono will be able to use it if the command `file SQLite.Interop.dll` says that it is mono and not something windows-y

**Comment by warwickmm** [comment]
Yup, windows.
```
$ file Executables/net48/Duplicati.GUI.TrayIcon/bin/Debug/net48/x64/SQLite.Interop.dll
Executables/net48/Duplicati.GUI.TrayIcon/bin/Debug/net48/x64/SQLite.Interop.dll: PE32+ executable (DLL) (GUI) x86-64, for MS Windows
```
I also found this:

https://www.sqlite.org/forum/forumpost/67cf1da1af

**Comment by GGG-KILLER** [comment]
I think the issue might be that mono does not support .NET Framework 4.8.
Please correct me if I'm wrong but on their [compatibility page](https://www.mono-project.com/docs/about-mono/compatibility/), they only mention support for up to .NET Framework 4.7.

**Comment by tsuckow** [comment]
It occurs to me that .net framework 4.8 has no concept of platforms and therefor only believes in windows. Therefore despite .netcore supporting multiple runtimes
![image](https://user-images.githubusercontent.com/262439/123806864-31ff8e80-d8a4-11eb-913e-8f4dae5be12e.png)

Framework only includes windows native dlls
![image](https://user-images.githubusercontent.com/262439/123807135-73903980-d8a4-11eb-84a5-aca982e8771e.png)

I did manage to compile the interop library. Not sure how portable it is. It is indeed the tip of the trunk branch of System.Data.SQLite
![image](https://user-images.githubusercontent.com/262439/123807244-899dfa00-d8a4-11eb-977a-70ac17114e92.png)

But I also just realized I'm behind the tip of the split branch which is where my SQLite patches are so I've been chasing my tail a bit looking at the build output. When I pulled the latest I ended up corrupting my FreeBSD VM through an out of memory so gotta fix that now... Not sure where the three gigs of ram went unless Duplicati wasn't exiting cleanly when it aborted.

**Comment by tsuckow** [comment]
I did manage to get it to be happy using the freebsd libSQLite.Interop.so but now I find Mono.Posix.NETStandard also has a native component. Down the rabbit hole we go.

**Comment by Thefrank** [comment]
`libdl` functions are found in `libc` under FreeBSD see [here](https://www.freebsd.org/cgi/man.cgi?query=dlopen&sektion=3&manpath=freebsd-release-ports). 

if you are building the code natively under FreeBSD use `/p:nodeReuse=false` as both `dotnet` and `dotnet msbuild` have a bad habit of never shutting down nodes. This may have caused the memory exhaustion.

**Comment by tsuckow** [comment]
I haven;t looksed at any portablility stuff, but I did manage to get Unix.Posix native lib built. It loads but the singleinstance checks fail as the lock file doesn't appear to get created

**Comment by kenkendk** [comment]
This issue covers three distinct topics.
The .NET5 update is now done (with .NET8) so the two remaining issues are registered as #5648 and #5649
