### ISSUE TITLE
Modify GitHub unit test workflow to work with .NET 5

### ISSUE THREAD

**Issue by warwickmm** [duplicati/duplicati#4537]
After we update the `netstandard` branch by merging in `master`, we should update the [unit test workflow](https://github.com/duplicati/duplicati/blob/master/.github/workflows/tests.yml) to run under .NET 5.  The OS-specific steps can be simplified (or even removed) by using `dotnet`.  We can refer to the work in https://github.com/tsuckow/duplicati/blob/4d6d671fdc11e9cce660ed58ad426eb87a549e86/.github/workflows/ci.yml, but should probably avoid using the `pipeline/selenium/test.sh` version of the UI tests and just use run `guiTests/guiTest.py` (like in the `master` branch).

For now, this task is limited to running the unit tests.  Creating build/release artifacts will be delegated to a separate task.

**Comment by tsuckow** [comment]
There is a substantial amount of work into this including switching to GitHub actions in https://github.com/tsuckow/duplicati/tree/net5ci

**Comment by warwickmm** [comment]
Thanks @tsuckow.  Ignoring the artifacts (which I think we should leave for a separate task), was it a lot of work to just get the unit tests to run?

**Comment by tsuckow** [comment]
It wasn't too bad. Mostly finding the subtle path changes if I remember correctly. And of course rewriting the build scripts to use dotnet.

**Comment by warwickmm** [comment]
Great.  The [existing workflow](https://github.com/duplicati/duplicati/blob/0a43410535d89e3e8ca93e78f799b9cec8812310/.github/workflows/tests.yml) has a lot of steps that can be simplified by using `dotnet`.

**Comment by warwickmm** [comment]
Also, I think we should just ditch AppVeyor and Travis.

**Comment by warwickmm** [comment]
With some minor changes (related to #4527 and #4526), I was able to get the tests to run:

https://github.com/warwickmm/duplicati/actions/runs/883834505

The macOS tests are failing for the known (weird) timestamp issue that is "fixed" in `master` (by allowing for a larger tolerance).  The UI tests are failing because I think no encryption modules are detected (and hence the "passphrase" element cannot be found).  When I run the tray icon project, I encounter similar issues:

![image](https://user-images.githubusercontent.com/17345532/119912105-9fb84380-bf0f-11eb-835b-8c39641467ef.png)

Sometimes refreshing the page helps, other times it doesn't.

**Comment by tsuckow** [comment]
If I'm not mistaken there should be a commit fixing the encryption as well on my branch

**Comment by tsuckow** [comment]
Back to your comment on selenium. I don't understand your aversion to selenium/test.sh as it is just a helper for the github action (or locally) to run guiTests/guiTest.py in a docker container with selenium installed.

**Comment by warwickmm** [comment]
> I see how you modified the github action to install all the things there. I guess it comes down to whether you expect developers to have selenium installed. By making scripts using docker, they can just have docker on any platform and run them to run the tests improving reproducibility.

My thought was that creating a docker container just to run the UI tests (which don't actually do that much, and historically randomly fail maybe 25% of the time) seemed a bit overkill, and is just more code to maintain.  Running it via Docker is [relatively new](https://github.com/duplicati/duplicati/pull/4005), and we used to run it directly via `guiTest.py`.

I actually don't have Docker on my main machine, and it's pretty trivial to create a python virtual environment to install the dependencies in an unobtrusive way.  Running it directly from `guiTest.py` probably makes it easier to debug, which could be helpful if we ever expand the tests to be more comprehensive.

I'm not totally opposed to the Docker approach.  I just like to avoid over complicating things if they're not absolutely necessary.

Regardless, I think we need to figure out the missing module problem.  Sometimes, the backend modules are not even detected so one cannot define a backup destination.

**Comment by warwickmm** [comment]
By the way, is there any way for `dotnet test` to summarize the test failures at the end of the run?  Currently, it seems that one has to scan all the logs to look for which tests failed.

**Comment by tsuckow** [comment]
> By the way, is there any way for `dotnet test` to summarize the test failures at the end of the run? Currently, it seems that one has to scan all the logs to look for which tests failed.

I think we would have to process the results output file and summarize it ourselves if we want to collect errors together. I do agree it is kinda annoying. We could also theoretically color them then.

**Comment by warwickmm** [comment]
I created issue #4543 to track the problem of the missing backend, compression, and encryption modules.

**Comment by warwickmm** [comment]
An interim solution to cleaning up the test logs could be to use the `minimal` verbosity.  This appears to limit the logs mainly to failed and skipped tests, which makes it much easier to identify the failures.

**Comment by warwickmm** [comment]
Issue #4554 concerns some missing resources, which causes "No encryption" to be the default encryption selection.  This results in the passphrase fields being hidden, and hence the UI tests fail.
