### ISSUE TITLE
Warning about option "verbose"

### ISSUE THREAD

**Issue by Hoffenbar** [duplicati/duplicati#4551]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.1_beta_2021-05-03
- **Operating system**: Windows 10
- **Backend**: local disk

## Description

In the GUI, one can select the option "verbose":

![image](https://user-images.githubusercontent.com/46227007/121157475-e419dc80-c849-11eb-8f63-27c41107627e.png)

If turned on, the follwoing warning is given after each backup:

![image](https://user-images.githubusercontent.com/46227007/121157616-027fd800-c84a-11eb-8825-921b9d6f1815.png)

## Steps to reproduce

1. Define a backup job with verbose=true
2. run backup

- **Actual result**:
Warning about outdated option verbose
- **Expected result**:
No warning, or the outdated option should not be available in GUI

## Screenshots

see above

**Comment by warwickmm** [comment]
This is an intentional warning to notify users that an option is no longer meaningful.  The GUI options are automatically populated, and the deprecated options will be removed in a future version.
