### ISSUE TITLE
Backup fails after switching OneDrive accounts without data transfer between both accounts

### ISSUE THREAD

**Issue by linuswagner** [duplicati/duplicati#4558]
- [X] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.1_beta_2021-05-03
- **Operating system**: Ubuntu 20.04.2 LTS
- **Backend**: OneDrive

## Description

I had switch my onedrive and did not care about existing backups, so I simply changed the backup destination in the configuration to the new onedrive (changed from OneDrive account A to Onedrive account B).
Now I'm greated with the error "Found 1961 files that are missing from the remote storage, please run repair" everytime I run the backup. However, repair does nothing and the problem repeats.
The "list" operation on remote returns "[ ]" (which is expected, since there is no backup data in account B).

## Steps to reproduce

1. Create a backup configuration for OneDrive account A
2. Backup your files
3. Change the backup destination in the configuration to OneDrive account B (where no backup data is available)
4. Get the error when running the backup
5. Click "repair"

- **Actual result**:
Nothing happens, the error happens again next time
- **Expected result**:
The missing files were created, a backup is possible again. If that is not possible, the backup shall behave as no backup was every made.

**Comment by linuswagner** [comment]
Seems like deleting the local database (Advanced -> Database ... -> Maintenance -> Delete) fixed the problem. However, from the point of useability this might still need to be improved

**Comment by warwickmm** [comment]
The failure is expected in this situation.  The client is expecting files to exist on the backend that are no longer there and the discrepancy must be addressed.  This can be due to several reasons, some of which can be "fixed" by a repair.  Perhaps in the situation where 0 files exist on the backend, a different error message should appear that doesn't recommend a repair.

**Comment by ts678** [comment]
> The missing files were created, a backup is possible again. If that is not possible

It is not generally possible to replace entire missing backup. There is no local copy, and source files can change. What of history?

> If that is not possible, the backup shall behave as no backup was every made.

History loss will occur, defeating a major function of backups. In addition, this wastes space with abandoned backup, and wastes resources making a new one without the old history. Re. topic title, it's supposed to fail without transferring the existing backup.

The database and destination must always stay in sync. I think there was one person who wanted an auto-destroy of database, should destination be found empty, or something like that which I didn't like. Duplicati is careful with your data, so sometimes a worrisome situation doesn't get a convenient-but-possibly-disastrous automatic fix, but wants you resolve it, possibly with help.

It is also dangerous to just go ahead with a new backup. When meaning to go to a mounted drive, people accidentally back up large amounts of data to the empty mount point instead, if the drive is unexpectedly not mounted. This can fill drive/kill system.

This issue needs tweaking somehow, maybe giving it a UI label, but for now I'll just see if there's even any further feedback on it. Posting this update may also get more developer opinions, but a better idea for usability might be a new issue written around it.
