### ISSUE TITLE
Hi. Is there a multi-thread OneDrive download?

### ISSUE THREAD

**Issue by 57382** [duplicati/duplicati#4559]
I am not a CPU multi-thread that compresses the module.
If you know the Internet Download Manager.
I want to use 32 threads to download and restore.
Thank you!

https://github.com/duplicati/duplicati/pull/3691 Implement Jottacloud multithreaded downloading support
Does OneDrive have something similar?

**Comment by warwickmm** [comment]
For OneDrive, different files are downloaded on different threads, but unlike Jottacloud a single file is not assigned to multiple threads.

**Comment by warwickmm** [comment]
Sorry, correction to the above comment. Downloads are not concurrent at the moment.  Download, hashing, and decryption occur on separate threads.
