### ISSUE TITLE
request: enhance method of limiting remote access

### ISSUE THREAD

**Issue by brainchild0** [duplicati/duplicati#4563]
Presently, the application is designed such that a fresh installation is accessible through a web interface from a browser operating locally, but not one connecting remotely.

This situation presents challenges for provisioning the application in embedded or otherwise headless environments. In such a case, an administrator will normally seek an allowed means to make an initial connection, in order to change settings for allowing remote access.

The present mechanism for distinguishing between local versus remote access appears to be based on reading the request header, rather than binding to a particular physical-layer interface. That is, it seems the application listens for connections on all interfaces, but responds to requests of non-local origination with the message "The host header sent by the client is not allowed".

This approach carries two essential limitations:

1. A request is treated as having non-local origination even if passed through a reverse proxy operating locally.
2. A request may be formed to mislead the application into inferring local origination for a processed request, when actual origination is non-local through a non-loopback interface.

Item (1) presents challenges for initial provisioning in a headless environment, while item (2) may present security liabilities.

**Comment by warwickmm** [comment]
> That is, it seems the application listens for connections on all interfaces, but responds to requests of non-local origination with the message "The host header sent by the client is not allowed".

Could you clarify?  I believe by default it listens to the loopback interface.

**Comment by brainchild0** [comment]
I think much of what I have inferred results from confusion over the Docker container being designed differently from the defaults in a generic  installation.
