### ISSUE TITLE
request: improve support in embedded environment for installation through Docker

### ISSUE THREAD

**Issue by brainchild0** [duplicati/duplicati#4564]
The application design currently imposes serious obstacles for provisioning the application through a Docker container operating in an embedded or otherwise headless environment. 

By default, the web interface is available only from browsers operating locally. For environments that preclude access through a local browser, and for which a remote web browser is the intended means of access, it would be necessary for an administrator to change the application settings to permit such access. Note that an application running in a Docker container, especially on an embedded platform, is unlikely to be operated regularly through command-line access.

A sensible installation procedure, for such an environment, might have the following steps:

1. Create a container in Docker.
2. Run a command that enables remote access through a browser.
3. Connect through a remote browser.

Presently, no solution appears to be available for step (2), and no other straightforward approach is apparent for reaching step (3).

Recommended is reviewing and correcting this limitation.

**Comment by warwickmm** [comment]
I'm not sure I understand.  Can you provide an example of a setup where publishing container port 8200 isn't enough?

/cc @drwtsn32x

**Comment by brainchild0** [comment]
>  Can you provide an example of a setup where publishing container port 8200 isn't enough?



In this case, the web browser shows the message "The host header sent by the client is not allowed".

**Comment by warwickmm** [comment]
Which Docker image are you using?

**Comment by brainchild0** [comment]
I am using the latest image from the official Docker repository.

**Comment by warwickmm** [comment]
Have you tried accessing via IP instead of hostname?  It could be related to this

https://forum.duplicati.com/t/error-message-in-browser-the-host-header-sent-by-the-client-is-not-allowed/5806

**Comment by drwtsn32x** [comment]
Yeah, the solution is to use the IP address, at least initially. You can then add the hostname to the main Settings page if you want to access it that way.

**Comment by warwickmm** [comment]
I think you can also try providing the `--webservice-allowed-hostnames` option when starting the server:

```
--webservice-allowed-hostnames: The hostnames that are accepted, separated with semicolons. If any of the hostnames are "*", all hostnames are allowed and the hostname checking is disabled.
```

**Comment by brainchild0** [comment]
> Have you tried accessing via IP instead of hostname? It could be related to this
> 
> https://forum.duplicati.com/t/error-message-in-browser-the-host-header-sent-by-the-client-is-not-allowed/5806

Following the suggestion, I tried access using the numeric address, with success. This result, however, is deeply confusing, because several sources, including the [manual](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/) and a variety of discussions, some   recent and in which I have been a participant (see #4547 and [forum post #1423](https://forum.duplicati.com/t/1423)), have indicated that remote access is not enabled by default.

**Comment by brainchild0** [comment]
> I think you can also try providing the `--webservice-allowed-hostnames` option when starting the server:

Starting the server is managed by the Docker container. This command-line option is useful in the context of a container only if  a practical means is given by which the administrator of the container may affect the startup command for the server.

**Comment by warwickmm** [comment]
> This result, however, is deeply confusing, because several sources, including the manual and a variety of discussions, some recent and in which I have been a participant (see #4547 and forum post #1423), have indicated that remote access is not enabled by default.

The Docker installation is "special" in that it specifies `--webservice-interface=any` when starting the server.  Otherwise, like you suspected, access would be difficult.  Our documentation is a bit behind (volunteers are needed and welcome), but the [forum](https://forum.duplicati.com/) is a good place to ask questions.

> Starting the server is managed by the Docker container. This command-line option is useful in the context of a container only if a practical means is given by which the administrator of the container may affect the startup command for the server.

Yes, you're correct.  Sorry, I only use the Docker container when testing/debugging so I build the image from the Dockerfile and the command-line options can be easily customized.  If you're interested, it looks like the LinuxServer.io Docker allows one to provide additional [command-line parameters](https://github.com/linuxserver/docker-duplicati#parameters), so you can see if that works for your situation.

**Comment by brainchild0** [comment]
Based on the above explanation, I suggest  the need for the following two actions:

1. Resolve the issue explained in [forum post #5806](https://forum.duplicati.com/t/5806), either by introducing a bug fix, or by documenting the behavior, as appropriate, as either a known limitation or a design feature.

2. Document the differences in the Docker container compared to a generic installation. (I suggest documenting these differences directly in the main user documentation, since relying on users to understand these differences based on a separate document for the container is likely to lead to confusion.)

**Comment by warwickmm** [comment]
Thanks @brainchild0.  I created issues https://github.com/kees-z/DuplicatiDocs/issues/80 and https://github.com/kees-z/DuplicatiDocs/issues/81 to better document some of this.  Although the remote access by IP is described in the user interface, we should mention this in the documentation as well

![image](https://user-images.githubusercontent.com/17345532/122788713-7a4afb00-d26b-11eb-8dfc-7f69e6391da3.png)

I also noticed the following on the [Docker main page](https://hub.docker.com/r/duplicati/duplicati):

**Specifying server arguments**

To launch the Duplicati server with additional arguments, run the duplicati-server command:
```
$ docker run duplicati/duplicati duplicati-server --log-level=debug
```
I think this would allow you to specify options when starting the server.

**Comment by brainchild0** [comment]
> To launch the Duplicati server with additional arguments, run the duplicati-server command:
> 
> ```
> $ docker run duplicati/duplicati duplicati-server --log-level=debug
> ```
> 
> I think this would allow you to specify options when starting the server

Normally, the container processes are managed by the *start* and *stop* actions on the container. For the current issue, a command would be required that has a persistent effect across invocations of these actions.

**Comment by warwickmm** [comment]
Have you tried it?  I did the following:

1. Create a container, and specify that the Duplicati server use port 8300, and map container port 8300 to host port 8200
  ```
  # docker run -d -p 8200:8300 duplicati/duplicati:canary duplicati-server --webservice-port=8300 --webservice-interface=any
  97515825261ffd4d9c05c60f055f35e5193fab04d938ce3a21ce676367c1c7f4
  ```
2. Verify by visiting host port 8200 that the Duplicati server is running with port 8300.
3. Stop the container.
  ```
  #  docker stop 97515825261ffd4d9c05c60f055f35e5193fab04d938ce3a21ce676367c1c7f4
  ```
4. Verify by visiting host port 8200 that the Duplicati server is not running.
5. Start the container.
  ```
  #  docker start 97515825261ffd4d9c05c60f055f35e5193fab04d938ce3a21ce676367c1c7f4
  ```
6. Verify by visiting host port 8200 that the Duplicati server is running with port 8300.
7. Inspect Docker run command for container to see that `--webservice-port=8300` is persisted:
  ```
  # docker ps --no-trunc
  97515825261ffd4d9c05c60f055f35e5193fab04d938ce3a21ce676367c1c7f4  duplicati/duplicati:canary   "/usr/sbin/tini -- duplicati-server --webservice-port=8300 --webservice-interface=any"   16 seconds ago   Up 15 seconds   8200/tcp, 0.0.0.0:8200->8300/tcp                 pensive_snyder
```

I'm not an expert with Docker, but it seems persistent to me.  Let me know if I'm doing something incorrectly.

Note that in the Dockerfile, we are using `CMD` instead of `ENTRYPOINT`:

https://github.com/duplicati/duplicati/blob/5af46b6eecc9fe04c140ec5304dabdd50bdaa3af/Installer/Docker/context/Dockerfile#L34

**Comment by warwickmm** [comment]
See the [docker run documentation](https://docs.docker.com/engine/reference/commandline/run/) for more details:

> A stopped container can be restarted with all its previous changes intact using docker start. 

Also, [Does restarting a Docker container “remember” initial run arguments?](https://stackoverflow.com/questions/32702992/does-restarting-a-docker-container-remember-initial-run-arguments/32703696)

**Comment by brainchild0** [comment]
Yes, fine, I understand now from the Docker documentation that the *run* command creates a new container, which is persistent, distinct from the *exec* command, which simply runs a command a single time as called. I think the usage you suggest. though, is not so convenient for those trying to create a basic configuration.
