### ISSUE TITLE
Triggering unwanted scripts during restore

### ISSUE THREAD

**Issue by riload35** [duplicati/duplicati#4575]
Hello everyone,

Sorry if my English is not correct.

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: linuxserver/duplicati (docker)
- **Backend**: Google Drive, Dropbox and external drive

## Description
On each of my backup jobs, I have defined two scripts, a "run-script-after" and a "script-before-required" which aim to stop containers before the backup job and then restart them after the backup. 
The problem I have is that when I trigger a restore on each of the jobs, the "run-script-after" and "script-before-required" scripts are triggered as if they were the backup. 
Is this normal? And if so, is there a way to only trigger scripts during backup?

## Steps to reproduce
1. Create a backup job with a "run-script-after" and a "script-before-required"
2. Start a backup
3. Start a restore

- **Actual result**:
Scripts executed during backup and restore
- **Expected result**:
I will want the scripts to run only when backing up

Thanks for your work :)

**Comment by warwickmm** [comment]
You can make your script check the `DUPLICATI__OPERATIONNAME` environment variable, which should tell you which operation is being run

https://github.com/duplicati/duplicati/blob/c0acaeee20609aa0762e2b39ae3f09d343582b1e/Duplicati/Library/Modules/Builtin/run-script-example.sh#L95-L98
