### ISSUE TITLE
Keep expanded path while changing "restore from" date

### ISSUE THREAD

**Issue by Germs2004** [duplicati/duplicati#4576]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.1_beta_2021-05-03
- **Operating system**: Windows Server 2019
- **Backend**: SMB share

## Description
When I am restoring files, I typically choose a date, expand the treeview folders below to the path I want to check, and see if the files I want are there.  If they aren't there, then I choose an earlier date, and then have to expand to the same path again to see if the files are available in that earlier backup.

I request a simple enhancement so that, when the user switches the "Restore from" dropdown date, the path they have already expanded to in the treeview below will REMAIN expanded, and its contents should simply refresh to show the files available in the newly selected date.  If that exact path doesn't exist in the earlier backup, then the expanded path should default to the deepest (nearest) path that does exist.

This will make the restore process much faster when we have to switch to several different dates and drill down 10 folders deep every time.  Especially because the drill-down process is kind of slow as it is.

## Steps to reproduce
1. Click Restore to go to the restore wizard
2. Select a "Restore from" date
3. Expand a bunch of folders down a path to see the files in that folder
4. Change the "Restore from" date to another value.

- **Actual result**:
The path below that you had previously expanded is now reset upon doing step 4, so you have to expand the whole path again.
- **Expected result**:
The path should be remembered and simply refresh its contents whenever you change the "Restore from" value.

**Comment by warwickmm** [comment]
I think the proposal in issue #72 is a better solution.

**Comment by warwickmm** [comment]
Closing this in favor of issue #72.
