### ISSUE TITLE
Can't exclude files and folders - "Failed to process path" although excluded

### ISSUE THREAD

**Issue by kankadev** [duplicati/duplicati#4582]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Win 10 64 bit Home
- **Backend**: external 3.5" HDD 5TB, connected to Laptop

## Description

I created a backup job in Duplicati. All backups ran with warnings "Failed to process path". But these warnings are about files and folders which I excluded in the config, so these warnings shouldn't exist anymore after excluding these files and folders.

Here are the filters:
![2021-07-23 17_43_04- Alltag  ASUS-LAPTOP - Duplicati](https://user-images.githubusercontent.com/84390410/126807851-bc928cdb-a018-4e1e-b368-eef963335c16.png)

But some of the excluded files or folders are present in the warnings:
![Firefox_Screenshot_2021-07-23T15-44-10 014Z](https://user-images.githubusercontent.com/84390410/126808000-0c5fa2be-f41e-449e-bb09-575a8a7caaa8.png)

Although I excluded the temp directory twice, it doesn't work. I tried to exclude `C:\Users\asus-laptop\AppData\Local\Temp` and `%APPDATA%\Local\Temp` which should be the same directory.

What's wrong?

Thanks.

PS: Is it because of the compression that Duplicati only finds and backs up 3 TB of data, even though the hard drive is 3.5 TB?

**Comment by warwickmm** [comment]
It looks like you are excluding `C:\Users\asus-laptop\AppData\Local\Temp`, but the warnings are for different folders (e.g., `C:\Users\asus-laptop\AppData\Local\Roaming`, `C:\Users\asus-laptop\AppData\Local\Stream`).

To exclude a file, you need to provide a specific path, or use wildcards:
```
C:\Users\asus-laptop\path\to\lockfile
C:\*\lockfile
```

> PS: Is it because of the compression that Duplicati only finds and backs up 3 TB of data, even though the hard drive is 3.5 TB?

The reported size is excluding filtered paths.

**Comment by kankadev** [comment]
> It looks like you are excluding `C:\Users\asus-laptop\AppData\Local\Temp`, but the warnings are for different folders (e.g., `C:\Users\asus-laptop\AppData\Local\Roaming`, `C:\Users\asus-laptop\AppData\Local\Stream`).

How can I exclude `C:\Users\asus-laptop\AppData\Local` and its subfolders?

> > PS: Is it because of the compression that Duplicati only finds and backs up 3 TB of data, even though the hard drive is 3.5 TB?
> 
> The reported size is excluding filtered paths.

That's the problem. It should backup 3.5 TB then, not 3 TB.

**Comment by warwickmm** [comment]
> How can I exclude C:\Users\asus-laptop\AppData\Local and its subfolders?

Exclude `C:\Users\asus-laptop\AppData\Local` instead of `C:\Users\asus-laptop\AppData\Local\Temp`.

> That's the problem. It should backup 3.5 TB then, not 3 TB.

I don't quite understand.  Why do you think it should be 3.5 TB?

**Comment by kankadev** [comment]
> 
> 
> > How can I exclude C:\Users\asus-laptop\AppData\Local and its subfolders?
> 
> Exclude `C:\Users\asus-laptop\AppData\Local` instead of `C:\Users\asus-laptop\AppData\Local\Temp`.

I want to backup `C:\Users\asus-laptop\AppData\Local` and its subfolders except the `Temp` folder inside.

> > That's the problem. It should backup 3.5 TB then, not 3 TB.
> 
> I don't quite understand. Why do you think it should be 3.5 TB?

I want to backup my data HDD called `D:`. It has 3.5 TB data. I excluded two folders inside this HDD which are only 24 GB big. So duplicati should find and backup still 3.5 TB data, not only ~ 3 TB.

**Comment by warwickmm** [comment]
> I want to backup C:\Users\asus-laptop\AppData\Local and its subfolders except the Temp folder inside.

Then just exclude `C:\Users\asus-laptop\AppData\Local\Temp` and make sure that Duplicati has read access to the other folders you want to back up.

> I want to backup my data HDD called D:. It has 3.5 TB data. I excluded two folders inside this HDD which are only 24 GB big. So duplicati should find and backup still 3.5 TB data, not only ~ 3 TB.

Make sure you're not confusing "size on disk" with the actual file sizes, and that you're not excluding more files than you think.  You can check the logs to see all the paths that are being excluded.  Based on the above screenshot, it looks like you are excluding at least 3 folders in D:.  Also, you should see if you have any of the "Exclude" boxes checked:

![image](https://user-images.githubusercontent.com/17345532/126835958-74f5198e-6882-42b6-9695-cb781487e664.png)

I recommend you create a post on the forums to get further support.  There are many more users there that may be able to help.

https://forum.duplicati.com/
