### ISSUE TITLE
MEGA.NZ: "Failed to connect: API response: ResourceNotExists"

### ISSUE THREAD

**Issue by G-i-o** [duplicati/duplicati#4583]
Hello. 

I've been trying to setup Duplicati with my Mega.nz account but I get an error as described below.

Have I made a mistake (maybe in the "Folder path" field)? Or is there something else wrong? 🙏🏽

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Linux (Kernel 5.12)
- **Backend**: Mega.nz

## Description
When testing the connection during setup, I get "Failed to connect: API response: ResourceNotExists "

## Steps to reproduce
1. Selected "Add New Backup" and "Mega.nz" for backup destination 
2. In folder path input: "mega://xx/xxxxxxxx" taken from the direct browser connection to "https://mega.nz/xx/xxxxxxxx" (where "x" is just a substitute for this report).
3. Filled the "Username" and "Password" fields (Those have been double checked).
4. Clicked on "Test connection"

**Comment by warwickmm** [comment]
The "folder path" should be the folder name in your "Cloud Drive", and not the URL.  For example, for the below account the folder path should be `duplicati_test`

![image](https://user-images.githubusercontent.com/17345532/127188053-8669d17f-f7b2-4aec-a82c-e3e964c3d721.png)

**Comment by G-i-o** [comment]
Thank You @warwickmm .

I'm sorry I didn't mention but I had tried that as well.....and just to make sure, I have tried all the following combinations:

• With the original folder I created "TEST MEGA"
- `mega://TEST MEGA`
- `mega://TEST MEGA/`
- `mega://TEST\ MEGA`
- `mega://"TEST MEGA" `
- //TEST MEGA
- /TEST MEGA
- TEST MEGA

• Then I changed folder name to TEST_MEGA and retried all the above combinations.
• Ultimately I changed the folder name to test_mega and retried the above combinations

All with the same result as described above.

Sorry if maybe I'm being idiotic but just don't get it if I'm still inputting the folder name incorrectly or if there's another fault.

**Comment by warwickmm** [comment]
Can you double-check your username and password?  Also, Duplicati doesn't support two-factor authentication with mega yet.  The changes have [been implemented](https://github.com/duplicati/duplicati/pull/4571), but they haven't been released yet.

**Comment by warwickmm** [comment]
In my testing, if I enter a folder path that doesn't exist, after clicking "Test connection" Duplicati asks if I want to create the folder:

![image](https://user-images.githubusercontent.com/17345532/127219489-18c09e5e-c406-4f2c-bd6a-111c14885dc1.png)

If I enter the wrong username or the wrong password, I get the ResourceNotExists error:

![image](https://user-images.githubusercontent.com/17345532/127219593-352e0863-2d7a-4581-b40f-2b381d1261cf.png)

**Comment by G-i-o** [comment]
Yes to both.

• Disabled 2FA.
• The username and pwd were inputted automatically but to make it 100% sure I did this:
- Logged out of Mega and obtain the login page again.
- Pasted the username into the relative field.
- Moved to Duplicati and pasted the same into the relative field.
- Back to Mega login page and this time pasted the pwd and it did login correctly.
- Back to duplicati and pasted the very same.

Yeah, I thought it should say if the folder does not exist. So, that is not the issue. Somehow then, it does not recognize the username or pwd. Could it be because the pwd is too long or something?

**Comment by warwickmm** [comment]
Not sure.  An older version of the MegaAPIClient had problems with [unicode characters](https://github.com/gpailler/MegaApiClient/issues/96) in the password, but the version we're using shouldn't have that problem.

According to the MegaApiClient author, the `ResourceNotExists` error is raised when the username/password [is incorrect](https://github.com/gpailler/MegaApiClient/issues/35#issuecomment-199253142).

Can you try simplifying your password for testing purposes?

**Comment by G-i-o** [comment]
Yup! That was the problem. It works now.

So, not sure whether is was the length or some of the characters used. I will test and give you some feedback on that.

For right now, thank You very much. :pray:

**Comment by warwickmm** [comment]
Great!  In my testing, a 32 character password works fine.

**Comment by G-i-o** [comment]
Yeah....it's not the length. Tried an over 140 char pwd and it worked.

It was one of the following chars which I've removed. ATM, I'm not going to test each of them as I fear to get locked out due to suspicious activity.

`*$%=-£`

**Comment by warwickmm** [comment]
Thanks @G-i-o.  My guess is that `£` is the problem.  If so, it's probably related to https://github.com/gpailler/MegaApiClient/issues/158.

**Comment by G-i-o** [comment]
I see. I'll leave a feedback there too, then. 🙏🏽
