### ISSUE TITLE
Localization: German: mixed pronominal form of address ("Du" and "Sie")

### ISSUE THREAD

**Issue by beppo-dd** [duplicati/duplicati#4605]
## Environment info
- **Duplicati version**: 2
- **Language**: German (DE)
- **Files**:
  - [duplicati/Localizations/duplicati/localization-de.po](https://github.com/duplicati/duplicati/blob/master/Localizations/duplicati/localization-de.po)
  - [duplicati/Localizations/webroot/localization_webroot-de.po](https://github.com/duplicati/duplicati/blob/master/Localizations/duplicati/localization-de.po)

## Description
The German localization mixes the [pronominal form of address](https://en.wikipedia.org/wiki/T%E2%80%93V_distinction) ([Pronominale Anredeform](https://de.wikipedia.org/wiki/Pronominale_Anredeform): "Du" and "Sie") in duplicati/Localizations/

  - [duplicati/localization-de.po](https://github.com/duplicati/duplicati/blob/master/Localizations/duplicati/localization-de.po): uses more "Sie"  (only 11 times "Du")
  - [webroot/localization_webroot-de.po](https://github.com/duplicati/duplicati/blob/master/Localizations/duplicati/localization-de.po): uses mostly "Du" (only two times "Sie"),

which is not consistent.

**Expected result**: A consistent pronominal form of address should be used. The corresponding choice should be documented as guideline for translation contributors.

## Proposal
Use "Sie" as pronominal form of address, …

- as this is the most common form of address to unfamiliar people in the German language, especially in the commercial sector, see [Anrede mit Sie](https://de.wikipedia.org/wiki/Pronominale_Anredeform#Anrede_mit_Sie). The domain [duplicati.com](https://duplicati.com) suggests a commercial sector. German companies and traditional international companies like [Microsoft](https://www.microsoft.com/de-de) use "Sie" (some international companies like [Apple](https://support.apple.com/de-de/HT201250) and [IKEA](https://www.ikea.de) want to appear personal and hip, and use "du").

- "Sie" is used in traditional software (documentation) as [Debian](https://www.debian.org/doc/index.de.html) or MATE Desktop. Also, [Duplicati 1.3](https://github.com/duplicati/duplicati/blob/1.3.x/Duplicati/Localization/report.de-DE.csv) uses "Sie" consistently. 

- In my opinion, backup software should look serious and rather traditional in order to exude reliability and trust. Therefore, as a user, I would prefer to be addressed with "Sie".

If this proposal will be accepted by @kenkendk and @agrajaghh, I can change the translation correspondingly in transifex.

**Comment by warwickmm** [comment]
Thank you @beppo-dd for the excellent description of the issue.

> In my opinion, backup software should look serious and rather traditional in order to exude reliability and trust. Therefore, as a user, I would prefer to be addressed with "Sie".

I agree with this.

**Comment by warwickmm** [comment]
@beppo-dd, if you're still willing to make these improvements, please go ahead.

**Comment by beppo-dd** [comment]
@warwickmm, thank you for your kind answer and your kind reminder. I'm still willing to make these improvement. I will do it as soon as my spare time allows it. I think, i can do it in the next two weeks.

**Comment by warwickmm** [comment]
There's no rush.  Thank you for volunteering.

**Comment by fe60** [comment]
@beppo-dd
To not mess something up (never heard of [transifex](https://www.transifex.com/duplicati/duplicati/dashboard/) before), I have created suggestions instead of saving changes.
Filter: `text:you user_suggestions:yes` 

I did not change anything else, to keep the focus on this issue. For potential improvements I have created issues in transifex.

I hope this helps. Otherwise it was a nice lesson on a new tool.

**Comment by beppo-dd** [comment]
@fe60, thank you for your work, and yes this helps a lot :-)

I'm also new in transifex, do you know, how to confirm your translations?

**Comment by fe60** [comment]
@beppo-dd 
1. Hover suggestion
2. Click on copy icon (tool tip: Use this)
=> Suggestion is copied into the editing area
3. Save changed translation

<image width="400" src="https://user-images.githubusercontent.com/31078918/142897322-998dfad9-a882-4d80-9aee-a4929a353729.png"/>

**Comment by beppo-dd** [comment]
@fe60 Thank you for your help :-). I hope I can use the free days at the end of the year the review your changes.

**Comment by beppo-dd** [comment]
@fe60 I reviewed all your suggestions. Thanks ones more for that!

**Comment by beppo-dd** [comment]
@fe60 I made proposals for all of your issues in transifex. Could check this this out? Thanks :-)

**Comment by beppo-dd** [comment]
@warwickmm We solved this issue in transifex (I reviewed and saved @fe60 's proposals and add some own). Do I have to do some thing else to get the changes in the sources?

**Comment by warwickmm** [comment]
If the changes are made in transifex, the translations will be updated when we create the next release.

Unless there's some more work to do, I'm going to go ahead and close this issue.  Thanks @beppo-dd and @fe60 for your hard work!
