### ISSUE TITLE
Excellent tools, but there is a problem with slowness.

### ISSUE THREAD

**Issue by alencarwell** [duplicati/duplicati#4616]
And I really am finding the tool fascinating.
You are to be congratulated.

However, I have two doubts.
I'm using it on an email server, from the company KERIO.
So I have a folder with all the company's emails, this folder is 900GB.

However, it has a Backup_ProcessingFiles step where this step alone takes more than 9 hours.

And I wanted to know if this slowness in this part is slow anyway.

Another doubt is that it should have a configuration of the place where it compresses this data, make it compress where the folder we want to backup is, makes the main drive full and crashes the server.

I have another HD and I wanted to configure the program to use it as a temporary and from this HD the program would send it to Google Drive.

Can you help me?

**Comment by warwickmm** [comment]
@alencarwell, please create a post in the forum.  There are more users there that can help you with this.

https://forum.duplicati.com/

**Comment by ts678** [comment]
[Backup_ProcessingFiles step where this step alone takes more than 9 hours](https://forum.duplicati.com/t/backup-processingfiles-step-where-this-step-alone-takes-more-than-9-hours/13153) looks like the post in the forum.
