### ISSUE TITLE
Website not working? Is this project live? 

### ISSUE THREAD

**Issue by yardstudio** [duplicati/duplicati#4620]
https://www.duplicati.com/
ERR_CONNECTION_REFUSED
![2021-10-06_17-13-52](https://user-images.githubusercontent.com/25852179/136242502-659a2c7f-2541-479e-96e6-620c42fd816e.png)

**Comment by ts678** [comment]
It looks like the webserver went down, although system responds to a ping.
If you need a download, go to http://github.com/duplicati/duplicati/releases

@kenkendk Please investigate.
