### ISSUE TITLE
Suppress PathProcessingFailed warning (notifications)

### ISSUE THREAD

**Issue by ElleshaHackett** [duplicati/duplicati#4623]
I often get PathProcessingFailed warnings when attempting to fully backup the `/etc` folder of the host machine that I mounted to duplicated read-only like `-v /etc:/source/etc:ro` when running duplicati from a Docker container.

Most Warnings are obvious like on `/etc/.pwd.lock` but is there an option to disable or supress such warnings or at least their notifications in the UI?

**Comment by warwickmm** [comment]
I don't think warnings can be disabled.  Ignoring warnings would not be recommended for something as critical as a backup program.  The best approach would be to fix the cause of the warnings.  Please create a post in the forum for help on this.

https://forum.duplicati.com/
