### ISSUE TITLE
Improve performance/efficiency by processing big files first?

### ISSUE THREAD

**Issue by GvY85** [duplicati/duplicati#4624]
First of all, thank you for your effort, been using Duplicaty for 5+ years so thank you.

I noticed that when I start a new backup Duplicati seems to randomly start compressing/encrypting files and uploading them. 
In practice that leads to the SSD that needs to be backed up clogging up on small files and thus limiting my upload to the backup storage.

I have a 3900X with a 980Pro SSD and a 1Gbit upload to a server with also an SSD but Duplicati is only uploading 30 to max 50% of the time as shown in the task manager.
Also the SSD is not busy 100% of the time and the CPU seems to have nothing to do?
To me it seems it could do the backup quite a bit faster utilizing more resources? What is the bottleneck here?

Perhaps Duplicati should process big/easy files first to create an upload cue and thus utilising the upload capabilities better?

I am using 500MB archive size.

![Untitled](https://user-images.githubusercontent.com/38404393/137492362-2e32f52c-0544-433e-ac72-7fc46a0edef9.png)
![Untitled2](https://user-images.githubusercontent.com/38404393/137492363-4f0f4248-9115-44bd-b59e-79157ce69d43.png)

**Comment by warwickmm** [comment]
I'm not sure I understand.  Duplicati processes the files a block at a time (by default 100 KB).  These blocks are then packaged into volumes, which are compressed, encrypted, and then uploaded.  The volumes may contain blocks from unrelated files, and there shouldn't be a huge difference between processing small or large files first.  

Sometimes, Duplicati performs additional verification or compacting operations that may make a backup appear to run slower than expected.

See the following for some more details:

https://www.duplicati.com/articles/Backup-Process/

**Comment by GvY85** [comment]
Think I solved it, the SSD had write cache disables leading to bad ssd performance
