### ISSUE TITLE
Microsoft OneDrive v2 receive Error when testing connection but is working

### ISSUE THREAD

**Issue by jeazyee** [duplicati/duplicati#4639]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.100_canary_2021-08-11
- **Operating system**: Debian 11
- **Backend**: N/A

## Description

When testing Microsoft OneDrive v2 connection settings, an error message shows up instead of success. The error message does not contain useful information. When ignoring the message from the connection test and finish the setup and test the config by creating a backup in OneDrive and restore it, everything works perfectly.

## Steps to reproduce

1. Configure New Backup
2. Backup Destination select "Microsoft OneDrive v2"
3. Enter Path "nicebackup/a1"
4. Click on AuthID, login to Microsoft and Duplicati receives the AuthID automatically
5. Press "Test connection"
6. Receive Error Message without any Error Information
7. Complete Setup ignoring the connection test then back up something and restore it from OneDrive -> works perfectly

- **Actual result**:
Error
Failed to connect:
- **Expected result**:
Success!

## Screenshots

The error message:
<img width="317" alt="Bildschirmfoto 2021-11-12 um 00 49 19" src="https://user-images.githubusercontent.com/16719990/141384984-a27c7b9a-6d12-4bdd-9a6c-6bd82a575e0d.png">
Backups getting created. Checked my OneDrive.
<img width="364" alt="Bildschirmfoto 2021-11-12 um 01 13 50" src="https://user-images.githubusercontent.com/16719990/141387159-28f019bf-b831-4368-9e4b-ee276b7658b8.png">

## Debug log

Does not contain something about this issue.

**Comment by warwickmm** [comment]
I am unable to reproduce this.  For me, if the destination folder exists I get "Connection worked!":

![image](https://user-images.githubusercontent.com/17345532/141696318-75cc04af-0e8c-4bc8-94be-41f05a79f274.png)

If the folder does not exist, it asks me if I want to create the folder:

![image](https://user-images.githubusercontent.com/17345532/141696312-9ddf4e62-674e-4f4f-9a4c-75625a19d7a7.png)

What browser are you using?  Can you try clearing the cache, disabling extensions, etc. and see if it still happens?  If so, is there anything interesting in the browser console logs?
