### ISSUE TITLE
Backup Retention Not Applied During Compress

### ISSUE THREAD

**Issue by Ryonez** [duplicati/duplicati#4642]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: unRaid
- **Backend**: unrelated
## Description

Compress does not apply `Backup retention` correctly, or outright ignores it

## Steps to reproduce

1. Create a backup
2. Have one that exists for a long time and has multiple versions backed up.
3. Change the Backup retention to a time less than the further backup available.

- **Actual result**:
Compress doesn't remove versions extending past the Backup retention time
- **Expected result**:
Compress to remove backup that don't match the Backup retention policy.

## Screenshots

![image](https://user-images.githubusercontent.com/16157130/143084810-1b3168ce-259f-4bb5-bb9a-4442d42a26a7.png)
![image](https://user-images.githubusercontent.com/16157130/143084924-1247bb56-e9e3-4ecf-9d35-4f44ab90addb.png)
![image](https://user-images.githubusercontent.com/16157130/143085002-e0fa25c1-d1fc-4f68-bea6-640a44504666.png)
![image](https://user-images.githubusercontent.com/16157130/143085086-b282cefb-0b52-4287-948c-f5ea4f6b7229.png)

## Debug log

None made sorry, logs seem to be off by default.

**Comment by drwtsn32x** [comment]
Pretty sure pruning of versions doesn't happen until after the next backup operation.  Compact by itself won't do the pruning operation.

**Comment by Ryonez** [comment]
That is...
I'm just going to try that. Will update once it's done.

**Comment by drwtsn32x** [comment]
By the way, compact may run automatically at the end of the next backup job unless you are using --no-auto-compact.

**Comment by Ryonez** [comment]
Alright, that did the trick. Somewhat confusing, I would've though compress would have looked at the backup retention, with version being something that can take up a huge amount of space. Thank you for pointing me the right way.
