### ISSUE TITLE
Change .NET 5 Migration to .NET 6

### ISSUE THREAD

**Issue by frelis** [duplicati/duplicati#4647]
I think the .NET 5 Migration project should target .NET 6 has several advantages:
- The .NET 6  is LTS release https://dotnet.microsoft.com/platform/support/policy then end of support of .NET 5 is in May 2022
- Supports more architectures
- Has a more stable(ish) library making more easy to update
- Was made several speed optimizations
- Has a better trimming support decreasing the package size
- C# 10 has several advantages.

**Comment by warwickmm** [comment]
Thanks @frelis.  At our current pace, targeting .NET 6 does seem to be a natural thing to do.  Feel free to add to [this conversation](https://github.com/duplicati/duplicati/pull/3124) if you want to discuss further.
