### ISSUE TITLE
Where's the stable version?

### ISSUE THREAD

**Issue by Lomacar** [duplicati/duplicati#4653]
Why is everything "beta", "canary" or "experimental"? Is this software reliable or not?

**Comment by warwickmm** [comment]
"Stable" means different things to different people.  I think many people have been using the beta release without problems, while there are others that encounter issues that are difficult to diagnose.  I recommend that you create a post in the [forum](https://forum.duplicati.com/) describing your anticipated configuration (total size of files, storage destination, etc.) to see if others can provide you with some guidance on whether Duplicati is a suitable solution for you.

**Comment by ts678** [comment]
The current way which you can see in action on the [Releases](https://github.com/duplicati/duplicati/releases) page is that Canary is bleeding-edge first-exposure. After enough of those plus some run time, a Canary is promoted to Experimental which is sort of Beta release candidate. It helps test less frequent upgrades like Beta users do. Assuming it works, Experimental becomes a Beta which works well, but not so well it's called "Stable".

**Comment by jonozw** [comment]
thank you:)
