### ISSUE TITLE
API to determine last successful backup timestamp

### ISSUE THREAD

**Issue by matthew-larner** [duplicati/duplicati#4654]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

Duplicati version: 2.0.6.3_beta_2021-06-17
Operating system: Linux

## Description
Due to a recent bug (https://github.com/duplicati/duplicati/issues/4650), my backups stopped working. I'd like a way to be alerted of this. A possible option would be to provide an API that can be called which lists all of the backup jobs and the last successful backup timestamp.

**Comment by warwickmm** [comment]
I think the following options could provide what you want:

* [email notifications](https://duplicati.readthedocs.io/en/latest/04-using-duplicati-from-the-command-line/#the-send-mail-command)
* [run-script-after](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#run-script-after)
* [duplicati client](https://github.com/Pectojin/duplicati-client)
