### ISSUE TITLE
Failed backups make next schedules fail

### ISSUE THREAD

**Issue by JPaulMora** [duplicati/duplicati#4655]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3-1
- **Operating system**: Ubuntu 20.04.2 LTS
- **Backend**: Backblaze B2

## Description

Duplicati suddenly stops backing up, seems to be crashing. found `"dumping_error" : "Exceeded the maximum number of frames",` in `mono-crash.json` but I can't find similar problems or errors with the same message.

## Steps to reproduce

1. Setup hourly backup to Backblaze B2
2. Backup 25GB worth of wordpress websites plus a 50GB mailcow backup (https://mailcow.email)
3. That's it.

- **Actual result**:
Some backups fail or crash, complains about missing files in local environment, after this no new backups are attempted.
- **Expected result**:
If crash, recover from it and continue with backup schedule. Probably would like a setting to "force" backups at different states, websites are very dynamic so files can always get crated/deleted by clients.

## Screenshots

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/8335656/147820224-b8b77f14-b373-448e-8ace-aa33616d1cc1.png"> (Last backup over a month ago, next one should be right now.. but didn't happen)

<img width="614" alt="image" src="https://user-images.githubusercontent.com/8335656/147820269-5fd7722c-3315-4b73-8a58-a8b972126e6c.png">

**Comment by warwickmm** [comment]
Scheduled backups should continue to run, and continue to fail if the reason for the error persists.  If mono is really crashing, that could prevent the scheduled backups from running.  However, it looks like you have some other errors that need to be resolved as well.

I'd recommend creating a post in the [forum](https://forum.duplicati.com/) for help with this.  There are more users over there that can help with this.

**Comment by JPaulMora** [comment]
Hi, thanks for your input. It's always the same error: missing files in remote storage, however repair does nothing. If i run a new backup the error goes away for a few runs but comes back some days later.

**Comment by warwickmm** [comment]
Is the problem that scheduled backups are not even attempted, or that they start but eventually fail?  

I'd recommend creating a post in the [forum](https://forum.duplicati.com/) for help with diagnosing what's causing the missing files.

**Comment by ts678** [comment]
This was marked as not reproducible two years ago, with two suggestions to post on the forum.
Upgrading mono from [mono-project.com](https://www.mono-project.com/download/stable/#download-lin) might help avoid the mono crash. Is this still an issue?
