### ISSUE TITLE
Suggestion: Additional compression exclusion extensions for windows imaging software

### ISSUE THREAD

**Issue by arberg** [duplicati/duplicati#4657]
Suggested addition to: [default_compressed_extensions.txt](https://github.com/duplicati/duplicati/blob/7b4f475762928ae72575cb96279364f0784de4e4/Duplicati/Library/Main/default_compressed_extensions.txt)
```
.tib #Acronis True Image windows backup image software
.tibx #Acronis True Image windows backup image software
.mrimg #Macrium Reflect windows backup image software
```

I've used both imaging softwares, though its long since I've change to Macrium. But it looks like the .tib is still correct, though have also added `.tibx` since i found that here:

See https://www.file-extensions.org/acronis-true-image-file-extensions
and 
https://www.file-extensions.org/mrimg-file-extension

By default all of these image types are compressed. It is possible to turn of compression in Macrium Reflect, but I doubt that is a common usage. Just like zip-files not necessarily are compressed, so it makes sense to add these extensions..

**Comment by Luxtech** [comment]
Another suggestion for a file extension to be added to: default_compressed_extensions.txt

`.rvz #Dolphin compression  storage format for Nintendo Gamecube and Wii games`

See post: "5.0-12188 - Support for RVZ and WIA disc formats": https://dolphin-emu.org/blog/2020/07/05/dolphin-progress-report-may-and-june-2020/?nocr=true
