### ISSUE TITLE
duplicati.com download broken

### ISSUE THREAD

**Issue by vancouverbluesea** [duplicati/duplicati#4679]
- [ ] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Operating system**: PopOS 20.04

## Description

Trying to download .deb from https://www.duplicati.com/download 
It is failing with complain from NGIX

## Steps to reproduce

1. Go to https://www.duplicati.com/download
2. Try to download the Ubuntu / Debian
3. This is consistent on Firefox, Vivaldi, wget

- **Actual result**:
Fails
- **Expected result**:
Should work.

**Comment by sconnary32** [comment]
Is duplicati even maintained any longer?  Forums are gone.  Seems a bit unnerving to use this software if EOL.

**Comment by warwickmm** [comment]
Which forums?  Looks like it's pretty active to me.

https://forum.duplicati.com/

**Comment by vancouverbluesea** [comment]
Hi,
Yes - it was resolved yesterday. I was able to download it.

**Comment by vancouverbluesea** [comment]
Thank you!
working now.
