### ISSUE TITLE
Duplicati reports lack of disk space, though there is more than enough left

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#468]
_From [stuart.r...@gmail.com](https://code.google.com/u/106293461981912245334/) on August 30, 2011 15:27:56_

What steps will reproduce the problem? 1.Backing up a 99GB directory structure with 30,817 files and 3797 folders
2. Everytime it now tries to run the incremental it stops immediately with the same error 3. What is the expected output? What do you see instead? Backup should complete, but stops after 53GB saying there is no more disk space, though there is 1.04TB available. What version of the product are you using? On what operating system? 1.2.1 What backend (destination) are you using? Linux NTFS 1.5TB disk Please provide any additional information below.

**Attachment:** [log.txt](http://code.google.com/p/duplicati/issues/detail?id=468)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=468_

**Comment by Hafid75012** [comment]
HI Everyone,
I have an issue trying to backup 5 TO :
the backup is still running and backup 240 GO. The agent is installed in the distination server . My issue is that the OS drive of the source ( file server ) is filled up . where Duplicati sotres file in the OS drive of the source machine? can we delete it ?*
the OS drive of the source ( file server) is diffrent of the Data drive that I am backup 
please help me

**Comment by drwtsn32x** [comment]
@Hafid75012 can you post to the Forum instead? It's preferred for general troubleshooting. Thanks!
