### ISSUE TITLE
Unable to copy open files with snapshot set to auto

### ISSUE THREAD

**Issue by elnath78** [duplicati/duplicati#4688]
Here is the test I did: first the logged in user is admin, then I ran Duplicati as admin specifically in boot settings. Looking on the webI found in some blog to run an utility to test the VSS and it failed:

I'm actually having this warning while trying to backup open Outlook .pst file. Outlook is always open so I need to resolve this, cannot remember to close the program to finish the backup. I'm running the latest version of Duplicati, the backup is to external drive, and VSS is enabled on the drive.

```
C:\Program Files\Duplicati 2>Duplicati.Library.Snapshots.exe
Creating file C:\Program Files\Duplicati 2\testfile.bin
The snapshot tester failed: System.UnauthorizedAccessException: Access to path 'C:\Program Files\Duplicati 2\testfile.bin' denied.
in [System.IO](https://system.io/).__Error.WinIOError(Int32 errorCode, String maybeFullPath)
in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
in Duplicati.Library.Snapshots.Program.Main(String[] _args)
* Test failed
```

**Comment by elnath78** [comment]
Had to install C++ libraries, resolved:

https://docs.microsoft.com/it-it/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by elnath78** [comment]
Again same problem, it seemed to have resolved but that's not the case.

**Comment by ts678** [comment]
> the logged in user is admin

> System.UnauthorizedAccessException: Access to path 'C:\Program Files\Duplicati 2\testfile.bin' denied.

suggests account is an `Administrator` but has not yet used a [User Account Control](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works) prompt to actually get admin privileges.
Lack of privilege will cause access issues and cause a snapshot to fail if you choose `required`. Does yours fail on that setting?

> admin specifically in boot settings

What specifically does that mean? If this is in Task Scheduler, the following shows how to get the equivalent of the UAC effect:

[Using Task Scheduler to Run Processes Later](https://www.howtogeek.com/school/using-windows-admin-tools-like-a-pro/lesson2/)

> Run with highest privileges – this option essentially gives the task administrator privileges the same way the User Account Control (UAC) prompt would do it.

Another option if you want Duplicati up at boot with plenty of privilege is to run it as SYSTEM under a Windows service install.

**Comment by elnath78** [comment]
@ts678 @warwickmm 

I'm not sure what you are asking I have Duplicati installed and I'm logged in as admin, we resolved by closing Outlook before running Duplicati, for the moment we don't see another solution.

**Comment by ts678** [comment]
> I'm logged in as admin

That doesn't give you administrator privileges unless you also used "Run as Administrator" or went through a UAC prompt.
[How User Account Control works](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/user-account-control/how-it-works). You can also run `whoami /groups` to see if you're actually using administrator privileges.
Task Manager's Details tab also has an `Elevated` column you can turn on, but you'd have to find the process in the listing.
Admin doesn't get full admin powers until they've elevated. It's for security, and you can read the Microsoft page I've cited.

> for the moment we don't see another solution.

Several were given to you in the earlier post. I am asking you to pick on. You can also explain how you like to start Duplicati.
Perhaps that will help select the appropriate one, as some of them are a little complicated or inconvenient to set up and run.

**Comment by ts678** [comment]
If you want to run as a service, [Duplicati Tutorial 02 Install Duplicati as a Service](https://www.youtube.com/watch?v=fZ_ukxbEyG0) gives the idea, though specifics vary by need.
Don't set up remote access unless you want it and trust the network and its occupants. Although it's more work, you can see

[Migrating from User to Service install on Windows](https://forum.duplicati.com/t/migrating-from-user-to-service-install-on-windows/660/46). That links to v3, which is the most thorough procedure and beats original.
If you want to run at login or as a specific user, it may be possible, but some combinations are difficult to get Windows to run.

**Comment by elnath78** [comment]
@ts678 
> You can also run `whoami /groups` to see if you're actually using administrator privileges.
> Task Manager's Details tab also has an `Elevated` column you can turn on

It result as `BUILTIN\Administrators` I added the 'elevated' column in task manager, but could not change it, would this resolve the issue in case that I find a way to change the process status?

Duplicati was installed, I don't think it is as a service, we can see the tray icon.
