### ISSUE TITLE
memory leak when using with rclone mounted drive

### ISSUE THREAD

**Issue by lilarcor** [duplicati/duplicati#4695]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: Duplicati - 2.0.6.3_beta_2021-06-17
- **Operating system**: unraid system
- **Backend**: a mapped local drive --->rclone--->Microsoft Onedrive for business

## Description

I have around over 500,000 files to be backed up. Ideally, I'd like to backup those file to onedrive with rclone mounted.

## Steps to reproduce

1. 'rclone config' , then use rclone mount to map the drive to local system
2. use docker , set source and dest vol 
3. create backup job 

- **Actual result**:
After a while, you will see the container starts to eat memory, and you cannot even stop or kill it. And memory will be exhausted finally. 
- **Expected result**:
Hope to fix it. And I didn't find issue if I create a job and set the target to OneDrive with API

**Comment by ts678** [comment]
> Backend: a mapped local drive --->rclone--->Microsoft Onedrive for business

> I didn't find issue if I create a job and set the target to OneDrive with API

Is the difference between those two that the growing one has rclone in the middle? Could memory be from rclone?
How are you measuring container memory? Have you been able to isolate memory growth to any specific process?

Is issue still of interest? Is it still happening?
