### ISSUE TITLE
Duplicati is taking up C Drive storage

### ISSUE THREAD

**Issue by chiragnahata** [duplicati/duplicati#4708]
I installed Duplicati on my laptop and after the first backup to Onedrive business I got to see that my C Drive was nearly full. Why is it taking up C Drive storage ? Please help as soon as possible.

**Comment by drwtsn32x** [comment]
Click on your backup job to expand options, then click the blue "Database" link.  Type a new path to where you want the database located and then click "move existing database."

In general  you will get faster and better support by posting to the Duplicati forum.  Please post there if you continue to have issues.  Thanks!
