### ISSUE TITLE
Add IDrive E2 backend

### ISSUE THREAD

**Issue by zuhairmushtaq** [duplicati/duplicati#4725]
Seems like IDrive e2 is the cheapest cloud storage in the market with no fees for egress and it's faster than other cloud storage provide too. It deserves a place in this amazing tool.

**Comment by ts678** [comment]
[https://www.idrive.com/e2/duplicati](https://www.idrive.com/e2/duplicati) seems to be their directions for Duplicati and may also explain why the pull request for this is so big (so may go through slowly or not at all). Typically a new S3 service just needs its URL [added](https://github.com/duplicati/duplicati/blob/93a4e2cb6e60c85357cfad9f1288c9833919a054/Duplicati/Library/Backend/S3/S3Backend.cs#L45-L59), but this has  has no fixed URLs.

**Comment by ts678** [comment]
[2.0.6.104_canary_2022-06-15](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.104-2.0.6.104_canary_2022-06-15)

> Added IDrivee2 backend, thanks @MuhammadAbrar1984

so in Beta channel, this should be in [2.0.7.1_beta_2023-05-25](https://github.com/duplicati/duplicati/releases/tag/v2.0.7.1-2.0.7.1_beta_2023-05-25)

[Backblaze B2 vs IDrive E2](https://forum.duplicati.com/t/backblaze-b2-vs-idrive-e2/17289) in forum might like your feedback.
