### ISSUE TITLE
Can duplicati load in explorer and compare the folder differences

### ISSUE THREAD

**Issue by xh542428798** [duplicati/duplicati#4732]
I often compare folders using beyond compare, Iwonder can duplicati load in explorer and compare the folder differences ？

**Comment by fe60** [comment]
I did not get the point. I which scenario do you expect Duplicati to do what exactly?

**Comment by ts678** [comment]
Duplicati is a backup program that is described at:

[https://www.duplicati.com/](https://www.duplicati.com/) Web site.
[https://duplicati.readthedocs.io/en/latest/](https://duplicati.readthedocs.io/en/latest/) Manual.
[https://github.com/duplicati/duplicati](https://github.com/duplicati/duplicati) GitHub

Please clarify if you have a question about backup.
