### ISSUE TITLE
One or more errors occurred while uplaoding backup

### ISSUE THREAD

**Issue by azukaar** [duplicati/duplicati#4735]
- **Duplicati version**:  2.0.6.102_canary_2022-04-06
- **Operating system**: Ubuntu
- **Backend**: Dropbox

## Description

I have beeen trying to backup a large folder for a while, but since the new dropbox change, my connection seems to drop every other day, making it impossible to backup a folder large enough to take more than a couple of days.

I get this in the UI : 

![image](https://user-images.githubusercontent.com/7872597/172021928-26cd99a2-8157-479f-bd84-6301aefe1aac.png)

Files succesfully started uploading:

![image](https://user-images.githubusercontent.com/7872597/172021940-62f8f862-4600-41f3-9926-b8829919ee42.png)

And this is the only error I can see in the console: 

![image](https://user-images.githubusercontent.com/7872597/172021951-e364d169-f22f-454f-8377-58eceaeb2208.png)

Thanks let me know if any additional data is required

**Comment by azukaar** [comment]
![image](https://user-images.githubusercontent.com/7872597/174448517-710c2c81-7e65-473a-9f22-060134a91cba.png)

for some reason this time I got more details-ish

**Comment by Xavron** [comment]
`"looks like the backup stops after a number of 500 errors, and never resume ?"`

That should be the Dropbox returning "error 500" basically. Not 500 errors :-)

eg https://www.dropboxforum.com/t5/Dropbox-files-folders/Internal-Server-Error-status-code-500/td-p/595305

Your one image shows invalid port specified for UriFormatException so it should be some new Duplicati bugs if they did indeed rework the Dropbox or related code.

**Comment by azukaar** [comment]
> That should be the whatever returning "error 500" basically. Not 500 errors :-)

Lol I can see how the phrasing could be confusing but no I didnt mean there were 500 individuals errors but yes, seems Dropbox is returning 500 status code responses and after a certain number of them, Duplicati interrupt the process. This is what I meant!

**Comment by azukaar** [comment]
> > Dropbox is returning 500 status code responses
> 
> [Error Handling Guide](https://developers.dropbox.com/error-handling-guide) from Dropbox talks about these. They should be brief. If you want to fine-tune retries, try [retry-delay](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#retry-delay) or
> 
> ```
>   --retry-with-exponential-backoff (Boolean): Whether to enable exponential
>     backoff.
>     After a failed transmission, Duplicati will wait a short period before
>     attempting again. This period is controlled by the retry-delay option.
>     When this option is enabled, that period is doubled after each
>     consecutive failure.
>     * default value: false
> ```
> 
> Even better, whatever was causing these isn't now. Any news? If not, a live log or [log-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file) at retry level may provide some info.

I stopped using Duplicati since it was impossible for me to do a single uninterrupted upload of backups, so I wouldn't be able to try or tell you if it works, sorry
