### ISSUE TITLE
Facebook link is dead

### ISSUE THREAD

**Issue by AldeRoberge** [duplicati/duplicati#4738]
- [ x] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: Latest

## Description

Facebook link is dead https://www.facebook.com/pages/Duplicati/105118456272281

## Steps to reproduce

1. Open the first page

- **Expected result**:
Couldn't find the official Facebook page

**Comment by kenkendk** [comment]
The Facebook page was fairly inactive and is now no longer working.
Do we have a link somewhere that points to the defunct page?

**Comment by serversage** [comment]
> The Facebook page was fairly inactive and is now no longer working. Do we have a link somewhere that points to the defunct page?

Yup, [Duplicati home page](https://www.duplicati.com/) on the bottom right, "Visit us on".
