### ISSUE TITLE
Missing zip release and inconsistency assets release

### ISSUE THREAD

**Issue by martadinata666** [duplicati/duplicati#4741]
- [x] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Description
On the latest release `v2.0.6.103-2.0.6.103_canary_2022-06-12` Missing zipped duplicati release. And checked another version release the assets seems missing bits

## Screenshots
![2022-06-13-094919_954x465_scrot](https://user-images.githubusercontent.com/2433562/173271065-4562f200-8663-43e1-a70b-3106ca15008f.png)
![2022-06-13-094932_951x503_scrot](https://user-images.githubusercontent.com/2433562/173271051-65b2ca54-28a8-4e6b-b13f-8c1ebd39731b.png)
![2022-06-13-094952_970x306_scrot](https://user-images.githubusercontent.com/2433562/173271035-f11027ec-dc99-44f5-b70a-b4027b2ba08e.png)
![2022-06-13-095007_950x499_scrot](https://user-images.githubusercontent.com/2433562/173271028-6507f7fc-53ed-4125-a956-a272a2f843b5.png)

## Steps to reproduce
1. Check release
2. Download zip, or other type of packaging
3. Missing zip

- **Actual result**:
Consistent release assets.
- **Expected result**:
The assets release work correctly.

**Comment by aptalca** [comment]
I'm with [linuxserver.io](https://linuxserver.io) and we publish a docker image for duplicati (both beta and canary releases). Because the zip artifact is missing in the latest canary release, our hourly ci builds keep triggering but failing :-)
We'd appreciate it if the zip could be added

Thanks

**Comment by kenkendk** [comment]
@martadinata666 & @aptalca I did not get any errors during the automated asset uploads, so not sure where the problem is.
I have added the zip file to the release now.

**Comment by aptalca** [comment]
Thanks so much. The build succeeded
https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-duplicati/detail/development/429/pipeline

**Comment by martadinata666** [comment]
> @martadinata666 & @aptalca I did not get any errors during the automated asset uploads, so not sure where the problem is. I have added the zip file to the release now.

I see, maybe some github quirks not really sure. Thanks.
