### ISSUE TITLE
Debian release of v2.0.6.103 canary will not install

### ISSUE THREAD

**Issue by Taomyn** [duplicati/duplicati#4742]
- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.103_canary
- **Operating system**: Raspberry OS (Buster)
- **Backend**: n/a

## Description
Latest canary release will not install, get "Reading package lists... Error!"

## Steps to reproduce
1. Download release
2. Execute "sudo apt install ./duplicati_2.0.6.103-1_all.deb"

- **Actual result**:
```
Reading package lists... Error!
E: Sub-process Popen returned an error code (2)
E: Encountered a section with no Package: header
E: Problem with MergeList /home/pi/duplicati_2.0.6.103-1_all.deb
E: The package lists or status file could not be parsed or opened.
```

- **Expected result**:
Successful installation, v2.0.6.102_canary was fine to install when it was released

**Comment by mathewparet** [comment]
I have the same issue but a different error message:

```
mathew@plug:~ $ sudo dpkg -i duplicati_2.0.6.103-1_all.deb 
dpkg-deb: error: archive 'duplicati_2.0.6.103-1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive duplicati_2.0.6.103-1_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 duplicati_2.0.6.103-1_all.deb
mathew@plug:~ $ 
```

**Comment by FredericMa** [comment]
@mathewparet I'm getting the same error message but I guess it is something else then the initial issue. I'll create a new issue.

**Comment by Pro-Idler** [comment]
I don't have a device with Raspberry OS to test on, but it's possible it's due to the fact that v2.0.6.103 uses Zstandard compression which is not supported by dpkg in mainline Debian. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664
v2.0.6.102 was compressed with LZMA2 which is fully supported by dpkg.

From what I've read it seems Ubuntu implements Zstandard support in dpkg, but for anyone using Debian this will pose a problem.
It's been a while since the previous release so I guess something changed in the build process in the meantime? Would be great if we could get a new package with LZMA2 that works on Debian.

**Comment by mathewparet** [comment]
I am not sure why that would be a problem since I already have `zstd` installed (`sudo apt install zstd`)

**Comment by martadinata666** [comment]
It not about is zstd existed in our system or not, it about the apt/dpkg compression method support, on debian still use lzma, when ubuntu already use zstd by default

**Comment by drwtsn32x** [comment]
I was able to install after repackaging the deb file:

https://forum.duplicati.com/t/unable-to-install-duplicati-2-0-6-103-1-all-deb-on-raspberry-pi-running-on-buster/14567/4?u=drwtsn32

**Comment by Taomyn** [comment]
Had to do the same for .104 but it worked fine.

**Comment by ts678** [comment]
[2.0.6.105_canary_2023-04-09](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.105-2.0.6.105_canary_2023-04-09) (or in Beta terms, 2.0.7.1_beta_2023-05-25) likely fixed this, although xz might also have worked.

> Build Debs with gzip compression for old debian releases, thanks @gpatel-fr

Anyone still on an older Debian (probably before 12) care to test a new `.deb`?

**Comment by Taomyn** [comment]
I updated to 2.0.7.2_canary_2023-05-25 on a Raspberry Pi still on Bullseye without needing to do anything special, if that counts - everything else I have that's Debian-based is now on Bookworm.

**Comment by ts678** [comment]
> if that counts

Original issue was Debian Buster (10). You tested the new `.deb` (not autoupdate which doesn't count) on Bullseye (11), and Bookworm (12) is thought to accept the format that Duplicati used to use before it moved to a really old one for old Debian.

Assuming the above is correct, it looks like this is indeed fixed. Thanks for testing it.
