### ISSUE TITLE
"Invalid signature." error when backing up to SMB share

### ISSUE THREAD

**Issue by HunterAhlquist** [duplicati/duplicati#4752]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3
- **Operating system**: Windows 11 21H2
- **Backend**: Local (SMB, direct IP/not a mapped drive)

## Description

Backing up to an SMB share (hosted by a Mac Mini) causes a generic "Invalid Signature." error after files have backed up. No other error information was found.

## Steps to reproduce

1. Create a new backup pointing to a MacOS hosted SMB share (via the "File Sharing" feature in system preferences)
2. Run the backup, all files should copy successfully
3. Wait to get to the validation procedure

- **Actual result**:
Unsuccessful backup with an "Invalid signature." error
- **Expected result**:
Backup successful.

## Screenshots

![image](https://user-images.githubusercontent.com/36090375/174463950-01537551-b0d2-4055-bce8-f36300a94a3c.png)

![image](https://user-images.githubusercontent.com/36090375/174463939-0d28f9d8-e5a6-4cb0-b5ba-66123638c602.png)

## Debug log

sqlite log: https://1drv.ms/u/s!Asm7qfyxvd1Lgp0cmuxr5qjSbLIcZQ?e=z4gOGC
system info:
[system-info.txt](https://github.com/duplicati/duplicati/files/8936319/system-info.txt)

**Comment by drwtsn32x** [comment]
The destination path is handled by the operating system, not Duplicati.  As such, UNC paths for a destination only work on the Windows platform. Linux (and presumably MacOS?) don't handle UNC paths directly.  You can either mount the SMB path to the local filesystem or use an alternate protocol.

**Comment by HunterAhlquist** [comment]
So I did a test, I did a backup of one folder to an external drive, and then I did one backup to my smb share. Both were successful... Could I have been backing up a corrupted file, or could validation fail if data has changed while backing up?

**Comment by HunterAhlquist** [comment]
Getting the "Invalid signature." error again, I updated the main post with what I think is my logs.

**Comment by HunterAhlquist** [comment]
While SSH is far slower than SMB, at least I can backup my files now. 
Better than wrestling with MacOS' insanely locked down settings.
