### ISSUE TITLE
long time running duplicati stopped working

### ISSUE THREAD

**Issue by teodias** [duplicati/duplicati#4781]
- [ ] I have searched open and closed issues for duplicates.   
Couldn't find good keywords for a useful search
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.  
not yet

----------------------------------------

## Environment info

- **Duplicati version**: Aktuell wird Duplicati - 2.0.6.104_canary_2022-06-15 verwendet
- **Operating system**: Microsoft Windows [Version 10.0.19044.1706]
- **Backend**: local ()

## Description

Duplicati worked for a longer period without any isseu 2-3 days ago it stopped with a very unspecific error.
I have no idea what it want's to tell me.
![image](https://user-images.githubusercontent.com/51795821/175821270-d9b150c5-1c55-4e8d-87b2-1544da905a7d.png)
I tried to create a bug report, thus took a very long time. Then there were a 'Right click and save me' message but it didn't work and did not save any file anywhere.
I also tried check files, repair database, compress backups.

What can I do?

## Steps to reproduce

How can I send my config?

- **Actual result**:
Stopping backups with the message above

- **Expected result**:
Running backups w/o error messages

## Screenshots

see above

## Debug log

even I tried to create a bug report, it didn't finish successfully

**Comment by ts678** [comment]
> it stopped with a very unspecific error

which is not a Duplicati error, but .NET Framework might have put one beneath it that you can go looking for in two places.

About --> Show log --> Stored and go by time of failure

About --> Show log --> Live --> Error and run a backup

**Comment by ts678** [comment]
No response. More detail? Any interest? Working now?

I agree about "very unspecific error". The translation is "At least one error occurred", and that's not enough to do anything with.

**Comment by zaonpt** [comment]
26 de Mar de 2024 13:58: The operation ListRemote has failed with error: Método não encontrado: 'System.Collections.Generic.IEnumerable`1<Duplicati.Library.Interface.IFileEntry> Duplicati.Library.Common.IO.ISystemIO.EnumerateFileEntries(System.String)'.

**Comment by ts678** [comment]
> Always worked until this update

What update? What came before? This isn't even the same error as before.
Yours is Method not found
Original At least one error occurred

Maybe you should open a new issue, with all of the details, and a proper title. Posting on closed issues is not always noticed.
