### ISSUE TITLE
Change default port

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [duplicati/duplicati#4784]
It would be nice to be able to change the default port for the WebUI

**Comment by Shlamy** [comment]
You already can, just add the switch.

--webservice-port=8200

Then change 8200 to whatever port value you want it to be at.

See https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/

**Comment by mariomurrent-softwaresolutions** [comment]
Does this also work for auto starting Duplicati on MacOS?

**Comment by Shlamy** [comment]
This is more of a question for the [Duplicati forums](https://forum.duplicati.com/) than it is an issue with Duplicati, but to answer your question, yes it does. In /Library/LaunchDaemons you'll have a file named something.Duplicati.something, open it in a text editor and make the change.

**Comment by ts678** [comment]
The requested capability sounds like it's there already. Can this issue be closed?
