### ISSUE TITLE
Be able to chain backups

### ISSUE THREAD

**Issue by federicoalvarez-github** [duplicati/duplicati#4789]
- [ X] I have searched open and closed issues for duplicates.
- [ X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Feature request
Be able to chain backups starting time.
Example:
- Backup 1: starts at 1am every day
- Backup 2: starts after Backup 1 every day
- Backup 3: starts after Backup 2 every day

This way we stop to worry about backup times, and can make the best use of time schedules.

**Comment by drwtsn32x** [comment]
Scheduled backups should queue up and run in sequence. Say for instance you schedule backup 2 to start 1 minute after backup 1 starts, and then backup 3 to start 1 minute after backup 2, they should run one after another regardless of how long they take.

Alternatively, you could only schedule backup 1 and configure it to run a post backup script that triggers backup 2 (using https://github.com/Pectojin/duplicati-client).  And do the same for backup 2.. a post backup script that triggers backup 3.  I think this might be more complex than the first idea though.

**Comment by federicoalvarez-github** [comment]
Oh, thanks a lot drwtsn32x for the info. Guess this issue can be closed then. The first tip is exactly what I was looking for. Best regards.
