### ISSUE TITLE
Microsoft OneDrive v2 --auth-username and --auth-password are set but not shown in the UI

### ISSUE THREAD

**Issue by dgasparri** [duplicati/duplicati#4797]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.3_beta_2021-06-170.0.0.0
- **Operating system**: Windows 10

## Description

When backing up to Microsoft OneDrive v2, --auth-username and --auth-password are set but not shown in the interface, and produce a warning ("given option... is not supported and will be ignored")

![warning message](https://user-images.githubusercontent.com/553197/180930602-c8850171-165c-4208-8e63-62a37cee948a.png)

They were probably set from a previous backup destination, and they remained in the config of the backup.   

Before "Microsoft OneDrive v2", the destination of that backup was set to "OneDrive for business" (I made lots of trials & errors to set it up, so not sure if they are from OneDrive for business or from other methods that I tried).

The command line output for the job is:

"C:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" backup "onedrivev2://DuplicatiDocs?authid=[AUTH_ID]&auth-username=[MY_OLD_USERNAME]&auth-password=[MY_OLD_PASSWORD]" [LIST OF FILES TO BACKUP] --backup-name="Documents e Home" --dbpath="C:\Users\[WIN_USER]\AppData\Local\Duplicati\[BACKUP_ID].sqlite" --encryption-module=aes --compression-module=zip --dblock-size=100MB --keep-time=3M --passphrase=[PASSPHRASE] --disable-module=console-password-input

Two fixes could be possible:
1) "erase" auth-username and auth-password from the config file when changing to OneDrive v.2
2) give some option from the UI to erase them manually (preferred, so you keep them stored in case you need them again)

Somehow related but different open issues: 
* #2312 Command Line option for auth-file https://github.com/duplicati/duplicati/issues/2312 
* #2024 Fix not revealing stored passwords from the UI

## Steps to reproduce
1. Set up a job with "OneDrive for business" as destination
2. Change the destination to "Microsoft OneDrive v2"
3. (do some random stuff to make OneDrive v2 work)

- **Actual result**:

![warning message](https://user-images.githubusercontent.com/553197/180930602-c8850171-165c-4208-8e63-62a37cee948a.png)

**Comment by ts678** [comment]
[Changing backend type leaves invalid backend options #3082](https://github.com/duplicati/duplicati/issues/3082#issuecomment-463431421) looks like this exact OneDrive issue, still open, with a workaround.
It's probably a generic issue though (not just OneDrive) awaiting a developer-volunteer with JavaScript skills to help. Any takers?
