### ISSUE TITLE
Website duplicati.com is down

### ISSUE THREAD

**Issue by BraveThrasher** [duplicati/duplicati#4801]
https://www.isitdownrightnow.com/duplicati.com.html

![image](https://user-images.githubusercontent.com/3652075/182545136-422d44ea-769b-4814-a286-761106b9d194.png)

**Comment by BraveThrasher** [comment]
It is back up and running.
![image](https://user-images.githubusercontent.com/3652075/182816585-a75a624c-3c27-4027-b615-284921ff87ec.png)

**Comment by nefingar** [comment]
Sorry to write into this old issue but it seems that your website is down again.

![Bildschirmfoto vom 2023-01-16 14-49-05](https://user-images.githubusercontent.com/6587625/212693945-b194e90f-086e-4245-ae36-a0f404d4599f.png)

**Comment by ts678** [comment]
[Duplicati.com down 01/16/23?](https://forum.duplicati.com/t/duplicati-com-down-01-16-23/15598) covers that outage and repair.
