### ISSUE TITLE
Jottaclout Oauth token expired - new release please =)

### ISSUE THREAD

**Issue by awisur** [duplicati/duplicati#4807]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com/) for related topics.
---------
Hi!

I notice in your commit log that you have fixed the Jottaclout Auth issue, happening in the 2.0.6.104 - 2022-06-15 release.

I am backing up pretty large chunks of data, and it fails midway due to Jottacloud auth (token expires), (Stuck on coax hybrid, with 25mbps limit) And sending a few hundred gigs takes time... I'd really appreciate a new release with the latest fix.

Thanks for a great product!

**Comment by ts678** [comment]
> you have fixed the Jottaclout Auth issue

That was the first try. There is another [fix checked in](https://github.com/duplicati/duplicati/pull/4779) but awaiting a Canary release. Meanwhile there are user-contributed DLLs.
[Jottacloud Error 401 (Unauthorized)](https://forum.duplicati.com/t/jottacloud-error-401-unauthorized/3929/188) and more testing and mulling... Ultimately I guess you want a Beta, but Canary comes first.
If you're willing to (carefully) run Canary plus unofficial DLLs, this was a [summary](https://forum.duplicati.com/t/jottacloud-error-401-unauthorized/3929/215?u=ts678) of how that seemed to be working for people.
Still not perfect. BTW, there's also a workaround of using current Beta plus [Rclone storage type](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#rclone) to imperfectly access Jottacloud.

**Comment by ts678** [comment]
> awaiting a Canary release

[2.0.6.105_canary_2023-04-09](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.105-2.0.6.105_canary_2023-04-09)

so should be in Beta release

[2.0.7.1_beta_2023-05-25](https://github.com/duplicati/duplicati/releases/tag/v2.0.7.1-2.0.7.1_beta_2023-05-25)

Please confirm this addresses the issue here, although this might not be the last of the Jottacloud glitches -- it's a difficult area.
