### ISSUE TITLE
Install & Run Windows 2008 R2 Server Core

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#481]
_From [carlos.a...@gmail.com](https://code.google.com/u/115322101827161513574/) on October 04, 2011 03:03:12_

The ability to install the application on Windows 2008 R2 Server Core and to run on it.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=481_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
