### ISSUE TITLE
PC was very slow when start backup 

### ISSUE THREAD

**Issue by xh542428798** [duplicati/duplicati#4811]
When I started backup, my PC got very slow, and nearly can't do any other work.
I adjusted some settings, but it didn't work, can you give me advice, thank you a lot.

![image](https://user-images.githubusercontent.com/49368033/187343126-1b231806-bab2-45dd-9605-bcf78f4110b1.png)

**Comment by mr-flibble** [comment]
Try:
`--thread-priority=belownormal`
or maybe
`--use-background-io-priority=true`

**Comment by ts678** [comment]
@xh542428798 did those help? Some amount of resource use is unavoidable, but at least you can give priority to other work.
Mechanical drives are slower than SSDs, CPU speeds vary, etc. Windows also does VSS snapshot (a.k.a. snapshot-policy) slowly.
Although you didn't mention it, startup on a PC can get very busy. To avoid adding load, Duplicati Settings can delay Duplicati.
