### ISSUE TITLE
[Question] Excuse me, it there any way to show file modified time in commandline?

### ISSUE THREAD

**Issue by xh542428798** [duplicati/duplicati#4813]
Excuse me, I want to look up some files' modified time, it there any way to show file modified time in commandline?

**Comment by ts678** [comment]
I think the answer is no, and nobody else seems to post a way so far.
[Implementing the feature to restore any version of a single file](https://forum.duplicati.com/t/implementing-the-feature-to-restore-any-version-of-a-single-file/14318/18?u=ts678) has thoughts, and at least shows you what versions have the file. There was also talk of a GUI feature (which got a pull request that for some reason got retracted later) to do something like this.
[Display versions for a file and allow any version to be restored #4805](https://github.com/duplicati/duplicati/pull/4805)

If you're really desperate, there might be a hard way. Maybe no easy.
