### ISSUE TITLE
MacOS Monterey 12.5.1 - Python 2.7 Not Found

### ISSUE THREAD

**Issue by cullinwible** [duplicati/duplicati#4816]
## Environment info
 Model Name:	Mac mini
  Model Identifier:	Macmini9,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	7459.141.1
  OS Loader Version:	7459.141.1

System Version:	macOS 12.5.1 (21G83)
  Kernel Version:	Darwin 21.6.0
  Boot Volume:	Internal
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled

Duplicati  Version:  - 2.0.6.104_canary_2022-06-15
Also reproducible in 2.6.0.3 release

- **Duplicati version**: 2.6.0.3
- **Operating system**: 12.5.1
- **Backend**: Amazon S3

## Description
The duplicati processes fails as it is unable to locate /usr/bin/python2.7.

In MacOS 12.5.1 the /usr/bin directory is read-only (and can't be modified even with SIP disabled) and Python 2.7 has been relocated to /usr/ocal/bin as per Apple's guidance.

As a result, the following error occurs:

./duplicati
Unexpected error: System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/usr/bin/python2.7', CommandLine='"/Applications/Duplicati.app/Contents/Resources/OSXTrayHost/osx-trayicon-rumps.py"', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <5964c1f33a6b4e45985e4259425270a7>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <5964c1f33a6b4e45985e4259425270a7>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <5964c1f33a6b4e45985e4259425270a7>:0 
  at Duplicati.GUI.TrayIcon.RumpsRunner.Restart () [0x0005c] in <3219859fc3fa41308da204ec423b38a9>:0 
  at Duplicati.GUI.TrayIcon.RumpsRunner.Init (System.String[] args) [0x0000c] in <3219859fc3fa41308da204ec423b38a9>:0 
  at Duplicati.GUI.TrayIcon.Program.StartTray (System.String[] _args, System.Collections.Generic.Dictionary`2[TKey,TValue] options, System.String toolkit, Duplicati.GUI.TrayIcon.HostedInstanceKeeper hosted, System.String password, System.Boolean saltedpassword) [0x000f9] in <3219859fc3fa41308da204ec423b38a9>:0 

Please note duplicati-cli process appears to work normally. It appears that the problem is related to locating Python 2.7 and launching the host tray icon in the interactive version.

The offending problem appears to be in GUI/Duplicati.GUI.TrayIcon/RumpsRunner.cs, Line 102: the definition of RUMPS_PYTHON.

As per the code, I performed the following, which allows the app to run:
- Install Python 2.7
- pip2 install rumps
- env PYTHON_RUMPS=/usr/local/bin/pyton2.7 ./duplicati 

One fix would be to make PYTHON_RUMPS a list and check multiple common file locations.

## Steps to reproduce
1. Install Duplicati
2. Launch Terminal
3. cd /Applications/Duplicati.app/Contents/MacOS
4. ./duplicati

- **Actual result**: Stack Trace, Failure
- **Expected result**: Program Launch

## Screenshots
There are no screenshots. From a visual perspective the app appears to do nothing (as it crashes in the background).

**Comment by cullinwible** [comment]
Thank you for the related PR.

I searched for this issue prior to submitting this bug and couldn't find anything.

If that solution works, then that's great.

Using env to launch the program definitely works as a temporary solution.

And it's definitely broken on 12.5.1 out of the box..

**Comment by ielashi** [comment]
I'm running into the same issue as well.

**Comment by tephyrnex** [comment]
_If you can get Python27 installed_, the following will launch the tray icon.  However, how you go about installing Python27 can vary greatly depending upon your needs.

RUMPS_PYTHON=/Library/Frameworks/Python.framework/Versions/2.7/bin/python open /Applications/Duplicati.app

The REAL solution is to update Duplicati.app to work with Python3.

**Comment by gpatel-fr** [comment]
@akalsnes 
rumps has been updated to python3 in 2.0.7, there is no need to test it further.

**Comment by ts678** [comment]
Testing of the maybe-missing installation directions might be useful. Would have been nice before 2.0.7.1, but maybe premature before real-world feedback on how the motivated early adopters went about this install -- and what bumps they hit on the way.

There were several users interested in the fix, but only the latest poster @akalsnes has responded. Does this mean you want the directions for 2.0.7.1 so as to get back up? That would be a good chance for @gpatel-fr to treat this as a support request or put directions somewhere (would a [How-To](https://forum.duplicati.com/c/howto/14) be good, pending updating the User Manual?), then hear how well steps go for another.

Currently the User Manual directions only document how to grab `mono`, but install has more actions now that Python 2 is gone. Alternatively, if nobody has an interest in install test or further feedback, this issue can just close either manually or automatically.
