### ISSUE TITLE
Dropbox connect fails

### ISSUE THREAD

**Issue by lupa18** [duplicati/duplicati#4817]
- [ x] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Linux Mint / Windows (tested on both)
- **Backend**: Dropbox

## Description

When trying to test Dropbox connection and after did the auth procedure, I got this error: 
```
Failed to connect: Non-json response: Error in call to API function "files/list_folder": The given OAuth 2 access token is malformed. 
```

I searched both github and forum and similar problem was supposed fixed on Feb 22 but it still happens. 

## Steps to reproduce

1. Create new backup
2. Choose Dropbox and do the auth process
3. Click test button

- **Actual result**: got an error
- **Expected result**: Test may success

## Screenshots

![imagen](https://user-images.githubusercontent.com/463429/188918055-5d1d8924-f735-4cbd-ba96-ba5384fe536f.png)

**Comment by gpatel-fr** [comment]
Hello

you say that the problem is supposed fixed on 22 Feb, yet you are using a version from June 2021. How about trying last canary ?

**Comment by lupa18** [comment]
Oh, your are right. What canary mean? I guess is a development snapshot or similar. 

Can't find references on README.

**Comment by gpatel-fr** [comment]
Canary means nightly in Duplicati lingo. Click on Releases in the main Github page for the project. Canary is in the last release name from 15 June (2022)

**Comment by lupa18** [comment]
Ok, thanks. It works !!
