### ISSUE TITLE
All recent download releases have invalid signatures and therefore cannot be trusted.

### ISSUE THREAD

**Issue by nsclong** [duplicati/duplicati#4820]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3-1 and 2.0.6.102
- **Operating system**: Debian 11
- **Backend**: n/a

## Description

The download files all have "Bad signatures" when using `gpg --verify` with the correct imported key.

## Steps to reproduce

1. Import keys with `gpg --keyserver pgp.mit.edu --recv-keys 0xC20E90473DAC703D`
2. Download latest release and signature files, then unzip signature files
3. Perform signature verification with `gpg --verify duplicati_2.0.6.102-1_all.deb.sig.asc`
4. Bad signature error is given
5. This affects all the latest canary releases and the latest beta release.

- **Actual result**:
"Bad signature" error received
- **Expected result**:
"Good signature"

**Comment by gpatel-fr** [comment]
Not sure what you want to do here. The result of your command seems to be to check the binary signature with the ascii form. I don't see why this should succeed. 

However, this works:
```
LANG=EN gpg --verify duplicati_2.0.6.104-1_all.deb.sig  duplicati_2.0.6.104-1_all.deb
gpg: Signature made Wed Jun 15 22:18:45 2022 CEST
gpg:                using RSA key CBD0A83118CAFD23DF82F99CC20E90473DAC703D
gpg: Good signature from "Kenneth Skovhede <kenneth@duplicati.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: CBD0 A831 18CA FD23 DF82  F99C C20E 9047 3DAC 703D

**Comment by nsclong** [comment]
I'm sorry - I was obviously having a brain freeze on my use of the gpg command line.
Many thanks for getting back to me, and for including the successful example.
Sorry to waste your time.
