### ISSUE TITLE
Feature Request: Add Digiboxx Cloud Storage

### ISSUE THREAD

**Issue by itsprakashp** [duplicati/duplicati#4823]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Description

Please add [Digiboxx Cloud Storage](https://digiboxx.com/). New budget cloud storage from India.

**Comment by ts678** [comment]
Do they have an application program interface (API) to upload, download, list, and delete files? Best case is a standard protocol.

**Comment by ts678** [comment]
> New budget cloud storage

I can't even tell from their web site what exactly this is. They have lots of different capabilities listed there, but few details.
There does seem to have been an allegedly S3 compatible product added in July 2023 called Megh3, but is pricing good?
They compare themselves to other premium services, so cost less, but cost a lot more than other non-premium vendors.

Basically the old stuff seems to have no API, and the new S3 protocol might just work if you're willing to sign up and test.
