### ISSUE TITLE
Issue with Duplicati OAuth Handler / Hubic

### ISSUE THREAD

**Issue by sebbo2002** [duplicati/duplicati#4824]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Linux
- **Backend**: Hubic

## Description

I currently have issues with the Duplicati OAuth Handler. Already generated AuthIDs do not work anymore (`Authorization with the OAuth service failed: Server error. If the problem persists, try to generate a new AuthID token from: https://duplicati-oauth-handler.appspot.com?type=hubic`) and when I click on the Hubic button on the OAuth Handler page, I get back an `ERR_EMPTY_RESPONSE`. Are there any current problems with the service?

## Steps to reproduce

1. Open https://duplicati-oauth-handler.appspot.com?type=hubic
2. Click on Hubic login button

- **Actual result**:
   `ERR_EMPTY_RESPONSE`
- **Expected result**:
   Probably a redirect to Hubic? I don't know to be honest.

## Screenshots
https://user-images.githubusercontent.com/812398/194777031-dd2db6dd-43bc-4d98-b531-10ad17e5f711.mov

## Debug log

\-

**Comment by NickPyz** [comment]
I was notified some time ago that the HubiC cloud storage service was shut down. Most likely why you are receiving the OAuth Handler error message
