### ISSUE TITLE
Malformed Dropbox token

### ISSUE THREAD

**Issue by wallart1** [duplicati/duplicati#4841]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

I saw issue 4817 where this issue was solved. But it doesn't say what release fixed it.

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Linux Mint 20.3
- **Backend**: Dropbox

## Description
New (first time) Dropbox connections gets: The given OAuth 2 access token is malformed.

## Steps to reproduce

1. Set up a new Dropbox Oauth connection. The key is automatically filled in.
2. Click on the "Test Connection" button
3. The error message results.

- **Actual result**:
An error message.
- **Expected result**:
A successful connection to Dropbox

![Screenshot from 2022-11-04 23-00-09](https://user-images.githubusercontent.com/84820338/200098128-845bdd3b-aa28-40fe-a779-cf6924c23656.png)
![Screenshot from 2022-11-04 23-03-33](https://user-images.githubusercontent.com/84820338/200098206-c6477d86-4267-4d7b-946c-7c2f25b70b40.png)
![Screenshot from 2022-11-04 23-04-26](https://user-images.githubusercontent.com/84820338/200098221-65916793-8c09-4de8-8089-2da63c612152.png)
[Log.zip](https://github.com/duplicati/duplicati/files/9942911/Log.zip)

**Comment by wallart1** [comment]
[bugreport.zip](https://github.com/duplicati/duplicati/files/9942926/bugreport.zip)

**Comment by ts678** [comment]
> it doesn't say what release fixed it

When it said:

> Canary means nightly in Duplicati lingo. Click on Releases in the main Github page for the project. Canary is in the last release name from 15 June (2022)

it referred to:

https://github.com/duplicati/duplicati/releases

https://github.com/duplicati/duplicati/releases/tag/v2.0.6.104-2.0.6.104_canary_2022-06-15

Typically one who wants Canary wants the latest one (maybe after waiting a bit, and watching [forum Releases](https://forum.duplicati.com/c/releases/10) for user reactions).

If you don't want to risk the unpredictable Canary release, the forum has a possible workaround at [Error connecting to Dropbox](https://forum.duplicati.com/t/error-connecting-to-dropbox/13989/4?u=ts678).

Please be careful about posting AuthID, especially if that's the entire string.

**Comment by wallart1** [comment]
Thank you very much. My Duplicati is working great now.

**Comment by ts678** [comment]
> My Duplicati is working great now.

Good to hear. Closing issue.
