### ISSUE TITLE
Bitcoin address on donation page is not valid

### ISSUE THREAD

**Issue by PLK2** [duplicati/duplicati#4842]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

https://www.duplicati.com/donate/

## Description

Your bitcoin address on your donation page is not valid.
https://www.duplicati.com/donate/

## Steps to reproduce

- **Actual result**:
I tried to send you bitcoin but it's an invalid address.
- **Expected result**:
I could send you some bitcoin.

**Comment by mr-russ** [comment]
@kenkendk I think this is one to be handled by you.  Bitcoin donation addresses.

**Comment by ts678** [comment]
[Halting donations](https://forum.duplicati.com/t/halting-donations/17583) explains the recent change to the funding model.
[Removed donation messages #5125](https://github.com/duplicati/duplicati/pull/5125) shows change to the program.
The web site has been remade, and has no donation page anymore.
