### ISSUE TITLE
"Search for files" feature on Restore page is unusable: It takes literally hours with no feedback on progress and no way to cancel or view the results if one accidentally navigates away from the page

### ISSUE THREAD

**Issue by posita** [duplicati/duplicati#4850]
- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Pop!_OS 22.04 LTS (64 bit)
- **Backend**: "Local" (SMB mount) storage

## Description

My `Search for files` operation has been currently running for 2.5 hours with no results and no indication on whether it will ever finish, much less when. `mono-sgen` has my CPU pegged the entire time. I'm not sure why. The following query takes under a second:

``` sh
% time sqlite3 ~/.config/Duplicati/<redacted>.sqlite "SELECT * FROM File WHERE Path LIKE '%<term>%'" | wc -l
181193
sqlite3 /<redacted>/.config/Duplicati/<redacted>.sqlite   0.32s user 0.04s system 97% cpu 0.369 total
```

Further, after I navigate away from the restore page, the CPU stays pegged, but I can't ever get back to the results (should they ever appear).

**Comment by gpatel-fr** [comment]
Is still this true with latest Duplicati (2.0.7.100) ?
