### ISSUE TITLE
Allow scheduled job to wait for other job to be completed

### ISSUE THREAD

**Issue by jaypi95** [duplicati/duplicati#4852]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Docker (linuxserver.io container)
- **Backend**: Google Drive

## Description

I have a job that runs a few minutes after another one. Sometimes that first job takes more time to complete and then the second one fails. It would be great if there was an advanced option where we could set that the second job should only run after the first one has finished even if that meant that the second job would get scheduled later.

**Comment by ts678** [comment]
Assuming you're talking about the Duplicati GUI scheduler, what you ask for is the default (and only) option -- second job waits.
If you're scheduling your own for CLI, jobs are independent of each other and of the GUI. This actually may reduce collision risks.
If you have a specific error situation to discuss, a support topic on the forum is a little more visible, and discussion is a bit easier...

**Comment by jaypi95** [comment]
I guess there must be something else broken then. I will investigate and if it turns out to be a duplicati problem, I'll open another issue. I apologize for unnecessarily open an issue here.
