### ISSUE TITLE
Timeout detection feature about duplicati

### ISSUE THREAD

**Issue by huangwb8** [duplicati/duplicati#4855]
Recently I found a "bug" of duplicati.

Supposed I backup files from A to B. Sometimes, the connection between A and B might be instable and interrupted.

A right way to deal with this situation is to stop the task after a given time limiatation (20 min for example), send a warning email, and begin the next task.  However, duplicati just stucks for a long time (days or months) without any warnings, errors, and new tasks starting. This feature seriously impairs the stableness of duplicati. 

Any suggestions?

===

Version: Duplicati - 2.0.6.3_beta_2021-06-17

**Comment by gpatel-fr** [comment]
Hello

could you give more precise steps to reproduce your problems ? 

I tried to repro with last canary installed on an Ubuntu server to launch a backup to a sftp server and stopped the server while Duplicati was uploading files. The backup was interrupted practically without delay. After I restarted the sftp server, I restarted a new backup and Duplicati completed the interrupted backup. In conclusion, everything worked as it should.

If you can't give precise operational details, you can discuss problems on the forum instead.

**Comment by huangwb8** [comment]
I would give more details in the next time I meet the bug. Please keep this issue open. Thanks!

**Comment by ts678** [comment]
Timeouts are extremely backend dependent, but you omitted the "Backend" and "Operating system" info from issue template.
If you prefer to keep it as generic enhancement request to add a global timeout, that's fine but not likely to actually get done.
Even ignoring the lack of developer volunteers, there are lots of third-party libraries involved that may or may not permit this.
For a specific problem using a specific backend (storage destination), it is probably best to attempt support work in the forum.

**Comment by huangwb8** [comment]
@ts678  @gpatel-fr 

Thanks for your concern!

Here is the environment of my Duplicati:

```bash
uname -a # Linux racknerd-74a241 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

docker-compose --version # Docker Compose version v2.4.1

docker --version # Docker version 20.10.21, build baeda1f
```
I use a docker image of Duplicati developed by linuxserver.io team

![image](https://user-images.githubusercontent.com/35643122/206884703-a9ff8627-68cd-499c-957b-cecb242d85b2.png)

Again, a similar situation appears:

1. The backup is stuck in `Verifying files`. Other projects were delayed:

![NsGxb21eMz](https://user-images.githubusercontent.com/35643122/206884777-a33122a4-699a-4257-8ebc-f945f71c282a.png)

2. The stuck time is about 10 hours and still continuing:

![bVmYcFDzLU](https://user-images.githubusercontent.com/35643122/206884793-0ba1e262-63c6-48a6-9444-938d0a311ebd.png)

Any suggestions?

**Comment by gpatel-fr** [comment]
I'd suggest to look at the general live log (About function / Show log) with maximum level (explicit only). From the job log, it seems that nothing has happened between 1h and 11h. See if this is really the case. If yes also from the server log, it may be that something has crashed. Look for a core file in this case (although I don't know docker and if it generates proper core files...)

**Comment by ts678** [comment]
Still asking for `Storage Type` of `Destination` and any other backend information you can offer. Does it keep any logs?
On Duplicati log on the last screenshot, does the `list` at the top show any remote files when you click it, i.e. did it run?
After `list`, the expected next (towards top of screen) things would normally be three file `get` as seen for previous day.
Maybe one of those started but didn't finish. That would be more clearly visible on any log at Information level or higher.
If it's not visible in the current live log, you could set up [log-file](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file)=\<path> [log-file-log-level](https://duplicati.readthedocs.io/en/latest/06-advanced-options/#log-file-log-level)=retry to try to catch next stop.

**Comment by gpatel-fr** [comment]
@ts678 
somehow I have a hunch that the storage type is 'disk', since it's a NAS. This kind of storage (remote disk) has the peculiarity that it can be subject to networks timeout like anything connected to a network, but it's nature is hidden behind the local hard disk appearance - 'timeout' is not a standard local disk error code. It could be a reason why Duplicati is not handling it well. Personally if I wanted to backup a local Windows workstation, I'd use SFTP (well, another reason is that it would be much easier to 'hide' the backend from prying ransomware)

**Comment by huangwb8** [comment]
Thanks guys! 

I have a solution, which I think is the best and fast way to deal with the so-called 'timeout' problem. 

Because I use docker, I just use cron like:

```bash
0 18 * * * root docker restart duplicati >/dev/null 2>&1
```

Thus, the duplicati container will restart everyday in 6:00 p.m., when is not a time I backup my projects (always 0:00-6:00 a.m.). Even thought the 'timeout' error occur, the backup would no be delayed more than 24 hours, which is acceptable for me.

Thanks for all of you!
