### ISSUE TITLE
No access to gui with https enabled

### ISSUE THREAD

**Issue by mkono87** [duplicati/duplicati#4856]
- [x ] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Windows 10
- **Backend**: SSH

## Description

Trying to open the gui with the windows tray icon opens my browser and gives me an ssl error. I cannot proceed through like you normally would with a self signed cert. I have to use firefox or change the link to http which doesnt work in vivaldi, only edge.

## Steps to reproduce

1. Trying to open the gui with the windows tray icon opens my browser and gives me an ssl error.

- **Actual result**:
No access to gui
- **Expected result**:
Access to gui

## Screenshots

![image](https://user-images.githubusercontent.com/35116314/205496356-410beb12-9491-4398-b496-71d5bf2484a3.png)

**Comment by gpatel-fr** [comment]
Hello

I tried it with (add sudo where necessary):

cd /usr/lib/duplicati/data
openssl req -x509 -days 730 -nodes -newkey rsa:2048 -keyout cert.pem -out cert.pem
openssl pkcs12 -in cert.pem -inkey cert.pem -out cert.p12 -export
vi /etc/default/duplicati
->
DAEMON_OPTS="--webservice-interface=any --webservice-port=8200 --portable-mode --webservice-sslcertificatefile=/usr/lib/duplicati/data/cert.p12"
then systemctl restart duplicati
and access to https://localhost:8200 worked after accepting the certificate.

tested with Firefox 107.0.1
