### ISSUE TITLE
Renci.SshNet.Common.SshConnectionException: MAC error

### ISSUE THREAD

**Issue by dsptech** [duplicati/duplicati#4881]
- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: v2.0.6.104-2.0.6.104_canary_2022-06-15
- **Operating system**: Windows 10 Home 22H1 - Italian
- **Backend**: SFTP storage with keyfile.

Background:
Hi,
I recently upgraded a computer from Windows 8.1 to Windows 10 (fresh installation), reinstalled the latest version of Duplicati, restored the sftp key and finally restored the batch scripts that calls duplicati.commandline (activation by scheduled tasks). After that, I wiped out the SFTP storage and also the local DB to start a new fresh backup.

Unfortunately now things no longer work as before and during the final download  (I presume) to check the saved backup I get the MAC error as reported in the log. This issue has been occurred after a week of daily backups. I also wiped again the backup from the storage (and the DB too) but the issue is still on.

This might not even be a Duplicati's issue (https://github.com/sshnet/SSH.NET/issues/874), but I would be grateful if anyone could give me some hint on how to deal the issue.
Thank you.
Regards.

---- Duplicati Log ----

DeletedFiles: 2
DeletedFolders: 0
ModifiedFiles: 32
ExaminedFiles: 7817
OpenedFiles: 7817
AddedFiles: 28
SizeOfModifiedFiles: 5146601970
SizeOfAddedFiles: 2370038
SizeOfExaminedFiles: 10681634833
SizeOfOpenedFiles: 10681634833
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
ParsedResult: Error
Version: 2.0.6.104 (2.0.6.104_canary_2022-06-15)
EndTime: 29/12/2022 00:12:26 (1672269146)
BeginTime: 29/12/2022 00:00:04 (1672268404)
Duration: 00:12:21.8615930
MessagesActualLength: 33
WarningsActualLength: 0
ErrorsActualLength: 1
LimitedMessages: [
    2022-12-29 00:00:09 +01 - [Information-GetGpgProgramPath-gpg]: C:\Program Files\Duplicati 2\win-tools\gpg.exe,
    2022-12-29 00:00:09 +01 - [Information-Duplicati.Library.Main.Controller-StartingOperation]: L'operazione Backup è iniziata,
    2022-12-29 00:00:12 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),
    2022-12-29 00:00:14 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (193 bytes),
    2022-12-29 00:04:30 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-be4aa2a1461394ba1bd257c4c3e464e8a.dblock.zip.aes (2,97 MB),
    2022-12-29 00:05:37 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-be4aa2a1461394ba1bd257c4c3e464e8a.dblock.zip.aes (2,97 MB),
    2022-12-29 00:05:37 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-i90998f09ec134491944632b206e7e9b2.dindex.zip.aes (180,33 KB),
    2022-12-29 00:05:41 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-i90998f09ec134491944632b206e7e9b2.dindex.zip.aes (180,33 KB),
    2022-12-29 00:05:41 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started: duplicati-20221228T230010Z.dlist.zip.aes (802,11 KB),
    2022-12-29 00:05:59 +01 - [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed: duplicati-20221228T230010Z.dlist.zip.aes (802,11 KB),
...
]
LimitedWarnings: []
LimitedErrors: [
    2022-12-29 00:12:26 +01 - [Error-Duplicati.Library.Main.Operation.TestHandler-FailedToProcessFile]: Failed to process file duplicati-b2b96595b4e904923835b5159de5c90bc.dblock.zip.aes
]
Log data:
2022-12-29 00:12:26 +01 - [Error-Duplicati.Library.Main.Operation.TestHandler-FailedToProcessFile]: Failed to process file duplicati-b2b96595b4e904923835b5159de5c90bc.dblock.zip.aes
Renci.SshNet.Common.SshConnectionException: MAC error
   in Duplicati.Library.Main.BackendManager.GetForTesting(String remotename, Int64 size, String hash)
   in Duplicati.Library.Main.Operation.TestHandler.DoRun(Int64 samples, LocalTestDatabase db, BackendManager backend)

**Comment by gpatel-fr** [comment]
Hello

did you change any default parameter - particularly dblock-size, since the ssh-rency issue you linked to is alluding to the file size getting too big ?

**Comment by dsptech** [comment]
Hi, 
I linked the issue to remark that the problem might came from the used SSH library and not from Duplicati itself (regardless the block size). Moreover, I also just found this: https://github.com/sshnet/SSH.NET/issues/1017 which reports the problem even with only 30KB of download.

Anyway yes, the block size is actually set to 100MB (to reduce the total number of files), but I must say the it work fine elsewhere. Could this be related to the issue ?

For completeness, I attach the (unattended) call to duplicati.commandline actually used ("Duplicati2" is a sub-folder of the user folder where the batch is running. Some sensitive info are obfuscated).

Thank you.
Regards.

--------
`
"C:\Program Files\Duplicati 2\Duplicati.CommandLine.exe" backup "ssh://<host name>:8888//backup/mainbackupPC2?auth-username=<username>&ssh-keyfile=%USERPROFILE%\AppData\Dup2\SftpKey.key&ssh-accept-any-fingerprints=true" <dir list> --backup-name=InternetBackup --dbpath="Duplicati2\DB\interBack.db" --encryption-module=aes --compression-module=zip --dblock-size=100MB --passphrase="<passphrase>" --retention-policy="2W:1D,8W:1W,24M:1M" --tempdir="Duplicati2\temp" --disable-filetime-check=true --send-mail-from="<mail from>" --send-mail-to="<mail to>" --send-mail-url=smtps://<smtp server> --send-mail-username="<smtp user>" --send-mail-password=<smtp pass> --send-mail-subject="Backup PC2" --log-file="Duplicati2\log\internetBackup.log" --log-file-log-level=Warning  --disable-module=console-password-input  >>Duplicati2Console.log
`

**Comment by dsptech** [comment]
Update: 
I just checked the last nightly backup log and now it seems to work again, but I'm not happy because the error has become random and it will be more difficult to find the real problem.

As a first check, I will download the entire backup storage and check it with another computer (just to see if the backup is not corrupted). It will take a few days but I will keep this issue updated.
Regards.

**Comment by gpatel-fr** [comment]
Reading the 2 SSH issues, it seems to be 2 different problems in fact.

- with WPF project, linked to big amount of data, > buffer size.
- with UWP project, unrelated, happens even with data < buffer size.

Duplicati is not an UWP project so it could be the first kind of problem. It's all murky since the SSHNET project has not a great level of support and there was no follow-up, just a string of complaints.

If the problem can't be reproduced reliably here, there is also the possibility that in the SSHNET issues the same was true.
Maybe the root cause is that the software is  not handling network errors reliably.
Did you check for errors in the statistics of your interface ? Also MTU is often a reason for quasi random network problems (however it only happens on the Internet usually, for local connections there is almost always only one path from a computer to another and either it works or it don't)

**Comment by dsptech** [comment]
Hi @gpatel-fr, 
sorry for the delay. 
It would appear that the backup inside the storage is not corrupted and that the error occurs only in download situations (by Duplicati). Tests with filezilla are fine instead (but hidden and strong retries may be involved). 
Moreover, the maximum unfragmented TCP packet size (ping -f) is: 1460 (MTU=1500), a normal valuea and statistics about the ethernet connection show no errors. Unfortunately I don't have access to the router logs, if any, and I doubt that the internet provider will provide serious feedbacks.

Anyway I'm now trying to catch other issues in case they are misinterpreted by the SSH layer and reported as a MAC error, so I've set a speed limit on Duplicati downloads. The issue hasn't reoccurred but to make this meaningful we have to wait another 2 or 3 weeks.

I keep you updated.
Thank you.

**Comment by dsptech** [comment]
Hi @gpatel-fr,
 
update: 
Two months ago I deactivated the network adapter (built into the HP motherboard) and installed a new one. After that the sporadic error did not occur again so now I can say that the issues is related to the network hardware.

Just for the record, and in case someone is facing the same issue:
- With Windows 8.1, the same release of Duplicati worked fine up to the upgrade to Windows 10.
- The built-in network adapter of the HP PC (Realtek based) appear to work properly with any OS (even Linux).
- Last available driver provided by HP is for Windows 8.1. 
- With windows 10, drivers from Realtek were tried as well as those taken from Windows Update.
- Transfers via Filezilla and any other network activity occurs without any issues.
- No network errors (of any kind) are reported by the Windows event log.
- The new network card is Realtek based too.

Now I suspect some customization by HP, or a very deep defect, not properly handled by the generic drivers for Windows 10. This can also lead to some false condition triggered like MAC error by Renci.SshNet.

Anyway, this problem is not related to Duplicati, so I'm closing the issue on github.

Thank you for the support.
Regards.
