### ISSUE TITLE
Option "Alternate-destination-marker and alter-destination-target

### ISSUE THREAD

**Issue by escandihado83** [duplicati/duplicati#4883]
## Environment info
Local -> Usb disk
- Duplicati version : 2.0.6.104_canary_2022-06-15
- Operating system : Windows 10
- Backend**: local disk USB

I tried to put these 2 options
- Alternate-destination-marker -> duplicati.txt
- and alter-destination-target -> *:\duplicati
 but when I re-edit the duplicati options these options disappear.

so I can not mark the usb disk
Of course I can still make a backup.

**Comment by Shlamy** [comment]
This is a known issue when first defining a backup job, the "Local Drive" options are missing or vanish after being added.

Work around: Create the job without the advanced options, save the job then reopen it and the options will now be available to add.

[Thread on the Duplicati forums](https://forum.duplicati.com/t/solved-losting-advanced-options-when-the-backup-job-is-changed/13478)
[One of the previous reports of this issue](https://github.com/duplicati/duplicati/issues/4553)

**Comment by escandihado83** [comment]
that doesn't work either
