### ISSUE TITLE
I want to repackage the source code into an exe installation file, but the "WixInstall" item in the source code cannot be used normally. Can I update it?

### ISSUE THREAD

**Issue by Renhj9** [duplicati/duplicati#4888]
## Environment info

- **Duplicati version**: 0.0.0.0
- **Operating system**: Windows
- **Backend**: Amazon S3

## Description
How do I package the project source code as a Windows installer?The package project in the current source code seems to be missing files,I want to repackage the source code into an exe installation file, but the "WixInstall" item in the source code cannot be used normally. Can you update it?

## Screenshots
![image](https://user-images.githubusercontent.com/114142291/217457814-d56e784e-f4ce-47e7-ad93-3f97e7a5e4f5.png)

**Comment by gpatel-fr** [comment]
Hello @Renhj9 

you ask many questions. I prefer only to focus on the first one 'How do I package the project source code as a Windows installer?'  I find your other questions confusing.

There are 3 steps for a custom build  (the steps used for the project are much more complicated)

- build the binaries: use msbuild against Duplicati.sln

- bundle: select binaries (resulting from the first step) and data files and bundle them into a zip file. You can find the exact list of required files in a command file named build-installers.sh (@Xavron has the basic right)

- build a msi: in Installer/Windows you can find a batch named 'build-msi.bat' that you call with the zip file as parameter.
After running it, in the same directory you will find Duplicati.msi and Duplicati-32.msi. This batch is using Wixinstaller.sln so if you want to find the exact incantation you can examine its console output.

tested today using wix3.14 and current latest Duplicati.

Hope this helps.

**Comment by Xavron** [comment]
Interestingly enough I just ran through this in the past hours today with Visual Studio 2022 as I made a comment in another posted issue about people can fork and built it themselves which makes building an installer highly relevant. Here's the exact steps needed with Visual Studio 2022 (I didn't look at the bat file that gpatel mentions but simply running it as a test did nothing for me):

Install Visual Studio 2022

Make sure .net's and targets are all installed (I also have c++ installed but that was without Duplicati in mind)


## To build Duplicati:

Grab git source of Duplicati

Open duplicati sln

If it complains about .net then you don't have all the packages installed and need to use Visual Studio Installer application and manage and find .net's not installed and install them.

Now need to fix nuget packages as that's broken in VS 2022 lol

Download the nuget exe: https://www.nuget.org/downloads

Put that in the duplicati source code root where duplicati project sln file is

Open duplicai sln and thus project in VS 2022

Open Terminal in VS 2022: View > terminal

Run nuget restore: ".\nuget restore Duplicati.sln" w/o quotes

Can now successfully build the project:
========== Build: 53 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 7:19 PM and took 10.265 seconds ==========


## To build the installer:

Grab the wix plugin for VS: https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2022Extension

Download and install it

Also need the build tools: https://wixtoolset.org/releases/v3.11/stable

Download the .exe installer and install it
 
Need to add > RunAsSeparateProcess="true" < to WixInstaller.wixproj's <HeatDirectory ... > entry or VS 2022 will hard crash

Need to copy "...\duplicati\Duplicati\GUI\Duplicati.GUI.TrayIcon\bin\Release" to "...\duplicati\Installer\Windows\" and then rename "Release" to "Duplicati"

Open "...\duplicati\Installer\Windows\WixInstaller.sln"

If it says incompatible from previously trying then right click on the solution in Solution Explorer and reload project

If you did it backwards then after getting wix above then exit VS and open the project again

May want to set project to eg Release and x64

Can now successfully build it:
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
========== Build started at 7:18 PM and took 21.879 seconds ==========

Built msi is found at "...\duplicati\Installer\Windows\bin\x64\Release\Duplicati.msi"

**Comment by gpatel-fr** [comment]
@Renhj9 

are these answers enough to solve your problem ?
