### ISSUE TITLE
really javascript htm interface ?? really only aes-256 encrypt;

### ISSUE THREAD

**Issue by mzayarnyuk** [duplicati/duplicati#4893]
really javascript htm interface ?? really only aes-256 encrypt; ???
is enough to stop use it;
pls do normal interface so maybe willcheck rest of functions

**Comment by mzayarnyuk** [comment]
is old 1.3.4 code aavailable for fork somewhere ?
what lic for old duplicati is ?

**Comment by gpatel-fr** [comment]
>>fork somewhere ?

the code you are searching for is in this repository.
Feel free to close this issue.

**Comment by mzayarnyuk** [comment]
thx. missed it's in top of branches;

**Comment by mzayarnyuk** [comment]
aes-128 is half bruteforced; so 256 will have or already had same options;
recheck tryecrypt make similar will be perfect;

**Comment by drwtsn32x** [comment]
Not sure what half bruteforced means, but I'm curious and will do some searching.

In any case AES-256 isn't twice as hard to brute force than AES-128.   Say AES-128 could be brute forced in 1 year (as an example).  Each "bit" increase would double that brute force time.  AES-256 would take 2^128 times as long to brute force than AES-128.  (All bets are off if a flaw is discovered in the algorithm, of course.)

**Comment by ts678** [comment]
> really only aes-256 encrypt; ???

Not really. You can use GNU Privacy Guard which adds about a dozen other options, per a glance at Wikipedia page.

![image](https://user-images.githubusercontent.com/40771998/219965152-a15ec30a-6f98-45fe-abca-1d427ee7b9d1.png)

> recheck tryecrypt

If that meant TrueCrypt, development ended in 2014. I think VeraCrypt is its successor. Its default looks like AES-256,
however I think both programs have lots of options. It's their main point, whereas Duplicati's main point is to backup.
It's also not going to protect the files on your drive or your backup as well as encrypted container. What's your need?
[Encryption program necessary?](https://forum.duplicati.com/t/encryption-program-necessary/15726) just talked about some of the tradeoffs.

> All bets are off if a flaw is discovered in the algorithm or implementation, of course.

VeraCrypt (and I think TrueCrypt) allow [Cascades of ciphers](https://veracrypt.eu/en/Cascades.html), raising protection against one falling, e.g. as you describe.

> really javascript htm interface ??

There's also a command line interface, if that helps any. If you need the old non-HTML GUI, unsupported 1.3.4 has it.
