### ISSUE TITLE
Doesn't Start on macOS Ventura 13.X

### ISSUE THREAD

**Issue by mhellmeier** [duplicati/duplicati#4899]
- [ x ] I have searched open and closed issues for duplicates.
  - Maybe related to #3197
- [ x ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3
- **Operating system**: macOS Ventura 13.2.1

## Description

Tried to create a fresh install of the latest Duplicati 2.X beta version, but it doesn't start on macOS.

For installation, I used Homebrew (`brew install --cask duplicati`) which doesn't work. I also tried to install it manually with the `.dmg` file (same result: doesn't work).

The application file appears in the correct folder, but after starting it, nothing happens. No browser or running background task is shown. `mono` is installed as described in the documentation.

**Comment by ts678** [comment]
> Tried to create a fresh install

Is this the first install for you? These days, the typical problem is from [Apple removing Python in macOS Monterey 12.3](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes).
[Duplicati not starting on MacOS Monterey 12.3 on M1](https://forum.duplicati.com/t/duplicati-not-starting-on-macos-monterey-12-3-on-m1/14096) is a topic where you can ask, or volunteer to try out a test build.

**Comment by mhellmeier** [comment]
Thanks a lot for your response and the link to the forum entry. I only got Python 3.X installed. After installing Python 2.X additionally, it doesn't work either.

But the workaround described in the forum works for me until this bug may be fixed. For other people, just open a terminal and execute the following commands:
```cmd
$ cd /Applications/Duplicati.app/Contents/MacOS
$ ./duplicati-server
```
Visit http://localhost:8200 and see if it works.

**Comment by ts678** [comment]
> I only got Python 3.X installed.

["Duplicati needs to be updated" warning on upgrade to MacOS Monterrey 12.1 #4668](https://github.com/duplicati/duplicati/issues/4668#issuecomment-1048181164) warns of stub.
Regardless, the script is for 2, unless you convert it using `2to3`, per the directions you can find there.
There also might be a need to get `pyobjc` but you can see what you think. Lots of experiments tried.

> After installing Python 2.X additionally, it doesn't work either.

[MacOS Monterey 12.5.1 - Python 2.7 Not Found #4816](https://github.com/duplicati/duplicati/issues/4816#issuecomment-1287785110) offers a workaround using RUMPS_PYTHON.

**Comment by gpatel-fr** [comment]
@mhellmeier 

with Canary 106 (or upcoming beta not yet out), you should have a working tray icon, see

https://forum.duplicati.com/t/release-2-0-6-106-canary-2023-05-03/16219/10
