### ISSUE TITLE
TargetLocation ignored - Local Drive filled on unknown location

### ISSUE THREAD

**Issue by beatbesmer** [duplicati/duplicati#4914]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.104_canary_2022-06-15
- **Operating system**: Win11 x64
- **Backend**: Local folder or drive

## Description

A local attached USB drive is used as target Location. When starting a backup, my local Drive C: is filled. There aren't any Data on the TargetDrive choosen. 200 of 500 GB have been free on C: before starting the backup.

After rebooting the computer and restarting Duplicati, the Error "No filesets found on remote target" showes up.
Unfortunatelly, i'm not able to see a location used in any of Duplicatis Logs.

Two questions remains:
- Why does this not work using the GUI?
- Did Duplicati fill my drive C:, and if yes, where did it put those data?

## Steps to reproduce

1. Attach a USB Disc
2. Setup a Backup using the GUI (to check -> Open Backup -> CommandLine
Use: 
- Command: backup
- Target URL > file://G:\Duplicati\Nutzerdaten\
- Advanced Options (as text): 
- --all-versions=true
--retention-policy=2D:0s,1W:1D,4W:1W,12M:1M
--backup-name=Alle Nutzerdaten
--dbpath=C:\Users\MY_USER_NAME\AppData\Local\Duplicati\LWJBMHDWIQ.sqlite
--encryption-module=
--compression-module=zip
--dblock-size=800GB
--no-encryption=true
--disable-module=console-password-input
--exclude=%HOME%\VirtualBox VMs\
--exclude=%HOME%\Videos\
--exclude=%HOME%\Music\
4. Start Backup

But as soon as i start the same job as followed, it works and my external USB disk is used.
HOME -> <MyBackupJob> -> Commandline -> Button: Run "backup" command now

- **Actual result**:
C: Drive filled, no clue where Data went to
As result, the drive C: is filled and an error thrown (see Debug log)

- **Expected result**:
external USB-Disk used for Backup

## Screenshots

![image](https://user-images.githubusercontent.com/17173365/228796044-5f9826d6-f5c9-4b52-8f7b-5136ea02f2ca.png)
![image](https://user-images.githubusercontent.com/17173365/228798105-bba29e6f-4261-4cb7-ab8a-20beab929a2b.png)

## Debug log

```
System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei SharpCompress.IO.CountingWritableSubStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   bei SharpCompress.Compressors.Deflate.ZlibBaseStream.finish()
   bei SharpCompress.Compressors.Deflate.ZlibBaseStream.Dispose(Boolean disposing)
   bei System.IO.Stream.Close()
   bei SharpCompress.Compressors.Deflate.DeflateStream.Dispose(Boolean disposing)
   bei System.IO.Stream.Close()
   bei SharpCompress.Writers.Zip.ZipWriter.ZipWritingStream.Dispose(Boolean disposing)
   bei System.IO.Stream.Close()
   bei Duplicati.Library.Main.Volumes.BlockVolumeWriter.AddBlock(String hash, Byte[] data, Int32 offset, Int32 size, CompressionHint hint)
   bei Duplicati.Library.Main.Operation.Backup.DataBlockProcessor.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Duplicati.Library.Main.Operation.Backup.DataBlockProcessor.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CoCoL.AutomationExtensions.<RunTask>d__10`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Duplicati.Library.Main.Operation.BackupHandler.<RunMainOperation>d__13.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Duplicati.Library.Main.Operation.BackupHandler.<RunAsync>d__20.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei CoCoL.ChannelExtensions.WaitForTaskOrThrow(Task task)
   bei Duplicati.Library.Main.Controller.<>c__DisplayClass14_0.<Backup>b__0(BackupResults result)
   bei Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   bei Duplicati.Library.Main.Controller.Backup(String[] inputsources, IFilter filter)
   bei Duplicati.Server.Runner.Run(IRunnerData data, Boolean fromQueue)
```

**Comment by gpatel-fr** [comment]
>>--dblock-size=800GB

this is far too much, the default is 50MB. The fine manual states that 'Changing the size can be useful if the backend has a limit on the size of each individual file.', in other words, the dblock size is configurable to be reduced, not multiplied by 16000. Duplicati tries to create a enormous temporary file and it is filling your disk.

**Comment by beatbesmer** [comment]
@gpatel-fr thx, guess this was caused due a misunderstanding of my part (confused with a kind of max file size I guess). I re-read the 'blocks-part'. So In this case, I guess, the exception refers to the system disk, where the blocks are prepared, before they're uploaded. Maybe this exception can be catched and described for dummies like me ;)
So, I'll fix the size and try again asap...

**Comment by beatbesmer** [comment]
But can you tell me, where I have to 'clean" my disk? I had more than 100GB free, now there are some MB left.

**Comment by gpatel-fr** [comment]
Should be in the TEMP directory for your user account (probably Appdata\Local\Temp). For Windows you can use the free software Windirstat to check on used disk space. There are others programs like that but I liked this one.

**Comment by beatbesmer** [comment]
Indeed, thx @gpatel-fr . 130 GB more space available now 🥳 
So two question remains:
- shouldn't a "cleanup" process take care about those files, or at least inform the user about? a regular user might prefer to delete Duplicati and to complain about the waste of disc-space, instead of searching a solution online.
- Is the name "Remote volume size" and the short description below misleading only for me or also for others? Since I didn't take the time to read and understand the linked information, this value was erroneously increased to the "maximum available space in remote storage". Well, I was in "simple user mode" while setting up the backup.... and I think software that "takes the user by the hand" (and leaves as few questions as possible) is more likely to gain popularity. 
Just some thoughts for new Issues ;-)
