### ISSUE TITLE
[Feature request] Reduce bandwidth by checking hash before uploading / backing up

### ISSUE THREAD

**Issue by rudolphos** [duplicati/duplicati#4919]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Windows 10, 64bit, 19045.2788
- **Backend**: Box.com

## Description

Reduce bandwidth by comparing the hash value of a previously stored file with the hash value of a new version of the file.

Duplicati could store hash values of a previously backed up file, and if the file that must be backed up has the same hash, file isn't backed up because latest copy is unchanged and already is backed up. But if the hash does not match, Duplicati backs up this particular file.

**Comment by gpatel-fr** [comment]
Hello

what you want seems to be already implemented by Duplicati.

https://www.duplicati.com/articles/FactSheet/#technology-deduplication

**Comment by ts678** [comment]
Also read:

[Overview](https://duplicati.readthedocs.io/en/latest/01-introduction/#overview)
[Features](https://duplicati.readthedocs.io/en/latest/01-introduction/#features)
[The backup process explained](https://duplicati.readthedocs.io/en/latest/01-introduction/#the-backup-process-explained)
[How the backup process works](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/) especially [Processing similar data](https://duplicati.readthedocs.io/en/latest/appendix-a-how-the-backup-process-works/#processing-similar-data) where what you ask is done at a block level.
Other manual sections explain how Dupicati doesn't upload complete files, but the changed blocks of the file.
