### ISSUE TITLE
Can not access OneDrive with WebDAV while WinSCP can 

### ISSUE THREAD

**Issue by jonozw** [duplicati/duplicati#4922]
- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta
- **Operating system**: Windows 11
- **Backend**: WebDAV of OneDrive

## Description

I want to use WebDAV of Onedrive. According to the article [Connecting securely to Microsoft OneDrive with WebDAV](https://winscp.net/eng/docs/guide_microsoft_onedrive)
I can access OneDrive with WebDAV in WinSCP. But when I do the same operation in duplicati, it said that "The folder /ABCDEFGHIJKLMNOP  does not exist. Create it now?"

## Steps to reproduce

1. Add Backup
2. Complete General backup settings and next
3. Backup destination
    * Storage Type: WebDAV
    * Server and Port d.docs.live.net 443
    * Path On Server: /ABCDEFGHIJKLMNOP (According to https://winscp.net/eng/docs/guide_microsoft_onedrive)
    * Test Connection
5. Faild, the error message is "The folder /ABCDEFGHIJKLMNOP  does not exist. Create it now?"

- **Actual result**:
Faild, the error message is "The folder /ABCDEFGHIJKLMNOP  does not exist. Create it now?"
- **Expected result**:
Like WinSCP, can access OneDrive with WebDAV. 

## Screenshots

![图片](https://user-images.githubusercontent.com/30031941/231384038-2756f3a3-b029-4558-8617-68c25e3bd549.png)
![图片](https://user-images.githubusercontent.com/30031941/231384217-a3380ccc-02e2-4771-8857-6a6e9d29b620.png)

**Comment by gpatel-fr** [comment]
Hello

I think that Duplicati is doing what it has been intended to do.
Please read the documentation here
https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#creating-a-new-backup-job
Specifically the part about Backup destination.

**Comment by jonozw** [comment]
Thanks.
