### ISSUE TITLE
Not backing up on Samba Share

### ISSUE THREAD

**Issue by gordnhoo** [duplicati/duplicati#4934]
- [ x] I have searched open and closed issues for duplicates.
- [x ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Ubuntu 22.10/Docker
- **Backend**: ?

## Description
I mounted  a samba share on my friend's computer and he is able to delete,modify and execute files but when running duplicati he always gets acess denied and is unable to backup the files
## Steps to reproduce

1. Mount a samba share with this options on my friends computer //IPADDRESS/MOUNTNAME /smb_share cifs username=USERNAME,password=PASSWORD,iocharset=utf8,,file_mode=0775,dir_mode=0775,cache=none
2. Try to use duplicati to backup the file

- **Actual result**:
Acess denied
- **Expected result**:
Should just backup the files

**Comment by gordnhoo** [comment]
Just found out I can backup from duplicati installed from a .Deb package there must be an issue with permissions and docker does anyone know what this could be

**Comment by mr-russ** [comment]
Does duplicati run as the same user in docker?
