### ISSUE TITLE
Error in Duplicati -EVP_MD_size assembly:<unknown assembly> type:<unknown type> member:(null)- whats that

### ISSUE THREAD

**Issue by Caligo2310** [duplicati/duplicati#4941]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 0.0.0.0
- **Operating system**: Replace me
- **Backend**: Replace me

## Description

Replace me

## Steps to reproduce

1. Replace me
2. Replace me
3. ...

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by Caligo2310** [comment]
This error is not new but nobody helps. ubuntu 23.04
Duplicati is usable - why??

**Comment by gpatel-fr** [comment]
Hello @Caligo2310 

The form that you are asked to fill is here to provide useful information to reproduce problems. If you can't explain your problem in any detailed way, I'd suggest you go to the [forum](https://forum.duplicati.com) .
