### ISSUE TITLE
Older backup files I need exist in AWS Compatible, but never get created in database.

### ISSUE THREAD

**Issue by RickkeeC** [duplicati/duplicati#4942]
- [x ] I have searched open and closed issues for duplicates.
- [x ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.6.3_beta_2021-0617
- **Operating system**: Win1022h2
- **Backend**: Wasabi

## Description
I see dead people.
Trying to get to very old version of backups, but the local database, and attempt to restore directly from Wasabi only show a few months.  Thousands of files exist with older dates like duplicati-b00def39caa534ddb9edcb452ae0da6ce.dblock.zip.aes  12/24/2019 4:00 PM.  

Is there any way to download, catalog, recover these seemingly orphaned backups?

## Steps to reproduce

1.  Setup backup, let it run a few years, then try to restore older files.

- **Actual result**:
Only a few months are restorable.  Did I screw it up by trying to recreate the database?
Even so, hundreds of gigs of older files exist.
Replace me
- **Expected result**:
Ability to recover from the old backup files.

## Screenshots

![dupli-wasabi](https://github.com/duplicati/duplicati/assets/40076667/0d0b19f2-1812-4775-ad2d-4c2be210d309)

**Comment by gpatel-fr** [comment]
Hello @RickkeeC 

Your information does not point to a specific bug that could be tracked, isolated and fixed. I'm afraid that it's not even possible to do that. For general help on recovering old data, you could ask on the forum instead. To cut short on your time, if you have only dblock files and no old dlist files it's practically not worth trying to recover information unless it is the secret to access a treasure since dlist files are the catalog.

**Comment by ts678** [comment]
[There is lots of junk in my bucket](https://forum.duplicati.com/t/there-is-lots-of-junk-in-my-bucket/16276) was the related forum topic. I hope that clarified how a block based deduplicated backup works.
Chosen 14 day retention removes old file listing and reassembly details. Some data blocks are used in new files. Others are waste.

> Only a few months are restorable.

conflicts with the 14 day retention mentioned on the forum topic though, but maybe some backup got a longer retention setting.
Database recreate uses the destination files (ideally just dlist and dindex). If retention deletes old dlist files, they're not recoverable.
