### ISSUE TITLE
Google Drive backups failing with 429 error for larger backups

### ISSUE THREAD

**Issue by georgfranz** [duplicati/duplicati#4944]
I'm experiencing an issue with Duplicati when trying to backup larger amounts of data to Google Drive. The backup works fine for smaller data sizes, but fails when attempting to backup larger amounts of data (around 180GB in my case).

The process fails with a 429 error from Google Drive after transferring around 1-2GB of data. According to Google's documentation, this error code signifies "Too Many Requests" and suggests that the user should wait and then retry the operation. Additionally, Google Drive has a daily upload limit of 750GB.

It seems that Duplicati doesn't handle these error responses from Google Drive in a way that allows the backup to continue successfully. It would be beneficial if Duplicati could implement a mechanism to manage these errors more effectively, perhaps by pausing and retrying the backup after a specified interval when a 429 error is received. This could allow the backup to continue without user intervention and respect Google Drive's daily upload limit.

Steps to reproduce:

Configure Duplicati to backup to a Google Drive destination.
Set up a backup that includes a large amount of data (in my case, 180GB).
Start the backup process.
Observe that the backup fails with a 429 error after transferring around 1-2GB of data.
Expected behavior:

Duplicati should handle 429 errors from Google Drive by pausing and retrying the backup after a delay, allowing the backup to continue without user intervention and respecting Google Drive's daily upload limit.

Actual behavior:

Currently, Duplicati fails the backup when a 429 error is received from Google Drive and does not attempt to retry the operation.

I would be happy to provide additional information if needed.

Thank you for your attention to this matter.

**Comment by gpatel-fr** [comment]
Hello

From what I can read, 429 error on Google Drive does mean that the access is rate limited, not that the daily maximum size has been reached. You even say that the limit is 750 GB and you get an error after 1-2 GB ! That can't be the reason.

You can try to play with:
https://duplicati.readthedocs.io/en/latest/06-advanced-options/#throttle-upload
https://duplicati.readthedocs.io/en/latest/06-advanced-options/#concurrency-max-threads

to make Duplicati less aggressive in uploading data.

It may be the case that you are trying to use a plan that your provider has designed for casual file storing to do backups, a possibility that they may prefer to reserve for more expensive options.

**Comment by georgfranz** [comment]
Hi,

thanks for you answer!

Yes - I didnt hit the 750GB rate limit. I just mentioned that because thats kind of a hard limit for google drive business.

Yes, I have also tried your suggested settings. I set concurrency threads to 1 and limit the upload speed to various settings. No difference, still is failing.

If Duplicati does not have a built-in mechanism for handling HTTP 429 error responses by delaying and retrying the operation, then it would likely continue to fail in the same manner, even with adjustments to the upload speed or the number of concurrent threads.

I read the documentation settings and found:
number-of-retries
retry-delay

I havent altered that, so I will try to increase this.

Best,
Georg.

**Comment by georgfranz** [comment]
I have found settings to complete the backup with google drive:

![image](https://github.com/duplicati/duplicati/assets/366371/d0c8aba3-4b46-4355-9752-5ab6542df15e)

asynchronous-upload-limit: 1
number-of-retries: 10
retry-delay: 60 (seconds)
throttle-upload: 3 mbytes

I still would be happy if the 429 status would not be handled as "unexpected status". 

But currently it works - tx!

Best,
Georg.
