### ISSUE TITLE
0 files (0 bytes) to go on Windows

### ISSUE THREAD

**Issue by m-primo** [duplicati/duplicati#4947]
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.3_beta_2021-06-17
- **Operating system**: Windows 11
- **Backend**: Replace me

## Description

Data shows 0 while uploading in Windows.
It's still the same way for every backup and every run.
It's also happening after verifying the files (while actually uploading not processing).

## Steps to reproduce

Just run any upload and you will see.

- **Actual result**:
0 files (0 bytes)
- **Expected result**:
n files (n bytes)

## Screenshots

![image](https://github.com/duplicati/duplicati/assets/44984918/600dd8d4-ba20-4614-a6d7-b451ac90b8af)

**Comment by m-primo** [comment]
> Hello
> 
> Does the backup eventually terminates ? if not, if you go to the real time windows (about / show log / Live) do you see activity when this is happening ?

No, it doesn't terminate, it works properly.
I don't know which activity exactly but i get this

```
May 22, 2023 7:40 AM: Cannot find any MS SQL Server instance. MS SQL Server is probably not installed
```

and some events of the backup process like completed:

```
The operation Backup has completed
Backend event: Get - Completed: duplicati
```

**Comment by gpatel-fr** [comment]
I'm not quite sure of what you mean.  Maybe it's because both of us have english as a secondary language ?
For me 'terminate' means finish normally. But you say that it don't, and it works properly. Could it be that you mean 'abort', 'end abnormally' when you say 'terminate' ?

Re: warning about MS SQL, possibly you set an option concerning MS SQL and there is no MS SQL server found in your setup ?

The 2 lines you are showing from the live log seem normal and show that the backup has effectively finished.
So it seems that what you are complaining concerns exclusively the fact that some Duplicati messages are confusing, rather than a straight bug ?

**Comment by m-primo** [comment]
> I'm not quite sure of what you mean. Maybe it's because both of us have english as a secondary language ? For me 'terminate' means finish normally. But you say that it don't, and it works properly. Could it be that you mean 'abort', 'end abnormally' when you say 'terminate' ?

I thought by terminate, you meant that the backup stopped in the middle and didn't complete.
But to clarify, the backup works 100% properly, no errors, no anything.. it just shows  0 files (0 bytes) in the topbar all the time.


> Re: warning about MS SQL, possibly you set an option concerning MS SQL and there is no MS SQL server found in your setup ?

I don't think I have anything that is related to MS SQL at all, or even an option related to it.


> The 2 lines you are showing from the live log seem normal and show that the backup has effectively finished.

The issue I'm reporting is not related to whether the backup was completed or not, as it shows "0 files (0 bytes)" all the time during the backup.

**Comment by gpatel-fr** [comment]
All the time is indeed surprising. Maybe it's a special problem for your backend (is it Backblaze ?)

**Comment by m-primo** [comment]
> All the time is indeed surprising. Maybe it's a special problem for your backend (is it Backblaze ?)

That's what I thought at first, but it happens for the other backends.
And it's not happening on the other server (which is Linux)..

That's why in the title of the issue I mentioned Windows.

**Comment by gpatel-fr** [comment]
Maybe it's Windows 11. I have only installed a Win11 VM recently to test Duplicati, and it's a major pain to do anything on it as it's horribly slow. I'm not sure to have seen on the forum a post reporting experience with Win 11.

**Comment by gpatel-fr** [comment]
Well just tested a backup setup with Alternate FTP on a Win11 Vm and I see a non zero amount to transfer so I can't confirm.
Could you try to export your backup (uncheck password option), edit it to remove identifying information such as user name and server name, and attach it here ?

**Comment by m-primo** [comment]
[B2_DESK-duplicati-config.zip](https://github.com/duplicati/duplicati/files/11549522/B2_DESK-duplicati-config.zip)

btw, I have tried to restart my PC and Duplicati itself and still the same..
I tried to run multiple backups (different backends & backups), the amount and transfer are shown correctly for minutes and then stuck at a fixed amount until the backup finish.

This screenshot was taken just now, and the amount was displayed correctly for only a few minutes before becoming stuck.
![image](https://github.com/duplicati/duplicati/assets/44984918/50d6c45a-3c70-453d-8471-bd237ee8d8e5)

**Comment by gpatel-fr** [comment]
Hello

the config don't show something specially interesting except the error message: your backend seems a bit in trouble (found 9 remote files not recorded), it could be an indication of something problematic in your setup / backend. Maybe try the test-backend command:
https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/#duplicaticommandlinebackendtesterexe

**Comment by m-primo** [comment]
> found 9 remote files not recorded

Yeah, I know about this error, I think it happens when I import the metadata or something.
Still, it has nothing to do with the stuck issue, because as I said it happens for every backup and every backend.

**Comment by ts678** [comment]
I think this line is constructed by the JavaScript below (and more above it that's not shown), and it would be worth doing an
About --> System info to especially grab `lastPgEvent` which overflows, so maybe grab whole screen and paste in notepad.

https://github.com/duplicati/duplicati/blob/8fad3ed5d01a56f11fe66769e365aea9489e86ee/Duplicati/Server/webroot/ngax/scripts/controllers/StateController.js#L52-L53

You can also open web developer tools (often F12 in browser) to see `progressstate` requests occur about every 2 seconds.
Looking inside should show numbers similar to those in `System info`. Is it still polling well, yet getting some wrong values?

Is there a simple network path from browser to Duplicati? Ideal would be that you're going to localhost on the same system.
Does this glitch occur if you try the simplest possible fewest-optioned backup you can, e.g. a short file into some local folder?

**Comment by ts678** [comment]
> But to clarify, the backup works 100% properly, no errors, no anything.. it just shows 0 files (0 bytes) in the topbar all the time.

So never says anything like the below? That seems very odd. What browser are you using? Any special configs? Tried any others?

https://github.com/duplicati/duplicati/blob/8fad3ed5d01a56f11fe66769e365aea9489e86ee/Duplicati/Server/webroot/ngax/scripts/services/ServerStatus.js#L33-L44

https://github.com/duplicati/duplicati/blob/8fad3ed5d01a56f11fe66769e365aea9489e86ee/Duplicati/Server/webroot/ngax/scripts/controllers/StateController.js#L24-L29

**Comment by m-primo** [comment]
> and it would be worth doing an
> About --> System info to especially grab `lastPgEvent` which overflows

`lastPgEvent` shows nothing!

**Comment by m-primo** [comment]
> What browser are you using?
Google Chrome

> Any special configs?

I don't understand? What special config?

> Tried any others?

Nope

**Comment by gpatel-fr** [comment]
@m-primo 

the special config is the particular options added to the backup. You have already posted an export of your config and the few options you added (removing encryption, block of 200MB...) are not obviously wrong.
However what you say is not fully clear as to what happens, and @ts678 is right to ask questions.

What you could try is to open 2 tabs on Duplicati, one for starting the backup, and one for examining what is done when it is blocking (this is not strictly necessary if you wait for the start of an automatic backup, but it's easier when you want to do a quick test at a convenient time). In this second tab, go to About / Show log / Live and select 'information'. Then when the backup is started on the first tab, switch to the second tab and observe when it is stuck. After the backup is finished, copy the shown log and paste it here, add a marker when the problem occurs (insert a line with an arrow for example) and paste it here.

**Comment by ts678** [comment]
> lastPgEvent shows nothing!

That suggests that it's actually done, but the status bar hasn't noticed, perhaps if its polling stopped. Press F12 to look at those, although pressing it at some time when backup is still running (yet status bar isn't) would be more interesting. Tray Icon polls as well, e.g. it turns green when backup is running, and returns to black if things are done and normal. Any observations on yours?

In the GUI, have you tried the Chrome refresh button to see if status bar info gets updated, gets exactly old text, is empty, etc.?

The suggested live log will show uploads, and an upload should start or raise the speed in status bar. It goes down between the uploads because it's an average. In a case like screenshot [above](https://github.com/duplicati/duplicati/issues/4947#issuecomment-1560325357), does the speed slowly decline even if the counts to the left are stuck? That means poll is running. Keeping an eye on lastPgEvent and other status (e.g. activeTask) should also add information.

**Comment by gpatel-fr** [comment]
Given what I have seen recently with Duplicati, I think that the backup could have problems with TLS 1.3.
It could be interesting to add the extended option
ssl-allowed-version
and set it to TLS 1.2 only (disable system default option)
