### ISSUE TITLE
Error with Infomaniak Swissbackup cluster 3

### ISSUE THREAD

**Issue by celestelium** [duplicati/duplicati#4953]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.1_beta_2023-05-25
- **Operating system**: Windows 11 22H2
- **Backend**: Infomaniak Swissbackup cluster 3 (OpenStack Swift)

## Description

(i don't spreak English et i use a translator for this text)

Hello,

I use Duplicati to backup my computer to a SwissBackup storage space from Infomaniak and since version _2.0.7.1_beta_2023-05-25_, the connection to the server systematically fails and returns an error 502: Passerelle Incorrecte.

- I get this error on cluster 3, but also on cluster 2. On the other hand, I don't have this problem on cluster 1.
- This problem disappears when I upgrade to version 2.0.6.3_beta_2021-06-17.

I've tried several things that didn't work:
- I used 2 internet connections (fixed and 4G)
- I disabled the firewall
- I uninstalled and reinstalled the software several times
- I changed the DNS

I'm a bit overwhelmed, and that's why I'm posting this ticket about this problem that appeared via the update.

## Steps to reproduce

1. Add Backup
2. Configure a new backup
3. Skip step 1
4. Backup Destination 
- **Storage Type :** OpenStack Object Storage / Swift
- **Bucket Name :** random
- **OpenStack AuthURI :** Infomaniak Swiss Backup cluster 3 (https://swiss-backup03.infomaniak.com/identity/v3)
- **Domain Name :** random
- **Username :** random
- **Password :** random
- **Tenant Name :** random
5. Test connection

- **Actual result**:
 Failed to connect: Le serveur distant a retourné une erreur : (502) Passerelle incorrecte. 
- **Expected result**:
Connection Worked!

## Debug log

```Jun 2, 2023 10:07 PM: Reporting error gave error

System.ObjectDisposedException: Impossible d'écrire dans un TextWriter fermé.
   à System.IO.__Error.WriterClosed()
   à System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   à Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
```
```Jun 2, 2023 10:07 PM: Request for http://localhost:8200/api/v1/remoteoperation/test gave error

System.Net.WebException: Le serveur distant a retourné une erreur : (502) Passerelle incorrecte.
   à System.Net.HttpWebRequest.GetResponse()
   à Duplicati.Library.Backend.OpenStack.OpenStackStorage.GetKeystone3AuthResponse()
   à Duplicati.Library.Backend.OpenStack.OpenStackStorage.get_SimpleStorageEndPoint()
   à Duplicati.Library.Backend.OpenStack.OpenStackStorage.<List>d__44.MoveNext()
   à Duplicati.Library.Interface.BackendExtensions.TestList(IBackend backend)
   à Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)
   à Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)
```

**Comment by gpatel-fr** [comment]
Thanks for the report. I have never tested with Openstack and I see that Infomaniak does not provide a fully free access for testing, it's a 3 month trial. Since you use it, is it possible to use the 3 month trial without providing credit card info ? It's not that I don't trust Infomaniak especially, I trust no one when it comes to cancel a subscription - easy to do, not always to undo unfortunately.
The error message you see - bad gateway - seems related to a server name issue more than a code problem by itself. The more so because you said that it works with one server name.
However, the working version for you (2.0.6 beta) did not include the Infomaniak servers names, it was added later, so I wonder how you did set up at the time - did you set the server name by hand  as a custom server ? Do you have the URL on the Infomaniak site on how to setup the API endpoint (server name) ?

**Comment by celestelium** [comment]
Hello and thank you for your reply.

At the time, I had configured the Openstack server manually, but the new version actually proposes the address of the Infomaniak cluster I use and sets it automatically.

I've tried setting the address manually but the problem persists. For configuration, Infomaniak provides a tutorial for configuring Duplicati with their service: https://faq.infomaniak.com/2355

However, you don't need to have any login or an Infomaniak account to see the bug appear, it even manifests itself with any bogus login. It's really a problem before authentication.

The two things that are surprising are that :
- the problem only manifests itself with these three specific addresses, all the others work normally:
![204nPvZiNd](https://github.com/duplicati/duplicati/assets/6538146/1e5b4125-8b4c-4658-ab21-58202ddb4549)
- I don't have this problem with my other Windows 10 computer. 

I'm always unlucky enough to come across the most specific and strange bugs and problems, but insofar as it's blocking my backups, this one is more annoying than the others...

**Comment by gpatel-fr** [comment]
I'm beginning to suspect that there could be a nasty incompatibility between current Duplicati and recent Windows versions (11 to name it). Could you try this experimental build ?

https://github.com/duplicati/duplicati/actions/runs/5168369542#artifacts

**Comment by celestelium** [comment]
I tested the build you sent me but the problem is still there.

**Comment by gpatel-fr** [comment]
That's strange on a Win11 Vm and this version, I see a 401 error not authorized. Are you sure the upgrade was effective ? In the 'About' function, do you see Duplicati - 2.0.7.3_canary_2023-06-04 ?
Note that I created an account but it is effectively asking for a credit card for doing anything, so I did no testing other than clicking on 'Test connection'.

**Comment by celestelium** [comment]
Unfortunately, I still have this problem on version Duplicati - 2.0.7.3_canary_2023-06-04 : 
![B7tqY5WXzp](https://github.com/duplicati/duplicati/assets/6538146/9d19db22-edf4-4fb2-b0e2-09d39a6d5a3f)

Out of curiosity, I tested the latest version of Duplicati in virtual machines on the problematic PC and it works with Debian and Windows 10. But on a Windows 11 VM, the problem persists.

I'd really like to get to the bottom of this witchcraft. 
(I'm not sure this sentence will translate correctly...)

**Comment by gpatel-fr** [comment]
If with Duplicati 2.0.7.1 beta I force ssl version to TLS 1.2, I get 401 error with swiss-backup03 (allowed-ssl-version set to *only* tls 1.2)

**Comment by celestelium** [comment]
Yes, it works again by forcing TLS 1.2. I have the solution to make my backups work on the latest version of Duplicati. Thanks for the help!

But is the problem linked to a TLS problem at Infomaniak or to the changes made to Duplicati's Openstack support?

**Comment by gpatel-fr** [comment]
2 things are certain: there is no recent change in Duplicati Openstack support. There should be TBH but it's rather static these days. 
The other certain thing is that TLS 1.3 is only possible with Windows 11. The support provided by .NET goes through the OS stack (unless one uses a specific library, and that's not the case with Openstack driver), and Win 11 is the first Microsoft OS to support it. There are words said about the TLS 1.3 support of Win11 being second rate though, so I'll not be quick to say that Infomaniak is the culprit.

**Comment by gpatel-fr** [comment]
I think that what you can do for future Duplicati updates is trying them and do good (precise) problem reports if you see any regression.
Thanks for closing the issue.

**Comment by celestelium** [comment]
Okay, thanks again for the help.
