### ISSUE TITLE
Make the pause/resume functions work during file list creation.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#496]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on October 28, 2011 10:30:16_

The listing of files can take a long time, it is reasonable to think that the user would want to pause during this operation.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=496_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
