### ISSUE TITLE
`Storage Type` change does not delete previous `Storage Type`: `mega` settings

### ISSUE THREAD

**Issue by yiyungent** [duplicati/duplicati#4963]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: `2.0.6.106_canary_2023-05-03`
- **Operating system**: `Microsoft Windows 10 Pro 22H2 (64 bit)`
- **Backend**: `mega` -> `rclone`

## Description

I used the mega storage type before, but changed it to rclone later, and found that the previous settings are still preserved. As long as I switch back to mega, I will find that the previous settings for mega are preserved, which leads to invalid parameter warnings

![image](https://github.com/duplicati/duplicati/assets/16939388/cb2ee7ee-2a93-455a-9db2-ee264aa8994f)
![image](https://github.com/duplicati/duplicati/assets/16939388/ef1c321a-30a8-42ed-8707-8dd1a806270b)

You can find the parameters for `mega` in `Advanced` -> `Commandline` -> `Target URL`

![image](https://github.com/duplicati/duplicati/assets/16939388/ec0c6f45-4219-4189-b9fe-c84b8af89930)

## Steps to reproduce

1. `Add backup` -> `Storage Type` : `mega`,  fill in the necessary settings, save
2. `Configuration` -> `Edit` ->  `Storage Type`: `rclone`,  fill in the necessary settings, save
3. `Run now`

- **Actual result**:

![image](https://github.com/duplicati/duplicati/assets/16939388/ef1c321a-30a8-42ed-8707-8dd1a806270b)

- **Expected result**:

Without warning, the previous configuration for mega was removed

**Comment by ts678** [comment]
Isn't this a duplicate of [Changing backend type leaves invalid backend options #3082](https://github.com/duplicati/duplicati/issues/3082)? If so, there's no need to keep this open.
The workaround is there too, until someone who does JavaScript can go work on what I presume could be handled to achieve:

> Without warning, the previous configuration for mega was removed

which was the `Expected result`. Basically the preference here is to quietly toss old settings when abandoning a storage type.
This seems a smoother flow to me, and simpler than either warning or inventing some complex dialog on what things to keep.

**Comment by yiyungent** [comment]
Thanks！
