### ISSUE TITLE
Sending e-mail works on command line, not in backup job

### ISSUE THREAD

**Issue by markcharlesobrien** [duplicati/duplicati#4966]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.1_beta_2023-05-25
- **Operating system**: MacOS Monterey 12.5
- **Backend**: SFTP

## Description

Trying for three days to get e-mail notifications working on Duplicati. Very frustrated. Found somewhere on the internet, I can use the following command line to test if e-mail notifications are correctly configured, and it works:

`/Applications/Duplicati.app/Contents/MacOS/duplicati-cli send-mail 
--send-mail-password="[my password]"
--send-mail-to="[my destination address]" 
--send-mail-username="[e-mail provider username]" 
--send-mail-url="smtp://smtp.migadu.com:587/?starttls=when-available" 
--send-mail-from="[my sender address]" 
--verbose 
--log-level=profiling`

When I then copy the relevant options into my Duplicati settings, as follows:

`--send-mail-to="[same destination e-mail address]"
--send-mail-from="[same sender address]"
--send-mail-url=smtp://smtp.migadu.com:587/?starttls=when-available
--send-mail-password=[my password]
--send-mail-any-operation=true
--send-mail-level=all
--send-mail-username="[same e-mail provider username]"`

I get the following error and no e-mail is sent:

`2023-06-14 13:30:51 -04 - [Warning-Duplicati.Library.Modules.Builtin.ReportHelper-ReportSubmitError]: Failed to send message: MailKit.Security.AuthenticationException: 535: 5.7.8 Error: authentication failed: VXNlcm5hbWU6 --> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Error: authentication failed: VXNlcm5hbWU6`

This is frustrating because it's the exact same options and exact same usernames/server names/e-mail addresses and password and yet it works in one place and doesn't work in the other. I'm probably doing something wrong by assuming that the same options work in two places, but I don't know.

I searched here and on the forum and I only found people using GMail or Office 365 for their email and the solutions don't apply (for instance, there is no "less secure" option at my e-mail provider as there is at GMail). Also, I can't find any issue or forum post where the CLI mail test works but it doesn't work in the Duplicati options.

Also, I am not a coder, so if you are going to reply "just pull a PR and fix it yourself," I can't. I know that some open-source projects require people with problems to change the source code themselves.

## Steps to reproduce

1. Run the first code block. You will receive a test e-mail from Duplicati.
2. Put the second code block in the Duplicati options and run a backup. The Duplicati web interface will respond "2023-06-14 13:30:51 -04 - [Warning-Duplicati.Library.Modules.Builtin.ReportHelper-ReportSubmitError]: Failed to send message: MailKit.Security.AuthenticationException: 535: 5.7.8 Error: authentication failed: VXNlcm5hbWU6 --> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Error: authentication failed: VXNlcm5hbWU6"

- **Actual result**:
"2023-06-14 13:30:51 -04 - [Warning-Duplicati.Library.Modules.Builtin.ReportHelper-ReportSubmitError]: Failed to send message: MailKit.Security.AuthenticationException: 535: 5.7.8 Error: authentication failed: VXNlcm5hbWU6 --> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Error: authentication failed: VXNlcm5hbWU6"
- **Expected result**:
An e-mail with details of the backup.

## Debug log

```Jun 14, 2023 1:30 PM: The operation Backup has completed
Jun 14, 2023 1:30 PM: Failed to send message: MailKit.Security.AuthenticationException: 535: 5.7.8 Error: authentication failed: VXNlcm5hbWU6 --> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Error: authentication failed: VXNlcm5hbWU6
Jun 14, 2023 1:30 PM: Whole SMTP communication: Connected to smtp://smtp.migadu.com:587/?starttls=when-available S: 220 mta1.migadu.com ESMTP C: EHLO [192.168.1.198] S: 250-mta1.migadu.com S: 250-PIPELINING S: 250-SIZE 52428800 S: 250-ETRN S: 250-STARTTLS S: 250-ENHANCEDSTATUSCODES S: 250-8BITMIME S: 250-DSN S: 250 CHUNKING C: STARTTLS S: 220 2.0.0 Ready to start TLS C: EHLO [192.168.1.198] S: 250-mta1.migadu.com S: 250-PIPELINING S: 250-SIZE 52428800 S: 250-ETRN S: 250-AUTH PLAIN LOGIN S: 250-AUTH=PLAIN LOGIN S: 250-ENHANCEDSTATUSCODES S: 250-8BITMIME S: 250-DSN S: 250 CHUNKING C: AUTH PLAIN ACJkdXBsaWNhdGlAdW5jb21tb25lcGhlbWVyYS5vcmciAG5RNGNEQkh2Tlg3NTNrbkRBb1RwcVpnOG1zcDlvWA== S: 535 5.7.8 Error: authentication failed: C: AUTH LOGIN S: 334 VXNlcm5hbWU6 C: ImR1cGxpY2F0aUB1bmNvbW1vbmVwaGVtZXJhLm9yZyI= S: 535 5.7.8 Error: authentication failed: VXNlcm5hbWU6 ```

**Comment by Jojo-1000** [comment]
Are you using the web UI when specifying the options? I think you don't need the quotes there, so they might be included in the username and password instead  (if you enter them using the text fields, no quotes are added). You could try and remove them to see if that helps.

**Comment by markcharlesobrien** [comment]
I removed them and now it works.

Which bothers me, because I have copied this stuff before from the test command line and removed quotes and it never worked before. Sometimes I just have to bother someone, lol. Thanks.
