### ISSUE TITLE
Github sponsors?

### ISSUE THREAD

**Issue by aslilac** [duplicati/duplicati#4987]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

Hey there!

Not really a bug, much more meta. Just wasn't sure if there was a better avenue to bring it up.

Have you all considered opening up Github sponsors donations? The cut they take is pretty small relative to lots of similar platforms. Also, I'm lazy and I'd love to start donating (Duplicati is v cool 💕) but would rather keep it on a platform I'm already using.

**Comment by kenkendk** [comment]
Thanks for requesting this. I have sent in an application to be sponsored.

**Comment by kenkendk** [comment]
Thanks for your request. [Duplicati is now backed by Duplicati Inc](https://forum.duplicati.com/t/introducing-duplicati-inc/17491/48), so donations are not possible.
