### ISSUE TITLE
Docker container cannot find source files

### ISSUE THREAD

**Issue by antgustech** [duplicati/duplicati#4995]
- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
Debian, docker

## Description
I have the following docker configuration in my file system:
/home/user/docker/homeassistant
/home/user/docker/duplicati
/home/user/docker/pihole

In my docker-compose file, I have mapped the source directly to my home dir like this:

`

version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - CLI_ARGS= #optional
    volumes:
      - /home/user/docker/duplicati/duplicati_config:/config
      # - /path/to/backups:/backups  local backup storage
      - /home/user/docker:/source
    ports:
      - 8200:8200
    restart: unless-stopped

`

Even so, no files seem to appear in duplicati gui:

![Capture](https://github.com/duplicati/duplicati/assets/8721113/edd4239d-1011-49c0-b421-0f2ce829cadd)

- **Actual result**:
No files
- **Expected result**:
Files

**Comment by martadinata666** [comment]
I saw the `source` path (9 lines from the bottom) you bind to, where do you expect the folder to be?
