### ISSUE TITLE
When Duplicati is idle mono-sgen64 uses 20-30% cpu

### ISSUE THREAD

**Issue by fwh-dc** [duplicati/duplicati#5002]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.1_beta_2023-05-25
- **Operating system**: MacOS Ventura 13.4.1 (c)
- **Backend**: 

## Description

After updating to 2.0.7.1_beta_2023-05-25 mono-sgen64 uses 20-30% cpu when Duplicati is idle. Is there a way to prove that Duplicati is the culprit?

## Steps to reproduce

Happens consequently and even after a reboot.

- **Actual result**:
Replace me
- **Expected result**:
Replace me

**Comment by cityrolr** [comment]
I experience exactly the same issue on macOS 13.5 (22G74) and the only way to stop is to kill Duplicati.
![Screenshot 2023-08-02 at 22 04 43](https://github.com/duplicati/duplicati/assets/13933169/8992699a-773b-45cc-bebf-ff6237290d29)

**Comment by gpatel-fr** [comment]
Hello, please read

https://forum.duplicati.com/t/issues-after-upgrading-to-v2-0-7-1/16429/2

**Comment by fwh-dc** [comment]
Hi,

Thanks a lot!

After locating the correct python installation I was able to fix my issue as you describe in the forum page. I see it more as a workaround, shouldn't Duplicati resolve such dependencies during installation?

**Comment by gpatel-fr** [comment]
Yes, it's a workaround. There is not much workforce available to make work it better.
