### ISSUE TITLE
 Issue of Not Reflecting VeraCrypt Encrypted Volumes in Duplicati

### ISSUE THREAD

**Issue by veridiano007** [duplicati/duplicati#5008]
**Description:**

I would like to report an issue I have been facing while using Duplicati in conjunction with VeraCrypt-encrypted volumes. Duplicati is not reflecting the changes made in the encrypted volumes to the destination file, even after performing backups. This situation has raised concerns about the security and reliability of the integrity of my backups.

**Problem Details:**

- **Scenario:** I am using Duplicati to back up VeraCrypt-encrypted volumes to a destination, such as Google Drive.
- **Problem:** After performing backups, I noticed that changes made in the encrypted volumes are not being reflected in subsequent backups. In other words, backups seem to contain only the original files within the volume, without the latest changes.
- **Backup Settings:** I have checked my backup settings in Duplicati and confirmed that VeraCrypt volumes and relevant folders are correctly selected for backup.
- **Backup Execution:** Backups are being executed as scheduled, and Duplicati does not report any apparent errors or issues during the backup process.
- **Other Considerations:** I made sure that incremental or differential backup options are enabled, to capture only changes in files.

**Reproduction Steps:**

1. Create a VeraCrypt-encrypted volume.
2. Configure Duplicati to back up this encrypted volume to a destination, such as Google Drive.
3. Make changes to files within the encrypted volume.
4. Execute the backup in Duplicati.
5. Verify the resulting backup file to confirm whether changes were properly reflected.

**Expected:**
After performing the backup, changes made to files within the encrypted volume should be reflected in the resulting backup file.

**Observed:**
Changes made to files within the encrypted volume are not being reflected in the resulting backup file in Duplicati.

**Comment by NickPyz** [comment]
Duplicati works perfectly for me with a VeraCrypt volume. It correctly backs up all files - **as long as the volume is mounted (unencrypted) at the time of the scheduled backup job.** 

I can't imagine Duplicati can see the contents of a dismounted volume, which might explain the OP's problem.

In my case, I run the Duplicati backup in the middle of the night. I run a script to dismount the volume just after the scheduled backup job occurs.

**Comment by ts678** [comment]
> I can't imagine Duplicati can see the contents of a dismounted volume, which might explain the OP's problem.

It might also produce larger backups. I don't know. Ordinarily Duplicati uploads changed blocks in changed files.
I don't use Veracrypt, but making the container appear unchanged is a security feature. To backup, [disable that](https://steveshank.com/cgi-bin/article.pl?aid=787)?
If you really don't want your container to have a new timestamp when you change something inside, read here:
[No incremental backups of VeraCrypt file containers #2332](https://github.com/duplicati/duplicati/issues/2332) and note performance impacts of no timestamp use.
