### ISSUE TITLE
--symlink-policy=Store doesn't work, symlinks are followed anyway

### ISSUE THREAD

**Issue by muncrief** [duplicati/duplicati#5012]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.2
- **Operating system**: Arch Linux
- **Backend**: Local folder

## Description

When I set the symlink-policy to "Store" symlinks are followed anyway, and everything in their target directory is backed up. According to everything I could find "Store" should only backup and restore the symlink and it's target pathname, not the files in the target directory.

One symptom of the problem is that when you're defining backup sources and select a directory symlink everything in the target directory is selected as well, and then if you deselect everything in the target directory they're simply added as exclusions. However if something else is later added to the target directory it will be included in the next backup because it hasn't been manually excluded.

So the "Store" symlink-policy is acting just like the "Follow" policy. What should happen with "Store" is that when you select a symlink nothing underneath it should be selected, and the files in the target directory should not be backed up.

This is critical for people like me who have many disks with symlinks to them in other primary directories. For example, my home server has 11 TB of data, spread across 4 disks, with many symlinks not only from a primary directory, but also among the disks themselves. So it would be very difficult, if not impossible, for me to restore my system without the symlinks because many programs, including systemd and other boot operations, depend upon the symlink structure. 

## Steps to reproduce

1. Create a test backup with the Default option symlink-policy set to "Store".
2. Add a symlink to the sources.
3. Run the backup.

- **Actual result**:
The symlink target directory data is backed up.
- **Expected result**:
Only the symlink and it's target pathname should be backed up.

**Comment by gpatel-fr** [comment]
Hello

a quick test has not backed up a symlinked directory. I tried to delete the symlink and restore it and it was not restored, though.

If you enable logging at the Verbose level do you see (like I do) the message 'Stored symlink" ? 
(you have probably better to log to a file since verbose is just that, very verbose, and in the Live log you could miss it easily).

**Comment by muncrief** [comment]
I never tried to restore the symlink because the entire directory was backed up, and I kept searching the internet and forums for a solution because I was sure I was doing something wrong. Unfortunately I deleted all the backup files between tests, and wasn't convinced it was a bug until after the last test and searching some more. 

However I'm hoping to be able to use Duplicati and rclone instead of CrashPlan so I'm going to be running a lot of tests, with symlink tests first. And now that I know this is indeed a bug I'll turn on verbose logging and be ready to take screenshots if necessary.

But first I have to do raw rsync backups of 12 TB of data (including my workstation) as CrashPlan is no longer an option and I have to rely on temporary local backups until I can get a cloud solution working, and start uploading the data. So it will be a few days before I can do more debugging.

**Comment by gpatel-fr** [comment]
I have found why symbolic links were not restored: it's needed to check 'Restore read/write permissions' for that. This is not documented. First real problem. Second real problem: the symbolic links are restored correctly in this case, but the report is unaware of it, so if only symbolic link(s) have been selected for restoring, the backup has a warning status, because 'nothing has been restored' (wrong !). 
However I was not able to reproduce any of the problem signaled in your report, sorry.

**Comment by Jojo-1000** [comment]
> One symptom of the problem is that when you're defining backup sources and select a directory symlink everything in the target directory is selected as well, and then if you deselect everything in the target directory they're simply added as exclusions.

This might just be a visual bug in the UI. It doesn't distinguish between symlinks and normal files.
If you try to restore, does the symlink on the restore page also contain the contents, or only in the source selection?
