### ISSUE TITLE
doesn't support architecture 'i386' ?

### ISSUE THREAD

**Issue by ProTechEx** [duplicati/duplicati#5022]
I try to install it on my Ubuntu 20.04 Server 

Follow this procedure to install Mono on your Linux based system.
Ubuntu 20.04 / 20.10:

Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.mono-project.com/repo/ubuntu stable-focal InRelease' doesn't support architecture 'i386'

I get this issue, doesn't 64 bit supported ?

**Comment by gpatel-fr** [comment]
Hello

``
doesn't 64 bit supported ?
``
Yes it is. This is a warning that i386 is not. 
Does it answer your question ?
