### ISSUE TITLE
Deleting backup files on the destination should not cause backup full stop

### ISSUE THREAD

**Issue by TheGP** [duplicati/duplicati#5026]
## Environment info
Any

## Description
Deleting backup files on the destination should not cause backup full stop. Currently backup stops and the window with "please repair" pops up. Repair doesn't work thou. I don't see the reason backup should permanently fail like this.

## Steps to reproduce
1. Finish the backup
2. Remove all files of the backup

**Comment by Jojo-1000** [comment]
After the destination is altered in any way, the local database is no longer consistent with the destination. It is not possible to know if removing everything was intended.

In your case, you should be able to continue using the configuration after deleting the database (on the database page of the backup).

**Comment by D3Zyre** [comment]
I believe there is a documented way to recover from this type of failure (where some destination backup files are missing or corrupted), which will keep as much valid information as possible and rebuild anything that's missing or corrupted.

This is not done automatically however.

**Comment by ts678** [comment]
For partial file loss (maybe the destination dropped something), [Disaster Recovery](https://duplicati.readthedocs.io/en/latest/08-disaster-recovery/) in the User's Manual documents ways, but it's best to work with the experts here or on the forum for more help. Total delete situation here leaves no pieces to pick up though.

**Comment by gpatel-fr** [comment]
Does deleting the database as suggested by @Jojo-1000  solve your problem ?

**Comment by TheGP** [comment]
I just exported the whole backup, deleted and re-imported. Anyway, the reason I bring it up is because it is not user friendly approach. It should suggest recreating back up from scratch by clicking a button or silently do it itself.
