### ISSUE TITLE
Bugs in negated `in` expressions

### ISSUE THREAD

**Issue by gorosgobe** [duplicati/duplicati#5028]
`in` and `instanceof` expressions in JS
```js
a in obj;
a instanceof C;
```
can be negated by grouping them and applying the `!` operator, i.e.

```js
!(a in obj);
!(a instanceof C);
```

Applying the `!` operator incorrectly (on the LHS operand) leads to bugs:
```js
!a in obj; // will evaluate to false, unless obj has a "true" or "false" key
!a instanceof C; // will evaluate to false, unless C overrides instanceof with a @@hasInstance method
```
For more information, please see these [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#not_an_instanceof) and [the no-unsafe-negation recommended Eslint rule](https://eslint.org/docs/latest/rules/no-unsafe-negation).

I have found a potentially problematic instance of the above bugs in your codebase:
https://github.com/duplicati/duplicati/blob/44ce6d746f6784bac8a3d4e65b439d8b1ccd2db8/Duplicati/Server/webroot/ngax/scripts/controllers/RestoreController.js#L456

**Comment by gpatel-fr** [comment]
This should fix the problem where a restore would ask for a passphrase even if not necessary (unencrypted backup...)
Thanks (even if you will probably never read it).
