### ISSUE TITLE
New Feature - Consolidate Backup Versions

### ISSUE THREAD

**Issue by hl2guide** [duplicati/duplicati#5044]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Description

Please consider adding a **consolidate versions** link to the main home page of Duplicati.

The action would be to merge all versions of a backup into one version.

**Comment by gpatel-fr** [comment]
Hello

I don't understand what you mean by that. Versions of backups correspond to different versions of data: the file I created in december was modified in march, then in june. Consolidate would be that the restored file is equal simultaneously to the 3 versions ? Seems impossible to me. Please enlighten me.

If what you want is to just use the latest version, you can already delete range of versions, so all versions but the last (1-100000 for example). I don't see a pressing need for catering to this special need by loading more the UI.

**Comment by hl2guide** [comment]
> Hello
> 
> I don't understand what you mean by that. Versions of backups correspond to different versions of data: the file I created in december was modified in march, then in june. Consolidate would be that the restored file is equal simultaneously to the 3 versions ? Seems impossible to me. Please enlighten me.
> 
> If what you want is to just use the latest version, you can already delete range of versions, so all versions but the last (1-100000 for example). I don't see a pressing need for catering to this special need by loading more the UI.

In regards to what you described it would be "keep the latest version and delete all previous".

**Comment by gpatel-fr** [comment]
Like I said that can be easily done with the 'Delete' command (remove paths, add extra advanced option 'version' and specify for it as value something like 1-100000 to delete all versions but the '0' one). If there is doubt on the correct syntax the dry-run option is available.

**Comment by ts678** [comment]
> "keep the latest version and delete all previous".

[Creating a new backup job](https://duplicati.readthedocs.io/en/latest/03-using-the-graphical-user-interface/#creating-a-new-backup-job) explains the option

> Keep a specific number of backups:
The specified number of backup versions will be kept, all older backups will be deleted.

Setting that to 1 sounds like it might do what you just wrote, but the ask is still not clear.

Original post talked about "consolidate" and "merge" without giving much definition of it.

Duplicati version is a point-in-time view of the files then -- so by definition latest of each, provided file has not been deleted.
[Features](https://duplicati.readthedocs.io/en/latest/01-introduction/#features) in the manual may help, if your worry is space:

> Incremental backups
Duplicati performs a full backup initially. Afterwards, Duplicati updates the initial backup by adding the changed data only. That means, if only tiny parts of a huge file have changed, only those tiny parts are added to the backup. This saves time and space and the backup size usually grows slowly.

so there's not much reason to limit yourself to a single version, and old versions let you restore old versions and deleted files.
There have been requests to have the Restore screen set this up more nicely, but it's not clear what this "consolidate" issue is.
