### ISSUE TITLE
Better handling of low-free-space on backup target when automatically delete old backups is set

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#505]
_From [whlabr...@gmail.com](https://code.google.com/u/105293865642444434986/) on November 08, 2011 01:29:09_

What steps will reproduce the problem? 1. Setup a backup such that the destination only has room for N full backups, and set Duplicati to keep at most N full backups
2. Run N+1 full backups What is the expected output? What do you see instead? The N+1th full backup should complete successfully, deleting the oldest backup. At present, old backups are deleted after the backup completes, so the destination runs out of space mid way through the N+1th backup, errors out, then the old backup is deleted What version of Duplicati are you using? On what operating system? Duplicati 1.2.2 Final, Windows 7 x64 What backend (destination) are you using? Windows network share Please provide any additional information below. example log file:

BackupType      : Full
BeginTime       : 11/08/2011 02:00:00
EndTime         : 11/08/2011 06:33:42
Duration        : 04:33:42.3133026
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 0
AddedFiles      : 53605
AddedFolders    : 13841
ExaminedFiles   : 53605
OpenedFiles     : 53605
SizeOfModified  : 0
SizeOfAdded     : 43656203829
SizeOfExamined  : 43656203829
Unprocessed     : 22009
TooLargeFiles   : 0
FilesWithError  : 0
OperationName   : Backup
BytesUploaded   : 41163059783
BytesDownloaded : 0
RemoteCalls     : 474
NumberOfErrors  : 6
****************
There is not enough space on the disk.

There is not enough space on the disk.

There is not enough space on the disk.

There is not enough space on the disk.

There is not enough space on the disk.

Failed after uploading 156 volume(s). Error message: Failed to upload file: There is not enough space on the disk.

****************

Cleanup output:
Deleting backup at 10/31/2011 02:00:15
Deleting backup at 10/30/2011 02:00:15
Deleting backup at 10/29/2011 02:00:16
Deleting backup at 10/28/2011 02:00:15
Deleting backup at 10/27/2011 02:00:19
Deleting backup at 10/26/2011 02:00:16
Deleting backup at 10/25/2011 02:00:01

Cleanup output:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=505_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
