### ISSUE TITLE
Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: /mnt/SMB

### ISSUE THREAD

**Issue by michas79de** [duplicati/duplicati#5050]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.7.1_beta_2023-05-25
- **Operating system**: Ubuntu 22.04.3 LTS
- **Backend**: Jottacloud
## Description

While backups of all SSDs in my PC do work fine, the backup of my router's storage don't (but in Windows 10 it did).
I keep getting errors for each single file:

`2023-10-30 19:23:25 +01 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: /mnt/FritzNAS/Videos/FRITZ-Video.mp4`
...
`2023-10-30 19:23:25 +01 - [Warning-Duplicati.Library.Main.Operation.Backup.FileBlockProcessor.FileEntry-PathProcessingFailed]: Failed to process path: /mnt/FritzNAS/FritzUSB/BackUp/Samba_Backup_2023_10_29_00_00.tar`

The router is an "AVM Fritz!Box 6660 Cable" with an attached USB.
Accessing the router with its web GUI, the USB seems mounted as an additional folder "FritzUSB" between the other folders like Video, Musik...
The complete router's storage is accessible via SMB at //IP/FRITZBox6660Cable
I've mounted it via the fstab entry:
`//192.168.0.1/FRITZBox6660Cable /mnt/FritzNAS cifs _netdev,credentials=/home/verwalter/.smbcredentials,uid=1000,gid=1000 0 0`
The mount point /mnt/FritzNAS was made with sudo and is owned my root.
With a file explorer one can browse in /mnt/FritzNAS, so the mounting seems to be fine.
In the web GUI I selected this mount point as backup source with the checkbox in the tree, not by entering the path manually.

Duplicati runs as a service, but with some errors:
```
$ systemctl status duplicati
● duplicati.service - Duplicati web-server
     Loaded: loaded (/etc/systemd/system/duplicati.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-10-28 17:22:04 CEST; 2 days ago
   Main PID: 1581 (mono)
      Tasks: 44 (limit: 38215)
     Memory: 16.2G
        CPU: 1d 11h 4min 58.504s
     CGroup: /system.slice/duplicati.service
             ├─1581 DuplicatiServer /usr/lib/duplicati/Duplicati.Server.exe --webservice-interface=any --webservice-port=8200 --portable-mode
             └─2078 /usr/bin/mono-sgen /usr/lib/duplicati/Duplicati.Server.exe --webservice-interface=any --webservice-port=8200 --portable-mode

Okt 30 19:23:28 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:28 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:28 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:29 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:29 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:29 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:29 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:29 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:29 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
Okt 30 19:23:29 verwalter-MS-7A59 duplicati-server[2078]: w32error-unix.c: unknown error (116) "Veraltete Dateizugriffsnummer (file handle)"
```
And htop shows several processes of Duplicati.Server.exe as root:
![grafik](https://github.com/duplicati/duplicati/assets/49291708/c85ece3f-1038-41ec-b284-254083437ef7)

The backup job's advanced options seems to be:
```
--thread-priority=low
--use-background-io-priority=true
--use-block-cache=true
--tempdir=/tmp/
--synchronous-upload=true
--backup-name=FritzNAS
--dbpath=/mnt/Sicherungen/Duplicati/FritzNAS/UFVNGWVLZN.sqlite
--encryption-module=aes
--compression-module=zip
--dblock-size=500MB
--passphrase=***
--retention-policy=1W:1D,4W:1W,12M:1M
--disable-module=console-password-input
--exclude=/mnt/FritzNAS/FritzUSB/System Volume Information/
```

## Steps to reproduce

1. Just run a backup job for /mnt/FritzNAS with the GUI

- **Actual result**:
See the backup of about 7 GiB "completes" in about 10 sec. without errors but with the above mentioned warning.
Find only empty files in the backup.
- **Expected result**:
a longer backup time with at least 15 to 20 minutes upload time for a new backup
of course usable instead of empty backup files
(no more warning)

## Debug log

I think that's all the information I have ATM, but I'ld like to assist with more data, to help to solve this, if you tell me how.

**Comment by Jojo-1000** [comment]
For hopefully more detailed error messages, open the live log on the about page and set it to verbose while you run the backup. There should be more info about the underlying error.

**Comment by michas79de** [comment]
Oh, I'm sorry!
I had to recognize in the meantime, that I'm able to browse through this mounted SMD share with a file manager but I'm not able to open files by myself even with sudo. So I think it's no Duplicati issue. Sorry!
Since I'm new to Ubuntu it may take a while to solve this mounting issue.
However I attached the log.
[live_log_verbose.txt](https://github.com/duplicati/duplicati/files/13210275/live_log_verbose.txt)

**Comment by michas79de** [comment]
OK, I've found another mount command entry for my fstab including the options `vers=3.0,cache=none,noserverino`:
`//192.168.0.1/FRITZBox6660Cable /mnt/FritzNAS cifs _netdev,credentials=/home/verwalter/.smbcredentials,vers=3.0,uid=1000,gid=1000,cache=none,noserverino 0 0` 
Now I can open not only the folders but also the files and Duplicati can do it, too. At least it seems so, running a backup job since ten minutes for now instead of "completing" within ten seconds.
So I'm closing this issue again, hoping for a good finish. Sorry for my mistake!
