### ISSUE TITLE
How do I preserve "crtime" (creation/birth time) when  recovery  from Windows NTFS to Linux EXT4?

### ISSUE THREAD

**Issue by githubmyname** [duplicati/duplicati#5060]
How do I preserve "crtime" (creation/birth time) when recovery from Windows NTFS to Linux EXT4?

or 

How do I preserve "crtime" (creation/birth time) when  recovery from linux  EXT4 to Linux EXT4?

**Comment by Jojo-1000** [comment]
Duplicati should save the creation time as part of the file metadata (there is creation time, last write time and attributes). It uses the standard C# functions to get and apply the creation time. Is that not working in your case?

**Comment by githubmyname** [comment]
> Duplicati should save the creation time as part of the file metadata (there is creation time, last write time and attributes). It uses the standard C# functions to get and apply the creation time. Is that not working in your case?

doesn't work under linux,
ext4 only retains the modification time,
Both the creation time and the access time are overwritten as the time of recovery.

`dd if=boot.img of=/dev/fd0 bs=1440k `
If you use the dd command to back up and restore the file, all the attributes of the file are the same as the source time

**Comment by Jojo-1000** [comment]
From my quick googling, there is no way to set the creation time on ext4, except by manually messing with the partition data.

[Stackexchange question](https://unix.stackexchange.com/a/591388)

The comments claim that the Linux kernel has no method to set the creation time, so I don't see any way to support this.

> If you use the dd command to back up and restore the file, all the attributes of the file are the same as the source time

The dd command does not back up a file (at least in your example), it copies the whole partition bitwise, so all the file system data will be exactly the same.

**Comment by githubmyname** [comment]
> From my quick googling, there is no way to set the creation time on ext4, except by manually messing with the partition data.
> 
> [Stackexchange question](https://unix.stackexchange.com/a/591388)
> 
> The comments claim that the Linux kernel has no method to set the creation time, so I don't see any way to support this.
> 
> > If you use the dd command to back up and restore the file, all the attributes of the file are the same as the source time
> 
> The dd command does not back up a file (at least in your example), it copies the whole partition bitwise, so all the file system data will be exactly the same.

Thank you for your reply, I learned through the information, unfortunately, ext4 currently only provides the creation time to print, and has provided an interface to modify it, looking forward to the mainline linux to support it.

There is also a fifth timestamp to record inode creation time (crtime); this field is 64-bits wide and decoded in the same manner as 64-bit [cma]time. Neither crtime nor dtime are accessible through the regular stat() interface, though debugfs will report them. 
https://ext4.wiki.kernel.org/index.php/Ext4_Disk_Layout#Inode_Timestamps



https://unix.stackexchange.com/questions/50177/birth-is-empty-on-ext4#
https://www.linuxquestions.org/questions/linux-newbie-8/how-do-i-preserve-crtime-creation-birth-time-when-copying-from-windows-ntfs-to-linux-ext4-4175625229/

**Comment by githubmyname** [comment]
> From my quick googling, there is no way to set the creation time on ext4, except by manually messing with the partition data.
> 
> [Stackexchange question](https://unix.stackexchange.com/a/591388)
> 
> The comments claim that the Linux kernel has no method to set the creation time, so I don't see any way to support this.
> 
> > If you use the dd command to back up and restore the file, all the attributes of the file are the same as the source time
> 
> The dd command does not back up a file (at least in your example), it copies the whole partition bitwise, so all the file system data will be exactly the same.

In Windows,
We use github.com/matt-wu/Ext3Fsd mount ext4 partition. Then the ext partition is mounted on the windows system just like the local partition and accesses normally as with NTFS,

At this time, we can use some software under windows, such as: rsync, SyncToy, UrBackup and other software that can retain the file creation time in windows, we synchronize the ntfs file to EXT4,
Compare their creation time, and then mount it to the deeping Linux system in ext4, compare their creation time, which has been kept synchronized.

？？ Windows can keep the creation time with github matt-wu/Ext3Fsd, but Linux can't?
