### ISSUE TITLE
OneDrive backups stopped working

### ISSUE THREAD

**Issue by ririko5834** [duplicati/duplicati#5071]
I tried to also regenerate my auth ID but it still doesn't work. Getting this error 

Failed to connect: Forbidden: Forbidden error from request https://graph.microsoft.com/v1.0/me/drive/root:/Duplicati_Backups/Node1 System.Net.HttpWebResponse { "error": { "code": "accessDenied", "message": "Database Is Read Only", "innerError": { "code": "serviceReadOnly", "date": "2023-12-16T14:54:10", "request-id": "ffb7cf0d-a43a-486f-9a35-aa5c01e3275d", "client-request-id": "ffb7cf0d-a43a-486f-9a35-aa5c01e3275d" } } }

**Comment by gpatel-fr** [comment]
Hello

this looks like a backend (hoster) problem, did you try to investigate in your Onedrive console to see if anything was amiss ? also, is it a transient or permanent problem ?

**Comment by ririko5834** [comment]
I am trying to regenerate authid but even the oauth server for duplicate isn't working when I open the page 
![image](https://github.com/duplicati/duplicati/assets/64729293/391dfdbe-ee06-447c-8df0-033e7bfe007c)

**Comment by gpatel-fr** [comment]
Well, works for me (TM).
 I just deleted the Oauth token and recreated it without problem, did a backup and it worked all fine. Maybe it could be a firewall or antivirus problem  ? can you try on another computer ?

**Comment by ts678** [comment]
Google search of "OneDrive" "accessDenied" "serviceReadOnly" finds very little.
[One user](https://forums.unraid.net/topic/56610-support-linuxserverio-duplicati/?do=findComment&comment=1168384) was blocked by Microsoft. Is this a paid account? Can you ask them?
OneDrive also uses throttling mechanisms, maybe including temporary blocks.
[An rclone user](https://forum.rclone.org/t/database-is-read-only/33105) (so might not apply to yours) found that they were over quota.

The AuthID problem is probably unrelated. If you want it pursued, post a step-by-step description of the actions and the screens, however the "interaction_required" appears to be from Microsoft, so presents the same problem of no info as the other message. 

Using a very plain (no extra blockers, security, privacy, firewall, etc.) computer may help. You can also go to OAuth server directly:

`https://duplicati-oauth-handler.appspot.com/` but you will have to manually choose OneDrive, then copy the AuthID back.

**Comment by ririko5834** [comment]
Managed to get it working but I am facing another problem.
I deleted all backup configuration, restored it (I use new onedrive account and I had problem with backup files are missing errors so I recreated it).
I used run now button,
the backup was getting created
![image](https://github.com/duplicati/duplicati/assets/64729293/a9eba2db-d9cd-4428-afa4-46d83cdfd1a2)
after a few mins I came back to that page , got this
![image](https://github.com/duplicati/duplicati/assets/64729293/d2c6e0e8-eaec-4f67-8d83-3fde954a4283)
I refreshed the page, I login again with my password and then I didn't see the backup state anymore 
![image](https://github.com/duplicati/duplicati/assets/64729293/1bcf868f-95f1-4b1e-b3a7-3013149a81d9)


Why was the backup creation stopped? It wasn't completed, however some files has duplicate uploaded to my onedrive account but I guess its not  complete, the backups isn't being shown on the GUI. Shows Last successful backup:Never 
![image](https://github.com/duplicati/duplicati/assets/64729293/9235359b-fd6a-433b-8189-ad6cbd7d96f9)

Log:
![image](https://github.com/duplicati/duplicati/assets/64729293/23c10a30-d038-42f2-bb20-2c68c4fdc335)
![image](https://github.com/duplicati/duplicati/assets/64729293/9a386c6b-0a9c-4f43-851c-87ccf495a77e)


What could be the problem?

**Comment by gpatel-fr** [comment]
@ririko5834 

Please use the [forum](https://forum.duplicati.com/) for help.
