### ISSUE TITLE
GitHub Sponsor for donation

### ISSUE THREAD

**Issue by agung2001** [duplicati/duplicati#5073]
Firstly I wanted to say thank you to the Duplicati team and all the contributors
which delivers outstanding products with an easy-to-use interface. 🌟👍

I would like to sponsor the project
is there any plan to open a GitHub sponsor for donation?
currently, I can only do sponsor via GitHub sponsor due to company policy

**Comment by kenkendk** [comment]
Thanks for requesting this. I have sent in an application to be sponsored.

**Comment by luzpaz** [comment]
Duplication of #4987

**Comment by kenkendk** [comment]
Thanks for your request. [Duplicati is now backed by Duplicati Inc](https://forum.duplicati.com/t/introducing-duplicati-inc/17491/48), so donations are not possible.
