### ISSUE TITLE
How to clean-up orphan files?

### ISSUE THREAD

**Issue by andrew521** [duplicati/duplicati#5078]
Version:  - 2.0.7.1_beta_2023-05-25

Trying to run purge and getting:
```
ErrorID: CannotPurgeWithOrphans
Unable to start the purge process as there are 1 orphan file(s)
```
I've looked at older issues,  orphan file(s) related, and the recommendation was to manually run  Duplicati.CommandLine.exe cleanup. 
Unfortunately it seems that cleanup command was removed from newer releases.
`Command not supported: cleanup`

```
Duplicati.CommandLine.exe help

See duplicati.commandline.exe help <topic> for more information.
  General: example, changelog
  Commands: backup, find, restore, delete, compact, test, compare, purge,
  vacuum
  Repair: repair, affected, list-broken-files, purge-broken-files
  Debug: debug, logging, create-report, test-filters, system-info, send-mail
  Targets: aftp, azure, b2, box, cloudfiles, dropbox, file, ftp, googledrive,
  gcs, hubic, e2, jottacloud, mega, msgroup, onedrivev2, sharepoint,
  openstack, rclone, s3, od4b, mssp, sia, ssh, storj, tahoe, tardigrade, cos,
  webdav
  Modules: aes, gpg, zip, 7z, console-password-input, mssql-options,
  hyperv-options, http-options, sendhttp, sendmail, runscript, sendxmpp,
  check-mono-ssl
  Formats: date, time, size, encryption, compression
  Advanced: mail, advanced, returncodes, filter, filter-groups, <option>

http://www.duplicati.com/              Version:  - 2.0.7.1_beta_2023-05-25
```

**Comment by gpatel-fr** [comment]
Hello

the cleanup operation still exists under the name 'repair', unfortunately this is not the same kind of files; repair handles **remote** files (Duplicati backup files), while the problem here is with **local** files (your files, as they are known in the local database). As far as I know, the only way to repair it is to recreate the database. 

Can you try to switch to current Duplicati (Canary), especially if your backup is of decent size (>100 GB), to rename the current database and run recreate ?

If something goes wrong with the recreate, you can still restore the previous database (something you should never do in normal operation, but in the case of recreating the database it can be done).

**Comment by andrew521** [comment]
ok, I did a database recreate. running purge again:
```
Input command: purge
Input arguments:
        file://G:\.......
        E:\Data\Invest\data\ledger\ldg_j

Input options:
backup-name: 
dbpath: 
encryption-module: aes
compression-module: zip
dblock-size: 100MB
passphrase: 
prefix: 
no-auto-compact: true
profile-all-database-queries: true
log-file-log-level: error
auto-cleanup: true
disable-module: console-password-input
dry-run:
debug-output: true
```

and this is what I'm getting:

```
  Listing remote folder ...

Duplicati.Library.Interface.UserInformationException: Refusing to purge 0 files from fileset with ID 1718, as that would remove the entire fileset.
To delete a fileset, use the "delete" command.
   at Duplicati.Library.Main.Database.LocalPurgeDatabase.TemporaryFileset.PostFilterChecks()
   at Duplicati.Library.Main.Database.LocalPurgeDatabase.TemporaryFileset.ApplyFilter(IFilter filter)
   at Duplicati.Library.Main.Operation.PurgeFilesHandler.DoRun(LocalPurgeDatabase db, IFilter filter, Action`3 filtercommand, Single pgoffset, Single pgspan)
   at Duplicati.Library.Main.Operation.PurgeFilesHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.PurgeFiles(IFilter filter)
   at Duplicati.CommandLine.Commands.PurgeFiles(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.ParseCommandLine(TextWriter outwriter, Action`1 setup, Boolean& verboseErrors, String[] args)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)
```

**Comment by gpatel-fr** [comment]
Has the database recreation gone well ? that is, can you open the restore command and see the same versions you did see before ?

**Comment by andrew521** [comment]
actually yes. the database recreation went well and the purge was successful after that. shall I close the ticket or live it open as someone might look into a way to actually identify orphan file(s) in the error message.

**Comment by gpatel-fr** [comment]
Sorry, I don't understand what you say by 'the purge was successful' while you posted an error message in  https://github.com/duplicati/duplicati/issues/5078#issuecomment-1873038527
What did you do to solve this error message ?
