### ISSUE TITLE
 Download links for 1.3.4 are dead  

### ISSUE THREAD

**Issue by Titule1** [duplicati/duplicati#5079]
This
[https://github.com/duplicati/duplicati/issues/3661]
is closed. Seems I can't re-open it.

Environment info

    Duplicati version: 1.3.4

Description

I have a number of backups made with Duplicati 1.3.4. Since 2.0 does not support old backups, I need to get it to restore my files. However, links on the official [page](https://sites.google.com/a/duplicati.com/duplicati/news/duplicati134available) are dead. On GitHub [releases](https://github.com/duplicati/duplicati/releases/tag/1.3.4) page there's only source code. There was an issue https://github.com/duplicati/duplicati/issues/1545 in 2016, but it was closed, assuring that Google Code [archive](https://code.google.com/archive/p/duplicati/downloads) page with binaries "will exist for a number of years". Well, it doesn't anymore. I'd still like to get the binaries and restore my files though, and I don't want to download from warez sites for obvious reasons. Could anyone upload the latest 1.x version to GitHub? I need **Linux** version specifically, but I feel all platforms should be available, I'm probably not the only one who still has 1.x version backups lying around
Steps to reproduce

    Try to download 1.3.4
    Fail

**Comment by ts678** [comment]
Please fix your first broken link to `https://github.com/duplicati/duplicati/issues/url` (instead of `3661`) which I guess you quoted except for changing `Windows` to bolded `Linux`. Which one, in case a specific one is more quickly found than everything?

**Comment by Titule1** [comment]
Fixed it.
Windows is easier to find, I couldn't find Linux.
Anyway, a good fix would be to have a page with all versions.

**Comment by ts678** [comment]
> Anyway, a good fix would be to have a page with all versions.

Sure, but what Linux would you want if one can be found soon?

**Comment by Titule1** [comment]
mint

**Comment by ts678** [comment]
Try `http://updates.duplicati.com/1.3.x/Duplicati 1.3.4.deb`

**Comment by Titule1** [comment]
Thanks,

It requires `libmono2.0-cil`

I could  **not**   fix that with 
`sudo apt-get install libmono2.0-cil`  or
`sudo apt-get install mono-devel libmono-cil-dev` 

(Be warned, that took long.)

Seems that is another, bigger problem (see [https://github.com/duplicati/duplicati/issues/1844]

I couldn't find a solution

**Comment by ts678** [comment]
That issue was Duplicati 2 (see screenshot), and a rebuild as mentioned is hugely unlikely for 1.3.4. General historical comment:

[Package 'libmono2.0-cil' has no installation candidate](https://askubuntu.com/questions/840677/package-libmono2-0-cil-has-no-installation-candidate) gives the Ubuntu versions of that time that had it. There have been cases where people have had to set up older software environments (e.g. on a VM) to run older software. I assume you'd rather not...

Even if installer says it technically requires the library, does it run without it? If you can't finish install, maybe test `.zip` version.

**Comment by Titule1** [comment]
Where's the zip? Your link points to deb, and https://updates.duplicati.com/1.3.x does not show anything for me

**Comment by ts678** [comment]
> Where's the zip? Your link points to deb

Take my URL, change `deb` to `zip`.

But I also found from `man dpkg` that there is an `--ignore-depends=package` that might do the job with your current file.

**Comment by Titule1** [comment]
The zip does run for me, (that is: it opens the wizard-window)

>  Take my URL, change deb to zip.

(That's https://updates.duplicati.com/1.3.x/Duplicati%201.3.4.zip for the others)

Thank you very much for your help

**Comment by gpatel-fr** [comment]
A PR has been posted to upgrade the Duplicati front page.
Is your problem addressed ?

**Comment by kenkendk** [comment]
> (That's https://updates.duplicati.com/1.3.x/Duplicati%201.3.4.zip for those who will find this thread later)

I would assume it can run with [latest mono](https://www.mono-project.com/download/stable/#download-lin)?
Unzip it and run `mono Duplicati.CommandLine.exe`, I would guess that the GUI will be harder to get up and running.

**Comment by ts678** [comment]
An ambitious approach to making old links available would have a full set. The Wayback Machine at archive.org lacks some.
https://sites.google.com/a/duplicati.com/duplicati/news/duplicati134available is what I used to find the update server URLs.
I'm guessing that anything with lots of dependencies (e.g. Linux) would have trouble (as it did here). Maybe Windows runs?

I just mention this, but don't specifically argue for it. I think the current release and a .NET 8 (or whatever) are more urgent.
