### ISSUE TITLE
Please exclude folder `System Volume Information` from sorce in backaping.

### ISSUE THREAD

**Issue by korenevskiy** [duplicati/duplicati#5109]
Please exclude folder `System Volume Information` from sorce in backaping.

 

- [ v] I have searched open and closed issues for duplicates.
 
----------------------------------------

## Environment info
 
- **Duplicati version**:  2.0.7.1_beta_2023-05-25
- **Operating system**: Windows 11 pro
- **Backend**:  usb hdd DISK

![изображение](https://github.com/duplicati/duplicati/assets/6898474/9848157a-cc56-45f7-a4cc-7fb81d917db9)

**Comment by ts678** [comment]
Duplicate of [2.0.5.0_experimental - Denied access to System Volume Information gives a Warning #4045](https://github.com/duplicati/duplicati/issues/4045) (it appears).
While you're here, is this the only odd thing you want excluded? There are lots more potential excludes, aren't there?

**Comment by korenevskiy** [comment]
Yes, you are right, but I am afraid that my backup will be interrupted due to an error accessing the system folder.
I agree with the statement on the link, there should be a default rule with ignoring system access files.

**Comment by ts678** [comment]
> I am afraid that my backup will be interrupted due to an error accessing the system folder.

My point is it might be interrupted by other things, but if you want to start with that one, you can exclude it from Source

![image](https://github.com/duplicati/duplicati/assets/40771998/500cbd49-9f18-4600-bcab-5c2e840cbea5)

**Comment by korenevskiy** [comment]
👍
