### ISSUE TITLE
Get rid of Tardigrad-Backend?

### ISSUE THREAD

**Issue by TopperDEL** [duplicati/duplicati#5121]
This is more kind of a discussion: shall we get rid of the Tardigrade-Backend? Technically it already uses the newer Storj DCS-Backend. But maybe it is time to remove it completely.

Do you have any usage statistics of it? Is there a way to migrate configuration automatically from Tardigrade to Storj DCS? We already show a deprecation warning. But maybe it is a good time to clean it up?

**Comment by kenkendk** [comment]
A quick snapshot for the last 24h shows 0.125% usage of Storj and 0.049% usage for Tardigrade.
I am not deep enough into the API to understand how a migration would work.
But for the CLI we cannot change the input URL (as that is provided by the user).

I would simply add a warning to Tardigrade backend that it is not supported, hopefully with at nice "how to migrate" link pointing to the forum. Then wait some more, and remove it, and make it clear from the release notes that it is now removed.

**Comment by luixxiul** [comment]
I think it has been taken care of by https://github.com/duplicati/duplicati/pull/5314, and can be closed.

**Comment by TopperDEL** [comment]
Looks good to me 👍
