### ISSUE TITLE
Pre-release detected as virus - 2.0.7.101_canary_2024-03-08

### ISSUE THREAD

**Issue by rbeede** [duplicati/duplicati#5124]
## Description

1. Download duplicati-2.0.7.101_canary_2024-03-08-x64.msi from GitHub URL:
 - https://github.com/duplicati/duplicati/releases/tag/v2.0.7.101-2.0.7.101_canary_2024-03-08
 - [duplicati-2.0.7.101_canary_2024-03-08-x64.msi](https://github.com/duplicati/duplicati/releases/download/v2.0.7.101-2.0.7.101_canary_2024-03-08/duplicati-2.0.7.101_canary_2024-03-08-x64.msi)
2. Windows Defender instantly reports a virus was detected and removed

![image](https://github.com/duplicati/duplicati/assets/1429214/330ab634-b8bc-4cfc-87fd-6ff692567067)

**Comment by ts678** [comment]
Which Windows, and is this the Microsoft Defender included with Windows, or something else.
With default Defender, I can download and even right-click request  scan, and there's no issue.
I'm using your second link, direct to the executable, and giving it to virustotal.com is clean too.

**Comment by rbeede** [comment]
Windows 11 Pro. The one that came with it.

**Comment by rbeede** [comment]
Security intelligence version: 1.407.120.0
Version created on: 3/8/2024 6:57AM

**Comment by rbeede** [comment]
Did update and got 1.407.136.0.

Same when I download the file again.

**Comment by ts678** [comment]
This seems to be a common false positive, but sounds like it's more likely if it's been found before.
A Google search for "wacatac" "ml" "defender" "false positive" "detection history" has suggestions.

My [VirustTotal submission](https://www.virustotal.com/gui/url/d28f7f86c349d3472106587bcf9628f1d340eff84c2c8b3132a8f49c8092cec2/details) of your GitHub link now has

![image](https://github.com/duplicati/duplicati/assets/40771998/a03c3974-80df-4fd5-b325-82ef4b4b99c4)

If clearing you detection history doesn't help, maybe you can suggest a false positive to Microsoft.
The directions suggest not submitting installers. I wonder if the `.zip` file would trigger your A/V?
Problem is that they'd like you to isolate the problem, but that's hard if Defender keeps blocking...

If you can at least get that installer downloaded, SHA-256 signature on it should be the following:

![image](https://github.com/duplicati/duplicati/assets/40771998/b8ac4f52-694e-4063-889f-7d21aa854850)

If you have a hash tool such as Hash Tool from DigitalVolcano in the Microsoft Store, the SHA-256 is:

30f1da666e1261e2d651d0aa647fcb4957247a1d6038820f72f5efb6cf903775

**Comment by ts678** [comment]
> 1.407.136.0

I took that for Windows 10, and for good measure (in case something else is different) also a Windows 11. VM. All went fine.
Advice on wider Internet for how to deal with Defender glitches of this sort is probably better than a Duplicati issue can offer.

I gave a few suggestions I found, but saw other people suggesting full system scans and maybe using different AV programs.
Reporting a false positive is perhaps best done by the person getting it, and so far, I haven't been able to get any such thing.

**Comment by rbeede** [comment]
Submitted to Microsoft's form for reporting possible false positives.

**Comment by rbeede** [comment]
Security intelligence version: 1.407.178.0
Created 3/9/2024 12:35 AM

No longer reports the file as a virus. Looks like Microsoft pushed a definition update that fixed the false positive.

**Comment by ts678** [comment]
That's good to hear. They've been super busy with definition updates, although the last note naming Wacatac was [1.407.163.0](https://www.microsoft.com/en-us/wdsi/definitions/antimalware-definition-release-notes?requestVersion=1.407.163.0)
