### ISSUE TITLE
Script before_backup - localpath option not working for multiple sources

### ISSUE THREAD

**Issue by CireSacud26** [duplicati/duplicati#5140]
Hello,

- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.7.101
- **Operating system**: Windows10
- **Backend**: Local NAS repository

## Description
I use a "before_backup" script to set variables for the backup job. I want to set the localpath option to set 2 local directories being backed up, according the documentation :
REM DUPLICATI__LOCALPATH
REM This is the path to the folders being backed up or restored. This variable
REM is empty operations  other than backup or restore. The local path can 
REM contain : to separate multiple folders. This value can be changed by echoing
REM --localpath = "new value".

My actual script line is like this:
`echo --localpath = "c:\users\%username%":"C:\LocalDir\%username%"`

On backup job launch, an error occurs : `"Invalid path : "c:\users\[actual user]":"C:\LocalDir\[actual user]" (invalid character in path)"`

If I remove the one of the local directories from localpath option like this
`echo --localpath = "c:\users\%username%"`
The backup job works fine.

It seems the ":" separator doesn't work to set multiple folders to backup. Or have I misunderstand how this option works ?

Regards,
Eric

**Comment by ts678** [comment]
GitHub might have eaten some backslashes. You can avoid this by putting the string between backticks (even now using edit). Meanwhile, I'll guess there are unseen backslashes where they ought to be, such as before `%username%` and `[actual user]`.

> It seems the ":" separator doesn't work

It might be documented wrong. The code actually seems to split on [System.IO.Path.PathSeparator](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.pathseparator?view=netframework-4.7.1) - a semicolon on Windows,

https://github.com/duplicati/duplicati/blob/b0e852d9adb2196cb3fdc52e7cff65c9a18f0813/Duplicati/Library/Modules/Builtin/RunScript.cs#L372-L375

**Comment by CireSacud26** [comment]
Hi !
Thx for your quick reply. And yes, Github has eaten backslashes in my post. I should set this code lines as code ;-)

I've tried to use semicolon as suggested like this
`echo --localpath = "C:\users\%username%";"C:\LocalDir\%username%"`
but the same error occurs :-/

I gived a try with a colon "," but no more chance... 

Regards,
Eric

**Comment by CireSacud26** [comment]
Hi again !
I've solved the issue. This was not about semicolon seperator but about the double quotes I used for sources chains.

With this code line, it works : 
`echo --localpath = "C:\users\%username%;C:\LocalDir\%username%"`

Regards,
Eric

**Comment by ts678** [comment]
> This was not about semicolon seperator but about the double quotes

How do you know it wasn't also about colon versus semicolon? Can you test colon, and open an issue if that fails?

**Comment by CireSacud26** [comment]
> How do you know it wasn't also about colon versus semicolon? Can you test colon, and open an issue if that fails?

I know because I tested it.
This code lines  don't work:
`echo --localpath = "C:\users\%username%";"C:\LocalDir\%username%"
echo --localpath = "C:\users\%username%","C:\LocalDir\%username%"
echo --localpath = "C:\users\%username%":"C:\LocalDir\%username%"
echo --localpath = "C:\users\%username%,C:\LocalDir\%username%"
echo --localpath = "C:\users\%username%:C:\LocalDir\%username%"`

Only this code line works:
`echo --localpath = "C:\users\%username%;C:\LocalDir\%username%"`

Using a colon instead of semicolon in this last case should it work ? Or is it only a mistype in documentation ? I'll open an issue for it then.

**Comment by ts678** [comment]
Your testing proved that colon doesn't work even with double quotes fixed, so I think the example code and manual are wrong.

https://github.com/duplicati/duplicati/blob/23065d44ef142c104d47ef84e083b51cdf5d54ff/Duplicati/Library/Modules/Builtin/run-script-example.bat#L110-L114

[Example Scripts](https://docs.duplicati.com/en/latest/appendix-g-example-scripts/) is the manual, and technically is separately maintained. Ideally whoever fixed the code will open a PR to fix it too.

Thanks for noticing this. I'm often surprised at presumably old issues finally being spotted...
