### ISSUE TITLE
Please stop spamming people

### ISSUE THREAD

**Issue by DePasqualeOrg** [duplicati/duplicati#5168]
Today I received a promotional email about Duplicati at my GitHub email address. I have never signed up for your newsletter or used your service. I once starred this repository, which is probably why you decided to scrape my email address from GitHub and spam me. This is a violation of GitHub's terms of use and of privacy laws in many jurisdictions. Please stop doing this. It will not earn you any good will in the open-source community, and I will now be sure never to use your service.

**Comment by kenkendk** [comment]
Sorry to hear that you received an unwanted email.
This repository tracks the opens source Duplicati client and does not send any emails.

**Comment by piegamesde** [comment]
Where would you say is the correct place to complain about this?

**Comment by DePasqualeOrg** [comment]
He's misdirecting. Obviously Duplicati Inc is using their open-source repo to illegally send spam to promote Duplicati Inc.

**Comment by kenkendk** [comment]
@piegamesde There is an unsubscribe link in the mail, and you can reply to the email if you like.

**Comment by piegamesde** [comment]
@kenkendk no no no, that's not how it works. If you illegally send me spam, I'm not going to jump through any hoops to unsubscribe. I don't want spam in the first place. I never consented to this in any way.

**Comment by DePasqualeOrg** [comment]
Absolutely, it's insulting. Stop abusing the open-source community, @kenkendk.

**Comment by DePasqualeOrg** [comment]
https://github.com/duplicati/duplicati/issues/5171
