### ISSUE TITLE
Violation of 15 U.S. Code §§ 7701-7713

### ISSUE THREAD

**Issue by 5HT2** [duplicati/duplicati#5171]
Relevant documentation, for your convenience:
- https://www.ftc.gov/sites/default/files/documents/cases/2007/11/canspam.pdf
- https://uscode.house.gov/view.xhtml?req=granuleid%3AUSC-prelim-title15-chapter103&edition=prelim

---

I have never used Duplicati before, never interacted with any of your repos, and never use my `git@` email address for anything except git. The ONLY place my `git@` email address exists is on Github and as a commit author email.

It's extremely obvious if an email is spam / unwanted if it's being sent to my git email for that reason, and it's incredibly scummy to scrape Github for your marketing emails.

<img width="592" alt="image" src="https://github.com/duplicati/duplicati/assets/17222512/7f9b4f3e-86ff-4686-b37b-7e88ef743bc4">

---

### Please refer to Chapter 15 § 7702 3(1).

You did **not** obtain my consent before adding me to this mailing list and you are using it for commercial marketing.

This is illegal, regardless of if it is possible to unsubscribe, and it's insulting to the open-source community as a whole by leveraging emails used for OSS contributions for your marketing.

**Comment by mikini** [comment]
```
Delivered-To: <redacted>github<redacted>@<redacted>
Date: Fri, 03 May 2024 00:11:31 +0000
Reply-To: hello@duplicati.com
Subject: Introducing the Duplicati Portal - Monitor your backups from anywhere
From: "Duplicati Team" <hello@mailer.duplicati.com
```

Same here, just an incredibly obnoxious way to behave. How do you think this is in any way acceptable?
