### ISSUE TITLE
Status Information during upload

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#518]
_From [imi...@gmail.com](https://code.google.com/u/101313097058429111752/) on December 16, 2011 16:37:07_

What steps will reproduce the problem? 1.Open the UI, and observe "Status" during a multi-volume upload to a remote server 2. 3. What is the expected output? What do you see instead? In version 1.2.x and earlier, the Status screen would identify each volume, signature, and manifest file (1,2,3 ... etc) as it was uploaded.

In version 1.3, I see a generic message "Waiting for upload to complete" and the progress bars are advancing.. and then suddenly it switched over to a more verbose report beginning at volume 7 - "uploading content volume 7".

This seems to be inconsistent. What version of Duplicati are you using? On what operating system? ver. 1.4 (64 bit) on Windows 7 (64) What backend (destination) are you using? box.com (formerly box.net) using the Webdav option (SSL, port 443) + zip + aes encryption. Volume size set at 30 Mb. Please provide any additional information below. Also, a suggestion for the Version 2.x UI: Please label the 2 progress bars. I assume that the top bar is for the current volume, and the lower bar is for the entire job - but this information is not displayed at the present time.

Thanks!

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=518_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
