### ISSUE TITLE
Box.com authorization no longer works

### ISSUE THREAD

**Issue by n00b12345** [duplicati/duplicati#5183]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.8.1_beta_2024-05-07
- **Operating system**: Windows 11
- **Backend**: Windows 11

## Description

Box (box.com) can no longer be authorised. Trying different ways of authorising leads to errors:

## Steps to reproduce

1. Click on Auth ID after creating a new backup (or restoring old backup)
2. Grant access to Duplicati after logging in to Box

- **Actual result**:
Nothing happens on clicking "Grant Access" on Box's website (or using the recommended Duplicati redirection link) and AuthID remains blank
- **Expected result**:
AuthID is autofilled once access is granted

## Screenshots

![Screenshot 2024-05-10 024530](https://github.com/duplicati/duplicati/assets/17707852/d88258e2-74c1-40b6-a92e-bb6c701b5362)

## Debug log

`Duplicati.Library.Interface.UserInformationException: Failed to authorize using the OAuth service: Server error. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=box.com ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.`

   `at Duplicati.Library.Utility.AsyncHttpRequest.AsyncWrapper.GetResponseOrStream()`

   `at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse()`

   `at Duplicati.Library.JSONWebHelper.GetResponse(AsyncHttpRequest req, Object requestdata)`

   `at Duplicati.Library.JSONWebHelper.ReadJSONResponse[T](AsyncHttpRequest req, Object requestdata)`

  `at Duplicati.Library.OAuthHelper.GetTokenResponse[T]()`

   `at Duplicati.Library.OAuthHelper.get_AccessToken()`

   `--- End of inner exception stack trace ---`

   `at Duplicati.Library.OAuthHelper.get_AccessToken()`

   `at Duplicati.Library.OAuthHelper.CreateRequest(String url, String method, Boolean noAuthorization)`

   `at Duplicati.Library.JSONWebHelper.GetJSONData[T](String url, Action`1 setup, Action`1 setupbodyreq)`

   `at Duplicati.Library.Backend.Box.BoxBackend.<PagedFileListResponse>d__18.MoveNext()`

   `at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)`

   `at Duplicati.Library.Backend.Box.BoxBackend.GetCurrentFolder(Boolean create)`

   `at Duplicati.Library.Backend.Box.BoxBackend.List()`

   `at Duplicati.Library.Interface.BackendExtensions.TestList(IBackend backend)`

   `at Duplicati.Server.WebServer.RESTMethods.RemoteOperation.TestConnection(String url, RequestInfo info)`

   `at Duplicati.Server.WebServer.RESTHandler.DoProcess(RequestInfo info, String method, String module, String key)`

**Comment by n00b12345** [comment]
Problem is resolved. This was probably a temporary issue. It's working now.

**Comment by kenkendk** [comment]
@n00b12345 I got an email saying my "Activation request has been denied", but I have not requested an activation.
I will investigate, but please let me know if the problem returns, so I can escalate with box.com.

**Comment by n00b12345** [comment]
> @n00b12345 I got an email saying my "Activation request has been denied", but I have not requested an activation.
> I will investigate, but please let me know if the problem returns, so I can escalate with box.com. 

Thank you so much for helping. I have been able to reconnect to Box.com and everything is working fine right now.

I had reset my computer and had to reinstall Duplicati configuration from a backup. Other than having to repair the database, everything seems to be in order.

**Comment by tagatac** [comment]
I have been getting the error in the screenshot for the last hour or so. New auth IDs don't resolve the issue. @kenkendk can we reopen this? 🙏

**Comment by tagatac** [comment]
@kenkendk is there anything we can do to help get this working again? Is this a Box app issue?

**Comment by tagatac** [comment]
Please disregard. For me, this was a firewall issue after installing the new beta. Specifically, simplewall was blocking `duplicati.gui.trayicon.exe`. After unblocking, the connection seems to be okay.

**Comment by kenkendk** [comment]
Sorry for not getting backup to this sooner. I checked the status at box.com and everything seems operational.
I think the email was a slipup in some internal system at Box.
Closing as it appears all is working as expected.
