### ISSUE TITLE
Direct restore fails with non-default blocksize

### ISSUE THREAD

**Issue by Jojo-1000** [duplicati/duplicati#5196]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.8.1
- **Operating system**: Windows 10
- **Backend**: -

## Description

Direct restore does not save the detected blocksize from an existing backup. Instead, it tries to use the default value.

The detection works for the first partial recreate, which creates the latest version. However, the default blocksize is saved in the temporary database instead of the detected version.

## Steps to reproduce

1. Create a backup with `--blocksize=100KB`, `--upload-unchanged-backups` to a local folder
2. Backup twice, to have at least 2 versions
3. Direct restore from that folder
4. Select an older version

- **Actual result**:
A warning is shown and the list of files is empty.
```
2024-05-17 18:39:20 +02 - [Warning-Duplicati.Library.Main.Operation.RecreateDatabaseHandler-FileProcessingFailed]: Failed to process file: duplicati-20240517T162243Z.dlist.zip
InvalidManifestException: Invalid manifest detected, the field Blocksize has value 102400 but the value 1048576 was expected
```

- **Expected result**:
The older version should show in the list and be restored without any problems.

**Comment by ts678** [comment]
> Duplicati version: 2.0.8.1

Are you sure? New default went into master on April 21, which would have been between Experimental and Beta, so unlikely.
plus [GitHub shows 2.0.8.1 has the old default](https://github.com/duplicati/duplicati/blob/78ea50c8335772f2684ff39f8e44c22d2836322b/Duplicati/Library/Main/Options.cs#L40-L43). While it's a good thing to find the bug, I'm hoping it didn't just go into a Beta.

**Comment by Jojo-1000** [comment]
> Are you sure? New default went into master on April 21, which would have been between Experimental and Beta, so unlikely.

You are right, the reproduction is for the current master branch. You should be able to reproduce it with a blocksize of 1MB in the released version.

**Comment by Jojo-1000** [comment]
The cause why it only fails for direct restore is here:

https://github.com/duplicati/duplicati/blob/a89ccdec7d01bbff61689119dca3231ade1d25d7/Duplicati/Library/Main/Operation/RecreateDatabaseHandler.cs#L344-L345

`VerifyParameters()` writes the detected blocksize to the database, but for partial backups `updating=true`, even when the first recreate is run. This also has the effect that all volumeIds

**Comment by ts678** [comment]
> You should be able to reproduce it with a blocksize of 1MB in the released version.

Confirmed. I'm surprised it hasn't been seen before. Maybe need of old version helps.

I know increased blocksize is sometimes used, e.g. for performance on larger backups.

Wouldn't increased default blocksize on .NET 8 versions increase the visibility of issue?

Any workaround spotted yet?

**Comment by Jojo-1000** [comment]
> I'm surprised it hasn't been seen before. Maybe need of old version helps.

I guess most people don't use direct restore, but import the job and recreate the database fully. And those who do were probably only interested in the latest version.

> Any workaround spotted yet?

You should be able to set the blocksize explicitly in advanced options underneath the password to fix it temporarily.

**Comment by ts678** [comment]
Confirmed, but not underneath the screen 1 Password, but underneath the screen 2 Passphrase. It's easiest if you know the size exactly in the somewhat picky option format, e.g. `--blocksize=1MB` works, but giving it `--blocksize=1048576` gets Warnings:

```
Warnings 2 
2024-05-19 09:19:04 -04 - [Warning-Duplicati.Library.Main.Controller-OptionValidationError]: The size "1048576" supplied to --blocksize does not have a multiplier (b, kb, mb, etc). A multiplier is recommended to avoid unexpected changes if the program is updated.
2024-05-19 09:19:08 -04 - [Warning-Duplicati.Library.Main.Operation.RecreateDatabaseHandler-FileProcessingFailed]: Failed to process file: duplicati-20240518T105448Z.dlist.zip
InvalidManifestException: Invalid manifest detected, the field Blocksize has value 1048576 but the value 1073741824 was expected
```

If one doesn't know the blocksize, it seems like hiding dlist files of undesired later dates works, e.g. by changing prefix (if possible).

**Comment by kenkendk** [comment]
It took a bit to figure out what is going on exactly.
It happens because the UI automatically fetches version=0.
This works fine, but writes the default values for blocksize etc into the database.
When changing the version, the logic re-uses the database (with default sizes) and this triggers the error.

I reworked the logic around when the values are written, so they are always written if anything has been parsed from a manifest file, and changed the logic so the default values are not written in this operation.

There is a bit of logic involved, but essentially, the operation can only work if there already exists a remote file list, and this will naturally provide the correct values. I think a later refactor should split the validation of parameters and the saving of parameters to make it more clear what is intended.
