### ISSUE TITLE
Does the latest version support remote subfolders?

### ISSUE THREAD

**Issue by gdtv** [duplicati/duplicati#5237]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: latest
- **Operating system**: any
- **Backend**: any

## Description
I checked many related posts on github and forum.duplicati.com. The earliest post is from 2015, and the latest post is to 2023. I see that everyone has been discussing it, but I don't know how it is progressing.
I don't seem to find any settings for remote subfolders in the latest version. What is the progress of this matter? Is it being developed or will it not be developed?
This is not to urge, I just want to know the progress and plan.
This feature is very important to me.
Thank you.

**Comment by Jojo-1000** [comment]
> I don't seem to find any settings for remote subfolders in the latest version. What is the progress of this matter?

Can you clarify what you mean by remote subfolders? Do you mean that the backup should be split further into smaller folders?

That is currently not supported or in development. There is some discussion here:
https://github.com/duplicati/duplicati/issues/1374

And this [forum post](https://forum.duplicati.com/t/logic-and-usecase-for-remote-subfolders/6511?u=kees-z) describes a potential solution.

There have been some slowdowns observed for some storage types when there are a lot of files. Also, FTP often cuts off the file list after some number of entries. A way to bypass this is to increase the dblock size from the default 50MB.
