### ISSUE TITLE
Will the file name and directory name be encrypted with Encryption enabled ?

### ISSUE THREAD

**Issue by gdtv** [duplicati/duplicati#5238]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: latest
- **Operating system**: any
- **Backend**: any

## Description
If I enable encryption option and set " --passphrase" option, I know that the file contents will be encrypted, but will the file names and directory names be encrypted?

![2024-06-16 105644](https://github.com/duplicati/duplicati/assets/10823194/cac301f5-c3cf-438d-a61d-6834fd028b9c)

Thank you.

**Comment by kenkendk** [comment]
Hi @gdtv, yes, Duplicati groups everything in zip files and then encrypts the zip files. No filename or path information can be observed from the (encrypted) destination data.

**Comment by gdtv** [comment]
> Hi @gdtv, yes, Duplicati groups everything in zip files and then encrypts the zip files. No filename or path information can be observed from the (encrypted) destination data.

Thank you for your reply. Because there is another software, juicefs, which is also groups source files into encrypted files, but its documentation says that it only encrypts file contents and not file names, so I have this question about duplicati.

**Comment by kenkendk** [comment]
From a brief glance at juicefs, it aims to provide a filesystem, so in that case it is not easy to have encrypted filenames. Duplicati is not meant to be used as a working store of files, it is meant for (infrequent) restores, so it can fully encrypt all information.

**Comment by ts678** [comment]
Anything else here? If not, it will close.
