### ISSUE TITLE
If backup time < 6 minutes, profile failes to save.

### ISSUE THREAD

**Issue by KostromDan** [duplicati/duplicati#5266]
Duplicati - 2.0.8.1_beta_2024-05-07
![image](https://github.com/user-attachments/assets/7b63f015-545d-440c-98c2-35369e994366)
If backup time < 6 minutes, profile failes to save.
Save button just stops working.

**Comment by ts678** [comment]
There is a message from the server which browser code isn't showing. It used to work, and 2.0.9.101 works. Not sure why.

https://github.com/duplicati/duplicati/blob/78ea50c8335772f2684ff39f8e44c22d2836322b/Duplicati/Server/Database/Connection.cs#L467-L469

Browser developer tools can show this. Browser JavaScript does the popup locally for some other checks, but not this one.

![image](https://github.com/user-attachments/assets/8c5f3fd8-1fab-440f-bb09-c28ef5ffbb15)

In 2.0.9.101 Canary, the server error message is shown and the ReferenceError in the console is not. Maybe that was fixed?

**Comment by Jojo-1000** [comment]
https://github.com/duplicati/duplicati/commit/a1349b1af9e5a566a8c97998ae28cdeb817d10e9 added the missing AppService parameters in AppUtils.js for an unrelated change, not sure how I missed this in the first place.

**Comment by kenkendk** [comment]
This is fixed in latest canary: https://updates.duplicati.com/canary
