### ISSUE TITLE
Swapped strings in Duplicati/CommandLine/CLI/Strings.cs

### ISSUE THREAD

**Issue by grzesieklagocki** [duplicati/duplicati#5267]
It looks like `ControlFilesOptionShort `and `ControlFilesOptionShort ` strings in `Duplicati/CommandLine/CLI/Strings.cs` file are swapped. 

https://github.com/duplicati/duplicati/blob/60437d7fc0b0551c066adbb8404c12806ed4aaa9/Duplicati/CommandLine/CLI/Strings.cs#L50-L51

If it's not intentional you can use this little fix: https://github.com/grzesieklagocki/duplicati/tree/fix/cli-strings
Maybe there is more to change, e.g. when getting this strings?

https://github.com/duplicati/duplicati/blob/60437d7fc0b0551c066adbb8404c12806ed4aaa9/Duplicati/CommandLine/CLI/Program.cs#L278-L291

**Comment by kenkendk** [comment]
Thanks for finding this!
