### ISSUE TITLE
Strings split into multiple lines (such as "OptionServerLong") not properly localized and applied to UI

### ISSUE THREAD

**Issue by luixxiul** [duplicati/duplicati#5279]
- [ ] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: debug
- **Operating system**: Debian
- **Backend**: irrelevant

## Description

There seem to be some cases where strings which are split into multiple lines, such as [`OptionServerLong`](https://github.com/duplicati/duplicati/blob/63fc93ab38d01d014ca92a446c531c5cc49542a0/Duplicati/Library/Modules/Builtin/Strings.cs#L130-L133) for SendMail.cs, have not been properly localized and applied to UI.

## Steps to reproduce

1. Open settings http://localhost:8200/ngax/index.html#/settings
2. Change the language into one which has been actively maintained (Dutch for example)
3. Enable `send-mail-url` on "Standaard opties" ("Default options")

- **Actual result**:
[Localized strings as below](https://app.transifex.com/duplicati/duplicati/viewstrings/#nl_NL/duplicati?q=translation_text%3A'Een+url+voor+de+SMTP+server') should be applied:

![a](https://github.com/user-attachments/assets/55ecc1bf-8c24-476f-b760-01678715332e)

- **Expected result**:
The strings are displayed in English as original ones:

![b](https://github.com/user-attachments/assets/5f4985a6-7e51-4925-922a-e897cc1908ed)

**Comment by luixxiul** [comment]
IMHO this should be fixed because from the perspective of users it is basically the long descriptions that need localization.

**Comment by kenkendk** [comment]
I found the issue. This is caused by the strings having the Windows style `\r\n` lines but NGettext expects Linux style `\n`.
