### ISSUE TITLE
Localized strings became unavailable on pulldown items

### ISSUE THREAD

**Issue by luixxiul** [duplicati/duplicati#5285]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: debug
- **Operating system**: Debian
- **Backend**: irrelevant

## Description

After pulling the latest commit https://github.com/duplicati/duplicati/commit/abe37e7e33d4e28fc241fd4eed2d18ddd82ab200 and running `dotnet build` and `dotnet run`, localized strings became unavailable on pulldown menu.

## Steps to reproduce

1. Pull the latest commit 
2. Run `dotnet build` and `dotnet run`
3. Open the UI
4. Change the language into Dutch
5. Open the pulldown under "Standaard opties" (Default options)

- **Actual result**:
The localized strings should be available.

- **Expected result**:
They became unavailable.

## Screenshots
![b](https://github.com/user-attachments/assets/9ad25da7-adb5-4ef0-b69f-b3e517c27e8c)

**Comment by luixxiul** [comment]
Also apparently the description which appears by selecting an item has become available only in English:

![2](https://github.com/user-attachments/assets/1a3f7fb4-d943-4a96-bba6-a2201b4d0d65)

**Comment by luixxiul** [comment]
I confirmed that this issue has been introduced by either https://github.com/duplicati/duplicati/commit/2f26f52a305d180791a56c065c383d23d107dddb or https://github.com/duplicati/duplicati/commit/2f26f52a305d180791a56c065c383d23d107dddb, by building the binary after running `git reset --hard HEAD~2`, which applied the localized strings as expected.

**Comment by kenkendk** [comment]
@luixxiul I discovered this as part of the linefeed issue. The custom language header was not being used in the new webserver. I have merged #5283 which fixes it.
