### ISSUE TITLE
Pause and throttle icons should be able to be selected with tab key

### ISSUE THREAD

**Issue by luixxiul** [duplicati/duplicati#5289]
- [x] I have searched open and closed issues for duplicates.
- [ ] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: Debug
- **Operating system**: Debian
- **Backend**: irrelevant

## Description

From the perspective of accessibility, the action icons to pause or throttle should be able to be selected with <kbd>tab</kbd> key:

https://github.com/duplicati/duplicati/blob/d3071e95bb363e70e4699b1180e02fd29e645e67/Duplicati/Server/webroot/ngax/index.html#L147-L148 

https://github.com/duplicati/duplicati/blob/d3071e95bb363e70e4699b1180e02fd29e645e67/Duplicati/Server/webroot/ngax/index.html#L198-L199

## Steps to reproduce

1. Open http://localhost:8200/ngax/index.html
2. Set focus to the page
3. Push <kbd>tab</kbd> key to select the pause or throttle icon

- **Actual result**: they cannot be selected.

- **Expected result**: they should be selected.

**Comment by Jojo-1000** [comment]
See also this issue for other accessibility concerns: #5098

**Comment by luixxiul** [comment]
Adopting WAI-ARIA should be conducted although it should require intensive research and take a lot of manpower.
