### ISSUE TITLE
ubuntu 10.10 create new backup on new machine fails if suggested ducuments is sellected

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#531]
_From [tommy.gr...@gmail.com](https://code.google.com/u/105840414107018291737/) on January 04, 2012 11:07:42_

What steps will reproduce the problem? 1.create new backup on new machine (Ubuntu 10.10)
2.follow new backup guide, keep all default. (select all home,Documents,Videos mm.)
3.Set backup destination. run backup What is the expected output? What do you see instead? Duplcati builds a file list but crashes, never get past this point. What version of Duplicati are you using? On what operating system? 1.3 .DEB What backend (destination) are you using? webdaw, synology Please provide any additional information below. no error just quits, next time Duplicati starts a red error sign with questionmark inside is showing. no errors. 

By manually selecting folders backup works fine.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=531_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
