### ISSUE TITLE
Warning messages about SharpAESCrypt version

### ISSUE THREAD

**Issue by luixxiul** [duplicati/duplicati#5346]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: Debug
- **Operating system**: Debian
- **Backend**: irrelevant

## Description

By running `dotnet build && dotnet run` at `Duplicati.GUI.TrayIcon`, I got a lot of warning messages (although they do not seem to be harmful) about SharpAESCrypt version:

...
`/Duplicati/Library/Encryption/Duplicati.Library.Encryption.csproj : warning NU1603: Duplicati.Library.Encryption depends on SharpAESCrypt (>= 1.8.0) but SharpAESCrypt 1.8.0 was not found. An approximate best match of SharpAESCrypt 2.0.0 was resolved.`
`/Duplicati/WebserverCore/Duplicati.WebserverCore.csproj : warning NU1603: Duplicati.Library.Encryption depends on SharpAESCrypt (>= 1.8.0) but SharpAESCrypt 1.8.0 was not found. An approximate best match of SharpAESCrypt 2.0.0 was resolved.`
...

Since SharpAESCrypt 2.0.0 is resolved, the app is built and works, still I assume they probably should be addressed somehow.

## Steps to reproduce

1. Pull the latest source code into a new directory
2. Run `dotnet build && dotnet run` on the console

- **Actual result**: a lot of warning messages about SharpAESCrypt version were output.
 
- **Expected result**: there should not be warning messages about the version.

**Comment by kenkendk** [comment]
Yes, the correct version is 2.0.2, I will update.

**Comment by luixxiul** [comment]
I confirmed there were no warning messages output on the latest master branch :+1:
