### ISSUE TITLE
"Value too large for defined data type" error after upgrade to 2.0.9.101_canary_2024-06-27

### ISSUE THREAD

**Issue by LLPP65** [duplicati/duplicati#5352]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.9.101_canary_2024-06-27
- **Operating system**: Debian 12.6 / Raspbian bookworm 
- **Backend**: Microsoft OneDrive V2

Duplicati: Duplicati.Server, Version=2.0.9.101, Culture=neutral, PublicKeyToken=null (Duplicati.Library.Main, Version=2.0.9.101, Culture=neutral, PublicKeyToken=null)
Autoupdate urls: https://updates.duplicati.com/canary/latest-v2.manifest;https://alt.updates.duplicati.com/canary/latest-v2.manifest
Update folder: /root/.config/Duplicati
Install folder: /usr/lib/duplicati
Version name: "2.0.9.101_canary_2024-06-27" (2.0.9.101)
Current Version folder /usr/lib/duplicati
OS: Unix 6.6.31.7
Uname: Linux raspy3 6.6.31+rpt-rpi-v7l #1 SMP Raspbian 1:6.6.31-1+rpt1 (2024-05-29) armv7l GNU/Linux
64bit: False (False)
Machinename: raspy3
Processors: 4
.Net Version: 8.0.6
Locale: en-GB, en-GB, en-GB
Date/time strings: dddd, d MMMM yyyy - HH:mm:ss
Tempdir: /media/usb0/duplicati-tmp
SQLite: 3.42.0 - System.Data.SQLite.SQLiteConnection
SQLite assembly: /usr/lib/duplicati/System.Data.SQLite.dll

## Description

110 log errors like the following:
2024-07-30 03:01:07 +02 - [Warning-Duplicati.Library.Main.Operation.Backup.FileEnumerationProcess-PathProcessingError]: Failed to process path: /media/usb0/Movies/HomePicsAndMovies/60.mp4
OverflowException: Value too large for defined data type

## Steps to reproduce

These errors were produced during a nightly backup, after upgrade. I re-ran the backup and got the same errors.

- **Actual result**:
Errors as specified above
- **Expected result**:
No errors

## Debug log

I tried to upload the bug report.zip file but it is 452 MB.

**Comment by kenkendk** [comment]
Just to clarify, this did not give any errors on previous Duplicati versions, and the file is not new?
Also, do you see anything special about the file, like huge size, incorrect timestamps, etc?

**Comment by LLPP65** [comment]
I was previously running 2.0.8.1 and had not seen these errors. This specific backup is mostly large video files, with the largest being about 4 GB.

**Comment by kenkendk** [comment]
I think this is a problem with Arm7 being 32bit: https://raspberrypi.stackexchange.com/questions/82261/value-too-large-for-defined-data-type-error-on-files-larger-than-2gb-only-in-r

I will see if there is a solution to enable LFS on .NET8

**Comment by kenkendk** [comment]
I need to investigate this a bit more, but I think this stems from the use of the `Mono.Posix` package to access some of the Linux-specific filesystem attributes and properties. If so, it should be fixable. 

If the problem is in the .NET implementation, it will likely be very hard to fix.

**Comment by kenkendk** [comment]
Some progress on this. I tried to access big files with a pre-built .NET binary and it works fine, so the problem is the Mono.Posix package that appears to be built without big-file support.
