### ISSUE TITLE
"Backup_ProcessingFiles" cannot be localized

### ISSUE THREAD

**Issue by luixxiul** [duplicati/duplicati#5381]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: Debug
- **Operating system**: Debian
- **Backend**: irrelevant

## Description

The string `Backup_ProcessingFiles` cannot be localized. It should be so, because it tells users most direcly that everything is working as expected. 

## Steps to reproduce

1. Change the UI language from English
2. Start a backup task

- **Actual result**: `Backup_ProcessingFiles` should be displayed in the selected language
- 
- **Expected result**: it can only be displayed in English

## Screenshots

![before](https://github.com/user-attachments/assets/ea25b78a-6b5b-4ce2-9bac-cc9c240e0a83)

**Comment by kenkendk** [comment]
This is one of the places where the UI is just passing the raw value. Even in English language, it is not nice to do it like this.

I suggest we map the known values from [`OperationPhase`](https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/OperationPhase.cs#L26) as translate-able strings, and then have a default that shows the raw value in case a new value is added to the codebase without updating the html.
