### ISSUE TITLE
Mirror backup

### ISSUE THREAD

**Issue by yodaluca23** [duplicati/duplicati#5390]
Hello, I have taken a look through the manual, but still can't figure out how to make an exact mirror backup. I want the destination folder, to be identical, with no ZIPing, no encryption, no volumes, nothing, to the source. I looked at previous issues and found nothing, if someone could give a step-by-step or something that'd be great, I think also for people looking through here in the future.., I tried disabled as ZIP format, and making the volume size very large...

**Comment by ts678** [comment]
> I have taken a look through the manual, but still can't figure out how to make an exact mirror backup.

[Overview](https://docs.duplicati.com/en/latest/01-introduction/#overview) in the manual says right at top that this isn't what it does, and describes what it does, which is not what you want.
[Features](https://docs.duplicati.com/en/latest/01-introduction/#features) covers other things, many of which are very much part of the design. I'm afraid you likely want a different program.

> I think also for people looking through here in the future..

The forum is the better place for support information, and is searchable. The topics below have ideas on what you might use:

[Backup files and folders as is](https://forum.duplicati.com/t/backup-files-and-folders-as-is/15485)

[There is any way to backup just copying files? (not in data in volumes)](https://forum.duplicati.com/t/there-is-any-way-to-backup-just-copying-files-not-in-data-in-volumes/11657)

[Block-based storage engine](https://forum.duplicati.com/t/block-based-storage-engine/17681)
shows how this is now the second generation (thus Duplicati 2) of a non-mirror format, and I think the goal is to complete it.
