### ISSUE TITLE
Web server syslog strings and hostname configuration.

### ISSUE THREAD

**Issue by LLPP65** [duplicati/duplicati#5397]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.9.102_canary_2024-08-02
- **Operating system**: raspbian/debian12 arm7 cli
- **Backend**: Microsoft OneDrive v2

## Description

1. I have my duplicati web server configured to use port 8201 to avoid interfering with another service that uses 8200. On first start after upgrading to current version, the start message and login string displayed in the syslog specifies port 8200, but the server is running on port 8201.

Aug  3 10:19:20 raspy3 duplicati-server[8491]: Server is now running on port 8200
Aug  3 10:19:20 raspy3 duplicati-server[8491]: Initial signin url: http://localhost:8200/signin.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXAiOiJTaWduaW5Ub2tlbiIsInNpZCI6InNlcnZlci1jbGkiLCJuYmYiOjE3MjI2NzMxNjAsImV4cCI6MTcyMjY3Mz.......BsaWNhdGkiLCJhdWQiOiJodHRwczovL2R1cGxpY2F0aSJ9.jRq6nHYtG0quSY-X4aKzAmj5PnGFAtJwbwhX_Guo4M0

2. I have configured duplicati to allow a hostname for web access, then restarted the server, but it throws a "hostname not allowed" error when accessing via hostname or IP address, and only allows access to localhost (via ssh tunnel)

3. Duplicati takes a long time to terminate when stopped.

Aug  3 10:37:36 raspy3 systemd[1]: Stopping duplicati.service - Duplicati web-server...
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: State 'stop-sigterm' timed out. Killing.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Killing process 10980 (duplicati-serve) with signal SIGKILL.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Killing process 10981 (.NET SynchManag) with signal SIGKILL.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Killing process 10985 (.NET Finalizer) with signal SIGKILL.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Killing process 10987 (n/a) with signal SIGKILL.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Killing process 10988 (n/a) with signal SIGKILL.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Killing process 10991 (n/a) with signal SIGKILL.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Killing process 10993 (.NET TP Gate) with signal SIGKILL.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Killing process 10999 (n/a) with signal SIGKILL.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Main process exited, code=killed, status=9/KILL
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Failed with result 'timeout'.
Aug  3 10:39:06 raspy3 systemd[1]: Stopped duplicati.service - Duplicati web-server.
Aug  3 10:39:06 raspy3 systemd[1]: duplicati.service: Consumed 22.036s CPU time.

4. Other syslog notes:
```
Aug  3 10:45:52 raspy3 duplicati-server[14422]: warn: Duplicati.WebserverCore.Abstractions.ISettingsService[0]
Aug  3 10:45:52 raspy3 duplicati-server[14422]:       Could not deserialize last update version information `?packagetypeid=linux-arm7-cli.deb`
Aug  3 10:49:26 raspy3 duplicati-server[14422]: warn: Duplicati.WebserverCore.Abstractions.ISettingsService[0]
Aug  3 10:49:26 raspy3 duplicati-server[14422]:       Could not deserialize last update version information `?packagetypeid=linux-arm7-cli.deb`
Aug  3 10:54:26 raspy3 duplicati-server[14422]: warn: Duplicati.WebserverCore.Abstractions.ISettingsService[0]

Aug  3 10:58:59 raspy3 duplicati-server[17447]: fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
Aug  3 10:58:59 raspy3 duplicati-server[17447]:       An unhandled exception has occurred while executing the request.
Aug  3 10:58:59 raspy3 duplicati-server[17447]:       Duplicati.WebserverCore.Exceptions.NotFoundException: No active backup
Aug  3 10:58:59 raspy3 duplicati-server[17447]:          at Duplicati.WebserverCore.Endpoints.V1.ProgressState.Execute()
Aug  3 10:58:59 raspy3 duplicati-server[17447]:          at lambda_method255(Closure, EndpointFilterInvocationContext)
Aug  3 10:58:59 raspy3 duplicati-server[17447]:          at Duplicati.WebserverCore.Middlewares.LanguageFilter.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
Aug  3 10:58:59 raspy3 duplicati-server[17447]:          at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteValueTaskOfObject>g__ExecuteAwaited|129_0(ValueTask`1 valueTask, HttpContext httpContext, JsonTypeInfo`1 jsonTypeInfo)
Aug  3 10:58:59 raspy3 duplicati-server[17447]:          at Duplicati.WebserverCore.Middlewares.WebsocketExtensions.<>c__DisplayClass0_0.<<UseNotifications>b__0>d.MoveNext()
Aug  3 10:58:59 raspy3 duplicati-server[17447]:       --- End of stack trace from previous location ---
Aug  3 10:58:59 raspy3 duplicati-server[17447]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by LLPP65** [comment]
I wrote this and forgot to submit it. Now I see that someone already submitted the web access / hostname issue.

**Comment by kenkendk** [comment]
For the second part, the problem is that the option was mistakenly renamed from `--webservice-allowed-hostnames` to `--webservice-allowedhostnames`. 

The PR #5403 fixes this by allowing both variants.

For the first part, I think you are running two instances? 
I cannot see how the code could report another port than what it is actually listening to?

**Comment by kenkendk** [comment]
Aha! I found the problem, there was some older code looking for the appSettings.json values which are not used.

The error with `Could not deserialize last update version information `?packagetypeid=linux-arm7-cli.deb` is tracked in #5434 
The exception is "normal" and should not be logged, so you can ignore it for now.
