### ISSUE TITLE
TrayIcon uses same log. file as server

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#5399]
- [x ] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.9.102
- **Operating system**: Win11
- **Backend**: File

## Description

When running Duplicati in portable mode and then starting Trayicon in portable mode to get to webui because webserver stating "Connection to server was rejected due to invalid authentication. Reload browser window to reconnect to server properly. If this problem persist open this page from the TrayIcon instead." TrayIcon crashes:

D:\Software\Duplicati\Duplicati\Duplicati.GUI.TrayIcon --portable-mode
Unhandled exception. System.IO.IOException: The process cannot access the file 'D:\Software\Duplicati\Duplicati\Duplicati.debug.log' because it is being used by another process.
   at Duplicati.GUI.TrayIcon.HostedInstanceKeeper..ctor(String[] args) in D:\Projects-open\Duplicati\Duplicati\GUI\Duplicati.GUI.TrayIcon\HostedInstanceKeeper.cs:line 82

## Steps to reproduce

1. Run Duplicati.Server with --portable-mode
2. Run Duplicati.TrayIcon with --portable-mode

Maybe logic was changed during rewrite.

**Comment by mnaiman** [comment]
Obviously problem of debug build (I have compiled that version). Downloaded version is working. Still for debugging not good.

Another problem found with downloaded version:
Run Duplicati.Server with --portable-mode
Run Duplicati.TrayIcon with --portable-mode

D:\Software\Duplicati\Duplicati\Duplicati.GUI.TrayIcon --portable-mode
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Duplicati.GUI.TrayIcon.HostedInstanceKeeper..ctor(String[] args)
   at Duplicati.GUI.TrayIcon.Program.Main(String[] _args)
   at Duplicati.GUI.TrayIcon.Net8.Program.Main(String[] args)

**Comment by kenkendk** [comment]
At least the last part is a new bug introduced with the Kestrel code.
For the first part, I think we can use the executable name as part of the log filename?

**Comment by kenkendk** [comment]
@mnaiman I missed the part about this happening with debug builds, but I will fix it anyway.
The other problem is slightly harder to track. It looks like it happens due to some startup failure where the `Provider` is not set causing dependency injection to fail. 
Do you have a more extensive trace?

**Comment by kenkendk** [comment]
I think this issue has been resolved.
