### ISSUE TITLE
Kestrel support for EC private keys for HTTPS

### ISSUE THREAD

**Issue by mnaiman** [duplicati/duplicati#5400]
- [x ] I have searched open and closed issues for duplicates.
- [ x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.9.102
- **Operating system**: Win11
- **Backend**: File

## Description

.NET8 version have some trouble with X509Certificate2. Working great with RSA keys. But when EC keys are used and loaded HasPrivateKey property is true, but private key cannot be loaded from certificate and has to be extracted using ECDsa class. But Kestrel missing support to load certificate, because it support to load from drive from PEM, from P12, or using X509Certificate2 class.

I will prepare commit to change behavior to what we agree:
1) P12 file has to be saved eg in data folder as server.pfx and encrypted with password. Then Kestrel will be instructed like that:
listenOptions.UseHttps("data\\server.pfx", "super-secure-password-because-of-private-key");
2) Option in WebUI Settings to upload P12 file and set password, which will be saved to "data\\server.pfx" and used during startup. Optionally P12 can be stored to DB and save to file system during startup of Duplicati process.

I can prepare option 1, If someone will prepare option2 webui functionality.

Than I can test on Win/Linux environment.

## Steps to reproduce

1. Run Duplicati.Server with  --webservice-sslcertificatefile= containing EC private key.

**Comment by kenkendk** [comment]
Sounds good. So far we have not had the option to upload the certificate in the API, so I would make that a separate issue.

**Comment by mnaiman** [comment]
fix - https://github.com/duplicati/duplicati/pull/5413
ready for API and GUI that will have checkbox "Enable HTTPS" and upload field, that will save certificate to DB (as base64) and for certificate password
when saving it would be great to exit duplicati for change to be reload (in containers or service). it not, at least some button to perform exit in Duplicati to reload.

**Comment by mnaiman** [comment]
Working in 109, thanks
