### ISSUE TITLE
Error message for duplicate backup names not displayed in GUI

### ISSUE THREAD

**Issue by oniscript** [duplicati/duplicati#5419]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.8.1_beta_2024-05-07
- **Operating system**: Windows 10
- **Backend**: Local folder or drive

## Description
While this is a minor issue, I wanted to bring it to your attention. When attempting to create or save a backup with a duplicate name in the Duplicati GUI, no error message is displayed to inform the user of the issue. Although the error message is printed to the browser console, the user interface remains unresponsive, leaving the user unaware of why the "Save" button does not work.

## Steps to reproduce
1. Open Duplicati GUI (tested on both Edge and Chrome).
2. Attempt to create a backup using a name that already exists in the system.

- **Actual result**:
No error message is displayed in the user interface. The "Save" button becomes unresponsive, and the user receives no feedback indicating why the backup cannot be saved. The error is only visible in the browser console, not in the user interface.
- **Expected result**:
An error message should be displayed in the user interface to inform the user of the duplicate backup name, allowing them to correct the issue and successfully save their backup.

**Comment by ts678** [comment]
Looks like message issue [If backup time < 6 minutes, profile failes to save. #5266](https://github.com/duplicati/duplicati/issues/5266) in terms of when it arose and was fixed.

2.0.8.108 Debug lacks message. Console:

![image](https://github.com/user-attachments/assets/3d1b8525-f9d6-4f4d-b245-8b5bc5c4ef93)

2.0.8.109 Debug and 2.0.7.1 Beta pop up:

![image](https://github.com/user-attachments/assets/51cb1aa0-17db-4733-b7a8-7d3314affab6)

**Comment by kenkendk** [comment]
This is fixed in the latest canary build: https://updates.duplicati.com/canary
