### ISSUE TITLE
SSH keyfile connection failed

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#546]
_From [spisca...@gmail.com](https://code.google.com/u/103505171468222377961/) on January 19, 2012 17:27:54_

What steps will reproduce the problem? 1. Create a new job and select SSH as destination
2. Select an openssh keyfile
3. Test connection
4. Observe error message What is the expected output? What do you see instead? I expect to see "connection successful" but instead I see an error message. What version of Duplicati are you using? On what operating system? 1.3.1.1101. Issues also exists in 1.3. Windows 7 Ult 32bit. What backend (destination) are you using? SSH Please provide any additional information below. I was able to recreate the issue in a Win7 virtual machine. The connection was successful using the same configuration in an XP virtual machine.

**Attachment:** [duplicati.jpg](http://code.google.com/p/duplicati/issues/detail?id=546)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=546_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
