### ISSUE TITLE
Update Docker description explaining the encrypted field settings implications

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#5496]
After #5420 was implemented, the database is no longer directly portable between machines.

For Docker usage, this may cause unexpected loss of the encryption key as it is default using the machine serial number to derive a key. If the VM running Docker is recreated or changed in some way, which is common for Docker applications, the serial number will no longer match.

In this case it may be hard/impossible to get the original serial number restored, and the database contents will be inaccessible.

While this is "as designed" the README for Docker users should explain the setup and recommend setting either `SETTINGS_ENCRYPTION_KEY=<custom-password>` or setting `DUPLICATI__DISABLE_DB_ENCRYPTION=true` to prevent the database from being encrypted.

Alternative solution would be to use #5492 and inject a preload configuration that disables encryption for Docker builds, unless actively enabled.

**Comment by ts678** [comment]
> the README for Docker users should explain

The popular Docker seems to be LinuxServer.io although I suppose they could follow our lead. I wonder if we could warn them?

**Comment by kenkendk** [comment]
@ts678 I have created an issue and proposed a change to LinuxServer.io

**Comment by kenkendk** [comment]
For Duplicati's version of the Docker image, the least intrusive way is to disable the encryption for now.
This allows everyone to simply update and keep working, without the chance of a nasty surprise later.

For those not running Docker we need to figure out some way to communicate that simply making a backup of the settings database is not sufficient to recover the passphrase if the machine breaks. Long term solution is to make 1st class support for backing up the settings as tracked by #5494 .
