### ISSUE TITLE
Purge backups when only XX free space is left on target

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#550]
_From [039.m...@gmail.com](https://code.google.com/u/114869400157319322451/) on January 23, 2012 20:35:36_

What steps will reproduce the problem? 1.Several backups are done
2. Drive runs out of room
3. No further backups can be done What is the expected output? What do you see instead? Drive is full, Purge destination??  / Cannot backup to destination, disk is full What version of Duplicati are you using? On what operating system? 1.3 Ubuntu 10.04 What backend (destination) are you using? SSH Please provide any additional information below. Add feature to automatically or manually purge the destination when XX free space is left.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=550_
##

**Comment by rryk** [comment]
Would be nice to force Duplicati do cleanup after changing limits (e.g. keep only 1 backup instead of 3 months) or to force compacting after removing some folders from the list of folders to be backed up.

**Comment by warwickmm** [comment]
I don't think Duplicati should automatically purge backups when storage limits are reached.  First, the user should probably decide which backups to keep/delete.  Second, the lack of free space may be temporary or unintentional, and the real solution may actually be to remove non-duplicati files from the storage.
