### ISSUE TITLE
send-http-output-result-format json doesn't work

### ISSUE THREAD

**Issue by olaulau** [duplicati/duplicati#5500]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.
only found this : https://forum.duplicati.com/t/dupicati-http-json-data-is-null/10994/4

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.8.1
- **Operating system**: windows
- **Backend**: local

## Description
trying to configure duplicati to send an http request after each backup
but ```send-http-output-result-format=json``` send an empty HTTP query
I've setup a PHP page to receive the query, works well with 'duplicati' format but no data with 'json' format

## Steps to reproduce

1. create a small backup
2. in advanced options, set a 'send-http-url' => this works
3. set 'send-http-output-result-format=json' then the http query is empty

- **Actual result**:
empty query
- **Expected result**:
having an equivalent of the 'duplicati' format data, but json_encoded

## other informations
tried many 'send-http' options values without any good result.

**Comment by kenkendk** [comment]
But... that bug should only make it back to the original format, not make an empty one?
Have you by any chance changed any of the other `--send-http-*` options?

Particularly, the `--send-http-message` parameter does some hard-to-understand logic for mapping fields if you change it. I can easily see how this could lead to empty requests.

**Comment by kenkendk** [comment]
> I made a fresh new backup config, with only extra option : sent-http-url & sent-http-result-output-format=Json
-> the message is in duplicati format, not json.

So you say you see the message still not in Json format? Or was it fixed by not having the extra options?

**Comment by olaulau** [comment]
no extra option -> message not empty
but still in duplicati format despite I asked format in json format

**Comment by kenkendk** [comment]
That is strange... And you are sure the option is configured on the backup itself? (not in the place found under "Settings").

We use the same feature (Json formatted) for the Duplicati Portal, and here it is rejected if not valid JSON and we see reports from 2.0.8.1.

Have you tried something like webhook.site or similar where you can see all content passed?

**Comment by olaulau** [comment]
It's a brand new install of duplicati, no general settings.

I wrote myself a small PHP script which receive the query and log all informations (GLOBAL, SERVER, POST, GET ...).
Didn't know about webhook.site, it's wonderfull. and json is working ...

So the problem was between the chair and the keyboard, as usual !
In PHP, $_POST only get associated variables in an array.
For raw body, like a json stream, you have to use : ```file_get_contents('php://input');```, then ```json_decode``` what you got.

Sorry for my mistakes ... and thank you for the time you took finding my problem.

**Comment by kenkendk** [comment]
Happy to hear that you got it solved!

For the next versions (out in canary form) I have added `--send-http-json-urls` to allow sending JSON data without having to keep track of two variables. The weirdness around sending blank messages is not resolved though.

**Comment by olaulau** [comment]
do you believe it will possible to set multiple URLs ?
