### ISSUE TITLE
Translate msgid error, and can't change in transifex

### ISSUE THREAD

**Issue by nadirvishun** [duplicati/duplicati#5509]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: git clone from master branch(2024-08-30)，build and run in about page is `Duplicati 1.0.0.0`
- **Operating system**: win11
- **Backend**: local

## Description

in `duplicati\Localizations\duplicati\localization-zh_CN.po` file `msgid` is error ,example :
| msgid text | source in .cs file|
| ---- | ---- |
| Sets| Set |
| Disables | Disable |
| Supplies | Supply |
| ... | ... |

also checke other `.po` file, the same issue.
I log in [transifex](https://app.transifex.com/) to make change, However, after the modification is completed and then downloaded, it is found that msgid has returned to its original state before the modification.

## Steps to reproduce

- **Actual result**:
Due to mismatched msgid, the translation is ineffective.
- **Expected result**:
Translation takes effect normally.

## Screenshots

no
## Debug log

no

**Comment by kenkendk** [comment]
Hi @nadirvishun I have run the push/pull cycle so all msgids should now match Transifex.
