### ISSUE TITLE
Duplicati installer should not install autostart shortcut

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#551]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on January 24, 2012 21:09:39_

The current installer will set a shared shortcut to autostart Duplicati.
This makes it difficult to use Duplicati in a shared environment where not all users are Duplicati users.

Instead Duplicati should install a per-user autostart shortcut after the user has configure a new backup.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=551_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
