### ISSUE TITLE
Listen interface setting appears to not be applied correctly

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#5515]
After the update to Kestrel, it seems the default socket listener is on any interface, where it was previously restricted to 127.0.0.1 (aka loopback).

See [more details on the forum](https://forum.duplicati.com/t/release-2-0-9-103-canary-2024-08-15/18827/16).

**Comment by ts678** [comment]
I think default is from database, per followup forum discussion. I just started 2.0.9.105 with a new database and no option:

```
C:\>netstat -ano | findstr 8200
  TCP    127.0.0.1:8200         0.0.0.0:0              LISTENING       25752
```

seems as intended for the coded default without benefit of getting remembered setting out of the server database for this.
It did set up its new database's Option table with server-listen-interface of loopback, even though no CLI option was given.


</body></html>

**Comment by kenkendk** [comment]
Great! I will close this issue then.
