### ISSUE TITLE
Need Help with Debian Lenny Command Line Modus

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#552]
_From [webseite...@gmail.com](https://code.google.com/u/114146241461488759884/) on January 26, 2012 00:59:51_

Hi, i have a problem. I installed duplicati on debian lenny. And when
i try to start a backup, i got the message:

The requested feature is not implemented.

Here a few examples what i try:

mono /root/Duplicati/Duplicati.CommandLine.exe /var/www/vhosts/site.de/
httpsdocs/ ftp://user:p...@backup.server.de/folder/

*********************

mono /root/Duplicati/Duplicati.CommandLine.exe --full-if-more-than-n-
incrementals=10 --auto-cleanup --no-encryption  /var/www/vhosts/site.de/httpsdocs/ ftp://user:p...@backup.server.de/folder/

Is there something wrong with the syntax ?

Thx for help

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=552_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
