### ISSUE TITLE
Parse URL typed into servername field

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#553]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on January 26, 2012 11:09:50_

It seems tempting for power users to just type in an url into the servername field, like: http://example.com/folder , instead of splitting the url into the components and typing them in the appropriate fields.

Duplicati should try to parse the servername as a string, and apply the components as typed, and set servername, path, port, username and password as appropriate.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=553_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
