### ISSUE TITLE
Add a skip existing files to the restore files option

### ISSUE THREAD

**Issue by nachoha** [duplicati/duplicati#5537]
**Is your feature request related to a problem? Please describe.**
Sometimes I have a directory with hundreds or thousands of files and only want to restore files that are missing, right now the only 2 options I have are to compare the list of backed-up files and existing files and manually select each missing file, or to overwrite all existing files

**Describe the solution you'd like**
It would be nice if the restore options had a skip existing files rather than overwrite or make a new copy

**Comment by ts678** [comment]
> or to overwrite all existing files

That's not how it works. If existing files are fine (right version, not corrupted, etc.) there is no need to do anything on a restore.

> only want to restore files that are missing

If, however, your goal is to consider any file (partial, corrupted, obsolete) as good, then that's currently hard for Duplicati to do.

> had a skip existing files rather than overwrite or make a new copy

It will neither overwrite nor make a new copy if the current file is OK. Please test a restore and see if you can verify the behavior.

**Comment by nachoha** [comment]
That's great, as you mentioned in your edit the behavior is not mentioned on the screen so I didn't realize it behaved in that way. Thanks for the feedback
