### ISSUE TITLE
Exception when aborting backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#554]
_From [Boris.W...@gmail.com](https://code.google.com/u/107494042338589850044/) on January 29, 2012 19:59:42_

What steps will reproduce the problem? 1. During running backup use dropdown and select "abort running backup"
2. repeat the selection from the dropdown What is the expected output? What do you see instead? There is no response from the system. It just keeps going and finishes uploading. The user is unsure whether he selected the right entry. When soing this twice (sometimes multiple times) the backup really aborts with this stack trace in the log:

Error: System.Threading.ThreadAbortException: Thread was being aborted.
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task) What version of Duplicati are you using? On what operating system? Win7 x64 Duplicati 1.3 What backend (destination) are you using? FTP Server Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=554_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
