### ISSUE TITLE
Duplicati  can't see the .key extension

### ISSUE THREAD

**Issue by popescuvitor** [duplicati/duplicati#5565]
I don't even know how to reproduce this failure, I just had a big loss when I lost the rootCA.key file of my self-signed certificate. The file simply cannot be listed by duplicati. When I looked, several other files that also have the .key extension, were simply never saved.

**Comment by ts678** [comment]
> several other files that also have the .key extension, were simply never saved.

Did some do OK? Note that in GUI restore, there is also a search you could use.

I ask because rootCA.key has restricted permissions, so only its owner can read.
You'd need to run Duplicati as the correct user. What user are you starting it as?
Having said that, if there's an access error, a message about it should be raised.

[How to Create Self-Signed Certificates using OpenSSL](https://devopscube.com/create-self-signed-certificates-openssl/) is what I tested, and got:

```
$ ls -ln
total 8
-rw-rw-r-- 1 1000 1000 1237 Sep 20 21:03 rootCA.crt
-rw------- 1 1000 1000 1704 Sep 20 21:03 rootCA.key
$ 
```

**Comment by ts678** [comment]
>  I lost the rootCA.key file

So not an entire drive, so Duplicati is still runnable and has its configuration? Does your job Source have any relevant filters?

Have you checked older backups with GUI search as above to see if file is there? You can also search all versions at one time.

[The FIND command](https://docs.duplicati.com/en/latest/04-using-duplicati-from-the-command-line/#the-find-command) in GUI [Commandline](https://docs.duplicati.com/en/latest/03-using-the-graphical-user-interface/#using-the-command-line-tools-from-within-the-graphical-user-interface) with `*.key` in `Commandline arguments` might do well. I also turned on [all-versions](https://docs.duplicati.com/en/latest/06-advanced-options/#all-versions):

```
            
Listing files and versions:
/tmp/openssl/rootCA.key
0	: 9/23/2024 3:07:15 PM 1.664 KB
1	: 9/20/2024 9:41:31 PM 1.664 KB
```

**Comment by popescuvitor** [comment]
@ts678 Thank you very much for your answer, I believe you may be right. Look
![Screenshot from 2024-09-23 16-13-42](https://github.com/user-attachments/assets/23e29624-ca91-4727-9d3e-dd8e3c6312c7)


I'll adjust the permissions and try again.

**Comment by popescuvitor** [comment]
That really was it. After adjusting the permissions, it worked:

![Screenshot from 2024-09-23 16-24-25](https://github.com/user-attachments/assets/75760e35-dffa-4fe6-abcd-091224857a88)

I messed up 🤦‍♂️ Thank you very much for your attention, I will close the issue.
