### ISSUE TITLE
Telegram notification error

### ISSUE THREAD

**Issue by Thormir84** [duplicati/duplicati#5567]
- [X] I have searched open and closed issues for duplicates.
- [X] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info
- **Duplicati version**: 2.0.9.107_canary_2024-09-11
- **Operating system**: Docker - image: lscr.io/linuxserver/duplicati:development

## Description
I have set Telegram's notifications but does not work correctly.

## Steps to reproduce
Go to "Settings" and copy&paste this (with your BOT_TOKEN and CHAT_ID:
--send-telegram-any-operation=true
--send-telegram-api-key="https://api.telegram.org/botMY_BOT_TOKEN/sendMessage"
--send-telegram-channel-id="MY_CHAT_ID"
--send-telegram-level=all
--send-telegram-log-level=Warning
--send-telegram-message="Duplicati %OPERATIONNAME% report for %backup-name% %RESULT%"
--send-telegram-result-output-format=Duplicati

- **Actual result**:
[Warning-Duplicati.Library.Modules.Builtin.SendTelegramMessage-telegramSendError]: Failed to send to telegram messages: Value cannot be null. (Parameter 'stringToEscape') ArgumentNullException: Value cannot be null. (Parameter 'stringToEscape')

At the end of every backup's job.

- **Expected result**:
A message received on Telegram with the report

## Screenshots
![Immagine 2024-09-22 103204](https://github.com/user-attachments/assets/caac40e4-d358-4e50-bf04-7a1a90a8216a)

## Debug log
NULL

**Comment by kenkendk** [comment]
Fixed with #5653

**Comment by dsultanr** [comment]
for those who came here as a last resort:

BotFather gives you the Token as a concatenated string "botId:Token" but [code](https://github.com/duplicati/duplicati/blob/46e5bf3f6f5f95da8ea36aea31fb4f03411d74ca/Duplicati/Library/Modules/Builtin/SendTelegramMessage.cs#L249) expects that it is divided into a separate botId (send-telegram-bot-id) and apiKey (send-telegram-api-key) parameters
```
                botId = Uri.EscapeDataString(m_botid),
                apiKey = Uri.EscapeDataString(m_apikey)
...
            var url = $"https://api.telegram.org/bot{p.botId}:{p.apiKey}/sendMessage?chat_id={p.chat_id}&parse_mode={p.parse_mode}&text={p.text}";
```

**Comment by spupuz** [comment]
For anyone who'd rather avoid dealing with the built-in Telegram integration quirks altogether, I've created a small open-source shell script that plugs into Duplicati via `--run-script-after` / `--run-script-before` and sends rich HTML-formatted Telegram notifications directly through the Bot API.

It's Docker-friendly (Bot Token and Chat ID are loaded from env vars or a `.env` file), handles CRLF issues when scripts are edited on Windows, and produces detailed reports with status icons, changed files, size/duration metrics, and optional logs on failure.

Repo: https://github.com/spupuz/duplicati-telegram-notifications

Might be useful for those who keep running into issues with the native Telegram support.
