### ISSUE TITLE
Generated password warning when re-typed in manually thereafter

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#561]
_From [james.co...@gmail.com](https://code.google.com/u/105829900405594709437/) on February 13, 2012 01:49:04_

What steps will reproduce the problem? 1. launch duplicati setup wizard
2. click generate random password button
3. replace random password with one yourself What is the expected output? What do you see instead? You see this:

---------------------------
Duplicati
---------------------------
You have generated a new random password.

Please write down the password and store it in a safe location.

Without this password, you will not be able to recover a single file from the backups!

You cannot recover the password from within Duplicati after saving this setup.

Are you sure you have a safely stored copy of the generated password?
---------------------------
Yes   No   Cancel   
---------------------------

but it's wrong What version of Duplicati are you using? On what operating system? latest /win7x64 What backend (destination) are you using? none yet, this is a new user wizard thing Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=561_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
