### ISSUE TITLE
Run hours

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#563]
_From [james.co...@gmail.com](https://code.google.com/u/105829900405594709437/) on February 15, 2012 00:31:34_

How are you using Duplicati now? It starts at 7.00pm, and if it's a full backup, it takes approx 50 hours. I assume the 7.00pm the next day will be skipped, or is it queued? Hopefully it's ignored. One failure eg error 400, and the whole backup stops dead. How would you like it to work? I want backup to work hard during hours I specify; 7.00pm-5.00am. This means any failures should be tried again and again until 5.00am. If the cycle was Full and it hit's 5.00am, take special care to resume the full back at 7.00pm. Are there special considerations to this request? Additional information: The internet always has packet loss of >0.0&#37; and will always randomly fail.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=563_
##

**Comment by warwickmm** [comment]
Closing this in favor of:
* Issue #2921 (limit bandwidth during certain times)
* Issue #611 (pause backup during certain times)
