### ISSUE TITLE
During 'building filelist', Stop the current backup seemingly does nothing

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#564]
_From [james.co...@gmail.com](https://code.google.com/u/105829900405594709437/) on February 16, 2012 16:45:12_

What steps will reproduce the problem? 1. start a backup so you see 'building filelist' status
2. on the Quick actions, choose Stop What is the expected output? What do you see instead? Nothing happened, but it should have immediately stopped. What version of Duplicati are you using? On what operating system? latest, win 7 x64 as administrator What backend (destination) are you using? well, the job it was running was a Google Docs one Please provide any additional information below. awesome project, i'm loving it

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=564_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
