### ISSUE TITLE
Instead of random, order the backup by file size (smallest first) and date modified (oldest first)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#565]
_From [james.co...@gmail.com](https://code.google.com/u/105829900405594709437/) on February 16, 2012 17:08:02_

How are you using Duplicati now? File list is randomised. How would you like it to work? File list ordered by a blend of:
+ the backup by file size (smallest first)
+ date modified (oldest first) Are there special considerations to this request? There will be a weighting factor involved, probably for the advanced option. If you find the min and max for each weighting factor, then normalize both values, then either multiply or add them together. Finally, sort the file list by that answer. Additional information: When I update my Accounts.xls and also dump a 50 GB video file on my desktop, I do not want the video file clogging up the backup of my precious Accounts.xls file.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=565_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
