### ISSUE TITLE
Cannot add or import backup - button missing

### ISSUE THREAD

**Issue by Christopher87R** [duplicati/duplicati#5688]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.9.111_canary_2024-11-14
- **Operating system**: Windows 11 24H2 (Build 26100.2314)
- **Backend**: Replace me

## Description

I cannot add or modify backups, a button in the last step is missing.

Only possibility: export the configuration file, edit it manually and import it with the option to save it immediately.

I tested Chrome and Edge in the latest versions, cleared the cache and tried it in Incognito mode

## Screenshots
![image](https://github.com/user-attachments/assets/ffe38afc-47b8-40ca-8587-3ba5b16e8920)

**Comment by ts678** [comment]
![image](https://github.com/user-attachments/assets/e9fecaee-e210-4eb8-af3b-9f36089ba185)

That looks like a scroll bar. Is it just some screenshot oddity or is it really there? What's visible if you scroll down?

Have you ever run any earlier Duplicati release, i.e. is this a new problem or one that has been around for awhile?

**Comment by Christopher87R** [comment]
> @Christopher87R thanks for reporting this. Seems like a critical bug :)
> 
> However, I have not been able to reproduce this. I tried a Windows 11 in Edge and the buttons were there as expected. This part of Duplicati has not been changed for a while, but I would like to make sure it is working.
> 
> Do you see next/previous buttons on the other pages?
> 
> Can you try a developer tool (Ctrl+Shift+I) and see if there are any errors? If you are experienced with the DOM, could you try the picker tool and see if the buttons are there or not (as opposed to being invisible).

Yes, I can see the next/previous buttons on the other pages.

![image](https://github.com/user-attachments/assets/49ba4afe-92f7-432c-b8df-61e9fcf0c53e)
index.html:32 
        
GET http://localhost:8200/ngax/styles/%7B%7Bactive_theme%7D%7D.css net::ERR_ABORTED 404 (Not Found)

Ok, I think the topic can be closed.
I have installed Adguard and apparently this is what caused the problem.

Although I had disabled the protection, the browser extension was not enabled and used an incognito window. Sorry for the inconvenience and thanks for the help

**Comment by kenkendk** [comment]
Thanks for reporting the cause as well.

The failed stylesheet load is a by-product of how AngularJS is implemented.
It will be fixed once we migrate away from AngularJS.
