### ISSUE TITLE
Duplicati not working after update

### ISSUE THREAD

**Issue by joslmar** [duplicati/duplicati#5721]
Good morning, after updating to the latest available version, the duplicate does not work; when I try to access the container, I get the following error message:

![image](https://github.com/user-attachments/assets/86ca8d7a-a3ad-45ce-a16d-4d34731c61c8)

I have tried both options:log in and reload but can't reestablish the connection.

The following messages appear in the container logs:

![image](https://github.com/user-attachments/assets/be5c8341-69ac-41c7-8299-755ae5268cec)

Does anyone know or can help me solve this problem?

Thank you very much

**Comment by lordraiden** [comment]
Same in docker
![imagen](https://github.com/user-attachments/assets/9cc7bdf5-3d9d-4e49-be53-12674174343f)

using     image: lscr.io/linuxserver/duplicati:latest
A few days ago it was working, I tried with the latest beta too

```
Linuxserver.io version: v2.1.0.2_beta_2024-11-29-ls225
Build-date: 2024-11-29T16:39:04+00:00
───────────────────────────────────────
    
***      Missing encryption key, unable to encrypt your settings database     ***
*** Please set a value for SETTINGS_ENCRYPTION_KEY and recreate the container ***
[custom-init] No custom files found, skipping...
Inside getter
Connection to localhost (127.0.0.1) 8200 port [tcp/*] succeeded!
[ls.io-init] done.
Server has started and is listening on port 8200
Use the following link to sign in: http://localhost:8200/signin.html?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXAiOiJTaWduaW5Ub2tlbiIsInNpZCI6InNlcnZlci1jbGkiLCJuYmYiOjE3MzMwNzIyNTIsImV4cCI6MTczMzA3MjU1MiwiaXNzIjoiaHR0cHM6Ly9kdXBsaWNhdGkiLCJhdWQiOiJodHRwczovL2R1cGxpY2F0aSJ9.e-NVLq4HOuQu7HpgiVvTHL2EhZ7IVeE8TuKBxXUOu58
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Duplicati.WebserverCore.Exceptions.UnauthorizedException: Authorization failed due to missing cookie.
         at Duplicati.WebserverCore.Endpoints.V1.Auth.<>c.<<Map>b__3_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<TaskOfTToValueTaskOfObject>g__ExecuteAwaited|92_0[T](Task`1 task)
         at Duplicati.WebserverCore.Middlewares.HostnameFilter.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
         at Duplicati.WebserverCore.Middlewares.LanguageFilter.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteValueTaskOfObject>g__ExecuteAwaited|129_0(ValueTask`1 valueTask, HttpContext httpContext, JsonTypeInfo`1 jsonTypeInfo)
         at Duplicati.WebserverCore.Middlewares.WebsocketExtensions.<>c__DisplayClass0_0.<<UseNotifications>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Duplicati.WebserverCore.Exceptions.UnauthorizedException: Authorization failed due to missing cookie.
         at Duplicati.WebserverCore.Endpoints.V1.Auth.<>c.<<Map>b__3_0>d.MoveNext()
      --- End of stack trace from previous location ---
```

**Comment by ts678** [comment]
> using image: lscr.io/linuxserver/duplicati:latest
A few days ago it was working, I tried with the latest beta too

Any idea what you had a few days ago? Also, latest seems to be 2.1.0.2 Beta. I don't use Docker, but I will see if I can assist...

LSIO images, per `https://hub.docker.com/r/linuxserver/duplicati`, take a CLI_ARGS environment variable for extra options.

The 2.0.9.x Canary versions and the new Beta now require a password for security. Did either of you have one set up before?

Docker is unfortunately dealt with in different ways, and documentation has yet to emerge on the best way to handle things.

[Duplicati.Server.exe](https://docs.duplicati.com/en/latest/07-other-command-line-utilities/#duplicatiserverexe)

> --webservice-password
The password required to access the webserver.

works in old and new Duplicati if you simply have need for a password. If you had them before, I'm not sure they will convert.

This change affects people who were previously on a 2.0.8.x Duplicati (or older), but I don't know what you were using before.

The new Beta is not quite rolled out through Duplicati update channel, but possibly you're relying on some Docker updaters?

Release note is [here](https://forum.duplicati.com/t/release-2-1-0-2-beta-2024-11-29/19577) in forum, or [here](https://github.com/duplicati/duplicati/releases/tag/v2.1.0.2_beta_2024-11-29) in GitHub.

For anyone unable to use LSIO's CLI_ARGS, I had thought `webservice-password`  variable would do, but I'm now doubting that.

[Support resetting webservice password with environment variable #5392](https://github.com/duplicati/duplicati/issues/5392)

**Comment by joslmar** [comment]
Good morning,

Thanks for the answers!

Is there any way I can get that container working again in Docker? I can't backup anything since yesterday.


Best regards,

**Comment by lordraiden** [comment]
> > using image: lscr.io/linuxserver/duplicati:latest
> > A few days ago it was working, I tried with the latest beta too
> 
> Any idea what you had a few days ago? Also, latest seems to be 2.1.0.2 Beta. I don't use Docker, but I will see if I can assist...
> 
> LSIO images, per `https://hub.docker.com/r/linuxserver/duplicati`, take a CLI_ARGS environment variable for extra options.
> 
> The 2.0.9.x Canary versions and the new Beta now require a password for security. Did either of you have one set up before?
> 
> Docker is unfortunately dealt with in different ways, and documentation has yet to emerge on the best way to handle things.
> 
> [Duplicati.Server.exe](https://docs.duplicati.com/en/latest/07-other-command-line-utilities/#duplicatiserverexe)
> 
> > --webservice-password
> > The password required to access the webserver.
> 
> works in old and new Duplicati if you simply have need for a password. If you had them before, I'm not sure they will convert.
> 
> This change affects people who were previously on a 2.0.8.x Duplicati (or older), but I don't know what you were using before.
> 
> The new Beta is not quite rolled out through Duplicati update channel, but possibly you're relying on some Docker updaters?
> 
> Release note is [here](https://forum.duplicati.com/t/release-2-1-0-2-beta-2024-11-29/19577) in forum, or [here](https://github.com/duplicati/duplicati/releases/tag/v2.1.0.2_beta_2024-11-29) in GitHub.
> 
> For anyone unable to use LSIO's CLI_ARGS, I had thought `webservice-password` variable would do, but I'm now doubting that.
> 
> [Support resetting webservice password with environment variable #5392](https://github.com/duplicati/duplicati/issues/5392)

I was using the latest version, the images are updated every night.

**Comment by joslmar** [comment]
> > > using image: lscr.io/linuxserver/duplicati:latest
> > > A few days ago it was working, I tried with the latest beta too
> > 
> > 
> > Any idea what you had a few days ago? Also, latest seems to be 2.1.0.2 Beta. I don't use Docker, but I will see if I can assist...
> > LSIO images, per `https://hub.docker.com/r/linuxserver/duplicati`, take a CLI_ARGS environment variable for extra options.
> > The 2.0.9.x Canary versions and the new Beta now require a password for security. Did either of you have one set up before?
> > Docker is unfortunately dealt with in different ways, and documentation has yet to emerge on the best way to handle things.
> > [Duplicati.Server.exe](https://docs.duplicati.com/en/latest/07-other-command-line-utilities/#duplicatiserverexe)
> > > --webservice-password
> > > The password required to access the webserver.
> > 
> > 
> > works in old and new Duplicati if you simply have need for a password. If you had them before, I'm not sure they will convert.
> > This change affects people who were previously on a 2.0.8.x Duplicati (or older), but I don't know what you were using before.
> > The new Beta is not quite rolled out through Duplicati update channel, but possibly you're relying on some Docker updaters?
> > Release note is [here](https://forum.duplicati.com/t/release-2-1-0-2-beta-2024-11-29/19577) in forum, or [here](https://github.com/duplicati/duplicati/releases/tag/v2.1.0.2_beta_2024-11-29) in GitHub.
> > For anyone unable to use LSIO's CLI_ARGS, I had thought `webservice-password` variable would do, but I'm now doubting that.
> > [Support resetting webservice password with environment variable #5392](https://github.com/duplicati/duplicati/issues/5392)
> 
> I was using the latest version, the images are updated every night.

Hello!

have you managed to get it working again?

Best regards,

**Comment by ilyadel** [comment]
Hello,

I'm using the linuxserver image as well and encountered a similar issue on one of my three servers, but with a different logging error. I had to reset my password using Docker environment variables; CLI_ARGS didn't work.

Try with:

```
environment:

    - DUPLICATI__WEBSERVICE_PASSWORD=changeme


```

**Comment by ilyadel** [comment]
I tried a few syntaxes (probably not the correct ones) with --webservice-password=changeme in the CLI_ARGS environment variable of my Docker Compose file with linuxserver/duplicati:

```
environment:
  - CLI_ARGS= "--webservice-password=changeme"
```
```
environment:
  - CLI_ARGS= '--webservice-password=changeme'
```
I used DUPLICATI__WEBSERVICE_PASSWORD=changeme only once to set a temporary password. I removed it from the Docker Compose file after resetting a new one from the GUI.

I've had this problem (and another one wirh all my FTP backups, which I'm still "debugging") since updating to v2.1.0.2_beta_2024-11-29-ls225, I haven't changed anything recently other than that.

**Comment by lordraiden** [comment]
> Hello,
> 
> I'm using the linuxserver image as well and encountered a similar issue on one of my three servers, but with a different logging error. I had to reset my password using Docker environment variables; CLI_ARGS didn't work.
> 
> Try with:
> 
> ```
> environment:
> 
>     - DUPLICATI__WEBSERVICE_PASSWORD=changeme
> ```

I fixed the issue following this.

BTW, how do you get the new WEBUI?
![imagen](https://github.com/user-attachments/assets/15915c72-8913-4c1c-95ab-9097918e53ed)

**Comment by joslmar** [comment]
Good afternoon,

Will this problem be solved soon with an update?

Best regards,

**Comment by joslmar** [comment]
> > Hola,
> > También estoy usando la imagen de Linux Server y encontré un problema similar en uno de mis tres servidores, pero con un error de registro diferente. Tuve que restablecer mi contraseña usando variables de entorno de Docker; CLI_ARGS no funcionó.
> > Prueba con:
> > ```
> > environment:
> > 
> >     - 
> > ```
> 
> Solucioné el problema siguiendo esto.
> 
> Por cierto, ¿cómo se obtiene la nueva WEBUI? ![imagen](https://private-user-images.githubusercontent.com/17175395/391602268-15915c72-8913-4c1c-95ab-9097918e53ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTU2OTksIm5iZiI6MTczMzE1NTM5OSwicGF0aCI6Ii8xNzE3NTM5NS8zOTE2MDIyNjgtMTU5MTVjNzItODkxMy00YzFjLTk1YWItOTA5NzkxOGU1M2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDE2NzI1ZTI3NGVjMGI1NzRmYTlmNDNlYmQxNzlkZDhjY2Y3M2U3Y2ExOTZmYjMzZTliMDRhMzczNzZjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TKPG_nbyhbMfvZBveBJBkMxHz9cOYXK4b6orSKfHmxM)

Good afternoon,

The solution you propose is to put the following command in ssh?:

DUPLICATI__WEBSERVICE_PASSWORD=changeme


Best regards,

**Comment by ilyadel** [comment]
In docker compose file or as env option in docker command 
```
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - DUPLICATI__WEBSERVICE_PASSWORD=changeme
    volumes:
      - ./config:/config
      - ./data:/source
    ports:
      - 8200:8200
```

**Comment by joslmar** [comment]
> In docker compose file or as env option in docker command
> 
> ```
> services:
>   duplicati:
>     image: lscr.io/linuxserver/duplicati:latest
>     container_name: duplicati
>     environment:
>       - PUID=0
>       - PGID=0
>       - DUPLICATI__WEBSERVICE_PASSWORD=changeme
>     volumes:
>       - ./config:/config
>       - ./data:/source
>     ports:
>       - 8200:8200
> ```


Good afternoon,

Thanks for your answer!

Ok, I didn't understand it well; it's just a matter of changing the variable in the container's docker compose. Should this solve the problem?

I'm away from home for work, at the end of the week when I get back I'll try it and let you know if the problem has been solved.


Best regards,

**Comment by ts678** [comment]
> Will this problem be solved soon with an update?

You would have to hear from the developer, but I don't think it's a bug (despite the automatic label). Password is now required. Possibly a better way to smooth it out can be found, but as I don't use Docker, or design the code, more expertise is necessary.

Non-Docker experience is smoother, and in some cases you see a nice popup to warn you of new need, and open up Settings.
Docker IMO suffers from being in a container, and I'm not sure if a similar or somehow improved experience can be produced.

[Increasing security for Duplicati’s web server](https://forum.duplicati.com/t/increasing-security-for-duplicati-s-web-server/18871)
explains why I suspect the password-required will stay, but maybe the devs can figure out some more transparent way to do it.

The GUI TrayIcon can bypass the password by default. Server can't do that (no icon to drive), and Docker might be the hardest.
It might also be the most likely to have an update without any opportunity to read release notes, changes, etc., so bad combo.

**Comment by kenkendk** [comment]
I can see a few people chimed in with the answers.
The linuxserver images have the CLI_ARGS, but the regular Duplicati Docker image does not.

I have written a docs page on how to set up the passwords with Docker here:
https://docs.duplicati.com/detailed-descriptions/using-duplicati-from-docker

For more details on how to generally deal with the password, there is a docs page here:
https://docs.duplicati.com/detailed-descriptions/duplicati-access-password

> BTW, how do you get the new WEBUI?
The image you have posted is from the [Duplicati Console](https://app.duplicati.com), offering monitoring and remote management.

But there is a new experimental UI in the beta, you can access it with:
```
http://localhost:8200/theme.html
```

It is still a bit early, but bugs and feature requests for this UI can be logged here:
https://github.com/duplicati/ngclient

I am closing this issue as it has a solution, but we can re-open if there are still issues.

**Comment by eric-fps-dev** [comment]
Try this: 

`services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SETTINGS_ENCRYPTION_KEY=password123
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD=password
    volumes:
      - ./config:/config
      - ./backups:/backups
      - ./source:/source
    ports:
      - 8200:8200
    restart: unless-stopped`
