### ISSUE TITLE
Support for Amazon Cloud Drive service

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#598]
_From [bladem84](https://code.google.com/u/bladem84/) on March 31, 2012 20:23:09_

Hi, is it possible to add Amazon Cloud Drive support on Duplicati?

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=598_

**Comment by ApetersDev** [comment]
this should be the cloud drive api https://developer.amazon.com/public/apis/experience/cloud-drive

**Comment by virgiliu** [comment]
Indeed, that seems to be the API. Here's the RESTful API https://developer.amazon.com/appsandservices/apis/experience/cloud-drive/content/restful-api-getting-started

I'd really like to see this implemented.

**Comment by kenkendk** [comment]
After a quick look through the documentation, it seems that only approved apps can get access to Amazon Cloud Drive:

https://developer.amazon.com/public/apis/experience/cloud-drive/content/developer-guide

I have written the Amazon team and asked if Duplicati could eventually be approved.

**Comment by kenkendk** [comment]
The Amazon support did not say if it would be possible for Duplicati to be whitelisted, just that I need to apply for it.

Looking at the service, it looks like a slightly more expensive front for Amazon S3. Are there any particular reasons for using Amazon Cloud Drive, rather than S3?

**Comment by steilerDev** [comment]
In the US ACD provides unlimited storage for 60$/year. I think this makes it the perfect provider for Duplicati.

**Comment by scspijker** [comment]
Clouddrive is marketed as a consumer backup solution and much more appealing then calculating your way through S3 storage and bandwidth costs.

Also: Unlimited is a good term in consumer land.

I expect the API not to be much different from S3..

**Comment by kelna** [comment]
I'm using ACD for backup with Duplicati on Ubuntu right now. Let me give a little know-how. 

I used Deja Dup first, but it strangely deletes everything from ACD after I reconnect, if I don't finish the initial backup in one round -- what is impossible at such a low bandwidth. Amazon doesn't provide more than 250 kiB/s which is really-really a shame. But at least it's cheap. Oh, and unlimited seems to be meaning 100 TB according to what Netdrive shows, which is quite enough. I really haven't expected more than 10 TB as "fair use". OK, cut the crap, here is my method:

At this point we need proprietary software to use ACD as a backup solution. 

1. Make a virtual PC with Windows, if your host OS is Linux.
2. Install Netdrive2 on Windows. As far as I know, this is the only program (or at least the best) that can mount ACD as a network or local drive. This means that every file transfer happens transparently like it would between local drives, without keeping the transferred files on the local disk. This is crucial since we want to make an online backup, not an offline. Mount the ACD as a given drive letter (not automatic), let's say Y:, because y not.

If you are using Windows, you are good to go and start backing up to your Y: drive. In case of Linux, we need a little more effort.

3. Install Filezilla FTP server on the emulated Windows. Start a connection. Add a new user, enable it, then add Y: as a shared folder. Grant the desired access rights to your user to that folder.
4. You need to set a bridged network adapter in VirtualBox to give proper connection to your Windows. Check the IP address of your Windows.
5. Start Duplicati in your host OS, and set the IP as destination and FTP as protocol. You're ready to roll!

I hope I could help you guys. And I also hope that we won't need this workaround too long.
Keep up the good work, and thanks for the efforts, devs! :smile:

**Comment by kelna** [comment]
BTW here is a very promising project to make a "Netdrive for Linux":
https://github.com/yadayada/acd_cli/issues/77
Maybe it can be of help.

**Comment by kelna** [comment]
And yes, yadayada did it! acd_cli can R/W ACD now! Check it out:
https://github.com/yadayada/acd_cli

**Comment by kelna** [comment]
Maybe acd_cli could be included in duplicati to be able to backup to ACD directly.

**Comment by utdrmac** [comment]
+1 for ACD support. ACD is cheaper than CrashPlan (built-in encryption). With Duplicati comes a much better client too. acd_cli works nice but there's no encryption support there. @kenkendk check out how acd_cli handles [app authorization](https://acd-cli.readthedocs.org/en/latest/authorization.html). It's quite simple and increases security in that only the user of duplicati has authorization, rather than the app "being approved."

**Comment by Jamyn** [comment]
This would be amazing. I'd donate to the project for this feature alone.

**Comment by kenkendk** [comment]
@utdrmac: Thanks! 
It appears that I can forego all the whitelisting stuff, and instead use OAuth2 access directly.
Very nice considering I have no intention of distributing an app through the Amazon store, which is what all documents for CloudDrive lead to.

**Comment by kenkendk** [comment]
I have now added and tested the ACD backend.
It works, but I still need another whitelisting before I can make it available, as the non-whitelisted version is rate-limited.

**Comment by kelna** [comment]
Amazing! Thanks so much! I can't wait to test it. :)

**Comment by hcjehg** [comment]
Wow, super. 

It seems https://duplicati-oauth-handler.appspot.com/ does not yet support Amazon Cloud Drive. Is there any way to get the oauth token before that is set up ?

Best regards
HC

**Comment by kenkendk** [comment]
If you happen to have the amazon client_id and client_secret of a working security profile, you can set up your own OAuth Handler from the source here: 
https://github.com/duplicati/oauth-handler

Use `--oauth-url=https://your-handler-name-appspot.com/refresh` in Duplicati to use your own handler.


Otherwise you need to wait until Amazon approves my request. Once they do that, I will activate Amazon support on the oauth handler and you can use it from there. Amazon explicitly states that I cannot make it available before they have approved the request.

I would not recommend trying to circumvent it by registering an application, because you get "test rate limiting", so you cannot use it for production.

**Comment by hcjehg** [comment]
@kenkendk

Thanks for this info - hoping that Amazon works fast :-)

I'll wait till it is white listed - hopefully :-D

Ill betterstart looking for the link to paypal :-)

Takker og bukker

Super arbejde der!

**Comment by kelna** [comment]
ACD support will be available in the 2.0 version or only in 1.3?

**Comment by kenkendk** [comment]
It will be in version 2.0 only.

**Comment by kenkendk** [comment]
Amazon has now put Duplicati in the app review queue, and state "This process may take several weeks".

Lets see what happens :)

**Comment by johim** [comment]
Can I use Duplicati with ACD without the app being approved by Amazon? Perhaps I can use the oauth token from ACD_CLI ?

**Comment by utdrmac** [comment]
Could you provide an example of how you are using ACD to perform a backup?

```
root@gasgiant:/data/Transmission/CompletedTorrents# duplicati-cli backup --verbose amzcd://gasgiant/torrents2/ /data/Transmission/CompletedTorrents/
Input command: backup
Input arguments:
	amzcd://gasgiant/torrents2/
	/data/Transmission/CompletedTorrents/

Input options:
verbose:

Backup started at 1/4/2016 1:05:25 PM

Enter encryption passphrase:

Confirm encryption passphrase:
Fatal error => Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
```

**Comment by kenkendk** [comment]
@johim: You need an OAuth token. There is no support for providing a token directly, as tokens expire after one hour anyway.

You need to run your own OAuth server to use Amazon Cloud Drive.

@utdrmac: It looks right, but you need to supply --authid=*****. The error was supposed to be "You need an AuthID, you can get it from: https://duplicati-oauth-handler.appspot.com?type=amzcd", but the code providing the message had a bug, so you get the confusing FormatException instead.

**Comment by utdrmac** [comment]
So, the only way to test ACD support is to run your own OAuth server to get the authid token and refresh it every hour?

acd_cli has some refresh mechanism built-in for this. On my NAS, /root/.cache/acd_cli/oauth_data shows my current access_token and a refresh_token. Presumably, an API method is called using the refresh token which gets a new token, thus extending you for another hour.

**Comment by kelna** [comment]
> Amazon has now put Duplicati in the app review queue, and state "This process may take several weeks".

Is there any news on this? Can we expect it to be accepted in the close future?

**Comment by utdrmac** [comment]
After that ridiculously painful OAuth setup process in which one must 1) Get a google app account. 2) Install the SDK. 3) clone the repo noted above. 4) register as a developer with Amazon 5) create a client_id with all the correct settings and such. 6) configure google app. 7) deploy. 8) load and click through, I finally got an auth ID and attempted to do a backup only to get a new error message:

(That's not the EXACT authid, I changed a few letters/numbers for public posting purposes.)

```
root@gasgiant:~# duplicati-cli --debug-output --verbose --authid="eec9a22a3f98b221d3910ec42e987234:R2LlQv_c1CvAvBy5nDqEf" backup amzcd://gasgiant/torrents2/ /data/Transmission/CompletedTorrents/
Input command: backup
Input arguments:
	amzcd://gasgiant/torrents2/
	/data/Transmission/CompletedTorrents/

Input options:
debug-output:
verbose:
authid: eec9a22a3f98b221d3910ec42e987234:R2LlQv_c1CvAvBy5nDqEf

Backup started at 1/10/2016 10:08:05 PM

Enter encryption passphrase:

Confirm encryption passphrase:
Checking remote backup ...
  Listing remote folder ...
Operation List with file  attempt 1 of 5 failed with message: Failed to authorize using the OAuth service: No such key. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=amzcd => System.Exception: Failed to authorize using the OAuth service: No such key. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=amzcd ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
  at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () <0x41f28870 + 0x0010b> in <filename unknown>:0
  at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () <0x41f97300 + 0x00163> in <filename unknown>:0
  at Duplicati.Library.JSONWebHelper.GetResponse (Duplicati.Library.Utility.AsyncHttpRequest req, System.Object requestdata) <0x420168e0 + 0x003fb> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Duplicati.Library.OAuthHelper.get_AccessToken () <0x42015990 + 0x006d3> in <filename unknown>:0
  at Duplicati.Library.OAuthHelper.CreateRequest (System.String url, System.String method) <0x42015630 + 0x0006f> in <filename unknown>:0
  at Duplicati.Library.JSONWebHelper.GetJSONData[T] (System.String url, System.Action`1 setup, System.Action`1 setupreq) <0x42015540 + 0x00038> in <filename unknown>:0
  at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.RefreshMetadataAndContentUrl () <0x420151f0 + 0x0019b> in <filename unknown>:0
  at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.get_MetadataUrl () <0x420150e0 + 0x0001f> in <filename unknown>:0
  at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.List () <0x42014b50 + 0x00033> in <filename unknown>:0
  at Duplicati.Library.Main.BackendManager.DoList (Duplicati.Library.Main.FileEntryItem item) <0x42014110 + 0x00068> in <filename unknown>:0
  at Duplicati.Library.Main.BackendManager.ThreadRun () <0x41ffeb50 + 0x00367> in <filename unknown>:0
```

I see a 404 Not Found error in there but I verified the path in my ACD does exist. Thoughts?

**Comment by utdrmac** [comment]
Ah. I'll read better. Forgot to include my --oauth-url but that gave a new error:

```
root@gasgiant:~# duplicati-cli --debug-output --verbose --authid="1c9a3f7bcXXXXXXb8138acec27:hHq2PXXXXXXMuWpPo" --oauth-url=https://acdoauthtest.appspot.com/refresh backup amzcd://gasgiant/torrents2/ /data/Transmission/CompletedTorrents/
Operation List with file  attempt 1 of 5 failed with message: The remote server returned an error: (403) Forbidden. => System.Net.WebException: The remote server returned an error: (403) Forbidden.
```

This is a 403 potentially coming from my appspot url? Attempting to access https://acdoauthtest.appspot.com/refresh produces a 500 error code.

**Comment by utdrmac** [comment]
So using curl --verbose I was able to test my appspot.com/refresh page giving it my authid which was returning an error code 403 and a message in the headers that said "too many requests" or something. I changed the ratelimit in my appspot config.yml and redeployed. Tested /refresh again and that was successful with curl. It returned a json string with an access_token and some other parameters.

The error message I got about rate-limiting should be a bit more prominent within duplicati.

Still not working though. I'm not sure who is sending me this 403. Amazon?

```
Operation List with file  attempt 1 of 5 failed with message: The remote server returned an error: (403) Forbidden. => System.Net.WebException: The remote server returned an error: (403) Forbidden.
```

**Comment by utdrmac** [comment]
I've got --log-file=/tmp/duplicati.log --log-level=Profiling --debug-output --verbose; Is there no way to get output of all the URL/API calls duplicati is making to external sites?

**Comment by utdrmac** [comment]
Woo! Success! Earlier in my first attempts to get my own OAuth working, Amazon's response was "bad scope request" or something like that. After re-adding back 'clouddrive:read_all' and re-creating my oauth token, it works!

I don't get why Amazon needs to whitelist your request when I was able to do all this in about 1 hour?

**Comment by utdrmac** [comment]
Seems you don't need to re-oauth every hour. The token I generated last night still works. I'm guessing this is the 'refresh' functionality?

**Comment by kenkendk** [comment]
Wow, you did it :)

When I tested the ACD with the backendtester tool, it would give me the 403 errors after some 40-50 requests, and then I needed to stop the testing for a few minutes before it would resume.

If I were to allow other users to access the service, even a few users (10 or so) would trigger the 403, essentially making the service useless. So until Amazon decides to "enable production rate" I will not enable the Amazon OAuth service on my instance.

You are free to offer your service to others (unless Amazon says different), but you may hit the limit I described if you have a few users.

There are two oauth tokens, the access token and the refresh token. The access token is delivered to Duplicati and allows it to send requests, but it expires every hour. The refresh token is stored encrypted on the OAuth server, and can be used to generate a new access token.

In principle, you can store the refresh token on the client as well, but the client needs the server secret to request a new access token. Hence the server will be required anyways and will always see the refresh token. The authid is simply a username/password that is used to locate and decrypt the refresh token on the server. 

The encryption is used to protect against cold attacks, where someone gets hold of (a copy of) the server datastore.

**Comment by kenkendk** [comment]
Good news everybody!

Amazon has approved Duplicati and there are now production-level rate limits, so I opened up for creating an AuthID on the main OAuth server.

The latests binaries are here:
http://updates.duplicati.com/preview/duplicati-2.0.0.96_preview_2015-12-17.zip

And the authid can be created from here:
https://duplicati-oauth-handler.appspot.com/?type=amzcd

**Comment by hcjehg** [comment]
:-) Wow wow wow

**Comment by hcjehg** [comment]
Hmmm, Amazon Cloud Drive seems to no longer be unlimited everything?

:-(

**Comment by AlexBaker-** [comment]
Still looks unlimited to me.  See screenshot below.  What differences are you experiencing?

![screenshot from 2016-01-14 10-47-46](https://cloud.githubusercontent.com/assets/9062757/12321076/8dda065c-baac-11e5-896e-285a11749f1e.png)

**Comment by hcjehg** [comment]
Yes but when you Start your 3 months free trail, you get to to your cloud drive. Select Manage storage. Your storage plan is still what it was before, mine 5GB Total. Click the Change your plan button:

![image](https://cloud.githubusercontent.com/assets/12269445/12321783/51ca90ce-bab0-11e5-95b4-49e50b19cc75.png)

People have been mentioning that it might be different depending on what country you are in (I'm in France). What are you getting?

HC

**Comment by Jamyn** [comment]
Houston, TX:
![amazon_cloud](https://cloud.githubusercontent.com/assets/696574/12322104/c1a2574e-ba77-11e5-994e-6c0dd2bc55d1.png)

**Comment by hcjehg** [comment]
Me want! :-) but no cigar in France... :-/

**Comment by AlexBaker-** [comment]
@hcjehg Are you using Amazon.co.uk, or Amazon.com directly?

**Comment by hcjehg** [comment]
@AlexBaker-  No matter where I start (.com or .co.uk) I am being re-routed to amazon.fr

**Comment by seals55** [comment]
Is this working for anyone running on linux (Ubuntu 15.10, mono 4.0.3)? I'm getting time-out when testing destination and when manually specifying. I've created a new oauth as it suggests as well.

Failed to connect: Failed to authorize using the OAuth service: GetResponse timed out. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=amzcd


System.Exception: Failed to authorize using the OAuth service: GetResponse timed out. If the problem persists, try generating a new authid token from: https://duplicati-oauth-handler.appspot.com?type=amzcd ---> System.Net.WebException: GetResponse timed out ---> System.Net.WebException: Aborted.
at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.OnAsync (IAsyncResult r) [0x00000] in <filename unknown>:0 
--- End of inner exception stack trace ---
at Duplicati.Library.Utility.AsyncHttpRequest+AsyncWrapper.GetResponseOrStream () [0x00000] in <filename unknown>:0 
at Duplicati.Library.Utility.AsyncHttpRequest.GetResponse () [0x00000] in <filename unknown>:0 
at Duplicati.Library.JSONWebHelper.GetResponse (Duplicati.Library.Utility.AsyncHttpRequest req, System.Object requestdata) [0x00000] in <filename unknown>:0 
--- End of inner exception stack trace ---
at Duplicati.Library.OAuthHelper.get_AccessToken () [0x00000] in <filename unknown>:0 
at Duplicati.Library.OAuthHelper.CreateRequest (System.String url, System.String method) [0x00000] in <filename unknown>:0 
at Duplicati.Library.JSONWebHelper.GetJSONData[EndpointInfo] (System.String url, System.Action`1 setup, System.Action`1 setupreq) [0x00000] in <filename unknown>:0 
at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.RefreshMetadataAndContentUrl () [0x00000] in <filename unknown>:0 
at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.get_MetadataUrl () [0x00000] in <filename unknown>:0 
at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.List () [0x00000] in <filename unknown>:0 
at Duplicati.Library.Main.BackendManager.DoList (Duplicati.Library.Main.FileEntryItem item) [0x00000] in <filename unknown>:0 
at Duplicati.Library.Main.BackendManager.ThreadRun () [0x00000] in <filename unknown>:0

**Comment by kelna** [comment]
hcjehg, try it with US VPN (or Tor).

**Comment by utdrmac** [comment]
@seals55 paste the complete command you are executing

**Comment by seals55** [comment]
I exported the job and changed keys ;)

mono "/opt/duplicati/Duplicati.CommandLine.exe" backup "amzcd://DuplicatiBackups/SEALSBUNTU/Root?authid=AUTHID" "/root/" --backup-name="Backup Root to ACD (1)" --dbpath="/root/.config/Duplicati/EUDPLDRAUG.sqlite" --encryption-module="aes" --passphrase="PASS" --dblock-size="50mb" --disable-module="console-password-input" --exclude="/root/.config/Duplicati/" --exclude="/root/VirtualBox VMs/"

**Comment by utdrmac** [comment]
Your command looks odd to me. See my comments above for how I ran it 
with the authid parameters and oauth-provider URL.

**Comment by steilerDev** [comment]
I am currently running a backup, using a command very similiar to yours @seals55, only differences: No spaces in the backup name, no excludes and no disable-module.

**Comment by utdrmac** [comment]
My command, for comparative. How come you guys have to execute with 
mono? Did you not install the distro-ball?

```
duplicati-cli --debug-output --verbose --authid="$AUTHID" 
--oauth-url=http://acdoauthtest.appspot.com/refresh backup 
amzcd://gasgiant/Backup/ /data/Backup/
```

Frank Steiler wrote:

**Comment by steilerDev** [comment]
There is a distro-ball? How/Where do I get it? The file @kenkendk linked only contains the exe's, or do I miss something?

Now, that ACD is whitelisted with amazon we don't need any oauth url, do we (Well apparently I don't need it :D )? You can get your oauth token directly from amazon through the oauth url above. It could still expire after an hour (my backup isn't running that long yet), we'll see.

**Comment by utdrmac** [comment]
There's a distro-ball if you compile it, as I did. If the oauth URL 
@kenkendk is providing/hosting is hard-coded within, then you probably 
don't need to provide it.

Frank Steiler wrote:

**Comment by kenkendk** [comment]
@seals55 if you can make a connection to the webpage, then I think there is no network blocking issues.
Can you do either:
`curl https://duplicati-oauth-handler.appspot.com`
or
`wget https://duplicati-oauth-handler.appspot.com`

I assume you can, which means that there is some issue with Duplicati instead, but most likely a problem with mono. Can you then try:
`mono "/opt/duplicati/Duplicati.CommandLine.exe" test "amzcd://DuplicatiBackups/SEALSBUNTU/Root?authid=AUTHID" --oauth-url=http://www.google.com`

Of course that won't work, but it will reveal if the https part is the problem or the network connection itself is causing issues.

**Comment by seals55** [comment]
OK I think I'm good now, at least from the command line. I'm thinking the UI test button isn't using the --accept-specified-ssl-hash option.

I'm guessing my Ubuntu which has been upgraded twice had a funky mono installed. I was not able to install the version from apt-get (I didn't want to force remove it and uninstall other apps).

I built/upgraded to mono 4.2.1. I believe this gave me the error message, where the older one didn't:

`Failed to connect: The server certificate had the error RemoteCertificateChainErrors and the hash 90B85... If you trust this certificate, use the commandline option --accept-specified-ssl-hash=90B85... to accept the server certificate anyway.You can also attempt to import the server certificate into your operating systems trust pool.You may want to import a set of trusted certificates into the Mono certificate store.Use the command:    mozroots --import --syncRead more: http://manpages.ubuntu.com/manpages/natty/man1/mozroots.1.html`

Also running on command line gave me a similar message:
`No certificates found, you can install some with this command:
    mozroots --import --sync
Read more: http://manpages.ubuntu.com/manpages/natty/man1/mozroots.1.html`


I still have an issue testing the destination in the UI, but when I exported the same job, I successfully started uploading to ACD

`mono "/opt/duplicati/Duplicati.CommandLine.exe" backup "amzcd://DuplicatiBackups/SEALSBUNTU/Root?authid=abcd" "/root/" --backup-name="Backup Root to ACD (1)" --dbpath="/root/.config/Duplicati/EUDPLDRAUG.sqlite" --encryption-module="aes" --passphrase="abcd" --dblock-size="50mb" --accept-specified-ssl-hash="90B85..." --disable-module="console-password-input" --exclude="/root/.config/Duplicati/" --exclude="/root/VirtualBox VMs/"`

I can see files being created in ACD via the web page.

**Comment by seals55** [comment]
Hi,

Just to follow-up, I can define the job in the web interface (skipping the test of the ACD destination). I set it to no schedule.

Running via web page fails, with suggestion to try new OAUTH key.
Let me note that I am using the web page remotely, as my linux server doesn't have a UI.

I export the job as command line.
Run command line without issue. Multiple runs, no problems.

I can use the web page to restore files, just not to run the backup.

thanks,
Chris

**Comment by livingfield** [comment]
I've been following this discussion for the past few months but I've never used Duplicati, and it seems like people are describing complicated hacks to make it work with ACD. Now that Duplicati is whitelisted, is it simpler to setup a backup to ACD? What are the steps? 

I'm not sure what OAUTH is. Is this description of OAUTH used with One Drive applicable for ACD too?
http://www.duplicati.com/news/howduplicatisonedriveserviceworks

I'd like to have Duplicati backing up my QNAP TS-251 to ACD. If it's too difficult to get Duplicati running on the QNAP directly, then I can run it in a container or a virtual machine.

Can anyone point me in the right direction?

**Comment by kenkendk** [comment]
@livingfield: Yes, it should be trouble free now that it is whitelisted. OAuth is a protocol for authenticating with various services. The description you found is also applicable to the ACD login process. You need at least version 2.0.0.96 for ACD support.

QNAP seems to have some issues with an old version of Mono, see issue #1535.

**Comment by kelna** [comment]
My version is 2.0.0.91 and it doesn't find updates, so I can't update to .96. Should I build it or how can I get it?

**Comment by steilerDev** [comment]
There is a link given above: http://updates.duplicati.com/preview/duplicati-2.0.0.96_preview_2015-12-17.zip
This binary shows the version `Version: 2.0.0.96- 2.0.0.96_preview_2015-12-17`

**Comment by kelna** [comment]
Oh thanks, how could I miss this?

**Comment by henfri** [comment]
Hello,

where can I find documentation on using duplicati with Amazon Cloud drive?

Greetings,
Hendrik

**Comment by BirokratskaZila** [comment]
I'm also interested in Amazon Cloud drive setup. I've got my authID and everthing but the files won't start uploading.
