### ISSUE TITLE
Wishlist: Monitor file/folder changes

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#60]
_From [Col...@gmail.com](https://code.google.com/u/104596042515694179283/) on April 28, 2009 11:57:44_

Here's a low priority feature request: Have an option to run a backup
whenever a file/folder is modified. This would be used instead of setting a
schedule to run the backup. This would be sort of "real time" backup.

I think something like this could be done with the .NET FileSystemWatcher
class.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=60_

**Comment by vlsi** [comment]
@kenkendk , would you please clarify why the issue has been closed?

I wonder if something like https://facebook.github.io/watchman/ would suit continuous data protection.

**Comment by kenkendk** [comment]
I closed this because it was created for the Duplicati 1.3.x version.
There is some support for this in Duplicati 2.0, but it is not yet ready. There are options meant to pass the list of changed files into the backup process.

There is a built-in `FileSystemWatcher` in .Net/Mono that "does the right thing" on different filesystems. On Windows we can also use USN to build the list to avoid the repeated filesystem scanning.
