### ISSUE TITLE
Passphrase in advanced options is fully displayed

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#606]
_From [dc.des...@gmail.com](https://code.google.com/u/114746244506366832476/) on April 13, 2012 06:48:38_

What steps will reproduce the problem? 1.  Create a backup but use the advanced options to set the passphrase
2.  Edit/view the backup and go to the passphrase option 3. What is the expected output? What do you see instead? I expected a row of asterix, I saw the passphrase What version of Duplicati are you using? On what operating system? 1.3, Windows 7 What backend (destination) are you using? S3 Please provide any additional information below. I use different passphrases for different machines and was doing a test restore of a backup from another machine.  I used the advanced options to avoid impacting my existing backups.  I think this is how that should be done?

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=606_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
