### ISSUE TITLE
Cloudfiles will not auto-create bucket

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#607]
_From [dus...@dustinlambert.com](https://code.google.com/u/114173709495359917541/) on April 26, 2012 13:27:28_

What steps will reproduce the problem? 1. Use command line to create backup against cloudfiles container that doesn't exist
2. Eventually returns 404 not found
3. Attempting to use the "create-folder" command eventually times out
4. If the container does exists, duplicati works fine What is the expected output? What do you see instead? If auto create folders is enabled, duplicati should create the container What version of Duplicati are you using? On what operating system? 1.3 on ubuntu x64 What backend (destination) are you using? coudfiles Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=607_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
