### ISSUE TITLE
Support for Google Drive

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#615]
_From [marcomsousa](https://code.google.com/u/marcomsousa/) on May 08, 2012 19:45:48_

Please support for Google Drive

Google Drive API Library https://developers.google.com/drive/downloads

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=615_

**Comment by nathancheek** [comment]
Are there any plans to implement the Google Drive API?  According to Google, the googledocs API will be discontinued April 20, 2015.

https://developers.google.com/google-apps/documents-list/

http://googleappsdeveloper.blogspot.com/2014/12/reminder-to-migrate-to-updated-google.html

**Comment by kenkendk** [comment]
The update to OAuth2 is in progress and tracked in issue #1347.
