### ISSUE TITLE
Setting the Duplicati temporary folder to a non-existing folder crashes Duplicati

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#618]
_From [MarcoSub...@gmail.com](https://code.google.com/u/110766674233410969507/) on May 14, 2012 17:34:45_

What steps will reproduce the problem? 1. Schedule a backup with a File backend, on a directory you can remove (e.g. USB hard disk, quite a common setup)
2. Remove the directory (e.g. unmount the external HDD)
3. Run the backup task What is the expected output? What do you see instead? Expected "Could not find destination directory" message. Duplicati crashes instead. It would be nice to have an option to retry the backup task, so as to remind to connect the USB disk. What version of Duplicati are you using? On what operating system? My version is 1.3.1, on Windows 7 x64 Ultimate What backend (destination) are you using? File backend Please provide any additional information below. In a quite common configuration, I use Duplicati to make a backup of my laptop. Among the three backends I have, one is a USB hard disk, which I connect only for backups. I understand that the start-up sleep time is meant to let the computer connect to devices/networks needed to reach the destinations of the backup tasks, but it is not the case with the computer being put to sleep. If I schedule a backup in the morning and put the computer to sleep without the USB hard disk connected, when I resume the pc in the morning duplicati crashes with a DirectoryNotFoundException, supposedly because it can't find the hard disk. This exception could be handled, and the user may be prompted to check device/network availability and provided with a retry option.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=618_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
