### ISSUE TITLE
Duplicati gets stuck at "building filelist" , uses over 3GB of RAM.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#619]
_From [Chieftai...@gmail.com](https://code.google.com/u/100739234006866607177/) on May 15, 2012 14:51:07_

What steps will reproduce the problem? 1. Install and run Duplicati (1.3.1.1205)
2. Define new backup, select whole drive (or any other dir with LOTS of files, 300000+ )
3. Run backup

What is the expected output? 
Memory footprint of the process should be relatively small or moderate.

What do you see instead?
After about 20 minutes of "building filelist" Duplicati uses more than 3GB of RAM! Had to kill the process because the swap partition kicked in. What version of Duplicati are you using? On what operating system? Duplicati version: 1.3.1.1205
OS: Windows XP 64bit eng What backend (destination) are you using? FTP Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=619_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
