### ISSUE TITLE
Sorting list of "Anstehende Sicherungen "

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#622]
_From [thomas.s...@gmail.com](https://code.google.com/u/101401119752284674446/) on May 19, 2012 09:18:02_

Would be great to have the chance to sort that list by date or by "Sicherungs-Satz"

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=622_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
