### ISSUE TITLE
Removing entries from "Abgeschlossene Sicherungen"

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#623]
_From [thomas.s...@gmail.com](https://code.google.com/u/101401119752284674446/) on May 19, 2012 09:19:29_

Would be great to remove selected entries by hand from that list.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=623_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
