### ISSUE TITLE
Linux unable add hidden folders to filters

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#634]
_From [alistair...@gmail.com](https://code.google.com/u/110337485894780285592/) on May 30, 2012 05:24:57_

What steps will reproduce the problem? 1. regardless of nautilus or file explorer setting eg set hidden folders visible is not reflected in filter selection.

What is the expected output? 
.directory = visible
What do you see instead?
.directory = hidden What version of Duplicati are you using? On what operating system? 1.3.2/Ubuntu 11

Thanks,
Alistair.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=634_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
