### ISSUE TITLE
Setting an 'Each backup size limit' of more than 1024MB rounds down to nearest GB.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#641]
_From [sam.fick...@gmail.com](https://code.google.com/u/110478256204228457810/) on June 07, 2012 12:51:44_

What steps will reproduce the problem? 1. Run through the setup wizard as per normal
2. Activate the 'Each backup size limit' option and change the amount to a figure over 1024MB (eg; 1500MB)
3. Click next
4. Click back What is the expected output? What do you see instead? I expected to see the 1500MB remain as set, however the measurement units are changed to GB and the figure is is rounded down to 1.  If I enter 2500MB, the result is 2GB.  If you enter 1500GB, the result is 0 bytes.
This also happens when using other units (eg; bytes, kb) What version of Duplicati are you using? On what operating system? Duplicati v1.3.2, Windows 7 x64 What backend (destination) are you using? Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=641_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
