### ISSUE TITLE
Empty source directory on first backup configuration with local backend

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#642]
_From [ClemensB...@googlemail.com](https://code.google.com/u/109976763450030801363/) on June 08, 2012 19:25:27_

What steps will reproduce the problem? 1. Install duplicati and start assistant
2. On 3rd page: use the proposed user directories (My documents, My Pictures, Files on desktop)
3. Go on configuring the backup with a local backend
4. Check on the summary page that the source directory line is empty What is the expected output? What do you see instead? The proposed user directories are taken into account and are used for this backup configuration.
After finishing the assistant, the main status page is coming up and seems to be in an endless loop with the message "Creating file ist..." What version of Duplicati are you using? On what operating system? Ubuntu 12.04 - Duplicati Version 1.3.2 What backend (destination) are you using? local file Please provide any additional information below. Problem of summary page with empty source directory line can be reproduced with Win32 version 1.3.2.

**Attachment:** [Duplicati_Summary_Page.png.png](http://code.google.com/p/duplicati/issues/detail?id=642)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=642_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
