### ISSUE TITLE
Duplicati prevent pc from shutting down

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#644]
_From [shtripok](https://code.google.com/u/shtripok/) on June 10, 2012 21:26:00_

What steps will reproduce the problem? 1. have running backup
2. try to shutdown pc
3. kill-task window will appear What is the expected output? What do you see instead? pc should be shutdowned

Maybe, it should be an optinon - like "stop when pc shutdowned".

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=644_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
