### ISSUE TITLE
Crash when trying to restore from backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#647]
_From [venkovan...@gmail.com](https://code.google.com/u/110154454007529472877/) on June 13, 2012 23:58:37_

What steps will reproduce the problem? 1. Wizard, Restore files from backup
2. Restore from existing; selected the only one backup, I have created (FTP)
3. Backup contains one full backup and one incremental backup; I choose the inceremental one (but crashes even with full)
4. Enter path (existing, empty directory). Summary:
Action: Restore backup
Backup: Arbosoft
Date: 13.6.2012 23:46:05
Folder: c:\temp\xxx
Restore as background job enabled
5. Duplicati is paused; resume? Yes. What is the expected output? What do you see instead? I expect restored files. Windows error shown instead (program stopped working...):
Popis:
  Stopped working

Podpis problému:
  Název události problému:	CLR20r3
  Podpis problému 01:	duplicati.exe
  Podpis problému 02:	1.3.2.1304
  Podpis problému 03:	4fba8ee3
  Podpis problému 04:	mscorlib
  Podpis problému 05:	2.0.0.0
  Podpis problému 06:	4ef6c131
  Podpis problému 07:	de
  Podpis problému 08:	10
  Podpis problému 09:	System.ArgumentException
  Verze operačního systému:	6.1.7601.2.1.0.256.48
  ID národního prostředí:	1029

Přečtěte si prohlášení o zásadách ochrany osobních údajů online: http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0405 Pokud není k dispozici Prohlášení o zásadách ochrany osobních údajů online, přečtěte si toto prohlášení offline:
  C:\Windows\system32\cs-CZ\erofflps.txt What version of Duplicati are you using? On what operating system? Windows 7 64bit, Duplicati 1.3.2 What backend (destination) are you using? FTP Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=647_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
