### ISSUE TITLE
Duplicati WinXP error FTP access : Remote folder doesn't exist

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#651]
_From [bruno.va...@gmail.com](https://code.google.com/u/104314686740465039019/) on June 22, 2012 13:55:14_

What steps will reproduce the problem? 1. Create a new save (Ftp) 2. 3. What is the expected output? What do you see instead? When I attempt to create a new save with ftp, Duplicati tells that the remote folder doesn't exist. (the folder yet really exists)
I have made a try with Duplicati for linux (ubuntu), no connection problem, the forlder is found. What version of Duplicati are you using? On what operating system? 1.3.2.1335 on Win XP What backend (destination) are you using? computer on local network, Linux Ubuntu, ftp server : pure-ftp Please provide any additional information below. log of last backup and windows error attached.

**Attachment:** [FolderNotFound.png log.txt](http://code.google.com/p/duplicati/issues/detail?id=651)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=651_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
