### ISSUE TITLE
Crash on throttle 

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#653]
_From [christia...@gmail.com](https://code.google.com/u/114407587927402177949/) on June 25, 2012 21:41:35_

What steps will reproduce the problem? 1. Start Duplicati
2. Go to throttle set
3. ???

1.3.2.1335.

iMac Lion 10.7.4.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=653_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
