### ISSUE TITLE
Blank "select folder" window in custom "select files to backup" 

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#655]
_From [christia...@gmail.com](https://code.google.com/u/114407587927402177949/) on June 25, 2012 22:47:22_

What steps will reproduce the problem? 1. Wizard Schedule a new backup
2. Step "custom folder list"
3. select files to backup

When I do it again it's OK.

But only 6 folders in the list: a lot too small. 

1.3.2.1335.

iMac Lion 10.7.4.

**Attachment:** [Capture d’écran 2012-06-25 à 22.30.15.png Capture d’écran 2012-06-25 à 22.40.26.png](http://code.google.com/p/duplicati/issues/detail?id=655)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=655_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
