### ISSUE TITLE
Invalid future time causes manifest errors

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#656]
_From [jhiswin](https://code.google.com/u/jhiswin/) on June 28, 2012 14:48:13_

What steps will reproduce the problem? 1.  Set clock to sometime in the future (in my example it was 2 months forward).
2.  Run a backup (should be full)
3.  Set time back to normal
4.  Run another backup (incremental)
5.  Try to view contents of recent incremental backup
6.  "An error occurred: System.Exception: Error: System.IO.InvalidDataException:  The manifest file (recent incremental) indicates that the previous manifest file should be (full backup made with wrong future time) but it was (previous incremental or full backup on normal time)." What is the expected output? What do you see instead? Contents of incremental should show. What version of Duplicati are you using? On what operating system? All versions 1.2.1 and 1.3.2 What backend (destination) are you using? Rackspace CloudFiles Please provide any additional information below. Sometimes the time will be set to a wrong time, such as the user tampering with the clock that just happens to be at the same time as the backup, or the clock drifts for some odd reason.
It would be nice if it didn't just break the backups.  An error is fine, but it makes the backups unusable.  If you don't check and catch it, you will lose a lot of backups.

Another problem, is that it will no longer make full backups once you have a backup with an invalid future time.  All backups become incremental.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=656_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
