### ISSUE TITLE
OutOfMemoryException when Duplicati computes delta of very large files

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#664]
_From [pierre....@gmail.com](https://code.google.com/u/116043127485739138881/) on July 08, 2012 19:38:12_

What steps will reproduce the problem? 1. Do a full backup of a selection containing a very large file (really larger than amount of memory you have)
2. Change slighty the file
3. Do an incremental backup What is the expected output? What do you see instead? Backup fails with this error :

BackupType      : Incremental
TypeReason      : An incremental backup is made because the latest full backup is from 08/07/2012 1:24:37 and the full backup threshold is 1M
BeginTime       : 07/08/2012 17:18:56
EndTime         : 07/08/2012 18:06:44
Duration        : 00:47:47.8281250
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 23
AddedFiles      : 2
AddedFolders    : 0
ExaminedFiles   : 21731
OpenedFiles     : 40
SizeOfModified  : 12052799769
SizeOfAdded     : 5243042
SizeOfExamined  : 31816347732
Unprocessed     : 0
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.2.1354, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.2.1354, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 80183979
BytesDownloaded : 702199
RemoteCalls     : 5
NumberOfErrors  : 1
****************
Failed to process file: *anonymised*\priv1.edb. Error message: Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at Duplicati.Library.SharpRSync.ChecksumFileReader..ctor(Stream input)
   at Duplicati.Library.SharpRSync.Interface.GenerateDelta(Stream signature, Stream input, Stream output)
   at Duplicati.Library.Main.RSync.RSyncDir.AddFileToCompression(Stream fs, String s, Stream signature, ICompression contentfile, ICompression signaturefile, Int64 volumesize, DateTime lastWrite)
   at Duplicati.Library.Main.RSync.RSyncDir.MakeMultiPassDiff(ICompression signaturefile, ICompression contentfile, Int64 volumesize)
**************** What version of Duplicati are you using? On what operating system? v1.3.2.1354 on Windows Server 2003 R2 SP2 32-bits (2GB of RAM) What backend (destination) are you using? SFTP (SSH) Please provide any additional information below. priv1.edb is an Exchange 2003 store (18GB)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=664_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
