### ISSUE TITLE
Diff of signatures

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#666]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on July 18, 2012 13:06:19_

When backing up large files, the signature file takes up some space. If a large file has minor modifications, the entire signature set is uploaded afterwards. This means that the signature files is often larger than the changed data itself.

The signature-diff could be made like a normal diff itself.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=666_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
