### ISSUE TITLE
Duplicati Should detect Mono as installed from MacPorts

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#667]
_From [AaronJac...@gmail.com](https://code.google.com/u/102420898617723937965/) on July 19, 2012 00:25:07_

How are you using Duplicati now? I'm not quite yet. How would you like it to work? Right now Duplicati either can't or won't detect mono as installed by MacPorts, and encourages me to install the direct download package of Mono. Ideally it would detect Mono in the standard Library location OR in the port location and use either. Are there special considerations to this request? Not that I know of. Additional information: Keep up the good work, you sexy beasts.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=667_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
