### ISSUE TITLE
Improve error message when manifest detects errors

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#668]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on July 20, 2012 17:15:40_

Instead of the "Found x files, expected y", Duplicati should report exactly what file was missing (and also report multiple missing files if that is the case.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=668_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
