### ISSUE TITLE
Make it easier to select single files for backups

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#670]
_From [ernst.m...@gmail.com](https://code.google.com/u/114302124077215675693/) on July 28, 2012 00:08:46_

Make it easier to select single files for backups:
With Duplicati it is easy to backup folders, but very difficult to choose single files without using regular expressions to be included in backups. This is the main weak point of Duplicati in my opinion.

I suggest to provide a single-file-selection in an explorer-like window similar to the duplicati-folder-selection without using regular expressions as in Cobian Backup or in Uranium Backup.

I use the portable duplicati version 1.3.2.1354 on Vista 64 bit.
The backend destination is another harddisk.

**Attachment:** [File-Selection in Cobian Backup.png Uranium - Select files OR folders to add to the backup set.png](http://code.google.com/p/duplicati/issues/detail?id=670)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=670_

**Comment by agrajaghh** [comment]
implemented in 2.0
