### ISSUE TITLE
connection failed: execution of request failed: https://docs.google.com............

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#673]
_From [la...@thehaverkamps.net](https://code.google.com/u/101179002141597830090/) on July 30, 2012 08:26:36_

What steps will reproduce the problem? 1. Install Duplicati 
2. Create new backup
3. Select Google
4. enter email, password & collection name
5. click create collection What is the expected output? What do you see instead? I expect Duplicati to create the collection;
Instead I see: connection failed: execution of request failed: https://docs.google.com........... What version of Duplicati are you using? On what operating system? Ver: 1.3.2 on xububtu 12.04 What backend (destination) are you using? Google Please provide any additional information below. I'm using Google Apps

I'm a first time user, so I'm unfamiliar with Duplicati, but I've been using Rdiff-Backup locally for years.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=673_

**Comment by yanickrochon** [comment]
I'm not sure what I need to resolve this. Just got this, too. Some clear steps would be appreciated.
