### ISSUE TITLE
Insufficient timeout interval for WebDAV

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#679]
_From [vaclav.t...@gmail.com](https://code.google.com/u/101904275079360634606/) on August 01, 2012 00:25:57_

I use Duplicati via SSH in LAN, now I would like to switch to WebDAV protocol to use the same backup from the internet remotely. In my target directory I have around 10 GB of backup data from SSH (1000 chunks by 10 MB + 1000 signatures). When I aim Duplicati at this directory via WebDAV and press [Test connection] button, after a long while the following error occurs:

Connection Failed: The remote server returned an error: (500) Internal Server Error.

Whenever I aim at another directory, connection is succesfull. I tried to move those 2000 files to another location; with the empty target directory, the connection was successful again, so a folder name (for instance) is not the the issue.

When I connect to the directory (containing 2000 files) from CyberDuck (www.cyberduck.ch), I access it after ca. 30 seconds of waiting. So I suspect Duplicati being not patient enough; the reason of my trouble might be in some short timeout. What do you think?

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=679_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
