### ISSUE TITLE
Enable ALT-N in LocalizationTool.exe for different keyboard layouts

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#680]
_From [philip.t...@gmail.com](https://code.google.com/u/112476227343105425552/) on August 02, 2012 11:37:37_

When doing GUI translation via LocalizatioTool GUI (if called with LocalizationTool guiupdate <language-COUNTRY>) it's better to be able to write a translation using appropriate keyboard layout (including non-Latin, f.e. Cyrillic), and then press ALT+N without changing keyboard layout to English and back again to enter next translation.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=680_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
