### ISSUE TITLE
Default install doesn't add a firewall exeption to Windows which causes a application hang.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#694]
_From [jasminle...@gmail.com](https://code.google.com/u/101441642211699152142/) on August 08, 2012 18:08:10_

What steps will reproduce the problem? 1. Have an activated Windows firewall
2. Install Duplicati (32 or 64bits) on Windows 2008
3. Create a FTP job
4. Click on "Test connection"

Result: application hangs and needs to be killed manually, no backup jobs are able to run.

Running Duplicati 1.3.2 32bits and 64bits on Windows 2008sp2 64bits.

Workaround: 
Add an exception to the Windows firewall by executable name, backups runs fine afterwards.

Could it be a installation option siilar to the "Run at startup" option?

Thanks,

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=682_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
