### ISSUE TITLE
Failed after uploading XXX volume(s). Error message: Input string was not in a correct format.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#696]
_From [mok...@gmail.com](https://code.google.com/u/101737245556031534275/) on August 16, 2012 18:05:53_

> What steps will reproduce the problem?
1. Start backup and recv message:
Failed after uploading 175 volume(s). Error message: Input string was not in a correct format.

Volume number is different each time I start backup. Can be 15 of 20 of 175. Backing up directories are approximately 12 Gb size.

Full log attached.

> What version of Duplicati are you using? On what operating system?
Tried both latest release (1.3.2) and 1.3 beta - the same thing with that backup profile.

Windows 7 x64

> What backend (destination) are you using?
local folder

**Attachment:** [duplicati-backup-log.txt](http://code.google.com/p/duplicati/issues/detail?id=684)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=684_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
