### ISSUE TITLE
No restore of 'selected' files with semicolon in filename

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#709]
_From [mezzopol...@googlemail.com](https://code.google.com/u/100765909363135121845/) on September 04, 2012 13:50:48_

What steps will reproduce the problem? 1. backup some files, partly with semicolon in filename
   >> result: backup will work properly
2. restore entire backup in a new folder
   >> result: duplicati will restore all files correctly
3. try to restore while selecting every single file
   (mark 'Restore only the items selected below')
   >> result: only files without semicolon in filename will be restored What is the expected output? What do you see instead? - restore of ALL selected files, also with semicolon on filename What version of Duplicati are you using? On what operating system? - duplicati 1.3.2, german
- Windows 7 Professional 64 bit, SP 1 What backend (destination) are you using? - local filesystem Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=697_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
