### ISSUE TITLE
Regular expression filter not working as expected

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#726]
_From [sitemast...@gmail.com](https://code.google.com/u/115487122441843590646/) on October 03, 2012 20:24:36_

What steps will reproduce the problem? Task: Exclude Walter’s Thunderbird profile folder except for its subfolders \Mail\ and \ImapMail\

Regex:  (?!._\Thunderbird\Walter\(Imap)?Mail\)^._$

Test 1: Include filter 

Test strings:
d:\Thunderbird\Walter\key3.db
MATCH (The file is included due to rule)

d:\Thunderbird\Walter\ImapMail\test.msf
NO MATCH (The file is included because no rule matched)

d:\Thunderbird\Walter\Mail\test.msf
NO MATCH (The file is included because no rule matched)

The MATCH/NO MATCH logic is correct but an inclusion rule does not do what we want as we need the exact opposite behavior. So let's try the same regex as an exclude filter. What is the expected output? What do you see instead? Since the MATCH/NO MATCH logic is correct in the inclusion filter I expect the following in a corresponding exclusion filter:

d:\Thunderbird\Walter\key3.db
MATCH (file will thus be excluded)

d:\Thunderbird\Walter\ImapMail\test.msf
NO MATCH (file will thus not be excluded)

d:\Thunderbird\Walter\Mail\test.msf
NO MATCH (file will thus not be excluded)

This is what I get instead:

Test 2: Exclude filter (same test strings)

d:\Thunderbird\Walter\key3.db
The folder d:\Thunderbird\ is excluded due to rule

d:\Thunderbird\Walter\ImapMail\test.msf
The folder d:\Thunderbird\ is excluded due to rule

d:\Thunderbird\Walter\Mail\test.msf
The folder d:\Thunderbird\ is excluded due to rule

Note that all 3 resulting Duplicati messages refer to only the initial part of the folder used in the test string which is strange. What version of Duplicati are you using? On what operating system? 1.3.2 on Win XP Pro SP3 What backend (destination) are you using? File (network share) Please provide any additional information below. The regex used is a negative lookahead assertion. Support for this type varies somewhat between programming languages but I do not think that lack of language support is the issue here because the assertion perfectly works if used as an inclusion filter.

There is probably more important work to do but I thought you may want know. I tried this expression because Duplicati filters work on a "first match only" basis which means that I cannot exlude the entire Thunderbird folder with one rule and then allow 2 of its subfolders with a second rule.

Thanks for making Duplicati available! I use it since Steve Gibson recommended it in the "Security Now" Podcast (episodes 354, 356, 367, www.grc.com/securitynow.htm).

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=714_

**Comment by NiJoao** [comment]
Can someone confirm that Negative Lookaheads are working on exclusion filters in Duplicati v2?
I'm simply not able to make them work.
Example,
excluding folders ending in "top" with -[.*(top)\\]  =Works
excluding folders NOT ending in "top" with -[.*(?!top)\\]  =excludes all subfloders

Regards
