### ISSUE TITLE
Error message using the sftp connection

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#752]
_From [cgorri...@gmail.com](https://code.google.com/u/101932158175909790826/) on October 12, 2012 22:04:47_

Hi, when im trying to use the sftp connection i have the following error message:
I have the last version of Duplicati (1.3.3), and i have the Windows XP SP3.

Error: Unable to get the list of files: Object reference not set to an instance of an object.

Error: System.Exception: No se ha podido conseguir el listado de ficheros: Referencia a objeto no establecida como instancia de un objeto. ---> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Tamir.SharpSsh.jsch.ChannelSftp.remoteAbsolutePath(String path)
   en Tamir.SharpSsh.jsch.ChannelSftp.ls(String path)
   en Duplicati.Library.Backend.SFTPCon.ListFiles(String path)
   en Duplicati.Library.Backend.SSH.ListManaged()
   en Duplicati.Library.Backend.SSH.List()
   en Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   en Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   en Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   en Duplicati.Library.Main.Interface.Backup(String[] sources)
   en Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Tamir.SharpSsh.jsch.ChannelSftp.remoteAbsolutePath(String path)
   en Tamir.SharpSsh.jsch.ChannelSftp.ls(String path)
   en Duplicati.Library.Backend.SFTPCon.ListFiles(String path)
   en Duplicati.Library.Backend.SSH.ListManaged()
   en Duplicati.Library.Backend.SSH.List()
   en Duplicati.Library.Main.BackendWrapper.ListInternal()
Resultado de la limpieza:
Error: System.Exception: No se ha podido conseguir el listado de ficheros: Referencia a objeto no establecida como instancia de un objeto. ---> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Tamir.SharpSsh.jsch.ChannelSftp.remoteAbsolutePath(String path)
   en Tamir.SharpSsh.jsch.ChannelSftp.ls(String path)
   en Duplicati.Library.Backend.SFTPCon.ListFiles(String path)
   en Duplicati.Library.Backend.SSH.ListManaged()
   en Duplicati.Library.Backend.SSH.List()
   en Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   en Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   en Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   en Duplicati.Library.Main.Interface.DeleteAllButNFull()
   en Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Tamir.SharpSsh.jsch.ChannelSftp.remoteAbsolutePath(String path)
   en Tamir.SharpSsh.jsch.ChannelSftp.ls(String path)
   en Duplicati.Library.Backend.SFTPCon.ListFiles(String path)
   en Duplicati.Library.Backend.SSH.ListManaged()
   en Duplicati.Library.Backend.SSH.List()
   en Duplicati.Library.Main.BackendWrapper.ListInternal()c

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=725_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
