### ISSUE TITLE
Folders missing in backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#757]
_From [seed1...@gmail.com](https://code.google.com/u/114774251241391301764/) on October 18, 2012 00:00:51_

What steps will reproduce the problem? 1. Extract 16k_folders.7z.
2. Back it up with usn-policy set to required.
3. Restore the backup in a new folder. What is the expected output? What do you see instead? The restored folder tree is missing 56 folders from the original tree, they have gone missing without any errors from duplicati. What version of Duplicati are you using? On what operating system? Duplicati 1.3.3 x64
Windows 7 Professional 64 bit SP1 What backend (destination) are you using? Local file system. Please provide any additional information below.

**Attachment:** [16k_folders.7z](http://code.google.com/p/duplicati/issues/detail?id=730)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=730_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
