### ISSUE TITLE
Patch for /trunk/Installer/Duplicati.wxs

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#758]
_From [HGFE...@gmail.com](https://code.google.com/u/102110820832598654224/) on October 20, 2012 13:03:19_

Hi, I have tried to build the installation package (v1.2) but when installed I did not see the desktop shortcut actually.
So I suggest that the attribute "Level" of "DuplicatiDesktopShortCutFeature" should be 1 not 0, or the DesktopShortCutFeature will not display in the installation and will not be installed

**Attachment:** [Duplicati.wxs.patch](http://code.google.com/p/duplicati/issues/detail?id=731)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=731_

**Comment by timkoers** [comment]
This issue is still occurring on 1.3.4.
