### ISSUE TITLE
RPM packaging error on Fedora 18

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#759]
_From [twill...@gmail.com](https://code.google.com/u/104993296104588182678/) on October 22, 2012 19:11:07_

Transaction Check Error:
  file / from install of duplicati-1.3.3-1.noarch conflicts with file from package filesystem-3.1-2.fc18.i686
  file /usr/bin from install of duplicati-1.3.3-1.noarch conflicts with file from package filesystem-3.1-2.fc18.i686
  file /usr/lib from install of duplicati-1.3.3-1.noarch conflicts with file from package filesystem-3.1-2.fc18.i686

[root@localhost ~]# rpm -qpl /home/noon/Downloads/Duplicati\ 1.3.3.noarch.rpm/
/usr
/usr/bin
/usr/bin/duplicati
/usr/bin/duplicati-commandline
/usr/lib
/usr/lib/duplicati
...

RPM packages must not include folders from filesystem, please add only new folders.

Additionally it's strange that the RPM file name contains spaces and upper case characters; "Duplicati 1.3.3.noarch.rpm", I recommend renaming the package to "duplicati-1.3.3.noarch.rpm".

Tested on Fedora 18 alpha.
 fedora-release-18-0.8.noarch

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=732_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
