### ISSUE TITLE
problem with junction in source folder

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#760]
_From [ruvim.pi...@gmail.com](https://code.google.com/u/107073572472596978342/) on October 24, 2012 05:38:59_

Hello!
It seems that duplicati doesn't work with junctions(hard-links) as source folder. It just creates empty backup set, or outputs error-message. What steps will reproduce the problem? 1. The c:\temp\test-duplicity\src folder is junction.

2. Duplicati.CommandLine.exe backup --no-encryption c:\temp\test-duplicity\src file:///temp/test-duplicity/trg/

Outputs:
startIndex cannot be larger than length of string.
Parameter name: startIndex

Duplicati Version: 1.3.3, Windows Vista

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=733_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
