### ISSUE TITLE
Backup failes on Windows (first time user) "Error: Failed to retrieve file listing: Timeout..."

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#761]
_From [VomAnder...@spam.la](https://code.google.com/u/112926523393106796236/) on October 24, 2012 10:32:47_

What steps will reproduce the problem? 1. Running the Backup (folder including subfolders, total of ~40MB)
2. Showing the contents when clicked on the failed backup "Show contents..." items, the progress bar is displayed for a specific time and then I get a timeout error
3. Testing the connection in the wizard yields in a timeout error What is the expected output? What do you see instead? The backup does not finish.
- There are no files created in the temporary backup folder
- the process of "Reading incremental data" takes a long time (I don't know if this is meant to be) it then switches to "Removing old backups..." and the progress bar is near completion. Then the error file is displayed "Failed to run backup Error: Failed to retrieve file listing: Timeout für Vorgang überschritten see below for the entire log please) What version of Duplicati are you using? On what operating system? latest as of 10/23/12 (1.3.3) x64 on Windows 7 x64 What backend (destination) are you using? Amazon S3 (EU), default server address in the wizard (?) Please provide any additional information below. - I can connect manually to s3.amazonaws.com and load the AWS Management Console successfully

here is the log of one of my many backup tries:

=============================LOG START===============================
Error: Failed to retrieve file listing: Timeout für Vorgang überschritten

Error: System.Exception: Failed to retrieve file listing: Timeout für Vorgang überschritten ---> System.Net.WebException: Timeout für Vorgang überschritten
   bei Amazon.S3.AmazonS3Client.processRequestError(String actionName, HttpWebRequest request, WebException we, HttpWebResponse errorResponse, String requestAddr, WebHeaderCollection& respHdrs, Type t, Exception& cause)
   bei Amazon.S3.AmazonS3Client.handleHttpWebErrorResponse(S3Request userRequest, WebException we, HttpWebRequest request, HttpWebResponse httpResponse, Exception& cause, HttpStatusCode& statusCode)
   bei Amazon.S3.AmazonS3Client.getResponseCallback[T](IAsyncResult result)
   bei Amazon.S3.AmazonS3Client.endOperation[T](IAsyncResult result)
   bei Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request)
   bei Duplicati.Library.Backend.S3Wrapper.ListBucket(String bucketName, String prefix)
   bei Duplicati.Library.Backend.S3.List()
   bei Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   bei Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   bei Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   bei Duplicati.Library.Main.Interface.Backup(String[] sources)
   bei Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: Timeout für Vorgang überschritten
   bei Amazon.S3.AmazonS3Client.processRequestError(String actionName, HttpWebRequest request, WebException we, HttpWebResponse errorResponse, String requestAddr, WebHeaderCollection& respHdrs, Type t, Exception& cause)
   bei Amazon.S3.AmazonS3Client.handleHttpWebErrorResponse(S3Request userRequest, WebException we, HttpWebRequest request, HttpWebResponse httpResponse, Exception& cause, HttpStatusCode& statusCode)
   bei Amazon.S3.AmazonS3Client.getResponseCallback[T](IAsyncResult result)
   bei Amazon.S3.AmazonS3Client.endOperation[T](IAsyncResult result)
   bei Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request)
   bei Duplicati.Library.Backend.S3Wrapper.ListBucket(String bucketName, String prefix)
   bei Duplicati.Library.Backend.S3.List()
   bei Duplicati.Library.Main.BackendWrapper.ListInternal()
Cleanup output:
Error: System.Exception: Failed to retrieve file listing: Timeout für Vorgang überschritten ---> System.Net.WebException: Timeout für Vorgang überschritten
   bei Amazon.S3.AmazonS3Client.processRequestError(String actionName, HttpWebRequest request, WebException we, HttpWebResponse errorResponse, String requestAddr, WebHeaderCollection& respHdrs, Type t, Exception& cause)
   bei Amazon.S3.AmazonS3Client.handleHttpWebErrorResponse(S3Request userRequest, WebException we, HttpWebRequest request, HttpWebResponse httpResponse, Exception& cause, HttpStatusCode& statusCode)
   bei Amazon.S3.AmazonS3Client.getResponseCallback[T](IAsyncResult result)
   bei Amazon.S3.AmazonS3Client.endOperation[T](IAsyncResult result)
   bei Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request)
   bei Duplicati.Library.Backend.S3Wrapper.ListBucket(String bucketName, String prefix)
   bei Duplicati.Library.Backend.S3.List()
   bei Duplicati.Library.Main.BackendWrapper.ListInternal()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   bei Duplicati.Library.Main.BackendWrapper.List(Boolean filter)
   bei Duplicati.Library.Main.BackendWrapper.GetBackupSets()
   bei Duplicati.Library.Main.Interface.DeleteAllButNFull()
   bei Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: Timeout für Vorgang überschritten
   bei Amazon.S3.AmazonS3Client.processRequestError(String actionName, HttpWebRequest request, WebException we, HttpWebResponse errorResponse, String requestAddr, WebHeaderCollection& respHdrs, Type t, Exception& cause)
   bei Amazon.S3.AmazonS3Client.handleHttpWebErrorResponse(S3Request userRequest, WebException we, HttpWebRequest request, HttpWebResponse httpResponse, Exception& cause, HttpStatusCode& statusCode)
   bei Amazon.S3.AmazonS3Client.getResponseCallback[T](IAsyncResult result)
   bei Amazon.S3.AmazonS3Client.endOperation[T](IAsyncResult result)
   bei Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request)
   bei Duplicati.Library.Backend.S3Wrapper.ListBucket(String bucketName, String prefix)
   bei Duplicati.Library.Backend.S3.List()
   bei Duplicati.Library.Main.BackendWrapper.ListInternal()
=============================LOG END===============================

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=734_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
