### ISSUE TITLE
Receiving Failed to retrieve file listing: Cannot be negative. error

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#768]
_From [csb...@multiservice.com](https://code.google.com/u/108136711343383342007/) on November 01, 2012 16:31:33_

What steps will reproduce the problem? 1. Try to connect to Google Drive account with Google Apps For Your Domain user with 2-Factor authentication from commandline
2. Receive error
3. No profit

This is in ubuntu 12.04
export FTP_USERNAME='MY_USER@MYDOMAIN.COM'
export FTP_PASSWORD='SINGLE_USE_APPLICATION_PASSWORD'

duplicati-commandline  backup /home/me/work googledocs://Laptop What is the expected output? What do you see instead? I would expect it to work, instead I get an error message:
+++++
Failed to retrieve file listing: Cannot be negative.
Parameter name: startIndex
+++++ What version of Duplicati are you using? On what operating system? 1.3.3/LTS12.04 What backend (destination) are you using? Google Drive with 2-Factor Authentication and Google Apps For Your Domain user accounts. Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=741_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
