### ISSUE TITLE
Failed after uploading x volume(s). Error message: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#774]
_From [soski...@gmail.com](https://code.google.com/u/101467867579054477351/) on November 10, 2012 23:43:06_

What steps will reproduce the problem? 1. Define Backup for directory with content >10MB
2. start backup
3. after some volumes (1-14 seen) backup fails, error message in log: "Failed after uploading 7 volume(s). Error message: Exception has been thrown by the target of an invocation." What is the expected output? What do you see instead? Backup works.                Backup fails. What version of Duplicati are you using? On what operating system? Version=1.3.3.1457 on Win XP SP3.
.NETs installed:
1.1
2.0 SP2
3.0 SP2
3.5 SP1 What backend (destination) are you using? Local Disk, unencrypted Please provide any additional information below. Tried multiple times, backup fails every time. First I suspected virus scanner (Avira), but turning it off makes no difference. VSS test using Duplicati.Library.Snapshots.exe passes ok, so that could also be ruled out.

Interesting enough, when I active encryption by setting a password, the error message changes sometimes to "Failed after uploading 2 volume(s). Error message: The process cannot access the file 'F:\tmp\63cfb056-22c7-4f35-9e60-a8d9d145fe09' because it is being used by another process." Seems like encrypting the temporary zipfile fails?

Rebooted, re-installed, tried Version=1.3.2, tried different targets (NAS), different sources. No luck.

Alway reproducible.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=747_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
