### ISSUE TITLE
Folder cannot be created

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#775]
_From [m.rog...@gmail.com](https://code.google.com/u/115094554575909369104/) on November 11, 2012 09:29:46_

What steps will reproduce the problem? 1. a complete Backup 2. 3. What is the expected output? What do you see instead? a full Backup from my D-Drice and my "own Files" (in german:eigene Dateien) What version of Duplicati are you using? On what operating system? I use Duplicati 1.3.3 on Windows XP What backend (destination) are you using? an external hard drive Please provide any additional information below. This is the Message thai i ger from duplicati (in this case in german)

BackupType      : Full
TypeReason      : Ein vollständiges Backup wird durchgeführt, da keine Backup-Ketten im Backup-Ziel gefunden wurden
BeginTime       : 11/10/2012 18:12:07
EndTime         : 11/11/2012 00:47:04
Duration        : 06:34:56.7656250
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 0
AddedFiles      : 42659
AddedFolders    : 11121
ExaminedFiles   : 42659
OpenedFiles     : 42659
SizeOfModified  : 0
SizeOfAdded     : 68073613571
SizeOfExamined  : 68073613571
Unprocessed     : 74652
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.3.1457, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.3.1457, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 68823273499
BytesDownloaded : 0
RemoteCalls     : 18148
NumberOfErrors  : 1
****************
Misserfolg nach dem Hochladen von 6047 Volumes. Fehlermeldung: Fehler Das Verzeichnis oder die Datei kann nicht erstellt werden.
 beim Hochladen der Datei "duplicati-full-signature.20121110T171207Z.vol6048.zip"
****************
NumberOfRetries : 5
RetryOperations : 5

Ergebnis des Aufräumens:

_________________-
Thanks a lot for your help.

Best regards
Manuel

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=748_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
