### ISSUE TITLE
SSH2 backend seems to be broken in 1473

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#776]
_From [philip.t...@gmail.com](https://code.google.com/u/112476227343105425552/) on November 13, 2012 11:26:03_

What steps will reproduce the problem? 1. Open Duplicati.sln
2. Browse to Duplicati.Library.Backend.SSHv2
3. Right click -> Properties What is the expected output? What do you see instead? Warnings prevent one from checking whether the form is localizable (seems to be not). Thus, no changes can be made to the form in order to localize it. Screenshot is attached. What version of Duplicati are you using? On what operating system? v.1473, Windows 7 What backend (destination) are you using? SSH2 Please provide any additional information below.

**Attachment:** [warnings.jpg](http://code.google.com/p/duplicati/issues/detail?id=749)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=749_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
