### ISSUE TITLE
Infinite number of small files created on Synology (ARM Mono)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#777]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on November 13, 2012 12:39:49_

From Groups: https://groups.google.com/forum/#!topic/duplicati/JnO4VFXVxZ4 It seems that something fails when creating split volume files.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=750_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
