### ISSUE TITLE
crashes when coming off pause

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#779]
_From [patr...@e2ftech.com](https://code.google.com/u/100098806143035638501/) on November 17, 2012 21:09:46_

What steps will reproduce the problem? 1. Brand new Windows 7 Ultimate 64 system, everything else works fine, about 20 softwares installed. Fully updated.
2. Install Duplicati
3. Duplacati starts fine, first-use wizard kicks-in
4. The setting-up of a backup works fine
5. Either after 5 minutes, when the backup automatically starts, or when the backup is "unpaused" manually, Duplacati crashes, Windows looks for a solution, of course no solution is found, Duplicati closes and when you run the mouse over the Duplicati icon in the tray, the icon disappears.

What is the expected output?
Backup
What do you see instead?
Duplicati crash What version of Duplicati are you using? On what operating system? Latest and greatest, 1.3.3, I tried with both 32 and 64 bits versions of Duplicati. I also tried several sequences of restart before and after install. What backend (destination) are you using? A seperate internal drive Please provide any additional information below. I have been using for 3-4 years without a hitch. Why does it fail me now? No, no, please don't fail me Duplicati.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=752_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
