### ISSUE TITLE
Incremental Backup doesn't work on encrypted USD Drive

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#780]
_From [B.Siedel...@googlemail.com](https://code.google.com/u/100759737806639110272/) on November 21, 2012 16:45:49_

What steps will reproduce the problem? 1. First I create a new Backup, the first run will result in a full backup. 
The destination of the Backup is on a USB drive (Memory Stick) which is encrypted with the "DevicePro Agent" from "cynapspro" (see following link: http://cynapspro.com/Downloads/2011/cynapspro&#37;20Endpoint&#37;20Data&#37;20Protection&#37;202011&#37;20Step-By-Step&#37;20Anleitung&#37;20DevicePro&#37;20und&#37;20CryptionPro.pdf )
2. Next I start an incremental backup 3. What is the expected output? What do you see instead? The incremental backup is aborted, an in the protocol I find the following information:

##################
Fehler: Fehler Die Datei duplicati-full-manifestB.20121120T145604Z.manifest.aes wurde heruntergeladen und hatte die Größe 93184, aber die Größe sollte eigentlich sein 92624 beim Herunterladen der Datei "D:\Dokumente und Einstellungen\Siedelmann.Burkhard\Lokale Einstellungen\Temp\431c5b0c-f3b3-4b55-8423-fd2d024aef92"

Error: System.Exception: Fehler Die Datei duplicati-full-manifestB.20121120T145604Z.manifest.aes wurde heruntergeladen und hatte die Größe 93184, aber die Größe sollte eigentlich sein 92624 beim Herunterladen der Datei "D:\Dokumente und Einstellungen\xxx\Lokale Einstellungen\Temp\431c5b0c-f3b3-4b55-8423-fd2d024aef92" ---> System.Exception: Die Datei duplicati-full-manifestB.20121120T145604Z.manifest.aes wurde heruntergeladen und hatte die Größe 93184, aber die Größe sollte eigentlich sein 92624
   bei Duplicati.Library.Main.BackendWrapper.GetInternal(BackupEntryBase remote, Manifestfile manifest, String filename, HashEntry hash)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Duplicati.Library.Main.BackendWrapper.ProtectedInvoke(String methodname, Object[] arguments)
   bei Duplicati.Library.Main.Interface.GetManifest(BackendWrapper backend, ManifestEntry entry)
   bei Duplicati.Library.Main.Interface.VerifyBackupChainWithFiles(BackendWrapper backend, ManifestEntry entry)
   bei Duplicati.Library.Main.Interface.Backup(String[] sources)
   bei Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Exception: Die Datei duplicati-full-manifestB.20121120T145604Z.manifest.aes wurde heruntergeladen und hatte die Größe 93184, aber die Größe sollte eigentlich sein 92624
   bei Duplicati.Library.Main.BackendWrapper.GetInternal(BackupEntryBase remote, Manifestfile manifest, String filename, HashEntry hash)
Ergebnis des Aufräumens:

########### What version of Duplicati are you using? On what operating system? Version 1.3.2 What backend (destination) are you using? USB Memory Stick Please provide any additional information below. My question is whether there is any known restriction on performing backups on encrypted USB devices.

Thank you for your kind support
Burkhard

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=753_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
