### ISSUE TITLE
crashes when update starts on vista64bit

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#781]
_From [baddi1...@googlemail.com](https://code.google.com/u/113736505135053878604/) on November 21, 2012 17:56:58_

What steps will reproduce the problem? 1. switching duplicat from pause mode to running mode What is the expected output? What do you see instead? expect: updateing

it crashes down often. Or Vista 64bit crashes it down. acually i able to create a profil then it crashes down. may after view minutes it crashes. do you need more information? which? thanks for your great tool. hopefully i able to use it next time again. What version of Duplicati are you using? On what operating system? 1.3.3 (latest) What backend (destination) are you using? vista 64bit Please provide any additional information below. hmmm. i will if you can. thank for your great product!

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=754_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
