### ISSUE TITLE
Is Google Cloud Storage supported?

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#784]
_From [creative...@gmail.com](https://code.google.com/u/109960626136827242669/) on December 13, 2012 19:33:26_

Is this supported? https://developers.google.com/storage/

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=757_

**Comment by matthiasbier** [comment]
I was able to run a backup to Google Cloud Storage with this CommandLine:

`Duplicati.CommandLine.exe backup "s3s://bucket/path?&auth-username=my_auth_key_id&auth-password=my_auth_key&s3-server-name=storage.googleapis.com" "E:\localpath"`

It starts uploading files to the bucket, but it seems to have a problem getting the files from the bucket. After verifying the remote backup it fails with:

```
Verifying remote backup ...
Remote backup verification completed
  Downloading file (1,20 KB) ...
Operation Get with file duplicati-b9f5082def1cd459293d504b909523877.dblock.zip.aes 
attempt 4 of 5 failed with message: Invalid S3 URI - hostname does not appear to be a 
valid S3 endpoint => Invalid S3 URI - hostname does not appear to be avalid S3 endpoint
```

I verified that the files were successfully stored in the bucket...
