### ISSUE TITLE
Limit how many files are kept open

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#785]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on December 13, 2012 22:18:19_

In the current setup, the RsyncDir instance will extract all filenames from the zip archives before continuing. This will open all the archives, but this gives "Too many files open" if there are more than 1000 volumes. They should be closed again, and then reopened later when they are actually needed.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=758_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
