### ISSUE TITLE
Incoherence between filter preview (tooltip) and result

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#788]
_From [nicolas.hatier](https://code.google.com/u/nicolas.hatier/) on January 05, 2013 18:20:26_

What steps will reproduce the problem? 1. Create a new backup for directory c:\ToBackup. This directory contains these files:
   c:\ToBackup\test.ini
   c:\ToBackup\test.txt
   c:\ToBackup\SubDirectory\test.txt

2. Use these filters:
   Include: c:\ToBackup\*.ini
   Include: c:\ToBackup\SubDirectory\*
   Exclude: c:\ToBackup\*

3. Enter C:\ToBackup\test.ini in the "Test a filename" box

The box tooltip says "C:\ToBackup\test.ini is included due to the rule (c:\\ToBackup\\.*\.ini)|..."

4. Click Test Search Selection.

The "Files to be included" list comes empty. What happens is, when scanning for files, Duplicati tries to first match c:\ToBackup\ with a rule, and the Exclude one matches. So it stops there, even if the first rule would match a file.

Using Duplicati 1.33 on Windows 7 x64

Backend irrelevant to the issue.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=761_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
