### ISSUE TITLE
Duplicati should be able to list backups with a custom prefix from an ad-hoc location

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#790]
_From [nicolas.hatier](https://code.google.com/u/nicolas.hatier/) on January 05, 2013 19:01:29_

I'm considering the case of a disaster recovery, where I don't have the local Duplicati settings anymore, so I want to "restore files directly" using the wizard.

If I use custom prefixes for my backup and point Duplicati to a remote directory containing several backup sets (each with a different prefix), I think Duplicati should be able to list (a tree?) of all backups of each set (prefix).

Currently I may have to use ssh or something else to go look what the prefix was, then use the wizard with Advanced options and set the one custom prefix I want.

As the filename pattern of Duplicati backups is quite unique, it shouldn't be hard to look for this pattern instead of looking for customprefix-*:
/(.*)-full-manifest[\w]*.\d{8}T\d{6}Z.manifest/

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=763_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
