### ISSUE TITLE
Connection Failed: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#797]
_From [ericsson...@gmail.com](https://code.google.com/u/112529058874932162786/) on January 11, 2013 07:12:33_

What steps will reproduce the problem? 1. Set up a new backup.
2. Hit 'Test connection' at 'backup storage options' step. What is the expected output? What do you see instead? I expect to see a message indicating that connection was successfully made. Wilfully using the wrong password will result in an authentication failure, so it's not that. What version of Duplicati are you using? On what operating system? 1.3.3 on os x 10.6.8 What backend (destination) are you using? Google drive Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=770_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
