### ISSUE TITLE
Duplicati.CommandLine exit code is always 0.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#798]
_From [Jarmo.P@gmail.com](https://code.google.com/u/Jarmo.P@gmail.com/) on January 13, 2013 19:35:07_

What steps will reproduce the problem? 1. Run some invalid command for Duplicati.CommandLine or valid command with some settings, which might make the backup to fail or set the backup store path to some remote location and disconnect from the network to let the Duplicati.CommandLine to fail.

For example:
C:\users\Jarmo>"\Program Files\Duplicati\Duplicati.CommandLine.exe" foo
...
C:\users\Jarmo>echo &#37;ERRORLEVEL&#37;
0 What is the expected output? What do you see instead? Expected output would be to have error level 1 and not 0 when any command was not successful. What version of Duplicati are you using? On what operating system? 1.3.3, Win8 64bit What backend (destination) are you using? Does not matter.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=771_

**Comment by mdsmdsmds** [comment]
please, can you provide a link to download fixed version with commandline-correct-returncode?

**Comment by dsptech** [comment]
Hi @kenkendk,
I am sorry to bother you.
For a particular reason, I have to maintain a single installation with the old version of duplicati (1.3.4).
I would like to update the version with the latest patch available (ersion 1.3.4-dev01-x64) but every link I found no longer works.
I would be grateful if you could provide a working link.
Thank you.
Regards.
