### ISSUE TITLE
Auto-configuration

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#801]
_From [jer...@koekkoek.nl](https://code.google.com/u/105512739204770584420/) on January 18, 2013 10:24:30_

What I would like is the possibility to auto-configure Duplicati. in the same way that you can/would autoconfigure mozilla thunderbird or microsoft outlook. You would for example ask the user for a username and a password and Duplicati would query for instance example.com/duplicati.xml and retrieve the configuration settings from that XML file. This way users wouldn't have to worry about configuring it and leave that task up to somebody who knows what he's doing. Of course the XML could also be a ASP.NET application that generates the XML.

Thanks for a great client btw.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=774_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
