### ISSUE TITLE
Incremental backup failed due to missing filelist folder

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#802]
_From [efield...@gmail.com](https://code.google.com/u/100191020531468134433/) on January 18, 2013 18:59:06_

What steps will reproduce the problem? 1. incremental backup daily background operation 2. 3. What is the expected output? What do you see instead? A scheduled incremental daily backup was not performed because a file folder in the file backup list had been moved between the time the full backup was performed and the start of a daily incremental backup. My backup settings call for a full backup every 30 days, and daily incrementals 

I would have expected the missing folder (from the filelist) to have generated a warning but the backup to have continued.  I did add the new folder to the filelist prior to the start of the incremental thus the moved folder should have been backed up as well, had the backup been performed. What version of Duplicati are you using? On what operating system? 1.3.3 on MS Vista What backend (destination) are you using? thumb drive Please provide any additional information below. log report:
Error: The source folder C:\Users\Ed\Documents\Eastmans Online Genealogy Articles Plus Edition pdfs\ does not exist, aborting backup

Error: System.IO.IOException: The source folder C:\Users\Ed\Documents\Eastmans Online Genealogy Articles Plus Edition pdfs\ does not exist, aborting backup
   at Duplicati.Library.Main.Interface.Backup(String[] sources)
   at Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
Cleanup output:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=775_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
