### ISSUE TITLE
Setup Wizard - Click to Remove Entry icon

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#805]
_From [efield...@gmail.com](https://code.google.com/u/100191020531468134433/) on January 19, 2013 16:22:03_

How are you using Duplicati now? perhaps the international red slash symbol on the icon would give users a heads up before they mistakenly hit one or more of the delete entry button.  Once the entry is gone, it can't be restored unless one remembers the text.  alternatively, an 'Are you sure prompt?' would be useful. How would you like it to work? Are there special considerations to this request? Additional information:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=778_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
