### ISSUE TITLE
Crash after running restored settings

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#807]
_From [oskari.p...@gmail.com](https://code.google.com/u/115944795696772541554/) on January 20, 2013 22:31:41_

What steps will reproduce the problem? 1. Restore settings from a previous Duplicati installation (through wizard)
2. Select to run now
3. Crash What is the expected output? What do you see instead? I expect Duplicati to run the backup. Instead it just crashes. What version of Duplicati are you using? On what operating system? Duplicati 1.3.3, Windows 7 Professional N What backend (destination) are you using? SSH backed decrypted network destination (runnin on linux of some sort) Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=780_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
