### ISSUE TITLE
Exit duplicati process when backup is done

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#810]
_From [googlec1...@9ox.net](https://code.google.com/u/104649368153110392137/) on January 28, 2013 18:07:19_

I'm not running duplicati.exe process all the time. I'll start it from Windows scheduler or from larger backup batch for creating off-line backups when it's required. Currently I'm using parameters: --run-backup="Backup" --trayless 

Simply said option to tell proces toProcess should exit when it's done. Currently there's no option for duplicati.exe to do that. I have defined it to be closed when certain time has passed, but as we all know, this can be very dangerous and incorrect method. I would love to be able to add: --exit-when-done parameter.

That's all, when backup job(s) are done, exit.

Why? Because some Windows admins doesn't seem able to understand the commandline version too well.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=783_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
