### ISSUE TITLE
No se ha podido subir el fichero

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#811]
_From [flopezca...@gmail.com](https://code.google.com/u/107530496594724804445/) on January 30, 2013 18:20:02_

Hola a todos. queria saber por qué me da ese mensaje de error cuando quiere subir el fichero a Google Docs. Muchas gracias

Error: No se ha podido subir el fichero "duplicati-full-content.20130130T162821Z.vol1.zip.aes": Anulada la solicitud: La solicitud fue cancelada.

Error: System.Exception: No se ha podido subir el fichero "duplicati-full-content.20130130T162821Z.vol1.zip.aes": Anulada la solicitud: La solicitud fue cancelada. ---> System.Net.WebException: Anulada la solicitud: La solicitud fue cancelada. ---> System.IO.IOException: No se puede cerrar la secuencia hasta que todos los bytes estén escritos.
   en System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   en System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   en System.Net.ConnectStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en Duplicati.Library.Backend.GoogleDocs.Put(String remotename, Stream stream)
   en Duplicati.Library.Main.BackendWrapper.PutInternal(BackupEntryBase remote, String filename)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Duplicati.Library.Main.BackendWrapper.Put(BackupEntryBase remote, String filename, Boolean forcesync)
   en Duplicati.Library.Main.Interface.Backup(String[] sources)
   en Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task)
InnerError: System.Net.WebException: Anulada la solicitud: La solicitud fue cancelada. ---> System.IO.IOException: No se puede cerrar la secuencia hasta que todos los bytes estén escritos.
   en System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   en System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   en System.Net.ConnectStream.Dispose(Boolean disposing)
   en System.IO.Stream.Close()
   en Duplicati.Library.Backend.GoogleDocs.Put(String remotename, Stream stream)
   en Duplicati.Library.Main.BackendWrapper.PutInternal(BackupEntryBase remote, String filename)
InnerError: System.IO.IOException: No se puede cerrar la secuencia hasta que todos los bytes estén escritos.
   en System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
Resultado de la limpieza:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=784_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
