### ISSUE TITLE
GUI: window height to small

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#812]
_From [icandoit...@gmail.com](https://code.google.com/u/108947213741249463445/) on January 31, 2013 06:46:48_

As the attachment, the window's height is too small.
I'm using x64 version on Windows.
Thank you.

**Attachment:** [window-height.png](http://code.google.com/p/duplicati/issues/detail?id=785)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=785_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
