### ISSUE TITLE
Can't start at openSUSE 12.2

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#813]
_From [oleg...@gmail.com](https://code.google.com/u/110731806796731977018/) on February 01, 2013 15:19:31_

I installed duplicati 1.3.3 using rpm, but whet i try to start i get

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'Duplicati.GUI.Program' from assembly 'Duplicati, Version=1.3.3.1457, Culture=neutral, PublicKeyToken=8bfe994a39631a7b'.

The same i get running from pre-compiled binary from the site.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=786_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
