### ISSUE TITLE
Possible mismatch between filter preview and actual backup filtering

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#814]
_From [kenneth@hexad.dk](https://code.google.com/u/kenneth@hexad.dk/) on February 03, 2013 21:31:45_

Reportedly setting an exclude filter for 
c:\*\AppData\Local*\

Will include the files in:
c:\users\al\appdata\locallow\

But the preview will say they are excluded.

Full story: https://groups.google.com/forum/?fromgroups=#!topic/duplicati/FrJYJLPZctE

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=787_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
