### ISSUE TITLE
Translation doesn't fit in layout

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#815]
_From [rosm...@gmail.com](https://code.google.com/u/107558750170190516931/) on February 05, 2013 18:30:25_

Russian translation (and, I guess, not only russian) is too long in some labels.
As on screenshot example, сheckbox overlaps the password textbox.
In other cases text is hidden by other controls (not only case on 2nd screenshot).

version: 1.3.4

**Attachment:** [screenshot-0433_(2013-02-05_23.33.29).png screenshot-0434_(2013-02-06_00.05.07).png](http://code.google.com/p/duplicati/issues/detail?id=788)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=788_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
