### ISSUE TITLE
Pause should also pause current upload

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#819]
_From [rryk...@gmail.com](https://code.google.com/u/115928866317852872320/) on February 17, 2013 16:22:36_

How are you using Duplicati now? Backup my files to a remote SSH server. Sometimes when I need to use Skype or other network-heavy application I pause Duplicati to free network bandwidth. This however doesn't stop uploading current volume, which I have set to 1GB (since my backups are rather large), therefore not freeing the network resources. How would you like it to work? Pause button should not only pause current backup, but also pause current volume upload. If this is not possible on some backends, please let the user choose whether they want to interrupt such an upload or continue uploading until current volume is uploaded completely.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=792_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
