### ISSUE TITLE
Restore Files Directly from file based

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#821]
_From [linuxi...@gmail.com](https://code.google.com/u/104132367338245355691/) on February 20, 2013 15:46:46_

What steps will reproduce the problem? 1.Restore files from backup
2.Restore Files Directly
3.File based
4.then it prompts for the backup storage option (where to store the backup data) bad wording when I am trying a restore
5.Choose the backup I want to restore
6. Restore the items selected below,
  6.a. but above it, it's asking me for a folder where I want to restore. This should not be asked when the option was to restore file directly. We expect to overwrite the current file(s).
7. If I continue, and choose a folder where I restored before it gives me a warning that it's not empty and if I want to continue. I click on Yes.
8. It runs but nothing happens What is the expected output? What do you see instead? I expect to see the file overwritten, but I only see the old file What version of Duplicati are you using? On what operating system? V.1.3.4 on Windows Server and Windows 7 What backend (destination) are you using? File based on my pc. The original backups are file based on a USB drive.

Thank you.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=794_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
