### ISSUE TITLE
Real-Time sync (as opposed to schedule sync)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#822]
_From [l...@lantera.co.il](https://code.google.com/u/110778747923176997356/) on February 27, 2013 20:15:59_

How are you using Duplicati now? How would you like it to work? Are there special considerations to this request? Additional information:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=795_
##

**Comment by kenkendk** [comment]
There is work towards this in 2.0

**Comment by codearoo** [comment]
Hi.. so is it possible now in 2.0? (2.0.2.1_beta_2017-08-01)  Because I don't see anything besides the "Restore" option and don't see any scheduling about it.

**Comment by meersjo** [comment]
I'm wondering about this, too. It's a common enough approach, and other software either does it natively (Crashplan, SpiderOak) or has a separate daemon to handle it (syncthing).

I suspect a separate daemon may be the easiest way of integrating it - a file watcher that logs changes somewhere.

Duplicati will then have two schedules: one to pick up the file watcher changes, which is going to be small changesets and low overhead, so may be fairly often; and a separate one to run occasional full filesystem scans.

The filewatcher schedule could even be something other than simply timebased - you could for example say "run whenever there are x MB of changes, and at least every y minutes".
