### ISSUE TITLE
Error/Status/Message window

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#823]
_From [2020now...@gmail.com](https://code.google.com/u/110491217820530220529/) on February 28, 2013 09:29:02_

How are you using Duplicati now? Log is available after a job finishes How would you like it to work? Would like an option to have status window running with messages displayed in real time. Are there special considerations to this request? Additional information:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=796_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
