### ISSUE TITLE
GUI for Filter regular expression misleading

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#829]
_From [leo.ze...@gmail.com](https://code.google.com/u/100699985538181979113/) on March 08, 2013 11:48:16_

I tried to filter all files which starts with ~$ cause these are temporary files from Microsoft Office.

What I tried very much is something like ~$* resp. ^~\$.* (all files starting with ...) or similar. But now I concluded, that the file names all include the complete path. This surprises me cause the followed dialog lists filenames.

So my proposal is to add somewhere in the text the hint, 'Filtering includes to whole path, e.g. ....' or something else. 

OR add a checkbox to apply the filter for names only, disable Regular-Expression-search and build internally the appropriate string. 

Overall, the issue might be easily fixable with some GUI-cosmetics. As it is now, the context is heavily misleading.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=802_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
