### ISSUE TITLE
Symbolic link creation fail on Windows XP

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#833]
_From [poubelle...@gmail.com](https://code.google.com/u/117529441158569253308/) on March 22, 2013 16:12:07_

What steps will reproduce the problem? 1. backup a folder with junctions inside
2. then restore What is the expected output? What do you see instead? expected : restore junctions or create folders instead.
reality : replace junctions folder by a filename instead of a folder and all data is lost. What version of Duplicati are you using? On what operating system? 1.3.4 windows xp sp3 What backend (destination) are you using? NTFS drive Please provide any additional information below. Duplicati try to create a junction with CreateSymbolicLinkW but fail. Not implanted in Windows XP
(Error message: Unable to find an entry point named 'CreateSymbolicLinkW' in DLL 'kernel32.dll')

I try to recreate the junction or a folder inside still fail. No luck lost everything :(

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=806_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
