### ISSUE TITLE
Wrong status of backup for blocked files and next backup are incremental without this files (but have rights to work on blocked content)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#842]
_From [goo...@kompix.pl](https://code.google.com/u/108000685500140028556/) on April 25, 2013 07:48:19_

What steps will reproduce the problem? 1. Define new job to backup files from outlook 2013 but not running on administrator rights. Outlook 2013 is running in background and blocking pst file.
2. run backup job
3. Close Duplicati
4. Run on administrator rights.
5. run the same backup job without snapshot-policy set What is the expected output? What do you see instead? 1. I should see no warnings for backup jobs, that have blocked files. Icon says that is all right.
2. There is no full backup done because when it was fired pst files was blocked. But output says that all is ok. So the next backup is incremental (?) and any backup doesn't have pst files.

BackupType      : Incremental
TypeReason      : An incremental backup is made because the latest full backup is from 2013-04-25 07:27:10 and the full backup threshold is 1M
BeginTime       : 04/25/2013 07:28:52
EndTime         : 04/25/2013 07:28:52
Duration        : 00:00:00.0791001
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 0
AddedFiles      : 0
AddedFolders    : 0
ExaminedFiles   : 23
OpenedFiles     : 2
SizeOfModified  : 0
SizeOfAdded     : 0
SizeOfExamined  : 1784922112
Unprocessed     : 0
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 0
BytesDownloaded : 632
RemoteCalls     : 2
NumberOfErrors  : 2
****************
Failed to process file: C:\Users\Uzytkownik\AppData\Local\Microsoft\Outlook\wsparcie@kompix.pl.ost. Error message: Proces nie może uzyskać dostępu do pliku, ponieważ inny proces zablokował jego część.

Failed to process file: C:\Users\Uzytkownik\AppData\Local\Microsoft\Outlook\przemek@kompix.pl (1).ost. Error message: Proces nie może uzyskać dostępu do pliku, ponieważ inny proces zablokował jego część.

****************

Cleanup output: What version of Duplicati are you using? On what operating system? 1.3.4 on windows 8 pro What backend (destination) are you using? file to desktop Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=815_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
