### ISSUE TITLE
Insufficient error message on low TEMP space

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#843]
_From [duplicat...@rcpt.at](https://code.google.com/u/114769670600438537285/) on April 26, 2013 11:08:34_

What steps will reproduce the problem? 1. Create TEMP directory with low free space (eg < 1 GB on ramdisk), set environment vars "TEMP" and "TMP" to this dir.
2. In Duplicati set backup block size greater than free space on TEMP
3. Do backup What is the expected output? What do you see instead? The message I expect is in form of "Not enough free space in TEMP directory" with the naming of drive and directory. I only got not enough space on disk):
Error: System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   bei System.IO.FileStream.Flush()
   bei ICSharpCode.SharpZipLib.Zip.Compression.Streams.DeflaterOutputStream.Flush()
   bei Duplicati.Library.Compression.FileArchiveZip.Dispose()
   bei Duplicati.Library.Main.Interface.Backup(String[] sources)
   bei Duplicati.GUI.DuplicatiRunner.ExecuteTask(IDuplicityTask task) What version of Duplicati are you using? On what operating system? 1.3.4 on Win7/64 What backend (destination) are you using? Filesystem Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=816_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
