### ISSUE TITLE
Log level Profiling does not work

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#853]
_From [it.frate...@gmail.com](https://code.google.com/u/116399352867531758550/) on May 21, 2013 04:50:00_

What steps will reproduce the problem? 1. Set up a backup with --log-level=Profiling
2. Run the backup. What is the expected output? What do you see instead? Expected:
Lines beginning with "Profiling:"
Actual:
Information: The operation Backup has started
Information: The operation DeleteAllButNFull has started
Information: The operation DeleteOlderThan has started What version of Duplicati are you using? On what operating system? Dupicati 1.3.4, Windows 7 64-bit What backend (destination) are you using? File based Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=826_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
