### ISSUE TITLE
List included files in package before starting backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#855]
_From [dsl...@gmail.com](https://code.google.com/u/118364151781751428626/) on May 23, 2013 19:40:49_

I'm using Duplicati to create backup packages with several exclusions and would like to check whether my settings are correct and which files will indeed be included/excluded in my package before actually running the process.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=828_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
