### ISSUE TITLE
Built in SFTP Client does not support dual authentication

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#858]
_From [bottswan...@googlemail.com](https://code.google.com/u/117163230676713186653/) on May 26, 2013 23:24:18_

What steps will reproduce the problem? 1. Connect to a SFTP server requiring dual auth (Pubkey & Password)
2. Enter both password and pubkey
3. Test Connection What is the expected output? What do you see instead? Expect to connect successfully, instead receive an authentication error. What version of Duplicati are you using? On what operating system? 1.3.4, Win Server 2008 R2 What backend (destination) are you using? SFTP/SSH. Please provide any additional information below. Works fine when dual auth is disabled. Logs show the library auths with the pubkey then ignores the request for additonal password auth.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=831_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
