### ISSUE TITLE
Prevent deleting old backups if full backups were not completed

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#861]
_From [JanDanie...@gmail.com](https://code.google.com/u/100467400991144034229/) on June 01, 2013 22:51:21_

What is the expected output? What do you see instead? I have incremental backup each day and monthly full, keeping max 1 full backup. But now my full last full backup was deleted by duplicati before new was fully uploaded. (I have cca 100G, so it should be everytime bigger then 100G, but now its only 20G used.) What version of Duplicati are you using? On what operating system? 1.3.3 - win 7 64bit What backend (destination) are you using? SSH Please provide any additional information below. I have turned off computer when creating new (2nd) full backup and two days later I have noticed that my space usage is really low.

In attachment you can see my backup folder usage.

**Attachment:** [2013-06-01 22_50_11-Brick status.png](http://code.google.com/p/duplicati/issues/detail?id=834)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=834_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
