### ISSUE TITLE
Typo in "Select cleanup options" dialog

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#862]
_From [asksh...@gmail.com](https://code.google.com/u/102278725322696915659/) on June 01, 2013 23:06:09_

What steps will reproduce the problem? 1. Get to "Select cleanup options" dialog What is the expected output? What do you see instead? The word "indefinitely" is spelled incorrectly. What version of Duplicati are you using? On what operating system? 1.3.4

**Attachment:** [typo1.JPG](http://code.google.com/p/duplicati/issues/detail?id=835)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=835_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
