### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#863]
_From [miroslav...@gmail.com](https://code.google.com/u/112778307053988927339/) on June 03, 2013 17:57:22_

Hi,

I've started the Czech translation. Could you please grant me access?
File attached.

Regards
Miroslav
------------
Nord Comp Ltd.

**Attachment:** [report.empty.xlsx](http://code.google.com/p/duplicati/issues/detail?id=836)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=836_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
