### ISSUE TITLE
Support for backup to Azure blob storage

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#864]
_From [livers...@gmail.com](https://code.google.com/u/106796061371397712467/) on June 03, 2013 22:48:05_

Adding support for backup to Azure blob storage would be really useful. http://www.windowsazure.com/en-us/manage/services/storage/

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=837_

**Comment by rocifier** [comment]
You just did this :) you can close this issue!

**Comment by kenkendk** [comment]
Yes, this was done by @donlockhart.

**Comment by polarapfel** [comment]
Hey guys.

Great to see you considered Azure as a backup destination. I can't see Azure supported in the current stable build, but I do see a bunch of mentions in the source code about Azure. What's the state of this currently?

thanks,

Tobias W.
