### ISSUE TITLE
SVG icon

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#868]
_From [ismael.olea](https://code.google.com/u/ismael.olea/) on June 18, 2013 13:29:12_

Vectorized with Inkscape from original PNG.

I think it do the work.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=841_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
