### ISSUE TITLE
Cannot skip locked files & file exclusions not working

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#869]
_From [m...@lotbiniere.org](https://code.google.com/u/103145976267702242788/) on June 18, 2013 23:46:39_

What steps will reproduce the problem? 1. This is the command line generated by the Duplicati wizard:
"C:\Program Files\Duplicati\Duplicati.CommandLine.exe" backup --ftp-username=XXX --ftp-password=********** --ftp-passive --passphrase=********** --aes-encryption-dont-allow-fallback=true --open-file-policy=ignore --full-if-older-than=1M --exclude=parent.lock --exclude=control_dir\lock C:\Users\XXX\Documents\;C:\Users\XXX\Pictures\;C:\Users\XXX\Music\;C:\Users\XXX\AppData\Roaming\ ftp://10.11.12.1:21//smbshares/XXX/Duplicati

It is executed by the Duplicati program running on user XXX at logon (a regular non-administrative user account). Open file policy is set to "ignore", since VSS can't be used, and since running programs often obtain an exclusive read/write lock on a file, so why fill up the backup log with failure messages?

I also attempt to exclude some commonly locked files in the backup configuration. What is the expected output? What do you see instead? Extract from log file:
BackupType      : Incremental
TypeReason      : An incremental backup is made because the latest full backup is from 2013-06-16 20:30:27 and the full backup threshold is 1M
BeginTime       : 06/18/2013 16:51:00
EndTime         : 06/18/2013 16:56:36
Duration        : 00:05:36.1572271
DeletedFiles    : 0
DeletedFolders  : 0
ModifiedFiles   : 4
AddedFiles      : 0
AddedFolders    : 0
ExaminedFiles   : 40375
OpenedFiles     : 21
SizeOfModified  : 405968
SizeOfAdded     : 0
SizeOfExamined  : 2383125
Unprocessed     : 0
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.4.1, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.4.1, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 20343
BytesDownloaded : 2719775
RemoteCalls     : 9
NumberOfErrors  : 12
****************
Failed to process file: C:\Users\XXX\AppData\Roaming\Duplicati\control_dir\lock. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Duplicati\control_dir\lock' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Duplicati\Duplicati.sqlite. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Duplicati\Duplicati.sqlite' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\CertPatrol.sqlite. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\CertPatrol.sqlite' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\parent.lock. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\parent.lock' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\places.sqlite. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\places.sqlite' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\cookies.sqlite. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\cookies.sqlite' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\ybookmarks@yahoo.log. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\ybookmarks@yahoo.log' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Microsoft\CLR Security Config\v2.0.50727.312\64bit\security.config.cch.3660.366602. Error message: Access to the path 'C:\Users\XXX\AppData\Roaming\Microsoft\CLR Security Config\v2.0.50727.312\64bit\security.config.cch.3660.366602' is denied.
Failed to process file: C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\webappsstore.sqlite. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\webappsstore.sqlite' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\places.sqlite-wal. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\places.sqlite-wal' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Microsoft\Windows\Cookies\index.dat. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Microsoft\Windows\Cookies\index.dat' because it is being used by another process.
Failed to process file: C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\webappsstore.sqlite-wal. Error message: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\Profiles\d6cd5ppa.XXX 20110209\webappsstore.sqlite-wal' because it is being used by another process.
**************** What version of Duplicati are you using? On what operating system? Duplicate 1.3.4-dev on Windows 7 Ult. x64 (SP1 + all MS current patches) What backend (destination) are you using? FTP (vsftpd running on an OpenWRT router, USB external disk)

Is there something I'm doing wrong here that stops Duplicati from a) ignoring open files and b) excluding files with glob patterns like "control_dir\lock" and "parent.lock" (I tried RX patterns *control_dir\\lock and parent\.lock which did not work either.)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=842_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
