### ISSUE TITLE
Error in shell script

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#873]
_From [smahawad...@gmail.com](https://code.google.com/u/102082433582603344059/) on July 11, 2013 14:05:18_

What steps will reproduce the problem? 1.when i run your mac shell script make-dmg-from-zip.sh it give me "unexpected end of file error" What is the expected output? What do you see instead? i want to create dmg installer for mac osx What version of Duplicati are you using? On what operating system? Duplicati version is:1.3, mac os lion 10.7.5 What backend (destination) are you using? xcode Please provide any additional information below. give me step how to create dmg file for my knowledge purpose

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=846_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
