### ISSUE TITLE
Duplicati hangs trying to open a fifo (aka a named pipe) on Linux

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#876]
_From [mateusz....@gmail.com](https://code.google.com/u/110205435890705673487/) on August 05, 2013 16:39:30_

What steps will reproduce the problem? 1. Create a fifo with mk_fifo on Linux
2. Add the directory containing the fifo to Duplicati
3. Run full backup
4. Duplicati hangs, trying to open() the fifo (confirmed with a strace of the mono subprocess) What is the expected output? What do you see instead? Duplicati checks if the file type is a pipe and acts accordingly (does not try to open it and/or creates the fifo in the backup) What version of Duplicati are you using? On what operating system? 1.3.4 on Debian GNU/Linux Jessie (testing) What backend (destination) are you using? SSH, but this seems to be irrelevant

A workaround is to write something into the pipe - a simple echo "pipe" > path/to/the/pipe makes the backup continue

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=849_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
