### ISSUE TITLE
Windows 8 failure 0x80070020 reading outlook.pst via mklink despite --snapshot-policy=required and admin rights

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#878]
_From [sebastia...@googlemail.com](https://code.google.com/u/114408990318135178582/) on August 19, 2013 21:15:22_

What steps will reproduce the problem?
1. Move user account to D: and mklink /J C:\Users\Username D:\Users\Username
2. Run Outlook, run Duplicati as Admin on Windows 8
3. Try to back up outlook.pst under C:\Users\Username path

What is the expected output? What do you see instead?
Expect no warning. Getting instead:
Fehler beim Verarbeiten der Datei: C:\Users\Username\Documents\Outlook Email\outlook.pst, Fehlermeldung: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (Ausnahme von HRESULT: 0x80070020)
System.IO.FileLoadException: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (Ausnahme von HRESULT: 0x80070020)
   bei Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   bei Alphaleonis.Win32.Filesystem.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   bei Duplicati.Library.Snapshots.SystemIOWindows.FileOpenRead(String path)
   bei Duplicati.Library.Snapshots.WindowsSnapshot.OpenRead(String file)
   bei Duplicati.Library.Main.RSync.RSyncDir.MakeMultiPassDiff(ICompression signaturefile, ICompression contentfile, Int64 volumesize)

What version of Duplicati are you using? On what operating system?
Duplicati 1.3.4.0 on Windows 8

What backend (destination) are you using?
SFTP

Please provide any additional information below.
Backup works fine when denoting D:\Users\Username in backup paths. So, seemingly Duplicati creates a VSS for C:, missing that due to the mklink some (in my case all) files to backup rather reside on D:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=851_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
