### ISSUE TITLE
SFTP conection will time out on proftpd servers

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#879]
_From [left...@gmail.com](https://code.google.com/u/110888767622631992526/) on August 23, 2013 20:11:02_

What steps will reproduce the problem? 1. Setup a proftpd server to run a sftp server on port 22
2. Connect to the server What is the expected output? What do you see instead? The connection to establish.

I get the following exception
Renci.SshNet.Common.SshOperationTimeoutException occurred
  HResult=-2146233088
  Message=Session operation has timed out
  Source=Renci.SshNet
  StackTrace:
       at Renci.SshNet.Session.WaitHandle(WaitHandle waitHandle)
       at Renci.SshNet.Session.Connect()
       at Renci.SshNet.BaseClient.Connect()
       at Duplicati.Library.Backend.SSHv2.CreateConnection(Boolean changeDir) in e:\Code\duplicati-71abe91c3b60\Duplicati\Library\Backend\SSHv2\SSHv2Backend.cs:line 185
  InnerException: What version of Duplicati are you using? On what operating system? Commit 71abe91c3b60 from the source. What backend (destination) are you using? SFTP Please provide any additional information below. By downloading version 2013.4.7.0 of SSH.NET, signing the dll and replacing it in the thirdparty\SSH.NET folder the connection estabilishes fine.

Whatever issue is causing this it is fixed in the current release of SSH.NET.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=852_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
