### ISSUE TITLE
[windows] crash when starting from menu and service is installed and running

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#882]
_From [waffel.c...@googlemail.com](https://code.google.com/u/111546037115378300217/) on August 26, 2013 09:24:09_

What steps will reproduce the problem? 1. Install Duplicati as a service as described at http://www.duplicati.com/howtos/howto-backup-opened-files-e-g-outlook-pst 2. start windows ... duplicati now make the job as setup fine
3. try to start duplicati from windows start menu (or any other) ... take a look with process explorer (or similar) ... you will see dr-watson and the duplicati background task and fresh started job dies. Now you can start duplicati again from start menu and you get the expected ui. What is the expected output? What do you see instead? - I expect, that the UI starts/come to from or the task icon appears from where I can do the known operations. What version of Duplicati are you using? On what operating system? - Duplicati version: 1.3.4
- Windows version: Windows 7 ultimate x64 What backend (destination) are you using? - local file storage (on internal device) Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=855_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
