### ISSUE TITLE
Can't connect to OwnCloud Behind a proxy

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#884]
_From [linusj...@googlemail.com](https://code.google.com/u/104514642746572654070/) on August 28, 2013 18:52:26_

What steps will reproduce the problem? 1. Configure the WebDAV connection through the duplicati wizard 2. 3. What is the expected output? What do you see instead? Connection Failed: The operation has timed out What version of Duplicati are you using? On what operating system? 1.3.4 on Wiondows Server 2008 R2 What backend (destination) are you using? OwnCloud 5.0.10 Please provide any additional information below. The proxy is a smoothwall proxy, managed by the council. We can connect to the owncloud pages through various browsers on the same machine. We can also connect to the same OwnCloud server using the Duplicati client on machines that aren't behind the proxy.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=857_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
