### ISSUE TITLE
Option to suppress first-time wizard on subsequent startups if you don't have backups

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#885]
_From [Stealth...@gmail.com](https://code.google.com/u/113413651082251230655/) on August 29, 2013 01:45:00_

How are you using Duplicati now? To back up shared folders on several Windows and Linux office file sharing / web servers. It is also installed on several employee machines, some of whom also have backups, and others who only use it to restore files when needed.

If you have no backups, the first-time wizard will appear every single time Duplicati starts up, until you make a backup.

Currently in order to suppress the wizard automatically showing on every login, we have had to set up dummy backups that never automatically execute. How would you like it to work? It would be helpful to have an option to turn off the wizard's automatic appearance without having to create a dummy backup.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=858_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
