### ISSUE TITLE
Offer way to list sizes of file deltas in an incremental backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#887]
_From [a.n.o.n....@gmail.com](https://code.google.com/u/110221309123202676454/) on September 14, 2013 19:33:34_

What steps will reproduce the problem? 1. Create an incremental backup.

Expected: There is a way for me to determine what files added how many bytes to that incremental backup.

Actual: There is no way to list the size differentials of files stored in a given incremental backup. What version of Duplicati are you using? On what operating system? 1.3.4 Windows 7 Enterprise 64-bit What backend (destination) are you using? file based Please provide any additional information below. The "list-actual-signature-files" command line option lists files in a backup, but not how many bytes they added to the backup. I'm seeing large incremental backups and it's difficult to figure out what files or file moves are adding considerably to the size of the backup.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=860_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
