### ISSUE TITLE
SSH-Connection not working when using build-in sftp program on linux

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#888]
_From [alexande...@googlemail.com](https://code.google.com/u/110840794063121466256/) on September 15, 2013 14:21:57_

What steps will reproduce the problem? 1. Create a new backup job using the SSH-Connection target
2. Enter all necessary credentials (Server, path, username)
2. Check the "Use installed sftp program[...]" box. 
3. Press "Test connection What is the expected output? What do you see instead? Given the fact that I have key authentication enabled and ssh login from my laptop (Ubuntu 12.10 machine) to the server (Debian Squeeze) works flawlessly without entering passwords I would expect the "Test connection" to return some kind of success message. 

Instead it gives me the following error msg after a short period: 

Connection failed: Timeout occurred while connecting. log: 
*O* spawn sftp myusername@192.168.0.1 -P 22 
*O* usage: sftp [-1246Cpqrv] [-B buffer_size] [-b batchfile] [-c cipher]
*O*          [-D sftp_server_path] [-F ssh_config] [-i identity_file] [-l limit]
*O*          [-o ssh_option] [-P port] [-R num_requests] [-S program]
*O*          [-s subsystem | sftp_server] host
*O*       sftp [user@]host[:file ...]
*O*       sftp [user@]host[:dir[/]]
*O*       sftp -b batchfile [user@]host

Possible solution to the Problem: 
It seems like Duplicati is running with wine under Linux and the build-in linux sftp commandline tool expects it's parameters in the (more usual) "optional-stuff first, then mandatory parameters" order instead of the other way around, which might be the way an expected windows commandline tool works. You might add a detection for the Linux environment to give the arguments in the correct order. Or just do a little trial-and-error on which way around works and remember it for the next run. What version of Duplicati are you using? On what operating system? - Duplicati 1.3.4 from the *.deb install package. 
- Ubuntu 12.10 "Quantal Quetzal" i386 What backend (destination) are you using? - Target server is a Debian Squeeze amd64 machine Please provide any additional information below. -Using the build-in SSH client is no option for me because it doesn't support my ssh key. ("Unsupported encryption format for OpenSSH key, must be 3des-cbc")

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=861_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
