### ISSUE TITLE
Failed to authenticate using the given credentials

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#892]
_From [Wu.si...@gmail.com](https://code.google.com/u/113718086563866894539/) on September 25, 2013 13:15:32_

What steps will reproduce the problem? 1.Setup a new backup
2.Chooses "File based"
3.Enters correct user name and passwd What is the expected output? What do you see instead? "Failed to authenticate using the given credentials" What version of Duplicati are you using? On what operating system? Windows Server 2008 R2 Duplicati 1.3.4(x64) What backend (destination) are you using? File Please provide any additional information below. I debugged the source codes,and I discovered that the return value of the function "WNetAddConnection2" is 1219 ERROR_SESSION_CREDENTIAL_CONFLICT.The explain on MSDN is "Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.".
So I used the function "WNetCancelConnection2" to force close the existing network connection,then authenticate success.
Did I do wrong?

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=865_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
