### ISSUE TITLE
Why does duplicati not have a choice for full raw and recursive direct backups?

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#893]
_From [Andrew.J...@gmail.com](https://code.google.com/u/117258634708636146442/) on September 27, 2013 00:13:46_

Please consider using the Duplicat group for questions regarding Duplicati: http://groups.google.com/group/duplicati Otherwise, enter question here: I have been seeking a software that utilizes the usn's in the ntfs log to perform backups on very large structured directories.  Differential backups are very inefficient when you have millions files to check against in hundreds of directories. This would be one circumstance where such a feature would be beneficial. Why does duplicati not have a choice for full raw and recursive direct backups to a remote directory?

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=866_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.

afaik USN is implemented in 2.0
