### ISSUE TITLE
Backup fails with message "Error: Cannot find central directory"

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#898]
_From [quartz...@gmail.com](https://code.google.com/u/100330071242423698069/) on September 29, 2013 04:41:30_

What steps will reproduce the problem? 1. Create a backup that backs up folders from one external hard drive to another (in my case, I was using two external Seagate harddrives)
2. Set the backup to run every day at 6:00AM
Note that both external hard drives are plugged in, powered, and accessible by Windows Explorer.

Expected Output
I would expect the backup to run without errors.

Current Output
The backup will run correctly for approximately ten or so days, and then fail every time it tries. The cross will come up, and the log of the failed backup is as follows:
------------------------
Error: Cannot find central directory

Error: ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at Duplicati.Library.Compression.FileArchiveZip..ctor(String file, Dictionary`2 options)
Cleanup output:
------------------------ What version of Duplicati are you using? On what operating system? Duplicati 1.3.4
Windows 8 32bit What backend (destination) are you using? File Based Please provide any additional information below. The faulty backup(f_other) is one of two backups I run. The other one (f_personal) behaves very similarly, the major difference being which folders each one backs up. f_personal is working fine.
Usually, I will delete the backup f_other and set it up again - it will then work for several days, and then stop working.

I hope this isn't just a Ten-T error, thanks in advance.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=871_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
