### ISSUE TITLE
Local application data not backed up when application settings is chosen in wizard

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#899]
_From [kakos...@gmail.com](https://code.google.com/u/102069476005370821367/) on September 29, 2013 18:31:46_

What steps will reproduce the problem? 1. Create a new backup
2. Choose "Include application settings" in wizard
3. Run backup
4. View contents of the backup.

What is the expected output? 
All application data (AppData\Local, AppData\LocalLow and AppData\Roaming) are backed up.

What do you see instead?
Only AppData\Roaming is backed up. What version of Duplicati are you using? On what operating system? Duplicati 1.3.4 on Windows Vista. What backend (destination) are you using? SSH

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=872_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
