### ISSUE TITLE
Error 530 accessing FTP

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#904]
_From [forti.fr...@gmail.com](https://code.google.com/u/106055065900119025567/) on October 02, 2013 10:40:34_

Duplicati 1.3.4
XP Home SP3

Backup on FTP server

I give host (IP), username and password (working fine with filezilla and cobian) but I get 530 error

I can only say that username contains a @ and password contains special charatcters

Any idea? 

FF

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=877_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
