### ISSUE TITLE
Small typo in Italian translation

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#905]
_From [sher...@gmail.com](https://code.google.com/u/103695009273864041021/) on October 05, 2013 17:59:16_

In the status window Italian translation of "Duplicati Options" has a small typo

Oipzioni Duplicati

but instead it should be Opzioni Duplicati

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=878_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
