### ISSUE TITLE
Mac OS 10.5

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#907]
_From [subcamou...@gmail.com](https://code.google.com/u/100852643957587967928/) on October 11, 2013 10:18:21_

Hi,

I try to install Duplicati v1.3.4 on Mac OS 10.5. After installing it prompt out need the MonoFrame work 2.6 or later. But on the site i try to install the stable version 2.1.

After installing Mono retry to launch Duplicati and its seem that its not working.

Regards 
Sub What version of Duplicati are you using? On what operating system? Duplicati v1.3.4
Mac OS 10.5

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=880_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
