### ISSUE TITLE
Failed to process path message (Duplicati 2.0) during backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#908]
_From [w.v.a...@gmail.com](https://code.google.com/u/104198121188704403070/) on October 13, 2013 11:18:10_

What steps will reproduce the problem? 1. Initial backup Ok
2. Next Backup produces this error message: 
Failed to process path: <path> => Object reference not set to an instance of an object
3. Finally Backup finishes ok What is the expected output? What do you see instead? Expected out : no error message What version of Duplicati are you using? On what operating system? 2.0 What backend (destination) are you using? NAS EMC ix4-300D (RAID 1) 2x SATA Disk 2 TB Please provide any additional information below.

**Attachment:** [cmd-output-duplicati20.png](http://code.google.com/p/duplicati/issues/detail?id=881)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=881_

**Comment by agrajaghh** [comment]
closing since there hasn't been an answer since 3 years ;)
