### ISSUE TITLE
Create folder does not work with owncloud

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#911]
_From [livio.ma...@gmail.com](https://code.google.com/u/111386583258591241520/) on October 19, 2013 08:34:35_

What steps will reproduce the problem? 1. Run duplicati setup wizard GUI
2. On options page, complete the backend server info completely.
3. Click 'test Connection' says connection is okay, but says "The folder does not exist, do you want to create it?"
4. Answer Yes
5. The GUI freezes and eventually times out with error "Connection failed: The request times out"
6. The folder is not created on the OwnCloud backend. What is the expected output? What do you see instead? The folder should be created at the OwnCloud backend and the setup wizard should continue to the following steps. What version of Duplicati are you using? On what operating system? Duplicati 1.3.4 on Ubuntu 13.04 64-bit What backend (destination) are you using? OwnCloud 5.0.8 Please provide any additional information below. If I use an existing folder, or no folder at all, the 'Test Connection' button succeeds.
Also, the 'Create Folder' button fails in the same way.
The Path I use is remote.php/webdav/ 
as recommended by owncloud.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=884_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
