### ISSUE TITLE
Network Shared Folder Not Available When I choose custom folder and browse for it.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#912]
_From [cicorfri...@gmail.com](https://code.google.com/u/102766750313421187020/) on October 24, 2013 08:53:41_

What steps will reproduce the problem? 1. First please fix this bug 2. 3. What is the expected output? What do you see instead? I think what i want to see is when i browse for network shared folder it must be there. What do i see when i click on Network there is "absolutely nothing" What version of Duplicati are you using? On what operating system? Duplicati 1.3.2 and OS Ubuntu 13.10 What backend (destination) are you using? Local my pc Hard disk drive Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=885_

**Comment by agrajaghh** [comment]
@rissala please open a new issue if you still have this problem with a new version
