### ISSUE TITLE
"Reading file list, please wait" indefinietely when trying to restore.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#914]
_From [gaz...@gmail.com](https://code.google.com/u/113683785179603026830/) on October 27, 2013 21:11:45_

What steps will reproduce the problem? 1. Go to the wizard. Hit restore.
2. Select "restore only the items selected below" 3. What is the expected output? What do you see instead? I presume Duplicati will show a list of files available for restoring. What version of Duplicati are you using? On what operating system? 1.3.4 - Ubuntu x64 13.04 What backend (destination) are you using? Amazon S3. Please provide any additional information below.

**Attachment:** [Screenshot from 2013-10-27 17:09:43.png](http://code.google.com/p/duplicati/issues/detail?id=887)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=887_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
