### ISSUE TITLE
skydrive delete-all-but-n-full issue

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#916]
_From [mana.mam...@gmail.com](https://code.google.com/u/107506735935548676926/) on October 30, 2013 12:41:29_

Duplicati.CommandLine.exe delete-all-but-n-full 1 sky drive://_dup --passport-username=*******@outlook.com --passport-password=*******

Great response, ok.

Deleting backup at 10/22/2013 20:42:19
Deleting backup at 10/15/2013 21:30:14
Deleting backup at 10/11/2013 14:15:31
Deleting backup at 10/08/2013 15:00:33
Deleting backup at 10/07/2013 14:52:26
Deleting backup at 10/07/2013 12:44:52
Files are not deleted, use the --force command to actually remove files

But with force switch:

Duplicati.CommandLine.exe delete-all-but-n-full 1 sky drive://_dup --passport-username=*******@outlook.com --passport-password=******* --force

Value cannot be null.
Parameter name: passphrase

XP SP3 / Duplicati 1.3.4 / skydrive

Thanks for your support
BR,
M

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=889_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
