### ISSUE TITLE
Error: Failed to retrieve file listing: There are multiple files named ...

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#919]
_From [ypm...@gmail.com](https://code.google.com/u/115842934718405181459/) on November 01, 2013 01:27:04_

What steps will reproduce the problem? 1. just do scheduled normal backup 2. 3. What is the expected output? What do you see instead? Output would be normal backup done but there is error with two file with the same name, although I don't do anything, just let the normal backup does it works.. and when login to google drive, suddenly there is two file mentioned with same name What version of Duplicati are you using? On what operating system? 1.3.4 What backend (destination) are you using? Google Drive Please provide any additional information below. the complete log is in the attachment,
the setting for the backup would be;

incremental then full after this period : 1 month

never keep more than this many full backup : 1

never keep backup older than this : 1 month

**Attachment:** [error_log.txt](http://code.google.com/p/duplicati/issues/detail?id=892)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=892_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
