### ISSUE TITLE
Error getting response stream (ReadDone4): ServerProtocolViolation

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#921]
_From [christ...@chwe.at](https://code.google.com/u/114059438829472389465/) on November 01, 2013 20:45:51_

What steps will reproduce the problem? 1. First full backup to SkyDrive works without problems: 

mono Duplicati.CommandLine.exe /volume1/public/source/ skydrive://Backups/Duplicati --ftp-username=XXX --ftp-password=XXX --tempdir=/volume1/backups/temp --debug-output --log-level=Profiling

2. When I create a second backup (with the same cmd-line statement) or when I try a restore, it fails. command for restore:

mono Duplicati.CommandLine.exe restore skydrive://Backups/Duplicati /volume1/public/restore --ftp-username=XXX --ftp-password=XXX --tempdir=/volume1/backups/temp What is the expected output? What do you see instead? Error: An error occurred while running the backup, no files were uploaded: Failed to download file "/volume1/backups/temp/5b1b7d8b-3f5c-48a2-9382-fab26ea473aa": Error getting response stream (ReadDone4): ServerProtocolViolation What version of Duplicati are you using? On what operating system? - Duplicati 1.3.4 
- on Synology DiskStation DS411+II (DSM 4.3-3776) 
- with "Mono"-Package (Mono JIT compiler version 2.11.1 ((no/426188e Wed Aug 29 11:05:42 CST 2012) What backend (destination) are you using? SkyDrive Please provide any additional information below. I'm working with Duplicati for the first time, so I'm in my initial setup. I'm testing it with some dummy folders which have a content of ~ 10 MB.

During execution of the second backup (and also during restore), multiple files are created and deleted in the temp directory. I refreshed the folder multiple times and it seemed like they always had 0 bytes. But since they had content on initial upload, I guess the permissions are ok.

when I delete the files from SkyDrive and run the backup again, it sucessfully creates a full backup again.

Your help is appreciated! best regards,
christian

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=894_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
