### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#922]
_From [pim...@gmail.com](https://code.google.com/u/115082703034550798068/) on November 03, 2013 15:54:53_

Hi,

Finished the Dutch translation for Duplicati, unfortunately I was unable to do it 'the hard way' so here is the Excel file instead. 

How will you proceed now? Eg when can we expect a new version with Dutch included?

Kind Rgds, Pim

**Attachment:** [report.nl-NL.xlsx](http://code.google.com/p/duplicati/issues/detail?id=895)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=895_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
