### ISSUE TITLE
Scheduled tasks don't run

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#924]
_From [geoffake...@gmail.com](https://code.google.com/u/103891745445004512283/) on November 09, 2013 01:07:16_

What steps will reproduce the problem? 1. Create a scheduled task to run Duplicati at startup.
2. Choose to run with administrator privileges.
3. Restart computer. What is the expected output? What do you see instead? Scheduled tasks should run.  They don't. What version of Duplicati are you using? On what operating system? 1.3.4 on Win8 x64. What backend (destination) are you using? File based. Please provide any additional information below. Scheduled tasks don't run when Duplicati is started with the Task Scheduler at boot.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=897_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
