### ISSUE TITLE
Duplicati ask passphrase twice when backing up to an existing backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#925]
_From [kakos...@gmail.com](https://code.google.com/u/102069476005370821367/) on November 09, 2013 14:40:02_

What steps will reproduce the problem? 1.Create a new backup without giving encryption passphrase on commandline.
2.Rerun the same backup What is the expected output? What do you see instead? On the first run Duplicati asks for passphrase and asks user to confirm the passphrase. 

On the second run Duplicati shows again the confirm prompt even if it can check the existing backup to see if passphrase is correct. What version of Duplicati are you using? On what operating system? 2.0_2013-09-13exp on Ubuntu 13.10. What backend (destination) are you using? File Please provide any additional information below. For example "mono Duplicati.Commandline.exe test <TARGET>" asks passphrase only once.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=898_

**Comment by agrajaghh** [comment]
fixed I think
