### ISSUE TITLE
Find not listing all available backups when given no filename.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#926]
_From [kakos...@gmail.com](https://code.google.com/u/102069476005370821367/) on November 09, 2013 15:08:34_

What steps will reproduce the problem? 1. mono Duplicati.CommandLine.exe backup ~/DuplicatiTest/
2. mono Duplicati.CommandLine.exe find ~/DuplicatiTest/

What is the expected output? 
Help states: 
"If no <filename> is specified, a list of all available backups is shown."

What do you see instead?

Argument is out of range.
Parameter name: index What version of Duplicati are you using? On what operating system? 2.0_2013-09-13exp on Ubuntu 13.10. What backend (destination) are you using? File Please provide any additional information below. Unless the help text is using some convention I'm not familiar with, 
"Usage: find <storage-URL> ["<filename>"] [<options>]"
indicates that only mandatory argument is storage URL.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=899_

**Comment by agrajaghh** [comment]
fixed
