### ISSUE TITLE
Incorrect time stamps in status window.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#933]
_From [kakos...@gmail.com](https://code.google.com/u/102069476005370821367/) on November 14, 2013 23:38:56_

What steps will reproduce the problem? 1. Update to 1.3.4-dev05 from 1.3.4 released version.
2. View status window What is the expected output? What do you see instead? Old backups are shown with their start times. Instead they are all shown with timestamps 1.1.0001 00:00. See the attached screenshot. What version of Duplicati are you using? On what operating system? 1.3.4-dev05 on Windows Vista x86 What backend (destination) are you using? SSH Please provide any additional information below. Here is the log (minus some warnings about open files) for the first backup. 

BackupType      : Incremental
TypeReason      : An incremental backup is made because the latest full backup is from 4.11.2013 14:14:47 and the full backup threshold is 1M
BeginTime       : 11/14/2013 23:01:33
EndTime         : 11/14/2013 23:03:06
Duration        : 00:01:32.4600000
DeletedFiles    : 0
DeletedFolders  : 2
ModifiedFiles   : 48
AddedFiles      : 17
AddedFolders    : 2
ExaminedFiles   : 2748
OpenedFiles     : 85
SizeOfModified  : 27888785
SizeOfAdded     : 16826586
SizeOfExamined  : 66354342
Unprocessed     : 0
TooLargeFiles   : 0
FilesWithError  : 0
Executable      : Duplicati, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
Library         : Duplicati.Library.Main, Version=1.3.4.0, Culture=neutral, PublicKeyToken=8bfe994a39631a7b
OperationName   : Backup
BytesUploaded   : 9129463
BytesDownloaded : 679
RemoteCalls     : 5
NumberOfErrors  : 3
****************
Failed to process file: 
SNIP
****************

Cleanup output:

**Attachment:** [Issue906-Status1.png](http://code.google.com/p/duplicati/issues/detail?id=906)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=906_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
