### ISSUE TITLE
1.3.4-dev05: SSH backend missing

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#934]
_From [kakos...@gmail.com](https://code.google.com/u/102069476005370821367/) on November 14, 2013 23:53:50_

What steps will reproduce the problem? 1. Install Duplicati 1.3.4.-dev05
2. Try to do something with backups requiring SSH backend. 

What is the expected output? 
SSH backend is available in all backup operations.

What do you see instead?
When creating a new backup SSH is not offered as a destination.

When trying to restore an old backup that uses SSH backend, restore ends in error "Error: Missing backend" and when trying to run an old backup Duplicati crashes. What version of Duplicati are you using? On what operating system? What backend (destination) are you using? SSH with external program (psft) Please provide any additional information below. See attached screenshots.

**Attachment:** [Issue907-Wizard-New.png Issue907-Wizard-Restore-Error.png](http://code.google.com/p/duplicati/issues/detail?id=907)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=907_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
