### ISSUE TITLE
Connection error: Configuration System Fails to initalise

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#935]
_From [toxsickc...@gmail.com](https://code.google.com/u/116641654208541286615/) on November 15, 2013 01:47:27_

What steps will reproduce the problem? 1. Running Windows XP
2. trying to create a new backup
3. running the backup What is the expected output? What do you see instead? an error about connection.. when in settings.. test connection yields same errors What version of Duplicati are you using? On what operating system? 1.3.4 & latest dev5 What backend (destination) are you using? Google drive Please provide any additional information below. I tried with and without encryption 
I tried single folders
try with default settings

I cannot make it backup..

thanks
Shaun

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=908_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
