### ISSUE TITLE
Open File dialog for exclusion filter rejects locked files

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#940]
_From [bruck.mi...@gmail.com](https://code.google.com/u/117038943164870204556/) on November 30, 2013 14:17:39_

1. have a file locked by another process
2. try to add said file to the exclusion filter using the open file dialog

The dialog refuses because the file is locked. The accessibility of a file that is being added to an exclusion filter should not be checked by the dialog.

Duplicati v. 1.3.4 on win7 64bit, backup to local folder

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=913_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
