### ISSUE TITLE
Failed to locate the Zip Header

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#941]
_From [cory.thi...@commerx.com](https://code.google.com/u/110807062130627749227/) on December 02, 2013 18:50:07_

What steps will reproduce the problem? 1. Using Duplicati 2 beta
2. Nightly Executed Backup to remote ssh server
3. When compacting remote backup it fails with Fatal error => Failed to locate the Zip Header What is the expected output? What do you see instead? When successful and not compacting remote backup:
  0 files need to be examined (0 bytes)
  Uploading file (8.41 MB) ...
  Uploading file (13.42 KB) ...
  Uploading file (11.83 MB) ...
Checking remote backup ...
  Listing remote folder ...
Verifying remote backup ...
  Downloading file (11.62 MB) ...
  Downloading file (87.60 KB) ...
  Downloading file (49.90 MB) ...
Remote backup verification completed
DeletedFiles: 48
DeletedFolders: 0
ModifiedFiles: 2
ExaminedFiles: 143729
OpenedFiles: 52
AddedFiles: 47
SizeOfModifiedFiles: 907264
SizeOfAddedFiles: 10182738
SizeOfExaminedFiles: 121591414420
SizeOfOpenedFiles: 11090002
NotProcessedFiles: 0
AddedFolders: 0
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
VerboseOutput: True
VerboseErrors: False
Messages: []
Warnings: []
Errors: []
Backup completed successfully!

Output of failed run:

Compacting remote backup ...
Found 0 fully deletable volume(s)
Found 27 small volumes(s) with a total size of 87.19 MB
Found 0 volume(s) with a total of 0.00&#37; wasted space (0 bytes of 94.92 GB)
Compacting because there are 87.19 MB in small volumes and the volume size is 50.00 MB
  Downloading file (2.87 MB) ...
  Downloading file (8.80 MB) ...
  Downloading file (unknown) ...
  Downloading file (3.76 MB) ...
Fatal error => Failed to locate the Zip Header What version of Duplicati are you using? On what operating system? Duplicati 2.0_2013-09-13exp on Windows Server 2012 What backend (destination) are you using? Linux via ssh Please provide any additional information below.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=914_

**Comment by agrajaghh** [comment]
closing as old / probably fixed (there would have been more reports otherwise)
