### ISSUE TITLE
Display warning in UI if full backup will be created instead of incremental backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#942]
_From [a.n.o.n....@gmail.com](https://code.google.com/u/110221309123202676454/) on December 02, 2013 22:11:53_

How are you using Duplicati now? - I have custom settings that determine when incremental and when full backups will be made (a full backup every "6M"). I kick off a backup manually every month or so before going to bed. In the morning it's usually done, taking up 7G or so. How would you like it to work? - I'd like for it to post a warning right when I kick off the backup if, based upon my settings, it will be creating a full backup instead of an incremental one. The warning should be visible in the UI, e.g. in the "Pending Backups" field. Are there special considerations to this request? - I'm getting up in the morning to find my backup hasn't completed and it filling my hard drive, and I don't understand why (it's because it's a full backup). I have a laptop, and need to make space for a full backup, e.g. by offloading the old one to an external drive, before I start a new full backup. Additional information: - See also issue #830 , which I created as a result of not knowing a full backup was underway.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=915_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
