### ISSUE TITLE
Update log file prior to end of backup

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#943]
_From [a.n.o.n....@gmail.com](https://code.google.com/u/110221309123202676454/) on December 02, 2013 22:17:51_

How are you using Duplicati now? - I have a custom setting for "--log-file". During a backup that was taking longer than expected ( issue 860 ), I wanted to read the log to see what was going on. But the file specified in --log-file hadn't been updated with information on the current backup. It wasn't updated until the backup completed (by me cancelling it). How would you like it to work? - I'd like the log file to be updated as the log progresses. Are there special considerations to this request? Additional information:

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=916_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
