### ISSUE TITLE
Error: Failed to retrieve file listing: There are multiple files named  "duplicati-full-content.20131215T214328Z.vol150.zip.aes" in the folder named "xxxxxxxx", please rename the files manually

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#955]
_From [dps...@gmail.com](https://code.google.com/u/103601495114000618087/) on December 19, 2013 14:29:18_

What steps will reproduce the problem? 1. Any scheduled backup attempt fails with the above error message
2. Tried deleting the oldest "duplicati-full-signature-*-aes.zip" file, no change. 3. What is the expected output? What do you see instead? Normal backup expected, but none created. Error log attached. What version of Duplicati are you using? On what operating system? 1.3.4 What backend (destination) are you using? Google Drive Please provide any additional information below.

**Attachment:** [duplicati-error.txt](http://code.google.com/p/duplicati/issues/detail?id=928)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=928_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
