### ISSUE TITLE
Can't ssh on alternative port in Windows

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#957]
_From [rfw...@gmail.com](https://code.google.com/u/104636668958382961079/) on December 20, 2013 00:57:38_

What steps will reproduce the problem? 1.I've gotten a very odd issue that's cropped up.  I'm running duplicati fine on my Ubuntu 13 laptop (1.3.4), thought I'd take it to the next step and start migrating backups from my current method to duplicati on a Windows Server 2012 box.

I'm backing up to the same box (or destination server) on my Ubuntu laptop as the Windows box but I get an error when trying to connect on Windows.  I tested another server (connecting to CentOS from Windows 2012 duplicati 1.3.4) and it works but it doesn't seem to want to connect to FreeNAS's SSH daemon version 7.2...I think it is.  It's their last version for 7.x.

So duplicati on Linux connects to FreeNAS over SSH correctly but Windows Server 2012 does not and seems to be having a hard time.  FreeNAS does log it as a Sharp SSH client using protocol 2 but then duplicati pukes.

See attached error and the FreeNAS server log.

Can anyone shed light on this issue or some light on it?

Setup is:

Windows 2012 Server Standard x64
duplicati 1.3.4 x64 (also tried x32)
Server:  fqdn for my backup server, can indeed ping and see it
Path:  Confirmed path: /.../...format not \...\...windows format
Username:  Confirmed this is correct
Password:  Created another account in fact with a simpler pw for testing - checks out and is correct
Port:  10003 <-- Using an alternate port (but does hit FreeNAS server according to log - see pic)

Error when connecting is a long string but it starts out like:

Connection Failed:  Session.connect:
System.Security.Cryptography.CryptographicException: Bad Data.

...and a bunch more, see pic. What is the expected output? What do you see instead? I expect to see it connect like it does on Linux! What version of Duplicati are you using? On what operating system? 1.3.4 What backend (destination) are you using? FreeNAS ssh, openbsd openssh-server Please provide any additional information below. My GoogleGroup post with pics of error output: https://groups.google.com/forum/#!topic/duplicati/BK21zF6Y3ww

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=930_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
