### ISSUE TITLE
SSH RSA keyfile not working on windows (32bit)

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#960]
_From [mikmor...@gmail.com](https://code.google.com/u/100425644283587953999/) on December 29, 2013 20:42:28_

What steps will reproduce the problem? 1. generate keyfile with ssh-keygen, password 'mypassword'
2. copy keyfile to 32bit windows client
3. Run C:\Program Files\Duplicati>Duplicati.CommandLine.exe --ssh-keyfile="C:\mdmserver_backup3.key" --debug-to-console --ftp-username=myuser --debug-output --no-encryption --ftp-password=mypassword C:\ ssh://host/blahblah What is the expected output? What do you see instead? System.Security.Cryptography.CryptographicException: Bad Data.

   at System.Security.Cryptography.CryptographicException.ThrowCryptogaphicExcep
tion(Int32 hr)
   at System.Security.Cryptography.Utils._ImportKey(SafeProvHandle hCSP, Int32 k
eyNumber, CspProviderFlags flags, Object cspObject, SafeKeyHandle& hKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSA
Parameters parameters)
   at Tamir.SharpSsh.jsch.jce.SignatureRSA.sign()
   at Tamir.SharpSsh.jsch.IdentityFile.getSignature_rsa(Session session, Byte[]
data) What version of Duplicati are you using? On what operating system? Version 1.3.4, Windows XP Pro 2002, SP3 What backend (destination) are you using? Linux OpenSSH daemon. Please provide any additional information below. This may be related - http://stackoverflow.com/questions/9659898/bad-data-cryptographicexception I've used this method before on a 64bit Win7 machine, without problems. Using the GUI, when attempting the test connection option, I get "Auth failed." I've tried this with and without password protection on the keyfile. I've also attempted to use a keyfile converted using PuttyGen (export as OpenSSH) to test any compatibility issues.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=933_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
