### ISSUE TITLE
GUI/frontend missing on Vista client

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#961]
_From [leif.rom...@gmail.com](https://code.google.com/u/104965878505237137601/) on January 07, 2014 15:23:37_

Have successfully run Duplicati on two PCs against a NAS for months. One client is running W7, the other Vista. The Vista client now suddenly has no GUI, but keeps backing up to the FTP server.  Can I uninstall and reinstall Duplicati without losing access to the backups on the server?

Using Duplicati 1.3.4 on Vista, against a QNAP NAS running Linux.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=934_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
