### ISSUE TITLE
Duplicati 2.0 on Synology NAS

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#972]
_From [Daniel.D...@gmail.com](https://code.google.com/u/100705901785824166424/) on January 28, 2014 23:02:20_

What steps will reproduce the problem? 1. Trying to create a backup on a Synology NAS to a webdav target What is the expected output? What do you see instead? I Excpect a successful backup, but receive the following output:

---

Backup started at 01/28/2014 21:57:08
Failed to process path:  => System.TypeInitializationException: An exception was thrown by the type initializer for Mono.Unix.Native.Syscall ---> System.DllNotFoundException: libMonoPosixHelper.so
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall:_L_ctermid ()
  at Mono.Unix.Native.Syscall..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at UnixSupport.File..cctor () [0x00000] in <filename unknown>:0 
Checking remote backup ...
  Listing remote folder ...
Scanning local files ...
  0 files need to be examined (0 bytes)
Failed to process path:  => System.TypeInitializationException: An exception was thrown by the type initializer for Mono.Unix.Native.Syscall ---> System.DllNotFoundException: libMonoPosixHelper.so
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall:_L_ctermid ()
  at Mono.Unix.Native.Syscall..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at UnixSupport.File..cctor () [0x00000] in <filename unknown>:0 
Compacting remote backup ...
Compacting not required
Checking remote backup ...
  Listing remote folder ...
  Duration of backup: 00:00:31
  Files added: 0
  Files deleted: 0
  Files changed: 0
  Data uploaded: 0 bytes
  Data downloaded: 0 bytes
## Backup completed successfully!

The following command has been used with mono enabled on the NAS:

mono /usr/local/dup/Duplicati.CommandLine.exe backup --auth-username=username --auth-password=password --use-ssl webdav://webdav.hidrive.strato.com/path /volume1/Storage/Files --passphrase=xyz What version of Duplicati are you using? On what operating system? Duplicati 2.0 on a Synology DS212 NAS (Marvell Kirkwood) What backend (destination) are you using? WebDAV target (Strato HiDrive) Please provide any additional information below. After performing successful backups/restores with a similar Duplicati 1.3.4 command line on the NAS I wanted to check the experimental version and receive the above error.

**Attachment:** [debug.txt](http://code.google.com/p/duplicati/issues/detail?id=945)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=945_
##

**Comment by hcjehg** [comment]
In my installation it is found in 

/volume1/@appstore/Mono/usr/etc/mono/config

it contains the line

<dllmap dll="MonoPosixHelper" target="/usr/lib/libMonoPosixHelper.so" os="!windows" />

Changing it to 

<dllmap dll="MonoPosixHelper" target="/volume1/@appstore/Mono/usr/lib/libMonoPosixHelper.so" os="!windows" />

seems to fix the problem

**Comment by kenkendk** [comment]
I think this is fixed
