### ISSUE TITLE
LVM snapshot does not mounts correctly

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#975]
_From [lornade...@mail.ru](https://code.google.com/u/116871215092930282679/) on January 31, 2014 07:13:28_

What steps will reproduce the problem? 1.Start backup with --snapshot-policy=required on LVM volume. What is the expected output? What do you see instead? mount -o ro throws a mount error (something like "Logical device duplicati-xxxx not found") What version of Duplicati are you using? On what operating system? Duplicati 1.3.4. Linux Mint 16 Petra x64. What backend (destination) are you using? Does not matter

lvm2 2.02.98-6ubuntu1
This can be fixed for me by changing this line in create-lvm-snapshot.sh:
mount -o ro "$LV_SNAPSHOT" "$TMPDIR"
to
mount -o ro /dev/"$LV_GROUP/$LV_SNAPSHOT" "$TMPDIR"

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=948_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
