### ISSUE TITLE
SSH Key Error 

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#979]
_From [imi...@gmail.com](https://code.google.com/u/101313097058429111752/) on February 15, 2014 17:59:58_

What steps will reproduce the problem? 1. Create OpenSSH keypair with PuttyGen and upload to server
2. Configure "passwordless" login (ID + Key only) on server
3. Setup Duplicati backup to SSH server using SSH key and no password. What is the expected output? What do you see instead? Expected: Connection and backup
What I see: When I point the Duplicati UI to the local location of the Private SSH key, I receive the following error:

"File must have the OpenSSH private key header,eg:----BEGIN PRIVATE RSA KEY---" What version of Duplicati are you using? On what operating system? Duplicati 1.3.4 (64bit) on Windows 7 What backend (destination) are you using? DigitalOcean VPS server using SSH Please provide any additional information below. The existing Private key works perfectly using SSH from Putty and WinSCP. Not sure why it fails in Duplicati.

The top of the Puttygen created key reads as follows: "ssh-rsa", while the Duplicati SSH engine seems to require a different format based on the error message.

Thanks.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=952_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
