### ISSUE TITLE
Duplicati does not run from cmd

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#980]
_From [niklas.l...@googlemail.com](https://code.google.com/u/112814281586418210792/) on February 17, 2014 01:08:35_

What steps will reproduce the problem? I'm using these two commands below in a bat file. 

"C:\Program Files\Duplicati\Duplicati.CommandLine.exe" backup --ftp-username=ftpuser --ftp-password=*** --passphrase=*** --aes-encryption-dont-allow-fallback=true --log-level=Error --log-file="D:\Eigene Dokumente\Backup\Duplicati\log.txt" "D:\Backups\;D:\Virtual Machines\;D:\Eigene Dokumente\\" ftp://fritz.nas:21/WD-Elements1078-01\Duplicati "C:\Program Files\Duplicati\Duplicati.CommandLine.exe" delete-all-but-n 6 --ftp-username=ftpuser --ftp-password=*** --aes-encryption-dont-allow-fallback=true --log-level=Error --log-file="D:\Eigene Dokumente\Backup\Duplicati\log.txt" ftp://fritz.nas:21/WD-Elements1078-01\Duplicati What is the expected output? What do you see instead? The backup fails with this message in the log file:

Error: An error occurred while running the backup, no files were uploaded: Fehler Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. beim Herunterladen der Datei "C:\Users\Marovelo\AppData\Local\Temp\51f61fed-5c9a-4c0b-9dbe-972b32562f2d\patch-25.zip"

Translation of the german part: Error The connection with the remote server cannot be established. while downloading the file What version of Duplicati are you using? On what operating system? Duplicati 1.3.4 (64bit) on Windows 7 (64bit) What backend (destination) are you using? A Western Digital Elements 1078 connected to a FritzBox 7360 SL Please provide any additional information below. If I run the same job from the Duplicati-GUI it works perfectly fine.
I checked the passwords multiple times.
I don't really understand why Duplicati would like to download a file from C:\. This directory doesn't exist on my target drive.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=953_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
