### ISSUE TITLE
System Exception at Restore

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#986]
_From [schou...@googlemail.com](https://code.google.com/u/115150894819331686010/) on March 07, 2014 07:34:29_

What steps will reproduce the problem? 1.Restore files from backup (no encryption)
2.Restore only the items selected below

What is the expected output? 
A list to select the files.

What do you see instead?
Error: System.Exception: Ein Problem bei der Sortierreihenfolge des Volumens wurde festgestellt bei Duplicati.Library.Main.Interface.FindPateches(BackendWraper bacend.List´1 entries, String tempfolder, Boolean allowHashFial, CommunicationStatistics stat) What version of Duplicati are you using? On what operating system? Duplicati 1.3.4 x64
Windows 7 x64 What backend (destination) are you using? Backup to external USB3 HDD. Please provide any additional information below. The Backup is a new fullbackup with no incrementals. Backup size is about 50 GB.

**Attachment:** [Image 1.png](http://code.google.com/p/duplicati/issues/detail?id=959)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=959_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
