### ISSUE TITLE
Minor errors in german translation

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#988]
_From [cschw...@gmail.com](https://code.google.com/u/103601766013613001819/) on March 08, 2014 10:13:23_

What steps will reproduce the problem? - Translation for lbLoading.Text contained a typo
- Translation for IncrementalBecauseLastFullIsFrom was wrong (incremental was translated as full - copy&paste error?) What is the expected output? What do you see instead? Corrected Translation What version of Duplicati are you using? On what operating system? 1.3.4 What backend (destination) are you using? SMB Please provide any additional information below.

**Attachment:** [report.de-DE.xlsx](http://code.google.com/p/duplicati/issues/detail?id=961)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=961_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
