### ISSUE TITLE
Excel Files Unusable after Duplicati if Left Open

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#990]
_From [keric.h...@gmail.com](https://code.google.com/u/107325288068019754191/) on March 21, 2014 13:28:02_

What steps will reproduce the problem? 1. Open up a Spreadsheet from Share Drive
2. Make your Backup of Shared folder happen 1x daily
3. Leave Spreadsheet open overnight
4. Next day its being used by someone / readonly (duplicati does not release the FILE LOCK) What is the expected output? What do you see instead? What version of Duplicati are you using? On what operating system? Duplicati 1.3.4 - Windows 7 64bit What backend (destination) are you using? Windows Server 2008 R2 Please provide any additional information below. In a Enterprise environment or small business people dont close spreadsheet everyday they leave them open, but after Duplicati runs on that folder the spreadsheet is locked / readonly / used -- all you can do then is save as... and delete the original spreadsheet.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=963_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
