### ISSUE TITLE
(404) Not Found with webdav instead of creating folder

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#992]
_From [brian...@gmail.com](https://code.google.com/u/106835133001800971312/) on March 27, 2014 16:57:16_

I am using Duplicati2.0_2013-09-13exp with webdav backup backend.  The remote folder is not auto created, and duplicati reports The remote server returned an error: (404) Not Found.  I was expecting duplicati to create the remote folder as needed

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=965_

**Comment by hippich** [comment]
having same issue. i have commanline version running and it automatically detects new folders and tries to backup these, but currently it requires manual intervention in order to create remote folder during first time backup. Is there a way to tell it always try to auto create remote folders?
