### ISSUE TITLE
Duplicati hangs and will not restart.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#995]
_From [frank.la...@xerox.com](https://code.google.com/u/109159435098194260584/) on April 08, 2014 21:59:44_

What is the expected output? What do you see instead? A backup.  Duplicati ran for about 3 hours then hung.  Plenty of files on the target backup drive.  Will not restart. What version of Duplicati are you using? On what operating system? 1.3.4 What backend (destination) are you using? network drive. Please provide any additional information below. Where is the log file?
The docs say to use the UI, but duplicati is hung and will not restart.
Sheesh!
Deleting the lock file does not help.
I am running Win7, 64 bit.

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=968_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
