### ISSUE TITLE
Unknown reason for fail.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/duplicati#997]
_From [ian.trun...@gmail.com](https://code.google.com/u/114010330717297170373/) on April 09, 2014 11:22:22_

What steps will reproduce the problem? 1.Run backup job. (no password is set to encrypt the files)
2.Starts to run and then stats completed (Green tick) but log shows failed. (see attached log file) 3. What is the expected output? What do you see instead? Backup completed What version of Duplicati are you using? On what operating system? 1.3.4 What backend (destination) are you using? Traget is SSH SFTP site. Please provide any additional information below.

**Attachment:** [Duplicati fail unknown reason.txt](http://code.google.com/p/duplicati/issues/detail?id=970)

_Original issue: http://code.google.com/p/duplicati/issues/detail?id=970_

**Comment by agrajaghh** [comment]
Duplicati 1.3.x is not maintained anymore. We are currently working to make Duplicati 2.0 stable. Duplicati 2.0 can be downloaded from https://github.com/duplicati/duplicati/releases.
